### ISSUE TITLE
[CDCSDK] Attaching CDC to a table having pg_lsn type column results in crashing of CDC Java Client

### ISSUE THREAD

**Issue by vaibhav-yb** [yugabyte/yugabyte-db#10070]
Steps to reproduce:
- `create table test (a int primary key, b pg_lsn);`
- Run the java client now

Client crashes with the following exception-

```
Exception in thread "main" java.lang.IllegalArgumentException: The provided data type doesn't map to know any known one: yb.DataType
	at org.yb.Type.getTypeForDataType(Type.java:186)
	at org.yb.client.ProtobufHelper.pbToSchema(ProtobufHelper.java:126)
	at org.yb.client.GetTableSchemaRequest.deserialize(GetTableSchemaRequest.java:99)
	at org.yb.client.TabletClient.decode(TabletClient.java:384)
	at org.yb.client.TabletClient.decode(TabletClient.java:98)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:500)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.yb.client.TabletClient.handleUpstream(TabletClient.java:608)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.handler.timeout.ReadTimeoutHandler.messageReceived(ReadTimeoutHandler.java:184)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
	at org.yb.client.AsyncYBClient$TabletClientPipeline.sendUpstream(AsyncYBClient.java:2299)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:318)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by vaibhav-yb** [comment]
This has been fixed now. Now if you would insert a pg_lsn type value, it would be streamed correctly across CDC.

**Steps to reproduce the behaviour:**
  1. Execute the following queries:
        ```sql
        CREATE TABLE test (a INT, b pg_lsn);
        INSERT INTO test VALUES (1, '7/A25801C8');
        ```
  2. Run the java client `java -jar java/yb-cdc/target/yb-cdc-connector.jar -config_file <path-to-config.properties>`
      This is the config.properties I am using:
      ```properties
      admin.operation.timeout.ms=30000
      operation.timeout.ms=30000
      num.io.threads=1
      socket.read.timeout.ms=30000
      table.name=test
      stream.id=
      schema.name=yugabyte
      format=proto
      master.addrs=127.0.0.1\:7100
      tablets.list=
      schema.nama=yugabyte
      ```
      **Note that since the record is proto, you would get the record as a snapshot of the table.**
  
The streamed record (snapshot) for the equivalent insert is:
```
row_message {
  new_tuple {
    column_name: "a"
    column_type: 23
    datum_int32: 1
  }
  new_tuple {
    column_name: "b"
    column_type: 3220
    datum_string: "7/A25801C8"
  }
  old_tuple {
  }
  old_tuple {
  }
}
```
