### ISSUE TITLE
[Driver] YCQL 4.x driver routes all requests incorrectly to local-dc in multi-region/multi-dc topology

### ISSUE THREAD

**Issue by nchandrappa** [yugabyte/yugabyte-db#10117]
In YCQL 4.x Java driver, all the request are being only routed to local DC specified as part of the CQLSession.

## Setup:

- Rf-3 - 3 region topology
- Us-east-1, us-east-2, us-west-1
- Us-west-1 local datacenter, peers (us-east-1, us-east-2)
- `yb-sample-apps` was used to test the behaviour of 4.x and 3.x driver
- consistency level set to `QUORUM / YB_STRONG`

## 4.x Driver

- In 4.x driver, local datacenter is mandatory for creating CqlSession 
- `with_local_dc` value set to the local datacenter (us-west-1), all the traffic is routed only to the nodes in that datacenter. Leader tablets are not pinned to this region.
- 2/3rd remote reads/writes with Multi-dc setup than local reads/writes

## 3.x driver

- In 3.x, local datacenter is not mandatory
- Traffic is being routed to all the three regions, expected behaviour 
- No remote reads/writes
- No remote reads/write, with_local_dc value set in the cluster

**Comment by aravind-nallan-yb** [comment]
I'm seeing this in multiple discussions that we seem to think that the 4.x driver requires local DC to be set for creating CqlSession. I dont think this is true at all. CqlSession and SessionBuilder dont require with DC to be specified.

When we have our own LB policy like the PartitionAwarePolicy, its upto this class to either require local DC or not. Its parent DefaultLoadBalancingPolicy decided to mandate it in discoverLocalDc(). It's parent BasicLoadBalancingPolicy's documentation explicitly states that implementations can decide if local DC is required or not.

**Comment by randersenYB** [comment]
FYI, if you don't specify a "builder.withLocalDatacenter" when using an "builder.addContactPoint" with the Java 4.x driver you will receive the below runtime exception.  Note that the "PartitionAwarePolicy" is in play.

`
Exception in thread "main" java.lang.IllegalStateException: Since you provided explicit contact points, the local DC must be explicitly set (see basic.load-balancing-policy.local-datacenter in the config, or set it programmatically with SessionBuilder.withLocalDatacenter). Current contact points are: Node(endPoint=/172.17.0.9:9042, hostId=768aadcf-7f2f-07ab-d742-26572c58a729, hashCode=6e4d69f6)=datacenter1. Current DCs in this cluster are: datacenter1
	at com.datastax.oss.driver.internal.core.loadbalancing.helper.MandatoryLocalDcHelper.discoverLocalDc(MandatoryLocalDcHelper.java:91)
	at com.datastax.oss.driver.internal.core.loadbalancing.DefaultLoadBalancingPolicy.discoverLocalDc(DefaultLoadBalancingPolicy.java:118)
	at com.datastax.oss.driver.internal.core.loadbalancing.BasicLoadBalancingPolicy.init(BasicLoadBalancingPolicy.java:126)
	at com.datastax.oss.driver.internal.core.loadbalancing.DefaultLoadBalancingPolicy.init(DefaultLoadBalancingPolicy.java:109)
	at com.yugabyte.oss.driver.internal.core.loadbalancing.PartitionAwarePolicy.init(PartitionAwarePolicy.java:67)
	at com.datastax.oss.driver.internal.core.metadata.LoadBalancingPolicyWrapper.init(LoadBalancingPolicyWrapper.java:121)
	at com.datastax.oss.driver.internal.core.session.DefaultSession$SingleThreaded.afterInitialSchemaRefresh(DefaultSession.java:444)
	at com.datastax.oss.driver.internal.core.session.DefaultSession$SingleThreaded.lambda$afterInitialNodeListRefresh$5(DefaultSession.java:434)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2143)
	at com.datastax.oss.driver.internal.core.metadata.MetadataManager$SingleThreaded.lambda$startSchemaRequest$1(MetadataManager.java:465)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:831)
`

**Comment by nchandrappa** [comment]
[4.6.0-yb-10](https://github.com/yugabyte/cassandra-java-driver/releases/tag/4.6.0-yb-10) released to fix the issue.
