### ISSUE TITLE
YSQL: Starting a new cluster with an old YSQL snapshot fails in debug build

### ISSUE THREAD

**Issue by frozenspider** [yugabyte/yugabyte-db#10116]
In **debug** build, using YSQL initdb snapshot from 2.0.9.0 (https://github.com/yugabyte/yugabyte-db-ysql-catalog-snapshots/releases/tag/v2.0.9.0) leads to a yb-master startup error:
```
./bin/yb-ctl create --rf=1 --master_flags="initial_sys_catalog_snapshot_path=/opt/yb-build/ysql-sys-catalog-snapshots/initial_sys_catalog_snapshot_2.0.9.0"
```
results in
```
F20210927 16:32:18 ../../src/yb/common/ql_value.h:123] Check failed: pb.BOOST_PP_CAT(has_, BOOST_PP_CAT(binary, _value))() Value: 
    @        0x11f06bee3  google::LogDestination::LogToSinks()
    @        0x11f06b14c  google::LogMessage::SendToLog()
    @        0x11f06ba45  google::LogMessage::Flush()
    @        0x11f07089f  google::LogMessageFatal::~LogMessageFatal()
    @        0x11f06ca59  google::LogMessageFatal::~LogMessageFatal()
    @        0x10cd12fbc  yb::QLValue::binary_value()
    @        0x10cd0cd09  yb::QLValue::binary_value()
    @        0x10cd0c77a  yb::master::EnumerateSysCatalog()
    @        0x10cd0b75d  yb::master::EnumerateSysCatalog()
    @        0x10cca50da  yb::master::SysCatalogTable::Visit()
    @        0x10c84b74e  yb::master::CatalogManager::Load<>()
    @        0x10c84a920  yb::master::CatalogManager::RunLoaders()
    @        0x10ce86abd  yb::master::enterprise::CatalogManager::RunLoaders()
    @        0x10c845163  yb::master::CatalogManager::VisitSysCatalog()
    @        0x10c842cc3  yb::master::CatalogManager::LoadSysCatalogDataTask()
...
```

Full logs: [master-logs.zip](https://github.com/yugabyte/yugabyte-db/files/7235853/master-logs.zip)

In **release** build, doing so works though.

This comes into play when implementing tests as a part of #4856

**Comment by frozenspider** [comment]
When using old `yugabyte_data` instead, this leads to the following crash:
```
F20210929 12:28:02 ../../src/yb/master/master_main.cc:138] Internal error (yb/common/ql_expr.cc:691): Unable to initialize catalog manager: Failed to initialize sys tables async: Failed log replay. Reason: Column unexpectedly not found in cache
    @        0x11780bee3  google::LogDestination::LogToSinks()
    @        0x11780b14c  google::LogMessage::SendToLog()
    @        0x11780ba45  google::LogMessage::Flush()
    @        0x11781089f  google::LogMessageFatal::~LogMessageFatal()
    @        0x11780ca59  google::LogMessageFatal::~LogMessageFatal()
    @        0x104d19075  yb::master::MasterMain()
    @        0x104d17d92  main

*** Check failure stack trace: ***
    @        0x11780b2c8  google::LogMessage::SendToLog()
    @        0x11780ba45  google::LogMessage::Flush()
    @        0x11781089f  google::LogMessageFatal::~LogMessageFatal()
    @        0x11780ca59  google::LogMessageFatal::~LogMessageFatal()
    @        0x104d19075  yb::master::MasterMain()
    @        0x104d17d92  main

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)
```

**Comment by jasonyb** [comment]
@myang2021, I'm still getting the unhelpful message when upgrading 2.12.7.0 or 2.14.0.0 to recent master commit 303b72ffe3b815bc37a33d35881a6b02a692a1d1 fastdebug gcc11 alma8.

```
W0823 15:44:36.689481 25414 tablet_bootstrap.cc:1719] T N/A Tablet bootstrap failed: Internal error (yb/common/ql_expr.cc:810): Failed log replay. Reason: Column unexpectedly not found in cache
I0823 15:44:36.689546 25414 tablet.cc:964] T 00000000000000000000000000000000 P 6d22f8fdf7ae402db4135e0ac9033c1b: StartShutdown
I0823 15:44:36.689823 25414 transaction_participant.cc:157] T 00000000000000000000000000000000 P 6d22f8fdf7ae402db4135e0ac9033c1b: Shutdown
I0823 15:44:36.689836 25414 tablet.cc:983] T 00000000000000000000000000000000 P 6d22f8fdf7ae402db4135e0ac9033c1b: CompleteShutdown
I0823 15:44:36.689843 25414 tablet.cc:964] T 00000000000000000000000000000000 P 6d22f8fdf7ae402db4135e0ac9033c1b: StartShutdown
I0823 15:44:36.689896 25418 transaction_participant.cc:1060] T 00000000000000000000000000000000 P 6d22f8fdf7ae402db4135e0ac9033c1b: LoadFinished: closing, not starting transaction status resolution
I0823 15:44:36.689908 25414 db_impl.cc:785] T 00000000000000000000000000000000 P 6d22f8fdf7ae402db4135e0ac9033c1b [R]: Shutting down RocksDB at: /nfusr/dev-server/jason2/yugabyte-data/node-1/disk-1/yb-data/master/data/rocksdb/table-sys.catalog.uuid/tablet-00000000000000000000000000000000
I0823 15:44:36.690001 25414 db_impl.cc:785] T 00000000000000000000000000000000 P 6d22f8fdf7ae402db4135e0ac9033c1b [I]: Shutting down RocksDB at: /nfusr/dev-server/jason2/yugabyte-data/node-1/disk-1/yb-data/master/data/rocksdb/table-sys.catalog.uuid/tablet-00000000000000000000000000000000.intents
I0823 15:44:36.695971 25414 db_impl.cc:909] T 00000000000000000000000000000000 P 6d22f8fdf7ae402db4135e0ac9033c1b [I]: Shutdown done
I0823 15:44:36.697659 25414 db_impl.cc:909] T 00000000000000000000000000000000 P 6d22f8fdf7ae402db4135e0ac9033c1b [R]: Shutdown done
E0823 15:44:36.697980 25414 master.cc:330] Master@127.0.0.1:7100: Unable to init master catalog manager: Internal error (yb/common/ql_expr.cc:810): Unable to initialize catalog manager: Failed to initialize sys tables async: Failed log replay. Reason: Column unexpectedly not found in cache
F0823 15:44:36.698397 25367 master_main.cc:132] Internal error (yb/common/ql_expr.cc:810): Unable to initialize catalog manager: Failed to initialize sys tables async: Failed log replay. Reason: Column unexpectedly not found in cache
```

**Comment by myang2021** [comment]
I tried on centos with gcc11 fastdebug build of the commit 303b72ffe3b815bc37a33d35881a6b02a692a1d1 and  could not reproduce the problem (see the end of the text for the FATAL message).  Perhaps it is alma8 only. I don't have an alma8 dev machine.
```
==========================================================================================
YUGABYTE BUILD SUMMARY
==========================================================================================
Build type                       : fastdebug
C/C++ compiler                   : gcc11
Build architecture               : x86_64
Build directory                  : /nfusr/dev-server/myang/code/yb7/build/fastdebug-gcc11-dynamic-ninja
Third-party dir                  : /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20220806014332-c2f02d2024-centos7-x86_64-gcc11
C++ compilation time             : 1 seconds
Java compilation time            : 57 seconds
------------------------------------------------------------------------------------------
[myang@dev-server-myang yb7]$ /nfusr/dev-server/myang/code/yb7/build/latest/bin/yb-master --version
version 2.15.3.0 build PRE_RELEASE revision 303b72ffe3b815bc37a33d35881a6b02a692a1d1 build_type FASTDEBUG built at 24 Aug 2022 02:37:42 UTC
[myang@dev-server-myang yb7]$ ./bin/yb-ctl create --rf 1 --master_flags "initial_sys_catalog_snapshot_path=/nfusr/dev-server/myang/tmp/yugabyte-2.12.7.0/share/initial_sys_catalog_snapshot"
Creating cluster.
Waiting for cluster to be ready.
Traceback (most recent call last):
  File "/nfusr/dev-server/myang/code/yb7/scripts/installation/bin/yb-ctl", line 2140, in <module>
    control.run()
  File "/nfusr/dev-server/myang/code/yb7/scripts/installation/bin/yb-ctl", line 2117, in run
    self.args.func()
  File "/nfusr/dev-server/myang/code/yb7/scripts/installation/bin/yb-ctl", line 1874, in create_cmd_impl
    self.wait_for_cluster_or_raise()
  File "/nfusr/dev-server/myang/code/yb7/scripts/installation/bin/yb-ctl", line 1680, in wait_for_cluster_or_raise
    raise RuntimeError("Timed out waiting for a YugaByte DB cluster!")
RuntimeError: Timed out waiting for a YugaByte DB cluster!
Viewing file /tmp/tmpe1jnvo9e:
2022-08-24 02:38:51,769 INFO: Using binaries path: /nfusr/dev-server/myang/code/yb7/build/latest
2022-08-24 02:38:51,780 INFO: Using binaries path: /nfusr/dev-server/myang/code/yb7/build/latest
2022-08-24 02:38:51,780 INFO: Starting master-1 with:
/nfusr/dev-server/myang/code/yb7/build/latest/bin/yb-master --fs_data_dirs "/nfusr/dev-server/myang/yugabyte-data/node-1/disk-1" --webserver_interface 127.0.0.1 --rpc_bind_addresses 127.0.0.1 --v 0 --version_file_json_path=/nfusr/dev-server/myang/code/yb7/build/fastdebug-gcc11-dynamic-ninja --replication_factor=1 --yb_num_shards_per_tserver 2 --ysql_num_shards_per_tserver=2 --default_memory_limit_to_ram_ratio=0.35 --master_addresses 127.0.0.1:7100 --enable_ysql=true --initial_sys_catalog_snapshot_path=/nfusr/dev-server/myang/tmp/yugabyte-2.12.7.0/share/initial_sys_catalog_snapshot >"/nfusr/dev-server/myang/yugabyte-data/node-1/disk-1/master.out" 2>"/nfusr/dev-server/myang/yugabyte-data/node-1/disk-1/master.err" &
2022-08-24 02:38:51,784 INFO: Using binaries path: /nfusr/dev-server/myang/code/yb7/build/latest
2022-08-24 02:38:51,798 INFO: Using binaries path: /nfusr/dev-server/myang/code/yb7/build/latest
2022-08-24 02:38:51,799 INFO: Starting tserver-1 with:
/nfusr/dev-server/myang/code/yb7/build/latest/bin/yb-tserver --fs_data_dirs "/nfusr/dev-server/myang/yugabyte-data/node-1/disk-1" --webserver_interface 127.0.0.1 --rpc_bind_addresses 127.0.0.1 --v 0 --version_file_json_path=/nfusr/dev-server/myang/code/yb7/build/fastdebug-gcc11-dynamic-ninja --tserver_master_addrs=127.0.0.1:7100 --yb_num_shards_per_tserver=2 --redis_proxy_bind_address=127.0.0.1:6379 --cql_proxy_bind_address=127.0.0.1:9042 --local_ip_for_outbound_sockets=127.0.0.1 --use_cassandra_authentication=false --ysql_num_shards_per_tserver=2 --default_memory_limit_to_ram_ratio=0.65 --enable_ysql=true --pgsql_proxy_bind_address=127.0.0.1:5433 >"/nfusr/dev-server/myang/yugabyte-data/node-1/disk-1/tserver.out" 2>"/nfusr/dev-server/myang/yugabyte-data/node-1/disk-1/tserver.err" &
2022-08-24 02:38:51,802 INFO: Waiting for master and tserver processes to come up.
2022-08-24 02:38:51,831 INFO: Using binaries path: /nfusr/dev-server/myang/code/yb7/build/latest
2022-08-24 02:38:51,832 INFO: Waiting for master leader election and tablet server registration.
2022-08-24 02:39:53,135 ERROR: Failed waiting for None tservers, got None
^^^ Encountered errors ^^^
[myang@dev-server-myang yb7]$ grep ^F /nfusr/dev-server/myang/yugabyte-data/node-1/disk-1/master.err
F0824 02:38:58.788661  6774 catalog_manager.cc:1008] T 00000000000000000000000000000000 P aaafb87083ff45e29b36bd9fbd89b748: Failed to load sys catalog: Corruption (yb/master/sys_catalog_writer.cc:206): Failed while visiting roles in sys catalog: System catalog snapshot is corrupted, or is built using different build type: 0 vs 10
Fatal failure details written to /nfusr/dev-server/myang/yugabyte-data/node-1/disk-1/yb-data/master/logs/yb-master.FATAL.details.2022-08-24T02_38_58.pid6703.txt
F20220824 02:38:58 ../../src/yb/master/catalog_manager.cc:1008] T 00000000000000000000000000000000 P aaafb87083ff45e29b36bd9fbd89b748: Failed to load sys catalog: Corruption (yb/master/sys_catalog_writer.cc:206): Failed while visiting roles in sys catalog: System catalog snapshot is corrupted, or is built using different build type: 0 vs 10
```

**Comment by jasonyb** [comment]
To be clear, it was rf=1 for both before and after, and the before used downloaded releases.

**Comment by myang2021** [comment]
Got it, I wasn't doing exactly the same steps. Now I use yugabyted to create the old cluster, then stop the cluster, and finally restart the cluster using newly built yugabyted of commit  303b72ffe3b815bc37a33d35881a6b02a692a1d1. I reproduced the bug.
