### ISSUE TITLE
ysql: TestPgRegressTypesMisc may fail with `role "yugabyte_test" does not exist`

### ISSUE THREAD

**Issue by tedyu** [yugabyte/yugabyte-db#10146]
Jira Link: [DB-4797](https://yugabyte.atlassian.net/browse/DB-4797)
```
org.postgresql.util.PSQLException: FATAL: role "yugabyte_test" does not exist
3530             at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
3531             at org.postgresql.core.v3.QueryExecutorImpl.readStartupMessages(QueryExecutorImpl.java:2559)
3532             at org.postgresql.core.v3.QueryExecutorImpl.<init>(QueryExecutorImpl.java:133)
3533             at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:250)
3534             at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
3535             at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:195)
3536             at org.postgresql.Driver.makeConnection(Driver.java:454)
3537             at org.postgresql.Driver.connect(Driver.java:256)
3538             at java.sql.DriverManager.getConnection(DriverManager.java:664)
3539             at java.sql.DriverManager.getConnection(DriverManager.java:208)
3540             at org.yb.pgsql.BasePgSQLTest$ConnectionBuilder.connect(BasePgSQLTest.java:1839)
3541             at org.yb.pgsql.BasePgSQLTest.initPostgresBefore(BasePgSQLTest.java:303)
```
Here is the code which should have created the role earlier:
```
    // Create test role.
    try (Connection initialConnection = getConnectionBuilder().withUser(DEFAULT_PG_USER).connect();
         Statement statement = initialConnection.createStatement()) {
      statement.execute(
          "CREATE ROLE " + TEST_PG_USER + " SUPERUSER CREATEROLE CREATEDB BYPASSRLS LOGIN");
```
It seems the role was not in the cache of the server answering the subsequent connection request.

**Comment by m-iancu** [comment]
This issue does not appear in latest. Closing.
https://detective-gcp.dev.yugabyte.com/stability/test?branch=master&build_type=all&class=org.yb.pgsql.TestPgRegressTypesMisc&fail_tag=all&name=testPgRegressTypes&platform=all
