### ISSUE TITLE
[YSQL] SqlInserts sample app fails immediately if the master has not elected a leader yet

### ISSUE THREAD

**Issue by mbautin** [yugabyte/yugabyte-db#1015]
Jira Link: [DB-934](https://yugabyte.atlassian.net/browse/DB-934)
```
org.postgresql.util.PSQLException: FATAL: Not found: Error loading table with id 000000010000300080000000000004ec: Illegal state (yb/master/catalog_manager.cc:6978): Not the leader. Local UUID: 846ca1c055ba42dc9fe9c17a773e8554, Consensus state: current_term: 1 config { opid_index: -1 peers { permanent_uuid: "846ca1c055ba42dc9fe9c17a773e8554" member_type: VOTER last_known_private_addr { host: "127.0.0.1" port: 7100 } cloud_info { placement_cloud: "cloud1" placement_region: "datacenter1" placement_zone: "rack1" } } }
        at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:473)
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:205)
        at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
        at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:195)
        at org.postgresql.Driver.makeConnection(Driver.java:452)
        at org.postgresql.Driver.connect(Driver.java:254)
        at java.sql.DriverManager.getConnection(DriverManager.java:664)
        at java.sql.DriverManager.getConnection(DriverManager.java:208)
        at com.yugabyte.sample.apps.AppBase.getPostgresConnection(AppBase.java:139)
        at com.yugabyte.sample.apps.AppBase.getPostgresConnection(AppBase.java:127)
        at com.yugabyte.sample.apps.SqlInserts.createTablesIfNeeded(SqlInserts.java:77)
        at com.yugabyte.sample.Main.run(Main.java:166)
        at com.yugabyte.sample.Main.main(Main.java:245)

Mar 16, 2019 2:58:54 AM org.postgresql.Driver connect
SEVERE: Connection error:
org.postgresql.util.PSQLException: FATAL: Not found: Error loading table with id 000000010000300080000000000004ec: Illegal state (yb/master/catalog_manager.cc:6978): Not the leader. Local UUID: 846ca1c055ba42dc9fe9c17a773e8554, Consensus state: current_term: 1 config { opid_index: -1 peers { permanent_uuid: "846ca1c055ba42dc9fe9c17a773e8554" member_type: VOTER last_known_private_addr { host: "127.0.0.1" port: 7100 } cloud_info { placement_cloud: "cloud1" placement_region: "datacenter1" placement_zone: "rack1" } } }
        at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:473)
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:205)
        at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
        at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:195)
        at org.postgresql.Driver.makeConnection(Driver.java:452)
        at org.postgresql.Driver.connect(Driver.java:254)
        at java.sql.DriverManager.getConnection(DriverManager.java:664)
        at java.sql.DriverManager.getConnection(DriverManager.java:208)
        at com.yugabyte.sample.apps.AppBase.getPostgresConnection(AppBase.java:139)
        at com.yugabyte.sample.apps.AppBase.getPostgresConnection(AppBase.java:127)
        at com.yugabyte.sample.apps.SqlInserts.createTablesIfNeeded(SqlInserts.java:77)
        at com.yugabyte.sample.Main.run(Main.java:166)
        at com.yugabyte.sample.Main.main(Main.java:245)

Exception in thread "main" org.postgresql.util.PSQLException: FATAL: Not found: Error loading table with id 000000010000300080000000000004ec: Illegal state (yb/master/catalog_manager.cc:6978): Not the leader. Local UUID: 846ca1c055ba42dc9fe9c17a773e8554, Consensus state: current_term: 1 config { opid_index: -1 peers
{ permanent_uuid: "846ca1c055ba42dc9fe9c17a773e8554" member_type: VOTER last_known_private_addr { host: "127.0.0.1" port: 7100 } cloud_info { placement_cloud: "cloud1" placement_region: "datacenter1" placement_zone: "rack1" } } }
        at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:473)
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:205)
        at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
        at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:195)
        at org.postgresql.Driver.makeConnection(Driver.java:452)
        at org.postgresql.Driver.connect(Driver.java:254)
        at java.sql.DriverManager.getConnection(DriverManager.java:664)
        at java.sql.DriverManager.getConnection(DriverManager.java:208)
        at com.yugabyte.sample.apps.AppBase.getPostgresConnection(AppBase.java:139)
        at com.yugabyte.sample.apps.AppBase.getPostgresConnection(AppBase.java:127)
        at com.yugabyte.sample.apps.SqlInserts.createTablesIfNeeded(SqlInserts.java:77)
        at com.yugabyte.sample.Main.run(Main.java:166)
        at com.yugabyte.sample.Main.main(Main.java:245)
```

**Comment by kriteshranjan** [comment]
Closing this issue based on AI validation. cc: @m-iancu , @VamsidharGunturu

**Comment by kriteshranjan** [comment]
AI validation notes (`yb-issue-1015-analysis.md`):

# Analysis: yugabyte/yugabyte-db#1015 (DB-934)

Issue: "[YSQL] SqlInserts sample app fails immediately if the master has not elected a leader yet"
(filed 2019-03-16, open; labels kind/bug, kind/improve-ux, area/ysql, priority/medium; no comments).

Reported signature (verbatim key):

```
org.postgresql.util.PSQLException: FATAL: Not found: Error loading table with id 000000010000300080000000000004ec:
Illegal state (yb/master/catalog_manager.cc:6978): Not the leader. Local UUID: 846ca1c055ba42dc9fe9c17a773e8554, ...
        at ...
        at com.yugabyte.sample.apps.AppBase.getPostgresConnection(AppBase.java:139)
        at com.yugabyte.sample.apps.SqlInserts.createTablesIfNeeded(SqlInserts.java:77)
```

Reporter topology: single master (one VOTER peer `127.0.0.1:7100`, `current_term: 1`,
consensus state carries no `leader_uuid`), March-2019 build (~1.2 era).

## Verdict

VALIDATED — the 2019 defect is real and root-caused at file:line from the era source
(the reported error text embeds `yb/master/catalog_manager.cc:6978`, which matches the
2019-03-16 tree exactly); it was fixed in two layers long ago (server/client library
2019-09-06 in commit `5236661e62`, first verifiable release tag 2.0.5; sample app
2020-12-10 in yb-sample-apps `298300aa05`), and a five-cell runtime matrix on
2026.1.1.0 shows the immediate-failure UX cannot recur. Recommend closing as fixed.

## Root cause

Failure chain at the reported version (verified in this repo at commit
`9cb4f10cde2a` = 2019-03-16, the day the issue was filed):

1. `src/yb/master/catalog_manager.cc:6975-6978` (@9cb4f10cde2a) —
   `CatalogManager::ScopedLeaderSharedLock` ctor: committed consensus state has no
   `leader_uuid` (election not finished), so it sets
   `leader_status_ = STATUS_FORMAT(IllegalState, "Not the leader. Local UUID: $0, Consensus state: $1", ...)`.
   The message's own file:line (`catalog_manager.cc:6978`) matches the report byte-for-byte.
2. `src/yb/master/catalog_manager-internal.h:93-108` (@9cb4f10cde2a) —
   `CheckIsInitializedAndIsLeaderOrRespondInternal` returns that status to the client
   with wire code `MasterErrorPB::NOT_THE_LEADER` (a retryable classification).
3. **The defect** — `src/yb/client/client-internal.cc:973-981` (@9cb4f10cde2a),
   `GetTableSchemaRpc::Finished`: on `NOT_THE_LEADER` /
   `CATALOG_MANAGER_NOT_INITIALIZED` it re-resolved the master leader and retried
   **only inside `if (client_->IsMultiMaster())`**. With the reporter's single
   master, the branch was skipped and the raw `IllegalState` escaped on the first
   attempt — zero retries, hence "fails immediately".
4. `src/yb/yql/pggate/pg_session.cc:365-369` (@9cb4f10cde2a) —
   `PgSession::LoadTable` wrapped any `OpenTable` failure as
   `NotFound "Error loading table with id $0: $1"`, discarding the retryable
   classification.
5. The postgres backend was still in startup (catalog priming during connection
   establishment), where any error is reported as FATAL — surfaced to JDBC as
   `PSQLException` inside `doAuthentication`.
6. Client side: 2019 `AppBase.getPostgresConnection` had no retry around
   `DriverManager.getConnection`, so `SqlInserts.createTablesIfNeeded` aborted the app.

Fix history (why master/current releases are NOT affected):

- `5236661e62` (2019-09-06, issue #2222, D7147) — commit message states verbatim:
  "Master RPC is not retried with a single master. Fixed by retrying for a single
  master (multi-master already had retry mechanism)." It deleted the three
  `if (client_->IsMultiMaster())` gates (NOT_THE_LEADER, TimedOut, NetworkError
  branches) in `ClientMasterRpc::HandleFinished`. First release tag in this clone
  containing it: `2.0.5_FINAL`; every later train (2.1 ... 2026.1) descends from it.
- Today the unified retry lives at `src/yb/client/client_master_rpc.cc:104-122`
  (`ClientMasterRpcBase::Finished`): NOT_THE_LEADER / CATALOG_MANAGER_NOT_INITIALIZED /
  LeaderNotReadyToServe / LeaderHasNoLease all call `ResetMasterLeader(Retry::kTrue)`,
  and `ResetMasterLeader` (`client_master_rpc.cc:60-68`) passes
  `true /* wait for leader election */`. Retries continue until the RPC deadline,
  single-master included.
- The lossy NotFound wrap was removed by `442fe7937e` (2021-09-18, #9936
  "Open table via PgClient"); today `PgSession::DoLoadTable`
  (`src/yb/yql/pggate/pg_session.cc:682-714`) propagates the original status via
  `VERIFY_RESULT(pg_client_.OpenTable(...))`.
- Master-side guard today: `ScopedLeaderSharedLock::Lock()`
  (`src/yb/master/scoped_leader_shared_lock.cc:104-143`) delegates to
  `GetLeaderState().CreateStatus()` (`src/yb/consensus/consensus.cc:151-173`), and the
  wire code is still NOT_THE_LEADER (`src/yb/master/scoped_leader_shared_lock-internal.h:74`)
  — i.e. still retryable; `CatalogManager::CheckIsLeaderAndReady` keeps the same
  "Not the leader" text at `src/yb/master/catalog_manager.cc:2263-2265`.
- Additionally, modern defaults close the original race window at fresh start:
  `enable_ysql_operation_lease` defaults true (`src/yb/common/ysql_operation_lease.cc:21`,
  `IsYsqlLeaseEnabled()` at `:27-30`), so the tserver starts postgres paused
  (`src/yb/tserver/tablet_server_main_impl.cc:350-354`: `InitPaused()` vs `Start()`)
  until it holds a YSQL lease granted by the master leader
  (TTL `master_ysql_operation_lease_ttl_ms` = 30000,
  `src/yb/master/object_lock_info_manager.cc:63`). No master leader means postgres
  is not accepting connections at all ("connection refused", not a FATAL).
- Sample-app layer: yb-sample-apps commit `298300aa05` (2020-12-10, PR #42 "Retry SQL
  on connection error") wrapped `AppBase.getPostgresConnection(String,String,String)`
  in an infinite `do { try ... } catch (Exception) { log; sleep(2000); } while (true)`
  loop ("Going to retrieve connection again: ..."); current master (`29ecc465ec`)
  still has it, and `SqlInserts.createTablesIfNeeded` uses that path. (The sample app
  itself left this repo on 2019-02-19, commit `9d724d5de3`, ENG-4790; canonical home
  is github.com/yugabyte/yb-sample-apps.)

Master affected: NO (both defect layers fixed; behavior demonstrated below).

## Trigger matrix

All predictions derived from source before execution; all cells run on
`docker.io/yugabytedb/yugabyte:2026.1.1.0-b91-aarch64` via podman (Apple Silicon).
The disproven-2019 outcome in every cell is an immediate client-visible
`FATAL ... Not the leader`.

| # | Condition | Predicted | Observed |
|---|-----------|-----------|----------|
| 1 | Control: healthy cluster (3 masters + 1 tserver, lease off), fresh connection + query | OK immediately | OK, 0.038 s (`count=1`) |
| 2 | Reporter's race: connect-spam from t=0 of fresh single-node `yugabyted start` (stock defaults) | refused / "starting up" then success; never "Not the leader" | t=1..6 s `Connection refused`; t=7 s success; 0 occurrences of "Not the leader" in 100 attempts |
| 3 | Deterministic leaderless master (kill Raft leader + 1 follower of 3; survivor is a quorum-less follower; lease off so postgres stays up), new connection bounded at 20 s | blocks and retries (or serves from tserver catalog cache); NOT immediate FATAL | blocked the full 20 s, then client-side `timeout expired` (libpq PGCONNECT_TIMEOUT); tserver log shows retry loop: `tablet_rpc.cc:176] Unable to find the leader for 00000000000000000000000000000000, replicas: [], followers: ...` plus heartbeater NOT_THE_LEADER polls |
| 4 | Same leaderless state; connection attempt pending; master quorum restored at t=10 s | pending attempt completes successfully | success at 13.2 s total (10 s leaderless + ~3 s election), `count=1`, exit 0 |
| 5 | Leaderless with default lease semantics; wait 45 s (> 30 s TTL); new connection | connection refused (pg paused by lease loss); no FATAL | `Connection refused` in 0.005 s; postmaster process still running but not accepting; no "Not the leader" |

5/5 cells match prediction. The 2019 signature appeared nowhere.

## Reproduction

The 2019 immediate failure cannot be run on this host (1.2-era images are amd64-only
and predate aarch64 tags; prior sessions showed qemu-emulated old images are
unreliable here). The 2019 mechanism is instead proven by source archaeology: the
error text embeds `catalog_manager.cc:6978`, which matches the 2019-03-16 tree at
that exact line, and fix commit `5236661e62`'s message describes the single-master
no-retry bug verbatim. What is executable today is the modern-behavior matrix above,
including a bounded best-effort attempt at the reporter's exact race (cell 2).

Modern-behavior repro (paste-ready; aarch64 tags shown, drop `-aarch64` on x86_64):

```sh
IMG=docker.io/yugabytedb/yugabyte:2026.1.1.0-b91-aarch64

# Cell 2 - reporter's race on modern defaults: connect from t=0 of a fresh start
podman run -d --name yb1015a $IMG bash -c \
  '/home/yugabyte/bin/yugabyted start --daemon=false --advertise_address=127.0.0.1'
for i in $(seq 1 100); do
  podman exec yb1015a /home/yugabyte/bin/ysqlsh -h 127.0.0.1 -c 'select 1' 2>&1 | head -1
  sleep 1
done | tee cell2.log
grep -c 'Not the leader' cell2.log   # => 0

# Cells 1/3/4 - deterministic leaderless master with postgres up (lease disabled)
podman run -d --name yb1015b $IMG sleep infinity
podman exec yb1015b bash -c '
for i in 1 2 3; do
  mkdir -p /tmp/m$i
  /home/yugabyte/bin/yb-master --fs_data_dirs=/tmp/m$i \
    --master_addresses=127.0.0.1:7100,127.0.0.2:7100,127.0.0.3:7100 \
    --rpc_bind_addresses=127.0.0.$i:7100 --webserver_interface=127.0.0.$i \
    --webserver_port=7000 --replication_factor=1 \
    --enable_ysql_operation_lease=false --enable_object_locking_for_table_locks=false \
    --logtostderr > /tmp/m$i.log 2>&1 & echo $! > /tmp/m$i.pid
done
sleep 1; mkdir -p /tmp/ts1
/home/yugabyte/bin/yb-tserver --fs_data_dirs=/tmp/ts1 \
  --tserver_master_addrs=127.0.0.1:7100,127.0.0.2:7100,127.0.0.3:7100 \
  --rpc_bind_addresses=127.0.0.1:9100 --enable_ysql \
  --pgsql_proxy_bind_address=127.0.0.1:5433 --replication_factor=1 \
  --enable_ysql_operation_lease=false --enable_object_locking_for_table_locks=false \
  --logtostderr > /tmp/ts1.log 2>&1 & echo $! > /tmp/ts1.pid'
# wait for `ysqlsh -h 127.0.0.1 -c "select 1"` to succeed, then:
podman exec yb1015b bash -c '
/home/yugabyte/bin/ysqlsh -h 127.0.0.1 -c "create table t1015(k int primary key, v text); insert into t1015 values (1, chr(97));"
/home/yugabyte/bin/yb-admin --master_addresses=127.0.0.1:7100,127.0.0.2:7100,127.0.0.3:7100 list_all_masters'
# kill the LEADER row's master and one follower (survivor = quorum-less follower), e.g.:
podman exec yb1015b bash -c 'kill -9 $(cat /tmp/m3.pid) $(cat /tmp/m2.pid); sleep 3
echo "cell 3:"; time timeout 25 env PGCONNECT_TIMEOUT=20 \
  /home/yugabyte/bin/ysqlsh -h 127.0.0.1 -c "select count(*) from t1015"'
# expect: blocks ~20 s, then "timeout expired"; NOT an immediate FATAL Not-the-leader
podman exec yb1015b bash -c '
( timeout 90 env PGCONNECT_TIMEOUT=88 /home/yugabyte/bin/ysqlsh -h 127.0.0.1 \
    -c "select count(*) from t1015" > /tmp/cell4.out 2>&1; echo exit=$? >> /tmp/cell4.out ) &
sleep 10
for i in 2 3; do /home/yugabyte/bin/yb-master --fs_data_dirs=/tmp/m$i \
  --master_addresses=127.0.0.1:7100,127.0.0.2:7100,127.0.0.3:7100 \
  --rpc_bind_addresses=127.0.0.$i:7100 --webserver_interface=127.0.0.$i \
  --webserver_port=7000 --replication_factor=1 \
  --enable_ysql_operation_lease=false --enable_object_locking_for_table_locks=false \
  --logtostderr >> /tmp/m$i.log 2>&1 & echo $! > /tmp/m$i.pid; done
wait %1; cat /tmp/cell4.out'
# expect: " count \n-------\n     1" and exit=0 (~13 s total)

# Cell 5 - default lease semantics: repeat yb1015b WITHOUT the two lease flags,
# kill leader+follower, sleep 45 (> master_ysql_operation_lease_ttl_ms=30000), then:
#   ysqlsh -> "Connection refused" instantly (postgres paused by lease loss)

podman rm -f yb1015a yb1015b   # cleanup
```

Failure-signature greps used: `Not the leader` (must be absent client-side),
`Unable to find the leader for 00000000000000000000000000000000` (tserver retry
evidence, present during cell 3). Control case: cell 1 (healthy cluster, 0.038 s).
Evidence files: /tmp/claude/yb-issue-1015-cell2.log,
/tmp/claude/yb-issue-1015-cell3-evidence.log.

Note: one transient environment flake occurred while bringing up the cell-5
container (two yb-masters took an externally-delivered SIGSEGV under podman/applehv
during simultaneous spawn); a clean retry of the identical commands succeeded. Not
related to the issue under test.

## Versions tested

- 2019 defect version: source-verified at repo commit `9cb4f10cde2a` (2019-03-16,
  the filing date; ~1.2 era). Not executed (no aarch64 images exist for 2019 builds).
- Modern runtime: `docker.io/yugabytedb/yugabyte:2026.1.1.0-b91-aarch64` (newest
  published aarch64 tag at validation time) — all 5 matrix cells.
- Master branch: source-verified at `b89bc62335` (retry at
  `client_master_rpc.cc:104-122`; no `IsMultiMaster` gate; wrap removed). Master
  affected: NO.
- Fix vehicles: yugabyte-db `5236661e62` (first verifiable tag `2.0.5_FINAL`,
  2019); yb-sample-apps `298300aa05` (2020-12-10), still present on yb-sample-apps
  master `29ecc465ec`.

## Proposed fix direction

No code fix needed — both layers were fixed years ago:

- DB: `5236661e62` (#2222, D7147) made master-leader RPC retry unconditional
  (single-master included); today's `client_master_rpc.cc:104-122` retries and
  waits for leader election until the RPC deadline. `442fe7937e` (#9936) removed
  the status-laundering NotFound wrap. The YSQL operation lease (default on) keeps
  postgres from accepting connections when no master leader exists.
- Sample app: yb-sample-apps `298300aa05` (PR #42) retries connection establishment
  every 2 s indefinitely.

Recommended action: close #1015 as fixed, referencing `5236661e62` /
yb-sample-apps#42, or transfer any residual sample-app UX wish to
github.com/yugabyte/yb-sample-apps (the app left this repo in 2019 via
`9d724d5de3` / ENG-4790).

## Test strategy

Regression coverage already exists: `PgLibPqTest.OnConflictWithKillMaster`
(`src/yb/yql/pgwrapper/pg_on_conflict-test.cc`) was the test stabilized by the fix
commit `5236661e62` itself — it kills/restarts the master under YSQL load and fails
if master RPCs are not retried. Exercise via public entry points:

```sh
./yb_build.sh release --cxx-test pgwrapper_pg_on_conflict-test \
  --gtest_filter PgLibPqTest.OnConflictWithKillMaster
```

For the connection-during-leaderless-window path specifically, the container matrix
above (cells 3/4) is rerunnable by a maintainer with stock images and no build.
If a dedicated in-tree test were wanted, an ExternalMiniCluster test that stops the
master leader of a 3-master cluster, opens a new libpq connection with a generous
connect timeout, restarts the masters, and asserts the connection completes would
encode cell 4; no test-only production APIs required.

## Confidentiality check

All hosts/IPs are loopback (127.0.0.x) from the public issue text or local
containers; table/database names are synthetic (`t1015`); UUIDs shown are from the
public issue body or local throwaway clusters; no customer identifiers, PII,
internal hostnames/URLs, or secrets appear above. Jira reference DB-934 is the
public cross-link already present in the issue body. Safe for public artifacts.
