### ISSUE TITLE
[docdb] Master process terminates generating core_rpc_tp_Master 

### ISSUE THREAD

**Issue by adil246** [yugabyte/yugabyte-db#10176]
We see the _yb-master_ leader switching to various nodes in a span of few minutes with delays in leader elections. The process getting restarted and I see below cores generating. One of the node statuses shows **NETWORK_ERROR** before changing to **ALIVE**.

```

rw-------. 1 yugabyte yugabyte 2397741056 Oct  2 20:01 core_yb-master.19401
-rw-------. 1 yugabyte yugabyte  724631552 Oct  2 20:02 core_rpc_tp_Master_0.1942
-rw-------. 1 yugabyte yugabyte  916684800 Oct  2 20:04 core_rpc_tp_Master_1.2062
-rw-------. 1 yugabyte yugabyte  749527040 Oct  2 20:09 core_rpc_tp_Master_4.2471
-rw-------. 1 yugabyte yugabyte  718020608 Oct  2 20:15 core_rpc_tp_Master_0.3148
-rw-------. 1 yugabyte yugabyte  890449920 Oct  2 20:33 core_rpc_tp_Master_1.3835
-rw-------. 1 yugabyte yugabyte  770818048 Oct  2 20:37 core_rpc_tp_Master_1.5404
-rw-------. 1 yugabyte yugabyte  713027584 Oct  2 20:38 core_rpc_tp_Master_4.5808
-rw-------. 1 yugabyte yugabyte  758358016 Oct  2 20:49 core_rpc_tp_Master_8.5935
-rw-------. 1 yugabyte yugabyte  750010368 Oct  2 21:04 core_rpc_tp_Master_8.7103
-rw-------. 1 yugabyte yugabyte  731160576 Oct  2 21:05 core_rpc_tp_Master_3.8861
-rw-------. 1 yugabyte yugabyte  746893312 Oct  2 21:31 core_rpc_tp_Master_9.9177
-rw-------. 1 yugabyte yugabyte  722010112 Oct  2 21:32 core_rpc_tp_Master_0.12844
-rw-------. 1 yugabyte yugabyte  792809472 Oct  2 21:42 core_rpc_tp_Master_1.13019
-rw-------. 1 yugabyte yugabyte  708358144 Oct  2 21:43 core_rpc_tp_Master_3.14652

```
```
yb-admin list_masters
     State                            Role
     ALIVE                      FOLLOWER
      ALIVE                         LEADER
     NETWORK_ERROR   UNKNOWN

 State           Role
  ALIVE           FOLLOWER
  ALIVE           FOLLOWER
  ALIVE           LEADER


```
```
gdb /home/yugabyte/master/bin/yb-master core_rpc_tp_Master_3.14652

(gdb) bt
#0  __GI___pthread_mutex_lock (mutex=mutex@entry=0x8) at ../nptl/pthread_mutex_lock.c:67
#1  0x00007f7cc9bd329a in yb::Mutex::Acquire (this=this@entry=0x8) at ../../src/yb/util/mutex.cc:85
#2  0x00007f7cc9c28881 in MutexLock (lock=..., this=<synthetic pointer>) at ../../src/yb/util/mutex.h:105
#3  yb::RWCLock::ReadLock (this=this@entry=0x8) at ../../src/yb/util/rwc_lock.cc:65
#4  0x00007f7cd46bf3a8 in ReadLock (this=0x8) at ../../src/yb/util/cow_object.h:59
#5  yb::CowLock<yb::master::PersistentTableInfo>::CowLock (this=this@entry=0x5a37290, info=info@entry=0x8, mode=mode@entry=yb::CowLock<yb::master::PersistentTableInfo>::READ)
    at ../../src/yb/util/cow_object.h:187
#6  0x00007f7cd47c9e27 in MetadataLock (mode=yb::CowLock<yb::master::PersistentTableInfo>::READ, info=0x0, this=0x5a37290)
    at ../../ent/src/yb/master/../../../../src/yb/master/catalog_entity_info.h:105
#7  LockForRead (this=0x0) at ../../ent/src/yb/master/../../../../src/yb/master/catalog_entity_info.h:132
#8  yb::master::MasterServiceImpl::GetTabletLocations (this=this@entry=0x191b680, req=req@entry=0xb9f1410, resp=resp@entry=0xe869cf0, rpc=...) at ../../src/yb/master/master_service.cc:302
#9  0x00007f7ccd460f39 in yb::master::MasterServiceIf::Handle (this=0x191b680, call=...) at src/yb/master/master.service.cc:502
#10 0x00007f7ccc34b519 in yb::rpc::ServicePoolImpl::Handle (this=0x15a8d80, incoming=...) at ../../src/yb/rpc/service_pool.cc:262
#11 0x00007f7ccc2f0314 in yb::rpc::InboundCall::InboundCallTask::Run (this=<optimized out>) at ../../src/yb/rpc/inbound_call.cc:212
#12 0x00007f7ccc35d638 in yb::rpc::(anonymous namespace)::Worker::Execute (this=<optimized out>) at ../../src/yb/rpc/thread_pool.cc:105
#13 0x00007f7cc9c48edf in operator() (this=0x1c78dd8) at /home/yugabyte/yb-software/yugabyte-2.4.4.0-b7-centos-x86_64/linuxbrew-xxxxxxxxxxxxxx/Cellar/gcc/5.5.0_4/include/c++/5.5.0/functional:2267
#14 yb::Thread::SuperviseThread (arg=0x1c78d80) at ../../src/yb/util/thread.cc:771
#15 0x00007f7cc5396694 in start_thread (arg=0x7f7cb5bf6700) at pthread_create.c:333
#16 0x00007f7cc4ad341d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

(gdb) disas
Dump of assembler code for function __GI___pthread_mutex_lock:
   0x00007f7cc5398660 <+0>:     sub    $0x8,%rsp
=> 0x00007f7cc5398664 <+4>:     mov    0x10(%rdi),%esi
   0x00007f7cc5398667 <+7>:     mov    %rdi,%r8
   0x00007f7cc539866a <+10>:    mov    %esi,%eax
   0x00007f7cc539866c <+12>:    mov    %esi,%edx
   0x00007f7cc539866e <+14>:    and    $0x17f,%eax
   0x00007f7cc5398673 <+19>:    and    $0x7c,%edx
   0x00007f7cc5398676 <+22>:    jne    0x7f7cc5398763 <__GI___pthread_mutex_lock+259>
   0x00007f7cc539867c <+28>:    test   %eax,%eax
   0x00007f7cc539867e <+30>:    jne    0x7f7cc539870a <__GI___pthread_mutex_lock+170>
   0x00007f7cc5398684 <+36>:    mov    0x211d96(%rip),%edx        # 0x7f7cc55aa420 <__pthread_force_elision>
   0x00007f7cc539868a <+42>:    test   %edx,%edx
   0x00007f7cc539868c <+44>:    je     0x7f7cc53986c0 <__GI___pthread_mutex_lock+96>
   0x00007f7cc539868e <+46>:    test   $0x300,%esi
   0x00007f7cc5398694 <+52>:    jne    0x7f7cc53986c0 <__GI___pthread_mutex_lock+96>
   0x00007f7cc5398696 <+54>:    or     $0x100,%esi
   0x00007f7cc539869c <+60>:    mov    %esi,0x10(%rdi)
   0x00007f7cc539869f <+63>:    mov    %esi,%edx
   0x00007f7cc53986a1 <+65>:    lea    0x16(%r8),%rsi
   0x00007f7cc53986a5 <+69>:    mov    %r8,%rdi
   0x00007f7cc53986a8 <+72>:    and    $0x80,%edx
   0x00007f7cc53986ae <+78>:    add    $0x8,%rsp
   0x00007f7cc53986b2 <+82>:    jmpq   0x7f7cc539ff50 <__lll_lock_elision>
   0x00007f7cc53986b7 <+87>:    nopw   0x0(%rax,%rax,1)
   0x00007f7cc53986c0 <+96>:    and    $0x80,%esi
   0x00007f7cc53986c6 <+102>:   mov    $0x1,%edi
   0x00007f7cc53986cb <+107>:   xor    %eax,%eax
   0x00007f7cc53986cd <+109>:   lock cmpxchg %edi,(%r8)
   0x00007f7cc53986d2 <+114>:   je     0x7f7cc53986ea <__GI___pthread_mutex_lock+138>
   0x00007f7cc53986d4 <+116>:   lea    (%r8),%rdi
   0x00007f7cc53986d7 <+119>:   sub    $0x80,%rsp
   0x00007f7cc53986de <+126>:   callq  0x7f7cc539db20 <__lll_lock_wait>
   0x00007f7cc53986e3 <+131>:   add    $0x80,%rsp
   0x00007f7cc53986ea <+138>:   mov    0x8(%r8),%eax
   0x00007f7cc53986ee <+142>:   test   %eax,%eax
   0x00007f7cc53986f0 <+144>:   jne    0x7f7cc5398769 <__GI___pthread_mutex_lock+265>
   0x00007f7cc53986f2 <+146>:   mov    %fs:0x2d0,%eax
   0x00007f7cc53986fa <+154>:   addl   $0x1,0xc(%r8)
   0x00007f7cc53986ff <+159>:   mov    %eax,0x8(%r8)
   0x00007f7cc5398703 <+163>:   xor    %eax,%eax
   0x00007f7cc5398705 <+165>:   add    $0x8,%rsp
   0x00007f7cc5398709 <+169>:   retq
   0x00007f7cc539870a <+170>:   cmp    $0x100,%eax
   0x00007f7cc539870f <+175>:   je     0x7f7cc539869f <__GI___pthread_mutex_lock+63>
   0x00007f7cc5398711 <+177>:   mov    %esi,%edi
   0x00007f7cc5398713 <+179>:   and    $0x7f,%edi
   0x00007f7cc5398716 <+182>:   cmp    $0x1,%edi
---Type <return> to continue, or q <return> to quit---
   0x00007f7cc5398719 <+185>:   jne    0x7f7cc53987c2 <__GI___pthread_mutex_lock+354>
   0x00007f7cc539871f <+191>:   mov    %fs:0x2d0,%eax
   0x00007f7cc5398727 <+199>:   cmp    0x8(%r8),%eax
   0x00007f7cc539872b <+203>:   je     0x7f7cc53987a7 <__GI___pthread_mutex_lock+327>
   0x00007f7cc539872d <+205>:   and    $0x80,%esi
   0x00007f7cc5398733 <+211>:   mov    %edx,%eax
   0x00007f7cc5398735 <+213>:   lock cmpxchg %edi,(%r8)
   0x00007f7cc539873a <+218>:   je     0x7f7cc5398752 <__GI___pthread_mutex_lock+242>
   0x00007f7cc539873c <+220>:   lea    (%r8),%rdi
   0x00007f7cc539873f <+223>:   sub    $0x80,%rsp
   0x00007f7cc5398746 <+230>:   callq  0x7f7cc539db20 <__lll_lock_wait>
   0x00007f7cc539874b <+235>:   add    $0x80,%rsp
   0x00007f7cc5398752 <+242>:   cmpl   $0x0,0x8(%r8)
   0x00007f7cc5398757 <+247>:   jne    0x7f7cc5398788 <__GI___pthread_mutex_lock+296>
   0x00007f7cc5398759 <+249>:   movl   $0x1,0x4(%r8)
   0x00007f7cc5398761 <+257>:   jmp    0x7f7cc53986f2 <__GI___pthread_mutex_lock+146>
   0x00007f7cc5398763 <+259>:   pop    %rcx
   0x00007f7cc5398764 <+260>:   jmpq   0x7f7cc53939c0 <__pthread_mutex_lock_full>
   0x00007f7cc5398769 <+265>:   lea    0x8160(%rip),%rcx        # 0x7f7cc53a08d0 <__PRETTY_FUNCTION__.8513>
   0x00007f7cc5398770 <+272>:   lea    0x7fd1(%rip),%rsi        # 0x7f7cc53a0748
   0x00007f7cc5398777 <+279>:   lea    0x7fe7(%rip),%rdi        # 0x7f7cc53a0765
   0x00007f7cc539877e <+286>:   mov    $0x51,%edx
   0x00007f7cc5398783 <+291>:   callq  0x7f7cc5393670 <__assert_fail@plt>
   0x00007f7cc5398788 <+296>:   lea    0x8141(%rip),%rcx        # 0x7f7cc53a08d0 <__PRETTY_FUNCTION__.8513>
   0x00007f7cc539878f <+303>:   lea    0x7fb2(%rip),%rsi        # 0x7f7cc53a0748
   0x00007f7cc5398796 <+310>:   lea    0x7fc8(%rip),%rdi        # 0x7f7cc53a0765
   0x00007f7cc539879d <+317>:   mov    $0x75,%edx
   0x00007f7cc53987a2 <+322>:   callq  0x7f7cc5393670 <__assert_fail@plt>
   0x00007f7cc53987a7 <+327>:   mov    0x4(%r8),%eax
   0x00007f7cc53987ab <+331>:   cmp    $0xffffffff,%eax
   0x00007f7cc53987ae <+334>:   je     0x7f7cc5398862 <__GI___pthread_mutex_lock+514>
   0x00007f7cc53987b4 <+340>:   add    $0x1,%eax
   0x00007f7cc53987b7 <+343>:   mov    %eax,0x4(%r8)
   0x00007f7cc53987bb <+347>:   xor    %eax,%eax
   0x00007f7cc53987bd <+349>:   jmpq   0x7f7cc5398705 <__GI___pthread_mutex_lock+165>
   0x00007f7cc53987c2 <+354>:   cmp    $0x3,%edi
   0x00007f7cc53987c5 <+357>:   jne    0x7f7cc539889c <__GI___pthread_mutex_lock+572>
   0x00007f7cc53987cb <+363>:   cmpl   $0x0,0x211bd2(%rip)        # 0x7f7cc55aa3a4 <__is_smp>
   0x00007f7cc53987d2 <+370>:   je     0x7f7cc53986c0 <__GI___pthread_mutex_lock+96>
   0x00007f7cc53987d8 <+376>:   mov    %edx,%eax
   0x00007f7cc53987da <+378>:   mov    $0x1,%edx
   0x00007f7cc53987df <+383>:   lock cmpxchg %edx,(%r8)
   0x00007f7cc53987e4 <+388>:   test   %eax,%eax
   0x00007f7cc53987e6 <+390>:   je     0x7f7cc5398838 <__GI___pthread_mutex_lock+472>
   0x00007f7cc53987e8 <+392>:   movswl 0x14(%r8),%eax
   0x00007f7cc53987ed <+397>:   mov    $0x1,%esi
   0x00007f7cc53987f2 <+402>:   lea    0xa(%rax,%rax,1),%ecx
   0x00007f7cc53987f6 <+406>:   mov    $0x64,%eax

End of assembler dump.
(gdb) i r
rax            0x5a37290        94597776
rbx            0x8      8
rcx            0xdfcb00 14666496
rdx            0x0      0
rsi            0x8      8
rdi            0x8      8
rbp            0x7f7cb5beb6a0   0x7f7cb5beb6a0
rsp            0x7f7cb5beb680   0x7f7cb5beb680
r8             0xdfcac0 14666432
r9             0x7f7cc989b680   140173933917824
r10            0x10     16
r11            0x7f7cc4b56be0   140173852896224
r12            0x0      0
r13            0x7f7cb5becb30   140173601852208
r14            0xe869cf0        243703024
r15            0xe869cf0        243703024
rip            0x7f7cc5398664   0x7f7cc5398664 <__GI___pthread_mutex_lock+4>
eflags         0x10202  [ IF RF ]
cs             0x33     51
ss             0x2b     43
ds             0x0      0
es             0x0      0
fs             0x0      0
gs             0x0      0
(gdb)



```

Reference Ticket: 2003

**Comment by lizayugabyte** [comment]
@adil246 Is there any particular reason this ticket was added to the Documentation project? (docs posted on YB website)

**Comment by bmatican** [comment]
Closing. This was a 2.4.x bug only and we've since backported a narrow fix for it.

6977ae1912be3244f0c2b177fab3a0715aee9be0
