### ISSUE TITLE
[YCQL]Spark, Dataframe, when Dataframe has a column which does not exist in YCQL, error message is wrong.

### ISSUE THREAD

**Issue by mheer9** [yugabyte/yugabyte-db#10202]
We have A customer who is using Spark, DataFrame with YCQL.

When Dataframe has a column which does not exist in YCQL, the error message refers to jsonb column.

E.g
CREATE TABLE param.person (
id int PRIMARY KEY,
name text,
address text
) WITH default_time_to_live = 0
AND transactions = {'enabled': 'false'};

I/P Dataframe :

+------+-----+-------+------------+
|id    |name |address|code        |
+------+-----+-------+------------+
|11222 |Param| India |IND         |
+------+-----+-------+------------+

The Error is
Caused by: java.lang.IllegalArgumentException: JSON column mapping is missing
at com.datastax.spark.connector.writer.TableWriter.queryTemplateUsingUpdate$lzycompute(TableWriter.scala:130)
at com.datastax.spark.connector.writer.TableWriter.queryTemplateUsingUpdate(TableWriter.scala:80)
at com.datastax.spark.connector.writer.TableWriter.getAsyncWriter(TableWriter.scala:217

The Error should be something like "code column not available in person table", as the current error message is misleading.

**Comment by tedyu** [comment]
Resolved in 3.0-yb-10 release.
