### ISSUE TITLE
Add retries around the initdb build step to work around transient port conflicts

### ISSUE THREAD

**Issue by mbautin** [yugabyte/yugabyte-db#10290]
Saw this when trying to do a release using a command line like below. We need to make sure the initdb build step is more resilient to transient failures.
```
docker run -it yugabyteci/yb_build_infra_centos7:v2021-09-09T02_46_27 /bin/sudo -i -u yugabyteci bash -c 'cd /home/yugabyteci && export PATH=/usr/local/bin:$PATH && git clone https://github.com/yugabyte/yugabyte-db.git --depth 1  && cd yugabyte-db && ./yb_release --force'
```

Error log:
```
[m-1] I1013 19:15:00.463873 13036 net_util.cc:508] $ export PATH=$PATH:/usr/sbin ; lsof -n -i 'TCP:23785' -sTCP:LISTEN ; for pid in $(lsof -F p -n -i 'TCP:23785' -sTCP:LISTEN | cut -f 2 -dp) ; do  while [ $pid -gt 1 ] ; do    ps h -fp $pid ;    pid=$(sed 's/.* (.*) [^ ] \([0-9]*\).*/\1/g' /proc/$pid/stat);  done ; done
[m-1] bash: lsof: command not found
[m-1] bash: lsof: command not found
[m-1] W1013 19:15:00.477408 13036 net_util.cc:515]
[m-1] F1013 19:15:00.477497 13036 master_main.cc:138] Network error (yb/server/webserver.cc:248): Webserver: Could not start on address localhost:23785
[m-1] Fatal failure details written to /home/yugabyteci/yugabyte-db/build/release-gcc-dynamic-ninja/yb-test-logs/tests-pgwrapper__create_initial_sys_catalog_snapshot/CreateInitialSysCatalogSnapshotTest_CreateInitialSysCatalogSnapshot.fatal_failure_details.m-1.2021-10-13T19_15_00.pid13036.txt
[m-1] F20211013 19:15:00 ../../src/yb/master/master_main.cc:138] Network error (yb/server/webserver.cc:248): Webserver: Could not start on address localhost:23785
[m-1]     @     0x7f33df82548c  yb::LogFatalHandlerSink::send()
[m-1]     @     0x7f33dec204a6  google::LogMessage::SendToLog()
[m-1]     @     0x7f33dec1da7a  google::LogMessage::Flush()
[m-1]     @     0x7f33dec21169  google::LogMessageFatal::~LogMessageFatal()
[m-1]     @           0x409a7b  yb::master::MasterMain()
[m-1]     @     0x7f33da289825  __libc_start_main
[m-1]     @           0x408a89  _start
[m-1]     @              (nil)  (unknown)
[m-1]
[m-1] *** Check failure stack trace: ***
[m-1]     @     0x7f33df823871  yb::(anonymous namespace)::DumpStackTraceAndExit()
[m-1]     @     0x7f33dec1e01d  google::LogMessage::Fail()
[m-1]     @     0x7f33dec20546  google::LogMessage::SendToLog()
[m-1]     @     0x7f33dec1da7a  google::LogMessage::Flush()
[m-1]     @     0x7f33dec21169  google::LogMessageFatal::~LogMessageFatal()
[m-1]     @           0x409a7b  yb::master::MasterMain()
[m-1]     @     0x7f33da289825  __libc_start_main
[m-1]     @           0x408a89  _start
[m-1]     @              (nil)  (unknown)
../../src/yb/yql/pgwrapper/pg_wrapper_test_base.cc:55: Failure
Failed
Bad status: Runtime error (yb/integration-tests/external_mini_cluster.cc:2048): Failed to start masters.: Unable to start Master at index 0: Process exited with rc=6: /home/yugabyteci/yugabyte-db/build/release-gcc-dynamic-ninja/tests-pgwrapper/../bin/yb-master
Test failure stack trace:
    @     0x7f08d92dd255  MinimalistPrinter::OnTestPartResult()
    @     0x7f08c7b493a1  testing::internal::TestEventRepeater::OnTestPartResult()
    @     0x7f08c7b62c81  testing::UnitTest::AddTestPartResult()
    @     0x7f08c7b63153  testing::internal::AssertHelper::operator=()
    @     0x7f08d95014c4  yb::pgwrapper::PgWrapperTestBase::SetUp()
    @     0x7f08c7b6d6e8  testing::internal::HandleExceptionsInMethodIfSupported<>()
    @     0x7f08c7b644b6  testing::Test::Run()
    @     0x7f08c7b64668  testing::TestInfo::Run()
    @     0x7f08c7b64745  testing::TestCase::Run()
    @     0x7f08c7b649f8  testing::internal::UnitTestImpl::RunAllTests()
    @     0x7f08c7b6db98  testing::internal::HandleExceptionsInMethodIfSupported<>()
    @     0x7f08c7b64d3e  testing::UnitTest::Run()
    @     0x7f08d92dccff  main
    @     0x7f08c6aaf825  __libc_start_main
    @           0x4067e9  _start
    @              (nil)  (unknown)

I1013 19:15:00.509845 13029 test_util.cc:93] -----------------------------------------------
I1013 19:15:00.509871 13029 test_util.cc:94] Had fatal failures, leaving test files at /tmp/yb_test.tmp.8655.10824.6738.pid12963/create_initial_sys_catalog_snapshot.CreateInitialSysCatalogSnapshotTest.CreateInitialSysCatalogSnapshot.1634152500246711-13029
[  FAILED  ] CreateInitialSysCatalogSnapshotTest.CreateInitialSysCatalogSnapshot (246 ms)
[----------] 1 test from CreateInitialSysCatalogSnapshotTest (246 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (246 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] CreateInitialSysCatalogSnapshotTest.CreateInitialSysCatalogSnapshot


```

**Comment by radekg** [comment]
Very similar to this `./yb_build.sh --clang11`:

```
[m-1] I0118 00:00:52.751585  9135 permissions_manager.cc:98] Created role: cassandra
[m-1] I0118 00:00:52.752436  9135 catalog_manager.cc:1175] T 00000000000000000000000000000000 P b7d37da31e5245ed973b7f3aded08ba2: Setting cluster UUID to d39de2c0-2602-4078-bfb1-23cd236246bc (randomly generated)
[m-1] I0118 00:00:52.755415  9135 catalog_manager.cc:1005] T 00000000000000000000000000000000 P b7d37da31e5245ed973b7f3aded08ba2: YSQL is enabled, will create the transaction status table when 3 tablet servers are online
[m-1] I0118 00:00:52.755590  9135 sys_catalog_initialization.cc:234] initdb has never been run on this cluster, running it
[m-1] I0118 00:00:52.755793  9135 catalog_manager.cc:896] T 00000000000000000000000000000000 P b7d37da31e5245ed973b7f3aded08ba2: Completed load of sys catalog in term 1
[m-1] I0118 00:00:52.755825  9261 pg_wrapper.cc:488] Running initdb to initialize YSQL cluster with master addresses {127.0.0.1:27216}
[m-1] I0118 00:00:52.756170  9261 pg_wrapper.cc:447] Launching initdb: [/source/code/yugabyte-db/build/debug-clang11-dynamic/postgres/bin/initdb, -D, /tmp/tmp_pg_data_1528166012, -U, postgres]
[m-1 stdout] The files belonging to this database system will be owned by user "root".
[m-1 stdout] This user must also own the server process.
[m-1 stdout]
[m-1] In YugabyteDB, setting LC_COLLATE to C and all other locale settings to en_US.UTF-8 by default. Locale support will be enhanced as part of addressing https://github.com/yugabyte/yugabyte-db/issues/1557
[m-1] initdb: invalid locale name "en_US.UTF-8"
[m-1] I0118 00:00:52.879910  9261 pg_wrapper.cc:514] initdb took 123 ms
[m-1] E0118 00:00:52.879968  9261 pg_wrapper.cc:518] initdb failed: Runtime error (yb/yql/pgwrapper/pg_wrapper.cc:460): /source/code/yugabyte-db/build/debug-clang11-dynamic/postgres/bin/initdb failed with exit code 1
[m-1] E0118 00:00:52.880069  9261 catalog_manager.cc:7582] initdb failed: Runtime error (yb/yql/pgwrapper/pg_wrapper.cc:460): /source/code/yugabyte-db/build/debug-clang11-dynamic/postgres/bin/initdb failed with exit code 1
E0118 00:00:53.218441  8678 external_mini_cluster.cc:1220] master reported an initdb error: Runtime error (yb/yql/pgwrapper/pg_wrapper.cc:460): /source/code/yugabyte-db/build/debug-clang11-dynamic/postgres/bin/initdb failed with exit code 1
/source/code/yugabyte-db/src/yb/yql/pgwrapper/pg_wrapper_test_base.cc:55: Failure
Failed
Bad status: Runtime error (yb/integration-tests/external_mini_cluster.cc:1221): Failed to start masters.: initdb failed: Runtime error (yb/yql/pgwrapper/pg_wrapper.cc:460): /source/code/yugabyte-db/build/debug-clang11-dynamic/postgres/bin/initdb failed with exit code 1
[m-1] W0118 00:00:53.250577  9279 catalog_manager.cc:2014] Tablespace refresh task failed with error Internal error (yb/master/catalog_manager.cc:1879): pg_tablespace table info not found
Test failure stack trace:
/source/code/yugabyte-db/src/yb/yql/pgwrapper/pg_wrapper_test_base.cc:55:                               @     0x7f7aab7b122f  yb::pgwrapper::PgWrapperTestBase::SetUp()
/source/code/yugabyte-db/src/yb/yql/pgwrapper/create_initial_sys_catalog_snapshot.cc:32:                @           0x40ccb7  yb::pgwrapper::CreateInitialSysCatalogSnapshotTest::SetUp()
I0118 00:00:53.885790  8678 external_mini_cluster.cc:2169] { daemon_id: m-1 bound_rpc: :0 } Starting Shutdown()
I0118 00:00:53.885936  8678 external_mini_cluster.cc:2212] Killing /source/code/yugabyte-db/build/debug-clang11-dynamic/tests-pgwrapper/../bin/yb-master with pid 8719 with SIGKILL
I0118 00:00:53.897431  8678 test_util.cc:93] -----------------------------------------------
I0118 00:00:53.897469  8678 test_util.cc:94] Had fatal failures, leaving test files at /tmp/yb_test.tmp.12166.6623.7710.pid8561/create_initial_sys_catalog_snapshot.CreateInitialSysCatalogSnapshotTest.CreateInitialSysCatalogSnapshot.1642464048827206-8678
[  FAILED  ] CreateInitialSysCatalogSnapshotTest.CreateInitialSysCatalogSnapshot (5035 ms)
[----------] 1 test from CreateInitialSysCatalogSnapshotTest (5035 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (5035 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] CreateInitialSysCatalogSnapshotTest.CreateInitialSysCatalogSnapshot

 1 FAILED TEST
I0118 00:00:53.928683  8676 run-with-timeout.cc:197] subprocess.Wait finished, waitpid() returned 256
I0118 00:00:53.928771  8676 run-with-timeout.cc:204] Waiting for reaper thread to join
I0118 00:00:53.928810  8679 run-with-timeout.cc:181] Reaper thread: finished=1, subprocess_is_running=0, timeout_sec=1201
I0118 00:00:53.928872  8676 run-with-timeout.cc:208] Child process returned exit code 1
I0118 00:00:53.928884  8676 run-with-timeout.cc:223] Returning exit code 1
I0118 00:00:53.928890  8676 run-with-timeout.cc:225] Total time taken: 5.229 sec
(end of standard output)

Standard error from external program {{ '/source/code/yugabyte-db/build-support/run-test.sh' /source/code/yugabyte-db/build/debug-clang11-dynamic/tests-pgwrapper/create_initial_sys_catalog_snapshot }} running in '/source/code/yugabyte-db/build/debug-clang11-dynamic', saving stdout to {{ /source/code/yugabyte-db/build/debug-clang11-dynamic/create_initial_sys_catalog_snapshot.out }}, stderr to {{ /source/code/yugabyte-db/build/debug-clang11-dynamic/create_initial_sys_catalog_snapshot.err }}:
Details of third-party dependencies:
    YB_THIRDPARTY_DIR: /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20211123154036-c38d3df279-ubuntu2004-x86_64-clang11 (from environment)
    YB_DOWNLOAD_THIRDPARTY: 1
    NO_REBUILD_THIRDPARTY: 1
+ /source/code/yugabyte-db/build/debug-clang11-dynamic/bin/run-with-timeout 1201 /source/code/yugabyte-db/build/debug-clang11-dynamic/tests-pgwrapper/create_initial_sys_catalog_snapshot --initial_sys_catalog_snapshot_dest_path=/source/code/yugabyte-db/build/debug-clang11-dynamic/share/initial_sys_catalog_snapshot --gtest_output=xml:/source/code/yugabyte-db/build/debug-clang11-dynamic/yb-test-logs/tests-pgwrapper__create_initial_sys_catalog_snapshot/CreateInitialSysCatalogSnapshotTest_CreateInitialSysCatalogSnapshot.xml --gtest_filter=CreateInitialSysCatalogSnapshotTest.CreateInitialSysCatalogSnapshot
[2022-01-18T00:00:53 common-test-env.sh:1163 did_test_succeed] Test failure reason: exit code: 1

TEST FAILURE
Test command: /source/code/yugabyte-db/build/debug-clang11-dynamic/tests-pgwrapper/create_initial_sys_catalog_snapshot --initial_sys_catalog_snapshot_dest_path=/source/code/yugabyte-db/build/debug-clang11-dynamic/share/initial_sys_catalog_snapshot --gtest_output=xml:/source/code/yugabyte-db/build/debug-clang11-dynamic/yb-test-logs/tests-pgwrapper__create_initial_sys_catalog_snapshot/CreateInitialSysCatalogSnapshotTest_CreateInitialSysCatalogSnapshot.xml --gtest_filter=CreateInitialSysCatalogSnapshotTest.CreateInitialSysCatalogSnapshot
Test exit status: 1
Log path: /source/code/yugabyte-db/build/debug-clang11-dynamic/yb-test-logs/tests-pgwrapper__create_initial_sys_catalog_snapshot/CreateInitialSysCatalogSnapshotTest_CreateInitialSysCatalogSnapshot.log
[2022-01-18T00:00:54 common-test-env.sh:806 handle_cxx_test_xml_output] Test failed, updating /source/code/yugabyte-db/build/debug-clang11-dynamic/yb-test-logs/tests-pgwrapper__create_initial_sys_catalog_snapshot/CreateInitialSysCatalogSnapshotTest_CreateInitialSysCatalogSnapshot.xml
+ /source/code/yugabyte-db/build-support/update_test_result_xml.py --result-xml /source/code/yugabyte-db/build/debug-clang11-dynamic/yb-test-logs/tests-pgwrapper__create_initial_sys_catalog_snapshot/CreateInitialSysCatalogSnapshotTest_CreateInitialSysCatalogSnapshot.xml --mark-as-failed true
[postprocess_test_result.py:145] 2022-01-18 00:00:54,803 INFO: Log path: /source/code/yugabyte-db/build/debug-clang11-dynamic/yb-test-logs/tests-pgwrapper__create_initial_sys_catalog_snapshot/CreateInitialSysCatalogSnapshotTest_CreateInitialSysCatalogSnapshot.log
[postprocess_test_result.py:146] 2022-01-18 00:00:54,803 INFO: JUnit XML path: /source/code/yugabyte-db/build/debug-clang11-dynamic/yb-test-logs/tests-pgwrapper__create_initial_sys_catalog_snapshot/CreateInitialSysCatalogSnapshotTest_CreateInitialSysCatalogSnapshot.xml
[postprocess_test_result.py:246] 2022-01-18 00:00:54,804 INFO: Wrote JSON test report file: /source/code/yugabyte-db/build/debug-clang11-dynamic/yb-test-logs/tests-pgwrapper__create_initial_sys_catalog_snapshot/CreateInitialSysCatalogSnapshotTest_CreateInitialSysCatalogSnapshot_test_report.json
(end of standard error)
Traceback (most recent call last):
  File "/source/code/yugabyte-db/python/yb/gen_initial_sys_catalog_snapshot.py", line 83, in <module>
    main()
  File "/source/code/yugabyte-db/python/yb/gen_initial_sys_catalog_snapshot.py", line 74, in main
    raise RuntimeError("initdb failed in %.1f sec" % elapsed_time_sec)
RuntimeError: initdb failed in 6.4 sec
make[2]: *** [src/yb/yql/pgwrapper/CMakeFiles/initial_sys_catalog_snapshot.dir/build.make:57: src/yb/yql/pgwrapper/CMakeFiles/initial_sys_catalog_snapshot] Error 1
make[1]: *** [CMakeFiles/Makefile2:50001: src/yb/yql/pgwrapper/CMakeFiles/initial_sys_catalog_snapshot.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[100%] Built target pg_index_backfill-test
[100%] Built target ql-create-table-test
[100%] Linking CXX executable ../../../../tests-pgwrapper/pg_mini-test
[100%] Built target pg_mini-test
[100%] Linking CXX executable ../../../../tests-pgwrapper/pg_libpq-test
[100%] Built target pg_libpq-test
make: *** [Makefile:95: all] Error 2

real	12m31.518s
user	319m59.614s
sys	19m1.396s
[2022-01-18T00:01:00 yb_build.sh:449 run_cxx_build] C++ build finished with exit code 2 (build type: debug, compiler: clang11). Timing information is available above.

==========================================================================================
YUGABYTE BUILD SUMMARY
==========================================================================================
Build type                       : debug
C/C++ compiler                   : clang11
Build architecture               : x86_64
Build directory                  : /source/code/yugabyte-db/build/debug-clang11-dynamic
Third-party dir                  : /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20211123154036-c38d3df279-ubuntu2004-x86_64-clang11
C++ compilation time             : 752 seconds
Exit code                        : 2
------------------------------------------------------------------------------------------
```
