### ISSUE TITLE
TestPgRegressLargeTable times out and leaves no JUnit XML result file

### ISSUE THREAD

**Issue by mbautin** [yugabyte/yugabyte-db#10322]
This test sometimes times out in 30 minutes and does not leave an XML file behind, so we don't see the failure.

**Comment by tedyu** [comment]
Sometimes test output was generated, failing with:
```
2022-02-01 01:31:48,027 (main) [ERROR - org.yb.BaseYBTest$1$2.logEventDetails(BaseYBTest.java:240)] YB Java test failed: class="org.yb.pgsql.TestPgRegressLargeTable", method="testPgRegressLargeTable"
java.lang.AssertionError: Query 'com.yugabyte.jdbc.PgStatement@3d4a1a6' took 30435 ms! Expected 30000 ms at most
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.assertTrue(Assert.java:41)
    at org.yb.AssertionWrappers.lambda$assertTrue$0(AssertionWrappers.java:61)
    at org.yb.AssertionWrappers.wrapAssertion(AssertionWrappers.java:45)
    at org.yb.AssertionWrappers.assertTrue(AssertionWrappers.java:61)
    at org.yb.pgsql.BasePgSQLTest.assertQueryRuntimeWithRowCount(BasePgSQLTest.java:1868)
    at org.yb.pgsql.TestPgRegressLargeTable.testPgRegressLargeTable(TestPgRegressLargeTable.java:98)
```
