### ISSUE TITLE
[DocDB] Null pointer dereference in TabletPeer::GetLastReplicatedData

### ISSUE THREAD

**Issue by karishmalalani** [yugabyte/yugabyte-db#10824]
### Description

Description 

 tservers crashing during a period of high write load, From inspecting the core dump, it appears the cause is a null pointer dereference on the `consensus_` member here: https://github.com/yugabyte/yugabyte-db/blob/v2.6.1.1/src/yb/tablet/tablet_peer.cc

BackTrace

```
(gdb) bt
#0 yb::tablet::TabletPeer::GetLastReplicatedData (this=0x520e600, data=0x7fc8d0455da0) at ../../src/yb/tablet/tablet_peer.cc:648
#1 0x00007fee57658c1b in yb::tablet::RemoveIntentsTask::Run (this=0xa3101cab0) at ../../src/yb/tablet/remove_intents_task.cc:45
#2 0x00007fee51d352c9 in yb::rpc::Strand::Done (this=0x5201cb0, status=...) at ../../src/yb/rpc/strand.cc:77
#3 0x00007fee51d43243 in yb::rpc::(anonymous namespace)::Worker::Execute (this=<optimized out>) at ../../src/yb/rpc/thread_pool.cc:106
#4 0x00007fee4dab79cf in std::function<void ()>::operator()() const (this=0xb822838)
at /usr/scratch/yugabyte/yugabyte-2.6.1.d-linux/linuxbrew-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/Cellar/gcc/5.5.0_4/include/c++/5.5.0/functional:2267
#5 yb::Thread::SuperviseThread (arg=0xb8227e0) at ../../src/yb/util/thread.cc:771
#6 0x00007fee49204694 in start_thread (arg=0x7fc8d045e700) at pthread_create.c:333
#7 0x00007fee4894141d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

Reference Ticket:#2395

**Comment by bmatican** [comment]
This was fixed by 686303321093c9bdea8363117c018b742e13bd9a and backported through 2.6, where this issue was detected.

**Comment by tedyu** [comment]
The referenced commit was on Jun 25, 2021 

This issue was filed on Dec 9th, 2021.

**Comment by bmatican** [comment]
@tedyu note that the stack shared was a 2.6.1 stack
