### ISSUE TITLE
[Platform] Backup fails with Tables for table <tableid> not found on tablet server

### ISSUE THREAD

**Issue by markwjeske** [yugabyte/yugabyte-db#10950]
### Description

Getting this error on yugaware 2.11.2.0-b52 when performing ysql restore of database:

2021-12-28 16:41:36.183 [error] TaskExecutor.java:787 [TaskPool-BackupUniverse(7f0eb94c-1d83-49cc-b583-e2b0cb86d18e)-0] Failed to execute task type subtasks.BackupTable UUID 37f3b896-01ae-4cdf-8c30-af10bb424c68 details {"nodeExporterUser":"prometheus","universeUUID":"7f0eb94c-1d83-49cc-b583-e2b0cb86d18e","encryptionAtRestConfig":{"encryptionAtRestEnabled":false,"opType":"UNDEFINED","type":"DATA_KEY"},"communicationPorts":{"masterHttpPort":7000,"masterRpcPort":7100,"tserverHttpPort":9000,"tserverRpcPort":9100,"redisServerHttpPort":11000,"redisServerRpcPort":6379,"yqlServerHttpPort":12000,"yqlServerRpcPort":9042,"ysqlServerHttpPort":13000,"ysqlServerRpcPort":5433,"nodeExporterPort":9300},"extraDependencies":{"installNodeExporter":true},"firstTry":true,"keyspace":"backup_test_restore","sse":false,"storageConfigUUID":"a83cbb6f-b96a-4585-9e57-3166e890a97e","storageLocation":"s3://mjeske-backup-1/univ-7f0eb94c-1d83-49cc-b583-e2b0cb86d18e/backup-2021-12-28T16:36:02-1849327189/keyspace-backup_test","actionType":"RESTORE","schedulingFrequency":0,"minNumBackupsToRetain":3,"timeBeforeDelete":0,"enableVerboseLogs":false,"transactionalBackup":false,"parallelism":8,"customerUuid":"e5af1595-c53a-483e-adb8-f7db11cc5ef4","ignoreErrors":false,"targetXClusterConfigs":[],"sourceXClusterConfigs":[]}, hit error.
java.lang.RuntimeException: java.lang.RuntimeException: {"error": "Backup exception: Tablets for table 00004541000030008000000000004543 not found on tablet server 172.161.49.219"}
at com.yugabyte.yw.commissioner.tasks.subtasks.BackupTable.run(BackupTable.java:107)
at com.yugabyte.yw.commissioner.TaskExecutor$AbstractRunnableTask.run(TaskExecutor.java:681)
at com.yugabyte.yw.commissioner.TaskExecutor$RunnableSubTask.run(TaskExecutor.java:971)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at com.yugabyte.yw.common.logging.MDCAwareRunnable.run(MDCAwareRunnable.java:42)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: {"error": "Backup exception: Tablets for table 00004541000030008000000000004543 not found on tablet server 172.161.49.219"}
at com.yugabyte.yw.commissioner.tasks.subtasks.BackupTable.run(BackupTable.java:94)
... 8 common frames omitted

**Comment by OlegLoginov** [comment]
Reproducible cases - backup-restore for:
- a geo-partitioned table
- the table if number of tablets < number of TSes
