### ISSUE TITLE
[yugabyted] Stay connected to ycqlsh/ysqlsh on ctrl+c

### ISSUE THREAD

**Issue by jaki** [yugabyte/yugabyte-db#11032]
Jira Link: [DB-4645](https://yugabyte.atlassian.net/browse/DB-4645)
On centos7 latest master (and also a month ago), ctrl+c during ysqlsh or ycqlsh started using `yugabyted connect` causes the connection to shutdown rather than to abort the current ysqlsh/ycqlsh prompt and stay connected.  This is unexpected and hurts usability.

```
bin/yugabyted connect ysql
ysqlsh (11.2-YB-2.11.2.0-b0)
Type "help" for help.

yugabyte=# select 1;
 ?column?
----------
        1
(1 row)

yugabyte=#
yugabyte=# Traceback (most recent call last):
  File "bin/yugabyted", line 2751, in <module>
    ControlScript().run()
  File "bin/yugabyted", line 1468, in run
    args.func()
  File "bin/yugabyted", line 303, in connect_ysql
    ysql_proxy.connect()
  File "bin/yugabyted", line 2037, in connect
    shell.communicate()
  File "/usr/share/python-2.7.17/lib/python2.7/subprocess.py", line 480, in communicate
    self.wait()
  File "/usr/share/python-2.7.17/lib/python2.7/subprocess.py", line 1099, in wait
    pid, sts = _eintr_retry_call(os.waitpid, self.pid, 0)
  File "/usr/share/python-2.7.17/lib/python2.7/subprocess.py", line 125, in _eintr_retry_call
    return func(*args)
KeyboardInterrupt
```

```
bin/yugabyted connect ycql
Warning: Timezone defined and 'pytz' module for timezone conversion not installed. Timestamps will be displayed in UTC timezone.

Connected to local cluster at 127.0.0.111:9042.
[ycqlsh 5.0.1 | Cassandra 3.9-SNAPSHOT | CQL spec 3.4.2 | Native protocol v4]
Use HELP for help.
ycqlsh>
ycqlsh> Traceback (most recent call last):
  File "bin/yugabyted", line 2751, in <module>
    ControlScript().run()
  File "bin/yugabyted", line 1468, in run
    args.func()
  File "bin/yugabyted", line 312, in connect_ycql
    ycql_proxy.connect()
  File "bin/yugabyted", line 2130, in connect
    shell.communicate()
  File "/usr/share/python-2.7.17/lib/python2.7/subprocess.py", line 480, in communicate
    self.wait()
  File "/usr/share/python-2.7.17/lib/python2.7/subprocess.py", line 1099, in wait
    pid, sts = _eintr_retry_call(os.waitpid, self.pid, 0)
  File "/usr/share/python-2.7.17/lib/python2.7/subprocess.py", line 125, in _eintr_retry_call
    return func(*args)
KeyboardInterrupt
```

**Comment by jaki** [comment]
Possibly related to issue #3676.

**Comment by gargsans-yb** [comment]
Code Fix Landed.
