### ISSUE TITLE
[SQLancer][YSQL] "Infinite loop detected at" occurred on select statement against colocated database if MONEY PK used

### ISSUE THREAD

**Issue by qvad** [yugabyte/yugabyte-db#11293]
Jira Link: [DB-822](https://yugabyte.atlassian.net/browse/DB-822)
### Description

Faced this issue in SQLancer with 16 thread. Can't reproduce it in single thread, so it might be related to concurrent workload.

```
--java.lang.AssertionError: SELECT ALL t4.c0 FROM t5*, t2 RIGHT OUTER JOIN t4 ON ((((((((t4.c1)*(t4.c1)))*(((t4.c1)*(t4.c1)))))-(((((t4.c1)-(t4.c1)))*(t4.c1)))))<<(((((((t4.c1)*(t4.c1)))*(((t4.c1)*(t4.c1)))))*(t4.c1)))) WHERE (0.58166557469060986562681137002073228359222412109375) BETWEEN SYMMETRIC (t2.c0) AND (0.78082748010430413909688240892137400805950164794921875);
--	at sqlancer.common.query.SQLQueryAdapter.checkException(SQLQueryAdapter.java:100)
--	at sqlancer.common.query.SQLQueryAdapter.executeAndGet(SQLQueryAdapter.java:131)
--	at sqlancer.ComparatorHelper.getResultSetFirstColumnAsString(ComparatorHelper.java:54)
--	at sqlancer.ComparatorHelper.getCombinedResultSet(ComparatorHelper.java:128)
--	at sqlancer.yugabyte.oracle.tlp.YugabyteTLPWhereOracle.whereCheck(YugabyteTLPWhereOracle.java:40)
--	at sqlancer.yugabyte.oracle.tlp.YugabyteTLPWhereOracle.check(YugabyteTLPWhereOracle.java:22)
--	at sqlancer.common.oracle.CompositeTestOracle.check(CompositeTestOracle.java:21)
--	at sqlancer.ProviderAdapter.generateAndTestDatabase(ProviderAdapter.java:49)
--	at sqlancer.Main$DBMSExecutor.run(Main.java:328)
--	at sqlancer.Main$2.run(Main.java:512)
--	at sqlancer.Main$2.runThread(Main.java:490)
--	at sqlancer.Main$2.run(Main.java:480)
--	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
--	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
--	at java.base/java.lang.Thread.run(Thread.java:834)
--Caused by: org.postgresql.util.PSQLException: ERROR: Query error: Infinite loop detected at "0\x00\x00D\x16!"
--	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2674)
--	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2364)
--	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:354)
--	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:484)
--	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:404)
--	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:325)
--	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:311)
--	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:287)
--	at org.postgresql.jdbc.PgStatement.executeQuery(PgStatement.java:239)
--	at sqlancer.common.query.SQLQueryAdapter.executeAndGet(SQLQueryAdapter.java:121)
--	... 13 more
---- Time: 2022/01/30 22:49:24
-- Database: database18
-- Database version: 11.2-YB-2.11.3.0-b0
-- seed value: 1643576894609
\c yugabyte;
```

[partial-reproducer.txt](https://github.com/yugabyte/yugabyte-db/files/7973389/partial-reproducer.txt)

**Comment by qvad** [comment]
@m-iancu  It's related to colocated database, no concurrent workload involved here.
Simplified case
```
CREATE TABLE IF NOT EXISTS t1(c0 boolean);
CREATE TABLE IF NOT EXISTS t2(c0 money  NOT NULL UNIQUE);
INSERT INTO t1(c0) VALUES (true), (FALSE);
TRUNCATE t2; --, t3;
SELECT SUM(count) FROM (SELECT ALL (t1.c0)::INT as count FROM ONLY t2 RIGHT OUTER JOIN ONLY t1 ON ((t2.c0)<(CAST(0.27233025 AS MONEY)))) as res;
```
