### ISSUE TITLE
[YSQL][Postgis] Segmentation fault in isvaliddetail()

### ISSUE THREAD

**Issue by def-** [yugabyte/yugabyte-db#11318]
### Description

See https://docs.yugabyte.com/latest/api/ysql/extensions/#postgis for Postgis installation instructions.

Can be reproduced against yugabyte-2.11.2.0 on CentOS using https://github.com/def-/postgis/tree/stable-3.1/regress by running `PATH=/nfusr/dev-server/dfelsing/code/postgis/regress/bin/:$PATH ./run_test.pl core/validdetail.sql`

tserver log:
```
2022-02-01 09:15:08.827 UTC [4020] LOG:  server process (PID 3841) was terminated by signal 11: Segmentation fault
2022-02-01 09:15:08.827 UTC [4020] DETAIL:  Failed process was running: select 1, valid, reason, st_astext
(location) FROM (
          SELECT (ST_IsValidDetail('LINESTRING (70 250, 190 340)')).*
        ) foo;
```
backtrace from gdb:
```
Core was generated by `postgres: yugabyte postgis_reg 127.0.0.1(48556) SELECT                        '.
Program terminated with signal 11, Segmentation fault.
#0  __memcpy_avx_unaligned () at ../sysdeps/x86_64/multiarch/memcpy-avx-unaligned.S:126
126	../sysdeps/x86_64/multiarch/memcpy-avx-unaligned.S: No such file or directory.
(gdb) bt
#0  __memcpy_avx_unaligned () at ../sysdeps/x86_64/multiarch/memcpy-avx-unaligned.S:126
#1  0x00007fa9576b7cea in isvaliddetail () from /nfusr/dev-server/dfelsing/yugabyte-2.11.2.0/postgres/lib/postgis-3.so
#2  0x00000000006c9ba1 in ExecInterpExpr (state=0x38f4328, econtext=0x38f48f8, isnull=<optimized out>) at ../../../../../../src/postgres/src/backend/executor/execExprInterp.c:703
#3  0x00000000007b28ea in ExecEvalExprSwitchContext (isNull=0x7ffc0fa7591c, econtext=<optimized out>, state=0x38f4328) at ../../../../../../../src/postgres/src/include/executor/executor.h:321
#4  evaluate_expr (expr=<optimized out>, result_type=result_type@entry=330140, result_typmod=result_typmod@entry=-1, result_collation=result_collation@entry=0)
    at ../../../../../../../src/postgres/src/backend/optimizer/util/clauses.c:4970
#5  0x00000000007b60af in evaluate_function (context=0x7ffc0fa75c80, func_tuple=0x383f980, funcvariadic=false, args=0x38ed8f8, input_collid=0, result_collid=0, result_typmod=-1, result_type=330140, funcid=330141)
    at ../../../../../../../src/postgres/src/backend/optimizer/util/clauses.c:4512
#6  simplify_function (funcid=330141, result_type=330140, result_typmod=-1, result_collid=result_collid@entry=0, input_collid=input_collid@entry=0, args_p=args_p@entry=0x7ffc0fa75a90, funcvariadic=false,
    process_args=true, allow_non_const=true, context=0x7ffc0fa75c80) at ../../../../../../../src/postgres/src/backend/optimizer/util/clauses.c:4152
#7  0x00000000007b4a72 in eval_const_expressions_mutator (node=0x38ed098, context=0x7ffc0fa75c80) at ../../../../../../../src/postgres/src/backend/optimizer/util/clauses.c:2742
#8  0x00000000007b5251 in eval_const_expressions_mutator (node=0x38ed068, context=0x7ffc0fa75c80) at ../../../../../../../src/postgres/src/backend/optimizer/util/clauses.c:3522
#9  0x0000000000737b1f in expression_tree_mutator (node=node@entry=0x38ed018, mutator=mutator@entry=0x7b47f0 <eval_const_expressions_mutator>, context=context@entry=0x7ffc0fa75c80)
    at ../../../../../../src/postgres/src/backend/nodes/nodeFuncs.c:3449
#10 0x00000000007b4842 in eval_const_expressions_mutator (node=0x38ed018, context=0x7ffc0fa75c80) at ../../../../../../../src/postgres/src/backend/optimizer/util/clauses.c:3759
#11 0x0000000000737dab in expression_tree_mutator (node=node@entry=0x38ecfe8, mutator=mutator@entry=0x7b47f0 <eval_const_expressions_mutator>, context=context@entry=0x7ffc0fa75c80)
    at ../../../../../../src/postgres/src/backend/nodes/nodeFuncs.c:3319
#12 0x00000000007b822b in eval_const_expressions_mutator (context=0x7ffc0fa75c80, node=0x38ecfe8) at ../../../../../../../src/postgres/src/backend/optimizer/util/clauses.c:3759
#13 eval_const_expressions (root=root@entry=0x389db78, node=0x38ecfe8) at ../../../../../../../src/postgres/src/backend/optimizer/util/clauses.c:2534
#14 0x000000000079c625 in preprocess_expression (kind=1, expr=<optimized out>, root=0x389db78) at ../../../../../../../src/postgres/src/backend/optimizer/plan/planner.c:1041
#15 subquery_planner (glob=glob@entry=0x389a748, parse=parse@entry=0x3886a10, parent_root=parent_root@entry=0x0, hasRecursion=hasRecursion@entry=false, tuple_fraction=tuple_fraction@entry=0)
    at ../../../../../../../src/postgres/src/backend/optimizer/plan/planner.c:732
#16 0x000000000079df25 in standard_planner (parse=0x3886a10, cursorOptions=256, boundParams=<optimized out>) at ../../../../../../../src/postgres/src/backend/optimizer/plan/planner.c:405
#17 0x00007fa965c33ead in pg_hint_plan_planner (parse=0x3886a10, cursorOptions=256, boundParams=0x0) at ../../../../../src/postgres/third-party-extensions/pg_hint_plan/pg_hint_plan.c:3221
#18 0x0000000000880324 in pg_plan_query (querytree=querytree@entry=0x3886a10, cursorOptions=cursorOptions@entry=256, boundParams=boundParams@entry=0x0)
    at ../../../../../../src/postgres/src/backend/tcop/postgres.c:848
#19 0x0000000000880467 in pg_plan_queries (querytrees=<optimized out>, cursorOptions=cursorOptions@entry=256, boundParams=boundParams@entry=0x0) at ../../../../../../src/postgres/src/backend/tcop/postgres.c:914
#20 0x00000000008849e0 in exec_simple_query (query_string=0x358a118 "select 1, valid, reason, st_astext(location) FROM (\n  SELECT (ST_IsValidDetail('LINESTRING (70 250, 190 340)')).*\n) foo;",
    query_string@entry=0x7ffc0fa76080 "Pa\247\017\374\177") at ../../../../../../src/postgres/src/backend/tcop/postgres.c:1089
#21 yb_exec_simple_query_impl (query_string=query_string@entry=0x358a118) at ../../../../../../src/postgres/src/backend/tcop/postgres.c:4434
#22 0x000000000087f8b8 in yb_exec_query_wrapper (exec_context=exec_context@entry=0x358a000, restart_data=restart_data@entry=0x7ffc0fa762b0, functor=functor@entry=0x884620 <yb_exec_simple_query_impl>,
    functor_context=functor_context@entry=0x358a118) at ../../../../../../src/postgres/src/backend/tcop/postgres.c:4419
#23 0x00000000008802ec in yb_exec_simple_query (
    query_string=query_string@entry=0x358a118 "select 1, valid, reason, st_astext(location) FROM (\n  SELECT (ST_IsValidDetail('LINESTRING (70 250, 190 340)')).*\n) foo;",
    exec_context=exec_context@entry=0x358a000) at ../../../../../../src/postgres/src/backend/tcop/postgres.c:4449
#24 0x0000000000882213 in PostgresMain (argc=<optimized out>, argv=argv@entry=0x35cbbd8, dbname=0x35cbab8 "postgis_reg", username=0x3585fe8 "yugabyte")
    at ../../../../../../src/postgres/src/backend/tcop/postgres.c:5084
#25 0x000000000049e292 in BackendRun (port=0x3474960) at ../../../../../../src/postgres/src/backend/postmaster/postmaster.c:4470
#26 BackendStartup (port=0x3474960) at ../../../../../../src/postgres/src/backend/postmaster/postmaster.c:4136
#27 ServerLoop () at ../../../../../../src/postgres/src/backend/postmaster/postmaster.c:1754
#28 0x00000000007ea21f in PostmasterMain (argc=argc@entry=23, argv=argv@entry=0x334e000) at ../../../../../../src/postgres/src/backend/postmaster/postmaster.c:1417
#29 0x000000000073588a in PostgresServerProcessMain (argc=23, argv=0x334e000) at ../../../../../../src/postgres/src/backend/main/main.c:234
#30 0x0000000000735a89 in main ()
```

Same failure with core/core.sql. Coredump: [core.3841.zip](https://github.com/yugabyte/yugabyte-db/files/7987459/core.3841.zip)

**Comment by andrei-mart** [comment]
I can not reproduce this.
The https://github.com/def-/postgis/tree/stable-3.1/regress has harcoded paths not existing on my platform.
The quoted query works for me:
```
yugabyte=# select 1, valid, reason, st_astext
yugabyte-# (location) FROM (
yugabyte(#           SELECT (ST_IsValidDetail('LINESTRING (70 250, 190 340)')).*
yugabyte(#         ) foo;
 ?column? | valid | reason | st_astext 
----------+-------+--------+-----------
        1 | t     |        | 
(1 row)
``` 
Until we can reproduce it, it should be considered a documentation issue.
We need better document how to properly install postgis.

**Comment by def-** [comment]
Thanks, I have removed some hardcoded paths, have to specify $PATH and $POSTGIS_SCRIPTDIR now instead.

I have previously installed postgis on CentOS as described in https://docs.yugabyte.com/latest/api/ysql/extensions/#postgis

Tested again against current 2.11.2.0-b89 build, can still reproduce:
```
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
$ sudo yum install postgresql11-server postgis31_11 postgis31_11-client
$ cd
$ wget https://downloads.yugabyte.com/releases/2.11.2.0/yugabyte-2.11.2.0-b89-linux-x86_64.tar.gz
$ tar xvfz yugabyte-2.11.2.0-b89-linux-x86_64.tar.gz && cd yugabyte-2.11.2.0/
$ cd postgres/lib && cp -v "$(/usr/pgsql-11/bin/pg_config --pkglibdir)"/*postgis*.so . && cp -v "$(/usr/pgsql-11/bin/pg_config --sharedir)"/extension/*postgis*.sql ../share/extension/ && cp -v "$(/usr/pgsql-11/bin/pg_config --sharedir)"/extension/*postgis*.control ../share/extension/ && cd ../..
$ bin/post_install.sh -e
post_install.sh was already run (marker at /nfusr/dev-server/dfelsing/yugabyte-2.11.2.0/.post_install.sh.completed)
Installing postgis extension.
$ bin/yugabyted start
Starting yugabyted...
✅ System checks

+--------------------------------------------------------------------------------------------------+
|                                            yugabyted                                             |
+--------------------------------------------------------------------------------------------------+
| Status              : Running. Leader Master is present                                          |
| Web console         : http://127.0.0.1:7000                                                      |
| JDBC                : jdbc:postgresql://127.0.0.1:5433/yugabyte?user=yugabyte&password=yugabyte  |
| YSQL                : bin/ysqlsh   -U yugabyte -d yugabyte                                       |
| YCQL                : bin/ycqlsh   -u cassandra                                                  |
| Data Dir            : /nfusr/dev-server/dfelsing/var/data                                        |
| Log Dir             : /nfusr/dev-server/dfelsing/var/logs                                        |
| Universe UUID       : 3f38ad49-c497-492f-8162-904e71b59d7c                                       |
+--------------------------------------------------------------------------------------------------+
🚀 yugabyted started successfully! To load a sample dataset, try 'yugabyted demo'.
🎉 Join us on Slack at https://www.yugabyte.com/slack
👕 Claim your free t-shirt at https://www.yugabyte.com/community-rewards/
$ bin/ysqlsh -c "CREATE EXTENSION postgis;"
WARNING:  'analyze' is a beta feature!
HINT:  Set 'ysql_beta_features' yb-tserver gflag to true to suppress the warning for all beta features.
CREATE EXTENSION
$ cd ~/code/postgis/regress
$ git checkout stable-3.1
$ PATH=$PWD/bin:/usr/pgsql-11/bin:$PATH POSTGIS_SCRIPTDIR=/usr/pgsql-11/share/contrib/postgis-3.1 ./run_test.pl core/isvaliddetail.sql
PATH is /nfusr/dev-server/dfelsing/code/postgis/regress/bin:/usr/pgsql-11/bin:/nfusr/dev-server/dfelsing/perl5/bin:/nfusr/dev-server/dfelsing/tools/bin:/nfusr/dev-server/dfelsing/tools/google-cloud-sdk/bin:/nfusr/dev-server/dfelsing/.local/bin:/nfusr/dev-server/dfelsing/tools/arcanist/bin:/usr/local/bin:/usr/lib64/ccache:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin
Checking for shp2pgsql ... found
Checking for pgsql2shp ... found
TMPDIR is /tmp/pgis_reg
Creating database 'postgis_reg'
Loading unpackaged components from /usr/pgsql-11/share/contrib/postgis-3.1
Loading PostGIS into 'postgis_reg'
PostgreSQL 11.2-YB-2.11.2.0-b0 on x86_64-pc-linux-gnu, compiled by gcc (Homebrew gcc 5.5.0_4) 5.5.0, 64-bit
  Postgis 3.1.5dev - (3.1.4-29-gc929e566d) - 2022-02-02 15:52:24
  scripts 3.1.5dev 3.1.4-29-gc929e566d
  GEOS: 3.9.2-CAPI-1.14.3
  PROJ: 7.2.1

Running tests

 core/isvaliddetail .. failed (diff expected obtained: /tmp/pgis_reg/test_1_diff)
 failed (PostGIS object count pre-test (ysqlsh: could not connect to server: Connection refused
	Is the server running on host "localhost" (::1) and accepting
	TCP/IP connections on port 5433?
FATAL:  the database system is in recovery mode) != post-test (8500))
 uninstall .
Run tests: 2
Failed: 2
$ ls -lha ~/var/data/core*
-rw------- 1 dfelsing ybdev 254M Feb 17 10:25 /nfusr/dev-server/dfelsing/var/data/pg_data/core.20772
$ file !$
/nfusr/dev-server/dfelsing/var/data/pg_data/core.20772: ELF 64-bit LSB core file x86-64, version 1 (SYSV), SVR4-style, from 'postgres: yugabyte postgis_reg 127.0.0.1(38636) SELECT', real uid: 2200, effective uid: 2200, real gid: 1500, effective gid: 1500, execfn: '/nfusr/dev-server/dfelsing/yugabyte-2.11.2.0/postgres/bin/postgres', platform: 'x86_64'
$ gdb /nfusr/dev-server/dfelsing/yugabyte-2.11.2.0/postgres/bin/postgres !$
Core was generated by `postgres: yugabyte postgis_reg 127.0.0.1(38636) SELECT                        '.
Program terminated with signal 11, Segmentation fault.
#0  __memcpy_avx_unaligned () at ../sysdeps/x86_64/multiarch/memcpy-avx-unaligned.S:126
126	../sysdeps/x86_64/multiarch/memcpy-avx-unaligned.S: No such file or directory.
(gdb) bt
#0  __memcpy_avx_unaligned () at ../sysdeps/x86_64/multiarch/memcpy-avx-unaligned.S:126
#1  0x00007fb99532c56a in memcpy (__len=<optimized out>, __src=<optimized out>, __dest=0x3250748) at /usr/include/bits/string3.h:51
#2  isvaliddetail (fcinfo=<optimized out>) at lwgeom_geos.c:1745
#3  0x00000000006c9ba1 in ExecInterpExpr (state=0x324e328, econtext=0x324e8f8, isnull=<optimized out>) at ../../../../../../src/postgres/src/backend/executor/execExprInterp.c:703
#4  0x00000000007b28ea in ExecEvalExprSwitchContext (isNull=0x7ffc6136ae2c, econtext=<optimized out>, state=0x324e328) at ../../../../../../../src/postgres/src/include/executor/executor.h:321
#5  evaluate_expr (expr=<optimized out>, result_type=result_type@entry=17799, result_typmod=result_typmod@entry=-1, result_collation=result_collation@entry=0)
    at ../../../../../../../src/postgres/src/backend/optimizer/util/clauses.c:4970
#6  0x00000000007b60af in evaluate_function (context=0x7ffc6136b190, func_tuple=0x3197980, funcvariadic=false, args=0x32478f8, input_collid=0, result_collid=0, result_typmod=-1, result_type=17799, funcid=17800)
    at ../../../../../../../src/postgres/src/backend/optimizer/util/clauses.c:4512
#7  simplify_function (funcid=17800, result_type=17799, result_typmod=-1, result_collid=result_collid@entry=0, input_collid=input_collid@entry=0, args_p=args_p@entry=0x7ffc6136afa0, funcvariadic=false,
    process_args=true, allow_non_const=true, context=0x7ffc6136b190) at ../../../../../../../src/postgres/src/backend/optimizer/util/clauses.c:4152
#8  0x00000000007b4a72 in eval_const_expressions_mutator (node=0x3247098, context=0x7ffc6136b190) at ../../../../../../../src/postgres/src/backend/optimizer/util/clauses.c:2742
#9  0x00000000007b5251 in eval_const_expressions_mutator (node=0x3247068, context=0x7ffc6136b190) at ../../../../../../../src/postgres/src/backend/optimizer/util/clauses.c:3522
#10 0x0000000000737b1f in expression_tree_mutator (node=node@entry=0x3247018, mutator=mutator@entry=0x7b47f0 <eval_const_expressions_mutator>, context=context@entry=0x7ffc6136b190)
    at ../../../../../../src/postgres/src/backend/nodes/nodeFuncs.c:3449
#11 0x00000000007b4842 in eval_const_expressions_mutator (node=0x3247018, context=0x7ffc6136b190) at ../../../../../../../src/postgres/src/backend/optimizer/util/clauses.c:3759
#12 0x0000000000737dab in expression_tree_mutator (node=node@entry=0x3246fe8, mutator=mutator@entry=0x7b47f0 <eval_const_expressions_mutator>, context=context@entry=0x7ffc6136b190)
    at ../../../../../../src/postgres/src/backend/nodes/nodeFuncs.c:3319
#13 0x00000000007b822b in eval_const_expressions_mutator (context=0x7ffc6136b190, node=0x3246fe8) at ../../../../../../../src/postgres/src/backend/optimizer/util/clauses.c:3759
#14 eval_const_expressions (root=root@entry=0x31f9b78, node=0x3246fe8) at ../../../../../../../src/postgres/src/backend/optimizer/util/clauses.c:2534
#15 0x000000000079c625 in preprocess_expression (kind=1, expr=<optimized out>, root=0x31f9b78) at ../../../../../../../src/postgres/src/backend/optimizer/plan/planner.c:1041
#16 subquery_planner (glob=glob@entry=0x31f6748, parse=parse@entry=0x31e0a10, parent_root=parent_root@entry=0x0, hasRecursion=hasRecursion@entry=false, tuple_fraction=tuple_fraction@entry=0)
    at ../../../../../../../src/postgres/src/backend/optimizer/plan/planner.c:732
#17 0x000000000079df25 in standard_planner (parse=0x31e0a10, cursorOptions=256, boundParams=<optimized out>) at ../../../../../../../src/postgres/src/backend/optimizer/plan/planner.c:405
#18 0x00007fb9a38f7ead in pg_hint_plan_planner (parse=0x31e0a10, cursorOptions=256, boundParams=0x0) at ../../../../../src/postgres/third-party-extensions/pg_hint_plan/pg_hint_plan.c:3221
#19 0x0000000000880324 in pg_plan_query (querytree=querytree@entry=0x31e0a10, cursorOptions=cursorOptions@entry=256, boundParams=boundParams@entry=0x0)
    at ../../../../../../src/postgres/src/backend/tcop/postgres.c:848
#20 0x0000000000880467 in pg_plan_queries (querytrees=<optimized out>, cursorOptions=cursorOptions@entry=256, boundParams=boundParams@entry=0x0) at ../../../../../../src/postgres/src/backend/tcop/postgres.c:914
#21 0x00000000008849e0 in exec_simple_query (query_string=0x2f00118 "select 1, valid, reason, st_astext(location) FROM (\n  SELECT (ST_IsValidDetail('LINESTRING (70 250, 190 340)')).*\n) foo;",
    query_string@entry=0x7ffc6136b590 "`\266\066a\374\177") at ../../../../../../src/postgres/src/backend/tcop/postgres.c:1089
#22 yb_exec_simple_query_impl (query_string=query_string@entry=0x2f00118) at ../../../../../../src/postgres/src/backend/tcop/postgres.c:4434
#23 0x000000000087f8b8 in yb_exec_query_wrapper (exec_context=exec_context@entry=0x2f00000, restart_data=restart_data@entry=0x7ffc6136b7c0, functor=functor@entry=0x884620 <yb_exec_simple_query_impl>,
    functor_context=functor_context@entry=0x2f00118) at ../../../../../../src/postgres/src/backend/tcop/postgres.c:4419
#24 0x00000000008802ec in yb_exec_simple_query (
    query_string=query_string@entry=0x2f00118 "select 1, valid, reason, st_astext(location) FROM (\n  SELECT (ST_IsValidDetail('LINESTRING (70 250, 190 340)')).*\n) foo;",
    exec_context=exec_context@entry=0x2f00000) at ../../../../../../src/postgres/src/backend/tcop/postgres.c:4449
#25 0x0000000000882213 in PostgresMain (argc=<optimized out>, argv=argv@entry=0x2efb500, dbname=0x2efb398 "postgis_reg", username=0x2efb378 "yugabyte")
    at ../../../../../../src/postgres/src/backend/tcop/postgres.c:5084
#26 0x000000000049e292 in BackendRun (port=0x2dea960) at ../../../../../../src/postgres/src/backend/postmaster/postmaster.c:4470
#27 BackendStartup (port=0x2dea960) at ../../../../../../src/postgres/src/backend/postmaster/postmaster.c:4136
#28 ServerLoop () at ../../../../../../src/postgres/src/backend/postmaster/postmaster.c:1754
#29 0x00000000007ea21f in PostmasterMain (argc=argc@entry=23, argv=argv@entry=0x2cc4000) at ../../../../../../src/postgres/src/backend/postmaster/postmaster.c:1417
#30 0x000000000073588a in PostgresServerProcessMain (argc=23, argv=0x2cc4000) at ../../../../../../src/postgres/src/backend/main/main.c:234
#31 0x0000000000735a89 in main ()
```

**Comment by andrei-mart** [comment]
Your Yugabyte and PostGIS binaries are incompatible.
Best way to ensure compatibility is to build them from the sources.
Build from the sources is not simple, there are issues to workaround, both in Yugabyte and PostGIS.
Probably we should take down the docs on binary install, they mislead people.

**Comment by def-** [comment]
I see. Do you have instructions for how to build them with the workarounds?
