### ISSUE TITLE
[YSQL][Postgis] Segmentation fault in LWGEOM_dumppoints()

### ISSUE THREAD

**Issue by def-** [yugabyte/yugabyte-db#11319]
### Description

See https://docs.yugabyte.com/latest/api/ysql/extensions/#postgis for Postgis installation instructions.

Can be reproduced against yugabyte-2.11.2.0 on CentOS using https://github.com/def-/postgis/tree/stable-3.1/regress by running `PATH=$CWD/bin/:$PATH ./run_test.pl core/computed_columns.sql`

tserver log:
```
2022-02-01 09:09:50.727 UTC [4020] LOG:  server process (PID 2350) was terminated by signal 11: Segmentation fault
2022-02-01 09:09:50.727 UTC [4020] DETAIL:  Failed process was running: CREATE TABLE testc.streets AS
        WITH d AS (SELECT dp.geom FROM testc.city_boundary AS c, ST_DumpPoints(c.geom) AS dp)
        SELECT ROW_NUMBER() OVER() AS id, ST_MakeLine(d1.geom, d2.geom) AS geom
        FROM d AS d1, d AS d2
        ORDER BY d1.geom <-> d2.geom DESC LIMIT 1000;
```
backtrace from gdb:
```
#0  HeapTupleHeaderGetDatum (tuple=0x0) at ../../../../../../src/postgres/src/backend/executor/execTuples.c:1385
#1  0x00007fa956c8ba80 in LWGEOM_dumppoints () from /nfusr/dev-server/dfelsing/yugabyte-2.11.2.0/postgres/lib/postgis-3.so
#2  0x00000000006da32c in ExecMakeTableFunctionResult (setexpr=0x3a96ef8, econtext=0x3a96df8, argContext=<optimized out>, expectedDesc=0x3a97e88, randomAccess=false)
    at ../../../../../../src/postgres/src/backend/executor/execSRF.c:231
#3  0x00000000006e9a60 in FunctionNext (node=node@entry=0x3a96ce8) at ../../../../../../src/postgres/src/backend/executor/nodeFunctionscan.c:94
#4  0x00000000006d95d1 in ExecScanFetch (recheckMtd=0x6e9770 <FunctionRecheck>, accessMtd=0x6e97a0 <FunctionNext>, node=0x3a96ce8) at ../../../../../../src/postgres/src/backend/executor/execScan.c:95
#5  ExecScan (node=0x3a96ce8, accessMtd=0x6e97a0 <FunctionNext>, recheckMtd=0x6e9770 <FunctionRecheck>) at ../../../../../../src/postgres/src/backend/executor/execScan.c:145
#6  0x00000000006fd1de in ExecProcNode (node=0x3a96ce8) at ../../../../../../src/postgres/src/include/executor/executor.h:249
#7  ExecNestLoop (pstate=0x3a96378) at ../../../../../../src/postgres/src/backend/executor/nodeNestloop.c:160
#8  0x0000000000700b95 in ExecProcNode (node=0x3a96378) at ../../../../../../src/postgres/src/include/executor/executor.h:249
#9  CteScanNext (node=node@entry=0x3acf4f8) at ../../../../../../src/postgres/src/backend/executor/nodeCtescan.c:103
#10 0x00000000006d95d1 in ExecScanFetch (recheckMtd=0x700a80 <CteScanRecheck>, accessMtd=0x700ab0 <CteScanNext>, node=0x3acf4f8) at ../../../../../../src/postgres/src/backend/executor/execScan.c:95
#11 ExecScan (node=0x3acf4f8, accessMtd=0x700ab0 <CteScanNext>, recheckMtd=0x700a80 <CteScanRecheck>) at ../../../../../../src/postgres/src/backend/executor/execScan.c:145
#12 0x00000000006fd12d in ExecProcNode (node=0x3acf4f8) at ../../../../../../src/postgres/src/include/executor/executor.h:249
#13 ExecNestLoop (pstate=0x3acf338) at ../../../../../../src/postgres/src/backend/executor/nodeNestloop.c:109
#14 0x0000000000704f65 in ExecProcNode (node=0x3acf338) at ../../../../../../src/postgres/src/include/executor/executor.h:249
#15 begin_partition (winstate=winstate@entry=0x3acedc8) at ../../../../../../src/postgres/src/backend/executor/nodeWindowAgg.c:1111
#16 0x000000000070a30b in ExecWindowAgg (pstate=0x3acedc8) at ../../../../../../src/postgres/src/backend/executor/nodeWindowAgg.c:2104
#17 0x00000000006fff56 in ExecProcNode (node=0x3acedc8) at ../../../../../../src/postgres/src/include/executor/executor.h:249
#18 ExecSort (pstate=0x3acecb8) at ../../../../../../src/postgres/src/backend/executor/nodeSort.c:116
#19 0x00000000006f3eb0 in ExecProcNode (node=0x3acecb8) at ../../../../../../src/postgres/src/include/executor/executor.h:249
#20 ExecLimit (pstate=0x3aceb88) at ../../../../../../src/postgres/src/backend/executor/nodeLimit.c:113
#21 0x00000000006ce5db in ExecProcNode (node=0x3aceb88) at ../../../../../../src/postgres/src/include/executor/executor.h:249
#22 ExecutePlan (execute_once=<optimized out>, dest=0x335f228, direction=<optimized out>, numberTuples=0, sendTuples=<optimized out>, operation=CMD_SELECT, use_parallel_mode=<optimized out>, planstate=0x3aceb88,
    estate=0x3a96118) at ../../../../../../src/postgres/src/backend/executor/execMain.c:1730
#23 standard_ExecutorRun (queryDesc=0x3acbf50, direction=<optimized out>, count=0, execute_once=<optimized out>) at ../../../../../../src/postgres/src/backend/executor/execMain.c:367
#24 0x00007fa96624d8bd in pgss_ExecutorRun (queryDesc=0x3acbf50, direction=ForwardScanDirection, count=0, execute_once=<optimized out>)
    at ../../../../../src/postgres/contrib/pg_stat_statements/pg_stat_statements.c:947
#25 0x00007fa9660463aa in ybpgm_ExecutorRun (queryDesc=0x3acbf50, direction=ForwardScanDirection, count=0, execute_once=<optimized out>) at ../../../../../src/postgres/contrib/yb_pg_metrics/yb_pg_metrics.c:499
#26 0x000000000062a5a6 in ExecCreateTableAs (stmt=stmt@entry=0x3a64680,
    queryString=queryString@entry=0x358a118 "CREATE TABLE testc.streets AS\nWITH d AS (SELECT dp.geom FROM testc.city_boundary AS c, ST_DumpPoints(c.geom) AS dp)\nSELECT ROW_NUMBER() OVER() AS id, ST_MakeLine(d1.geom, d2.geom) AS geom\nFROM d AS d1"..., params=params@entry=0x0, queryEnv=queryEnv@entry=0x0, completionTag=completionTag@entry=0x7ffc0fa760e0 "")
    at ../../../../../../src/postgres/src/backend/commands/createas.c:359
#27 0x0000000000889fa5 in ProcessUtilitySlow (pstate=pstate@entry=0x335f118, pstmt=pstmt@entry=0x3a64730,
    queryString=queryString@entry=0x358a118 "CREATE TABLE testc.streets AS\nWITH d AS (SELECT dp.geom FROM testc.city_boundary AS c, ST_DumpPoints(c.geom) AS dp)\nSELECT ROW_NUMBER() OVER() AS id, ST_MakeLine(d1.geom, d2.geom) AS geom\nFROM d AS d1"..., context=context@entry=PROCESS_UTILITY_TOPLEVEL, params=params@entry=0x0, queryEnv=queryEnv@entry=0x0, completionTag=0x7ffc0fa760e0 "", dest=0x3a0e978)
    at ../../../../../../src/postgres/src/backend/tcop/utility.c:1575
#28 0x00000000008889f0 in standard_ProcessUtility (pstmt=pstmt@entry=0x3a64730,
    queryString=queryString@entry=0x358a118 "CREATE TABLE testc.streets AS\nWITH d AS (SELECT dp.geom FROM testc.city_boundary AS c, ST_DumpPoints(c.geom) AS dp)\nSELECT ROW_NUMBER() OVER() AS id, ST_MakeLine(d1.geom, d2.geom) AS geom\nFROM d AS d1"..., context=context@entry=PROCESS_UTILITY_TOPLEVEL, params=params@entry=0x0, queryEnv=queryEnv@entry=0x0, dest=dest@entry=0x3a0e978, completionTag=0x7ffc0fa760e0 "")
    at ../../../../../../src/postgres/src/backend/tcop/utility.c:970
#29 0x00000000008895fe in YBProcessUtilityDefaultHook (pstmt=<optimized out>,
    queryString=0x358a118 "CREATE TABLE testc.streets AS\nWITH d AS (SELECT dp.geom FROM testc.city_boundary AS c, ST_DumpPoints(c.geom) AS dp)\nSELECT ROW_NUMBER() OVER() AS id, ST_MakeLine(d1.geom, d2.geom) AS geom\nFROM d AS d1"..., context=PROCESS_UTILITY_TOPLEVEL, params=0x0, queryEnv=0x0, dest=<optimized out>, completionTag=0x7ffc0fa760e0 "") at ../../../../../../src/postgres/src/backend/tcop/utility.c:3594
#30 0x00007fa96625047c in pgss_ProcessUtility (pstmt=0x3a64730,
    queryString=0x358a118 "CREATE TABLE testc.streets AS\nWITH d AS (SELECT dp.geom FROM testc.city_boundary AS c, ST_DumpPoints(c.geom) AS dp)\nSELECT ROW_NUMBER() OVER() AS id, ST_MakeLine(d1.geom, d2.geom) AS geom\nFROM d AS d1"..., context=PROCESS_UTILITY_TOPLEVEL, params=0x0, queryEnv=0x0, dest=0x3a0e978, completionTag=0x7ffc0fa760e0 "")
    at ../../../../../src/postgres/contrib/pg_stat_statements/pg_stat_statements.c:1056
#31 0x00007fa9660474c2 in ybpgm_ProcessUtility (pstmt=0x3a64730,
    queryString=0x358a118 "CREATE TABLE testc.streets AS\nWITH d AS (SELECT dp.geom FROM testc.city_boundary AS c, ST_DumpPoints(c.geom) AS dp)\nSELECT ROW_NUMBER() OVER() AS id, ST_MakeLine(d1.geom, d2.geom) AS geom\nFROM d AS d1"..., context=PROCESS_UTILITY_TOPLEVEL, params=0x0, queryEnv=0x0, dest=0x3a0e978, completionTag=0x7ffc0fa760e0 "") at ../../../../../src/postgres/contrib/yb_pg_metrics/yb_pg_metrics.c:682
#32 0x00007fa965c29b59 in pg_hint_plan_ProcessUtility (pstmt=<optimized out>, queryString=<optimized out>, context=<optimized out>, params=<optimized out>, queryEnv=<optimized out>, dest=<optimized out>,
    completionTag=0x7ffc0fa760e0 "") at ../../../../../src/postgres/third-party-extensions/pg_hint_plan/pg_hint_plan.c:3033
#33 0x0000000000a38b3e in YBTxnDdlProcessUtility (pstmt=0x3a64730,
    queryString=0x358a118 "CREATE TABLE testc.streets AS\nWITH d AS (SELECT dp.geom FROM testc.city_boundary AS c, ST_DumpPoints(c.geom) AS dp)\nSELECT ROW_NUMBER() OVER() AS id, ST_MakeLine(d1.geom, d2.geom) AS geom\nFROM d AS d1"..., context=PROCESS_UTILITY_TOPLEVEL, params=0x0, queryEnv=0x0, dest=0x3a0e978, completionTag=0x7ffc0fa760e0 "") at ../../../../../../../src/postgres/src/backend/utils/misc/pg_yb_utils.c:1361
#34 0x000000000088580e in PortalRunUtility (portal=portal@entry=0x365e118, pstmt=pstmt@entry=0x3a64730, isTopLevel=isTopLevel@entry=true, setHoldSnapshot=setHoldSnapshot@entry=false, dest=<optimized out>,
    completionTag=<optimized out>) at ../../../../../../src/postgres/src/backend/tcop/pquery.c:1201
#35 0x0000000000885f5d in PortalRunMulti (portal=portal@entry=0x365e118, isTopLevel=isTopLevel@entry=true, setHoldSnapshot=setHoldSnapshot@entry=false, dest=dest@entry=0x3a0e978, altdest=altdest@entry=0x3a0e978,
    completionTag=completionTag@entry=0x7ffc0fa760e0 "") at ../../../../../../src/postgres/src/backend/tcop/pquery.c:1368
#36 0x0000000000886fd2 in PortalRun (portal=portal@entry=0x365e118, count=count@entry=9223372036854775807, isTopLevel=isTopLevel@entry=true, run_once=run_once@entry=true, dest=dest@entry=0x3a0e978,
    altdest=altdest@entry=0x3a0e978, completionTag=0x7ffc0fa760e0 "") at ../../../../../../src/postgres/src/backend/tcop/pquery.c:810
#37 0x0000000000884ad8 in exec_simple_query (
    query_string=0x358a118 "CREATE TABLE testc.streets AS\nWITH d AS (SELECT dp.geom FROM testc.city_boundary AS c, ST_DumpPoints(c.geom) AS dp)\nSELECT ROW_NUMBER() OVER() AS id, ST_MakeLine(d1.geom, d2.geom) AS geom\nFROM d AS d1"..., query_string@entry=0x7ffc0fa76060 "\030\341e\003") at ../../../../../../src/postgres/src/backend/tcop/postgres.c:1161
#38 yb_exec_simple_query_impl (query_string=query_string@entry=0x358a118) at ../../../../../../src/postgres/src/backend/tcop/postgres.c:4434
#39 0x000000000087f8b8 in yb_exec_query_wrapper (exec_context=exec_context@entry=0x358a000, restart_data=restart_data@entry=0x7ffc0fa762b0, functor=functor@entry=0x884620 <yb_exec_simple_query_impl>,
    functor_context=functor_context@entry=0x358a118) at ../../../../../../src/postgres/src/backend/tcop/postgres.c:4419
#40 0x00000000008802ec in yb_exec_simple_query (
    query_string=query_string@entry=0x358a118 "CREATE TABLE testc.streets AS\nWITH d AS (SELECT dp.geom FROM testc.city_boundary AS c, ST_DumpPoints(c.geom) AS dp)\nSELECT ROW_NUMBER() OVER() AS id, ST_MakeLine(d1.geom, d2.geom) AS geom\nFROM d AS d1"..., exec_context=exec_context@entry=0x358a000) at ../../../../../../src/postgres/src/backend/tcop/postgres.c:4449
#41 0x0000000000882213 in PostgresMain (argc=<optimized out>, argv=argv@entry=0x35ca9d8, dbname=0x35ca8b8 "postgis_reg", username=0x3585fe8 "yugabyte")
    at ../../../../../../src/postgres/src/backend/tcop/postgres.c:5084
#42 0x000000000049e292 in BackendRun (port=0x3474960) at ../../../../../../src/postgres/src/backend/postmaster/postmaster.c:4470
#43 BackendStartup (port=0x3474960) at ../../../../../../src/postgres/src/backend/postmaster/postmaster.c:4136
#44 ServerLoop () at ../../../../../../src/postgres/src/backend/postmaster/postmaster.c:1754
#45 0x00000000007ea21f in PostmasterMain (argc=argc@entry=23, argv=argv@entry=0x334e000) at ../../../../../../src/postgres/src/backend/postmaster/postmaster.c:1417
#46 0x000000000073588a in PostgresServerProcessMain (argc=23, argv=0x334e000) at ../../../../../../src/postgres/src/backend/main/main.c:234
#47 0x0000000000735a89 in main ()
```

Coredump: [core.2350.zip](https://github.com/yugabyte/yugabyte-db/files/7987555/core.2350.zip)

**Comment by andrei-mart** [comment]
Can not reproduce.
```
yugabyte=# CREATE TABLE testc.streets AS
yugabyte-#         WITH d AS (SELECT dp.geom FROM testc.city_boundary AS c, ST_DumpPoints(c.geom) AS dp)
yugabyte-#         SELECT ROW_NUMBER() OVER() AS id, ST_MakeLine(d1.geom, d2.geom) AS geom
yugabyte-#         FROM d AS d1, d AS d2
yugabyte-#         ORDER BY d1.geom <-> d2.geom DESC LIMIT 1000;
ERROR:  relation "testc.city_boundary" does not exist
LINE 2:         WITH d AS (SELECT dp.geom FROM testc.city_boundary A...
                                               ^
```
Also see https://github.com/yugabyte/yugabyte-db/issues/11318#issuecomment-1040875605

**Comment by def-** [comment]
See my comment for full setup instructions to get postgis working: https://github.com/yugabyte/yugabyte-db/issues/11318#issuecomment-1042798619
Can still reproduce with:
```
$ PATH=$PWD/bin:/usr/pgsql-11/bin:$PATH POSTGIS_SCRIPTDIR=/usr/pgsql-11/share/contrib/postgis-3.1 ./run_test.pl core/computed_columns.sql
```
