### ISSUE TITLE
[YSQL][Postgis] Segmentation fault in ST_AsGeoJsonRow()

### ISSUE THREAD

**Issue by def-** [yugabyte/yugabyte-db#11324]
### Description

See https://docs.yugabyte.com/latest/api/ysql/extensions/#postgis for Postgis installation instructions.

Can be reproduced against yugabyte-2.11.2.0 on CentOS using https://github.com/def-/postgis/tree/stable-3.1/regress by running `PATH=$CWD/bin/:$PATH ./run_test.pl core/out_geojson.sql`

tserver log:
```
2022-02-01 09:32:22.729 UTC [4020] LOG:  server process (PID 5518) was terminated by signal 11: Segmentation fault
2022-02-01 09:32:22.729 UTC [4020] DETAIL:  Failed process was running: SELECT 'gj02', i, ST_AsGeoJSON(g.*) AS gj2
                FROM g ORDER BY i;

```
backtrace from gdb:
```
#0  nocachegetattr (tuple=0x7ffc0fa75aa0, attnum=2, tupleDesc=0x36799f8) at ../../../../../../../src/postgres/src/backend/access/common/heaptuple.c:487
#1  0x00007fa956ed9db0 in ST_AsGeoJsonRow () from /nfusr/dev-server/dfelsing/yugabyte-2.11.2.0/postgres/lib/postgis-3.so
#2  0x00000000006c9ba1 in ExecInterpExpr (state=0x3a730f0, econtext=0x3a72548, isnull=<optimized out>) at ../../../../../../src/postgres/src/backend/executor/execExprInterp.c:703
#3  0x00000000006d957a in ExecEvalExprSwitchContext (isNull=0x7ffc0fa75bcf, econtext=0x3a72548, state=0x3a730f0) at ../../../../../../src/postgres/src/include/executor/executor.h:321
#4  ExecProject (projInfo=0x3a730e8) at ../../../../../../src/postgres/src/include/executor/executor.h:355
#5  ExecScan (node=<optimized out>, accessMtd=0x704830 <ForeignNext>, recheckMtd=0x704920 <ForeignRecheck>) at ../../../../../../src/postgres/src/backend/executor/execScan.c:210
#6  0x00000000006fff56 in ExecProcNode (node=0x3a72438) at ../../../../../../src/postgres/src/include/executor/executor.h:249
#7  ExecSort (pstate=0x3a72328) at ../../../../../../src/postgres/src/backend/executor/nodeSort.c:116
#8  0x00000000006ce5db in ExecProcNode (node=0x3a72328) at ../../../../../../src/postgres/src/include/executor/executor.h:249
#9  ExecutePlan (execute_once=<optimized out>, dest=0x370b6a8, direction=<optimized out>, numberTuples=0, sendTuples=<optimized out>, operation=CMD_SELECT, use_parallel_mode=<optimized out>, planstate=0x3a72328,
    estate=0x3a72118) at ../../../../../../src/postgres/src/backend/executor/execMain.c:1730
#10 standard_ExecutorRun (queryDesc=0x335f118, direction=<optimized out>, count=0, execute_once=<optimized out>) at ../../../../../../src/postgres/src/backend/executor/execMain.c:367
#11 0x00007fa96624d8bd in pgss_ExecutorRun (queryDesc=0x335f118, direction=ForwardScanDirection, count=0, execute_once=<optimized out>)
    at ../../../../../src/postgres/contrib/pg_stat_statements/pg_stat_statements.c:947
#12 0x00007fa9660463aa in ybpgm_ExecutorRun (queryDesc=0x335f118, direction=ForwardScanDirection, count=0, execute_once=<optimized out>) at ../../../../../src/postgres/contrib/yb_pg_metrics/yb_pg_metrics.c:499
#13 0x000000000088564b in PortalRunSelect (portal=portal@entry=0x365e118, forward=forward@entry=true, count=0, count@entry=9223372036854775807, dest=dest@entry=0x370b6a8)
    at ../../../../../../src/postgres/src/backend/tcop/pquery.c:955
#14 0x0000000000887141 in PortalRun (portal=portal@entry=0x365e118, count=count@entry=9223372036854775807, isTopLevel=isTopLevel@entry=true, run_once=run_once@entry=true, dest=dest@entry=0x370b6a8,
    altdest=altdest@entry=0x370b6a8, completionTag=0x7ffc0fa760e0 "") at ../../../../../../src/postgres/src/backend/tcop/pquery.c:784
#15 0x0000000000884ad8 in exec_simple_query (query_string=0x358a118 "SELECT 'gj02', i, ST_AsGeoJSON(g.*) AS gj2\n\tFROM g ORDER BY i;", query_string@entry=0x7ffc0fa76060 "\030\341e\003")
    at ../../../../../../src/postgres/src/backend/tcop/postgres.c:1161
#16 yb_exec_simple_query_impl (query_string=query_string@entry=0x358a118) at ../../../../../../src/postgres/src/backend/tcop/postgres.c:4434
#17 0x000000000087f8b8 in yb_exec_query_wrapper (exec_context=exec_context@entry=0x358a000, restart_data=restart_data@entry=0x7ffc0fa762b0, functor=functor@entry=0x884620 <yb_exec_simple_query_impl>,
    functor_context=functor_context@entry=0x358a118) at ../../../../../../src/postgres/src/backend/tcop/postgres.c:4419
#18 0x00000000008802ec in yb_exec_simple_query (query_string=query_string@entry=0x358a118 "SELECT 'gj02', i, ST_AsGeoJSON(g.*) AS gj2\n\tFROM g ORDER BY i;", exec_context=exec_context@entry=0x358a000)
    at ../../../../../../src/postgres/src/backend/tcop/postgres.c:4449
#19 0x0000000000882213 in PostgresMain (argc=<optimized out>, argv=argv@entry=0x35cc958, dbname=0x35cc838 "postgis_reg", username=0x3585fe8 "yugabyte")
    at ../../../../../../src/postgres/src/backend/tcop/postgres.c:5084
#20 0x000000000049e292 in BackendRun (port=0x3474960) at ../../../../../../src/postgres/src/backend/postmaster/postmaster.c:4470
#21 BackendStartup (port=0x3474960) at ../../../../../../src/postgres/src/backend/postmaster/postmaster.c:4136
#22 ServerLoop () at ../../../../../../src/postgres/src/backend/postmaster/postmaster.c:1754
#23 0x00000000007ea21f in PostmasterMain (argc=argc@entry=23, argv=argv@entry=0x334e000) at ../../../../../../src/postgres/src/backend/postmaster/postmaster.c:1417
#24 0x000000000073588a in PostgresServerProcessMain (argc=23, argv=0x334e000) at ../../../../../../src/postgres/src/backend/main/main.c:234
#25 0x0000000000735a89 in main ()

core/regress_gist_index_nd.sql
022-02-01 09:34:34.447 UTC [4020] LOG:  server process (PID 5908) was terminated by signal 11: Segmentation fault
2022-02-01 09:34:34.447 UTC [4020] DETAIL:  Failed process was running: insert into test_gist_idx_nd(op, n
oidx, noidxscan)
        select '&&&', count(*), qnodes('select count(*) from tbl_geomcollection_nd t1, tbl_geomcollection_
nd t2 where t1.g &&& t2.g') from tbl_geomcollection_nd t1, tbl_geomcollection_nd t2 where t1.g &&& t2.g;

#0  0x0000000000000000 in ?? ()
#1  0x00000000009e2d47 in CatalogCacheComputeHashValue (v4=0, v3=1, v2=2, v1=331758, nkeys=3, cache=0x3672700) at ../../../../../../../src/postgres/src/backend/utils/cache/catcache.c:306
#2  SearchCatCacheInternal (nkeys=3, v4=0, v3=<optimized out>, v2=<optimized out>, v1=<optimized out>, cache=0x3672700) at ../../../../../../../src/postgres/src/backend/utils/cache/catcache.c:1602
#3  SearchCatCache3 (cache=0x3672700, v1=331758, v2=2, v3=1) at ../../../../../../../src/postgres/src/backend/utils/cache/catcache.c:1549
#4  0x00007fa956c9764d in pg_get_nd_stats () from /nfusr/dev-server/dfelsing/yugabyte-2.11.2.0/postgres/lib/postgis-3.so
#5  0x00007fa956c9a99d in gserialized_joinsel_internal () from /nfusr/dev-server/dfelsing/yugabyte-2.11.2.0/postgres/lib/postgis-3.so
#6  0x00007fa956c9aa43 in gserialized_gist_joinsel () from /nfusr/dev-server/dfelsing/yugabyte-2.11.2.0/postgres/lib/postgis-3.so
#7  0x0000000000a0f82d in DirectFunctionCall5Coll (func=0x7fa956c9aa00 <gserialized_gist_joinsel>, collation=<optimized out>, arg1=<optimized out>, arg2=<optimized out>, arg3=<optimized out>,
    arg4=<optimized out>, arg5=0) at ../../../../../../../src/postgres/src/backend/utils/fmgr/fmgr.c:918
#8  0x00007fa956c9a8ca in gserialized_gist_joinsel_nd () from /nfusr/dev-server/dfelsing/yugabyte-2.11.2.0/postgres/lib/postgis-3.so
#9  0x0000000000a10dc8 in OidFunctionCall5Coll (functionId=<optimized out>, collation=collation@entry=0, arg1=arg1@entry=62485432, arg2=arg2@entry=330903, arg3=arg3@entry=62488712, arg4=arg4@entry=0,
    arg5=140720571110560) at ../../../../../../../src/postgres/src/backend/utils/fmgr/fmgr.c:1545
#10 0x00000000007c397b in join_selectivity (root=root@entry=0x3b973b8, operatorid=330903, args=0x3b98088, inputcollid=0, jointype=jointype@entry=JOIN_INNER, sjinfo=sjinfo@entry=0x7ffc0fa754a0)
    at ../../../../../../../src/postgres/src/backend/optimizer/util/plancat.c:1820
#11 0x000000000076c8f3 in clause_selectivity (root=root@entry=0x3b973b8, clause=<optimized out>, varRelid=varRelid@entry=0, jointype=jointype@entry=JOIN_INNER, sjinfo=sjinfo@entry=0x7ffc0fa754a0)
    at ../../../../../../../src/postgres/src/backend/optimizer/path/clausesel.c:739
#12 0x000000000076cadc in clauselist_selectivity (root=root@entry=0x3b973b8, clauses=clauses@entry=0x3b99a38, varRelid=varRelid@entry=0, jointype=JOIN_INNER, sjinfo=sjinfo@entry=0x7ffc0fa754a0)
    at ../../../../../../../src/postgres/src/backend/optimizer/path/clausesel.c:117
#13 0x000000000076df8a in calc_joinrel_size_estimate (root=0x3b973b8, outer_rows=1000, inner_rows=1000, sjinfo=0x7ffc0fa754a0, restrictlist_in=0x3b99a38, inner_rel=<optimized out>, outer_rel=<optimized out>,
    joinrel=<optimized out>) at ../../../../../../../src/postgres/src/backend/optimizer/path/costsize.c:4538
#14 0x0000000000773b8a in set_joinrel_size_estimates (root=root@entry=0x3b973b8, rel=rel@entry=0x3b997a0, outer_rel=outer_rel@entry=0x3b98648, inner_rel=inner_rel@entry=0x3b98988,
    sjinfo=sjinfo@entry=0x7ffc0fa754a0, restrictlist=restrictlist@entry=0x3b99a38) at ../../../../../../../src/postgres/src/backend/optimizer/path/costsize.c:4393
#15 0x00000000007c6f20 in build_join_rel (root=root@entry=0x3b973b8, joinrelids=joinrelids@entry=0x3b99788, outer_rel=outer_rel@entry=0x3b98648, inner_rel=inner_rel@entry=0x3b98988, sjinfo=0x7ffc0fa754a0,
    restrictlist_ptr=restrictlist_ptr@entry=0x7ffc0fa75498) at ../../../../../../../src/postgres/src/backend/optimizer/util/relnode.c:673
#16 0x0000000000781416 in make_join_rel (root=root@entry=0x3b973b8, rel1=rel1@entry=0x3b98648, rel2=rel2@entry=0x3b98988) at ../../../../../../../src/postgres/src/backend/optimizer/path/joinrels.c:730
#17 0x00000000007815ef in make_rels_by_clause_joins (other_rels=<optimized out>, old_rel=<optimized out>, root=<optimized out>) at ../../../../../../../src/postgres/src/backend/optimizer/path/joinrels.c:290
#18 join_search_one_level (root=root@entry=0x3b973b8, level=level@entry=2) at ../../../../../../../src/postgres/src/backend/optimizer/path/joinrels.c:112
#19 0x000000000076be9b in standard_join_search (root=0x3b973b8, levels_needed=2, initial_rels=<optimized out>) at ../../../../../../../src/postgres/src/backend/optimizer/path/allpaths.c:2822
#20 0x000000000076c307 in make_one_rel (root=root@entry=0x3b973b8, joinlist=joinlist@entry=0x3b98d00) at ../../../../../../../src/postgres/src/backend/optimizer/path/allpaths.c:227
#21 0x0000000000794dc0 in query_planner (root=root@entry=0x3b973b8, tlist=tlist@entry=0x3b97bd8, qp_callback=qp_callback@entry=0x795f00 <standard_qp_callback>, qp_extra=qp_extra@entry=0x7ffc0fa75770)
    at ../../../../../../../src/postgres/src/backend/optimizer/plan/planmain.c:265
#22 0x000000000079a10d in grouping_planner (root=root@entry=0x3b973b8, inheritance_update=inheritance_update@entry=false, tuple_fraction=<optimized out>, tuple_fraction@entry=0)
    at ../../../../../../../src/postgres/src/backend/optimizer/plan/planner.c:1908
#23 0x000000000079ce2c in subquery_planner (glob=<optimized out>, parse=parse@entry=0x3acade8, parent_root=parent_root@entry=0x3b95830, hasRecursion=hasRecursion@entry=false, tuple_fraction=0)
    at ../../../../../../../src/postgres/src/backend/optimizer/plan/planner.c:966
#24 0x000000000076a321 in set_subquery_pathlist (rte=<optimized out>, rti=<optimized out>, rel=0x3b95210, root=0x3b95830) at ../../../../../../../src/postgres/src/backend/optimizer/path/allpaths.c:2277
#25 set_rel_size (root=root@entry=0x3b95830, rel=rel@entry=0x3b95210, rti=rti@entry=2, rte=<optimized out>) at ../../../../../../../src/postgres/src/backend/optimizer/path/allpaths.c:438
#26 0x000000000076c29e in set_base_rel_sizes (root=<optimized out>) at ../../../../../../../src/postgres/src/backend/optimizer/path/allpaths.c:323
#27 make_one_rel (root=root@entry=0x3b95830, joinlist=joinlist@entry=0x3b96568) at ../../../../../../../src/postgres/src/backend/optimizer/path/allpaths.c:221
#28 0x0000000000794dc0 in query_planner (root=root@entry=0x3b95830, tlist=tlist@entry=0x3b96220, qp_callback=qp_callback@entry=0x795f00 <standard_qp_callback>, qp_extra=qp_extra@entry=0x7ffc0fa75bd0)
    at ../../../../../../../src/postgres/src/backend/optimizer/plan/planmain.c:265
#29 0x000000000079a10d in grouping_planner (root=root@entry=0x3b95830, inheritance_update=inheritance_update@entry=false, tuple_fraction=<optimized out>, tuple_fraction@entry=0)
    at ../../../../../../../src/postgres/src/backend/optimizer/plan/planner.c:1908
#30 0x000000000079ce2c in subquery_planner (glob=glob@entry=0x3b957a0, parse=parse@entry=0x3acaef8, parent_root=parent_root@entry=0x0, hasRecursion=hasRecursion@entry=false, tuple_fraction=tuple_fraction@entry=0)
    at ../../../../../../../src/postgres/src/backend/optimizer/plan/planner.c:966
#31 0x000000000079df25 in standard_planner (parse=0x3acaef8, cursorOptions=256, boundParams=<optimized out>) at ../../../../../../../src/postgres/src/backend/optimizer/plan/planner.c:405
#32 0x00007fa965c33ead in pg_hint_plan_planner (parse=0x3acaef8, cursorOptions=256, boundParams=0x0) at ../../../../../src/postgres/third-party-extensions/pg_hint_plan/pg_hint_plan.c:3221
#33 0x0000000000880324 in pg_plan_query (querytree=querytree@entry=0x3acaef8, cursorOptions=cursorOptions@entry=256, boundParams=boundParams@entry=0x0)
    at ../../../../../../src/postgres/src/backend/tcop/postgres.c:848
#34 0x0000000000880467 in pg_plan_queries (querytrees=<optimized out>, cursorOptions=cursorOptions@entry=256, boundParams=boundParams@entry=0x0) at ../../../../../../src/postgres/src/backend/tcop/postgres.c:914
#35 0x00000000008849e0 in exec_simple_query (
    query_string=0x358a118 "insert into test_gist_idx_nd(op, noidx, noidxscan)\nselect '&&&', count(*), qnodes('select count(*) from tbl_geomcollection_nd t1, tbl_geomcollection_nd t2 where t1.g &&& t2.g') from tbl_geomcollection"..., query_string@entry=0x7ffc0fa76080 "Pa\247\017\374\177") at ../../../../../../src/postgres/src/backend/tcop/postgres.c:1089
#36 yb_exec_simple_query_impl (query_string=query_string@entry=0x358a118) at ../../../../../../src/postgres/src/backend/tcop/postgres.c:4434
#37 0x000000000087f8b8 in yb_exec_query_wrapper (exec_context=exec_context@entry=0x358a000, restart_data=restart_data@entry=0x7ffc0fa762b0, functor=functor@entry=0x884620 <yb_exec_simple_query_impl>,
    functor_context=functor_context@entry=0x358a118) at ../../../../../../src/postgres/src/backend/tcop/postgres.c:4419
#38 0x00000000008802ec in yb_exec_simple_query (
    query_string=query_string@entry=0x358a118 "insert into test_gist_idx_nd(op, noidx, noidxscan)\nselect '&&&', count(*), qnodes('select count(*) from tbl_geomcollection_nd t1, tbl_geomcollection_nd t2 where t1.g &&& t2.g') from tbl_geomcollection"..., exec_context=exec_context@entry=0x358a000) at ../../../../../../src/postgres/src/backend/tcop/postgres.c:4449
#39 0x0000000000882213 in PostgresMain (argc=<optimized out>, argv=argv@entry=0x35ccdd8, dbname=0x35cccb8 "postgis_reg", username=0x3585fe8 "yugabyte")
    at ../../../../../../src/postgres/src/backend/tcop/postgres.c:5084
#40 0x000000000049e292 in BackendRun (port=0x3474960) at ../../../../../../src/postgres/src/backend/postmaster/postmaster.c:4470
#41 BackendStartup (port=0x3474960) at ../../../../../../src/postgres/src/backend/postmaster/postmaster.c:4136
#42 ServerLoop () at ../../../../../../src/postgres/src/backend/postmaster/postmaster.c:1754
#43 0x00000000007ea21f in PostmasterMain (argc=argc@entry=23, argv=argv@entry=0x334e000) at ../../../../../../src/postgres/src/backend/postmaster/postmaster.c:1417
#44 0x000000000073588a in PostgresServerProcessMain (argc=23, argv=0x334e000) at ../../../../../../src/postgres/src/backend/main/main.c:234
#45 0x0000000000735a89 in main ()
```

Coredump: [core.5518.zip](https://github.com/yugabyte/yugabyte-db/files/7987642/core.5518.zip)

**Comment by andrei-mart** [comment]
Can not reproduce
```
yugabyte-#                 FROM g ORDER BY i;
ERROR:  relation "g" does not exist
LINE 2:                 FROM g ORDER BY i;
                             ^
```
also see https://github.com/yugabyte/yugabyte-db/issues/11318#issuecomment-1040875605

**Comment by def-** [comment]
See my comment for full instructions: https://github.com/yugabyte/yugabyte-db/issues/11318#issuecomment-1042798619
Can still reproduce with:
```
$ PATH=$PWD/bin:/usr/pgsql-11/bin:$PATH POSTGIS_SCRIPTDIR=/usr/pgsql-11/share/contrib/postgis-3.1 ./run_test.pl core/out_geojson.sql
```
