### ISSUE TITLE
[YSQL][Postgis] Segmentation fault in LWGEOM_dump()

### ISSUE THREAD

**Issue by def-** [yugabyte/yugabyte-db#11326]
### Description

See https://docs.yugabyte.com/latest/api/ysql/extensions/#postgis for Postgis installation instructions.

Can be reproduced against yugabyte-2.11.2.0 on CentOS using https://github.com/def-/postgis/tree/stable-3.1/regress by running `PATH=$CWD/bin/:$PATH ./run_test.pl core/tickets.sql`

tserver log:
```
2022-02-01 09:37:40.177 UTC [4020] LOG:  server process (PID 6978) was terminated by signal 11: Segmentation fault
2022-02-01 09:37:40.177 UTC [4020] DETAIL:  Failed process was running: SELECT '#66', ST_AsText((ST_Dump(ST_GeomFromEWKT('CIRCULARSTRING(0 0,1 1,2 2)'))).geom);
```
backtrace from gdb:
```
#0  HeapTupleHeaderGetDatum (tuple=0x0) at ../../../../../../src/postgres/src/backend/executor/execTuples.c:1385
#1  0x00007fa9576c30d1 in LWGEOM_dump () from /nfusr/dev-server/dfelsing/yugabyte-2.11.2.0/postgres/lib/postgis-3.so
#2  0x00000000006dad56 in ExecMakeFunctionResultSet (fcache=0x38070b8, econtext=econtext@entry=0x3806628, argContext=0x3a9e000, isNull=0x3806fd8, isDone=isDone@entry=0x38070a0)
    at ../../../../../../src/postgres/src/backend/executor/execSRF.c:604
#3  0x00000000006fda93 in ExecProjectSRF (continuing=false, node=0x3806518) at ../../../../../../src/postgres/src/backend/executor/nodeProjectSet.c:175
#4  ExecProjectSet (pstate=0x3806518) at ../../../../../../src/postgres/src/backend/executor/nodeProjectSet.c:105
#5  0x00000000006fe40d in ExecProcNode (node=0x3806518) at ../../../../../../src/postgres/src/include/executor/executor.h:249
#6  ExecResult (pstate=0x3806328) at ../../../../../../src/postgres/src/backend/executor/nodeResult.c:115
#7  0x00000000006ce5db in ExecProcNode (node=0x3806328) at ../../../../../../src/postgres/src/include/executor/executor.h:249
#8  ExecutePlan (execute_once=<optimized out>, dest=0x3ad4760, direction=<optimized out>, numberTuples=0, sendTuples=<optimized out>, operation=CMD_SELECT, use_parallel_mode=<optimized out>, planstate=0x3806328,
    estate=0x3806118) at ../../../../../../src/postgres/src/backend/executor/execMain.c:1730
#9  standard_ExecutorRun (queryDesc=0x335f118, direction=<optimized out>, count=0, execute_once=<optimized out>) at ../../../../../../src/postgres/src/backend/executor/execMain.c:367
#10 0x00007fa96624d8bd in pgss_ExecutorRun (queryDesc=0x335f118, direction=ForwardScanDirection, count=0, execute_once=<optimized out>)
    at ../../../../../src/postgres/contrib/pg_stat_statements/pg_stat_statements.c:947
#11 0x00007fa9660463aa in ybpgm_ExecutorRun (queryDesc=0x335f118, direction=ForwardScanDirection, count=0, execute_once=<optimized out>) at ../../../../../src/postgres/contrib/yb_pg_metrics/yb_pg_metrics.c:499
#12 0x000000000088564b in PortalRunSelect (portal=portal@entry=0x365e118, forward=forward@entry=true, count=0, count@entry=9223372036854775807, dest=dest@entry=0x3ad4760)
    at ../../../../../../src/postgres/src/backend/tcop/pquery.c:955
#13 0x0000000000887141 in PortalRun (portal=portal@entry=0x365e118, count=count@entry=9223372036854775807, isTopLevel=isTopLevel@entry=true, run_once=run_once@entry=true, dest=dest@entry=0x3ad4760,
    altdest=altdest@entry=0x3ad4760, completionTag=0x7ffc0fa760e0 "") at ../../../../../../src/postgres/src/backend/tcop/pquery.c:784
#14 0x0000000000884ad8 in exec_simple_query (query_string=0x358a118 "SELECT '#66', ST_AsText((ST_Dump(ST_GeomFromEWKT('CIRCULARSTRING(0 0,1 1,2 2)'))).geom);", query_string@entry=0x7ffc0fa76060 "\030\341e\003")
    at ../../../../../../src/postgres/src/backend/tcop/postgres.c:1161
#15 yb_exec_simple_query_impl (query_string=query_string@entry=0x358a118) at ../../../../../../src/postgres/src/backend/tcop/postgres.c:4434
#16 0x000000000087f8b8 in yb_exec_query_wrapper (exec_context=exec_context@entry=0x358a000, restart_data=restart_data@entry=0x7ffc0fa762b0, functor=functor@entry=0x884620 <yb_exec_simple_query_impl>,
    functor_context=functor_context@entry=0x358a118) at ../../../../../../src/postgres/src/backend/tcop/postgres.c:4419
#17 0x00000000008802ec in yb_exec_simple_query (query_string=query_string@entry=0x358a118 "SELECT '#66', ST_AsText((ST_Dump(ST_GeomFromEWKT('CIRCULARSTRING(0 0,1 1,2 2)'))).geom);",
    exec_context=exec_context@entry=0x358a000) at ../../../../../../src/postgres/src/backend/tcop/postgres.c:4449
#18 0x0000000000882213 in PostgresMain (argc=<optimized out>, argv=argv@entry=0x35cdb58, dbname=0x35cda38 "postgis_reg", username=0x3585fe8 "yugabyte")
    at ../../../../../../src/postgres/src/backend/tcop/postgres.c:5084
#19 0x000000000049e292 in BackendRun (port=0x3474960) at ../../../../../../src/postgres/src/backend/postmaster/postmaster.c:4470
#20 BackendStartup (port=0x3474960) at ../../../../../../src/postgres/src/backend/postmaster/postmaster.c:4136
#21 ServerLoop () at ../../../../../../src/postgres/src/backend/postmaster/postmaster.c:1754
#22 0x00000000007ea21f in PostmasterMain (argc=argc@entry=23, argv=argv@entry=0x334e000) at ../../../../../../src/postgres/src/backend/postmaster/postmaster.c:1417
#23 0x000000000073588a in PostgresServerProcessMain (argc=23, argv=0x334e000) at ../../../../../../src/postgres/src/backend/main/main.c:234
#24 0x0000000000735a89 in main ()
```

Same failure with core/concave_hull_hard.sql, core/concave.sql, core/dump.sql. Coredump: [core.6978.zip](https://github.com/yugabyte/yugabyte-db/files/7987681/core.6978.zip)

**Comment by andrei-mart** [comment]
Can not reproduce
```
yugabyte=# SELECT '#66', ST_AsText((ST_Dump(ST_GeomFromEWKT('CIRCULARSTRING(0 0,1 1,2 2)'))).geom);
 ?column? |          st_astext          
----------+-----------------------------
 #66      | CIRCULARSTRING(0 0,1 1,2 2)
(1 row)
```
also see https://github.com/yugabyte/yugabyte-db/issues/11318#issuecomment-1040875605
