### ISSUE TITLE
 [YSQL][Postgis] Segmentation fault in protobuf_c_message_get_packed_size()

### ISSUE THREAD

**Issue by def-** [yugabyte/yugabyte-db#11330]
### Description

See https://docs.yugabyte.com/latest/api/ysql/extensions/#postgis for Postgis installation instructions.

Can be reproduced against yugabyte-2.11.2.0 on CentOS using https://github.com/def-/postgis/tree/stable-3.1/regress self-built with protobuf-c support (CentOS default Postgis version comes without protobuf-c support, so the test fails with "Compiled without protobuf-c support") by running `PATH=$CWD/bin/:$PATH ./run_test.pl core/geobuf.sql`

tserver log:
```
2022-02-02 16:02:05.222 UTC [950] LOG:  server process (PID 1363) was terminated by signal 11: Segmentation fault
2022-02-02 16:02:05.222 UTC [950] DETAIL:  Failed process was running: SELECT 'T2', encode(ST_AsGeobuf(q, 'geom'), 'base64')
            FROM (SELECT 'test' as test_str, 1 as test_pos_int, -1 as test_neg_int, 1.1 as test_numeric, 1.1::float as test_float, ST_MakeLine(ST_MakePoint(1,1), ST_MakePoint(2,2)) as geom) AS q;

```
backtrace from gdb:
```
#0  strlen () at ../sysdeps/x86_64/strlen.S:106
#1  0x00007f4799350f41 in required_field_get_packed_size.isra.14 () from /nfusr/dev-server/dfelsing/yugabyte-2.11.2.0/postgres/../lib/yb-thirdparty/libprotobuf-c.so.1
#2  0x00007f479935093b in protobuf_c_message_get_packed_size () from /nfusr/dev-server/dfelsing/yugabyte-2.11.2.0/postgres/../lib/yb-thirdparty/libprotobuf-c.so.1
#3  0x00007f4799350bc2 in protobuf_c_message_get_packed_size () from /nfusr/dev-server/dfelsing/yugabyte-2.11.2.0/postgres/../lib/yb-thirdparty/libprotobuf-c.so.1
#4  0x00007f4799350bc2 in protobuf_c_message_get_packed_size () from /nfusr/dev-server/dfelsing/yugabyte-2.11.2.0/postgres/../lib/yb-thirdparty/libprotobuf-c.so.1
#5  0x00007f47993510b6 in required_field_get_packed_size.isra.14 () from /nfusr/dev-server/dfelsing/yugabyte-2.11.2.0/postgres/../lib/yb-thirdparty/libprotobuf-c.so.1
#6  0x00007f479935093b in protobuf_c_message_get_packed_size () from /nfusr/dev-server/dfelsing/yugabyte-2.11.2.0/postgres/../lib/yb-thirdparty/libprotobuf-c.so.1
#7  0x00007f4799d4c445 in data__get_packed_size (message=<optimized out>) at geobuf.pb-c.c:44
#8  0x00007f4799d567d8 in geobuf_agg_finalfn (ctx=0x394e118) at geobuf.c:652
#9  0x00000000006e2121 in finalize_aggregate (aggstate=aggstate@entry=0x38dc328, peragg=peragg@entry=0x38ddc30, pergroupstate=0x397d060, resultVal=resultVal@entry=0x38ddc00,
    resultIsNull=resultIsNull@entry=0x38ddc18) at ../../../../../../src/postgres/src/backend/executor/nodeAgg.c:970
#10 0x00000000006e28d6 in finalize_aggregates (aggstate=aggstate@entry=0x38dc328, peraggs=peraggs@entry=0x38ddc30, pergroup=<optimized out>) at ../../../../../../src/postgres/src/backend/executor/nodeAgg.c:1177
#11 0x00000000006e35a4 in agg_retrieve_direct (aggstate=0x38dc328) at ../../../../../../src/postgres/src/backend/executor/nodeAgg.c:2167
---Type <return> to continue, or q <return> to quit---
#12 ExecAgg (pstate=0x38dc328) at ../../../../../../src/postgres/src/backend/executor/nodeAgg.c:1766
#13 0x00000000006ce5db in ExecProcNode (node=0x38dc328) at ../../../../../../src/postgres/src/include/executor/executor.h:249
#14 ExecutePlan (execute_once=<optimized out>, dest=0x3911740, direction=<optimized out>, numberTuples=0, sendTuples=<optimized out>, operation=CMD_SELECT, use_parallel_mode=<optimized out>, planstate=0x38dc328,
    estate=0x38dc118) at ../../../../../../src/postgres/src/backend/executor/execMain.c:1730
#15 standard_ExecutorRun (queryDesc=0x33c1118, direction=<optimized out>, count=0, execute_once=<optimized out>) at ../../../../../../src/postgres/src/backend/executor/execMain.c:367
#16 0x00007f47a890f8bd in pgss_ExecutorRun (queryDesc=0x33c1118, direction=ForwardScanDirection, count=0, execute_once=<optimized out>)
    at ../../../../../src/postgres/contrib/pg_stat_statements/pg_stat_statements.c:947
#17 0x00007f47a87083aa in ybpgm_ExecutorRun (queryDesc=0x33c1118, direction=ForwardScanDirection, count=0, execute_once=<optimized out>) at ../../../../../src/postgres/contrib/yb_pg_metrics/yb_pg_metrics.c:499
#18 0x000000000088564b in PortalRunSelect (portal=portal@entry=0x36b2118, forward=forward@entry=true, count=0, count@entry=9223372036854775807, dest=dest@entry=0x3911740)
    at ../../../../../../src/postgres/src/backend/tcop/pquery.c:955
#19 0x0000000000887141 in PortalRun (portal=portal@entry=0x36b2118, count=count@entry=9223372036854775807, isTopLevel=isTopLevel@entry=true, run_once=run_once@entry=true, dest=dest@entry=0x3911740,
    altdest=altdest@entry=0x3911740, completionTag=0x7ffe807cab80 "") at ../../../../../../src/postgres/src/backend/tcop/pquery.c:784
#20 0x0000000000884ad8 in exec_simple_query (
    query_string=0x35ec118 "SELECT 'T2', encode(ST_AsGeobuf(q, 'geom'), 'base64')\n    FROM (SELECT 'test' as test_str, 1 as test_pos_int, -1 as test_neg_int, 1.1 as test_numeric, 1.1::float as test_float, ST_MakeLine(ST_MakePoin"..., query_string@entry=0x7ffe807cab00 "\030!k\003") at ../../../../../../src/postgres/src/backend/tcop/postgres.c:1161
#21 yb_exec_simple_query_impl (query_string=query_string@entry=0x35ec118) at ../../../../../../src/postgres/src/backend/tcop/postgres.c:4434
#22 0x000000000087f8b8 in yb_exec_query_wrapper (exec_context=exec_context@entry=0x35ec000, restart_data=restart_data@entry=0x7ffe807cad50, functor=functor@entry=0x884620 <yb_exec_simple_query_impl>,
    functor_context=functor_context@entry=0x35ec118) at ../../../../../../src/postgres/src/backend/tcop/postgres.c:4419
#23 0x00000000008802ec in yb_exec_simple_query (
    query_string=query_string@entry=0x35ec118 "SELECT 'T2', encode(ST_AsGeobuf(q, 'geom'), 'base64')\n    FROM (SELECT 'test' as test_str, 1 as test_pos_int, -1 as test_neg_int, 1.1 as test_numeric, 1.1::float as test_float, ST_MakeLine(ST_MakePoin"..., exec_context=exec_context@entry=0x35ec000) at ../../../../../../src/postgres/src/backend/tcop/postgres.c:4449
#24 0x0000000000882213 in PostgresMain (argc=<optimized out>, argv=argv@entry=0x35e7500, dbname=0x35e7398 "postgis_reg", username=0x35e7378 "yugabyte")
    at ../../../../../../src/postgres/src/backend/tcop/postgres.c:5084
#25 0x000000000049e292 in BackendRun (port=0x34d6960) at ../../../../../../src/postgres/src/backend/postmaster/postmaster.c:4470
#26 BackendStartup (port=0x34d6960) at ../../../../../../src/postgres/src/backend/postmaster/postmaster.c:4136
#27 ServerLoop () at ../../../../../../src/postgres/src/backend/postmaster/postmaster.c:1754
#28 0x00000000007ea21f in PostmasterMain (argc=argc@entry=23, argv=argv@entry=0x33b0000) at ../../../../../../src/postgres/src/backend/postmaster/postmaster.c:1417
#29 0x000000000073588a in PostgresServerProcessMain (argc=23, argv=0x33b0000) at ../../../../../../src/postgres/src/backend/main/main.c:234
#30 0x0000000000735a89 in main ()
```

Coredump: [core.1363.zip](https://github.com/yugabyte/yugabyte-db/files/7988119/core.1363.zip)

**Comment by andrei-mart** [comment]
Can not reproduce 
```
yugabyte=# SELECT 'T2', encode(ST_AsGeobuf(q, 'geom'), 'base64')
yugabyte-#             FROM (SELECT 'test' as test_str, 1 as test_pos_int, -1 as test_neg_int, 1.1 as test_numeric, 1.1::float as test_float, ST_MakeLine(ST_MakePoint(1,1), ST_MakePoint(2,2)) as geom) AS q;
 ?column? |                                    encode                                    
----------+------------------------------------------------------------------------------
 T2       | Cgh0ZXN0X3N0cgoMdGVzdF9wb3NfaW50Cgx0ZXN0X25lZ19pbnQKDHRlc3RfbnVtZXJpYwoKdGVz+
          | dF9mbG9hdBgAIjoKOAoICAIaBAICAgJqBgoEdGVzdGoCGAFqAiABagUKAzEuMWoJEZqZmZmZmfE/+
          | cgoAAAEBAgIDAwQE
(1 row)
```
also see https://github.com/yugabyte/yugabyte-db/issues/11318#issuecomment-1040875605

**Comment by def-** [comment]
See my comment for full instructions: https://github.com/yugabyte/yugabyte-db/issues/11318#issuecomment-1042798619
Can still reproduce with:
```
$ PATH=$PWD/bin:/usr/pgsql-11/bin:$PATH POSTGIS_SCRIPTDIR=/usr/pgsql-11/share/contrib/postgis-3.1 ./run_test.pl core/geobuf.sql
```
