### ISSUE TITLE
[YSQL][Postgis] Segmentation fault in 

### ISSUE THREAD

**Issue by def-** [yugabyte/yugabyte-db#11331]
### Description

See https://docs.yugabyte.com/latest/api/ysql/extensions/#postgis for Postgis installation instructions.

Can be reproduced against yugabyte-2.11.2.0 on CentOS using https://github.com/def-/postgis/tree/stable-3.1/regress self-built with protobuf-c support (CentOS default Postgis version comes without protobuf-c support, so the test fails with "Compiled without protobuf-c support") by running `PATH=$CWD/bin/:$PATH ./run_test.pl core/mvt.sql`

tserver log:
```
2022-02-02 16:08:36.022 UTC [950] DETAIL:  Failed process was running: SELECT 'TG1', encode(ST_AsMVT(q, 'test', 4096, 'geom'), 'base64') FROM (SELECT 1 AS c1,
                ST_AsMVTGeom(ST_GeomFromText('POINT(25 17)'),
                        ST_MakeBox2D(ST_Point(0, 0), ST_Point(4096, 4096)), 4096, 0, false) AS geom) AS q;
```
backtrace from gdb:
```
Core was generated by `postgres: yugabyte postgis_reg 127.0.0.1(35720) SELECT                        '.
Program terminated with signal 11, Segmentation fault.
#0  heap_deform_tuple (tuple=tuple@entry=0x7ffe807ca4e0, tupleDesc=tupleDesc@entry=0x38b1428, values=values@entry=0x3a763e8, isnull=isnull@entry=0x3a76408)
    at ../../../../../../../src/postgres/src/backend/access/common/heaptuple.c:1339
1339	../../../../../../../src/postgres/src/backend/access/common/heaptuple.c: No such file or directory.
(gdb) bt
#0  heap_deform_tuple (tuple=tuple@entry=0x7ffe807ca4e0, tupleDesc=tupleDesc@entry=0x38b1428, values=values@entry=0x3a763e8, isnull=isnull@entry=0x3a76408)
    at ../../../../../../../src/postgres/src/backend/access/common/heaptuple.c:1339
#1  0x00007f4799d4f400 in parse_values (ctx=0x36fa118) at mvt.c:650
#2  mvt_agg_transfn (ctx=ctx@entry=0x36fa118) at mvt.c:1286
#3  0x00007f4799d54fca in pgis_asmvt_transfn (fcinfo=0x39ec188) at lwgeom_out_mvt.c:172
#4  0x00000000006ca1fa in ExecInterpExpr (state=0x39ed180, econtext=0x3858550, isnull=<optimized out>) at ../../../../../../src/postgres/src/backend/executor/execExprInterp.c:1687
#5  0x00000000006e37f1 in ExecEvalExprSwitchContext (isNull=0x7ffe807ca6af, econtext=<optimized out>, state=0x39ed180) at ../../../../../../src/postgres/src/include/executor/executor.h:321
#6  advance_aggregates (aggstate=0x3858328, aggstate=0x3858328) at ../../../../../../src/postgres/src/backend/executor/nodeAgg.c:685
#7  agg_retrieve_direct (aggstate=0x3858328) at ../../../../../../src/postgres/src/backend/executor/nodeAgg.c:2108
#8  ExecAgg (pstate=0x3858328) at ../../../../../../src/postgres/src/backend/executor/nodeAgg.c:1766
#9  0x00000000006ce5db in ExecProcNode (node=0x3858328) at ../../../../../../src/postgres/src/include/executor/executor.h:249
#10 ExecutePlan (execute_once=<optimized out>, dest=0x39400d0, direction=<optimized out>, numberTuples=0, sendTuples=<optimized out>, operation=CMD_SELECT, use_parallel_mode=<optimized out>, planstate=0x3858328,
    estate=0x3858118) at ../../../../../../src/postgres/src/backend/executor/execMain.c:1730
#11 standard_ExecutorRun (queryDesc=0x33c1118, direction=<optimized out>, count=0, execute_once=<optimized out>) at ../../../../../../src/postgres/src/backend/executor/execMain.c:367
#12 0x00007f47a890f8bd in pgss_ExecutorRun (queryDesc=0x33c1118, direction=ForwardScanDirection, count=0, execute_once=<optimized out>)
    at ../../../../../src/postgres/contrib/pg_stat_statements/pg_stat_statements.c:947
#13 0x00007f47a87083aa in ybpgm_ExecutorRun (queryDesc=0x33c1118, direction=ForwardScanDirection, count=0, execute_once=<optimized out>) at ../../../../../src/postgres/contrib/yb_pg_metrics/yb_pg_metrics.c:499
#14 0x000000000088564b in PortalRunSelect (portal=portal@entry=0x36b2118, forward=forward@entry=true, count=0, count@entry=9223372036854775807, dest=dest@entry=0x39400d0)
    at ../../../../../../src/postgres/src/backend/tcop/pquery.c:955
#15 0x0000000000887141 in PortalRun (portal=portal@entry=0x36b2118, count=count@entry=9223372036854775807, isTopLevel=isTopLevel@entry=true, run_once=run_once@entry=true, dest=dest@entry=0x39400d0,
    altdest=altdest@entry=0x39400d0, completionTag=0x7ffe807cab80 "") at ../../../../../../src/postgres/src/backend/tcop/pquery.c:784
#16 0x0000000000884ad8 in exec_simple_query (
    query_string=0x35ec118 "SELECT 'TG1', encode(ST_AsMVT(q, 'test', 4096, 'geom'), 'base64') FROM (SELECT 1 AS c1,\n\tST_AsMVTGeom(ST_GeomFromText('POINT(25 17)'),\n\t\tST_MakeBox2D(ST_Point(0, 0), ST_Point(4096, 4096)), 4096, 0, fa"..., query_string@entry=0x7ffe807cab00 "\030!k\003") at ../../../../../../src/postgres/src/backend/tcop/postgres.c:1161
#17 yb_exec_simple_query_impl (query_string=query_string@entry=0x35ec118) at ../../../../../../src/postgres/src/backend/tcop/postgres.c:4434
#18 0x000000000087f8b8 in yb_exec_query_wrapper (exec_context=exec_context@entry=0x35ec000, restart_data=restart_data@entry=0x7ffe807cad50, functor=functor@entry=0x884620 <yb_exec_simple_query_impl>,
    functor_context=functor_context@entry=0x35ec118) at ../../../../../../src/postgres/src/backend/tcop/postgres.c:4419
#19 0x00000000008802ec in yb_exec_simple_query (
    query_string=query_string@entry=0x35ec118 "SELECT 'TG1', encode(ST_AsMVT(q, 'test', 4096, 'geom'), 'base64') FROM (SELECT 1 AS c1,\n\tST_AsMVTGeom(ST_GeomFromText('POINT(25 17)'),\n\t\tST_MakeBox2D(ST_Point(0, 0), ST_Point(4096, 4096)), 4096, 0, fa"..., exec_context=exec_context@entry=0x35ec000) at ../../../../../../src/postgres/src/backend/tcop/postgres.c:4449
#20 0x0000000000882213 in PostgresMain (argc=<optimized out>, argv=argv@entry=0x35e7980, dbname=0x35e7818 "postgis_reg", username=0x35e77f8 "yugabyte")
    at ../../../../../../src/postgres/src/backend/tcop/postgres.c:5084
#21 0x000000000049e292 in BackendRun (port=0x34d6960) at ../../../../../../src/postgres/src/backend/postmaster/postmaster.c:4470
#22 BackendStartup (port=0x34d6960) at ../../../../../../src/postgres/src/backend/postmaster/postmaster.c:4136
#23 ServerLoop () at ../../../../../../src/postgres/src/backend/postmaster/postmaster.c:1754
#24 0x00000000007ea21f in PostmasterMain (argc=argc@entry=23, argv=argv@entry=0x33b0000) at ../../../../../../src/postgres/src/backend/postmaster/postmaster.c:1417
#25 0x000000000073588a in PostgresServerProcessMain (argc=23, argv=0x33b0000) at ../../../../../../src/postgres/src/backend/main/main.c:234
#26 0x0000000000735a89 in main ()
```

Coredump: [core.2023.zip](https://github.com/yugabyte/yugabyte-db/files/7988171/core.2023.zip)

**Comment by andrei-mart** [comment]
Can not reproduce
```
yugabyte=# SELECT 'TG1', encode(ST_AsMVT(q, 'test', 4096, 'geom'), 'base64') FROM (SELECT 1 AS c1,
yugabyte(#                 ST_AsMVTGeom(ST_GeomFromText('POINT(25 17)'),
yugabyte(#                         ST_MakeBox2D(ST_Point(0, 0), ST_Point(4096, 4096)), 4096, 0, false) AS geom) AS q;
 ?column? |                      encode                      
----------+--------------------------------------------------
 TG1      | GiEKBHRlc3QSDBICAAAYASIECTLePxoCYzEiAigBKIAgeAI=
(1 row)
```
also see https://github.com/yugabyte/yugabyte-db/issues/11318#issuecomment-1040875605

**Comment by def-** [comment]
See my comment for full instructions: https://github.com/yugabyte/yugabyte-db/issues/11318#issuecomment-1042798619
Can still reproduce with:
```
$ PATH=$PWD/bin:/usr/pgsql-11/bin:$PATH POSTGIS_SCRIPTDIR=/usr/pgsql-11/share/contrib/postgis-3.1 ./run_test.pl core/mvt.sql
```
