### ISSUE TITLE
[DocDB] RPC Failure in master can lead to infinite loop 

### ISSUE THREAD

**Issue by ajcaldera1** [yugabyte/yugabyte-db#11344]
### Description

This issue came up while processing a catalog request on the master. The database in question has a very high number of objects (>67000). The request times out on the client, but the master drops a core file. This is the thread it was focused on.

```
Thread 1 (LWP 14541):
#0  0x00007f4aea9455d7 in _IO_vfprintf_internal (s=s@entry=0x7f4acbc09450, format=format@entry=0x7f4aefd621ee "%d", ap=ap@entry=0x7f4acbc095d8) at vfprintf.c:1267
#1  0x00007f4aea96c049 in _IO_vsnprintf (string=0x7f4acbc095b0 "", maxlen=<optimized out>, format=0x7f4aefd621ee "%d", args=0x7f4acbc095d8) at vsnprintf.c:114
#2  0x00007f4afaf3a15d in __gnu_cxx::__to_xstring<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char> (__convf=<optimized out>,
    __n=<optimized out>, __fmt=<optimized out>)
    at /home/yugabyte/yb-software/yugabyte-2.11.2.0-b54-centos-x86_64/linuxbrew-xxxxxxxxxxxx/Cellar/gcc/5.5.0_4/include/c++/5.5.0/ext/string_conversions.h:95
#3  0x00007f4aefd0e616 in to_string (__val=<optimized out>)
    at /home/yugabyte/yb-software/yugabyte-2.11.2.0-b54-centos-x86_64/linuxbrew-xxxxxxxxxxxx/Cellar/gcc/5.5.0_4/include/c++/5.5.0/bits/basic_string.h:5404
#4  yb::Status::ToString[abi:cxx11](bool, bool) const (this=this@entry=0x7f4acbc09920, include_file_and_line=include_file_and_line@entry=true, include_code=include_code@entry=true)
    at ../../src/yb/util/status.cc:448
#5  0x00007f4af0bee4b0 in yb::rpc::YBInboundCall::RespondFailure (this=0x1d07810, error_code=yb::rpc::ErrorStatusPB_RpcErrorCodePB_ERROR_APPLICATION, status=...)
    at ../../src/yb/rpc/yb_rpc.cc:453
#6  0x00007f4af0bee1ed in yb::rpc::YBInboundCall::Respond (this=0x1d07810, response=..., is_success=<optimized out>) at ../../src/yb/rpc/yb_rpc.cc:484
#7  0x00007f4af0bee55b in yb::rpc::YBInboundCall::RespondFailure (this=0x1d07810, error_code=yb::rpc::ErrorStatusPB_RpcErrorCodePB_ERROR_APPLICATION, status=...)
    at ../../src/yb/rpc/yb_rpc.cc:456
<snip>
#34780 0x00007f4af0bee1ed in yb::rpc::YBInboundCall::Respond (this=0x1d07810, response=..., is_success=<optimized out>) at ../../src/yb/rpc/yb_rpc.cc:484
#34781 0x00007f4af0bee55b in yb::rpc::YBInboundCall::RespondFailure (this=0x1d07810, error_code=yb::rpc::ErrorStatusPB_RpcErrorCodePB_ERROR_APPLICATION, status=...)
    at ../../src/yb/rpc/yb_rpc.cc:456
#34782 0x00007f4af0bee1ed in yb::rpc::YBInboundCall::Respond (this=0x1d07810, response=..., is_success=<optimized out>) at ../../src/yb/rpc/yb_rpc.cc:484
#34783 0x00007f4af0bee55b in yb::rpc::YBInboundCall::RespondFailure (this=0x1d07810, error_code=yb::rpc::ErrorStatusPB_RpcErrorCodePB_ERROR_APPLICATION, status=...)
    at ../../src/yb/rpc/yb_rpc.cc:456
#34784 0x00007f4af0bee1ed in yb::rpc::YBInboundCall::Respond (this=0x1d07810, response=..., is_success=<optimized out>) at ../../src/yb/rpc/yb_rpc.cc:484
#34785 0x00007f4af0bea25c in yb::rpc::YBInboundCall::RespondSuccess (this=0x1d07810, response=...) at ../../src/yb/rpc/yb_rpc.cc:446
#34786 0x00007f4af0bae224 in yb::rpc::RpcContext::RespondSuccess (this=0xc85ce50) at ../../src/yb/rpc/rpc_context.cc:162
#34787 0x00007f4afa68767b in operator() (status=..., __closure=<optimized out>) at ../../src/yb/tserver/service_util.h:193
#34788 yb::tserver::TabletServiceImpl::CompleteRead (this=this@entry=0x137c000, read_context=read_context@entry=0x936d890) at ../../src/yb/tserver/tablet_service.cc:2321
#34789 0x00007f4afa688ddd in yb::tserver::TabletServiceImpl::Read (this=0x137c000, req=0x1cec9b8, resp=0x1ceca60, context=...) at ../../src/yb/tserver/tablet_service.cc:2229
#34790 0x00007f4af64bfca6 in operator() (rpc_context=..., resp=0x1ceca60, req=0x1cec9b8, __closure=<synthetic pointer>) at src/yb/tserver/tserver_service.service.cc:483
#34791 yb::rpc::HandleCall<yb::rpc::RpcCallPBParamsImpl<yb::tserver::ReadRequestPB, yb::tserver::ReadResponsePB>, yb::tserver::TabletServerServiceIf::InitMethods(const scoped_refptr<yb::MetricEntity>&)::<lambda(yb::rpc::InboundCallPtr)>::<lambda(const yb::tserver::ReadRequestPB*, yb::tserver::ReadResponsePB*, yb::rpc::RpcContext)> >(yb::rpc::InboundCallPtr, yb::tserver::TabletServerServiceIf::<lambda(yb::rpc::InboundCallPtr)>::<lambda(const yb::tserver::ReadRequestPB*, yb::tserver::ReadResponsePB*, yb::rpc::RpcContext)>) (call=..., f=...)
    at ../../src/yb/rpc/local_call.h:122
#34792 0x00007f4af64bfe5d in operator() (call=..., __closure=0x137c100) at src/yb/tserver/tserver_service.service.cc:484
#34793 std::_Function_handler<void(std::shared_ptr<yb::rpc::InboundCall>), yb::tserver::TabletServerServiceIf::InitMethods(const scoped_refptr<yb::MetricEntity>&)::<lambda(yb::rpc::InboundCallPtr)> >::_M_invoke(const std::_Any_data &, <unknown type in /home/yugabyte/yb-software/yugabyte-2.11.2.0-b54-centos-x86_64/lib/yb/libtserver_service_proto.so, CU 0x6ad5d, DIE 0x13d83a>) (__functor=..., __args#0=<optimized out>)
    at /home/yugabyte/yb-software/yugabyte-2.11.2.0-b54-centos-x86_64/linuxbrew-xxxxxxxxxxxx/Cellar/gcc/5.5.0_4/include/c++/5.5.0/functional:1871
#34794 0x00007f4af64b5204 in operator() (__args#0=<error reading variable: access outside bounds of object referenced via synthetic pointer>, this=<optimized out>)
    at /home/yugabyte/yb-software/yugabyte-2.11.2.0-b54-centos-x86_64/linuxbrew-xxxxxxxxxxxx/Cellar/gcc/5.5.0_4/include/c++/5.5.0/functional:2267
#34795 yb::tserver::TabletServerServiceIf::Handle (this=<optimized out>, call=...) at src/yb/tserver/tserver_service.service.cc:451
#34796 0x00007f4af0bd293e in yb::rpc::ServicePoolImpl::Handle (this=0x11a18c0, incoming=...) at ../../src/yb/rpc/service_pool.cc:269
#34797 0x00007f4af0b74b64 in yb::rpc::InboundCall::InboundCallTask::Run (this=<optimized out>) at ../../src/yb/rpc/inbound_call.cc:223
#34798 0x00007f4af0be6588 in yb::rpc::(anonymous namespace)::Worker::Execute (this=<optimized out>) at ../../src/yb/rpc/thread_pool.cc:104
#34799 0x00007f4aefd28635 in operator() (this=0xc8376d8)
    at /home/yugabyte/yb-software/yugabyte-2.11.2.0-b54-centos-x86_64/linuxbrew-xxxxxxxxxxxx/Cellar/gcc/5.5.0_4/include/c++/5.5.0/functional:2267
#34800 yb::Thread::SuperviseThread (arg=0xc837680) at ../../src/yb/util/thread.cc:774
#34801 0x00007f4aeb2a8694 in start_thread (arg=0x7f4acc408700) at pthread_create.c:333
#34802 0x00007f4aea9e541d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```
It looks like this may have been part of #10857. Full backtrace attached.
[bt_core_rpc_tp_master.log](https://github.com/yugabyte/yugabyte-db/files/7991367/bt_core_rpc_tp_master.log)

**Comment by amitanandaiyer** [comment]
```
(gdb) frame 16
#16 0x00007fe717b501ed in yb::rpc::YBInboundCall::Respond (this=0x465a610, response=..., is_success=<optimized out>)
    at ../../src/yb/rpc/yb_rpc.cc:484
484	in ../../src/yb/rpc/yb_rpc.cc
(gdb) locals
Undefined command: "locals".  Try "help".
(gdb) p locals
No symbol "locals" in current context.
(gdb) info locals
s = {state_ = {px = 0x11ba5180}}
(gdb) info args
this = 0x465a610
response = {<yb::rpc::AnyMessagePtrBase<google::protobuf::Message const*, yb::rpc::LightweightMessage const*>> = {
    message_ = 140630099911584}, <No data fields>}
is_success = <optimized out>
(gdb) p s
$8 = {state_ = {px = 0x11ba5180}}
(gdb) p s.state_
$9 = {px = 0x11ba5180}
(gdb) p s.state_.code
There is no member or method named code.
(gdb) p s.state_
$10 = {px = 0x11ba5180}
(gdb) p s.state_.px
$11 = (yb::Status::State *) 0x11ba5180
(gdb) p *s.state_.px
$12 = {counter = {<std::__atomic_base<unsigned long>> = {static _S_alignment = 8, _M_i = 1}, <No data fields>}, message_len = 46,
  code = 4 '\004', file_name = 0x7fe717b69990 "../../src/yb/rpc/serialization.cc", line_number = 74, message = "S"}
(gdb)
```



seems to be caused here
```
if (total_size > FLAGS_rpc_max_message_size) {
    return STATUS_FORMAT(InvalidArgument, "Sending too long RPC message ($0 bytes)", total_size);
  }
  ```
