### ISSUE TITLE
[DocDB] TestWipeNode fails with 'All host(s) tried for query failed'

### ISSUE THREAD

**Issue by tedyu** [yugabyte/yugabyte-db#11368]
Jira Link: [DB-1148](https://yugabyte.atlassian.net/browse/DB-1148)
### Description

As of commit 3176514348471b63f4065264fad8aca7e7a6ffa3, TestWipeNode fails with `All host(s) tried for query failed`
```
[ERROR] org.yb.cql.TestWipeNode.testWipeTserver  Time elapsed: 6.762 s  <<< ERROR!
com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (no host was tried)
    at org.yb.cql.TestWipeNode.writeRows(TestWipeNode.java:55)
    at org.yb.cql.TestWipeNode.testWipeTserver(TestWipeNode.java:120)
```
I got the above in debug build. I haven't tried other build types.

[DB-1148]: https://yugabyte.atlassian.net/browse/DB-1148?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DB-1148]: https://yugabyte.atlassian.net/browse/DB-1148?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
https://detective-gcp.dev.yugabyte.com/stability/test?branch=master&build_type=all&class=org.yb.cql.TestWipeNode&fail_tag=all&name=testWipeTserver&platform=all

**Comment by rthallamko3** [comment]
```


09/02/2022 11:33 | alma8-master-clang13-release/263/ |   | java.lang.Exception: Operation timed out after 10000ms
-- | -- | -- | --
09/01/2022 14:33 | centos-master-clang12-tsan/872/ |   | java.lang.Exception: Operation timed out after 30000ms
08/31/2022 21:33 | alma8-master-clang12-asan/1220/ |   | java.lang.Exception: Operation timed out after 15000ms

09/02/2022 11:33	[alma8-master-clang13-release/263/](https://jenkins.dev.yugabyte.com/job/github-yugabyte-db-alma8-master-clang13-release/263/)		java.lang.Exception: Operation timed out after 10000ms
09/01/2022 14:33	[centos-master-clang12-tsan/872/](https://jenkins.dev.yugabyte.com/job/github-yugabyte-db-centos-master-clang12-tsan/872/)		java.lang.Exception: Operation timed out after 30000ms
08/31/2022 21:33	[alma8-master-clang12-asan/1220/](https://jenkins.dev.yugabyte.com/job/github-yugabyte-db-alma8-master-clang12-asan/1220/)		java.lang.Exception: Operation timed out after 15000ms
```
