### ISSUE TITLE
[YSQL] Postgres process crash when specifying incorrect node IP

### ISSUE THREAD

**Issue by ttyusupov** [yugabyte/yugabyte-db#11390]
Jira Link: [DB-828](https://yugabyte.atlassian.net/browse/DB-828)
### Description

`postgres` process crashes with core dump when specifying node IP without `postgres` process? For example:
```
# Create RF=1 cluster
$ ./bin/yb-ctl create
$ ./bin/ysqlsh -h 127.0.0.2
ysqlsh: could not connect to server: Connection refused
	Is the server running on host "127.0.0.2" and accepting
	TCP/IP connections on port 5433?
$ ls -l ~/cores/
total 169928
-rw-------. 1 timur ybdev 243900416 Feb  8 14:42 core.postgres.19702.dev-server-timur.1644331370
```

Thread dump from core file:
```
Core was generated by `/nfusr/dev-server/timur/code/yugabyte-db/build/release-clang12-linuxbrew-dynami'.
Program terminated with signal 11, Segmentation fault.
#0  yb::SharedMemorySegment::GetAddress() const (this=0x0) at ../../src/yb/util/shared_mem.cc:267
267	  return base_address_;
(gdb) bt
#0  yb::SharedMemorySegment::GetAddress() const (this=0x0) at ../../src/yb/util/shared_mem.cc:267
#1  0x00007f3a0adaab7b in get (this=0x0) at ../../src/yb/util/shared_mem.h:88
#2  operator* (this=0x0) at ../../src/yb/util/shared_mem.h:96
#3  Start (this=0x1436900, proxy_cache=<optimized out>, scheduler=<optimized out>, tserver_shared_object=...) at ../../src/yb/yql/pggate/pg_client.cc:61
#4  yb::pggate::PgClient::Start(yb::rpc::ProxyCache*, yb::rpc::Scheduler*, yb::SharedMemoryObject<yb::tserver::TServerSharedData> const&) (this=<optimized out>, proxy_cache=0x1453080, scheduler=0x15bc278,
    tserver_shared_object=...) at ../../src/yb/yql/pggate/pg_client.cc:302
#5  0x00007f3a0ad9d88b in yb::pggate::PgApiImpl::PgApiImpl(yb::pggate::PgApiContext, PgTypeEntity const*, int, PgCallbacks) (this=<optimized out>, context=..., YBCDataTypeArray=<optimized out>, count=161, callbacks=...)
    at ../../src/yb/yql/pggate/pggate.cc:262
#6  0x00007f3a0ad904ef in yb::pggate::YBCInitPgGateEx(PgTypeEntity const*, int, PgCallbacks, yb::pggate::PgApiContext*) (data_type_table=0x349980 <YbTypeEntityTable>, count=161, pg_callbacks=..., context=<optimized out>)
    at ../../src/yb/yql/pggate/ybc_pggate.cc:115
#7  0x00007f3a0ad9095c in YBCInitPgGate (data_type_table=0x0, count=22352104, pg_callbacks=...) at ../../src/yb/yql/pggate/ybc_pggate.cc:123
#8  0x0000000000b03a4f in YBInitPostgresBackend (program_name=<optimized out>, db_name=0x334f49 "", user_name=0x0) at ../../../../../../../src/postgres/src/backend/utils/misc/pg_yb_utils.c:497
#9  0x0000000000ae5b1a in InitPostgres (in_dbname=0x0, dboid=0, username=0x0, useroid=0, out_dbname=0x0, override_allow_connections=false)
    at /nfusr/dev-server/timur/code/yugabyte-db/src/postgres/src/backend/utils/cache/../../../../../../../src/postgres/src/backend/utils/cache/relcache.c:4143
#10 0x00000000005b0260 in BootstrapModeMain () at ../../../../../../src/postgres/src/backend/bootstrap/bootstrap.c:509
#11 0x00000000005affd9 in AuxiliaryProcessMain (argc=<optimized out>, argv=0x1565d88) at ../../../../../../src/postgres/src/backend/bootstrap/bootstrap.c:442
#12 0x00000000007ac7e4 in PostgresServerProcessMain (argc=6, argv=0x1565d80) at ../../../../../../src/postgres/src/backend/main/main.c:226
#13 0x00000000004de3b2 in main ()
```

**Comment by sushantrmishra** [comment]
Tried on latest master with the following commit but no core file generated.

```
commit 2e2a33490b0650751d2c30cc4a912925c4fb2163 (HEAD -> master, origin/master, origin/HEAD)
Author: Jethro Mak <88681329+Jethro-M@users.noreply.github.com>
Date:   Thu Oct 20 17:21:23 2022 -0400

    [PLAT-5822] Update xCluster config actions interfaces
```

./bin/ysqlsh -h 120.0.0.2
ysqlsh: could not connect to server: Connection timed out
        Is the server running on host "120.0.0.2" and accepting
        TCP/IP connections on port 5433?
      
./bin/ysqlsh -h 127.0.0.2
ysqlsh: could not connect to server: Connection refused
        Is the server running on host "127.0.0.2" and accepting
        TCP/IP connections on port 5433?


 @ttyusupov Feel free to reopen the issue if you still able to reproduce it.
