### ISSUE TITLE
[YSQL][postgres_fdw] Segmentation fault in IsYBRelation(relation=0x0) in EXPLAIN

### ISSUE THREAD

**Issue by def-** [yugabyte/yugabyte-db#11417]
### Description

Can be reproduced reliably:
```
CREATE EXTENSION postgres_fdw;

CREATE SERVER testserver1 FOREIGN DATA WRAPPER postgres_fdw;
DO $d$
    BEGIN
        EXECUTE $$CREATE SERVER loopback FOREIGN DATA WRAPPER postgres_fdw
            OPTIONS (dbname '$$||current_database()||$$',
                     port '$$||current_setting('port')||$$'
            )$$;
        EXECUTE $$CREATE SERVER loopback2 FOREIGN DATA WRAPPER postgres_fdw
            OPTIONS (dbname '$$||current_database()||$$',
                     port '$$||current_setting('port')||$$'
            )$$;
    END;
$d$;

CREATE USER MAPPING FOR public SERVER testserver1
OPTIONS (user 'value', password 'value');
CREATE USER MAPPING FOR CURRENT_USER SERVER loopback;
CREATE USER MAPPING FOR CURRENT_USER SERVER loopback2;

CREATE TYPE user_enum AS ENUM ('foo', 'bar', 'buz');
CREATE SCHEMA "S 1";
CREATE TABLE "S 1"."T 1" (
"C 1" int NOT NULL,
c2 int NOT NULL,
c3 text,
c4 timestamptz,
c5 timestamp,
c6 varchar(10),
c7 char(10),
c8 user_enum,
CONSTRAINT t1_pkey PRIMARY KEY ("C 1")
);
CREATE TABLE "S 1"."T 2" (
c1 int NOT NULL,
c2 text,
CONSTRAINT t2_pkey PRIMARY KEY (c1)
);
CREATE TABLE "S 1"."T 3" (
c1 int NOT NULL,
c2 int NOT NULL,
c3 text,
CONSTRAINT t3_pkey PRIMARY KEY (c1)
);

CREATE FOREIGN TABLE ft1 (
c0 int,
c1 int OPTIONS (column_name 'C 1') NOT NULL,
c2 int NOT NULL,
c3 text,
c4 timestamptz,
c5 timestamp,
c6 varchar(10),
c7 char(10) default 'ft1',
c8 user_enum
) SERVER loopback OPTIONS (schema_name 'S 1', table_name 'T 1');
ALTER FOREIGN TABLE ft1 DROP COLUMN c0;

CREATE FOREIGN TABLE ft2 (
c1 int OPTIONS (column_name 'C 1') NOT NULL,
c2 int NOT NULL,
cx int,
c3 text,
c4 timestamptz,
c5 timestamp,
c6 varchar(10),
c7 char(10) default 'ft2',
c8 user_enum
) SERVER loopback OPTIONS (schema_name 'S 1', table_name 'T 1', use_remote_estimate 'true');
ALTER FOREIGN TABLE ft2 DROP COLUMN cx;

EXPLAIN (VERBOSE, COSTS OFF)
SELECT t1."C 1" FROM "S 1"."T 1" t1 left join ft1 t2 join ft2 t3 on (t2.c1 = t3.c1) on (t3.c1 = t1."C 1") OFFSET 100 LIMIT 10;
```
Backtrace from coredump:
```
Core was generated by `postgres: yugabyte yugabyte 127.0.0.1(44314) EXPLAIN                          '.
Program terminated with signal 11, Segmentation fault.
b#0  IsYBRelation (relation=0x0) at /nfusr/dev-server/dfelsing/code/yugabyte-db/src/postgres/src/backend/utils/misc/../../../../../../../src/postgres/src/backend/utils/misc/pg_yb_utils.c:125
125	/nfusr/dev-server/dfelsing/code/yugabyte-db/src/postgres/src/backend/utils/misc/../../../../../../../src/postgres/src/backend/utils/misc/pg_yb_utils.c: No such file or directory.
(gdb) bt
#0  IsYBRelation (relation=0x0) at /nfusr/dev-server/dfelsing/code/yugabyte-db/src/postgres/src/backend/utils/misc/../../../../../../../src/postgres/src/backend/utils/misc/pg_yb_utils.c:125
#1  ExplainNode (planstate=0x31ee7d8, ancestors=0x329bc88, relationship=0x2da671 "Outer", plan_name=0x0, es=0x30f8c38) at ../../../../../../src/postgres/src/backend/commands/explain.c:1111
#2  0x000000000069c21a in ExplainNode (planstate=0x31ee518, ancestors=0x329bc88, relationship=<optimized out>, plan_name=0x30f8c48 "", es=0x30f8c38)
    at ../../../../../../src/postgres/src/backend/commands/explain.c:1896
#3  0x000000000069c21a in ExplainNode (planstate=0x31ee328, ancestors=0x329bc88, relationship=<optimized out>, plan_name=0x30f8c48 "", es=0x30f8c38)
    at ../../../../../../src/postgres/src/backend/commands/explain.c:1896
#4  0x00000000006931c6 in ExplainPrintPlan (es=0x30f8c38, queryDesc=0x329a1b8) at ../../../../../../src/postgres/src/backend/commands/explain.c:637
#5  0x00000000006929f1 in ExplainOnePlan (plannedstmt=0x329a0a8, into=0x0, es=0x30f8c38, queryString=0x0, params=<optimized out>, queryEnv=<optimized out>, planduration=0x7fffd5748ac8)
    at ../../../../../../src/postgres/src/backend/commands/explain.c:548
#6  0x00000000006923e1 in ExplainOneQuery (query=<optimized out>, cursorOptions=<optimized out>, into=0x0, es=0x30f8c38, queryString=0x0, params=0x0, queryEnv=0x0)
    at ../../../../../../src/postgres/src/backend/commands/explain.c:372
#7  0x0000000000691daf in ExplainQuery (pstate=<optimized out>, stmt=0x322d278,
    queryString=0x2f98118 "EXPLAIN (VERBOSE, COSTS OFF)\nSELECT t1.\"C 1\" FROM \"S 1\".\"T 1\" t1 left join ft1 t2 join ft2 t3 on (t2.c1 = t3.c1) on (t3.c1 = t1.\"C 1\") OFFSET 100 LIMIT 10;", params=0x0,
    queryEnv=0x0, dest=0x368aa40) at ../../../../../../src/postgres/src/backend/commands/explain.c:255
#8  0x000000000093d28a in standard_ProcessUtility (pstmt=0x322d328,
    queryString=0x2f98118 "EXPLAIN (VERBOSE, COSTS OFF)\nSELECT t1.\"C 1\" FROM \"S 1\".\"T 1\" t1 left join ft1 t2 join ft2 t3 on (t2.c1 = t3.c1) on (t3.c1 = t1.\"C 1\") OFFSET 100 LIMIT 10;",
    context=PROCESS_UTILITY_TOPLEVEL, params=0x0, queryEnv=0x0, dest=0x368aa40, completionTag=0x7fffd57490d0 "") at ../../../../../../src/postgres/src/backend/tcop/utility.c:699
#9  0x00007fb8367e8890 in pgss_ProcessUtility (pstmt=0x31ee701,
    queryString=0x2f98118 "EXPLAIN (VERBOSE, COSTS OFF)\nSELECT t1.\"C 1\" FROM \"S 1\".\"T 1\" t1 left join ft1 t2 join ft2 t3 on (t2.c1 = t3.c1) on (t3.c1 = t1.\"C 1\") OFFSET 100 LIMIT 10;",
    context=PROCESS_UTILITY_TOPLEVEL, params=0x0, queryEnv=0x0, dest=0x368aa40, completionTag=0x7fffd57490d0 "") at ../../../../../src/postgres/contrib/pg_stat_statements/pg_stat_statements.c:1056
#10 0x00007fb8367df837 in ybpgm_ProcessUtility (pstmt=0x31ee701,
    queryString=0x2f98118 "EXPLAIN (VERBOSE, COSTS OFF)\nSELECT t1.\"C 1\" FROM \"S 1\".\"T 1\" t1 left join ft1 t2 join ft2 t3 on (t2.c1 = t3.c1) on (t3.c1 = t1.\"C 1\") OFFSET 100 LIMIT 10;",
    context=PROCESS_UTILITY_TOPLEVEL, params=0x0, queryEnv=0x0, dest=0x368aa40, completionTag=0x7fffd57490d0 "") at ../../../../../src/postgres/contrib/yb_pg_metrics/yb_pg_metrics.c:682
#11 0x00007fb8367c3fbe in pg_hint_plan_ProcessUtility (pstmt=0x31ee701, queryString=0x0, context=2991729, params=0x0, queryEnv=0x0, dest=0x12, completionTag=0x7fffd57490d0 "")
    at ../../../../../src/postgres/third-party-extensions/pg_hint_plan/pg_hint_plan.c:3033
#12 0x0000000000b03c6f in YBTxnDdlProcessUtility (pstmt=0x322d328,
    queryString=0x2f98118 "EXPLAIN (VERBOSE, COSTS OFF)\nSELECT t1.\"C 1\" FROM \"S 1\".\"T 1\" t1 left join ft1 t2 join ft2 t3 on (t2.c1 = t3.c1) on (t3.c1 = t1.\"C 1\") OFFSET 100 LIMIT 10;",
    context=PROCESS_UTILITY_TOPLEVEL, params=0x0, queryEnv=0x0, dest=0x368aa40, completionTag=0x7fffd57490d0 "") at ../../../../../../../src/postgres/src/backend/utils/misc/pg_yb_utils.c:1365
#13 0x000000000093c094 in PortalRunUtility (portal=0x3076118, pstmt=0x322d328, isTopLevel=<optimized out>, setHoldSnapshot=<optimized out>, dest=0x12, completionTag=0x7fffd57490d0 "")
    at ../../../../../../src/postgres/src/backend/tcop/utility.c:374
#14 0x000000000093b7fd in FillPortalStore (portal=0x3076118, isTopLevel=true) at ../../../../../../src/postgres/src/backend/tcop/pquery.c:1061
#15 0x000000000093b3f4 in PortalRun (portal=0x3076118, count=9223372036854775807, isTopLevel=true, run_once=<optimized out>, dest=0x2f99f58, altdest=0x2f99f58, completionTag=0x7fffd57492b0 "")
    at ../../../../../../src/postgres/src/backend/tcop/pquery.c:779
#16 0x0000000000937776 in yb_exec_simple_query_impl (query_string=0x2f98118) at ../../../../../../src/postgres/src/backend/tcop/postgres.c:1161
#17 0x0000000000937e4e in yb_exec_query_wrapper (exec_context=0x2f98000, restart_data=<optimized out>, functor=0x936ed0 <yb_exec_simple_query_impl>, functor_context=0x2f98118)
    at ../../../../../../src/postgres/src/backend/tcop/postgres.c:4445
#18 0x000000000093472d in PostgresMain (argc=1, argv=<optimized out>, dbname=<optimized out>, username=0x2f79378 "yugabyte") at ../../../../../../src/postgres/src/backend/tcop/postgres.c:4479
#19 0x000000000089013b in BackendRun (port=0x2e121e0) at ../../../../../../src/postgres/src/backend/postmaster/postmaster.c:4470
#20 0x000000000088f872 in ServerLoop () at ../../../../../../src/postgres/src/backend/postmaster/postmaster.c:4136
#21 0x000000000088c0b1 in PostmasterMain (argc=<optimized out>, argv=0x2e286c0) at ../../../../../../src/postgres/src/backend/postmaster/postmaster.c:1417
#22 0x00000000007ac8d3 in PostgresServerProcessMain (argc=23, argv=0x2e286c0) at ../../../../../../src/postgres/src/backend/main/main.c:234
#23 0x00000000004de432 in main ()
```

**Comment by def-** [comment]
Also happens with:
```
EXPLAIN (VERBOSE, COSTS OFF)
  SELECT count(c3) FROM ft1 t1 WHERE t1.c1 = abs(t1.c2);
```

**Comment by andrei-mart** [comment]
Fixed by https://github.com/yugabyte/yugabyte-db/commit/205035e68785d3d1d8279d2e0ad91d91b22c2e68
