### ISSUE TITLE
[YSQL][postgres_fdw] Segmentation fault in MakeExpandedObjectReadOnlyInternal()

### ISSUE THREAD

**Issue by def-** [yugabyte/yugabyte-db#11426]
### Description

Can be reproduced:
```
CREATE EXTENSION postgres_fdw;

CREATE SERVER testserver1 FOREIGN DATA WRAPPER postgres_fdw;
DO $d$
    BEGIN
        EXECUTE $$CREATE SERVER loopback FOREIGN DATA WRAPPER postgres_fdw
            OPTIONS (dbname '$$||current_database()||$$',
                     port '$$||current_setting('port')||$$'
            )$$;
        EXECUTE $$CREATE SERVER loopback2 FOREIGN DATA WRAPPER postgres_fdw
            OPTIONS (dbname '$$||current_database()||$$',
                     port '$$||current_setting('port')||$$'
            )$$;
    END;
$d$;

CREATE USER MAPPING FOR public SERVER testserver1
OPTIONS (user 'value', password 'value');
CREATE USER MAPPING FOR CURRENT_USER SERVER loopback;
CREATE USER MAPPING FOR CURRENT_USER SERVER loopback2;

SET enable_partitionwise_join=on;

CREATE TABLE fprt1 (a int, b int, c varchar) PARTITION BY RANGE(a);
CREATE TABLE fprt1_p1 (a int, b int, c varchar);
CREATE TABLE fprt1_p2 (a int, b int, c varchar);
INSERT INTO fprt1_p1 SELECT i, i, to_char(i/50, 'FM0000') FROM generate_series(0, 249, 2) i;
INSERT INTO fprt1_p2 SELECT i, i, to_char(i/50, 'FM0000') FROM generate_series(250, 499, 2) i;
CREATE FOREIGN TABLE ftprt1_p1 PARTITION OF fprt1 FOR VALUES FROM (0) TO (250)
SERVER loopback OPTIONS (table_name 'fprt1_p1', use_remote_estimate 'true');
CREATE FOREIGN TABLE ftprt1_p2 PARTITION OF fprt1 FOR VALUES FROM (250) TO (500)
SERVER loopback OPTIONS (TABLE_NAME 'fprt1_p2');
ANALYZE fprt1;
ANALYZE fprt1_p1;
ANALYZE fprt1_p2;

CREATE TABLE fprt2 (a int, b int, c varchar) PARTITION BY RANGE(b);
CREATE TABLE fprt2_p1 (a int, b int, c varchar);
CREATE TABLE fprt2_p2 (a int, b int, c varchar);
INSERT INTO fprt2_p1 SELECT i, i, to_char(i/50, 'FM0000') FROM generate_series(0, 249, 3) i;
INSERT INTO fprt2_p2 SELECT i, i, to_char(i/50, 'FM0000') FROM generate_series(250, 499, 3) i;
CREATE FOREIGN TABLE ftprt2_p1 (b int, c varchar, a int)
SERVER loopback OPTIONS (table_name 'fprt2_p1', use_remote_estimate 'true');
ALTER TABLE fprt2 ATTACH PARTITION ftprt2_p1 FOR VALUES FROM (0) TO (250);
CREATE FOREIGN TABLE ftprt2_p2 PARTITION OF fprt2 FOR VALUES FROM (250) TO (500)
SERVER loopback OPTIONS (table_name 'fprt2_p2', use_remote_estimate 'true');
ANALYZE fprt2;
ANALYZE fprt2_p1;
ANALYZE fprt2_p2;

SELECT t1.a, t2.b FROM fprt1 t1 INNER JOIN fprt2 t2 ON (t1.a = t2.b) WHERE t1.a % 25 = 0 ORDER BY 1,2 FOR UPDATE OF t1;
```
Backtrace from gdb:
```
Core was generated by `postgres: yugabyte yugabyte 127.0.0.1(47000) SELECT                           '.
Program terminated with signal 11, Segmentation fault.
#0  MakeExpandedObjectReadOnlyInternal (d=0) at /nfusr/dev-server/dfelsing/code/yugabyte-db/src/postgres/src/backend/utils/adt/../../../../../../../src/postgres/src/backend/utils/adt/expandeddatum.c:100
100	/nfusr/dev-server/dfelsing/code/yugabyte-db/src/postgres/src/backend/utils/adt/../../../../../../../src/postgres/src/backend/utils/adt/expandeddatum.c: No such file or directory.
(gdb) bt
#0  MakeExpandedObjectReadOnlyInternal (d=0) at /nfusr/dev-server/dfelsing/code/yugabyte-db/src/postgres/src/backend/utils/adt/../../../../../../../src/postgres/src/backend/utils/adt/expandeddatum.c:100
#1  ExecInterpExpr (state=<optimized out>, econtext=<optimized out>, isnull=0x7fffd5748c16) at ../../../../../../src/postgres/src/backend/executor/execExprInterp.c:643
#2  0x0000000000746fa2 in ExecScan (node=0x3439320, accessMtd=0x77a880 <ForeignNext>, recheckMtd=0x77a970 <ForeignRecheck>) at ../../../../../../src/postgres/src/include/executor/executor.h:321
#3  0x0000000000750b43 in ExecProcNode (node=0x3439320) at ../../../../../../src/postgres/src/include/executor/executor.h:249
#4  ExecAppend (pstate=0x3438e68) at ../../../../../../src/postgres/src/backend/executor/nodeAppend.c:294
#5  0x0000000000761b64 in ExecHashJoin (pstate=0x3438b78) at ../../../../../../src/postgres/src/include/executor/executor.h:249
#6  0x000000000077537e in ExecSort (pstate=0x3438a68) at ../../../../../../src/postgres/src/include/executor/executor.h:249
#7  0x0000000000767e24 in ExecProcNode (node=0x3438a68) at ../../../../../../src/postgres/src/include/executor/executor.h:249
#8  ExecLockRows (pstate=0x3438548) at ../../../../../../src/postgres/src/backend/executor/nodeLockRows.c:62
#9  0x000000000073a52e in standard_ExecutorRun (queryDesc=0x2e37118, direction=<optimized out>, count=0, execute_once=<optimized out>) at ../../../../../../src/postgres/src/include/executor/executor.h:249
#10 0x00007fb8367e8565 in pgss_ExecutorRun (queryDesc=0x2e37118, direction=ForwardScanDirection, count=0, execute_once=true) at ../../../../../src/postgres/contrib/pg_stat_statements/pg_stat_statements.c:947
#11 0x00007fb8367df3da in ybpgm_ExecutorRun (queryDesc=0x2e37118, direction=ForwardScanDirection, count=0, execute_once=true) at ../../../../../src/postgres/contrib/yb_pg_metrics/yb_pg_metrics.c:499
#12 0x000000000093b9c6 in PortalRunSelect (portal=0x3076118, forward=<optimized out>, count=0, dest=<optimized out>)
    at /nfusr/dev-server/dfelsing/code/yugabyte-db/src/postgres/src/backend/executor/../../../../../../src/postgres/src/backend/executor/execMain.c:305
#13 0x000000000093b4a6 in PortalRun (portal=0x3076118, count=9223372036854775807, isTopLevel=true, run_once=<optimized out>, dest=0x39ecda0, altdest=0x39ecda0, completionTag=0x7fffd57492b0 "")
    at ../../../../../../src/postgres/src/backend/tcop/pquery.c:784
#14 0x0000000000937776 in yb_exec_simple_query_impl (query_string=0x2f98118) at ../../../../../../src/postgres/src/backend/tcop/postgres.c:1161
#15 0x0000000000937e4e in yb_exec_query_wrapper (exec_context=0x2f98000, restart_data=<optimized out>, functor=0x936ed0 <yb_exec_simple_query_impl>, functor_context=0x2f98118)
    at ../../../../../../src/postgres/src/backend/tcop/postgres.c:4445
#16 0x000000000093472d in PostgresMain (argc=1, argv=<optimized out>, dbname=<optimized out>, username=0x2f79fe8 "yugabyte") at ../../../../../../src/postgres/src/backend/tcop/postgres.c:4479
#17 0x000000000089013b in BackendRun (port=0x2e121e0) at ../../../../../../src/postgres/src/backend/postmaster/postmaster.c:4470
#18 0x000000000088f872 in ServerLoop () at ../../../../../../src/postgres/src/backend/postmaster/postmaster.c:4136
#19 0x000000000088c0b1 in PostmasterMain (argc=<optimized out>, argv=0x2e286c0) at ../../../../../../src/postgres/src/backend/postmaster/postmaster.c:1417
#20 0x00000000007ac8d3 in PostgresServerProcessMain (argc=23, argv=0x2e286c0) at ../../../../../../src/postgres/src/backend/main/main.c:234
#21 0x00000000004de432 in main ()
```

**Comment by timothy-e** [comment]
This is still reproducible as of master commit f41f8cde8831c1dd8dc42f617178fa979643e547 (Jan 6, 2025)
