### ISSUE TITLE
[CDCSDK] Throw proper exception if CDC is deployed on a table without a primary key

### ISSUE THREAD

**Issue by vaibhav-yb** [yugabyte/yugabyte-db#11552]
Jira Link: [DB-4520](https://yugabyte.atlassian.net/browse/DB-4520)
Currently, if the user creates a table without a primary key, then creates a DB stream ID, and uses the same to stream data out of YugabyteDB using Debezium, he will receive an exception:

```
Table ID <> not a part of stream ID <>
```

This exception doesn't explain much as to what's actually wrong with the deployment and can mislead the users.

**Steps to reproduce:**
1. Create a table without primary key: `create table test (id int);`
2. Create a DB stream ID (assuming the table is in the namespace - yugabyte): `./yb-admin create_change_data_stream ysql.yugabyte`
3. Run Debezium and deploy a connector config for the table created above.

**Comment by huuhait** [comment]
same problem here

**Comment by vaibhav-yb** [comment]
Hi @huuhait The issue is noted and the plan to support CDC on tables without primary key is already in our roadmap. This ticket will be updated once we start working on it.

**Comment by huuhait** [comment]
> Hi @huuhait The issue is noted and the plan to support CDC on tables without primary key is already in our roadmap. This ticket will be updated once we start working on it.

my table've primary key but still get this error

```bash
debezium_1              | Caused by: org.yb.client.CDCErrorException: Server[b5b7281563fd4328ab6cb17296529f1e] INVALID_ARGUMENT[code 4]: Tablet ID 321d8cfa445744f7813b7769460ee228 is not part of stream ID dab7ebc09bcb4dd58281c6be0deab344
debezium_1              |       at org.yb.client.TabletClient.dispatchCDCErrorOrReturnException(TabletClient.java:508)
debezium_1              |       at org.yb.client.TabletClient.decode(TabletClient.java:439)
debezium_1              |       at org.yb.client.TabletClient.decode(TabletClient.java:100)
debezium_1              |       at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:500)
debezium_1              |       at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435)
debezium_1              |       at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
debezium_1              |       at org.yb.client.TabletClient.handleUpstream(TabletClient.java:651)
debezium_1              |       at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
debezium_1              |       at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
debezium_1              |       at org.jboss.netty.handler.timeout.ReadTimeoutHandler.messageReceived(ReadTimeoutHandler.java:184)
debezium_1              |       at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
debezium_1              |       at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
debezium_1              |       at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
debezium_1              |       at org.yb.client.AsyncYBClient$TabletClientPipeline.sendUpstream(AsyncYBClient.java:2503)
debezium_1              |       at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
debezium_1              |       at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
debezium_1              |       at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
debezium_1              |       at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
debezium_1              |       at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
debezium_1              |       at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
debezium_1              |       at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
debezium_1              |       at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
debezium_1              |       at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
debezium_1              |       ... 3 more
debezium_1              | 2022-05-17 10:28:56,559 INFO   ||  Stopping down connector   [io.debezium.connector.common.BaseSourceTask]
```

**Comment by vaibhav-yb** [comment]
@huuhait Can you please drop a message in our community slack channel (#topic-change-data-capture) with the steps you went through to get this error?

Community link: https://communityinviter.com/apps/yugabyte-db/register

**Comment by vaibhav-yb** [comment]
A troubleshooting point has been added in the documentation mentioning about the error message and possible scenarios when that can be thrown.
