### ISSUE TITLE
[YSQL] Prefer custom plans for prepared statements using partitioned tables if partition pruning is possible

### ISSUE THREAD

**Issue by deeps1991** [yugabyte/yugabyte-db#11617]
Jira Link: [DB-479](https://yugabyte.atlassian.net/browse/DB-479)
### Description

While trying to run Geopartitioned TPCC with local transaction tables, the TPCC run fails with the following error:

```
Caused by: org.postgresql.util.PSQLException: ERROR: Illegal state: Nonlocal tablet accessed in local transaction: tablet 78719c3d1937431d81f7ed6b3f626953: . Errors from tablet servers: [Illegal state (yb/client/transaction.cc:288): Nonlocal tablet accessed in local transaction: tablet 78719c3d1937431d81f7ed6b3f626953]
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2468)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2211)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:309)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:446)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:370)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:149)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:124)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
	at com.oltpbenchmark.jdbc.InstrumentedPreparedStatement.executeUpdate(InstrumentedPreparedStatement.java:49)
	at com.oltpbenchmark.benchmarks.tpcc.procedures.NewOrder.newOrderTransaction(NewOrder.java:314)
	at com.oltpbenchmark.benchmarks.tpcc.procedures.NewOrder.run(NewOrder.java:258)
	at com.oltpbenchmark.api.Worker.executeWork(Worker.java:612)
	at com.oltpbenchmark.api.Worker.doWork(Worker.java:506)
	... 2 more
```

By default, for a transaction, a local transaction tablet is chosen to coordinate the transaction. However if this transaction tries to access data that is not local to the current region, it will fail with the above error. 
However for Geopartitioned TPCC, all the tables in the schema are partitioned by warehouse-id, and for geopartitioned TPCC it is ensured that all the transactions only access the local partition.

Thus, the above error is not expected, as constraint exclusion/partition pruning should ensure that only the local partition is accessed.

After some investigation, I could see that normally partition pruning does indeed ensure most of the time that the query hits only the local partition. But in some rare cases, partition pruning does not happen and all the partitions of the table are accessed. In fact, changing the TPCC client to do a simple retry upon hitting the above exception even fixes the issue.

Our TPCC client normally uses prepared statements for all the queries in the transaction. Thus there are two types of plans for prepared statements - 
i) generic plan, that is made without delving into the values of the bound statements
ii) custom plan, one that is made by also taking the values of the bound statements into account.

I noticed whenever the above error hit, it was because the planner favored a  generic plan rather than custom plan. In a generic plan, since we do not know the values of the parameters, partition pruning cannot exclude any partitions because it cannot know that the partition constraint for some partitions will ensure that they do not have the data that satisfies the provided WHERE clause.

For example, note the following query on table DISTRICT which is partitioned on D_W_ID (I have 2 partitions in my test). Having a WHERE clause on D_W_ID means that we will definitely whittle down to a single partition.

```
2022-03-01 16:58:19.538 IST [34657] STATEMENT:  UPDATE DISTRICT SET D_NEXT_O_ID = D_NEXT_O_ID + 1  WHERE D_W_ID = $1    AND D_ID = $2
2022-03-01 16:58:19.538 IST [34657] LOG:  Generic cost :8.229000 Custom cost: 16.611500, using generic plan
2022-03-01 16:58:19.538 IST [34657] DETAIL:  parameters: $1 = '1', $2 = '2'
2022-03-01 16:58:19.544 IST [34657] ERROR:  Illegal state: Nonlocal tablet accessed in local transaction: tablet 78719c3d1937431d81f7ed6b3f626953: . Errors from tablet servers: [Illegal state (yb/client/transaction.cc:288): Nonlocal tablet accessed in local transaction: tablet 78719c3d1937431d81f7ed6b3f626953]
```

Similar behavior has happened for few other SELECT queries in TPCC as well.

 Ideally for queries on partitioned tables in YB, having a WHERE clause that will whittle down the partitions at plan time is guaranteed to always perform better than a generic plan simply because of the reduction in the number of queries and tables accessed.

Opening this ticket to track why the planner decides that a generic plan is cheaper than a custom plan.

**Comment by deeps1991** [comment]
Digging deeper into the issue, the following code picks a generic plan over a custom plan if it determines that the generic plan is cheaper:

```
static bool                                                                     
  choose_custom_plan(CachedPlanSource *plansource, ParamListInfo boundParams)     
  {                 
     .....
     .....
     .....
     avg_custom_cost = plansource->total_custom_cost / plansource->num_custom_plans;
                                                                                  
      /*                                                                          
       * Prefer generic plan if it's less expensive than the average custom       
       * plan.  (Because we include a charge for cost of planning in the          
       * custom-plan costs, this means the generic plan only has to be less       
       * expensive than the execution cost plus replan cost of the custom         
       * plans.)                                                                  
       *                                                                          
       * Note that if generic_cost is -1 (indicating we've not yet determined     
       * the generic plan cost), we'll always prefer generic at this point.       
       */                                                                         
       if (plansource->generic_cost < avg_custom_cost)                             
          return false; 
      return true;
  }           
```

Since Postgres chooses to use a custom plan for the first five times, I ran the query 6 times with EXPLAIN to see the costs involved in both types of plans.

Custom Plan:
```
yugabyte=# EXPLAIN (ANALYZE) EXECUTE mystmt(3618.2900390625, 1);
                                                             QUERY PLAN                                                             
------------------------------------------------------------------------------------------------------------------------------------
 Update on warehouse  (cost=0.00..4.11 rows=1 width=648) (actual time=2.065..2.065 rows=0 loops=1)
   Update on warehouse1
   ->  Index Scan using warehouse1_pkey on warehouse1  (cost=0.00..4.11 rows=1 width=648) (actual time=1.944..1.949 rows=1 loops=1)
         Index Cond: (w_id = 1)
 Planning Time: 0.300 ms
 Execution Time: 5.608 ms
(6 rows)

```

Generic Plan:
```
yugabyte=# EXPLAIN (ANALYZE) EXECUTE mystmt(3618.2900390625, 1);
                                                             QUERY PLAN                                                             
------------------------------------------------------------------------------------------------------------------------------------
 Update on warehouse  (cost=0.00..8.23 rows=2 width=648) (actual time=12.575..12.575 rows=0 loops=1)
   Update on warehouse1
   Update on warehouse2
   ->  Index Scan using warehouse1_pkey on warehouse1  (cost=0.00..4.11 rows=1 width=648) (actual time=2.696..2.703 rows=1 loops=1)
         Index Cond: (w_id = $2)
   ->  Index Scan using warehouse2_pkey on warehouse2  (cost=0.00..4.12 rows=1 width=648) (actual time=9.725..9.725 rows=0 loops=1)
         Index Cond: (w_id = $2)
 Planning Time: 0.040 ms
 Execution Time: 12.729 ms
(9 rows)

```

The custom plan cost (4.11) is indeed cheaper than the generic plan (8.23). However in cached_plan_cost, we include a replan cost to the actual custom plan cost:
```
              /*                                                                  
               * Currently we use a very crude estimate of planning effort based  
               * on the number of relations in the finished plan's rangetable.    
               * Join planning effort actually scales much worse than linearly    
               * in the number of relations --- but only until the join collapse  
               * limits kick in.  Also, while inheritance child relations surely  
               * add to planning effort, they don't make the join situation       
               * worse.  So the actual shape of the planning cost curve versus    
               * number of relations isn't all that obvious.  It will take        
               * considerable work to arrive at a less crude estimate, and for    
               * now it's not clear that's worth doing.                           
               *                                                                  
               * The other big difficulty here is that we don't have any very     
               * good model of how planning cost compares to execution costs.     
               * The current multiplier of 1000 * cpu_operator_cost is probably   
               * on the low side, but we'll try this for awhile before making a   
               * more aggressive correction.                                      
               *                                                                  
               * If we ever do write a more complicated estimator, it should      
               * probably live in src/backend/optimizer/ not here.                
               */                                                                 
              int         nrelations = list_length(plannedstmt->rtable);         
              result += 1000.0 * cpu_operator_cost * (nrelations + 1);    
```

In the above query's case, the planning cost is 12.5. Add that to the custom plan cost of 4.11, we get 16.6 compared to 8.23 for custom plan. Thus the planner incorrectly chooses a generic plan which is in reality has nearly double execution time. This would be even worse for geopartitioned clusters.
