### ISSUE TITLE
[YSQL] TestYbBackup#testUserDefinedTypes fails with `Failed process with exit code 2`

### ISSUE THREAD

**Issue by tedyu** [yugabyte/yugabyte-db#11613]
### Description

From https://detective-gcp.dev.yugabyte.com/job/github-yugabyte-db-phabricator%2F167367%2Fartifact%2Fjava%2Fyb-pgsql%2Ftarget%2Fsurefire-reports_org.yb.pgsql.TestYbBackup__testUserDefinedTypes%2Forg.yb.pgsql.TestYbBackup-output.txt.gz?class=org.yb.pgsql.TestYbBackup&max_lines=3000&name=testUserDefinedTypes&start_line=30001 
```
org.yb.util.YBBackupException: Failed process with exit code 2: [$BUILD_ROOT/bin/../../../managed/devops/bin/yb_backup.py --masters M-1_RPC_HOST_PORT,M-2_RPC_HOST_PORT,M-3_RPC_HOST_PORT --remote_yb_admin_binary=$BUILD_ROOT/bin/yb-admin --remote_ysql_dump_binary=$BUILD_ROOT/bin/../postgres/bin/ysql_dump --remote_ysql_shell_binary=$BUILD_ROOT/bin/../postgres/bin/ysqlsh --storage_type nfs --nfs_storage_path /tmp/yb_test.org.yb.pgsql.TestYbBackup#testUserDefinedTypes.20220228185836349365.6367987509 --no_ssh --no_auto_name --ysql_host=127.73.98.209 --ysql_port=12457 --ts_web_hosts_ports=TS-2_WEB_HOST_PORT,TS-3_WEB_HOST_PORT,TS-1_WEB_HOST_PORT create --keyspace ysql.yugabyte]
--
31358 | at org.yb.util.YBBackupUtil.runProcess(YBBackupUtil.java:95)
31359 | at org.yb.util.YBBackupUtil.runYbBackup(YBBackupUtil.java:136)
31360 | at org.yb.util.YBBackupUtil.runYbBackupCreate(YBBackupUtil.java:160)
31361 | at org.yb.util.YBBackupUtil.runYbBackupCreate(YBBackupUtil.java:154)
31362 | at org.yb.pgsql.TestYbBackup.testUserDefinedTypes(TestYbBackup.java:1005)

org.yb.util.YBBackupException: Failed process with exit code 2: [$BUILD_ROOT/bin/../../../managed/devops/bin/yb_backup.py --masters M-1_RPC_HOST_PORT,M-2_RPC_HOST_PORT,M-3_RPC_HOST_PORT --remote_yb_admin_binary=$BUILD_ROOT/bin/yb-admin --remote_ysql_dump_binary=$BUILD_ROOT/bin/../postgres/bin/ysql_dump --remote_ysql_shell_binary=$BUILD_ROOT/bin/../postgres/bin/ysqlsh --storage_type nfs --nfs_storage_path /tmp/yb_test.org.yb.pgsql.TestYbBackup#testUserDefinedTypes.20220228185836349365.6367987509 --no_ssh --no_auto_name --ysql_host=127.73.98.209 --ysql_port=12457 --ts_web_hosts_ports=TS-2_WEB_HOST_PORT,TS-3_WEB_HOST_PORT,TS-1_WEB_HOST_PORT create --keyspace ysql.yugabyte]
[31358](https://detective-gcp.dev.yugabyte.com/job/github-yugabyte-db-phabricator%2F167367%2Fartifact%2Fjava%2Fyb-pgsql%2Ftarget%2Fsurefire-reports_org.yb.pgsql.TestYbBackup__testUserDefinedTypes%2Forg.yb.pgsql.TestYbBackup-output.txt.gz?class=org.yb.pgsql.TestYbBackup&max_lines=3000&name=testUserDefinedTypes&start_line=30001#line-31358)	         at org.yb.util.YBBackupUtil.runProcess(YBBackupUtil.java:95)
[31359](https://detective-gcp.dev.yugabyte.com/job/github-yugabyte-db-phabricator%2F167367%2Fartifact%2Fjava%2Fyb-pgsql%2Ftarget%2Fsurefire-reports_org.yb.pgsql.TestYbBackup__testUserDefinedTypes%2Forg.yb.pgsql.TestYbBackup-output.txt.gz?class=org.yb.pgsql.TestYbBackup&max_lines=3000&name=testUserDefinedTypes&start_line=30001#line-31359)	         at org.yb.util.YBBackupUtil.runYbBackup(YBBackupUtil.java:136)
[31360](https://detective-gcp.dev.yugabyte.com/job/github-yugabyte-db-phabricator%2F167367%2Fartifact%2Fjava%2Fyb-pgsql%2Ftarget%2Fsurefire-reports_org.yb.pgsql.TestYbBackup__testUserDefinedTypes%2Forg.yb.pgsql.TestYbBackup-output.txt.gz?class=org.yb.pgsql.TestYbBackup&max_lines=3000&name=testUserDefinedTypes&start_line=30001#line-31360)	         at org.yb.util.YBBackupUtil.runYbBackupCreate(YBBackupUtil.java:160)
[31361](https://detective-gcp.dev.yugabyte.com/job/github-yugabyte-db-phabricator%2F167367%2Fartifact%2Fjava%2Fyb-pgsql%2Ftarget%2Fsurefire-reports_org.yb.pgsql.TestYbBackup__testUserDefinedTypes%2Forg.yb.pgsql.TestYbBackup-output.txt.gz?class=org.yb.pgsql.TestYbBackup&max_lines=3000&name=testUserDefinedTypes&start_line=30001#line-31361)	         at org.yb.util.YBBackupUtil.runYbBackupCreate(YBBackupUtil.java:154)
[31362](https://detective-gcp.dev.yugabyte.com/job/github-yugabyte-db-phabricator%2F167367%2Fartifact%2Fjava%2Fyb-pgsql%2Ftarget%2Fsurefire-reports_org.yb.pgsql.TestYbBackup__testUserDefinedTypes%2Forg.yb.pgsql.TestYbBackup-output.txt.gz?class=org.yb.pgsql.TestYbBackup&max_lines=3000&name=testUserDefinedTypes&start_line=30001#line-31362)	         at org.yb.pgsql.TestYbBackup.testUserDefinedTypes(TestYbBackup.java:1005)
```

**Comment by myang2021** [comment]
This is a regression that was caused by

```
commit a6a6858e15d1efc7d2a48ecf937f014df1254744
Author:     AAYUSH CHAUHAN <achauhan@yugabyte.com>
AuthorDate: Fri Feb 11 04:31:07 2022 +0000
Commit:     AAYUSH CHAUHAN <achauhan@yugabyte.com>
CommitDate: Sun Feb 27 07:40:42 2022 +0000

    [PLAT-2975] Return Backup size from yb_backup script

```

Apparently, there was an implicit merge conflict that could not be auto-detected. The failed test
TestYbBackup#testUserDefinedTypes was recently added by commit:

```
commit 63ffdae951eacb0da9aee08cf8247052446623a8
Author:     Minghui Yang <myang@yugabyte.com>
AuthorDate: Thu Feb 3 06:10:58 2022 +0000
Commit:     Minghui Yang <myang@yugabyte.com>
CommitDate: Fri Feb 25 17:50:52 2022 +0000

```

From test log I saw the failure message:
```
2022-02-28 19:19:32,530 (Time-limited test) [INFO - org.yb.util.YBBackupUtil.runProcess(YBBackupUtil.java:75)] STDERR: yb_backup.py: error: one of the arguments --backup_location is required
```

The new argument `--backup_location` was introduced by commit
a6a6858e15d1efc7d2a48ecf937f014df1254744 but it was not added for the new test testUserDefinedTypes
that was introduced in Feb 25.
