### ISSUE TITLE
[CDCSDK] CDCErrorException with CDC enabled on target table in xCluster replication

### ISSUE THREAD

**Issue by vaibhav-yb** [yugabyte/yugabyte-db#11829]
Jira Link: [DB-3011](https://yugabyte.atlassian.net/browse/DB-3011)
If we have xCLuster replication enabled on a table `test` from `source` universe to `target` universe and we insert an intent in the `source` universe, an exception is thrown by Debezium which is basically coming from yb-client itself:

```
org.yb.client.CDCErrorException: Server[ac622ee5d2ba4343895108ff4d1c73e9] CORRUPTION[code 2]: Error when decoding range components of a document key: Unexpected end of key when decoding document key
	at org.yb.client.TabletClient.dispatchCDCErrorOrReturnException(TabletClient.java:508)
	at org.yb.client.TabletClient.decode(TabletClient.java:439)
	at org.yb.client.TabletClient.decode(TabletClient.java:100)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:500)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.yb.client.TabletClient.handleUpstream(TabletClient.java:651)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.handler.timeout.ReadTimeoutHandler.messageReceived(ReadTimeoutHandler.java:184)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
	at org.yb.client.AsyncYBClient$TabletClientPipeline.sendUpstream(AsyncYBClient.java:2504)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	... 3 more
```

**Steps to reproduce:**
1. Enable xCluster replication by following https://docs.yugabyte.com/latest/deploy/multi-dc/async-replication/
2. I used a table named `test` for my setup.
3. Create a DB stream ID on the `target` universe's database under which the table `test` resides.
4. On `source` universe, execute:
    ```sql
    INSERT INTO test VALUES (1);
    ```
    The above record works fine and the value will be seen in the target universe's table as well as across CDC. Now execute:
    ```sql
    BEGIN;
    INSERT INTO test VALUES (2);
    COMMIT;
    ```
    The record for the previous operation will be replicated via xCluster to the target table but it will result the above mentioned exception in the Debezium client.

**Comment by mrajcevic01** [comment]
Have a customer that is interested in CDC that is using bidirectional replication between two primary clusters. Due to each cluster being both a source and a target I anticipate we will see the issue above. Are there any current workarounds? The same customer also asked about using [Read Replicas to do CDC](https://github.com/yugabyte/yugabyte-db/issues/11116) off of in this case, however this also appears to not be supported.
