### ISSUE TITLE
Ubuntu 18.04: Error in starting without --disable_ysql

### ISSUE THREAD

**Issue by rajukumaryb** [yugabyte/yugabyte-db#1190]
Jira Link: [DB-996](https://yugabyte.atlassian.net/browse/DB-996)
Command: ./bin/yb-ctl --replication_factor 3 create  --tserver_flags "leader_failure_max_missed_heartbeat_periods=60"

2019-04-10 21:46:01,443 INFO: creating directory /home/raju/yugabyte-data/yb-ctl_tmp_pg_data_d38b12ca1ca7596832ed069973028ba9 ... ok
2019-04-10 21:46:01,443 INFO: creating subdirectories ... ok
2019-04-10 21:46:01,443 INFO: selecting default max_connections ... 100
2019-04-10 21:46:01,443 INFO: selecting default shared_buffers ... 128MB
2019-04-10 21:46:01,444 INFO: selecting dynamic shared memory implementation ... posix
2019-04-10 21:46:01,444 INFO: creating configuration files ... ok
2019-04-10 21:46:01,444 INFO: running bootstrap script ... I0410 21:45:54.772634 30380 ybc_util.cc:59] Setting flag pggate_master_addresses to the value of the env var FLAGS_pggate_master_addresses: 127.0.0.1:7100,127.0.0.2:7100,127.0.0.3:7100
2019-04-10 21:46:01,444 INFO: I0410 21:45:54.774675 30380 mem_tracker.cc:241] MemTracker: hard memory limit is 9.967682 GB
2019-04-10 21:46:01,444 INFO: I0410 21:45:54.774729 30380 mem_tracker.cc:243] MemTracker: soft memory limit is 8.472529 GB
2019-04-10 21:46:01,444 INFO: I0410 21:45:54.776321 30381 async_initializer.cc:77] Starting to init ybclient
2019-04-10 21:46:01,444 INFO: I0410 21:45:54.835062 30381 async_initializer.cc:83] Successfully built ybclient
2019-04-10 21:46:01,444 INFO: W0410 21:45:57.449417 30387 outbound_call.cc:341] RPC callback for RPC call yb.master.MasterService.GetTableLocations -> { remote: 127.0.0.1:7100 idx: 0 protocol: 0x00007fe5c02a60d0 -> tcp } , state=FINISHED_SUCCESS. blocked reactor thread for 202288us
2019-04-10 21:46:01,444 INFO: I0410 21:46:00.648913 30387 tablet_rpc.cc:318] Already present (yb/consensus/retryable_requests.cc:238): Failed Write(tablet: 00000000000000000000000000000000, num_ops: 16, num_attempts: 5, txn: 00000000-0000-0000-0000-000000000000) to tablet 00000000000000000000000000000000 on tablet server { uuid: 305199772cb6404c9c1520bf4ec561cd
private: [host: "127.0.0.1" port: 7100] cloud_info: placement_cloud: "cloud1" placement_region: "datacenter1" placement_zone: "rack1" after 5 attempt(s): Duplicate request
2019-04-10 21:46:01,444 INFO: E0410 21:46:00.856701 30380 elog.c:436] Stack trace for a FATAL log message
2019-04-10 21:46:01,444 INFO:     @     0x7fe5c621a1a7  YBCLogImpl (src/yb/util/ybc_util.cc:111)
2019-04-10 21:46:01,444 INFO:     @     0x55bd7c7b108e  errfinish (src/postgres/src/backend/utils/error/elog.c:436)
2019-04-10 21:46:01,444 INFO:     @     0x55bd7c7e3761  HandleYBStatus (src/postgres/src/backend/utils/misc/pg_yb_utils.c:175)
2019-04-10 21:46:01,444 INFO:     @     0x55bd7c46e62d  YBCFlushBufferedWriteOperations (src/postgres/src/backend/executor/ybcModifyTable.c:642)
2019-04-10 21:46:01,445 INFO:     @     0x55bd7c27ed8a  boot_yyparse (postgres/src/backend/bootstrap/bootparse.y:184)
2019-04-10 21:46:01,445 INFO:     @     0x55bd7c283632  BootstrapModeMain (src/postgres/src/backend/bootstrap/bootstrap.c:535)
2019-04-10 21:46:01,445 INFO:     @     0x55bd7c2834c7  AuxiliaryProcessMain (src/postgres/src/backend/bootstrap/bootstrap.c:442)
2019-04-10 21:46:01,446 INFO:     @     0x55bd7c48b816  PostgresServerProcessMain (src/postgres/src/backend/main/main.c:226)
2019-04-10 21:46:01,446 INFO:     @     0x55bd7c48bbf5
2019-04-10 21:46:01,446 INFO:     @     0x7fe5c510cb96
2019-04-10 21:46:01,447 INFO:     @     0x55bd7c1751c9
2019-04-10 21:46:01,447 INFO:     @ 0xffffffffffffffff
2019-04-10 21:46:01,447 INFO: 2019-04-10 21:46:01.392 UTC [30380] FATAL:  IO error: Errors occured while reaching out to the tablet servers: . Errors from tablet servers: [Already present (yb/consensus/retryable_requests.cc:238): Duplicate request]
2019-04-10 21:46:01,449 INFO: 2019-04-10 21:46:01.392 UTC [30380] WARNING:  cannot remove relcache entry for "pg_proc" because it has nonzero refcount
2019-04-10 21:46:01,450 INFO: child process exited with exit code 1
2019-04-10 21:46:01,450 INFO: initdb: removing data directory "/home/raju/yugabyte-data/yb-ctl_tmp_pg_data_d38b12ca1ca7596832ed069973028ba9"
Traceback (most recent call last):
  File "/home/raju/code/yugabyte/submodules/yugabyte-installation/bin/yb-ctl", line 1267, in <module>
    ClusterControl().run()
  File "/home/raju/code/yugabyte/submodules/yugabyte-installation/bin/yb-ctl", line 1258, in run
    self.args.func()
  File "/home/raju/code/yugabyte/submodules/yugabyte-installation/bin/yb-ctl", line 1102, in create
    self.run_cluster_wide_postgres_initdb()
  File "/home/raju/code/yugabyte/submodules/yugabyte-installation/bin/yb-ctl", line 1227, in run_cluster_wide_postgres_initdb
    ], stdout=initdb_stdout_file, stderr=subprocess.STDOUT)
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/raju/code/yugabyte/build/latest/postgres/bin/initdb', '-D', '/home/raju/yugabyte-data/yb-ctl_tmp_pg_data_d38b12ca1ca7596832ed069973028ba9', '-U', 'postgres']' returned non-zero exit status 1

**Comment by rajukumaryb** [comment]
Built using -

diff --git a/src/yb/docdb/CMakeLists.txt b/src/yb/docdb/CMakeLists.txt
index d11d14eda..1c1a3ec77 100644
--- a/src/yb/docdb/CMakeLists.txt
+++ b/src/yb/docdb/CMakeLists.txt
@@ -24,6 +24,9 @@ ADD_YB_LIBRARY(docdb_proto
   DEPS protobuf yb_common_proto opid_proto
   NONLINK_DEPS ${DOCDB_PROTO_TGTS})

+set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -O0 -g -Wno-aligned-new")
+set(CMAKE_CXX_FLAGS "${CMAKE_C_FLAGS} -O0 -g -Wno-aligned-new")
+
 set(DOCDB_SRCS
     conflict_resolution.cc
     consensus_frontier.cc

**Comment by mbautin** [comment]
The build type here is debug.

**Comment by m-iancu** [comment]
Looks similar to https://github.com/YugaByte/yugabyte-db/issues/1208.

**Comment by Bessonov** [comment]
@rajukumaryb  is this still relevant?

**Comment by sushantrmishra** [comment]
This issue is not reproducible anymore. Please reopen if you see reoccurrence  of it.

```
(venv) /bin/yb-ctl --replication_factor 3 create --tlags "leader_failure_max_missed_heartbeat_periods=60"
Creating cluster.
Waiting for cluster to be ready.
----------------------------------------------------------------------------------------------------
| Node Count: 3 | Replication Factor: 3                                                            |
----------------------------------------------------------------------------------------------------
| JDBC                : jdbc:postgresql://127.0.0.1:5433/yugabyte                                  |
| YSQL Shell          : bin/ysqlsh                                                                 |
| YCQL Shell          : bin/ycqlsh                                                                 |
| YEDIS Shell         : bin/redis-cli                                                              |
| Web UI              : http://127.0.0.1:7000/                                                     |
| Cluster Data        : /home/yugabyte-data                                    |
----------------------------------------------------------------------------------------------------

For more info, please use: yb-ctl status
$./bin/ysqlsh
ysqlsh (11.2-YB-2.15.3.0-b0)
Type "help" for help.

yugabyte=# select version();

        version

--------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------
------------------------
 PostgreSQL 11.2-YB-2.15.3.0-b0 on x86_64-pc-linux-gnu, compiled by clang version 13.0.1 (/opt/yb-build/llvm/y
b-llvm-v13.0.1-yb-2-1659058819-0131d8e1-centos7-x86_64-build/src/llvm-project/clang 0131d8e1a20f72a0f374979985
db4c2871be71bc), 64-bit
(1 row)
```
