### ISSUE TITLE
[DocDB] Update zlib from 1.2.11 to 1.2.12

### ISSUE THREAD

**Issue by def-** [yugabyte/yugabyte-db#11964]
### Description

"Fix a deflate bug when using the Z_FIXED strategy that can result in out-of-bound accesses." sounds serious. See https://github.com/yugabyte/yugabyte-db-thirdparty/pull/106

**Comment by rthallamko3** [comment]
@def- , can we resolve this issue, it looks like you have merged the necessary changes?

**Comment by def-** [comment]
I still have a phabricator change open to actually switch to new zlib version in yugabyte-db repo: https://phabricator.dev.yugabyte.com/D16347
I'm trying to rebase it, but `build-support/thirdparty_tool -u` is currently failing for me, have to check:
```
Traceback (most recent call last):
  File "/nfusr/dev-server/dfelsing/code/yugabyte-db/python/yb/thirdparty_tool.py", line 637, in <module>
    main()
  File "/nfusr/dev-server/dfelsing/code/yugabyte-db/python/yb/thirdparty_tool.py", line 582, in main
    updater.update_archive_metadata_file()
  File "/nfusr/dev-server/dfelsing/code/yugabyte-db/python/yb/thirdparty_tool.py", line 384, in update_archive_metadata_file
    yb_dep_release = GitHubThirdPartyRelease(release)
  File "/nfusr/dev-server/dfelsing/code/yugabyte-db/python/yb/thirdparty_tool.py", line 142, in __init__
    raise ValueError(f"Could not parse tag: {tag}, does not match regex: {TAG_RE}")
ValueError: Could not parse tag: v20220413154237-81bb2d6459-almalinux8-aarch64-13, does not match regex: re.compile('^v(?:(?P<branch_name>[0-9.]+)-)?(?P<timestamp>[0-9]+)-(?P<sha_prefix>[0-9a-f]+)(?:-(?P<architecture1>x86_64|aarch64|arm64))?(?:-(?P<os>(?:macos|almalinux|alpine|centos|debian|fedora|ol|rocky|ubuntu|o)
```

**Comment by def-** [comment]
@mbautin I tried upgrading https://github.com/yugabyte/sys-detection to 1.2.0 but still getting the same failure. This tag looks a bit strange to me, is it a new format or a mistake?

**Comment by def-** [comment]
CC @spolitov
