### ISSUE TITLE
[YSQL] [Test] `SET SESSION AUTHORIZATION su` doesn't fail

### ISSUE THREAD

**Issue by tedyu** [yugabyte/yugabyte-db#11985]
### Description

From https://detective-gcp.dev.yugabyte.com/job/github-yugabyte-db-phabricator%2F175083%2Fartifact%2Fjava%2Fyb-pgsql%2Ftarget%2Fsurefire-reports_org.yb.pgsql.TestPgAuthorization__testGrantAttributesMidSession%2Forg.yb.pgsql.TestPgAuthorization-output.txt.gz?class=org.yb.pgsql.TestPgAuthorization&max_lines=3000&name=testGrantAttributesMidSession&start_line=6001 :
```
java.lang.AssertionError: Statement did not fail: SET SESSION AUTHORIZATION su
--
7884 | at org.junit.Assert.fail(Assert.java:88)
7885 | at org.yb.AssertionWrappers.lambda$fail$4(AssertionWrappers.java:104)
7886 | at org.yb.AssertionWrappers.wrapAssertion(AssertionWrappers.java:45)
7887 | at org.yb.AssertionWrappers.fail(AssertionWrappers.java:104)
7888 | at org.yb.pgsql.BasePgSQLTest.runInvalidQuery(BasePgSQLTest.java:1613)
7889 | at org.yb.pgsql.TestPgAuthorization.testGrantAttributesMidSession(TestPgAuthorization.java:2761)

java.lang.AssertionError: Statement did not fail: SET SESSION AUTHORIZATION su
[7884](https://detective-gcp.dev.yugabyte.com/job/github-yugabyte-db-phabricator%2F175083%2Fartifact%2Fjava%2Fyb-pgsql%2Ftarget%2Fsurefire-reports_org.yb.pgsql.TestPgAuthorization__testGrantAttributesMidSession%2Forg.yb.pgsql.TestPgAuthorization-output.txt.gz?class=org.yb.pgsql.TestPgAuthorization&max_lines=3000&name=testGrantAttributesMidSession&start_line=6001#line-7884)	         at org.junit.Assert.fail(Assert.java:88)
[7885](https://detective-gcp.dev.yugabyte.com/job/github-yugabyte-db-phabricator%2F175083%2Fartifact%2Fjava%2Fyb-pgsql%2Ftarget%2Fsurefire-reports_org.yb.pgsql.TestPgAuthorization__testGrantAttributesMidSession%2Forg.yb.pgsql.TestPgAuthorization-output.txt.gz?class=org.yb.pgsql.TestPgAuthorization&max_lines=3000&name=testGrantAttributesMidSession&start_line=6001#line-7885)	         at org.yb.AssertionWrappers.lambda$fail$4(AssertionWrappers.java:104)
[7886](https://detective-gcp.dev.yugabyte.com/job/github-yugabyte-db-phabricator%2F175083%2Fartifact%2Fjava%2Fyb-pgsql%2Ftarget%2Fsurefire-reports_org.yb.pgsql.TestPgAuthorization__testGrantAttributesMidSession%2Forg.yb.pgsql.TestPgAuthorization-output.txt.gz?class=org.yb.pgsql.TestPgAuthorization&max_lines=3000&name=testGrantAttributesMidSession&start_line=6001#line-7886)	         at org.yb.AssertionWrappers.wrapAssertion(AssertionWrappers.java:45)
[7887](https://detective-gcp.dev.yugabyte.com/job/github-yugabyte-db-phabricator%2F175083%2Fartifact%2Fjava%2Fyb-pgsql%2Ftarget%2Fsurefire-reports_org.yb.pgsql.TestPgAuthorization__testGrantAttributesMidSession%2Forg.yb.pgsql.TestPgAuthorization-output.txt.gz?class=org.yb.pgsql.TestPgAuthorization&max_lines=3000&name=testGrantAttributesMidSession&start_line=6001#line-7887)	         at org.yb.AssertionWrappers.fail(AssertionWrappers.java:104)
[7888](https://detective-gcp.dev.yugabyte.com/job/github-yugabyte-db-phabricator%2F175083%2Fartifact%2Fjava%2Fyb-pgsql%2Ftarget%2Fsurefire-reports_org.yb.pgsql.TestPgAuthorization__testGrantAttributesMidSession%2Forg.yb.pgsql.TestPgAuthorization-output.txt.gz?class=org.yb.pgsql.TestPgAuthorization&max_lines=3000&name=testGrantAttributesMidSession&start_line=6001#line-7888)	         at org.yb.pgsql.BasePgSQLTest.runInvalidQuery(BasePgSQLTest.java:1613)
[7889](https://detective-gcp.dev.yugabyte.com/job/github-yugabyte-db-phabricator%2F175083%2Fartifact%2Fjava%2Fyb-pgsql%2Ftarget%2Fsurefire-reports_org.yb.pgsql.TestPgAuthorization__testGrantAttributesMidSession%2Forg.yb.pgsql.TestPgAuthorization-output.txt.gz?class=org.yb.pgsql.TestPgAuthorization&max_lines=3000&name=testGrantAttributesMidSession&start_line=6001#line-7889)	         at org.yb.pgsql.TestPgAuthorization.testGrantAttributesMidSession(TestPgAuthorization.java:2761)
```
This seems to be caused by commit c961dacdbcd2ab9b8a6e312777422844d52dbccc

**Comment by paullee-yb** [comment]
Fixed in this [change](https://github.com/yugabyte/yugabyte-db/commit/a9eb8b8a8e385763535fd268aa76300d1a6d33b6).
