### ISSUE TITLE
[YSQL] assertMigrationsWorked should not consider the order of permissions

### ISSUE THREAD

**Issue by tedyu** [yugabyte/yugabyte-db#12179]
### Description

I saw the following in https://detective-gcp.dev.yugabyte.com/job/github-yugabyte-db-phabricator%2F181925%2Fartifact%2Fjava%2Fyb-pgsql%2Ftarget%2Fsurefire-reports_org.yb.pgsql.TestYsqlUpgrade__migratingIsEquivalentToReinitdb%2Forg.yb.pgsql.TestYsqlUpgrade-output.txt.gz?class=org.yb.pgsql.TestYsqlUpgrade&max_lines=3000&name=migratingIsEquivalentToReinitdb&start_line=15001 :
```
ERROR | 157.699000 | Time-limited test | AssertionWrappers.java:40 | Assertion error:
-- | -- | -- | -- | --
17277 | java.lang.AssertionError: Table 'pg_class': Column #31 (relacl) mismatch: expected:<{postgres=arwdDxt/postgres,=r/postgres}> but was:<{=r/postgres,postgres=arwdDxt/postgres}>
17278 | Expected row: Row[oid=java.lang.Long::1234567890,relname=java.lang.String::pg_stat_statements,relnamespace=java.lang.String::pg_catalog,reltype=java.lang.String::pg_stat_statements,reloftype=java.lang.Long::0,relowner=java.lang.Long::10,relam=java.lang.Long::0,relfilenode=java.lang.String::pg_stat_statements,reltablespace=java.lang.Long::0,relpages=java.lang.Integer::0,relallvisible=java.lang.Integer::0,reltoastrelid=java.lang.Long::0,relhasindex=java.lang.Boolean::false,relisshared=java.lang.Boolean::false,relpersistence=java.lang.String::p,relkind=java.lang.String::v,relnatts=java.lang.Integer::23,relchecks=java.lang.Integer::0,relhasoids=java.lang.Boolean::false,relhasrules=java.lang.Boolean::true,relhastriggers=java.lang.Boolean::false,relhassubclass=java.lang.Boolean::false,relrowsecurity=java.lang.Boolean::false,relforcerowsecurity=java.lang.Boolean::false,relispopulated=java.lang.Boolean::true,relreplident=java.lang.String::n,relispartition=java.lang.Boolean::false,relrewrite=java.lang.Long::0,relfrozenxid=com.yugabyte.util.PGobject::0,relminmxid=com.yugabyte.util.PGobject::0,relacl=com.yugabyte.jdbc.PgArray::{postgres=arwdDxt/postgres,=r/postgres},reloptions=null,relpartbound=null]
17279 | Actual row: Row[oid=java.lang.Long::1234567890,relname=java.lang.String::pg_stat_statements,relnamespace=java.lang.String::pg_catalog,reltype=java.lang.String::pg_stat_statements,reloftype=java.lang.Long::0,relowner=java.lang.Long::10,relam=java.lang.Long::0,relfilenode=java.lang.String::pg_stat_statements,reltablespace=java.lang.Long::0,relpages=java.lang.Integer::0,relallvisible=java.lang.Integer::0,reltoastrelid=java.lang.Long::0,relhasindex=java.lang.Boolean::false,relisshared=java.lang.Boolean::false,relpersistence=java.lang.String::p,relkind=java.lang.String::v,relnatts=java.lang.Integer::23,relchecks=java.lang.Integer::0,relhasoids=java.lang.Boolean::false,relhasrules=java.lang.Boolean::true,relhastriggers=java.lang.Boolean::false,relhassubclass=java.lang.Boolean::false,relrowsecurity=java.lang.Boolean::false,relforcerowsecurity=java.lang.Boolean::false,relispopulated=java.lang.Boolean::true,relreplident=java.lang.String::n,relispartition=java.lang.Boolean::false,relrewrite=java.lang.Long::0,relfrozenxid=com.yugabyte.util.PGobject::0,relminmxid=com.yugabyte.util.PGobject::0,relacl=com.yugabyte.jdbc.PgArray::{=r/postgres,postgres=arwdDxt/postgres},reloptions=null,relpartbound=null]
17280 | at org.junit.Assert.fail(Assert.java:88)
17281 | at org.junit.Assert.assertTrue(Assert.java:41)
17282 | at org.yb.AssertionWrappers.lambda$assertTrue$0(AssertionWrappers.java:61)
17283 | at org.yb.AssertionWrappers.wrapAssertion(AssertionWrappers.java:45)
17284 | at org.yb.AssertionWrappers.assertTrue(AssertionWrappers.java:61)
17285 | at org.yb.pgsql.BasePgSQLTest.assertRow(BasePgSQLTest.java:1302)
17286 | at org.yb.pgsql.TestYsqlUpgrade.lambda$assertMigrationsWorked$47(TestYsqlUpgrade.java:1371)
17287 | at java.util.TreeMap.forEach(TreeMap.java:1005)
17288 | at org.yb.pgsql.TestYsqlUpgrade.assertMigrationsWorked(TestYsqlUpgrade.java:1357)
17289 | at org.yb.pgsql.TestYsqlUpgrade.migratingIsEquivalentToReinitdb(TestYsqlUpgrade.java:822)

ERROR	157.699000	Time-limited test	AssertionWrappers.java:40	Assertion error:
[17277](https://detective-gcp.dev.yugabyte.com/job/github-yugabyte-db-phabricator%2F181925%2Fartifact%2Fjava%2Fyb-pgsql%2Ftarget%2Fsurefire-reports_org.yb.pgsql.TestYsqlUpgrade__migratingIsEquivalentToReinitdb%2Forg.yb.pgsql.TestYsqlUpgrade-output.txt.gz?class=org.yb.pgsql.TestYsqlUpgrade&max_lines=3000&name=migratingIsEquivalentToReinitdb&start_line=15001#line-17277)	java.lang.AssertionError: Table 'pg_class': Column #31 (relacl) mismatch: expected:<{postgres=arwdDxt/postgres,=r/postgres}> but was:<{=r/postgres,postgres=arwdDxt/postgres}>
[17278](https://detective-gcp.dev.yugabyte.com/job/github-yugabyte-db-phabricator%2F181925%2Fartifact%2Fjava%2Fyb-pgsql%2Ftarget%2Fsurefire-reports_org.yb.pgsql.TestYsqlUpgrade__migratingIsEquivalentToReinitdb%2Forg.yb.pgsql.TestYsqlUpgrade-output.txt.gz?class=org.yb.pgsql.TestYsqlUpgrade&max_lines=3000&name=migratingIsEquivalentToReinitdb&start_line=15001#line-17278)	Expected row: Row[oid=java.lang.Long::1234567890,relname=java.lang.String::pg_stat_statements,relnamespace=java.lang.String::pg_catalog,reltype=java.lang.String::pg_stat_statements,reloftype=java.lang.Long::0,relowner=java.lang.Long::10,relam=java.lang.Long::0,relfilenode=java.lang.String::pg_stat_statements,reltablespace=java.lang.Long::0,relpages=java.lang.Integer::0,relallvisible=java.lang.Integer::0,reltoastrelid=java.lang.Long::0,relhasindex=java.lang.Boolean::false,relisshared=java.lang.Boolean::false,relpersistence=java.lang.String::p,relkind=java.lang.String::v,relnatts=java.lang.Integer::23,relchecks=java.lang.Integer::0,relhasoids=java.lang.Boolean::false,relhasrules=java.lang.Boolean::true,relhastriggers=java.lang.Boolean::false,relhassubclass=java.lang.Boolean::false,relrowsecurity=java.lang.Boolean::false,relforcerowsecurity=java.lang.Boolean::false,relispopulated=java.lang.Boolean::true,relreplident=java.lang.String::n,relispartition=java.lang.Boolean::false,relrewrite=java.lang.Long::0,relfrozenxid=com.yugabyte.util.PGobject::0,relminmxid=com.yugabyte.util.PGobject::0,relacl=com.yugabyte.jdbc.PgArray::{postgres=arwdDxt/postgres,=r/postgres},reloptions=null,relpartbound=null]
[17279](https://detective-gcp.dev.yugabyte.com/job/github-yugabyte-db-phabricator%2F181925%2Fartifact%2Fjava%2Fyb-pgsql%2Ftarget%2Fsurefire-reports_org.yb.pgsql.TestYsqlUpgrade__migratingIsEquivalentToReinitdb%2Forg.yb.pgsql.TestYsqlUpgrade-output.txt.gz?class=org.yb.pgsql.TestYsqlUpgrade&max_lines=3000&name=migratingIsEquivalentToReinitdb&start_line=15001#line-17279)	Actual row: Row[oid=java.lang.Long::1234567890,relname=java.lang.String::pg_stat_statements,relnamespace=java.lang.String::pg_catalog,reltype=java.lang.String::pg_stat_statements,reloftype=java.lang.Long::0,relowner=java.lang.Long::10,relam=java.lang.Long::0,relfilenode=java.lang.String::pg_stat_statements,reltablespace=java.lang.Long::0,relpages=java.lang.Integer::0,relallvisible=java.lang.Integer::0,reltoastrelid=java.lang.Long::0,relhasindex=java.lang.Boolean::false,relisshared=java.lang.Boolean::false,relpersistence=java.lang.String::p,relkind=java.lang.String::v,relnatts=java.lang.Integer::23,relchecks=java.lang.Integer::0,relhasoids=java.lang.Boolean::false,relhasrules=java.lang.Boolean::true,relhastriggers=java.lang.Boolean::false,relhassubclass=java.lang.Boolean::false,relrowsecurity=java.lang.Boolean::false,relforcerowsecurity=java.lang.Boolean::false,relispopulated=java.lang.Boolean::true,relreplident=java.lang.String::n,relispartition=java.lang.Boolean::false,relrewrite=java.lang.Long::0,relfrozenxid=com.yugabyte.util.PGobject::0,relminmxid=com.yugabyte.util.PGobject::0,relacl=com.yugabyte.jdbc.PgArray::{=r/postgres,postgres=arwdDxt/postgres},reloptions=null,relpartbound=null]
[17280](https://detective-gcp.dev.yugabyte.com/job/github-yugabyte-db-phabricator%2F181925%2Fartifact%2Fjava%2Fyb-pgsql%2Ftarget%2Fsurefire-reports_org.yb.pgsql.TestYsqlUpgrade__migratingIsEquivalentToReinitdb%2Forg.yb.pgsql.TestYsqlUpgrade-output.txt.gz?class=org.yb.pgsql.TestYsqlUpgrade&max_lines=3000&name=migratingIsEquivalentToReinitdb&start_line=15001#line-17280)	         at org.junit.Assert.fail(Assert.java:88)
[17281](https://detective-gcp.dev.yugabyte.com/job/github-yugabyte-db-phabricator%2F181925%2Fartifact%2Fjava%2Fyb-pgsql%2Ftarget%2Fsurefire-reports_org.yb.pgsql.TestYsqlUpgrade__migratingIsEquivalentToReinitdb%2Forg.yb.pgsql.TestYsqlUpgrade-output.txt.gz?class=org.yb.pgsql.TestYsqlUpgrade&max_lines=3000&name=migratingIsEquivalentToReinitdb&start_line=15001#line-17281)	         at org.junit.Assert.assertTrue(Assert.java:41)
[17282](https://detective-gcp.dev.yugabyte.com/job/github-yugabyte-db-phabricator%2F181925%2Fartifact%2Fjava%2Fyb-pgsql%2Ftarget%2Fsurefire-reports_org.yb.pgsql.TestYsqlUpgrade__migratingIsEquivalentToReinitdb%2Forg.yb.pgsql.TestYsqlUpgrade-output.txt.gz?class=org.yb.pgsql.TestYsqlUpgrade&max_lines=3000&name=migratingIsEquivalentToReinitdb&start_line=15001#line-17282)	         at org.yb.AssertionWrappers.lambda$assertTrue$0(AssertionWrappers.java:61)
[17283](https://detective-gcp.dev.yugabyte.com/job/github-yugabyte-db-phabricator%2F181925%2Fartifact%2Fjava%2Fyb-pgsql%2Ftarget%2Fsurefire-reports_org.yb.pgsql.TestYsqlUpgrade__migratingIsEquivalentToReinitdb%2Forg.yb.pgsql.TestYsqlUpgrade-output.txt.gz?class=org.yb.pgsql.TestYsqlUpgrade&max_lines=3000&name=migratingIsEquivalentToReinitdb&start_line=15001#line-17283)	         at org.yb.AssertionWrappers.wrapAssertion(AssertionWrappers.java:45)
[17284](https://detective-gcp.dev.yugabyte.com/job/github-yugabyte-db-phabricator%2F181925%2Fartifact%2Fjava%2Fyb-pgsql%2Ftarget%2Fsurefire-reports_org.yb.pgsql.TestYsqlUpgrade__migratingIsEquivalentToReinitdb%2Forg.yb.pgsql.TestYsqlUpgrade-output.txt.gz?class=org.yb.pgsql.TestYsqlUpgrade&max_lines=3000&name=migratingIsEquivalentToReinitdb&start_line=15001#line-17284)	         at org.yb.AssertionWrappers.assertTrue(AssertionWrappers.java:61)
[17285](https://detective-gcp.dev.yugabyte.com/job/github-yugabyte-db-phabricator%2F181925%2Fartifact%2Fjava%2Fyb-pgsql%2Ftarget%2Fsurefire-reports_org.yb.pgsql.TestYsqlUpgrade__migratingIsEquivalentToReinitdb%2Forg.yb.pgsql.TestYsqlUpgrade-output.txt.gz?class=org.yb.pgsql.TestYsqlUpgrade&max_lines=3000&name=migratingIsEquivalentToReinitdb&start_line=15001#line-17285)	         at org.yb.pgsql.BasePgSQLTest.assertRow(BasePgSQLTest.java:1302)
[17286](https://detective-gcp.dev.yugabyte.com/job/github-yugabyte-db-phabricator%2F181925%2Fartifact%2Fjava%2Fyb-pgsql%2Ftarget%2Fsurefire-reports_org.yb.pgsql.TestYsqlUpgrade__migratingIsEquivalentToReinitdb%2Forg.yb.pgsql.TestYsqlUpgrade-output.txt.gz?class=org.yb.pgsql.TestYsqlUpgrade&max_lines=3000&name=migratingIsEquivalentToReinitdb&start_line=15001#line-17286)	         at org.yb.pgsql.TestYsqlUpgrade.lambda$assertMigrationsWorked$47(TestYsqlUpgrade.java:1371)
[17287](https://detective-gcp.dev.yugabyte.com/job/github-yugabyte-db-phabricator%2F181925%2Fartifact%2Fjava%2Fyb-pgsql%2Ftarget%2Fsurefire-reports_org.yb.pgsql.TestYsqlUpgrade__migratingIsEquivalentToReinitdb%2Forg.yb.pgsql.TestYsqlUpgrade-output.txt.gz?class=org.yb.pgsql.TestYsqlUpgrade&max_lines=3000&name=migratingIsEquivalentToReinitdb&start_line=15001#line-17287)	         at java.util.TreeMap.forEach(TreeMap.java:1005)
[17288](https://detective-gcp.dev.yugabyte.com/job/github-yugabyte-db-phabricator%2F181925%2Fartifact%2Fjava%2Fyb-pgsql%2Ftarget%2Fsurefire-reports_org.yb.pgsql.TestYsqlUpgrade__migratingIsEquivalentToReinitdb%2Forg.yb.pgsql.TestYsqlUpgrade-output.txt.gz?class=org.yb.pgsql.TestYsqlUpgrade&max_lines=3000&name=migratingIsEquivalentToReinitdb&start_line=15001#line-17288)	         at org.yb.pgsql.TestYsqlUpgrade.assertMigrationsWorked(TestYsqlUpgrade.java:1357)
[17289](https://detective-gcp.dev.yugabyte.com/job/github-yugabyte-db-phabricator%2F181925%2Fartifact%2Fjava%2Fyb-pgsql%2Ftarget%2Fsurefire-reports_org.yb.pgsql.TestYsqlUpgrade__migratingIsEquivalentToReinitdb%2Forg.yb.pgsql.TestYsqlUpgrade-output.txt.gz?class=org.yb.pgsql.TestYsqlUpgrade&max_lines=3000&name=migratingIsEquivalentToReinitdb&start_line=15001#line-17289)	         at org.yb.pgsql.TestYsqlUpgrade.migratingIsEquivalentToReinitdb(TestYsqlUpgrade.java:822)
```
It seems the relacl's are effectively the same, just in different order.

**Comment by tedyu** [comment]
Tentative fix is in D12940

**Comment by frozenspider** [comment]
The problem is not the test, but the actual order.
However, I could not repro it in D16698 using the exact same diff but without test changes.
