### ISSUE TITLE
[DocDB] SIGSEGV encountered during restart (yb::rpc::ThreadPool::Impl::Enqueue)

### ISSUE THREAD

**Issue by ajcaldera1** [yugabyte/yugabyte-db#12176]
Jira Link: [DB-1437](https://yugabyte.atlassian.net/browse/DB-1437)
### Description

```
#0  alloc (this=0x0) at /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20211222064200-dd4872fe56-centos7-x86_64-linuxbrew-gcc5/installed/uninstrumented/include/cds/gc/dhp.h:109
109 /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20211222064200-dd4872fe56-centos7-x86_64-linuxbrew-gcc5/installed/uninstrumented/include/cds/gc/dhp.h: No such file or directory.
(gdb) bt
#0  alloc (this=0x0) at /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20211222064200-dd4872fe56-centos7-x86_64-linuxbrew-gcc5/installed/uninstrumented/include/cds/gc/dhp.h:109
#1  Guard (this=<synthetic pointer>)
    at /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20211222064200-dd4872fe56-centos7-x86_64-linuxbrew-gcc5/installed/uninstrumented/include/cds/gc/dhp.h:710
#2  cds::intrusive::BasketQueue<cds::gc::DHP, cds::container::details::make_basket_queue<cds::gc::DHP, yb::rpc::ThreadPoolTask*, cds::container::basket_queue::traits>::node_type, cds::container::details::make_basket_queue<cds::gc::DHP, yb::rpc::ThreadPoolTask*, cds::container::basket_queue::traits>::intrusive_traits>::enqueue (this=this@entry=0x2359230, val=...)
    at /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20211222064200-dd4872fe56-centos7-x86_64-linuxbrew-gcc5/installed/uninstrumented/include/cds/intrusive/basket_queue.h:634
#3  0x00007fe6c84122bb in enqueue (val=<synthetic pointer>, this=<optimized out>)
    at /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20211222064200-dd4872fe56-centos7-x86_64-linuxbrew-gcc5/installed/uninstrumented/include/cds/container/basket_queue.h:296
#4  push (val=<synthetic pointer>, this=<optimized out>)
    at /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20211222064200-dd4872fe56-centos7-x86_64-linuxbrew-gcc5/installed/uninstrumented/include/cds/container/basket_queue.h:339
#5  yb::rpc::ThreadPool::Impl::Enqueue (this=<optimized out>, task=task@entry=0x16f48e48) at ../../src/yb/rpc/thread_pool.cc:185
#6  0x00007fe6c840e1cd in yb::rpc::ThreadPool::Enqueue (this=<optimized out>, task=task@entry=0x16f48e48) at ../../src/yb/rpc/thread_pool.cc:289
#7  0x00007fe6c83b57a4 in yb::rpc::OutboundCall::InvokeCallback (this=this@entry=0x16f48d90) at ../../src/yb/rpc/outbound_call.cc:341
#8  0x00007fe6c83b5a4a in yb::rpc::OutboundCall::SetFailed (this=0x16f48d90, status=..., err_pb=...) at ../../src/yb/rpc/outbound_call.cc:476
#9  0x00007fe6c83bd1bb in yb::rpc::Proxy::NotifyFailed (controller=<optimized out>, status=...) at ../../src/yb/rpc/proxy.cc:313
#10 0x00007fe6c83bd36f in yb::rpc::Proxy::NotifyAllFailed (this=this@entry=0xcd31680, status=...) at ../../src/yb/rpc/proxy.cc:271
#11 0x00007fe6c83bd4d1 in yb::rpc::Proxy::ResolveDone (this=this@entry=0xcd31680, result=...) at ../../src/yb/rpc/proxy.cc:290
#12 0x00007fe6c83bf4ec in yb::rpc::Proxy::HandleResolve (this=0xcd31680, result=...) at ../../src/yb/rpc/proxy.cc:279
#13 0x00007fe6c74e51fd in operator() (__args#0=..., this=0x7fe6ae6bff40)
    at /home/yugabyte/linuxbrew-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/Cellar/gcc/5.5.0_4/include/c++/5.5.0/functional:2267
#14 yb::DnsResolver::Impl::CacheEntry::DoResolve(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::function<void (yb::Result<boost::asio::ip::address> const&)> const*, boost::asio::ip::basic_resolver<boost::asio::ip::tcp>*) (this=this@entry=0xaa812b8, host=..., callback=<optimized out>, callback@entry=0x7fe6ae6bff40,
    resolver=resolver@entry=0x1ff2480) at ../../src/yb/util/net/dns_resolver.cc:147
#15 0x00007fe6c74de8c2 in AsyncResolve (callback=..., host=..., this=<optimized out>) at ../../src/yb/util/net/dns_resolver.cc:99
#16 yb::DnsResolver::AsyncResolve(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::function<void (yb::Result<boost::asio::ip::address> const&)> const&) (this=<optimized out>, host=..., callback=...) at ../../src/yb/util/net/dns_resolver.cc:241
#17 0x00007fe6c83be2f7 in yb::rpc::Proxy::Resolve (this=this@entry=0xcd31680) at ../../src/yb/rpc/proxy.cc:265
#18 0x00007fe6c83bec52 in yb::rpc::Proxy::DoAsyncRequest(yb::rpc::RemoteMethod const*, std::shared_ptr<yb::rpc::OutboundMethodMetrics const>, yb::rpc::AnyMessageConstPtr, yb::rpc::AnyMessagePtr, yb::rpc::RpcController*, std::function<void ()>, bool) (this=0xcd31680,
    method=method@entry=0x7fe6ce996320 <yb::tserver::TabletServerServiceProxy::ReadAsync(yb::tserver::ReadRequestPB const&, yb::tserver::ReadResponsePB*, yb::rpc::RpcController*, std::function<void ()>) const::method>, method_metrics=..., req=..., req@entry=..., resp=resp@entry=..., controller=controller@entry=0x2bf91260, callback=..., force_run_callback_on_reactor=false)
    at ../../src/yb/rpc/proxy.cc:218
#19 0x00007fe6c83bef15 in yb::rpc::Proxy::AsyncRequest(yb::rpc::RemoteMethod const*, std::shared_ptr<yb::rpc::OutboundMethodMetrics const>, google::protobuf::Message const&, google::protobuf::Message*, yb::rpc::RpcController*, std::function<void ()>) (this=<optimized out>,
    method=method@entry=0x7fe6ce996320 <yb::tserver::TabletServerServiceProxy::ReadAsync(yb::tserver::ReadRequestPB const&, yb::tserver::ReadResponsePB*, yb::rpc::RpcController*, std::function<void ()>) const::method>, method_metrics=..., req=..., resp=resp@entry=0x2bf91458, controller=controller@entry=0x2bf91260, callback=...) at ../../src/yb/rpc/proxy.cc:126
#20 0x00007fe6ce76df3e in yb::tserver::TabletServerServiceProxy::ReadAsync(yb::tserver::ReadRequestPB const&, yb::tserver::ReadResponsePB*, yb::rpc::RpcController*, std::function<void ()>) const (this=0x65a35e80, req=..., resp=resp@entry=0x2bf91458, controller=controller@entry=0x2bf91260, callback=...) at src/yb/tserver/tserver_service.proxy.cc:419
#21 0x00007fe6cebc8464 in yb::client::internal::TabletInvoker::ReadAsync(yb::tserver::ReadRequestPB const&, yb::tserver::ReadResponsePB*, yb::rpc::RpcController*, std::function<void ()>&&) (
---Type <return> to continue, or q <return> to quit---
    this=this@entry=0x2bf912c8, req=..., resp=resp@entry=0x2bf91458, controller=0x2bf91260, cb=cb@entry=<unknown type in /home/yugabyte/lib/yb/libyb_client.so, CU 0xf73328, DIE 0x103424e>)
    at ../../src/yb/client/tablet_rpc.cc:564
#22 0x00007fe6ceb01633 in yb::client::internal::ReadRpc::CallRemoteMethod (this=0x2bf91210) at ../../src/yb/client/async_rpc.cc:700
#23 0x00007fe6ceb05e3d in yb::client::internal::AsyncRpcBase<yb::tserver::ReadRequestPB, yb::tserver::ReadResponsePB>::SendRpcToTserver (this=0x2bf91210, attempt_num=1)
    at ../../src/yb/client/async_rpc.cc:414
#24 0x00007fe6cebca106 in yb::client::internal::TabletInvoker::Execute (this=this@entry=0x2bf912c8, tablet_id=..., leader_only=<optimized out>) at ../../src/yb/client/tablet_rpc.cc:267
#25 0x00007fe6ceb00d20 in yb::client::internal::AsyncRpc::SendRpc (this=0x2bf91210) at ../../src/yb/client/async_rpc.cc:186
#26 0x00007fe6ceb0cccb in yb::client::internal::Batcher::ExecuteOperations (this=0x68e3f090, initial=...) at ../../src/yb/client/batcher.cc:523
#27 0x00007fe6ceb10c7e in yb::client::internal::Batcher::AllLookupsDone (this=this@entry=0x68e3f090) at ../../src/yb/client/batcher.cc:471
#28 0x00007fe6ceb12074 in yb::client::internal::Batcher::TabletLookupFinished (this=0x68e3f090, op=0x56db7b40, lookup_result=...) at ../../src/yb/client/batcher.cc:328
#29 0x00007fe6ceb16fc9 in _M_call<std::shared_ptr<yb::client::internal::Batcher>&, yb::client::internal::InFlightOp*&, yb::Result<scoped_refptr<yb::client::internal::RemoteTablet> > const&>
    (__ptr=..., this=0x47966360) at /home/yugabyte/linuxbrew-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/Cellar/gcc/5.5.0_4/include/c++/5.5.0/functional:634
#30 operator()<std::shared_ptr<yb::client::internal::Batcher>&, yb::client::internal::InFlightOp*&, const yb::Result<scoped_refptr<yb::client::internal::RemoteTablet> >&, void> (
    __object=..., this=0x47966360) at /home/yugabyte/linuxbrew-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/Cellar/gcc/5.5.0_4/include/c++/5.5.0/functional:610
#31 __call<void, yb::Result<scoped_refptr<yb::client::internal::RemoteTablet> > const&, 0ul, 1ul, 2ul> (__args=<optimized out>, this=0x47966360)
    at /home/yugabyte/linuxbrew-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/Cellar/gcc/5.5.0_4/include/c++/5.5.0/functional:1074
#32 operator()<const yb::Result<scoped_refptr<yb::client::internal::RemoteTablet> >&, void> (this=0x47966360)
    at /home/yugabyte/linuxbrew-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/Cellar/gcc/5.5.0_4/include/c++/5.5.0/functional:1133
#33 std::_Function_handler<void (yb::Result<scoped_refptr<yb::client::internal::RemoteTablet> > const&), std::_Bind<std::_Mem_fn<void (yb::client::internal::Batcher::*)(yb::client::internal::InFlightOp*, yb::Result<scoped_refptr<yb::client::internal::RemoteTablet> >)> (std::shared_ptr<yb::client::internal::Batcher>, yb::client::internal::InFlightOp*, std::_Placeholder<1>)> >::_M_invoke(std::_Any_data const&, yb::Result<scoped_refptr<yb::client::internal::RemoteTablet> > const&) (__functor=..., __args#0=...)
    at /home/yugabyte/linuxbrew-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/Cellar/gcc/5.5.0_4/include/c++/5.5.0/functional:1871
#34 0x00007fe6ceb8e454 in operator() (__args#0=..., this=<optimized out>)
    at /home/yugabyte/linuxbrew-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/Cellar/gcc/5.5.0_4/include/c++/5.5.0/functional:2267
#35 bool yb::client::internal::MetaCache::DoLookupTabletByKey<yb::SharedLock<std::shared_timed_mutex> >(std::shared_ptr<yb::client::YBTable const> const&, std::shared_ptr<yb::client::VersionedTablePartitionList const> const&, std::shared_ptr<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const> const&, std::chrono::time_point<yb::CoarseMonoClock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > >, std::function<void (yb::Result<scoped_refptr<yb::client::internal::RemoteTablet> > const&)>*, std::shared_ptr<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const>*)::{lambda()#1}::operator()() const (__closure=__closure@entry=0x7fe6ae6c0bd0) at ../../src/yb/client/meta_cache.cc:1852
#36 0x00007fe6ceb9a4e4 in ~ScopeExitLambda (this=0x7fe6ae6c0bd0, __in_chrg=<optimized out>) at ../../src/yb/util/scope_exit.h:36
#37 yb::client::internal::MetaCache::DoLookupTabletByKey<yb::SharedLock<std::shared_timed_mutex> >(std::shared_ptr<yb::client::YBTable const> const&, std::shared_ptr<yb::client::VersionedTablePartitionList const> const&, std::shared_ptr<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const> const&, std::chrono::time_point<yb::CoarseMonoClock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > >, std::function<void (yb::Result<scoped_refptr<yb::client::internal::RemoteTablet> > const&)>*, std::shared_ptr<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const>*) (this=this@entry=0x2e51980, table=..., partitions=..., partition_start=..., deadline=...,
    callback=callback@entry=0x7fe6ae6c1050, partition_group_start=0x7fe6ae6c0e00) at ../../src/yb/client/meta_cache.cc:1854
#38 0x00007fe6ceb86f10 in yb::client::internal::MetaCache::LookupTabletByKey(std::shared_ptr<yb::client::YBTable> const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::chrono::time_point<yb::CoarseMonoClock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > >, std::function<void (yb::Result<scoped_refptr<yb::client::internal::RemoteTablet> > const&)>) (this=0x2e51980, table=..., partition_key=..., deadline=..., callback=...) at ../../src/yb/client/meta_cache.cc:2004
#39 0x00007fe6ceb12c18 in yb::client::internal::Batcher::FlushAsync(boost::function<void (yb::Status const&)>, yb::StronglyTypedBool<yb::client::internal::IsWithinTransactionRetry_Tag>) (
    this=0x68e3f090, callback=..., is_within_transaction_retry=..., is_within_transaction_retry@entry=...) at ../../src/yb/client/batcher.cc:273
---Type <return> to continue, or q <return> to quit---
#40 0x00007fe6ceba77ae in yb::client::(anonymous namespace)::FlushBatcherAsync (batcher=..., callback=..., batcher_config=..., is_within_transaction_retry=...)
    at ../../src/yb/client/session.cc:213
#41 0x00007fe6cebac417 in yb::client::YBSession::FlushAsync(boost::function<void (yb::client::FlushStatus*)>) (this=this@entry=0x13f86390, callback=...) at ../../src/yb/client/session.cc:231
#42 0x00007fe6cebacb92 in yb::client::YBSession::FlushFuture (this=<optimized out>) at ../../src/yb/client/session.cc:243
#43 0x00007fe6cebad2cd in yb::client::YBSession::FlushAndGetOpsErrors (this=<optimized out>) at ../../src/yb/client/session.cc:135
#44 0x00007fe6cebc482f in yb::client::TableIterator::ExecuteOps (this=this@entry=0x7fe6ae6c1bb0) at ../../src/yb/client/table_handle.cc:258
#45 0x00007fe6cebc5ac7 in yb::client::TableIterator::TableIterator (this=0x7fe6ae6c1bb0, table=0x51a00fb0, options=...) at ../../src/yb/client/table_handle.cc:246
#46 0x00007fe6d1cc56a4 in begin (this=0x7fe6ae6c1a30) at ../../src/yb/client/table_handle.h:227
#47 yb::cdc::CDCServiceImpl::UpdateLagMetrics (this=this@entry=0x2017800) at ../../ent/src/yb/cdc/cdc_service.cc:1240
#48 0x00007fe6d1cc6814 in yb::cdc::CDCServiceImpl::UpdatePeersAndMetrics (this=0x2017800) at ../../ent/src/yb/cdc/cdc_service.cc:1387
#49 0x00007fe6c361d7a0 in ?? () from /home/yugabyte/linuxbrew/lib/libstdc++.so.6
#50 0x00007fe6c2e32694 in start_thread (arg=0x7fe6ae6ca700) at pthread_create.c:333
#51 0x00007fe6c256f41d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

Thread apply all bt attached here
[restart_core_sigsegv.txt](https://github.com/yugabyte/yugabyte-db/files/8493186/restart_core_sigsegv.txt)

**Comment by ajcaldera1** [comment]
This occurred after a restart due to #12175

**Comment by rthallamko3** [comment]
@suranjan , Is this CDC related?

**Comment by suranjan** [comment]
Yes, this has been fixed. Closing it.
