### ISSUE TITLE
[YSQL] Query error: Restart read required at: { read: { physical: .. } local_limit: { physical: .. } global_limit: ...

### ISSUE THREAD

**Issue by kmuthukk** [YugaByte/yugabyte-db#1233]
When trying to do concurrent inserts to a table, where a column is indexed, getting read-restart error.  If num_write_threads below is set to 1, then the issue doesn't happen.

Test Case:
```
import psycopg2;
from multiprocessing.dummy import Pool as ThreadPool

num_write_threads=2
num_users=500

def create_table():
  conn = psycopg2.connect("host=localhost dbname=postgres user=postgres port=5433")
  conn.set_session(autocommit=True)
  cur = conn.cursor()
  cur.execute("""DROP TABLE IF EXISTS users""");
  cur.execute("""CREATE TABLE IF NOT EXISTS users(
                      id     text,
                      ename  text,
                      age    int,
                      PRIMARY KEY(id))
              """)
  print("Created users table")
  print("====================")
  cur.execute("""
          CREATE INDEX IF NOT EXISTS name_idx ON users(ename)
    """)
  print("Created name_idx on table")


def load_data_slave(thread_num):
  thread_id = str(thread_num)
  conn = psycopg2.connect("host=localhost dbname=postgres user=postgres port=5433")
  conn.set_session(autocommit=True)
  cur = conn.cursor()

  print("Thread-" + thread_id + ": Inserting %d rows..." % (num_users))
  # "name" column is indexed, and may have duplicates across threads.
  for idx in range(num_users):
    cur.execute("""INSERT INTO users (id, ename, age) VALUES (%s, %s, %s)""",
                ("user-"+thread_id+"-"+str(idx),
                 "name--"+str(idx),
                  20 + (idx % 50)))
  print("Thread-" + thread_id + ": Inserted %d rows" %  (num_users))

def load_data():
  pool = ThreadPool(num_write_threads)
  results = pool.map(load_data_slave, range(num_write_threads))

# Main
create_table()
load_data()
```

Output:
```
02:29 $ python ~/notes/sql_index_read_restart_bug.py
Created users table
====================
Created name_idx on table
Thread-0: Inserting 500 rows...
Thread-1: Inserting 500 rows...
Traceback (most recent call last):
  File "/home/centos/notes/sql_index_read_restart_bug.py", line 48, in <module>
    load_data()
  File "/home/centos/notes/sql_index_read_restart_bug.py", line 43, in load_data
    results = pool.map(load_data_slave, range(num_write_threads))
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 250, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 554, in get
    raise self._value
psycopg2.errors.InternalError_: Query error: Restart read required at: { read: { physical: 1555727379834828 } local_limit: { physical: 1555727379835572 } global_limit: <min> in_txn_limit: <max> serial_no: 0 }
```

**Comment by kmuthukk** [comment]
The issue seems specific to YSQL and does not repro with an equivalent program in YCQL (which also supports strongly-consistent secondary indexes using distributed transactions). This seems to suggest the YB SQL Layer needs to handle and retry the error internally like the YB YCQL Layer.

Equivalent YCQL test which doesn't have the same issue:

```
from cassandra.cluster import Cluster
import time
import random
from multiprocessing.dummy import Pool as ThreadPool

# Load Phase params
num_write_threads=4
num_users=500

cluster = Cluster(['127.0.0.1'])
session = cluster.connect()

def create_table():
  start_time = time.time()
  session.execute("""CREATE KEYSPACE IF NOT EXISTS k""");
  session.execute("""USE k""");
  session.execute("""DROP TABLE IF EXISTS users""");
  now_time = time.time()
  print("Dropped (if exists): users table")
  print("Time: %s ms" % ((now_time - start_time) * 1000))
  print("====================")
  start_time = time.time()
  session.execute("""
        CREATE TABLE IF NOT EXISTS users(
           id     text,
           name   text,
           age    int,
           PRIMARY KEY(id)
        ) WITH TRANSACTIONS = {'enabled' : true}
    """)
  now_time = time.time()
  print("Created users table")
  print("Time: %s ms" % ((now_time - start_time) * 1000))
  print("====================")
  start_time = time.time()
  session.execute("""
          CREATE INDEX IF NOT EXISTS name_idx ON users(name)
   """)
  now_time = time.time()
  print("Created users table")
  print("Time: %s ms" % ((now_time - start_time) * 1000))
  print("====================")


def load_data_slave(thread_num):
  thread_id = str(thread_num)
  print("Thread-" + thread_id + ": Inserting %d rows..." % (num_users))
  start_time = time.time()
  for idx in range(num_users):
    session.execute("""INSERT INTO users (id, name, age) VALUES (%s, %s, %s)""",
                       ("user-"+thread_id+"-"+str(idx),
                        "name--"+str(idx),
                        20 + (idx % 50)))
  now_time = time.time()
  print("Thread-" + thread_id + ": Inserted %d rows" %  (num_users))
  print("Thread-" + thread_id + ": Time: %s ms" % ((now_time - start_time) * 1000))
  print("Thread-" + thread_id + ": Inserts/sec: %s" % (num_users / (now_time - start_time)))
  print("Thread-" + thread_id + ": Avg Time: %s ms" % ((now_time - start_time) * 1000 / (num_users)))

def load_data():
  pool = ThreadPool(num_write_threads)
  t1 = time.time()
  results = pool.map(load_data_slave, range(num_write_threads))
  t2 = time.time()
  total_rows=num_users*num_write_threads
  print("====================")
  print("Inserted %d rows" %  (total_rows))
  print("Total Time: %s ms" % ((t2 - t1) * 1000))
  print("Inserts/sec: %s" % (total_rows / (t2 - t1)))
  print("====================")

# Main
create_table()
load_data()
```

Output:

```
01:18 $ python /tmp/test.py
Dropped (if exists): users table
Time: 2094.66004372 ms
====================
Created users table
Time: 1079.32710648 ms
====================
Created users table
Time: 865.906953812 ms
====================
Thread-0: Inserting 500 rows...
Thread-1: Inserting 500 rows...Thread-2: Inserting 500 rows...

Thread-3: Inserting 500 rows...
Thread-0: Inserted 500 rows
Thread-0: Time: 1757.3120594 ms
Thread-0: Inserts/sec: 284.525447444
Thread-0: Avg Time: 3.5146241188 ms
Thread-2: Inserted 500 rows
Thread-2: Time: 1772.91202545 ms
Thread-2: Inserts/sec: 282.021889875
Thread-2: Avg Time: 3.5458240509 ms
Thread-3: Inserted 500 rows
Thread-3: Time: 1777.57501602 ms
Thread-3: Inserts/sec: 281.282081202
Thread-3: Avg Time: 3.55515003204 ms
Thread-1: Inserted 500 rows
Thread-1: Time: 1788.73205185 ms
Thread-1: Inserts/sec: 279.527612581
Thread-1: Avg Time: 3.5774641037 ms
====================
Inserted 2000 rows
Total Time: 1789.66403008 ms
Inserts/sec: 1117.52818763
====================
```

**Comment by bbaddepudi** [comment]
Ran into same symptom on a local cluster. Created it with RF=3
`~/code/yugabyte/bin/yb-ctl  --replication_factor 3 create`

Running this command:
`/usr/bin/java -jar ~/code/yb-sample-apps/target/yb-sample-apps.jar --num_unique_keys 1000000 --num_threads_read 2 --num_threads_write 2 --workload SqlSecondaryIndex --value_size 16 --nodes 127.0.0.1:5433,127.0.0.2:5433,127.0.0.3:5433 --use_ascii_values --sanity_check_at_end`

caused the following error:
`21700 [Thread-2] FATAL com.yugabyte.sample.apps.SqlSecondaryIndex  - Failed writing key: 3b8272f0-7c72-4d09-8288-84516d777cee:13
org.postgresql.util.PSQLException: ERROR: Query error: Restart read required at: { read: { physical: 1557294268666485 } local_limit: { physical: 1557294268669703 } global_limit: <min> in_txn_limit: <max> serial_no: 0 }
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2178)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:306)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:155)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:132)
	at com.yugabyte.sample.apps.SqlSecondaryIndex.doWrite(SqlSecondaryIndex.java:162)
	at com.yugabyte.sample.apps.AppBase.performWrite(AppBase.java:632)
	at com.yugabyte.sample.common.IOPSThread.run(IOPSThread.java:87)
23253 [Thread-1] INFO com.yugabyte.sample.common.metrics.MetricsTracker  - Read: 0.00 ops/sec (0.00 ms/op), 0 total ops  |  Write: 42.56 ops/sec (93.77 ms/op), 213 total ops  |  Uptime: 10010 ms | 
...
`

**Comment by butla** [comment]
I'm having that error right now. This issue being closed means that it should be fixed? I'm just runnig a local cluster (created with `yb-docker-ctl create --rf 3`), as I'm evaluating yugabyte for our HA solution :)

**Comment by spolitov** [comment]
Is your scenario the same as described in the issue?

**Comment by butla** [comment]
I think it's even simpler. My table definition: `create table bla(id SERIAL primary key, value BIGINT);`. I'm using separate python processes to keep updating a single row with:

```
UPDATE bla
SET value = value + 1
WHERE ID=1;
```

**Comment by koder-ua** [comment]
Having the same issue on with plain select  in RR transaction, consists of one statement
SELECT * FROM x WHERE status!=10

**Comment by pilshchikov** [comment]
Can reproduce if run 3 workloads in the same time:
```
java -jar yb-sample-apps.jar --workload SqlDataLoad  --num_writes 10000000 --num_threads_write 50 --num_threads_read 0 --num_reads 0 --num_unique_keys 100000000 --num_foreign_key_table_rows 1000000 --create_table_name table_10_9_13_31_b807fb_SqlDataLoad --uuid 25de165a-ae41-4d62-a7c6-187ca785df4e --nodes 
java -jar yb-sample-apps.jar --workload SqlSecondaryIndex  --num_writes 10000000 --num_threads_write 50 --num_threads_read 0 --num_reads 0 --num_unique_keys 100000000 --create_table_name table_10_9_5_4_9f6fb3_SqlSecondaryIndex --uuid 5ea031fc-bece-4c3c-840b-99e20f372275 --nodes 
java -jar yb-sample-apps.jar --workload SqlSnapshotTxns  --num_writes 10000000 --num_threads_write 50 --num_threads_read 0 --num_reads 0 --num_unique_keys 100000000 --create_table_name table_10_9_13_31_3df7dc_SqlSnapshotTxns --uuid 3820ad03-e3c3-47c5-bf51-e7b2d3d167f4 --nodes 
```
It throws errors but after some retries, it starts to load data
```
1470 [main] INFO com.yugabyte.sample.apps.SqlSnapshotTxns  - Dropping table(s) left from previous runs if any
2972 [main] INFO com.yugabyte.sample.apps.SqlSnapshotTxns  - Created table: table_10_9_13_31_3df7dc_sqlsnapshottxns
4299 [Thread-17] INFO com.yugabyte.sample.apps.AppBase  - Going to retrieve connection again: FATAL: Query error: Restart read required at: { read: { physical: 1631123325263408 } local_limit: { physical: 1631123325255929 } global_limit: <min> in_txn_limit: <max> serial_no: 0 }
4323 [Thread-18] INFO com.yugabyte.sample.apps.AppBase  - Going to retrieve connection again: FATAL: Query error: Restart read required at: { read: { physical: 1631123325263408 } local_limit: { physical: 1631123325281777 logical: 3 } global_limit: <min> in_txn_limit: <max> serial_no: 0 }
4330 [Thread-19] INFO com.yugabyte.sample.apps.AppBase  - Going to retrieve connection again: FATAL: Query error: Restart read required at: { read: { physical: 1631123325263408 } local_limit: { physical: 1631123325299558 logical: 8 } global_limit: <min> in_txn_limit: <max> serial_no: 0 }
4331 [Thread-16] INFO com.yugabyte.sample.apps.AppBase  - Going to retrieve connection again: FATAL: Query error: Restart read required at: { read: { physical: 1631123325263408 } local_limit: { physical: 1631123325292669 logical: 4095 } global_limit: <min> in_txn_limit: <max> serial_no: 0 }
4352 [Thread-22] INFO com.yugabyte.sample.apps.AppBase  - Going to retrieve connection again: FATAL: Query error: Restart read required at: { read: { physical: 1631123325263408 } local_limit: { physical: 1631123325271681 logical: 4095 } global_limit: <min> in_txn_limit: <max> serial_no: 0 }
4353 [Thread-21] INFO com.yugabyte.sample.apps.AppBase  - Going to retrieve connection again: FATAL: Query error: Restart read required at: { read: { physical: 1631123325263408 } local_limit: { physical: 1631123325300913 logical: 6 } global_limit: <min> in_txn_limit: <max> serial_no: 0 }
4367 [Thread-20] INFO com.yugabyte.sample.apps.AppBase  - Going to retrieve connection again: FATAL: Query error: Restart read required at: { read: { physical: 1631123325263408 } local_limit: { physical: 1631123325335312 logical: 3 } global_limit: <min> in_txn_limit: <max> serial_no: 0 }
4763 [Thread-31] INFO com.yugabyte.sample.apps.AppBase  - Going to retrieve connection again: FATAL: Query error: Restart read required at: { read: { physical: 1631123325731483 logical: 30 } local_limit: { physical: 1631123325731217 } global_limit: <min> in_txn_limit: <max> serial_no: 0 }
4766 [Thread-30] INFO com.yugabyte.sample.apps.AppBase  - Going to retrieve connection again: FATAL: Query error: Restart read required at: { read: { physical: 1631123325731483 logical: 30 } local_limit: { physical: 1631123325727739 logical: 8 } global_limit: <min> in_txn_limit: <max> serial_no: 0 }
4835 [Thread-32] INFO com.yugabyte.sample.apps.AppBase  - Going to retrieve connection again: FATAL: Query error: Restart read required at: { read: { physical: 1631123325731483 logical: 30 } local_limit: { physical: 1631123325810256 } global_limit: <min> in_txn_limit: <max> serial_no: 0 }
7994 [Thread-0] INFO com.yugabyte.sample.common.metrics.MetricsTracker  - Read: 0.00 ops/sec (0.00 ms/op), 0 total ops  |  Write: 237.73 ops/sec (23.68 ms/op), 1189 total ops  |  Uptime: 5021 ms | 
12994 [Thread-0] INFO com.yugabyte.sample.common.metrics.MetricsTracker  - Read: 0.00 ops/sec (0.00 ms/op), 0 total ops  |  Write: 3.40 ops/sec (7233.94 ms/op), 1206 total ops  |  Uptime: 10021 ms | 
17995 [Thread-0] INFO com.yugabyte.sample.common.metrics.MetricsTracker  - Read: 0.00 ops/sec (0.00 ms/op), 0 total ops  |  Write: 135.39 ops/sec (327.17 ms/op), 1883 total ops  |  Uptime: 15022 ms | 
```
