### ISSUE TITLE
[ASAN Unit Test Failure] RaftConsensusITest.VerifyTransactionOrder

### ISSUE THREAD

**Issue by kripasreenivasan** [yugabyte/yugabyte-db#12392]
Jira Link: [DB-1813](https://yugabyte.atlassian.net/browse/DB-1813)
### Description

The Unit test RaftConsensusITest.VerifyTransactionOrder is failing with ASAN issues.
Failure stack trace- https://gist.github.com/kripasreenivasan/f3747ce9fed1fec3ef953bae8e7b9f27 

CC: @spolitov yb::rpc::ParseRemoteMethod(yb::Slice const&) $YB_SRC_ROOT/build/asan-clang12-dynamic-ninja/../../src/yb/rpc/serialization.cc:271:19

**Comment by bmatican** [comment]
```
[ts-2] READ of size 1 at 0x6130001b0b55 thread T13 (TabletServer_re)
...
[ts-2]     #4 0x7f321189ef3c in yb::rpc::YBInboundCall::ToString() const $YB_SRC_ROOT/build/asan-clang12-dynamic-ninja/../../src/yb/rpc/yb_rpc.cc:369:25
...
[ts-2]     #14 0x7f32117428df in yb::rpc::RpcCall::Transferred(yb::Status const&, yb::rpc::Connection*) $YB_SRC_ROOT/build/asan-clang12-dynamic-ninja/../../src/yb/rpc/rpc_call.cc:29:3
[ts-2]     #15 0x7f32116999ce in yb::rpc::Connection::Shutdown(yb::Status const&) $YB_SRC_ROOT/build/asan-clang12-dynamic-ninja/../../src/yb/rpc/connection.cc:138:11

[ts-2] freed by thread T9 (iotp_TabletServ) here:
...
[ts-2]     #4 0x7f32116d58ca in yb::rpc::InboundCall::Clear() $YB_SRC_ROOT/build/asan-clang12-dynamic-ninja/../../src/yb/rpc/inbound_call.cc:212:17
[ts-2]     #5 0x7f32116d57c9 in yb::rpc::InboundCall::RespondTimedOutIfPending(char const*) $YB_SRC_ROOT/build/asan-clang12-dynamic-ninja/../../src/yb/rpc/inbound_call.cc:205:3
[ts-2]     #6 0x7f321186ef78 in yb::rpc::ServicePoolImpl::TimedOut(yb::rpc::InboundCall*, char const*, yb::Counter*) $YB_SRC_ROOT/build/asan-clang12-dynamic-ninja/../../src/yb/rpc/service_pool.cc:286:15
[ts-2]     #7 0x7f321186ebc0 in yb::rpc::ServicePoolImpl::CheckTimeout(long, std::chrono::time_point<yb::CoarseMonoClock, std::chrono::duration<long long, std::ratio<1l, 1000000000l> > >, yb::Status const&) $YB_SRC_ROOT/build/asan-clang12-dynamic-ninja/../../src/yb/rpc/service_pool.cc:337:11
[ts-2]     #8 0x7f321186e894 in yb::rpc::ServicePoolImpl::ScheduleCheckTimeout(std::chrono::time_point<yb::CoarseMonoClock, std::chrono::duration<long long, std::ratio<1l, 1000000000l> > >)::'lambda'()::operator()() const::'lambda'(long, yb::Status const&)::operator()(long, yb::Status const&) const::'lambda'()::operator()() const $YB_SRC_ROOT/build/asan-clang12-dynamic-ninja/../../src/yb/rpc/service_pool.cc:375:19
```

Seems like some race on call timeout vs connection destroy.
