### ISSUE TITLE
[DocDB] Upgrade on Linux aarch64 fails

### ISSUE THREAD

**Issue by def-** [yugabyte/yugabyte-db#12393]
### Description

Tried from 2.13.2.0-b68 (fresh installation) to 2.13.2.0-b122, getting failed health checks:
```
Version from platform metadata 2.13.2.0-b68-arm, version reported by instance process 2.13.2.0-b122
```
This is without systemd, upgraded using YugabyteDB Anywhere UI.

**Comment by def-** [comment]
Upgrade failure:
```
Failed to execute task {"nodeExporterUser":"prometheus","universeUUID":"07dc9421-542c-4be3-b7bd-3ce7be36764d","encryptionAtRestConfig":{"encryptionAtRestEnabled":false,"opType":"UNDEFINED","type":"DATA_KEY"},"communicationPorts":{"masterHttpPort":7000,"masterRpcPort":7100,"tserverHttpPort":9000,"tserverRpcPort":9100,"redisServerHttpPort":11000,"redisServerRpcPort":6379,"yqlServerHttpPort":12000,"yqlServerRpcPort":9042,"ysqlServerHttpPort":13000,"ysqlServerRpcPort":5433,"nodeExporterPort":9300},"extraDependencies":{..., hit error:

Error occurred. Output: [0;32m[2022-05-04_15_39_00 common.sh:327 activate_virtualenv][0m Using virtualenv python executable now.
[0;32m[2022-05-04_15_39_00 common.sh:327 activate_virtualenv][0m Using virtualenv python executable now.
/opt/yugabyte/devops/venv/lib64/python3.6/site-packages/paramiko/kex_ecdh_nist.py:39: CryptographyDeprecationWarning: encode_point has been deprecated on EllipticCurvePublicNumbers and will be removed in a future version. Please use EllipticCurvePublicKey.public_bytes to obtain both compressed and uncompressed point encoding.
  m.add_string(self.Q_C.public_numbers().encode_point())
/opt/yugabyte/devops/venv/lib64/python3.6/site-packages/paramiko/kex_ecdh_nist.py:96: CryptographyDeprecationWarning: Support for unsafe construction of public numbers from encoded data will be removed in a future version. Please use EllipticCurvePublicKey.from_encoded_point
  self.curve, Q_S_bytes
/opt/yugabyte/devops/venv/lib64/python3.6/site-packages/paramiko/kex_ecdh_nist.py:111: CryptographyDeprecationWarning: encode_point has been deprecated on EllipticCurvePublicNumbers and will be removed in a future version. Please use EllipticCurvePublicKey.public_bytes to obtain both compressed and uncompressed point encoding.
  hm.add_string(self.Q_C.public_numbers().encode_point())
Traceback (most recent call last):
  File "bin/run_node_action.py", line 207, in <module>
    main()
  File "bin/run_node_action.py", line 200, in main
    actions[args.action].handler(args, client)
  File "bin/run_node_action.py", line 39, in handle_run_command
    output = client.exec_command(args.command)
  File "/opt/yugabyte/devops/bin/node_client_utils.py", line 95, in exec_command
    raise RuntimeError('Command returned error code {}: {}'.format(command, error))
RuntimeError: Command returned error code /usr/bin/timeout 924 /home/yugabyte/master/bin/yb-admin --master_addresses X -timeout_ms 924000 upgrade_ysql: Error running upgrade_ysql: Network error (yb/yql/pgwrapper/libpq_utils.cc:233): Unable to upgrade YSQL cluster: Execute of 'SET ysql_upgrade_mode TO true;' failed: 7, message: ERROR:  permission denied to set parameter "ysql_upgrade_mode"
 (pgsql error 42501).
```

**Comment by anmalysh-yb** [comment]
Link to the universe: http://portal.dev.yugabyte.com/universes/07dc9421-542c-4be3-b7bd-3ce7be36764d

**Comment by def-** [comment]
There were multiple issues, systemd was enabled, server had unexpected user changes. Will reopen if this fails again.
