### ISSUE TITLE
[DocDB] Postgres process segfaults in __longjmp on AlmaLinux 8 x86_64 with GCC 11

### ISSUE THREAD

**Issue by mbautin** [yugabyte/yugabyte-db#12429]
Jira Link: [DB-1825](https://yugabyte.atlassian.net/browse/DB-1825)
### Description

```
Thread 1 (Thread 0x7f95560852c0 (LWP 3626833)):
#0  0x00007f955b25b0de in __longjmp () from /lib64/libc.so.6
#1  0xd72864f5212de5ba in ?? ()
Backtrace stopped: Cannot access memory at address 0xd70064f5212de5ba
```

Third-party dependencies built from commit https://github.com/yugabyte/yugabyte-db-thirdparty/commits/4cda3bf56cf142f9f3f5767f224d8e48a02d14d1 using GCC 11 (`./build_thirdparty.sh --devtoolset=11`).

This happens at least in debug and fastdebug buidls.

https://gist.githubusercontent.com/mbautin/1520f3dafee889bf35ef67f353202ea8/raw

Also sometimes there is a different core dump stack trace, involving `__strtoll`: https://gist.githubusercontent.com/mbautin/e4fda551ad1058037aaf40bd64c1707c/raw

This problem does not happen if third-party dependencies are built with GCC 9.

TODO: check if this is happening on CentOS 7.

Test command line:
```
./yb_build.sh --gcc11 --cxx-test pg_mini-test --gtest_filter PgMiniTest.BigInsert
```

**Comment by mbautin** [comment]
This also occurs on CentOS 7 x86_64 debug build when third-party dependencies are built with GCC 10 and YugabyteDB is built with GCC 11.
https://gist.githubusercontent.com/mbautin/f4e09b464bd79aa6333c630457acefee/raw

**Comment by mbautin** [comment]
Another backtrace on CentOS 7 (thirdparty built with GCC 10):
https://gist.githubusercontent.com/mbautin/5db8a3692b740e9138de32e8018995ed/raw

**Comment by mbautin** [comment]
When setting YB_PG_STACK_TRACE_ON_ERROR=1, the first postgres process that crashes output the following stack trace:
```
E0524 00:00:06.187247 40824 readfuncs.c:2868] Postgres error: ERROR
    @     0x7fe18c225b44  YBCLogImpl (src/yb/common/ybc_util.cc:317)
    @           0x9bf0a7  errstart (src/postgres/src/backend/utils/error/elog.c:424)
    @           0x9c41aa  elog_finish (src/postgres/src/backend/utils/error/elog.c:1463)
    @           0x7703a1  readDatum (src/postgres/src/backend/nodes/readfuncs.c:2868)
    @           0x77066d  _readConst (src/postgres/src/backend/nodes/readfuncs.c:557)
    @           0x772036  parseNodeString (src/postgres/src/backend/nodes/readfuncs.c:2594)
    @           0x774dd6  nodeRead (src/postgres/src/backend/nodes/read.c:313)
    @           0x774e81  nodeRead (src/postgres/src/backend/nodes/read.c:379)
    @           0x7737e3  _readArrayExpr (src/postgres/src/backend/nodes/readfuncs.c:1008)
    @           0x7737e3  parseNodeString (src/postgres/src/backend/nodes/readfuncs.c:2642)
    @           0x774dd6  nodeRead (src/postgres/src/backend/nodes/read.c:313)
    @           0x774e81  nodeRead (src/postgres/src/backend/nodes/read.c:379)
    @           0x772a55  _readScalarArrayOpExpr (src/postgres/src/backend/nodes/readfuncs.c:777)
    @           0x772a55  parseNodeString (src/postgres/src/backend/nodes/readfuncs.c:2616)
    @           0x774dd6  nodeRead (src/postgres/src/backend/nodes/read.c:313)
    @           0x774e81  nodeRead (src/postgres/src/backend/nodes/read.c:379)
    @           0x772bb4  _readBoolExpr (src/postgres/src/backend/nodes/readfuncs.c:803)
    @           0x772bb4  parseNodeString (src/postgres/src/backend/nodes/readfuncs.c:2618)
    @           0x774dd6  nodeRead (src/postgres/src/backend/nodes/read.c:313)
    @           0x76b63a  _readFromExpr (src/postgres/src/backend/nodes/readfuncs.c:1307)
    @           0x773bab  parseNodeString (src/postgres/src/backend/nodes/readfuncs.c:2678)
    @           0x774dd6  nodeRead (src/postgres/src/backend/nodes/read.c:313)
    @           0x76ad1a  _readQuery (src/postgres/src/backend/nodes/readfuncs.c:257)
    @           0x7716d1  parseNodeString (src/postgres/src/backend/nodes/readfuncs.c:2568)
    @           0x774dd6  nodeRead (src/postgres/src/backend/nodes/read.c:313)
    @           0x774e81  nodeRead (src/postgres/src/backend/nodes/read.c:379)
    @           0x775282  stringToNode (src/postgres/src/backend/nodes/read.c:77)
    @           0x9abc66  YBRelationBuildRuleLock (src/postgres/src/backend/utils/cache/relcache.c:853)
    @           0x9abc66  YbCompleteProcessingImpl (src/postgres/src/backend/utils/cache/relcache.c:1614)
    @           0x9abc66  YbCompleteProcessing (src/postgres/src/backend/utils/cache/relcache.c:1638)
    @           0x9ae57c  YBUpdateRelationsAttributes (src/postgres/src/backend/utils/cache/relcache.c:1666)
    @           0x9ae57c  YBPreloadRelCache (src/postgres/src/backend/utils/cache/relcache.c:1806)
    @           0x9b4266  RelationCacheInitializePhase3 (src/postgres/src/backend/utils/cache/relcache.c:4379)
    @           0x9d3567  InitPostgresImpl (src/postgres/src/backend/utils/init/postinit.c:1074)
    @           0x9d3567  InitPostgres (src/postgres/src/backend/utils/init/postinit.c:1148)
    @           0x87fd95  PostgresMain (src/postgres/src/backend/tcop/postgres.c:4832)
    @           0x7e9490  BackendRun (src/postgres/src/backend/postmaster/postmaster.c:4555)
    @           0x7e9490  BackendStartup (src/postgres/src/backend/postmaster/postmaster.c:4198)
    @           0x7e9490  ServerLoop (src/postgres/src/backend/postmaster/postmaster.c:1767)
    @           0x7eb71a  PostmasterMain (src/postgres/src/backend/postmaster/postmaster.c:1423)
    @           0x741286  PostgresServerProcessMain (src/postgres/src/backend/main/main.c:234)
    @           0x74135b
    @     0x7fe18b64f554
    @           0x48e903
    @ 0xffffffffffffffff
2022-05-24 00:00:06.607 UTC [40815] LOG:  server process (PID 40824) was terminated by signal 11: Segmentation fault
2022-05-24 00:00:06.607 UTC [40815] LOG:  terminating any other active server processes
```
This is CentOS 7 x86_64, fastdebug-gcc11-dynamic-ninja, thirdparty built with GCC 10.

**Comment by mbautin** [comment]
The readDatum function is as follows:
```
   2813 /*
   2814  * readDatum
   2815  *
   2816  * Given a string representation of a constant, recreate the appropriate
   2817  * Datum.  The string representation embeds length info, but not byValue,
   2818  * so we must be told that.
   2819  */
   2820 Datum
   2821 readDatum(bool typbyval)
   2822 {
   2823         Size            length,
   2824                                 i;
   2825         int                     tokenLength;
   2826         char       *token;
   2827         Datum           res;
   2828         char       *s;
   2829
   2830         /*
   2831          * read the actual length of the value
   2832          */
   2833         token = pg_strtok(&tokenLength);
   2834         length = atoui(token);
   2835
   2836         token = pg_strtok(&tokenLength);        /* read the '[' */
   2837         if (token == NULL || token[0] != '[')
   2838                 elog(ERROR, "expected \"[\" to start datum, but got \"%s\"; length = %zu",
   2839                          token ? (const char *) token : "[NULL]", length);
   2840
   2841         if (typbyval)
   2842         {
   2843                 if (length > (Size) sizeof(Datum))
   2844                         elog(ERROR, "byval datum but length = %zu", length);
   2845                 res = (Datum) 0;
   2846                 s = (char *) (&res);
   2847                 for (i = 0; i < (Size) sizeof(Datum); i++)
   2848                 {
   2849                         token = pg_strtok(&tokenLength);
   2850                         s[i] = (char) atoi(token);
   2851                 }
   2852         }
   2853         else if (length <= 0)
   2854                 res = (Datum) NULL;
   2855         else
   2856         {
   2857                 s = (char *) palloc(length);
   2858                 for (i = 0; i < length; i++)
   2859                 {
   2860                         token = pg_strtok(&tokenLength);
   2861                         s[i] = (char) atoi(token);
   2862                 }
   2863                 res = PointerGetDatum(s);
   2864         }
   2865
   2866         token = pg_strtok(&tokenLength);        /* read the ']' */
   2867         if (token == NULL || token[0] != ']')
   2868                 elog(ERROR, "expected \"]\" to end datum, but got \"%s\"; length = %zu",  /* <-- ERROR HAPPENS HERE */
   2869                          token ? (const char *) token : "[NULL]", length);
   2870
   2871         return res;
   2872 }
```

**Comment by mbautin** [comment]
Tried preloading gcc9-built versions of various libraries that the postgres binary depends on using LD_PRELOAD. More precisely, tried preloading all libraries except one, for each library. Found that if I don't preload libsnappy, the test fails, otherwise it succeeds.

```
( ulimit -c 0; for l in $( cat gcc9_libs.txt ); do ( LD_PRELOAD=$( echo $(cat gcc9_libs.txt | grep -v "$l"  ) )   build/fastdebug-gcc11-dynamic-ninja/tests-pgwrapper/pg_mini-test --gtest_filter=PgMiniTest.BigInsert |& tee ~/test/gcc11_pg_segfault/preload_without_${l##*/}.txt ); done )
```
Result:
```
 ~/test/gcc11_pg_segfault # ls -l
total 20716
-rw-rw-r--. 1 centos centos  786080 May 24 00:23 preload_without_libbacktrace.so.0.txt
-rw-rw-r--. 1 centos centos  795130 May 24 00:22 preload_without_libboost_atomic.so.1.78.0.txt
-rw-rw-r--. 1 centos centos  785622 May 24 00:21 preload_without_libboost_system.so.1.78.0.txt
-rw-rw-r--. 1 centos centos  720884 May 24 00:22 preload_without_libboost_thread.so.1.78.0.txt
-rw-rw-r--. 1 centos centos  753829 May 24 00:22 preload_without_libcds.so.2.3.3.txt
-rw-rw-r--. 1 centos centos  766320 May 24 00:21 preload_without_libcom_err.so.3.txt
-rw-rw-r--. 1 centos centos  761440 May 24 00:22 preload_without_libcrcutil.so.0.txt
-rw-rw-r--. 1 centos centos  731417 May 24 00:19 preload_without_libcrypto.so.1.1.txt
-rw-rw-r--. 1 centos centos  769300 May 24 00:23 preload_without_libcurl.so.4.txt
-rw-rw-r--. 1 centos centos  771293 May 24 00:23 preload_without_libev.so.4.txt
-rw-rw-r--. 1 centos centos  727958 May 24 00:23 preload_without_libgflags.so.2.txt
-rw-rw-r--. 1 centos centos  756601 May 24 00:24 preload_without_libglog.so.0.txt
-rw-rw-r--. 1 centos centos  753018 May 24 00:19 preload_without_libgssapi_krb5.so.2.txt
-rw-rw-r--. 1 centos centos  762482 May 24 00:20 preload_without_libicudata.so.70.txt
-rw-rw-r--. 1 centos centos  734515 May 24 00:20 preload_without_libicui18n.so.70.txt
-rw-rw-r--. 1 centos centos  758883 May 24 00:20 preload_without_libicuuc.so.70.txt
-rw-rw-r--. 1 centos centos  719855 May 24 00:21 preload_without_libk5crypto.so.3.txt
-rw-rw-r--. 1 centos centos  747888 May 24 00:21 preload_without_libkeyutils.so.1.txt
-rw-rw-r--. 1 centos centos  792112 May 24 00:20 preload_without_libkrb5.so.3.txt
-rw-rw-r--. 1 centos centos  756984 May 24 00:21 preload_without_libkrb5support.so.0.txt
-rw-rw-r--. 1 centos centos  756120 May 24 00:21 preload_without_liblber-2.4.so.2.txt
-rw-rw-r--. 1 centos centos  766831 May 24 00:19 preload_without_libldap-2.4.so.2.txt
-rw-rw-r--. 1 centos centos  764869 May 24 00:24 preload_without_libprotobuf.so.15.txt
-rw-rw-r--. 1 centos centos 1469003 May 24 00:25 preload_without_libsnappy.so.1.txt
-rw-rw-r--. 1 centos centos  747009 May 24 00:19 preload_without_libssl.so.1.1.txt
-rw-rw-r--. 1 centos centos  752610 May 24 00:24 preload_without_libuuid.so.1.txt
-rw-rw-r--. 1 centos centos  757172 May 24 00:23 preload_without_libz.so.1.txt
```

**Comment by mbautin** [comment]
The following makes the test pass (the rest of third-party dependencies are built with GCC 10):
```
export LD_PRELOAD=/opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20220420172538-91c632476c-centos7-x86_64-gcc9/installed/uninstrumented/lib/libsnappy.so.1
build/fastdebug-gcc11-dynamic-ninja/tests-pgwrapper/pg_mini-test --gtest_filter=PgMiniTest.BigInsert
```

**Comment by mbautin** [comment]
The two snappy builds are as follows:

Working:

/opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20220420172538-91c632476c-centos7-x86_64-gcc9/installed/uninstrumented/lib/libsnappy.so.1

Not working:

/opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20220522045151-83261e39a2-centos7-x86_64-gcc10/installed/uninstrumented/lib/libsnappy.so.1

Here is a diff command to view the differences between disassembled versions of the two libraries, just in case:

```
diff --side-by-side  --width=350 <( objdump -d /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20220420172538-91c632476c-centos7-x86_64-gcc9/installed/uninstrumented/lib/libsnappy.so.1 | sed -r 's/[0-9a-f]+://g' | c++filt ) <(objdump -d /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20220522045151-83261e39a2-centos7-x86_64-gcc10/installed/uninstrumented/lib/libsnappy.so.1 | sed -r 's/[0-9a-f]+://g' | c++filt ) | less -N
```

Diff: 

https://gist.githubusercontent.com/mbautin/555fc8a8d25199bd0559d075f90074fa/raw
