### ISSUE TITLE
[Ossexp] yugabyted unable to start due to a missing function

### ISSUE THREAD

**Issue by vaibhav-yb** [yugabyte/yugabyte-db#12472]
While trying to start yugabyted on a AlmaLinux8 machine, yugabyted is unable to start the process.

Steps to reproduce:
Execute the following command:
```bash
./bin/yugabyted start --advertise_address $(hostname -i)
```

The output which comes up after the above command is executed is as follows:
```
Starting yugabyted...
⚠ WARNING System checks. Following pre-reqs are not met:
- ntp package missing. We recommend installing ntp package.

Review the following docs and rerun the start command.
Quick start for Linux: https://docs.yugabyte.com/latest/quick-start/install/linux/


✅ YugabyteDB Started
yugabyted crashed. For troubleshooting, contact us on https://www.yugabyte.com/slack or check our FAQ at https://docs.yugabyte.com/latest/faq/
Traceback (most recent call last):
  File "./bin/yugabyted", line 1698, in run
    args.func()
  File "./bin/yugabyted", line 325, in start
    self.start_processes()
  File "./bin/yugabyted", line 891, in start_processes
    status = self.get_status_string() + \
  File "./bin/yugabyted", line 1363, in get_status_string
    (Output.make_yellow("Replication Factor"), YBAdminProxy.get_cluster_rf(master_addrs)),
  File "./bin/yugabyted", line 2221, in get_cluster_rf
    if cluster_config.has_key("replicationInfo"):
AttributeError: 'dict' object has no attribute 'has_key'

For more information, check the logs in /home/ec2-user/var/logs
```

**Comment by gargsans-yb** [comment]
Successfully landed the diff - https://phabricator.dev.yugabyte.com/D17038 to close this issue.
