### ISSUE TITLE
[YSQL][LST] FATAL: Check failed: _s.ok() Bad status: Timed out (yb/rpc/outbound_call.cc:488): FinishTransaction RPC (request call id 104) to 127.0.0.1:9100 timed out after 32.000s

### ISSUE THREAD

**Issue by def-** [yugabyte/yugabyte-db#12475]
Jira Link: [[DB-298]](https://yugabyte.atlassian.net/browse/DB-298)
### Description

Happened during a `DROP DATABASE IF EXISTS` for a large database. Is this an expected failure? Since it causes a FATAL log file I'm posting it here:
```
$ git checkout 90623fb && python3.9 ./long_system_test.py --runtime=0 --threads=8 --seed=773252 --complexity=full
2022-05-11 16:31:02,466 MainThread INFO
2022-05-11 16:31:02,466 MainThread INFO     --------------------------------------------------------------------------------
2022-05-11 16:31:02,466 MainThread INFO     Running Long System Test 0.1
2022-05-11 16:31:02,466 MainThread INFO     --------------------------------------------------------------------------------
2022-05-11 16:31:02,466 MainThread INFO
2022-05-11 16:31:02,473 MainThread INFO     Reproduce with: git checkout 8806ee17-dirty && ./long_system_test.py --runtime=0 --threads=8 --seed=773252 --complexity=full
2022-05-11 16:31:02,475 MainThread INFO     Creating tables for database db_lst_773252
2022-05-11 16:31:02,775 MainThread INFO     Database version: PostgreSQL 11.2-YB-2.13.3.0-b0 on x86_64-pc-linux-gnu, compiled by clang version 12.0.1 (https://github.com/yugabyte/llvm-project.git bdb147e675d8c87cee72cc1f87c4b82855977d94), 64-bit
Traceback (most recent call last):
  File "/nfusr/dev-server/dfelsing/code/yb-long-system-test/./long_system_test.py", line 268, in <module>
    main()
  File "/nfusr/dev-server/dfelsing/code/yb-long-system-test/./long_system_test.py", line 259, in main
    lst.run()
  File "/nfusr/dev-server/dfelsing/code/yb-long-system-test/./long_system_test.py", line 192, in run
    self._create_tables()
  File "/nfusr/dev-server/dfelsing/code/yb-long-system-test/./long_system_test.py", line 173, in _create_tables
    self.database.create(cur)
  File "/nfusr/dev-server/dfelsing/code/yb-long-system-test/lst/dbobject.py", line 198, in create
    self.drop(cur)
  File "/nfusr/dev-server/dfelsing/code/yb-long-system-test/lst/dbobject.py", line 205, in drop
    cur.execute(f'DROP DATABASE IF EXISTS {self.name()};')
psycopg2.OperationalError: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
```
```
$ cat ./node-1/disk-1/yb-data/tserver/logs/yb-tserver.FATAL.details.2022-05-11T16_32_06.pid149365.txt
F20220511 16:32:06 ../../src/yb/yql/pggate/pggate.cc:1545] Check failed: _s.ok() Bad status: Timed out (yb/rpc/outbound_call.cc:488): FinishTransaction RPC (request call id 104) to 127.0.0.1:9100 timed out after 32.000s
    @     0x7f70b895a34c  google::LogDestination::LogToSinks()
    @     0x7f70b895401f  google::LogMessage::SendToLog()
    @     0x7f70b8954928  google::LogMessage::Flush()
    @     0x7f70b8957aaf  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f70bcedcb8f  yb::pggate::PgApiImpl::ClearSeparateDdlTxnMode()
    @           0xb1f1a8  YBTxnDdlProcessUtility
    @           0x9565f4  PortalRunUtility
    @           0x9563c7  PortalRunMulti
    @           0x955983  PortalRun
    @           0x951806  yb_exec_simple_query_impl
    @           0x951fc4  yb_exec_query_wrapper_one_attempt
    @           0x94e57b  PostgresMain
    @           0x8a9e1b  BackendRun
    @           0x8a952a  ServerLoop
    @           0x8a5b81  PostmasterMain
    @           0x7c64b3  PostgresServerProcessMain
    @           0x4f4052  main
    @     0x7f70bc500825  __libc_start_main
    @           0x4f3f59  _start
    @              (nil)  (unknown)
```
Afterwards the database stays unreachable:
```
psycopg2.OperationalError: connection to server at "localhost" (::1), port 5433 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5433 failed: timeout expired
```
I can provide the full yugabyte-data directory on request, available from within Yugabyte organization: https://drive.google.com/file/d/19Aixr3uyUNPHWjiyvk4wALWWIVxUNUv4/view?usp=sharing https://drive.google.com/file/d/1A4ofKvF1lt-V1FD4flEpbGhtHNNOEJcr/view?usp=sharing

**Comment by qvad** [comment]
Reproduced w/o DROP TABLE statement in our stress tests

**Comment by def-** [comment]
Also happens in LST without concurrent DDLs and tablegroups.
