### ISSUE TITLE
[DocDB] [TPCC 250k] TPCC Client failed with "Invalid argument: Index 18446744071962625088 does not reference a valid sidecar" in execute phase 

### ISSUE THREAD

**Issue by sonalsagarwal** [yugabyte/yugabyte-db#12515]
Jira Link: [[DB-356]](https://yugabyte.atlassian.net/browse/DB-356)
### Description

TPC-C 250k we started 163 nodes(3 masters and 160 tservers) on c5d.9xlarge VMs. The load and execute phase were run from 100 TPCC clients. In execute phase few clients failed with following error :
` 
java.lang.RuntimeException: Unexpected fatal, error in 'Worker<18887>' when executing 'Payment/02'
    at com.oltpbenchmark.api.Worker.doWork(Worker.java:584)
    at com.oltpbenchmark.api.Worker.run(Worker.java:368)
    at java.lang.Thread.run(Thread.java:750)
Caused by: org.postgresql.util.PSQLException: ERROR: Invalid argument: Index 18446744071962625088 does not reference a valid sidecar
    at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2468)
    at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2211)
    at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:309)
    at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:446)
    at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:370)
    at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:149)
    at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:124)
    at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
    at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
    at com.oltpbenchmark.jdbc.InstrumentedPreparedStatement.executeUpdate(InstrumentedPreparedStatement.java:49)
    at com.oltpbenchmark.benchmarks.tpcc.procedures.Payment.run(Payment.java:285)
    at com.oltpbenchmark.api.Worker.executeWork(Worker.java:609)"`

[DB-356]: https://yugabyte.atlassian.net/browse/DB-356?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
@spolitov , Is it related to the PG client refactoring issue?

**Comment by rthallamko3** [comment]
@sonalsagarwal , Do we have the tserver logs for this? If not, can we close it till we get a hit with the relevant logs uploaded? cc @hbhanawat
