### ISSUE TITLE
[DocDB] [TPCC 250k] TPCC Client failed with "Connection org.postgresql.jdbc.PgConnection@2b092d69 marked as broken because of SQLSTATE(08006" in execute phase 

### ISSUE THREAD

**Issue by sonalsagarwal** [yugabyte/yugabyte-db#12516]
### Description

Few of the TPCC clients failed with following error : 
```
[Worker<1102>] WARN com.zaxxer.hikari.pool.ProxyConnection - HikariPool-143 - Connection org.postgresql.jdbc.PgConnection@2b092d69 marked as broken because of SQLSTATE(08006), ErrorCode(0)\norg.postgresql.util.PSQLException: An I/O error occurred while sending to the backend.
     at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:336).  
     at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:446)
     at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:370)
     at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:149)
     at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:108)
    at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
    at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
    at com.oltpbenchmark.jdbc.InstrumentedPreparedStatement.executeQuery(InstrumentedPreparedStatement.java:35)
    at com.oltpbenchmark.benchmarks.tpcc.procedures.Payment.getCustomerByName(Payment.java:394)
    at com.oltpbenchmark.benchmarks.tpcc.procedures.Payment.run(Payment.java:173)
    at com.oltpbenchmark.api.Worker.executeWork(Worker.java:609)
    at com.oltpbenchmark.api.Worker.doWork(Worker.java:506)
    at com.oltpbenchmark.api.Worker.run(Worker.java:368)
    at java.lang.Thread.run(Thread.java:750)\nCaused by: java.io.EOFException
    at org.postgresql.core.PGStream.receiveChar(PGStream.java:323)
    at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1978)
    at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:309)
    ... 13 more\njava.lang.RuntimeException: Unexpected fatal, error in 'Worker<1102>' when executing 'Payment/02'
    at com.oltpbenchmark.api.Worker.doWork(Worker.java:584)
    at com.oltpbenchmark.api.Worker.run(Worker.java:368)
    at java.lang.Thread.run(Thread.java:750)\nCaused by: java.sql.SQLException: Connection is closed
    at com.zaxxer.hikari.pool.ProxyConnection$ClosedConnection.lambda$getClosedConnection$0(ProxyConnection.java:515)
    at com.sun.proxy.$Proxy0.getAutoCommit(Unknown Source)
    at com.zaxxer.hikari.pool.HikariProxyConnection.getAutoCommit(HikariProxyConnection.java)
    at com.oltpbenchmark.api.Worker.doWork(Worker.java:528)
    ... 2 more
```

**Comment by rthallamko3** [comment]
@sonalsagarwal , Can you share the time the application ran into issues and also the corresponding logs from postgres, tserver, master.
