### ISSUE TITLE
[YSQL] libpq picked up by the test suite might be the system libpq, not the one from YB postgres

### ISSUE THREAD

**Issue by mbautin** [yugabyte/yugabyte-db#1252]
[263/264] Linking CXX shared library lib/libpg_wrapper_test_base.so
/ld: warning: libssl.so.10, needed by /usr/lib64/libpq.so, may conflict with libssl.so.1.0.0
ld: warning: libcrypto.so.10, needed by /usr/lib64/libpq.so, may conflict with libcrypto.so.1.0.0
ld: warning: libcrypto.so.10, needed by /usr/lib64/libpq.so, may conflict with libcrypto.so.1.0.0

**Comment by bmatican** [comment]
Using `./yb_release --build_args="--clean --dltp" --force` on centos

```
cat /etc/redhat-release
CentOS Linux release 7.5.1804 (Core)
```

```
==========================================================================================
YUGABYTE BUILD SUMMARY
==========================================================================================
Build type                       : release
C/C++ compiler                   : gcc
Build directory                  : /n/users/bogdan/code/yugabyte-db/build/release-gcc-dynamic-ninja
Third-party dir                  : /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20200625021759-2dafffee0f-centos
Linuxbrew dir                    : /opt/yb-build/brew/linuxbrew-20181203T161736v9
Targets                          : ldb log-dump sst_dump yb-admin yb-bulk_load yb-generate_partitions_main yb-master yb-pbc-dump yb-ts-cli yb-tserver yb-ysck yb_load_test_tool initial_sys_catalog_snapshot initial_sys_catalog_snapshot
CMake time                       : 52 seconds
C++ compilation time             : 1040 seconds
------------------------------------------------------------------------------------------
2020-07-01 00:25:11,619 [yb_release.py:189 INFO] Build descriptor: {'build_type': 'release', 'cmake_build_type': 'release', 'build_root': '/n/users/bogdan/code/yugabyte-db/build/release-gcc-dynamic-ninja', 'compiler_type': 'gcc', 'thirdparty_dir': '/opt/
yb-build/thirdparty/yugabyte-db-thirdparty-v20200625021759-2dafffee0f-centos', 'linuxbrew_dir': '/opt/yb-build/brew/linuxbrew-20181203T161736v9'}
2020-07-01 00:25:11,797 [release_util.py:52 INFO] Java project version from pom.xml: 0.8.0-SNAPSHOT
2020-07-01 00:25:11,798 [release_util.py:82 INFO] Substituting '$BUILD_ROOT/version_metadata.json' -> '/n/users/bogdan/code/yugabyte-db/build/release-gcc-dynamic-ninja/version_metadata.json' in manifest
2020-07-01 00:25:11,798 [release_util.py:82 INFO] Substituting '$BUILD_ROOT/bin/ldb' -> '/n/users/bogdan/code/yugabyte-db/build/release-gcc-dynamic-ninja/bin/ldb' in manifest
2020-07-01 00:25:11,798 [release_util.py:82 INFO] Substituting '$BUILD_ROOT/bin/log-dump' -> '/n/users/bogdan/code/yugabyte-db/build/release-gcc-dynamic-ninja/bin/log-dump' in manifest
2020-07-01 00:25:11,798 [release_util.py:82 INFO] Substituting '$BUILD_ROOT/bin/sst_dump' -> '/n/users/bogdan/code/yugabyte-db/build/release-gcc-dynamic-ninja/bin/sst_dump' in manifest
2020-07-01 00:25:11,798 [release_util.py:82 INFO] Substituting '$BUILD_ROOT/bin/yb-admin' -> '/n/users/bogdan/code/yugabyte-db/build/release-gcc-dynamic-ninja/bin/yb-admin' in manifest
2020-07-01 00:25:11,798 [release_util.py:82 INFO] Substituting '$BUILD_ROOT/bin/yb-bulk_load' -> '/n/users/bogdan/code/yugabyte-db/build/release-gcc-dynamic-ninja/bin/yb-bulk_load' in manifest
2020-07-01 00:25:11,798 [release_util.py:82 INFO] Substituting '$BUILD_ROOT/bin/yb-generate_partitions_main' -> '/n/users/bogdan/code/yugabyte-db/build/release-gcc-dynamic-ninja/bin/yb-generate_partitions_main' in manifest
2020-07-01 00:25:11,798 [release_util.py:82 INFO] Substituting '$BUILD_ROOT/bin/yb-master' -> '/n/users/bogdan/code/yugabyte-db/build/release-gcc-dynamic-ninja/bin/yb-master' in manifest
2020-07-01 00:25:11,798 [release_util.py:82 INFO] Substituting '$BUILD_ROOT/bin/yb-pbc-dump' -> '/n/users/bogdan/code/yugabyte-db/build/release-gcc-dynamic-ninja/bin/yb-pbc-dump' in manifest
2020-07-01 00:25:11,798 [release_util.py:82 INFO] Substituting '$BUILD_ROOT/bin/yb-ts-cli' -> '/n/users/bogdan/code/yugabyte-db/build/release-gcc-dynamic-ninja/bin/yb-ts-cli' in manifest
2020-07-01 00:25:11,798 [release_util.py:82 INFO] Substituting '$BUILD_ROOT/bin/yb-tserver' -> '/n/users/bogdan/code/yugabyte-db/build/release-gcc-dynamic-ninja/bin/yb-tserver' in manifest
2020-07-01 00:25:11,798 [release_util.py:82 INFO] Substituting '$BUILD_ROOT/bin/yb-ysck' -> '/n/users/bogdan/code/yugabyte-db/build/release-gcc-dynamic-ninja/bin/yb-ysck' in manifest
2020-07-01 00:25:11,798 [release_util.py:82 INFO] Substituting '$BUILD_ROOT/bin/yb_load_test_tool' -> '/n/users/bogdan/code/yugabyte-db/build/release-gcc-dynamic-ninja/bin/yb_load_test_tool' in manifest
2020-07-01 00:25:11,798 [release_util.py:82 INFO] Substituting '$BUILD_ROOT/postgres/bin/*' -> '/n/users/bogdan/code/yugabyte-db/build/release-gcc-dynamic-ninja/postgres/bin/*' in manifest
2020-07-01 00:25:11,798 [release_util.py:82 INFO] Substituting '$THIRDPARTY_BUILD_SPECIFIC_DIR/bin/pprof' -> '/opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20200625021759-2dafffee0f-centos/installed/uninstrumented/bin/pprof' in manifest
2020-07-01 00:25:11,798 [release_util.py:82 INFO] Substituting 'thirdparty/installed/common/bin/redis-cli' -> '/opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20200625021759-2dafffee0f-centos/installed/common/bin/redis-cli' in manifest
2020-07-01 00:25:11,798 [release_util.py:82 INFO] Substituting 'thirdparty/installed/common/cqlsh/bin/cqlsh' -> '/opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20200625021759-2dafffee0f-centos/installed/common/cqlsh/bin/cqlsh' in manifest
2020-07-01 00:25:11,799 [release_util.py:82 INFO] Substituting 'thirdparty/installed/common/cqlsh/bin/ycqlsh' -> '/opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20200625021759-2dafffee0f-centos/installed/common/cqlsh/bin/ycqlsh' in manifest
2020-07-01 00:25:11,799 [release_util.py:82 INFO] Substituting 'thirdparty/installed/common/cqlsh/bin/ycqlsh.py' -> '/opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20200625021759-2dafffee0f-centos/installed/common/cqlsh/bin/ycqlsh.py' in manifest
2020-07-01 00:25:11,799 [release_util.py:82 INFO] Substituting 'thirdparty/installed/common/cqlsh/lib/*' -> '/opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20200625021759-2dafffee0f-centos/installed/common/cqlsh/lib/*' in manifest
2020-07-01 00:25:11,799 [release_util.py:82 INFO] Substituting '$BUILD_ROOT/postgres_build/src/interfaces/libpq/libpq.so' -> '/n/users/bogdan/code/yugabyte-db/build/release-gcc-dynamic-ninja/postgres_build/src/interfaces/libpq/libpq.so' in manifest
2020-07-01 00:25:11,799 [release_util.py:82 INFO] Substituting '$BUILD_ROOT/postgres/*' -> '/n/users/bogdan/code/yugabyte-db/build/release-gcc-dynamic-ninja/postgres/*' in manifest
2020-07-01 00:25:11,799 [release_util.py:82 INFO] Substituting 'thirdparty/installed/common/cqlsh/pylib/*' -> '/opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20200625021759-2dafffee0f-centos/installed/common/cqlsh/pylib/*' in manifest
2020-07-01 00:25:11,799 [release_util.py:82 INFO] Substituting '$BUILD_ROOT/share/initial_sys_catalog_snapshot' -> '/n/users/bogdan/code/yugabyte-db/build/release-gcc-dynamic-ninja/share/initial_sys_catalog_snapshot' in manifest
Traceback (most recent call last):
  File "/n/users/bogdan/code/yugabyte-db/build-support/yb_release.py", line 289, in <module>
    main()
  File "/n/users/bogdan/code/yugabyte-db/build-support/yb_release.py", line 232, in main
    library_packager.package_binaries()
  File "/n/users/bogdan/code/yugabyte-db/python/yb/library_packager.py", line 347, in package_binaries
    dep_name, deps
RuntimeError: Multiple dependencies with the same name libpq.so.5 but different targets: [Dependency(name='libpq.so.5', target='/n/users/bogdan/code/yugabyte-db/build/release-gcc-dynamic-ninja/postgres/lib/libpq.so.5.11', origin='/n/users/bogdan/code/yug
abyte-db/build/release-gcc-dynamic-ninja/postgres/bin/initdb'), Dependency(name='libpq.so.5', target='/usr/lib64/libpq.so.5.5', origin='/n/users/bogdan/code/yugabyte-db/build/release-gcc-dynamic-ninja/bin/yb-admin')]
```
