### ISSUE TITLE
[YSQL][LST] Upgrade: The catalog snapshot used for this transaction has been invalidated: MISMATCHED_SCHEMA

### ISSUE THREAD

**Issue by def-** [yugabyte/yugabyte-db#12621]
### Description

After upgrading database with LST running I'm getting this error:
```
2022-05-23 19:26:28,606 worker_3   ERROR    Unexpected query failure: SerializationFailure
Query: EXECUTE stmt;
  values: None
  runtime: 2022-05-23 19:26:28.568 - 2022-05-23 19:26:28.605
  supports explain: True
  supports rollback: True
  affected rows: None
Action: RandomSelectAction
Error class: SerializationFailure
Error code: 40001
Error message: ERROR:  Query error: [Query error (yb/tserver/read_query.cc:265): The catalog snapshot used for this transaction has been invalidated: MISMATCHED_SCHEMA (tablet server error 5)]
CONTEXT:  Catalog Version Mismatch: A DDL occurred while processing this query. Try again.
Transaction isolation level: serializable
DB Node: host: 10.9.130.19, port: 5433
DB Backend PID: 17346
```
Other than the DB upgrade only select and set config queries were running. Is this an expected failure during upgrades? See also #2323.

**Comment by def-** [comment]
This is also happening inside the upgrade_ysql itself. Should upgrade_ysql handle this or are users expected to retry upgrade_ysql until it succeeds? (Which it never might if the system is under load)
```
2022-12-14 15:18:50,632 ssh_utils.py:300 INFO testupgrade-k8s-rf3-upgrade-2.12.10.0_41 CMD=/home/yugabyte/master/bin/yb-admin --timeout_ms 120000 --master_addresses 10.9.79.103:7100,10.9.141.67:7100,10.9.203.9:7100 upgrade_ysql, RETCODE=1, OUT=, ERR=Error running upgrade_ysql: Network error (yb/yql/pgwrapper/libpq_utils.cc:271): Unable to upgrade YSQL cluster: Failed to apply migration 'V19__6560__pg_collation_icu_70.sql' to a database template1: Execute failed: 7, message: ERROR:  Query error: Flush: The catalog snapshot used for this transaction has been invalidated: MISMATCHED_SCHEMA: . Errors from tablet servers: [Query error (yb/tserver/service_util.h:270): Flush: The catalog snapshot used for this transaction has been invalidated: MISMATCHED_SCHEMA (tablet server error 5)] (pgsql error XX000) (aux msg ERROR:  Query error: Flush: The catalog snapshot used for this transaction has been invalidated: MISMATCHED_SCHEMA: . Errors from tablet servers: [Query error (yb/tserver/service_util.h:270): Flush: The catalog snapshot used for this transaction has been invalidated: MISMATCHED_SCHEMA (tablet server error 5)])
```

**Comment by rjalan-yb** [comment]
This was not seen in LST in latest upgrades in 2.20 and 2.21 but on one itest-system runs, we did see this error on 2.18:
https://jenkins.dev.yugabyte.com/job/itest-system-developer/9630/

**Comment by shamanthchandra-yb** [comment]
@m-iancu 

I was able to see this issue in one of the CDC stress runs on 2.20.2:

Again, have seen only once: **test_cdc_tx_colocation_nemesis** (This was colocation + CDC)

Testcase had failed. When went into sample apps log, saw:

`The catalog snapshot used for this transaction has been invalidated: MISMATCHED_SCHEMA`

```
2024-01-09 07:48:27,875 [main] INFO SqlDataLoadWithDDL - setup: gather table info
Exception in thread "main" java.lang.RuntimeException: com.yugabyte.util.PSQLException: ERROR: The catalog snapshot used for this transaction has been invalidated: MISMATCHED_SCHEMA
	at com.yugabyte.sample.apps.SqlDataLoadWithDDL.setup(SqlDataLoadWithDDL.java:124)
	at com.yugabyte.sample.Main.run(Main.java:166)
	at com.yugabyte.sample.Main.main(Main.java:89)
Caused by: com.yugabyte.util.PSQLException: ERROR: The catalog snapshot used for this transaction has been invalidated: MISMATCHED_SCHEMA
	at com.yugabyte.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2675)
	at com.yugabyte.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2365)
	at com.yugabyte.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:355)
	at com.yugabyte.jdbc.PgStatement.executeInternal(PgStatement.java:490)
	at com.yugabyte.jdbc.PgStatement.execute(PgStatement.java:408)
	at com.yugabyte.jdbc.PgStatement.executeWithFlags(PgStatement.java:329)
	at com.yugabyte.jdbc.PgStatement.executeCachedSql(PgStatement.java:315)
	at com.yugabyte.jdbc.PgStatement.executeWithFlags(PgStatement.java:291)
	at com.yugabyte.jdbc.PgStatement.executeQuery(PgStatement.java:243)
	at com.yugabyte.jdbc.PgDatabaseMetaData.getColumns(PgDatabaseMetaData.java:1592)
	at com.yugabyte.sample.apps.SqlDataLoadWithDDL.setup(SqlDataLoadWithDDL.java:116)
	... 2 more
```

SampleAppWorkloads_SQL_DATA_LOAD_WITH_DDLS was run with DELETE_ROW,UPDATE_ROW,UPDATE_ROWS,INSERT_ROW
and SQL_TX was run alternatively.
