### ISSUE TITLE
Ubuntu Server 16.04 initdb: could not look up effective user ID 0: user does not exist

### ISSUE THREAD

**Issue by Exocomp** [YugaByte/yugabyte-db#1266]
Server: Ubuntu 16.04 Server
YugaByte Version: 1.2.5.0

I'm getting the following error, I've followed the steps in the YugaByte docs, I'd appreciate the help.

```
administrator@server-100:~/yugabyte-1.2.5.0$ ./bin/yb-ctl create --enable_postgres

2019-04-26 10:24:50,566 INFO: Starting master-1 with:
/home/administrator/yugabyte-1.2.5.0/bin/yb-master --fs_data_dirs "/home/administrator/yugabyte-data/node-1/disk-1,/home/administrator/yugabyte-data/node-1/disk-2" --webserver_interface 127.0.0.1 --rpc_bind_addresses 127.0.0.1 --v 0 --version_file_json_path=/home/administrator/yugabyte-1.2.5.0 --webserver_doc_root "/home/administrator/yugabyte-1.2.5.0/www" --replication_factor=1 --yb_num_shards_per_tserver 2 --master_addresses 127.0.0.1:7100 >"/home/administrator/yugabyte-data/node-1/disk-1/master.out" 2>"/home/administrator/yugabyte-data/node-1/disk-1/master.err" &
2019-04-26 10:24:50,576 INFO: Starting tserver-1 with:
/home/administrator/yugabyte-1.2.5.0/bin/yb-tserver --fs_data_dirs "/home/administrator/yugabyte-data/node-1/disk-1,/home/administrator/yugabyte-data/node-1/disk-2" --webserver_interface 127.0.0.1 --rpc_bind_addresses 127.0.0.1 --v 0 --version_file_json_path=/home/administrator/yugabyte-1.2.5.0 --webserver_doc_root "/home/administrator/yugabyte-1.2.5.0/www" --tserver_master_addrs=127.0.0.1:7100 --memory_limit_hard_bytes=1073741824 --yb_num_shards_per_tserver=2 --redis_proxy_bind_address=127.0.0.1 --cql_proxy_bind_address=127.0.0.1 --local_ip_for_outbound_sockets=127.0.0.1 --use_cassandra_authentication=false --start_pgsql_proxy --pgsql_proxy_bind_address=127.0.0.1 >"/home/administrator/yugabyte-data/node-1/disk-1/tserver.out" 2>"/home/administrator/yugabyte-data/node-1/disk-1/tserver.err" &
2019-04-26 10:24:50,595 INFO: Waiting until we have enough tablet servers (currently 1)
2019-04-26 10:24:55,395 INFO: Waiting until we have enough tablet servers (currently 1)
2019-04-26 10:24:55,466 INFO: Running initdb to initialize PostgreSQL metadata in the YugaByte cluster. This may take up to a minute.
2019-04-26 10:24:55,524 INFO: initdb log file (from /home/administrator/yugabyte-data/initdb.log):
2019-04-26 10:24:55,525 INFO: initdb: could not look up effective user ID 1000: user does not exist
Traceback (most recent call last):
  File "./bin/yb-ctl", line 1267, in <module>
    ClusterControl().run()
  File "./bin/yb-ctl", line 1258, in run
    self.args.func()
  File "./bin/yb-ctl", line 1102, in create
    self.run_cluster_wide_postgres_initdb()
  File "./bin/yb-ctl", line 1227, in run_cluster_wide_postgres_initdb
    ], stdout=initdb_stdout_file, stderr=subprocess.STDOUT)
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/administrator/yugabyte-1.2.5.0/postgres/bin/initdb', '-D', '/home/administrator/yugabyte-data/yb-ctl_tmp_pg_data_89e142518f6ad2ddbb5d32453857d69b', '-U', 'postgres']' returned non-zero exit status 1
```

**Comment by kmuthukk** [comment]
hi @Exocomp :

We have addressed [this issue](https://github.com/YugaByte/yugabyte-db/issues/1018) in a [recent commit](https://github.com/YugaByte/yugabyte-db/commit/2ae238be785b1b361fd3ac6ef38008dfe17d2d82).

If you pick up 1.2.6.0, then you shouldn't see this issue any more:

`wget https://downloads.yugabyte.com/yugabyte-ce-1.2.6.0-linux.tar.gz`

Or, prior to 1.2.6, the workaround would be to set this environment variable:
`export YB_PG_FALLBACK_SYSTEM_USER_NAME=$USER`

regards,
Kannan

**Comment by Exocomp** [comment]
Excellent, it worked.  Loving it so far.
Great job Kannan and team!
