### ISSUE TITLE
[YSQL][LST] Upgrade: Crash in SearchCatCacheMiss

### ISSUE THREAD

**Issue by def-** [yugabyte/yugabyte-db#12694]
### Description

LST crashes postgres during upgrade from 2.0.9.0-b13 to 2.13.3.0-b81:
```
[New LWP 18120]

warning: Unable to find libthread_db matching inferior's thread library, thread debugging will not be available.

warning: Unable to find libthread_db matching inferior's thread library, thread debugging will not be available.
Core was generated by `postgres: yugabyte db_lst_972303 10.150.0.47(46946) SELECT                    '.
Program terminated with signal 11, Segmentation fault.
#0  heap_endscan (scan=0x0) at ../../../../../../../src/postgres/src/backend/access/heap/heapam.c:1588
1588	../../../../../../../src/postgres/src/backend/access/heap/heapam.c: No such file or directory.

Thread 1 (LWP 18120):
#0  heap_endscan (scan=0x0) at ../../../../../../../src/postgres/src/backend/access/heap/heapam.c:1588
No locals.
#1  0x00000000004ea879 in systable_endscan (sysscan=0x37da6a8) at ../../../../../../../src/postgres/src/backend/access/index/genam.c:532
No locals.
#2  0x0000000000915808 in SearchCatCacheMiss (cache=cache@entry=0x340d300, nkeys=nkeys@entry=2, hashValue=2074789965, hashIndex=hashIndex@entry=13, v1=v1@entry=54104936, v2=v2@entry=2200, v3=0, v4=0) at ../../../../../../../src/postgres/src/backend/utils/cache/catcache.c:1730
        cur_skey = {{sk_flags = 0, sk_attno = 1, sk_strategy = 3, sk_subtype = 0, sk_collation = 0, sk_func = {fn_addr = 0x87e0a0 <nameeq>, fn_oid = 62, fn_nargs = 2, fn_strict = true, fn_retset = false, fn_stats = 2 '\002', fn_extra = 0x0, fn_mcxt = 0x33efbf0, fn_expr = 0x0}, sk_argument = 54104936}, {sk_flags = 0, sk_attno = 2, sk_strategy = 3, sk_subtype = 0, sk_collation = 0, sk_func = {fn_addr = 0x896590 <oideq>, fn_oid = 184, fn_nargs = 2, fn_strict = true, fn_retset = false, fn_stats = 2 '\002', fn_extra = 0x0, fn_mcxt = 0x33efbf0, fn_expr = 0x0}, sk_argument = 2200}, {sk_flags = 1539281680, sk_attno = 32766, sk_strategy = 0, sk_subtype = 11000559, sk_collation = 0, sk_func = {fn_addr = 0x7ffe5bbf9330, fn_oid = 0, fn_nargs = 0, fn_strict = false, fn_retset = false, fn_stats = 224 '\340', fn_extra = 0x6a71d2 <appendStringInfoVA+66>, fn_mcxt = 0x7ffe5bbf9310, fn_expr = 0x7ffe5bbf90f8}, sk_argument = 0}, {sk_flags = 6976413, sk_attno = 0, sk_strategy = 0, sk_subtype = 65059096, sk_collation = 0, sk_func = {fn_addr = 0x3000000018, fn_oid = 1539281184, fn_nargs = 32766, fn_strict = false, fn_retset = false, fn_stats = 43 '+', fn_extra = 0x7ffe5bbf9140, fn_mcxt = 0x0, fn_expr = 0x7ffe5bbf9170}, sk_argument = 0}}
        relation = 0x7f45ec0f5c28
        scandesc = 0x37da6a8
        ntp = <optimized out>
        ct = 0x0
        arguments = {54104936, 2200, 0, 0}
#3  0x00000000009178fe in SearchCatCacheInternal (v4=0, v3=0, v2=2200, v1=54104936, nkeys=2, cache=0x340d300) at ../../../../../../../src/postgres/src/backend/utils/cache/catcache.c:1649
        hashValue = 2074789965
        iter = <optimized out>
        bucket = 0x340d7a8
        arguments = {54104936, 2200, 0, 0}
        hashIndex = 13
        ct = <optimized out>
#4  SearchCatCache (cache=0x340d300, v1=v1@entry=54104936, v2=2200, v3=v3@entry=0, v4=v4@entry=0) at ../../../../../../../src/postgres/src/backend/utils/cache/catcache.c:1503
No locals.
#5  0x0000000000930ec8 in SearchSysCache (cacheId=cacheId@entry=73, key1=key1@entry=54104936, key2=<optimized out>, key3=key3@entry=0, key4=key4@entry=0) at ../../../../../../../src/postgres/src/backend/utils/cache/syscache.c:1398
No locals.
#6  0x0000000000930fce in GetSysCacheOid (cacheId=cacheId@entry=73, key1=key1@entry=54104936, key2=<optimized out>, key3=key3@entry=0, key4=key4@entry=0) at ../../../../../../../src/postgres/src/backend/utils/cache/syscache.c:1520
        tuple = <optimized out>
        result = <optimized out>
#7  0x00000000005510dd in TypenameGetTypid (typname=0x3399368 "isempty") at ../../../../../../src/postgres/src/backend/catalog/namespace.c:777
        namespaceId = <optimized out>
        typid = <optimized out>
        l = 0x33d5a88
#8  0x00000000005c98b9 in LookupTypeName (pstate=pstate@entry=0x0, typeName=0x37da388, typmod_p=typmod_p@entry=0x0, missing_ok=missing_ok@entry=false) at ../../../../../../src/postgres/src/backend/parser/parse_type.c:175
        schemaname = 0x0
        typname = 0x3399368 "isempty"
        typoid = <optimized out>
        tup = <optimized out>
        __func__ = "LookupTypeName"
#9  0x00000000005bca27 in FuncNameAsType (funcname=0x33993c0) at ../../../../../../src/postgres/src/backend/parser/parse_func.c:1880
        result = <optimized out>
        typtup = <optimized out>
#10 func_get_detail (funcname=funcname@entry=0x33993c0, fargs=fargs@entry=0x37da308, fargnames=fargnames@entry=0x0, nargs=nargs@entry=1, argtypes=argtypes@entry=0x7ffe5bbf94b0, expand_variadic=<optimized out>, expand_defaults=true, funcid=0x7ffe5bbf9464, rettype=0x7ffe5bbf9460, retset=0x7ffe5bbf945f, nvargs=0x7ffe5bbf9468, vatype=0x7ffe5bbf946c, true_typeids=0x7ffe5bbf9470, argdefaults=0x7ffe5bbf9478) at ../../../../../../src/postgres/src/backend/parser/parse_func.c:1467
        raw_candidates = 0x37da338
        best_candidate = <optimized out>
        __func__ = "func_get_detail"
#11 0x00000000005bda0e in ParseFuncOrColumn (pstate=pstate@entry=0x3399818, funcname=0x33993c0, fargs=<optimized out>, fargs@entry=0x37da308, last_srf=last_srf@entry=0x0, fn=fn@entry=0x3399598, proc_call=proc_call@entry=false, location=109) at ../../../../../../src/postgres/src/backend/parser/parse_func.c:257
        is_column = false
        agg_order = <optimized out>
        agg_filter = 0x0
        agg_within_group = <optimized out>
        agg_star = <optimized out>
        agg_distinct = <optimized out>
        func_variadic = <optimized out>
        over = <optimized out>
        could_be_projection = false
        rettype = 0
        funcid = 0
        l = <optimized out>
        nextl = <optimized out>
        first_arg = <optimized out>
        nargs = <optimized out>
        nargsplusdefs = <optimized out>
        actual_arg_types = {3904, 0, 58566832, 0, 11036255, 0, 68482728, 0, 1539282176, 32766, 54106088, 0, 8, 0, 0, 0, 0, 0, 54104888, 0, 54105496, 0, 0, 0, 0, 0, 0, 0, 0, 0, 54105144, 0, 1539282256, 32766, 9523243, 0, 1539282256, 32766, 9833012, 0, 1539282272, 32766, 3353374648, 32581, 1539282512, 32766, 9716302, 0, 1539282400, 32766, 9716302, 0, 1539282384, 32766, 0, 0, 54468000, 0, 3353375768, 32581, 3353375744, 32581, 14869712, 0, 1539282432, 32766, 9534134, 0, 1539282608, 32766, 3353375768, 32581, 1539282432, 32766, 1539282608, 32766, 23, 0, 23, 0, 54104728, 0, 1539282488, 32766, 1539282800, 32766, 6030188, 0, 1539282496, 0, 7075008, 0, 54107472, 92, 54106136, 0, 0, 0, 10191116, 0}
        declared_arg_types = 0x0
        argnames = <optimized out>
        argdefaults = 0x0
        retval = <optimized out>
        retset = false
        nvargs = 0
        vatype = 0
        fdresult = <optimized out>
        aggkind = <optimized out>
        pcbstate = {pstate = 0x3399818, location = 109, errcallback = {previous = 0x0, callback = 0x5bf510 <pcb_error_callback>, arg = 0x7ffe5bbf9480}}
        __func__ = "ParseFuncOrColumn"
#12 0x00000000005b9dfd in transformFuncCall (fn=0x3399598, pstate=0x3399818) at ../../../../../../src/postgres/src/backend/parser/parse_expr.c:1479
        last_srf = 0x0
        targs = 0x37da308
        args = <optimized out>
#13 transformExprRecurse (pstate=pstate@entry=0x3399818, expr=<optimized out>) at ../../../../../../src/postgres/src/backend/parser/parse_expr.c:266
        result = <optimized out>
        __func__ = "transformExprRecurse"
#14 0x00000000005b84b6 in transformExpr (pstate=pstate@entry=0x3399818, expr=<optimized out>, exprKind=exprKind@entry=EXPR_KIND_WHERE) at ../../../../../../src/postgres/src/backend/parser/parse_expr.c:156
        result = 0x0
        sv_expr_kind = EXPR_KIND_NONE
#15 0x00000000005ab927 in transformWhereClause (pstate=pstate@entry=0x3399818, clause=<optimized out>, exprKind=exprKind@entry=EXPR_KIND_WHERE, constructName=constructName@entry=0x9b78c8 "WHERE") at ../../../../../../src/postgres/src/backend/parser/parse_clause.c:1733
        qual = <optimized out>
#16 0x000000000057d645 in transformSelectStmt (stmt=<optimized out>, pstate=0x3399818) at ../../../../../../src/postgres/src/backend/parser/analyze.c:1267
        qry = 0x3399928
        qual = <optimized out>
        l = <optimized out>
#17 transformStmt (pstate=pstate@entry=0x3399818, parseTree=parseTree@entry=0x33995e8) at ../../../../../../src/postgres/src/backend/parser/analyze.c:318
        n = <optimized out>
        result = <optimized out>
#18 0x000000000057f78a in transformOptionalSelectInto (parseTree=0x33995e8, pstate=0x3399818) at ../../../../../../src/postgres/src/backend/parser/analyze.c:263
No locals.
#19 transformTopLevelStmt (pstate=pstate@entry=0x3399818, parseTree=parseTree@entry=0x3399798) at ../../../../../../src/postgres/src/backend/parser/analyze.c:213
No locals.
#20 0x000000000057f878 in parse_analyze (parseTree=0x3399798, sourceText=0x3398200 "SELECT '{\"a\": 1, \"b\": [\"0\", \"1\", \"2\"], \"c\": false}'::json FROM t2 JOIN v0 AS j ON t2.c1_int = j.c1_int WHERE isempty(('(-39,2)'::INT4RANGE)) LIMIT 8;", paramTypes=0x0, numParams=0, queryEnv=0x0) at ../../../../../../src/postgres/src/backend/parser/analyze.c:119
        pstate = 0x3399818
        query = <optimized out>
#21 0x00000000007e7560 in pg_analyze_and_rewrite (parsetree=parsetree@entry=0x3399798, query_string=query_string@entry=0x3398200 "SELECT '{\"a\": 1, \"b\": [\"0\", \"1\", \"2\"], \"c\": false}'::json FROM t2 JOIN v0 AS j ON t2.c1_int = j.c1_int WHERE isempty(('(-39,2)'::INT4RANGE)) LIMIT 8;", paramTypes=paramTypes@entry=0x0, numParams=numParams@entry=0, queryEnv=queryEnv@entry=0x0) at ../../../../../../src/postgres/src/backend/tcop/postgres.c:696
        query = <optimized out>
        querytree_list = 0x0
#22 0x00000000007e7a01 in exec_simple_query (query_string=0x3398200 "SELECT '{\"a\": 1, \"b\": [\"0\", \"1\", \"2\"], \"c\": false}'::json FROM t2 JOIN v0 AS j ON t2.c1_int = j.c1_int WHERE isempty(('(-39,2)'::INT4RANGE)) LIMIT 8;") at ../../../../../../src/postgres/src/backend/tcop/postgres.c:1084
        parsetree = 0x3399798
        portal = <optimized out>
        snapshot_set = true
        commandTag = 0xa83354 "SELECT"
        completionTag = "܂\335\000\000\000\000\000\302Ú\000\000\000\000\000\220\237\277[\376\177\000\000\001\000\000\000\000\000\000\000@\236\277[\376\177\000\000\211Nk\000\000\000\000\000\220\235<\003", '\000' <repeats 11 times>
        querytree_list = <optimized out>
        plantree_list = <optimized out>
        receiver = <optimized out>
        format = 0
        dest = DestRemote
        parsetree_list = 0x33997e8
        save_log_statement_stats = false
        was_logged = <optimized out>
        msec_str = "\220\235<\003\000\000\000\000G\000\000\000\000\000\000\000\300\234\277[\376\177\000\000\064\n\226\000\000\000\000"
        parsetree_item = 0x33997c8
        use_implicit_block = false
#23 yb_exec_simple_query_attempting_to_restart_read (query_string=query_string@entry=0x3398200 "SELECT '{\"a\": 1, \"b\": [\"0\", \"1\", \"2\"], \"c\": false}'::json FROM t2 JOIN v0 AS j ON t2.c1_int = j.c1_int WHERE isempty(('(-39,2)'::INT4RANGE)) LIMIT 8;", exec_context=exec_context@entry=0x33980f0) at ../../../../../../src/postgres/src/backend/tcop/postgres.c:4017
        save_exception_stack = 0x7ffe5bbfa0e0
        save_context_stack = 0x0
        local_sigjmp_buf = {{__jmpbuf = {140730437705616, 6151769340894239387, 14516956, 10142658, 54164648, 1, 6151769340973931163, -6150846043965367653}, __mask_was_saved = 0, __saved_mask = {__val = {139938695567103, 140730437705184, 9754305, 139934329470976, 140730437705148, 54164648, 6, 54100480, 6, 54164648, 1, 140730437705200, 9754636, 140730437705280, 9744247, 14516956}}}}
        attempt = 0
#24 0x00000000007e963e in PostgresMain (argc=<optimized out>, argv=argv@entry=0x33a7ca0, dbname=0x33a7b90 "db_lst_972303", username=0x33a7b70 "yugabyte") at ../../../../../../src/postgres/src/backend/tcop/postgres.c:4675
        need_retry = false
        save_exception_stack = 0x7ffe5bbfa010
        save_context_stack = 0x0
        local_sigjmp_buf = {{__jmpbuf = {140730437705616, 6151769340818741915, 14516956, 10142658, 54164648, 1, 6151769340892142235, -6150846040663926117}, __mask_was_saved = 0, __saved_mask = {__val = {140730437715154, 140730437717922, 140730437715102, 140730437717922, 0, 0, 0, 0, 0, 1539285488, 6982803, 18446742974197923840, 0, 0, 8589934592, 18446744073709551615}}}}
        oldcontext = 0x33980f0
        firstchar = 1539284880
        input_message = {data = 0x3398200 "SELECT '{\"a\": 1, \"b\": [\"0\", \"1\", \"2\"], \"c\": false}'::json FROM t2 JOIN v0 AS j ON t2.c1_int = j.c1_int WHERE isempty(('(-39,2)'::INT4RANGE)) LIMIT 8;", len = 150, maxlen = 1024, cursor = 150}
        local_sigjmp_buf = {{__jmpbuf = {14869656, 6151769340818741915, 14869664, 10142658, 54164648, 1, 6151769340892142235, -6150846040150123877}, __mask_was_saved = 1, __saved_mask = {__val = {0, 140730437706704, 139938672827168, 140730437706512, 139938722388103, 14867592, 4294967295, 1, 54164176, 3, 100663296, 0, 0, 140730437705984, 140730437705984, 11507204}}}}
        send_ready_for_query = false
        disable_idle_in_transaction_timeout = false
        __func__ = "PostgresMain"
#25 0x00000000004958ae in BackendRun (port=0x33c9d90) at ../../../../../../src/postgres/src/backend/postmaster/postmaster.c:4398
        ac = 1
        secs = 706968028
        usecs = 409431
        i = 1
        av = 0x33a7ca0
        maxac = <optimized out>
#26 BackendStartup (port=0x33c9d90) at ../../../../../../src/postgres/src/backend/postmaster/postmaster.c:4064
        bn = <optimized out>
        pid = <optimized out>
#27 ServerLoop () at ../../../../../../src/postgres/src/backend/postmaster/postmaster.c:1724
        rmask = {fds_bits = {8, 0 <repeats 15 times>}}
        selres = <optimized out>
        now = <optimized out>
        readmask = {fds_bits = {8, 0 <repeats 15 times>}}
        last_lockfile_recheck_time = <optimized out>
        last_touch_time = 1653652790
        __func__ = "ServerLoop"
#28 0x0000000000762df5 in PostmasterMain (argc=argc@entry=23, argv=argv@entry=0x33a6cb0) at ../../../../../../src/postgres/src/backend/postmaster/postmaster.c:1387
        opt = <optimized out>
        status = <optimized out>
        userDoption = <optimized out>
        listen_addr_saved = true
        i = <optimized out>
        output_config_variable = <optimized out>
        __func__ = "PostmasterMain"
#29 0x00000000006ba86a in PostgresServerProcessMain (argc=23, argv=0x33a6cb0) at ../../../../../../src/postgres/src/backend/main/main.c:234
        do_check_root = <optimized out>
#30 0x00000000006baa69 in main ()
No symbol table info available.
```
I'll add full logs on Jira.

**Comment by def-** [comment]
I believe this is an instance of https://github.com/yugabyte/yugabyte-db/issues/13040 which happens with Release build.
