### ISSUE TITLE
[DocDB][LST] Upgrade: ERROR:  Raft issues leading to failures

### ISSUE THREAD

**Issue by def-** [yugabyte/yugabyte-db#12708]
Jira Link: [DB-597](https://yugabyte.atlassian.net/browse/DB-597)
### Description

Fails during upgrade with LST workload running (2.4.7.0-b7 - 2.13.3.0-b81):
```
2022-05-30 13:50:28,539 worker_2   ERROR    Unexpected query failure: InternalError_
Query: EXECUTE stmt;
  values: None
  runtime: 2022-05-30 13:50:28.503 - 2022-05-30 13:50:28.539
  supports explain: True
  supports rollback: True
  affected rows: None
Action: RandomSelectAction
Error class: InternalError_
Error code: XX000
Error message: ERROR:  Aborted: Failed to schedule: 0x0000000003d4eae0 -> Read(tablet: 7f922ce432d64c8dbd682f7f7436db52, num_ops: 1, num_attempts: 2, txn: 00000000-0000-0000-0000-000000000000)
Transaction isolation level: read uncommitted
DB Node: host: 10.9.207.50, port: 5433
DB Backend PID: 18462
```
I'll provide full logs on Jira.

[DB-597]: https://yugabyte.atlassian.net/browse/DB-597?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by def-** [comment]
Can't ignore this since after ignoring it the ysql connection gets closed:
```
Exception in thread worker_1:
Traceback (most recent call last):
  File "/var/lib/jenkins/code/yb-long-system-test/nohints/lst/action.py", line 103, in _exec
    cur.execute(query.string)
psycopg2.errors.InternalError_: Aborted: Failed to schedule: 0x00000000048fd0a0 -> Write(tablet: 4e08cc4efa5b47bd9f5df2fa294ec066, num_ops: 1, num_attempts: 2, txn: c2dcccdc-9427-474d-a4b1-fdabff755248)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/jenkins/code/yb-long-system-test/nohints/lst/worker.py", line 51, in run
    action.run(cur)
  File "/var/lib/jenkins/code/yb-long-system-test/nohints/lst/action.py", line 472, in run
    self._exec(cur, Query(query, supports_explain=True, supports_rollback=True))
  File "/var/lib/jenkins/code/yb-long-system-test/nohints/lst/action.py", line 112, in _exec
    raise Error(query, self, e)
lst.error.Error: (<lst.query.Query object at 0x7f966f4f9a10>, <lst.action.SingleInsertAction object at 0x7f966f4ddd90>, InternalError_('Aborted: Failed to schedule: 0x00000000048fd0a0 -> Write(tablet: 4e08cc4efa5b47bd9f5df2fa294ec066, num_ops: 1, num_attempts: 2, txn: c2dcccdc-9427-474d-a4b1-fdabff755248)\n'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/python-3.7.7/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/share/python-3.7.7/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/var/lib/jenkins/code/yb-long-system-test/nohints/lst/worker.py", line 59, in run
    self.conn.rollback()
psycopg2.OperationalError: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
```

**Comment by def-** [comment]
This also happened during upgrade testing when verifying objects, from 2.13.2.0-b135 to 2.17.1.0-b190: https://phabricator.dev.yugabyte.com/D20539
```
Verifying during upgrade failed:
Aborted: Failed to schedule: 0x0000000002b10010 -> Read(tablet: 00000000000000000000000000000000, num_ops: 1, num_attempts: 2, txn: 00000000-0000-0000-0000-000000000000, subtxn: [none])
```

**Comment by rthallamko3** [comment]
On the original set of logs that were shared, Around the time of the failure, I could see some leader election stuck, which could have caused the read RPCs to fail 

`Leader pre-election vote request: Denying vote to candidate e4f41d97f8fa418f91f080f18a5d15cb for term 4 because replica is either leader or believes a valid leader to be alive.`

@def- , Can you share the more recent logs for the upgrade? Want to see if the new hit is also related to Raft issues during upgrade.

**Comment by rthallamko3** [comment]
Checked with @Huqicheng , The raft failures can happen during rolling restarts. The read failures can also happen during node restarts. Closing this for now. In case there is a reliable repro of an unexpected failure, let us know. cc @kripasreenivasan
