### ISSUE TITLE
Error message does not say why yb-ctl create failed

### ISSUE THREAD

**Issue by rao-vasireddy** [YugaByte/yugabyte-db#1270]
My CE install failed for a valid reason due to a conflict on port 9000. We should report the actual error why it failed rather than having to find and look for the error in the log files.

22:54 $ ./bin/yb-ctl create
2019-04-26 22:54:54,545 INFO: Starting master-1 with:
/home/centos/temp/yugabyte-1.2.6.0/bin/yb-master --fs_data_dirs "/home/centos/yugabyte-data/node-1/disk-1,/home/centos/yugabyte-data/node-1/disk-2" --webserver_interface 127.0.0.1 --rpc_bind_addresses 127.0.0.1 --v 0 --version_file_json_path=/home/centos/temp/yugabyte-1.2.6.0 --webserver_doc_root "/home/centos/temp/yugabyte-1.2.6.0/www" --callhome_enabled=false --replication_factor=1 --yb_num_shards_per_tserver 2 --master_addresses 127.0.0.1:7100 >"/home/centos/yugabyte-data/node-1/disk-1/master.out" 2>"/home/centos/yugabyte-data/node-1/disk-1/master.err" &
2019-04-26 22:54:54,570 INFO: Starting tserver-1 with:
/home/centos/temp/yugabyte-1.2.6.0/bin/yb-tserver --fs_data_dirs "/home/centos/yugabyte-data/node-1/disk-1,/home/centos/yugabyte-data/node-1/disk-2" --webserver_interface 127.0.0.1 --rpc_bind_addresses 127.0.0.1 --v 0 --version_file_json_path=/home/centos/temp/yugabyte-1.2.6.0 --webserver_doc_root "/home/centos/temp/yugabyte-1.2.6.0/www" --callhome_enabled=false --tserver_master_addrs=127.0.0.1:7100 --memory_limit_hard_bytes=1073741824 --yb_num_shards_per_tserver=2 --redis_proxy_bind_address=127.0.0.1 --cql_proxy_bind_address=127.0.0.1 --local_ip_for_outbound_sockets=127.0.0.1 --use_cassandra_authentication=false --start_pgsql_proxy --pgsql_proxy_bind_address=127.0.0.1 >"/home/centos/yugabyte-data/node-1/disk-1/tserver.out" 2>"/home/centos/yugabyte-data/node-1/disk-1/tserver.err" &
2019-04-26 22:54:54,618 INFO: Waiting until we have enough tablet servers (currently 1)
2019-04-26 22:54:59,115 INFO: Waiting until we have enough tablet servers (currently 0)
2019-04-26 22:55:00,213 INFO: Waiting until we have enough tablet servers (currently 0)
2019-04-26 22:55:01,310 INFO: Waiting until we have enough tablet servers (currently 0)
2019-04-26 22:55:02,429 INFO: Waiting until we have enough tablet servers (currently 0)
2019-04-26 22:55:03,527 INFO: Waiting until we have enough tablet servers (currently 0)
2019-04-26 22:55:04,620 INFO: Waiting until we have enough tablet servers (currently 0)
2019-04-26 22:55:05,711 INFO: Waiting until we have enough tablet servers (currently 0)
2019-04-26 22:55:06,814 INFO: Waiting until we have enough tablet servers (currently 0)
2019-04-26 22:55:07,915 INFO: Waiting until we have enough tablet servers (currently 0)
2019-04-26 22:55:09,016 INFO: Waiting until we have enough tablet servers (currently 0)
2019-04-26 22:55:10,117 INFO: Waiting until we have enough tablet servers (currently 0)
2019-04-26 22:55:11,212 INFO: Waiting until we have enough tablet servers (currently 0)
2019-04-26 22:55:12,306 INFO: Waiting until we have enough tablet servers (currently 0)
2019-04-26 22:55:13,402 INFO: Waiting until we have enough tablet servers (currently 0)
2019-04-26 22:55:14,496 INFO: Waiting until we have enough tablet servers (currently 0)
2019-04-26 22:55:15,594 INFO: Waiting until we have enough tablet servers (currently 0)
2019-04-26 22:55:16,688 INFO: Waiting until we have enough tablet servers (currently 0)
2019-04-26 22:55:17,783 INFO: Waiting until we have enough tablet servers (currently 0)
2019-04-26 22:55:18,884 INFO: Waiting until we have enough tablet servers (currently 0)
2019-04-26 22:55:19,975 ERROR: Failed waiting for 0 tservers, got -1
Traceback (most recent call last):
  File "./bin/yb-ctl", line 1267, in <module>
    ClusterControl().run()
  File "./bin/yb-ctl", line 1258, in run
    self.args.func()
  File "./bin/yb-ctl", line 1102, in create
    self.run_cluster_wide_postgres_initdb()
  File "./bin/yb-ctl", line 1204, in run_cluster_wide_postgres_initdb
    self.wait_for_cluster_or_raise()
  File "./bin/yb-ctl", line 1040, in wait_for_cluster_or_raise
    raise RuntimeError("Timed out waiting for Yugabyte cluster!")

**Comment by kokizzu** [comment]
same here, indefinitely wait then error without meaningful info if PostgreSQL is running, so I randomly disable another running databases in sequence (Redis, PostgreSQL, MySQL, CockroachDB, etc..) and it works after i shutdown the running PostgreSQL..

**Comment by bmatican** [comment]
This should have been improved through https://github.com/YugaByte/yugabyte-installation/pull/15.

@kokizzu Feel free to retry this with our latest 1.3 version. This fix might not explicitly mention, for example, which other process might be preventing YB from starting up, but it will bubble up that YB failed due to not being able to bind to a certain port, if that's the root cause...
