### ISSUE TITLE
[DocDB][Redis] Upgrade: Crash in __run_exit_handlers

### ISSUE THREAD

**Issue by def-** [yugabyte/yugabyte-db#12705]
Jira Link: [DB-594](https://yugabyte.atlassian.net/browse/DB-594)
### Description

During upgrade testing I got a Redis client crash during upgrade from 2.8.5.0-b22 to 2.13.3.0-b117:
```
warning: exec file is newer than core file.
[New LWP 20621]

warning: .dynamic section for "/home/yugabyte/yb-software/yugabyte-2.13.3.0-b117-centos-x86_64/linuxbrew/lib/libm.so.6" is not at the expected address (wrong library or version mismatch?)

warning: .dynamic section for "/home/yugabyte/yb-software/yugabyte-2.13.3.0-b117-centos-x86_64/linuxbrew/lib/libdl.so.2" is not at the expected address (wrong library or version mismatch?)

warning: .dynamic section for "/home/yugabyte/yb-software/yugabyte-2.13.3.0-b117-centos-x86_64/linuxbrew/lib/libpthread.so.0" is not at the expected address (wrong library or version mismatch?)
Warning: couldn't activate thread debugging using libthread_db: Cannot find new threads: debugger service failed

warning: Unable to find libthread_db matching inferior's thread library, thread debugging will not be available.
Warning: couldn't activate thread debugging using libthread_db: Cannot find new threads: debugger service failed

warning: Unable to find libthread_db matching inferior's thread library, thread debugging will not be available.
Core was generated by `/home/yugabyte/tserver/bin/redis-cli -h 10.9.135.114 -p 6379 ping'.
Program terminated with signal 11, Segmentation fault.
#0  0x00007ff537002326 in _dl_fini () at dl-fini.c:235
235	dl-fini.c: No such file or directory.

Thread 1 (LWP 20621):
#0  0x00007ff537002326 in _dl_fini () at dl-fini.c:235
        array = 0x5858d84d8f275858
        i = 185273098
        l = 0x7ff537214730
        maps = 0x7ffd4d375770
        i = <optimized out>
        l = <optimized out>
        nmaps = <optimized out>
        nloaded = <optimized out>
        ns = 0
        do_audit = 0
        __PRETTY_FUNCTION__ = "_dl_fini"
#1  0x00007ff535f63969 in __run_exit_handlers (status=0, listp=0x7ff5362c45c0 <__exit_funcs>, run_list_atexit=run_list_atexit@entry=true) at exit.c:82
        atfct = <optimized out>
        onfct = <optimized out>
        cxafct = <optimized out>
        f = <optimized out>
#2  0x00007ff535f639b5 in __GI_exit (status=<optimized out>) at exit.c:104
No locals.
#3  0x00007ff535f4e82c in __libc_start_main (main=0x2246d0 <main>, argc=6, argv=0x7ffd4d375938, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffd4d375928) at ../csu/libc-start.c:323
        result = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {0, 5429469031035503107, 2234960, 140725898926384, 0, 0, -5430282048162299389, -5425937355928174077}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x7ffd4d375970, 0x7ff537217168}, data = {prev = 0x0, cleanup = 0x0, canceltype = 1295473008}}}
        not_first_call = <optimized out>
#4  0x0000000000221a7e in _start ()
No symbol table info available.
```
What was special about this is that I killed the workloads too quickly by accident in https://phabricator.dev.yugabyte.com/D16982
I'll add logs on Jira.

**Comment by def-** [comment]
Something similar happened in ysqlsh, but with even less info:
```

warning: exec file is newer than core file.
[New LWP 20663]

warning: .dynamic section for "/home/yugabyte/yb-software/yugabyte-2.13.3.0-b117-centos-x86_64/linuxbrew/lib/libnss_files.so.2" is not at the expected address (wrong library or version mismatch?)
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/home/yugabyte/yb-software/yugabyte-2.13.3.0-b117-centos-x86_64/linuxbrew/lib/libthread_db.so.1".
Core was generated by `/home/yugabyte/tserver/bin/ysqlsh -h 10.9.135.114 -p 5433 -U yugabyte -d system'.
Program terminated with signal 11, Segmentation fault.
#0  0x00000000000020d6 in ?? ()

Thread 1 (Thread 0x7f3ac8593780 (LWP 20663)):
#0  0x00000000000020d6 in ?? ()
No symbol table info available.
#1  0x00007f3ac8387043 in ?? ()
No symbol table info available.
#2  0x00007fff8b765120 in ?? ()
No symbol table info available.
#3  0x00007f3ac83872a0 in ?? ()
No symbol table info available.
#4  0x0000000000000000 in ?? ()
No symbol table info available.
```

**Comment by rthallamko3** [comment]
@kripasreenivasan , Closing out old redis issues as won't fix for now.
