### ISSUE TITLE
[DocDB] Segmentation fault at yb::tablet::Tablet::DeleteMarkerRetentionTime(at  ../../src/yb/tablet/tablet.cc:3812) 

### ISSUE THREAD

**Issue by sonalsagarwal** [yugabyte/yugabyte-db#12729]
### Description

Observed this while running sysbench workload. It was in the create table phase, where existing tables were dropped and recreated. The create tables did not fail, the tserver 172.151.40.32 restarted as the **priority-worker** thread crashed.

sysbench output for create tables
```
(23:17:55) Creating table 'sbtest5'...
alter sequence with cache size: 1000
(23:18: 0) Creating table 'sbtest6'...
alter sequence with cache size: 1000
(23:18: 4) Creating table 'sbtest7'...
alter sequence with cache size: 1000
(23:18: 9) Creating table 'sbtest8'...
alter sequence with cache size: 1000
(23:18:13) Creating table 'sbtest9'...
alter sequence with cache size: 1000
(23:18:18) Creating table 'sbtest10'...
alter sequence with cache size: 1000
(23:18:22) Creating table 'sbtest11'...
alter sequence with cache size: 1000
(23:18:27) Creating table 'sbtest12'...
alter sequence with cache size: 1000
(23:18:31) Creating table 'sbtest13'...
alter sequence with cache size: 1000
(23:18:35) Creating table 'sbtest14'...
alter sequence with cache size: 1000
(23:18:40) Creating table 'sbtest15'...
alter sequence with cache size: 1000
(23:18:44) Creating table 'sbtest16'...
alter sequence with cache size: 1000
(23:18:49) Creating table 'sbtest17'...
alter sequence with cache size: 1000
(23:18:53) Creating table 'sbtest18'...
alter sequence with cache size: 1000
(23:18:57) Creating table 'sbtest19'...
alter sequence with cache size: 1000
(23:19: 2) Creating table 'sbtest20'...
alter sequence with cache size: 1000
(23:19: 6) Creating table 'sbtest21'..
```
File creation : 
```
ll -ltr /home/yugabyte/cores/core_priority-worker.7716 
-rw-------. 1 yugabyte yugabyte 93554823168 May 30 23:18 /home/yugabyte/cores/core_priority-worker.7716
```

Universe details : created on c5.4xlarge instances with ami-0686851c4e7b1a8e1 for centos. RF3, AZ3 and YB build 2.13.3.0-b44.
Sysbench workload : 100 tables with 4M records in each tables.

Analysis core dump from of **priority-worker** thread  shows we got segmentation fault at **Tablet::DeleteMarkerRetentionTime** called from **docdb_compaction_context.**

```
warning: File "/home/yugabyte/yb-software/yugabyte-2.13.3.0-b44-centos-x86_64/linuxbrew/lib/libthread_db.so.1" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load:/usr/share/gdb/auto-load".
To enable execution of this file add
	add-auto-load-safe-path /home/yugabyte/yb-software/yugabyte-2.13.3.0-b44-centos-x86_64/linuxbrew/lib/libthread_db.so.1
line to your configuration file "/root/.gdbinit".
To completely disable this security protection add
	set auto-load safe-path /
line to your configuration file "/root/.gdbinit".
For more information about this security protection see the
"Auto-loading safe path" section in the GDB manual.  E.g., run from the shell:
	info "(gdb)Auto-loading safe path"

warning: Unable to find libthread_db matching inferior's thread library, thread debugging will not be available.

warning: File "/home/yugabyte/yb-software/yugabyte-2.13.3.0-b44-centos-x86_64/linuxbrew/lib/libthread_db.so.1" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load:/usr/share/gdb/auto-load".

warning: Unable to find libthread_db matching inferior's thread library, thread debugging will not be available.
Core was generated by `/home/yugabyte/tserver/bin/yb-tserver --flagfile /home/yugabyte/tserver/conf/se'.
Program terminated with signal SIGSEGV, Segmentation fault.
Dwarf Error: Cannot find DIE at 0x433eb referenced from DIE at 0xafce0 [in module /home/yugabyte/yb-software/yugabyte-2.13.3.0-b44-centos-x86_64/lib/yb/libtablet.so]
(gdb) bt
#0  yb::tablet::Tablet::DeleteMarkerRetentionTime (this=0x87e49c20, inputs=...) at ../../src/yb/tablet/tablet.cc:3812
#1  0x00007f870f67eb3e in std::__1::__function::__value_func<yb::HybridTime (std::__1::vector<rocksdb::FileMetaData*, std::__1::allocator<rocksdb::FileMetaData*> > const&)>::operator()(std::__1::vector<rocksdb::FileMetaData*, std::__1::allocator<rocksdb::FileMetaData*> > const&) const (this=0x7ccf1bc0, __args=...) at /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20220505181632-c1907426fc-almalinux8-x86_64-clang12-linuxbrew/installed/uninstrumented/libcxx/include/c++/v1/functional:1885
#2  std::__1::function<yb::HybridTime (std::__1::vector<rocksdb::FileMetaData*, std::__1::allocator<rocksdb::FileMetaData*> > const&)>::operator()(std::__1::vector<rocksdb::FileMetaData*, std::__1::allocator<rocksdb::FileMetaData*> > const&) const
    (this=0x7ccf1bc0, __arg=...) at /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20220505181632-c1907426fc-almalinux8-x86_64-clang12-linuxbrew/installed/uninstrumented/libcxx/include/c++/v1/functional:2560
#3  yb::docdb::CreateCompactionContextFactory(std::__1::shared_ptr<yb::docdb::HistoryRetentionPolicy>, yb::docdb::KeyBounds const*, std::__1::function<yb::HybridTime (std::__1::vector<rocksdb::FileMetaData*, std::__1::allocator<rocksdb::FileMetaData*> > const&)> const&, yb::docdb::SchemaPackingProvider*)::$_0::operator()(rocksdb::CompactionFeed*, rocksdb::CompactionContextOptions const&) const (this=0x7ccf1ba0, next_feed=<optimized out>, options=...)
    at ../../src/yb/docdb/docdb_compaction_context.cc:775
#4  std::__1::__invoke<yb::docdb::CreateCompactionContextFactory(std::__1::shared_ptr<yb::docdb::HistoryRetentionPolicy>, yb::docdb::KeyBounds const*, std::__1::function<yb::HybridTime (std::__1::vector<rocksdb::FileMetaData*, std::__1::allocator<rocksdb::FileMetaData*> > const&)> const&, yb::docdb::SchemaPackingProvider*)::$_0&, rocksdb::CompactionFeed*, rocksdb::CompactionContextOptions const&> (__f=..., __args=..., __args=...)
    at /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20220505181632-c1907426fc-almalinux8-x86_64-clang12-linuxbrew/installed/uninstrumented/libcxx/include/c++/v1/type_traits:3694
#5  std::__1::__invoke_void_return_wrapper<std::__1::unique_ptr<rocksdb::CompactionContext, std::__1::default_delete<rocksdb::CompactionContext> >, false>::__call<yb::docdb::CreateCompactionContextFactory(std::__1::shared_ptr<yb::docdb::HistoryRetentionPolicy>, yb::docdb::KeyBounds const*, std::__1::function<yb::HybridTime (std::__1::vector<rocksdb::FileMetaData*, std::__1::allocator<rocksdb::FileMetaData*> > const&)> const&, yb::docdb::SchemaPackingProvider*)::$_0&, rocksdb::CompactionFeed*, rocksdb::CompactionContextOptions const&>(yb::docdb::CreateCompactionContextFactory(std::__1::shared_ptr<yb::docdb::HistoryRetentionPolicy>, yb::docdb::KeyBounds const*, std::__1::function<yb::HybridTime (std::__1::vector<rocksdb::FileMetaData*, std::__1::allocator<rocksdb::FileMetaData*> > const&)> const&, yb::docdb::SchemaPackingProvider*)::$_0&, rocksdb::CompactionFeed*&&, rocksdb::CompactionContextOptions const&) (__args=..., __args=..., __args=...)
    at /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20220505181632-c1907426fc-almalinux8-x86_64-clang12-linuxbrew/installed/uninstrumented/libcxx/include/c++/v1/__functional_base:317
#6  std::__1::__function::__alloc_func<yb::docdb::CreateCompactionContextFactory(std::__1::shared_ptr<yb::docdb::HistoryRetentionPolicy>, yb::docdb::KeyBounds const*, std::__1::function<yb::HybridTime (std::__1::vector<rocksdb::FileMetaData*, std::__1::allocator<rocksdb::FileMetaData*> > const&)> const&, yb::docdb::SchemaPackingProvider*)::$_0, std::__1::allocator<yb::docdb::CreateCompactionContextFactory(std::__1::shared_ptr<yb::docdb::HistoryRetentionPolicy>, yb::docdb::KeyBounds const*, std::__1::function<yb::HybridTime (std::__1::vector<rocksdb::FileMetaData*, std::__1::allocator<rocksdb::FileMetaData*> > const&)> const&, yb::docdb::SchemaPackingProvider*)::$_0>, std::__1::unique_ptr<rocksdb::CompactionContext, std::__1::default_delete<rocksdb::CompactionContext> > (rocksdb::CompactionFeed*, rocksdb::CompactionContextOptions const&)>::operator()(rocksdb::CompactionFeed*&&, rocksdb::CompactionContextOptions const&) (this=0x7ccf1ba0, __arg=..., __arg=...)
    at /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20220505181632-c1907426fc-almalinux8-x86_64-clang12-linuxbrew/installed/uninstrumented/libcxx/include/c++/v1/functional:1558
#7  std::__1::__function::__func<yb::docdb::CreateCompactionContextFactory(std::__1::shared_ptr<yb::docdb::HistoryRetentionPolicy>, yb::docdb::KeyBounds const*, std::__1::function<yb::HybridTime (std::__1::vector<rocksdb::FileMetaData*, std::__1::allocator<rocksdb::FileMetaData*> > const&)> const&, yb::docdb::SchemaPackingProvider*)::$_0, std::__1::allocator<yb::docdb::CreateCompactionContextFactory(std::__1::shared_ptr<yb::docdb::HistoryRetentionPolicy>, yb::docdb::KeyBounds const*, std::__1::function<yb::HybridTime (std::__1::vector<rocksdb::FileMetaData*, std::__1::allocator<rocksdb::FileMetaData*> > const&)> const&, yb::docdb::SchemaPackingProvider*)::$_0>, std::__1::unique_ptr<rocksdb::CompactionContext, std::__1::default_delete<rocksdb::CompactionContext> > (rocksdb::CompactionFeed*, rocksdb::CompactionContextOptions const&)>::operator()(rocksdb::CompactionFeed*&&, rocksdb::CompactionContextOptions const&) (this=0x7ccf1b90, __arg=..., __arg=...)
    at /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20220505181632-c1907426fc-almalinux8-x86_64-clang12-linuxbrew/installed/uninstrumented/libcxx/include/c++/v1/functional:1732
#8  0x00007f870e11e76b in std::__1::__function::__value_func<std::__1::unique_ptr<rocksdb::CompactionContext, std::__1::default_delete<rocksdb::CompactionContext> > (rocksdb::CompactionFeed*, rocksdb::CompactionContextOptions const&)>::operator()(rocksdb::CompactionFeed*&&, rocksdb::CompactionContextOptions const&) const (this=<optimized out>, __args=..., __args=...)
    at /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20220505181632-c1907426fc-almalinux8-x86_64-clang12-linuxbrew/installed/uninstrumented/libcxx/include/c++/v1/functional:1885
#9  std::__1::function<std::__1::unique_ptr<rocksdb::CompactionContext, std::__1::default_delete<rocksdb::CompactionContext> > (rocksdb::CompactionFeed*, rocksdb::CompactionContextOptions const&)>::operator()(rocksdb::CompactionFeed*, rocksdb::CompactionContextOptions const&) const (this=<optimized out>, __arg=..., __arg=...)
    at /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20220505181632-c1907426fc-almalinux8-x86_64-clang12-linuxbrew/installed/uninstrumented/libcxx/include/c++/v1/functional:2560
#10 rocksdb::CompactionJob::ProcessKeyValueCompaction (this=<optimized out>, holder=0x7f675ffffe38, sub_compact=0xc0318ea0) at ../../src/yb/rocksdb/db/compaction_job.cc:638
#11 0x00007f870e11d39a in rocksdb::CompactionJob::Run (this=0x7f675ffffec8) at ../../src/yb/rocksdb/db/compaction_job.cc:467
#12 0x00007f870e14b312 in rocksdb::DBImpl::BackgroundCompaction (
    this=<error reading variable: Dwarf Error: Cannot find DIE at 0x16def referenced from DIE at 0x7c34a [in module /home/yugabyte/yb-software/yugabyte-2.13.3.0-b44-centos-x86_64/lib/yb/librocksdb.so]>, made_progress=0x7f67600010a7, 
    job_context=<optimized out>, log_buffer=<error reading variable: Dwarf Error: Cannot find DIE at 0x16def referenced from DIE at 0x7c34a [in module /home/yugabyte/yb-software/yugabyte-2.13.3.0-b44-centos-x86_64/lib/yb/librocksdb.so]>, 
    manual_compaction=0x0, compaction=...) at ../../src/yb/rocksdb/db/db_impl.cc:3723
#13 0x00007f870e1499e6 in rocksdb::DBImpl::BackgroundCallCompaction (this=0x29dfa400, m=0x0, compaction=..., compaction_task=<optimized out>) at ../../src/yb/rocksdb/db/db_impl.cc:3447
#14 0x00007f870e15924a in rocksdb::DBImpl::CompactionTask::DoRun (this=0x7f870fa1c000 <yb::tablet::Tablet::DeleteMarkerRetentionTime(std::__1::vector<rocksdb::FileMetaData*, std::__1::allocator<rocksdb::FileMetaData*> > const&)>, 
    suspender=<optimized out>) at ../../src/yb/rocksdb/db/db_impl.cc:284
#15 0x00007f870cc2fb02 in yb::(anonymous namespace)::PriorityThreadPoolWorker::Run (this=0xf705dd8) at ../../src/yb/util/priority_thread_pool.cc:275
#16 0x00007f870cc56e51 in yb::Thread::SuperviseThread (arg=0x10ae58360) at /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20220505181632-c1907426fc-almalinux8-x86_64-clang12-linuxbrew/installed/uninstrumented/libcxx/include/c++/v1/functional:1885
#17 0x00007f870af42694 in start_thread (arg=0x7f6760009700) at pthread_create.c:333
#18 0x00007f870a67f41d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

Universe link : http://10.9.131.126/universes/ca4dfbca-83c5-4560-a074-a58d71d45d3f/nodes

Since multiple tests were run using scripts, the current data is for the later runs scheduled.

**Comment by rthallamko3** [comment]
Needs to be back-ported to 2.14 branch too.
