### ISSUE TITLE
[xcluster] alter_universe_replication add_table fails for universe with different certs

### ISSUE THREAD

**Issue by shashwat-yb** [yugabyte/yugabyte-db#12859]
Jira Link: [DB-2620](https://yugabyte.atlassian.net/browse/DB-2620)
### Description

Steps to repro -

- Setup xcluster replication between 2 universes with TLS ON and different certs.
- Start replication in demo1 table.
- Edit replication by adding demo2 table → fails.

Failing on 2.14, 2.15.0 and 2.15.1.

Platform Error message -

```
java.lang.RuntimeException: java.lang.RuntimeException: XClusterConfigModifyTables : completed 1 out of 1 tasks. failed.
	at com.yugabyte.yw.commissioner.tasks.EditXClusterConfig.run(EditXClusterConfig.java:80)
	at com.yugabyte.yw.commissioner.TaskExecutor$AbstractRunnableTask.run(TaskExecutor.java:783)
	at com.yugabyte.yw.commissioner.TaskExecutor$RunnableTask.run(TaskExecutor.java:954)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.yugabyte.yw.common.logging.MDCAwareRunnable.run(MDCAwareRunnable.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.RuntimeException: XClusterConfigModifyTables : completed 1 out of 1 tasks. failed.
	at com.yugabyte.yw.commissioner.TaskExecutor$RunnableTask.runSubTasks(TaskExecutor.java:1057)
	at com.yugabyte.yw.commissioner.tasks.EditXClusterConfig.run(EditXClusterConfig.java:76)
	... 8 common frames omitted
Caused by: java.lang.RuntimeException: org.yb.client.MasterErrorException: Server[YB Master - 10.9.117.14:7100] INVALID_ARGUMENT[code 4]: Failed to add certificate file: No such file or directory
	at com.yugabyte.yw.commissioner.tasks.subtasks.xcluster.XClusterConfigModifyTables.run(XClusterConfigModifyTables.java:200)
	at com.yugabyte.yw.commissioner.TaskExecutor$AbstractRunnableTask.run(TaskExecutor.java:783)
	at com.yugabyte.yw.commissioner.TaskExecutor$RunnableSubTask.run(TaskExecutor.java:1122)
	... 6 common frames omitted
Caused by: org.yb.client.MasterErrorException: Server[YB Master - 10.9.117.14:7100] INVALID_ARGUMENT[code 4]: Failed to add certificate file: No such file or directory
```

**Comment by shashwat-yb** [comment]
Jira ticket - https://yugabyte.atlassian.net/browse/PLAT-4313

**Comment by shashwat-yb** [comment]
After Triage - `It is a DB issue. If the replication group name is 4ac3e59a-1039-46e3-9641-5b9f9cccd162_myrepl1, It reads the cert from /home/yugabyte/yugabyte-tls-producer/4ac3e59a-1039-46e3-9641-5b9f9cccd162_myrepl1.ALTER instead of /home/yugabyte/yugabyte-tls-producer/4ac3e59a-1039-46e3-9641-5b9f9cccd162_myrepl1.`

**Comment by nspiegelberg** [comment]
> [Hamidreza Zare](https://app.slack.com/team/U021EAHRRN0)  [6 minutes ago](https://yugabyte.slack.com/archives/CHC5RSY74/p1655136067482229?thread_ts=1655114782.626209&cid=CHC5RSY74)
> This issue is referring to **alter_universe_replication** operation to add a table to an existing xCluster replication config when the certs for the source and target universe are different.
> In case of mismatched certs, the source root TLS must be in a directory on the target universe with the same name as producer_id (<source_universe_uuid>_<config_name>). The issue happens because the target universe looks up the cert in a directory with name <source_universe_uuid>_<config_name>.ALTER instead.

**Comment by nspiegelberg** [comment]
There’s a workaround for this issue (softlink create *.ALTER cert dir).  Not a good experience, but unblocks functionality.
