### ISSUE TITLE
[DocDB] Duplicate request error in java client while hitting OOM on YSQL node side

### ISSUE THREAD

**Issue by qvad** [yugabyte/yugabyte-db#12983]
### Description

1. Setup c5.large cluster
2. Start workload and wait for 600 seconds to have some data on cluster
3. At some point evaluate query that might cause OOM (use repeat function for that)
4. Check, /var/log/messages for OOM and that Postgres process killed

We use SqlInserts workload from sample apps and at some point client can hit `Already present: Duplicate request 57202 from client 7abdbbc1-8617-486b-8448-cc1702ad56eb (min running 57202)`, this issue might be confusing.

```
615442 [Thread-0] INFO com.yugabyte.sample.common.metrics.MetricsTracker  - Read: 590.35 ops/sec (3.39 ms/op), 388528 total ops  |  Write: 523.75 ops/sec (3.81 ms/op), 344526 total ops  |  Uptime: 615092 ms | 
620442 [Thread-0] INFO com.yugabyte.sample.common.metrics.MetricsTracker  - Read: 526.76 ops/sec (3.79 ms/op), 391162 total ops  |  Write: 412.37 ops/sec (4.85 ms/op), 346588 total ops  |  Uptime: 620093 ms | 
625442 [Thread-0] INFO com.yugabyte.sample.common.metrics.MetricsTracker  - Read: 6.00 ops/sec (3.40 ms/op), 391192 total ops  |  Write: 3.80 ops/sec (3.95 ms/op), 346607 total ops  |  Uptime: 625093 ms | 
630443 [Thread-0] INFO com.yugabyte.sample.common.metrics.MetricsTracker  - Read: 0.00 ops/sec (0.00 ms/op), 391192 total ops  |  Write: 2.00 ops/sec (540.90 ms/op), 346617 total ops  |  Uptime: 630094 ms | 
635443 [Thread-0] INFO com.yugabyte.sample.common.metrics.MetricsTracker  - Read: 0.00 ops/sec (0.00 ms/op), 391192 total ops  |  Write: 0.00 ops/sec (0.00 ms/op), 346617 total ops  |  Uptime: 635094 ms | 
638246 [Thread-1] INFO com.yugabyte.sample.apps.SqlInserts  - Failed writing key: 4f404e8d-d47e-4930-86e1-394639a061a2:seed:LxLHLwPvEvLOwELQKHEPNwIEKQLNKQsHNIsJMyMIMxQwFwMPxFMRLIFQOxJFLRMOLRtIOJtKNzNJNyRxGxNQyGNSMJGRPyKGMSNPMSuJPKuLOAOKOzSyHyORzHOTNKHSQzLHNTOQNTvKQLvMPBPLPATzIzPSAIPUOLITRAMIOUPROUwLRMwNQCQMQBUAJAQTBJQVPMJUSBNJPVQSPVxMSNxORDRNRCVBKBRUCKRWQNKVTCOKQWRTQWyNTOyPSESOSDWCLCSVDLSXROLWUDPLRXSURXzOUPzQTFTPTEXDMDTWEMTYSPMXVEQMSYTVSYAPVQARUGUQUFYENEUXFNUZTQNYWFRNTZUWTZBQWRBS:346608
com.yugabyte.util.PSQLException: ERROR: Already present: Duplicate request 57202 from client 7abdbbc1-8617-486b-8448-cc1702ad56eb (min running 57202)
	at com.yugabyte.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2679)
	at com.yugabyte.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2359)
	at com.yugabyte.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:349)
	at com.yugabyte.jdbc.PgStatement.executeInternal(PgStatement.java:484)
	at com.yugabyte.jdbc.PgStatement.execute(PgStatement.java:404)
	at com.yugabyte.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:162)
	at com.yugabyte.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:130)
	at com.yugabyte.sample.apps.SqlInserts.doWrite(SqlInserts.java:181)
	at com.yugabyte.sample.apps.AppBase.performWrite(AppBase.java:782)
	at com.yugabyte.sample.common.IOPSThread.run(IOPSThread.java:87)
```

**Comment by pilshchikov** [comment]
Duplicate for https://github.com/yugabyte/yugabyte-db/issues/7251

**Comment by pilshchikov** [comment]
@Huqicheng can you please approve tht it sililar to 7251 issue?
