### ISSUE TITLE
[DocDB] Tserver crash in yb::docdb::DocRowwiseIterator::DoNextRow

### ISSUE THREAD

**Issue by def-** [yugabyte/yugabyte-db#12996]
Jira Link: [DB-2720](https://yugabyte.atlassian.net/browse/DB-2720)
### Description

I initially thought this is another instance of https://github.com/yugabyte/yugabyte-db/issues/12813, but after getting coredumps to print fully it might be a separate bug:
```
$ cd ~/code/yugabyte-db
$ git checkout b0dcb81db7f0793ab7e6278ec1f2e34d344d3a7c
$ ./yb_build.sh release
$ bin/yb-ctl --replication_factor 1 create --tserver_flags=ysql_enable_packed_row=true,ysql_packed_row_size_limit=1700 --master_flags=ysql_enable_packed_row=true,ysql_packed_row_size_limit=1700
$ cd ~/code/yb-long-system-test
$ python3.9 ./long_system_test.py --nodes=127.0.0.1:5433 --threads=10 --runtime=0 --complexity=full --max-columns=10 --seed=032216
2022-06-22 16:19:01,643 MainThread INFO
2022-06-22 16:19:01,644 MainThread INFO     --------------------------------------------------------------------------------
2022-06-22 16:19:01,644 MainThread INFO     Running Long System Test 0.1
2022-06-22 16:19:01,644 MainThread INFO     --------------------------------------------------------------------------------
2022-06-22 16:19:01,644 MainThread INFO
2022-06-22 16:19:01,651 MainThread INFO     Reproduce with: git checkout 6fdda644 && ./long_system_test.py --nodes=127.0.0.1:5433 --threads=10 --runtime=0 --complexity=full --max-columns=10 --seed=032216
2022-06-22 16:19:01,882 MainThread INFO     Database version: PostgreSQL 11.2-YB-2.15.1.0-b0 on x86_64-pc-linux-gnu, compiled by clang version 12.0.1 (https://github.com/yugabyte/llvm-project.git bdb147e675d8c87cee72cc1f87c4b82855977d94), 64-bit
2022-06-22 16:19:01,884 MainThread INFO     Creating tables for database db_lst_032216
2022-06-22 16:19:12,566 MainThread INFO     Starting worker_0: RandomSelectAction, SetConfigAction
2022-06-22 16:19:12,568 MainThread INFO     Starting worker_1: CreateIndexAction, DropIndexAction, SetConfigAction, AddColumnAction
2022-06-22 16:19:12,569 MainThread INFO     Starting worker_2: CreateIndexAction, DropIndexAction, SetConfigAction, AddColumnAction
2022-06-22 16:19:12,570 MainThread INFO     Starting worker_3: CreateIndexAction, DropIndexAction, SetConfigAction, AddColumnAction
2022-06-22 16:19:12,570 MainThread INFO     Starting worker_4: RandomSelectAction, SetConfigAction
2022-06-22 16:19:12,571 MainThread INFO     Starting worker_5: SingleInsertAction, SingleUpdateAction, SingleDeleteAction, BulkInsertAction, BulkUpdateAction, SetConfigAction
2022-06-22 16:19:12,572 MainThread INFO     Starting worker_6: RandomSelectAction, SetConfigAction
2022-06-22 16:19:12,573 MainThread INFO     Starting worker_7: CreateIndexAction, DropIndexAction, SetConfigAction, AddColumnAction
2022-06-22 16:19:12,574 MainThread INFO     Starting worker_8: SingleInsertAction, SingleUpdateAction, SingleDeleteAction, BulkInsertAction, BulkUpdateAction, SetConfigAction
2022-06-22 16:19:12,574 MainThread INFO     Starting worker_9: RandomSelectAction, SetConfigAction
2022-06-22 16:19:22,585 MainThread INFO     Worker queries/s: [008.2][000.6][001.0][000.5][013.1][013.1][009.1][000.9][010.4][010.4]
[...]
2022-06-22 17:15:16,045 MainThread INFO     Worker queries/s: [000.9][000.1][000.2][000.0][000.5][001.1][000.9][000.2][002.0][000.4]
2022-06-22 17:15:25,275 worker_9   ERROR    Unexpected query failure: OperationalError
Query: EXPLAIN (ANALYZE TRUE, VERBOSE TRUE, COSTS TRUE, BUFFERS FALSE, TIMING TRUE, SUMMARY TRUE, FORMAT XML)
SELECT '2004-06-20', -51, 92, ceil(57.77156509952039), 83, (2147483647) >= (17), '[36,93]'::INT2RANGE, '78', '{"a": 4, "b": ["0", "1", "2", "3"], "c": true}'::jsonb, -59.3284072693391, '{"a": 4, "b": ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9"], "c": true}'::jsonb, '{"a": 3, "b": ["0", "1", "2", "3", "4", "5"], "c": true}'::json, ('(-99,)'::INT8RANGE) * ('[-99,-1]'::INT8RANGE), CAST((CAST((-60.99414560869645) AS SMALLINT)) AS NUMERIC), '[-5.6048566897154615,39.646949363324296)'::NUMRANGE, '{"a": 8, "b": ["0", "1", "2", "3", "4", "5"], "c": true}'::json, '(,29]'::INT4RANGE, '82', 60, 95, range_merge((int4range((2147483647), NULL)), ('(,-42]'::INT4RANGE)), -41.50422737918529, -4, '(,-86)'::INT4RANGE, 25.648300420345066, @ (-43), '15', '(-96.91078829764635,70.85141444929789]'::NUMRANGE, 5.1837522518543295, '(-97,-26]'::INT4RANGE, -43.553053325169365, '{"a": 10, "b": ["0", "1", "2", "3", "4", "5", "6", "7"], "c": false}'::json, ('[-99,18]'::INT4RANGE) * (('(-51,26)'::INT4RANGE) * ('(,-2147483648]'::INT4RANGE)), count(tg4_1.c33_numrange), 51.554864295708654, 52, '[-61.81760085042336,5.5180558962250075)'::NUMRANGE, 9, FALSE, count(tg4_1.c39_float8), FALSE, ||/ ((CAST((32767) AS SMALLINT)) + (3)), '(-86,-78]'::INT4RANGE, 25, '{"a": 10, "b": ["0"], "c": false}'::json, 20, CAST((30) AS FLOAT8), -95, '80', -22.634996538641914, count(*), range_merge(('(-4.734322816556698,67.19313992624765)'::NUMRANGE), (numrange(NULL, (54.037978831172694)))), 12.498788959755004, '[1906-07-01,1958-01-20)'::DATERANGE, '[1914-11-27,1989-11-27]'::DATERANGE, -29.530326954169198, range_merge((range_merge(((range_merge((range_merge(('(,-6)'::INT2RANGE), ('(,-8]'::INT2RANGE))), ((range_merge(('(,-69)'::INT2RANGE), ((('[6,93)'::INT2RANGE) * ('[-94,-70)'::INT2RANGE)) * ('[46,93)'::INT2RANGE)))) * ('(,79)'::INT2RANGE)))) * (range_merge((('(59,80)'::INT2RANGE) * (range_merge(('(-51,-9]'::INT2RANGE), ('(23,)'::INT2RANGE)))), (range_merge((range_merge(('[-93,-78)'::INT2RANGE), ('[-18,12]'::INT2RANGE))), ('empty'::INT2RANGE)))))), ('(,11)'::INT2RANGE))), ((range_merge(('(,95]'::INT2RANGE), (range_merge((('(-79,86)'::INT2RANGE) * ('[-67,-15]'::INT2RANGE)), ('(-28,73]'::INT2RANGE))))) * (range_merge(('(-20,31]'::INT2RANGE), ('(,-18]'::INT2RANGE))))), 88.6406092013155, '1936-04-16', '(,-32768]'::INT2RANGE, -82.14457611018003, range_merge(('(1907-07-17,2000-07-11]'::DATERANGE), (range_merge(('(1930-09-23,2002-08-27]'::DATERANGE), ('(1984-11-03,2008-05-10)'::DATERANGE)))), CAST((-11.110183161881665) AS BIGINT), -59, ('[-79,-36]'::INT2RANGE) * (('[-53,37)'::INT2RANGE) * ('(,19)'::INT2RANGE)), count(tg4_1.c65_daterange), range_merge((numrange(NULL, (9.258862600098226))), (numrange(NULL, (-77.72972645873304)))), TRUE, -68 FROM tg4_1 WHERE FALSE ORDER BY 15 ASC LIMIT 5 OFFSET 6;
  values: None
  runtime: 2022-06-22 17:15:09.878 - 2022-06-22 17:15:25.275
  supports explain: False
  supports rollback: False
  affected rows: None
Action: RandomSelectAction
Error class: OperationalError
Error code: None
Error message: FATAL:  Could not reconnect to database
    @           0x997b18  errmsg
    @           0x9836a2  YBPreloadRelCache
    @           0x83f955  YBPreloadRelCacheHelper
    @           0x83f77d  YBRefreshCache
    @           0x83b7fd  PostgresMain
    @           0x7ad74c  BackendRun
    @           0x7acba0  ServerLoop
    @           0x7a920b  PostmasterMain
    @           0x712f4d  PostgresServerProcessMain
    @           0x7133f2  main
    @     0x7fcc68409825  __libc_start_main
    @           0x4b89f9  _start
    @              (nil)  (unknown)

HINT:  Database might have been dropped by another user
    @           0x9991d8  errhint
    @           0x9836b2  YBPreloadRelCache
    @           0x83f955  YBPreloadRelCacheHelper
    @           0x83f77d  YBRefreshCache
    @           0x83b7fd  PostgresMain
    @           0x7ad74c  BackendRun
    @           0x7acba0  ServerLoop
    @           0x7a920b  PostmasterMain
    @           0x712f4d  PostgresServerProcessMain
    @           0x7133f2  main
    @     0x7fcc68409825  __libc_start_main
    @           0x4b89f9  _start
    @              (nil)  (unknown)

server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
Transaction isolation level: serializable
DB Node: host: 127.0.0.1, port: 5433
DB Backend PID: 595941
```
Afterwards I can't connect to database anymore:
```
[dfelsing@dev-server-dfelsing yb-long-system-test]$ python3.9 ./long_system_test.py --nodes=127.0.0.1:5433 --threads=10 --runtime=0 --complexity=full --max-columns=10 --seed=032216
2022-06-22 17:41:05,208 MainThread INFO
2022-06-22 17:41:05,208 MainThread INFO     --------------------------------------------------------------------------------
2022-06-22 17:41:05,208 MainThread INFO     Running Long System Test 0.1
2022-06-22 17:41:05,209 MainThread INFO     --------------------------------------------------------------------------------
2022-06-22 17:41:05,209 MainThread INFO
2022-06-22 17:41:05,215 MainThread INFO     Reproduce with: git checkout 6fdda644 && ./long_system_test.py --nodes=127.0.0.1:5433 --threads=10 --runtime=0 --complexity=full --max-columns=10 --seed=032216
Traceback (most recent call last):
  File "/nfusr/dev-server/dfelsing/code/yb-long-system-test/./long_system_test.py", line 279, in <module>
    main()
  File "/nfusr/dev-server/dfelsing/code/yb-long-system-test/./long_system_test.py", line 270, in main
    lst.run()
  File "/nfusr/dev-server/dfelsing/code/yb-long-system-test/./long_system_test.py", line 203, in run
    self._create_tables()
  File "/nfusr/dev-server/dfelsing/code/yb-long-system-test/./long_system_test.py", line 166, in _create_tables
    conn = psycopg2.connect(**self._get_connect_opts())
  File "/usr/local/lib64/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "127.0.0.1", port 5433 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
```
```

**Comment by def-** [comment]
So far couldn't reproduce without packed columns enabled.

**Comment by spolitov** [comment]
Seems it has the same root cause as #13097
