### ISSUE TITLE
Error changing RLIMIT_NOFILE from 1024 to 1048576

### ISSUE THREAD

**Issue by tadli** [yugabyte/yugabyte-db#13070]
Jira Link: [DB-2790](https://yugabyte.atlassian.net/browse/DB-2790)
### Description

/ Running system checks...ERROR:root: | 0.0s | Error changing RLIMIT_NOFILE from 1024 to 1048576: current limit exceeds maximum limit
ERROR:root: | 0.0s | Error changing RLIMIT_NPROC from 7102 to 12000: current limit exceeds maximum limit
⚠ WARNING System checks. Following pre-reqs are not met:
- ntp package missing. We recommend installing ntp package.
- open files ulimits value set low. Please set soft and hard limits to 1048576.
- max user processes ulimits value set low. Please set soft and hard limits to 12000.

Review the following docs and rerun the start command.
Quick start for Linux: https://docs.yugabyte.com/latest/quick-start/install/linux/

/ Starting the YugabyteDB Processes...ERROR:root: | 0.1s | Failed to create symlink from /root/var/data/yb-data/master/logs to /root/var/logs/master
- Starting the YugabyteDB Processes...ERROR:root: | 0.8s | Failed waiting for yb-master... process died.
ERROR:root: | 0.8s | Failed to setup master. Exception: Traceback (most recent call last):
  File "./bin/yugabyted", line 1543, in setup_master
    if retry_op(self.wait_master, timeout):
  File "./bin/yugabyted", line 3495, in retry_op
    return func()
  File "./bin/yugabyted", line 1281, in wait_master
    raise RuntimeError("process died unexpectedly.")
RuntimeError: process died unexpectedly.

For more information, check the logs in /root/var/logs
Failed to setup master. Exception: Traceback (most recent call last):
  File "./bin/yugabyted", line 1543, in setup_master
    if retry_op(self.wait_master, timeout):
  File "./bin/yugabyted", line 3495, in retry_op
    return func()
  File "./bin/yugabyted", line 1281, in wait_master
    raise RuntimeError("process died unexpectedly.")
RuntimeError: process died unexpectedly.

I installed in centos 8 and got this error, how should I fix it, thanks!

**Comment by ddorian** [comment]
> File "/home/yugabyte/yugabyte-2.17.0.0/./bin/yugabyted", line 822, in linux_prereqs_check
transparent_hugepages = re.search("[(.*)]", transparent_hugepages_check[0]).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

Looks like transparent huge pages don't exist in your system. I've asked internally if we support Windows, but in linux it will definitely work.

**Comment by nchandrappa** [comment]
We will look into downgrading `transparent huge pages` validation to the warning. We'll update the ticket after assessing the impact of this change. Thanks
