### ISSUE TITLE
[DocDB][LST] Packed columns: Tserver crash in yb::docdb::SchemaPackingStorage::GetPacking

### ISSUE THREAD

**Issue by def-** [yugabyte/yugabyte-db#13097]
Jira Link: [DB-2808](https://yugabyte.atlassian.net/browse/DB-2808)
### Description

```
$ cd ~/code/yugabyte-db
$ git checkout 4c08faee38cf8cb0affeff1785751cd93cabb9a5
$ git revert 85ac8d87d99a214d99f6e701334b3162bfedc7e5.
$ ./yb_build.sh release
$ bin/yb-ctl --replication_factor 1 create --tserver_flags=yb_enable_read_committed_isolation=true,ysql_enable_packed_row=true,ysql_num_shards_per_tserver=1,enable_stream_compression=true,stream_compression_algo=1,yb_num_shards_per_tserver=1 --master_flags=yb_enable_read_committed_isolation=true,ysql_enable_packed_row=true,enable_stream_compression=true,stream_compression_algo=1,enable_automatic_tablet_splitting=true,tablet_split_low_phase_shard_count_per_node=40,tablet_split_high_phase_shard_count_per_node=50
$ cd ~/code/yb-long-system-test
$ git checkout aa0c41ff07d3617fd85c62cad743ce4ca0cfc26f
$ python3.9 ./long_system_test.py --nodes=127.0.0.1:5433 --threads=20 --runtime=60 --max-columns=20 --complexity=full
```
No FATAL file is written, but tserver crashed:
```
[dfelsing@dev-server-dfelsing yugabyte-data]$ coredumpctl gdb 348571
           PID: 348571 (yb-tserver)
           UID: 2200 (dfelsing)
           GID: 1500 (ybdev)
        Signal: 11 (SEGV)
     Timestamp: Wed 2022-06-29 14:13:33 UTC (19min ago)
  Command Line: /nfusr/dev-server/dfelsing/code/yugabyte-db/build/latest/bin/yb-tserver --fs_data_dirs /nfusr/dev-server/dfelsing/yugabyte-data/node-1/disk-1 --webserver_interface 127.0.0.1 --rpc_bind_addresses 127.0.0.1 --v 0 --version_file_json_path=/nfusr/dev-server/dfelsing/code/yugabyte-db/build/release-clang12-linuxbrew-dynamic-ninja --tserver_master_addrs=127.0.0.1:7100 --yb_num_shards_per_tserver=2 --redis_proxy_bind_address=127.0.0.1:6379 --cql_proxy_bind_address=127.0.0.1:9042 --local_ip_for_outbound_sockets=127.0.0.1 --use_cassandra_authentication=false --ysql_num_shards_per_tserver=2 --default_memory_limit_to_ram_ratio=0.65 --enable_ysql=true --pgsql_proxy_bind_address=127.0.0.1:5433 --yb_enable_read_committed_isolation=true --ysql_enable_packed_row=true --ysql_num_shards_per_tserver=1 --enable_stream_compression=true --stream_compression_algo=1 --yb_num_shards_per_tserver=1
    Executable: /nfusr/dev-server/dfelsing/code/yugabyte-db/build/release-clang12-linuxbrew-dynamic-ninja/bin/yb-tserver
 Control Group: /
         Slice: -.slice
       Boot ID: ec49ddc173ff46c5a373cc2ff8001c66
    Machine ID: 8ce570b287c573260282d2e8edd33beb
      Hostname: dev-server-dfelsing
       Storage: /var/lib/systemd/coredump/core.yb-tserver.2200.ec49ddc173ff46c5a373cc2ff8001c66.348571.1656512013000000.lz4
       Message: Process 348571 (yb-tserver) of user 2200 dumped core.
[...]
(gdb) bt
#0  std::__1::__hash_table<std::__1::__hash_value_type<unsigned int, yb::docdb::SchemaPacking>, std::__1::__unordered_map_hasher<unsigned int, std::__1::__hash_value_type<unsigned int, yb::docdb::SchemaPacking>, std::__1::hash<unsigned int>, std::__1::equal_to<unsigned int>, true>, std::__1::__unordered_map_equal<unsigned int, std::__1::__hash_value_type<unsigned int, yb::docdb::SchemaPacking>, std::__1::equal_to<unsigned int>, std::__1::hash<unsigned int>, true>, std::__1::allocator<std::__1::__hash_value_type<unsigned int, yb::docdb::SchemaPacking> > >::find<unsigned int> (this=0x1ad711b8, __k=@0x7f0628e58d14: 0)
    at /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20220505181632-c1907426fc-almalinux8-x86_64-clang12-linuxbrew/installed/uninstrumented/libcxx/include/c++/v1/__hash_table:2425
#1  std::__1::unordered_map<unsigned int, yb::docdb::SchemaPacking, std::__1::hash<unsigned int>, std::__1::equal_to<unsigned int>, std::__1::allocator<std::__1::pair<unsigned int const, yb::docdb::SchemaPacking> > >::find (this=0x1ad711b8, __k=@0x7f0628e58d14: 0)
    at /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20220505181632-c1907426fc-almalinux8-x86_64-clang12-linuxbrew/installed/uninstrumented/libcxx/include/c++/v1/unordered_map:1354
#2  yb::docdb::SchemaPackingStorage::GetPacking (this=0x1ad711b8, schema_version=0) at ../../src/yb/docdb/packed_row.cc:197
#3  0x00007f09d878d6b9 in yb::docdb::PgsqlWriteOperation::ApplyInsert (this=this@entry=0x5fa0ea0, data=..., is_upsert=...) at ../../src/yb/docdb/pgsql_operation.cc:454
#4  0x00007f09d878d4bc in yb::docdb::PgsqlWriteOperation::Apply (this=0x5fa0ea0, data=...) at ../../src/yb/docdb/pgsql_operation.cc:419
#5  0x00007f09d86eb728 in yb::docdb::AssembleDocWriteBatch (doc_write_ops=..., deadline=..., deadline@entry=..., read_time=..., doc_db=..., write_batch=write_batch@entry=0x367f28c0,
    init_marker_behavior=yb::docdb::InitMarkerBehavior::kOptional, monotonic_counter=0x148d5340, restart_read_ht=0xe4c1438, table_name=...) at ../../src/yb/docdb/docdb.cc:319
#6  0x00007f09d8b48cdc in yb::tablet::WriteQuery::DoCompleteExecute (this=this@entry=0xe4c1340) at ../../src/yb/tablet/write_query.cc:560
#7  0x00007f09d8b486fd in yb::tablet::WriteQuery::CompleteExecute (this=this@entry=0xe4c1340) at ../../src/yb/tablet/write_query.cc:536
#8  0x00007f09d8b4899e in yb::tablet::WriteQuery::DoTransactionalConflictsResolved (this=this@entry=0xe4c1340) at ../../src/yb/tablet/write_query.cc:531
#9  0x00007f09d8b487aa in yb::tablet::WriteQuery::TransactionalConflictsResolved (this=this@entry=0xe4c1340) at ../../src/yb/tablet/write_query.cc:511
#10 0x00007f09d8b4ab67 in yb::tablet::WriteQuery::DoExecute()::$_2::operator()(yb::Result<yb::HybridTime> const&) const (this=<optimized out>, result=...)
    at ../../src/yb/tablet/write_query.cc:495
#11 boost::detail::function::void_function_obj_invoker1<yb::tablet::WriteQuery::DoExecute()::$_2, void, yb::Result<yb::HybridTime> const&>::invoke(boost::detail::function::function_buffer&, yb::Result<yb::HybridTime> const&) (function_obj_ptr=..., a0=...)
    at /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20220505181632-c1907426fc-almalinux8-x86_64-clang12-linuxbrew/installed/uninstrumented/include/boost/function/function_template.hpp:158
#12 0x00007f09d86bb1af in boost::function1<void, yb::Result<yb::HybridTime> const&>::operator() (this=<optimized out>, a0=...)
    at /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20220505181632-c1907426fc-almalinux8-x86_64-clang12-linuxbrew/installed/uninstrumented/include/boost/function/function_template.hpp:763
#13 yb::docdb::(anonymous namespace)::ConflictResolver::InvokeCallback (this=<optimized out>, this@entry=0xc6c3338, result=...) at ../../src/yb/docdb/conflict_resolution.cc:310
#14 0x00007f09d86b9d28 in yb::docdb::(anonymous namespace)::ConflictResolver::ResolveConflicts (this=0xc6c3338) at ../../src/yb/docdb/conflict_resolution.cc:336
#15 yb::docdb::(anonymous namespace)::ConflictResolver::Resolve (this=<optimized out>, this@entry=0xc6c3338) at ../../src/yb/docdb/conflict_resolution.cc:191
#16 0x00007f09d86b9076 in yb::docdb::ResolveTransactionConflicts(std::__1::vector<std::__1::unique_ptr<yb::docdb::DocOperation, std::__1::default_delete<yb::docdb::DocOperation> >, std::__1::allocator<std::__1::unique_ptr<yb::docdb::DocOperation, std::__1::default_delete<yb::docdb::DocOperation> > > > const&, yb::docdb::KeyValueWriteBatchPB const&, yb::HybridTime, yb::HybridTime, yb::docdb::DocDB const&, yb::StronglyTypedBool<yb::docdb::PartialRangeKeyIntents_Tag>, yb::TransactionStatusManager*, yb::Counter*, boost::function<void (yb::Result<yb::HybridTime> const&)>) (doc_ops=..., write_batch=..., hybrid_time=..., read_time=..., doc_db=..., partial_range_key_intents=..., status_manager=0x1e0a63c0, conflicts_metric=0x24e74d00, callback=...)
    at ../../src/yb/docdb/conflict_resolution.cc:1106
#17 0x00007f09d8b48311 in yb::tablet::WriteQuery::DoExecute (this=<optimized out>, this@entry=0xe4c1340) at ../../src/yb/tablet/write_query.cc:484
#18 0x00007f09d8b47866 in yb::tablet::WriteQuery::Execute (query=...) at ../../src/yb/tablet/write_query.cc:408
#19 0x00007f09d8a4e841 in yb::tablet::Tablet::AcquireLocksAndPerformDocOperations (this=<optimized out>, query=...) at ../../src/yb/tablet/tablet.cc:1702
#20 0x00007f09d8a9fc9a in yb::tablet::TabletPeer::WriteAsync (this=0x87fdb80, query=...) at ../../src/yb/tablet/tablet_peer.cc:653
#21 0x00007f09d8d8d61d in yb::tserver::TabletServiceImpl::Write (this=<optimized out>, req=<optimized out>, resp=<optimized out>, context=...)
    at ../../src/yb/tserver/tablet_service.cc:1763
#22 0x00007f09d7206278 in yb::tserver::TabletServerServiceIf::InitMethods(scoped_refptr<yb::MetricEntity> const&)::$_0::operator()(std::__1::shared_ptr<yb::rpc::InboundCall>) const::{lambda(yb::tserver::WriteRequestPB const*, yb::tserver::WriteResponsePB*, yb::rpc::RpcContext)#1}::operator()(yb::tserver::WriteRequestPB const*, yb::tserver::WriteResponsePB*, yb::rpc::RpcContext) const (this=<optimized out>, req=0x25d26fa0, resp=0x25d27060, rpc_context=...) at src/yb/tserver/tserver_service.service.cc:488
#23 yb::rpc::HandleCall<yb::rpc::RpcCallPBParamsImpl<yb::tserver::WriteRequestPB, yb::tserver::WriteResponsePB>, yb::tserver::TabletServerServiceIf::InitMethods(scoped_refptr<yb::MetricEntity> const&)::$_0::operator()(std::__1::shared_ptr<yb::rpc::InboundCall>) const::{lambda(yb::tserver::WriteRequestPB const*, yb::tserver::WriteResponsePB*, yb::rpc::RpcContext)#1}>(std::__1::shared_ptr<yb::rpc::InboundCall>, yb::tserver::TabletServerServiceIf::InitMethods(scoped_refptr<yb::MetricEntity> const&)::$_0::operator()(std::__1::shared_ptr<yb::rpc::InboundCall>) const::{lambda(yb::tserver::WriteRequestPB const*, yb::tserver::WriteResponsePB*, yb::rpc::RpcContext)#1}) (call=..., f=...) at ../../src/yb/rpc/local_call.h:117
#24 yb::tserver::TabletServerServiceIf::InitMethods(scoped_refptr<yb::MetricEntity> const&)::$_0::operator()(std::__1::shared_ptr<yb::rpc::InboundCall>) const (this=<optimized out>, call=...) at src/yb/tserver/tserver_service.service.cc:486
#25 std::__1::__invoke<yb::tserver::TabletServerServiceIf::InitMethods(scoped_refptr<yb::MetricEntity> const&)::$_0&, std::__1::shared_ptr<yb::rpc::InboundCall> > (__f=..., __args=...) at /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20220505181632-c1907426fc-almalinux8-x86_64-clang12-linuxbrew/installed/uninstrumented/libcxx/include/c++/v1/type_traits:3694
#26 std::__1::__invoke_void_return_wrapper<void, true>::__call<yb::tserver::TabletServerServiceIf::InitMethods(scoped_refptr<yb::MetricEntity> const&)::$_0&, std::__1::shared_ptr<yb::rpc::InboundCall> >(yb::tserver::TabletServerServiceIf::InitMethods(scoped_refptr<yb::MetricEntity> const&)::$_0&, std::__1::shared_ptr<yb::rpc::InboundCall>&&) (__args=..., __args=...) at /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20220505181632-c1907426fc-almalinux8-x86_64-clang12-linuxbrew/installed/uninstrumented/libcxx/include/c++/v1/__functional_base:348
#27 std::__1::__function::__alloc_func<yb::tserver::TabletServerServiceIf::InitMethods(scoped_refptr<yb::MetricEntity> const&)::$_0, std::__1::allocator<yb::tserver::TabletServerServiceIf::InitMethods(scoped_refptr<yb::MetricEntity> const&)::$_0>, void (std::__1::shared_ptr<yb::rpc::InboundCall>)>::operator()(std::__1::shared_ptr<yb::rpc::InboundCall>&&) (this=<optimized out>, __arg=...) at /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20220505181632-c1907426fc-almalinux8-x86_64-clang12-linuxbrew/installed/uninstrumented/libcxx/include/c++/v1/functional:1558
#28 std::__1::__function::__func<yb::tserver::TabletServerServiceIf::InitMethods(scoped_refptr<yb::MetricEntity> const&)::$_0, std::__1::allocator<yb::tserver::TabletServerServiceIf::InitMethods(scoped_refptr<yb::MetricEntity> const&)::$_0>, void (std::__1::shared_ptr<yb::rpc::InboundCall>)>::operator()(std::__1::shared_ptr<yb::rpc::InboundCall>&&) (this=<optimized out>, __arg=...) at /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20220505181632-c1907426fc-almalinux8-x86_64-clang12-linuxbrew/installed/uninstrumented/libcxx/include/c++/v1/functional:1732
#29 0x00007f09d7205e06 in std::__1::__function::__value_func<void (std::__1::shared_ptr<yb::rpc::InboundCall>)>::operator()(std::__1::shared_ptr<yb::rpc::InboundCall>&&) const (this=<optimized out>, __args=...) at /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20220505181632-c1907426fc-almalinux8-x86_64-clang12-linuxbrew/installed/uninstrumented/libcxx/include/c++/v1/functional:1885
#30 std::__1::function<void (std::__1::shared_ptr<yb::rpc::InboundCall>)>::operator()(std::__1::shared_ptr<yb::rpc::InboundCall>) const (this=<optimized out>, __arg=...) at /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20220505181632-c1907426fc-almalinux8-x86_64-clang12-linuxbrew/installed/uninstrumented/libcxx/include/c++/v1/functional:2560
#31 yb::tserver::TabletServerServiceIf::Handle (this=<optimized out>, call=...) at src/yb/tserver/tserver_service.service.cc:471
#32 0x00007f09d5ca744a in yb::rpc::ServicePoolImpl::Handle (this=0x2422000, incoming=...) at ../../src/yb/rpc/service_pool.cc:270
#33 0x00007f09d5c50fc5 in yb::rpc::InboundCall::InboundCallTask::Run (this=<optimized out>) at ../../src/yb/rpc/inbound_call.cc:237
#34 0x00007f09d5cb33d0 in yb::rpc::(anonymous namespace)::Worker::Execute (this=<optimized out>) at ../../src/yb/rpc/thread_pool.cc:104
#35 0x00007f09d58eb551 in std::__1::__function::__value_func<void ()>::operator()() const (this=0xe7556d0) at /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20220505181632-c1907426fc-almalinux8-x86_64-clang12-linuxbrew/installed/uninstrumented/libcxx/include/c++/v1/functional:1885
#36 std::__1::function<void ()>::operator()() const (this=0xe7556d0) at /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20220505181632-c1907426fc-almalinux8-x86_64-clang12-linuxbrew/installed/uninstrumented/libcxx/include/c++/v1/functional:2560
#37 yb::Thread::SuperviseThread (arg=0xe755680) at ../../src/yb/util/thread.cc:774
#38 0x00007f09d3d0e694 in start_thread (arg=0x7f0628e62700) at pthread_create.c:333
#39 0x00007f09d3a4f41d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```
Can't connect to server anymore afterwards:
```
[dfelsing@dev-server-dfelsing yugabyte-db]$ bin/ysqlsh
ysqlsh: could not connect to server: Connection refused
	Is the server running on host "localhost" (::1) and accepting
	TCP/IP connections on port 5433?
could not connect to server: Connection refused
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 5433?
```

**Comment by def-** [comment]
Happened again on 226465305d7db859424e06178723b445b6bf964c, can't connect via ysqlsh afterwards.

**Comment by def-** [comment]
Trying to reproduce with the potential fix, haven't seen this failure happen anymore since then, but will check again on Monday.

**Comment by def-** [comment]
Seems to be fixed (or happening more rarely) with D18056. Didn’t get the crash over the weekend and on Monday.

**Comment by bmatican** [comment]
Closing, as per your last comment @def-
