### ISSUE TITLE
[YSQL][LST] Master FATAL: Failed to load sys catalog: Already present (yb/master/ysql_tablegroup_manager.cc:80): Failed while visiting tablets in sys catalog: Tablegroup ... already exists

### ISSUE THREAD

**Issue by def-** [yugabyte/yugabyte-db#13132]
Jira Link: [DB-2836](https://yugabyte.atlassian.net/browse/DB-2836)
### Description

```
$ cd ~/code/yugabyte-db
$ git checkout 226465305d7db859424e06178723b445b6bf964c
$ ./yb_build.sh release
$ bin/yb-ctl --replication_factor 3 create --tserver_flags=yb_enable_read_committed_isolation=true,ysql_enable_packed_row=true,ysql_num_shards_per_tserver=1,enable_stream_compression=true,stream_compression_algo=1,yb_num_shards_per_tserver=1 --master_flags=yb_enable_read_committed_isolation=true,ysql_enable_packed_row=true,enable_stream_compression=true,stream_compression_algo=1,enable_automatic_tablet_splitting=true,tablet_split_low_phase_shard_count_per_node=40,tablet_split_high_phase_shard_count_per_node=50
$ cd ~/code/yb-long-system-test
$ git checkout e78e1e69c8ca04d8019d54703f1fe70ab75ca3e5
$ ./long_system_test.py --nodes=127.0.0.1:5433,127.0.0.2:5433,127.0.0.3:5433 --threads=10 --complexity=full --runtime=60 --max-columns=10 --seed=911292
2022-07-01 10:28:29,630 MainThread INFO     Reproduce with: git checkout e78e1e69 && ./long_system_test.py --nodes=127.0.0.1:5433,127.0.0.2:5433,127.0.0.3:5433 --threads=10 --complexity=full --runtime=60 --max-columns=10 --seed=911292
2022-07-01 10:28:30,098 MainThread INFO     Database version: PostgreSQL 11.2-YB-2.15.1.0-b0 on x86_64-pc-linux-gnu, compiled by clang version 12.0.1 (https://github.com/yugabyte/llvm-project.git bdb147e675d8c87cee72cc1f87c4b82855977d94), 64-bit
2022-07-01 10:28:30,101 MainThread INFO     Creating tables for database db_lst_911292
2022-07-01 10:28:57,017 MainThread INFO     Starting worker_0: CreateIndexAction, DropIndexAction, SetConfigAction, AddColumnAction
2022-07-01 10:28:57,019 MainThread INFO     Starting worker_1: SingleInsertAction, SingleUpdateAction, SingleDeleteAction, BulkInsertAction, BulkUpdateAction, SetConfigAction
2022-07-01 10:28:57,020 MainThread INFO     Starting worker_2: RandomSelectAction, SetConfigAction
2022-07-01 10:28:57,021 MainThread INFO     Starting worker_3: CreateIndexAction, DropIndexAction, SetConfigAction, AddColumnAction
2022-07-01 10:28:57,022 MainThread INFO     Starting worker_4: SingleInsertAction, SingleUpdateAction, SingleDeleteAction, BulkInsertAction, BulkUpdateAction, SetConfigAction
2022-07-01 10:28:57,026 MainThread INFO     Starting worker_5: RandomSelectAction, SetConfigAction
2022-07-01 10:28:57,028 MainThread INFO     Starting worker_6: RandomSelectAction, SetConfigAction
2022-07-01 10:28:57,031 MainThread INFO     Starting worker_7: RandomSelectAction, SetConfigAction
2022-07-01 10:28:57,031 MainThread INFO     Starting worker_8: RandomSelectAction, SetConfigAction
2022-07-01 10:28:57,035 MainThread INFO     Starting worker_9: SingleInsertAction, SingleUpdateAction, SingleDeleteAction, BulkInsertAction, BulkUpdateAction, SetConfigAction
2022-07-01 10:29:07,046 MainThread INFO     Worker queries/s: [001.4][004.9][001.3][001.7][004.7][002.3][001.8][002.1][001.4][003.5]
[...]
2022-07-01 11:03:29,358 MainThread INFO     Worker queries/s: [000.0][000.0][021.6][000.0][000.0][021.6][017.9][021.3][015.5][000.0]
2022-07-01 11:03:38,451 worker_0   ERROR    Unexpected query failure: InternalError_
Query: CREATE INDEX NONCONCURRENTLY idx_t4_c22_boolean_c25_float4_c27_bigint_c9_int_c41_numeric_c11_int_c32_numeric_c10_boolean_c20_numeric_c40_float4_c13_int ON t4 USING lsm (c22_boolean HASH NULLS FIRST, c25_float4 ASC NULLS FIRST, c27_bigint DESC NULLS LAST, c9_int ASC NULLS LAST, c41_numeric ASC NULLS FIRST, c11_int ASC NULLS LAST, c32_numeric DESC NULLS LAST, c10_boolean DESC NULLS LAST, c20_numeric DESC NULLS FIRST, c40_float4 DESC NULLS FIRST, c13_int DESC NULLS LAST) SPLIT INTO 53 TABLETS WHERE FALSE;
  values: None
  runtime: 2022-07-01 11:02:38.341 - 2022-07-01 11:03:38.451
  supports explain: False
  supports rollback: False
  affected rows: None
Action: CreateIndexAction
Error class: InternalError_
Error code: XX000
Error message: ERROR:  Timed out: Timed out waiting for Create Table
    @           0x997398  errmsg
    @           0x9c2968  HandleYBStatusAtErrorLevel
    @           0x6a1615  YBCCreateIndex
    @           0x575043  index_create
    @           0x640dbe  DefineIndex
    @           0x845b26  ProcessUtilitySlow
    @           0x844048  standard_ProcessUtility
    @           0x84361e  YBProcessUtilityDefaultHook
    @     0x7fa00c247dd0  pgss_ProcessUtility
    @     0x7fa00c23eab7  ybpgm_ProcessUtility
    @     0x7fa00c22353e  pg_hint_plan_ProcessUtility
    @           0x9c59c7  YBTxnDdlProcessUtility
    @           0x84326a  PortalRunUtility
    @           0x842927  PortalRunMulti
    @           0x8420c6  PortalRun
    @           0x83f8c6  yb_exec_simple_query_impl
    @           0x83fe66  yb_exec_query_wrapper_one_attempt
    @           0x83cee8  PostgresMain
    @           0x7acffc  BackendRun
    @           0x7ac450  ServerLoop
    @           0x7a8abb  PostmasterMain
    @           0x7127fd  PostgresServerProcessMain
    @           0x712ca2  main
    @     0x7fa01073f825  __libc_start_main
    @           0x4b8569  _start

    @           0x997398  errmsg
    @           0x83e0cb  YBPrepareCacheRefreshIfNeeded
    @           0x83cc20  PostgresMain
    @           0x7acffc  BackendRun
    @           0x7ac450  ServerLoop
    @           0x7a8abb  PostmasterMain
    @           0x7127fd  PostgresServerProcessMain
    @           0x712ca2  main
    @     0x7fa01073f825  __libc_start_main
    @           0x4b8569  _start

CONTEXT:  Catalog Version Mismatch: A DDL occurred while processing this query. Try again.
Transaction isolation level: default
DB Node: host: 127.0.0.1, port: 5433
DB Backend PID: 3755491
```
After this failure all the next runs failed to create tablegroups:
```
2022-07-01 12:22:10,923 MainThread INFO     Reproduce with: git checkout e78e1e69 && ./long_system_test.py --nodes=127.0.0.1:5433,127.0.0.2:5433,127.0.0.3:5433 --threads=10 --complexity=full --runtime=60 --max-columns=10 --seed=228368
2022-07-01 12:22:11,140 MainThread INFO     Database version: PostgreSQL 11.2-YB-2.15.1.0-b0 on x86_64-pc-linux-gnu, compiled by clang version 12.0.1 (https://github.com/yugabyte/llvm-project.git bdb147e675d8c87cee72cc1f87c4b82855977d94), 64-bit
2022-07-01 12:22:11,142 MainThread INFO     Creating tables for database db_lst_228368
Traceback (most recent call last):
  File "/home/deen/code/yb-long-system-test/./long_system_test.py", line 279, in <module>
    main()
  File "/home/deen/code/yb-long-system-test/./long_system_test.py", line 270, in main
    lst.run()
  File "/home/deen/code/yb-long-system-test/./long_system_test.py", line 203, in run
    self._create_tables()
  File "/home/deen/code/yb-long-system-test/./long_system_test.py", line 184, in _create_tables
    self.database.create_relations(cur)
  File "/home/deen/code/yb-long-system-test/lst/dbobject.py", line 228, in create_relations
    tablegroup.create(cur)
  File "/home/deen/code/yb-long-system-test/lst/dbobject.py", line 163, in create
    self.execute(cur, query)
  File "/home/deen/code/yb-long-system-test/lst/dbobject.py", line 24, in execute
    raise e
  File "/home/deen/code/yb-long-system-test/lst/dbobject.py", line 17, in execute
    cur.execute(query)
psycopg2.errors.InternalError_: Timed out: Timed out waiting for Create Tablegroup
```
Then this FATAL in yb-master happened:
```
[deen@devp ~]$ cat yugabyte-data/node-2/disk-1/yb-data/master/logs/yb-master.FATAL.details.2022-07-01T10_25_23.pid3753862.txt
F20220701 10:25:23 ../../../../../src/yb/master/catalog_manager.cc:993] T 00000000000000000000000000000000 P c1a9de06b1fe41d3860a7a92a065bb4c: Failed to load sys catalog: Already present (yb/master/ysql_tablegroup_manager.cc:80): Failed while visiting tablets in sys catalog: Tablegroup 0000484c000030008000000000004861 already exists
    @     0x7fd63fbb851c  google::LogDestination::LogToSinks()
    @     0x7fd63fbb2c4f  google::LogMessage::SendToLog()
    @     0x7fd63fbb3558  google::LogMessage::Flush()
    @     0x7fd63fbb5e5f  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fd6430c4349  yb::master::CatalogManager::LoadSysCatalogDataTask()
    @     0x7fd63fe9c48a  yb::ThreadPool::DispatchThread()
    @     0x7fd63fe90871  yb::Thread::SuperviseThread()
    @     0x7fd63e270694  start_thread
    @     0x7fd63dfb241d  __clone
```
I have only seen this failure with RF3, not RF1. Afterwards the connection via ysqlsh simply hangs, can't open new sessions:
```
2022-07-01 12:26:03,341 MainThread INFO     Reproduce with: git checkout e78e1e69 && ./long_system_test.py --nodes=127.0.0.1:5433,127.0.0.2:5433,127.0.0.3:5433 --threads=10 --complexity=full --runtime=60 --max-columns=10 --seed=485365
Traceback (most recent call last):
  File "/home/deen/code/yb-long-system-test/./long_system_test.py", line 279, in <module>
    main()
  File "/home/deen/code/yb-long-system-test/./long_system_test.py", line 270, in main
    lst.run()
  File "/home/deen/code/yb-long-system-test/./long_system_test.py", line 203, in run
    self._create_tables()
  File "/home/deen/code/yb-long-system-test/./long_system_test.py", line 166, in _create_tables
    conn = psycopg2.connect(**self._get_connect_opts())
  File "/usr/lib64/python3.9/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: timeout expired
```
[yb-master.devp.deen.log.INFO.20220701-082817.3753862.zip](https://github.com/yugabyte/yugabyte-db/files/9029030/yb-master.devp.deen.log.INFO.20220701-082817.3753862.zip)
I have kept yugabyte-data directory around in case it helps:
```
-rw-rw-r--. 1 deen deen 536M Jul  1 15:15 yugabyte-data-13132.tar.gz
```
Please excuse the confusing times, the times printed by LST are in UTC+2, while yugabyte-db logs are in UTC. I'll change the for future runs so everything is UTC.

**Comment by def-** [comment]
I am commonly seeing the `psycopg2.errors.InternalError_: Timed out: Timed out waiting for Create Tablegroup` failure with LST, seems like the database goes into a bad state and new tablegroups can't be created anymore:
```
I0705 13:15:48.727064 30967168 pggate.cc:149] InitTServerSharedObject: 0, 0, 4
W0705 13:15:48.727185 30967168 hybrid_clock.cc:133] HybridClock initialized in local mode (OS X only). Not
 suitable for distributed clusters.
I0705 13:15:48.727262 30967168 pg_client.cc:125] Using TServer host_port: 127.0.0.1:9100
I0705 13:15:48.727843 30967168 pg_client.cc:132] S 75: Session id acquired
2022-07-05 13:15:48.738 CEST [74555] LOG:  unable to find pgstat entry for abnormally terminated PID 79074
2022-07-05 13:15:49.056 CEST [79096] WARNING:  'tablegroup' is a beta feature! at character 1
2022-07-05 13:15:49.056 CEST [79096] HINT:  To suppress this warning, set the 'ysql_beta_feature_tablegrou
p' yb-tserver gflag to true.
        (Set 'ysql_beta_features' yb-tserver gflag to true to suppress the warning for all beta features.)
2022-07-05 13:15:49.056 CEST [79096] WARNING:  'tablegroup' is a beta feature! at character 1
2022-07-05 13:15:49.056 CEST [79096] HINT:  To suppress this warning, set the 'ysql_beta_feature_tablegrou
p' yb-tserver gflag to true.
        (Set 'ysql_beta_features' yb-tserver gflag to true to suppress the warning for all beta features.)
2022-07-05 13:15:49.099 CEST [79096] WARNING:  'tablegroup' is a beta feature! at character 1
2022-07-05 13:15:49.099 CEST [79096] HINT:  To suppress this warning, set the 'ysql_beta_feature_tablegrou
p' yb-tserver gflag to true.
        (Set 'ysql_beta_features' yb-tserver gflag to true to suppress the warning for all beta features.)
2022-07-05 13:15:49.099 CEST [79096] WARNING:  'tablegroup' is a beta feature! at character 1
2022-07-05 13:15:49.099 CEST [79096] HINT:  To suppress this warning, set the 'ysql_beta_feature_tablegrou
p' yb-tserver gflag to true.
        (Set 'ysql_beta_features' yb-tserver gflag to true to suppress the warning for all beta features.)
2022-07-05 13:17:49.111 CEST [79096] ERROR:  Timed out: Timed out waiting for Create Tablegroup
2022-07-05 13:17:49.111 CEST [79096] STATEMENT:  CREATE TABLEGROUP tg1;
I0705 13:17:49.117067 1863086080 poller.cc:66] Poll stopped: Service unavailable (yb/rpc/scheduler.cc:80): Scheduler is shutting down (system error 58)
2022-07-05 13:17:49.131 CEST [74555] LOG:  unable to find pgstat entry for abnormally terminated PID 79096
I0705 13:17:49.294610 30967168 mem_tracker.cc:299] MemTracker: hard memory limit is 10.400000 GB
I0705 13:17:49.294703 30967168 mem_tracker.cc:301] MemTracker: soft memory limit is 8.840000 GB
I0705 13:17:49.295032 30967168 thread_pool.cc:170] Starting thread pool { name: pggate_ybclient queue_limit: 10000 max_workers: 1024 }
```
and so on, postgresql logs.

**Comment by def-** [comment]
Also happens without packed columns

**Comment by yifanguan** [comment]
@def- Is the postgres log according to your first comment in ticket still available? I wanna to take a look at the executed sql statements.

**Comment by def-** [comment]
https://drive.google.com/file/d/1tNKzjQgha-7_ksOY1YU43WzyyZtPhXmu/view?usp=sharing
Accessible from inside Yugabyte

**Comment by def-** [comment]
Still happening on a166e5a6e87d1a9b9e72406e26a8d927933e6ea0

**Comment by qvad** [comment]
Reproduced in SQLancer tests 
```
F0816 05:00:58.459318  9626 catalog_manager.cc:1008] T 00000000000000000000000000000000 P c9241763d352495c8cc199b7ebb7e9de: Failed to load sys catalog: Already present (yb/master/ysql_tablegroup_manager.cc:80): Failed while visiting tablets in sys catalog: Tablegroup 00004e2f000030008000000000005103 already exists
```

**Comment by yifanguan** [comment]
@qvad from your tests, is there any quick repro for this issue? Thanks!

**Comment by yifanguan** [comment]
@def- @qvad Did you ever run a same test, but with `enable_automatic_tablet_splitting = false`? If you did, did you observe the same error? Thanks!

**Comment by def-** [comment]
I'm not sure, mostly ran with tablet splitting enabled.

**Comment by def-** [comment]
There now appears to be some additional text when this fails:
```
F20220907 05:13:51 ../../src/yb/master/catalog_manager.cc:1016] T 00000000000000000000000000000000 P 2037b70d05d14cb2853da9d467cef5d8: Failed to load sys catalog: Already present (yb/master/ysql_tablegroup_manager.cc:80): Failed while visiting tablets in sys catalog: System catalog snapshot is corrupted or built using different build type: Tablegroup 00006ad3000030008000000000006aed already exists
    @     0x7f4107fd66ab  google::LogMessage::SendToLog()
    @     0x7f4107fd70ce  google::LogMessage::Flush()
    @     0x7f4107fd985f  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f410b6b16b8  yb::master::CatalogManager::LoadSysCatalogDataTask()
    @     0x7f41082dd07e  yb::ThreadPool::DispatchThread()
    @     0x7f41082d15d7  yb::Thread::SuperviseThread()
    @     0x7f41068bd694  start_thread
    @     0x7f41065fe41d  __clone
```
See also https://github.com/yugabyte/yugabyte-db/issues/13810

**Comment by frozenspider** [comment]
So far I couldn't repro this after a bunch of attempts using LST.
Also, as reported by @qvad, this looks to be the same error as #13810.

**Comment by frozenspider** [comment]
I think I was able to repro another symptom of the same issue.
Here's a code that eliminates OID assignment randomness:
```sql
CREATE TABLEGROUP tg1;

SET yb_test_fail_next_ddl TO true;
CREATE TABLEGROUP tg2; -- this one fails, as requested

SET yb_binary_restore TO true;
SELECT oid, binary_upgrade_set_next_tablegroup_oid(oid::int + 1) FROM pg_yb_tablegroup WHERE grpname = 'tg1';
CREATE TABLEGROUP tg3;
```
Due to DCHECK, this crashes the master in debug build, and probably leads to the original symptoms in the release build.
