### ISSUE TITLE
[DocDB] org.yb.cql.TestUserDefinedTypes because EXPLAIN does not use an index scan

### ISSUE THREAD

**Issue by mbautin** [yugabyte/yugabyte-db#13224]
### Description

```
[INFO] Running org.yb.cql.TestUserDefinedTypes
[ERROR] Tests run: 2, Failures: 1, Errors: 1, Skipped: 0, Time elapsed: 18.193 s <<< FAILURE! - in org.yb.cql.TestUserDefinedTypes
[ERROR] testNestedUDTs(org.yb.cql.TestUserDefinedTypes)  Time elapsed: 17.634 s  <<< FAILURE!
java.lang.AssertionError: Should use index scan. Query: EXPLAIN SELECT * FROM test_nested_udts_pk WHERE r = {i:1,u3:{i:1,u2:{i:1,u1:{i:1,t:'b'}}}}. Result: [Row[Seq Scan on cql_test_keyspace.test_nested_udts_pk], Row[  Filter: (r = expr)                             ]]
        at org.yb.cql.TestUserDefinedTypes.testNestedUDTs(TestUserDefinedTypes.java:629)

```

**Comment by mbautin** [comment]
The context around when the assertion failed:
```
ts3|pid2050926|:13701|http://127.67.208.182:25656 I0709 06:31:08.576855 2051128 thread_pool.cc:170] Starting thread pool { name: TransactionManager queue_limit: 500 max_workers: 50 }
ts2|pid2050848|:31847|http://127.56.250.84:26468 W0709 06:31:08.578497 2052228 mvcc.cc:433] T {transactions_tablet_id1} P {ts2_peer_id}: Received propagated safe time { physical: 1657348268556346 } less than the old value: { physical: 1657348268571876 logical: 4095 }. This could happen on followers when a new leader is elected.
ts3|pid2050926|:13701|http://127.67.208.182:25656 I0709 06:31:08.580590 2051536 tablet.cc:2104] Using grace margin of 1000ms, original deadline: 29.792s
ts3|pid2050926|:13701|http://127.67.208.182:25656 I0709 06:31:08.580667 2051536 tablet.cc:2419] Done BackfillIndexes at { physical: 1657348268361882 } for [36ec4992e55047599dc8575c1f2c06ea] until <end of the tablet>
m1|pid2050374|:13424|http://127.75.77.244:15995 I0709 06:31:08.582592 2052206 backfill_index.cc:1257] Done backfilling the tablet 0x000000000a2d8280 -> {test_nested_udts_pk_tablet_id7} (table test_nested_udts_pk [id=922c5444989445e2a967595e538c9008])
ts2|pid2050848|:31847|http://127.56.250.84:26468 I0709 06:31:08.601950 2051508 thread_pool.cc:170] Starting thread pool { name: TransactionManager queue_limit: 500 max_workers: 50 }
ts2|pid2050848|:31847|http://127.56.250.84:26468 I0709 06:31:08.689913 2051412 pt_expr.h:206] Missing QLName for expression(14) that is being selected
06:31:08.691 (Time-limited test) [ERROR - org.yb.AssertionWrappers.logError(AssertionWrappers.java:40)] Assertion error:
java.lang.AssertionError: Should use index scan. Query: EXPLAIN SELECT * FROM test_nested_udts_pk WHERE r = {i:1,u3:{i:1,u2:{i:1,u1:{i:1,t:'b'}}}}. Result: [Row[Seq Scan on cql_test_keyspace.test_nested_udts_pk], Row[  Filter: (r = expr)                             ]]
	at org.junit.Assert.fail(Assert.java:88)
	at org.yb.AssertionWrappers.lambda$fail$4(AssertionWrappers.java:104)
	at org.yb.AssertionWrappers.wrapAssertion(AssertionWrappers.java:45)
	at org.yb.AssertionWrappers.fail(AssertionWrappers.java:104)
	at org.yb.cql.TestUserDefinedTypes.testNestedUDTs(TestUserDefinedTypes.java:629)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
06:31:08.691 (Time-limited test) [INFO - org.yb.cql.BaseCQLTest.tearDownAfter(BaseCQLTest.j
```
It looks like backfill was still in progress at that time.
