### ISSUE TITLE
[DocDB] UBSAN issue in GetYsqlTablespaceInfo

### ISSUE THREAD

**Issue by mbautin** [yugabyte/yugabyte-db#13239]
Jira Link: [DB-2895](https://yugabyte.atlassian.net/browse/DB-2895)
### Description

./yb_build.sh asan --cxx-test tools_yb-admin-snapshot-schedule-test --gtest_filter PITRFlags/YbAdminSnapshotScheduleTestWithYsqlColocatedParam.PgsqlCreateTable/0

```
[m-1]     #0 0x7fe15d39dcab in yb::master::CatalogManager::GetYsqlTablespaceInfo() ${BUILD_ROOT}/../../src/yb/master/catalog_manager.cc:2040:31
[m-1]     #1 0x7fe15d3a2373 in yb::master::CatalogManager::DoRefreshTablespaceInfo() ${BUILD_ROOT}/../../src/yb/master/catalog_manager.cc:2327:26
[m-1]     #2 0x7fe15d3a1ef1 in yb::master::CatalogManager::RefreshTablespaceInfoPeriodically() ${BUILD_ROOT}/../../src/yb/master/catalog_manager.cc:2314:14
[m-1]     #3 0x7fe15d5219cb in decltype(*(std::__1::forward<yb::master::CatalogManager*&>(fp0)).*fp()) std::__1::__invoke<void (yb::master::CatalogManager::*&)(), yb::master::CatalogManager*&, void>(void (yb::master::CatalogManager::*&)(), yb::master::CatalogManager*&) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20220630123436-af96d73e39-almalinux8-x86_64-clang12/installed/asan/libcxx/include/c++/v1/type_traits:3635:1
[m-1]     #4 0x7fe15d521942 in std::__1::__bind_return<void (yb::master::CatalogManager::*)(), std::__1::tuple<yb::master::CatalogManager*>, std::__1::tuple<>, __is_valid_bind_return<void (yb::master::CatalogManager::*)(), std::__1::tuple<yb::master::CatalogManager*>, std::__1::tuple<> >::value>::type std::__1::__apply_functor<void (yb::master::CatalogManager::*)(), std::__1::tuple<yb::master::CatalogManager*>, 0ul, std::__1::tuple<> >(void (yb::master::CatalogManager::*&)(), std::__1::tuple<yb::master::CatalogManager*>&, std::__1::__tuple_indices<0ul>, std::__1::tuple<>&&) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20220630123436-af96d73e39-almalinux8-x86_64-clang12/installed/asan/libcxx/include/c++/v1/functional:2857:12
[m-1]     #5 0x7fe15d5218c3 in std::__1::__bind_return<void (yb::master::CatalogManager::*)(), std::__1::tuple<yb::master::CatalogManager*>, std::__1::tuple<>, __is_valid_bind_return<void (yb::master::CatalogManager::*)(), std::__1::tuple<yb::master::CatalogManager*>, std::__1::tuple<> >::value>::type std::__1::__bind<void (yb::master::CatalogManager::*)(), yb::master::CatalogManager*>::operator()<>() /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20220630123436-af96d73e39-almalinux8-x86_64-clang12/installed/asan/libcxx/include/c++/v1/functional:2890:20
[m-1]     #6 0x7fe15d5217fc in yb::RunnableImpl<std::__1::__bind<void (yb::master::CatalogManager::*)(), yb::master::CatalogManager*> >::Run() ${BUILD_ROOT}/../../src/yb/util/threadpool.h:79:5
[m-1]     #7 0x7fe141b9a199 in yb::ThreadPool::DispatchThread(bool) ${BUILD_ROOT}/../../src/yb/util/threadpool.cc:611:22
[m-1]     #8 0x7fe141bc0378 in decltype(*(std::__1::forward<yb::ThreadPool*&>(fp0)).*fp(std::__1::forward<bool&>(fp1))) std::__1::__invoke<void (yb::ThreadPool::*&)(bool), yb::ThreadPool*&, bool&, void>(void (yb::ThreadPool::*&)(bool), yb::ThreadPool*&, bool&) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20220630123436-af96d73e39-almalinux8-x86_64-clang12/installed/asan/libcxx/include/c++/v1/type_traits:3635:1
[m-1]     #9 0x7fe141bc02b2 in std::__1::__bind_return<void (yb::ThreadPool::*)(bool), std::__1::tuple<yb::ThreadPool*, bool>, std::__1::tuple<>, __is_valid_bind_return<void (yb::ThreadPool::*)(bool), std::__1::tuple<yb::ThreadPool*, bool>, std::__1::tuple<> >::value>::type std::__1::__apply_functor<void (yb::ThreadPool::*)(bool), std::__1::tuple<yb::ThreadPool*, bool>, 0ul, 1ul, std::__1::tuple<> >(void (yb::ThreadPool::*&)(bool), std::__1::tuple<yb::ThreadPool*, bool>&, std::__1::__tuple_indices<0ul, 1ul>, std::__1::tuple<>&&) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20220630123436-af96d73e39-almalinux8-x86_64-clang12/installed/asan/libcxx/include/c++/v1/functional:2857:12
[m-1]     #10 0x7fe141bc0213 in std::__1::__bind_return<void (yb::ThreadPool::*)(bool), std::__1::tuple<yb::ThreadPool*, bool>, std::__1::tuple<>, __is_valid_bind_return<void (yb::ThreadPool::*)(bool), std::__1::tuple<yb::ThreadPool*, bool>, std::__1::tuple<> >::value>::type std::__1::__bind<void (yb::ThreadPool::* const&)(bool), yb::ThreadPool* const&, bool const&>::operator()<>() /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20220630123436-af96d73e39-almalinux8-x86_64-clang12/installed/asan/libcxx/include/c++/v1/functional:2890:20
[m-1]     #11 0x7fe141bc0148 in decltype(std::__1::forward<std::__1::__bind<void (yb::ThreadPool::* const&)(bool), yb::ThreadPool* const&, bool const&>&>(fp)()) std::__1::__invoke<std::__1::__bind<void (yb::ThreadPool::* const&)(bool), yb::ThreadPool* const&, bool const&>&>(std::__1::__bind<void (yb::ThreadPool::* const&)(bool), yb::ThreadPool* const&, bool const&>&) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20220630123436-af96d73e39-almalinux8-x86_64-clang12/installed/asan/libcxx/include/c++/v1/type_traits:3694:1
[m-1]     #12 0x7fe141bc0118 in void std::__1::__invoke_void_return_wrapper<void, true>::__call<std::__1::__bind<void (yb::ThreadPool::* const&)(bool), yb::ThreadPool* const&, bool const&>&>(std::__1::__bind<void (yb::ThreadPool::* const&)(bool), yb::ThreadPool* const&, bool const&>&) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20220630123436-af96d73e39-almalinux8-x86_64-clang12/installed/asan/libcxx/include/c++/v1/__functional_base:348:9
[m-1]     #13 0x7fe141bc00f0 in std::__1::__function::__alloc_func<std::__1::__bind<void (yb::ThreadPool::* const&)(bool), yb::ThreadPool* const&, bool const&>, std::__1::allocator<std::__1::__bind<void (yb::ThreadPool::* const&)(bool), yb::ThreadPool* const&, bool const&> >, void ()>::operator()() /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20220630123436-af96d73e39-almalinux8-x86_64-clang12/installed/asan/libcxx/include/c++/v1/functional:1558:16
[m-1]     #14 0x7fe141bbe92c in std::__1::__function::__func<std::__1::__bind<void (yb::ThreadPool::* const&)(bool), yb::ThreadPool* const&, bool const&>, std::__1::allocator<std::__1::__bind<void (yb::ThreadPool::* const&)(bool), yb::ThreadPool* const&, bool const&> >, void ()>::operator()() /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20220630123436-af96d73e39-almalinux8-x86_64-clang12/installed/asan/libcxx/include/c++/v1/functional:1732:12
[m-1]     #15 0x7fe15da80f08 in std::__1::__function::__value_func<void ()>::operator()() const /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20220630123436-af96d73e39-almalinux8-x86_64-clang12/installed/asan/libcxx/include/c++/v1/functional:1885:16
[m-1]     #16 0x7fe15da679d8 in std::__1::function<void ()>::operator()() const /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20220630123436-af96d73e39-almalinux8-x86_64-clang12/installed/asan/libcxx/include/c++/v1/functional:2560:12
[m-1]     #17 0x7fe141b6c22b in yb::Thread::SuperviseThread(void*) ${BUILD_ROOT}/../../src/yb/util/thread.cc:774:3
[m-1]     #18 0x7fe13b27d1ce in start_thread (/lib64/libpthread.so.0+0x81ce)
[m-1]     #19 0x7fe13aee9d82 in clone (/lib64/libc.so.6+0x39d82)
[m-1] SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior ../../src/yb/master/catalog_manager.cc:2040:31 in
```

**Comment by bmatican** [comment]
@hari90 is this something that might get addressed by your https://phabricator.dev.yugabyte.com/D17894 ?

**Comment by hari90** [comment]
Yup this is a dupe of #13032

**Comment by hari90** [comment]
Duplicate of #13032
