### ISSUE TITLE
[YCQL] Performance degradation in CassandraDataLoad workload leads to operations unavailability

### ISSUE THREAD

**Issue by qvad** [yugabyte/yugabyte-db#13316]
Jira Link: [DB-2952](https://yugabyte.atlassian.net/browse/DB-2952)
### Description

Running CassandraDataLoad (see attachments) against 3RF 3 node cluster. 
Eventually read operation throughput grows up to 10 seconds and all connections eventually became failed.

Start workload client log:
```
20157 [Thread-0] INFO com.yugabyte.sample.common.metrics.MetricsTracker  - Read: 72.18 ops/sec (66.59 ms/op), 361 total ops  |  Write: 495.23 ops/sec (10.09 ms/op), 2545 total ops  |  Uptime: 20034 ms | 
25158 [Thread-0] INFO com.yugabyte.sample.common.metrics.MetricsTracker  - Read: 22.40 ops/sec (220.97 ms/op), 473 total ops  |  Write: 445.35 ops/sec (11.22 ms/op), 4772 total ops  |  Uptime: 25035 ms | 
30158 [Thread-0] INFO com.yugabyte.sample.common.metrics.MetricsTracker  - Read: 12.40 ops/sec (384.13 ms/op), 535 total ops  |  Write: 444.55 ops/sec (11.24 ms/op), 6995 total ops  |  Uptime: 30035 ms | 
35159 [Thread-0] INFO com.yugabyte.sample.common.metrics.MetricsTracker  - Read: 10.60 ops/sec (459.58 ms/op), 588 total ops  |  Write: 424.76 ops/sec (11.76 ms/op), 9119 total ops  |  Uptime: 35036 ms | 
40159 [Thread-0] INFO com.yugabyte.sample.common.metrics.MetricsTracker  - Read: 8.00 ops/sec (613.73 ms/op), 628 total ops  |  Write: 432.35 ops/sec (11.56 ms/op), 11281 total ops  |  Uptime: 40036 ms | 
45160 [Thread-0] INFO com.yugabyte.sample.common.metrics.MetricsTracker  - Read: 5.60 ops/sec (880.79 ms/op), 656 total ops  |  Write: 438.35 ops/sec (11.41 ms/op), 13473 total ops  |  Uptime: 45037 ms | 
50160 [Thread-0] INFO com.yugabyte.sample.common.metrics.MetricsTracker  - Read: 6.40 ops/sec (774.53 ms/op), 688 total ops  |  Write: 449.35 ops/sec (11.13 ms/op), 15720 total ops  |  Uptime: 50037 ms | 
55161 [Thread-0] INFO com.yugabyte.sample.common.metrics.MetricsTracker  - Read: 4.80 ops/sec (1046.58 ms/op), 712 total ops  |  Write: 457.76 ops/sec (10.91 ms/op), 18009 total ops  |  Uptime: 55038 ms | 
60161 [Thread-0] INFO com.yugabyte.sample.common.metrics.MetricsTracker  - Read: 3.80 ops/sec (1208.05 ms/op), 731 total ops  |  Write: 430.56 ops/sec (11.60 ms/op), 20162 total ops  |  Uptime: 60038 ms | 
65162 [Thread-0] INFO com.yugabyte.sample.common.metrics.MetricsTracker  - Read: 3.80 ops/sec (1414.47 ms/op), 750 total ops  |  Write: 448.75 ops/sec (11.15 ms/op), 22406 total ops  |  Uptime: 65039 ms | 
70162 [Thread-0] INFO com.yugabyte.sample.common.metrics.MetricsTracker  - Read: 2.60 ops/sec (1687.23 ms/op), 763 total ops  |  Write: 434.16 ops/sec (11.52 ms/op), 24577 total ops  |  Uptime: 70039 ms | 
```

End workload log:
```
515204 [Thread-0] INFO com.yugabyte.sample.common.metrics.MetricsTracker  - Read: 0.00 ops/sec (0.00 ms/op), 1253 total ops  |  Write: 421.77 ops/sec (11.89 ms/op), 220915 total ops  |  Uptime: 515081 ms | 
520205 [Thread-0] INFO com.yugabyte.sample.common.metrics.MetricsTracker  - Read: 0.00 ops/sec (0.00 ms/op), 1253 total ops  |  Write: 403.97 ops/sec (12.36 ms/op), 222935 total ops  |  Uptime: 520082 ms | 
525205 [Thread-0] INFO com.yugabyte.sample.common.metrics.MetricsTracker  - Read: 0.20 ops/sec (22960.00 ms/op), 1254 total ops  |  Write: 433.96 ops/sec (11.54 ms/op), 225105 total ops  |  Uptime: 525082 ms | 
com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /172.151.59.83:9042 (com.datastax.driver.core.exceptions.OperationTimedOutException: [/172.151.59.83:9042] Timed out waiting for server response), /172.151.22.200:9042 (com.datastax.driver.core.exceptions.OperationTimedOutException: [/172.151.22.200:9042] Timed out waiting for server response), /172.151.47.103:9042 (com.datastax.driver.core.exceptions.OperationTimedOutException: [/172.151.47.103:9042] Timed out waiting for server response))
...
	at com.yugabyte.sample.apps.CassandraDataLoad.doRead(CassandraDataLoad.java:198)
	at com.yugabyte.sample.apps.AppBase.performRead(AppBase.java:821)
	at com.yugabyte.sample.common.IOPSThread.run(IOPSThread.java:88)
```

![Screenshot 2022-07-15 at 12 44 26](https://user-images.githubusercontent.com/5963536/179198595-0c6ca536-7e22-499d-9045-8a209cf760fc.png)

[Flamegraphs for initial stage and 30 min timeout workloads with client logs](https://github.com/yugabyte/yugabyte-db/files/9119769/Archive.zip)
[Java reproducer](https://github.com/yugabyte/yugabyte-db/files/9119777/yb-sample-apps-1.8.12.jar.zip)

**Comment by qvad** [comment]
Reproduced in 2.8 also

**Comment by rthallamko3** [comment]
5 worker threads, 1 yb-client connection?

**Comment by rthallamko3** [comment]
@qvad , We have improved the performance of writes in 2.14. Can you confirm if this is an issue in master or recent builds? If not, can we close this?

**Comment by qvad** [comment]
No longer reproduced in master branch
