### ISSUE TITLE
Yugaware logs about "Host not in GCP"

### ISSUE THREAD

**Issue by aegershman** [yugabyte/yugabyte-db#1342]
Currently running yugaware on PKS on top of AWS:

When provisioning a new yugabyte universe from the yugaware UI, if you `kubectl logs -f` the logs from the `yugaware-0 -c yugaware` pod/container, there are peculiar log messages about "Host not in GCP" streaming out of it. I really doubt this is a big deal, but figured I'd point it out:

```log
2019-05-09 15:47:39.421 INFO  ShellProcessHandler.java:85 [application-akka.actor.default-dispatcher-32] {"region": "us-west-2", "privateIp": "10.redact.redact.14", "instance-id": "i-asdfasdfasdf", "vpc-id": "vpc-asdfasdf"}
2019-05-09 15:47:39.422 INFO  DevopsBase.java:99 [application-akka.actor.default-dispatcher-32] Command to run: [bin/ybcloud.sh gcp query current-host]
2019-05-09 15:47:40.170 INFO  ShellProcessHandler.java:85 [application-akka.actor.default-dispatcher-32] {"error": "Host not in GCP."}
```

Thanks /cc @ajcaldera1

**Comment by kmuthukk** [comment]
Thx @aegershman - yes the log is harmeless, but should be cleaned up.

**Comment by tylarb** [comment]
Still seeing this issue in 2.4 release. Reopening.

```
[DEBUG] from ShellProcessHandler in application-akka.actor.default-dispatcher-443 - Proc stdout | {"error": "Host not in GCP."}
```

**Comment by vpatibandla-yb** [comment]
This issue is not limited to GCP alone. This occurs for AWS also if the AWS provider is not configured.
```[DEBUG] from ShellProcessHandler in application-akka.actor.default-dispatcher-31 - Proc stdout for 'bin/ybcloud.sh aws query current-host region' | {"error": "Unable to fetch host metadata"}```

**Comment by vpatibandla-yb** [comment]
Closed by: https://github.com/yugabyte/yugabyte-db/commit/7a131e26489b6937eea10da2c5944b72e265af28

**Comment by streddy-yb** [comment]
hi @vpatibandla-yb - Can you back port this to 2.4?

**Comment by SergeyPotachev** [comment]
A related exception appeared on 2.4.2:

2021-04-27 14:55:45,147 [ERROR] from com.yugabyte.yw.common.DevopsBase in application-akka.actor.default-dispatcher-2422 - Traceback (most recent call last):
  File "/opt/yugabyte/devops/python_virtual_env/bin/ybcloud.py", line 4, in <module>
    __import__('pkg_resources').run_script('ybops==0.4', 'ybcloud.py')
  File "/opt/yugabyte/devops/python_virtual_env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/opt/yugabyte/devops/python_virtual_env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1462, in run_script
    exec(code, namespace, namespace)
  File "/opt/yugabyte/devops/python_virtual_env/lib/python2.7/site-packages/ybops-0.4-py2.7.egg/EGG-INFO/scripts/ybcloud.py", line 15, in <module>
    YbCloud().run()
  File "/opt/yugabyte/devops/python_virtual_env/lib/python2.7/site-packages/ybops-0.4-py2.7.egg/ybops/cloud/ybcloud.py", line 56, in run
    self.options.func(self.options)
  File "/opt/yugabyte/devops/python_virtual_env/lib/python2.7/site-packages/ybops-0.4-py2.7.egg/ybops/cloud/common/method.py", line 77, in callback_wrapper
    self.callback(args)
  File "/opt/yugabyte/devops/python_virtual_env/lib/python2.7/site-packages/ybops-0.4-py2.7.egg/ybops/cloud/gcp/method.py", line 146, in callback
    print(json.dumps(self.cloud.get_current_host_info()))
  File "/usr/lib64/python2.7/json/__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib64/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib64/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib64/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: set(['Unable to auto-discover GCP provider information']) is not JSON serializable
