### ISSUE TITLE
[DocDB][LST] B&R: Error running import_snapshot: Invalid argument (yb/master/catalog_manager_ent.cc:2084): Unable to import snapshot meta file /tmp/.../SnapshotInfoPB: YSQL table not found: t0: OBJECT_NOT_FOUND (master error 3)

### ISSUE THREAD

**Issue by def-** [yugabyte/yugabyte-db#13539]
Jira Link: [DB-3123](https://yugabyte.atlassian.net/browse/DB-3123)
### Description

I started testing Backup & Restore with LST today and am seeing an issue where restoring backup timed out after multiple successful backup/restore cycles:
```
RuntimeError: wait_for_task: Timed out getting task state for restore_multitable_backup: {'title': 'Restoring Backup : keySpace', 'createTime': 'Fri Aug 05 16:37:03 UTC 2022', 'target': 'keySpace', 'targetUUID': 'edaf84f8-508e-4fc0-840f-6b91d37ad21c', 'type': 'Restore', 'status': 'Running', 'percent': 0.0, 'details': {'taskDetails': [{'title': 'Restoring Table Backup', 'description': 'Restoring from a backup.', 'state': 'Running'}, {'title': 'Configuring the universe', 'description': 'Creating and populating the universe config, waiting for the various machines to discover one another.', 'state': 'Created'}]}, 'abortable': True, 'retryable': False} 3873.0446882247925s
```
Logs show what happened to cause the timeout, I guess the root cause should be fixed and additionally there should not be a timeout for this error, but an immediate error message instead:
```
YW 2022-08-05T20:08:04.067Z [DEBUG] cf7af8c4-7748-4529-9ca4-fcd87bdee26e from ShellProcessHandler in TaskPool-BackupUniverse(edaf84f8-508e-4fc0-840f-6b91d37ad21c)-0 - 2022-08-05 20:08:03,544 ERROR: Failed to run command [[ ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ControlMaster=auto -o 'ControlPath=~/.ssh/ssh-%r@%h:%p' -o ControlPersist=1m -i /opt/yugabyte/yugaware/data/keys/0a7b8253-c7bb-4684-84c0-8b6cd6b70811/yb-15-my-aws-provider_0a7b8253-c7bb-4684-84c0-8b6cd6b70811-key.pem -p 54422 -q yugabyte@X 'cd / &&  bash -c '"'"'/home/yugabyte/master/bin/yb-admin --master_addresses X import_snapshot /tmp/yb_backup_peqpnmfskujhlxse/SnapshotInfoPB db_lst_084761 --never_fsync=false'"'"'' ]]: code=1 output=Read snapshot meta file /tmp/yb_backup_peqpnmfskujhlxse/SnapshotInfoPB
YW 2022-08-05T20:08:04.067Z [DEBUG] cf7af8c4-7748-4529-9ca4-fcd87bdee26e from ShellProcessHandler in TaskPool-BackupUniverse(edaf84f8-508e-4fc0-840f-6b91d37ad21c)-0 - Importing snapshot 18576c59-63fb-4302-9c4b-4d900fd2e41a (COMPLETE)
YW 2022-08-05T20:08:04.067Z [DEBUG] cf7af8c4-7748-4529-9ca4-fcd87bdee26e from ShellProcessHandler in TaskPool-BackupUniverse(edaf84f8-508e-4fc0-840f-6b91d37ad21c)-0 - Target imported YSQL database name: db_lst_084761
YW 2022-08-05T20:08:04.067Z [DEBUG] cf7af8c4-7748-4529-9ca4-fcd87bdee26e from ShellProcessHandler in TaskPool-BackupUniverse(edaf84f8-508e-4fc0-840f-6b91d37ad21c)-0 - YSQL database being imported: db_lst_084761
YW 2022-08-05T20:08:04.067Z [DEBUG] cf7af8c4-7748-4529-9ca4-fcd87bdee26e from ShellProcessHandler in TaskPool-BackupUniverse(edaf84f8-508e-4fc0-840f-6b91d37ad21c)-0 - Table type: table
YW 2022-08-05T20:08:04.067Z [DEBUG] cf7af8c4-7748-4529-9ca4-fcd87bdee26e from ShellProcessHandler in TaskPool-BackupUniverse(edaf84f8-508e-4fc0-840f-6b91d37ad21c)-0 - Target imported table name: db_lst_084761.t0
YW 2022-08-05T20:08:04.067Z [DEBUG] cf7af8c4-7748-4529-9ca4-fcd87bdee26e from ShellProcessHandler in TaskPool-BackupUniverse(edaf84f8-508e-4fc0-840f-6b91d37ad21c)-0 - Table being imported: db_lst_084761.t0
YW 2022-08-05T20:08:04.067Z [DEBUG] cf7af8c4-7748-4529-9ca4-fcd87bdee26e from ShellProcessHandler in TaskPool-BackupUniverse(edaf84f8-508e-4fc0-840f-6b91d37ad21c)-0 - Table type: table
[...]
YW 2022-08-05T20:08:04.070Z [DEBUG] cf7af8c4-7748-4529-9ca4-fcd87bdee26e from ShellProcessHandler in TaskPool-BackupUniverse(edaf84f8-508e-4fc0-840f-6b91d37ad21c)-0 - Error running import_snapshot: Invalid argumen
t (yb/master/catalog_manager_ent.cc:2084): Unable to import snapshot meta file /tmp/yb_backup_peqpnmfskujhlxse/SnapshotInfoPB: YSQL table not found: t0: OBJECT_NOT_FOUND (master error 3)
YW 2022-08-05T20:08:04.070Z [DEBUG] cf7af8c4-7748-4529-9ca4-fcd87bdee26e from ShellProcessHandler in TaskPool-BackupUniverse(edaf84f8-508e-4fc0-840f-6b91d37ad21c)-0 - Usage: /home/yugabyte/master/bin/yb-admin impo
rt_snapshot  <file_name> [<namespace> <table_name> [<table_name>]...]
YW 2022-08-05T20:08:04.070Z [DEBUG] cf7af8c4-7748-4529-9ca4-fcd87bdee26e from ShellProcessHandler in TaskPool-BackupUniverse(edaf84f8-508e-4fc0-840f-6b91d37ad21c)-0 -
YW 2022-08-05T20:08:04.070Z [DEBUG] cf7af8c4-7748-4529-9ca4-fcd87bdee26e from ShellProcessHandler in TaskPool-BackupUniverse(edaf84f8-508e-4fc0-840f-6b91d37ad21c)-0 - Traceback (most recent call last):
YW 2022-08-05T20:08:04.070Z [DEBUG] cf7af8c4-7748-4529-9ca4-fcd87bdee26e from ShellProcessHandler in TaskPool-BackupUniverse(edaf84f8-508e-4fc0-840f-6b91d37ad21c)-0 -   File "bin/yb_backup.py", line 3613, in run
YW 2022-08-05T20:08:04.070Z [DEBUG] cf7af8c4-7748-4529-9ca4-fcd87bdee26e from ShellProcessHandler in TaskPool-BackupUniverse(edaf84f8-508e-4fc0-840f-6b91d37ad21c)-0 -     self.restore_table()
YW 2022-08-05T20:08:04.070Z [DEBUG] cf7af8c4-7748-4529-9ca4-fcd87bdee26e from ShellProcessHandler in TaskPool-BackupUniverse(edaf84f8-508e-4fc0-840f-6b91d37ad21c)-0 -   File "bin/yb_backup.py", line 3450, in resto
re_table
YW 2022-08-05T20:08:04.070Z [DEBUG] cf7af8c4-7748-4529-9ca4-fcd87bdee26e from ShellProcessHandler in TaskPool-BackupUniverse(edaf84f8-508e-4fc0-840f-6b91d37ad21c)-0 -     snapshot_metadata = self.import_snapshot(m
etadata_file_path)
YW 2022-08-05T20:08:04.070Z [DEBUG] cf7af8c4-7748-4529-9ca4-fcd87bdee26e from ShellProcessHandler in TaskPool-BackupUniverse(edaf84f8-508e-4fc0-840f-6b91d37ad21c)-0 -   File "bin/yb_backup.py", line 3217, in impor
t_snapshot
YW 2022-08-05T20:08:04.070Z [DEBUG] cf7af8c4-7748-4529-9ca4-fcd87bdee26e from ShellProcessHandler in TaskPool-BackupUniverse(edaf84f8-508e-4fc0-840f-6b91d37ad21c)-0 -     output = self.run_yb_admin(yb_admin_args,
run_ip=self.get_main_host_ip())
YW 2022-08-05T20:08:04.070Z [DEBUG] cf7af8c4-7748-4529-9ca4-fcd87bdee26e from ShellProcessHandler in TaskPool-BackupUniverse(edaf84f8-508e-4fc0-840f-6b91d37ad21c)-0 -   File "bin/yb_backup.py", line 1614, in run_y
b_admin
YW 2022-08-05T20:08:04.070Z [DEBUG] cf7af8c4-7748-4529-9ca4-fcd87bdee26e from ShellProcessHandler in TaskPool-BackupUniverse(edaf84f8-508e-4fc0-840f-6b91d37ad21c)-0 -     raise ex
YW 2022-08-05T20:08:04.071Z [DEBUG] cf7af8c4-7748-4529-9ca4-fcd87bdee26e from ShellProcessHandler in TaskPool-BackupUniverse(edaf84f8-508e-4fc0-840f-6b91d37ad21c)-0 -   File "bin/yb_backup.py", line 1609, in run_y
b_admin
YW 2022-08-05T20:08:04.071Z [DEBUG] cf7af8c4-7748-4529-9ca4-fcd87bdee26e from ShellProcessHandler in TaskPool-BackupUniverse(edaf84f8-508e-4fc0-840f-6b91d37ad21c)-0 -     cmd_line_args, run_ip=run_ip)
YW 2022-08-05T20:08:04.071Z [DEBUG] cf7af8c4-7748-4529-9ca4-fcd87bdee26e from ShellProcessHandler in TaskPool-BackupUniverse(edaf84f8-508e-4fc0-840f-6b91d37ad21c)-0 -   File "bin/yb_backup.py", line 1563, in run_t
ool
YW 2022-08-05T20:08:04.071Z [DEBUG] cf7af8c4-7748-4529-9ca4-fcd87bdee26e from ShellProcessHandler in TaskPool-BackupUniverse(edaf84f8-508e-4fc0-840f-6b91d37ad21c)-0 -     env_vars=env_vars)
YW 2022-08-05T20:08:04.071Z [DEBUG] cf7af8c4-7748-4529-9ca4-fcd87bdee26e from ShellProcessHandler in TaskPool-BackupUniverse(edaf84f8-508e-4fc0-840f-6b91d37ad21c)-0 -   File "bin/yb_backup.py", line 2097, in run_s
sh_cmd
YW 2022-08-05T20:08:04.071Z [DEBUG] cf7af8c4-7748-4529-9ca4-fcd87bdee26e from ShellProcessHandler in TaskPool-BackupUniverse(edaf84f8-508e-4fc0-840f-6b91d37ad21c)-0 -     return self.run_program(ssh_command, num_r
etry=num_retries)
YW 2022-08-05T20:08:04.071Z [DEBUG] cf7af8c4-7748-4529-9ca4-fcd87bdee26e from ShellProcessHandler in TaskPool-BackupUniverse(edaf84f8-508e-4fc0-840f-6b91d37ad21c)-0 -   File "bin/yb_backup.py", line 1060, in run_p
rogram
YW 2022-08-05T20:08:04.071Z [DEBUG] cf7af8c4-7748-4529-9ca4-fcd87bdee26e from ShellProcessHandler in TaskPool-BackupUniverse(edaf84f8-508e-4fc0-840f-6b91d37ad21c)-0 -     self.sleep_or_raise(num_retry, timeout, e)
YW 2022-08-05T20:08:04.071Z [DEBUG] cf7af8c4-7748-4529-9ca4-fcd87bdee26e from ShellProcessHandler in TaskPool-BackupUniverse(edaf84f8-508e-4fc0-840f-6b91d37ad21c)-0 -   File "bin/yb_backup.py", line 1024, in sleep
_or_raise
YW 2022-08-05T20:08:04.071Z [DEBUG] cf7af8c4-7748-4529-9ca4-fcd87bdee26e from ShellProcessHandler in TaskPool-BackupUniverse(edaf84f8-508e-4fc0-840f-6b91d37ad21c)-0 -     raise ex
YW 2022-08-05T20:08:04.071Z [DEBUG] cf7af8c4-7748-4529-9ca4-fcd87bdee26e from ShellProcessHandler in TaskPool-BackupUniverse(edaf84f8-508e-4fc0-840f-6b91d37ad21c)-0 -   File "bin/yb_backup.py", line 1046, in run_p
rogram
YW 2022-08-05T20:08:04.071Z [DEBUG] cf7af8c4-7748-4529-9ca4-fcd87bdee26e from ShellProcessHandler in TaskPool-BackupUniverse(edaf84f8-508e-4fc0-840f-6b91d37ad21c)-0 -     env=proc_env, **kwargs).decode('utf-8', er
rors='replace')
YW 2022-08-05T20:08:04.071Z [DEBUG] cf7af8c4-7748-4529-9ca4-fcd87bdee26e from ShellProcessHandler in TaskPool-BackupUniverse(edaf84f8-508e-4fc0-840f-6b91d37ad21c)-0 -   File "/usr/lib64/python3.6/subprocess.py", l
ine 356, in check_output
YW 2022-08-05T20:08:04.071Z [DEBUG] cf7af8c4-7748-4529-9ca4-fcd87bdee26e from ShellProcessHandler in TaskPool-BackupUniverse(edaf84f8-508e-4fc0-840f-6b91d37ad21c)-0 -     **kwargs).stdout
YW 2022-08-05T20:08:04.071Z [DEBUG] cf7af8c4-7748-4529-9ca4-fcd87bdee26e from ShellProcessHandler in TaskPool-BackupUniverse(edaf84f8-508e-4fc0-840f-6b91d37ad21c)-0 -   File "/usr/lib64/python3.6/subprocess.py", l
ine 438, in run
YW 2022-08-05T20:08:04.071Z [DEBUG] cf7af8c4-7748-4529-9ca4-fcd87bdee26e from ShellProcessHandler in TaskPool-BackupUniverse(edaf84f8-508e-4fc0-840f-6b91d37ad21c)-0 -     output=stdout, stderr=stderr)
```
What the workload is doing right now is:
1. Create tables
2. Run inserts/selects/updates/DDL
3. Back up entire database
4. Drop database
5. Restore database
6. Go back to 2

The universe (2.15.2.0-b40, RF3) is running at https://portal.dev.yugabyte.com/universes/edaf84f8-508e-4fc0-840f-6b91d37ad21c/tasks with the broken backup being s3://csunittest/univ-edaf84f8-508e-4fc0-840f-6b91d37ad21c/backup-2022-08-05T16:32:21-208841407/keyspace-db_lst_084761
For LST I ran:
```
$ cd ~/code/yb-long-sytem-test
$ git checkout 55f650f3
$ ./long_system_test.py --scenario=backup_restore --portal=portal.dev.yugabyte.com --universe_uuid=edaf84f8-508e-4fc0-840f-6b91d37ad21c --threads=10 --runtime=5 --complexity=full --seed=084761
```

**Comment by def-** [comment]
There might be a connection to https://github.com/yugabyte/yugabyte-db/issues/10716 which happened immediately after this bug.

**Comment by def-** [comment]
This might be related to https://github.com/yugabyte/yugabyte-db/issues/12223

**Comment by sanketkedia** [comment]
It seems like the master is hitting soft-memory limits causing hindrances in executing the YSQL dump during restore.

`I0805 16:37:12.794569 19670 maintenance_manager.cc:340] we have exceeded our soft memory limit (current capacity is 88.87%).  However, there are no ops currently runnable which would free memory.`

1. During Create database. The create database request to the master fails several times before eventually succeeding. When failing, it fails with the following message:
```
W0805 16:37:24.529098 15668 catalog_manager.cc:7659] Error Copying PGSQL System Tables for Pending Namespace: Service unavailable (yb/tablet/operations/operation_tracker.cc:167): Operation failed, tablet 00000000000000000000000000000000 operation memory consumption (0) has exceeded its limit (1073741824) or the limit of an ancestral tracker

I0805 16:37:24.531234 15668 catalog_manager.cc:7672] Failed keyspace: db_lst_084761 [id=000048fc000030008000000000000000]
```

2. However it does eventually succeed after several retries.
`I0805 16:45:56.133600 16782 catalog_manager.cc:7726] Namespace transaction succeeded: db_lst_084761 [id=00004905000030008000000000000000]`

3. Next when creating the first table t0, on postgres side the RPC to CreateTable to the master (via tserver) times out after 10 mins. 
```
17:11:42.327980  5428 pg_create_table.cc:90] PgCreateTable: creating a transactional table: db_lst_084761.t0/{ database_oid: 18693 object_oid: 18696 }
...
2022-08-05 17:21:55.262 UTC [7936] ERROR:  Timed out: Perform RPC (request call id 478) to 172.151.19.242:9100 timed out after 602.000s
2022-08-05 17:21:55.262 UTC [7936] STATEMENT:  CREATE TABLE public.t0 (
```

4. The master however gets the create table request and it successfully creates all tablets. I can see that all the 59 tablets for this table get a leader and they respond back to the master. 
```
 I0805 17:11:42.331019 21326 catalog_manager.cc:3300] CreateTable from 172.151.19.242:45526:
 ...
 
 I0805 17:11:42.335036 21326 catalog_manager.cc:3891] Successfully created table t0 [id=00004905000030008000000000004908] in db_lst_084761 [id=00004905000030008000000000000000] per request from 172.151.19.242:45526
 
 I0805 17:11:46.033689 18453 catalog_entity_info.cc:118] T 0646bea5bbc949d982737e6e8cc4bd43: Leader changed from <NULL> to 0x0000000007547018 ...
```

5. After 10 mins, however the create table txn fails on the master and it deletes the tables.
```
I0805 17:21:55.396106 25060 catalog_manager.cc:3954] Table transaction failed, deleting: t0 [id=00004905000030008000000000004908]
I0805 17:21:55.396860 25060 catalog_manager.cc:5240] Servicing DeleteTable request from internal request: table { table_id: "00004905000030008000000000004908" table_name: "t0" } is_index_table: false 
```
 
It's puzzling why the create table of `t0` fails. There are no logs on the tserver as to why the RPC to the master failed/timed out. It seems likely that the tserver is stuck in `YBClient::Data::WaitForCreateTableToFinish` and that the master is rejecting such RPCs from the tserver because of hitting soft-memory limits.

**Comment by def-** [comment]
As discussed on call I will try with dropping database after each run to ensure we don't run into OoM

**Comment by def-** [comment]
Similar failure now with only one database (12 tables currently) after 3 hours:
```
YW 2022-08-18T20:53:34.714Z [DEBUG] 1e099c94-e7aa-434c-9ab1-1e763c3122ac from ShellProcessHandler in TaskPool-BackupUniverse(76e945a0-0084-4d71-be95-5e0896cdfccd)-0 - Table type: index (attaching to the old table
id 0000436e0000300080000000000043c3)
YW 2022-08-18T20:53:34.714Z [DEBUG] 1e099c94-e7aa-434c-9ab1-1e763c3122ac from ShellProcessHandler in TaskPool-BackupUniverse(76e945a0-0084-4d71-be95-5e0896cdfccd)-0 - Target imported table name: db_lst_216376.idx_
t2_c25_varchar_c27_text_c70_int_c62_text_c24_varchar
YW 2022-08-18T20:53:34.714Z [DEBUG] 1e099c94-e7aa-434c-9ab1-1e763c3122ac from ShellProcessHandler in TaskPool-BackupUniverse(76e945a0-0084-4d71-be95-5e0896cdfccd)-0 - Table being imported: db_lst_216376.idx_t2_c25
_varchar_c27_text_c70_int_c62_text_c24_varchar
YW 2022-08-18T20:53:34.714Z [DEBUG] 1e099c94-e7aa-434c-9ab1-1e763c3122ac from ShellProcessHandler in TaskPool-BackupUniverse(76e945a0-0084-4d71-be95-5e0896cdfccd)-0 - Error running import_snapshot: Invalid argumen
t (yb/master/catalog_manager_ent.cc:2176): Unable to import snapshot meta file /tmp/yb_backup_yideqdblwudyhntz/SnapshotInfoPB: YSQL table not found: idx_t0_c31_float8_c66_varchar_c5_numeric_c57_float4_c49_boolean:
 OBJECT_NOT_FOUND (master error 3)
YW 2022-08-18T20:53:34.714Z [DEBUG] 1e099c94-e7aa-434c-9ab1-1e763c3122ac from ShellProcessHandler in TaskPool-BackupUniverse(76e945a0-0084-4d71-be95-5e0896cdfccd)-0 - Usage: /home/yugabyte/master/bin/yb-admin impo
rt_snapshot  <file_name> [<namespace> <table_name> [<table_name>]...]
```
![Screenshot 2022-08-18 at 23-05-06 YugabyteDB Anywhere UI](https://user-images.githubusercontent.com/2335377/185494677-816b2af6-a42c-4ba9-a5d4-924176e35a37.png)

New universe is at http://portal-iam.dev.yugabyte.com/universes/76e945a0-0084-4d71-be95-5e0896cdfccd/overview

**Comment by def-** [comment]
Happened again on the same universe, so this is blocking further B&R testing with LST.

**Comment by sanketkedia** [comment]
There are soft-memory exceeded errors still, something is leaking memory that we should investigate

**Comment by nmantrav2** [comment]
Using 2.19.1.0-b103 universe, LST run threw following error

Query: EXPLAIN (ANALYZE TRUE, VERBOSE TRUE, COSTS TRUE, BUFFERS TRUE, TIMING FALSE, SUMMARY FALSE, FORMAT YAML)
EXECUTE stmt;
  values: None
  runtime: 2023-06-05 15:44:07.305 - 2023-06-05 15:44:07.367
  supports explain: False
  supports rollback: False
  affected rows: None
Action: RandomSelectAction
Error class: InternalError_
Error code: XX000
Error message: ERROR:  invalid attribute number 24 for t2_0
    @     0x5578c08ea372  elog_finish
    @     0x5578c08c7a7d  YbApplyAttr
    @     0x5578c08c437c  YbPreloadRelCacheImpl
    @     0x5578c08c511b  YbRunWithPrefetcherImpl
    @     0x5578c08c4eba  YbRunWithPrefetcher
    @     0x5578c073f098  YBRefreshCache
    @     0x5578c0738d0d  PostgresMain
    @     0x5578c06799ce  BackendRun
    @     0x5578c0678a90  ServerLoop
    @     0x5578c0673f05  PostmasterMain
    @     0x5578c057923f  PostgresServerProcessMain
    @     0x5578c0241352  main
    @     0x7f37b77f6825  __libc_start_main
    @     0x5578c0241269  _start
Transaction isolation level: default
DB Node: host: 10.9.92.116, port: 5433
DB Backend PID: 32337

**Comment by nmantrav2** [comment]
For another round of run 

2023-06-05 16:48:06,796 worker_0   ERROR    Unexpected query failure: InternalError_
Query: INSERT INTO t0_0 (c0_int8range_3, c1_bigint_1, c2_text_0, c3_int2range_0, c4_int8range_2, c5_date_1, c6_smallint_0) VALUES ('(,-67)'::INT8RANGE, -17, '-46', '(-75,-38)'::INT2RANGE, '(-78,-15)'::INT8RANGE, '2009-03-07', -39);
  values: None
  runtime: 2023-06-05 16:48:06.793 - 2023-06-05 16:48:06.795
  supports explain: True
  supports rollback: True
  affected rows: None
Action: SingleInsertAction
Error class: InternalError_
Error code: XX000
Error message: ERROR:  Attribute value type does not match column type: 10 vs 2
Transaction isolation level: read uncommitted
DB Node: host: 10.9.141.79, port: 5433
DB Backend PID: 55776
