### ISSUE TITLE
[YSQL] TestPgMemoryGC fails on some platforms

### ISSUE THREAD

**Issue by tedyu** [yugabyte/yugabyte-db#13763]
Jira Link: [DB-3288](https://yugabyte.atlassian.net/browse/DB-3288)
### Description

TestPgMemoryGC#testPgMemoryGcOrderBy (https://detective-gcp.dev.yugabyte.com/job/yugabyte-db-phabricator%2F16893%2Fartifact%2Fjava%2Fyb-pgsql%2Ftarget%2Fsurefire-reports_org.yb.pgsql.TestPgMemoryGC__testPgMemoryGcOrderBy%2Forg.yb.pgsql.TestPgMemoryGC-output.txt.gz?class=org.yb.pgsql.TestPgMemoryGC&max_lines=3000&name=testPgMemoryGcOrderBy&start_line=12001)
```
19:46:38.853 (main) [ERROR - org.yb.BaseYBTest$1$2.logEventDetails(BaseYBTest.java:243)] YB Java test failed: class="org.yb.pgsql.TestPgMemoryGC", method="testPgMemoryGcOrderBy"
--
13321 | java.lang.AssertionError: Freed bytes should be recycled when GC threshold is reached
13322 | at org.junit.Assert.fail(Assert.java:88)
13323 | at org.junit.Assert.assertTrue(Assert.java:41)
13324 | at org.yb.AssertionWrappers.lambda$assertTrue$0(AssertionWrappers.java:61)
13325 | at org.yb.AssertionWrappers.wrapAssertion(AssertionWrappers.java:45)
13326 | at org.yb.AssertionWrappers.assertTrue(AssertionWrappers.java:61)
13327 | at org.yb.pgsql.TestPgMemoryGC.testPgMemoryGcOrderBy(TestPgMemoryGC.java:67)

19:46:38.853 (main) [ERROR - org.yb.BaseYBTest$1$2.logEventDetails(BaseYBTest.java:243)] YB Java test failed: class="org.yb.pgsql.TestPgMemoryGC", method="testPgMemoryGcOrderBy"
[13321](https://detective-gcp.dev.yugabyte.com/job/yugabyte-db-phabricator%2F16893%2Fartifact%2Fjava%2Fyb-pgsql%2Ftarget%2Fsurefire-reports_org.yb.pgsql.TestPgMemoryGC__testPgMemoryGcOrderBy%2Forg.yb.pgsql.TestPgMemoryGC-output.txt.gz?class=org.yb.pgsql.TestPgMemoryGC&max_lines=3000&name=testPgMemoryGcOrderBy&start_line=12001#line-13321)	java.lang.AssertionError: Freed bytes should be recycled when GC threshold is reached
[13322](https://detective-gcp.dev.yugabyte.com/job/yugabyte-db-phabricator%2F16893%2Fartifact%2Fjava%2Fyb-pgsql%2Ftarget%2Fsurefire-reports_org.yb.pgsql.TestPgMemoryGC__testPgMemoryGcOrderBy%2Forg.yb.pgsql.TestPgMemoryGC-output.txt.gz?class=org.yb.pgsql.TestPgMemoryGC&max_lines=3000&name=testPgMemoryGcOrderBy&start_line=12001#line-13322)	         at org.junit.Assert.fail(Assert.java:88)
[13323](https://detective-gcp.dev.yugabyte.com/job/yugabyte-db-phabricator%2F16893%2Fartifact%2Fjava%2Fyb-pgsql%2Ftarget%2Fsurefire-reports_org.yb.pgsql.TestPgMemoryGC__testPgMemoryGcOrderBy%2Forg.yb.pgsql.TestPgMemoryGC-output.txt.gz?class=org.yb.pgsql.TestPgMemoryGC&max_lines=3000&name=testPgMemoryGcOrderBy&start_line=12001#line-13323)	         at org.junit.Assert.assertTrue(Assert.java:41)
[13324](https://detective-gcp.dev.yugabyte.com/job/yugabyte-db-phabricator%2F16893%2Fartifact%2Fjava%2Fyb-pgsql%2Ftarget%2Fsurefire-reports_org.yb.pgsql.TestPgMemoryGC__testPgMemoryGcOrderBy%2Forg.yb.pgsql.TestPgMemoryGC-output.txt.gz?class=org.yb.pgsql.TestPgMemoryGC&max_lines=3000&name=testPgMemoryGcOrderBy&start_line=12001#line-13324)	         at org.yb.AssertionWrappers.lambda$assertTrue$0(AssertionWrappers.java:61)
[13325](https://detective-gcp.dev.yugabyte.com/job/yugabyte-db-phabricator%2F16893%2Fartifact%2Fjava%2Fyb-pgsql%2Ftarget%2Fsurefire-reports_org.yb.pgsql.TestPgMemoryGC__testPgMemoryGcOrderBy%2Forg.yb.pgsql.TestPgMemoryGC-output.txt.gz?class=org.yb.pgsql.TestPgMemoryGC&max_lines=3000&name=testPgMemoryGcOrderBy&start_line=12001#line-13325)	         at org.yb.AssertionWrappers.wrapAssertion(AssertionWrappers.java:45)
[13326](https://detective-gcp.dev.yugabyte.com/job/yugabyte-db-phabricator%2F16893%2Fartifact%2Fjava%2Fyb-pgsql%2Ftarget%2Fsurefire-reports_org.yb.pgsql.TestPgMemoryGC__testPgMemoryGcOrderBy%2Forg.yb.pgsql.TestPgMemoryGC-output.txt.gz?class=org.yb.pgsql.TestPgMemoryGC&max_lines=3000&name=testPgMemoryGcOrderBy&start_line=12001#line-13326)	         at org.yb.AssertionWrappers.assertTrue(AssertionWrappers.java:61)
[13327](https://detective-gcp.dev.yugabyte.com/job/yugabyte-db-phabricator%2F16893%2Fartifact%2Fjava%2Fyb-pgsql%2Ftarget%2Fsurefire-reports_org.yb.pgsql.TestPgMemoryGC__testPgMemoryGcOrderBy%2Forg.yb.pgsql.TestPgMemoryGC-output.txt.gz?class=org.yb.pgsql.TestPgMemoryGC&max_lines=3000&name=testPgMemoryGcOrderBy&start_line=12001#line-13327)	         at org.yb.pgsql.TestPgMemoryGC.testPgMemoryGcOrderBy(TestPgMemoryGC.java:67)
```

**Comment by tedyu** [comment]
cc @sushantrmishra

**Comment by tedyu** [comment]
Another form of test failure:
```
java.lang.AssertionError: Freed bytes should be recycled when GC threshold is low
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.assertTrue(Assert.java:41)
    at org.yb.AssertionWrappers.lambda$assertTrue$0(AssertionWrappers.java:61)
    at org.yb.AssertionWrappers.wrapAssertion(AssertionWrappers.java:45)
    at org.yb.AssertionWrappers.assertTrue(AssertionWrappers.java:61)
    at org.yb.pgsql.TestPgMemoryGC.checkRssDiffForGcThreshold(TestPgMemoryGC.java:96)
    at org.yb.pgsql.TestPgMemoryGC.testPgMemoryGcThresholdOverride(TestPgMemoryGC.java:86)
```
This means on Alma, freed bytes may not be recycled.

**Comment by m-iancu** [comment]
This covers both sub-test failures below:
[org.yb.pgsql.TestPgMemoryGC.testPgMemoryGcOrderBy](https://detective-gcp.dev.yugabyte.com/stability/test?branch=master&build_type=all&class=org.yb.pgsql.TestPgMemoryGC&fail_tag=all&name=testPgMemoryGcOrderBy&platform=all) 
[org.yb.pgsql.TestPgMemoryGC.testPgMemoryGcThresholdOverride](https://detective-gcp.dev.yugabyte.com/stability/test?branch=master&build_type=all&class=org.yb.pgsql.TestPgMemoryGC&fail_tag=all&name=testPgMemoryGcThresholdOverride&platform=all)
