### ISSUE TITLE
[YCQL] PREPARE failure on "SELECT... WHERE (r1, r2) IN ((?, ?))" in 2.8, 2.12, 2.14

### ISSUE THREAD

**Issue by OlegLoginov** [yugabyte/yugabyte-db#13837]
### Description

The issue was found during the fix backporting:
Diff: https://phabricator.dev.yugabyte.com/D18640
Commit: https://github.com/yugabyte/yugabyte-db/commit/5c3f73189ab142269d876ff3e78bbf7d5ad5bbd3

The test does not work as expected:
```
ybd --cxx-test ql-statement-test --gtest_filter TestQLStatement.TestBindVarPositions
```
Exactly these 2 test-cases:
```
  prepareAndCheck(processor,
    "SELECT * FROM tbl WHERE h1 = ? AND h2 = ? AND (r1, r2) IN ((?, ?));", {0, 1});
  prepareAndCheck(processor,
      "SELECT * FROM tbl WHERE (r1, r2) IN ((?, ?)) AND h1 = ? AND h2 = ?;", {2, 3});
```
The statements handling is different in different YB branches:
Master branch (2.15?) - WORKS FINE
`2.14` branch - Query error: Feature Not Supported
`2.12` branch - Feature Not Supported + TS Crash
`2.8` branch - Feature Not Supported + TS Crash

The unstable behavior must be investigated and fixed.

**Comment by OlegLoginov** [comment]
Call stack:
```
W0901 01:15:59.801918  8218 process_context.cc:185] SQL Error: Feature Not Supported
SELECT * FROM tbl WHERE h1 = ? AND h2 = ? AND (r1, r2) IN ((?, ?));
                                              ^^^^^^^^

Thread 1 "ql-statement-te" received signal SIGSEGV, Segmentation fault.
0x00007fffde95ffe0 in vtable for __cxxabiv1::__class_type_info () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
(gdb) bt
#0  0x00007fffde95ffe0 in vtable for __cxxabiv1::__class_type_info () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#1  0x00007ffff5de8f21 in yb::ql::ParseContext::SetCmp::operator() (this=0x5555577422b0, v1=0x555559800588, v2=0x555559800438) at ../../src/yb/yql/cql/ql/parser/parse_context.cc:109
#2  0x00007ffff5e67b3c in std::_Rb_tree<yb::ql::PTBindVar*, yb::ql::PTBindVar*, std::_Identity<yb::ql::PTBindVar*>, yb::ql::ParseContext::SetCmp, yb::internal::ArenaAllocatorBase<yb::ql::PTBindVar*, yb::internal::ArenaTraits> >::_M_get_insert_unique_pos (this=0x5555577422a8, __k=@0x7fffffffbe90: 0x555559800588) at /usr/include/c++/8/bits/stl_tree.h:2061
#3  0x00007ffff5e5a97c in std::_Rb_tree<yb::ql::PTBindVar*, yb::ql::PTBindVar*, std::_Identity<yb::ql::PTBindVar*>, yb::ql::ParseContext::SetCmp, yb::internal::ArenaAllocatorBase<yb::ql::PTBindVar*, yb::internal::ArenaTraits> >::_M_insert_unique<yb::ql::PTBindVar* const&> (this=0x5555577422a8, __v=@0x7fffffffbe90: 0x555559800588) at /usr/include/c++/8/bits/stl_tree.h:2113
#4  0x00007ffff5e3b7ee in std::set<yb::ql::PTBindVar*, yb::ql::ParseContext::SetCmp, yb::internal::ArenaAllocatorBase<yb::ql::PTBindVar*, yb::internal::ArenaTraits> >::insert (this=0x5555577422a8, 
    __x=@0x7fffffffbe90: 0x555559800588) at /usr/include/c++/8/bits/stl_set.h:511
#5  0x00007ffff5e3801b in yb::ql::ParseContext::AddBindVariable (this=0x555557742280, var=0x555559800588) at ../../src/yb/yql/cql/ql/parser/parse_context.h:51
#6  0x00007ffff5e380ea in yb::ql::Parser::AddBindVariable (this=0x55555777f800, var=0x555559800588) at ../../src/yb/yql/cql/ql/parser/parser.h:62
#7  0x00007ffff5e17f95 in yb::ql::GramProcessor::parse (this=0x55555777fbb0) at parser_gram.y:3557
#8  0x00007ffff5de4e21 in yb::ql::Parser::Parse (this=0x55555777f800, stmt="SELECT * FROM tbl WHERE h1 = ? AND h2 = ? AND (r1, r2) IN ((?, ?));", reparsed=false, 
    mem_tracker=std::shared_ptr<yb::MemTracker> (empty) = {...}, internal=false) at ../../src/yb/yql/cql/ql/parser/parser.cc:44
#9  0x00007ffff6b99ab3 in yb::ql::QLProcessor::Parse (this=0x5555576badc0, stmt="SELECT * FROM tbl WHERE h1 = ? AND h2 = ? AND (r1, r2) IN ((?, ?));", parse_tree=0x7fffffffd488, reparsed=false, 
    mem_tracker=std::shared_ptr<yb::MemTracker> (empty) = {...}, internal=false) at ../../src/yb/yql/cql/ql/ql_processor.cc:175
#10 0x00007ffff6b99fcf in yb::ql::QLProcessor::Prepare (this=0x5555576badc0, stmt="SELECT * FROM tbl WHERE h1 = ? AND h2 = ? AND (r1, r2) IN ((?, ?));", parse_tree=0x7fffffffd488, reparsed=false, 
    mem_tracker=std::shared_ptr<yb::MemTracker> (empty) = {...}, internal=false) at ../../src/yb/yql/cql/ql/ql_processor.cc:208
#11 0x00007ffff6b93e94 in yb::ql::Statement::Prepare (this=0x7fffffffd560, processor=0x5555576badc0, mem_tracker=std::shared_ptr<yb::MemTracker> (empty) = {...}, internal=false, result=0x7fffffffd500)
    at ../../src/yb/yql/cql/ql/statement.cc:48
#12 0x0000555555568b34 in yb::ql::prepareAndCheck (processor=0x5555571a3f20, query="SELECT * FROM tbl WHERE h1 = ? AND h2 = ? AND (r1, r2) IN ((?, ?));", positions=...)
    at ../../src/yb/yql/cql/ql/test/ql-statement-test.cc:115
#13 0x000055555556a6cf in yb::ql::TestQLStatement_TestBindVarPositions_Test::TestBody (this=0x555555fb0180) at ../../src/yb/yql/cql/ql/test/ql-statement-test.cc:169

--------------
#14 0x00007fffe2bca3cd in testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void> (location=0x7fffe2bd9d19 "the test body", method=<optimized out>, object=0x555555fb0180)
    at /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20211222064157-dd4872fe56-ubuntu1804-x86_64-gcc8/src/gmock-1.8.0/googletest/src/gtest.cc:2383
#15 testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void> (object=object@entry=0x555555fb0180, method=<optimized out>, location=location@entry=0x7fffe2bd9d19 "the test body")
    at /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20211222064157-dd4872fe56-ubuntu1804-x86_64-gcc8/src/gmock-1.8.0/googletest/src/gtest.cc:2438
#16 0x00007fffe2bbff82 in testing::Test::Run (this=0x555555fb0180)
    at /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20211222064157-dd4872fe56-ubuntu1804-x86_64-gcc8/src/gmock-1.8.0/googletest/src/gtest.cc:2474
#17 testing::Test::Run (this=0x555555fb0180) at /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20211222064157-dd4872fe56-ubuntu1804-x86_64-gcc8/src/gmock-1.8.0/googletest/src/gtest.cc:2465
#18 0x00007fffe2bc00c8 in testing::TestInfo::Run (this=0x555555fae6c0)
    at /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20211222064157-dd4872fe56-ubuntu1804-x86_64-gcc8/src/gmock-1.8.0/googletest/src/gtest.cc:2656
#19 testing::TestInfo::Run (this=0x555555fae6c0) at /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20211222064157-dd4872fe56-ubuntu1804-x86_64-gcc8/src/gmock-1.8.0/googletest/src/gtest.cc:2630
#20 0x00007fffe2bc01a5 in testing::TestCase::Run (this=0x555555fce100)
    at /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20211222064157-dd4872fe56-ubuntu1804-x86_64-gcc8/src/gmock-1.8.0/googletest/src/gtest.cc:2774
#21 testing::TestCase::Run (this=0x555555fce100) at /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20211222064157-dd4872fe56-ubuntu1804-x86_64-gcc8/src/gmock-1.8.0/googletest/src/gtest.cc:2759
#22 0x00007fffe2bc069c in testing::internal::UnitTestImpl::RunAllTests (this=0x555556a82e00) at /usr/include/c++/8/bits/stl_vector.h:930
#23 testing::internal::UnitTestImpl::RunAllTests() () at /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20211222064157-dd4872fe56-ubuntu1804-x86_64-gcc8/src/gmock-1.8.0/googletest/src/gtest.cc:4551
#24 0x00007fffe2bca8ad in testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (location=0x7fffe2bdb030 "auxiliary test code (environments or event listeners)", 
```

**Comment by OlegLoginov** [comment]
One more call stack (YB v2.14):
```
	W	4.973551	31943	process_context.cc:185	SQL Error: Feature Not Supported
SELECT * FROM tbl WHERE h1 = ? AND h2 = ? AND (r1, r2) IN ((?, ?));
                                               ^^^^^^^^
pure virtual method called
terminate called without an active exception
*** Aborted at 1662129371 (unix time) try "date -d @1662129371" if you are using GNU date ***
PC: @ 0x0 (unknown)
*** SIGABRT (@0x7100007cc7) received by PID 31943 (TID 0x7f11856b82c0) from PID 31943; stack trace: ***
     @ 0x7f1189932246 google::(anonymous namespace)::FailureSignalHandler()
     @ 0x7f1187d0ece0 (unknown)
     @ 0x7f1187985a9f __GI_raise
     @ 0x7f1187958e05 __GI_abort
     @ 0x7f118854809b (unknown)
     @ 0x7f118854e53c (unknown)
     @ 0x7f118854e597 std::terminate()
     @ 0x7f118854f3f5 __cxa_pure_virtual
     @ 0x7f118d577b31 yb::ql::ParseContext::SetCmp::operator()()
     @ 0x7f118d5b3f92 std::_Rb_tree<>::_M_insert_unique<>()
     @ 0x7f118d5b408b std::set<>::insert()
     @ 0x7f118d594951 yb::ql::GramProcessor::parse()
     @ 0x7f118d576b99 yb::ql::Parser::Parse()
     @ 0x7f118dbb6e79 yb::ql::QLProcessor::Parse()
     @ 0x7f118dbb6ebf yb::ql::QLProcessor::Prepare()
     @ 0x7f118dbb4d0c yb::ql::Statement::Prepare()
     @ 0x40b82c yb::ql::TestQLStatement_TestBindVarPositions_Test::TestBody()
     @ 0x7f1189cddb01 testing::internal::HandleExceptionsInMethodIfSupported<>()
     @ 0x7f1189cd301d testing::Test::Run()
     @ 0x7f1189cd3168 testing::TestInfo::Run()
     @ 0x7f1189cd324f testing::TestCase::Run()
     @ 0x7f1189cd3797 testing::internal::UnitTestImpl::RunAllTests()
     @ 0x7f1189cd386b testing::UnitTest::Run()
     @ 0x7f118dcdd496 main
     @ 0x7f1187971cf3 __libc_start_main
     @ 0x4075be _start
     @ 0x0 (unknown)
```
