### ISSUE TITLE
[YSQL] Internal error: Namespace Create Failed: not onlined. when creating many databases

### ISSUE THREAD

**Issue by def-** [yugabyte/yugabyte-db#13875]
Jira Link: [DB-3377](https://yugabyte.atlassian.net/browse/DB-3377)
### Description

In https://phabricator.dev.yugabyte.com/D19100 I am trying to create 360 databases. On database 33 I deterministically get this error:
```
2022-09-05 20:15:54,769 database_operations.py:1576 INFO testupgrademanydbs-aws-rf3-upgrade-2.8.8.0_2 Create database gp_upgrade_db_33_2_8_8_0
2022-09-05 20:15:54,770 database_operations.py:417 INFO testupgrademanydbs-aws-rf3-upgrade-2.8.8.0_2 Create database query: CREATE DATABASE gp_upgrade_db_33_2_8_8_0
2022-09-05 20:16:15,605 test_base.py:163 ERROR testupgrademanydbs-aws-rf3-upgrade-2.8.8.0_2 ITEST FAILED testupgrademanydbs-aws-rf3-upgrade-2.8.8.0_2 : InternalError_('Internal error: Namespace Create Failed: not onlined.\n')
2022-09-05 20:16:15,663 test_base.py:164 INFO testupgrademanydbs-aws-rf3-upgrade-2.8.8.0_2 Traceback (most recent call last):
  File "/var/lib/jenkins/code/internal-services/itest/src/test_base.py", line 159, in execute_steps
    step.call()
  File "/var/lib/jenkins/code/internal-services/itest/src/test_base.py", line 51, in call
    ret = self.function()
  File "/var/lib/jenkins/code/internal-services/itest/src/universe_tests/system_tests/test_upgrade.py", line 461, in do_custom_work
    dbname=f'upgrade_db_{i}')
  File "/var/lib/jenkins/code/internal-services/itest/src/universe_tests/system_tests/test_upgrade.py", line 279, in create_ysql_objects
    gp_tablespace)
  File "/var/lib/jenkins/code/internal-services/itest/src/universe_tests/system_tests/system_test_utils/database_operations.py", line 1577, in create_geo_partitioned_schema
    ysql_create_database(session, database)
  File "/var/lib/jenkins/code/internal-services/itest/src/universe_tests/system_tests/system_test_utils/database_operations.py", line 418, in ysql_create_database
    session.execute(query)
psycopg2.errors.InternalError_: Internal error: Namespace Create Failed: not onlined.
```
Last postgres logging:
```
I0905 20:16:05.622880 15918 thread_pool.cc:171] Starting thread pool { name: TransactionManager queue_limit: 500 max_workers: 50 }
W0905 20:16:05.776741 15923 outbound_call.cc:126] Failed to schedule invoking callback on response for request yb.master.MasterService.GetMasterRegistration to 10.9.194.112: Aborted (yb/rpc/thread_pool.cc:261): Service is shutting down
I0905 20:16:05.780803 15920 poller.cc:66] Poll stopped: Service unavailable (yb/rpc/scheduler.cc:80): Scheduler is shutting down (system error 108)
W0905 20:16:09.369331 15736 yb_rpc.cc:591] Connection (0x00000000028a1b10) client 10.9.131.217:55216 => 10.9.194.112:7100: Network error (yb/rpc/yb_rpc.cc:590): Rpc timeout, passed: 15.001s, timeout: 15.000s, now: 3386.030s, last_read_time_: 3371.029s
I0905 20:16:13.068414 18966 tablet_rpc.cc:148] Unable to pick leader for 539a30893bdc41aba30f823aea458970, replicas: [0x0000000002d2b770 -> { uuid: 21e7811e192c4e1ab8b47cfa59c15ab7 private: [host: "10.9.131.217" port: 9100] cloud_info: placement_cloud: "aws" placement_region: "us-west-2" placement_zone: "us-west-2b", 0x0000000002d2b950 -> { uuid: 7b872a2b9c2b46b894603e4c254e3154 private: [host: "10.9.217.154" port: 9100] cloud_info: placement_cloud: "aws" placement_region: "us-west-2" placement_zone: "us-west-2d"], followers: [{0x0000000002d2b950 -> { uuid: 7b872a2b9c2b46b894603e4c254e3154 private: [host: "10.9.217.154" port: 9100] cloud_info: placement_cloud: "aws" placement_region: "us-west-2" placement_zone: "us-west-2d", { status: Illegal state (yb/consensus/consensus.cc:113): Not the leader (tablet server error 15) time: 0.005s }}, {0x0000000002d2b770 -> { uuid: 21e7811e192c4e1ab8b47cfa59c15ab7 private: [host: "10.9.131.217" port: 9100] cloud_info: placement_cloud: "aws" placement_region: "us-west-2" placement_zone: "us-west-2b", { status: Illegal state (yb/consensus/consensus.cc:113): Not the leader (tablet server error 15) time: 0.025s }}]
2022-09-05 20:16:15.596 UTC [15731] ERROR:  Internal error: Namespace Create Failed: not onlined.
2022-09-05 20:16:15.596 UTC [15731] STATEMENT:  CREATE DATABASE gp_upgrade_db_33_2_8_8_0
I0905 20:16:15.674916 15732 poller.cc:66] Poll stopped: Service unavailable (yb/rpc/scheduler.cc:80): Scheduler is shutting down (system error 108)
```
Full logs accessible from without Yugabyte org: https://drive.google.com/file/d/1navqeYEKp_ACwcrgRNVkxoq3IA9cPRW3/view?usp=sharing
There is a similar bug https://github.com/yugabyte/yugabyte-db/issues/10716 but it is about backup/restore, while this happened without any backup/restore.

**Comment by def-** [comment]
@shamanthchandra-yb noted that this is most likely due to OoM and thus expected. Closing for now
