### ISSUE TITLE
[DocDB][LST] Upgrade: Crash in core_rpc_tp_TabletSe

### ISSUE THREAD

**Issue by def-** [yugabyte/yugabyte-db#13907]
Jira Link: [DB-3404](https://yugabyte.atlassian.net/browse/DB-3404)
### Description

Happened during upgrade testing with LST enabled from version 2.0.9.0-b13 to 2.15.3.0-b133:
```
Core was generated by `/home/yugabyte/tserver/bin/yb-tserver --flagfile /home/yugabyte/tserver/conf/se'.
Program terminated with signal 11, Segmentation fault.
#0  0x00000000027792c0 in ?? ()

Thread 354 (LWP 18451):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
No locals.
#1  0x00007f857990e85c in std::condition_variable::wait(std::unique_lock<std::mutex>&) () from /home/yugabyte/yb-software/yugabyte-2.0.9.0-b13-centos-x86_64/linuxbrew/lib/libstdc++.so.6
No symbol table info available.
#2  0x00007f858009d3cb in PopTask (task=<synthetic pointer>, this=<optimized out>) at ../../src/yb/rpc/thread_pool.cc:128
        lock = {_M_device = 0x8e05f20, _M_owns = true}
#3  yb::rpc::(anonymous namespace)::Worker::Execute (this=<optimized out>) at ../../src/yb/rpc/thread_pool.cc:98
        task = <optimized out>
#4  0x00007f857e66766f in operator() (this=0x8ea7918) at /home/yugabyte/yb-software/yugabyte-2.0.9.0-b13-centos-x86_64/linuxbrew-xxxxxxxxxxxxx/Cellar/gcc/5.5.0_4/include/c++/5.5.0/functional:2267
No locals.
#5  yb::Thread::SuperviseThread (arg=0x8ea78c0) at ../../src/yb/util/thread.cc:739
        __clframe = {__cancel_routine = 0x7f857e666c40 <yb::Thread::FinishThread(void*)>, __cancel_arg = 0x8ea78c0, __do_it = 1, __cancel_type = <optimized out>}
        t = 0x8ea78c0
        name = {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x9bad180 "rpc_tp_TabletServer_36-18451"}, _M_string_length = 28, {_M_local_buf = "\036", '\000' <repeats 14 times>, _M_allocated_capacity = 30}}
        thread_mgr_ref = {<std::__shared_ptr<yb::(anonymous namespace)::ThreadMgr, (__gnu_cxx::_Lock_policy)2>> = {_M_ptr = <optimized out>, _M_refcount = {_M_pi = 0x2786360}}, <No data fields>}
        thread_ref = {ptr_ = 0x8ea78c0}
        loop_count = <optimized out>
#6  0x00007f8579128694 in start_thread (arg=0x7f8413b6e700) at pthread_create.c:333
        __res = <optimized out>
        pd = 0x7f8413b6e700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140205243164416, -916839792662795584, 0, 140210848903519, 140210848903936, 140205243164416, 886818238466632384, 886163722943212224}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#7  0x00007f857886541d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
No locals.
```
Full log: https://gist.github.com/def-/26688da52583f26303a4e8f2d6e91363 and https://gist.github.com/def-/20f8e82999c72c76117745dd15dbda28
I have seen similar crashes in my LRU, @qvad reported similar ones with large key-value load in stress tests too. I guess this is a regression since it started failing in 3 separate places within a week.

**Comment by def-** [comment]
The full logs I posted contain all backtraces.

This issue appears to be different from the other ones we have seen though since I don't see this part in the backtraces:
```
#4  0x0000ffff927b5914 in yb::tablet::TransactionParticipant::Impl::ProcessRemoveQueueUnlocked (this=this@entry=0x7aab2e00, min_running_notifier=min_running_notifier@entry=0xfffe5e6b6960)
    at ../../src/yb/tablet/transaction_participant.cc:1166
#5  0x0000ffff927b454c in yb::tablet::TransactionParticipant::Impl::EnqueueRemoveUnlocked (this=0x7aab2e00, id=..., reason=<optimized out>, min_running_notifier=<optimized out>)
    at ../../src/yb/tablet/transaction_participant.cc:1145
#6  0x0000ffff9271b3e0 in yb::tablet::RunningTransaction::DoStatusReceived (this=0x50a77b98, status=..., response=..., serial_no=1, shared_self=...) at ../../src/yb/tablet/running_transaction.cc:343
#7  0x0000ffff90dc5438 in yb::client::(anonymous namespace)::TransactionRpcBase::Finished (this=0x492dd420, status=...) at ../../src/yb/client/transaction_rpc.cc:67
```

**Comment by rthallamko3** [comment]
@def- , Does the issue persist after the crash?

**Comment by bmatican** [comment]
@es1024 Were we able to get any signal on this? Or did we not prioritize this, as i wasn't a crash *loop* per se?

**Comment by rthallamko3** [comment]
@kripasreenivasan , Can you clarify if this failure happens regularly or was it a one time crash?

**Comment by rthallamko3** [comment]
@rjalan-yb , @kripasreenivasan , Can you let us know if this is still an issue?
