### ISSUE TITLE
[CDCSDK] Connector deployment fails if there are tasks.max is less than the total number of tablets

### ISSUE THREAD

**Issue by vaibhav-yb** [yugabyte/yugabyte-db#13903]
Jira Link: [DB-3400](https://yugabyte.atlassian.net/browse/DB-3400)
After upgrading the Debezium core dependencies to 1.9.5.Final, it was observed that if a connector is deployed with a task count less than the number of tablets (in this case 2), we get the following error:
```
 io.debezium.DebeziumException: The task must be configured to use exactly one partition, 2 found
        	at io.debezium.pipeline.spi.Offsets.getTheOnlyOffset(Offsets.java:78)
        	at io.debezium.connector.yugabytedb.YugabyteDBConnectorTask.start(YugabyteDBConnectorTask.java:156)
        	at io.debezium.connector.common.BaseSourceTask.start(BaseSourceTask.java:130)
        	at org.apache.kafka.connect.runtime.WorkerSourceTask.initializeAndStart(WorkerSourceTask.java:231)
        	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:186)
        	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:237)
        	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        	at java.base/java.lang.Thread.run(Thread.java:829)
```

Moreover, this can also be reproduced if there are multiple tables in the `table.include.list`.

Steps to reproduce:
1. Start the pipeline with Zookeeper, Kafka and Kafka Connect having the latest jar file
2. Create a table in YB with 2 tablets
3. Deploy the connector with `tasks.max` set to 1 - this is when you'll encounter the above error.

**Comment by vaibhav-yb** [comment]
Closing this issue since the relevant changes have been fixed and merged in [yugabyte/debezium-connector-yugabytedb](https://github.com/yugabyte/debezium-connector-yugabytedb)
