### ISSUE TITLE
[DocDB][LST] B&R: BackupTable : completed 1 out of 1 tasks. failed.

### ISSUE THREAD

**Issue by def-** [yugabyte/yugabyte-db#13941]
Jira Link: [DB-3437](https://yugabyte.atlassian.net/browse/DB-3437)
### Description

During restore with LST I am running into a new failure (2.15.3.0-b113):
```
git checkout b4db6724 && ./long_system_test.py --scenario=backup_restore --portal=portal-iam.dev.yugabyte.com --universe_uuid=829efd3f-cae4-465b-a111-387b07169caa --threads=10 --runtime=5 --complexity=full --drop --seed=309250
```

This is on a larger system with more RAM to prevent running into https://github.com/yugabyte/yugabyte-db/issues/13539
```
Failed to execute task {"nodeExporterUser":"prometheus","universeUUID":"829efd3f-cae4-465b-a111-387b07169caa","enableYbc":false,"installYbc":false,"ybcInstalled":false,"encryptionAtRestConfig":{"encryptionAtRestEnabled":false,"opType":"UNDEFINED","type":"DATA_KEY"},"communicationPorts":{"masterHttpPort":7000,"masterRpcPort":7100,"tserverHttpPort":9000,"tserverRpcPort":9100,"ybControllerHttpPort":14000,"ybControllerrRpcPort":18018,"redisServerHttpPort":11000,"redisServerRpcPort":6379,"yqlServerHttpPort":12000,"yqlSe..., hit error:

{"error": "Exception: Command '['ssh', '-o', 'StrictHostKeyChecking=no', '-o', 'UserKnownHostsFile=/dev/null', '-o', 'ControlMaster=auto', '-o', 'ControlPath=~/.ssh/ssh-%r@%h:%p', '-o', 'ControlPersist=1m', '-i', '/opt/yugabyte/yugaware/data/keys/df9d85fd-ab55-4ed2-88b6-11d1179074dd/yb-dev-aws-test_df9d85fd-ab55-4ed2-88b6-11d1179074dd-key.pem', '-p', '22', '-q', 'yugabyte@10.9.124.118', \"cd / &&  bash -c '/home/yugabyte/master/bin/yb-admin --master_addresses 10.9.103.38:7100,10.9.124.118:7100,10.9.86.236:7100 import_snapshot /tmp/yb_backup_boquugvspekvsvxi/SnapshotInfoPB db_lst_309250 --never_fsync=false'\"]' returned non-zero exit status 1."}.
```
Universe is at http://portal-iam.dev.yugabyte.com/universes/829efd3f-cae4-465b-a111-387b07169caa/tasks
For this new failure I'm having trouble finding the actual error message in Yugaware logs:
```
YW 2022-09-08T22:09:18.824Z [ERROR] 43935018-ca8f-40c9-84a5-6d19852c1968 from BackupTable in TaskPool-BackupUniverse(829efd3f-cae4-465b-a111-387b07169caa)-0 - Response code=0, hasError=true.
YW 2022-09-08T22:09:18.824Z [ERROR] 43935018-ca8f-40c9-84a5-6d19852c1968 from BackupTable in TaskPool-BackupUniverse(829efd3f-cae4-465b-a111-387b07169caa)-0 - Errored out with: java.lang.RuntimeException: {"error": "Exception: Command '['ssh', '-o', 'StrictHostKeyChecking=no', '-o', 'UserKnownHostsFile=/dev/null', '-o', 'ControlMaster=auto', '-o', 'ControlPath=~/.ssh/ssh-%r@%h:%p', '-o', 'ControlPersist=1m', '-i', '/opt/yugabyte/yugaware/data/keys/df9d85fd-ab55-4ed2-88b6-11d1179074dd/yb-dev-aws-test_df9d85fd-ab55-4ed2-88b6-11d1179074dd-key.pem', '-p', '22', '-q', 'yugabyte@10.9.124.118', \"cd / &&  bash -c '/home/yugabyte/master/bin/yb-admin --master_addresses 10.9.103.38:7100,10.9.124.118:7100,10.9.86.236:7100 import_snapshot /tmp/yb_backup_boquugvspekvsvxi/SnapshotInfoPB db_lst_309250 --never_fsync=false'\"]' returned non-zero exit status 1."}
YW 2022-09-08T22:09:18.828Z [DEBUG] 43935018-ca8f-40c9-84a5-6d19852c1968 from Backup in TaskPool-BackupUniverse(829efd3f-cae4-465b-a111-387b07169caa)-0 - New Backup API: transitioned from InProgress to Failed
YW 2022-09-08T22:09:18.830Z [ERROR] 43935018-ca8f-40c9-84a5-6d19852c1968 from TaskExecutor in TaskPool-BackupUniverse(829efd3f-cae4-465b-a111-387b07169caa)-0 - Failed to execute task type subtasks.BackupTable UUID eab9f0bc-d3a9-471c-bee9-3d9fac5d67f4 details {"nodeExporterUser":"prometheus","universeUUID":"829efd3f-cae4-465b-a111-387b07169caa","enableYbc":false,"installYbc":false,"ybcInstalled":false,"encryptionAtRestConfig":{"encryptionAtRestEnabled":false,"opType":"UNDEFINED","type":"DATA_KEY"},"communicationPorts":{"masterHttpPort":7000,"masterRpcPort":7100,"tserverHttpPort":9000,"tserverRpcPort":9100,"ybControllerHttpPort":14000,"ybControllerrRpcPort":18018,"redisServerHttpPort":11000,"redisServerRpcPort":6379,"yqlServerHttpPort":12000,"yqlServerRpcPort":9042,"ysqlServerHttpPort":13000,"ysqlServerRpcPort":5433,"nodeExporterPort":9300},"extraDependencies":{"installNodeExporter":true},"firstTry":true,"keyspace":"db*********50","sse":false,"storageConfigUUID":"aa1a91ec-9d7c-4075-88e3-23abe5a807e3","storageLocation":"s3://backups.yugabyte.com/s3Backup//univ-829efd3f-cae4-465b-a111-387b07169caa/backup-2022-09-08T22:02:28-1616191662/keyspace-db_lst_309250","actionType":"RESTORE","isFullBackup":false,"disableChecksum":false,"schedulingFrequency":0,"minNumBackupsToRetain":3,"timeBeforeDelete":0,"enableVerboseLogs":true,"alterLoadBalancer":false,"transactionalBackup":false,"parallelism":8,"disableParallelism":false,"customerUuid":"f84fdd82-9ba3-4119-8e77-97ec07df4b0c","ignoreErrors":false,"useTablespaces":false,"oldOwner":"yugabyte","backupSizeInBytes":0,"expiryTimeUnit":"DAYS","fullBackup":false,"targetXClusterConfigs":[],"sourceXClusterConfigs":[]}, hit error.
java.lang.RuntimeException: {"error": "Exception: Command '['ssh', '-o', 'StrictHostKeyChecking=no', '-o', 'UserKnownHostsFile=/dev/null', '-o', 'ControlMaster=auto', '-o', 'ControlPath=~/.ssh/ssh-%r@%h:%p', '-o', 'ControlPersist=1m', '-i', '/opt/yugabyte/yugaware/data/keys/df9d85fd-ab55-4ed2-88b6-11d1179074dd/yb-dev-aws-test_df9d85fd-ab55-4ed2-88b6-11d1179074dd-key.pem', '-p', '22', '-q', 'yugabyte@10.9.124.118', \"cd / &&  bash -c '/home/yugabyte/master/bin/yb-admin --master_addresses 10.9.103.38:7100,10.9.124.118:7100,10.9.86.236:7100 import_snapshot /tmp/yb_backup_boquugvspekvsvxi/SnapshotInfoPB db_lst_309250 --never_fsync=false'\"]' returned non-zero exit status 1."}
        at com.yugabyte.yw.commissioner.tasks.subtasks.BackupTable.run(BackupTable.java:110)
        at com.yugabyte.yw.commissioner.TaskExecutor$AbstractRunnableTask.run(TaskExecutor.java:786)
        at com.yugabyte.yw.commissioner.TaskExecutor$RunnableSubTask.run(TaskExecutor.java:1131)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at com.yugabyte.yw.common.logging.MDCAwareRunnable.run(MDCAwareRunnable.java:46)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
YW 2022-09-08T22:09:18.831Z [DEBUG] 43935018-ca8f-40c9-84a5-6d19852c1968 from TaskExecutor in TaskPool-BackupUniverse(829efd3f-cae4-465b-a111-387b07169caa)-0 - Task creator callstack:
com.yugabyte.yw.commissioner.TaskExecutor$SubTaskGroup.addSubTask(TaskExecutor.java:557)
com.yugabyte.yw.commissioner.tasks.UniverseTaskBase.createTableBackupTask(UniverseTaskBase.java:1708)
com.yugabyte.yw.commissioner.tasks.BackupUniverse.run(BackupUniverse.java:149)
com.yugabyte.yw.commissioner.TaskExecutor$AbstractRunnableTask.run(TaskExecutor.java:786)
com.yugabyte.yw.commissioner.TaskExecutor$RunnableTask.run(TaskExecutor.java:963)
java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
com.yugabyte.yw.common.logging.MDCAwareRunnable.run(MDCAwareRunnable.java:46)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:750)
YW 2022-09-08T22:09:18.832Z [DEBUG] 43935018-ca8f-40c9-84a5-6d19852c1968 from TaskExecutor in TaskPool-BackupUniverse(829efd3f-cae4-465b-a111-387b07169caa)-0 - Completed task BackupTable
YW 2022-09-08T22:09:18.833Z [ERROR] 43935018-ca8f-40c9-84a5-6d19852c1968 from TaskExecutor in TaskPool-6 - Error occurred in subtask taskType : subtasks.BackupTable, taskState: Failure
java.lang.RuntimeException: {"error": "Exception: Command '['ssh', '-o', 'StrictHostKeyChecking=no', '-o', 'UserKnownHostsFile=/dev/null', '-o', 'ControlMaster=auto', '-o', 'ControlPath=~/.ssh/ssh-%r@%h:%p', '-o',
'ControlPersist=1m', '-i', '/opt/yugabyte/yugaware/data/keys/df9d85fd-ab55-4ed2-88b6-11d1179074dd/yb-dev-aws-test_df9d85fd-ab55-4ed2-88b6-11d1179074dd-key.pem', '-p', '22', '-q', 'yugabyte@10.9.124.118', \"cd / &&
 bash -c '/home/yugabyte/master/bin/yb-admin --master_addresses 10.9.103.38:7100,10.9.124.118:7100,10.9.86.236:7100 import_snapshot /tmp/yb_backup_boquugvspekvsvxi/SnapshotInfoPB db_lst_309250 --never_fsync=false'\
"]' returned non-zero exit status 1."}
        at com.yugabyte.yw.commissioner.tasks.subtasks.BackupTable.run(BackupTable.java:110)
        at com.yugabyte.yw.commissioner.TaskExecutor$AbstractRunnableTask.run(TaskExecutor.java:786)
        at com.yugabyte.yw.commissioner.TaskExecutor$RunnableSubTask.run(TaskExecutor.java:1131)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at com.yugabyte.yw.common.logging.MDCAwareRunnable.run(MDCAwareRunnable.java:46)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
YW 2022-09-08T22:09:18.833Z [ERROR] 43935018-ca8f-40c9-84a5-6d19852c1968 from BackupUniverse in TaskPool-6 - Error executing task BackupUniverse(829efd3f-cae4-465b-a111-387b07169caa) with error='BackupTable : compl
eted 1 out of 1 tasks. failed.'.
java.lang.RuntimeException: BackupTable : completed 1 out of 1 tasks. failed.
        at com.yugabyte.yw.commissioner.TaskExecutor$RunnableTask.runSubTasks(TaskExecutor.java:1066)
        at com.yugabyte.yw.commissioner.tasks.BackupUniverse.run(BackupUniverse.java:172)
        at com.yugabyte.yw.commissioner.TaskExecutor$AbstractRunnableTask.run(TaskExecutor.java:786)
        at com.yugabyte.yw.commissioner.TaskExecutor$RunnableTask.run(TaskExecutor.java:963)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at com.yugabyte.yw.common.logging.MDCAwareRunnable.run(MDCAwareRunnable.java:46)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.RuntimeException: {"error": "Exception: Command '['ssh', '-o', 'StrictHostKeyChecking=no', '-o', 'UserKnownHostsFile=/dev/null', '-o', 'ControlMaster=auto', '-o', 'ControlPath=~/.ssh/ssh-%r@%h:
%p', '-o', 'ControlPersist=1m', '-i', '/opt/yugabyte/yugaware/data/keys/df9d85fd-ab55-4ed2-88b6-11d1179074dd/yb-dev-aws-test_df9d85fd-ab55-4ed2-88b6-11d1179074dd-key.pem', '-p', '22', '-q', 'yugabyte@10.9.124.118',
 \"cd / &&  bash -c '/home/yugabyte/master/bin/yb-admin --master_addresses 10.9.103.38:7100,10.9.124.118:7100,10.9.86.236:7100 import_snapshot /tmp/yb_backup_boquugvspekvsvxi/SnapshotInfoPB db_lst_309250 --never_fs
ync=false'\"]' returned non-zero exit status 1."}
        at com.yugabyte.yw.commissioner.tasks.subtasks.BackupTable.run(BackupTable.java:110)
        at com.yugabyte.yw.commissioner.TaskExecutor$AbstractRunnableTask.run(TaskExecutor.java:786)
        at com.yugabyte.yw.commissioner.TaskExecutor$RunnableSubTask.run(TaskExecutor.java:1131)
        ... 6 common frames omitted
YW 2022-09-08T22:09:18.834Z [DEBUG] 43935018-ca8f-40c9-84a5-6d19852c1968 from TransactionUtil in TaskPool-6 - Trying(1)...
YW 2022-09-08T22:09:18.839Z [ERROR] 43935018-ca8f-40c9-84a5-6d19852c1968 from TaskExecutor in TaskPool-6 - Failed to execute task type BackupUniverse UUID 1eac640a-d37b-47e5-9b05-b9e331e603fd details {"nodeExporter
User":"prometheus","universeUUID":"829efd3f-cae4-465b-a111-387b07169caa","enableYbc":false,"installYbc":false,"ybcInstalled":false,"encryptionAtRestConfig":{"encryptionAtRestEnabled":false,"opType":"UNDEFINED","typ
e":"DATA_KEY"},"communicationPorts":{"masterHttpPort":7000,"masterRpcPort":7100,"tserverHttpPort":9000,"tserverRpcPort":9100,"ybControllerHttpPort":14000,"ybControllerrRpcPort":18018,"redisServerHttpPort":11000,"re
disServerRpcPort":6379,"yqlServerHttpPort":12000,"yqlServerRpcPort":9042,"ysqlServerHttpPort":13000,"ysqlServerRpcPort":5433,"nodeExporterPort":9300},"extraDependencies":{"installNodeExporter":true},"firstTry":true
,"keyspace":"db*********50","sse":false,"storageConfigUUID":"aa1a91ec-9d7c-4075-88e3-23abe5a807e3","storageLocation":"s3://backups.yugabyte.com/s3Backup//univ-829efd3f-cae4-465b-a111-387b07169caa/backup-2022-09-08T
22:02:28-1616191662/keyspace-db_lst_309250","actionType":"RESTORE","isFullBackup":false,"disableChecksum":false,"schedulingFrequency":0,"minNumBackupsToRetain":3,"timeBeforeDelete":0,"enableVerboseLogs":true,"alter
LoadBalancer":false,"transactionalBackup":false,"parallelism":8,"disableParallelism":false,"customerUuid":"f84fdd82-9ba3-4119-8e77-97ec07df4b0c","ignoreErrors":false,"useTablespaces":false,"oldOwner":"yugabyte","ba
ckupSizeInBytes":0,"expiryTimeUnit":"DAYS","fullBackup":false,"targetXClusterConfigs":[],"sourceXClusterConfigs":[]}, hit error.
java.lang.RuntimeException: BackupTable : completed 1 out of 1 tasks. failed.
```
`grep OBJECT_NOT_FOUND application.log` is empty so at least it seems to be a different issue.

A few minutes earlier in the master logs I see this, not sure if related:
```
E0908 22:02:26.219274 13322 backfill_index.cc:914] Backfill Index Table(s) { idx_t1_c4_date_c11_date_c19_smallint_c45_text_c8_smallint_c29_f } failed to backfill the index: [0000454e0000300080000000000045bf] due to Illegal state (yb/tablet/tablet.cc:2074): ERROR:  Query error: schema version mismatch for table 0000454e00003000800000000000455f: expected 104, got 103
```

**Comment by def-** [comment]
@sanketkedia  New universe, new reproduction:
```
git checkout 9b545334f3e50816d1b75fca4ec5748b2442c7fe && python3.9 ./long_system_test.py --scenario=backup_restore --portal=portal-iam.dev.yugabyte.com --universe_uuid=82b35bdd-d6e5-464e-9c9b-6247d9c4084a --threads=10 --runtime=5 --complexity=full --drop
```
Failed restore again:
```
Failed to execute task {"sleepAfterMasterRestartMillis":180000,"sleepAfterTServerRestartMillis":180000,"nodeExporterUser":"prometheus","universeUUID":"82b35bdd-d6e5-464e-9c9b-6247d9c4084a","enableYbc":false,"installYbc":false,"ybcInstalled":false,"encryptionAtRestConfig":{"encryptionAtRestEnabled":false,"opType":"UNDEFINED","type":"DATA_KEY"},"communicationPorts":{"masterHttpPort":7000,"masterRpcPort":7100,"tserverHttpPort":9000,"tserverRpcPort":9100,"ybControllerHttpPort":14000,"ybControllerrRpcPort":18018,"redisS..., hit error:

{"error": "Exception: Command '['ssh', '-o', 'StrictHostKeyChecking=no', '-o', 'UserKnownHostsFile=/dev/null', '-o', 'ControlMaster=auto', '-o', 'ControlPath=~/.ssh/ssh-%r@%h:%p', '-o', 'ControlPersist=1m', '-i', '/opt/yugabyte/yugaware/data/keys/928a32f3-5978-4ca4-b512-08ffd91bd6cb/yb-dev-gcp-sarthak_928a32f3-5978-4ca4-b512-08ffd91bd6cb-key.pem', '-p', '22', '-q', 'yugabyte@10.150.0.164', \"cd / &&  bash -c '/home/yugabyte/master/bin/yb-admin --master_addresses 10.150.0.164:7100,10.150.3.186:7100,10.150.4.200:7100 import_snapshot /tmp/yb_backup_qoxgjsehpdjzqnri/SnapshotInfoPB db_lst_123988 --never_fsync=false'\"]' returned non-zero exit status 1."}.
```
Universe is available at http://portal-iam.dev.yugabyte.com/universes/82b35bdd-d6e5-464e-9c9b-6247d9c4084a/ and looks healthy otherwise.

**Comment by sanketkedia** [comment]
> W0916 01:49:59.585651 29720 backfill_index.cc:1481] TS 2c668a6fdc244beaa9932334fa0d8f7d: backfill failed for tablet b738a117cb3c4c5ca9182d28eae85476 (table t1 [id=00004d45000030008000000000004d6d]) no further retry: Illegal state (yb/tablet/tablet.cc:2056): ERROR:  Query error: schema version mismatch for table 00004d45000030008000000000004d6d: expected 37, got 36 response was error { code: OPERATION_NOT_SUPPORTED status { code: ILLEGAL_STATE message: "ERROR:  Query error: schema version mismatch for table 00004d45000030008000000000004d6d: expected 37, got 36" source_file: "../../src/yb/tablet/tablet.cc" source_line: 2056 errors: "\000" } } propagated_hybrid_time: 6812848126301859840 backfilled_until: "" failed_index_ids: "00004d45000030008000000000004c9f" number_rows_processed: 0

This error msg is causing backfill to fail when creating an index, consequently the backup doesn't include this index and thus restore complains about this index. Will investigate deeper as to how this can happen

**Comment by def-** [comment]
I get these query errors quite often with LST and have been ignoring them as there is an open bug for them already: https://github.com/yugabyte/yugabyte-db/issues/9973

**Comment by def-** [comment]
@sanketkedia do you still need the universe or should I download the logs? For cost reasons I wouldn't want to keep it around for long.
