### ISSUE TITLE
[DocDB][LST] Timed out: Timed out waiting for Create Table with enable_leader_failure_detection=false

### ISSUE THREAD

**Issue by def-** [yugabyte/yugabyte-db#13954]
Jira Link: [DB-3445](https://yugabyte.atlassian.net/browse/DB-3445)
### Description

This is a new LST test trying to set random master/tserver flags:
```
$ cd ~/code/yb-long-system-test
$ git checkout git checkout 879d8291
$ python3.9 ./long_system_test.py --complexity=full --create-destroy-local --yb-ctl-flags="--replication_factor 3" --nodes=127.0.0.1:5433,127.0.0.2:5433,127.0.0.3:5433 --runtime=5 --threads=4 --seed=210354
2022-09-09 17:03:00,450 MainThread INFO
2022-09-09 17:03:00,450 MainThread INFO     --------------------------------------------------------------------------------
2022-09-09 17:03:00,451 MainThread INFO     Running Long System Test 0.1 - https://github.com/yugabyte/yb-long-system-test/
2022-09-09 17:03:00,451 MainThread INFO     --------------------------------------------------------------------------------
2022-09-09 17:03:00,451 MainThread INFO
2022-09-09 17:03:00,461 MainThread INFO     Reproduce with: git checkout 879d8291 && ./long_system_test.py --complexity=full --create-destroy-local --yb-ctl-flags=--replication_factor 3 --nodes=127.0.0.1:5433,127.0.0.2:5433,127.0.0.3:5433 --runtime=5 --threads=4 --seed=210354
2022-09-09 17:03:00,461 MainThread INFO     /home/deen/code/yugabyte-db/bin/yb-ctl destroy
2022-09-09 17:03:03,940 MainThread INFO     /home/deen/code/yugabyte-db/bin/yb-ctl --replication_factor 3 create --tserver_flags=enable_leader_failure_detection=false --master_flags=enable_automatic_tablet_splitting=false
2022-09-09 17:03:15,107 MainThread INFO     Database version: PostgreSQL 11.2-YB-2.15.3.0-b0 on x86_64-pc-linux-gnu, compiled by clang version 13.0.1 (https://github.com/yugabyte/llvm-project.git 0131d8e1a20f72a0f374979985db4c2871be71bc), 64-bit
2022-09-09 17:03:15,109 MainThread INFO     Creating tables for database db_lst_210354
Traceback (most recent call last):
  File "/home/deen/code/yb-long-system-test/./long_system_test.py", line 564, in <module>
    main()
  File "/home/deen/code/yb-long-system-test/./long_system_test.py", line 555, in main
    lst.run()
  File "/home/deen/code/yb-long-system-test/./long_system_test.py", line 428, in run
    self._create_tables()
  File "/home/deen/code/yb-long-system-test/./long_system_test.py", line 221, in _create_tables
    self.database.create_relations(cur)
  File "/home/deen/code/yb-long-system-test/lst/dbobject.py", line 280, in create_relations
    table.create(cur)
  File "/home/deen/code/yb-long-system-test/lst/dbobject.py", line 136, in create
    self.execute(cur, query)
  File "/home/deen/code/yb-long-system-test/lst/dbobject.py", line 26, in execute
    raise e
  File "/home/deen/code/yb-long-system-test/lst/dbobject.py", line 19, in execute
    cur.execute(query)
psycopg2.errors.InternalError_: Timed out: Timed out waiting for Create Table
```
[lst_2022-09-09_17:03:00_210354.zip](https://github.com/yugabyte/yugabyte-db/files/9537770/lst_2022-09-09_17.03.00_210354.zip)
Yugabyte-data directory accessible from Yugabyte org: https://drive.google.com/file/d/1_jGivfLlgoOBFb0zWrQuoVuRQVhjN_CN/view?usp=sharing
It can be reproduced:
```
$ cd ~/code/yugabyte-db
$ bin/yb-ctl --replication_factor 3 create --tserver_flags=enable_leader_failure_detection=false
CREATE TABLE t0(c0_json JSON NOT NULL,
  c1_json JSON NOT NULL DEFAULT '{"a": 6, "b": ["0", "1", "2", "3", "4", "5", "6", "7"], "c": false}'::json,
  c2_jsonb JSONB NOT NULL DEFAULT '{"a": 2, "b": ["0", "1", "2", "3"], "c": false}'::jsonb,
  c3_daterange DATERANGE) SPLIT INTO 47 TABLETS;
```
Works fine without `--tserver_flags=enable_leader_failure_detection=false`

**Comment by def-** [comment]
The tserver logs contain a lot of:
```
E0909 18:04:17.401957 2882849 tablet_metadata.cc:497] Failed to destroy regular DB at: /home/deen/yugabyte-data/node-2/disk-1/yb-data/tserver/data/rocksdb/table-f6848c97aa8c407abfa0d5d9f3fb36e9/tablet-69872de8863b4dac8094bbc237abba71: IO error (yb/rocksdb/util/env_posix.cc:317): /home/deen/yugabyte-data/node-2/disk-1/yb-data/tserver/data/rocksdb/table-f6848c97aa8c407abfa0d5d9f3fb36e9/tablet-69872de8863b4dac8094bbc237abba71/LOCK: No such file or directory
```

**Comment by bmatican** [comment]
@def- why are we testing with `enable_leader_failure_detection=false` ?

**Comment by def-** [comment]
It was one of the available flags. I'm not sure if it makes sense to test all of them or only a specific subset. (and if so how to figure out that subset)
