### ISSUE TITLE
[Spark connector] Unsupported data source V2 partitioning type: CassandraPartitioning

### ISSUE THREAD

**Issue by tedyu** [yugabyte/yugabyte-db#14086]
Jira Link: [DB-3579](https://yugabyte.atlassian.net/browse/DB-3579)
### Description

Spark 3.3 introduced V2 partitioning.
CassandraPartitioning (in Spark connector) is not recognized :
```
java.lang.IllegalArgumentException: Unsupported data source V2 partitioning type: CassandraPartitioning
    at org.apache.spark.sql.execution.datasources.v2.V2ScanPartitioning$$anonfun$apply$1.applyOrElse(V2ScanPartitioning.scala:46)
    at org.apache.spark.sql.execution.datasources.v2.V2ScanPartitioning$$anonfun$apply$1.applyOrElse(V2ScanPartitioning.scala:34)
    at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformDownWithPruning$1(TreeNode.scala:584)
    at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:176)
    at org.apache.spark.sql.catalyst.trees.TreeNode.transformDownWithPruning(TreeNode.scala:584)
```

**Comment by tedyu** [comment]
Fixed via Spark commit:

commit 08044ec3ce35f263ae5356816aa20601456590c7
Author: Ted Yu <yuzhihong@gmail.com>
Date:   Wed Sep 21 09:41:22 2022 -0700

    [SPARK-40508][SQL] Treat unknown partitioning as UnknownPartitioning
