### ISSUE TITLE
[yugabyted] [QA] [Mac] advertise_address is required for secure connection to work

### ISSUE THREAD

**Issue by zlareb1-yb** [yugabyte/yugabyte-db#14110]
### Description

**Secure connection to yugabyted without advertise_address**:
```
MacBook-Pro-16-inch-2021:yugabyte-2.15.3.0 mzafar$ ./bin/yugabyted start --secure --certs_dir ~/certs/127.0.0.1
Starting yugabyted...
✅ System checks           
✅ YugabyteDB Started                  
- Enabling SSL Authentication...Could not update Postgress user password. Exception: Traceback (most recent call last):
  File "./bin/yugabyted", line 1583, in update_db_passwords
    retry_op_with_argument(ysql_proxy.try_update_password, new_password, timeout=60)
  File "./bin/yugabyted", line 3710, in retry_op_with_argument
    now - start_time))
RuntimeError: Failed after retrying operation for 60.5155160427 secs.
```

**Secure connection to yugabyted with advertise_address**:
```
MacBook-Pro-16-inch-2021:yugabyte-2.15.3.0 mzafar$ ./bin/yugabyted start --secure --certs_dir ~/certs/127.0.0.1 --advertise_address=127.0.0.1
Starting yugabyted...
✅ System checks           
✅ YugabyteDB Started                  
✅ SSL Authentication enabled.   
✅ User Authentication enabled.
YugabyteDB Started

+----------------------------------------------------------------------------------------------------------+
|                                                yugabyted                                                 |
+----------------------------------------------------------------------------------------------------------+
| Status              : Running.                                                                           |
| Replication Factor  : 1                                                                                  |
| Web console         : http://127.0.0.1:7000                                                              |
| JDBC                : jdbc:postgresql://127.0.0.1:5433/yugabyte?user=yugabyte&password=2FCAvI1jDZPn      |
| YSQL                : bin/ysqlsh   -U yugabyte -d yugabyte                                               |
| YCQL                : bin/ycqlsh   -u cassandra --ssl                                                    |
| Data Dir            : /Users/mzafar/var/data                                                             |
| Log Dir             : /Users/mzafar/var/logs                                                             |
| Universe UUID       : e89f6cfb-79a1-4cdd-968c-2095010e62cd                                               |
+----------------------------------------------------------------------------------------------------------+
🚀 YugabyteDB started successfully! To load a sample dataset, try 'yugabyted demo'.
🎉 Join us on Slack at https://www.yugabyte.com/slack
👕 Claim your free t-shirt at https://www.yugabyte.com/community-rewards/

Credentials File is stored at /Users/mzafar/var/data/yugabyted_credentials.txt

```

**Error Logs** - 
```
<< ERR >>
ysqlsh: FATAL:  Network error: Handshake failed: Network error (yb/rpc/secure_stream.cc:1106): Endpoint does not match, address: 0.0.0.0, hostname: 0.0.0.0
FATAL:  Network error: Handshake failed: Network error (yb/rpc/secure_stream.cc:1106): Endpoint does not match, address: 0.0.0.0, hostname: 0.0.0.0
```
Looks like the server is trying to connect to 0.0.0.0 instead of 127.0.0.1 here

**Build** - 2.15.3.0-b211

**Comment by gargsans-yb** [comment]
This is not valid after the [commit](https://github.com/yugabyte/yugabyte-db/commit/3c579971097bebacf0822ad45424174b281ac813) for secure deployment through yugabyted (Phase 2). Now advertise_address is not a requirement for secure deployment in Mac.
