### ISSUE TITLE
[yugabyted] Yugabyted fails to start after a host restart.

### ISSUE THREAD

**Issue by renjith-yb** [yugabyte/yugabyte-db#14111]
### Description

Environment - Centos 7

- Installed 2.15.3-b199 build and ran the post install script - ./bin/post_install.sh
- Started - ./bin/yugabyted start , was able to access the UI , created few databases/ tables 

- Added 2 more more node using ./bin/yugabyted start  --join 
- Added nodes were visible from on UI and was able to query from all the nodes .

Powered off and restarted all the VMs

On the first VM 
 after restart checked status of yugabyted ( bin/yugabyted status) was shown as Stopped
Tried starting  yugabyted (/bin/yugabyted start) -

Observed behaviour 
Db node fails to start
- Status: Status command timed out as YugabyteDB "yb-master" process is not responding. 
- 
from the yugabyted.log
```

<< ERR >>
Timed out (yb/rpc/outbound_call.cc:547): Unable to establish connection to leader master at [10.9.139.128:7100]. Please verify the addresses and check if server is up, or if y
ou're missing --certs_dir_name.

: Could not locate the leader master: Call timed out before sending

<<
[yugabyted start] 2022-09-21 05:50:41,295 INFO:  | 180.5s | Got all masters: []
[yugabyted start] 2022-09-21 05:50:41,295 INFO:  | 180.5s | Failed to query for all masters. Exception: Traceback (most recent call last):
  File "bin/yugabyted", line 1344, in wait_get_all_masters
    return retry_op(self.get_all_masters, timeout)
  File "bin/yugabyted", line 3693, in retry_op
    now - start_time))
RuntimeError: Failed after retrying operation for 60.0886039734 secs.
[yugabyted start] 2022-09-21 06:34:56,825 INFO: Callhome failed: HTTP Error 502: Bad Gateway
[yugabyted start] 2022-09-21 08:53:47,335 ERROR: master died unexpectedly. Restarting...
[yugabyted start] 2022-09-21 08:53:47,336 INFO: About to start master with cmd /home/centos/yugabyte-2.15.3.0/bin/yb-master --stop_on_parent_termination --undefok=stop_on_pare
nt_termination --fs_data_dirs=/home/centos/var/data --webserver_interface=10.9.139.128 --metrics_snapshotter_tserver_metrics_whitelist=handler_latency_yb_tserver_TabletServerS
ervice_Read_count,handler_latency_yb_tserver_TabletServerService_Write_count,handler_latency_yb_tserver_TabletServerService_Read_sum,handler_latency_yb_tserver_TabletServerSer
vice_Write_sum,disk_usage,cpu_usage,node_up --yb_num_shards_per_tserver=1 --ysql_num_shards_per_tserver=1 --placement_cloud=cloud1 --placement_region=datacenter1 --placement_z
one=rack1 --rpc_bind_addresses=10.9.139.128:7100 --server_broadcast_addresses=10.9.139.128:7100 --re[yugabyted start] 2022-09-21 08:53:47,341 INFO: master started running with
 PID 10297.
[yugabyted start] 2022-09-21 08:53:47,343 ERROR: Traceback (most recent call last):
  File "bin/yugabyted", line 2377, in run
    args.func()
  File "bin/yugabyted", line 352, in start
    self.start_processes()
  File "bin/yugabyted", line 1027, in start_processes
    process.start()
  File "bin/yugabyted", line 2764, in start
    super(YBProcessManager, self).start()
  File "bin/yugabyted", line 2583, in start
    self.write_pid(self.process.pid)
  File "bin/yugabyted", line 2600, in write_pid
    Output.log("{} started running with PID {}.".format(self.name, pid))
IOError: [Errno 28] No space left on device

For more information, check the logs in /home/centos/var/logs
[yugabyted start] 2022-09-21 08:53:47,343 INFO: Shutting down...
```
[yugabyted.log](https://github.com/yugabyte/yugabyte-db/files/9617389/yugabyted.log)

**Comment by nchandrappa** [comment]
The root cause may be similar to the #14440 issue where the master leader has changed and cannot reach a quorum.
