### ISSUE TITLE
[CDC + xCluster + Upgrade] Table enabled for both CDC + xCluster, after upgrade only table data enabled for both is not getting ingested to target

### ISSUE THREAD

**Issue by shamanthchandra-yb** [yugabyte/yugabyte-db#14159]
Jira Link: [DB-3632](https://yugabyte.atlassian.net/browse/DB-3632)
### Description

**Here is the slack thread:**
https://yugabyte.slack.com/archives/CHC5RSY74/p1663926522479249

**Steps:**
It's a LRU setup, which had 2 tables. One enabled for only CDC and other for both CDC + xCluster.
employees_1 (was also enabled for xcluster)
cdc_test (only cdc enabled, without xcluster)
After upgrade table which was enabled for both xcluster and cdc, is no longer getting data to target. Below trace is seen in connector log at exact same time when it has stopped.

Note: Table which is only enabled for cdc is still working fine.

Note: Upgrade was done for both source and target to b220(from b77) - Upgrade went well, Healthchecks are fine, workloads are running - Observed lag is increasing periodically after upgrade.

`2022-09-23 08:10:57,774 WARN   YugabyteDB|dbserver1|streaming  GetChangesCDCSDK got Errback    [org.yb.client.AsyncYBClient]
org.yb.client.CDCErrorException: Server[93f31d85cbd149739e1dad0b1cbe089d] INTERNAL_ERROR[code 21]: CDCSDK Trying to fetch already GCed intents for transaction 7cbb4da2-f1bc-46e3-acc3-00cd96298bcd
        at org.yb.client.TabletClient.dispatchCDCErrorOrReturnException(TabletClient.java:495)
        at org.yb.client.TabletClient.decode(TabletClient.java:426)
        at org.yb.client.TabletClient.decode(TabletClient.java:87)
        at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:500)
        at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.yb.client.TabletClient.handleUpstream(TabletClient.java:641)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.jboss.netty.handler.timeout.ReadTimeoutHandler.messageReceived(ReadTimeoutHandler.java:184)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
        at org.yb.client.AsyncYBClient$TabletClientPipeline.sendUpstream(AsyncYBClient.java:2525)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
        at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
org.yb.client.CDCErrorException: Server[93f31d85cbd149739e1dad0b1cbe089d] INTERNAL_ERROR[code 21]: CDCSDK Trying to fetch already GCed intents for transaction 7cbb4da2-f1bc-46e3-acc3-00cd96298bcd
        at org.yb.client.TabletClient.dispatchCDCErrorOrReturnException(TabletClient.java:495)
        at org.yb.client.TabletClient.decode(TabletClient.java:426)
        at org.yb.client.TabletClient.decode(TabletClient.java:87)
        at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:500)
        at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.yb.client.TabletClient.handleUpstream(TabletClient.java:641)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.jboss.netty.handler.timeout.ReadTimeoutHandler.messageReceived(ReadTimeoutHandler.java:184)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
        at org.yb.client.AsyncYBClient$TabletClientPipeline.sendUpstream(AsyncYBClient.java:2525)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
        at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)`

[connector_logs_LRU.txt](https://github.com/yugabyte/yugabyte-db/files/9633963/connector_logs_LRU.txt)

Also, xCluster tserver.log

```
W0923 08:58:47.796535  6364 long_operation_tracker.cc:117] Read running for 1.000s in thread 7014:
    @          0x41bd1c0  YbgSetCurrentMemoryContext
    @          0x2f655c6  yb::docdb::DocPgExprExecutor::Exec()
    @          0x2fdc424  yb::docdb::PgsqlReadOperation::ExecuteScalar()
    @          0x35934e6  yb::tablet::AbstractTablet::ProcessPgsqlReadRequest()
    @          0x35d0303  yb::tablet::Tablet::HandlePgsqlReadRequest()
    @          0x378c2db  yb::tserver::(anonymous namespace)::ReadQuery::Complete()
    @          0x3786663  yb::tserver::PerformRead()
    @          0x37cdba1  yb::tserver::TabletServiceImpl::Read()
    @          0x38bd0cc  std::__1::__function::__func<>::operator()()
    @          0x38beae3  yb::tserver::TabletServerServiceIf::Handle()
    @          0x351b7fb  yb::rpc::ServicePoolImpl::Handle()
    @          0x3460d62  yb::rpc::InboundCall::InboundCallTask::Run()
    @          0x352a778  yb::rpc::(anonymous namespace)::Worker::Execute()
    @          0x3b2e3a1  yb::Thread::SuperviseThread()
    @     0x7f716954d693  start_thread
    @     0x7f7169a4f41c  __clone
W0923 08:58:47.834420  6364 long_operation_tracker.cc:117] Read running for 1.038s in thread 6758:
    @     0x7f7169a40e62  __GI___pread
    @          0x3acc980  yb::PosixRandomAccessFile::Read()
    @          0x3acb8ca  yb::RandomAccessFile::ReadAndValidate()
    @          0x340e575  rocksdb::RandomAccessFileReader::ReadAndValidate()
    @          0x33e1c11  rocksdb::ReadBlockContents()
    @          0x33d7b3d  rocksdb::block_based_table::ReadBlockFromFile()
    @          0x33d6c46  rocksdb::BlockBasedTable::RetrieveBlock()
    @          0x33d97cf  rocksdb::BlockBasedTable::NewDataBlockIterator()
    @          0x3400960  rocksdb::(anonymous namespace)::TwoLevelIterator::InitDataBlock()
    @          0x3400343  rocksdb::(anonymous namespace)::TwoLevelIterator::Seek()
    @          0x33ee823  rocksdb::MergingIterator::Seek()
    @          0x334f156  rocksdb::DBIter::Seek()
    @          0x2face01  yb::docdb::PerformRocksDBSeek()
    @          0x2fb69b0  yb::docdb::IntentAwareIterator::SeekForwardRegular()
    @          0x2fb67c7  yb::docdb::IntentAwareIterator::SeekForward()
    @          0x2f6f1ec  yb::docdb::DocDBTableReader::GetHelper::DoHandleRecord()

```

cc: @Arjun-yb

**Comment by Arjun-yb** [comment]
Lag is increasing periodically for the table(which is used in both xCluster and CDC setup). And we observed that last_replication_time on Source is old for the xCluster stream for some tablets. That's why the replication lag is increasing periodically.
cc: @shahrooz1997 @lingamsandeep

**Comment by sureshdash2022-yb** [comment]
we have fixed this issue as part https://phabricator.dev.yugabyte.com/D19878 diff, so closing this issue
