### ISSUE TITLE
[YCQL] TestReturnsClause#testReturnsStatusWithIndex fails in several build types

### ISSUE THREAD

**Issue by tedyu** [yugabyte/yugabyte-db#14205]
Jira Link: [DB-3670](https://yugabyte.atlassian.net/browse/DB-3670)
### Description

From https://detective-gcp.dev.yugabyte.com/job/yugabyte-db-phabricator%2F33244%2Fartifact%2Fjava%2Fyb-cql%2Ftarget%2Fsurefire-reports_org.yb.cql.TestReturnsClause__testReturnsStatusWithIndex%2Forg.yb.cql.TestReturnsClause-output.txt.gz?class=org.yb.cql.TestReturnsClause&name=testReturnsStatusWithIndex 
```
22:58:44.988 (Time-limited test) [INFO - org.yb.cql.BaseCQLTest.tearDownAfter(BaseCQLTest.java:267)] BaseCQLTest.tearDownAfter: finished attempting to drop tables and trying to close CQL session/client
22:58:44.990 (main) [ERROR - org.yb.BaseYBTest$1$2.logEventDetails(BaseYBTest.java:243)] YB Java test failed: class="org.yb.cql.TestReturnsClause", method="testReturnsStatusWithIndex"
org.junit.ComparisonFailure: expected:<Row[[false, Duplicate value disallowed by unique index test_rs_pk_idx], NULL, NULL, NULL, ...> but was:<Row[[true, NULL], NULL, NULL, NULL, ...>
    at org.junit.Assert.assertEquals(Assert.java:115)
    at org.junit.Assert.assertEquals(Assert.java:144)
    at org.yb.AssertionWrappers.lambda$assertEquals$7(AssertionWrappers.java:140)
    at org.yb.AssertionWrappers.wrapAssertion(AssertionWrappers.java:45)
    at org.yb.AssertionWrappers.assertEquals(AssertionWrappers.java:140)
    at org.yb.cql.BaseCQLTest.assertQuery(BaseCQLTest.java:592)
    at org.yb.cql.BaseCQLTest.assertQuery(BaseCQLTest.java:596)
    at org.yb.cql.TestReturnsClause.checkReturnStatus(TestReturnsClause.java:78)
    at org.yb.cql.TestReturnsClause.testReturnsStatusWithIndex(TestReturnsClause.java:255)
```
This seems to be regression.

**Comment by tedyu** [comment]
I am a bit curious: the race condition is long standing.
But this test started failing across the board recently.

I wonder if this is a regression.

**Comment by joe-maley** [comment]
@tedyu It's not a regression. It started failing more recently because feec0ad significantly decreased the time that it takes to create an index table, which increases the likelihood of this race taking the failure path.
