### ISSUE TITLE
[DocDB] LeakSanitizer error in several index tests

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#14228]
Jira Link: [DB-3688](https://yugabyte.atlassian.net/browse/DB-3688)
### Description

https://detective-gcp.dev.yugabyte.com/stability/test?branch=master&build_type=all&class=CqlIndexTest&fail_tag=memory_leak&name=TxnCleanup&platform=linux

https://detective-gcp.dev.yugabyte.com/stability/test?branch=master&build_type=all&class=TestQLCreateIndex&fail_tag=memory_leak&name=TestQLCreateIndexDefaultName&platform=linux

https://detective-gcp.dev.yugabyte.com/stability/test?branch=master&build_type=all&class=TestQLCreateIndex&fail_tag=memory_leak&name=TestQLCreateIndexExpr&platform=linux

```
Indirect leak of 1600 byte(s) in 1 object(s) allocated from:
    #0 0x7f75c24db15d in operator new(unsigned long) /opt/yb-build/llvm/yb-llvm-v13.0.1-yb-2-1659059078-0131d8e1-almalinux8-x86_64-build/src/llvm-project/compiler-rt/lib/asan/asan_new_delete.cpp:95:3
    #1 0x7f75c08052a3 in void* std::__1::__libcpp_operator_new<unsigned long>(unsigned long) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20220924220949-f77b91747b-almalinux8-x86_64-clang13/installed/asan/libcxx/include/c++/v1/new:235:10
    #2 0x7f75c08052a3 in std::__1::__libcpp_allocate(unsigned long, unsigned long) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20220924220949-f77b91747b-almalinux8-x86_64-clang13/installed/asan/libcxx/include/c++/v1/new:261:10
    #3 0x7f75c08052a3 in std::__1::allocator<std::__1::shared_ptr<yb::server::MonitoredTask> >::allocate(unsigned long) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20220924220949-f77b91747b-almalinux8-x86_64-clang13/installed/asan/libcxx/include/c++/v1/__memory/allocator.h:108:38
    #4 0x7f75c08052a3 in boost::circular_buffer<std::__1::shared_ptr<yb::server::MonitoredTask>, std::__1::allocator<std::__1::shared_ptr<yb::server::MonitoredTask> > >::allocate(unsigned long) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20220924220949-f77b91747b-almalinux8-x86_64-clang13/installed/asan/include/boost/circular_buffer/base.hpp:2396:39
    #5 0x7f75c08049f4 in boost::circular_buffer<std::__1::shared_ptr<yb::server::MonitoredTask>, std::__1::allocator<std::__1::shared_ptr<yb::server::MonitoredTask> > >::initialize_buffer(unsigned long) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20220924220949-f77b91747b-almalinux8-x86_64-clang13/installed/asan/include/boost/circular_buffer/base.hpp:2494:18
    #6 0x7f75c08049f4 in boost::circular_buffer<std::__1::shared_ptr<yb::server::MonitoredTask>, std::__1::allocator<std::__1::shared_ptr<yb::server::MonitoredTask> > >::circular_buffer(unsigned long, std::__1::allocator<std::__1::shared_ptr<yb::server::MonitoredTask> > const&) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20220924220949-f77b91747b-almalinux8-x86_64-clang13/installed/asan/include/boost/circular_buffer/base.hpp:1039:9
    #7 0x7f75c08037fe in yb::master::TasksTracker::TasksTracker(yb::StronglyTypedBool<yb::master::IsUserInitiated_Tag>) ${BUILD_ROOT}/../../src/yb/master/tasks_tracker.cc:40:7
    #8 0x7f75c02c152f in yb::master::CatalogManager::CatalogManager(yb::master::Master*) ${BUILD_ROOT}/../../src/yb/master/catalog_manager.cc:847:26
    #9 0x7f75c060d897 in yb::master::enterprise::CatalogManager::CatalogManager(yb::master::Master*) ${BUILD_ROOT}/../../ent/src/yb/master/catalog_manager.h:34:9
    #10 0x7f75c0600c10 in yb::master::Master::Master(yb::master::MasterOptions const&) ${BUILD_ROOT}/../../src/yb/master/master.cc:149:28
    #11 0x7f75c0a22c9d in yb::master::enterprise::Master::Master(yb::master::MasterOptions const&) ${BUILD_ROOT}/../../ent/src/yb/master/master_ent.cc:39:45
    #12 0x7f75c06f2545 in yb::master::MiniMaster::StartOnPorts(unsigned short, unsigned short, yb::master::MasterOptions*) ${BUILD_ROOT}/../../src/yb/master/mini_master.cc:164:38
    #13 0x7f75c06f1413 in yb::master::MiniMaster::StartDistributedMasterOnPorts(unsigned short, unsigned short, std::__1::vector<unsigned short, std::__1::allocator<unsigned short> > const&) ${BUILD_ROOT}/../../src/yb/master/mini_master.cc:205:10
    #14 0x7f75c06f087c in yb::master::MiniMaster::StartDistributedMaster(std::__1::vector<unsigned short, std::__1::allocator<unsigned short> > const&) ${BUILD_ROOT}/../../src/yb/master/mini_master.cc:88:10
    #15 0x7f75c11dda72 in yb::MiniCluster::StartMasters() ${BUILD_ROOT}/../../src/yb/integration-tests/mini_cluster.cc:258:37
    #16 0x7f75c11db8ee in yb::MiniCluster::Start(std::__1::vector<yb::tserver::TabletServerOptions, std::__1::allocator<yb::tserver::TabletServerOptions> > const&) ${BUILD_ROOT}/../../src/yb/integration-tests/mini_cluster.cc:206:3
    #17 0x7f75c2e94f4a in yb::CqlTestBase<yb::MiniCluster>::SetUp() ${BUILD_ROOT}/../../src/yb/integration-tests/cql_test_base.cc:87:3
    #18 0x7f75b3bfa2ef in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20220924220949-f77b91747b-almalinux8-x86_64-clang13/src/googletest-1.12.1/googletest/src/gtest.cc:2599:10
    #19 0x7f75b3bfa2ef in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20220924220949-f77b91747b-almalinux8-x86_64-clang13/src/googletest-1.12.1/googletest/src/gtest.cc:2635:14
    #20 0x7f75b3badaad in testing::Test::Run() /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20220924220949-f77b91747b-almalinux8-x86_64-clang13/src/googletest-1.12.1/googletest/src/gtest.cc:2669:3
    #21 0x7f75b3baf90f in testing::TestInfo::Run() /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20220924220949-f77b91747b-almalinux8-x86_64-clang13/src/googletest-1.12.1/googletest/src/gtest.cc:2853:11
    #22 0x7f75b3bb1ea0 in testing::TestSuite::Run() /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20220924220949-f77b91747b-almalinux8-x86_64-clang13/src/googletest-1.12.1/googletest/src/gtest.cc:3012:30
    #23 0x7f75b3bd9736 in testing::internal::UnitTestImpl::RunAllTests() /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20220924220949-f77b91747b-almalinux8-x86_64-clang13/src/googletest-1.12.1/googletest/src/gtest.cc:5870:44
    #24 0x7f75b3bfee3a in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20220924220949-f77b91747b-almalinux8-x86_64-clang13/src/googletest-1.12.1/googletest/src/gtest.cc:2599:10
    #25 0x7f75b3bfee3a in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20220924220949-f77b91747b-almalinux8-x86_64-clang13/src/googletest-1.12.1/googletest/src/gtest.cc:2635:14
    #26 0x7f75b3bd836c in testing::UnitTest::Run() /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20220924220949-f77b91747b-almalinux8-x86_64-clang13/src/googletest-1.12.1/googletest/src/gtest.cc:5444:10
    #27 0x7f75c2e6c6e0 in RUN_ALL_TESTS() /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20220924220949-f77b91747b-almalinux8-x86_64-clang13/installed/asan/include/gtest/gtest.h:2293:73
    #28 0x7f75c2e6c6e0 in main ${BUILD_ROOT}/../../src/yb/util/test_main.cc:109:13
    #29 0x7f75ae8d6cf2 in __libc_start_main (/lib64/libc.so.6+0x3acf2)

Objects leaked above:
0x61b000003880 (1600 bytes)

Indirect leak of 888 byte(s) in 1 object(s) allocated from:
    #0 0x7f75c24db15d in operator new(unsigned long) /opt/yb-build/llvm/yb-llvm-v13.0.1-yb-2-1659059078-0131d8e1-almalinux8-x86_64-build/src/llvm-project/compiler-rt/lib/asan/asan_new_delete.cpp:95:3
    #1 0x7f75c042b8a9 in scoped_refptr<yb::master::TableInfo> make_scoped_refptr<yb::master::TableInfo, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, scoped_refptr<yb::master::TasksTracker>&>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, scoped_refptr<yb::master::TasksTracker>&) ${BUILD_ROOT}/../../src/yb/gutil/ref_counted.h:436:27
    #2 0x7f75c03e3801 in yb::master::CatalogManager::NewTableInfo(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) ${BUILD_ROOT}/../../src/yb/master/catalog_manager.cc:11365:10
    #3 0x7f75c032d1d7 in yb::master::CatalogManager::CreateTableInfo(yb::master::CreateTableRequestPB const&, yb::Schema const&, yb::PartitionSchema const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, yb::IndexInfoPB*) ${BUILD_ROOT}/../../src/yb/master/catalog_manager.cc:4833:36
    #4 0x7f75c02e16fd in yb::master::CatalogManager::CreateTableInMemory(yb::master::CreateTableRequestPB const&, yb::Schema const&, yb::PartitionSchema const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::vector<yb::Partition, std::__1::allocator<yb::Partition> > const&, yb::IndexInfoPB*, std::__1::vector<scoped_refptr<yb::master::TabletInfo>, std::__1::allocator<scoped_refptr<yb::master::TabletInfo> > >*, yb::master::CreateTableResponsePB*, scoped_refptr<yb::master::TableInfo>*) ${BUILD_ROOT}/../../src/yb/master/catalog_manager.cc:4252:12
    #5 0x7f75c031be79 in yb::master::CatalogManager::CreateTable(yb::master::CreateTableRequestPB const*, yb::master::CreateTableResponsePB*, yb::rpc::RpcContext*) ${BUILD_ROOT}/../../src/yb/master/catalog_manager.cc:3850:5
    #6 0x7f75c0657582 in void yb::master::MasterServiceBase::HandleIn<yb::master::CatalogManager, yb::master::CreateTableRequestPB, yb::master::CreateTableResponsePB>(yb::master::CreateTableRequestPB const*, yb::master::CreateTableResponsePB*, yb::rpc::RpcContext*, yb::Status (yb::master::CatalogManager::*)(yb::master::CreateTableRequestPB const*, yb::master::CreateTableResponsePB*, yb::rpc::RpcContext*), char const*, int, char const*, yb::StronglyTypedBool<yb::master::HoldCatalogLock_Tag>)::'lambda'()::operator()() const ${BUILD_ROOT}/../../src/yb/master/master_service_base-internal.h:146:14
    #7 0x7f75c0657582 in void yb::master::MasterServiceBase::HandleOnLeader<yb::master::CreateTableRequestPB, yb::master::CreateTableResponsePB, void yb::master::MasterServiceBase::HandleIn<yb::master::CatalogManager, yb::master::CreateTableRequestPB, yb::master::CreateTableResponsePB>(yb::master::CreateTableRequestPB const*, yb::master::CreateTableResponsePB*, yb::rpc::RpcContext*, yb::Status (yb::master::CatalogManager::*)(yb::master::CreateTableRequestPB const*, yb::master::CreateTableResponsePB*, yb::rpc::RpcContext*), char const*, int, char const*, yb::StronglyTypedBool<yb::master::HoldCatalogLock_Tag>)::'lambda'()>(yb::master::CatalogManager const*, yb::master::CreateTableRequestPB*, yb::rpc::RpcContext*, yb::master::CreateTableResponsePB, char const*, int, char const*, yb::StronglyTypedBool<yb::master::HoldCatalogLock_Tag>) ${BUILD_ROOT}/../../src/yb/master/master_service_base-internal.h:84:20
    #8 0x7f75c0651913 in void yb::master::MasterServiceBase::HandleIn<yb::master::CatalogManager, yb::master::CreateTableRequestPB, yb::master::CreateTableResponsePB>(yb::master::CreateTableRequestPB const*, yb::master::CreateTableResponsePB*, yb::rpc::RpcContext*, yb::Status (yb::master::CatalogManager::*)(yb::master::CreateTableRequestPB const*, yb::master::CreateTableResponsePB*, yb::rpc::RpcContext*), char const*, int, char const*, yb::StronglyTypedBool<yb::master::HoldCatalogLock_Tag>) ${BUILD_ROOT}/../../src/yb/master/master_service_base-internal.h:145:3
    #9 0x7f75c0651913 in yb::master::(anonymous namespace)::MasterDdlServiceImpl::CreateTable(yb::master::CreateTableRequestPB const*, yb::master::CreateTableResponsePB*, yb::rpc::RpcContext) ${BUILD_ROOT}/../../src/yb/master/master_ddl_service.cc:29:3
    #10 0x7f75b82deedc in yb::master::MasterDdlIf::InitMethods(scoped_refptr<yb::MetricEntity> const&)::$_0::operator()(std::__1::shared_ptr<yb::rpc::InboundCall>) const::'lambda'(yb::master::CreateTableRequestPB const*, yb::master::CreateTableResponsePB*, yb::rpc::RpcContext)::operator()(yb::master::CreateTableRequestPB const*, yb::master::CreateTableResponsePB*, yb::rpc::RpcContext) const ${BUILD_ROOT}/src/yb/master/master_ddl.service.cc:648:9
    #11 0x7f75b82deedc in auto yb::rpc::HandleCall<yb::rpc::RpcCallPBParamsImpl<yb::master::CreateTableRequestPB, yb::master::CreateTableResponsePB>, yb::master::MasterDdlIf::InitMethods(scoped_refptr<yb::MetricEntity> const&)::$_0::operator()(std::__1::shared_ptr<yb::rpc::InboundCall>) const::'lambda'(yb::master::CreateTableRequestPB const*, yb::master::CreateTableResponsePB*, yb::rpc::RpcContext)>(std::__1::shared_ptr<yb::rpc::InboundCall>, yb::master::MasterDdlIf::InitMethods(scoped_refptr<yb::MetricEntity> const&)::$_0::operator()(std::__1::shared_ptr<yb::rpc::InboundCall>) const::'lambda'(yb::master::CreateTableRequestPB const*, yb::master::CreateTableResponsePB*, yb::rpc::RpcContext)) ${BUILD_ROOT}/../../src/yb/rpc/local_call.h:124:7
    #12 0x7f75b82de586 in yb::master::MasterDdlIf::InitMethods(scoped_refptr<yb::MetricEntity> const&)::$_0::operator()(std::__1::shared_ptr<yb::rpc::InboundCall>) const ${BUILD_ROOT}/src/yb/master/master_ddl.service.cc:646:7
    #13 0x7f75b82de586 in decltype(static_cast<yb::master::MasterDdlIf::InitMethods(scoped_refptr<yb::MetricEntity> const&)::$_0&>(fp)(static_cast<std::__1::shared_ptr<yb::rpc::InboundCall>>(fp0))) std::__1::__invoke<yb::master::MasterDdlIf::InitMethods(scoped_refptr<yb::MetricEntity> const&)::$_0&, std::__1::shared_ptr<yb::rpc::InboundCall> >(yb::master::MasterDdlIf::InitMethods(scoped_refptr<yb::MetricEntity> const&)::$_0&, std::__1::shared_ptr<yb::rpc::InboundCall>&&) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20220924220949-f77b91747b-almalinux8-x86_64-clang13/installed/asan/libcxx/include/c++/v1/type_traits:3918:1
    #14 0x7f75b82de2dc in void std::__1::__invoke_void_return_wrapper<void, true>::__call<yb::master::MasterDdlIf::InitMethods(scoped_refptr<yb::MetricEntity> const&)::$_0&, std::__1::shared_ptr<yb::rpc::InboundCall> >(yb::master::MasterDdlIf::InitMethods(scoped_refptr<yb::MetricEntity> const&)::$_0&, std::__1::shared_ptr<yb::rpc::InboundCall>&&) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20220924220949-f77b91747b-almalinux8-x86_64-clang13/installed/asan/libcxx/include/c++/v1/__functional/invoke.h:61:9
    #15 0x7f75b82de2dc in std::__1::__function::__alloc_func<yb::master::MasterDdlIf::InitMethods(scoped_refptr<yb::MetricEntity> const&)::$_0, std::__1::allocator<yb::master::MasterDdlIf::InitMethods(scoped_refptr<yb::MetricEntity> const&)::$_0>, void (std::__1::shared_ptr<yb::rpc::InboundCall>)>::operator()(std::__1::shared_ptr<yb::rpc::InboundCall>&&) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20220924220949-f77b91747b-almalinux8-x86_64-clang13/installed/asan/libcxx/include/c++/v1/__functional/function.h:171:16
    #16 0x7f75b82de2dc in std::__1::__function::__func<yb::master::MasterDdlIf::InitMethods(scoped_refptr<yb::MetricEntity> const&)::$_0, std::__1::allocator<yb::master::MasterDdlIf::InitMethods(scoped_refptr<yb::MetricEntity> const&)::$_0>, void (std::__1::shared_ptr<yb::rpc::InboundCall>)>::operator()(std::__1::shared_ptr<yb::rpc::InboundCall>&&) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20220924220949-f77b91747b-almalinux8-x86_64-clang13/installed/asan/libcxx/include/c++/v1/__functional/function.h:345:12
    #17 0x7f75b7ee8ce8 in std::__1::__function::__value_func<void (std::__1::shared_ptr<yb::rpc::InboundCall>)>::operator()(std::__1::shared_ptr<yb::rpc::InboundCall>&&) const /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20220924220949-f77b91747b-almalinux8-x86_64-clang13/installed/asan/libcxx/include/c++/v1/__functional/function.h:498:16
    #18 0x7f75b82ddc60 in std::__1::function<void (std::__1::shared_ptr<yb::rpc::InboundCall>)>::operator()(std::__1::shared_ptr<yb::rpc::InboundCall>) const /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20220924220949-f77b91747b-almalinux8-x86_64-clang13/installed/asan/libcxx/include/c++/v1/__functional/function.h:1175:12
    #19 0x7f75b82ddc60 in yb::master::MasterDdlIf::Handle(std::__1::shared_ptr<yb::rpc::InboundCall>) ${BUILD_ROOT}/src/yb/master/master_ddl.service.cc:631:3
    #20 0x7f75b5247fda in yb::rpc::ServicePoolImpl::Handle(std::__1::shared_ptr<yb::rpc::InboundCall>) ${BUILD_ROOT}/../../src/yb/rpc/service_pool.cc:270:19
    #21 0x7f75b5119ba2 in yb::rpc::InboundCall::InboundCallTask::Run() ${BUILD_ROOT}/../../src/yb/rpc/inbound_call.cc:241:13
    #22 0x7f75b5270895 in yb::rpc::(anonymous namespace)::Worker::Execute() ${BUILD_ROOT}/../../src/yb/rpc/thread_pool.cc:104:15
    #23 0x7f75b527140f in decltype(*(static_cast<yb::rpc::(anonymous namespace)::Worker*&>(fp0)).*fp()) std::__1::__invoke<void (yb::rpc::(anonymous namespace)::Worker::*&)(), yb::rpc::(anonymous namespace)::Worker*&, void>(void (yb::rpc::(anonymous namespace)::Worker::*&)(), yb::rpc::(anonymous namespace)::Worker*&) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20220924220949-f77b91747b-almalinux8-x86_64-clang13/installed/asan/libcxx/include/c++/v1/type_traits:3859:1
    #24 0x7f75b527140f in std::__1::__bind_return<void (yb::rpc::(anonymous namespace)::Worker::*)(), std::__1::tuple<yb::rpc::(anonymous namespace)::Worker*>, std::__1::tuple<>, __is_valid_bind_return<void (yb::rpc::(anonymous namespace)::Worker::*)(), std::__1::tuple<yb::rpc::(anonymous namespace)::Worker*>, std::__1::tuple<> >::value>::type std::__1::__apply_functor<void (yb::rpc::(anonymous namespace)::Worker::*)(), std::__1::tuple<yb::rpc::(anonymous namespace)::Worker*>, 0ul, std::__1::tuple<> >(void (yb::rpc::(anonymous namespace)::Worker::*&)(), std::__1::tuple<yb::rpc::(anonymous namespace)::Worker*>&, std::__1::__tuple_indices<0ul>, std::__1::tuple<>&&) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20220924220949-f77b91747b-almalinux8-x86_64-clang13/installed/asan/libcxx/include/c++/v1/__functional/bind.h:257:12
    #25 0x7f75b5271287 in std::__1::__bind_return<void (yb::rpc::(anonymous namespace)::Worker::*)(), std::__1::tuple<yb::rpc::(anonymous namespace)::Worker*>, std::__1::tuple<>, __is_valid_bind_return<void (yb::rpc::(anonymous namespace)::Worker::*)(), std::__1::tuple<yb::rpc::(anonymous namespace)::Worker*>, std::__1::tuple<> >::value>::type std::__1::__bind<void (yb::rpc::(anonymous namespace)::Worker::* const&)(), yb::rpc::(anonymous namespace)::Worker* const&>::operator()<>() /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20220924220949-f77b91747b-almalinux8-x86_64-clang13/installed/asan/libcxx/include/c++/v1/__functional/bind.h:292:20
    #26 0x7f75b5271287 in decltype(static_cast<std::__1::__bind<void (yb::rpc::(anonymous namespace)::Worker::* const&)(), yb::rpc::(anonymous namespace)::Worker* const&>&>(fp)()) std::__1::__invoke<std::__1::__bind<void (yb::rpc::(anonymous namespace)::Worker::* const&)(), yb::rpc::(anonymous namespace)::Worker* const&>&>(std::__1::__bind<void (yb::rpc::(anonymous namespace)::Worker::* const&)(), yb::rpc::(anonymous namespace)::Worker* const&>&) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20220924220949-f77b91747b-almalinux8-x86_64-clang13/installed/asan/libcxx/include/c++/v1/type_traits:3918:1
    #27 0x7f75b5271287 in void std::__1::__invoke_void_return_wrapper<void, true>::__call<std::__1::__bind<void (yb::rpc::(anonymous namespace)::Worker::* const&)(), yb::rpc::(anonymous namespace)::Worker* const&>&>(std::__1::__bind<void (yb::rpc::(anonymous namespace)::Worker::* const&)(), yb::rpc::(anonymous namespace)::Worker* const&>&) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20220924220949-f77b91747b-almalinux8-x86_64-clang13/installed/asan/libcxx/include/c++/v1/__functional/invoke.h:61:9
    #28 0x7f75b5271287 in std::__1::__function::__alloc_func<std::__1::__bind<void (yb::rpc::(anonymous namespace)::Worker::* const&)(), yb::rpc::(anonymous namespace)::Worker* const&>, std::__1::allocator<std::__1::__bind<void (yb::rpc::(anonymous namespace)::Worker::* const&)(), yb::rpc::(anonymous namespace)::Worker* const&> >, void ()>::operator()() /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20220924220949-f77b91747b-almalinux8-x86_64-clang13/installed/asan/libcxx/include/c++/v1/__functional/function.h:171:16
    #29 0x7f75b5271287 in std::__1::__function::__func<std::__1::__bind<void (yb::rpc::(anonymous namespace)::Worker::* const&)(), yb::rpc::(anonymous namespace)::Worker* const&>, std::__1::allocator<std::__1::__bind<void (yb::rpc::(anonymous namespace)::Worker::* const&)(), yb::rpc::(anonymous namespace)::Worker* const&> >, void ()>::operator()() /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20220924220949-f77b91747b-almalinux8-x86_64-clang13/installed/asan/libcxx/include/c++/v1/__functional/function.h:345:12
    #30 0x7f75b347d068 in std::__1::__function::__value_func<void ()>::operator()() const /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20220924220949-f77b91747b-almalinux8-x86_64-clang13/installed/asan/libcxx/include/c++/v1/__functional/function.h:498:16
    #31 0x7f75b380b28a in std::__1::function<void ()>::operator()() const /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20220924220949-f77b91747b-almalinux8-x86_64-clang13/installed/asan/libcxx/include/c++/v1/__functional/function.h:1175:12
    #32 0x7f75b380b28a in yb::Thread::SuperviseThread(void*) ${BUILD_ROOT}/../../src/yb/util/thread.cc:774:3
    #33 0x7f75aec691ce in start_thread (/lib64/libpthread.so.0+0x81ce)
```

**Comment by druzac** [comment]
I haven't been able to repro any of the failures. All the detective links I could find show the latest failures happening in November 2022. Closing.
