### ISSUE TITLE
[DocDB] undefined behavior in AutomaticTabletSplitITest.AutomaticTabletSplitting

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#14230]
### Description

https://detective-gcp.dev.yugabyte.com/stability/test?branch=master&build_type=all&class=AutomaticTabletSplitITest&fail_tag=undefined_behavior&name=AutomaticTabletSplitting&platform=linux

```
../../src/yb/integration-tests/tablet-split-itest.cc:945:7: runtime error: member call on null pointer of type 'yb::tablet::Tablet'
    #0 0x39fec1 in yb::AutomaticTabletSplitITest::FlushAllTabletReplicas(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::'lambda'()::operator()() const ${BUILD_ROOT}/../../src/yb/integration-tests/tablet-split-itest.cc:945:7
    #1 0x39fc80 in decltype(static_cast<yb::AutomaticTabletSplitITest::FlushAllTabletReplicas(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::'lambda'()&>(fp)()) std::__1::__invoke<yb::AutomaticTabletSplitITest::FlushAllTabletReplicas(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::'lambda'()&>(yb::AutomaticTabletSplitITest::FlushAllTabletReplicas(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::'lambda'()&) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20220920000458-7f25c9789a-almalinux8-x86_64-clang13/installed/asan/libcxx/include/c++/v1/type_traits:3918:1
    #2 0x39fc80 in yb::Result<bool> std::__1::__invoke_void_return_wrapper<yb::Result<bool>, false>::__call<yb::AutomaticTabletSplitITest::FlushAllTabletReplicas(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::'lambda'()&>(yb::AutomaticTabletSplitITest::FlushAllTabletReplicas(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::'lambda'()&) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20220920000458-7f25c9789a-almalinux8-x86_64-clang13/installed/asan/libcxx/include/c++/v1/__functional/invoke.h:30:16
    #3 0x39fc80 in std::__1::__function::__alloc_func<yb::AutomaticTabletSplitITest::FlushAllTabletReplicas(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::'lambda'(), std::__1::allocator<yb::AutomaticTabletSplitITest::FlushAllTabletReplicas(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::'lambda'()>, yb::Result<bool> ()>::operator()() /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20220920000458-7f25c9789a-almalinux8-x86_64-clang13/installed/asan/libcxx/include/c++/v1/__functional/function.h:171:16
    #4 0x39fae1 in std::__1::__function::__func<yb::AutomaticTabletSplitITest::FlushAllTabletReplicas(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::'lambda'(), std::__1::allocator<yb::AutomaticTabletSplitITest::FlushAllTabletReplicas(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::'lambda'()>, yb::Result<bool> ()>::operator()() /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20220920000458-7f25c9789a-almalinux8-x86_64-clang13/installed/asan/libcxx/include/c++/v1/__functional/function.h:345:12
    #5 0x7fb402c14e4d in std::__1::__function::__value_func<yb::Result<bool> ()>::operator()() const /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20220920000458-7f25c9789a-almalinux8-x86_64-clang13/installed/asan/libcxx/include/c++/v1/__functional/function.h:498:16
    #6 0x7fb402c1120d in std::__1::function<yb::Result<bool> ()>::operator()() const /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20220920000458-7f25c9789a-almalinux8-x86_64-clang13/installed/asan/libcxx/include/c++/v1/__functional/function.h:1175:12
    #7 0x7fb402c1120d in yb::Wait(std::__1::function<yb::Result<bool> ()> const&, std::__1::chrono::time_point<yb::CoarseMonoClock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, yb::MonoDelta, double, yb::MonoDelta) ${BUILD_ROOT}/../../src/yb/util/test_util.cc:283:26
    #8 0x7fb402c11a5c in yb::Wait(std::__1::function<yb::Result<bool> ()> const&, yb::MonoTime, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, yb::MonoDelta, double, yb::MonoDelta) ${BUILD_ROOT}/../../src/yb/util/test_util.cc:312:10
    #9 0x7fb402c11f95 in yb::WaitFor(std::__1::function<yb::Result<bool> ()> const&, yb::MonoDelta, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, yb::MonoDelta, double, yb::MonoDelta) ${BUILD_ROOT}/../../src/yb/util/test_util.cc:337:10
    #10 0x37e315 in yb::AutomaticTabletSplitITest::FlushAllTabletReplicas(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) ${BUILD_ROOT}/../../src/yb/integration-tests/tablet-split-itest.cc:945:7
    #11 0x37be5b in yb::AutomaticTabletSplitITest::AutomaticallySplitSingleTablet(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, unsigned long, int*) ${BUILD_ROOT}/../../src/yb/integration-tests/tablet-split-itest.cc:974:7
    #12 0x2ef017 in yb::AutomaticTabletSplitITest_AutomaticTabletSplitting_Test::TestBody() ${BUILD_ROOT}/../../src/yb/integration-tests/tablet-split-itest.cc:1032:3
    #13 0x7fb402a902ef in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20220920000458-7f25c9789a-almalinux8-x86_64-clang13/src/googletest-1.12.1/googletest/src/gtest.cc:2599:10
    #14 0x7fb402a902ef in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20220920000458-7f25c9789a-almalinux8-x86_64-clang13/src/googletest-1.12.1/googletest/src/gtest.cc:2635:14
    #15 0x7fb402a43bc2 in testing::Test::Run() /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20220920000458-7f25c9789a-almalinux8-x86_64-clang13/src/googletest-1.12.1/googletest/src/gtest.cc:2674:5
    #16 0x7fb402a4590f in testing::TestInfo::Run() /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20220920000458-7f25c9789a-almalinux8-x86_64-clang13/src/googletest-1.12.1/googletest/src/gtest.cc:2853:11
    #17 0x7fb402a47ea0 in testing::TestSuite::Run() /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20220920000458-7f25c9789a-almalinux8-x86_64-clang13/src/googletest-1.12.1/googletest/src/gtest.cc:3012:30
    #18 0x7fb402a6f736 in testing::internal::UnitTestImpl::RunAllTests() /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20220920000458-7f25c9789a-almalinux8-x86_64-clang13/src/googletest-1.12.1/googletest/src/gtest.cc:5870:44
    #19 0x7fb402a94e3a in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20220920000458-7f25c9789a-almalinux8-x86_64-clang13/src/googletest-1.12.1/googletest/src/gtest.cc:2599:10
    #20 0x7fb402a94e3a in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20220920000458-7f25c9789a-almalinux8-x86_64-clang13/src/googletest-1.12.1/googletest/src/gtest.cc:2635:14
    #21 0x7fb402a6e36c in testing::UnitTest::Run() /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20220920000458-7f25c9789a-almalinux8-x86_64-clang13/src/googletest-1.12.1/googletest/src/gtest.cc:5444:10
    #22 0x7fb411cc86e0 in RUN_ALL_TESTS() /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20220920000458-7f25c9789a-almalinux8-x86_64-clang13/installed/asan/include/gtest/gtest.h:2293:73
    #23 0x7fb411cc86e0 in main ${BUILD_ROOT}/../../src/yb/util/test_main.cc:109:13
    #24 0x7fb3fd76dcf2 in __libc_start_main (/lib64/libc.so.6+0x3acf2)
    #25 0x2c953d in _start (${BUILD_ROOT}/tests-integration-tests/tablet-split-itest+0x2c953d)

```

**Comment by bmatican** [comment]
Passing to @yusong-yan as he was investigating an unrelated test issue, but observed the same stack already

**Comment by rthallamko3** [comment]
@yusong-yan , can you backport this change to 2.14 branch too?
