### ISSUE TITLE
[DocDB][LST][B&R] Error running import_snapshot: SNAPSHOT_FAILED (master error 23)

### ISSUE THREAD

**Issue by def-** [yugabyte/yugabyte-db#14373]
Jira Link: [DB-3795](https://yugabyte.atlassian.net/browse/DB-3795)
### Description

During restore with LST I am running into a new failure (2.15.3.0-b113):
```
$ python3.9 ./long_system_test.py --scenario=backup_restore --portal=portal-iam.dev.yugabyte.com --universe_uuid=82b35bdd-d6e5-464e-9c9b-6247d9c4084a --threads=10 --runtime=5 --complexity=full --drop
[...]
2022-10-07 13:48:43,047 MainThread INFO     Restoring db_lst_029734 multitable from backup UUID 5619a28e-b2ae-43a3-9c11-497853fab2da (universe 82b35bdd-d6e5-464e-9c9b-6247d9c4084a)
2022-10-07 13:48:43,276 MainThread INFO     Restoring multitable backup from S3 path s3://backups.yugabyte.com/s3Backup/univ-82b35bdd-d6e5-464e-9c9b-6247d9c4084a/backup-2022-10-07T13:46:40-727456399/keyspace-db_lst_029734
2022-10-07 13:48:43,340 MainThread INFO     Multitable Restore backup returned: {'taskUUID': '0ebee5fa-df0c-45df-ad8a-e189ad17dce5'}
2022-10-07 13:48:43,341 MainThread INFO     Waiting for completion of task restore_multitable_backup UUID 0ebee5fa-df0c-45df-ad8a-e189ad17dce5
2022-10-07 13:48:43,397 MainThread INFO     Still waiting for task: 0ebee5fa-df0c-45df-ad8a-e189ad17dce5
2022-10-07 13:51:44,056 MainThread ERROR    wait_for_task: Failed task with errors in 180.71481561660767s:
Failed to execute task {"sleepAfterMasterRestartMillis":180000,"sleepAfterTServerRestartMillis":180000,"nodeExporterUser":"prometheus","universeUUID":"82b35bdd-d6e5-464e-9c9b-6247d9c4084a","enableYbc":false,"installYbc":false,"ybcInstalled":false,"encryptionAtRestConfig":{"encryptionAtRestEnabled":false,"opType":"UNDEFINED","type":"DATA_KEY"},"communicationPorts":{"masterHttpPort":7000,"masterRpcPort":7100,"tserverHttpPort":9000,"tserverRpcPort":9100,"ybControllerHttpPort":14000,"ybControllerrRpcPort":18018,"redisS..., hit error:

{"error": "Exception: Command '['ssh', '-o', 'StrictHostKeyChecking=no', '-o', 'UserKnownHostsFile=/dev/null', '-o', 'ControlMaster=auto', '-o', 'ControlPath=~/.ssh/ssh-%r@%h:%p', '-o', 'ControlPersist=1m', '-i', 'X', '-p', '22', '-q', 'yugabyte@X', \"cd / &&  bash -c '/home/yugabyte/master/bin/yb-admin --master_addresses X import_snapshot /tmp/yb_backup_wzzauhjfcuuvtqih/SnapshotInfoPB db_lst_029734 --never_fsync=false'\"]' returned non-zero exit status 1."}.
2022-10-07 13:51:44,056 MainThread INFO     Dumping more platform logs
Traceback (most recent call last):
  File "/nfusr/dev-server/dfelsing/code/yb-long-system-test/./long_system_test.py", line 513, in <module>
    main()
  File "/nfusr/dev-server/dfelsing/code/yb-long-system-test/./long_system_test.py", line 503, in main
    lst.run()
  File "/nfusr/dev-server/dfelsing/code/yb-long-system-test/./long_system_test.py", line 427, in run
    self.yw.restore_multitable_backup(self.args.universe_uuid, backup_uuid, self.database.name(), config_uuid, self.args.universe_uuid)
  File "/nfusr/dev-server/dfelsing/code/yb-long-system-test/yw_proxy.py", line 933, in restore_multitable_backup
    self.wait_for_task(task_uuid, sys._getframe().f_code.co_name)
  File "/nfusr/dev-server/dfelsing/code/yb-long-system-test/yw_proxy.py", line 624, in wait_for_task
    raise RuntimeError(error_msg)
RuntimeError: wait_for_task: Failed task with errors in 180.71481561660767s:
Failed to execute task {"sleepAfterMasterRestartMillis":180000,"sleepAfterTServerRestartMillis":180000,"nodeExporterUser":"prometheus","universeUUID":"82b35bdd-d6e5-464e-9c9b-6247d9c4084a","enableYbc":false,"installYbc":false,"ybcInstalled":false,"encryptionAtRestConfig":{"encryptionAtRestEnabled":false,"opType":"UNDEFINED","type":"DATA_KEY"},"communicationPorts":{"masterHttpPort":7000,"masterRpcPort":7100,"tserverHttpPort":9000,"tserverRpcPort":9100,"ybControllerHttpPort":14000,"ybControllerrRpcPort":18018,"redisS..., hit error:

{"error": "Exception: Command '['ssh', '-o', 'StrictHostKeyChecking=no', '-o', 'UserKnownHostsFile=/dev/null', '-o', 'ControlMaster=auto', '-o', 'ControlPath=~/.ssh/ssh-%r@%h:%p', '-o', 'ControlPersist=1m', '-i', 'X', '-p', '22', '-q', 'yugabyte@X', \"cd / &&  bash -c '/home/yugabyte/master/bin/yb-admin --master_addresses X import_snapshot /tmp/yb_backup_wzzauhjfcuuvtqih/SnapshotInfoPB db_lst_029734 --never_fsync=false'\"]' returned non-zero exit status 1."}.
```
This is with CREATE/DROP INDEX disabled in LST because of https://github.com/yugabyte/yugabyte-db/issues/13941
Universe is at http://portal-iam.dev.yugabyte.com/universes/829efd3f-cae4-465b-a111-387b07169caa/tasks
Yugaware logs:
```
YW 2022-10-07T13:51:15.981Z [DEBUG] 98fddfd4-91a5-4095-9737-53f366e40d76 from ShellProcessHandler in TaskPool-BackupUniverse(82b35bdd-d6e5-464e-9c9b-6247d9c4084a)-0 -  957:c955_boolean[bool NULLABLE NOT A PARTITION KEY],
YW 2022-10-07T13:51:15.981Z [DEBUG] 98fddfd4-91a5-4095-9737-53f366e40d76 from ShellProcessHandler in TaskPool-BackupUniverse(82b35bdd-d6e5-464e-9c9b-6247d9c4084a)-0 -  958:c956_numrange[binary NULLABLE NOT A PARTITION KEY],
YW 2022-10-07T13:51:15.981Z [DEBUG] 98fddfd4-91a5-4095-9737-53f366e40d76 from ShellProcessHandler in TaskPool-BackupUniverse(82b35bdd-d6e5-464e-9c9b-6247d9c4084a)-0 -  959:c957_int2range[binary NULLABLE NOT A PARTITION KEY]
YW 2022-10-07T13:51:15.981Z [DEBUG] 98fddfd4-91a5-4095-9737-53f366e40d76 from ShellProcessHandler in TaskPool-BackupUniverse(82b35bdd-d6e5-464e-9c9b-6247d9c4084a)-0 - ]
YW 2022-10-07T13:51:15.981Z [DEBUG] 98fddfd4-91a5-4095-9737-53f366e40d76 from ShellProcessHandler in TaskPool-BackupUniverse(82b35bdd-d6e5-464e-9c9b-6247d9c4084a)-0 - properties: contain_counters: false is_transactional: true consistency_level: STRONG use_mangled_column_name: false num_tablets: 3 is_ysql_catalog_table: false retain_delete_markers: false partitioning_version: 1}: SNAPSHOT_FAILED (master error 23)
YW 2022-10-07T13:51:15.981Z [DEBUG] 98fddfd4-91a5-4095-9737-53f366e40d76 from ShellProcessHandler in TaskPool-BackupUniverse(82b35bdd-d6e5-464e-9c9b-6247d9c4084a)-0 -
YW 2022-10-07T13:51:15.981Z [DEBUG] 98fddfd4-91a5-4095-9737-53f366e40d76 from ShellProcessHandler in TaskPool-BackupUniverse(82b35bdd-d6e5-464e-9c9b-6247d9c4084a)-0 - Traceback (most recent call last):
YW 2022-10-07T13:51:15.981Z [DEBUG] 98fddfd4-91a5-4095-9737-53f366e40d76 from ShellProcessHandler in TaskPool-BackupUniverse(82b35bdd-d6e5-464e-9c9b-6247d9c4084a)-0 -   File "bin/yb_backup.py", line 3642, in run
YW 2022-10-07T13:51:15.981Z [DEBUG] 98fddfd4-91a5-4095-9737-53f366e40d76 from ShellProcessHandler in TaskPool-BackupUniverse(82b35bdd-d6e5-464e-9c9b-6247d9c4084a)-0 -     self.restore_table()
YW 2022-10-07T13:51:15.981Z [DEBUG] 98fddfd4-91a5-4095-9737-53f366e40d76 from ShellProcessHandler in TaskPool-BackupUniverse(82b35bdd-d6e5-464e-9c9b-6247d9c4084a)-0 -   File "bin/yb_backup.py", line 3479, in restore_table
YW 2022-10-07T13:51:15.981Z [DEBUG] 98fddfd4-91a5-4095-9737-53f366e40d76 from ShellProcessHandler in TaskPool-BackupUniverse(82b35bdd-d6e5-464e-9c9b-6247d9c4084a)-0 -     snapshot_metadata = self.import_snapshot(metadata_file_path)
YW 2022-10-07T13:51:15.981Z [DEBUG] 98fddfd4-91a5-4095-9737-53f366e40d76 from ShellProcessHandler in TaskPool-BackupUniverse(82b35bdd-d6e5-464e-9c9b-6247d9c4084a)-0 -   File "bin/yb_backup.py", line 3246, in import_snapshot
YW 2022-10-07T13:51:15.981Z [DEBUG] 98fddfd4-91a5-4095-9737-53f366e40d76 from ShellProcessHandler in TaskPool-BackupUniverse(82b35bdd-d6e5-464e-9c9b-6247d9c4084a)-0 -     output = self.run_yb_admin(yb_admin_args, run_ip=self.get_main_host_ip())
YW 2022-10-07T13:51:15.981Z [DEBUG] 98fddfd4-91a5-4095-9737-53f366e40d76 from ShellProcessHandler in TaskPool-BackupUniverse(82b35bdd-d6e5-464e-9c9b-6247d9c4084a)-0 -   File "bin/yb_backup.py", line 1636, in run_yb_admin
YW 2022-10-07T13:51:15.982Z [DEBUG] 98fddfd4-91a5-4095-9737-53f366e40d76 from ShellProcessHandler in TaskPool-BackupUniverse(82b35bdd-d6e5-464e-9c9b-6247d9c4084a)-0 -     raise ex
YW 2022-10-07T13:51:15.982Z [DEBUG] 98fddfd4-91a5-4095-9737-53f366e40d76 from ShellProcessHandler in TaskPool-BackupUniverse(82b35bdd-d6e5-464e-9c9b-6247d9c4084a)-0 -   File "bin/yb_backup.py", line 1631, in run_yb_admin
YW 2022-10-07T13:51:15.982Z [DEBUG] 98fddfd4-91a5-4095-9737-53f366e40d76 from ShellProcessHandler in TaskPool-BackupUniverse(82b35bdd-d6e5-464e-9c9b-6247d9c4084a)-0 -     cmd_line_args, run_ip=run_ip)
YW 2022-10-07T13:51:15.982Z [DEBUG] 98fddfd4-91a5-4095-9737-53f366e40d76 from ShellProcessHandler in TaskPool-BackupUniverse(82b35bdd-d6e5-464e-9c9b-6247d9c4084a)-0 -   File "bin/yb_backup.py", line 1585, in run_tool
YW 2022-10-07T13:51:15.982Z [DEBUG] 98fddfd4-91a5-4095-9737-53f366e40d76 from ShellProcessHandler in TaskPool-BackupUniverse(82b35bdd-d6e5-464e-9c9b-6247d9c4084a)-0 -     env_vars=env_vars)
YW 2022-10-07T13:51:15.982Z [DEBUG] 98fddfd4-91a5-4095-9737-53f366e40d76 from ShellProcessHandler in TaskPool-BackupUniverse(82b35bdd-d6e5-464e-9c9b-6247d9c4084a)-0 -   File "bin/yb_backup.py", line 2121, in run_ssh_cmd
YW 2022-10-07T13:51:15.982Z [DEBUG] 98fddfd4-91a5-4095-9737-53f366e40d76 from ShellProcessHandler in TaskPool-BackupUniverse(82b35bdd-d6e5-464e-9c9b-6247d9c4084a)-0 -     return self.run_program(ssh_command, num_retry=num_retries)
YW 2022-10-07T13:51:15.982Z [DEBUG] 98fddfd4-91a5-4095-9737-53f366e40d76 from ShellProcessHandler in TaskPool-BackupUniverse(82b35bdd-d6e5-464e-9c9b-6247d9c4084a)-0 -   File "bin/yb_backup.py", line 1073, in run_program
YW 2022-10-07T13:51:15.982Z [DEBUG] 98fddfd4-91a5-4095-9737-53f366e40d76 from ShellProcessHandler in TaskPool-BackupUniverse(82b35bdd-d6e5-464e-9c9b-6247d9c4084a)-0 -     self.sleep_or_raise(num_retry, timeout, e)
YW 2022-10-07T13:51:15.982Z [DEBUG] 98fddfd4-91a5-4095-9737-53f366e40d76 from ShellProcessHandler in TaskPool-BackupUniverse(82b35bdd-d6e5-464e-9c9b-6247d9c4084a)-0 -   File "bin/yb_backup.py", line 1037, in sleep_or_raise
YW 2022-10-07T13:51:15.982Z [DEBUG] 98fddfd4-91a5-4095-9737-53f366e40d76 from ShellProcessHandler in TaskPool-BackupUniverse(82b35bdd-d6e5-464e-9c9b-6247d9c4084a)-0 -     raise ex
YW 2022-10-07T13:51:15.982Z [DEBUG] 98fddfd4-91a5-4095-9737-53f366e40d76 from ShellProcessHandler in TaskPool-BackupUniverse(82b35bdd-d6e5-464e-9c9b-6247d9c4084a)-0 -   File "bin/yb_backup.py", line 1059, in run_program
YW 2022-10-07T13:51:15.982Z [DEBUG] 98fddfd4-91a5-4095-9737-53f366e40d76 from ShellProcessHandler in TaskPool-BackupUniverse(82b35bdd-d6e5-464e-9c9b-6247d9c4084a)-0 -     env=proc_env, **kwargs).decode('utf-8', errors='replace')
YW 2022-10-07T13:51:15.982Z [DEBUG] 98fddfd4-91a5-4095-9737-53f366e40d76 from ShellProcessHandler in TaskPool-BackupUniverse(82b35bdd-d6e5-464e-9c9b-6247d9c4084a)-0 -   File "/usr/lib64/python3.6/subprocess.py", line 356, in check_output
YW 2022-10-07T13:51:15.982Z [DEBUG] 98fddfd4-91a5-4095-9737-53f366e40d76 from ShellProcessHandler in TaskPool-BackupUniverse(82b35bdd-d6e5-464e-9c9b-6247d9c4084a)-0 -     **kwargs).stdout
YW 2022-10-07T13:51:15.982Z [DEBUG] 98fddfd4-91a5-4095-9737-53f366e40d76 from ShellProcessHandler in TaskPool-BackupUniverse(82b35bdd-d6e5-464e-9c9b-6247d9c4084a)-0 -   File "/usr/lib64/python3.6/subprocess.py", line 438, in run
YW 2022-10-07T13:51:15.982Z [DEBUG] 98fddfd4-91a5-4095-9737-53f366e40d76 from ShellProcessHandler in TaskPool-BackupUniverse(82b35bdd-d6e5-464e-9c9b-6247d9c4084a)-0 -     output=stdout, stderr=stderr)
YW 2022-10-07T13:51:15.982Z [DEBUG] 98fddfd4-91a5-4095-9737-53f366e40d76 from ShellProcessHandler in TaskPool-BackupUniverse(82b35bdd-d6e5-464e-9c9b-6247d9c4084a)-0 - subprocess.CalledProcessError: Command '['ssh', '-o', 'StrictHostKeyChecking=no', '-o', 'UserKnownHostsFile=/dev/null', '-o', 'ControlMaster=auto', '-o', 'ControlPath=~/.ssh/ssh-%r@%h:%p', '-o', 'ControlPersist=1m', '-i', 'X', '-p', '22', '-q', 'yugabyte@X', "cd / &&  bash -c '/home/yugabyte/master/bin/yb-admin --master_addresses X import_snapshot /tmp/yb_backup_wzzauhjfcuuvtqih/SnapshotInfoPB db_lst_029734 --never_fsync=false'"]' returned non-zero exit status 1.
YW 2022-10-07T13:51:15.982Z [DEBUG] 98fddfd4-91a5-4095-9737-53f366e40d76 from ShellProcessHandler in TaskPool-BackupUniverse(82b35bdd-d6e5-464e-9c9b-6247d9c4084a)-0 -   File "/usr/lib64/python3.6/threading.py", line 884, in _bootstrap
YW 2022-10-07T13:51:15.982Z [DEBUG] 98fddfd4-91a5-4095-9737-53f366e40d76 from ShellProcessHandler in TaskPool-BackupUniverse(82b35bdd-d6e5-464e-9c9b-6247d9c4084a)-0 -     self._bootstrap_inner()
YW 2022-10-07T13:51:15.982Z [DEBUG] 98fddfd4-91a5-4095-9737-53f366e40d76 from ShellProcessHandler in TaskPool-BackupUniverse(82b35bdd-d6e5-464e-9c9b-6247d9c4084a)-0 -   File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
YW 2022-10-07T13:51:15.982Z [DEBUG] 98fddfd4-91a5-4095-9737-53f366e40d76 from ShellProcessHandler in TaskPool-BackupUniverse(82b35bdd-d6e5-464e-9c9b-6247d9c4084a)-0 -     self.run()
YW 2022-10-07T13:51:15.982Z [DEBUG] 98fddfd4-91a5-4095-9737-53f366e40d76 from ShellProcessHandler in TaskPool-BackupUniverse(82b35bdd-d6e5-464e-9c9b-6247d9c4084a)-0 -   File "/usr/lib64/python3.6/threading.py", line 864, in run
YW 2022-10-07T13:51:15.983Z [DEBUG] 98fddfd4-91a5-4095-9737-53f366e40d76 from ShellProcessHandler in TaskPool-BackupUniverse(82b35bdd-d6e5-464e-9c9b-6247d9c4084a)-0 -     self._target(*self._args, **self._kwargs)
YW 2022-10-07T13:51:15.983Z [DEBUG] 98fddfd4-91a5-4095-9737-53f366e40d76 from ShellProcessHandler in TaskPool-BackupUniverse(82b35bdd-d6e5-464e-9c9b-6247d9c4084a)-0 -   File "/usr/lib64/python3.6/multiprocessing/pool.py", line 119, in worker
YW 2022-10-07T13:51:15.983Z [DEBUG] 98fddfd4-91a5-4095-9737-53f366e40d76 from ShellProcessHandler in TaskPool-BackupUniverse(82b35bdd-d6e5-464e-9c9b-6247d9c4084a)-0 -     result = (True, func(*args, **kwds))
YW 2022-10-07T13:51:15.983Z [DEBUG] 98fddfd4-91a5-4095-9737-53f366e40d76 from ShellProcessHandler in TaskPool-BackupUniverse(82b35bdd-d6e5-464e-9c9b-6247d9c4084a)-0 -   File "bin/yb_backup.py", line 3657, in run
YW 2022-10-07T13:51:15.983Z [DEBUG] 98fddfd4-91a5-4095-9737-53f366e40d76 from ShellProcessHandler in TaskPool-BackupUniverse(82b35bdd-d6e5-464e-9c9b-6247d9c4084a)-0 -     traceback.print_stack()
YW 2022-10-07T13:51:15.983Z [DEBUG] 98fddfd4-91a5-4095-9737-53f366e40d76 from ShellProcessHandler in TaskPool-BackupUniverse(82b35bdd-d6e5-464e-9c9b-6247d9c4084a)-0 - 2022-10-07 13:51:14,972 INFO: Completed phase 2: Import snapshot [Time taken for phase: 0:01:32.118967]
YW 2022-10-07T13:51:15.983Z [DEBUG] 98fddfd4-91a5-4095-9737-53f366e40d76 from ShellProcessHandler in TaskPool-BackupUniverse(82b35bdd-d6e5-464e-9c9b-6247d9c4084a)-0 - 2022-10-07 13:51:14,972 INFO: [app] Summary of run:
YW 2022-10-07T13:51:15.983Z [DEBUG] 98fddfd4-91a5-4095-9737-53f366e40d76 from ShellProcessHandler in TaskPool-BackupUniverse(82b35bdd-d6e5-464e-9c9b-6247d9c4084a)-0 - 0:00:51.733284 : PHASE 1 : Create objects via YSQL dumps
YW 2022-10-07T13:51:15.983Z [DEBUG] 98fddfd4-91a5-4095-9737-53f366e40d76 from ShellProcessHandler in TaskPool-BackupUniverse(82b35bdd-d6e5-464e-9c9b-6247d9c4084a)-0 - 0:01:32.118967 : PHASE 2 : Import snapshot
YW 2022-10-07T13:51:15.983Z [DEBUG] 98fddfd4-91a5-4095-9737-53f366e40d76 from ShellProcessHandler in TaskPool-BackupUniverse(82b35bdd-d6e5-464e-9c9b-6247d9c4084a)-0 - Total runtime: 0:02:31.234661
```
I will pause the universe for now. Tell me when it's not needed anymore so I can destroy it.

**Comment by def-** [comment]
@sanketkedia Should I destroy the universe?

**Comment by Karvy-yb** [comment]
Reproduce with: 
```
git checkout a9514252 && ./long_system_test.py --scenario=backup_restore --portal=portal-iam.dev.yugabyte.com --universe_uuid=8fc6dfc9-b32e-4a62-a12b-f0897134bde9 --threads=10 --runtime=5 --complexity=full --drop --seed=029734
```

**Comment by yamen-haddad** [comment]
This bug is related to orphaned Materialized Views not being cleaned up. It has been fixed in the following [diff](https://phabricator.dev.yugabyte.com/D19654).
