### ISSUE TITLE
[YSQL] flaky test: undefined behavior in PgPessimisticLockingTest.SavepointRollbackUnblock

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#14455]
Jira Link: [DB-3855](https://yugabyte.atlassian.net/browse/DB-3855)
### Description

https://detective-gcp.dev.yugabyte.com/stability/test?branch=master&build_type=all&class=PgPessimisticLockingTest&fail_tag=undefined_behavior&name=SavepointRollbackUnblock&platform=linux

```
../../../../../../src/postgres/src/backend/postmaster/pgstat.c:2859:33: runtime error: member access within null pointer of type 'PgBackendStatus' (aka 'struct PgBackendStatus')
    #0 0x118300f in pgstat_report_query_termination ${YB_SRC_ROOT}/src/postgres/src/backend/postmaster/../../../../../../src/postgres/src/backend/postmaster/pgstat.c:2859:33
    #1 0x119aec1 in LogChildExit ${YB_SRC_ROOT}/src/postgres/src/backend/postmaster/../../../../../../src/postgres/src/backend/postmaster/postmaster.c
    #2 0x119106f in CleanupBackend ${YB_SRC_ROOT}/src/postgres/src/backend/postmaster/../../../../../../src/postgres/src/backend/postmaster/postmaster.c:3360:2
    #3 0x119106f in reaper ${YB_SRC_ROOT}/src/postgres/src/backend/postmaster/../../../../../../src/postgres/src/backend/postmaster/postmaster.c:3219:3
    #4 0x7fbaf25a0cdf  (/lib64/libpthread.so.0+0x12cdf)
    #5 0x7fbaf22f01ba in select (/lib64/libc.so.6+0x1271ba)
    #6 0x11941f0 in ServerLoop ${YB_SRC_ROOT}/src/postgres/src/backend/postmaster/../../../../../../src/postgres/src/backend/postmaster/postmaster.c:1725:13
    #7 0x118dd7e in PostmasterMain ${YB_SRC_ROOT}/src/postgres/src/backend/postmaster/../../../../../../src/postgres/src/backend/postmaster/postmaster.c:1424:11
    #8 0xf604c0 in PostgresServerProcessMain ${YB_SRC_ROOT}/src/postgres/src/backend/main/../../../../../../src/postgres/src/backend/main/main.c:234:3
    #9 0xf60901 in main (${BUILD_ROOT}/postgres/bin/postgres+0xf60901)
    #10 0x7fbaf2203cf2 in __libc_start_main (/lib64/libc.so.6+0x3acf2)
    #11 0x77d6cd in _start (${BUILD_ROOT}/postgres/bin/postgres+0x77d6cd)

```

**Comment by tedyu** [comment]
It seems the above test run did not include D20104

**Comment by bmatican** [comment]
Oh, if it was recently fixed, ok to close it, thanks @tedyu
