### ISSUE TITLE
[YSQL] flaky test: undefined behavior in PgLibPqTest.DBCatalogVersion

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#14456]
Jira Link: [DB-3856](https://yugabyte.atlassian.net/browse/DB-3856)
### Description

https://detective-gcp.dev.yugabyte.com/stability/test?branch=master&build_type=all&class=PgLibPqTest&fail_tag=undefined_behavior&name=DBCatalogVersion&platform=linux

```
[ts-1] ../../../../../../../src/postgres/src/backend/catalog/yb_catalog/yb_catalog_version.c:472:5: runtime error: null pointer passed as argument 2, which is declared to never be null
[ts-1] /usr/include/stdlib.h:819:6: note: nonnull attribute specified here
[ts-1]     #0 0xa61a7a in YbGetTserverCatalogVersion ${YB_SRC_ROOT}/src/postgres/src/backend/catalog/yb_catalog/../../../../../../../src/postgres/src/backend/catalog/yb_catalog/yb_catalog_version.c:470:36
[ts-1]     #1 0x1795030 in YbResolveDBTserverCatalogVersion ${YB_SRC_ROOT}/src/postgres/src/backend/utils/init/../../../../../../../src/postgres/src/backend/utils/init/postinit.c:1170:33
[ts-1]     #2 0x1791a34 in InitPostgresImpl ${YB_SRC_ROOT}/src/postgres/src/backend/utils/init/../../../../../../../src/postgres/src/backend/utils/init/postinit.c
[ts-1]     #3 0x17910c5 in InitPostgres ${YB_SRC_ROOT}/src/postgres/src/backend/utils/init/../../../../../../../src/postgres/src/backend/utils/init/postinit.c:1201:3
[ts-1]     #4 0x1351e36 in PostgresMain ${YB_SRC_ROOT}/src/postgres/src/backend/tcop/../../../../../../src/postgres/src/backend/tcop/postgres.c:4848:2
[ts-1]     #5 0x1197860 in BackendRun ${YB_SRC_ROOT}/src/postgres/src/backend/postmaster/../../../../../../src/postgres/src/backend/postmaster/postmaster.c:4576:2
[ts-1]     #6 0x1195a09 in BackendStartup ${YB_SRC_ROOT}/src/postgres/src/backend/postmaster/../../../../../../src/postgres/src/backend/postmaster/postmaster.c:4214:3
[ts-1]     #7 0x1195a09 in ServerLoop ${YB_SRC_ROOT}/src/postgres/src/backend/postmaster/../../../../../../src/postgres/src/backend/postmaster/postmaster.c:1768:7
[ts-1]     #8 0x118dd7e in PostmasterMain ${YB_SRC_ROOT}/src/postgres/src/backend/postmaster/../../../../../../src/postgres/src/backend/postmaster/postmaster.c:1424:11
[ts-1]     #9 0xf604c0 in PostgresServerProcessMain ${YB_SRC_ROOT}/src/postgres/src/backend/main/../../../../../../src/postgres/src/backend/main/main.c:234:3
[ts-1]     #10 0xf60901 in main (${BUILD_ROOT}/postgres/bin/postgres+0xf60901)
[ts-1]     #11 0x7f0d67824cf2 in __libc_start_main (/lib64/libc.so.6+0x3acf2)
[ts-1]     #12 0x77d6cd in _start (${BUILD_ROOT}/postgres/bin/postgres+0x77d6cd)
```

**Comment by m-iancu** [comment]
Closing since this is an older issue and there are no longer failures with that tag (undefined behavior) found.
