### ISSUE TITLE
[Packed Columns + Tserver crash] Cores seen/FATAL when packed columns was enabled while running workload

### ISSUE THREAD

**Issue by shamanthchandra-yb** [yugabyte/yugabyte-db#14461]
Jira Link: [DB-3860](https://yugabyte.atlassian.net/browse/DB-3860)
### Description

**Version:**
2.17.1.0-b14

**Steps:**
1. Start workloads for sometime.
2. Enabled packed columns in g-flag for both ysql and ycql (only on t-server). Do rolling restart.
3. In UI it shows upgrade successful, but there is a tserver crash.

Here is the analysis:

```
Log file created at: 2022/10/12 16:31:29
Current UTC time: 2022/10/12 16:31:29
Running on machine: ip-172-151-21-72.us-west-2.compute.internal
Application fingerprint: version 2.17.1.0 build 14 revision b737017d49a1257146f7af5b663d4edf8fe12ceb build_type RELEASE built at 11 Oct 2022 04:25:01 UTC
Node information: { hostname: 'ip-172-151-21-72.us-west-2.compute.internal', rpc_ip: '172.151.21.72', webserver_ip: '172.151.21.72', uuid: 'aea4bf2f5ebb48f9a24332a4e7245cb2' }
Running duration (h:mm:ss): 0:02:31
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
F1012 16:31:29.200034 22459 malloc.cc:53] Check failed: data != nullptr failed to allocate 1751020 bytes
```

```
F20221012 16:31:29 ../../src/yb/util/malloc.cc:53] Check failed: data != nullptr failed to allocate 1751020 bytes
    @          0x2aaa1c8  google::LogMessage::SendToLog()
    @          0x2aab083  google::LogMessage::Flush()
    @          0x2aab57f  google::LogMessageFatal::~LogMessageFatal()
    @          0x3b4bfbe  yb::malloc_with_check()
    @          0x34c4cfb  yb::rpc::OutboundCall::SetRequestParam()
    @          0x34ca4cc  yb::rpc::Proxy::PrepareCall()
    @          0x34c9ce4  yb::rpc::Proxy::DoAsyncRequest()
    @          0x34c8e6c  yb::rpc::Proxy::AsyncRequest()
    @          0x391ce31  yb::tserver::TabletServerServiceProxy::WriteAsync()
    @          0x2c6ec57  yb::client::internal::WriteRpc::CallRemoteMethod()
    @          0x2d14c45  yb::client::internal::TabletInvoker::Execute()
    @          0x2c6a9b3  yb::client::internal::AsyncRpc::SendRpc()
    @          0x34e06f1  yb::rpc::RpcRetrier::DoRetry()
    @          0x34daefb  ev::base<>::method_thunk<>()
    @          0x349c73c  ev_invoke_pending
    @          0x349fa0d  ev_run
    @          0x34d652a  yb::rpc::Reactor::RunThread()
    @          0x3ba3aa2  yb::Thread::SuperviseThread()
    @     0x7f6f547f8694  start_thread
    @     0x7f6f54cfa41d  __clone
```

2 core files were seen in node:
core_sq_worker.19986
core_sq_worker.23141

On gdb:

```
`[yugabyte@ip-172-151-21-72 cores]$ gdb /home/yugabyte/tserver/bin/yb-tserver core_sq_worker.19986 
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-120.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /home/yugabyte/yb-software/yugabyte-2.17.1.0-b14-centos-x86_64/bin/yb-tserver...Dwarf Error: wrong version in compilation unit header (is 5, should be 2, 3, or 4) [in module /home/yugabyte/yb-software/yugabyte-2.17.1.0-b14-centos-x86_64/bin/yb-tserver]
(no debugging symbols found)...done.
[New LWP 20910]
[New LWP 19989]
[New LWP 20916]
[New LWP 19988]
[New LWP 20006]
[New LWP 19993]
[New LWP 20007]
[New LWP 19990]
[New LWP 20009]
[New LWP 20014]
[New LWP 20018]
[New LWP 20011]
[New LWP 20020]
[New LWP 20017]
[New LWP 20021]
[New LWP 20022]
[New LWP 20025]
[New LWP 20046]
[New LWP 20026]
[New LWP 20058]
[New LWP 20039]
[New LWP 20061]
[New LWP 20040]
[New LWP 20038]
[New LWP 20063]
[New LWP 20041]
[New LWP 20043]
[New LWP 20097]
[New LWP 20042]
[New LWP 20048]
[New LWP 20295]
[New LWP 20044]
[New LWP 20056]
[New LWP 20057]
[New LWP 20305]
[New LWP 19991]
[New LWP 20059]
[New LWP 20067]
[New LWP 20409]
[New LWP 19992]
[New LWP 20060]
[New LWP 20071]
[New LWP 20416]
[New LWP 20028]
[New LWP 20062]
[New LWP 20073]
[New LWP 20423]
[New LWP 20074]
[New LWP 20069]
[New LWP 20400]
[New LWP 20569]
[New LWP 20084]
[New LWP 20072]
[New LWP 20410]
[New LWP 20570]
[New LWP 20086]
[New LWP 20428]
[New LWP 20083]
[New LWP 20576]
[New LWP 20092]
[New LWP 20085]
[New LWP 20550]
[New LWP 20093]
[New LWP 20583]
[New LWP 20089]
[New LWP 20567]
[New LWP 20590]
[New LWP 20091]
[New LWP 20296]
[New LWP 20573]
[New LWP 20606]
[New LWP 20294]
[New LWP 20401]
[New LWP 20587]
[New LWP 20610]
[New LWP 20306]
[New LWP 20405]
[New LWP 20603]
[New LWP 20642]
[New LWP 20307]
[New LWP 20411]
[New LWP 20658]
[New LWP 20612]
[New LWP 20404]
[New LWP 20418]
[New LWP 20716]
[New LWP 20614]
[New LWP 20419]
[New LWP 20407]
[New LWP 20617]
[New LWP 20633]
[New LWP 20420]
[New LWP 20607]
[New LWP 20412]
[New LWP 20650]
[New LWP 20421]
[New LWP 20643]
[New LWP 20414]
[New LWP 20652]
[New LWP 20422]
[New LWP 20016]
[New LWP 20534]
[New LWP 20660]
[New LWP 20424]
[New LWP 20535]
[New LWP 20047]
[New LWP 20675]
[New LWP 20551]
[New LWP 20427]
[New LWP 20680]
[New LWP 20066]
[New LWP 20431]
[New LWP 20552]
[New LWP 20912]
[New LWP 20594]
[New LWP 20436]
[New LWP 20554]
[New LWP 20630]
[New LWP 20555]
[New LWP 20437]
[New LWP 20070]
[New LWP 20556]
[New LWP 20553]
[New LWP 20561]
[New LWP 20565]
[New LWP 20563]
[New LWP 20566]
[New LWP 20564]
[New LWP 20577]
[New LWP 20696]
[New LWP 20560]
[New LWP 20580]
[New LWP 20572]
[New LWP 20586]
[New LWP 20065]
[New LWP 20582]
[New LWP 20575]
[New LWP 20429]
[New LWP 20595]
[New LWP 20585]
[New LWP 20578]
[New LWP 20087]
[New LWP 20644]
[New LWP 20593]
[New LWP 20579]
[New LWP 20425]
[New LWP 20665]
[New LWP 20599]
[New LWP 20581]
[New LWP 20019]
[New LWP 20613]
[New LWP 20584]
[New LWP 20600]
[New LWP 20075]
[New LWP 20591]
[New LWP 20605]
[New LWP 20589]
[New LWP 20064]
[New LWP 20667]
[New LWP 20596]
[New LWP 20609]
[New LWP 20641]
[New LWP 20435]
[New LWP 20597]
[New LWP 20616]
[New LWP 20574]
[New LWP 20055]
[New LWP 20598]
[New LWP 20621]
[New LWP 20588]
[New LWP 20090]
[New LWP 20602]
[New LWP 20623]
[New LWP 20655]
[New LWP 20562]
[New LWP 20608]
[New LWP 20626]
[New LWP 20430]
[New LWP 20618]
[New LWP 20611]
[New LWP 20629]
[New LWP 20088]
[New LWP 20651]
[New LWP 20619]
[New LWP 20632]
[New LWP 20008]
[New LWP 20622]
[New LWP 20645]
[New LWP 20426]
[New LWP 20627]
[New LWP 20662]
[New LWP 20433]
[New LWP 20663]
[New LWP 20402]
[New LWP 20664]
[New LWP 20027]
[New LWP 20733]
[New LWP 20666]
[New LWP 20631]
[New LWP 20720]
[New LWP 20625]
[New LWP 20671]
[New LWP 20068]
[New LWP 20634]
[New LWP 20679]
[New LWP 20661]
[New LWP 20076]
[New LWP 20646]
[New LWP 20657]
[New LWP 20683]
[New LWP 20005]
[New LWP 20656]
[New LWP 20010]
[New LWP 20701]
[New LWP 20653]
[New LWP 20659]
[New LWP 20718]
[New LWP 20654]
[New LWP 20690]
[New LWP 20045]
[New LWP 20592]
[New LWP 19986]
[New LWP 20013]
[New LWP 20012]
[New LWP 20648]

warning: File "/home/yugabyte/yb-software/yugabyte-2.17.1.0-b14-centos-x86_64/linuxbrew/lib/libthread_db.so.1" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load:/usr/bin/mono-gdb.py".
To enable execution of this file add
    add-auto-load-safe-path /home/yugabyte/yb-software/yugabyte-2.17.1.0-b14-centos-x86_64/linuxbrew/lib/libthread_db.so.1
line to your configuration file "/home/yugabyte/.gdbinit".
To completely disable this security protection add
    set auto-load safe-path /
line to your configuration file "/home/yugabyte/.gdbinit".
For more information about this security protection see the
"Auto-loading safe path" section in the GDB manual.  E.g., run from the shell:
    info "(gdb)Auto-loading safe path"

warning: Unable to find libthread_db matching inferior's thread library, thread debugging will not be available.

warning: File "/home/yugabyte/yb-software/yugabyte-2.17.1.0-b14-centos-x86_64/linuxbrew/lib/libthread_db.so.1" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load:/usr/bin/mono-gdb.py".

warning: Unable to find libthread_db matching inferior's thread library, thread debugging will not be available.
Core was generated by `/home/yugabyte/tserver/bin/yb-tserver --flagfile /home/yugabyte/tserver/conf/se'.
Program terminated with signal 6, Aborted.
#0  0x00007f14199420a7 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
54  ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) where
#0  0x00007f14199420a7 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007f14199434aa in __GI_abort () at abort.c:89
#2  0x000000000436c801 in abort_message ()
#3  0x00000000043515ca in demangling_terminate_handler() ()
#4  0x000000000436c476 in std::__terminate(void (*)()) ()
#5  0x000000000436df4b in __cxxabiv1::failed_throw(__cxxabiv1::__cxa_exception*) ()
#6  0x000000000436ded8 in __cxa_throw ()
#7  0x0000000002a82e6f in (anonymous namespace)::handle_oom(void* (*)(void*), void*, bool, bool) ()
#8  0x000000000436f445 in tcmalloc::allocate_full_cpp_throw_oom(unsigned long) ()
#9  0x0000000002aa81e7 in std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> >::str() const ()
#10 0x00000000035d821f in yb::Webserver::Impl::BeginRequestCallbackStatic(sq_connection*) ()
#11 0x00000000035de28d in process_new_connection ()
#12 0x00000000035dc8e9 in worker_thread ()
#13 0x00007f14194f3694 in start_thread (arg=0x7f13d90e2700) at pthread_create.c:333
#14 0x00007f14199f541d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109`
```

**Jenkins log file:**
[log.txt](https://github.com/yugabyte/yugabyte-db/files/9774652/log.txt)

**Sql workload:**
export JAVA_HOME=/tmp/tests/artifacts/java-11/jdk-11; export PATH=$PATH:/tmp/tests/artifacts/java-11/jdk-11/bin; nohup java -jar /tmp/tests/artifacts/sample-app-tool/yb-sample-apps-1.8.20.jar --workload SqlDataLoad --uuid ce4b2e5d-7f1e-489b-a186-08b050fd06a7 --create_table_name test_packed_columns_sql_9ef7ee --num_writes -1 --num_threads_write 41 --num_reads -1 --num_threads_read 34 --num_unique_keys 10000000000 --num_value_columns 100 --batch_size 908 --uuid_marker 7f6a3f63-d7c9-4906-ab35-43963495ef68 --nodes

**Cql workload:**
export JAVA_HOME=/tmp/tests/artifacts/java-11/jdk-11; export PATH=$PATH:/tmp/tests/artifacts/java-11/jdk-11/bin; nohup java -jar /tmp/tests/artifacts/sample-app-tool/yb-sample-apps-1.8.20.jar --workload CassandraDataLoad --uuid cf7bcb3a-d499-45ac-b910-b3d596432257 --create_table_name test_packed_columns_cql_7cd0a6 --num_writes -1 --num_threads_write 41 --num_reads -1 --num_threads_read 34 --num_unique_keys 10000000000 --num_value_columns 100 --batch_size 908 --uuid_marker 9916e811-ff2e-4f45-bc61-fb21280f2326 --nodes 172.151.21.72:9042,172.151.28.176:9042,172.151.16.26:9042 2>&1 > /tmp/tests/PackedColumnsSuite/test_packed_columns_toggle_on_and_off/workload-CassandraDataLoad.20221012162330.log 2>&1 &

**Comment by bmatican** [comment]
This seems similar to https://github.com/yugabyte/yugabyte-db/issues/13909#issuecomment-1277770787

Can you try reducing the workload number of threads? The error is basically a running out of memory problem.

**Comment by shamanthchandra-yb** [comment]
Sure @bmatican . Let me reduce workload and try, will let you know if we hit this issue again.

**Comment by rthallamko3** [comment]
@shamanthchandra-yb , Can you clarify if the reduced workload still ran into it or not?

**Comment by shamanthchandra-yb** [comment]
With reduced workload we didn't see this issue @rthallamko3

**Comment by rthallamko3** [comment]
@shamanthchandra-yb , closing the issue as the first crash you saw was due to out-of-memory.
