### ISSUE TITLE
[YSQL] Segmentation fault in Postgres process in DDL workload

### ISSUE THREAD

**Issue by qvad** [yugabyte/yugabyte-db#14551]
### Description

Scenario is exactly the same with https://github.com/yugabyte/yugabyte-db/issues/14526, but evaluated against remote universe with 3 nodes, 3RF and AWS node restarts.
Eventually it leads to code dump for postgres.

```
Core was generated by `postgres: postgres postgres 172.151.23.80(58476) startup                      '.
Program terminated with signal 11, Segmentation fault.
#0  __longjmp () at ../sysdeps/x86_64/__longjmp.S:67
67	../sysdeps/x86_64/__longjmp.S: No such file or directory.

Thread 2 (Thread 0x7fe1af90b700 (LWP 10709)):
#0  pthread_cond_timedwait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:225
No locals.
#1  0x00007fe1c1b72f2b in std::__1::condition_variable::__do_timed_wait(std::__1::unique_lock<std::__1::mutex>&, std::__1::chrono::time_point<std::__1::chrono::system_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > >) () from /home/yugabyte/yb-software/yugabyte-2.17.1.0-b3113-centos-x86_64/postgres/../lib/yb-thirdparty/libc++.so.1
No symbol table info available.
#2  0x00007fe1bd6337cd in yb::(anonymous namespace)::LongOperationTrackerHelper::Execute() () from /home/yugabyte/yb-software/yugabyte-2.17.1.0-b3113-centos-x86_64/lib/yb/libyb_util.so
No symbol table info available.
#3  0x00007fe1bd633d42 in void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, std::__1::__bind<void (yb::(anonymous namespace)::LongOperationTrackerHelper::*)(), yb::(anonymous namespace)::LongOperationTrackerHelper*> > >(void*) () from /home/yugabyte/yb-software/yugabyte-2.17.1.0-b3113-centos-x86_64/lib/yb/libyb_util.so
No symbol table info available.
#4  0x00007fe1c25a6694 in start_thread (arg=0x7fe1af90b700) at pthread_create.c:333
        __res = <optimized out>
        pd = 0x7fe1af90b700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140607289865984, -1920157504747514942, 0, 140607298223663, 26, 140607289865984, 1916675043974796226, 1916772403938284482}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#5  0x00007fe1c1ce341d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
No locals.

Thread 1 (Thread 0x7fe1bcd8d1c0 (LWP 10674)):
#0  __longjmp () at ../sysdeps/x86_64/__longjmp.S:67
No locals.
#1  0xa9e172ad1d76205c in ?? ()
No symbol table info available.
Cannot access memory at address 0xa9e172ad1d76205c
```

**Comment by shamanthchandra-yb** [comment]
I was able to hit this issue while testing out packed columns:

Test: creating indexes + tserver restart, core dump is seen.

![Profile (4)](https://user-images.githubusercontent.com/109518123/210238495-464931d8-43ad-45a3-879e-1942a359e356.png)

```
(lldb) target create "/home/yugabyte/yb-software/yugabyte-2.16.1.0-b22-centos-x86_64/postgres/bin/postgres" --core "/home/yugabyte/cores/core_postgres.14891"
Core file '/home/yugabyte/cores/core_postgres.14891' (x86_64) was loaded.
warning: This version of LLDB has no plugin for the language "assembler". Inspection of frame variables will be limited.
(lldb) bt all
warning: This version of LLDB has no plugin for the language "assembler". Inspection of frame variables will be limited.
* thread #1, name = 'postgres', stop reason = signal SIGSEGV
  * frame #0: 0x00007f75b1dd1f9e libc.so.6`__longjmp at __longjmp.S:67
  thread #2, stop reason = signal 0
    frame #0: 0x00007f75b274d3b8 libpthread.so.0`pthread_cond_timedwait@@GLIBC_2.3.2 at pthread_cond_timedwait.S:225
    frame #1: 0x00007f75b1d0b26b libc++.so.1`std::__1::condition_variable::__do_timed_wait(std::__1::unique_lock<std::__1::mutex>&, std::__1::chrono::time_point<std::__1::chrono::system_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l>>>) + 91
    frame #2: 0x00007f75add44b40 libyb_util.so`yb::(anonymous namespace)::LongOperationTrackerHelper::Execute() [inlined] std::__1::cv_status std::__1::condition_variable::wait_for<long long, std::__1::ratio<1l, 1000000000l>>(this=0x00007f75ade56ba8, __lk=0x00007f75a006f428, __d=<unavailable>) at __mutex_base:0:72
    frame #3: 0x00007f75add44ab9 libyb_util.so`yb::(anonymous namespace)::LongOperationTrackerHelper::Execute(this=0x00007f75ade56b60) at long_operation_tracker.cc:107:19
    frame #4: 0x00007f75add45112 libyb_util.so`void* std::__1::__thread_proxy[abi:v15002]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, std::__1::__bind<void (yb::(anonymous namespace)::LongOperationTrackerHelper::*)(), yb::(anonymous namespace)::LongOperationTrackerHelper*>>>(void*) [inlined] decltype(__f=<unavailable>, __a0=<unavailable>)::LongOperationTrackerHelper*&>().*std::declval<void (yb::(anonymous namespace)::LongOperationTrackerHelper::*&)()>()()) std::__1::__invoke[abi:v15002]<void (yb::(anonymous namespace)::LongOperationTrackerHelper::*&)(), yb::(anonymous namespace)::LongOperationTrackerHelper*&, void>(void (yb::(anonymous namespace)::LongOperationTrackerHelper::*&)(), yb::(anonymous namespace)::LongOperationTrackerHelper*&) at invoke.h:359:23
    frame #5: 0x00007f75add45100 libyb_util.so`void* std::__1::__thread_proxy[abi:v15002]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, std::__1::__bind<void (yb::(anonymous namespace)::LongOperationTrackerHelper::*)(), yb::(anonymous namespace)::LongOperationTrackerHelper*>>>(void*) [inlined] std::__1::__bind_return<void (yb::(anonymous namespace)::LongOperationTrackerHelper::*)(), std::__1::tuple<yb::(anonymous namespace)::LongOperationTrackerHelper*>, std::__1::tuple<>, __is_valid_bind_return<void (yb::(anonymous namespace)::LongOperationTrackerHelper::*)(), std::__1::tuple<yb::(anonymous namespace)::LongOperationTrackerHelper*>, std::__1::tuple<>>::value>::type std::__1::__apply_functor[abi:v15002]<void (__f=<unavailable>, __bound_args=<unavailable>, (null)=<unavailable>, __args=<unavailable>)::LongOperationTrackerHelper::*)(), std::__1::tuple<yb::(anonymous namespace)::LongOperationTrackerHelper*>, 0ul, std::__1::tuple<>>(void (yb::(anonymous namespace)::LongOperationTrackerHelper::*&)(), std::__1::tuple<yb::(anonymous namespace)::LongOperationTrackerHelper*>&, std::__1::__tuple_indices<0ul>, std::__1::tuple<>&&) at bind.h:263:12
    frame #6: 0x00007f75add45100 libyb_util.so`void* std::__1::__thread_proxy[abi:v15002]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, std::__1::__bind<void (yb::(anonymous namespace)::LongOperationTrackerHelper::*)(), yb::(anonymous namespace)::LongOperationTrackerHelper*>>>(void*) [inlined] std::__1::__bind_return<void (yb::(anonymous namespace)::LongOperationTrackerHelper::*)(), std::__1::tuple<yb::(anonymous namespace)::LongOperationTrackerHelper*>, std::__1::tuple<>, __is_valid_bind_return<void (yb::(anonymous namespace)::LongOperationTrackerHelper::*)(), std::__1::tuple<yb::(anonymous namespace)::LongOperationTrackerHelper*>, std::__1::tuple<>>::value>::type std::__1::__bind<void (this=0x0000560b41176048)::LongOperationTrackerHelper::*)(), yb::(anonymous namespace)::LongOperationTrackerHelper*>::operator()[abi:v15002]<>() at bind.h:295:20
    frame #7: 0x00007f75add450f8 libyb_util.so`void* std::__1::__thread_proxy[abi:v15002]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, std::__1::__bind<void (yb::(anonymous namespace)::LongOperationTrackerHelper::*)(), yb::(anonymous namespace)::LongOperationTrackerHelper*>>>(void*) [inlined] decltype(__f=0x0000560b41176048)::LongOperationTrackerHelper::*)(), yb::(anonymous namespace)::LongOperationTrackerHelper*>>()()) std::__1::__invoke[abi:v15002]<std::__1::__bind<void (yb::(anonymous namespace)::LongOperationTrackerHelper::*)(), yb::(anonymous namespace)::LongOperationTrackerHelper*>>(std::__1::__bind<void (yb::(anonymous namespace)::LongOperationTrackerHelper::*)(), yb::(anonymous namespace)::LongOperationTrackerHelper*>&&) at invoke.h:394:23
    frame #8: 0x00007f75add450f8 libyb_util.so`void* std::__1::__thread_proxy[abi:v15002]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, std::__1::__bind<void (yb::(anonymous namespace)::LongOperationTrackerHelper::*)(), yb::(anonymous namespace)::LongOperationTrackerHelper*>>>(void*) [inlined] void std::__1::__thread_execute[abi:v15002]<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, std::__1::__bind<void (yb::(anonymous namespace)::LongOperationTrackerHelper::*)(), yb::(anonymous namespace)::LongOperationTrackerHelper*>>(__t=0x0000560b41176040, (null)=<unavailable>)::LongOperationTrackerHelper::*)(), yb::(anonymous namespace)::LongOperationTrackerHelper*>>&, std::__1::__tuple_indices<>) at thread:284:5
    frame #9: 0x00007f75add450f8 libyb_util.so`void* std::__1::__thread_proxy[abi:v15002]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, std::__1::__bind<void (yb::(anonymous namespace)::LongOperationTrackerHelper::*)(), yb::(anonymous namespace)::LongOperationTrackerHelper*>>>(__vp=0x0000560b41176040) at thread:295:5
    frame #10: 0x00007f75b2748694 libpthread.so.0`start_thread(arg=0x00007f75a0077700) at pthread_create.c:333
    frame #11: 0x00007f75b1e8541d libc.so.6`__clone at clone.S:109

```
cc: @m-iancu @kripasreenivasan
