### ISSUE TITLE
Java test framework failure due to master process exit with error code 141

### ISSUE THREAD

**Issue by OlegLoginov** [YugaByte/yugabyte-db#1456]
The case reproduced from TestIndex java test:
`ybd --java-test org.yb.cql.TestIndex`
All individual tests were passed successfully, but all-in-one test run fails with the error:
```[INFO] Running org.yb.cql.TestIndex
[ERROR] Tests run: 22, Failures: 0, Errors: 14, Skipped: 0, Time elapsed: 284.262 s <<< FAILURE! - in org.yb.cql.TestIndex
[ERROR] testPreparedStatement(org.yb.cql.TestIndex)  Time elapsed: 61.091 s  <<< ERROR!
java.lang.Exception: We tried starting a process (/Users/oleg/code/yugabyte/build/debug-clang-dynamic-enterprise-ninja/bin/yb-master) but it exited with value=141
	at org.yb.cql.TestIndex.testPreparedStatement(TestIndex.java:579)

[ERROR] testUncoveredIndex(org.yb.cql.TestIndex)  Time elapsed: 0.334 s  <<< ERROR!
java.lang.Exception: We tried starting a process (/Users/oleg/code/yugabyte/build/debug-clang-dynamic-enterprise-ninja/bin/yb-master) but it exited with value=141
...
```

**Comment by OlegLoginov** [comment]
In the log:
```2019-05-30 18:44:36,492 (Time-limited test) [INFO - org.yb.minicluster.MiniYBCluster.startCluster(MiniYBCluster.java:431)] Starting 3 masters...
2019-05-30 18:44:36,518 (Time-limited test) [INFO - org.yb.minicluster.MiniYBCluster.updateMasterAddresses(MiniYBCluster.java:470)] Retrieved flags file content: --log_dir=target/testdata
--max_message_size=67108864
--webserver_port=0
--tserver_master_addrs=127.0.1.214:18863,127.0.2.14:28148,127.0.3.238:30312

2019-05-30 18:44:36,519 (Time-limited test) [INFO - org.yb.minicluster.MiniYBCluster.updateMasterAddresses(MiniYBCluster.java:479)] Wrote flags file content: --log_dir=target/testdata
--max_message_size=67108864
--webserver_port=0
--tserver_master_addrs=127.0.0.109:16114,127.0.3.24:15012,127.0.1.5:17604

2019-05-30 18:44:36,519 (Time-limited test) [INFO - org.yb.minicluster.MiniYBCluster.configureAndStartProcess(MiniYBCluster.java:765)] Starting process: /Users/oleg/code/yugabyte/build/debug-clang-dynamic-enterprise-ninja/bin/yb-master --flagfile=/tmp/ybtest-oleg-1559230792828-97259057/yb-flags5424879497473017342.flags --fs_wal_dirs=/tmp/ybtest-oleg-1559230792828-97259057/master-127.0.0.109-16114-1559231076519 --fs_data_dirs=/tmp/ybtest-oleg-1559230792828-97259057/master-127.0.0.109-16114-1559231076519 --webserver_interface=127.0.0.109 --local_ip_for_outbound_sockets=127.0.0.109 --rpc_bind_addresses=127.0.0.109:16114 --tserver_unresponsive_timeout_ms=5000 --catalog_manager_bg_task_wait_ms=500 --rpc_slow_query_threshold_ms=10000000 --webserver_port=24111 --callhome_enabled=false --logtostderr --logbuflevel=-1 --webserver_doc_root=/Users/oleg/.m2/repository/org/yb/yb-client/0.8.0-SNAPSHOT/www --yb_test_name=org.yb.cql.TestIndex --memory_limit_hard_bytes=1073741824 --yb_num_shards_per_tserver=3 --master_addresses=127.0.0.109:16114,127.0.3.24:15012,127.0.1.5:17604 --fatal_details_path_prefix=/Users/oleg/code/yugabyte/java/yb-cql/target/surefire-reports_org.yb.cql.TestIndex/org.yb.cql.TestIndex.testPreparedStatement.fatal_failure_details.m-1.127.0.0.109-port16114 --logtostderr --logbuflevel=-1 --webserver_doc_root=/Users/oleg/.m2/repository/org/yb/yb-client/0.8.0-SNAPSHOT/www --yb_test_name=org.yb.cql.TestIndex --memory_limit_hard_bytes=1073741824 --yb_num_shards_per_tserver=3 with environment {}
2019-05-30 18:44:36,525 (Time-limited test) [INFO - org.yb.minicluster.MiniYBDaemon.<init>(MiniYBDaemon.java:240)] Started stdout/stderr threads for mini YB daemon: master process on bind IP 127.0.0.109, rpc port 16114, web port 24111, pid 5336
m1|pid5336|:16114|http://127.0.0.109:24111 I0530 18:44:36.569488 173204928 master_main.cc:93] HELLO 1 
2019-05-30 18:44:36,573 (Termination handler for master process on bind IP 127.0.0.109, rpc port 16114, web port 24111, pid 5336) [INFO - org.yb.minicluster.MiniYBDaemon$TerminationHandler.handleTermination(MiniYBDaemon.java:143)] 0Process master process on bind IP 127.0.0.109, rpc port 16114, web port 24111, pid 5336 exited with code 141 (abnormal termination)
2019-05-30 18:44:36,828 (Time-limited test) [INFO - org.yb.cql.BaseCQLTest.tearDownAfter(BaseCQLTest.java:219)] BaseCQLTest.tearDownAfter: mini cluster has been destroyed
2019-05-30 18:44:36,829 (main) [ERROR - org.yb.BaseYBTest$1$2.logEventDetails(BaseYBTest.java:240)] YB Java test failed: class="org.yb.cql.TestIndex", method="testPreparedStatement"
java.lang.Exception: We tried starting a process (/Users/oleg/code/yugabyte/build/debug-clang-dynamic-enterprise-ninja/bin/yb-master) but it exited with value=141
	at org.yb.minicluster.MiniYBCluster.configureAndStartProcess(MiniYBCluster.java:775)
	at org.yb.minicluster.MiniYBCluster.startMasters(MiniYBCluster.java:699)
	at org.yb.minicluster.MiniYBCluster.startCluster(MiniYBCluster.java:432)
	at org.yb.minicluster.MiniYBCluster.<init>(MiniYBCluster.java:185)
	at org.yb.minicluster.MiniYBClusterBuilder.build(MiniYBClusterBuilder.java:170)
	at org.yb.minicluster.BaseMiniClusterTest.createMiniCluster(BaseMiniClusterTest.java:181)
	at org.yb.minicluster.BaseMiniClusterTest.createMiniCluster(BaseMiniClusterTest.java:150)
	at org.yb.minicluster.BaseMiniClusterTest.createMiniCluster(BaseMiniClusterTest.java:135)
	at org.yb.minicluster.BaseMiniClusterTest.setUpBefore(BaseMiniClusterTest.java:112)
	at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
```

**Comment by OlegLoginov** [comment]
Exit code 141 (as all codes > 128) means that the process got signal = 141-128 = 13 = SIGPIPE.

**Comment by OlegLoginov** [comment]
Source code in the test:
```    destroyMiniCluster();
    createMiniCluster();      <<< FAILED
```

In the MiniYBCluster:
```    LOG.info("Starting process: {} with environment {}", Joiner.on(" ").join(command), envString);
    Process proc = procBuilder.start();
    final MiniYBDaemon daemon =
        new MiniYBDaemon(type, indexForLog, command, proc, bindIp, rpcPort, webPort,
                         pgsqlWebPort, cqlWebPort, redisWebPort, dataDirPath);
    logPrinters.add(daemon.getLogPrinter());

    Thread.sleep(300);
    try {
      int ev = proc.exitValue();
      throw new Exception("We tried starting a process (" + command[0] + ") but it exited with " +
          "value=" + ev);
    } catch (IllegalThreadStateException ex) {
      // This means the process is still alive, it's like reverse psychology.
    }

    LOG.info("Started " + command[0] + " as pid " + ProcessUtil.pidOfProcess(proc));
```

**Comment by OlegLoginov** [comment]
Looks like the process cannot write anything to the output stream (it should be STDERR due to ` --logtostderr` flag). Possible cause - controlling daemon thread is not yet ready/started while the process tries to print something.

**Comment by OlegLoginov** [comment]
From the logs:  the master started successfully first 6 times. From 7-th run it starts failing with error code 141 (SIGPIPE).

**Comment by OlegLoginov** [comment]
Root cause: the LogPrinter (from the java test framework) closed master/tserver process output stream, so the process was killed by SIGPIPE signal (code=141=128+13=128+SIGPIPE). It happens due to the limited log size controlled by the variable:
  ```private static final long MAX_ALLOWED_LOGGED_BYTES =
      EnvAndSysPropertyUtil.getLongEnvVarOrSystemProperty(
          "YB_JAVA_TEST_MAX_ALLOWED_LOG_BYTES",
          50 * 1024 * 1024);```
`50 MB` by default. To fix the fail you can increase the default value or use the mentioned `YB_JAVA_TEST_MAX_ALLOWED_LOG_BYTES` env variable.

The main problem actually in such case that the LogPrinter closed the streams silently - without any logs - I'll fix it.

**Comment by OlegLoginov** [comment]
Fix: improved diagnostic logs & changed the log size limit for package-run mode of the test runs:
https://github.com/YugaByte/yugabyte-db/commit/0b1d7295aaa8a8a188fb825277f6cb2d2e06fe85
