### ISSUE TITLE
Postgres Core dump is seen when enabled packed rows with YSQL, when DDLs running

### ISSUE THREAD

**Issue by shamanthchandra-yb** [yugabyte/yugabyte-db#14587]
Jira Link: [DB-3960](https://yugabyte.atlassian.net/browse/DB-3960)
### Description

1. Started a workload with DDL
```
nohup java  -jar /tmp/tests/artifacts/sample-app-tool/yb-sample-apps-1.8.23.jar --workload SqlDataLoadWithDDL  --uuid 783f7114-c438-4996-a5a1-696c04caa212 --create_table_name test_packed_columns_sql_d27487 --num_writes -1 --num_threads_write 20 --num_reads -1 --num_threads_read 20 --num_unique_keys 10000000000 --num_value_columns 100 --batch_size 10 --num_indexes 2 --use_unique_index true --ddl_operations DELETE_ROW,UPDATE_ROW,DELETE_ROWS,UPDATE_ROWS,ADD_COLUMN,DROP_COLUMN --uuid_marker 64305d71-2807-4cb6-b92c-0988c0a9456e --nodes 172.151.20.23:5433,172.151.26.37:5433,172.151.27.143:5433 2>&1
```

2. Enabled ysql packed row flag only on tserver.

Core dump was seen:
Tried to analyze with lldb (nothing much useful info got):
<img width="972" alt="Screenshot 2022-10-19 at 9 24 05 PM (1)" src="https://user-images.githubusercontent.com/109518123/197125808-ccc52b1a-9949-415e-a61c-d4c1bcfa1527.png">

[core_postgres.27863.zip](https://github.com/yugabyte/yugabyte-db/files/9836194/core_postgres.27863.zip)

Via GDB 12.1 analysed the core. Here is the stack trace:

```
Thread 2 (LWP 27922):
#0  pthread_cond_timedwait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:225
#1  0x00007f869c2f00cb in std::__1::condition_variable::__do_timed_wait(std::__1::unique_lock<std::__1::mutex>&, std::__1::chrono::time_point<std::__1::chrono::system_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > >) () from /home/yugabyte/yb-software/yugabyte-2.17.1.0-b46-centos-x86_64/postgres/../lib/yb-thirdparty/libc++.so.1
#2  0x00007f869833b92d in std::__1::condition_variable::wait_for<long long, std::__1::ratio<1l, 1000000000l> > (this=0x7f869844575c <yb::(anonymous namespace)::LongOperationTrackerHelper::Instance()::result+76>, __lk=..., __d=...) at /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20221010235007-8f0b4a580c-almalinux8-x86_64-clang14-linuxbrew-full-lto/installed/uninstrumented/libcxx/include/c++/v1/__mutex_base:462
#3  yb::(anonymous namespace)::LongOperationTrackerHelper::Execute (this=0x7f8698445710 <yb::(anonymous namespace)::LongOperationTrackerHelper::Instance()::result>) at ../../src/yb/util/debug/long_operation_tracker.cc:107
#4  0x00007f869833be52 in std::__1::__invoke<void (yb::(anonymous namespace)::LongOperationTrackerHelper::*&)(), yb::(anonymous namespace)::LongOperationTrackerHelper*&, , void>(void (yb::(anonymous namespace)::LongOperationTrackerHelper::*&)(), yb::(anonymous namespace)::LongOperationTrackerHelper*&) (__a0=@0x2d44018: 0x7f8698445710 <yb::(anonymous namespace)::LongOperationTrackerHelper::Instance()::result>, __f=<optimized out>) at /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20221010235007-8f0b4a580c-almalinux8-x86_64-clang14-linuxbrew-full-lto/installed/uninstrumented/libcxx/include/c++/v1/type_traits:3565
#5  std::__1::__apply_functor<void (yb::(anonymous namespace)::LongOperationTrackerHelper::*)(), std::__1::tuple<yb::(anonymous namespace)::LongOperationTrackerHelper*>, 0ul, std::__1::tuple<> >(void (yb::(anonymous namespace)::LongOperationTrackerHelper::*&)(), std::__1::tuple<yb::(anonymous namespace)::LongOperationTrackerHelper*>&, std::__1::__tuple_indices<0ul>, std::__1::tuple<>&&) (__bound_args=..., __f=<optimized out>, __args=...) at /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20221010235007-8f0b4a580c-almalinux8-x86_64-clang14-linuxbrew-full-lto/installed/uninstrumented/libcxx/include/c++/v1/__functional/bind.h:263
#6  std::__1::__bind<void (yb::(anonymous namespace)::LongOperationTrackerHelper::*)(), yb::(anonymous namespace)::LongOperationTrackerHelper*>::operator()<>() (this=0x2d44008) at /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20221010235007-8f0b4a580c-almalinux8-x86_64-clang14-linuxbrew-full-lto/installed/uninstrumented/libcxx/include/c++/v1/__functional/bind.h:298
--Type <RET> for more, q to quit, c to continue without paging--
#7  std::__1::__invoke<std::__1::__bind<void (yb::(anonymous namespace)::LongOperationTrackerHelper::*)(), yb::(anonymous namespace)::LongOperationTrackerHelper*>>(std::__1::__bind<void (yb::(anonymous namespace)::LongOperationTrackerHelper::*)(), yb::(anonymous namespace)::LongOperationTrackerHelper*>&&) (__f=...) at /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20221010235007-8f0b4a580c-almalinux8-x86_64-clang14-linuxbrew-full-lto/installed/uninstrumented/libcxx/include/c++/v1/type_traits:3640
#8  std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, std::__1::__bind<void (yb::(anonymous namespace)::LongOperationTrackerHelper::*)(), yb::(anonymous namespace)::LongOperationTrackerHelper*>>(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, std::__1::__bind<void (yb::(anonymous namespace)::LongOperationTrackerHelper::*)(), yb::(anonymous namespace)::LongOperationTrackerHelper*>>&, std::__1::__tuple_indices<>) (__t=...) at /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20221010235007-8f0b4a580c-almalinux8-x86_64-clang14-linuxbrew-full-lto/installed/uninstrumented/libcxx/include/c++/v1/thread:282
#9  std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, std::__1::__bind<void (yb::(anonymous namespace)::LongOperationTrackerHelper::*)(), yb::(anonymous namespace)::LongOperationTrackerHelper*> > > (__vp=0x2d44000) at /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20221010235007-8f0b4a580c-almalinux8-x86_64-clang14-linuxbrew-full-lto/installed/uninstrumented/libcxx/include/c++/v1/thread:293
#10 0x00007f869cd2e694 in start_thread (arg=0x7f868a667700) at pthread_create.c:333
#11 0x00007f869c46b41d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 1 (LWP 27863):
#0  __longjmp () at ../sysdeps/x86_64/__longjmp.S:67
#1  0x7da625b750ee37a2 in ?? ()
Backtrace stopped: Cannot access memory at address 0x7da625b750ee37a2
```

**Comment by rthallamko3** [comment]
@shamanthchandra-yb , Assigning to you to obtain the backtrace and then route it to LRT team as the dump seems to be in postgres area.

**Comment by shamanthchandra-yb** [comment]
Tried with gdb 12.1, still we are not able to see symbols from our code.

![Screenshot 2022-10-27 at 12 47 57 PM](https://user-images.githubusercontent.com/109518123/198221369-ddea5af3-6487-40b2-ab8c-3e5ae918ec30.png)

**Comment by shamanthchandra-yb** [comment]
On GDB 12.1, fetched backtraces from all threads: Attached to the description.
Please check @m-iancu @tverona1

**Comment by shamanthchandra-yb** [comment]
Not seen this issue recently. Closing it.
