### ISSUE TITLE
[YSQL] UBSAN error in PgLibPqTest.DBCatalogVersion

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#14662]
Jira Link: [DB-4025](https://yugabyte.atlassian.net/browse/DB-4025)
### Description

https://detective-gcp.dev.yugabyte.com/stability/test?branch=master&build_type=all&class=PgLibPqTest&fail_tag=undefined_behavior&name=DBCatalogVersion&platform=linux

https://jenkins.dev.yugabyte.com/job/github-yugabyte-db-alma8-master-clang13-asan/189/artifact/build/asan-clang13-dynamic-ninja/yb-test-logs/tests-pgwrapper__pg_libpq-test/PgLibPqTest_DBCatalogVersion.log

```
[ts-1]     #0 0xa6656a in YbGetTserverCatalogVersion ${YB_SRC_ROOT}/src/postgres/src/backend/catalog/yb_catalog/../../../../../../../src/postgres/src/backend/catalog/yb_catalog/yb_catalog_version.c:470:36
[ts-1]     #1 0x179b0a0 in YbResolveDBTserverCatalogVersion ${YB_SRC_ROOT}/src/postgres/src/backend/utils/init/../../../../../../../src/postgres/src/backend/utils/init/postinit.c:1170:33
[ts-1]     #2 0x1797aa4 in InitPostgresImpl ${YB_SRC_ROOT}/src/postgres/src/backend/utils/init/../../../../../../../src/postgres/src/backend/utils/init/postinit.c
[ts-1]     #3 0x1797135 in InitPostgres ${YB_SRC_ROOT}/src/postgres/src/backend/utils/init/../../../../../../../src/postgres/src/backend/utils/init/postinit.c:1201:3
[ts-1]     #4 0x1357d86 in PostgresMain ${YB_SRC_ROOT}/src/postgres/src/backend/tcop/../../../../../../src/postgres/src/backend/tcop/postgres.c:4847:2
[ts-1]     #5 0x119d7b0 in BackendRun ${YB_SRC_ROOT}/src/postgres/src/backend/postmaster/../../../../../../src/postgres/src/backend/postmaster/postmaster.c:4576:2
[ts-1]     #6 0x119b959 in BackendStartup ${YB_SRC_ROOT}/src/postgres/src/backend/postmaster/../../../../../../src/postgres/src/backend/postmaster/postmaster.c:4214:3
[ts-1]     #7 0x119b959 in ServerLoop ${YB_SRC_ROOT}/src/postgres/src/backend/postmaster/../../../../../../src/postgres/src/backend/postmaster/postmaster.c:1768:7
[ts-1]     #8 0x1193cce in PostmasterMain ${YB_SRC_ROOT}/src/postgres/src/backend/postmaster/../../../../../../src/postgres/src/backend/postmaster/postmaster.c:1424:11
[ts-1]     #9 0xf66520 in PostgresServerProcessMain ${YB_SRC_ROOT}/src/postgres/src/backend/main/../../../../../../src/postgres/src/backend/main/main.c:234:3
[ts-1]     #10 0xf66961 in main (${BUILD_ROOT}/postgres/bin/postgres+0xf66961)
[ts-1]     #11 0x7fbd70794cf2 in __libc_start_main (/lib64/libc.so.6+0x3acf2)
[ts-1]     #12 0x7820fd in _start (${BUILD_ROOT}/postgres/bin/postgres+0x7820fd)
[ts-1] 
[ts-1] SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior ../../../../../../../src/postgres/src/backend/catalog/yb_catalog/yb_catalog_version.c:472:5 in 

```

**Comment by d-uspenskiy** [comment]
Fixed in context of #14309
