### ISSUE TITLE
[JDBC Smart Driver] socketTimeout not being honored in all cases.

### ISSUE THREAD

**Issue by ssherwood** [yugabyte/yugabyte-db#14664]
Jira Link: [DB-4027](https://yugabyte.atlassian.net/browse/DB-4027)
### Description

I have added a `connectionInitSql` to my HikariCP in my application.  This query can be slow at times depending on the environment.  I've observed that for some reason this query always seems to time out if it goes longer than 5 seconds.  This happens regardless of how large I configure `socketTimeout`.

The default behavor of a Java Socket is to time out in 5 seconds, so there appears to be a path in the driver code that does not configure the timeouts correctly (or are being ignored).

```
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.base/sun.nio.ch.NioSocketImpl.timedRead(NioSocketImpl.java:283) ~[na:na]
	at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:309) ~[na:na]
	at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:350) ~[na:na]
	at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:803) ~[na:na]
	at java.base/java.net.Socket$SocketInputStream.read(Socket.java:966) ~[na:na]
	at com.yugabyte.core.VisibleBufferedInputStream.readMore(VisibleBufferedInputStream.java:161) ~[jdbc-yugabytedb-42.3.5-yb-1.jar:42.3.5-yb-1]
	at com.yugabyte.core.VisibleBufferedInputStream.ensureBytes(VisibleBufferedInputStream.java:128) ~[jdbc-yugabytedb-42.3.5-yb-1.jar:42.3.5-yb-1]
	at com.yugabyte.core.VisibleBufferedInputStream.ensureBytes(VisibleBufferedInputStream.java:113) ~[jdbc-yugabytedb-42.3.5-yb-1.jar:42.3.5-yb-1]
	at com.yugabyte.core.VisibleBufferedInputStream.read(VisibleBufferedInputStream.java:73) ~[jdbc-yugabytedb-42.3.5-yb-1.jar:42.3.5-yb-1]
	at com.yugabyte.core.PGStream.receiveChar(PGStream.java:453) ~[jdbc-yugabytedb-42.3.5-yb-1.jar:42.3.5-yb-1]
	at com.yugabyte.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2119) ~[jdbc-yugabytedb-42.3.5-yb-1.jar:42.3.5-yb-1]
	at com.yugabyte.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:355) ~[jdbc-yugabytedb-42.3.5-yb-1.jar:42.3.5-yb-1]
	... 130 common frames omitted
```

To simplify testing, I used `select * from pg_sleep(6)` as my `connectionInitSql` in HikariCP.

**Comment by ssherwood** [comment]
Just confirmed that this is because of the default configuration for HikariCP `validationTimeout` of 5 seconds:

**validationTimeout**
This property controls the maximum amount of time that a connection will be tested for aliveness. This value must be less than the `connectionTimeout`. Lowest acceptable validation timeout is 250 ms. Default: 5000

Setting this value higher than the pg_sleep() causes the connections to be established, run the `connectionInitQuery` and be put into the pool w/o a timeout.
