### ISSUE TITLE
[YugabyteD] [QA] Handle condition gracefully if configuring YuagabyteD without starting it

### ISSUE THREAD

**Issue by zlareb1-yb** [yugabyte/yugabyte-db#14739]
### Description

If we are configuring yugabyted without starting it - Yugabyted crashes

In below eg. base_dir doesn't exists
```
MacBook-Pro-16-inch-2021:yugabyte-2.17.1.0 mzafar$ ./bin/yugabyted configure --base_dir=/Users/mzafar/l
yugabyted crashed. For troubleshooting, contact us on https://www.yugabyte.com/slack or check our FAQ at https://docs.yugabyte.com/latest/faq/
Traceback (most recent call last):
  File "./bin/yugabyted", line 2832, in run
    args.func()
  File "./bin/yugabyted", line 609, in configure
    current_masters = self.get_all_masters()
  File "./bin/yugabyted", line 1525, in get_all_masters
    raise RetryableError()
RetryableError

For more information, check the logs in /Users/mzafar/l/logs
```

Below logs are available in /Users/mzafar/l/logs/yugabyted.log
```
[yugabyted configure] 2022-10-29 14:46:11,221 INFO:  | 0.0s | cmd = configure using config file: /Users/mzafar/l/conf/yugabyted.conf (args.config=None)
[yugabyted configure] 2022-10-29 14:46:11,221 INFO:  | 0.0s | Found directory /Users/mzafar/ybd/a/yugabyte-2.17.1.0/bin for file gen_certs.sh
[yugabyted configure] 2022-10-29 14:46:11,222 INFO:  | 0.0s | Found directory /Users/mzafar/ybd/a/yugabyte-2.17.1.0/bin for file yb-admin
[yugabyted configure] 2022-10-29 14:46:11,222 ERROR:  | 0.0s | Traceback (most recent call last):
  File "./bin/yugabyted", line 2832, in run
    args.func()
  File "./bin/yugabyted", line 609, in configure
    current_masters = self.get_all_masters()
  File "./bin/yugabyted", line 1525, in get_all_masters
    raise RetryableError()
RetryableError

For more information, check the logs in /Users/mzafar/l/logs
```

We should have pre flight checks to ensure YugabyteD was started from this base_dir and contents of this dir are correct

**Comment by zlareb1-yb** [comment]
Similar is the case if YugabyteD is stopped:

```
MacBook-Pro-16-inch-2021:yugabyte-2.17.1.0 mzafar$ ./bin/yugabyted stop
Stopped yugabyted using config /Users/mzafar/var/conf/yugabyted.conf.
MacBook-Pro-16-inch-2021:yugabyte-2.17.1.0 mzafar$ ./bin/yugabyted configure
yugabyted crashed. For troubleshooting, contact us on https://www.yugabyte.com/slack or check our FAQ at https://docs.yugabyte.com/latest/faq/
Traceback (most recent call last):
  File "./bin/yugabyted", line 2832, in run
    args.func()
  File "./bin/yugabyted", line 609, in configure
    current_masters = self.get_all_masters()
  File "./bin/yugabyted", line 1525, in get_all_masters
    raise RetryableError()
RetryableError

For more information, check the logs in /Users/mzafar/var/logs
```

**Comment by gargsans-yb** [comment]
Landed the code fix.
