### ISSUE TITLE
[YSQL][Unit Test] detected memory leaks in TestQLCreateIndex.TestQLCreateIndexExpr

### ISSUE THREAD

**Issue by def-** [yugabyte/yugabyte-db#14796]
Jira Link: [DB-4111](https://yugabyte.atlassian.net/browse/DB-4111)
### Description

On [2.17.1.0-b139](https://detective.dev.yugabyte.com/?commits=59f9cbde784b456b2e2603058edd2a3e1122093c) TestQLCreateIndex.TestQLCreateIndexExpr is indicating a potential productive code memory leak:
```
==338434==ERROR: LeakSanitizer: detected memory leaks

Indirect leak of 1600 byte(s) in 1 object(s) allocated from:
    #0 0x7f3953a2d15d in operator new(unsigned long) /opt/yb-build/llvm/yb-llvm-v13.0.1-yb-2-1659059078-0131d8e1-almalinux8-x86_64-build/src/llvm-project/compiler-rt/lib/asan/asan_new_delete.cpp:95:3
    #1 0x7f3951f8ecf3 in void* {std::}__libcpp_operator_new<unsigned long>(unsigned long) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20221019013159-1aec6dda08-almalinux8-x86_64-clang13/installed/asan/libcxx/include/c++/v1/new:235:10
    #2 0x7f3951f8ecf3 in {std::}__libcpp_allocate(unsigned long, unsigned long) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20221019013159-1aec6dda08-almalinux8-x86_64-clang13/installed/asan/libcxx/include/c++/v1/new:261:10
    #3 0x7f3951f8ecf3 in {std::}allocator<{std::}shared_ptr<yb::server::MonitoredTask> >::allocate(unsigned long) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20221019013159-1aec6dda08-almalinux8-x86_64-clang13/installed/asan/libcxx/include/c++/v1/__memory/allocator.h:108:38
    #4 0x7f3951f8ecf3 in boost::circular_buffer<{std::}shared_ptr<yb::server::MonitoredTask>, {std::}allocator<{std::}shared_ptr<yb::server::MonitoredTask> > >::allocate(unsigned long) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20221019013159-1aec6dda08-almalinux8-x86_64-clang13/installed/asan/include/boost/circular_buffer/base.hpp:2396:39
    #5 0x7f3951f8e444 in boost::circular_buffer<{std::}shared_ptr<yb::server::MonitoredTask>, {std::}allocator<{std::}shared_ptr<yb::server::MonitoredTask> > >::initialize_buffer(unsigned long) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20221019013159-1aec6dda08-almalinux8-x86_64-clang13/installed/asan/include/boost/circular_buffer/base.hpp:2494:18
    #6 0x7f3951f8e444 in boost::circular_buffer<{std::}shared_ptr<yb::server::MonitoredTask>, {std::}allocator<{std::}shared_ptr<yb::server::MonitoredTask> > >::circular_buffer(unsigned long, {std::}allocator<{std::}shared_ptr<yb::server::MonitoredTask> > const&) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20221019013159-1aec6dda08-almalinux8-x86_64-clang13/installed/asan/include/boost/circular_buffer/base.hpp:1039:9
    #7 0x7f3951f8d24e in yb::master::TasksTracker::TasksTracker(yb::StronglyTypedBool<yb::master::IsUserInitiated_Tag>) ${BUILD_ROOT}/../../src/yb/master/tasks_tracker.cc:40:7
    #8 0x7f3951a1c513 in yb::master::CatalogManager::CatalogManager(yb::master::Master*) ${BUILD_ROOT}/../../src/yb/master/catalog_manager.cc:840:26
    #9 0x7f3951d78b98 in yb::master::enterprise::CatalogManager::CatalogManager(yb::master::Master*) ${BUILD_ROOT}/../../ent/src/yb/master/catalog_manager.h:33:9
    #10 0x7f3951d6c040 in yb::master::Master::Master(yb::master::MasterOptions const&) ${BUILD_ROOT}/../../src/yb/master/master.cc:150:28
    #11 0x7f39521d574d in yb::master::enterprise::Master::Master(yb::master::MasterOptions const&) ${BUILD_ROOT}/../../ent/src/yb/master/master_ent.cc:39:45
    #12 0x7f3951e61bf5 in yb::master::MiniMaster::StartOnPorts(unsigned short, unsigned short, yb::master::MasterOptions*) ${BUILD_ROOT}/../../src/yb/master/mini_master.cc:167:38
    #13 0x7f3951e60afc in yb::master::MiniMaster::StartDistributedMasterOnPorts(unsigned short, unsigned short, {std::}vector<unsigned short, {std::}allocator<unsigned short> > const&) ${BUILD_ROOT}/../../src/yb/master/mini_master.cc:208:10
    #14 0x7f3951e5ffbc in yb::master::MiniMaster::StartDistributedMaster({std::}vector<unsigned short, {std::}allocator<unsigned short> > const&) ${BUILD_ROOT}/../../src/yb/master/mini_master.cc:91:10
    #15 0x7f39534f23f2 in yb::MiniCluster::StartMasters() ${BUILD_ROOT}/../../src/yb/integration-tests/mini_cluster.cc:259:37
    #16 0x7f39534f029e in yb::MiniCluster::Start({std::}vector<yb::tserver::TabletServerOptions, {std::}allocator<yb::tserver::TabletServerOptions> > const&) ${BUILD_ROOT}/../../src/yb/integration-tests/mini_cluster.cc:207:3
    #17 0x7f395446d758 in yb::ql::QLTestBase::CreateSimulatedCluster(int) ${BUILD_ROOT}/../../src/yb/yql/cql/ql/test/ql-test-base.cc:71:3
    #18 0x21ea3f in yb::ql::TestQLCreateIndex_TestQLCreateIndexExpr_Test::TestBody() ${BUILD_ROOT}/../../src/yb/yql/cql/ql/test/ql-create-index-test.cc:182:3
    #19 0x7f39458a32ef in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20221019013159-1aec6dda08-almalinux8-x86_64-clang13/src/googletest-1.12.1/googletest/src/gtest.cc:2599:10
    #20 0x7f39458a32ef in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20221019013159-1aec6dda08-almalinux8-x86_64-clang13/src/googletest-1.12.1/googletest/src/gtest.cc:2635:14
    #21 0x7f3945856bc2 in testing::Test::Run() /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20221019013159-1aec6dda08-almalinux8-x86_64-clang13/src/googletest-1.12.1/googletest/src/gtest.cc:2674:5
    #22 0x7f394585890f in testing::TestInfo::Run() /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20221019013159-1aec6dda08-almalinux8-x86_64-clang13/src/googletest-1.12.1/googletest/src/gtest.cc:2853:11
    #23 0x7f394585aea0 in testing::TestSuite::Run() /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20221019013159-1aec6dda08-almalinux8-x86_64-clang13/src/googletest-1.12.1/googletest/src/gtest.cc:3012:30
    #24 0x7f3945882736 in testing::internal::UnitTestImpl::RunAllTests() /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20221019013159-1aec6dda08-almalinux8-x86_64-clang13/src/googletest-1.12.1/googletest/src/gtest.cc:5870:44
    #25 0x7f39458a7e3a in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20221019013159-1aec6dda08-almalinux8-x86_64-clang13/src/googletest-1.12.1/googletest/src/gtest.cc:2599:10
    #26 0x7f39458a7e3a in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20221019013159-1aec6dda08-almalinux8-x86_64-clang13/src/googletest-1.12.1/googletest/src/gtest.cc:2635:14
    #27 0x7f394588136c in testing::UnitTest::Run() /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20221019013159-1aec6dda08-almalinux8-x86_64-clang13/src/googletest-1.12.1/googletest/src/gtest.cc:5444:10
    #28 0x7f395444a840 in RUN_ALL_TESTS() /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20221019013159-1aec6dda08-almalinux8-x86_64-clang13/installed/asan/include/gtest/gtest.h:2293:73
    #29 0x7f395444a840 in main ${BUILD_ROOT}/../../src/yb/util/test_main.cc:109:13
    #30 0x7f394055bcf2 in __libc_start_main (/lib64/libc.so.6+0x3acf2)
```
Full logs: https://gist.github.com/def-/d044291fbf82272d6b3feb3d89091ab4
[TestQLCreateIndex_TestQLCreateIndexExpr.log](https://github.com/yugabyte/yugabyte-db/files/9919002/TestQLCreateIndex_TestQLCreateIndexExpr.log)
Would be good to check if this is just a test issue or also productive, a leak in catalog manager when creating indexes would probably be bad.

**Comment by def-** [comment]
@sanketkedia Just seen there is a bug already for this: https://github.com/yugabyte/yugabyte-db/issues/14228

**Comment by kripasreenivasan** [comment]
The stability plot shows that this issue was hit 132 times recently.
<img width="1789" alt="image" src="https://user-images.githubusercontent.com/87007277/209289852-f8266ab4-536c-4a68-b04b-d7cc7d73a0f7.png">

**Comment by rthallamko3** [comment]
Catalog manager related leaks. cc @lingamsandeep
