### ISSUE TITLE
[DocDB][Perf][m6i.4xlarge][Sysbench][oltp_multi_insert] observed postgres and consensus cores while executing CREATE with oltp_multi_insert workload, after which cluster became non-responsive.

### ISSUE THREAD

**Issue by mangesh-at-yb** [yugabyte/yugabyte-db#14845]
Jira Link: [DB-4142](https://yugabyte.atlassian.net/browse/DB-4142)
### Description

observed postgres and consensus cores while running "sysbench workload" with "oltp_multi_insert", during CREATE phase, number of tables set to "1500". Please note that, its "m6i.4xlarge" instance and never observed OOM.

### Setup:

- Three **m6i.4xlarge** nodes, RF=3 cluster running with YB version: **2.15.1.0-b175**

- Below gFalgs set : 
```
        masterGFlags:
          - "name": "enable_automatic_tablet_splitting"
            "value": true
          - "name": "ysql_enable_packed_row"
            "value": true
          - "name": "default_memory_limit_to_ram_ratio"
            "value": 0.10
        tserverGFlags:
          - "name": "enable_automatic_tablet_splitting"
            "value": true
          - "name": "ysql_enable_packed_row"
            "value": true
          - "name": "default_memory_limit_to_ram_ratio"
            "value": 0.70
          - "name": "db_block_cache_size_percentage"
            "value": 50
```
### Steps:

- Clone sysbench repo and build sysbench on one of the client machines, recommending c5.2xlarge due to heavy workload. 
```
git clone --branch scanworkloads https://github.com/yugabyte/sysbench.git
```
- Configure node=3 and RF=3 YB-Cluster with said gFlags.

- **Execute below commands  from client machine :** 

- Cleanup: ( if cluster has used previously )

```
sysbench oltp_multi_insert --table_size=500000 --range_selects=false --pgsql-user=yugabyte --range_size=1000 --index_updates=10 --tables=1500 --warmup-time=600 --point_selects=10 --serial_cache_size=1000 --create_secondary=false --range_key_partitioning=true --non_index_updates=10 --thread-init-timeout=90 --time=1800 --pgsql-password=Password321! --db-driver=pgsql --pgsql-db=yugabyte --pgsql-port=5433 --pgsql-host=172.151.26.87,172.151.28.120,172.151.17.113 --threads=1 cleanup;
```
- CREATE phase:  After which cores can be observed.
```
sysbench oltp_multi_insert --table_size=500000 --range_selects=false --pgsql-user=yugabyte --range_size=1000 --index_updates=10 --tables=1500 --warmup-time=600 --point_selects=10 --serial_cache_size=1000 --create_secondary=false --range_key_partitioning=true --non_index_updates=10 --thread-init-timeout=90 --time=1800 --pgsql-password=Password321! --db-driver=pgsql --pgsql-db=yugabyte --pgsql-port=5433 --pgsql-host=172.151.26.87,172.151.28.120,172.151.17.113 --threads=1 create;
```

- Sysbench reports below error, during "Creating table 'sbtest897'"

```
Creating table 'sbtest897'...", "FATAL: PQexec() failed: 7 Network error: Connect timeout Connection (0x0000000001bf3e78) client 172.151.26.87:45024 => 172.151.26.87:9100, passed: 15.000s, timeout: 15.000s: kConnectFailed", "FATAL: failed query was: CREATE TABLE sbtest897(", "  id SERIAL,", "  k INTEGER DEFAULT '0' NOT NULL,", "  c CHAR(120) DEFAULT '' NOT NULL,", "  pad CHAR(60) DEFAULT '' NOT NULL,", "  PRIMARY KEY (id ASC)", ")  SPLIT AT VALUES((20833),(41666),(62500),(83333),(104166),(125000),(145833),(166666),(187500),(208333),(229166),(250000),(270833),(291666),(312500),(333333),(354166),(375000),(395833),(416666),(437500),(458333),(479166))", "FATAL: `sysbench.cmdline.call_command' function failed: ./src/lua/oltp_common.lua:255: SQL error, errno = 0, state = 'XX000': Network error: Connect timeout Connection (0x0000000001bf3e78) client 172.151.26.87:45024 => 172.151.26.87:9100, passed: 15.000s, timeout: 15.000s: kConnectFailed"]}
```

### Observed: 

- **core_postgres.19572** on node "ip-172-151-26-87":
```
gdb /home/yugabyte/yb-software/yugabyte-2.15.1.0-b175-centos-x86_64/postgres/bin/postgres ./core_postgres.19572
```
```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/home/yugabyte/yb-software/yugabyte-2.15.1.0-b175-centos-x86_64/linuxbrew/lib/libthread_db.so.1".
Core was generated by `postgres: yugabyte yugabyte 172.151.23.195(38860) CREATE TABLE                '.
Program terminated with signal 6, Aborted.
#0  0x00007f1d254680a7 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
54	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt full
#0  0x00007f1d254680a7 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
        resultvar = 0
        pid = 19572
        selftid = 19572
#1  0x00007f1d254694aa in __GI_abort () at abort.c:89
        save_stage = 2
        act = {__sigaction_handler = {sa_handler = 0x0, sa_sigaction = 0x0}, sa_mask = {__val = {0, 140726714317296, 139763089043798, 139763089043798, 30793728, 139763089005456, 0, 12784800, 30795048, 0, 0, 0, 
              139763159717728, 139763159711872, 139763080905152, 0}}, sa_flags = 5, sa_restorer = 0x0}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x0000000000b5cc3f in errfinish (dummy=<optimized out>) at ../../../../../../../src/postgres/src/backend/utils/error/elog.c:593
        elevel = 22
        oldcontext = 0x1f9a000
        econtext = 0x0
#3  0x0000000000b65d97 in elog_start (filename=0x2d5c3c "../../../../../../../src/postgres/src/backend/access/transam/xact.c", lineno=2735, funcname=<optimized out>)
    at ../../../../../../../src/postgres/src/backend/utils/error/elog.c:1424
No locals.
#4  0x00000000005ae07b in AbortTransaction () at ../../../../../../../src/postgres/src/backend/access/transam/xact.c:2734
        s = 0xbe71c8 <TopTransactionStateData>
        latestXid = <optimized out>
#5  0x00000000005b16f8 in AbortCurrentTransaction () at ../../../../../../../src/postgres/src/backend/access/transam/xact.c:3428
        s = 0xbe71c8 <TopTransactionStateData>
#6  0x00000000009a3de8 in PostgresMain (argc=1, argv=0x1c713b8, dbname=<optimized out>, username=0x1c71378 "yugabyte") at ../../../../../../src/postgres/src/backend/tcop/postgres.c:5015
        input_message = {
          data = 0x1d74118 "CREATE TABLE sbtest897(\n  id SERIAL,\n  k INTEGER DEFAULT '0' NOT NULL,\n  c CHAR(120) DEFAULT '' NOT NULL,\n  pad CHAR(60) DEFAULT '' NOT NULL,\n  PRIMARY KEY (id ASC)\n)  SPLIT AT VALUES((20833),(41666),"..., len = 388, maxlen = 1024, cursor = 388}
        local_sigjmp_buf = {{__jmpbuf = {0, 1011230966609517296, 1, 29823928, 140726714317536, 8388608, 1011230963665115888, -1012633020023661840}, __mask_was_saved = 1, __saved_mask = {__val = {0, 6405831344, 
                17179869185, 29823928, 29823896, 1, 29823928, 1, 17246978049, 139763166112672, 3020807, 0, 0, 0, 0, 0}}}}
        send_ready_for_query = false
        disable_idle_in_transaction_timeout = false
        firstchar = <optimized out>
#7  0x00000000008ee1ab in BackendRun (port=0x1be61e0) at ../../../../../../src/postgres/src/backend/postmaster/postmaster.c:4560
        maxac = <optimized out>
        ac = <optimized out>
        av = 0x1c713b8
        i = <optimized out>
#8  0x00000000008ed642 in ServerLoop () at ../../../../../../src/postgres/src/backend/postmaster/postmaster.c:4198
        readmask = {fds_bits = {40, 0 <repeats 15 times>}}
        last_lockfile_recheck_time = 1667537182
        last_touch_time = 1667536935
        nSockets = 6
#9  0x00000000008e975a in PostmasterMain (argc=23, argv=<optimized out>) at ../../../../../../src/postgres/src/backend/postmaster/postmaster.c:1423
        output_config_variable = 0x1d74720 <incomplete sequence \336>
        listen_addr_saved = <optimized out>
        userDoption = 0x1d74468 "/tmp/.yb.9905242947111968367"
        opt = <optimized out>
        i = <optimized out>
        status = <optimized out>
#10 0x00000000007f9a51 in PostgresServerProcessMain (argc=23, argv=0x1bfc780) at ../../../../../../src/postgres/src/backend/main/main.c:234
        do_check_root = <optimized out>
#11 0x0000000000503842 in main ()
No symbol table info available.
```

- **tserver.err:** on node "ip-172-151-26-87": 
```
src/central_freelist.cc:330] tcmalloc: allocation failed 8192
src/central_freelist.cc:330] tcmalloc: allocation failed 8192
libc++abi: terminating with uncaught exception of type std::bad_alloc: std::bad_alloc
    @     0x7fd718e464aa __GI_abort
    @          0x42e61c1 abort_message
    @          0x42e5e2a demangling_terminate_handler()
    @          0x42e59d6 std::__terminate()
    @          0x42e788b __cxxabiv1::failed_throw()
    @          0x42e781e __cxa_throw
    @          0x42a359e std::__1::__throw_system_error()
    @          0x366b3e3 yb::tablet::TransactionParticipant::SetDB()
    @          0x35c8b9d yb::tablet::Tablet::OpenKeyValueTablet()
    @          0x35f3989 yb::tablet::TabletBootstrap::Bootstrap()
    @          0x37daece yb::tserver::TSTabletManager::OpenTablet()
src/central_freelist.cc:330] tcmalloc: allocation failed 8192
src/central_freelist.cc:330] tcmalloc: allocation failed 8192
libc++abi: terminating with uncaught exception of type std::bad_alloc: std::bad_alloc
    @          0x3af8731 yb::ThreadPool::DispatchThread()
    @          0x3af3ec1 yb::Thread::SuperviseThread()
src/central_freelist.cc:330] tcmalloc: allocation failed 16384
src/central_freelist.cc:330] tcmalloc: allocation failed 8192
libc++abi: terminating with uncaught exception of type std::bad_alloc: std::bad_alloc
    @     0x7fd7189f6694 start_thread
    @     0x7fd718ef841d __clone
2022-11-04 05:57:19.372 UTC [21933] LOG:  YugaByte is ENABLED in PostgreSQL. Transactions are enabled.
2022-11-04 05:57:19.378 UTC [21933] LOG:  pgaudit extension initialized
2022-11-04 05:57:19.378 UTC [21933] LOG:  listening on IPv4 address "172.151.26.87", port 5433
2022-11-04 05:57:19.381 UTC [21933] LOG:  listening on Unix socket "/tmp/.yb.9905242947111968367/.s.PGSQL.5433"
2022-11-04 05:57:19.397 UTC [21933] LOG:  redirecting log output to logging collector process
2022-11-04 05:57:19.397 UTC [21933] HINT:  Future log output will appear in directory "/mnt/d0/yb-data/tserver/logs".
libc++abi: terminating with uncaught exception of type std::__1::system_error: thread constructor failed: Resource temporarily unavailable
*** Aborted at 1667541507 (unix time) try "date -d @1667541507" if you are using GNU date ***
libc++abi: terminating with uncaught exception of type std::__1::system_error: thread constructor failed: Resource temporarily unavailable
libc++abi: terminating with uncaught exception of type std::__1::system_error: thread constructor failed: Resource temporarily unavailable
libc++abi: terminating with uncaught exception of type std::__1::system_error: thread constructor failed: Resource temporarily unavailable
libc++abi: terminating with uncaught exception of type std::__1::system_error: thread constructor failed: Resource temporarily unavailable
libc++abi: terminating with uncaught exception of type std::__1::system_error: thread constructor failed: Resource temporarily unavailable
libc++abi: terminating with uncaught exception of type std::__1::system_error: thread constructor failed: Resource temporarily unavailable
libc++abi: terminating with uncaught exception of type std::__1::system_error: thread constructor failed: Resource temporarily unavailable
PC: @                0x0 (unknown)
*** SIGABRT (@0x3e5000054ce) received by PID 21710 (TID 0x7f0caf9fd700) from PID 21710; stack trace: ***
    @     0x7f0cbe08a0a7 __GI_raise
    @     0x7f0cbe08b4aa __GI_abort
    @          0x42e61c1 abort_message
    @          0x42e5e2a demangling_terminate_handler()
    @          0x42e59d6 std::__terminate()
    @          0x42e788b __cxxabiv1::failed_throw()
    @          0x42e781e __cxa_throw
    @          0x42a359e std::__1::__throw_system_error()
    @          0x366b3e3 yb::tablet::TransactionParticipant::SetDB()
    @          0x35c8b9d yb::tablet::Tablet::OpenKeyValueTablet()
    @          0x35f3989 yb::tablet::TabletBootstrap::Bootstrap()
    @          0x37daece yb::tserver::TSTabletManager::OpenTablet()
    @          0x3af8731 yb::ThreadPool::DispatchThread()
    @          0x3af3ec1 yb::Thread::SuperviseThread()
    @     0x7f0cbdc3b694 start_thread
    @     0x7f0cbe13d41d __clone
```

- **core_consensus\ \[work.6055  :** on node "ip-172-151-28-120".
```
 gdb -q -nh -iex "set auto-load safe-path /" /home/yugabyte/tserver/bin/yb-tserver core_consensus\ \[work.6055 
```
```
 [Thread debugging using libthread_db enabled]
Using host libthread_db library "/home/yugabyte/yb-software/yugabyte-2.15.1.0-b175-centos-x86_64/linuxbrew/lib/libthread_db.so.1".
Core was generated by `/home/yugabyte/tserver/bin/yb-tserver --flagfile /home/yugabyte/tserver/conf/se'.
Program terminated with signal 6, Aborted.
#0  0x00007f60b60b70a7 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
54     ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007f60b60b70a7 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007f60b60b84aa in __GI_abort () at abort.c:89
#2  0x00000000042e61c1 in abort_message ()
#3  0x00000000042e5e2a in demangling_terminate_handler() ()
#4  0x00000000042e59d6 in std::__terminate(void (*)()) ()
#5  0x00000000042e788b in __cxxabiv1::failed_throw(__cxxabiv1::__cxa_exception*) ()
#6  0x00000000042e781e in __cxa_throw ()
#7  0x0000000002a395cf in (anonymous namespace)::handle_oom(void* (*)(void*), void*, bool, bool) ()
#8  0x0000000002ea2b26 in mutable_candidate_status (this=0x7ed337bccff0) at src/yb/consensus/consensus.pb.h:7002
#9  CreateElectionUnlocked (this=0x123c16c98, data=..., timeout=..., preelection=...) at ../../src/yb/consensus/raft_consensus.cc:686
#10 yb::consensus::RaftConsensus::DoStartElection(yb::consensus::LeaderElectionData const&, yb::StronglyTypedBool<yb::consensus::PreElected_Tag>) (this=0x123c16c98,
    data=..., preelected=...) at ../../src/yb/consensus/raft_consensus.cc:627
#11 0x0000000002e7d3d5 in yb::consensus::RaftConsensus::StartElection(yb::consensus::LeaderElectionData const&) (this=0x734a, data=...)
    at ../../src/yb/consensus/raft_consensus.h:249
#12 0x0000000002eaa7e4 in yb::consensus::RaftConsensus::ReportFailureDetectedTask() (this=0x123c16c98) at ../../src/yb/consensus/raft_consensus.cc:1017
#13 0x0000000003af8731 in yb::ThreadPool::DispatchThread(bool) (this=<optimized out>, permanent=false) at ../../src/yb/util/threadpool.cc:611
#14 0x0000000003af3ec1 in yb::Thread::SuperviseThread(void*) (arg=<optimized out>)
    at /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20220630123344-af96d73e39-almalinux8-x86_64-clang13-linuxbrew-full-lto/installed/uninstrumented/libcxx/include/c++/v
1/__functional/function.h:498
#15 0x00007f60b5c68694 in start_thread (arg=0x7ed337bd5700) at pthread_create.c:333
#16 0x00007f60b616a41d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
(gdb) bt full
#0  0x00007f60b60b70a7 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
        resultvar = 0
        pid = 6055
        selftid = 29514
#1  0x00007f60b60b84aa in __GI_abort () at abort.c:89
        save_stage = 2
        act = {__sigaction_handler = {sa_handler = 0x7f60b641b080 <_IO_2_1_stderr_>, sa_sigaction = 0x7f60b641b080 <_IO_2_1_stderr_>}, sa_mask = {__val = {
              140053348472489, 0, 140053348037840, 10, 140053348472477, 10, 140053351352160, 0, 10, 139445638354688, 10, 544568096, 140053348041541, 140053351346304,
              140053348042427, 140053351346304}}, sa_flags = 935119024, sa_restorer = 0x7f60b641b6d8 <stderr>}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x00000000042e61c1 in abort_message ()
No symbol table info available.
#3  0x00000000042e5e2a in demangling_terminate_handler() ()
No symbol table info available.
#4  0x00000000042e59d6 in std::__terminate(void (*)()) ()
No symbol table info available.
#5  0x00000000042e788b in __cxxabiv1::failed_throw(__cxxabiv1::__cxa_exception*) ()
No symbol table info available.
#6  0x00000000042e781e in __cxa_throw ()
No symbol table info available.
#7  0x0000000002a395cf in (anonymous namespace)::handle_oom(void* (*)(void*), void*, bool, bool) ()
        yb::bfql::kBfqlName2Opcode = {__table_ = {__bucket_list_ = {__ptr_ = {<> = {__value_ = 0x58e8000}, <> = {__value_ = {__data_ = {<> = {
                        __value_ = 97}, <> = {<allocator<std::__1::__hash_node_base<std::__1::__hash_node<std::__1::__hash_value_type<std::__1::string, yb::bfql::BFOpcode>, void *> *> *>> = {<> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}}}, <No data fields>}}, __p1_ = {<> = {__value_ = {
                  __next_ = 0x58db620}}, <> = {<allocator<std::__1::__hash_node<std::__1::__hash_value_type<std::__1::string, yb::bfql::BFOpcode>, void *> >> = {<> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, __p2_ = {<> = {
                __value_ = 91}, <> = {<__unordered_map_hasher<std::__1::string, std::__1::__hash_value_type<std::__1::string, yb::bfql::BFOpcode>, std::__1::hash<std::__1::string>, std::__1::equal_to<std::__1::string>, true>> = {<> = {<> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, <No data fields>},
            __p3_ = {<> = {
                __value_ = 1}, <> = {<__unordered_map_equal<std::__1::string, std::__1::__hash_value_type<std::__1::string, yb::bfql::BFOpcode>, std::__1::equal_to<std::__1::string>, std::__1::hash<std::__1::string>, true>> = {<> = {<> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}}}
#8  0x0000000002ea2b26 in mutable_candidate_status (this=0x7ed337bccff0) at src/yb/consensus/consensus.pb.h:7002
No locals.
#9  CreateElectionUnlocked (this=0x123c16c98, data=..., timeout=..., preelection=...) at ../../src/yb/consensus/raft_consensus.cc:686
        counter = {__ptr_ = {<> = {__value_ = 0x15ef08040}, <> = {<> = {<No data fields>}, <No data fields>}, <No data fields>}}
        request = warning: RTTI symbol not found for class 'yb::consensus::VoteRequestPB'
{<Message> = {<No data fields>}, static kIndexInFileMessages = 0, static kTabletIdFieldNumber = 2, static kCandidateUuidFieldNumber = 2,
          static kDestUuidFieldNumber = 1, static kCandidateStatusFieldNumber = 4, static kCandidateTermFieldNumber = 3, static kIgnoreLiveLeaderFieldNumber = 5,
          static kPreelectionFieldNumber = 7,
          _internal_metadata_ = {<InternalMetadataWithArenaBase<google::protobuf::UnknownFieldSet, google::protobuf::internal::InternalMetadataWithArena>> = {ptr_ = 0x0,
              static kPtrTagMask = 1, static kPtrValueMask = -2}, <No data fields>}, _has_bits_ = {has_bits_ = {123}}, _cached_size_ = 0, tablet_id_ = {
            ptr_ = 0x15c01a940}, candidate_uuid_ = {ptr_ = 0x15c01a9a0}, dest_uuid_ = {ptr_ = 0x4600b18 <google::protobuf::internal::fixed_address_empty_string>},
          candidate_status_ = 0x0, candidate_term_ = 23, ignore_live_leader_ = false, preelection_ = true}
        new_term = 23
        active_config = @0xdb0fe40: warning: RTTI symbol not found for class 'yb::consensus::RaftConfigPB'
{<Message> = {<No data fields>}, static kIndexInFileMessages = 0, static kPeersFieldNumber = 2, static kOpidIndexFieldNumber = 1,
          static kUnsafeConfigChangeFieldNumber = 4,
---Type <return> to continue, or q <return> to quit---
          _internal_metadata_ = {<InternalMetadataWithArenaBase<google::protobuf::UnknownFieldSet, google::protobuf::internal::InternalMetadataWithArena>> = {ptr_ = 0x0,
              static kPtrTagMask = 1, static kPtrValueMask = -2}, <No data fields>}, _has_bits_ = {has_bits_ = {1}}, _cached_size_ = 277,
          peers_ = {<RepeatedPtrFieldBase> = {static kInitialSize = 0, arena_ = 0x0, current_size_ = 3, total_size_ = 4, static kRepHeaderSize = 8,
              rep_ = 0x1280cef30}, <No data fields>}, opid_index_ = -1, unsafe_config_change_ = false}
        num_voters = <optimized out>
        majority_size = <optimized out>
        result = <optimized out>
#10 yb::consensus::RaftConsensus::DoStartElection(yb::consensus::LeaderElectionData const&, yb::StronglyTypedBool<yb::consensus::PreElected_Tag>) (this=0x123c16c98,
    data=..., preelected=...) at ../../src/yb/consensus/raft_consensus.cc:627
        __result = <optimized out>
        __static_assert = <optimized out>
        timeout = {static kMin = {static kMin = <same as static member of an already seen type>, static kMax = <same as static member of an already seen type>,
            static kZero = <optimized out>, static kUninitialized = 15, nano_delta_ = -9223372036854775808},
          static kMax = <same as static member of an already seen type>, static kZero = <optimized out>, static kUninitialized = 15, nano_delta_ = 3009000000}
        lock = {__m_ = 0x127a42730, __owns_ = true}
        active_role = <optimized out>
        start_now = <optimized out>
        trace_event_unique_atomic549 = 73351548
        vlocal__ = 0x4600a68 <fLI::FLAGS_v>
        vlocal__ = 0x42fa1f0 <google::kLogSiteUninitialized>
        trace_event_unique_tracer549 = {p_data_ = 0x0, data_ = {category_group_enabled = 0x0, name = 0x0, event_handle = {chunk_seq = 0, chunk_index = 0,
              event_index = 0}}}
        trace_event_unique_category_group_enabled549 = <optimized out>
        preelection = <optimized out>
        election_name = <optimized out>
        election = {ptr_ = 0x0}
#11 0x0000000002e7d3d5 in yb::consensus::RaftConsensus::StartElection(yb::consensus::LeaderElectionData const&) (this=0x734a, data=...)
    at ../../src/yb/consensus/raft_consensus.h:249
No locals.
#12 0x0000000002eaa7e4 in yb::consensus::RaftConsensus::ReportFailureDetectedTask() (this=0x123c16c98) at ../../src/yb/consensus/raft_consensus.cc:1017
        vlocal__ = 0x4600a68 <fLI::FLAGS_v>
        s = {state_ = {px = 0x7f60b5c6b911 <__pthread_mutex_unlock_usercnt+65>}}
        now = <optimized out>
        scope_exit = <error reading variable scope_exit (access outside bounds of object referenced via synthetic pointer)>
#13 0x0000000003af8731 in yb::ThreadPool::DispatchThread(bool) (this=<optimized out>, permanent=false) at ../../src/yb/util/threadpool.cc:611
        vlocal__ = 0x42fa1f0 <google::kLogSiteUninitialized>
        vlocal__ = 0x4600a68 <fLI::FLAGS_v>
        _result = {str_ = 0x2efb}
        unique_lock = <error reading variable unique_lock (access outside bounds of object referenced via synthetic pointer)>
#14 0x0000000003af3ec1 in yb::Thread::SuperviseThread(void*) (arg=<optimized out>)
    at /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20220630123344-af96d73e39-almalinux8-x86_64-clang13-linuxbrew-full-lto/installed/uninstrumented/libcxx/include/c++/v1/__functional/function.h:498
        occurrences_740 = 0
        occurrences_mod_n_740 = 0
        name = {<__basic_string_common<true>> = {<No data fields>}, static __short_mask = 1, static __long_mask = 1, __r_ = {<> = {__value_ = {{__l = {__cap_ = 49,
---Type <return> to continue, or q <return> to quit---
                    __size_ = 24, __data_ = 0x15bed19b0 "consensus [worker]-29514"}, __s = {{__size_ = 49 '1', __lx = 49 '1'},
                    __data_ = "\000\000\000\000\000\000\000\030\000\000\000\000\000\000\000\260\031\355[\001\000\000"}, __r = {__words = {49, 24,
                      5837232560}}}}}, <> = {<allocator<char>> = {<> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>},
          static npos = 18446744073709551615}
        thread_mgr_ref = {__ptr_ = 0x58f6118, __cntrl_ = 0x58f6100}
        system_tid = <optimized out>
        thread_ref = {ptr_ = 0x15bef19e0}
        loop_count = <optimized out>
#15 0x00007f60b5c68694 in start_thread (arg=0x7ed337bd5700) at pthread_create.c:333
        __res = <optimized out>
        pd = 0x7ed337bd5700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {139445638354688, -8110914923499703980, 0, 140053299038623, 5338732064, 139445638354688, 8274892212859482452,
                8192424118924652884}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#16 0x00007f60b616a41d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
No locals.
```

- **tserver.err :** on node "ip-172-151-28-120".
```
src/central_freelist.cc:330] tcmalloc: allocation failed 8192
src/central_freelist.cc:330] tcmalloc: allocation failed 8192
libc++abi: terminating with uncaught exception of type std::bad_alloc: std::bad_alloc
    @     0x7fd718e464aa __GI_abort
    @          0x42e61c1 abort_message
    @          0x42e5e2a demangling_terminate_handler()
    @          0x42e59d6 std::__terminate()
    @          0x42e788b __cxxabiv1::failed_throw()
    @          0x42e781e __cxa_throw
    @          0x42a359e std::__1::__throw_system_error()
    @          0x366b3e3 yb::tablet::TransactionParticipant::SetDB()
    @          0x35c8b9d yb::tablet::Tablet::OpenKeyValueTablet()
    @          0x35f3989 yb::tablet::TabletBootstrap::Bootstrap()
    @          0x37daece yb::tserver::TSTabletManager::OpenTablet()
src/central_freelist.cc:330] tcmalloc: allocation failed 8192
src/central_freelist.cc:330] tcmalloc: allocation failed 8192
libc++abi: terminating with uncaught exception of type std::bad_alloc: std::bad_alloc
    @          0x3af8731 yb::ThreadPool::DispatchThread()
    @          0x3af3ec1 yb::Thread::SuperviseThread()
src/central_freelist.cc:330] tcmalloc: allocation failed 16384
src/central_freelist.cc:330] tcmalloc: allocation failed 8192
libc++abi: terminating with uncaught exception of type std::bad_alloc: std::bad_alloc
    @     0x7fd7189f6694 start_thread
    @     0x7fd718ef841d __clone
2022-11-04 05:57:19.372 UTC [21933] LOG:  YugaByte is ENABLED in PostgreSQL. Transactions are enabled.
2022-11-04 05:57:19.378 UTC [21933] LOG:  pgaudit extension initialized
2022-11-04 05:57:19.378 UTC [21933] LOG:  listening on IPv4 address "172.151.26.87", port 5433
2022-11-04 05:57:19.381 UTC [21933] LOG:  listening on Unix socket "/tmp/.yb.9905242947111968367/.s.PGSQL.5433"
2022-11-04 05:57:19.397 UTC [21933] LOG:  redirecting log output to logging collector process
2022-11-04 05:57:19.397 UTC [21933] HINT:  Future log output will appear in directory "/mnt/d0/yb-data/tserver/logs".
libc++abi: terminating with uncaught exception of type std::__1::system_error: thread constructor failed: Resource temporarily unavailable
*** Aborted at 1667541507 (unix time) try "date -d @1667541507" if you are using GNU date ***
libc++abi: terminating with uncaught exception of type std::__1::system_error: thread constructor failed: Resource temporarily unavailable
libc++abi: terminating with uncaught exception of type std::__1::system_error: thread constructor failed: Resource temporarily unavailable
libc++abi: terminating with uncaught exception of type std::__1::system_error: thread constructor failed: Resource temporarily unavailable
libc++abi: terminating with uncaught exception of type std::__1::system_error: thread constructor failed: Resource temporarily unavailable
libc++abi: terminating with uncaught exception of type std::__1::system_error: thread constructor failed: Resource temporarily unavailable
libc++abi: terminating with uncaught exception of type std::__1::system_error: thread constructor failed: Resource temporarily unavailable
libc++abi: terminating with uncaught exception of type std::__1::system_error: thread constructor failed: Resource temporarily unavailable
PC: @                0x0 (unknown)
*** SIGABRT (@0x3e5000054ce) received by PID 21710 (TID 0x7f0caf9fd700) from PID 21710; stack trace: ***
    @     0x7f0cbe08a0a7 __GI_raise
    @     0x7f0cbe08b4aa __GI_abort
    @          0x42e61c1 abort_message
    @          0x42e5e2a demangling_terminate_handler()
    @          0x42e59d6 std::__terminate()
    @          0x42e788b __cxxabiv1::failed_throw()
    @          0x42e781e __cxa_throw
    @          0x42a359e std::__1::__throw_system_error()
    @          0x366b3e3 yb::tablet::TransactionParticipant::SetDB()
    @          0x35c8b9d yb::tablet::Tablet::OpenKeyValueTablet()
    @          0x35f3989 yb::tablet::TabletBootstrap::Bootstrap()
    @          0x37daece yb::tserver::TSTabletManager::OpenTablet()
    @          0x3af8731 yb::ThreadPool::DispatchThread()
    @          0x3af3ec1 yb::Thread::SuperviseThread()
    @     0x7f0cbdc3b694 start_thread
    @     0x7f0cbe13d41d __clone

```
- After these cores, cluster never came back and "tserver" keeps crashing in "bootstrap".

### Expected 

- Need to analyse why system went in to such state, **Please not that, we never hit OOM on both the machines and these are "m6i.4xlarge" instance. Creating "1500" tables

**Comment by rthallamko3** [comment]
@hbhanawat , Do you know if this instability could be due to us hitting the system limits? Does this repro?

**Comment by hbhanawat** [comment]
I would close this issue for now. Have not seen this issue recently. Will reopen in case we see this.
