### ISSUE TITLE
[YSQL] Fix I/O error segfault in backfill test

### ISSUE THREAD

**Issue by jasonyb** [yugabyte/yugabyte-db#14860]
### Description

Java test 'org.yb.pgsql.TestIndexBackfill#insertsWhileCreatingIndex' can sometimes fail with segfault and error message

```
Insert thread failed: An I/O error occurred while sending to the backend.
```

On 1500 runs on alma8 fastdebug gcc11 commit f84485c21bc6487ad3a35f02e4aff263782f7345 (2.16), it failed with this message twice.  Relevant parts of the logs:

```
java.util.concurrent.ExecutionException: java.lang.AssertionError: Insert thread failed: An I/O error occurred while sending to the backend.
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:206)
        at org.yb.pgsql.TestIndexBackfill.insertsWhileCreatingIndex(TestIndexBackfill.java:128)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
        at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
        at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.AssertionError: Insert thread failed: An I/O error occurred while sending to the backend.
        at org.junit.Assert.fail(Assert.java:88)
        at org.yb.AssertionWrappers.lambda$fail$4(AssertionWrappers.java:104)
        at org.yb.AssertionWrappers.wrapAssertion(AssertionWrappers.java:45)
        at org.yb.AssertionWrappers.fail(AssertionWrappers.java:104)
        at org.yb.pgsql.TestIndexBackfill.lambda$insertsWhileCreatingIndex$1(TestIndexBackfill.java:117)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        ... 1 common frames omitted
```

```
05:39:15.444 (main) [WARN - org.yb.util.CoreFileUtil.processCoreFile(CoreFileUtil.java:117)] Analyzing core file using the command: [${YB_SRC_ROOT}/build-support/analyze_core_file.sh, --core, ${TEST_TMPDIR}/ts-127.222.102.14-26885-1667565538410/pg_data/core.3768825, --exec
utable, ${BUILD_ROOT}/postgres/bin/postgres]
    |stdout Found a core file at '${TEST_TMPDIR}/ts-127.222.102.14-26885-1667565538410/pg_data/core.3768825', backtrace:
    |stdout + echo ''
    |stdout + ${YB_SRC_ROOT}/build-support/dedup_thread_stacks.py
    |stdout + grep -Ev '^\[New LWP [0-9]+\]$'
    |stdout + gdb -q -n -ex bt -ex 'thread apply all bt' -batch ${BUILD_ROOT}/postgres/bin/postgres ${TEST_TMPDIR}/ts-127.222.102.14-26885-1667565538410/pg_data/core.3768825
    |stdout + tee -a /dev/null
    |stdout 
    |stdout warning: Can't open file (null) during file-backed mapping note processing
    |stdout 
    |stdout warning: Can't open file (null) during file-backed mapping note processing
    |stdout 
    |stdout warning: Can't open file (null) during file-backed mapping note processing
    |stdout 
    |stdout warning: Can't open file (null) during file-backed mapping note processing
    |stdout BFD: warning: /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20221019013155-1aec6dda08-almalinux8-x86_64-gcc11/installed/uninstrumented/lib/libicudata.so.70: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0010001
    |stdout BFD: warning: /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20221019013155-1aec6dda08-almalinux8-x86_64-gcc11/installed/uninstrumented/lib/libicudata.so.70: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0010002
    |stdout BFD: warning: /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20221019013155-1aec6dda08-almalinux8-x86_64-gcc11/installed/common/lib/libunwind.so.8: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0010001
    |stdout BFD: warning: /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20221019013155-1aec6dda08-almalinux8-x86_64-gcc11/installed/common/lib/libunwind.so.8: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0010002
    |stdout [Thread debugging using libthread_db enabled]
    |stdout Using host libthread_db library "/lib64/libthread_db.so.1".
    |stdout Core was generated by `postgres: yugabyte_test yugabyte 127.0.0.1(51880) idle                        '.
    |stdout Program terminated with signal SIGSEGV, Segmentation fault.
    |stdout #0  0x00007fc8be0d944e in __longjmp () from /lib64/libc.so.6
    |stdout [Current thread is 1 (Thread 0x7fc8bbdd62c0 (LWP 3768825))]
    |stdout #0  0x00007fc8be0d944e in __longjmp () from /lib64/libc.so.6
    |stdout #1  0x6967043a4212c799 in ?? ()
    |stdout Backtrace stopped: Cannot access memory at address 0xf9c3043a7deddfa5
    |stdout 
    |stdout Thread 9 (Thread 0x7fc8a433d700 (LWP 3768830)):
    |stdout #0  0x00007fc8be48944c in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
    |stdout #1  0x00007fc8bf0056f6 in boost::asio::detail::posix_event::wait<boost::asio::detail::conditionally_enabled_mutex::scoped_lock> (lock=..., this=0x2752770) at /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20221019013155-1aec6dda08-almalinux8-x86_64-gcc11/inst
alled/uninstrumented/include/boost/asio/detail/conditionally_enabled_mutex.hpp:98
    |stdout #2  boost::asio::detail::conditionally_enabled_event::wait (lock=..., this=0x2752768) at /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20221019013155-1aec6dda08-almalinux8-x86_64-gcc11/installed/uninstrumented/include/boost/asio/detail/conditionally_enabled_
event.hpp:97
    |stdout #3  boost::asio::detail::scheduler::do_run_one (this=this@entry=0x2752700, lock=..., this_thread=..., ec=...) at /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20221019013155-1aec6dda08-almalinux8-x86_64-gcc11/installed/uninstrumented/include/boost/asio/detai
l/impl/scheduler.ipp:501
    |stdout #4  0x00007fc8bf006668 in boost::asio::detail::scheduler::run (this=0x2752700, ec=...) at /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20221019013155-1aec6dda08-almalinux8-x86_64-gcc11/installed/uninstrumented/include/boost/asio/detail/impl/scheduler.ipp:21
0
    |stdout #5  0x00007fc8bbedf02d in boost::asio::io_context::run (ec=..., this=<optimized out>) at /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20221019013155-1aec6dda08-almalinux8-x86_64-gcc11/installed/uninstrumented/include/boost/asio/impl/io_context.ipp:71
    |stdout #6  yb::rpc::IoThreadPool::Impl::Execute (this=<optimized out>) at ../../src/yb/rpc/io_thread_pool.cc:76
    |stdout #7  0x00007fc8bbedbec9 in std::__invoke_impl<void, void (yb::rpc::IoThreadPool::Impl::*&)(), yb::rpc::IoThreadPool::Impl*&> (__t=<optimized out>, __f=<optimized out>) at /opt/rh/gcc-toolset-11/root/usr/include/c++/11/bits/invoke.h:90
    |stdout #8  std::__invoke<void (yb::rpc::IoThreadPool::Impl::*&)(), yb::rpc::IoThreadPool::Impl*&> (__fn=<optimized out>) at /opt/rh/gcc-toolset-11/root/usr/include/c++/11/bits/invoke.h:96
    |stdout #9  std::_Bind<void (yb::rpc::IoThreadPool::Impl::*(yb::rpc::IoThreadPool::Impl*))()>::__call<void, , 0ul>(std::tuple<>&&, std::_Index_tuple<0ul>) (__args=..., this=<optimized out>) at /opt/rh/gcc-toolset-11/root/usr/include/c++/11/functional:420
    |stdout #10 std::_Bind<void (yb::rpc::IoThreadPool::Impl::*(yb::rpc::IoThreadPool::Impl*))()>::operator()<, void>() (this=<optimized out>) at /opt/rh/gcc-toolset-11/root/usr/include/c++/11/functional:503
    |stdout #11 std::__invoke_impl<void, std::_Bind<void (yb::rpc::IoThreadPool::Impl::*(yb::rpc::IoThreadPool::Impl*))()>&>(std::__invoke_other, std::_Bind<void (yb::rpc::IoThreadPool::Impl::*(yb::rpc::IoThreadPool::Impl*))()>&) (__f=...) at /opt/rh/gcc-toolset-11/root/usr/include/c++/11/bits/invoke.h:61
    |stdout #12 std::__invoke<std::_Bind<void (yb::rpc::IoThreadPool::Impl::*(yb::rpc::IoThreadPool::Impl*))()>&>(std::_Bind<void (yb::rpc::IoThreadPool::Impl::*(yb::rpc::IoThreadPool::Impl*))()>&) (__fn=...) at /opt/rh/gcc-toolset-11/root/usr/include/c++/11/bits/invoke.h:96
    |stdout #13 std::_Bind<std::_Bind<void (yb::rpc::IoThreadPool::Impl::*(yb::rpc::IoThreadPool::Impl*))()> ()>::__call<void>(std::tuple<>&&, std::_Index_tuple<>) (__args=..., this=<optimized out>) at /opt/rh/gcc-toolset-11/root/usr/include/c++/11/functional:420
    |stdout #14 std::_Bind<std::_Bind<void (yb::rpc::IoThreadPool::Impl::*(yb::rpc::IoThreadPool::Impl*))()> ()>::operator()<, void>() (this=<optimized out>) at /opt/rh/gcc-toolset-11/root/usr/include/c++/11/functional:503
    |stdout #15 std::__invoke_impl<void, std::_Bind<std::_Bind<void (yb::rpc::IoThreadPool::Impl::*(yb::rpc::IoThreadPool::Impl*))()> ()>&>(std::__invoke_other, std::_Bind<std::_Bind<void (yb::rpc::IoThreadPool::Impl::*(yb::rpc::IoThreadPool::Impl*))()> ()>&) (__f=...) at /opt/rh/gcc-toolset-11/root/usr/include/c++/11/bits/invoke.h:61
    |stdout #16 std::__invoke_r<void, std::_Bind<std::_Bind<void (yb::rpc::IoThreadPool::Impl::*(yb::rpc::IoThreadPool::Impl*))()> ()>&>(std::_Bind<std::_Bind<void (yb::rpc::IoThreadPool::Impl::*(yb::rpc::IoThreadPool::Impl*))()> ()>&) (__fn=...) at /opt/rh/gcc-toolset-11/root/usr/include/c++/11/bits/invoke.h:111
    |stdout #17 std::_Function_handler<void (), std::_Bind<std::_Bind<void (yb::rpc::IoThreadPool::Impl::*(yb::rpc::IoThreadPool::Impl*))()> ()> >::_M_invoke(std::_Any_data const&) (__functor=...) at /opt/rh/gcc-toolset-11/root/usr/include/c++/11/bits/std_function.h:290
    |stdout #18 0x00007fc8bf07b27a in std::function<void ()>::operator()() const (this=0x299e420) at /opt/rh/gcc-toolset-11/root/usr/include/c++/11/bits/std_function.h:586
    |stdout #19 yb::Thread::SuperviseThread (arg=0x299e3c0) at ../../src/yb/util/thread.cc:800
    |stdout #20 0x00007fc8be4831cf in start_thread () from /lib64/libpthread.so.0
    |stdout #21 0x00007fc8be0efdd3 in clone () from /lib64/libc.so.6
```

Full logs will be linked shortly.

**Comment by jasonyb** [comment]
logs:
- https://gist.github.com/jasonyb/2dc35dd68d1f9a004a1b2eeee0a8c09a/raw/b02fab491243849643a9aad048b8f08900938605/gistfile1.txt
- https://gist.github.com/jasonyb/2dc35dd68d1f9a004a1b2eeee0a8c09a/raw/b02fab491243849643a9aad048b8f08900938605/gistfile2.txt

**Comment by mbautin** [comment]
@jasonyb it looks like the only threads that are still running at the end are IoThreadPool threads. Perhaps we are not correctly shutting down the thread pool when handling SIGTERM, and one of the threads is accessing deallocated memory. But do you know if the test is failing due to the server crash, or is the server crash happening during incorrect shutdown after the test fails for a different reason? (Perhaps a timeout or some other kind of instability?)

**Comment by jasonyb** [comment]
@mbautin I don't know and don't plan on looking in near term.  cc: @frozenspider
