### ISSUE TITLE
[YugabyteD] [QA] Mac Shell stops working if connect command is interrupted with Cntrl+C

### ISSUE THREAD

**Issue by zlareb1-yb** [yugabyte/yugabyte-db#14867]
### Description

Control + C on Mac (if connect command is executing) corrupts the shell and it stops working. From thereon no text is shown on the terminal
```
MacBook-Pro-16-inch-2021:yugabyte-2.17.1.0 mzafar$ ./bin/yugabyted connect ysql --base_dir=~/kk
yugabyted is not running. Cannot connect to YSQL.
For more information, check the logs in /Users/mzafar/ybd/testing/yugabyte-2.17.1.0/~/kk/logs
MacBook-Pro-16-inch-2021:yugabyte-2.17.1.0 mzafar$ ./bin/yugabyted connect ysql --base_dir=/Users/mzafar/kk/
Password for user yugabyte: Traceback (most recent call last):
  File "./bin/yugabyted", line 4400, in <module>
    ControlScript().run()
  File "./bin/yugabyted", line 2888, in run
    args.func()
  File "./bin/yugabyted", line 470, in connect_ysql
    ysql_proxy.connect()
  File "./bin/yugabyted", line 3523, in connect
    shell.communicate()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 480, in communicate
    self.wait()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1099, in wait
    pid, sts = _eintr_retry_call(os.waitpid, self.pid, 0)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 125, in _eintr_retry_call
    return func(*args)
KeyboardInterrupt
-bash: dsfewrewrewrf: command not found1.0 mzafar$ 
-bash: dewr: command not foundyte-2.17.1.0 mzafar$ 
```

Not sure what might be the reason for it. But I am able to consistently reproduce this issue.

**Comment by nchandrappa** [comment]
Not able to replicate. On ctrl + c on my mac, it does nothing.

**Comment by zlareb1-yb** [comment]
Will try to find "Steps to Reproduce"
