### ISSUE TITLE
[DocDB] YB-Master can hit a deadlock when DDL is performed immediately after restart

### ISSUE THREAD

**Issue by deeps1991** [yugabyte/yugabyte-db#14995]
Jira Link: [DB-4242](https://yugabyte.atlassian.net/browse/DB-4242)
### Description

Some unit tests being added as part of https://github.com/yugabyte/yugabyte-db/issues/13358 cause YB-Master restart concurrently with DDL.
The new infrastructure being added as part of the above work causes a DDL to run as part of catalog loading. In some cases, this causes the YB-Master to become deadlocked and unresponsive, causing the tests to fail.

From the GDB dump of the YB-Master at the time of deadlock, here is the root cause discovered by @hari90 :
**Tablet Bootstrap is waiting on a mutex**:
```
Thread 38 (Thread 0x7f26d3f66700 (LWP 31954)):
#0  0x00007f26e670354d in __lll_lock_wait () from /lib64/libpthread.so.0
#1  0x00007f26e66fee9b in _L_lock_883 () from /lib64/libpthread.so.0
#2  0x00007f26e66fed68 in pthread_mutex_lock () from /lib64/libpthread.so.0
#3  0x00007f26e6ce12c9 in std::__1::mutex::lock() () from /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20221019013514-1aec6dda08-centos7-x86_64-clang15/installed/uninstrumented/libcxx/lib/libc++.so.1
#4  0x00007f26ee93dbb7 in std::__1::unique_lock<std::__1::mutex>::unique_lock[abi:v15002](std::__1::mutex&) () from /home/deepthi/code/yugabyte-db/build/debug-clang15-dynamic-ninja/bin/../lib/libtablet.so
#5  0x00007f26eeaf32fa in yb::tablet::TransactionParticipant::Impl::LockAndFind(yb::StronglyTypedUuid<yb::TransactionId_Tag> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, yb::EnumBitSet<yb::TransactionLoadFlag>, bool) () from /home/deepthi/code/yugabyte-db/build/debug-clang15-dynamic-ninja/bin/../lib/libtablet.so
#6  0x00007f26eeb01347 in yb::tablet::TransactionParticipant::Impl::ProcessApply(yb::tablet::TransactionApplyData const&) ()
   from /home/deepthi/code/yugabyte-db/build/debug-clang15-dynamic-ninja/bin/../lib/libtablet.so
#7  0x00007f26eeb00a47 in yb::tablet::TransactionParticipant::Impl::ReplicatedApplying(yb::StronglyTypedUuid<yb::TransactionId_Tag> const&, yb::tablet::TransactionParticipant::ReplicatedData const&) ()
   from /home/deepthi/code/yugabyte-db/build/debug-clang15-dynamic-ninja/bin/../lib/libtablet.so
#8  0x00007f26eeacd884 in yb::tablet::TransactionParticipant::Impl::ProcessReplicated(yb::tablet::TransactionParticipant::ReplicatedData const&) ()
   from /home/deepthi/code/yugabyte-db/build/debug-clang15-dynamic-ninja/bin/../lib/libtablet.so
#9  0x00007f26eeac6b1c in yb::tablet::TransactionParticipant::ProcessReplicated(yb::tablet::TransactionParticipant::ReplicatedData const&) ()
   from /home/deepthi/code/yugabyte-db/build/debug-clang15-dynamic-ninja/bin/../lib/libtablet.so
#10 0x00007f26eeb4c788 in yb::tablet::UpdateTxnOperation::DoReplicated(long, yb::Status*) () from /home/deepthi/code/yugabyte-db/build/debug-clang15-dynamic-ninja/bin/../lib/libtablet.so
#11 0x00007f26eeb1dd55 in yb::tablet::Operation::Replicated(long, yb::StronglyTypedBool<yb::tablet::WasPending_Tag>) ()
   from /home/deepthi/code/yugabyte-db/build/debug-clang15-dynamic-ninja/bin/../lib/libtablet.so
#12 0x00007f26eeb33a0d in yb::tablet::OperationDriver::ApplyTask(long, std::__1::vector<yb::OpId, std::__1::allocator<yb::OpId> >*) ()
   from /home/deepthi/code/yugabyte-db/build/debug-clang15-dynamic-ninja/bin/../lib/libtablet.so
#13 0x00007f26eeb33650 in yb::tablet::OperationDriver::ReplicationFinished(yb::Status const&, long, std::__1::vector<yb::OpId, std::__1::allocator<yb::OpId> >*) ()
```
**But TransactionResolver has the mutex and is trying to get a client connection to transaction status table. But this needs master to be up**:
```
Thread 59 (Thread 0x7f26e1875700 (LWP 31672)):
#0  0x00007f26e6700a35 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x00007f26e6cdf162 in std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) ()
   from /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20221019013514-1aec6dda08-centos7-x86_64-clang15/installed/uninstrumented/libcxx/lib/libc++.so.1
#2  0x00007f26e6cdfb8b in std::__1::__assoc_sub_state::__sub_wait(std::__1::unique_lock<std::__1::mutex>&) ()
   from /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20221019013514-1aec6dda08-centos7-x86_64-clang15/installed/uninstrumented/libcxx/lib/libc++.so.1
#3  0x00007f26ee96bdc2 in std::__1::__assoc_state<yb::client::YBClient*>::copy() () from /home/deepthi/code/yugabyte-db/build/debug-clang15-dynamic-ninja/bin/../lib/libtablet.so
#4  0x00007f26ee95a2f8 in std::__1::shared_future<yb::client::YBClient*>::get[abi:v15002]() const () from /home/deepthi/code/yugabyte-db/build/debug-clang15-dynamic-ninja/bin/../lib/libtablet.so
#5  0x00007f26eeb14ee1 in yb::tablet::TransactionStatusResolver::Impl::Execute() () from /home/deepthi/code/yugabyte-db/build/debug-clang15-dynamic-ninja/bin/../lib/libtablet.so
#6  0x00007f26eeb0f732 in yb::tablet::TransactionStatusResolver::Impl::Start(std::__1::chrono::time_point<yb::CoarseMonoClock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > >) ()
   from /home/deepthi/code/yugabyte-db/build/debug-clang15-dynamic-ninja/bin/../lib/libtablet.so
#7  0x00007f26eeb0edbd in yb::tablet::TransactionStatusResolver::Start(std::__1::chrono::time_point<yb::CoarseMonoClock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > >) ()
   from /home/deepthi/code/yugabyte-db/build/debug-clang15-dynamic-ninja/bin/../lib/libtablet.so
#8  0x00007f26eead7a19 in yb::tablet::TransactionParticipant::Impl::CheckForAbortedTransactions() () from /home/deepthi/code/yugabyte-db/build/debug-clang15-dynamic-ninja/bin/../lib/libtablet.so
#9  0x00007f26eead18e8 in yb::tablet::TransactionParticipant::Impl::Poll() () from /home/deepthi/code/yugabyte-db/build/debug-clang15-dynamic-ninja/bin/../lib/libtablet.so
#10 0x00007f26eeae1ac9 in std::__1::__invoke[abi:v15002]<void (yb::tablet::TransactionParticipant::Impl::*&)(), yb::tablet::TransactionParticipant::Impl*&, , void> ()
   from /home/deepthi/code/yugabyte-db/build/debug-clang15-dynamic-ninja/bin/../lib/libtablet.so
#11 0x00007f26eeae1a4d in std::__1::__apply_functor[abi:v15002]<void (yb::tablet::TransactionParticipant::Impl::*)(), std::__1::tuple<yb::tablet::TransactionParticipant::Impl*>, 0ul, std::__1::tuple<> > ()
   from /home/deepthi/code/yugabyte-db/build/debug-clang15-dynamic-ninja/bin/../lib/libtablet.so
#12 0x00007f26eeae1a00 in std::__1::__bind<void (yb::tablet::TransactionParticipant::Impl::*)(), yb::tablet::TransactionParticipant::Impl*>::operator()[abi:v15002]<> ()
   from /home/deepthi/code/yugabyte-db/build/debug-clang15-dynamic-ninja/bin/../lib/libtablet.so
#13 0x00007f26eeae19d5 in std::__1::__invoke[abi:v15002]<std::__1::__bind<void (yb::tablet::TransactionParticipant::Impl::*)(), yb::tablet::TransactionParticipant::Impl*>&> ()
   from /home/deepthi/code/yugabyte-db/build/debug-clang15-dynamic-ninja/bin/../lib/libtablet.so
#14 0x00007f26eeae1995 in void std::__1::__invoke_void_return_wrapper<void, true>::__call<std::__1::__bind<void (yb::tablet::TransactionParticipant::Impl::*)(), yb::tablet::TransactionParticipant::Impl*>&>(std::__1::__bind<void (yb::tablet::TransactionParticipant::Impl::*)(), yb::tablet::TransactionParticipant::Impl*>&) () from /home/deepthi/code/yugabyte-db/build/debug-clang15-dynamic-ninja/bin/../lib/libtablet.so
#15 0x00007f26eeae196d in std::__1::__function::__alloc_func<std::__1::__bind<void (yb::tablet::TransactionParticipant::Impl::*)(), yb::tablet::TransactionParticipant::Impl*>, std::__1::allocator<std::__1::__bind<void (yb::tablet::TransactionParticipant::Impl::*)(), yb::tablet::TransactionParticipant::Impl*> >, void ()>::operator()[abi:v15002]() ()
   from /home/deepthi/code/yugabyte-db/build/debug-clang15-dynamic-ninja/bin/../lib/libtablet.so
#16 0x00007f26eeae0d79 in std::__1::__function::__func<std::__1::__bind<void (yb::tablet::TransactionParticipant::Impl::*)(), yb::tablet::TransactionParticipant::Impl*>, std::__1::allocator<std::__1::__bind<void (yb::tablet::TransactionParticipant::Impl::*)(), yb::tablet::TransactionParticipant::Impl*> >, void ()>::operator()() ()
   from /home/deepthi/code/yugabyte-db/build/debug-clang15-dynamic-ninja/bin/../lib/libtablet.so
#17 0x00007f26f0401162 in std::__1::__function::__value_func<void ()>::operator()[abi:v15002]() const () from /home/deepthi/code/yugabyte-db/build/debug-clang15-dynamic-ninja/bin/../lib/libmaster.so
#18 0x00007f26f03d8855 in std::__1::function<void ()>::operator()() const () from /home/deepthi/code/yugabyte-db/build/debug-clang15-dynamic-ninja/bin/../lib/libmaster.so
#19 0x00007f26e8f0bc26 in yb::rpc::Poller::Poll(yb::Status const&) () from /home/deepthi/code/yugabyte-db/build/debug-clang15-dynamic-ninja/bin/../lib/libyrpc.so
#20 0x00007f26e8f0c9d1 in std::__1::__invoke[abi:v15002]<void (yb::rpc::Poller::*&)(yb::Status const&), yb::rpc::Poller*&, yb::Status const&, void> ()
   from /home/deepthi/code/yugabyte-db/build/debug-clang15-dynamic-ninja/bin/../lib/libyrpc.so
#21 0x00007f26e8f0c92a in std::__1::__apply_functor[abi:v15002]<void (yb::rpc::Poller::*)(yb::Status const&), std::__1::tuple<yb::rpc::Poller*, std::__1::placeholders::__ph<1> >, 0ul, 1ul, std::__1::tuple<yb::Status const&> > () from /home/deepthi/code/yugabyte-db/build/debug-clang15-dynamic-ninja/bin/../lib/libyrpc.so
```

**Comment by hari90** [comment]
closed this as completed in https://github.com/yugabyte/yugabyte-db/commit/14744f4dac08a75d665bdf2bbf737803a44c9e15
