### ISSUE TITLE
[CDCSDK + Connector] ADD TABLE with 100 tables scenario 'retrying after backoff' issue. Polling Interval to be increased to minutes

### ISSUE THREAD

**Issue by shamanthchandra-yb** [yugabyte/yugabyte-db#15056]
Jira Link: [DB-4284](https://yugabyte.atlassian.net/browse/DB-4284)
### Description

 I see this error in connector log. Here ybconnector_regex is yugabyte connector name

```
2022-11-17 10:20:37,758 ERROR  ||  [Worker clientId=connect-1, groupId=9e1eb5] Failed to reconfigure connector's tasks (ybconnector_regex), retrying after backoff:   [org.apache.kafka.connect.runtime.distributed.DistributedHerder]
io.debezium.DebeziumException: Couldn't initialize type registry
        at io.debezium.connector.yugabytedb.YugabyteDBTypeRegistry.<init>(YugabyteDBTypeRegistry.java:146)
        at io.debezium.connector.yugabytedb.YugabyteDBConnector.taskConfigs(YugabyteDBConnector.java:95)
        at org.apache.kafka.connect.runtime.Worker.connectorTaskConfigs(Worker.java:347)
        at org.apache.kafka.connect.runtime.distributed.DistributedHerder.reconfigureConnector(DistributedHerder.java:1566)
        at org.apache.kafka.connect.runtime.distributed.DistributedHerder.reconfigureConnectorTasksWithRetry(DistributedHerder.java:1513)
        at org.apache.kafka.connect.runtime.distributed.DistributedHerder.lambda$null$29(DistributedHerder.java:1526)
        at org.apache.kafka.connect.runtime.distributed.DistributedHerder.tick(DistributedHerder.java:408)
        at org.apache.kafka.connect.runtime.distributed.DistributedHerder.run(DistributedHerder.java:326)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

Connector version used: Connector version: [quay.io/vaibhav_yb/test_repo:1.9.5.y.2.1.1](http://quay.io/vaibhav_yb/test_repo:1.9.5.y.2.1.1)

**Comment by adithya-yb** [comment]
@vaibhav-yb  AFAIK we have already fixed this right ? 
If so, please add the ticket with which we landed this and let's close the issue.
