### ISSUE TITLE
[CDC + Connector]With tablet splitting (35 MB), CDC stopped again, with tablet=null

### ISSUE THREAD

**Issue by shamanthchandra-yb** [yugabyte/yugabyte-db#15260]
Jira Link: [DB-4425](https://yugabyte.atlassian.net/browse/DB-4425)
### Description

Still seeing on latest shared connector

`quay.io/yugabyte/debezium-connector:1.9.5.y.4` and `quay.io/vaibhav_yb/cdcsdk_server_custom:0.1`

`
WARN   YugabyteDB|db_cdc|streaming  Error while trying to bootstrap tablet 0a15a53830ab404caaa0200130d0d66e; will attempt retry 1 of 5 after 60000 milli-seconds. Exception message: Too many attempts: YRpc(method=GetCheckpoint, service=yb.cdc.CDCService, tablet=null, attempt=100, maxAttempts=100, maxTimeoutMs=600000, elapsedTimeMs=120)   [io.debezium.connector.yugabytedb.YugabyteDBStreamingChangeEventSource]
`

```
2022-12-08 13:36:42,627 ERROR  YugabyteDB|db_cdc|streaming  Too many errors while trying to get the changes from server. All 5 retries failed.   [io.debezium.connector.yugabytedb.YugabyteDBStreamingChangeEventSource]
2022-12-08 13:36:42,627 ERROR  YugabyteDB|db_cdc|streaming  Producer failure   [io.debezium.pipeline.ErrorHandler]
org.yb.client.CDCErrorException: Server[7ac4c5b4a0854f4c91ff9ac9c15be4b7] LEADER_NOT_READY_TO_SERVE[code 23]: Not ready to serve
	at org.yb.client.TabletClient.dispatchCDCErrorOrReturnException(TabletClient.java:506)
	at org.yb.client.TabletClient.decode(TabletClient.java:437)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

```
2022-12-08 13:36:43,160 ERROR  ||  WorkerSourceTask{id=ybconnector_cdc_3780c7_test_cdc_5e8069_test_cdc_f13f92-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted   [org.apache.kafka.connect.runtime.WorkerTask]
org.apache.kafka.connect.errors.ConnectException: An exception occurred in the change event producer. This connector will be stopped.
	at io.debezium.pipeline.ErrorHandler.setProducerThrowable(ErrorHandler.java:50)
	at io.debezium.connector.yugabytedb.YugabyteDBStreamingChangeEventSource.execute(YugabyteDBStreamingChangeEventSource.java:141)
	at io.debezium.connector.yugabytedb.YugabyteDBStreamingChangeEventSource.execute(YugabyteDBStreamingChangeEventSource.java:47)
	at io.debezium.pipeline.ChangeEventSourceCoordinator.streamEvents(ChangeEventSourceCoordinator.java:174)
	at io.debezium.connector.yugabytedb.YugabyteDBChangeEventSourceCoordinator.executeChangeEventSources(YugabyteDBChangeEventSourceCoordinator.java:132)
	at io.debezium.pipeline.ChangeEventSourceCoordinator.lambda$start$0(ChangeEventSourceCoordinator.java:109)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.yb.client.CDCErrorException: Server[7ac4c5b4a0854f4c91ff9ac9c15be4b7] LEADER_NOT_READY_TO_SERVE[code 23]: Not ready to serve
	at org.yb.client.TabletClient.dispatchCDCErrorOrReturnException(TabletClient.java:506)
	at org.yb.client.TabletClient.decode(TabletClient.java:437)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	... 3 more
```

```
2022-12-08 13:38:13,162 WARN   YugabyteDB|db_cdc|streaming  Error while trying to bootstrap tablet 0a15a53830ab404caaa0200130d0d66e; will attempt retry 3 of 5 after 60000 milli-seconds. Exception message: null   [io.debezium.connector.yugabytedb.YugabyteDBStreamingChangeEventSource]
2022-12-08 13:38:13,162 WARN   YugabyteDB|db_cdc|streaming  Connector retry sleep interrupted by exception: {}   [io.debezium.connector.yugabytedb.YugabyteDBStreamingChangeEventSource]
java.lang.InterruptedException
	at io.debezium.util.Metronome$2.pause(Metronome.java:94)
	at io.debezium.connector.yugabytedb.YugabyteDBStreamingChangeEventSource.bootstrapTabletWithRetry(YugabyteDBStreamingChangeEventSource.java:208)
	at io.debezium.connector.yugabytedb.YugabyteDBStreamingChangeEventSource.getChanges2(YugabyteDBStreamingChangeEventSource.java:299)
	at io.debezium.connector.yugabytedb.YugabyteDBStreamingChangeEventSource.execute(YugabyteDBStreamingChangeEventSource.java:138)
	at io.debezium.connector.yugabytedb.YugabyteDBStreamingChangeEventSource.execute(YugabyteDBStreamingChangeEventSource.java:47)
	at io.debezium.pipeline.ChangeEventSourceCoordinator.streamEvents(ChangeEventSourceCoordinator.java:174)
	at io.debezium.connector.yugabytedb.YugabyteDBChangeEventSourceCoordinator.executeChangeEventSources(YugabyteDBChangeEventSourceCoordinator.java:132)
	at io.debezium.pipeline.ChangeEventSourceCoordinator.lambda$start$0(ChangeEventSourceCoordinator.java:109)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

```
2022-12-08 13:38:13,164 ERROR  YugabyteDB|db_cdc|streaming  Some clients are left in the client cache and haven't been cleaned up: {172.151.21.13:7100=TabletClient@711134228(chan=[id: 0xcb25c138, L:/172.17.0.2:34306 ! R:/172.151.21.13:7100], uuid=YB Master - 172.151.21.13:7100, #pending_rpcs=0, #rpcs_inflight=0)}   [org.yb.client.AsyncYBClient]
2022-12-08 13:38:13,165 ERROR  YugabyteDB|db_cdc|streaming  Producer failure   [io.debezium.pipeline.ErrorHandler]
java.lang.NullPointerException
	at io.debezium.connector.yugabytedb.YugabyteDBErrorHandler.isRetriable(YugabyteDBErrorHandler.java:29)
	at io.debezium.pipeline.ErrorHandler.setProducerThrowable(ErrorHandler.java:38)
	at io.debezium.connector.yugabytedb.YugabyteDBStreamingChangeEventSource.execute(YugabyteDBStreamingChangeEventSource.java:141)
	at io.debezium.connector.yugabytedb.YugabyteDBStreamingChangeEventSource.execute(YugabyteDBStreamingChangeEventSource.java:47)
	at io.debezium.pipeline.ChangeEventSourceCoordinator.streamEvents(ChangeEventSourceCoordinator.java:174)
	at io.debezium.connector.yugabytedb.YugabyteDBChangeEventSourceCoordinator.executeChangeEventSources(YugabyteDBChangeEventSourceCoordinator.java:132)
	at io.debezium.pipeline.ChangeEventSourceCoordinator.lambda$start$0(ChangeEventSourceCoordinator.java:109)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by adithya-yb** [comment]
We have now fixed this issue, the tablet split + nemesis case passes in the daily LRU runs
