### ISSUE TITLE
[DocDB][Upgrade] Invalid argument: Invalid table definition: Error creating table mv_upgrade_db2_12_4_2.pg_temp_16427 on the master: num_tablets should be greater than 0. Client would need to wait for master leader get heartbeats from tserver.

### ISSUE THREAD

**Issue by def-** [yugabyte/yugabyte-db#15301]
Jira Link: [DB-4455](https://yugabyte.atlassian.net/browse/DB-4455)
### Description

Upgrade test fails when verifying objects, from 2.12.4.2-b1 to 2.17.1.0-b190: https://phabricator.dev.yugabyte.com/D20539
```
testupgrade-k8s-rf3-upgrade-2.12.4.2_1: Start
	(     0.473s) User Login : Success
	(     0.215s) Refresh YB Version : Success
	(    90.603s) Setup Provider : Success
	(     0.108s) Updating Health Check Interval to 60000 sec : Success
	(   421.649s) Create universe dfel-isd2464-134a9b7b27-20221212-094001 : Success
	(    38.000s) Start sample workloads : Success
	(   874.648s) Creating V2 backups in S3 : Success
	(   430.588s) Verify geo-partitioned objects : Success
	(   466.816s) Executing yb-admin upgrade_ysql : Success
	(     0.001s) Executing yb-admin upgrade_ysql : >>> Integration Test Failed <<< 
Verifying during upgrade failed:
Invalid argument: Invalid table definition: Error creating table mv_upgrade_db2_12_4_2.pg_temp_16427 on the master: num_tablets should be greater than 0. Client would need to wait for master leader get heartbeats from tserver.

	(    27.266s) Saved server log files and keys at /share/jenkins/workspace/itest-system-developer/logs/2.17.1.0_testupgrade-k8s-rf3-upgrade-2.12.4.2_1_20221212_141752 : Success
	(    95.903s) Destroy universe : Success
	(     0.233s) Check and stop workloads : Success
testupgrade-k8s-rf3-upgrade-2.12.4.2_1: End
```
This happens in relation to materialized views CC @fizaaluthra I'll notify if I also see it without the materialized view.
Master logs before:
```
I1212 14:14:05.488943 16294 ts_manager.cc:140] Registered new tablet server { permanent_uuid: "3626254c45874a2695bac1bba30a8eb0" instance_seqno: 1670854445470052 start_time_us: 1670854445470052 } with Master, full list: [{93369358a01f42949a726b3ef44c1e76, 0x0000000004a5b210 -> { permanent_uuid: 93369358a01f42949a726b3ef44c1e76 registration: common { private_rpc_addresses { host: "10.9.196.217" port: 9100 } http_addresses { host: "10.9.196.217" port: 9000 } cloud_info { placement_cloud: "aws" placement_region: "us-west-2" placement_zone: "us-west-2c" } placement_uuid: "741619b4-52b7-4138-afa9-7464bc9d251d" pg_port: 5433 } capabilities: 2189743739 capabilities: 1427296937 capabilities: 2980225056 placement_id: aws:us-west-2:us-west-2c }}, {3626254c45874a2695bac1bba30a8eb0, 0x0000000004b7f690 -> { permanent_uuid: 3626254c45874a2695bac1bba30a8eb0 registration: common { private_rpc_addresses { host: "10.9.105.50" port: 9100 } http_addresses { host: "10.9.105.50" port: 9000 } cloud_info { placement_cloud: "aws" placement_region: "us-west-2" placement_zone: "us-west-2a" } placement_uuid: "741619b4-52b7-4138-afa9-7464bc9d251d" pg_port: 5433 } capabilities: 2189743739 capabilities: 1427296937 capabilities: 2980225056 placement_id: aws:us-west-2:us-west-2a }}, {68ed1e71075b4a7d8a2e003fd10582d1, 0x0000000004faf210 -> { permanent_uuid: 68ed1e71075b4a7d8a2e003fd10582d1 registration: common { private_rpc_addresses { host: "10.9.134.11" port: 9100 } http_addresses { host: "10.9.134.11" port: 9000 } cloud_info { placement_cloud: "aws" placement_region: "us-west-2" placement_zone: "us-west-2b" } placement_uuid: "741619b4-52b7-4138-afa9-7464bc9d251d" pg_port: 5433 } capabilities: 2189743739 capabilities: 1427296937 capabilities: 2980225056 placement_id: aws:us-west-2:us-west-2b }}]
I1212 14:14:05.488988 16294 catalog_manager.cc:1052] T 00000000000000000000000000000000 P e6957f5f939141398cf04e9b1133468a: 3 tablet servers registered, creating the transaction status table
I1212 14:14:05.489073 16294 catalog_manager.cc:3752] Creating transaction status table transactions
I1212 14:14:05.489809 16294 catalog_manager.cc:2976] CreateTable from internal request:
name: "transactions"
schema {
  columns {
    name: "key"
    type {
      main: BINARY
    }
    is_key: true
    is_hash_key: true
    is_nullable: false
    is_static: false
    is_counter: false
    sorting_type: 0
    order: 0
    pg_type_oid: 0
  }
  table_properties {
    num_tablets: 0
  }
}
table_type: TRANSACTION_STATUS_TABLE_TYPE
namespace {
  name: "system"
}
I1212 14:14:05.489915 16294 catalog_manager.cc:3155] Setting default tablets to 0 with 0 primary servers
I1212 14:14:05.489935 16294 partition.cc:542] Creating partitions with num_tablets: 0
W1212 14:14:05.489989 16294 catalog_manager.cc:1063] T 00000000000000000000000000000000 P e6957f5f939141398cf04e9b1133468a: Failed creating transaction status table, waiting: Invalid argument (yb/common/partition.cc:547): num_tablets should be greater than 0. Client would need to wait for master leader get heartbeats from tserver.
```
Full logs: https://drive.google.com/file/d/1ew5lcKdM0RkRyprLMD9adu8sJ_jjI2b8/view?usp=share_link

**Comment by pilshchikov** [comment]
@kripasreenivasan 
Issues was reproduced on  `2.20.2.4-b3`
Case:
1. Sart creating tables (should create 1000 tables)
2. Run background nemesis (Stop/start AWS VM, restart master process)
On table 32 this issue throwed
```
2024-09-10 06:24:13,055 [main] INFO SqlDataLoadWithDDL - Drop and create table: test_31
2024-09-10 06:24:13,062 [main] INFO SqlDataLoadWithDDL - Adding additional 5 columns into a table, because DROP_COLUMN operation used
2024-09-10 06:24:13,224 [main] INFO SqlDataLoadWithDDL - Drop and create table: test_32
2024-09-10 06:24:13,232 [main] INFO SqlDataLoadWithDDL - Adding additional 5 columns into a table, because DROP_COLUMN operation used
2024-09-10 06:24:19,629 [main] INFO SqlDataLoadWithDDL - Drop and create table: test_33
2024-09-10 06:24:19,636 [main] INFO SqlDataLoadWithDDL - Adding additional 5 columns into a table, because DROP_COLUMN operation used
Exception in thread "main" com.yugabyte.util.PSQLException: ERROR: Invalid table definition: Error creating table db.test_33 on the master: num_tablets should be greater than 0. Client would need to wait for master leader get heartbeats from tserver.
	at com.yugabyte.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2675)
	at com.yugabyte.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2365)
	at com.yugabyte.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:355)
	at com.yugabyte.jdbc.PgStatement.executeInternal(PgStatement.java:490)
	at com.yugabyte.jdbc.PgStatement.execute(PgStatement.java:408)
	at com.yugabyte.jdbc.PgStatement.executeWithFlags(PgStatement.java:329)
	at com.yugabyte.jdbc.PgStatement.executeCachedSql(PgStatement.java:315)
	at com.yugabyte.jdbc.PgStatement.executeWithFlags(PgStatement.java:291)
	at com.yugabyte.jdbc.PgStatement.execute(PgStatement.java:286)
	at com.yugabyte.sample.apps.SqlDataLoadWithDDL.createTable(SqlDataLoadWithDDL.java:241)
	at com.yugabyte.sample.apps.SqlDataLoadWithDDL.createTablesIfNeeded(SqlDataLoadWithDDL.java:146)
	at com.yugabyte.sample.Main.run(Main.java:174)
	at com.yugabyte.sample.Main.main(Main.java:89)
```

Logs and report link in a Jira comment
