### ISSUE TITLE
[CDCSDK] Data loss seen in snapshot + stream mode

### ISSUE THREAD

**Issue by shamanthchandra-yb** [yugabyte/yugabyte-db#15449]
Jira Link: [DB-4559](https://yugabyte.atlassian.net/browse/DB-4559)
### Description

![Profile (1)](https://user-images.githubusercontent.com/109518123/209770778-63fde45e-d8fd-4cb9-b7f5-59217d2e1223.png)

All logs: 

[All_Logs.zip](https://github.com/yugabyte/yugabyte-db/files/10312649/All_Logs.zip)

Few errors in connector logs:

```
org.yb.client.CDCErrorException: Server[0a46ce1e05b04b399bf2b97d325f3257] NETWORK_ERROR[code 8]: recvmsg error: Connection refused
	at org.yb.client.TabletClient.dispatchCDCErrorOrReturnException(TabletClient.java:506)
	at org.yb.client.TabletClient.decode(TabletClient.java:437)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

[DB-4559]: https://yugabyte.atlassian.net/browse/DB-4559?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by shamanthchandra-yb** [comment]
@suranjan @adithya-yb 
I am able to see this issue again: 
http://stress.dev.yugabyte.com/stress_test/2a963766-3b51-4f65-b246-662bbea93d7a

Logs: 
[logs_snapshot_and_stream.zip](https://github.com/yugabyte/yugabyte-db/files/10869098/logs_snapshot_and_stream.zip)



Between streaming after snapshot and snapshot completion, few WARN msgs pasting here, not sure if its related.

```
WARN   YugabyteDB|db_cdc|streaming|0  None of the provided masters (172.151.24.184:7100,172.151.16.69:7100) is a leader, will retry.   [org.yb.client.GetMasterRegistrationReceived]
```

**Comment by shamanthchandra-yb** [comment]
Seen here as well: http://stress.dev.yugabyte.com/stress_test/522e8188-741f-483e-b69d-ee11a1e91c9b

**Comment by shamanthchandra-yb** [comment]
We are also seeing data loss in different testcase where we are using "snapshot: initial" mode

http://stress.dev.yugabyte.com/stress_test/564ae83a-63ad-4fa9-9c8e-5bc74ebeb55b

testcase name: **test_cdc_delete_stream_id_with_connector**

```
Create 5 databases
Create 1 table in each of the database
Add connector for each of the table (initial mode)

In iteration:
Load 10 rows to all the tables
Sleep 30 sec
Delete Stream ID (random one from the list of 5)
Load 10 rows to all the tables
Sleep 30 sec
Verify all the table rows in target except one which got deleted
.
.
.
```

In first iteration itself, its failing.

I tried with snapshot never mode, though this case is not written for snapshot never mode as we truncate picked table from sink and assertions are made as whole from inception.

But tweaked to not delete one of the table and delete only from remaining. It went fine (Tested till 9 iterations atleast). 

Me and @suranjan when looked into cdc_state table, the table which had data loss had status like 'snapshot_key' where as the tables which didn't had issue didn't had any entry which were still in **snapshot_key**

Hence deducing, this issue might also be same as this (Snapshot + Streaming mode).

**Comment by shamanthchandra-yb** [comment]
Backport to 2.16 is required. Hence reopening.
