### ISSUE TITLE
[YSQL] Memory leak in UT TestPgWithoutWaitQueuesIsolationRegress#runPgTransparentRestartsRegressTest

### ISSUE THREAD

**Issue by kripasreenivasan** [yugabyte/yugabyte-db#15448]
Jira Link: [DB-4558](https://yugabyte.atlassian.net/browse/DB-4558)
### Description

In master 2.17.1.0-b382, a memory leak was observed in TestPgWithoutWaitQueuesIsolationRegress#runPgTransparentRestartsRegressTest

https://storage.googleapis.com/test-results.yugabyte.com/jenkins/job/github-yugabyte-db-alma8-master-clang15-asan/221/artifact/java/yb-pgsql/target/surefire-reports_org.yb.pgsql.TestPgWithoutWaitQueuesIsolationRegress__runPgTransparentRestartsRegressTest/org.yb.pgsql.TestPgWithoutWaitQueuesIsolationRegress-output.txt?GoogleAccessId=detective-service-acct%40yugabyte.iam.gserviceaccount.com&Expires=1672206756&Signature=nJyc437nUVMy7GAlCtg5%2BtR1AGaVUAsSJxNpHpl5dfOvrhZAp%2FraZAqNggpE%2BtdjKGzgj6av2bfKkEkPO3gvwgBSutTDYB4hV6qrOfEReijBwJmVP7jP0ZwkCNHDUpKm%2BKce4U6cR7GeEFsXuGTpmEV%2FqCKE6fSXebpxGilvyrFaUpz450s0Hv1EHCrMT2GcZEwnk6P5NlKFrLaMR2Kzq0lGtWAy4SOfMC%2FzX%2BiB0qa%2FwbHUni7GGvrJirTugNcVQleGjPUYum7rMqAT5jdJQdvK%2BEJZwVtDVy9AKe3V1OwDbNWBfiFq8XtD0YffNe7IU9M751iUjD9erRRnSxUvAw%3D%3D 

```
+ =================================================================
+ ==26727==ERROR: LeakSanitizer: detected memory leaks
+ 
+ Direct leak of 2048 byte(s) in 1 object(s) allocated from:
+     #0 0x555dc9ac76d6 in realloc /opt/yb-build/llvm/yb-llvm-v15.0.3-yb-1-1667030060-0b8d1183-almalinux8-x86_64-build/src/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:85:3
+     #1 0x555dc9b0e0a9 in pg_realloc ${YB_SRC_ROOT}/src/postgres/src/common/../../../../../src/postgres/src/common/fe_memutils.c:72:8
+     #2 0x555dc9b057b2 in addlitchar ${YB_SRC_ROOT}/src/postgres/src/test/isolation/specscanner.l:116:12
+     #3 0x555dc9b057b2 in spec_yylex ${YB_SRC_ROOT}/src/postgres/src/test/isolation/specscanner.l:90:6
+     #4 0x555dc9b0195f in spec_yyparse ${YB_SRC_ROOT}/src/postgres/src/test/isolation/specparse.c:1190:16
+     #5 0x555dc9b08492 in main ${YB_SRC_ROOT}/src/postgres/src/test/isolation/../../../../../../src/postgres/src/test/isolation/isolationtester.c:116:2
+     #6 0x7f3ff9647d84 in __libc_start_main (/lib64/libc.so.6+0x3ad84) (BuildId: d18afae5244bc9c85026bd7d64b276d51b452d93)
+ 
+ Objects leaked above:
+ 0x61d000000080 (2048 bytes)
+ 
+ SUMMARY: AddressSanitizer: 2048 byte(s) leaked in 1 allocation(s).

======================================================================

13:02:44.977 (Time-limited test) [WARN - org.yb.pgsql.PgRegressRunner.run(PgRegressRunner.java:124)] Failed tests: [yb-stat-activity-waitevent-statement-retry]
13:02:44.977 (Time-limited test) [WARN - org.yb.pgsql.PgRegressRunner.run(PgRegressRunner.java:129)] Expected test output file ${TEST_TMPDIR}/pgregress_output/yb_without_wait_queues_schedule/expected/yb-stat-activity-waitevent-statement-retry.out not found.
13:02:44.977 (Time-limited test) [INFO - org.yb.pgsql.BasePgSQLTest.cleanUpAfter(BasePgSQLTest.java:411)] Cleaning up after runPgTransparentRestartsRegressTest
ts1|pid26394|:15627 2022-12-27 13:02:46.333 UTC [26707] WARNING:  there is no transaction in progress
13:02:46.337 (Time-limited test) [INFO - org.yb.pgsql.BasePgSQLTest.cleanUpCustomDatabases(BasePgSQLTest.java:445)] Cleaning up custom databases
13:02:46.422 (Time-limited test) [INFO - org.yb.pgsql.BasePgSQLTest.cleanUpCustomEntities(BasePgSQLTest.java:475)] Cleaning up roles
13:02:46.477 (Time-limited test) [INFO - org.yb.pgsql.BasePgSQLTest.cleanUpCustomEntities(BasePgSQLTest.java:489)] Cleaning up role yugabyte (persistent? true)
13:02:47.203 (Time-limited test) [INFO - org.yb.pgsql.BasePgSQLTest.cleanUpCustomEntities(BasePgSQLTest.java:489)] Cleaning up role yugabyte_test (persistent? true)
13:02:47.267 (Time-limited test) [INFO - org.yb.pgsql.BasePgSQLTest.cleanUpCustomEntities(BasePgSQLTest.java:489)] Cleaning up role yugabyte (persistent? true)
13:02:47.275 (Time-limited test) [INFO - org.yb.pgsql.BasePgSQLTest.cleanUpCustomEntities(BasePgSQLTest.java:489)] Cleaning up role yugabyte_test (persistent? true)
13:02:47.295 (main) [ERROR - org.yb.BaseYBTest$1$2.logEventDetails(BaseYBTest.java:243)] YB Java test failed: class="org.yb.pgsql.TestPgWithoutWaitQueuesIsolationRegress", method="runPgTransparentRestartsRegressTest"
java.lang.AssertionError: pg_regress exited with error code: 1, failed tests: [yb-stat-activity-waitevent-statement-retry]
	at org.yb.pgsql.PgRegressRunner.run(PgRegressRunner.java:174)
	at org.yb.pgsql.BasePgSQLTest.runPgRegressTest(BasePgSQLTest.java:168)
	at org.yb.pgsql.TestPgWithoutWaitQueuesIsolationRegress.runPgTransparentRestartsRegressTest(TestPgWithoutWaitQueuesIsolationRegress.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by kripasreenivasan** [comment]
Memory leak observed in back to back builds. Build 383 as well.
