### ISSUE TITLE
[CDCSDK + Connector] Too many errors while trying to get children for split tablet error seen and CDC stops

### ISSUE THREAD

**Issue by shamanthchandra-yb** [yugabyte/yugabyte-db#15679]
Jira Link: [DB-5045](https://yugabyte.atlassian.net/browse/DB-5045)
### Description

Seen on build  **2.16.1.0-b31**

http://stress.dev.yugabyte.com/stress_test/78350d1e-5680-418a-8084-f7d52c4ecb54

All Logs: 
[logs_cdc.zip](https://github.com/yugabyte/yugabyte-db/files/10409145/logs_cdc.zip)

```
2023-01-12 14:35:41,206 ERROR  YugabyteDB|db_cdc|streaming|0  Too many errors while trying to get children for split tablet 148f9e57d39c4c5c95f3e17fac2ca71f   [io.debezium.connector.yugabytedb.YugabyteDBStreamingChangeEventSource]
189542 2023-01-12 14:35:41,206 ERROR  YugabyteDB|db_cdc|streaming|0  Error   [io.debezium.connector.yugabytedb.YugabyteDBStreamingChangeEventSource]
189543 org.yb.client.NonRecoverableException: Too many attempts: YRpc(method=GetTabletListToPollForCDC, service=yb.cdc.CDCService, tablet=null, attempt=100, maxAttempts=100, maxTimeoutMs=600000, elapsedTimeMs=30)
189544         at org.yb.client.AsyncYBClient.tooManyAttemptsOrTimeout(AsyncYBClient.java:2026)
189545         at org.yb.client.AsyncYBClient.sendRpcToTablet(AsyncYBClient.java:1641)
189546         at org.yb.client.AsyncYBClient$RetryRpcCB.call(AsyncYBClient.java:1736)
189547         at org.yb.client.AsyncYBClient$RetryRpcCB.call(AsyncYBClient.java:1730)
189548         at com.stumbleupon.async.Deferred.doCall(Deferred.java:1280)
189549         at com.stumbleupon.async.Deferred.runCallbacks(Deferred.java:1259)
189550         at com.stumbleupon.async.Deferred.callback(Deferred.java:1002)
189551         at org.yb.client.YRpc.handleCallback(YRpc.java:184)
189552         at org.yb.client.YRpc.callback(YRpc.java:197)
189553         at org.yb.client.TabletClient.decode(TabletClient.java:451)
189554         at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
189555         at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
189556         at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
189557         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
189558         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
189559         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
189560         at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
189561         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
189562         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
189563         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
189564         at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
189565         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
189566         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
189567         at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
189568         at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
189569         at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
189570         at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
189571         at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
189572         at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
189573         at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
189574         at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
189575         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
189576         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
189577         at java.base/java.lang.Thread.run(Thread.java:829)
189578 2023-01-12 14:35:41,207 WARN   YugabyteDB|db_cdc|streaming|0  Error while trying to get the changes from the server; will attempt retry 5 of 10 after 60000 milli-seconds. Exception message: Too many attempts: YRpc(method=GetTabletListTo
189579 2023-01-12 14:35:41,207 WARN   YugabyteDB|db_cdc|streaming|0  Stacktrace   [io.debezium.connector.yugabytedb.YugabyteDBStreamingChangeEventSource]
189580 org.yb.client.NonRecoverableException: Too many attempts: YRpc(method=GetTabletListToPollForCDC, service=yb.cdc.CDCService, tablet=null, attempt=100, maxAttempts=100, maxTimeoutMs=600000, elapsedTimeMs=30)
189581         at org.yb.client.AsyncYBClient.tooManyAttemptsOrTimeout(AsyncYBClient.java:2026)
189582         at org.yb.client.AsyncYBClient.sendRpcToTablet(AsyncYBClient.java:1641)
189583         at org.yb.client.AsyncYBClient$RetryRpcCB.call(AsyncYBClient.java:1736)
189584         at org.yb.client.AsyncYBClient$RetryRpcCB.call(AsyncYBClient.java:1730)
189585         at com.stumbleupon.async.Deferred.doCall(Deferred.java:1280)
189586         at com.stumbleupon.async.Deferred.runCallbacks(Deferred.java:1259)
189587         at com.stumbleupon.async.Deferred.callback(Deferred.java:1002)
189588         at org.yb.client.YRpc.handleCallback(YRpc.java:184)
189589         at org.yb.client.YRpc.callback(YRpc.java:197)
189590         at org.yb.client.TabletClient.decode(TabletClient.java:451)
```

[DB-5045]: https://yugabyte.atlassian.net/browse/DB-5045?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by adithya-yb** [comment]
Closing , was also tracked through: https://github.com/yugabyte/yugabyte-db/issues/15433

**Comment by shamanthchandra-yb** [comment]
Seeing this issue again: https://github.com/yugabyte/yugabyte-db/issues/15679

Build: 2.16.2.0-b33

Hence re-opening.

**Comment by shamanthchandra-yb** [comment]
@vaibhav-yb I was able to see this again in today's LRU verification: http://stress.dev.yugabyte.com/stress_test/b7354896-63df-42af-a9ba-8e849a0fced1

Note: This is with EXPLICIT checkpoint

**Comment by shamanthchandra-yb** [comment]
Reopening this as we seen again:

http://stress.dev.yugabyte.com/stress_test/332ca590-dcea-4ab8-8dde-a92db5e40f44

`2.18.3.0-b12` + `1.9.5.y.34-SNAPSHOT`

Might be one off case, I hit this when tried without connector restart, 1 out of 6 times.

However, this could be resolved after connector restart, its not acceptable for CDC in production. Hence reopening to track.

cc: @suranjan
