### ISSUE TITLE
[CDCSDK] Errors occurred while reaching out to the tablet servers

### ISSUE THREAD

**Issue by shamanthchandra-yb** [yugabyte/yugabyte-db#15708]
Jira Link: [DB-5061](https://yugabyte.atlassian.net/browse/DB-5061)
### Description

There was a data loss in [test_cdc_lru_nemesis_splitting_postgres_debezium](http://stress.dev.yugabyte.com/stress_test/efad6b81-e93b-4f69-804a-f33a075935f2)

When tried to see why CDC stopped, I didn’t find any error apart from this

```
2023-01-16 04:22:45,615 WARN   YugabyteDB|db_cdc|streaming|3  Throwing error because error code did not match. Expected split code: TABLET_SPLIT, code received: INTERNAL_ERROR   [io.de
342432 2023-01-16 04:22:45,615 WARN   YugabyteDB|db_cdc|streaming|3  Error while trying to get the changes from the server; will attempt retry 1 of 10 after 60000 milli-seconds. Exception mes
342433 2023-01-16 04:22:45,615 WARN   YugabyteDB|db_cdc|streaming|3  Stacktrace   [io.debezium.connector.yugabytedb.YugabyteDBStreamingChangeEventSource]
342434 org.yb.client.CDCErrorException: Server[7ec5c73bf010414fa4c0196f3610be7f] IO_ERROR[code 5]: Errors occurred while reaching out to the tablet servers
342435         at org.yb.client.TabletClient.dispatchCDCErrorOrReturnException(TabletClient.java:506)
342436         at org.yb.client.TabletClient.decode(TabletClient.java:437)
342437         at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
342438         at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
342439         at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
342440         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
342441         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
342442         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
342443         at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
342444         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
342445         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
342446         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
342447         at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
342448         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
342449         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
342450         at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
342451         at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
342452         at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
342453         at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
342454         at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
342455         at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
342456         at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
342457         at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
342458         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
342459         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
342460         at java.base/java.lang.Thread.run(Thread.java:829)

```

**Logs:**
[Docker_and_frameworks_logs.zip](https://github.com/yugabyte/yugabyte-db/files/10423807/Docker_and_frameworks_logs.zip)

**Universe Node logs:**
[172.151.16.122.zip](https://github.com/yugabyte/yugabyte-db/files/10423811/172.151.16.122.zip)
[172.151.26.227.zip](https://github.com/yugabyte/yugabyte-db/files/10423813/172.151.26.227.zip)
[172.151.28.228.zip](https://github.com/yugabyte/yugabyte-db/files/10423814/172.151.28.228.zip)

[DB-5061]: https://yugabyte.atlassian.net/browse/DB-5061?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by vaibhav-yb** [comment]
@shamanthchandra-yb Closing this as a one-off case for nemesis.
