### ISSUE TITLE
[YugabyteD] [QA] EAR enabled is not working correctly

### ISSUE THREAD

**Issue by zlareb1-yb** [yugabyte/yugabyte-db#15723]
### Description

Noticed that `testmultiregioncluster-default` is failing since 2.17.2.0-b23.

```
2023-01-17 09:32:35,347 receiver.py:82 INFO testmultiregioncluster-default Executed command --> cd /home/centos/ce_tests; ./yugabyte-*/bin/yugabyted configure encrypt_at_rest --base_dir=$HOME/node1 --enable
INFO:root:Output of enable_encrypt_at_rest is 
+------------------------------------------------------------------------+
|                               yugabyted                                |
+------------------------------------------------------------------------+
| Status                     : Encryption at rest is already disabled.   |
+------------------------------------------------------------------------+


2023-01-17 09:32:35,347 test_multi_region_cluster.py:117 INFO testmultiregioncluster-default Output of enable_encrypt_at_rest is 
+------------------------------------------------------------------------+
|                               yugabyted                                |
+------------------------------------------------------------------------+
| Status                     : Encryption at rest is already disabled.   |
+------------------------------------------------------------------------+


ERROR:root:ITEST FAILED testmultiregioncluster-default : RuntimeError('EAR is not enabled')
2023-01-17 09:32:35,347 test_base.py:170 ERROR testmultiregioncluster-default ITEST FAILED testmultiregioncluster-default : RuntimeError('EAR is not enabled')
INFO:root:Traceback (most recent call last):
  File "/var/lib/jenkins/code/internal-services/itest/src/test_base.py", line 166, in execute_steps
    step.call()
  File "/var/lib/jenkins/code/internal-services/itest/src/test_base.py", line 51, in call
    ret = self.function()
  File "/var/lib/jenkins/code/internal-services/itest/src/universe_tests/yugabyted/tests/test_multi_region_cluster.py", line 119, in configure_enable_and_reenable_ear
    raise RuntimeError("EAR is not enabled")
RuntimeError: EAR is not enabled
```

**Comment by gargsans-yb** [comment]
Code Fix Landed.
