### ISSUE TITLE
[DocDB] Invalid Index-table state after DROP INDEX

### ISSUE THREAD

**Issue by OlegLoginov** [yugabyte/yugabyte-db#15883]
Jira Link: [DB-5288](https://yugabyte.atlassian.net/browse/DB-5288)
### Description

When the Index-table is deleted the Index state in the Master process must be DELETING or DELETED.
Currently the moment can be postponed and the Index is still in the RUNNING state.
So, the Index State value state-machine is broken.

And we have a bug which hides the invalid behavior: in `IsDeleteTableInProgress` we have:
```
Status YBClient::Data::IsDeleteTableInProgress(YBClient* client, ...) {
...
  auto status = SyncLeaderMasterRpc(
      deadline, req, &resp, "IsDeleteTableDone",
      &master::MasterDdlProxy::IsDeleteTableDoneAsync);
  if (resp.has_error()) {
    if (resp.error().code() == MasterErrorPB::OBJECT_NOT_FOUND) {
      *delete_in_progress = false;
      return Status::OK();
```
`*delete_in_progress = false` means "DO NOT RETRY".
`Status::OK()` means "THE TABLE (or INDEX) was SUCCESSFULLY DELETED".
And that's wrong. The Index was NOT deleted.. It's even in RUNNING (alive) state.
So, the code hides the bad Index State.

Reproducer:
1. Comment the line (to stop hiding the wrong state):
```
Status YBClient::Data::IsDeleteTableInProgress(YBClient* client, ...) {
...
  if (resp.has_error()) {
    if (resp.error().code() == MasterErrorPB::OBJECT_NOT_FOUND) {
      *delete_in_progress = false;
//      return Status::OK();              <<<<<< COMMENT THIS LINE (return the ERROR status below)
    }
  }
  RETURN_NOT_OK(status);
```
2. Run the test: 
```
ybd --cxx-test cql-test --gtest_filter CqlTest.CheckStateAfterDrop -n 100
```

[DB-5288]: https://yugabyte.atlassian.net/browse/DB-5288?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by OlegLoginov** [comment]
The log:
```
I0130 17:30:32.318225 1428967 cql_test_util.cc:394] Execute query: drop index i1
I0130 17:30:32.319506 1429008 catalog_manager.cc:5722] Servicing DeleteTable request from 127.0.0.2:42201: table { table_name: "i1" namespace { name: "test" database_type: YQL_DATABASE_CQL } } is_index_table: true
I0130 17:30:32.320395 1429008 catalog_manager.cc:5563] MarkIndexInfoFromTableForDeletion table a6f439ebec4e4c7ba1bdc47a87131795 index 496039bd43be4f62b0d5a61276041ea8 multi_stage=1
W0130 17:30:32.325049 1429234 catalog_manager.cc:6242] Servicing IsDeleteTableDone request for table id 496039bd43be4f62b0d5a61276041ea8: NOT deleted in state RUNNING
I0130 17:30:32.325626 1429417 client_master_rpc.cc:76] 0x00005571c35e9820 -> IsDeleteTableDone: Failed, got resp error: Illegal state (yb/master/catalog_manager.cc:6244): The object was NOT deleted (master error 3)
W0130 17:30:32.325883 1429210 process_context.cc:185] SQL Error: Server Error. The object was NOT deleted (master error 3)
drop index i1
           ^^
1675089032.326 [WARN] (src/request_handler.cpp:455:void cass::RequestExecution::on_error_response(cass::Connection *, cass::ResponseMessage *)): Received server error 'Server Error. The object was NOT deleted (master error 3)
drop index i1
           ^^
 (ql error -2)' from host 127.0.0.2. Defuncting the connection...
1675089032.326 [ERROR] (src/pool.cpp:412:virtual void cass::Pool::on_close(cass::Connection *)): Closing established connection pool to host 127.0.0.2 because of the following error: 
I0130 17:30:32.326200 1428967 cql_test_util.cc:275] Cassandra error code: 33554432: Server Error. The object was NOT deleted (master error 3)
drop index i1
           ^^
 (ql error -2)
../../src/yb/integration-tests/cql-test.cc:949: Failure
Failed
Bad status: Runtime error (yb/integration-tests/cql_test_util.cc:276): Server Error. The object was NOT deleted (master error 3)
drop index i1
           ^^
 (ql error -2)




I0130 17:30:33.497859 1428967 cql-test.cc:1011] ListTables returned 6 tables
I0130 17:30:33.497877 1428967 cql-test.cc:1017] Running 'tbl' [id=a6f439ebec4e4c7ba1bdc47a87131795] state: ALTERING
I0130 17:30:33.497886 1428967 cql-test.cc:1017] Running 'i2' [id=10e12577f8674102bd4e0741b106929e] state: RUNNING
I0130 17:30:33.497936 1428967 cql-test.cc:1032] Deleted 'i1' [id=496039bd43be4f62b0d5a61276041ea8] state: RUNNING
../../src/yb/integration-tests/cql-test.cc:1078: Failure
Failed
Bad status: Illegal state (yb/integration-tests/cql-test.cc:1037): Bad deleted table state: RUNNING
I0130 17:30:33.498353 1429530 catalog_manager.cc:5895] Deleting table: i1, retained by: []
I0130 17:30:33.499768 1429530 catalog_manager.cc:10398] Deleting tablet 1548ebf972e34d0cba5c08e52ace37de
I0130 17:30:33.499893 1429530 catalog_manager.cc:10398] Deleting tablet 1801f7e5772d4ff2815115cee04d4195
I0130 17:30:33.500080 1429530 catalog_manager.cc:10398] Deleting tablet 2718ae0c82b84a008881165e0385a637
Test failure stack trace:
~/code/yugabyte-db4/build/debug-clang15-dynamic-ninja/../../src/yb/integration-tests/cql-test.cc:1076:     @     0x5571bd4ae575  yb::CqlTest_CheckStateAfterDrop_Test::TestBody()
```

**Comment by OlegLoginov** [comment]
For the second bug - hiding the wrong state - the WIP fix:  https://phabricator.dev.yugabyte.com/D22198

**Comment by OlegLoginov** [comment]
One more reproducer:    `ybd --java-test org.yb.cql.TestPartialIndex#testPartialIndexSelectionPolicy -n 100`
@druzac Please rerun it after the issue fixing.

Error:  `Servicing IsDeleteTableDone request for table id ...: NOT deleted in state RUNNING`
Log:
```
m2|pid3422495|:17255|http://127.44.235.243:25540 I0217 21:46:15.020802 3422579 catalog_manager.cc:5790] Servicing DeleteTable request from 127.82.118.73:33115: table { table_name: "idx" namespace { name: "cql_test_keyspace" database_type: YQL_DATABASE_CQL } } is_index_table: true
m2|pid3422495|:17255|http://127.44.235.243:25540 I0217 21:46:15.021855 3422579 catalog_manager.cc:5631] MarkIndexInfoFromTableForDeletion table ed5bb2116fc14ba6812a3f90b7b86986 index b11cd96992e74ae7a8cd41b4fef255fe multi_stage=1
m2|pid3422495|:17255|http://127.44.235.243:25540 W0217 21:46:15.033756 3423383 catalog_manager.cc:6321] Servicing IsDeleteTableDone request for table id b11cd96992e74ae7a8cd41b4fef255fe: NOT deleted in state RUNNING
ts3|pid3423192|:14019|http://127.82.118.73:19051 I0217 21:46:15.034438 3423591 client_master_rpc.cc:76] 0x0000561ed7842f20 -> IsDeleteTableDone: Failed, got resp error: Illegal state (yb/master/catalog_manager.cc:6323): The object was NOT deleted (master error 3)
```

**Comment by druzac** [comment]
I'm not seeing these errors on `org.yb.cql.TestPartialIndex#testPartialIndexSelectionPolicy`. Instead I see:
```
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 34.317 s <<< FAILURE! - in org.yb.cql.TestPartialIndex
testPartialIndexSelectionPolicy(org.yb.cql.TestPartialIndex)  Time elapsed: 33.579 s  <<< ERROR!
com.datastax.driver.core.exceptions.InvalidQueryException: 
Execution Error. The tablet is shutting down (tablet server error 12)
select h1,h2,r1,r2,v1,v2 from test_partial_index where r2 = 2 and v1 = NULL
^^^^^^
 (ql error -300)
	at org.yb.cql.TestPartialIndex.queryOutputToStringSet(TestPartialIndex.java:356)
	at org.yb.cql.TestPartialIndex.testPartialIndexSelectInternal(TestPartialIndex.java:1310)
	at org.yb.cql.TestPartialIndex.testPartialIndexSelectionPolicy(TestPartialIndex.java:1604)
Caused by: com.datastax.driver.core.exceptions.InvalidQueryException: 
Execution Error. The tablet is shutting down (tablet server error 12)
select h1,h2,r1,r2,v1,v2 from test_partial_index where r2 = 2 and v1 = NULL
^^^^^^
 (ql error -300)
```

**Comment by druzac** [comment]
3d7aa1d1073b46ed797376cda83dbcd124cbeb5d leaves the index state as is. The synchronous deletion path for YCQL indices with backfill enabled changes the permissions to kick off the async deletion tasks instead of changing the state of the index. There's concern that setting the index table to `DELETING` synchronously as we do for other table objects may cause issues if there's a master failover.

Instead that commit updates `CatalogManager::IsDeleteTableDone` to properly account for the deletion flow of YCQL indices with backfill enabled.
