### ISSUE TITLE
[YCQL] Flaky test org.yb.cql.TestIndex.testPreparedStatement

### ISSUE THREAD

**Issue by NatashaSerebryanaya** [yugabyte/yugabyte-db#15910]
Jira Link: [DB-5318](https://yugabyte.atlassian.net/browse/DB-5318)
### Description

The test org.yb.cql.TestIndex.testPreparedStatement fails a lot in asan a tsan builds, less in debug build:
https://detective.dev.yugabyte.com/stability/test?analyze_trends=true&class=org.yb.cql.TestIndex&name=testPreparedStatement

The error is always the same:
```
18:53:54.040 (Time-limited test) [INFO - org.yb.cql.BaseCQLTest.tearDownAfter(BaseCQLTest.java:267)] BaseCQLTest.tearDownAfter: finished attempting to drop tables and trying to close CQL session/client
18:53:54.043 (main) [ERROR - org.yb.BaseYBTest$1$2.logEventDetails(BaseYBTest.java:243)] YB Java test failed: class="org.yb.cql.TestIndex", method="testPreparedStatement"
java.lang.NullPointerException: null
	at org.yb.cql.TestIndex.assertRoutingVariables(TestIndex.java:823)
	at org.yb.cql.TestIndex.testPreparedStatement(TestIndex.java:876)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```
The full debug log can be found [here](https://storage.googleapis.com/test-results.yugabyte.com/jenkins/job/github-yugabyte-db-centos-master-clang15-debug/570/artifact/java/yb-cql/target/surefire-reports_org.yb.cql.TestIndex__testPreparedStatement/org.yb.cql.TestIndex-output.txt?GoogleAccessId=detective-service-acct%40yugabyte.iam.gserviceaccount.com&Expires=1675212244&Signature=SQVOIqyJqAjANg8KWajSZyOk0upOAEb12pR6yc%2F%2FG88Vqe%2F57M6yUDVELi7WfIKAJzHNIQWUYhG5i0o7ex0kkWFKnolRE9Ny%2BleiCYhR2XZFFggPIFZsHwc2Vr%2F5BJG6BSmCuxdR86gdNOoaxEwit0A3h9UYg0Jr3TWZCMyUVk7QzaJ2rl%2Fge0RToGMOTW54uWwiib%2BMDOHp95l1dAx4CrwjX08w0L8EWEIDWeY2Hx2FGhichO%2FkYDZqYDDaJL9YZXvxIzHbWMtJhOBuFUtlQzm3M0dd7hbx81dIJ%2Fb0BeZfAu%2Bfjphts2lA0%2F%2BpQjrpfZwMkwCO6MhD7%2BEDdL8fTQ%3D%3D)

[DB-5318]: https://yugabyte.atlassian.net/browse/DB-5318?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by OlegLoginov** [comment]
Crash point:
```
  private void assertRoutingVariables(String query,
                                      List<String> expectedVars,
                                      Object[] values,
                                      String expectedRow) {
    PreparedStatement stmt = session.prepare(query);
    int hashIndexes[] = stmt.getRoutingKeyIndexes();     <<<< RETURNS NULL

    if (expectedVars == null) {
      assertNull(hashIndexes);
    } else {
      List<String> actualVars = new Vector<String>();
      ColumnDefinitions vars = stmt.getVariables();
      for (int hashIndex : hashIndexes) {    <<<< CRASH WITH NullPointerException - hashIndexes == NULL
```

**Comment by OlegLoginov** [comment]
Failed block:
```
    // Select using index i5 covering c1.
    assertRoutingVariables("select h1, h2, r1, r2, c1, c2 from test_prepare where c2 = ?;",
                           Arrays.asList("i5.c2"),
                           new Object[] {"c"},
                           "Row[1, a, 2, b, 3, c]");
```
Reproducer:   `ybd --java-test org.yb.cql.TestIndex#testPreparedStatement -n 10`
Fail rate: ~1 / 3

**Comment by OlegLoginov** [comment]
The bug is in YCQL server code - some TS can select wrong execution path - via the main table, while an Index is expected for the execution - here TS2 and TS1 correctly selected `i5` index, selection is wrong on TS3:
```
21:45:04.370 (Time-limited test) [INFO - org.yb.cql.TestIndex.assertRoutingVariables(TestIndex.java:822)] !assertRoutingVariables query = select h1, h2, r1, r2, c1, c2 from test_prepare where c2 = ?;
ts3|pid3321549|:24369|http://127.28.229.89:19460 W0309 21:45:04.372165 3322304 statement_result.cc:135] ! stmt.hash_col_indices() sz=0
ts3|pid3321549|:24369|http://127.28.229.89:19460 W0309 21:45:04.372195 3322304 statement_result.cc:139] ! table_name_=cql_test_keyspace.test_prepare

<<<<  !!! cql_test_keyspace.test_prepare, expected "cql_test_keyspace.i5"

ts2|pid3321357|:10038|http://127.150.193.132:20404 W0309 21:45:04.380084 3322313 statement_result.cc:135] ! stmt.hash_col_indices() sz=1
ts2|pid3321357|:10038|http://127.150.193.132:20404 W0309 21:45:04.380112 3322313 statement_result.cc:136] ! stmt.hash_col_indices() [0]=0
ts2|pid3321357|:10038|http://127.150.193.132:20404 W0309 21:45:04.380122 3322313 statement_result.cc:139] ! table_name_=cql_test_keyspace.i5

ts1|pid3321339|:20305|http://127.27.214.73:26385 W0309 21:45:04.392053 3322298 statement_result.cc:135] ! stmt.hash_col_indices() sz=1
ts1|pid3321339|:20305|http://127.27.214.73:26385 W0309 21:45:04.392081 3322298 statement_result.cc:136] ! stmt.hash_col_indices() [0]=0
ts1|pid3321339|:20305|http://127.27.214.73:26385 W0309 21:45:04.392092 3322298 statement_result.cc:139] ! table_name_=cql_test_keyspace.i5

**Comment by OlegLoginov** [comment]
TS1 "see" only 4 indexes, while TS3 "see" all 5 indexes:
```
ts1|pid3362263|W0309 22:06:58.996646 3363278 pt_select.cc:806] >>> Selectivity: index_id  is_local true prefix_length 0 single_key_read false full_table_scan true ends_with_range false covers_fully true predicate_len 0
ts1|pid3362263|W0309 22:06:58.996685 3363278 pt_select.cc:806] >>> Selectivity: index_id 2836e131006b4e0a854b91f6e6a59a8e is_local false prefix_length 0 single_key_read false full_table_scan true ends_with_range false covers_fully false predicate_len 0
ts1|pid3362263|W0309 22:06:58.996699 3363278 pt_select.cc:806] >>> Selectivity: index_id a4a7fb424a2a44a0b47bf82bcbc946b8 is_local false prefix_length 0 single_key_read false full_table_scan true ends_with_range false covers_fully false predicate_len 0
ts1|pid3362263|W0309 22:06:58.996712 3363278 pt_select.cc:806] >>> Selectivity: index_id 3c886b89e3c345f38e518b1d4c4a4b86 is_local false prefix_length 0 single_key_read false full_table_scan true ends_with_range false covers_fully false predicate_len 0
ts1|pid3362263|W0309 22:06:58.996724 3363278 pt_select.cc:806] >>> Selectivity: index_id dbef8e615ac44100be0447f845715702 is_local false prefix_length 0 single_key_read false full_table_scan true ends_with_range false covers_fully false predicate_len 0

ts1|pid3362263|W0309 22:06:58.996737 3363278 pt_select.cc:812] >>> Selected = Selectivity: index_id  is_local true prefix_length 0 single_key_read false full_table_scan true ends_with_range false covers_fully true predicate_len 0
ts1|pid3362263|W0309 22:06:58.996748 3363278 pt_select.cc:823] >>> selectivity DONE 
ts1|pid3362263|W0309 22:06:58.996824 3363278 statement_result.cc:135] ! stmt.hash_col_indices() sz=0
ts1|pid3362263|W0309 22:06:58.996840 3363278 statement_result.cc:139] ! table_name_=cql_test_keyspace.test_prepare

ts3|pid3362577|W0309 22:06:59.000463 3362953 pt_select.cc:806] >>> Selectivity: index_id 061e5e2f63e94a8eb59d53f58b019393 is_local false prefix_length 1 single_key_read false full_table_scan false ends_with_range false covers_fully true predicate_len 0
ts3|pid3362577|W0309 22:06:59.000512 3362953 pt_select.cc:806] >>> Selectivity: index_id  is_local true prefix_length 0 single_key_read false full_table_scan true ends_with_range false covers_fully true predicate_len 0
ts3|pid3362577|W0309 22:06:59.000526 3362953 pt_select.cc:806] >>> Selectivity: index_id 2836e131006b4e0a854b91f6e6a59a8e is_local false prefix_length 0 single_key_read false full_table_scan true ends_with_range false covers_fully false predicate_len 0
ts3|pid3362577|W0309 22:06:59.000538 3362953 pt_select.cc:806] >>> Selectivity: index_id a4a7fb424a2a44a0b47bf82bcbc946b8 is_local false prefix_length 0 single_key_read false full_table_scan true ends_with_range false covers_fully false predicate_len 0
ts3|pid3362577|W0309 22:06:59.000550 3362953 pt_select.cc:806] >>> Selectivity: index_id 3c886b89e3c345f38e518b1d4c4a4b86 is_local false prefix_length 0 single_key_read false full_table_scan true ends_with_range false covers_fully false predicate_len 0
ts3|pid3362577|W0309 22:06:59.000560 3362953 pt_select.cc:806] >>> Selectivity: index_id dbef8e615ac44100be0447f845715702 is_local false prefix_length 0 single_key_read false full_table_scan true ends_with_range false covers_fully false predicate_len 0

ts3|pid3362577|W0309 22:06:59.000571 3362953 pt_select.cc:812] >>> Selected = Selectivity: index_id 061e5e2f63e94a8eb59d53f58b019393 is_local false prefix_length 1 single_key_read false full_table_scan false ends_with_range false covers_fully true predicate_len 0
ts3|pid3362577|W0309 22:06:59.000582 3362953 pt_select.cc:823] >>> selectivity DONE 
ts3|pid3362577|W0309 22:06:59.013798 3362953 statement_result.cc:135] ! stmt.hash_col_indices() sz=1
ts3|pid3362577|W0309 22:06:59.013832 3362953 statement_result.cc:136] ! stmt.hash_col_indices() [0]=0
ts3|pid3362577|W0309 22:06:59.013845 3362953 statement_result.cc:139] ! table_name_=cql_test_keyspace.i5
```

**Comment by OlegLoginov** [comment]
"Bad" TS uses old/stale schema version (TS2: schema-version=19, TS1: schema-version=20):
```
ts2|22:49:18.036481 pt_dml.cc:175] ! TBL: 85be52be25b143079ac7ac56b647a70a cql_test_keyspace.test_prepare  schema-version=19
ts2|22:49:18.036744 pt_select.cc:806] >>> Selectivity: index_id  is_local true prefix_length 0 single_key_read false full_table_scan true ends_with_range false covers_fully true predicate_len 0
ts2|22:49:18.036765 pt_select.cc:806] >>> Selectivity: index_id 32ca5852266f499f97e4f67450977f9c is_local false prefix_length 0 single_key_read false full_table_scan true ends_with_range false covers_fully false predicate_len 0
ts2|22:49:18.036774 pt_select.cc:806] >>> Selectivity: index_id 4b7d4dad475f40a38f6cce733687d14f is_local false prefix_length 0 single_key_read false full_table_scan true ends_with_range false covers_fully false predicate_len 0
ts2|22:49:18.036782 pt_select.cc:806] >>> Selectivity: index_id 9895c426891d4cb2b9af81b4635943de is_local false prefix_length 0 single_key_read false full_table_scan true ends_with_range false covers_fully false predicate_len 0
ts2|22:49:18.036788 pt_select.cc:806] >>> Selectivity: index_id f15376ff2fe44405a885265317fad5b0 is_local false prefix_length 0 single_key_read false full_table_scan true ends_with_range false covers_fully false predicate_len 0
ts2|22:49:18.036794 pt_select.cc:812] >>> Selected = Selectivity: index_id  is_local true prefix_length 0 single_key_read false full_table_scan true ends_with_range false covers_fully true predicate_len 0
ts2|22:49:18.036803 pt_select.cc:823] >>> selectivity DONE 
ts2|22:49:18.036852 statement_result.cc:135] ! stmt.hash_col_indices() sz=0
ts2|22:49:18.036864 statement_result.cc:139] ! table_name_=cql_test_keyspace.test_prepare

ts1|22:49:18.038005 pt_dml.cc:175] ! TBL: 85be52be25b143079ac7ac56b647a70a cql_test_keyspace.test_prepare  schema-version=20
ts1|22:49:18.038460 pt_select.cc:806] >>> Selectivity: index_id 83db663e94c540c3946da7270b89d723 is_local false prefix_length 1 single_key_read false full_table_scan false ends_with_range false covers_fully true predicate_len 0
ts1|22:49:18.038486 pt_select.cc:806] >>> Selectivity: index_id  is_local true prefix_length 0 single_key_read false full_table_scan true ends_with_range false covers_fully true predicate_len 0
ts1|22:49:18.038501 pt_select.cc:806] >>> Selectivity: index_id 32ca5852266f499f97e4f67450977f9c is_local false prefix_length 0 single_key_read false full_table_scan true ends_with_range false covers_fully false predicate_len 0
ts1|22:49:18.038512 pt_select.cc:806] >>> Selectivity: index_id 4b7d4dad475f40a38f6cce733687d14f is_local false prefix_length 0 single_key_read false full_table_scan true ends_with_range false covers_fully false predicate_len 0
ts1|22:49:18.038525 pt_select.cc:806] >>> Selectivity: index_id 9895c426891d4cb2b9af81b4635943de is_local false prefix_length 0 single_key_read false full_table_scan true ends_with_range false covers_fully false predicate_len 0
ts1|22:49:18.038542 pt_select.cc:806] >>> Selectivity: index_id f15376ff2fe44405a885265317fad5b0 is_local false prefix_length 0 single_key_read false full_table_scan true ends_with_range false covers_fully false predicate_len 0
ts1|22:49:18.038554 pt_select.cc:812] >>> Selected = Selectivity: index_id 83db663e94c540c3946da7270b89d723 is_local false prefix_length 1 single_key_read false full_table_scan false ends_with_range false covers_fully true predicate_len 0
ts1|22:49:18.038566 pt_select.cc:823] >>> selectivity DONE 
ts1|22:49:18.047420 statement_result.cc:135] ! stmt.hash_col_indices() sz=1
ts1|22:49:18.047444 statement_result.cc:136] ! stmt.hash_col_indices() [0]=0
ts1|22:49:18.047456 statement_result.cc:139] ! table_name_=cql_test_keyspace.i5
```
That's not a problem, because when the SELECT will be executed - stale schema will be detected by the tablet (in READ RPC handling). And the query will be re-prepared.
The test is invalid - it should be fixed (to handle the case when the TS has stale schema).

**Comment by OlegLoginov** [comment]
Because the fix includes only changes in the test - the fix is not planned for backporting.
