### ISSUE TITLE
[CDC + Snapshot + Tablet Splitting] Too many errors while trying to stream the snapshot, all 10 retries failed. 

### ISSUE THREAD

**Issue by shamanthchandra-yb** [yugabyte/yugabyte-db#15951]
Jira Link: [DB-5362](https://yugabyte.atlassian.net/browse/DB-5362)
### Description

```
2023-02-02 02:09:14,962 ERROR  YugabyteDB|db_cdc|snapshot|2  Too many errors while trying to stream the snapshot, all 10 retries failed.   [io.debezium.connector.yugabytedb.YugabyteDBSnapshotChangeEventSource]
 7177 2023-02-02 02:09:14,962 INFO   YugabyteDB|db_cdc|snapshot|2  Tablets in the failed task:   [io.debezium.connector.yugabytedb.YugabyteDBSnapshotChangeEventSource]
 7178 2023-02-02 02:09:14,962 INFO   YugabyteDB|db_cdc|snapshot|2  Tablet: 743d3ada09ec4fae98e3303597bb0c21 table: test_cdc_81c12f(00004005000030008000000000004006)   [io.debezium.connector.yugabytedb.YugabyteDBSnapshotChangeEventSource]
 7179 2023-02-02 02:09:14,962 INFO   YugabyteDB|db_cdc|snapshot|2  Tablet: 78442eb5a7ff4c0fb4824dcdd32066a5 table: test_cdc_81c12f(00004005000030008000000000004006)   [io.debezium.connector.yugabytedb.YugabyteDBSnapshotChangeEventSource]
 7180 2023-02-02 02:09:14,962 INFO   YugabyteDB|db_cdc|snapshot|2  Snapshot - Final stage   [io.debezium.connector.yugabytedb.YugabyteDBSnapshotChangeEventSource]
 7181 2023-02-02 02:09:14,962 ERROR  YugabyteDB|db_cdc|snapshot|2  Producer failure   [io.debezium.pipeline.ErrorHandler]
 7182 io.debezium.DebeziumException: org.yb.client.NonRecoverableException: Too many attempts: YRpc(method=GetChanges, service=yb.cdc.CDCService, tablet=null, attempt=100, maxAttempts=100, maxTimeoutMs=600000, elapsedTimeMs=30)
 7183         at io.debezium.connector.yugabytedb.YugabyteDBSnapshotChangeEventSource.execute(YugabyteDBSnapshotChangeEventSource.java:136)
 7184         at io.debezium.connector.yugabytedb.YugabyteDBSnapshotChangeEventSource.execute(YugabyteDBSnapshotChangeEventSource.java:50)
 7185         at io.debezium.pipeline.ChangeEventSourceCoordinator.doSnapshot(ChangeEventSourceCoordinator.java:155)
 7186         at io.debezium.connector.yugabytedb.YugabyteDBChangeEventSourceCoordinator.executeChangeEventSources(YugabyteDBChangeEventSourceCoordinator.java:105)
 7187         at io.debezium.pipeline.ChangeEventSourceCoordinator.lambda$start$0(ChangeEventSourceCoordinator.java:109)
 7188         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
 7189         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
 7190         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
 7191         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
 7192         at java.base/java.lang.Thread.run(Thread.java:829)
 7193 Caused by: org.yb.client.NonRecoverableException: Too many attempts: YRpc(method=GetChanges, service=yb.cdc.CDCService, tablet=null, attempt=100, maxAttempts=100, maxTimeoutMs=600000, elapsedTimeMs=30)
 7194         at org.yb.client.AsyncYBClient.tooManyAttemptsOrTimeout(AsyncYBClient.java:2026)
 7195         at org.yb.client.AsyncYBClient.sendRpcToTablet(AsyncYBClient.java:1641)
 7196         at org.yb.client.AsyncYBClient$RetryRpcCB.call(AsyncYBClient.java:1736)
 7197         at org.yb.client.AsyncYBClient$RetryRpcCB.call(AsyncYBClient.java:1730)
 7198         at com.stumbleupon.async.Deferred.doCall(Deferred.java:1280)
 7199         at com.stumbleupon.async.Deferred.runCallbacks(Deferred.java:1259)
 7200         at com.stumbleupon.async.Deferred.callback(Deferred.java:1002)
 7201         at org.yb.client.YRpc.handleCallback(YRpc.java:184)
 7202         at org.yb.client.YRpc.callback(YRpc.java:197)
 7203         at org.yb.client.TabletClient.decode(TabletClient.java:451)
 7204         at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
 7205         at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
 7206         at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
 7207         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
 7208         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
 7209         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
 7210         at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
 7211         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
 7212         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
 7213         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
 7214         at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
 7215         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
 7216         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
 7217         at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
 7218         at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
 7219         at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
 7220         at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
 7221         at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
 7222         at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
 7223         at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
 7224         at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
 7225         ... 3 more
```
[DockerLogsAndTestLogs.zip](https://github.com/yugabyte/yugabyte-db/files/10570412/DockerLogsAndTestLogs.zip)

[Universe_logs.zip](https://github.com/yugabyte/yugabyte-db/files/10570418/Universe_logs.zip)

[DB-5362]: https://yugabyte.atlassian.net/browse/DB-5362?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by adithya-yb** [comment]
Closing since issue is solved. 
Was tracked through: https://github.com/yugabyte/debezium-connector-yugabytedb/commit/579745226eff8e76cfc45091fab335dacd1f9691
