### ISSUE TITLE
[YSQL][Unit Test] Flaky Test org.yb.pgsql.TestLDAPAuth.searchBindModeWithSearchWithEnvVarDefined

### ISSUE THREAD

**Issue by rjalan-yb** [yugabyte/yugabyte-db#15986]
Jira Link: [DB-5392](https://yugabyte.atlassian.net/browse/DB-5392)
### Description

The testcase org.yb.pgsql.TestLDAPAuth.searchBindModeWithSearchWithEnvVarDefined has been very flaky on multiple builds and fails with error:

05:10:06.781 (Time-limited test) [ERROR - org.yb.AssertionWrappers.logError(AssertionWrappers.java:40)] Assertion error:
java.lang.AssertionError: Unexpected Error Message. Got: 'FATAL: the database system is shutting down', Expected to contain: 'Check that the hostname and port are correct'

```
ts3|pid19022|:23781 I0206 05:10:06.717423 19169 webserver.cc:299] Webserver listen spec is 127.46.102.141:28022
ts3|pid19022|:23781 I0206 05:10:06.717648 19169 webserver.cc:415] Webserver started. Bound to: http://127.46.102.141:28022/
ts3|pid19022|:23781 2023-02-06 05:10:06.720 UTC [19166] LOG:  database system is ready to accept connections
05:10:06.775 (Time-limited test) [ERROR - org.yb.pgsql.BasePgSQLTest$ConnectionBuilder.connect(BasePgSQLTest.java:2351)] Exception while trying to create connection (after 1 attempts): FATAL: the database system is shutting down
05:10:06.781 (Time-limited test) [ERROR - org.yb.AssertionWrappers.logError(AssertionWrappers.java:40)] Assertion error:
java.lang.AssertionError: Unexpected Error Message. Got: 'FATAL: the database system is shutting down', Expected to contain: 'Check that the hostname and port are correct'
	at org.junit.Assert.fail(Assert.java:88)
	at org.yb.AssertionWrappers.lambda$fail$4(AssertionWrappers.java:104)
	at org.yb.AssertionWrappers.wrapAssertion(AssertionWrappers.java:45)
	at org.yb.AssertionWrappers.fail(AssertionWrappers.java:104)
	at org.yb.pgsql.TestLDAPAuth.searchBindModeWithSearchWithEnvVarDefined(TestLDAPAuth.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
05:10:06.782 (Time-limited test) [INFO - org.yb.pgsql.BasePgSQLTest.cleanUpAfter(BasePgSQLTest.java:411)] Cleaning up after searchBindModeWithSearchWithEnvVarDefined

```

Complete logs: https://gist.github.com/rjalan-yb/5f1a02711e246120ec62bb1ada4a6a58

[DB-5392]: https://yugabyte.atlassian.net/browse/DB-5392?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by hari90** [comment]
Test is not failing
