### ISSUE TITLE
[YSQL] Regression in query against information_schema.attributes

### ISSUE THREAD

**Issue by lukaseder** [yugabyte/yugabyte-db#16081]
Jira Link: [DB-5469](https://yugabyte.atlassian.net/browse/DB-5469)
### Description

I'm using Docker to run YugabyteDB:

```
docker pull yugabytedb/yugabyte
docker run -d --name YUGABYTEDB -p7000:7000 -p9000:9000 -p5433:5433 -p9042:9042 yugabytedb/yugabyte:latest bin/yugabyted start --daemon=false
```

I've upgraded my YugabyteDB instance to:

```
PostgreSQL 11.2-YB-2.17.1.0-b0 on x86_64-pc-linux-gnu, compiled by clang version 15.0.3 (https://github.com/yugabyte/llvm-project.git 0b8d1183745fd3998d8beffeec8cbe99c1b20529), 64-bit
```

(Not sure exactly what version I had before, I'm using the `latest` tag on https://hub.docker.com/r/yugabytedb/yugabyte). 

Now I'm getting a regression on this query, which worked before:

```sql
select distinct udt_schema, udt_name
from information_schema.attributes
where udt_schema = 'public'
order by udt_schema, udt_name;
```

The query produces this error:

> SQL Error [XX000]: ERROR: Query error: Cannot decode value type kGroupEnd from the key encoding format: "!"

Removing `distinct` and/or `order by` works around the problem

[DB-5469]: https://yugabyte.atlassian.net/browse/DB-5469?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by lukaseder** [comment]
Might also be a wire protocol compatibility issue with pgjdbc. The stack trace I'm getting in Dbeaver is this:

```
org.jkiss.dbeaver.model.sql.DBSQLException: SQL Error [XX000]: ERROR: Query error: Cannot decode value type kGroupEnd from the key encoding format: "!"
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:133)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:577)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$1(SQLQueryJob.java:486)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:172)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:493)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:894)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:3644)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:123)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:172)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:121)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:4937)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.postgresql.util.PSQLException: ERROR: Query error: Cannot decode value type kGroupEnd from the key encoding format: "!"
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:496)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:413)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:333)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:319)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:295)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:290)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:329)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.lambda$0(JDBCStatementImpl.java:131)
	at org.jkiss.dbeaver.utils.SecurityManagerUtils.wrapDriverActions(SecurityManagerUtils.java:94)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)
	... 12 more
```

**Comment by lukaseder** [comment]
Another workaround is to use `GROUP BY`, rather than `DISTINCT`:

```sql
select udt_schema, udt_name
from information_schema.attributes
where udt_schema = 'public'
group by udt_schema, udt_name
order by udt_schema, udt_name;
```

**Comment by lukaseder** [comment]
Or, in this particular case, the `information_schema.user_defined_types` view could be used, of course:

```sql
select user_defined_type_schema, user_defined_type_name 
from information_schema.user_defined_types 
where user_defined_type_schema = 'public'
order by user_defined_type_schema, user_defined_type_name;
```

**Comment by ddorian** [comment]
Hi @lukaseder 

Thank you for reporting this bug. I can reproduce this with a fresh 2.17.1.0 install. 

```
./bin/ysqlsh
ysqlsh (11.2-YB-2.17.1.0-b0)
Type "help" for help.

yugabyte=# select distinct udt_schema, udt_name
yugabyte-# from information_schema.attributes
yugabyte-# where udt_schema = 'public'
yugabyte-# order by udt_schema, udt_name;
ERROR:  Query error: Cannot decode value type kGroupEnd from the key encoding format: "!"
yugabyte=# 
```

**Comment by ddorian** [comment]
It was actually closed as duplicate of https://github.com/yugabyte/yugabyte-db/issues/16038.
It is planned to be fixed, the jira comment is incorrect.
