### ISSUE TITLE
[DocDB] Indirect memory leaks in PgIndexBackfillTest.PgStatProgressCreateIndexCheckIndexTypes

### ISSUE THREAD

**Issue by NatashaSerebryanaya** [yugabyte/yugabyte-db#16090]
Jira Link: [DB-5484](https://yugabyte.atlassian.net/browse/DB-5484)
### Description

There is a bunch of indirect leaks in PgIndexBackfillTest.PgStatProgressCreateIndexCheckIndexTypes:
https://detective.dev.yugabyte.com/?commits=8f446576ed9200989f68c9fbf1df352d498c3afa

The full log is [here](https://storage.googleapis.com/test-results.yugabyte.com/jenkins/job/github-yugabyte-db-alma8-master-clang15-asan/413/artifact/build/asan-clang15-dynamic-ninja/yb-test-logs/tests-pgwrapper__pg_index_backfill-test/PgIndexBackfillTest_DropAfterFail.log?GoogleAccessId=detective-service-acct%40yugabyte.iam.gserviceaccount.com&Expires=1676311430&Signature=mVeSqhcBthQib4uYIhcAFmDsNyXBorWuhT4IhD4UJXrrHZLmuSbfIHT7s0VztQR5tHmremEQ5u8Qeun27N1IkPASi3P76PFWA2fzaSB78ZS0SNr6TpXqoj25DTwUotlnUssY6EWktIrnAOwiZAvMa9nEjFWMhrsYa%2FkgXge%2BQkdlL8GK6Y4JrUKmDauFH4jgX46Ta8kYekGRjdTbcaXnGjmiQzwyKdoBNAbkaPkjMVZR9TU7I9BCZGJx1kFo7MyAzqdsSBZObgmZae20BZDSPFExfGaiJTE2iYx9t8vrqLmdIaQ7R6ywQAWWkBlG5Hk6mVV8R4Qz55OldWvi5kNNGA%3D%3D).

```
[m-1] =================================================================
[m-1] ==62243==ERROR: LeakSanitizer: detected memory leaks
[m-1] 
[m-1] Indirect leak of 1600 byte(s) in 1 object(s) allocated from:
[m-1]     #0 0x5582543d2ead in operator new(unsigned long) /opt/yb-build/llvm/yb-llvm-v15.0.3-yb-1-1667030060-0b8d1183-almalinux8-x86_64-build/src/llvm-project/compiler-rt/lib/asan/asan_new_delete.cpp:95:3
[m-1]     #1 0x7fbd2e5a55f3 in void* std::__libcpp_operator_new[abi:v15003]<unsigned long>(unsigned long) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20221115221821-32d6b89b02-almalinux8-x86_64-clang15/installed/asan/libcxx/include/c++/v1/new:246:10
[m-1]     #2 0x7fbd2e5a55f3 in std::__libcpp_allocate[abi:v15003](unsigned long, unsigned long) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20221115221821-32d6b89b02-almalinux8-x86_64-clang15/installed/asan/libcxx/include/c++/v1/new:272:10
[m-1]     #3 0x7fbd2e5a55f3 in std::allocator<std::shared_ptr<yb::server::MonitoredTask>>::allocate[abi:v15003](unsigned long) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20221115221821-32d6b89b02-almalinux8-x86_64-clang15/installed/asan/libcxx/include/c++/v1/__memory/allocator.h:112:38
[m-1]     #4 0x7fbd2e5a55f3 in boost::circular_buffer<std::shared_ptr<yb::server::MonitoredTask>, std::allocator<std::shared_ptr<yb::server::MonitoredTask>>>::allocate(unsigned long) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20221115221821-32d6b89b02-almalinux8-x86_64-clang15/installed/asan/include/boost/circular_buffer/base.hpp:2396:39
[m-1]     #5 0x7fbd2e5a4874 in boost::circular_buffer<std::shared_ptr<yb::server::MonitoredTask>, std::allocator<std::shared_ptr<yb::server::MonitoredTask>>>::initialize_buffer(unsigned long) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20221115221821-32d6b89b02-almalinux8-x86_64-clang15/installed/asan/include/boost/circular_buffer/base.hpp:2494:18
[m-1]     #6 0x7fbd2e5a4874 in boost::circular_buffer<std::shared_ptr<yb::server::MonitoredTask>, std::allocator<std::shared_ptr<yb::server::MonitoredTask>>>::circular_buffer(unsigned long, std::allocator<std::shared_ptr<yb::server::MonitoredTask>> const&) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20221115221821-32d6b89b02-almalinux8-x86_64-clang15/installed/asan/include/boost/circular_buffer/base.hpp:1039:9
[m-1]     #7 0x7fbd2e5a36a1 in yb::master::TasksTracker::TasksTracker(yb::StronglyTypedBool<yb::master::IsUserInitiated_Tag>) ${BUILD_ROOT}/../../src/yb/master/tasks_tracker.cc:41:7
[m-1]     #8 0x7fbd2dfcd782 in yb::master::CatalogManager::CatalogManager(yb::master::Master*) ${BUILD_ROOT}/../../src/yb/master/catalog_manager.cc:890:26
[m-1]     #9 0x7fbd2e3558c8 in yb::master::enterprise::CatalogManager::CatalogManager(yb::master::Master*) ${BUILD_ROOT}/../../ent/src/yb/master/catalog_manager.h:33:9
[m-1]     #10 0x7fbd2e346f86 in yb::master::Master::Master(yb::master::MasterOptions const&) ${BUILD_ROOT}/../../src/yb/master/master.cc:155:28
[m-1]     #11 0x7fbd2e7dc04d in yb::master::enterprise::Master::Master(yb::master::MasterOptions const&) ${BUILD_ROOT}/../../ent/src/yb/master/master_ent.cc:39:45
[m-1]     #12 0x5582543d6341 in yb::master::MasterMain(int, char**) ${BUILD_ROOT}/../../src/yb/master/master_main.cc:133:22
[m-1]     #13 0x5582543d6341 in main ${BUILD_ROOT}/../../src/yb/master/master_main.cc:191:12
[m-1]     #14 0x7fbd1b47ed84 in __libc_start_main (/lib64/libc.so.6+0x3ad84) (BuildId: d18afae5244bc9c85026bd7d64b276d51b452d93)
[m-1] 
[m-1] Objects leaked above:
[m-1] 0x61b000003880 (1600 bytes)
...
[m-1] SUMMARY: AddressSanitizer: 11904 byte(s) leaked in 145 allocation(s).


[DB-5484]: https://yugabyte.atlassian.net/browse/DB-5484?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by NatashaSerebryanaya** [comment]
Duplicate of https://github.com/yugabyte/yugabyte-db/issues/16064
