### ISSUE TITLE
[yugabyted] `yugabyted configure data_placement` not working with cluster when nodes were started with DNS name as `--advertise_address`

### ISSUE THREAD

**Issue by gargsans-yb** [yugabyte/yugabyte-db#16245]
Jira Link: [DB-5670](https://yugabyte.atlassian.net/browse/DB-5670)
### Description

When a cluster was started with nodes' `--advertise_adddress` as their DNS names, the configure step is giving an error.

Steps to replicate: 

On 3 different VMs:

VM1:
```
[gargsans@dev-sgarg-gcp1 bin]$ ./yugabyted start --advertise_address=dev-sgarg-gcp1.us-west1-b.c.yugabyte.internal --cloud_location=gcp.us-west1.us-west-1b
Starting yugabyted...
✅ System checks
✅ YugabyteDB Started                  
✅ UI ready         
✅ Data placement constraint successfully verified                 

⚠ WARNINGS:
- Cluster started in an insecure mode without authentication and encryption enabled. For non-production use only, not to be used without firewalls blocking the internet traffic.


+----------------------------------------------------------------------------------------------------------+
|                                                yugabyted                                                 |
+----------------------------------------------------------------------------------------------------------+
| Status              : Running.                                                                           |
| Replication Factor  : 1                                                                                  |
| YugabyteDB UI       : http://dev-sgarg-gcp1.us-west1-b.c.yugabyte.internal:15433                         |
| JDBC                : jdbc:postgresql://dev-sgarg-gcp1.us-west1-b.c.yugabyte.internal:5433/yugabyte?user=yugabyte&password=yugabyte |
| YSQL                : bin/ysqlsh -h dev-sgarg-gcp1.us-west1-b.c.yugabyte.internal  -U yugabyte -d yugabyte |
| YCQL                : bin/ycqlsh dev-sgarg-gcp1.us-west1-b.c.yugabyte.internal 9042 -u cassandra         |
| Data Dir            : /home/gargsans/var/data                                                            |
| Log Dir             : /home/gargsans/var/logs                                                            |
| Universe UUID       : 2c03091b-d18c-4fda-a181-58e936cd2c7b                                               |
+----------------------------------------------------------------------------------------------------------+
🚀 YugabyteDB started successfully! To load a sample dataset, try 'yugabyted demo'.
🎉 Join us on Slack at https://www.yugabyte.com/slack
👕 Claim your free t-shirt at https://www.yugabyte.com/community-rewards/
```

VM2:
```
[gargsans@dev-sgarg-gcp2 bin]$ ./yugabyted start --advertise_address=dev-sgarg-gcp2.us-west1-b.c.yugabyte.internal --join=dev-sgarg-gcp1.us-west1-b.c.yugabyte.internal --cloud_location=gcp.us-west1.us-west-1a
Starting yugabyted...
✅ System checks
✅ YugabyteDB Started                  
✅ Node joined a running cluster with UUID 2c03091b-d18c-4fda-a181-58e936cd2c7b
✅ UI ready         
✅ Data placement constraint successfully verified                 

⚠ WARNINGS:
- Cluster started in an insecure mode without authentication and encryption enabled. For non-production use only, not to be used without firewalls blocking the internet traffic.


+----------------------------------------------------------------------------------------------------------+
|                                                yugabyted                                                 |
+----------------------------------------------------------------------------------------------------------+
| Status              : Running.                                                                           |
| Replication Factor  : 1                                                                                  |
| YugabyteDB UI       : http://dev-sgarg-gcp2.us-west1-b.c.yugabyte.internal:15433                         |
| JDBC                : jdbc:postgresql://dev-sgarg-gcp2.us-west1-b.c.yugabyte.internal:5433/yugabyte?user=yugabyte&password=yugabyte |
| YSQL                : bin/ysqlsh -h dev-sgarg-gcp2.us-west1-b.c.yugabyte.internal  -U yugabyte -d yugabyte |
| YCQL                : bin/ycqlsh dev-sgarg-gcp2.us-west1-b.c.yugabyte.internal 9042 -u cassandra         |
| Data Dir            : /home/gargsans/var/data                                                            |
| Log Dir             : /home/gargsans/var/logs                                                            |
| Universe UUID       : 2c03091b-d18c-4fda-a181-58e936cd2c7b                                               |
+----------------------------------------------------------------------------------------------------------+
🚀 YugabyteDB started successfully! To load a sample dataset, try 'yugabyted demo'.
🎉 Join us on Slack at https://www.yugabyte.com/slack
👕 Claim your free t-shirt at https://www.yugabyte.com/community-rewards/
```

VM3:
```
[gargsans@dev-sgarg-gcp3 bin]$ ./yugabyted start --advertise_address=dev-sgarg-gcp3.us-west1-a.c.yugabyte.internal --join=dev-sgarg-gcp1.us-west1-b.c.yugabyte.internal --cloud_location=gcp.us-west1.us-west-1c
Starting yugabyted...
✅ System checks
✅ YugabyteDB Started                  
✅ Node joined a running cluster with UUID 2c03091b-d18c-4fda-a181-58e936cd2c7b
✅ UI ready         
✅ Data placement constraint successfully verified                 

⚠ WARNINGS:
- Cluster started in an insecure mode without authentication and encryption enabled. For non-production use only, not to be used without firewalls blocking the internet traffic.


+----------------------------------------------------------------------------------------------------------+
|                                                yugabyted                                                 |
+----------------------------------------------------------------------------------------------------------+
| Status              : Running.                                                                           |
| Replication Factor  : 3                                                                                  |
| YugabyteDB UI       : http://dev-sgarg-gcp3.us-west1-a.c.yugabyte.internal:15433                         |
| JDBC                : jdbc:postgresql://dev-sgarg-gcp3.us-west1-a.c.yugabyte.internal:5433/yugabyte?user=yugabyte&password=yugabyte |
| YSQL                : bin/ysqlsh -h dev-sgarg-gcp3.us-west1-a.c.yugabyte.internal  -U yugabyte -d yugabyte |
| YCQL                : bin/ycqlsh dev-sgarg-gcp3.us-west1-a.c.yugabyte.internal 9042 -u cassandra         |
| Data Dir            : /home/gargsans/var/data                                                            |
| Log Dir             : /home/gargsans/var/logs                                                            |
| Universe UUID       : 2c03091b-d18c-4fda-a181-58e936cd2c7b                                               |
+----------------------------------------------------------------------------------------------------------+
🚀 YugabyteDB started successfully! To load a sample dataset, try 'yugabyted demo'.
🎉 Join us on Slack at https://www.yugabyte.com/slack
👕 Claim your free t-shirt at https://www.yugabyte.com/community-rewards/
```

VM2:
```
[gargsans@dev-sgarg-gcp2 bin]$ ./yugabyted configure data_placement --fault_tolerance=zone
yugabyted crashed. For troubleshooting, contact us on https://www.yugabyte.com/slack or check our FAQ at https://docs.yugabyte.com/latest/faq/
Traceback (most recent call last):
  File "./yugabyted", line 3472, in run
    args.func()
  File "./yugabyted", line 658, in configure_data_placement
    leader_master, placement_locations, rf_value)
  File "./yugabyted", line 2070, in get_new_valid_masters
    master_locations[leader_master])
KeyError: u'dev-sgarg-gcp1.us-west1-b.c.yugabyte.internal'

For more information, check the logs in /home/gargsans/var/logs
```

[DB-5670]: https://yugabyte.atlassian.net/browse/DB-5670?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by gargsans-yb** [comment]
Code changes Landed.
