### ISSUE TITLE
[CDCSDK] Out of memory error with packed columns + CDC (enabled on xcluster source)

### ISSUE THREAD

**Issue by shamanthchandra-yb** [yugabyte/yugabyte-db#16256]
Jira Link: [DB-5681](https://yugabyte.atlassian.net/browse/DB-5681)
### Description

http://stress.dev.yugabyte.com/stress_test/26d285e5-5570-463c-a107-e17b4e37d17a

![Profile](https://user-images.githubusercontent.com/109518123/221798523-b4ad7ac7-fe8c-417e-956a-95b96261877f.png)

[AllLogs.zip](https://github.com/yugabyte/yugabyte-db/files/10848120/AllLogs.zip)

```
 99062 2023-02-26 20:51:18,242 INFO   YugabyteDB|db_cdc|streaming|3  Received throwable to check for retry: {}   [io.debezium.connector.yugabytedb.YugabyteDBErrorHandler]
 99063 java.lang.OutOfMemoryError: Java heap space
 99064         at java.base/java.util.Arrays.copyOf(Arrays.java:3745)
 99065         at java.base/java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:172)
 99066         at java.base/java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:538)
 99067         at java.base/java.lang.StringBuffer.append(StringBuffer.java:317)
 99068         at org.apache.log4j.helpers.PatternParser$LiteralPatternConverter.format(PatternParser.java:389)
 99069         at org.apache.log4j.PatternLayout.format(PatternLayout.java:510)
 99070         at org.apache.log4j.WriterAppender.subAppend(WriterAppender.java:303)
 99071         at org.apache.log4j.DailyRollingFileAppender.subAppend(DailyRollingFileAppender.java:353)
 99072         at org.apache.log4j.WriterAppender.append(WriterAppender.java:156)
 99073         at org.apache.log4j.AppenderSkeleton.doAppend(AppenderSkeleton.java:232)
 99074         at org.apache.log4j.helpers.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:65)
 99075         at org.apache.log4j.Category.callAppenders(Category.java:206)
 99076         at org.apache.log4j.Category.forcedLog(Category.java:384)
 99077         at org.apache.log4j.Category.log(Category.java:810)
 99078         at org.slf4j.impl.Reload4jLoggerAdapter.debug(Reload4jLoggerAdapter.java:209)
 99079         at io.debezium.connector.yugabytedb.YugabyteDBStreamingChangeEventSource.getChanges2(YugabyteDBStreamingChangeEventSource.java:505)
 99080         at io.debezium.connector.yugabytedb.YugabyteDBStreamingChangeEventSource.execute(YugabyteDBStreamingChangeEventSource.java:138)
 99081         at io.debezium.connector.yugabytedb.YugabyteDBStreamingChangeEventSource.execute(YugabyteDBStreamingChangeEventSource.java:47)
 99082         at io.debezium.pipeline.ChangeEventSourceCoordinator.streamEvents(ChangeEventSourceCoordinator.java:174)
 99083         at io.debezium.connector.yugabytedb.YugabyteDBChangeEventSourceCoordinator.executeChangeEventSources(YugabyteDBChangeEventSourceCoordinator.java:135)
 99084         at io.debezium.pipeline.ChangeEventSourceCoordinator.lambda$start$0(ChangeEventSourceCoordinator.java:109)
 99085         at io.debezium.pipeline.ChangeEventSourceCoordinator$$Lambda$1102/0x000000084098f840.run(Unknown Source)
 99086         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
 99087         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
 99088         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
 99089         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
 99090         at java.base/java.lang.Thread.run(Thread.java:829)
 99091 2023-02-26 20:51:12,171 ERROR  ||  [Consumer clientId=connector-consumer-jdbc-sink-test_cdc_8474a0-0, groupId=connect-jdbc-sink-test_cdc_8474a0] Heartbeat thread failed due to unexpected error   [org.apache.kafka.clients.consumer.internals.ConsumerCoordinator]
 99092 java.lang.OutOfMemoryError: Java heap space
 99093         at java.base/java.nio.HeapByteBuffer.<init>(HeapByteBuffer.java:61)
 99094         at java.base/java.nio.ByteBuffer.allocate(ByteBuffer.java:348)
 99095         at org.apache.kafka.common.memory.MemoryPool$1.tryAllocate(MemoryPool.java:30)
 99096         at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:113)
 99097         at org.apache.kafka.common.network.KafkaChannel.receive(KafkaChannel.java:452)
 99098         at org.apache.kafka.common.network.KafkaChannel.read(KafkaChannel.java:402)
 99099         at org.apache.kafka.common.network.Selector.attemptRead(Selector.java:674)
 99100         at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:576)
 99101         at org.apache.kafka.common.network.Selector.poll(Selector.java:481)
 99102         at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:560)
 99103         at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:265)
 99104         at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.pollNoWakeup(ConsumerNetworkClient.java:306)
 99105         at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$HeartbeatThread.run(AbstractCoordinator.java:1433)
```

Also:
```
 99312 2023-02-26 20:51:34,153 ERROR  ||  WorkerSourceTask{id=ybconnector_cdc_066b50_test_cdc_8474a0-0} failed to send record to db_cdc.public.test_cdc_8474a0:    [org.apache.kafka.connect.runtime.WorkerSourceTask]
 99313 org.apache.kafka.common.KafkaException: Producer is closed forcefully.
 99314         at org.apache.kafka.clients.producer.internals.RecordAccumulator.abortBatches(RecordAccumulator.java:781)
 99315         at org.apache.kafka.clients.producer.internals.RecordAccumulator.abortIncompleteBatches(RecordAccumulator.java:768)
 99316         at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:283)
 99317         at java.base/java.lang.Thread.run(Thread.java:829)
```

As per discussion with @vaibhav-yb , raising this to track to look to check if something is not getting cleaned up
Like any other leak possible ? We hadn’t seen this case fail for a long time apart from 2 recent runs

<img width="1700" alt="Screenshot 2023-02-28 at 2 09 44 PM" src="https://user-images.githubusercontent.com/109518123/221799050-18f1a8ba-4be9-4148-9da0-2aa70532eb54.png">

### Source connector version

quay.io/yugabyte/debezium-connector:latest

v1.9.5.y.16

### Connector configuration

```
adding yb connector stream_id='349e045d05a94c6eb50541a553e59431' db_name='cdc_066b50' connector_host='172.151.31.240' table_list=['test_cdc_8474a0']
2023-02-26 19:21:04,123:DEBUG: add connector connector_name='ybconnector_cdc_066b50_test_cdc_8474a0' stream_id='349e045d05a94c6eb50541a553e59431' db_name='cdc_066b50' connector_host='172.151.31.240' table_list=['test_cdc_8474a0'] {'name': 'ybconnector_cdc_066b50_test_cdc_8474a0', 'config': {'connector.class': 'io.debezium.connector.yugabytedb.YugabyteDBConnector', 'database.hostname': '172.151.16.206', 'database.master.addresses': '172.151.24.64:7100,172.151.22.133:7100,172.151.16.206:7100', 'database.port': 5433, 'database.masterhost': '172.151.16.206', 'database.masterport': '7100', 'database.user': 'yugabyte', 'database.password': 'yugabyte', 'database.dbname': 'cdc_066b50', 'database.server.name': 'db_cdc', 'database.streamid': '349e045d05a94c6eb50541a553e59431', 'snapshot.mode': 'never', 'admin.operation.timeout.ms': 600000, 'socket.read.timeout.ms': 600000, 'max.connector.retries': '10', 'operation.timeout.ms': 600000, 'topic.creation.default.compression.type': 'lz4', 'topic.creation.default.cleanup.policy': 'delete', 'topic.creation.default.partitions': '2', 'topic.creation.default.replication.factor': '1', 'tasks.max': '10', 'table.include.list': 'public.test_cdc_8474a0'}}
```

### YugabyteDB version

2.17.3.0-b6

[DB-5681]: https://yugabyte.atlassian.net/browse/DB-5681?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
@shamanthchandra-yb , If the issue has nothing to do with Packed, can you remove the Packed columns in the title?

**Comment by shamanthchandra-yb** [comment]
Looks like it is on off case for some reason it failed. 
![Screenshot 2023-04-05 at 10 57 12 AM](https://user-images.githubusercontent.com/109518123/229988797-3be524ef-f307-4cc7-a595-c6d27b96a7a5.png)

This is how it looks now. No issues seen recently. Hence closing.
