### ISSUE TITLE
[DocDB] unit tests using yb_backup are broken with newer versions of python3

### ISSUE THREAD

**Issue by druzac** [yugabyte/yugabyte-db#16275]
Jira Link: [DB-5706](https://yugabyte.atlassian.net/browse/DB-5706)
### Description

Newer versions of python3 moved internal libraries around. Older versions of the `boto` dependency that the `yb_backup` script has unfortunately relied on these internal libraries and is broken with these newer versions. Many developers find they can no longer run unit tests that use the backup script on their laptops.

Example failure:
```
Traceback (most recent call last):
  File "/Users/zdrudi/code/yugabyte-db/build/debug-clang-dynamic-arm64-ninja/tests-tools/../../../managed/devops/bin/yb_backup.py", line 29, in <module>
    from botocore.session import get_session
  File "/Users/zdrudi/code/yugabyte-db/build/venv-arm64/lib/python3.10/site-packages/botocore/session.py", line 25, in <module>
    import botocore.configloader
  File "/Users/zdrudi/code/yugabyte-db/build/venv-arm64/lib/python3.10/site-packages/botocore/configloader.py", line 20, in <module>
    import botocore.exceptions
  File "/Users/zdrudi/code/yugabyte-db/build/venv-arm64/lib/python3.10/site-packages/botocore/exceptions.py", line 15, in <module>
    from botocore.vendored.requests.exceptions import ConnectionError
  File "/Users/zdrudi/code/yugabyte-db/build/venv-arm64/lib/python3.10/site-packages/botocore/vendored/requests/__init__.py", line 58, in <module>
    from . import utils
  File "/Users/zdrudi/code/yugabyte-db/build/venv-arm64/lib/python3.10/site-packages/botocore/vendored/requests/utils.py", line 26, in <module>
    from .compat import parse_http_list as _parse_list_header
  File "/Users/zdrudi/code/yugabyte-db/build/venv-arm64/lib/python3.10/site-packages/botocore/vendored/requests/compat.py", line 7, in <module>
    from .packages import chardet
  File "/Users/zdrudi/code/yugabyte-db/build/venv-arm64/lib/python3.10/site-packages/botocore/vendored/requests/packages/__init__.py", line 3, in <module>
    from . import urllib3
  File "/Users/zdrudi/code/yugabyte-db/build/venv-arm64/lib/python3.10/site-packages/botocore/vendored/requests/packages/urllib3/__init__.py", line 10, in <module>
    from .connectionpool import (
  File "/Users/zdrudi/code/yugabyte-db/build/venv-arm64/lib/python3.10/site-packages/botocore/vendored/requests/packages/urllib3/connectionpool.py", line 38, in <module>
    from .response import HTTPResponse
  File "/Users/zdrudi/code/yugabyte-db/build/venv-arm64/lib/python3.10/site-packages/botocore/vendored/requests/packages/urllib3/response.py", line 9, in <module>
    from ._collections import HTTPHeaderDict
  File "/Users/zdrudi/code/yugabyte-db/build/venv-arm64/lib/python3.10/site-packages/botocore/vendored/requests/packages/urllib3/_collections.py", line 1, in <module>
    from collections import Mapping, MutableMapping
ImportError: cannot import name 'Mapping' from 'collections' (/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/collections/__init__.py)
../../src/yb/tools/yb-backup/yb-backup-test.cc:549: Failure
```

[DB-5706]: https://yugabyte.atlassian.net/browse/DB-5706?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by druzac** [comment]
Should be fixed by https://github.com/yugabyte/yugabyte-db/commit/fa7e0bb34f4b04a4a5d8ec57094527540167466e.
