### ISSUE TITLE
yb-ctl destroy hits OSError: [Errno 3] No such process if cluster doesn't 

### ISSUE THREAD

**Issue by kmuthukk** [YugaByte/yugabyte-db#1643]
In some cases, `yb-ctl destroy` seems to hit this error.

Steps to repro:

1. This step is expected to fail because we artifically force the same IP/port for all three yb-tserver processes on the node. So only 1 of them will start, and the others will fail.
```
$ ./bin/yb-ctl --rf 3 start --tserver_flags="redis_proxy_bind_address=0.0.0.0:6123"
Creating cluster.
Waiting for cluster to be ready.
----------------------------------------------------------------------------------------------------
| Node Count: 3 | Replication Factor: 3                                                            |
----------------------------------------------------------------------------------------------------
| JDBC                : postgresql://postgres@127.0.0.1:5433                                       |
| YSQL Shell          : ./bin/ysqlsh                                                               |
| YCQL Shell          : ./bin/cqlsh                                                                |
| YEDIS Shell         : ./bin/redis-cli -h 127.0.0.1 -p 6379                                       |
| Web UI              : http://127.0.0.1:7000/                                                     |
| Cluster Data        : /home/centos/yugabyte-data                                                 |
----------------------------------------------------------------------------------------------------
```

2. Confirm that two of the yb-tserver processes didn't start:
```
$ ./bin/yb-ctl status | grep yb-
./bin/yb-ctl status | grep yb-
| Node 1: yb-tserver (pid 22222), yb-master (pid 22213)                                            |
| data-dir[0]         : /home/centos/yugabyte-data/node-1/disk-1/yb-data                           |
| yb-tserver Logs     : /home/centos/yugabyte-data/node-1/disk-1/yb-data/tserver/logs              |
| yb-master Logs      : /home/centos/yugabyte-data/node-1/disk-1/yb-data/master/logs               |
| Node 2: yb-tserver (Stopped), yb-master (pid 22216)                                              |
| data-dir[0]         : /home/centos/yugabyte-data/node-2/disk-1/yb-data                           |
| yb-tserver Logs     : /home/centos/yugabyte-data/node-2/disk-1/yb-data/tserver/logs              |
| yb-master Logs      : /home/centos/yugabyte-data/node-2/disk-1/yb-data/master/logs               |
| Node 3: yb-tserver (Stopped), yb-master (pid 22219)                                              |
| data-dir[0]         : /home/centos/yugabyte-data/node-3/disk-1/yb-data                           |
| yb-tserver Logs     : /home/centos/yugabyte-data/node-3/disk-1/yb-data/tserver/logs              |
| yb-master Logs      : /home/centos/yugabyte-data/node-3/disk-1/yb-data/master/logs               |
```

3. Now, an attempt to yb-ctl destroy hits this issue:
```
$ ./bin/yb-ctl destroy
./bin/yb-ctl destroy
Destroying cluster.
Traceback (most recent call last):
  File "./bin/yb-ctl", line 1658, in <module>
    control.run()
  File "./bin/yb-ctl", line 1631, in run
    self.args.func()
  File "./bin/yb-ctl", line 1463, in destroy_cmd_impl
    self.for_all_daemons(self.stop_daemon)
  File "./bin/yb-ctl", line 1398, in for_all_daemons
    fn(DaemonId(daemon_type, daemon_index))
  File "./bin/yb-ctl", line 1172, in stop_daemon
    self.stop_process(postgres_pid, "Postmaster for {}".format(daemon_id))
  File "./bin/yb-ctl", line 1142, in stop_process
    os.kill(pid, signal.SIGTERM)
OSError: [Errno 3] No such process
2019-06-27 21:53:39,372 INFO: Stopping Server master-1 PID=22213
2019-06-27 21:53:39,373 INFO: Waiting for Server master-1 PID=22213 to stop...
2019-06-27 21:53:39,886 INFO: Stopping Server master-2 PID=22216
2019-06-27 21:53:39,886 INFO: Waiting for Server master-2 PID=22216 to stop...
2019-06-27 21:53:40,399 INFO: Stopping Server master-3 PID=22219
2019-06-27 21:53:40,399 INFO: Waiting for Server master-3 PID=22219 to stop...
2019-06-27 21:53:40,912 INFO: Stopping Server tserver-1 PID=22222
2019-06-27 21:53:40,912 INFO: Waiting for Server tserver-1 PID=22222 to stop...
2019-06-27 21:53:41,424 INFO: Server tserver-2 already stopped
2019-06-27 21:53:41,424 INFO: Stopping Postmaster for tserver-2 PID=22347
^^^ Encountered errors ^^^
```

**Comment by kmuthukk** [comment]
Workaround to manually destroy old state:

rm -rf ~/yugabyte-data/ (default, or the appropriate --data_dir used)
pkill yb-master
pkill yb-tserver
