### ISSUE TITLE
[CDCSDK] CDC on multi colocated tables, is causing issues (Error while fetching all the tablets)

### ISSUE THREAD

**Issue by shamanthchandra-yb** [yugabyte/yugabyte-db#16462]
Jira Link: [DB-5870](https://yugabyte.atlassian.net/browse/DB-5870)
### Description

Running a master 0 CDC case

There are 2 colocated tables in database. 

http://stress.dev.yugabyte.com/stress_test/2647f954-6d12-4f87-8773-b4b9a0012d27

Connector is throwing below error:

```
2023-03-17 08:34:21,792 ERROR  ||  Error while fetching all the tablets   [io.debezium.connector.yugabytedb.YugabyteDBConnector]
org.yb.client.NonRecoverableException: Too many attempts: YRpc(method=GetTabletListToPollForCDC, service=yb.cdc.CDCService, tablet=null, attempt=100, maxAttempts=100, maxTimeoutMs=600000, elapsedTimeMs=56)
	at org.yb.client.AsyncYBClient.tooManyAttemptsOrTimeout(AsyncYBClient.java:2039)
	at org.yb.client.AsyncYBClient.sendRpcToTablet(AsyncYBClient.java:1654)
	at org.yb.client.AsyncYBClient$RetryRpcCB.call(AsyncYBClient.java:1749)
	at org.yb.client.AsyncYBClient$RetryRpcCB.call(AsyncYBClient.java:1743)
	at com.stumbleupon.async.Deferred.doCall(Deferred.java:1280)
	at com.stumbleupon.async.Deferred.runCallbacks(Deferred.java:1259)
	at com.stumbleupon.async.Deferred.callback(Deferred.java:1002)
	at org.yb.client.YRpc.handleCallback(YRpc.java:184)
	at org.yb.client.YRpc.callback(YRpc.java:197)
	at org.yb.client.TabletClient.decode(TabletClient.java:451)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

### Source connector version

Latest

1.9.5.y.16

### Connector configuration

```
add connector connector_name='ybconnector_cdc_62aae3_test_cdc_8e3398_test_cdc_60b303' stream_id='40d2e3c6c0c246139c03e029bc22c3ab' db_name='cdc_62aae3' connector_host='172.151.17.222' table_list=['test_cdc_8e3398', 'test_cdc_60b303'] {'name': 'ybconnector_cdc_62aae3_test_cdc_8e3398_test_cdc_60b303', 'config': {'connector.class': 'io.debezium.connector.yugabytedb.YugabyteDBConnector', 'database.hostname': '172.151.19.15', 'database.master.addresses': '172.151.19.15:7100,172.151.25.254:7100,172.151.25.170:7100', 'database.port': 5433, 'database.masterhost': '172.151.19.15', 'database.masterport': '7100', 'database.user': 'yugabyte', 'database.password': 'yugabyte', 'database.dbname': 'cdc_62aae3', 'database.server.name': 'db_cdc', 'database.streamid': '40d2e3c6c0c246139c03e029bc22c3ab', 'snapshot.mode': 'never', 'admin.operation.timeout.ms': 600000, 'socket.read.timeout.ms': 600000, 'max.connector.retries': '10', 'operation.timeout.ms': 600000, 'topic.creation.default.compression.type': 'lz4', 'topic.creation.default.cleanup.policy': 'delete', 'topic.creation.default.partitions': 2, 'topic.creation.default.replication.factor': '1', 'tasks.max': '5', 'table.include.list': 'public.test_cdc_8e3398,public.test_cdc_60b303'}}
```

```
add connector name='jdbc-sink-test_cdc_8e3398' {'name': 'jdbc-sink-test_cdc_8e3398', 'config': {'connector.class': 'io.confluent.connect.jdbc.JdbcSinkConnector', 'tasks.max': '1', 'topics': 'db_cdc.public.test_cdc_8e3398', 'dialect.name': 'PostgreSqlDatabaseDialect', 'table.name.format': 'test_cdc_8e3398', 'connection.url': 'jdbc:postgresql://172.151.18.232:5432/postgres?user=postgres&password=postgres', 'transforms': 'unwrap', 'transforms.unwrap.type': 'io.debezium.connector.yugabytedb.transforms.YBExtractNewRecordState', 'transforms.unwrap.drop.tombstones': 'false', 'auto.create': 'true', 'insert.mode': 'upsert', 'pk.fields': 'k', 'pk.mode': 'record_key', 'delete.enabled': 'true', 'auto.evolve': 'true'}}
```

```
add connector name='jdbc-sink-test_cdc_60b303' {'name': 'jdbc-sink-test_cdc_60b303', 'config': {'connector.class': 'io.confluent.connect.jdbc.JdbcSinkConnector', 'tasks.max': '1', 'topics': 'db_cdc.public.test_cdc_60b303', 'dialect.name': 'PostgreSqlDatabaseDialect', 'table.name.format': 'test_cdc_60b303', 'connection.url': 'jdbc:postgresql://172.151.18.232:5432/postgres?user=postgres&password=postgres', 'transforms': 'unwrap', 'transforms.unwrap.type': 'io.debezium.connector.yugabytedb.transforms.YBExtractNewRecordState', 'transforms.unwrap.drop.tombstones': 'false', 'auto.create': 'true', 'insert.mode': 'upsert', 'pk.fields': 'k', 'pk.mode': 'record_key', 'delete.enabled': 'true', 'auto.evolve': 'true'}}
```

### YugabyteDB version

2.17.3.0-b91

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-5870]: https://yugabyte.atlassian.net/browse/DB-5870?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by shamanthchandra-yb** [comment]
As of now there is an issue when we have multiple tasks while deploying connector on colocated databases. There is a fix @vaibhav-yb working on where if its colocated, and if there are multiple tasks, internally it will convert it into single task. 

Drawback is: No parallelism is achieved in this case. There will be hit on perf aspect. 

The support of multiple tasks on colocated database is tracked here: https://github.com/yugabyte/yugabyte-db/issues/16479

**Comment by shamanthchandra-yb** [comment]
Closing this as this ERROR stack trace is not seen now, but testcase still fails with: https://github.com/yugabyte/yugabyte-db/issues/16707
