### ISSUE TITLE
[Backup Restore] Restore failed for dropped colocated database 

### ISSUE THREAD

**Issue by zlareb1-yb** [yugabyte/yugabyte-db#16521]
Jira Link: [DB-5918](https://yugabyte.atlassian.net/browse/DB-5918)
### Description

Steps:
1. Take Backup of a Colocated DB
2. DROP the DB
3. Restore the Backup

Observed Restore failed with below error:
`2023-03-22 11:19:01,918 test_base.py:178 ERROR testysqltabletsplittingwithrpc-aws-rf3 ITEST FAILED testysqltabletsplittingwithrpc-aws-rf3 : RuntimeError('wait_for_task: Failed task with errors in 30.35816502571106s:\nFailed to execute task {"platformVersion":"2.17.3.0-b16","sleepAfterMasterRestartMillis":180000,"sleepAfterTServerRestartMillis":180000,"nodeExporterUser":"prometheus","universeUUID":"feddcbfa-8379-4a3e-8ba7-8c9af9788fe9","enableYbc":false,"installYbc":false,"ybcInstalled":false,"encryptionAtRestConfig":{"encryptionAtRestEnabled":false,"opType":"UNDEFINED","type":"DATA_KEY"},"communicationPorts":{"masterHttpPort":7000,"masterRpcPort":7100,"tserverHttpPort":9000,"tserverRpcPort":9100,"ybControllerHttpPort":14000,"yb..., hit error:\n\nTask id 7901e4e9-f195-4897-95d6-8402d158cac0_PGSQL_TABLE_TYPE_colocated_db status: Failed with error COMMAND_FAILED.')`

```
YW 2023-03-22T11:40:46.430Z [ERROR] c8c6cf68-4a31-4885-97b5-7909b9427f25 from TaskExecutor in TaskPool-1 - Failed to execute task type RestoreBackup UUID 16226ab6-9715-44bf-a2c0-a4bb11eba31b details {"platformVersion":"2.17.2.0-b216","sleepAfterMasterRestartMillis":180000,"sleepAfterTServerRestartMillis":180000,"nodeExporterUser":"prometheus","universeUUID":"fa1fd3d9-cbc9-4b52-bd61-2c0b14c66063","enableYbc":false,"installYbc":false,"ybcInstalled":false,"encryptionAtRestConfig":{"encryptionAtRestEnabled":false,"opType":"UNDEFINED","type":"DATA_KEY"},"communicationPorts":{"masterHttpPort":7000,"masterRpcPort":7100,"tserverHttpPort":9000,"tserverRpcPort":9100,"ybControllerHttpPort":14000,"ybControllerrRpcPort":18018,"redisServerHttpPort":11000,"redisServerRpcPort":6379,"yqlServerHttpPort":12000,"yqlServerRpcPort":9042,"ysqlServerHttpPort":13000,"ysqlServerRpcPort":5433,"nodeExporterPort":9300},"extraDependencies":{"installNodeExporter":true},"firstTry":true,"customerUUID":"c9c4e6e2-a640-43f7-a522-29d2f2ededbd","actionType":"RESTORE","category":"YB_CONTROLLER","backupStorageInfoList":[{"backupType":"PGSQL_TABLE_TYPE","storageLocation":"gs://itest-backup/univ-fa1fd3d9-cbc9-4b52-bd61-2c0b14c66063/ybc_backup-2023-03-22T11:37:39-1662548782/multi-table-colocated_db","keyspace":"colocated_db","sse":false,"oldOwner":"postgres"}],"prefixUUID":"1a61a87a-ced3-48ff-a2cf-d21f56e5910b","currentIdx":0,"currentYbcTaskId":"1a61a87a-ced3-48ff-a2cf-d21f56e5910b_PGSQL_TABLE_TYPE_colocated_db","enableVerboseLogs":false,"storageConfigUUID":"0386d3e5-52f5-4b4a-b4ca-005d622e349e","alterLoadBalancer":true,"disableChecksum":false,"useTablespaces":false,"disableMultipart":false,"parallelism":8,"targetXClusterConfigs":[],"sourceXClusterConfigs":[]}, hit error.
java.lang.RuntimeException: RestoreBackupYbc : completed 1 out of 1 tasks. failed.
	at com.yugabyte.yw.commissioner.TaskExecutor$RunnableTask.runSubTasks(TaskExecutor.java:1110)
	at com.yugabyte.yw.commissioner.tasks.RestoreBackup.run(RestoreBackup.java:65)
	at com.yugabyte.yw.commissioner.TaskExecutor$AbstractRunnableTask.run(TaskExecutor.java:796)
	at com.yugabyte.yw.commissioner.TaskExecutor$RunnableTask.run(TaskExecutor.java:1005)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.yugabyte.yw.common.logging.MDCAwareRunnable.run(MDCAwareRunnable.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: com.yugabyte.yw.common.PlatformServiceException: Task id 1a61a87a-ced3-48ff-a2cf-d21f56e5910b_PGSQL_TABLE_TYPE_colocated_db status: Failed with error COMMAND_FAILED
	at com.yugabyte.yw.commissioner.YbcTaskBase.handleTaskCompleteStage(YbcTaskBase.java:95)
	at com.yugabyte.yw.commissioner.YbcTaskBase.pollTaskProgress(YbcTaskBase.java:66)
	at com.yugabyte.yw.commissioner.tasks.subtasks.RestoreBackupYbc.run(RestoreBackupYbc.java:179)
	at com.yugabyte.yw.commissioner.TaskExecutor$AbstractRunnableTask.run(TaskExecutor.java:796)
	at com.yugabyte.yw.commissioner.TaskExecutor$RunnableSubTask.run(TaskExecutor.java:1180)
	... 6 common frames omitted
```

Further details in Slack Thread accessible internal to YB - https://yugabyte.slack.com/archives/C8QDREM0R/p1679490341873789

cc: @renjith-yb @kripasreenivasan 

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-5918]: https://yugabyte.atlassian.net/browse/DB-5918?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by lingamsandeep** [comment]
Observed error: `pg_yb_tablegroup OID value not set when in binary upgrade mode`

**Comment by druzac** [comment]
Looks like a dup of #16482.
