### ISSUE TITLE
[CDCSDK] Snapshot + Tablet Splitting: Invalid checkpoint -1.-1 for tablet ERROR throws and CDC stopped

### ISSUE THREAD

**Issue by shamanthchandra-yb** [yugabyte/yugabyte-db#16556]
Jira Link: [DB-5962](https://yugabyte.atlassian.net/browse/DB-5962)
### Description

http://stress.dev.yugabyte.com/stress_test/f9fa8f32-dc79-4f7d-9304-598540f1e367

```
2023-03-23 19:39:29,508 ERROR  ||  WorkerSourceTask{id=ybconnector_cdc_77e5be_test_cdc_e08794-1} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted   [org.apache.kafka.connect.runtime.WorkerTask]
org.apache.kafka.connect.errors.ConnectException: An exception occurred in the change event producer. This connector will be stopped.
	at io.debezium.pipeline.ErrorHandler.setProducerThrowable(ErrorHandler.java:50)
	at io.debezium.connector.yugabytedb.YugabyteDBStreamingChangeEventSource.execute(YugabyteDBStreamingChangeEventSource.java:144)
	at io.debezium.connector.yugabytedb.YugabyteDBStreamingChangeEventSource.execute(YugabyteDBStreamingChangeEventSource.java:47)
	at io.debezium.pipeline.ChangeEventSourceCoordinator.streamEvents(ChangeEventSourceCoordinator.java:174)
	at io.debezium.connector.yugabytedb.YugabyteDBChangeEventSourceCoordinator.executeChangeEventSources(YugabyteDBChangeEventSourceCoordinator.java:138)
	at io.debezium.pipeline.ChangeEventSourceCoordinator.lambda$start$0(ChangeEventSourceCoordinator.java:109)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.yb.client.CDCErrorException: Server[d4a92e11c8404cf1922a85beab11d6e1] INVALID_ARGUMENT[code 4]: Invalid checkpoint -1.-1 for tablet 6181daa1a82541168ad6a62c5337e114. Hint: set checkpoint explicitly or take snapshot
	at org.yb.client.TabletClient.dispatchCDCErrorOrReturnException(TabletClient.java:506)
	at org.yb.client.TabletClient.decode(TabletClient.java:437)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	... 3 more
```

### Source connector version

latest

1.9.5.y.17

### Connector configuration

```
add connector connector_name='ybconnector_cdc_77e5be_test_cdc_e08794' stream_id='0b32ff0b1d4f4f77b869b81f9be95a09' db_name='cdc_77e5be' connector_host='172.151.30.106' table_list=['test_cdc_e08794'] {'name': 'ybconnector_cdc_77e5be_test_cdc_e08794', 'config': {'connector.class': 'io.debezium.connector.yugabytedb.YugabyteDBConnector', 'database.hostname': '172.151.24.25', 'database.master.addresses': '172.151.17.152:7100,172.151.24.219:7100,172.151.24.25:7100', 'database.port': 5433, 'database.masterhost': '172.151.24.25', 'database.masterport': '7100', 'database.user': 'yugabyte', 'database.password': 'yugabyte', 'database.dbname': 'cdc_77e5be', 'database.server.name': 'db_cdc', 'database.streamid': '0b32ff0b1d4f4f77b869b81f9be95a09', 'snapshot.mode': 'initial', 'admin.operation.timeout.ms': 600000, 'socket.read.timeout.ms': 600000, 'max.connector.retries': '10', 'operation.timeout.ms': 600000, 'topic.creation.default.compression.type': 'lz4', 'topic.creation.default.cleanup.policy': 'delete', 'topic.creation.default.partitions': 2, 'topic.creation.default.replication.factor': '1', 'tasks.max': '5', 'table.include.list': 'public.test_cdc_e08794'}}
```

### YugabyteDB version

2.17.3.0-b134

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-5962]: https://yugabyte.atlassian.net/browse/DB-5962?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
@vaibhav-yb , Can you backport the fix to 2.14 and 2.16 branches? tablet-splitting is GA since 2.14

**Comment by vaibhav-yb** [comment]
@rthallamko3 the fix was on the connector side and it will work as it is on 2.16 as well without any server side change.

**Comment by ccorbacho** [comment]
We hit this yesterday with YugabyteDB 2.18 and connector 1.9.5.y.25.

Restarting the connector wasn't sufficient - we found upgrading to 1.9.5.y.31 resolved it for us, but it's not clear to us if it was because the upgrade triggered a full restart of Kafka Connect, or because one of the changes between .25 and .31 fixes this.

**Comment by ccorbacho** [comment]
Connecting to a Kafka Connect pod and running:
`curl -X POST localhost:8083/connectors/<failing connector>/restart`

So it sounds like it is possible then that the upgrade to .31 may have fixed our particular case (not the connector restart), but we still need more fixes in future.

We are on 2.18.0.1-b4, but I will flag the 2.18.2.1-b1 upgrade to our infrastructure team.

Also - it's not very clear from this bug report (as it links to your internal JIRA) - what exactly triggers this error to happen?
