### ISSUE TITLE
[DocDB] rare UBSAN error in XClusterTestParams/XClusterTest.TestAlterUniverseRemoveTableAndDrop/0

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#16627]
Jira Link: [DB-6016](https://yugabyte.atlassian.net/browse/DB-6016)
### Description

https://jenkins.dev.yugabyte.com/job/github-yugabyte-db-alma8-master-clang15-asan/638/artifact/build/asan-clang15-dynamic-ninja/yb-test-logs/tests-integration-tests__xcluster-test/XClusterTestParams__XClusterTest_TestAlterUniverseRemoveTableAndDrop__0.log

```
../../src/yb/consensus/log_cache.cc:285:36: runtime error: member call on null pointer of type 'yb::log::LogReader'
...
[C-ts-1] I0329 02:59:00.616362 1554060 xcluster_consumer.cc:168] [TS {Cts1_peer_id}]: Shutting down CDC Consumer
    #0 0x7f8886700e61 in yb::consensus::LogCache::earliest_op_index() const ${BUILD_ROOT}/../../src/yb/consensus/log_cache.cc:285:36
    #1 0x7f88866afd72 in yb::consensus::PeerMessageQueue::ReadReplicatedMessagesForCDC(yb::OpId const&, long*, std::chrono::time_point<yb::CoarseMonoClock, std::chrono::duration<long long, std::ratio<1l, 1000000000l>>>, bool) ${BUILD_ROOT}/../../src/yb/consensus/consensus_queue.cc:780:45
    #2 0x7f88867746cd in yb::consensus::RaftConsensus::ReadReplicatedMessagesForCDC(yb::OpId const&, long*, std::chrono::time_point<yb::CoarseMonoClock, std::chrono::duration<long long, std::ratio<1l, 1000000000l>>>, bool) ${BUILD_ROOT}/../../src/yb/consensus/raft_consensus.cc:3489:18
    #3 0x7f888e5bd504 in yb::cdc::GetChangesForXCluster(string const&, string const&, yb::OpId const&, yb::cdc::StreamMetadata const&, std::shared_ptr<yb::tablet::TabletPeer> const&, std::shared_ptr<yb::client::YBSession> const&, std::function<yb::Status (yb::consensus::ReplicateMsg const&)>, std::shared_ptr<yb::MemTracker> const&, yb::consensus::ReplicateMsgsHolder*, yb::cdc::GetChangesResponsePB*, long*, std::chrono::time_point<yb::CoarseMonoClock, std::chrono::duration<long long, std::ratio<1l, 1000000000l>>>) ${BUILD_ROOT}/../../src/yb/cdc/cdc_producer.cc:530:16
    #4 0x7f888e4d9232 in yb::cdc::CDCServiceImpl::GetChanges(yb::cdc::GetChangesRequestPB const*, yb::cdc::GetChangesResponsePB*, yb::rpc::RpcContext) ${BUILD_ROOT}/../../src/yb/cdc/cdc_service.cc:1669:14
...
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior ../../src/yb/consensus/log_cache.cc:285:36 in 
```

Presumably we're calling GetChanges on a tablet that's in the process of shutting down. I assume this can be a legitimate product issue, on tablet shutdown (eg: LB moving data around, drop table).

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-6016]: https://yugabyte.atlassian.net/browse/DB-6016?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by bmatican** [comment]
Haven't seen any UBSAN issues in a while, probably after many of @hari90 's shutdown fixes
