### ISSUE TITLE
Failed creating Cluster

### ISSUE THREAD

**Issue by iambudi** [YugaByte/yugabyte-db#1669]
DB Version: 1.2.11.0
Mojave
Darwin mbp 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64

```
./yb-ctl --data_dir /Users/iambudi/db/ybtest --rf 3 create
Creating cluster.
Waiting for cluster to be ready.
Traceback (most recent call last):
  File "./yb-ctl", line 1658, in <module>
    control.run()
  File "./yb-ctl", line 1631, in run
    self.args.func()
  File "./yb-ctl", line 1417, in create_cmd_impl
    self.wait_for_cluster_or_raise()
  File "./yb-ctl", line 1297, in wait_for_cluster_or_raise
    raise RuntimeError("Timed out waiting for a YugaByte DB cluster!")
RuntimeError: Timed out waiting for a YugaByte DB cluster!
```

**Comment by rkarthik007** [comment]
Hi @iambudi,

Wondering if the processes started. Could you please output the result of running the following:
```
ps aux | grep yb
```

Also, could you please paste the output of:
```
yb-ctl status
```

**Comment by iambudi** [comment]
Hi @rkarthik007,

Here's the output of `ps aux | grep yb` after executing create db again.
`./yb-ctl --data_dir /Users/budi/db/Yugabyte/insight --rf 3 create`

```           
iambudi             13594   5.7  0.1  4420104  21548   ??  S     6:11AM   4:36.20 /Users/iambudi/Applications/yugabyte/bin/yb-tserver --fs_data_dirs /Users/iambudi/db/Yugabyte/insight/node-1/disk-1 --webserver_interface 127.0.0.1 --rpc_bind_addresses 127.0.0.1 --v 0 --version_file_json_path=/Users/iambudi/Applications/yugabyte --webserver_doc_root /Users/iambudi/Applications/yugabyte/www --tserver_master_addrs=127.0.0.1:7100,127.0.0.2:7100,127.0.0.3:7100 --memory_limit_hard_bytes=1073741824 --yb_num_shards_per_tserver=2 --redis_proxy_bind_address=127.0.0.1 --cql_proxy_bind_address=127.0.0.1 --local_ip_for_outbound_sockets=127.0.0.1 --use_cassandra_authentication=false --start_pgsql_proxy --pgsql_proxy_bind_address=127.0.0.1
iambudi             21606   1.0  0.1  4363256  17844 s000  S+    5:37PM   0:00.03 /Users/iambudi/Applications/yugabyte/bin/yb-admin --master_addresses 127.0.0.1:7100,127.0.0.2:7100,127.0.0.3:7100 list_all_tablet_servers
iambudi             20615   0.1  0.1  4343396  15140 s000  S+    5:36PM   0:00.16 /usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python ./yb-ctl --data_dir /Users/iambudi/db/Yugabyte/insight --rf 3 create
iambudi               446   0.0  0.0  4384440   4120   ??  S    Mon08AM   0:01.11 /usr/libexec/keyboardservicesd
iambudi             21624   0.0  0.0  4268056    804 s001  S+    5:37PM   0:00.00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn yb
root                77   0.0  0.0  4341688      8   ??  Ss   Mon08AM   0:00.02 /usr/libexec/keybagd -t 15
iambudi             20620   0.0  0.1  4392368  24300 s000  S+    5:36PM   0:00.12 /Users/iambudi/Applications/yugabyte/bin/yb-master --fs_data_dirs /Users/iambudi/db/Yugabyte/insight/node-1/disk-1 --webserver_interface 127.0.0.1 --rpc_bind_addresses 127.0.0.1 --v 0 --version_file_json_path=/Users/iambudi/Applications/yugabyte --webserver_doc_root /Users/iambudi/Applications/yugabyte/www --replication_factor=3 --yb_num_shards_per_tserver 2 --master_addresses 127.0.0.1:7100,127.0.0.2:7100,127.0.0.3:7100 --use_initial_sys_catalog_snapshot
```
Output of `yb-ctl status`
```
No cluster data found at: '/Users/iambudi/yugabyte-data'
```
It seems yb-ctl status pointing to different directory where i created the db.

Thanks.

**Comment by iambudi** [comment]
Passing the data-dir.

```
----------------------------------------------------------------------------------------------------
| Node Count: 3 | Replication Factor: 1                                                            |
----------------------------------------------------------------------------------------------------
| JDBC                : postgresql://postgres@127.0.0.1:5433                                       |
| YSQL Shell          : ./bin/ysqlsh                                                               |
| YCQL Shell          : ./bin/cqlsh                                                                |
| YEDIS Shell         : ./bin/redis-cli -h 127.0.0.1 -p 6379                                       |
| Web UI              : http://127.0.0.1:7000/                                                     |
| Cluster Data        : /Users/iambudi/db/Yugabyte/insight                                         |
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
| Node 1: yb-tserver (pid 13594), yb-master (pid 20620)                                            |
----------------------------------------------------------------------------------------------------
| JDBC                : postgresql://postgres@127.0.0.1:5433                                       |
| YSQL Shell          : ./bin/ysqlsh                                                               |
| YCQL Shell          : ./bin/cqlsh                                                                |
| YEDIS Shell         : ./bin/redis-cli -h 127.0.0.1 -p 6379                                       |
| data-dir[0]         : /Users/iambudi/db/Yugabyte/insight/node-1/disk-1/yb-data                   |
| yb-tserver Logs     : /Users/iambudi/db/Yugabyte/insight/node-1/disk-1/yb-data/tserver/logs      |
| yb-master Logs      : /Users/iambudi/db/Yugabyte/insight/node-1/disk-1/yb-data/master/logs       |
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
| Node 2: yb-tserver (Stopped), yb-master (Stopped)                                                |
----------------------------------------------------------------------------------------------------
| JDBC                : postgresql://postgres@127.0.0.2:5433                                       |
| YSQL Shell          : ./bin/ysqlsh                                                               |
| YCQL Shell          : ./bin/cqlsh                                                                |
| YEDIS Shell         : ./bin/redis-cli -h 127.0.0.2 -p 6379                                       |
| data-dir[0]         : /Users/iambudi/db/Yugabyte/insight/node-2/disk-1/yb-data                   |
| yb-tserver Logs     : /Users/iambudi/db/Yugabyte/insight/node-2/disk-1/yb-data/tserver/logs      |
| yb-master Logs      : /Users/iambudi/db/Yugabyte/insight/node-2/disk-1/yb-data/master/logs       |
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
| Node 3: yb-master (Stopped)                                                                      |
----------------------------------------------------------------------------------------------------
| data-dir[0]         : /Users/iambudi/db/Yugabyte/insight/node-3/disk-1/yb-data                   |
| yb-master Logs      : /Users/iambudi/db/Yugabyte/insight/node-3/disk-1/yb-data/master/logs       |
----------------------------------------------------------------------------------------------------
```

**Comment by kmuthukk** [comment]
Hi @iambudi 

The processes don't seem to have started correctly. 

Can you check the contents of, the google log files below?

/Users/iambudi/db/Yugabyte/insight/node-2/disk-1/yb-data/tserver/logs/yb-tserver.INFO
/Users/iambudi/db/Yugabyte/insight/node-2/disk-1/yb-data/master/logs/yb-master.INFO

and also please check if there's anything we can learn from the  .err/.out files in this directory:

/Users/iambudi/db/Yugabyte/insight/node-2/disk-1/

Is it possible that either something else is using one of the ports, causing these processes to not start.

**Comment by ttyusupov** [comment]
Hi @iambudi , were you able to start the cluster or get to log files?

**Comment by ttyusupov** [comment]
Hi @iambudi , just checking if you were able to get up and running. Please feel free to reach out, someone from our side will be happy to help. I am closing this issue for now, please feel free to open a new issue or reopen this one.

**Comment by creisle** [comment]
Don't know if this was the same problem I had, but I got the same error message. I had to delve pretty far into the logs to find this (could it be made more visible to the user?)


```
>>> cat cluster_data/node-1/disk-1/yb-data/tserver/logs/yb-tserver.<hostname>.<user>.log.ERROR.20191203-185226.126782
Log file created at: 2019/12/03 18:52:26
Running on machine: <hostname>
Application fingerprint: version 2.0.6.0 build 5 revision <id> build_type RELEASE built at 22 Nov 2019 11:36:19 UTC
Running duration (h:mm:ss): 0:00:00
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
E1203 18:52:26.385077 126782 main_util.cc:22] IO error (yb/fs/fs_manager.cc:176): Failed to load FS layout: Relative path cluster_data//node-1/disk-1 provided for filesystem root
```

I had provided a relative path for the `--data_dir` argument on create. When I provided an absolute path the cluster started fine
