### ISSUE TITLE
Segmentation fault on SELECT from TEMP table inside function

### ISSUE THREAD

**Issue by d-uspenskiy** [YugaByte/yugabyte-db#1676]
The following sequence of commands causes `Segmentation fault` in postgresql process

```

**Comment by kmuthukk** [comment]
Stack trace for:

select composrec();

```
(gdb) where
#0  __memcpy_avx_unaligned () at ../sysdeps/x86_64/multiarch/memcpy-avx-unaligned.S:238
#1  0x00000000008fb2e5 in cstring_to_text_with_len (s=0x7ffdf8f7b764 "", len=3629796) at ../../../../../../../src/postgres/src/backend/utils/adt/varlena.c:166
#2  0x000000000049f716 in heap_copytuple (tuple=tuple@entry=0x7ffdf8f7b710) at ../../../../../../../src/postgres/src/backend/access/common/heaptuple.c:741
#3  0x0000000000826f91 in expanded_record_set_tuple (erh=0x231ff20, tuple=0x7ffdf8f7b710, copy=<optimized out>, expand_external=false) at ../../../../../../../src/postgres/src/backend/utils/ad\
t/expandedrecord.c:493
#4  0x00007f3120035c77 in exec_move_row_from_datum (estate=estate@entry=0x7ffdf8f7bc30, target=target@entry=0x22223a8, value=value@entry=36758280) at ../../../../../../../src/postgres/src/pl/p\
lpgsql/src/pl_exec.c:7368
#5  0x00007f3120033cbb in exec_assign_value (estate=0x7ffdf8f7bc30, target=0x22223a8, value=36758280, isNull=false, valtype=2249, valtypmod=-1) at ../../../../../../../src/postgres/src/pl/plpg\
sql/src/pl_exec.c:5006
#6  0x00007f3120035fce in exec_assign_expr (estate=0x7ffdf8f7bc30, target=0x22223a8, expr=0x205b778) at ../../../../../../../src/postgres/src/pl/plpgsql/src/pl_exec.c:4859
#7  0x00007f3120037de8 in exec_stmt_assign (stmt=0x203acd8, stmt=0x203acd8, estate=0x7ffdf8f7bc30) at ../../../../../../../src/postgres/src/pl/plpgsql/src/pl_exec.c:2046
#8  exec_stmt (stmt=0x203acd8, estate=0x7ffdf8f7bc30) at ../../../../../../../src/postgres/src/pl/plpgsql/src/pl_exec.c:1914
#9  exec_stmts (estate=0x7ffdf8f7bc30, stmts=<optimized out>) at ../../../../../../../src/postgres/src/pl/plpgsql/src/pl_exec.c:1877
#10 0x00007f312003b1cc in exec_stmt_block (estate=estate@entry=0x7ffdf8f7bc30, block=0x203add8) at ../../../../../../../src/postgres/src/pl/plpgsql/src/pl_exec.c:1818
#11 0x00007f312003b632 in plpgsql_exec_function (func=func@entry=0x1f12d78, fcinfo=fcinfo@entry=0x1f826b0, simple_eval_estate=simple_eval_estate@entry=0x0, atomic=atomic@entry=true) at ../../.\
./../../../../src/postgres/src/pl/plpgsql/src/pl_exec.c:587
#12 0x00007f312002b97a in plpgsql_call_handler (fcinfo=0x1f826b0) at ../../../../../../../src/postgres/src/pl/plpgsql/src/pl_handler.c:263
#13 0x000000000065b233 in ExecInterpExpr (state=0x1f825d8, econtext=0x1f82300, isnull=<optimized out>) at ../../../../../../src/postgres/src/backend/executor/execExprInterp.c:1189
#14 0x0000000000688ca6 in ExecEvalExprSwitchContext (isNull=0x7ffdf8f7bf0f, econtext=0x1f82300, state=0x1f825d8) at ../../../../../../src/postgres/src/include/executor/executor.h:313
#15 ExecProject (projInfo=0x1f825d0) at ../../../../../../src/postgres/src/include/executor/executor.h:347
#16 ExecResult (pstate=<optimized out>) at ../../../../../../src/postgres/src/backend/executor/nodeResult.c:136
#17 0x000000000065f3cb in ExecProcNode (node=0x1f821f0) at ../../../../../../src/postgres/src/include/executor/executor.h:247
#18 ExecutePlan (execute_once=<optimized out>, dest=0x27b6e18, direction=<optimized out>, numberTuples=0, sendTuples=<optimized out>, operation=CMD_SELECT, use_parallel_mode=<optimized out>, p\
lanstate=0x1f821f0, estate=0x1f81fe0)
    at ../../../../../../src/postgres/src/backend/executor/execMain.c:1729
#19 standard_ExecutorRun (queryDesc=0x1f063e0, direction=<optimized out>, count=0, execute_once=<optimized out>) at ../../../../../../src/postgres/src/backend/executor/execMain.c:365
#20 0x00007f31322c562d in ybpgm_ExecutorRun (queryDesc=0x1f063e0, direction=ForwardScanDirection, count=0, execute_once=<optimized out>) at ../../../../../src/postgres/contrib/yb_pg_metrics/yb\
_pg_metrics.c:390
#21 0x00000000007e0b7b in PortalRunSelect (portal=portal@entry=0x1f4b0e0, forward=forward@entry=true, count=0, count@entry=9223372036854775807, dest=dest@entry=0x27b6e18) at ../../../../../../\
src/postgres/src/backend/tcop/pquery.c:939
#22 0x00000000007e2239 in PortalRun (portal=portal@entry=0x1f4b0e0, count=count@entry=9223372036854775807, isTopLevel=isTopLevel@entry=true, run_once=run_once@entry=true, dest=dest@entry=0x27b\
6e18, altdest=altdest@entry=0x27b6e18, completionTag=0x7ffdf8f7c2d0 "")
    at ../../../../../../src/postgres/src/backend/tcop/pquery.c:780
#23 0x00000000007ddf5c in exec_simple_query (query_string=0x1eda190 "select composrec();") at ../../../../../../src/postgres/src/backend/tcop/postgres.c:1149
#24 0x00000000007df1ac in PostgresMain (argc=<optimized out>, argv=argv@entry=0x1f11718, dbname=0x1f115f8 "postgres", username=0x1f115d8 "postgres") at ../../../../../../src/postgres/src/backe\
nd/tcop/postgres.c:4373
#25 0x00000000004927ad in BackendRun (port=0x1f07c20) at ../../../../../../src/postgres/src/backend/postmaster/postmaster.c:4398
#26 BackendStartup (port=0x1f07c20) at ../../../../../../src/postgres/src/backend/postmaster/postmaster.c:4064
#27 ServerLoop () at ../../../../../../src/postgres/src/backend/postmaster/postmaster.c:1724
#28 0x0000000000759a68 in PostmasterMain (argc=argc@entry=19, argv=argv@entry=0x1efa330) at ../../../../../../src/postgres/src/backend/postmaster/postmaster.c:1387
#29 0x00000000006b229a in PostgresServerProcessMain (argc=19, argv=0x1efa330) at ../../../../../../src/postgres/src/backend/main/main.c:234
#30 0x00000000006b2499 in main ()

```

**Comment by kmuthukk** [comment]
Slightly different stack for the 2nd issue (temptable) issue reported above.
```
(gdb) where
#0  0x000000000049f6f0 in heap_copytuple (tuple=0x26c1ce8) at ../../../../../../../src/postgres/src/backend/access/common/heaptuple.c:741
#1  0x000000000066a81f in ExecCopySlotTuple (slot=slot@entry=0x26c0fb0) at ../../../../../../src/postgres/src/backend/executor/execTuples.c:593
#2  0x0000000000698ecf in spi_printtup (slot=0x26c0fb0, self=<optimized out>) at ../../../../../../src/postgres/src/backend/executor/spi.c:1860
#3  0x000000000065f444 in ExecutePlan (execute_once=<optimized out>, dest=0xdcce80 <spi_printtupDR>, direction=<optimized out>, numberTuples=2, sendTuples=<optimized out>, operation=CMD_SELECT\
, use_parallel_mode=<optimized out>, planstate=0x26c0dc0, estate=0x26c0bb0)
    at ../../../../../../src/postgres/src/backend/executor/execMain.c:1768
#4  standard_ExecutorRun (queryDesc=0x24a3cc8, direction=<optimized out>, count=2, execute_once=<optimized out>) at ../../../../../../src/postgres/src/backend/executor/execMain.c:365
#5  0x00007f31322c562d in ybpgm_ExecutorRun (queryDesc=0x24a3cc8, direction=ForwardScanDirection, count=2, execute_once=<optimized out>) at ../../../../../src/postgres/contrib/yb_pg_metrics/yb\
_pg_metrics.c:390
#6  0x0000000000696f5c in _SPI_pquery (tcount=2, fire_triggers=true, queryDesc=0x24a3cc8) at ../../../../../../src/postgres/src/backend/executor/spi.c:2484
#7  _SPI_execute_plan (plan=plan@entry=0x241e410, paramLI=paramLI@entry=0x0, snapshot=snapshot@entry=0x0, crosscheck_snapshot=crosscheck_snapshot@entry=0x0, read_only=read_only@entry=false, fi\
re_triggers=fire_triggers@entry=true, tcount=2)
    at ../../../../../../src/postgres/src/backend/executor/spi.c:2246
#8  0x00000000006974ec in SPI_execute_plan_with_paramlist (plan=0x241e410, params=0x0, read_only=<optimized out>, tcount=2) at ../../../../../../src/postgres/src/backend/executor/spi.c:523
#9  0x00007f3107ce766d in exec_stmt_execsql (estate=estate@entry=0x7ffdf8f7bc30, stmt=stmt@entry=0x22ffc98) at ../../../../../../../src/postgres/src/pl/plpgsql/src/pl_exec.c:4115
#10 0x00007f3107cea86b in exec_stmt (stmt=0x22ffc98, estate=0x7ffdf8f7bc30) at ../../../../../../../src/postgres/src/pl/plpgsql/src/pl_exec.c:1986
#11 exec_stmts (estate=0x7ffdf8f7bc30, stmts=<optimized out>) at ../../../../../../../src/postgres/src/pl/plpgsql/src/pl_exec.c:1877
#12 0x00007f3107ced1cc in exec_stmt_block (estate=estate@entry=0x7ffdf8f7bc30, block=0x2300248) at ../../../../../../../src/postgres/src/pl/plpgsql/src/pl_exec.c:1818
#13 0x00007f3107ced632 in plpgsql_exec_function (func=func@entry=0x1f14830, fcinfo=fcinfo@entry=0x236b500, simple_eval_estate=simple_eval_estate@entry=0x0, atomic=atomic@entry=true) at ../../.\
./../../../../src/postgres/src/pl/plpgsql/src/pl_exec.c:587
#14 0x00007f3107cdd97a in plpgsql_call_handler (fcinfo=0x236b500) at ../../../../../../../src/postgres/src/pl/plpgsql/src/pl_handler.c:263
#15 0x000000000065b233 in ExecInterpExpr (state=0x236b428, econtext=0x236b150, isnull=<optimized out>) at ../../../../../../src/postgres/src/backend/executor/execExprInterp.c:1189
#16 0x0000000000688ca6 in ExecEvalExprSwitchContext (isNull=0x7ffdf8f7bf0f, econtext=0x236b150, state=0x236b428) at ../../../../../../src/postgres/src/include/executor/executor.h:313
#17 ExecProject (projInfo=0x236b420) at ../../../../../../src/postgres/src/include/executor/executor.h:347
#18 ExecResult (pstate=<optimized out>) at ../../../../../../src/postgres/src/backend/executor/nodeResult.c:136
#19 0x000000000065f3cb in ExecProcNode (node=0x236b040) at ../../../../../../src/postgres/src/include/executor/executor.h:247
#20 ExecutePlan (execute_once=<optimized out>, dest=0x21f2488, direction=<optimized out>, numberTuples=0, sendTuples=<optimized out>, operation=CMD_SELECT, use_parallel_mode=<optimized out>, p\
lanstate=0x236b040, estate=0x236ae30)
    at ../../../../../../src/postgres/src/backend/executor/execMain.c:1729
#21 standard_ExecutorRun (queryDesc=0x1f063e0, direction=<optimized out>, count=0, execute_once=<optimized out>) at ../../../../../../src/postgres/src/backend/executor/execMain.c:365
#22 0x00007f31322c562d in ybpgm_ExecutorRun (queryDesc=0x1f063e0, direction=ForwardScanDirection, count=0, execute_once=<optimized out>) at ../../../../../src/postgres/contrib/yb_pg_metrics/yb\
_pg_metrics.c:390
#23 0x00000000007e0b7b in PortalRunSelect (portal=portal@entry=0x1f490e0, forward=forward@entry=true, count=0, count@entry=9223372036854775807, dest=dest@entry=0x21f2488) at ../../../../../../\
src/postgres/src/backend/tcop/pquery.c:939
#24 0x00000000007e2239 in PortalRun (portal=portal@entry=0x1f490e0, count=count@entry=9223372036854775807, isTopLevel=isTopLevel@entry=true, run_once=run_once@entry=true, dest=dest@entry=0x21f\
2488, altdest=altdest@entry=0x21f2488, completionTag=0x7ffdf8f7c2d0 "")
    at ../../../../../../src/postgres/src/backend/tcop/pquery.c:780
#25 0x00000000007ddf5c in exec_simple_query (query_string=0x1eda190 "select stricttest();") at ../../../../../../src/postgres/src/backend/tcop/postgres.c:1149
#26 0x00000000007df1ac in PostgresMain (argc=<optimized out>, argv=argv@entry=0x1f09ee8, dbname=0x1f09d98 "postgres", username=0x1f09d78 "postgres") at ../../../../../../src/postgres/src/backe\
nd/tcop/postgres.c:4373
#27 0x00000000004927ad in BackendRun (port=0x1f05340) at ../../../../../../src/postgres/src/backend/postmaster/postmaster.c:4398
#28 BackendStartup (port=0x1f05340) at ../../../../../../src/postgres/src/backend/postmaster/postmaster.c:4064
#29 ServerLoop () at ../../../../../../src/postgres/src/backend/postmaster/postmaster.c:1724
#30 0x0000000000759a68 in PostmasterMain (argc=argc@entry=19, argv=argv@entry=0x1efa330) at ../../../../../../src/postgres/src/backend/postmaster/postmaster.c:1387
#31 0x00000000006b229a in PostgresServerProcessMain (argc=19, argv=0x1efa330) at ../../../../../../src/postgres/src/backend/main/main.c:234
#32 0x00000000006b2499 in main ()
```

**Comment by jj-kim** [comment]
This will be fixed with issue #1152.
