### ISSUE TITLE
high intermittent system CPU when idle on local cluster setup

### ISSUE THREAD

**Issue by kmuthukk** [YugaByte/yugabyte-db#1677]
User running on CentOS (1.2.11):

`yb-ctl --rf 3 create`

setup reporting seeing  yb-tserver's periodically consuming 70%  system CPU even when idle. This intermittent pattern was seen on all 3 yb-tserver processes.

It seems like it was an after affect of some sequence of operations. The user had run a bunch of tests using Rust ORM and pgAdmin etc. 

The problem didn't reproduce when we did a fresh install on their node again.

We attached gdb to the tserver process, and the thread stack of the thread consuming the system CPU was as follows:

```
(gdb) where
#0  pthread_cond_timedwait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:225
#1  0x00007f6bda360be2 in __gthread_cond_timedwait (__abs_timeout=0x7f6bb2679ab0, __mutex=<optimized out>, __cond=0x7f6bda6a6b68 <yb::(anonymous namespace)::LongOperationTrackerHelper::Instance()::result+72>)
    at /data/yugabyte/yugabyte-1.2.11.0/linuxbrew-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/Cellar/gcc/5.5.0_4/include/c++/5.5.0/x86_64-unknown-linux-gnu/bits/gthr-default.h:871
#2  __wait_until_impl<std::chrono::duration<long, std::ratio<1l, 1000000000l> > > (__atime=..., __lock=..., this=0x7f6bda6a6b68 <yb::(anonymous namespace)::LongOperationTrackerHelper::Instance()::result+72>)
    at /data/yugabyte/yugabyte-1.2.11.0/linuxbrew-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/Cellar/gcc/5.5.0_4/include/c++/5.5.0/condition_variable:165
#3  wait_until<std::chrono::duration<long, std::ratio<1l, 1000000000l> > > (__atime=..., __lock=..., this=0x7f6bda6a6b68 <yb::(anonymous namespace)::LongOperationTrackerHelper::Instance()::result+72>)
    at /data/yugabyte/yugabyte-1.2.11.0/linuxbrew-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/Cellar/gcc/5.5.0_4/include/c++/5.5.0/condition_variable:105
#4  wait_for<long, std::ratio<1l, 1000000000l> > (__rtime=..., __lock=..., this=0x7f6bda6a6b68 <yb::(anonymous namespace)::LongOperationTrackerHelper::Instance()::result+72>)
    at /data/yugabyte/yugabyte-1.2.11.0/linuxbrew-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/Cellar/gcc/5.5.0_4/include/c++/5.5.0/condition_variable:137
#5  yb::(anonymous namespace)::LongOperationTrackerHelper::Execute (this=0x7f6bda6a6b20 <yb::(anonymous namespace)::LongOperationTrackerHelper::Instance()::result>)
    at ../../src/yb/util/debug/long_operation_tracker.cc:102
#6  0x00007f6bd5fe87a0 in ?? () from /data/yugabyte/yugabyte-1.2.11.0/linuxbrew/lib/libstdc++.so.6
#7  0x00007f6bd57fd694 in start_thread (arg=0x7f6bb267a700) at pthread_create.c:333
#8  0x00007f6bd4f3a41d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

Surprisingly, this thread didn't show up in the `http://<node:9000>/threadz` view.

**Comment by ajaxdone** [comment]
I can reproduce this issue in following steps:

1) In order to use function, I turn on this flag:
```
./bin/yb-ctl start --tserver_flags="ysql_beta_features=true"
```

2) Run diesel setup
```
diesel setup
```
for this script:
```
1   -- This file was automatically created by Diesel to setup helper functions
  1 -- and other internal bookkeeping. This file is safe to edit, any future
  2 -- changes will be added to existing projects as new migrations.
  3
  4
  5
  6
  7 -- Sets up a trigger for the given table to automatically set a column called
  8 -- `updated_at` whenever the row is modified (unless `updated_at` was included
  9 -- in the modified columns)
 10 --
 11 -- # Example
 12 --
 13 -- ```sql
 14 -- CREATE TABLE users (id SERIAL PRIMARY KEY, updated_at TIMESTAMP NOT NULL DEFAULT NOW());
 15 --
 16 -- SELECT diesel_manage_updated_at('users');
 17 -- ```
 18 CREATE OR REPLACE FUNCTION diesel_manage_updated_at(_tbl regclass) RETURNS VOID AS $$
 19 BEGIN
 20     EXECUTE format('CREATE TRIGGER set_updated_at BEFORE UPDATE ON %s
 21                     FOR EACH ROW EXECUTE PROCEDURE diesel_set_updated_at()', _tbl);
 22 END;
 23 $$ LANGUAGE plpgsql;
 24
 25 CREATE OR REPLACE FUNCTION diesel_set_updated_at() RETURNS trigger AS $$
 26 BEGIN
 27     IF (
 28         NEW IS DISTINCT FROM OLD AND
 29         NEW.updated_at IS NOT DISTINCT FROM OLD.updated_at
 30     ) THEN
 31         NEW.updated_at := current_timestamp;
 32     END IF;
 33     RETURN NEW;
 34 END;
 35 $$ LANGUAGE plpgsql;
```

3) run migration 
```
-- Your SQL goes here
CREATE TABLE users (
  email VARCHAR(100) NOT NULL UNIQUE PRIMARY KEY,
  password VARCHAR(64) NOT NULL,
  created_at TIMESTAMP NOT NULL
);

```

On ysqlsh side, generate this error:
```
ysql_simple_auth-# \d
WARNING:  terminating connection because of crash of another server process
DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
HINT:  In a moment you should be able to reconnect to the database and repeat your command.
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
The connection to the server was lost. Attempting reset: Succeeded.
ysql_simple_auth-#
```
