### ISSUE TITLE
[YSQL] [Stored Procedures] Segmentation fault on use of CURSOR 

### ISSUE THREAD

**Issue by d-uspenskiy** [yugabyte/yugabyte-db#1681]
The following sequence of command causes `Segmentation fault` in postgres process

``` 
postgres=# create table rc_test (a int, b int);

postgres=# create function return_unnamed_refcursor() returns refcursor as $$
postgres$# declare
postgres$#     rc refcursor;
postgres$# begin
postgres$#     open rc for select a from rc_test;
postgres$#     return rc;
postgres$# end
postgres$# $$ language plpgsql;

postgres=# select return_unnamed_refcursor();
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
!> 
```

Also `FETCH NEXT FROM <CURSOR>` statement is not supported

**Comment by kmuthukk** [comment]
Stack trace associated with core:

```
(gdb) where
#0  InstrEndLoop (instr=0x0) at ../../../../../../src/postgres/src/backend/executor/instrument.c:119
#1  0x00007fb64a3393af in ybpgm_ExecutorEnd (queryDesc=0x37ee370) at ../../../../../src/postgres/contrib/yb_pg_metrics/yb_pg_metrics.c:445
#2  0x000000000060c36c in PortalCleanup (portal=<optimized out>) at ../../../../../../src/postgres/src/backend/commands/portalcmds.c:300
#3  0x0000000000961b42 in PortalDrop (portal=0x34151f0, isTopCommit=<optimized out>) at ../../../../../../../src/postgres/src/backend/utils/mmgr/portalmem.c:499
#4  0x0000000000962070 in PreCommit_Portals (isPrepare=isPrepare@entry=false) at ../../../../../../../src/postgres/src/backend/utils/mmgr/portalmem.c:747
#5  0x000000000051c60c in CommitTransaction () at ../../../../../../../src/postgres/src/backend/access/transam/xact.c:2025
#6  0x000000000051cca5 in YBCCommitTransactionAndUpdateBlockState () at ../../../../../../../src/postgres/src/backend/access/transam/xact.c:2837
#7  0x00000000007de03d in finish_xact_command () at ../../../../../../src/postgres/src/backend/tcop/postgres.c:2528
#8  exec_simple_query (query_string=0x33a4190 "select return_unnamed_refcursor();") at ../../../../../../src/postgres/src/backend/tcop/postgres.c:1174
#9  0x00000000007df1ac in PostgresMain (argc=<optimized out>, argv=argv@entry=0x33db718, dbname=0x33db5f8 "postgres", username=0x33db5d8 "postgres")
    at ../../../../../../src/postgres/src/backend/tcop/postgres.c:4373
#10 0x00000000004927ad in BackendRun (port=0x33d1c20) at ../../../../../../src/postgres/src/backend/postmaster/postmaster.c:4398
#11 BackendStartup (port=0x33d1c20) at ../../../../../../src/postgres/src/backend/postmaster/postmaster.c:4064
#12 ServerLoop () at ../../../../../../src/postgres/src/backend/postmaster/postmaster.c:1724
#13 0x0000000000759a68 in PostmasterMain (argc=argc@entry=19, argv=argv@entry=0x33c4330) at ../../../../../../src/postgres/src/backend/postmaster/postmaster.c:1387
#14 0x00000000006b229a in PostgresServerProcessMain (argc=19, argv=0x33c4330) at ../../../../../../src/postgres/src/backend/main/main.c:234
#15 0x00000000006b2499 in main ()
```

**Comment by m-iancu** [comment]
Works in latest probably fixed as part of https://github.com/yugabyte/yugabyte-db/issues/2005.
