### ISSUE TITLE
[YSQL] Batch TX delete/update is failed, could not serialize access due to concurrent update REPEATABLE_READ

### ISSUE THREAD

**Issue by pilshchikov** [yugabyte/yugabyte-db#17034]
Jira Link: [DB-6347](https://yugabyte.atlassian.net/browse/DB-6347)
### Description

! Issue happen only with repeatable_read + deletes in transaction + batch statement !

Running java code like this:
```java
<default tx type TRANSACTION_REPEATABLE_READ>
connection.setAutoCommit(false);
< create table >
Statement stmt = connection.createStatement();
stmt.addBatch("BEGIN TRANSACTION");
stmt.addBatch("<some query>");
stmt.addBatch("COMMIT");
stmt.executeBatch(); <- here is an error
```

Have 3 batches
First two is running well
operation is throwing error in third batch -`DELETE FROM test_tx_3 WHERE k = 'c03ced27-3e86-4ebb-a375-74d6eb813fb3:1_6_fc7acd2f-bd35-4056-99bb-894f69f516b5'`

If throwing this error:
```
java.sql.BatchUpdateException: Batch entry 4 DELETE FROM test_tx_2 WHERE k = 'c03ced27-3e86-4ebb-a375-74d6eb813fb1:1_2_2b47b74c-5ac9-4192-ab41-689e78470e75' was aborted: ERROR: could not serialize access due to concurrent update
  Detail: Value write after transaction start: { physical: 1682479510415694 } >= { physical: 1682479510374309 }: kConflict  Call getNextException to see other errors in the batch.
	at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:165)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2402)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:574)
	at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:896)
	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:919)
	at com.yugabyte.sample.apps.SqlTransactions.doWrite(SqlTransactions.java:426)
	at com.yugabyte.sample.apps.AppBase.performWrite(AppBase.java:934)
	at com.yugabyte.sample.common.IOPSThread.run(IOPSThread.java:88)
Caused by: org.postgresql.util.PSQLException: ERROR: could not serialize access due to concurrent update
  Detail: Value write after transaction start: { physical: 1682479510415694 } >= { physical: 1682479510374309 }: kConflict
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2713)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2401)
	... 6 more
```
Batches are executed in one thread and all that happen sequentially 

Batch 1 and 2 executed successfully, third one is failed on first delete
batches: 
```
batch 1
BEGIN TRANSACTION
INSERT INTO test_tx_1(k, v1, v2, uuid, ts, random_int) VALUES ('c03ced27-3e86-4ebb-a375-74d6eb813fb3:0_0_19cb2c88-acea-4e00-9392-6804534bfdde', 'c03ced27-3e86-4ebb-a375-74d6eb813fb3:val:0', 'c03ced27-3e86-4ebb-a375-74d6eb813fb3:val:0', 'c03ced27-3e86-4ebb-a375-74d6eb813fb3', '2023-04-25 20:08:14.579-07', -595)
INSERT INTO test_tx_2(k, v1, v2, uuid, ts, random_int) VALUES ('c03ced27-3e86-4ebb-a375-74d6eb813fb3:0_1_786a34b4-4499-4a9d-82d2-1c945a776b4f', 'c03ced27-3e86-4ebb-a375-74d6eb813fb3:val:0', 'c03ced27-3e86-4ebb-a375-74d6eb813fb3:val:0', 'c03ced27-3e86-4ebb-a375-74d6eb813fb3', '2023-04-25 20:08:14.58-07', -820)
INSERT INTO test_tx_3(k, v1, v2, uuid, ts, random_int) VALUES ('c03ced27-3e86-4ebb-a375-74d6eb813fb3:0_2_956c1297-25fa-4230-969d-07ce8cd72714', 'c03ced27-3e86-4ebb-a375-74d6eb813fb3:val:0', 'c03ced27-3e86-4ebb-a375-74d6eb813fb3:val:0', 'c03ced27-3e86-4ebb-a375-74d6eb813fb3', '2023-04-25 20:08:14.581-07', -700)
INSERT INTO test_tx_4(k, v1, v2, uuid, ts, random_int) VALUES ('c03ced27-3e86-4ebb-a375-74d6eb813fb3:0_3_759bb77d-707c-4c8f-891b-14dd6e7c49f3', 'c03ced27-3e86-4ebb-a375-74d6eb813fb3:val:0', 'c03ced27-3e86-4ebb-a375-74d6eb813fb3:val:0', 'c03ced27-3e86-4ebb-a375-74d6eb813fb3', '2023-04-25 20:08:14.581-07', -349)
INSERT INTO test_tx_5(k, v1, v2, uuid, ts, random_int) VALUES ('c03ced27-3e86-4ebb-a375-74d6eb813fb3:0_4_4532bc21-f039-47bb-a6e1-92d089a0b053', 'c03ced27-3e86-4ebb-a375-74d6eb813fb3:val:0', 'c03ced27-3e86-4ebb-a375-74d6eb813fb3:val:0', 'c03ced27-3e86-4ebb-a375-74d6eb813fb3', '2023-04-25 20:08:14.581-07', -115)
INSERT INTO test_tx_6(k, v1, v2, uuid, ts, random_int) VALUES ('c03ced27-3e86-4ebb-a375-74d6eb813fb3:0_5_7bbf7ae7-04d4-4e3d-8e31-66c6bb9596e5', 'c03ced27-3e86-4ebb-a375-74d6eb813fb3:val:0', 'c03ced27-3e86-4ebb-a375-74d6eb813fb3:val:0', 'c03ced27-3e86-4ebb-a375-74d6eb813fb3', '2023-04-25 20:08:14.582-07', -554)
INSERT INTO test_tx_7(k, v1, v2, uuid, ts, random_int) VALUES ('c03ced27-3e86-4ebb-a375-74d6eb813fb3:0_6_9431d0ef-d267-4d54-8746-05f5edc34920', 'c03ced27-3e86-4ebb-a375-74d6eb813fb3:val:0', 'c03ced27-3e86-4ebb-a375-74d6eb813fb3:val:0', 'c03ced27-3e86-4ebb-a375-74d6eb813fb3', '2023-04-25 20:08:14.582-07', -932)
INSERT INTO test_tx_8(k, v1, v2, uuid, ts, random_int) VALUES ('c03ced27-3e86-4ebb-a375-74d6eb813fb3:0_7_f54ec365-c6eb-41cc-9f95-69661d9421f6', 'c03ced27-3e86-4ebb-a375-74d6eb813fb3:val:0', 'c03ced27-3e86-4ebb-a375-74d6eb813fb3:val:0', 'c03ced27-3e86-4ebb-a375-74d6eb813fb3', '2023-04-25 20:08:14.582-07', -273)
INSERT INTO test_tx_1(k, v1, v2, uuid, ts, random_int) VALUES ('c03ced27-3e86-4ebb-a375-74d6eb813fb3:0_8_c62077e9-a3ba-4ab2-96ab-a14583e15c42', 'c03ced27-3e86-4ebb-a375-74d6eb813fb3:val:0', 'c03ced27-3e86-4ebb-a375-74d6eb813fb3:val:0', 'c03ced27-3e86-4ebb-a375-74d6eb813fb3', '2023-04-25 20:08:14.583-07', -83)
INSERT INTO test_tx_2(k, v1, v2, uuid, ts, random_int) VALUES ('c03ced27-3e86-4ebb-a375-74d6eb813fb3:0_9_26276b9f-f412-42e5-a6aa-87b1ec00e4c7', 'c03ced27-3e86-4ebb-a375-74d6eb813fb3:val:0', 'c03ced27-3e86-4ebb-a375-74d6eb813fb3:val:0', 'c03ced27-3e86-4ebb-a375-74d6eb813fb3', '2023-04-25 20:08:14.583-07', -634)
COMMIT

batch 2
BEGIN TRANSACTION
DELETE FROM test_tx_6 WHERE k = 'c03ced27-3e86-4ebb-a375-74d6eb813fb3:0_5_7bbf7ae7-04d4-4e3d-8e31-66c6bb9596e5'
INSERT INTO test_tx_1(k, v1, v2, uuid, ts, random_int) VALUES ('c03ced27-3e86-4ebb-a375-74d6eb813fb3:1_1_aa3d43a2-eb58-49a6-a900-9a75321a7698', 'c03ced27-3e86-4ebb-a375-74d6eb813fb3:val:1', 'c03ced27-3e86-4ebb-a375-74d6eb813fb3:val:1', 'c03ced27-3e86-4ebb-a375-74d6eb813fb3', '2023-04-25 20:08:14.911-07', -154)
DELETE FROM test_tx_1 WHERE k = 'c03ced27-3e86-4ebb-a375-74d6eb813fb3:0_8_c62077e9-a3ba-4ab2-96ab-a14583e15c42'
UPDATE test_tx_3 SET v1='c03ced27-3e86-4ebb-a375-74d6eb813fb3:val:1' WHERE k = 'c03ced27-3e86-4ebb-a375-74d6eb813fb3:val:1'
DELETE FROM test_tx_5 WHERE k = 'c03ced27-3e86-4ebb-a375-74d6eb813fb3:0_4_4532bc21-f039-47bb-a6e1-92d089a0b053'
INSERT INTO test_tx_2(k, v1, v2, uuid, ts, random_int) VALUES ('c03ced27-3e86-4ebb-a375-74d6eb813fb3:1_5_e795f271-f38b-49f2-808e-a0a631a04903', 'c03ced27-3e86-4ebb-a375-74d6eb813fb3:val:1', 'c03ced27-3e86-4ebb-a375-74d6eb813fb3:val:1', 'c03ced27-3e86-4ebb-a375-74d6eb813fb3', '2023-04-25 20:08:14.913-07', -410)
INSERT INTO test_tx_3(k, v1, v2, uuid, ts, random_int) VALUES ('c03ced27-3e86-4ebb-a375-74d6eb813fb3:1_6_fc7acd2f-bd35-4056-99bb-894f69f516b5', 'c03ced27-3e86-4ebb-a375-74d6eb813fb3:val:1', 'c03ced27-3e86-4ebb-a375-74d6eb813fb3:val:1', 'c03ced27-3e86-4ebb-a375-74d6eb813fb3', '2023-04-25 20:08:14.914-07', -684)
INSERT INTO test_tx_4(k, v1, v2, uuid, ts, random_int) VALUES ('c03ced27-3e86-4ebb-a375-74d6eb813fb3:1_7_ad5ba368-b57e-4f2c-9d05-f9472ed4bcb9', 'c03ced27-3e86-4ebb-a375-74d6eb813fb3:val:1', 'c03ced27-3e86-4ebb-a375-74d6eb813fb3:val:1', 'c03ced27-3e86-4ebb-a375-74d6eb813fb3', '2023-04-25 20:08:14.914-07', -457)
DELETE FROM test_tx_2 WHERE k = 'c03ced27-3e86-4ebb-a375-74d6eb813fb3:0_1_786a34b4-4499-4a9d-82d2-1c945a776b4f'
INSERT INTO test_tx_5(k, v1, v2, uuid, ts, random_int) VALUES ('c03ced27-3e86-4ebb-a375-74d6eb813fb3:1_9_16866a57-3c9b-48b5-bd92-f604c042b0bb', 'c03ced27-3e86-4ebb-a375-74d6eb813fb3:val:1', 'c03ced27-3e86-4ebb-a375-74d6eb813fb3:val:1', 'c03ced27-3e86-4ebb-a375-74d6eb813fb3', '2023-04-25 20:08:14.914-07', -844)
COMMIT

batch 3
BEGIN TRANSACTION
INSERT INTO test_tx_1(k, v1, v2, uuid, ts, random_int) VALUES ('c03ced27-3e86-4ebb-a375-74d6eb813fb3:2_0_a9990fe0-f339-48e6-ba23-4757c89d3534', 'c03ced27-3e86-4ebb-a375-74d6eb813fb3:val:2', 'c03ced27-3e86-4ebb-a375-74d6eb813fb3:val:2', 'c03ced27-3e86-4ebb-a375-74d6eb813fb3', '2023-04-25 20:08:14.994-07', -378)
INSERT INTO test_tx_2(k, v1, v2, uuid, ts, random_int) VALUES ('c03ced27-3e86-4ebb-a375-74d6eb813fb3:2_1_643d94aa-624d-4613-a4fd-16ca8fe4251d', 'c03ced27-3e86-4ebb-a375-74d6eb813fb3:val:2', 'c03ced27-3e86-4ebb-a375-74d6eb813fb3:val:2', 'c03ced27-3e86-4ebb-a375-74d6eb813fb3', '2023-04-25 20:08:14.994-07', -707)
DELETE FROM test_tx_3 WHERE k = 'c03ced27-3e86-4ebb-a375-74d6eb813fb3:0_2_956c1297-25fa-4230-969d-07ce8cd72714'
UPDATE test_tx_5 SET v2='c03ced27-3e86-4ebb-a375-74d6eb813fb3:val:2' WHERE k = 'c03ced27-3e86-4ebb-a375-74d6eb813fb3:val:2'

here we have concurrent update issue error throwed ->  
DELETE FROM test_tx_3 WHERE k = 'c03ced27-3e86-4ebb-a375-74d6eb813fb3:1_6_fc7acd2f-bd35-4056-99bb-
894f69f516b5'

INSERT INTO test_tx_3(k, v1, v2, uuid, ts, random_int) VALUES ('c03ced27-3e86-4ebb-a375-74d6eb813fb3:2_5_f654ffd9-f911-4879-898b-f7f798cd5c4a', 'c03ced27-3e86-4ebb-a375-74d6eb813fb3:val:2', 'c03ced27-3e86-4ebb-a375-74d6eb813fb3:val:2', 'c03ced27-3e86-4ebb-a375-74d6eb813fb3', '2023-04-25 20:08:14.995-07', -743)
DELETE FROM test_tx_1 WHERE k = 'c03ced27-3e86-4ebb-a375-74d6eb813fb3:1_1_aa3d43a2-eb58-49a6-a900-9a75321a7698'
INSERT INTO test_tx_4(k, v1, v2, uuid, ts, random_int) VALUES ('c03ced27-3e86-4ebb-a375-74d6eb813fb3:2_7_a0dc22ad-fefa-4ef1-83d4-8aa437a0f932', 'c03ced27-3e86-4ebb-a375-74d6eb813fb3:val:2', 'c03ced27-3e86-4ebb-a375-74d6eb813fb3:val:2', 'c03ced27-3e86-4ebb-a375-74d6eb813fb3', '2023-04-25 20:08:14.996-07', -311)
DELETE FROM test_tx_4 WHERE k = 'c03ced27-3e86-4ebb-a375-74d6eb813fb3:1_7_ad5ba368-b57e-4f2c-9d05-f9472ed4bcb9'
INSERT INTO test_tx_5(k, v1, v2, uuid, ts, random_int) VALUES ('c03ced27-3e86-4ebb-a375-74d6eb813fb3:2_9_eed05300-3277-4971-8441-c95e9f66437d', 'c03ced27-3e86-4ebb-a375-74d6eb813fb3:val:2', 'c03ced27-3e86-4ebb-a375-74d6eb813fb3:val:2', 'c03ced27-3e86-4ebb-a375-74d6eb813fb3', '2023-04-25 20:08:14.997-07', -213)
COMMIT
```

env:
- 1 node cluster
- RF=1
- version `2.17.3.0-b149`

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-6347]: https://yugabyte.atlassian.net/browse/DB-6347?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by pilshchikov** [comment]
Can't reproduce. Not a issue anymore
