### ISSUE TITLE
yb-tserver crash: system_error: mutex lock failed: std::__1::__tree<>::destroy()

### ISSUE THREAD

**Issue by jaki** [yugabyte/yugabyte-db#1733]
Jira Link: [DB-1847](https://yugabyte.atlassian.net/browse/DB-1847)
Got the following on testing #1643:
```
$ cat ~/yugabyte-data/node-1/disk-1/tserver.err
In YugaByte DB, setting LC_COLLATE to C and all other locale settings to en_US.UTF-8 by default. Locale support will be enhanced as part of addressing https://github.com/YugaByte/yugabyte-db/issues/15572019-07-08 15:00:04.955 PDT [56782] LOG:  YugaByte is ENABLED in PostgreSQL. Transactions are enabled.
2019-07-08 15:00:04.957 PDT [56782] LOG:  listening on IPv4 address "127.0.0.1", port 5433
2019-07-08 15:00:04.969 PDT [56782] LOG:  redirecting log output to logging collector process
2019-07-08 15:00:04.969 PDT [56782] HINT:  Future log output will appear in directory "/Users/xxxxxxxx/yugabyte-data/node-1/disk-1/yb-data/tserver/logs".
libc++abi.dylib: *** Aborted at 1562623209 (unix time) try "date -d @1562623209" if you are using GNU date ***
terminating with uncaught exception of type std::__1::system_error: mutex lock failed: Invalid argument
PC: @        0x115d88a12 std::__1::__tree<>::destroy()
*** SIGSEGV (@0x0) received by PID 56748 (TID 0x1120495c0) stack trace: ***
    @     0x7fff67a86b5d _sigtramp
    @     0x7fff6792c02e __vfprintf
    @        0x115d88a25  std::__1::__tree<>::destroy()
    @        0x115d88a19  std::__1::__tree<>::destroy()
    @        0x115d88a19  std::__1::__tree<>::destroy()
    @        0x115d88a19  std::__1::__tree<>::destroy()
    @        0x115d88a19  std::__1::__tree<>::destroy()
    @        0x115d88a19  std::__1::__tree<>::destroy()
    @        0x115d88a19  std::__1::__tree<>::destroy()
    @        0x115d88a19  std::__1::__tree<>::destroy()
    @        0x115d88a19  std::__1::__tree<>::destroy()
    @        0x115d88a19  std::__1::__tree<>::destroy()
    @        0x115d88a19  std::__1::__tree<>::destroy()
    @        0x115d88a19  std::__1::__tree<>::destroy()
    @        0x115d88a19  std::__1::__tree<>::destroy()
    @        0x115d88a19  std::__1::__tree<>::destroy()
    @        0x115d88a19  std::__1::__tree<>::destroy()
    @        0x115d88a19  std::__1::__tree<>::destroy()
    @        0x115d88a19  std::__1::__tree<>::destroy()
    @        0x115d88a19  std::__1::__tree<>::destroy()
    @        0x115d88a19  std::__1::__tree<>::destroy()
    @        0x115d88a19  std::__1::__tree<>::destroy()
    @        0x115d88a19  std::__1::__tree<>::destroy()
    @        0x115d88a19  std::__1::__tree<>::destroy()
    @        0x115d88a19  std::__1::__tree<>::destroy()
    @        0x115d88a19  std::__1::__tree<>::destroy()
    @        0x115d88a19  std::__1::__tree<>::destroy()
    @        0x115d88a19  std::__1::__tree<>::destroy()
    @        0x115d88a19  std::__1::__tree<>::destroy()
    @        0x115d88a19  std::__1::__tree<>::destroy()
    @        0x115d88a19  std::__1::__tree<>::destroy()
    @        0x115d88a25  std::__1::__tree<>::destroy()
```

**Comment by jj-kim** [comment]
This is after running
```
$ ./bin/yb-ctl --rf 3 create --tserver_flags="redis_proxy_bind_address=0.0.0.0:6123"
```
and sending SIGINT through ctrl-c.  Here is the output of doing the above:
```
Waiting for cluster to be ready.
^CTraceback (most recent call last):
  File "./bin/yb-ctl", line 1798, in <module>
    control.run()
  File "./bin/yb-ctl", line 1771, in run
    self.args.func()
  File "./bin/yb-ctl", line 1561, in create_cmd_impl
    self.wait_for_cluster_or_raise()
  File "./bin/yb-ctl", line 1405, in wait_for_cluster_or_raise
    if not self.wait_for_cluster():
  File "./bin/yb-ctl", line 1397, in wait_for_cluster
    if not retry_call_with_timeout(call_check_for_ts, self.options.timeout):
  File "./bin/yb-ctl", line 163, in retry_call_with_timeout
    time.sleep(SLEEP_TIME_IN_SEC)
KeyboardInterrupt
2019-07-08 15:00:04,196 INFO: Starting master-1 with:
/Users/xxxxxxxx/code/yugabyte/build/latest/bin/yb-master --fs_data_dirs "/Users/xxxxxxxx/yugabyte-data/node-1/disk-1" --webserver_interface 127.0.0.1 --rpc_bind_addresses 127.0.0.1 --v 0 --version_file_json_path=/Users/xxxxxxxx/code/yugabyte/build/debug-clang-dynamic-enterprise-ninja --callhome_enabled=false --replication_factor=3 --yb_num_shards_per_tserver 2 --master_a
ddresses 127.0.0.1:7100,127.0.0.2:7100,127.0.0.3:7100 --use_initial_sys_catalog_snapshot >"/Users/xxxxxxxx/yugabyte-data/node-1/disk-1/master.out" 2>"/Users/xxxxxxxx/yugabyte-data/node-1/disk-1/master.err" &
2019-07-08 15:00:04,217 INFO: Starting master-2 with:
/Users/xxxxxxxx/code/yugabyte/build/latest/bin/yb-master --fs_data_dirs "/Users/xxxxxxxx/yugabyte-data/node-2/disk-1" --webserver_interface 127.0.0.2 --rpc_bind_addresses 127.0.0.2 --v 0 --version_file_json_path=/Users/xxxxxxxx/code/yugabyte/build/debug-clang-dynamic-enterprise-ninja --callhome_enabled=false --replication_factor=3 --yb_num_shards_per_tserver 2 --master_a
ddresses 127.0.0.1:7100,127.0.0.2:7100,127.0.0.3:7100 --use_initial_sys_catalog_snapshot >"/Users/xxxxxxxx/yugabyte-data/node-2/disk-1/master.out" 2>"/Users/xxxxxxxx/yugabyte-data/node-2/disk-1/master.err" &
2019-07-08 15:00:04,240 INFO: Starting master-3 with:
/Users/xxxxxxxx/code/yugabyte/build/latest/bin/yb-master --fs_data_dirs "/Users/xxxxxxxx/yugabyte-data/node-3/disk-1" --webserver_interface 127.0.0.3 --rpc_bind_addresses 127.0.0.3 --v 0 --version_file_json_path=/Users/xxxxxxxx/code/yugabyte/build/debug-clang-dynamic-enterprise-ninja --callhome_enabled=false --replication_factor=3 --yb_num_shards_per_tserver 2 --master_a
ddresses 127.0.0.1:7100,127.0.0.2:7100,127.0.0.3:7100 --use_initial_sys_catalog_snapshot >"/Users/xxxxxxxx/yugabyte-data/node-3/disk-1/master.out" 2>"/Users/xxxxxxxx/yugabyte-data/node-3/disk-1/master.err" &
2019-07-08 15:00:04,264 INFO: Starting tserver-1 with:
/Users/xxxxxxxx/code/yugabyte/build/latest/bin/yb-tserver --fs_data_dirs "/Users/xxxxxxxx/yugabyte-data/node-1/disk-1" --webserver_interface 127.0.0.1 --rpc_bind_addresses 127.0.0.1 --v 0 --version_file_json_path=/Users/xxxxxxxx/code/yugabyte/build/debug-clang-dynamic-enterprise-ninja --callhome_enabled=false --tserver_master_addrs=127.0.0.1:7100,127.0.0.2:7100,127.0.0.3
:7100 --memory_limit_hard_bytes=1073741824 --yb_num_shards_per_tserver=2 --redis_proxy_bind_address=127.0.0.1:6379 --cql_proxy_bind_address=127.0.0.1:9042 --local_ip_for_outbound_sockets=127.0.0.1 --use_cassandra_authentication=false --start_pgsql_proxy --pgsql_proxy_bind_address=127.0.0.1:5433 --redis_proxy_bind_address=0.0.0.0:6123 >"/Users/xxxxxxxx/yugabyte-data
/node-1/disk-1/tserver.out" 2>"/Users/xxxxxxxx/yugabyte-data/node-1/disk-1/tserver.err" &
2019-07-08 15:00:04,321 INFO: Starting tserver-2 with:
/Users/xxxxxxxx/code/yugabyte/build/latest/bin/yb-tserver --fs_data_dirs "/Users/xxxxxxxx/yugabyte-data/node-2/disk-1" --webserver_interface 127.0.0.2 --rpc_bind_addresses 127.0.0.2 --v 0 --version_file_json_path=/Users/xxxxxxxx/code/yugabyte/build/debug-clang-dynamic-enterprise-ninja --callhome_enabled=false --tserver_master_addrs=127.0.0.1:7100,127.0.0.2:7100,127.0.0.3
:7100 --memory_limit_hard_bytes=1073741824 --yb_num_shards_per_tserver=2 --redis_proxy_bind_address=127.0.0.2:6379 --cql_proxy_bind_address=127.0.0.2:9042 --local_ip_for_outbound_sockets=127.0.0.2 --use_cassandra_authentication=false --start_pgsql_proxy --pgsql_proxy_bind_address=127.0.0.2:5433 --redis_proxy_bind_address=0.0.0.0:6123 >"/Users/xxxxxxxx/yugabyte-data
/node-2/disk-1/tserver.out" 2>"/Users/xxxxxxxx/yugabyte-data/node-2/disk-1/tserver.err" &
2019-07-08 15:00:04,387 INFO: Starting tserver-3 with:
/Users/xxxxxxxx/code/yugabyte/build/latest/bin/yb-tserver --fs_data_dirs "/Users/xxxxxxxx/yugabyte-data/node-3/disk-1" --webserver_interface 127.0.0.3 --rpc_bind_addresses 127.0.0.3 --v 0 --version_file_json_path=/Users/xxxxxxxx/code/yugabyte/build/debug-clang-dynamic-enterprise-ninja --callhome_enabled=false --tserver_master_addrs=127.0.0.1:7100,127.0.0.2:7100,127.0.0.3
:7100 --memory_limit_hard_bytes=1073741824 --yb_num_shards_per_tserver=2 --redis_proxy_bind_address=127.0.0.3:6379 --cql_proxy_bind_address=127.0.0.3:9042 --local_ip_for_outbound_sockets=127.0.0.3 --use_cassandra_authentication=false --start_pgsql_proxy --pgsql_proxy_bind_address=127.0.0.3:5433 --redis_proxy_bind_address=0.0.0.0:6123 >"/Users/xxxxxxxx/yugabyte-data
/node-3/disk-1/tserver.out" 2>"/Users/xxxxxxxx/yugabyte-data/node-3/disk-1/tserver.err" &
2019-07-08 15:00:04,394 INFO: Waiting for master leader election and tablet server registration.
2019-07-08 15:00:09,575 INFO: Waiting for all tablet servers to register: 1/3
2019-07-08 15:00:15,711 ERROR: Could not find TS info ('127.0.0.1:9100') in yb-admin output: Tablet Server UUID                 RPC Host/Port
dad7434725ad47bca75cee2009d0cec6        127.0.0.2:9100

2019-07-08 15:00:21,843 ERROR: Could not find TS info ('127.0.0.1:9100') in yb-admin output: Tablet Server UUID                 RPC Host/Port
dad7434725ad47bca75cee2009d0cec6        127.0.0.2:9100

2019-07-08 15:00:27,961 ERROR: Could not find TS info ('127.0.0.1:9100') in yb-admin output: Tablet Server UUID                 RPC Host/Port
dad7434725ad47bca75cee2009d0cec6        127.0.0.2:9100

^^^ Encountered errors ^^^
```

**Comment by jj-kim** [comment]
Also, this:
```
$ ps aux | grep yb-
xxxxxxxx            56745   1.4  0.2  4508992  37504 s004  S     3:00PM   0:01.57 /Users/xxxxxxxx/code/yugabyte/build/latest/bin/yb-master --fs_data_dirs /Users/xxxxxxxx/yugabyte-data/node-3/disk-1 --webserver_interface 127.0.0.3 --rpc_bind_addresses 127.0.0.3 --v 0 --version_file_json_path=/Users/xxxxxxxx/code/yugabyte/build/debug-clang-dynamic-enterprise-ninja --callhome_
enabled=false --replication_factor=3 --yb_num_shards_per_tserver 2 --master_addresses 127.0.0.1:7100,127.0.0.2:7100,127.0.0.3:7100 --use_initial_sys_catalog_snapshot
xxxxxxxx            56751   0.2  0.3  4544164  42524 s004  S     3:00PM   0:00.73 /Users/xxxxxxxx/code/yugabyte/build/latest/bin/yb-tserver --fs_data_dirs /Users/xxxxxxxx/yugabyte-data/node-2/disk-1 --webserver_interface 127.0.0.2 --rpc_bind_addresses 127.0.0.2 --v 0 --version_file_json_path=/Users/xxxxxxxx/code/yugabyte/build/debug-clang-dynamic-enterprise-ninja --callhome
_enabled=false --tserver_master_addrs=127.0.0.1:7100,127.0.0.2:7100,127.0.0.3:7100 --memory_limit_hard_bytes=1073741824 --yb_num_shards_per_tserver=2 --redis_proxy_bind_address=127.0.0.2:6379 --cql_proxy_bind_address=127.0.0.2:9042 --local_ip_for_outbound_sockets=127.0.0.2 --use_cassandra_authentication=false --start_pgsql_proxy --pgsql_proxy_bind_address=127.0.
0.2:5433 --redis_proxy_bind_address=0.0.0.0:6123
xxxxxxxx            56739   0.1  0.2  4514112  37496 s004  S     3:00PM   0:01.64 /Users/xxxxxxxx/code/yugabyte/build/latest/bin/yb-master --fs_data_dirs /Users/xxxxxxxx/yugabyte-data/node-1/disk-1 --webserver_interface 127.0.0.1 --rpc_bind_addresses 127.0.0.1 --v 0 --version_file_json_path=/Users/xxxxxxxx/code/yugabyte/build/debug-clang-dynamic-enterprise-ninja --callhome_
enabled=false --replication_factor=3 --yb_num_shards_per_tserver 2 --master_addresses 127.0.0.1:7100,127.0.0.2:7100,127.0.0.3:7100 --use_initial_sys_catalog_snapshot
xxxxxxxx            56742   0.1  0.3  4518756  42280 s004  S     3:00PM   0:02.26 /Users/xxxxxxxx/code/yugabyte/build/latest/bin/yb-master --fs_data_dirs /Users/xxxxxxxx/yugabyte-data/node-2/disk-1 --webserver_interface 127.0.0.2 --rpc_bind_addresses 127.0.0.2 --v 0 --version_file_json_path=/Users/xxxxxxxx/code/yugabyte/build/debug-clang-dynamic-enterprise-ninja --callhome_
enabled=false --replication_factor=3 --yb_num_shards_per_tserver 2 --master_addresses 127.0.0.1:7100,127.0.0.2:7100,127.0.0.3:7100 --use_initial_sys_catalog_snapshot
xxxxxxxx            56843   0.0  0.0  4267948    588 s004  R+    3:00PM   0:00.00 grep --color=auto yb-
xxxxxxxx            56834   0.0  0.2  4576828  32040 s004  S     3:00PM   0:00.05 /Users/xxxxxxxx/code/yugabyte/build/latest/postgres/bin/postgres -D /Users/xxxxxxxx/yugabyte-data/node-2/disk-1/pg_data -p 5433 -h 127.0.0.2 -k  -c logging_collector=on -c log_directory=/Users/xxxxxxxx/yugabyte-data/node-2/disk-1/yb-data/tserver/logs -c shared_preload_libraries=yb_pg_metrics -
c yb_pg_metrics.node_name=DEFAULT_NODE_NAME -c yb_pg_metrics.port=13000
```
