### ISSUE TITLE
[Yugabyted][QA][2.18.0.0-b65] Connect YCQL is not working on Mac builds 

### ISSUE THREAD

**Issue by ankit-yb** [yugabyte/yugabyte-db#17350]
Jira Link: [DB-6545](https://yugabyte.atlassian.net/browse/DB-6545)
### Description

Steps: 1. Create a cluster and try connection to YCQLSH shell using `./bin/yugabyted connect ycql` and observe it throws 

`Traceback (most recent call last):
 File "/Users/ysharmaryugabyte.com/yugabyte-2.18.0.0/yugabyte-2.18.0.0/bin/ycqlsh.py", line 176, in <module>
  from cqlshlib import cql3handling, cqlhandling, pylexotron, sslhandling, cqlshhandling
 File "/Users/ysharmaryugabyte.com/yugabyte-2.18.0.0/yugabyte-2.18.0.0/bin/../pylib/cqlshlib/cql3handling.py", line 19, in <module>
  from cqlshlib.cqlhandling import CqlParsingRuleSet, Hint
 File "/Users/ysharmaryugabyte.com/yugabyte-2.18.0.0/yugabyte-2.18.0.0/bin/../pylib/cqlshlib/cqlhandling.py", line 22, in <module>
  from cqlshlib import pylexotron, util
 File "/Users/ysharmaryugabyte.com/yugabyte-2.18.0.0/yugabyte-2.18.0.0/bin/../pylib/cqlshlib/pylexotron.py", line 342, in <module>
  class ParsingRuleSet:
 File "/Users/ysharmaryugabyte.com/yugabyte-2.18.0.0/yugabyte-2.18.0.0/bin/../pylib/cqlshlib/pylexotron.py", line 343, in ParsingRuleSet
  RuleSpecScanner = SaferScanner([
           ^^^^^^^^^^^^^^
 File "/Users/ysharmaryugabyte.com/yugabyte-2.18.0.0/yugabyte-2.18.0.0/bin/../pylib/cqlshlib/saferscanner.py", line 91, in __init__
  s = re.sre_parse.State()
    ^^^^^^^^^^^^
AttributeError: module 're' has no attribute 'sre_parse'`

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-6545]: https://yugabyte.atlassian.net/browse/DB-6545?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by gargsans-yb** [comment]
Not a `yugabyted` issue. The issue was with ycql not working in a Mac machine. Here's the internal discussion for the [ycql issue](https://yugabyte.slack.com/archives/C3SP5KNAC/p1685011460724269)
