### ISSUE TITLE
CassandraPersonalization app ran into 'Timed out waiting for server response'

### ISSUE THREAD

**Issue by mbautin** [yugabyte/yugabyte-db#174]
Was trying to add the CassandraPersonalization to perf_itest as suggested by @robertpang. For the pure write phase with 256 writers ran into an error after initial reduction in write ops...

```
2018-03-28 16:44:31,543 test_base.py:468 INFO 2018-03-28 16:44:31,502 [INFO|com.yugabyte.sample.apps.AppBase|AppBase] Created a Cassandra table using query: [CREATE TABLE IF NOT EXISTS PerfTest_0 (  customer_id text,  store_id text,  coupon_code text,  begin_date timestamp,  end_date timestamp,  relevance_score double,  PRIMARY KEY ((customer_id, store_id), coupon_code));]
2018-03-28 16:44:36,557 test_base.py:468 INFO 2018-03-28 16:44:36,515 [INFO|com.yugabyte.sample.common.metrics.MetricsTracker|MetricsTracker] Read: 0.00 ops/sec (0.00 ms/op), 0 total ops  |  Write: 1951.21 ops/sec (94.35 ms/op), 9759 total ops  |  Uptime: 5003 ms | maxWrittenKey: 9007 | maxGeneratedKey: 10017 |
2018-03-28 16:44:41,557 test_base.py:468 INFO 2018-03-28 16:44:41,516 [INFO|com.yugabyte.sample.common.metrics.MetricsTracker|MetricsTracker] Read: 0.00 ops/sec (0.00 ms/op), 0 total ops  |  Write: 2621.95 ops/sec (97.87 ms/op), 22871 total ops  |  Uptime: 10004 ms | maxWrittenKey: 22449 | maxGeneratedKey: 23126 |
2018-03-28 16:44:46,558 test_base.py:468 INFO 2018-03-28 16:44:46,516 [INFO|com.yugabyte.sample.common.metrics.MetricsTracker|MetricsTracker] Read: 0.00 ops/sec (0.00 ms/op), 0 total ops  |  Write: 2535.33 ops/sec (99.72 ms/op), 35549 total ops  |  Uptime: 15004 ms | maxWrittenKey: 34843 | maxGeneratedKey: 35804 |
2018-03-28 16:44:51,558 test_base.py:468 INFO 2018-03-28 16:44:51,517 [INFO|com.yugabyte.sample.common.metrics.MetricsTracker|MetricsTracker] Read: 0.00 ops/sec (0.00 ms/op), 0 total ops  |  Write: 2502.18 ops/sec (102.66 ms/op), 48061 total ops  |  Uptime: 20004 ms | maxWrittenKey: 47621 | maxGeneratedKey: 48316 |
2018-03-28 16:44:56,559 test_base.py:468 INFO 2018-03-28 16:44:56,517 [INFO|com.yugabyte.sample.common.metrics.MetricsTracker|MetricsTracker] Read: 0.00 ops/sec (0.00 ms/op), 0 total ops  |  Write: 2608.24 ops/sec (98.74 ms/op), 61104 total ops  |  Uptime: 25005 ms | maxWrittenKey: 60657 | maxGeneratedKey: 61359 |
2018-03-28 16:45:01,559 test_base.py:468 INFO 2018-03-28 16:45:01,518 [INFO|com.yugabyte.sample.common.metrics.MetricsTracker|MetricsTracker] Read: 0.00 ops/sec (0.00 ms/op), 0 total ops  |  Write: 2571.95 ops/sec (99.35 ms/op), 73965 total ops  |  Uptime: 30006 ms | maxWrittenKey: 73396 | maxGeneratedKey: 74220 |
2018-03-28 16:45:06,560 test_base.py:468 INFO 2018-03-28 16:45:06,518 [INFO|com.yugabyte.sample.common.metrics.MetricsTracker|MetricsTracker] Read: 0.00 ops/sec (0.00 ms/op), 0 total ops  |  Write: 1895.63 ops/sec (74.64 ms/op), 83444 total ops  |  Uptime: 35006 ms | maxWrittenKey: 77294 | maxGeneratedKey: 83699 |
2018-03-28 16:45:11,561 test_base.py:468 INFO 2018-03-28 16:45:11,519 [INFO|com.yugabyte.sample.common.metrics.MetricsTracker|MetricsTracker] Read: 0.00 ops/sec (0.00 ms/op), 0 total ops  |  Write: 809.31 ops/sec (304.20 ms/op), 87491 total ops  |  Uptime: 40007 ms | maxWrittenKey: 84726 | maxGeneratedKey: 87746 |
2018-03-28 16:45:16,561 test_base.py:468 INFO 2018-03-28 16:45:16,519 [INFO|com.yugabyte.sample.common.metrics.MetricsTracker|MetricsTracker] Read: 0.00 ops/sec (0.00 ms/op), 0 total ops  |  Write: 208.78 ops/sec (366.44 ms/op), 88535 total ops  |  Uptime: 45007 ms | maxWrittenKey: 84726 | maxGeneratedKey: 88790 |
2018-03-28 16:45:19,737 test_base.py:468 INFO 2018-03-28 16:45:19,692 [INFO|com.yugabyte.sample.apps.AppBase|AppBase] Caught Exception:
2018-03-28 16:45:19,737 test_base.py:468 INFO com.datastax.driver.core.exceptions.OperationTimedOutException: [/<some_ip_address>:9042] Timed out waiting for server response
2018-03-28 16:45:19,737 test_base.py:468 INFO   at com.datastax.driver.core.exceptions.OperationTimedOutException.copy(OperationTimedOutException.java:44)
2018-03-28 16:45:19,738 test_base.py:468 INFO   at com.datastax.driver.core.exceptions.OperationTimedOutException.copy(OperationTimedOutException.java:26)
2018-03-28 16:45:19,738 test_base.py:468 INFO   at com.datastax.driver.core.DriverThrowables.propagateCause(DriverThrowables.java:37)
2018-03-28 16:45:19,738 test_base.py:468 INFO   at com.datastax.driver.core.DefaultResultSetFuture.getUninterruptibly(DefaultResultSetFuture.java:264)
2018-03-28 16:45:19,738 test_base.py:468 INFO   at com.datastax.driver.core.AbstractSession.execute(AbstractSession.java:68)
2018-03-28 16:45:19,738 test_base.py:468 INFO   at com.yugabyte.sample.apps.CassandraPersonalization.doWrite(CassandraPersonalization.java:220)
2018-03-28 16:45:19,738 test_base.py:468 INFO   at com.yugabyte.sample.apps.AppBase.performWrite(AppBase.java:517)
2018-03-28 16:45:19,738 test_base.py:468 INFO   at com.yugabyte.sample.common.IOPSThread.run(IOPSThread.java:87)
2018-03-28 16:45:19,738 test_base.py:468 INFO Caused by: com.datastax.driver.core.exceptions.OperationTimedOutException: [/<some_ip_address>:9042] Timed out waiting for server response
2018-03-28 16:45:19,739 test_base.py:468 INFO   at com.datastax.driver.core.RequestHandler$SpeculativeExecution.onTimeout(RequestHandler.java:772)
2018-03-28 16:45:19,739 test_base.py:468 INFO   at com.datastax.driver.core.Connection$ResponseHandler$1.run(Connection.java:1406)
2018-03-28 16:45:19,739 test_base.py:468 INFO   at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:581)
2018-03-28 16:45:19,739 test_base.py:468 INFO   at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:655)
2018-03-28 16:45:19,739 test_base.py:468 INFO   at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:367)
2018-03-28 16:45:19,739 test_base.py:468 INFO   at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
2018-03-28 16:45:19,739 test_base.py:468 INFO   at java.lang.Thread.run(Thread.java:748)
```

Around the same time, in the tserver log, yb-tserver.yb-itest-ptest-sched-gcp-20180328-160854-n3.yugabyte.log.INFO.20180328-161949.13538 (<some_ip_address>), noticed this line:
```
W0328 16:45:12.656280 13583 column_family.cc:587] T 271a11e2903545919ed029f5cd384203: [default] Stopping writes because we have 2 immutable memtables (waiting for flush), max_write_buffer_number is set to 2
...
E0328 16:45:32.214391 14030 process_context.cc:179] SQL Error: Tablet Not Found. Not found (yb/client/meta_cache.cc:602): Failed Write(tablet: 271a11e2903545919ed029f5cd384203, num_ops: 150, num_attempts: 2) to tablet 271a11e2903545919ed029f5cd384203 (no tablet server available) after 2 attempt(s): LookupByIdRpc(271a11e2903545919ed029f5cd384203, 1) failed: No such tablet found
INSERT INTO PerfTest_0 (customer_id, store_id, coupon_code, begin_date, end_date, relevance_score) VALUES (?, ?, ?, ?, ?, ?);
^^^^^^
```

Not clear why the writes are not enabled and it keeps failing for 20+ seconds. May be the writes were not set back to enabled...

All the logs from tserver/master are in /home/centos/save/20180328_182153 ('ssh -i <some_private_key> -p <some_port> centos@<some_ip_address>')

Need some folks with rocksdb to take a further look... Cc: @mbautin, @robertpang

**Comment by jasonyb** [comment]
This was inadvertently closed when subtree-merging pgtap in 89e434e248f552213f4764064a6d64e0a9342b1b because of a pgtap commit message.
