### ISSUE TITLE
[YugabyteD] [QA] [iTest Failed] YugabyteD UI Start is failing

### ISSUE THREAD

**Issue by zlareb1-yb** [yugabyte/yugabyte-db#17502]
### Description

Slack Thread for further discussion (accessible internally) - https://yugabyte.slack.com/archives/C042MSG7G2Z/p1684822012556229
**Logs:**
```
[yugabyted start] 2023-05-23 09:21:44,285 INFO:  | 29.0s | About to start yugabyted-ui with cmd /home/gargsans/yugabyte-2.19.0.0/bin/yugabyted-ui -database_host=10.150.1.230
[yugabyted start] 2023-05-23 09:21:44,299 ERROR:  | 29.0s | Traceback (most recent call last):
  File "./yugabyted", line 3699, in run
    args.func()
  File "./yugabyted", line 399, in start
    self.start_processes()
  File "./yugabyted", line 1525, in start_processes
    (_, was_started) = self.verify_start_yugabyted_ui(is_first_run, is_first_install)
  File "./yugabyted", line 1617, in verify_start_yugabyted_ui
    yugabyted_ui_process.start()
  File "./yugabyted", line 3916, in start
    self.cmd, stdout=out_log, stderr=err_log, preexec_fn=self.set_rlimits)
  File "/usr/share/python-2.7.18/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/share/python-2.7.18/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

**Comment by nchandrappa** [comment]
Code changes landed.
