### ISSUE TITLE
[yugabyted] script failing while checking for pre-reqs

### ISSUE THREAD

**Issue by gargsans-yb** [yugabyte/yugabyte-db#17548]
Jira Link: [DB-6695](https://yugabyte.atlassian.net/browse/DB-6695)
### Description

The `yugabyted start` script is failing due to an error faced while checking for pre-reqs:
```
[jenkins@ip-10-9-10-19 yugabyte-db]$ ./bin/yugabyted start --ui false
Starting yugabyted...
yugabyted crashed. For troubleshooting, contact us on https://www.yugabyte.com/slack or check our FAQ at https://docs.yugabyte.com/latest/faq/
Traceback (most recent call last):
 File "./bin/yugabyted", line 3693, in run
  args.func()
 File "./bin/yugabyted", line 389, in start
  self.start_processes()
 File "./bin/yugabyted", line 1444, in start_processes
  prereqs_check_result = self.prereqs_check(ulimits=ulimits_failed)
 File "./bin/yugabyted", line 1102, in prereqs_check
  check = self.linux_prereqs_check()
 File "./bin/yugabyted", line 1077, in linux_prereqs_check
  if not self.linux_transparent_hugepage_check():
 File "./bin/yugabyted", line 1067, in linux_transparent_hugepage_check
  thp_mode = re.search("\[(.*)\]", thp_enabled).group(1)
 File "/usr/lib64/python3.8/re.py", line 201, in search
  return _compile(pattern, flags).search(string)
TypeError: expected string or bytes-like object
```

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-6695]: https://yugabyte.atlassian.net/browse/DB-6695?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by gargsans-yb** [comment]
Temporary Code Fix Landed.
