### ISSUE TITLE
[YSQL] `SELECT *` crashes tserver while doing mass inserts

### ISSUE THREAD

**Issue by WesleyW** [YugaByte/yugabyte-db#1755]
When running the SqlInsert sample app targetted at a local yb cluster, running `select * from postgresqlkeyvalue` or `select count(*) from postgresqlkeyvalue` will either:
a. Cause the ysqlsh shell to hang. Cancel requests do not do anything, but starting a new shell will work and the sample app continues to insert.
b. Crash yb-tserver with the following FATAL log:
```
Running on machine: MacBook-Pro-2
Application fingerprint: version 1.2.12.0 build PRE_RELEASE revision 562b8d859fc7390fefd35cc2175122ca0adfc569 build_type DEBUG built at 27 Jun 2019 17:25:35 PST
Running duration (h:mm:ss): 0:00:54
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
F0710 11:56:09.522387 188559360 docdb.cc:696] Check failed: iter->read_time().global_limit >= write_time.hybrid_time() ({ physical: 1562784969176512 } vs. { physical: 1562784969247487 }) Found key: SubDocKey(DocKey(0x1962, ["2da9b33f-dafb-401b-b882-49eb0348a49b:31453"], []), [SystemColumnId(0)])
```

**Comment by spolitov** [comment]
@WesleyW could you please provide more details on this issue.
I've started local cluster with:
`bin/yb-ctl --rf 1 create`
Launched workload:
`java -jar target/yb-sample-apps.jar --workload SqlInserts --nodes 127.0.0.1:5433 --num_threads_write 4 --num_threads_read 4`
And ysqlsh just requires restart:
```~/code/yugareview $ build/latest/postgres/bin/ysqlsh -h 127.0.0.1 -p 5433
ysqlsh (11.2)
Type "help" for help.

postgres=# select count(*) from postgresqlkeyvalue;
ERROR:  Query error: Restart read required at: { read: { physical: 1562854155750654 } local_limit: { physical: 1562854155884256 } global_limit: <min> in_txn_limit: <max> serial_no: 0 }
postgres=# select count(*) from postgresqlkeyvalue;
ERROR:  Query error: Restart read required at: { read: { physical: 1562854160906815 } local_limit: { physical: 1562854160936550 } global_limit: <min> in_txn_limit: <max> serial_no: 0 }
postgres=# select count(*) from postgresqlkeyvalue;
ERROR:  Query error: Restart read required at: { read: { physical: 1562854164393293 } local_limit: { physical: 1562854164402004 } global_limit: <min> in_txn_limit: <max> serial_no: 0 }
postgres=# select count(*) from postgresqlkeyvalue;
ERROR:  Query error: Restart read required at: { read: { physical: 1562854168765122 } local_limit: { physical: 1562854169210758 } global_limit: <min> in_txn_limit: <max> serial_no: 0 }
postgres=# select count(*) from postgresqlkeyvalue;
ERROR:  Query error: Restart read required at: { read: { physical: 1562854170502934 } local_limit: { physical: 1562854170542910 } global_limit: <min> in_txn_limit: <max> serial_no: 0 }
postgres=# select count(*) from postgresqlkeyvalue;
ERROR:  Query error: Restart read required at: { read: { physical: 1562854171856981 } local_limit: { physical: 1562854171997073 } global_limit: <min> in_txn_limit: <max> serial_no: 0 }
postgres=# select count(*) from postgresqlkeyvalue;
ERROR:  Query error: Restart read required at: { read: { physical: 1562854191358321 } local_limit: { physical: 1562854191437668 } global_limit: <min> in_txn_limit: <max> serial_no: 0 }```

That is expected.

**Comment by WesleyW** [comment]
Running it again: I create a local cluster with `yb-ctl start` and then run `java -jar target/yb-sample-apps.jar  --workload SqlInserts  --nodes 127.0.0.1:5433`. I then start a shell with `./ysqlsh` and run `select count(*) from postgresqlkeyvalue ;`

The following is the ysqlsh shell output. I interrupted (cmd+c) the first `SELECT` statement after a minute. yb-tserver crashed after that.

```
10:22 $ ./bin/ysqlsh 
ysqlsh (11.2)
Type "help" for help.

postgres=# select count(*) from postgresqlkeyvalue ;
 count 
-------
  6163
(1 row)

postgres=# select count(*) from postgresqlkeyvalue ;
^CCould not send cancel request: PQcancel() -- connect() failed: Connection refused
^CCould not send cancel request: PQcancel() -- connect() failed: Connection refused
^CCould not send cancel request: PQcancel() -- connect() failed: Connection refused
FATAL:  terminating connection due to unexpected postmaster exit
ERROR:  Timed out: Read(tablet: fb525fbc108d4efaa4765d9ecf968104, num_ops: 1, num_attempts: 343, txn: 00000000-0000-0000-0000-000000000000) passed its deadline 182245.839s (passed: 60.249s): Network error (yb/util/net/socket.cc:587): Recv() got EOF from remote (error 58)
postgres=# select count(*) from postgresqlkeyvalue ;
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
!> 
```

Because yb-tserver crashed, the sample app also couldn't connect anymore:
```
136614 [Thread-4] FATAL com.yugabyte.sample.apps.SqlInserts  - Failed reading value: val:18419
org.postgresql.util.PSQLException: This connection has been closed.
	at org.postgresql.jdbc.PgConnection.checkClosed(PgConnection.java:767)
	at org.postgresql.jdbc.PgConnection.getAutoCommit(PgConnection.java:728)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:405)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:155)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:118)
	at com.yugabyte.sample.apps.SqlInserts.doRead(SqlInserts.java:112)
	at com.yugabyte.sample.apps.AppBase.performRead(AppBase.java:657)
	at com.yugabyte.sample.common.IOPSThread.run(IOPSThread.java:88)
```
Here's the last few lines of the tserver logs, which occur right after a leader election:
```
I0711 10:22:38.926030 148971520 mutable_cf_options.cc:133] T fb525fbc108d4efaa4765d9ecf968104 P 976b56d6ccbf4769be0de77e1fe2eaa2:            verify_checksums_in_compaction: 1
I0711 10:22:38.926041 148434944 mutable_cf_options.cc:135] T 54085c8dad9c4ecf8562347c8e812ec1 P 976b56d6ccbf4769be0de77e1fe2eaa2:         max_sequential_skip_in_iterations: 8
I0711 10:22:38.926053 148971520 mutable_cf_options.cc:135] T fb525fbc108d4efaa4765d9ecf968104 P 976b56d6ccbf4769be0de77e1fe2eaa2:         max_sequential_skip_in_iterations: 8
I0711 10:22:38.926148 148434944 ts_tablet_manager.cc:991] T 54085c8dad9c4ecf8562347c8e812ec1 P 976b56d6ccbf4769be0de77e1fe2eaa2: Time spent starting tablet: real 0.011s	user 0.005s	sys 0.004s
I0711 10:22:38.926152 148971520 ts_tablet_manager.cc:991] T fb525fbc108d4efaa4765d9ecf968104 P 976b56d6ccbf4769be0de77e1fe2eaa2: Time spent starting tablet: real 0.011s	user 0.005s	sys 0.004s
I0711 10:22:38.926182 148434944 ts_tablet_manager.cc:1697] Deleted transition in progress creating tablet for tablet 54085c8dad9c4ecf8562347c8e812ec1
I0711 10:22:38.926188 148971520 ts_tablet_manager.cc:1697] Deleted transition in progress creating tablet for tablet fb525fbc108d4efaa4765d9ecf968104
I0711 10:22:49.856355 162385920 log.cc:546] T fb525fbc108d4efaa4765d9ecf968104 P 976b56d6ccbf4769be0de77e1fe2eaa2: Max segment size 1048576 reached. Starting new segment allocation. 
I0711 10:22:49.857501 162385920 log.cc:454] T fb525fbc108d4efaa4765d9ecf968104 P 976b56d6ccbf4769be0de77e1fe2eaa2: Rolled over to a new segment: /Users/wesley/yugabyte-data/node-1/disk-1/yb-data/tserver/wals/table-000030a5000030008000000000004105/tablet-fb525fbc108d4efaa4765d9ecf968104/wal-000000002
I0711 10:22:49.881497 162922496 log.cc:546] T 54085c8dad9c4ecf8562347c8e812ec1 P 976b56d6ccbf4769be0de77e1fe2eaa2: Max segment size 1048576 reached. Starting new segment allocation. 
I0711 10:22:49.882663 162922496 log.cc:454] T 54085c8dad9c4ecf8562347c8e812ec1 P 976b56d6ccbf4769be0de77e1fe2eaa2: Rolled over to a new segment: /Users/wesley/yugabyte-data/node-1/disk-1/yb-data/tserver/wals/table-000030a5000030008000000000004105/tablet-54085c8dad9c4ecf8562347c8e812ec1/wal-000000002
I0711 10:23:06.263856 162385920 log.cc:546] T fb525fbc108d4efaa4765d9ecf968104 P 976b56d6ccbf4769be0de77e1fe2eaa2: Max segment size 2097152 reached. Starting new segment allocation. 
I0711 10:23:06.265714 162385920 log.cc:454] T fb525fbc108d4efaa4765d9ecf968104 P 976b56d6ccbf4769be0de77e1fe2eaa2: Rolled over to a new segment: /Users/wesley/yugabyte-data/node-1/disk-1/yb-data/tserver/wals/table-000030a5000030008000000000004105/tablet-fb525fbc108d4efaa4765d9ecf968104/wal-000000003
I0711 10:23:06.477244 162922496 log.cc:546] T 54085c8dad9c4ecf8562347c8e812ec1 P 976b56d6ccbf4769be0de77e1fe2eaa2: Max segment size 2097152 reached. Starting new segment allocation. 
I0711 10:23:06.478557 162922496 log.cc:454] T 54085c8dad9c4ecf8562347c8e812ec1 P 976b56d6ccbf4769be0de77e1fe2eaa2: Rolled over to a new segment: /Users/wesley/yugabyte-data/node-1/disk-1/yb-data/tserver/wals/table-000030a5000030008000000000004105/tablet-54085c8dad9c4ecf8562347c8e812ec1/wal-000000003
F0711 10:23:08.841159 160239616 docdb.cc:696] Check failed: iter->read_time().global_limit >= write_time.hybrid_time() ({ physical: 1562865788641080 } vs. { physical: 1562865788663224 }) Found key: SubDocKey(DocKey(0x0d21, ["7cb45236-05fc-4315-96be-18115be44bd0:25314"], []), [SystemColumnId(0)])
```

**Comment by WesleyW** [comment]
If it's expected that this shouldn't work, then it's probably non-issue. I wasn't sure so I posted. @spolitov

**Comment by spolitov** [comment]
Did you try to update, it is possible that this issue was recently fixed.
I'm unable to reproduce it with the provided steps.

What replication factor is used for this cluster? @WesleyW

**Comment by WesleyW** [comment]
Updated YB and it seems to have been fixed. You were right @spolitov . Thanks!
