### ISSUE TITLE
[CDCSDK] EXPLICIT checkpoint with ADD_TABLE is throwing UnsupportedOperationException

### ISSUE THREAD

**Issue by shamanthchandra-yb** [yugabyte/yugabyte-db#17565]
### Description

![Profile (2)](https://github.com/yugabyte/yugabyte-db/assets/109518123/1a6f1d24-2df1-47b5-8f99-023b1f54cc42)

Run report in JIRA

```
2023-05-25 20:21:46,266 WARN   YugabyteDB|db_cdc|streaming|4  Stacktrace   [io.debezium.connector.yugabytedb.YugabyteDBStreamingChangeEventSource]
org.apache.kafka.connect.errors.ConnectException: Error while processing event at offset {ccd9e5b68f734baf97b3c908fd410d11=1:2::0:0, transaction_id=null, d403c10fe252464e8091f6c669aa6fa2=1:3::0:0}
	at io.debezium.connector.yugabytedb.YugabyteDBEventDispatcher.dispatchDataChangeEvent(YugabyteDBEventDispatcher.java:154)
	at io.debezium.connector.yugabytedb.YugabyteDBStreamingChangeEventSource.getChanges2(YugabyteDBStreamingChangeEventSource.java:601)
	at io.debezium.connector.yugabytedb.YugabyteDBStreamingChangeEventSource.execute(YugabyteDBStreamingChangeEventSource.java:147)
	at io.debezium.connector.yugabytedb.YugabyteDBStreamingChangeEventSource.execute(YugabyteDBStreamingChangeEventSource.java:48)
	at io.debezium.pipeline.ChangeEventSourceCoordinator.streamEvents(ChangeEventSourceCoordinator.java:174)
	at io.debezium.connector.yugabytedb.YugabyteDBChangeEventSourceCoordinator.executeChangeEventSources(YugabyteDBChangeEventSourceCoordinator.java:144)
	at io.debezium.pipeline.ChangeEventSourceCoordinator.lambda$start$0(ChangeEventSourceCoordinator.java:109)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.UnsupportedOperationException
	at io.debezium.connector.yugabytedb.YugabyteDBTaskConnection.prepareStatement(YugabyteDBTaskConnection.java:216)
	at io.debezium.connector.yugabytedb.YugabyteDBTypeRegistry.resolveUnknownType(YugabyteDBTypeRegistry.java:441)
	at io.debezium.connector.yugabytedb.YugabyteDBTypeRegistry.get(YugabyteDBTypeRegistry.java:244)
	at io.debezium.connector.yugabytedb.connection.pgproto.YbProtoReplicationMessage.lambda$transform$0(YbProtoReplicationMessage.java:107)
	at java.base/java.util.stream.IntPipeline$1$1.accept(IntPipeline.java:180)
	at java.base/java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:104)
	at java.base/java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:699)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at io.debezium.connector.yugabytedb.connection.pgproto.YbProtoReplicationMessage.transform(YbProtoReplicationMessage.java:125)
	at io.debezium.connector.yugabytedb.connection.pgproto.YbProtoReplicationMessage.getNewTupleList(YbProtoReplicationMessage.java:92)
	at io.debezium.connector.yugabytedb.YugabyteDBChangeRecordEmitter.getNewColumnValues(YugabyteDBChangeRecordEmitter.java:138)
	at io.debezium.connector.yugabytedb.YugabyteDBChangeRecordEmitter.emitCreateRecord(YugabyteDBChangeRecordEmitter.java:311)
	at io.debezium.relational.RelationalChangeRecordEmitter.emitChangeRecords(RelationalChangeRecordEmitter.java:47)
	at io.debezium.connector.yugabytedb.YugabyteDBChangeRecordEmitter.emitChangeRecords(YugabyteDBChangeRecordEmitter.java:99)
	at io.debezium.connector.yugabytedb.YugabyteDBEventDispatcher.dispatchDataChangeEvent(YugabyteDBEventDispatcher.java:124)
	... 11 more
```

### Source connector version

1.9.5.y.22

### Connector configuration

`
add connector connector_name='ybconnector_cdc_b01f17_test_cdc_f2bc9f' stream_id='e540266092b24c25b56f9ac55c69639b' db_name='cdc_b01f17' connector_host='172.151.18.92' table_list=['test_cdc_f2bc9f'] {'name': 'ybconnector_cdc_b01f17_test_cdc_f2bc9f', 'config': {'connector.class': 'io.debezium.connector.yugabytedb.YugabyteDBConnector', 'database.hostname': '172.151.20.1', 'database.master.addresses': '172.151.17.53:7100,172.151.17.12:7100,172.151.20.1:7100', 'database.port': 5433, 'database.masterhost': '172.151.20.1', 'database.masterport': '7100', 'database.user': 'yugabyte', 'database.password': 'yugabyte', 'database.dbname': 'cdc_b01f17', 'database.server.name': 'db_cdc', 'database.streamid': 'e540266092b24c25b56f9ac55c69639b', 'snapshot.mode': 'never', 'admin.operation.timeout.ms': 600000, 'socket.read.timeout.ms': 600000, 'max.connector.retries': '10', 'operation.timeout.ms': 600000, 'topic.creation.default.compression.type': 'lz4', 'topic.creation.default.cleanup.policy': 'delete', 'topic.creation.default.partitions': 2, 'topic.creation.default.replication.factor': '1', 'tasks.max': '5', 'table.include.list': 'public.test_cdc_f2bc9f', 'connection.timeout.ms': 100000}}
`

### YugabyteDB version

2.19.1.0-b60

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

**Comment by shamanthchandra-yb** [comment]
Same issue is seen with all runs with tx;

Report link in JIRA

```
org.apache.kafka.connect.errors.ConnectException: Error while processing event at offset {transaction_id=null, 078cee93b23b4410a1928c9145b27471=2:10420::0:0}
	at io.debezium.connector.yugabytedb.YugabyteDBEventDispatcher.dispatchDataChangeEvent(YugabyteDBEventDispatcher.java:154)
	at io.debezium.connector.yugabytedb.YugabyteDBStreamingChangeEventSource.getChanges2(YugabyteDBStreamingChangeEventSource.java:601)
	at io.debezium.connector.yugabytedb.YugabyteDBStreamingChangeEventSource.execute(YugabyteDBStreamingChangeEventSource.java:147)
	at io.debezium.connector.yugabytedb.YugabyteDBStreamingChangeEventSource.execute(YugabyteDBStreamingChangeEventSource.java:48)
	at io.debezium.pipeline.ChangeEventSourceCoordinator.streamEvents(ChangeEventSourceCoordinator.java:174)
	at io.debezium.connector.yugabytedb.YugabyteDBChangeEventSourceCoordinator.executeChangeEventSources(YugabyteDBChangeEventSourceCoordinator.java:144)
	at io.debezium.pipeline.ChangeEventSourceCoordinator.lambda$start$0(ChangeEventSourceCoordinator.java:109)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.UnsupportedOperationException
	at io.debezium.connector.yugabytedb.YugabyteDBTaskConnection.prepareStatement(YugabyteDBTaskConnection.java:216)
	at io.debezium.connector.yugabytedb.YugabyteDBTypeRegistry.resolveUnknownType(YugabyteDBTypeRegistry.java:441)
	at io.debezium.connector.yugabytedb.YugabyteDBTypeRegistry.get(YugabyteDBTypeRegistry.java:244)
	at io.debezium.connector.yugabytedb.connection.pgproto.YbProtoReplicationMessage.lambda$transform$0(YbProtoReplicationMessage.java:107)
	at java.base/java.util.stream.IntPipeline$1$1.accept(IntPipeline.java:180)
	at java.base/java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:104)
	at java.base/java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:699)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at io.debezium.connector.yugabytedb.connection.pgproto.YbProtoReplicationMessage.transform(YbProtoReplicationMessage.java:125)
	at io.debezium.connector.yugabytedb.connection.pgproto.YbProtoReplicationMessage.getNewTupleList(YbProtoReplicationMessage.java:92)
	at io.debezium.connector.yugabytedb.YugabyteDBChangeRecordEmitter.getNewColumnValues(YugabyteDBChangeRecordEmitter.java:138)
	at io.debezium.connector.yugabytedb.YugabyteDBChangeRecordEmitter.emitCreateRecord(YugabyteDBChangeRecordEmitter.java:311)
	at io.debezium.relational.RelationalChangeRecordEmitter.emitChangeRecords(RelationalChangeRecordEmitter.java:47)
	at io.debezium.connector.yugabytedb.YugabyteDBChangeRecordEmitter.emitChangeRecords(YugabyteDBChangeRecordEmitter.java:99)
	at io.debezium.connector.yugabytedb.YugabyteDBEventDispatcher.dispatchDataChangeEvent(YugabyteDBEventDispatcher.java:124)
	... 11 more
```

**Comment by shamanthchandra-yb** [comment]
Verified on 2.19.1.0-b77
