### ISSUE TITLE
[CDCSDK] NullPointerException with JDBC sink connector and in getTotalEventCount (Consistency)

### ISSUE THREAD

**Issue by shamanthchandra-yb** [yugabyte/yugabyte-db#17571]
Jira Link: [DB-6718](https://yugabyte.atlassian.net/browse/DB-6718)
### Description

Single thread, TPCC run caused below error in execute phase

```
2023-05-26 08:48:11,918 WARN   YugabyteDB|yugabyte_connector|streaming|0  Empty message is being returned from poll (may indicate issues)   [io.debezium.connector.yugabytedb.consistent.Merger]
462202 2023-05-26 08:48:12,098 ERROR  ||  WorkerSinkTask{id=jdbc-sink-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted. Error: null   [org.apache.kafka.connect.runtime.Wo
462203 java.lang.NullPointerException
462204         at io.confluent.connect.jdbc.sink.JdbcDbWriter.writeConsistently(JdbcDbWriter.java:111)
462205         at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:90)
462206         at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:581)
462207         at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:333)
462208         at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:234)
462209         at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:203)
462210         at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:188)
462211         at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:243)
462212         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
462213         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
462214         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
462215         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
462216         at java.base/java.lang.Thread.run(Thread.java:829)
```

As per dev:

`This is coming from JDBC sink in case of tombstone records. `

This is to track the same.

### Source connector version

[quay.io/yugabyte/debezium-connector:1.9.5.y.101](http://quay.io/yugabyte/debezium-connector:1.9.5.y.101)

### Connector configuration

`
add connector connector_name='yugabyte_connector' stream_id='8de2738907d2455bbc0f46315bf2ca99' db_name='yugabyte' connector_host='172.151.30.237' table_list=['oorder', 'district', 'item', 'customer', 'order_line', 'new_order', 'stock', 'warehouse'] {'name': 'yugabyte_connector', 'config': {'connector.class': 'io.debezium.connector.yugabytedb.YugabyteDBConnector', 'database.hostname': '172.151.20.92', 'database.master.addresses': '172.151.20.92:7100,172.151.18.211:7100,172.151.23.163:7100', 'database.port': 5433, 'database.masterhost': '172.151.20.92', 'database.masterport': '7100', 'database.user': 'yugabyte', 'database.password': 'yugabyte', 'database.dbname': 'yugabyte', 'database.server.name': 'yugabyte_connector', 'database.streamid': '8de2738907d2455bbc0f46315bf2ca99', 'snapshot.mode': 'never', 'admin.operation.timeout.ms': 600000, 'socket.read.timeout.ms': 600000, 'max.connector.retries': '10', 'operation.timeout.ms': 600000, 'topic.creation.default.compression.type': 'lz4', 'topic.creation.default.cleanup.policy': 'delete', 'topic.creation.default.partitions': 1, 'topic.creation.default.replication.factor': '1', 'tasks.max': '1', 'table.include.list': 'public.oorder,public.district,public.item,public.customer,public.order_line,public.new_order,public.stock,public.warehouse', 'transforms': 'Reroute', 'transforms.Reroute.topic.regex': '(.*)', 'transforms.Reroute.topic.replacement': 'db_cdc_all_events', 'transforms.Reroute.type': 'io.debezium.transforms.ByLogicalTableRouter', 'transforms.Reroute.key.field.regex': 'yugabyte_connector(.*)', 'transforms.Reroute.key.field.replacement': '$1', 'consistency.mode': 'global', 'provide.transaction.metadata': 'true', 'max.poll.interval.ms': '5000'}}
`

### YugabyteDB version

Custom build

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-6718]: https://yugabyte.atlassian.net/browse/DB-6718?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by shamanthchandra-yb** [comment]
I also see this:

```
2023-05-26 08:47:04,503 WARN   YugabyteDB|yugabyte_connector|streaming|0  Stacktrace   [io.debezium.connector.yugabytedb.YugabyteDBConsistentStreamingSource]
java.lang.NullPointerException
	at io.debezium.connector.yugabytedb.YugabyteDBTransactionContext.getTotalEventCount(YugabyteDBTransactionContext.java:52)
	at io.debezium.connector.yugabytedb.YugabyteDBTransactionMonitor.endTransaction(YugabyteDBTransactionMonitor.java:164)
	at io.debezium.connector.yugabytedb.YugabyteDBTransactionMonitor.transactionCommittedEventImpl(YugabyteDBTransactionMonitor.java:138)
	at io.debezium.connector.yugabytedb.YugabyteDBEventDispatcher.dispatchTransactionCommittedEvent(YugabyteDBEventDispatcher.java:177)
	at io.debezium.connector.yugabytedb.YugabyteDBConsistentStreamingSource.dispatchMessage(YugabyteDBConsistentStreamingSource.java:376)
	at io.debezium.connector.yugabytedb.YugabyteDBConsistentStreamingSource.getChanges2(YugabyteDBConsistentStreamingSource.java:257)
	at io.debezium.connector.yugabytedb.YugabyteDBStreamingChangeEventSource.execute(YugabyteDBStreamingChangeEventSource.java:147)
	at io.debezium.connector.yugabytedb.YugabyteDBStreamingChangeEventSource.execute(YugabyteDBStreamingChangeEventSource.java:48)
	at io.debezium.pipeline.ChangeEventSourceCoordinator.streamEvents(ChangeEventSourceCoordinator.java:174)
	at io.debezium.connector.yugabytedb.YugabyteDBChangeEventSourceCoordinator.executeChangeEventSources(YugabyteDBChangeEventSourceCoordinator.java:144)
	at io.debezium.pipeline.ChangeEventSourceCoordinator.lambda$start$0(ChangeEventSourceCoordinator.java:109)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2023-05-26 08:47:24,323 INFO   ||  Committing offsets on se
```
