### ISSUE TITLE
[YSQL] PostGIS extention incompatible with Rocky 8.8

### ISSUE THREAD

**Issue by jhg03a** [yugabyte/yugabyte-db#17747]
### Description

While attempting to follow the documentation on getting postgis to work on Rocky 8.8 using release 2.18.0.1 at the last step I'm unable to load the extension properly:

```bash
./bin/ysqlsh -c "CREATE EXTENSION postgis;"
WARNING:  'analyze' is a beta feature!
HINT:  Set 'ysql_beta_features' yb-tserver gflag to true to suppress the warning for all beta features.
ERROR:  could not load library "/mnt/yugabyte-2.18.0.1/postgres/lib/postgis-3.so": /mnt/yugabyte-2.18.0.1/linuxbrew/lib/libc.so.6: version 'GLIBC_2.28' not found (required by /mnt/yugabyte-2.18.0.1/postgres/../lib/yb-thirdparty/libxml2.so.2)
```

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

**Comment by jhg03a** [comment]
### postgres
Runpath:
```bash
readelf -a postgres/bin/postgres | grep RUNPATH
 0x000000000000001d (RUNPATH)            Library runpath: [/mnt/yugabyte-2.18.0.1/lib/yb:/mnt/yugabyte-2.18.0.1/lib/postgres:/mnt/yugabyte-2.18.0.1/lib/yb-thirdparty:/mnt/yugabyte-2.18.0.1/linuxbrew/lib]
```

Loads (trimmed for brevity):
```bash
ldd postgres/bin/postgres | grep -v "=> /mnt/yugabyte-2.18.0.1"
	linux-vdso.so.1 (0x00007fff59709000)
	/mnt/yugabyte-2.18.0.1/lib/ld.so => /lib64/ld-linux-x86-64.so.2 (0x00007f7c2129c000)
```

**Comment by jhg03a** [comment]
I was able to workaround the issue by downloading the latest Centos 7.9 versions of libxml and sqlite (matching up the arch properly), extracting the relevant two .so and replacing them in `lib/yb-thirdparty/`

**Comment by giovannicandido** [comment]
I do have the same problem. Downloading libxml from centos but the libsqlite not works:

[XX000] ERROR: could not load library "/home/yugabyte/postgres/lib/postgis-3.so": /home/yugabyte/linuxbrew/lib/libc.so.6: version `GLIBC_2.28' not found (required by /home/yugabyte/postgres/../lib/yb-thirdparty/libsqlite3.so.0)

**Comment by giovannicandido** [comment]
Here is a sample docker compose to replicate:

```
version: '3'
services:
    yugabytedb:
      image: docker.io/yugabytedb/yugabyte:latest
      command: |
         bash -c '
         yum -y install https://download.postgresql.org/pub/repos/yum/reporpms/EL-8-x86_64/pgdg-redhat-repo-latest.noarch.rpm

         dnf -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
         dnf install -y dnf-plugins-core
         dnf config-manager --set-enabled powertools
         dnf -qy module disable postgresql
         yum install -y gcc gcc-c++ kernel-devel
         yum install -y postgresql11-server postgis31_11 postgis31_11-client
         curl -O http://mirror.centos.org/centos/7/updates/x86_64/Packages/libxml2-2.9.1-6.el7_9.6.x86_64.rpm
         rpm2cpio libxml2-2.9.1-6.el7_9.6.x86_64.rpm | cpio -idmv
         rm -f lib/yb-thirdparty/libxml2.so.2
         cp usr/lib64/libxml2.so.2* lib/yb-thirdparty/
         rm -rf usr
         curl -O https://rpmfind.net/linux/centos/7.9.2009/os/x86_64/Packages/sqlite-3.7.17-8.el7_7.1.x86_64.rpm
         rpm2cpio sqlite-3.7.17-8.el7_7.1.x86_64.rpm | cpio -idmv
         rm -f lib/yb-thirdparty/libsqlite3.so.0
         cp usr/lib/libsqlite3.so.0* lib/yb-thirdparty/
         cp -v "$(/usr/pgsql-11/bin/pg_config --pkglibdir)"/*postgis*.so "$(postgres/bin/pg_config --pkglibdir)" &&
         cp -v "$(/usr/pgsql-11/bin/pg_config --sharedir)"/extension/*postgis*.sql "$(postgres/bin/pg_config --sharedir)"/extension &&
         cp -v "$(/usr/pgsql-11/bin/pg_config --sharedir)"/extension/*postgis*.control "$(postgres/bin/pg_config --sharedir)"/extension
         bin/post_install.sh -e

         mkdir -p /var/ybinit
         echo "create database $${POSTGRES_DB:-$${POSTGRES_USER}};             " > /var/ybinit/01-db.sql
         echo "create user $${POSTGRES_USER} with password '\''$${POSTGRES_PASSWORD}'\'';" > /var/ybinit/02-usr.sql
         echo "alter user admin with password '\''$${POSTGRES_PASSWORD}'\'';" > /var/ybinit/03-root.sql
         # start YugabyteDB
         bin/yugabyted start --listen 0.0.0.0 --daemon=false --initial_scripts_dir=/var/ybinit --tserver_flags=ysql_enable_auth=true
         '
      environment:
        - POSTGRES_USER=testuser
        - POSTGRES_PASSWORD=1234
        - POSTGRES_DB=test
      ports:
          - 25433:5433
          - 27000:7000
 ```

Then connect and try to enable the extension:

```
CREATE EXTENSION IF NOT EXISTS "postgis";
```

**Comment by giovannicandido** [comment]
Ok figure out the work around. Now it enables the extension. I was copying sqlite lib to the work location

Here is the docker-compose file:

```
version: '3'
services:
    yugabytedb:
      image: docker.io/yugabytedb/yugabyte:latest
      command: |
         bash -c '
         yum -y install https://download.postgresql.org/pub/repos/yum/reporpms/EL-8-x86_64/pgdg-redhat-repo-latest.noarch.rpm

         dnf -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
         dnf install -y dnf-plugins-core
         dnf config-manager --set-enabled powertools
         dnf -qy module disable postgresql
         yum install -y gcc gcc-c++ kernel-devel
         yum install -y postgresql11-server postgis33_11 postgis33_11-client
         
         curl -O http://mirror.centos.org/centos/7/updates/x86_64/Packages/libxml2-2.9.1-6.el7_9.6.x86_64.rpm
         rpm2cpio libxml2-2.9.1-6.el7_9.6.x86_64.rpm | cpio -idmv
         rm -f lib/yb-thirdparty/libxml2.so.2
         cp usr/lib64/libxml2.so.2* lib/yb-thirdparty/
         rm -rf usr
         curl -O https://rpmfind.net/linux/centos/7.9.2009/os/x86_64/Packages/sqlite-3.7.17-8.el7_7.1.x86_64.rpm
         rpm2cpio sqlite-3.7.17-8.el7_7.1.x86_64.rpm | cpio -idmv
         rm -f lib/yb-thirdparty/libsqlite3.so.0
         rm -f /lib64/libsqlite3.so.0.8.6
         rm -f /lib64/libsqlite3.so
         cp usr/lib64/libsqlite3.so.0* /lib64/
         
         cp -v "$(/usr/pgsql-11/bin/pg_config --pkglibdir)"/*postgis*.so "$(postgres/bin/pg_config --pkglibdir)" &&
         cp -v "$(/usr/pgsql-11/bin/pg_config --sharedir)"/extension/*postgis*.sql "$(postgres/bin/pg_config --sharedir)"/extension &&
         cp -v "$(/usr/pgsql-11/bin/pg_config --sharedir)"/extension/*postgis*.control "$(postgres/bin/pg_config --sharedir)"/extension
         bin/post_install.sh -e
         
         mkdir -p /var/ybinit
         echo "create database $${POSTGRES_DB:-$${POSTGRES_USER}};             " > /var/ybinit/01-db.sql
         echo "create user $${POSTGRES_USER} with password '\''$${POSTGRES_PASSWORD}'\'';" > /var/ybinit/02-usr.sql
         echo "alter user admin with password '\''$${POSTGRES_PASSWORD}'\'';" > /var/ybinit/03-root.sql
         # start YugabyteDB
         bin/yugabyted start --listen 0.0.0.0 --daemon=false --initial_scripts_dir=/var/ybinit --tserver_flags=ysql_enable_auth=true
         '
      environment:
        - POSTGRES_USER=testuser
        - POSTGRES_PASSWORD=1234
        - POSTGRES_DB=test
      ports:
          - 25433:5433
          - 27000:7000
    ```

**Comment by giovannicandido** [comment]
Problem with workaround is that yum and dnf stops working:

yum install unzip
Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/libdnf/error.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: /lib64/libdnf.so.2: undefined symbol: sqlite3_expanded_sql
