### ISSUE TITLE
[YCQL] Unit test TestIndex.testDMLInAbortedTransactionWith9Indexes is failing

### ISSUE THREAD

**Issue by Arjun-yb** [yugabyte/yugabyte-db#17778]
Jira Link: [DB-6872](https://yugabyte.atlassian.net/browse/DB-6872)
### Description

Test: `TestIndex.testDMLInAbortedTransactionWith9Indexes`
**Error**:
```
Object Not Found
select * from test_txn_by_v6;
```
Stability: https://detective-gcp.dev.yugabyte.com/stability/test?analyze_trends=true&branch=master&build_type=all&class=org.yb.cql.TestIndex&fail_tag=all&name=testDMLInAbortedTransactionWith9Indexes&platform=linux
Jenkins
https://jenkins.dev.yugabyte.com/job/github-yugabyte-db-centos-master-clang16-debug/239/testReport/junit/org.yb.cql/TestIndex/testDMLInAbortedTransactionWith9Indexes/

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-6872]: https://yugabyte.atlassian.net/browse/DB-6872?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by Huqicheng** [comment]
According to https://detective-gcp.dev.yugabyte.com/stability/test?analyze_trends=true&branch=master&build_type=all&class=org.yb.cql.TestIndex&fail_tag=all&name=testDMLInAbortedTransactionWith9Indexes&num_commits=500&platform=linux

The flakiness of this test should be reduced at master.

**Comment by Huqicheng** [comment]
Now only hit failure in debug build with 

```
16:02:27.564 (main) [ERROR - org.yb.BaseYBTest$1$2.logEventDetails(BaseYBTest.java:243)] YB Java test failed: class="org.yb.cql.TestIndex", method="testDMLInAbortedTransactionWith9Indexes"
java.lang.Exception: Operation timed out after 20000ms
	at org.yb.client.TestUtils.waitFor(TestUtils.java:368)
	at org.yb.cql.BaseCQLTest.waitForReadPermsOnAllIndexes(BaseCQLTest.java:840)
	at org.yb.cql.BaseCQLTest.waitForReadPermsOnAllIndexes(BaseCQLTest.java:836)
	at org.yb.cql.TestIndex.doTestDMLInTransactionWith9Indexes(TestIndex.java:1348)
	at org.yb.cql.TestIndex.testDMLInAbortedTransactionWith9Indexes(TestIndex.java:1378)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by Huqicheng** [comment]
backfill task for test_txn_by_v9 is not started

**Comment by rthallamko3** [comment]
Backfill is failing for the test.

**Comment by m-iancu** [comment]
https://detective-gcp.dev.yugabyte.com/stability/test?analyze_trends=true&class=org.yb.cql.TestIndex&name=testDMLInAbortedTransactionWith9Indexes

Closing as there's only 1 flaky (timeout) failure in last 50 commits (400 tests runs across builds).
To revisit if failures increase again.
