### ISSUE TITLE
[DocDB] org.yb.loadtester.TestRF1Cluster#testDefaultTTLWithFixedRF fails only on TSAN build

### ISSUE THREAD

**Issue by deeps1991** [yugabyte/yugabyte-db#17809]
Jira Link: [DB-6899](https://yugabyte.atlassian.net/browse/DB-6899)
### Description

This test was enabled on TSAN, however it has been constantly failing on Detective with the following Exception:
```
junit.framework.AssertionFailedError: null
        at junit.framework.Assert.fail(Assert.java:55)
        at junit.framework.Assert.assertTrue(Assert.java:22)
        at junit.framework.Assert.assertTrue(Assert.java:31)
        at junit.framework.TestCase.assertTrue(TestCase.java:201)
        at org.yb.loadtester.TestRF1Cluster.internalTestDefaultTTL(TestRF1Cluster.java:118)
        at org.yb.loadtester.TestRF1Cluster.testDefaultTTLWithFixedRF(TestRF1Cluster.java:158)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
        at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
        at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.lang.Thread.run(Thread.java:748)
21:19:22.309 (main) [INFO - org.yb.BaseYBTest$1$2.logEventDetails(BaseYBTest.java:250)] YB Java test class="org.yb.loadtester.TestRF1Cluster", method="testDefaultTTLWithFixedRF" took 84.79 seconds
[org.yb.loadtester.TestRF1Cluster-output.txt](https://github.com/yugabyte/yugabyte-db/files/11772265/org.yb.loadtester.TestRF1Cluster-output.txt)

```

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-6899]: https://yugabyte.atlassian.net/browse/DB-6899?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by bmatican** [comment]
Seems ok in master now
