### ISSUE TITLE
[yugabyted] `yugabyted start` not working when custom `--certs_dir` is provided.

### ISSUE THREAD

**Issue by gargsans-yb** [yugabyte/yugabyte-db#17981]
Jira Link: [DB-7045](https://yugabyte.atlassian.net/browse/DB-7045)
### Description

Steps to reproduce:

1. Create certificates using yugabyted:
```
./yugabyted cert generate_server_certs --hostnames=10.150.1.230

+-----------------------------------------------------------------------------------------------------+
|                                              yugabyted                                              |
+-----------------------------------------------------------------------------------------------------+
| Status                     : Server nodes certs generation for hostnames 10.150.1.230 successful.   |
| Server node certs path     : Certs can be found at: /home/gargsans/var/generated_certs/<hostname>   |
+-----------------------------------------------------------------------------------------------------+
```
2. Start the node by providing the cert directory:
```
./yugabyted start --secure --certs_dir /home/gargsans/var/generated_certs/10.150.1.230

ERROR: --certs_dir flag needs to be accompanied with the --secure flag.
[gargsans@dev-server-sgarg bin]$ ./yugabyted start --certs_dir /home/gargsans/var/generated_certs/10.150.1.230 --secure
Traceback (most recent call last):
  File "./yugabyted", line 6317, in <module>
    ControlScript().run()
  File "./yugabyted", line 4686, in run
    self.validate_and_set_configs(args)
  File "./yugabyted", line 4301, in validate_and_set_configs
    self.validate_security_configs(args)
  File "./yugabyted", line 3860, in validate_security_configs
    args.certs_dir = os.path.expanduser(args.certs_path)
```

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-7045]: https://yugabyte.atlassian.net/browse/DB-7045?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by gargsans-yb** [comment]
Code Fix landed. Backported to 2.18
