### ISSUE TITLE
[YSQL] YSQL backend processes stuck at start-up acquiring lwlock

### ISSUE THREAD

**Issue by SteveXiSong** [yugabyte/yugabyte-db#18016]
Jira Link: [DB-7074](https://yugabyte.atlassian.net/browse/DB-7074)
### Description

They were observed in YB 2.16.2 on YBM hosts. The PG master process has died while connection processes are stuck without termination. Stack trace are as followed:

```
Executable module set to "/home/yugabyte/yb-software/yugabyte-2.16.2.1130-b1-centos-x86_64/postgres/bin/postgres".
Architecture set to: x86_64--linux-gnu.
(lldb) bt 20
* thread #1: tid = 28386, 0x00007f7fa854918a libpthread.so.0`do_futex_wait + 43 at futex-internal.h:205, name = 'postgres', stop reason = trace
  * frame #0: 0x00007f7fa854918a libpthread.so.0`do_futex_wait + 43 at futex-internal.h:205
    frame #1: 0x00007f7fa854915f libpthread.so.0`do_futex_wait(sem=0x00007f7f99d4d238, abstime=0x0000000000000000) + 15 at sem_waitcommon.c:111
    frame #2: 0x00007f7fa8549231 libpthread.so.0`__new_sem_wait_slow(sem=0x00007f7f99d4d238, abstime=0x0000000000000000) + 81 at sem_waitcommon.c:181
    frame #3: 0x0000564e5c911438 postgres`LWLockAcquire + 408
    frame #4: 0x0000564e5cabd524 postgres`write_relcache_init_file + 1188
    frame #5: 0x0000564e5cabcbd5 postgres`RelationCacheInitializePhase3 + 1349
    frame #6: 0x0000564e5cae9cce postgres`InitPostgres + 5086
    frame #7: 0x0000564e5c92a3e8 postgres`PostgresMain + 1864
    frame #8: 0x0000564e5c873766 postgres`BackendRun + 566
    frame #9: 0x0000564e5c872b62 postgres`ServerLoop + 5538
    frame #10: 0x0000564e5c86e1f6 postgres`PostmasterMain + 5574
    frame #11: 0x0000564e5c77229a postgres`PostgresServerProcessMain + 2202
    frame #12: 0x0000564e5c464cf2 postgres`main + 34
    frame #13: 0x00007f7fa7bb9825 libc.so.6`__libc_start_main(main=0x0000564e5c464cd0, argc=23, argv=0x00007ffcdee82f78, init=<unavailable>, fini=<unavailable>, rtld_fini=<unavailable>, stack_end=0x00007ffcdee82f68) + 245 at libc-start.c:289
```

Sampled two processes and both of them are stuck at acquiring the locks during writing relcache init files. Likely, there is a dead-lock case so they were never able to move on.

This is a direct cause to "tserver stuck at restarting PG in a infinite loop without properly cleaning up old hung PG processes". (#17622)

Processes snapshot
```
[centos@yb-cloud-c-35i2pu5qbjewpfuwv7mqomfiru-readonly1-n5 ~]$ ps -ef | grep postgres
yugabyte 22954 23514  0 18:47 ?        00:00:00 /home/yugabyte/yb-software/yugabyte-2.16.2.1130-b1-centos-x86_64/postgres/bin/postgres -D /mnt/d0/pg_data -p 5433 -h 0.0.0.0 -k /tmp/.yb.0.0.0.0:5433 -c unix_socket_permissions=0700 -c logging_collector=on -c log_directory=/mnt/d0/yb-data/tserver/logs -c yb_pg_metrics.node_name=yb-cloud-c-35i2pu5qbjewpfuwv7mqomfiru-readonly1-n5 -c yb_pg_metrics.port=13000 -c config_file=/mnt/d0/pg_data/ysql_pg.conf -c hba_file=/mnt/d0/pg_data/ysql_hba.conf
centos   22956 21141  0 18:47 pts/4    00:00:00 grep --color=auto postgres
yugabyte 28374     1  0 Jun28 ?        00:00:00 postgres: logger
yugabyte 28384     1  0 Jun28 ?        00:01:51 postgres: admin postgres 35.247.35.206(39168) startup
yugabyte 28386     1  0 Jun28 ?        00:01:46 postgres: admin postgres 35.247.35.206(39172) startup
yugabyte 28397     1  0 Jun28 ?        00:01:45 postgres: admin postgres 35.247.35.206(39178) startup
yugabyte 28399     1  0 Jun28 ?        00:01:49 postgres: admin postgres 35.247.35.206(39182) startup
yugabyte 28431     1  0 Jun28 ?        00:02:00 postgres: admin postgres 35.247.35.206(39214) startup
yugabyte 28487     1  0 Jun28 ?        00:01:28 postgres: admin postgres 35.247.35.206(39232) startup
yugabyte 28724     1  0 Jun28 ?        00:01:58 postgres: admin postgres 35.247.35.206(39274) startup
yugabyte 28742     1  0 Jun28 ?        00:02:12 postgres: admin postgres 35.247.35.206(39302) startup
yugabyte 28837     1  0 Jun28 ?        00:02:02 postgres: admin postgres 35.247.35.206(39318) startup
```

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-7074]: https://yugabyte.atlassian.net/browse/DB-7074?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by timothy-e** [comment]
Another case: 

```
#0  0x00007f32d07e618a in futex_abstimed_wait_cancelable (private=128, abstime=0x0, expected=0, futex_word=0x7f32c1558338) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
#1  do_futex_wait (sem=sem@entry=0x7f32c1558338, abstime=0x0) at sem_waitcommon.c:111
#2  0x00007f32d07e6231 in __new_sem_wait_slow (sem=0x7f32c1558338, abstime=0x0) at sem_waitcommon.c:181
#3  0x0000561f40885a38 in LWLockAcquire ()
#4  0x00007f32cb5554e9 in pgss_store () from /home/yugabyte/yb-software/yugabyte-2.18.2.1-b1-centos-x86_64/postgres/lib/pg_stat_statements.so
#5  0x00007f32cb5548bf in pgss_post_parse_analyze () from /home/yugabyte/yb-software/yugabyte-2.18.2.1-b1-centos-x86_64/postgres/lib/pg_stat_statements.so
#6  0x00007f32cb5180c1 in pg_hint_plan_post_parse_analyze () from /home/yugabyte/yb-software/yugabyte-2.18.2.1-b1-centos-x86_64/postgres/lib/pg_hint_plan.so
#7  0x0000561f404fb23b in parse_analyze_varparams ()
#8  0x0000561f408a98cc in exec_parse_message ()
#9  0x0000561f408a053e in PostgresMain ()
#10 0x0000561f407dffee in BackendRun ()
#11 0x0000561f407df0bc in ServerLoop ()
#12 0x0000561f407da445 in PostmasterMain ()
#13 0x0000561f406df8af in PostgresServerProcessMain ()
#14 0x0000561f403a8572 in main ()
```

**Comment by timothy-e** [comment]
Most likely caused by #19509
