### ISSUE TITLE
[yugabyted] `yugabyted start --read_replica` breaking due to recent commit for alerts API.

### ISSUE THREAD

**Issue by gargsans-yb** [yugabyte/yugabyte-db#18070]
Jira Link: [DB-7114](https://yugabyte.atlassian.net/browse/DB-7114)
### Description

Issue due to commit: https://github.com/yugabyte/yugabyte-db/commit/b92b0a51d5da84f5ae3f4bd5b6c6457a237b7174

yugabyted CLI breaks while trying to start a read replica node due to recent changes to yugabyted script for alerts API.

Error:
```
yugabyted crashed. For troubleshooting, contact us on https://www.yugabyte.com/slack or check our FAQ at https://docs.yugabyte.com/latest/faq/
Traceback (most recent call last):
  File "./bin/yugabyted", line 4695, in run
    args.func()
  File "./bin/yugabyted", line 417, in start
    self.start_rr_process()
  File "./bin/yugabyted", line 1838, in start_rr_process
    warnings.extend(prereqs_check_result['msg'][:-1])
TypeError: unhashable type
```

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-7114]: https://yugabyte.atlassian.net/browse/DB-7114?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by gargsans-yb** [comment]
Code Fix Landed.
