### ISSUE TITLE
[YSQL] Read inconsistency is seen on Yugabyte with Single Table Bank Workload

### ISSUE THREAD

**Issue by shamanthchandra-yb** [yugabyte/yugabyte-db#18277]
Jira Link: [DB-7274](https://yugabyte.atlassian.net/browse/DB-7274)
### Description

Raising this, following from:
 
https://yugabyte.slack.com/archives/C027M2T0W8Z/p1689349348293239

Though this is seen on master, we are also seeing on 2.18.2.0. Hence, we are trying to bisect and see on 2.18.2.0 builds, because it would have fewer commits.

Run is here: http://stress.dev.yugabyte.com/stress_test/640d2353-de2a-47cc-a024-d489a2275b98

Though we discovered this while CDC testing is going on, we were able to find it even in without CDC setup.

```
2023-07-14 12:25:23,350 [Thread-1] INFO MetricsTracker - Read: 0.00 ops/sec (0.00 ms/op), 106 total ops  |  Write: 306.18 ops/sec (29.76 ms/op), 589035 total ops  |  Uptime: 2055199 ms | 
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
2023-07-14 12:25:25,218 [Thread-102] ERROR ExceptionsTracker - Failed to compare sums: Expected 1000001 - actual 1000000 
java.lang.AssertionError: Expected 1000001 - actual 1000000 
	at com.yugabyte.sample.apps.SqlBankTransfer.doRead(SqlBankTransfer.java:208) [yb-stress-sample-apps-1.1.9.jar:?]
	at com.yugabyte.sample.apps.AppBase.performRead(AppBase.java:991) [yb-stress-sample-apps-1.1.9.jar:?]
	at com.yugabyte.sample.common.IOPSThread.run(IOPSThread.java:89) [yb-stress-sample-apps-1.1.9.jar:?]
2023-07-14 12:25:25,418 [main] INFO Main - The sample app has finished
```

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-7274]: https://yugabyte.atlassian.net/browse/DB-7274?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by shamanthchandra-yb** [comment]
This looks like issue from stress sample apps, and the issue was around "First read transaction was failed to commit, but we got expected sum from there". On latest version 1.1.11, so far not seeing this issue. Hence closing it.
