### ISSUE TITLE
GitHub CI no space left on device

### ISSUE THREAD

**Issue by jasonyb** [yugabyte/yugabyte-db#18361]
### Description

Commit 961042ad7c32de7188914ff3f268cbc2e3dbefe5 increases space for GitHub actions, but recent run failed: https://github.com/yugabyte/yugabyte-db/actions/runs/5626344736/job/15246967183

```
  /-------------------------------------------------------------------------------
  | COMPILATION FAILED
  |-------------------------------------------------------------------------------
  ../../src/yb/yql/pgwrapper/pg_get_lock_status-test.cc:459:1: fatal error: error writing to /tmp/ccvLpf6c.s: No space left on device
    459 | } // namespace yb
        | ^
  compilation terminated.
```

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

**Comment by jasonyb** [comment]
```
   Error:  Failed to execute goal on project yb-cql-4x: Could not resolve dependencies for project org.yb:yb-cql-4x:jar:0.8.62-SNAPSHOT: The following artifacts could not be resolved: org.apache.hadoop:hadoop-client-runtime:jar:3.3.2, org.apache.spark:spark-sql_2.12:jar:3.3.1, org.rocksdb:rocksdbjni:jar:6.20.3, org.apache.spark:spark-catalyst_2.12:jar:3.3.1, org.apache.arrow:arrow-vector:jar:7.0.0, com.yugabyte:java-driver-core-shaded:jar:4.6.0-yb-11: Could not transfer artifact org.apache.hadoop:hadoop-client-runtime:jar:3.3.2 from/to central (https://repo.maven.apache.org/maven2): GET request of: org/apache/hadoop/hadoop-client-runtime/3.3.2/hadoop-client-runtime-3.3.2.jar from central failed: No space left on device -> [Help 1]
```

https://github.com/yugabyte/yugabyte-db/actions/runs/5835987848/job/15828635321#step:4:3732

**Comment by jasonyb** [comment]
https://github.com/yugabyte/yugabyte-db/actions/runs/5945654128/job/16125057849#step:4:3425: `Error:  Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M1:enforce (default) on project yb-parent: Execution default of goal org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M1:enforce failed: Plugin org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M1 or one of its dependencies could not be resolved: The following artifacts could not be resolved: org.apache.commons:commons-lang3:jar:3.5, commons-codec:commons-codec:jar:1.6, org.beanshell:bsh:jar:2.0b4, org.apache.maven.shared:maven-dependency-tree:jar:2.2, org.eclipse.aether:aether-util:jar:0.9.0.M2, org.apache.maven:maven-compat:jar:3.0, org.apache.maven.wagon:wagon-provider-api:jar:1.0-beta-6: Could not transfer artifact org.apache.commons:commons-lang3:jar:3.5 from/to central (https://repo.maven.apache.org/maven2): GET request of: org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar from central failed: No space left on device -> [Help 1`

https://github.com/yugabyte/yugabyte-db/actions/runs/5945654128:

```
GCC 11, release, CentOS 7
Unhandled exception. System.IO.IOException: No space left on device : '/home/runner/runners/2.308.0/_diag/Worker_20230823-005252-utc.log'
   at System.IO.RandomAccess.WriteAtOffset(SafeFileHandle handle, ReadOnlySpan`1 buffer, Int64 fileOffset)
   at System.IO.Strategies.BufferedFileStreamStrategy.FlushWrite()
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.Diagnostics.TextWriterTraceListener.Flush()
   at System.Diagnostics.TraceSource.Flush()
   at GitHub.Runner.Common.TraceManager.Dispose(Boolean disposing)
   at GitHub.Runner.Common.TraceManager.Dispose()
   at GitHub.Runner.Common.HostContext.Dispose(Boolean disposing)
   at GitHub.Runner.Common.HostContext.Dispose()
   at GitHub.Runner.Worker.Program.Main(String[] args)
System.IO.IOException: No space left on device : '/home/runner/runners/2.308.0/_diag/Worker_20230823-005252-utc.log'
   at System.IO.RandomAccess.WriteAtOffset(SafeFileHandle handle, ReadOnlySpan`1 buffer, Int64 fileOffset)
   at System.IO.Strategies.BufferedFileStreamStrategy.FlushWrite()
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.Diagnostics.TextWriterTraceListener.Flush()
   at GitHub.Runner.Common.HostTraceListener.WriteHeader(String source, TraceEventType eventType, Int32 id)
   at GitHub.Runner.Common.HostTraceListener.TraceEvent(TraceEventCache eventCache, String source, TraceEventType eventType, Int32 id, String message)
   at System.Diagnostics.TraceSource.TraceEvent(TraceEventType eventType, Int32 id, String message)
   at GitHub.Runner.Worker.Worker.RunAsync(String pipeIn, String pipeOut)
   at GitHub.Runner.Worker.Program.MainAsync(IHostContext context, String[] args)
System.IO.IOException: No space left on device : '/home/runner/runners/2.308.0/_diag/Worker_20230823-005252-utc.log'
   at System.IO.RandomAccess.WriteAtOffset(SafeFileHandle handle, ReadOnlySpan`1 buffer, Int64 fileOffset)
   at System.IO.Strategies.BufferedFileStreamStrategy.FlushWrite()
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.Diagnostics.TextWriterTraceListener.Flush()
   at GitHub.Runner.Common.HostTraceListener.WriteHeader(String source, TraceEventType eventType, Int32 id)
   at GitHub.Runner.Common.HostTraceListener.TraceEvent(TraceEventCache eventCache, String source, TraceEventType eventType, Int32 id, String message)
   at System.Diagnostics.TraceSource.TraceEvent(TraceEventType eventType, Int32 id, String message)
   at GitHub.Runner.Common.Tracing.Error(Exception exception)
   at GitHub.Runner.Worker.Program.MainAsync(IHostContext context, String[] args)
```

**Comment by jasonyb** [comment]
https://github.com/yugabyte/yugabyte-db/actions/runs/6090061357/job/16524156388
