### ISSUE TITLE
[CDCSDK] On build 2.18.2.0-b86, Snapshot cases seeing SAFEPOINT exceptions and NullPointerException

### ISSUE THREAD

**Issue by shamanthchandra-yb** [yugabyte/yugabyte-db#18464]
Jira Link: [DB-7437](https://yugabyte.atlassian.net/browse/DB-7437)
### Description

Please refer JIRA for stress run link.

```
2023-07-27 16:28:13,333 WARN   YugabyteDB|db_cdc|snapshot|2  Error while trying to get the snapshot from the server; will attempt retry 1 of 10 after 60000 milli-seconds. Exception: {}   [io.debezium.connector.yugabytedb.YugabyteDBSnapshotChangeEventSource]
java.lang.IllegalArgumentException: Unknown operation 'SAFEPOINT' in replication stream message commit_time: 6924186787249807360
table: "test_cdc_29aa7a"
op: SAFEPOINT
pgschema_name: "public"

	at io.debezium.connector.yugabytedb.connection.pgproto.YbProtoReplicationMessage.getOperation(YbProtoReplicationMessage.java:66)
	at io.debezium.connector.yugabytedb.connection.ReplicationMessage.isTransactionalMessage(ReplicationMessage.java:193)
	at io.debezium.connector.yugabytedb.YugabyteDBSnapshotChangeEventSource.doExecute(YugabyteDBSnapshotChangeEventSource.java:435)
	at io.debezium.connector.yugabytedb.YugabyteDBSnapshotChangeEventSource.execute(YugabyteDBSnapshotChangeEventSource.java:136)
	at io.debezium.connector.yugabytedb.YugabyteDBSnapshotChangeEventSource.execute(YugabyteDBSnapshotChangeEventSource.java:46)
	at io.debezium.pipeline.ChangeEventSourceCoordinator.doSnapshot(ChangeEventSourceCoordinator.java:155)
	at io.debezium.connector.yugabytedb.YugabyteDBChangeEventSourceCoordinator.executeChangeEventSources(YugabyteDBChangeEventSourceCoordinator.java:108)
	at io.debezium.pipeline.ChangeEventSourceCoordinator.lambda$start$0(ChangeEventSourceCoordinator.java:109)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2023-07-27 16:28:13,335 WARN   YugabyteDB|db_cdc|snapshot|1  Error while 
```

```
java.lang.NullPointerException
	at io.debezium.connector.yugabytedb.YugabyteDBSnapshotChangeEventSource.doExecute(YugabyteDBSnapshotChangeEventSource.java:398)
	at io.debezium.connector.yugabytedb.YugabyteDBSnapshotChangeEventSource.execute(YugabyteDBSnapshotChangeEventSource.java:136)
	at io.debezium.connector.yugabytedb.YugabyteDBSnapshotChangeEventSource.execute(YugabyteDBSnapshotChangeEventSource.java:46)
	at io.debezium.pipeline.ChangeEventSourceCoordinator.doSnapshot(ChangeEventSourceCoordinator.java:155)
	at io.debezium.connector.yugabytedb.YugabyteDBChangeEventSourceCoordinator.executeChangeEventSources(YugabyteDBChangeEventSourceCoordinator.java:108)
	at io.debezium.pipeline.ChangeEventSourceCoordinator.lambda$start$0(ChangeEventSourceCoordinator.java:109)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

### Source connector version

1.9.5.y.33-SNAPSHOT

### Connector configuration

```
add connector connector_name='ybconnector_cdc_fb1ef9_test_cdc_29aa7a' stream_id='f27b3af6fbae4b4781142209b7df643b' db_name='cdc_fb1ef9' connector_host='172.151.18.181' table_list=['test_cdc_29aa7a'] {'name': 'ybconnector_cdc_fb1ef9_test_cdc_29aa7a', 'config': {'connector.class': 'io.debezium.connector.yugabytedb.YugabyteDBConnector', 'database.hostname': '172.151.30.30', 'database.master.addresses': '172.151.29.232:7100,172.151.30.30:7100,172.151.25.16:7100', 'database.port': 5433, 'database.masterhost': '172.151.30.30', 'database.masterport': '7100', 'database.user': 'yugabyte', 'database.password': 'yugabyte', 'database.dbname': 'cdc_fb1ef9', 'database.server.name': 'db_cdc', 'database.streamid': 'f27b3af6fbae4b4781142209b7df643b', 'snapshot.mode': 'initial', 'admin.operation.timeout.ms': 600000, 'socket.read.timeout.ms': 600000, 'max.connector.retries': '10', 'operation.timeout.ms': 600000, 'topic.creation.default.compression.type': 'lz4', 'topic.creation.default.cleanup.policy': 'delete', 'topic.creation.default.partitions': 2, 'topic.creation.default.replication.factor': '1', 'tasks.max': '5', 'table.include.list': 'public.test_cdc_29aa7a', 'max.poll.interval.ms': '5000'}}
```

### YugabyteDB version

2.18.2.0-b86

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-7437]: https://yugabyte.atlassian.net/browse/DB-7437?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by adithya-yb** [comment]
Fixed, tracked through: https://yugabyte.atlassian.net/browse/DB-7439
