### ISSUE TITLE
[yugabyted] yb-docker-ctl broken

### ISSUE THREAD

**Issue by stelb** [yugabyte/yugabyte-db#18472]
### Description

./yb-docker-ctl create fails with python exception

root@docker02:~/yugabyte# ./yb-docker-ctl create
Traceback (most recent call last):
  File "./yb-docker-ctl", line 545, in <module>
    YBDockerControl().run()
  File "./yb-docker-ctl", line 518, in run
    self.create_clusters()
  File "./yb-docker-ctl", line 370, in create_clusters
    self.start_cluster(server_type, node_id, None)
  File "./yb-docker-ctl", line 332, in start_cluster
    server_cmds.extend(['--fs_data_dirs={}'.format(",".join(self.volumes))])
TypeError: can only join an iterable

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

**Comment by stelb** [comment]
The reason is, that the script uses .ContainerConfig to get image volumes:

CONTAINER_CONFIG_CMD = 'docker inspect -f "{{json .ContainerConfig.%s}}" %s'

with current image 

`yugabytedb/yugabyte      latest    405b30e0f958   6 weeks ago   1.91GB`

.ContainerConfig does not contain Volumes:

```
        "ContainerConfig": {
            "Hostname": "",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": null,
            "Cmd": null,
            "Image": "",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": null
        },
```

needed values are in .Config:
```

        "Config": {
---
            "Volumes": {
                "/mnt/disk0": {},
                "/mnt/disk1": {}
            },
...
```

I'm not deep down in docker, but as far as I understand .ContainerConfig is .Config of last image used to build current one.
Maybe it worked sometime ago and then image building changed. Either way, I think .Config should be used.
