### ISSUE TITLE
[yugabyted] yugabyted-ui doesn't start when --advertise_address=0.0.0.0

### ISSUE THREAD

**Issue by FranckPachot** [yugabyte/yugabyte-db#18580]
Jira Link: [DB-7514](https://yugabyte.atlassian.net/browse/DB-7514)
### Description

`--advertise_address=0.0.0.0` can be used on Docker containers that change their IP when restarted. 
However, the UI doesn't start:

It tries every 5 seconds:
```
[yugabyted start] 2023-08-07 09:26:31,170 ERROR:  | 408.0s | Webserver died unexpectedly. Restarting...
[yugabyted start] 2023-08-07 09:26:31,170 INFO:  | 408.0s | About to start yugabyted-ui with cmd /home/yugabyte/bin/yugabyted-ui -database_host=0.0.0.0
[yugabyted start] 2023-08-07 09:26:31,187 INFO:  | 408.0s | yugabyted-ui started running with PID 746.
[yugabyted start] 2023-08-07 09:26:36,704 ERROR:  | 413.5s | Webserver died unexpectedly. Restarting...
[yugabyted start] 2023-08-07 09:26:36,704 INFO:  | 413.5s | About to start yugabyted-ui with cmd /home/yugabyte/bin/yugabyted-ui -database_host=0.0.0.0
[yugabyted start] 2023-08-07 09:26:36,708 INFO:  | 413.5s | yugabyted-ui started running with PID 753.
```

It fails because it tries to connect to `0.0.0.0` rather than the master and tserver addresses:
```
panic: no valid connect address for host: [HostInfo hostname="0.0.0.0" connectAddress="0.0.0.0" peer="<nil>" rpc_address="<nil>" broadcast_address="<nil>" preferred_ip="<nil>" connect_addr="0.0.0.0" connect_addr_source="invalid" port=9042 data_centre="" rack="" host_id="" version="v0.0.0" state=UP num_tokens=0]. Is your cluster configured correctly?

goroutine 1 [running]:
github.com/yugabyte/gocql.(*HostInfo).ConnectAddress(0xc000180000)
        /var/lib/jenkins/go/pkg/mod/github.com/yugabyte/gocql@v0.0.0-20220204171058-0bd8e6cb12d0/host_source.go:187 +0x174
github.com/yugabyte/gocql.(*Session).dialWithoutObserver(0xc00012e700, {0xf52a30, 0xc0000ae870}, 0xc000180000, 0xc000144360, {0xf4dda0?, 0xeb3d20})
        /var/lib/jenkins/go/pkg/mod/github.com/yugabyte/gocql@v0.0.0-20220204171058-0bd8e6cb12d0/conn.go:226 +0x71
github.com/yugabyte/gocql.(*Session).dial(0xc00012e700, {0xf52a30?, 0xc0000ae870?}, 0xab3ba0?, 0x1?, {0xf4dda0?, 0xeb3d20?})
        /var/lib/jenkins/go/pkg/mod/github.com/yugabyte/gocql@v0.0.0-20220204171058-0bd8e6cb12d0/conn.go:211 +0x10c
github.com/yugabyte/gocql.(*controlConn).discoverProtocol(0xc0000aba40, {0xc0000d2120?, 0x0?, 0xc0001137b8?})
        /var/lib/jenkins/go/pkg/mod/github.com/yugabyte/gocql@v0.0.0-20220204171058-0bd8e6cb12d0/control.go:230 +0x125
github.com/yugabyte/gocql.(*Session).init(0xc00012e700)
        /var/lib/jenkins/go/pkg/mod/github.com/yugabyte/gocql@v0.0.0-20220204171058-0bd8e6cb12d0/session.go:198 +0x12e
github.com/yugabyte/gocql.NewSession({{0xc00016e1e0, 0x1, 0x1}, {0xaeca93, 0x5}, 0x0, 0x2cb417800, 0x23c34600, 0x2352, {0x0, ...}, ...})
        /var/lib/jenkins/go/pkg/mod/github.com/yugabyte/gocql@v0.0.0-20220204171058-0bd8e6cb12d0/session.go:173 +0x9c8
github.com/yugabyte/gocql.(*ClusterConfig).CreateSession(...)
        /var/lib/jenkins/go/pkg/mod/github.com/yugabyte/gocql@v0.0.0-20220204171058-0bd8e6cb12d0/cluster.go:205
main.main()
        /nfusr/alma8-gcp-cloud/jenkins-worker-kowabj/jenkins/jenkins-github-yugabyte-db-alma8-master-clang15-release-1704/yugabyte-db/yugabyted-ui/apiserver/cmd/server/main.go:118 +0x1a5
panic: no valid connect address for host: [HostInfo hostname="0.0.0.0" connectAddress="0.0.0.0" peer="<nil>" rpc_address="<nil>" broadcast_address="<nil>" preferred_ip="<nil>" connect_addr="0.0.0.0" connect_addr_source="invalid" port=9042 data_centre="" rack="" host_id="" version="v0.0.0" state=UP num_tokens=0]. Is your cluster configured correctly?
```

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-7514]: https://yugabyte.atlassian.net/browse/DB-7514?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by nchandrappa** [comment]
Code changes landed.
