### ISSUE TITLE
[DocDB] Gflag upgrade is failing with 'Under-replicated tablet size'

### ISSUE THREAD

**Issue by shamanthchandra-yb** [yugabyte/yugabyte-db#18717]
Jira Link: [DB-7618](https://yugabyte.atlassian.net/browse/DB-7618)
### Description

In our packed toggle on/off where we do rolling restart iteratively with gflag ON and OFF. We are seeing rolling restart task getting failed because of below reason:

Run Report in JIRA (Shared run on build 2.19.2.0-b75)

![Profile (2)](https://github.com/yugabyte/yugabyte-db/assets/109518123/e294691f-fd27-4790-be7f-4f3b8cb48f6f)

```
java.lang.RuntimeException: SubTaskGroup CheckUnderReplicatedTables of type UpdatingGFlags at position 2: completed 1 out of 1 tasks failed.
	at com.yugabyte.yw.commissioner.TaskExecutor$RunnableTask.runSubTasks(TaskExecutor.java:1168)
	at com.yugabyte.yw.commissioner.TaskExecutor$RunnableTask.runSubTasks(TaskExecutor.java:1123)
	at com.yugabyte.yw.commissioner.UpgradeTaskBase.runUpgrade(UpgradeTaskBase.java:109)
	at com.yugabyte.yw.commissioner.tasks.upgrade.GFlagsUpgrade.run(GFlagsUpgrade.java:61)
	at com.yugabyte.yw.commissioner.TaskExecutor$AbstractRunnableTask.run(TaskExecutor.java:823)
	at com.yugabyte.yw.commissioner.TaskExecutor$RunnableTask.run(TaskExecutor.java:1036)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.yugabyte.yw.common.logging.MDCAwareRunnable.run(MDCAwareRunnable.java:46)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.RuntimeException: CheckUnderReplicatedTablets, timing out after retrying 11 times for a duration of 697148ms, greater than max time out of 600000ms. Under-replicated tablet size: 41. Failing...
	at com.yugabyte.yw.commissioner.tasks.subtasks.CheckUnderReplicatedTablets.run(CheckUnderReplicatedTablets.java:187)
	at com.yugabyte.yw.commissioner.TaskExecutor$AbstractRunnableTask.run(TaskExecutor.java:823)
	at com.yugabyte.yw.commissioner.TaskExecutor$RunnableSubTask.run(TaskExecutor.java:1238)
	... 6 common frames omitted
```

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-7618]: https://yugabyte.atlassian.net/browse/DB-7618?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by bmatican** [comment]
Closing this as per our [Slack thread](https://yugabyte.slack.com/archives/C4K1838GL/p1692248337694639), turned out it was due to geo-partitioning also being setup and the endpoint not yet supporting that. That has since been fixed and we filed some suggestions for improvements here: #18957
