### ISSUE TITLE
[DocDB] Workload  Failed  with Error " Failed to obtain locks until deadline"

### ISSUE THREAD

**Issue by sushantrmishra** [yugabyte/yugabyte-db#18770]
Jira Link: [DB-7653](https://yugabyte.atlassian.net/browse/DB-7653)
### Description

During the WaitOnConflict workload testing when the test is run for longer duration,  following error is reported.  The was reported  after running well for ~65mins .

SEND WORKLOAD COMMAND:

`java -jar yb-stress-sample-apps-1.1.11-mc2.jar --workload SqlWaitQueues --drop_table_name daily_limit --nodes 172.151.29.31:5433 --transaction_type 2 --num_writes -1 --num_threads_write 15 --num_threads_read 0 --num_reads 0 --hikari_max_pool_size 30 --wait_on_conflict_all_customers true --wait_on_conflict_timeout 0 --password yugabyte --username yugabyte --run_time 43200`

**Error reported to the Client:**

```
Caused by: com.yugabyte.util.PSQLException: ERROR: Failed to obtain locks until deadline: 75768.254s, batch: [{
 key:  intent_types: [kWeakRead, kWeakWrite] }, { key: 47CFAA498000000000000002 intent_types: [kWeakRead, kWeak
Write] }, { key: 47CFAA4980000000000000022148800021B6 intent_types: [kStrongRead, kStrongWrite] }]
```

**SEND WORKLOAD:**

https://github.com/yugabyte/yb-stress-test/blob/maintain-aug/tools/sample-app/src/main/java/com/yugabyte/sample/apps/SqlWaitQueues.java#L109

**GFLAGS:** 

- yb_enable_read_committed_isolation = true
- enable_wait_queues = true
- ysql_enable_packed_row = true
- enable_deadlock_detection = true
- wait_queue_poll_interval_ms = 1
- ysql_pg_conf_csv = yb_lock_pk_single_rpc=true

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-7653]: https://yugabyte.atlassian.net/browse/DB-7653?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by sushantrmishra** [comment]
**Ran the  workload with `wait_queue_poll_interval_ms = 5` .** 

Errors reported on Client: 

```
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
2023-08-19 10:21:31,556 [Thread-16] ERROR ExceptionsTracker - ERROR: Perform RPC (request call id 2872263) to 172.151.29.31:9100 timed out after 602.000s
com.yugabyte.util.PSQLException: ERROR: Perform RPC (request call id 2872263) to 172.151.29.31:9100 timed out after 602.000s
    at com.yugabyte.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2675) ~[yb-stress-sample-apps-1.1.11-mc2.jar:?]
    at com.yugabyte.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2365) ~[yb-stress-sample-apps-1.1.11-mc2.jar:?]
    at com.yugabyte.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:355) ~[yb-stress-sample-apps-1.1.11-mc2.jar:?]
    at com.yugabyte.jdbc.PgStatement.executeInternal(PgStatement.java:490) ~[yb-stress-sample-apps-1.1.11-mc2.jar:?]
    at com.yugabyte.jdbc.PgStatement.execute(PgStatement.java:408) ~[yb-stress-sample-apps-1.1.11-mc2.jar:?]
    at com.yugabyte.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:162) ~[yb-stress-sample-apps-1.1.11-mc2.jar:?]
    at com.yugabyte.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:114) ~[yb-stress-sample-apps-1.1.11-mc2.jar:?]
    at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52) ~[yb-stress-sample-apps-1.1.11-mc2.jar:?]
    at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java) ~[yb-stress-sample-apps-1.1.11-mc2.jar:?]
    at com.yugabyte.sample.apps.SqlWaitQueues.doWrite(SqlWaitQueues.java:121) [yb-stress-sample-apps-1.1.11-mc2.jar:?]
```

**Comment by basavaraj29** [comment]
can see similar failure for the test that Piyush put up recently. haven't yet started to debug this issue, but just tracking the notes here. `PgReadTimeTest.TestConflictRetriesOnDocdb` fails occasionally in tsan with error `Failed to obtain locks until deadline: 3252.140s`.

https://jenkins.dev.yugabyte.com/job/github-yugabyte-db-centos-master-clang15-tsan/2110/testReport/junit/(root)/PgReadTimeTest/TestConflictRetriesOnDocdb/
