### ISSUE TITLE
[YSQL]  Crash reported DocPgsqlScanSpec 

### ISSUE THREAD

**Issue by sushantrmishra** [yugabyte/yugabyte-db#18776]
Jira Link: [DB-7657](https://yugabyte.atlassian.net/browse/DB-7657)
### Description

Following crash is reported with [v2.17.3.0](https://docs.yugabyte.com/preview/releases/release-notes/v2.17/#v2.17.3.0)
Suspicion is that  it may be related to [Batching IN queries on Hash Keys](https://github.com/yugabyte/yugabyte-db/issues/7836). 

**GFLAG:**
`--yb_enable_read_committed_isolation=true
`

**Backtrace:** 

```
"(gdb) bt
 #0 0x0000562dc6928e1f in yb::docdb::DocPgsqlScanSpec::bound_key(yb::Schema const&, bool) const ()
 #1 0x0000562dc69267ca in yb::docdb::DocPgsqlScanSpec::DocPgsqlScanSpec(yb::Schema const&, long, std::__1::reference_wrapper<std::__1::vector<yb::docdb::KeyEntryValue, std::__1::allocator<yb::docdb::KeyEntryValue> > const>, std::__1::reference_wrapper<std::__1::vector<yb::docdb::KeyEntryValue, std::__1::allocator<yb::docdb::KeyEntryValue> > const>, yb::PgsqlConditionPB const*, boost::optional<int>, boost::optional<int>, yb::PgsqlExpressionPB const*, yb::docdb::DocKey const&, bool, yb::docdb::DocKey const&, yb::docdb::DocKey const&, unsigned long) ()
 #2 0x0000562dc69a80fc in yb::docdb::QLRocksDBStorage::GetIterator(yb::PgsqlReadRequestPB const&, yb::Schema const&, std::__1::reference_wrapper<yb::docdb::DocReadContext const>, yb::TransactionOperationContext const&, std::__1::chrono::time_point<yb::CoarseMonoClock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > >, yb::ReadHybridTime const&, yb::docdb::DocKey const&, std::__1::unique_ptr<yb::docdb::YQLRowwiseIteratorIf, std::__1::default_delete<yb::docdb::YQLRowwiseIteratorIf> >*, boost::optional<unsigned long>) const ()
 #3 0x0000562dc69a469b in yb::docdb::(anonymous namespace)::CreateIterator(yb::docdb::YQLStorageIf const&, yb::PgsqlReadRequestPB const&, yb::Schema const&, std::__1::reference_wrapper<yb::docdb::DocReadContext const>, yb::TransactionOperationContext const&, std::__1::chrono::time_point<yb::CoarseMonoClock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > >, yb::ReadHybridTime const&, bool, boost::optional<unsigned long>) ()
 #4 0x0000562dc69a0982 in yb::docdb::PgsqlReadOperation::Execute(yb::docdb::YQLStorageIf const&, std::__1::chrono::time_point<yb::CoarseMonoClock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > >, yb::ReadHybridTime const&, bool, yb::docdb::DocReadContext const&, yb::docdb::DocReadContext const*, yb::WriteBuffer*, yb::HybridTime*) ()
 #5 0x0000562dc73d60eb in yb::tablet::Tablet::HandlePgsqlReadRequest(std::__1::chrono::time_point<yb::CoarseMonoClock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > >, yb::ReadHybridTime const&, bool, yb::PgsqlReadRequestPB const&, yb::TransactionMetadataPB const&, yb::SubTransactionMetadataPB const&, yb::tablet::PgsqlReadRequestResult*) ()
 #6 0x0000562dc75c833b in yb::tserver::(anonymous namespace)::ReadQuery::Complete() ()
 #7 0x0000562dc75c267c in yb::tserver::PerformRead(yb::tserver::TabletServerIf*, yb::tserver::ReadTabletProvider*, yb::tserver::ReadRequestPB const*, yb::tserver::ReadResponsePB*, yb::rpc::RpcContext) ()
 #8 0x0000562dc7618763 in yb::tserver::TabletServiceImpl::Read(yb::tserver::ReadRequestPB const*, yb::tserver::ReadResponsePB*, yb::rpc::RpcContext) ()
 #9 0x0000562dc7744e64 in std::__1::__function::__func<yb::tserver::TabletServerServiceIf::InitMethods(scoped_refptr<yb::MetricEntity> const&)::$_1, std::__1::allocator<yb::tserver::TabletServerServiceIf::InitMethods(scoped_refptr<yb::MetricEntity> const&)::$_1>, void (std::__1::shared_ptr<yb::rpc::InboundCall>)>::operator()(std::__1::shared_ptr<yb::rpc::InboundCall>&&) ()
 #10 0x0000562dc774680f in yb::tserver::TabletServerServiceIf::Handle(std::__1::shared_ptr<yb::rpc::InboundCall>) ()
 #11 0x0000562dc731c09e in yb::rpc::ServicePoolImpl::Handle(std::__1::shared_ptr<yb::rpc::InboundCall>) ()
 #12 0x0000562dc725d23f in yb::rpc::InboundCall::InboundCallTask::Run() ()
 #13 0x0000562dc732aa13 in yb::rpc::(anonymous namespace)::Worker::Execute() ()
 #14 0x0000562dc79dabf2 in yb::thread::SuperviseThread(void*) ()
 #15 0x00007fdea3130694 in start_thread (arg=0x7fd5b9dc3700) at pthread_create.c:333
 #16 0x00007fdea363241d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109


PC: @               0x0 (unknown)
*** SIGSEGV (@0x8) received by PID 23 (TID 0x7f69e73f0700) from PID 8; stack trace: ***
   @    0x5559475c6e1f yb::docdb::DocPgsqlScanSpec::bound_key()
   @    0x5559475c47ca yb::docdb::DocPgsqlScanSpec::DocPgsqlScanSpec()
   @    0x5559476460fc yb::docdb::QLRocksDBStorage::GetIterator()
   @    0x55594764269b yb::docdb::(anonymous namespace)::CreateIterator()
   @    0x55594763e982 yb::docdb::PgsqlReadOperation::Execute()
   @    0x5559480740eb yb::tablet::Tablet::HandlePgsqlReadRequest()
   @    0x55594826633b yb::tserver::(anonymous namespace)::ReadQuery::Complete()
   @    0x55594826067c yb::tserver::PerformRead()
   @    0x5559482b6763 yb::tserver::TabletServiceImpl::Read()
   @    0x5559483e2e64 std::__1::__function::__func<>::operator()()
   @    0x5559483e480f yb::tserver::TabletServerServiceIf::Handle()
   @    0x555947fba09e yb::rpc::ServicePoolImpl::Handle()
   @    0x555947efb23f yb::rpc::InboundCall::InboundCallTask::Run()
   @    0x555947fc8a13 yb::rpc::(anonymous namespace)::Worker::Execute()
   @    0x555948678bf2 yb::thread::SuperviseThread()
   @    0x7f69fe139694 start_thread

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-7657]: https://yugabyte.atlassian.net/browse/DB-7657?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
```

**Comment by sushantrmishra** [comment]
Duplicate of https://github.com/yugabyte/yugabyte-db/issues/17043
