### ISSUE TITLE
[Docs] yugabyted ysql_hba_conf_csv/ysql_pg_conf_csv curly brace syntax

### ISSUE THREAD

**Issue by jasonyb** [yugabyte/yugabyte-db#18907]
### Description

yugabyted's ysql_hba_conf_csv and ysql_pg_conf_csv flag syntax changed in commit 96d6e2b02e08f0644a727d6026852293e10cef13 to take curly braces.  The syntax is not documented in the script nor in the docs.  So I turned to old commits messages for a reference and found commits like 197d4c967b758cfae892378c3c9771e96b8feaa6 and d9b0de9665eea2b64b88a87826a9f3ed03a10b77 using the old syntax, such as

```
bin/yugabyted start --tserver_flags "vmodule=intent_aware_iterator=4,pg_savepoints_enabled=true,yb_savepoints_enabled=true"
```

and trying to copy that, got unhelpful error

```
Starting yugabyted...
yugabyted crashed. For troubleshooting, contact us on https://www.yugabyte.com/slack or check our FAQ at https://docs.yugabyte.com/latest/faq/
Traceback (most recent call last):
  File "./bin/yugabyted", line 4792, in run
    args.func()
  File "./bin/yugabyted", line 419, in start
    self.start_processes()
  File "./bin/yugabyted", line 1536, in start_processes
    yb_tserver_cmd = self.get_tserver_cmd(common_gflags)
  File "./bin/yugabyted", line 2148, in get_tserver_cmd
    if ysql_pg_conf_csv_flag[0] == "'" and ysql_pg_conf_csv_flag[-1] == "'":
IndexError: string index out of range
```

A different issue can be opened for making the error message better, but at least document this somewhere such as `reference/configuration/yugabyted.md`.  It's very unintuitive to put in curly braces.

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

**Comment by jasonyb** [comment]
I further realize that the change was only made to those specific flags but not others like `vmodule`, which logically should behave the same way.  It seems to me the approach of only handling curly brace syntax for specific hand-picked flags is not ideal since those kinds of csv flags will come and go all the time, so you need to modify yugabyted every time.
