### ISSUE TITLE
Unable to init master catalog manager: Not found (yb/util/env_posix.cc:1453)

### ISSUE THREAD

**Issue by halleyshx** [yugabyte/yugabyte-db#1896]
I run this command in a pure docker：
\# /export/App/yugabyte-1.3.0.0/bin/yb-master \
   --master_addresses 192.168.4.244:7100,192.168.4.162:7100,192.168.5.212:7100 \
   --rpc_bind_addresses 192.168.4.244 \
   --fs_data_dirs "/export/data/ybdisk1,/export/data/ybdisk2" \
   \>& /export/data/ybdisk1/yb-master.out &

The error is：
\# vim yb-master.ERROR
  1 Log file created at: 2019/07/24 17:39:23
  2 Running on machine: dxxxxxxxxxxx3
  3 Application fingerprint: version 1.3.0.0 build 1 revision a63a4a4413c08275955b170716f3ffff76c0ba15 build_type RELEASE built at 14 Jul 2019 02:31:03 UTC
  4 Running duration (h:mm:ss): 0:00:00
  5 Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
  6 E0724 17:39:23.439527 63916 master.cc:223] Master@192.168.4.244:7100: Unable to init master catalog manager: Not found (yb/util/env_posix.cc:1453): Unable to initialize catalog manager: Failed to initialize sys tables async: Could not
    load Raft group metadata from /export/data/ybdisk1/yb-data/master/tablet-meta/00000000000000000000000000000000: /export/data/ybdisk1/yb-data/master/tablet-meta/00000000000000000000000000000000: No such file or directory (error 2)
  7 E0724 17:39:23.439781 63888 main_util.cc:22] Not found (yb/util/env_posix.cc:1453): Unable to initialize catalog manager: Failed to initialize sys tables async: Could not load Raft group metadata from /export/data/ybdisk1/yb-data/mast
    er/tablet-meta/00000000000000000000000000000000: /export/data/ybdisk1/yb-data/master/tablet-meta/00000000000000000000000000000000: No such file or directory (error 2)

\# pwd
/export/data/ybdisk1/yb-data/master/tablet-meta
\# ls
--It's null--

**Comment by ramkumarvs** [comment]
@halleyshx can you please clarify few things, 
- when you say pure docker do you mean vanilla centos docker image?
- I am assuming you are following the manual deployment instructions here https://docs.yugabyte.com/latest/deploy/manual-deployment/ let us know if that is not the case. If you are following those instructions have you created the data directories. 
- I see you have three IPs in the master address, i am assuming you have brought up three docker containers and those are the IPs of those containers.

If you are evaluating the product in a docker environment i would highly recommend looking into our yb-docker-ctl option. https://docs.yugabyte.com/latest/quick-start/install/#docker

**Comment by bmatican** [comment]
@halleyshx based on the final part of your post:

```
# pwd
/export/data/ybdisk1/yb-data/master/tablet-meta
```

It looks as if you might have previously tried to create a cluster and the master process tried to write some data to disk.

We've recently fixed an issue (#1575) where our master startup code was not crash-safe, leaving metadata behind that would prevent it from starting cleanly afterwards. This fix might not be present in the release you are using thought...Can you try to ensure that the 2 data paths you are using are empty: `/export/data/ybdisk1/`, `/export/data/ybdisk2/`

**Comment by halleyshx** [comment]
Hi, @bmatican ,
I make sure that `/export/data/ybdisk1/` and `/export/data/ybdisk2/` are empty.
I run the command `mkdir -p /export/data/ybdisk1` and `mkdir -p /export/data/ybdisk2` to make the dir. Before this,they are not exist.

**Comment by halleyshx** [comment]
Hi, @ramkumarvs ,
1、The  pure docker is meaning that the docker without rocksdb.(undefined symbol: _ZTIN7rocksdb6LoggerE #1888    have rocksdb installed,I want to try it without rocksdb )
2、You are true，I run the cluster with `https://docs.yugabyte.com/latest/deploy/manual-deployment/`, and I'm sure that the data directories had be maked before run the cluster.
3、I checked the IPs and dockers are OK.

**Comment by bmatican** [comment]
@halleyshx do you recall if in the container where you were seeing this state at the end `/export/data/ybdisk1/yb-data/master/tablet-meta` (this path existing), it was maybe the 2nd time you had tried starting the master there?

It looks like the first time when it started, the master maybe came up, tried to initialize, did not finish, (for some yet unknown reason), and left some files created (see #1575, now fixed)

**Comment by halleyshx** [comment]
@bmatican ,No,it's the first.I don't start the master again.

**Comment by ramkumarvs** [comment]
@halleyshx we were not able to repro this buy internally, could you please let me know how you start the docker instance?

something like this `docker run --name demo-n1 -it centos`
exact command would help a lot. 

Also you didn't answer my other question, if your goal is to test our DB in a Docker Environment, we already have a utility which will bring up 3 node cluster quickly without any issues.. https://docs.yugabyte.com/latest/quick-start/install/#docker

And if you are goal is to try to run the manual deployment yourself and get familiarized that that is fine.

**Comment by nielsonsantana** [comment]
I had the same problem. The problem was that my local IP wasn't present in master_addresses IPS.

YugaByte version: 1.3.1.0
Server: Ubuntu 18.04

```
I0812 11:05:41.255193 7561 webserver.cc:239] Webserver started. Bound to: http://0.0.0.0:7000/
I0812 11:05:41.255439 7561 rpc_server.cc:167] RPC server started. Bound to: 172.30.0.139:7100
I0812 11:05:41.255471 7561 server_base.cc:477] Using private ip address 172.30.0.139
E0812 11:05:41.257042 7575 master.cc:224] Master@172.30.0.139:7100: Unable to init master
catalog manager: Illegal state (yb/master/catalog_manager.cc:1147): Unable to initialize 
catalog manager: Failed to initialize sys tables async: None of the local addresses are 
present in master_addresses 52.201.167.138:7100.
E0812 11:05:41.257226  7561 main_util.cc:22] Illegal state (yb/master/catalog_manager.cc:1147): 
Unable to initialize catalog manager: Failed to initialize sys tables async: None of the local
 addresses are present in master_addresses 52.201.167.138:7100.
I0812 11:05:41.257254  7561 master.cc:267] Master@172.30.0.139:7100 shutting down...
I0812 11:05:41.268214  7561 master.cc:275] Master@172.30.0.139:7100 shutdown complete.
```

**Comment by mingfang** [comment]
I'm still seeing this problem using the latest version, 2.0.0.0-b16

**Comment by kmuthukk** [comment]
@mingfang - can you share steps on how you started the cluster? 

Would like to see all the flags/arguments passed to the the yb-master & yb-tserver processes.

**Comment by mingfang** [comment]
@kmuthukk 
I'm running Yugabyte inside Kubernetes using my Terraform modules here 
https://github.com/mingfang/terraform-k8s-modules/tree/master/modules/yugabytedb

I believe the problem for me was not setting the `rpc_bind_addresses` correctly.
https://github.com/mingfang/terraform-k8s-modules/blob/master/modules/yugabytedb/master/main.tf#L50
Setting it to a changing IP address will prevent startup after a restart(with new IP).

A complete example with Yugabyte, persistent volume and Janusgraph is here
https://github.com/mingfang/terraform-k8s-modules/tree/master/examples/yugabytedb

**Comment by dhbaird** [comment]
Yugabyte version: yugabyte-2.1.2.0

I too to have triggered this issue it would seem. I tried to do a simple stress test of killing the leader node (node 1, in this case) after first ever startup of cluster. Now I can't re-add node 1.

Here's how I created the cluster:
```
$ ./bin/yb-ctl --rf 3 create
Creating cluster.
Waiting for cluster to be ready.
----------------------------------------------------------------------------------------------------
| Node Count: 3 | Replication Factor: 3                                                            |
----------------------------------------------------------------------------------------------------
| JDBC                : jdbc:postgresql://127.0.0.1:5433/postgres                                  |
| YSQL Shell          : bin/ysqlsh                                                                 |
| YCQL Shell          : bin/cqlsh                                                                  |
| YEDIS Shell         : bin/redis-cli                                                              |
| Web UI              : http://127.0.0.1:7000/                                                     |
| Cluster Data        : /home/person/yugabyte-data                                                 |
----------------------------------------------------------------------------------------------------

For more info, please use: yb-ctl status
```

```
$ ./bin/yb-ctl status
----------------------------------------------------------------------------------------------------
| Node Count: 3 | Replication Factor: 3                                                            |
----------------------------------------------------------------------------------------------------
| JDBC                : jdbc:postgresql://127.0.0.1:5433/postgres                                  |
| YSQL Shell          : bin/ysqlsh                                                                 |
| YCQL Shell          : bin/cqlsh                                                                  |
| YEDIS Shell         : bin/redis-cli                                                              |
| Web UI              : http://127.0.0.1:7000/                                                     |
| Cluster Data        : /home/person/yugabyte-data                                                 |
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
| Node 1: yb-tserver (pid 3017), yb-master (pid 3008)                                              |
----------------------------------------------------------------------------------------------------
| JDBC                : jdbc:postgresql://127.0.0.1:5433/postgres                                  |
| YSQL Shell          : bin/ysqlsh                                                                 |
| YCQL Shell          : bin/cqlsh                                                                  |
| YEDIS Shell         : bin/redis-cli                                                              |
| data-dir[0]         : /home/person/yugabyte-data/node-1/disk-1/yb-data                           |
| yb-tserver Logs     : /home/person/yugabyte-data/node-1/disk-1/yb-data/tserver/logs              |
| yb-master Logs      : /home/person/yugabyte-data/node-1/disk-1/yb-data/master/logs               |
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
| Node 2: yb-tserver (pid 3020), yb-master (pid 3011)                                              |
----------------------------------------------------------------------------------------------------
| JDBC                : jdbc:postgresql://127.0.0.2:5433/postgres                                  |
| YSQL Shell          : bin/ysqlsh -h 127.0.0.2                                                    |
| YCQL Shell          : bin/cqlsh 127.0.0.2                                                        |
| YEDIS Shell         : bin/redis-cli -h 127.0.0.2                                                 |
| data-dir[0]         : /home/person/yugabyte-data/node-2/disk-1/yb-data                           |
| yb-tserver Logs     : /home/person/yugabyte-data/node-2/disk-1/yb-data/tserver/logs              |
| yb-master Logs      : /home/person/yugabyte-data/node-2/disk-1/yb-data/master/logs               |
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
| Node 3: yb-tserver (pid 3029), yb-master (pid 3014)                                              |
----------------------------------------------------------------------------------------------------
| JDBC                : jdbc:postgresql://127.0.0.3:5433/postgres                                  |
| YSQL Shell          : bin/ysqlsh -h 127.0.0.3                                                    |
| YCQL Shell          : bin/cqlsh 127.0.0.3                                                        |
| YEDIS Shell         : bin/redis-cli -h 127.0.0.3                                                 |
| data-dir[0]         : /home/person/yugabyte-data/node-3/disk-1/yb-data                           |
| yb-tserver Logs     : /home/person/yugabyte-data/node-3/disk-1/yb-data/tserver/logs              |
| yb-master Logs      : /home/person/yugabyte-data/node-3/disk-1/yb-data/master/logs               |
----------------------------------------------------------------------------------------------------
```

(wait for a few minutes)

Then, kill node 1 processes and see what happens:

```
kill 3017 3008
````

Now I can't restart node.
```
$ ./bin/yb-ctl start_node 1
Starting node tserver-1.
Waiting for cluster to be ready.
Viewing file /home/person/yugabyte-data/node-1/disk-1/master.err:
*** Aborted at 1586188053 (unix time) try "date -d @1586188053" if you are using GNU date ***
PC: @     0x7fad8401a46d __GI___nanosleep
*** SIGTERM (@0x7d000000a92) received by PID 3008 (TID 0x7fad92dd2b40) from PID 2706; stack trace: ***
    @     0x7fad8401aba0 (unknown)
    @     0x7fad8401a46d __GI___nanosleep
    @     0x7fad8f46d95c  yb::server::TotalMemWatcher::MemoryMonitoringLoop()
    @           0x40861f  yb::master::MasterMain()
    @     0x7fad83689825 __libc_start_main
    @           0x407eb9 _start
    @                0x0 (unknown)
Traceback (most recent call last):
  File "./bin/yb-ctl", line 1969, in <module>
    control.run()
  File "./bin/yb-ctl", line 1946, in run
    self.args.func()
  File "./bin/yb-ctl", line 1804, in start_node_cmd_impl
    self.wait_for_cluster_or_raise()
  File "./bin/yb-ctl", line 1551, in wait_for_cluster_or_raise
    raise RuntimeError("Timed out waiting for a YugaByte DB cluster!")
RuntimeError: Timed out waiting for a YugaByte DB cluster!
Viewing file /tmp/tmpXeHd7g:
2020-04-06 12:38:23,524 INFO: Starting tserver-1 with:
/pool/HOME/person/Downloads/yugabyte-2.1.2.0/bin/yb-tserver --fs_data_dirs "/home/person/yugabyte-data/node-1/disk-1" --webserver_interface 127.0.0.1 --rpc_bind_addresses 127.0.0.1 --v 0 --version_file_json_path=/pool/HOME/person/Downloads/yugabyte-2.1.2.0 --webserver_doc_root "/pool/HOME/person/Downloads/yugabyte-2.1.2.0/www" --tserver_master_addrs=127.0.0.1:7100,127.0.0.2:7100,127.0.0.3:7100 --yb_num_shards_per_tserver=2 --redis_proxy_bind_address=127.0.0.1:6379 --cql_proxy_bind_address=127.0.0.1:9042 --local_ip_for_outbound_sockets=127.0.0.1 --use_cassandra_authentication=false --ysql_num_shards_per_tserver=2 --enable_ysql=true --pgsql_proxy_bind_address=127.0.0.1:5433 >"/home/person/yugabyte-data/node-1/disk-1/tserver.out" 2>"/home/person/yugabyte-data/node-1/disk-1/tserver.err" &
2020-04-06 12:38:23,528 INFO: Waiting for master and tserver processes to come up.
2020-04-06 12:38:34,790 INFO: PIDs found: {'tserver': [10775, 3020, 3029], 'master': [None, 3011, 3014]}
2020-04-06 12:38:34,790 ERROR: Failed waiting for master and tserver processes to come up.
^^^ Encountered errors ^^^
```

/home/person/yugabyte-data/node-1/disk-1/yb-data/master/logs/yb-master.myhost.person.log.INFO.20200406-190809.29819
```
I0406 19:08:09.166501 29853 tablet.cc:664] T 00000000000000000000000000000000 P 88ccd4fe51a24d28a698cb264bdf37b9: Successfully opened a RocksDB database at /home/person/yugabyte-data/node-1/disk-1/yb-data/master/data/rocksdb/table-sys.catalog.uuid/tablet-00000000000000000000000000000000, obj: 0xef3400
I0406 19:08:09.166543 29866 transaction_participant.cc:945] T 00000000000000000000000000000000 P 88ccd4fe51a24d28a698cb264bdf37b9: LoadTransactions start
I0406 19:08:09.166561 29853 tablet_bootstrap.cc:431] T 00000000000000000000000000000000 P 88ccd4fe51a24d28a698cb264bdf37b9: Time spent opening tablet: real 0.009s  user 0.008s sys 0.001s
I0406 19:08:09.166612 29866 transaction_participant.cc:984] T 00000000000000000000000000000000 P 88ccd4fe51a24d28a698cb264bdf37b9: LoadTransactions done: loaded 0 transactions
I0406 19:08:09.166752 29853 tablet_bootstrap.cc:497] T 00000000000000000000000000000000 P 88ccd4fe51a24d28a698cb264bdf37b9: Will attempt to recover log segment /home/person/yugabyte-data/node-1/disk-1/yb-data/master/wals/table-sys.catalog.uuid/tablet-00000000000000000000000000000000/wal-000000002
I0406 19:08:09.166787 29853 tablet_bootstrap.cc:497] T 00000000000000000000000000000000 P 88ccd4fe51a24d28a698cb264bdf37b9: Will attempt to recover log segment /home/person/yugabyte-data/node-1/disk-1/yb-data/master/wals/table-sys.catalog.uuid/tablet-00000000000000000000000000000000/wal-000000001
I0406 19:08:09.166844 29853 tablet_bootstrap.cc:833] T 00000000000000000000000000000000 P 88ccd4fe51a24d28a698cb264bdf37b9: Max persistent index in RocksDB's SSTables before bootstrap: term: 1 index: 4/term: 1 index: 4
I0406 19:08:09.166975 29853 log.cc:808] T 00000000000000000000000000000000 P 88ccd4fe51a24d28a698cb264bdf37b9: Setting log wal retention time to 0 seconds
W0406 19:08:09.167327 29853 log.cc:1179] Error closing log: Illegal state (yb/consensus/log.cc:1012): Bad state for Close() 0
I0406 19:08:09.167734 29853 transaction_participant.cc:141] T 00000000000000000000000000000000 P 88ccd4fe51a24d28a698cb264bdf37b9: Shutdown 
I0406 19:08:09.167825 29853 db_impl.cc:641] T 00000000000000000000000000000000 P 88ccd4fe51a24d28a698cb264bdf37b9 [I]: Shutting down RocksDB at: /home/person/yugabyte-data/node-1/disk-1/yb-data/master/data/rocksdb/table-sys.catalog.uuid/tablet-00000000000000000000000000000000.intents
I0406 19:08:09.168032 29853 db_impl.cc:751] T 00000000000000000000000000000000 P 88ccd4fe51a24d28a698cb264bdf37b9 [I]: Shutdown done
I0406 19:08:09.168081 29853 db_impl.cc:641] T 00000000000000000000000000000000 P 88ccd4fe51a24d28a698cb264bdf37b9 [R]: Shutting down RocksDB at: /home/person/yugabyte-data/node-1/disk-1/yb-data/master/data/rocksdb/table-sys.catalog.uuid/tablet-00000000000000000000000000000000
I0406 19:08:09.168210 29853 db_impl.cc:751] T 00000000000000000000000000000000 P 88ccd4fe51a24d28a698cb264bdf37b9 [R]: Shutdown done
E0406 19:08:09.168334 29853 master.cc:241] Master@127.0.0.1:7100: Unable to init master catalog manager: IO error (yb/util/env_util.cc:156): Unable to initialize catalog manager: Failed to initialize sys tables async: Failed log replay. Reason: Failed to open new log: Unable to open readable log segment: /home/person/yugabyte-data/node-1/disk-1/yb-data/master/wals/table-sys.catalog.uuid/tablet-00000000000000000000000000000000/wal-000000002: Unable to initialize segment: EOF trying to read 12 bytes at offset 0
E0406 19:08:09.168632 29819 main_util.cc:22] IO error (yb/util/env_util.cc:156): Unable to initialize catalog manager: Failed to initialize sys tables async: Failed log replay. Reason: Failed to open new log: Unable to open readable log segment: /home/person/yugabyte-data/node-1/disk-1/yb-data/master/wals/table-sys.catalog.uuid/tablet-00000000000000000000000000000000/wal-000000002: Unable to initialize segment: EOF trying to read 12 bytes at offset 0
I0406 19:08:09.168830 29819 master.cc:284] Master@127.0.0.1:7100 shutting down...
I0406 19:08:09.191009 29819 tablet_peer.cc:380] T 00000000000000000000000000000000 P 88ccd4fe51a24d28a698cb264bdf37b9 [state=BOOTSTRAPPING]: Initiating TabletPeer shutdown
I0406 19:08:09.191084 29819 tablet_peer.cc:397] T 00000000000000000000000000000000 P 88ccd4fe51a24d28a698cb264bdf37b9 [state=QUIESCING]: Started shutdown from state: BOOTSTRAPPING
I0406 19:08:09.191339 29819 master.cc:292] Master@127.0.0.1:7100 shutdown complete.
```

**Comment by dhbaird** [comment]
I mistakenly posted on this issue earlier today, but have since re-posted into a new issue (and deleted the post from here). In case that caused a disruption and people are wondering what happened to my original post, its new home is here: https://github.com/yugabyte/yugabyte-db/issues/4157

**Comment by kriteshranjan** [comment]
Closing this issue based on AI validation. cc: @m-iancu , @VamsidharGunturu
