### ISSUE TITLE
[Jepsen] [YSQL] Delays between Jepsen operation issue and execution

### ISSUE THREAD

**Issue by frozenspider** [yugabyte/yugabyte-db#1911]
Excerpt from Jepsen history for counter test:
```
{:type :invoke, :f :add, :value 1, :op-index 6, :process 6, :time 9129891137, :index 7}
...
{:op-exec-timing ["2019-07-26_11:30:11.165" "2019-07-26_11:30:12.980"], :index 47, :value 1, :time 10951044788, :process 6, :type :ok, :f :add, :op-index 6, :op-timing ["2019-07-26_11:30:11.164" "2019-07-26_11:30:12.980"]}
```
(Operation was issued at `2019-07-26_11:30:11.165` and response processed at `2019-07-26_11:30:12.980`)
However, on PG side (with some custom logs added), we see
```
2019-07-26 11:30:12.937 UTC [6592] LOG:   === firstchar E ===
2019-07-26 11:30:12.937 UTC [6592] LOG:   === PostgresMain_main_loop_E - start ===
2019-07-26 11:30:12.937 UTC [6592] LOG:   === Executing message for query UPDATE counter SET count = count + $1 WHERE id = 0 /* op-index 6 */  ===
2019-07-26 11:30:12.937 UTC [6592] LOG:   === exec_execute_message - start ===
...
2019-07-26 11:30:12.973 UTC [6592] LOG:   === exec_execute_message - end (took 36 ms) ===
2019-07-26 11:30:12.973 UTC [6592] LOG:   === PostgresMain_main_loop_E - end (took 36 ms) ===
```
Meaning that actual execution took from `11:30:12.937` to `11:30:12.973`. However, we don't know why request only started processing on `11:30:12.937`, while Jepsen operation started at `11:30:11.165` - execution has been delayed by ~1800 ms. We need to figure out, what happens in such cases.
Might be some kind of client-side (Java/Clojure) or server-side (YB) queue at play here?

Latency graph:
![latency-raw](https://user-images.githubusercontent.com/2077017/61955344-3e05b600-afd4-11e9-9100-f59d8845c195.png)

Jepsen log (without PG-side logs for time after the operation in question):
[logs-jepsen_2019-07-26_17-19-56__counter_c10_t600_logs5.zip](https://github.com/YugaByte/yugabyte-db/files/3435969/logs-jepsen_2019-07-26_17-19-56__counter_c10_t600_logs5.zip)

**Comment by qvad** [comment]
It's related to worker initialisation stage (later ops have no such significant delay), collected JVM thread dumps for ysql/bank workload as an example
```
INFO [2022-05-25 17:14:46,870] jepsen worker 10 - jepsen.util 10        :invoke :read   nil
...
INFO [2022-05-25 17:14:48,259] jepsen worker 10 - jepsen.util 10        :ok     :read   {0 100, 1 0, 2 0, 3 -5, 4 0, 5 0, 6 0, 7 5}
```
So we spent 2 seconds somewhere and here is a stacktrace for `worker 10` in these seconds.
```
"jepsen worker 10" #125 prio=5 os_prio=0 cpu=2.64ms elapsed=0.53s tid=0x00007f851ec55000 nid=0x478c waiting on condition  [0x00007f847faf8000]
   java.lang.Thread.State: TIMED_WAITING (parking)
        at jdk.internal.misc.Unsafe.park(java.base@11.0.15/Native Method)
        - parking to wait for  <0x000000071920e080> (a java.util.concurrent.FutureTask)
        at java.util.concurrent.locks.LockSupport.parkNanos(java.base@11.0.15/LockSupport.java:234)
        at java.util.concurrent.FutureTask.awaitDone(java.base@11.0.15/FutureTask.java:444)
        at java.util.concurrent.FutureTask.get(java.base@11.0.15/FutureTask.java:203)
        at clojure.core$deref_future.invokeStatic(core.clj:2302)
        at clojure.core$future_call$reify__8439.deref(core.clj:6974)
        at clojure.core$deref.invokeStatic(core.clj:2324)
        at clojure.core$deref.invoke(core.clj:2306)
        at yugabyte.ysql.client$open_conn$fn__4464.invoke(client.clj:111)
        at yugabyte.ysql.client$open_conn.invokeStatic(client.clj:111)
        at yugabyte.ysql.client$open_conn.invoke(client.clj:108)
        at clojure.core$partial$fn__5824.invoke(core.clj:2623)
        at jepsen.reconnect$open_BANG_$fn__3361.invoke(reconnect.clj:60)
        at jepsen.reconnect$open_BANG_.invokeStatic(reconnect.clj:58)
        at jepsen.reconnect$open_BANG_.invoke(reconnect.clj:55)
        at yugabyte.ysql.client$conn_wrapper.invokeStatic(client.clj:146)
        at yugabyte.ysql.client$conn_wrapper.invoke(client.clj:143)
        at yugabyte.ysql.bank.YSQLBankClient.open_BANG_(bank.clj:63)
        at jepsen.client.Validate.open_BANG_(client.clj:67)
        at jepsen.generator.interpreter.ClientWorker$fn__10543.invoke(interpreter.clj:48)
        at jepsen.generator.interpreter.ClientWorker.invoke_BANG_(interpreter.clj:46)
        at jepsen.generator.interpreter$spawn_worker$fn__10590$fn__10591.invoke(interpreter.clj:137)
        at jepsen.generator.interpreter$spawn_worker$fn__10590.invoke(interpreter.clj:120)
        at clojure.core$binding_conveyor_fn$fn__5739.invoke(core.clj:2030)
        at clojure.lang.AFn.call(AFn.java:18)
        at java.util.concurrent.FutureTask.run(java.base@11.0.15/FutureTask.java:264)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@11.0.15/ThreadPoolExecutor.java:1128)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@11.0.15/ThreadPoolExecutor.java:628)
        at java.lang.Thread.run(java.base@11.0.15/Thread.java:829)
```
