### ISSUE TITLE
[YSQL][SQLancer]Table with identifier not found during CREATE TABLE query

### ISSUE THREAD

**Issue by qvad** [yugabyte/yugabyte-db#19321]
### Description

Occurred in latest master builds (2.21), but it doesn't look like a recent regression

Currently DDLs in SQLancer are not concurrent - we have client lock and random timeout between each DDL, so it should not be concurrent. But we control this process on client side, so there might be parallel server DDLs.

```
--java.lang.AssertionError: CREATE TABLE IF NOT EXISTS t3(c0 boolean , FOREIGN KEY (c0) REFERENCES t1(c0) MATCH SIMPLE);
--	at sqlancer.common.query.SQLQueryAdapter.checkException(SQLQueryAdapter.java:111)
--	at sqlancer.common.query.SQLQueryAdapter.execute(SQLQueryAdapter.java:93)
--	at sqlancer.Main$QueryManager.execute(Main.java:265)
--	at sqlancer.GlobalState.executeStatement(GlobalState.java:108)
--	at sqlancer.yugabyte.ysql.YSQLProvider.createTables(YSQLProvider.java:258)
--	at sqlancer.yugabyte.ysql.YSQLProvider.generateDatabase(YSQLProvider.java:125)
--	at sqlancer.yugabyte.ysql.YSQLProvider.generateDatabase(YSQLProvider.java:1)
--	at sqlancer.ProviderAdapter.generateAndTestDatabase(ProviderAdapter.java:52)
--	at sqlancer.Main$DBMSExecutor.run(Main.java:364)
--	at sqlancer.Main$2.run(Main.java:559)
--	at sqlancer.Main$2.runThread(Main.java:541)
--	at sqlancer.Main$2.run(Main.java:532)
--	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
--	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
--	at java.base/java.lang.Thread.run(Thread.java:1589)
--Caused by: com.yugabyte.util.PSQLException: ERROR: Table with identifier 0000560c000030008000000000005c7c not found: OBJECT_NOT_FOUND
--	at com.yugabyte.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2675)
--	at com.yugabyte.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2365)
--	at com.yugabyte.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:355)
--	at com.yugabyte.jdbc.PgStatement.executeInternal(PgStatement.java:490)
--	at com.yugabyte.jdbc.PgStatement.execute(PgStatement.java:408)
--	at com.yugabyte.jdbc.PgStatement.executeWithFlags(PgStatement.java:329)
--	at com.yugabyte.jdbc.PgStatement.executeCachedSql(PgStatement.java:315)
--	at com.yugabyte.jdbc.PgStatement.executeWithFlags(PgStatement.java:291)
--	at com.yugabyte.jdbc.PgStatement.execute(PgStatement.java:286)
--	at sqlancer.common.query.SQLQueryAdapter.execute(SQLQueryAdapter.java:87)
--	... 13 more
---- Time: 2023/09/27 01:10:05
-- Database: database21
-- Database version: 11.2-YB-2.21.0.0-b0
-- seed value: 1695760846092
\c yugabyte;
DROP DATABASE IF EXISTS database21;
CREATE DATABASE database21 ;
\c database21;
CREATE TABLE t0(c0 FLOAT , CHECK((0.32216677) BETWEEN (0.18424527) AND (((((CAST(TRUE AS INT))*(166399512)))/(length('oIew'))))), PRIMARY KEY(c0), UNIQUE(c0));
CREATE TEMPORARY TABLE t1(c0 bytea  UNIQUE PRIMARY KEY NULL) WITH (COLOCATION=false);
CREATE TABLE IF NOT EXISTS t2(c0 FLOAT ) WITHOUT OIDS ;

```

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

**Comment by yifanguan** [comment]
Simple repro on default yugabyte database:
```
CREATE TEMPORARY TABLE t1(c0 int primary key);
CREATE TABLE t3(c0 int, FOREIGN KEY (c0) REFERENCES t1(c0));
```
The error indicates that when creating table `t3`, we try to find table `t1` on master. However, table `t1` is a temp table which is completely handled on PG.
