### ISSUE TITLE
[CDCSDK] Do not completely fail while fetching tablets if one table hits error

### ISSUE THREAD

**Issue by shamanthchandra-yb** [yugabyte/yugabyte-db#19434]
Jira Link: [DB-8227](https://yugabyte.atlassian.net/browse/DB-8227)
### Description

![Profile (4)](https://github.com/yugabyte/yugabyte-db/assets/109518123/c17f390c-f387-4921-b3ec-8b253825eb98)

```
1235457 2023-10-06 14:51:26,550 ERROR  YugabyteDB|db_cdc|streaming|2  Too many errors while trying to get children for split tablet 51747515064b4f6a891e3235f1c46903   [io.debez
1235458 2023-10-06 14:51:26,550 ERROR  YugabyteDB|db_cdc|streaming|2  Error   [io.debezium.connector.yugabytedb.YugabyteDBStreamingChangeEventSource]
1235459 java.lang.Exception: Found unexpected (0) number of tablets while trying to fetch the children of parent 51747515064b4f6a891e3235f1c46903
1235460         at io.debezium.connector.yugabytedb.YugabyteDBStreamingChangeEventSource.getTabletListResponseWithRetry(YugabyteDBStreamingChangeEventSource.java:1060)
1235461         at io.debezium.connector.yugabytedb.YugabyteDBStreamingChangeEventSource.handleTabletSplit(YugabyteDBStreamingChangeEventSource.java:994)
1235462         at io.debezium.connector.yugabytedb.YugabyteDBStreamingChangeEventSource.getChanges2(YugabyteDBStreamingChangeEventSource.java:458)
1235463         at io.debezium.connector.yugabytedb.YugabyteDBStreamingChangeEventSource.execute(YugabyteDBStreamingChangeEventSource.java:149)
1235464         at io.debezium.connector.yugabytedb.YugabyteDBStreamingChangeEventSource.execute(YugabyteDBStreamingChangeEventSource.java:47)
1235465         at io.debezium.pipeline.ChangeEventSourceCoordinator.streamEvents(ChangeEventSourceCoordinator.java:174)
1235466         at io.debezium.connector.yugabytedb.YugabyteDBChangeEventSourceCoordinator.executeChangeEventSources(YugabyteDBChangeEventSourceCoordinator.java:150)
1235467         at io.debezium.pipeline.ChangeEventSourceCoordinator.lambda$start$0(ChangeEventSourceCoordinator.java:109)
1235468         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
1235469         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
1235470         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
1235471         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
1235472         at java.base/java.lang.Thread.run(Thread.java:829)
```

### Source connector version

1.9.5.y.33-SNAPSHOT

### Connector configuration

```
adding yb connector stream_id='319e24ad0b9b46798d95b34537c3c033' db_name='cdc_d87c07' connector_host='172.151.18.78' table_list=['test_cdc_c87888']
2023-10-06 12:44:36,961:DEBUG: add connector connector_name='ybconnector_cdc_d87c07_test_cdc_c87888' stream_id='319e24ad0b9b46798d95b34537c3c033' db_name='cdc_d87c07' connector_host='172.151.18.78' table_list=['test_cdc_c87888'] {'name': 'ybconnector_cdc_d87c07_test_cdc_c87888', 'config': {'connector.class': 'io.debezium.connector.yugabytedb.YugabyteDBConnector', 'database.hostname': '172.151.17.232:5433,172.151.31.94:5433,172.151.30.97:5433', 'database.master.addresses': '172.151.17.232:7100,172.151.31.94:7100,172.151.30.97:7100', 'database.masterhost': '172.151.30.97', 'database.masterport': '7100', 'database.user': 'yugabyte', 'database.password': 'yugabyte', 'database.dbname': 'cdc_d87c07', 'database.server.name': 'db_cdc', 'database.streamid': '319e24ad0b9b46798d95b34537c3c033', 'snapshot.mode': 'initial', 'admin.operation.timeout.ms': 600000, 'socket.read.timeout.ms': 600000, 'max.connector.retries': '10', 'operation.timeout.ms': 600000, 'topic.creation.default.compression.type': 'lz4', 'topic.creation.default.cleanup.policy': 'delete', 'topic.creation.default.partitions': 2, 'topic.creation.default.replication.factor': '1', 'tasks.max': '5', 'table.include.list': 'public.test_cdc_c87888'}}
2023-10-06 12:44:37,801: INFO: sleep 5s 
2023-10-06 12:44:42,802:DEBUG: yugaware > https://172.151.17.254/api/v1/customers/de373293-eb0a-4524-8b80-a8b38615fc99/universes/402aeb21-12f9-4a6e-b261-ab5bf6382f10/leader
2023-10-06 12:44:42,862: INFO: adding yb connector stream_id='a39f6dbb20804a79830d33d5870240df' db_name='cdc_d87c07' connector_host='172.151.29.242' table_list=['test_cdc_1f8ea0']
2023-10-06 12:44:42,863:DEBUG: add connector connector_name='ybconnector_cdc_d87c07_test_cdc_1f8ea0' stream_id='a39f6dbb20804a79830d33d5870240df' db_name='cdc_d87c07' connector_host='172.151.29.242' table_list=['test_cdc_1f8ea0'] {'name': 'ybconnector_cdc_d87c07_test_cdc_1f8ea0', 'config': {'connector.class': 'io.debezium.connector.yugabytedb.YugabyteDBConnector', 'database.hostname': '172.151.17.232:5433,172.151.31.94:5433,172.151.30.97:5433', 'database.master.addresses': '172.151.17.232:7100,172.151.31.94:7100,172.151.30.97:7100', 'database.masterhost': '172.151.30.97', 'database.masterport': '7100', 'database.user': 'yugabyte', 'database.password': 'yugabyte', 'database.dbname': 'cdc_d87c07', 'database.server.name': 'db_cdc', 'database.streamid': 'a39f6dbb20804a79830d33d5870240df', 'snapshot.mode': 'initial', 'admin.operation.timeout.ms': 600000, 'socket.read.timeout.ms': 600000, 'max.connector.retries': '10', 'operation.timeout.ms': 600000, 'topic.creation.default.compression.type': 'lz4', 'topic.creation.default.cleanup.policy': 'delete', 'topic.creation.default.partitions': 2, 'topic.creation.default.replication.factor': '1', 'tasks.max': '5', 'table.include.list': 'public.test_cdc_1f8ea0'}}
2023-10-06 12:44:43,558: INFO: sleep 5s 
2023-10-06 12:44:48,559:DEBUG: yugaware > https://172.151.17.254/api/v1/customers/de373293-eb0a-4524-8b80-a8b38615fc99/universes/402aeb21-12f9-4a6e-b261-ab5bf6382f10/leader
2023-10-06 12:44:48,626: INFO: adding yb connector stream_id='9b4fbdc5a1884d74bc9abbff4595b239' db_name='cdc_d87c07' connector_host='172.151.18.78' table_list=['test_cdc_830b8a']
2023-10-06 12:44:48,626:DEBUG: add connector connector_name='ybconnector_cdc_d87c07_test_cdc_830b8a' stream_id='9b4fbdc5a1884d74bc9abbff4595b239' db_name='cdc_d87c07' connector_host='172.151.18.78' table_list=['test_cdc_830b8a'] {'name': 'ybconnector_cdc_d87c07_test_cdc_830b8a', 'config': {'connector.class': 'io.debezium.connector.yugabytedb.YugabyteDBConnector', 'database.hostname': '172.151.17.232:5433,172.151.31.94:5433,172.151.30.97:5433', 'database.master.addresses': '172.151.17.232:7100,172.151.31.94:7100,172.151.30.97:7100', 'database.masterhost': '172.151.30.97', 'database.masterport': '7100', 'database.user': 'yugabyte', 'database.password': 'yugabyte', 'database.dbname': 'cdc_d87c07', 'database.server.name': 'db_cdc', 'database.streamid': '9b4fbdc5a1884d74bc9abbff4595b239', 'snapshot.mode': 'initial', 'admin.operation.timeout.ms': 600000, 'socket.read.timeout.ms': 600000, 'max.connector.retries': '10', 'operation.timeout.ms': 600000, 'topic.creation.default.compression.type': 'lz4', 'topic.creation.default.cleanup.policy': 'delete', 'topic.creation.default.partitions': 2, 'topic.creation.default.replication.factor': '1', 'tasks.max': '5', 'table.include.list': 'public.test_cdc_830b8a'}}
2023-10-06 12:44:48,715: INFO: sleep 5s 
2023-10-06 12:44:53,715:DEBUG: yugaware > https://172.151.17.254/api/v1/customers/de373293-eb0a-4524-8b80-a8b38615fc99/universes/402aeb21-12f9-4a6e-b261-ab5bf6382f10/leader
2023-10-06 12:44:53,775: INFO: adding yb connector stream_id='e7b8324d3c9e42d9bc2492fe8b688bb2' db_name='cdc_d87c07' connector_host='172.151.29.242' table_list=['test_cdc_52b1cc']
2023-10-06 12:44:53,776:DEBUG: add connector connector_name='ybconnector_cdc_d87c07_test_cdc_52b1cc' stream_id='e7b8324d3c9e42d9bc2492fe8b688bb2' db_name='cdc_d87c07' connector_host='172.151.29.242' table_list=['test_cdc_52b1cc'] {'name': 'ybconnector_cdc_d87c07_test_cdc_52b1cc', 'config': {'connector.class': 'io.debezium.connector.yugabytedb.YugabyteDBConnector', 'database.hostname': '172.151.17.232:5433,172.151.31.94:5433,172.151.30.97:5433', 'database.master.addresses': '172.151.17.232:7100,172.151.31.94:7100,172.151.30.97:7100', 'database.masterhost': '172.151.30.97', 'database.masterport': '7100', 'database.user': 'yugabyte', 'database.password': 'yugabyte', 'database.dbname': 'cdc_d87c07', 'database.server.name': 'db_cdc', 'database.streamid': 'e7b8324d3c9e42d9bc2492fe8b688bb2', 'snapshot.mode': 'initial', 'admin.operation.timeout.ms': 600000, 'socket.read.timeout.ms': 600000, 'max.connector.retries': '10', 'operation.timeout.ms': 600000, 'topic.creation.default.compression.type': 'lz4', 'topic.creation.default.cleanup.policy': 'delete', 'topic.creation.default.partitions': 2, 'topic.creation.default.replication.factor': '1', 'tasks.max': '5', 'table.include.list': 'public.test_cdc_52b1cc'}}
2023-10-06 12:44:53,861: INFO: sleep 5s 
2023-10-06 12:44:58,861:DEBUG: yugaware > https://172.151.17.254/api/v1/customers/de373293-eb0a-4524-8b80-a8b38615fc99/universes/402aeb21-12f9-4a6e-b261-ab5bf6382f10/leader
2023-10-06 12:44:59,153: INFO: adding yb connector stream_id='8356253661614863b71be44215ae6b8f' db_name='cdc_d87c07' connector_host='172.151.18.78' table_list=['test_cdc_07fe05']
2023-10-06 12:44:59,153:DEBUG: add connector connector_name='ybconnector_cdc_d87c07_test_cdc_07fe05' stream_id='8356253661614863b71be44215ae6b8f' db_name='cdc_d87c07' connector_host='172.151.18.78' table_list=['test_cdc_07fe05'] {'name': 'ybconnector_cdc_d87c07_test_cdc_07fe05', 'config': {'connector.class': 'io.debezium.connector.yugabytedb.YugabyteDBConnector', 'database.hostname': '172.151.17.232:5433,172.151.31.94:5433,172.151.30.97:5433', 'database.master.addresses': '172.151.17.232:7100,172.151.31.94:7100,172.151.30.97:7100', 'database.masterhost': '172.151.30.97', 'database.masterport': '7100', 'database.user': 'yugabyte', 'database.password': 'yugabyte', 'database.dbname': 'cdc_d87c07', 'database.server.name': 'db_cdc', 'database.streamid': '8356253661614863b71be44215ae6b8f', 'snapshot.mode': 'initial', 'admin.operation.timeout.ms': 600000, 'socket.read.timeout.ms': 600000, 'max.connector.retries': '10', 'operation.timeout.ms': 600000, 'topic.creation.default.compression.type': 'lz4', 'topic.creation.default.cleanup.policy': 'delete', 'topic.creation.default.partitions': 2, 'topic.creation.default.replication.factor': '1', 'tasks.max': '5', 'table.include.list': 'public.test_cdc_07fe05'}}
2023-10-06 12:44:59,228: INFO: sleep 5s 
2023-10-06 12:45:04,228:DEBUG: yugaware > https://172.151.17.254/api/v1/customers/de373293-eb0a-4524-8b80-a8b38615fc99/universes/402aeb21-12f9-4a6e-b261-ab5bf6382f10/leader
2023-10-06 12:45:04,435: INFO: adding yb connector stream_id='1a31f94c0da04f4ab290e96205266d77' db_name='cdc_d87c07' connector_host='172.151.29.242' table_list=['test_cdc_90f0dc']
2023-10-06 12:45:04,435:DEBUG: add connector connector_name='ybconnector_cdc_d87c07_test_cdc_90f0dc' stream_id='1a31f94c0da04f4ab290e96205266d77' db_name='cdc_d87c07' connector_host='172.151.29.242' table_list=['test_cdc_90f0dc'] {'name': 'ybconnector_cdc_d87c07_test_cdc_90f0dc', 'config': {'connector.class': 'io.debezium.connector.yugabytedb.YugabyteDBConnector', 'database.hostname': '172.151.17.232:5433,172.151.31.94:5433,172.151.30.97:5433', 'database.master.addresses': '172.151.17.232:7100,172.151.31.94:7100,172.151.30.97:7100', 'database.masterhost': '172.151.30.97', 'database.masterport': '7100', 'database.user': 'yugabyte', 'database.password': 'yugabyte', 'database.dbname': 'cdc_d87c07', 'database.server.name': 'db_cdc', 'database.streamid': '1a31f94c0da04f4ab290e96205266d77', 'snapshot.mode': 'initial', 'admin.operation.timeout.ms': 600000, 'socket.read.timeout.ms': 600000, 'max.connector.retries': '10', 'operation.timeout.ms': 600000, 'topic.creation.default.compression.type': 'lz4', 'topic.creation.default.cleanup.policy': 'delete', 'topic.creation.default.partitions': 2, 'topic.creation.default.replication.factor': '1', 'tasks.max': '5', 'table.include.list': 'public.test_cdc_90f0dc'}}
2023-10-06 12:45:04,512: INFO: sleep 5s 
2023-10-06 12:45:09,512:DEBUG: yugaware > https://172.151.17.254/api/v1/customers/de373293-eb0a-4524-8b80-a8b38615fc99/universes/402aeb21-12f9-4a6e-b261-ab5bf6382f10/leader
2023-10-06 12:45:09,593: INFO: adding yb connector stream_id='856a670817d545b2b9e6257cac249b16' db_name='cdc_d87c07' connector_host='172.151.18.78' table_list=['test_cdc_f88ced']
2023-10-06 12:45:09,594:DEBUG: add connector connector_name='ybconnector_cdc_d87c07_test_cdc_f88ced' stream_id='856a670817d545b2b9e6257cac249b16' db_name='cdc_d87c07' connector_host='172.151.18.78' table_list=['test_cdc_f88ced'] {'name': 'ybconnector_cdc_d87c07_test_cdc_f88ced', 'config': {'connector.class': 'io.debezium.connector.yugabytedb.YugabyteDBConnector', 'database.hostname': '172.151.17.232:5433,172.151.31.94:5433,172.151.30.97:5433', 'database.master.addresses': '172.151.17.232:7100,172.151.31.94:7100,172.151.30.97:7100', 'database.masterhost': '172.151.30.97', 'database.masterport': '7100', 'database.user': 'yugabyte', 'database.password': 'yugabyte', 'database.dbname': 'cdc_d87c07', 'database.server.name': 'db_cdc', 'database.streamid': '856a670817d545b2b9e6257cac249b16', 'snapshot.mode': 'initial', 'admin.operation.timeout.ms': 600000, 'socket.read.timeout.ms': 600000, 'max.connector.retries': '10', 'operation.timeout.ms': 600000, 'topic.creation.default.compression.type': 'lz4', 'topic.creation.default.cleanup.policy': 'delete', 'topic.creation.default.partitions': 2, 'topic.creation.default.replication.factor': '1', 'tasks.max': '5', 'table.include.list': 'public.test_cdc_f88ced'}}
2023-10-06 12:45:09,667: INFO: sleep 5s 
2023-10-06 12:45:14,667:DEBUG: yugaware > https://172.151.17.254/api/v1/customers/de373293-eb0a-4524-8b80-a8b38615fc99/universes/402aeb21-12f9-4a6e-b261-ab5bf6382f10/leader
2023-10-06 12:45:14,741: INFO: adding yb connector stream_id='1018bbb08ae04faab04a20fe65d9e2da' db_name='cdc_d87c07' connector_host='172.151.29.242' table_list=['test_cdc_071c82']
2023-10-06 12:45:14,741:DEBUG: add connector connector_name='ybconnector_cdc_d87c07_test_cdc_071c82' stream_id='1018bbb08ae04faab04a20fe65d9e2da' db_name='cdc_d87c07' connector_host='172.151.29.242' table_list=['test_cdc_071c82'] {'name': 'ybconnector_cdc_d87c07_test_cdc_071c82', 'config': {'connector.class': 'io.debezium.connector.yugabytedb.YugabyteDBConnector', 'database.hostname': '172.151.17.232:5433,172.151.31.94:5433,172.151.30.97:5433', 'database.master.addresses': '172.151.17.232:7100,172.151.31.94:7100,172.151.30.97:7100', 'database.masterhost': '172.151.30.97', 'database.masterport': '7100', 'database.user': 'yugabyte', 'database.password': 'yugabyte', 'database.dbname': 'cdc_d87c07', 'database.server.name': 'db_cdc', 'database.streamid': '1018bbb08ae04faab04a20fe65d9e2da', 'snapshot.mode': 'initial', 'admin.operation.timeout.ms': 600000, 'socket.read.timeout.ms': 600000, 'max.connector.retries': '10', 'operation.timeout.ms': 600000, 'topic.creation.default.compression.type': 'lz4', 'topic.creation.default.cleanup.policy': 'delete', 'topic.creation.default.partitions': 2, 'topic.creation.default.replication.factor': '1', 'tasks.max': '5', 'table.include.list': 'public.test_cdc_071c82'}}
2023-10-06 12:45:14,808: INFO: sleep 5s 
2023-10-06 12:45:19,808:DEBUG: yugaware > https://172.151.17.254/api/v1/customers/de373293-eb0a-4524-8b80-a8b38615fc99/universes/402aeb21-12f9-4a6e-b261-ab5bf6382f10/leader
2023-10-06 12:45:19,893: INFO: adding yb connector stream_id='133d9292b5ab47c7bc9e7ae80d9c938a' db_name='cdc_d87c07' connector_host='172.151.18.78' table_list=['test_cdc_e5db8f']
2023-10-06 12:45:19,893:DEBUG: add connector connector_name='ybconnector_cdc_d87c07_test_cdc_e5db8f' stream_id='133d9292b5ab47c7bc9e7ae80d9c938a' db_name='cdc_d87c07' connector_host='172.151.18.78' table_list=['test_cdc_e5db8f'] {'name': 'ybconnector_cdc_d87c07_test_cdc_e5db8f', 'config': {'connector.class': 'io.debezium.connector.yugabytedb.YugabyteDBConnector', 'database.hostname': '172.151.17.232:5433,172.151.31.94:5433,172.151.30.97:5433', 'database.master.addresses': '172.151.17.232:7100,172.151.31.94:7100,172.151.30.97:7100', 'database.masterhost': '172.151.30.97', 'database.masterport': '7100', 'database.user': 'yugabyte', 'database.password': 'yugabyte', 'database.dbname': 'cdc_d87c07', 'database.server.name': 'db_cdc', 'database.streamid': '133d9292b5ab47c7bc9e7ae80d9c938a', 'snapshot.mode': 'initial', 'admin.operation.timeout.ms': 600000, 'socket.read.timeout.ms': 600000, 'max.connector.retries': '10', 'operation.timeout.ms': 600000, 'topic.creation.default.compression.type': 'lz4', 'topic.creation.default.cleanup.policy': 'delete', 'topic.creation.default.partitions': 2, 'topic.creation.default.replication.factor': '1', 'tasks.max': '5', 'table.include.list': 'public.test_cdc_e5db8f'}}
2023-10-06 12:45:19,962: INFO: sleep 5s 
2023-10-06 12:45:24,962:DEBUG: yugaware > https://172.151.17.254/api/v1/customers/de373293-eb0a-4524-8b80-a8b38615fc99/universes/402aeb21-12f9-4a6e-b261-ab5bf6382f10/leader
2023-10-06 12:45:25,038: INFO: adding yb connector stream_id='b4131edb69bd47ed93a28898575df6aa' db_name='cdc_d87c07' connector_host='172.151.29.242' table_list=['test_cdc_af272d']
2023-10-06 12:45:25,039:DEBUG: add connector connector_name='ybconnector_cdc_d87c07_test_cdc_af272d' stream_id='b4131edb69bd47ed93a28898575df6aa' db_name='cdc_d87c07' connector_host='172.151.29.242' table_list=['test_cdc_af272d'] {'name': 'ybconnector_cdc_d87c07_test_cdc_af272d', 'config': {'connector.class': 'io.debezium.connector.yugabytedb.YugabyteDBConnector', 'database.hostname': '172.151.17.232:5433,172.151.31.94:5433,172.151.30.97:5433', 'database.master.addresses': '172.151.17.232:7100,172.151.31.94:7100,172.151.30.97:7100', 'database.masterhost': '172.151.30.97', 'database.masterport': '7100', 'database.user': 'yugabyte', 'database.password': 'yugabyte', 'database.dbname': 'cdc_d87c07', 'database.server.name': 'db_cdc', 'database.streamid': 'b4131edb69bd47ed93a28898575df6aa', 'snapshot.mode': 'initial', 'admin.operation.timeout.ms': 600000, 'socket.read.timeout.ms': 600000, 'max.connector.retries': '10', 'operation.timeout.ms': 600000, 'topic.creation.default.compression.type': 'lz4', 'topic.creation.default.cleanup.policy': 'delete', 'topic.creation.default.partitions': 2, 'topic.creation.default.replication.factor': '1', 'tasks.max': '5', 'table.include.list': 'public.test_cdc_af272d'}}
2023-10-06 12:45:25,106: INFO: sleep 5s 
```

### YugabyteDB version

2.18.4.0-b39

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-8227]: https://yugabyte.atlassian.net/browse/DB-8227?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by vaibhav-yb** [comment]
**Update:**
The error in the ticket is because of a different error which is thrown by service wrapped in a code `INVALID_REQUEST` which is then caught by the connector thinking it’s a tablet split error. Note that the way we verify if an error is a tablet split error in the connector is by following logic:

```
if (cdcException.getCDCError().getCode() == Code.TABLET_SPLIT || cdcException.getCDCError().getCode() == Code.INVALID_REQUEST) {
  // Process tablet split
}
```

The error being thrown is:

```
org.yb.client.CDCErrorException: Server[73c694800b5440dcb13eace4cb3b753f] NOT_FOUND[code 1]: The object '00004000000030008000000000000000.test_cdc_af272d_dummy_95b044' does not exist: OBJECT_NOT_FOUND
        at org.yb.client.TabletClient.dispatchCDCErrorOrReturnException(TabletClient.java:506)
        at org.yb.client.TabletClient.decode(TabletClient.java:437)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
        at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

Upon investigation, we found the following set of steps can lead to the above error:
1. A table gets created i.e. `old_table` (let’s assume this has just one tablet)
2. Client starts streaming on this using a `db_stream_id`
3. New table is created i.e. `new_table` and it gets added to the stream dynamically by a background thread
4. Tserver hosting the `old_table`'s tablet leader gets restarted
5. Upon restart, `new_table` is dropped
6. Now `GetChanges` is called on the `old_table` and service goes to fetch all the tablets for the given stream since the tablet is still being bootstrapped
7. While fetching all the tablets, we iterate over the tables in the stream ID and try to get tablets
8. If any error is hit, it is directly thrown to the client being wrapped with the error code `INVALID_REQUEST` and that’s what the connector saw.
