### ISSUE TITLE
Support yugabyte for django v4 and higher

### ISSUE THREAD

**Issue by aminmaghsodi** [yugabyte/yugabyte-db#19446]
Jira Link: [DB-8237](https://yugabyte.atlassian.net/browse/DB-8237)
### Description

Hi, Django v4 was launched and it is now on 4.2.6
When I startup my application with the below config,
`
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'db',
        'USER': 'user',
        'PASSWORD': 'lJUD0YCB',
        'HOST': '10.10.10.1',
        'PORT': '5433',
    }
}
`

it says: django.db.utils.NotSupportedError: PostgreSQL 12 or later is required (found 11.2).
I am now on latest version of Yugabyte. 2.18

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-8237]: https://yugabyte.atlassian.net/browse/DB-8237?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by ddorian** [comment]
@aminmaghsodi 

Please paste the full error trace

**Comment by aminmaghsodi** [comment]
`
python3 manage.py migrate:
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/amin/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/amin/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/amin/venv/lib/python3.8/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/amin/venv/lib/python3.8/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/home/amin/venv/lib/python3.8/site-packages/django/core/management/base.py", line 106, in wrapper
    res = handle_func(*args, **kwargs)
  File "/home/amin/venv/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 117, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/home/amin/venv/lib/python3.8/site-packages/django/db/migrations/executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/home/amin/venv/lib/python3.8/site-packages/django/db/migrations/loader.py", line 58, in __init__
    self.build_graph()
  File "/home/amin/venv/lib/python3.8/site-packages/django/db/migrations/loader.py", line 235, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/home/amin/venv/lib/python3.8/site-packages/django/db/migrations/recorder.py", line 81, in applied_migrations
    if self.has_table():
  File "/home/amin/venv/lib/python3.8/site-packages/django/db/migrations/recorder.py", line 57, in has_table
    with self.connection.cursor() as cursor:
  File "/home/amin/venv/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/home/amin/venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 330, in cursor
    return self._cursor()
  File "/home/amin/venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 306, in _cursor
    self.ensure_connection()
  File "/home/amin/venv/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/home/amin/venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 289, in ensure_connection
    self.connect()
  File "/home/amin/venv/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/home/amin/venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 272, in connect
    self.init_connection_state()
  File "/home/amin/venv/lib/python3.8/site-packages/django/db/backends/postgresql/base.py", line 309, in init_connection_state
    super().init_connection_state()
  File "/home/amin/venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 239, in init_connection_state
    self.check_database_version_supported()
  File "/home/amin/venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 214, in check_database_version_supported
    raise NotSupportedError(
django.db.utils.NotSupportedError: PostgreSQL 12 or later is required (found 11.2).

`

**Comment by aminmaghsodi** [comment]
The root cause was because of using variable with Array type in data model.

**Comment by aminmaghsodi** [comment]
I think it is because of using array field in model and it is an open issue on yugabyte, isn't it?

`  File "/home/amin/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 87, in _execute
    return self.cursor.execute(sql)
psycopg2.errors.FeatureNotSupported: This ALTER TABLE command is not yet supported.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/amin/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/amin/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/amin/venv/lib/python3.8/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/amin/venv/lib/python3.8/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/home/amin/venv/lib/python3.8/site-packages/django/core/management/base.py", line 106, in wrapper
    res = handle_func(*args, **kwargs)
  File "/home/amin/venv/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 356, in handle
    post_migrate_state = executor.migrate(
  File "/home/amin/venv/lib/python3.8/site-packages/django/db/migrations/executor.py", line 135, in migrate
    state = self._migrate_all_forwards(
  File "/home/amin/venv/lib/python3.8/site-packages/django/db/migrations/executor.py", line 167, in _migrate_all_forwards
    state = self.apply_migration(
  File "/home/amin/venv/lib/python3.8/site-packages/django/db/migrations/executor.py", line 252, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/home/amin/venv/lib/python3.8/site-packages/django/db/migrations/migration.py", line 132, in apply
    operation.database_forwards(
  File "/home/amin/venv/lib/python3.8/site-packages/django/db/migrations/operations/fields.py", line 108, in database_forwards
    schema_editor.add_field(
  File "/home/amin/venv/lib/python3.8/site-packages/django/db/backends/base/schema.py", line 712, in add_field
    self.execute(sql, params)
  File "/home/amin/venv/lib/python3.8/site-packages/django/db/backends/postgresql/schema.py", line 48, in execute
    return super().execute(sql, None)
  File "/home/amin/venv/lib/python3.8/site-packages/django/db/backends/base/schema.py", line 201, in execute
    cursor.execute(sql, params)
  File "/home/amin/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
  File "/home/amin/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/home/amin/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/amin/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/amin/venv/lib/python3.8/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/amin/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 87, in _execute
    return self.cursor.execute(sql)
django.db.utils.NotSupportedError: This ALTER TABLE command is not yet supported.


`

**Comment by ddorian** [comment]
Can you print the migration query that is failing?

**Comment by aminmaghsodi** [comment]
Actually it is django that raise the Error. it does not support postgres version lower than 12.
For example you can clone [this](https://github.com/steve-njuguna-k/Django-CRUD-Operations-Using-PostgreSQL) CRUD project from github, then change django version to 4.2.6. then it raises the bellow error:
`File "/home/amin/projects/Django-CRUD-Operations-Using-PostgreSQL/vnv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 214, in check_database_version_supported
    raise NotSupportedError(
django.db.utils.NotSupportedError: PostgreSQL 12 or later is required (found 11.2).`

**Comment by aminmaghsodi** [comment]
I have tested some Django CRUD projects on yugabyte. 
Actually yugabyte just works with Django version lower than 4.

**Comment by ddorian** [comment]
Looks like support was dropped in 4.2 https://docs.djangoproject.com/en/4.2/releases/4.2/#dropped-support-for-postgresql-11

This will be available in https://github.com/yugabyte/yugabyte-db/issues/9797

**Comment by ddorian** [comment]
Maybe we can disable this check in https://github.com/yugabyte/yb-django ?

cc @Sfurti-yb @nmalladi

**Comment by aminmaghsodi** [comment]
Anyone any help?

**Comment by ashetkar** [comment]
@aminmaghsodi We'll have to see if simply removing the version check is possible and check if it breaks anything. cc @Sfurti-yb. If not, we'll have to wait until #9797 gets resolved. We will get back on this soon.

**Comment by Sfurti-yb** [comment]
Using the [YugabyteDB backend for django](https://github.com/yugabyte/yb-django) should resolve this issue. The version check for it requires minimum database version as postgresql 10.
