### ISSUE TITLE
[YSQL] Java driver error with MONEY type

### ISSUE THREAD

**Issue by OlegLoginov** [YugaByte/yugabyte-db#1949]
To reproduce the issue uncomment the lines after 'TOFIX:':
```
    // MONEY
    { "'0'", "'1'", "'-1'", "'100'", "'-100'", "'2.0001'", "'5,.06'", "'5,.6'", "'$3.0001'",
      "'$40'", "'1,2'", "'1,23'",
      // TOFIX:
      // "'-92233720368547758.08'", "'92233720368547758.07'",
      // "'100,120'", "'100,23'", "'1000,23'", "'1,000,000.12'", "'2,000.00012'",
      // "'$3,000.00012'", "'$4,000,000.12'"
    },
```
in the test: java/yb-pgsql/src/test/java/org/yb/pgsql/TestPgSortNumeric.java
Run the test:  `ybd --java-test org.yb.pgsql.TestPgSortNumeric`

The error: `Bad value for type double : 100,120.00`
Note: the INSERT was successful but SELECT cannot create internal Object from the MONEY type value (value = '100,120.00' in the example).

The catched exception:
```
2019-07-30 16:39:20,036 (main) [ERROR - org.yb.BaseYBTest$1$2.logEventDetails(BaseYBTest.java:240)] YB Java test failed: class="org.yb.pgsql.TestPgSortOther", method="testSort"
org.postgresql.util.PSQLException: Bad value for type double : 100,120.00
    at org.postgresql.jdbc.PgResultSet.toDouble(PgResultSet.java:2934)
    at org.postgresql.jdbc.PgResultSet.getDouble(PgResultSet.java:2323)
    at org.postgresql.jdbc.PgResultSet.internalGetObject(PgResultSet.java:194)
    at org.postgresql.jdbc.PgResultSet.getObject(PgResultSet.java:2572)
    at org.yb.pgsql.BasePgSQLTest.getRowList(BasePgSQLTest.java:700)
    at org.yb.pgsql.BasePgSortingOrder.selectAndCompare(BasePgSortingOrder.java:199)
    at org.yb.pgsql.BasePgSortingOrder.RunTest(BasePgSortingOrder.java:233)
    at org.yb.pgsql.TestPgSortOther.testSort(TestPgSortOther.java:66)
```

**Comment by OlegLoginov** [comment]
Dependency: diff D6886.

**Comment by ndeodhar** [comment]
Seems to be a known issue with JDBC:
https://github.com/pgjdbc/pgjdbc/issues/425
https://stackoverflow.com/questions/54924969/bug-in-pg-jdbc-driver-money-db-type-bad-value-for-type-double
