### ISSUE TITLE
[CDCSDK] Saw tablet=null issue in colocation scenario, (non tablet-splitting case)

### ISSUE THREAD

**Issue by shamanthchandra-yb** [yugabyte/yugabyte-db#19538]
Jira Link: [DB-8328](https://yugabyte.atlassian.net/browse/DB-8328)
### Description

Please find report link in JIRA

![Profile (5)](https://github.com/yugabyte/yugabyte-db/assets/109518123/5ad241b9-74a0-454d-942d-ca19037cf007)

```
2023-10-13 21:03:17,299 ERROR  YugabyteDB|db_cdc|streaming|0  Producer failure   [io.debezium.pipeline.ErrorHandler]
org.yb.client.NonRecoverableException: Too many attempts: YRpc(method=GetTableLocations, service=yb.master.MasterService, tablet=null, attempt=40, maxAttempts=100, maxTimeoutMs=600000, elapsedTimeMs=591637). Master config (172.151.23.10:7100,172.151.17.205:7100,172.151.27.66:7100) has no leader.. Exceptions received: org.yb.client.ConnectionResetException: [Peer YB Master - 172.151.27.66:7100] Connection reset on [id: 0xa8a070b6],org.yb.client.ConnectionResetException: [Peer YB Master - 172.151.17.205:7100] Connection reset on [id: 0x0772f52b]
	at org.yb.client.AsyncYBClient.tooManyAttemptsOrTimeout(AsyncYBClient.java:2350)
	at org.yb.client.AsyncYBClient.delayedSendRpcToTablet(AsyncYBClient.java:2558)
	at org.yb.client.AsyncYBClient.access$1400(AsyncYBClient.java:173)
	at org.yb.client.AsyncYBClient$RetryRpcErrback.call(AsyncYBClient.java:2093)
	at org.yb.client.AsyncYBClient$RetryRpcErrback.call(AsyncYBClient.java:2077)
	at com.stumbleupon.async.Deferred.doCall(Deferred.java:1280)
	at com.stumbleupon.async.Deferred.runCallbacks(Deferred.java:1259)
	at com.stumbleupon.async.Deferred.callback(Deferred.java:1002)
	at org.yb.client.GetMasterRegistrationReceived.incrementCountAndCheckExhausted(GetMasterRegistrationReceived.java:151)
	at org.yb.client.GetMasterRegistrationReceived.access$300(GetMasterRegistrationReceived.java:58)
	at org.yb.client.GetMasterRegistrationReceived$GetMasterRegistrationErrCB.call(GetMasterRegistrationReceived.java:239)
	at org.yb.client.GetMasterRegistrationReceived$GetMasterRegistrationErrCB.call(GetMasterRegistrationReceived.java:229)
	at com.stumbleupon.async.Deferred.doCall(Deferred.java:1280)
	at com.stumbleupon.async.Deferred.runCallbacks(Deferred.java:1259)
	at com.stumbleupon.async.Deferred.callback(Deferred.java:1002)
	at org.yb.client.YRpc.handleCallback(YRpc.java:185)
	at org.yb.client.YRpc.errback(YRpc.java:205)
	at org.yb.client.TabletClient.failOrRetryRpc(TabletClient.java:702)
	at org.yb.client.TabletClient.failOrRetryRpcs(TabletClient.java:689)
	at org.yb.client.TabletClient.cleanup(TabletClient.java:677)
	at org.yb.client.TabletClient.doCleanup(TabletClient.java:651)
	at org.yb.client.AsyncYBClient.lambda$newClient$0(AsyncYBClient.java:2846)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:571)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:550)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:609)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:262)
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

### Source connector version

1.9.5.y.33-SNAPSHOT

### Connector configuration

`
add connector connector_name='ybconnector_cdc_6934b5_test_cdc_207d41_test_cdc_80ca4a' stream_id='983b662c221a4e0b9c1bb07e519cad9e' db_name='cdc_6934b5' connector_host='172.151.23.21' table_list=['test_cdc_207d41', 'test_cdc_80ca4a'] {'name': 'ybconnector_cdc_6934b5_test_cdc_207d41_test_cdc_80ca4a', 'config': {'connector.class': 'io.debezium.connector.yugabytedb.YugabyteDBConnector', 'database.hostname': '172.151.23.10:5433,172.151.17.205:5433,172.151.27.66:5433', 'database.master.addresses': '172.151.23.10:7100,172.151.17.205:7100,172.151.27.66:7100', 'database.masterhost': '172.151.23.10', 'database.masterport': '7100', 'database.user': 'yugabyte', 'database.password': 'yugabyte', 'database.dbname': 'cdc_6934b5', 'database.server.name': 'db_cdc', 'database.streamid': '983b662c221a4e0b9c1bb07e519cad9e', 'snapshot.mode': 'never', 'admin.operation.timeout.ms': 600000, 'socket.read.timeout.ms': 600000, 'max.connector.retries': '10', 'operation.timeout.ms': 600000, 'topic.creation.default.compression.type': 'lz4', 'topic.creation.default.cleanup.policy': 'delete', 'topic.creation.default.partitions': 2, 'topic.creation.default.replication.factor': '1', 'tasks.max': '5', 'table.include.list': 'public.test_cdc_207d41,public.test_cdc_80ca4a'}}
`

### YugabyteDB version

2.18.5.0-b1

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-8328]: https://yugabyte.atlassian.net/browse/DB-8328?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by shamanthchandra-yb** [comment]
Master leader was down and system didn't look right. Looks correct behaviour as per internal conversations.
