### ISSUE TITLE
build for arm64 ubuntu18.04 fail

### ISSUE THREAD

**Issue by goodforever** [yugabyte/yugabyte-db#1973]
Jira Link: [DB-1915](https://yugabyte.atlassian.net/browse/DB-1915)
I build and fail
branch v1.3.0
os  ubuntu 18.04
platform arm64v8 (NVIDIA Jetson Nano)
gcc v7.4.0
cmake version 3.14.6

OSError: [Errno 2] No such file or directory
CMake Error at CMakeLists.txt:578 (message):
  Thirdparty was built unsuccessfully, terminating.

All meassages

--------------------------------------------------------------------------------
Building zlib (common)
--------------------------------------------------------------------------------
Bootstrapping /home/lijz/workspace/yugabyte-db/thirdparty/build/common/zlib-1.2.11 from /home/lijz/workspace/yugabyte-db/thirdparty/src/zlib-1.2.11
/home/lijz/workspace/yugabyte-db/thirdparty/build_definitions
Traceback (most recent call last):
  File "/home/lijz/workspace/yugabyte-db/thirdparty/yb_build_thirdparty_main.py", line 786, in <module>
    main()
  File "/home/lijz/workspace/yugabyte-db/thirdparty/yb_build_thirdparty_main.py", line 783, in main
    builder.run()
  File "/home/lijz/workspace/yugabyte-db/thirdparty/yb_build_thirdparty_main.py", line 222, in run
    self.build(BUILD_TYPE_COMMON)
  File "/home/lijz/workspace/yugabyte-db/thirdparty/yb_build_thirdparty_main.py", line 601, in build
    self.build_dependency(dep)
  File "/home/lijz/workspace/yugabyte-db/thirdparty/yb_build_thirdparty_main.py", line 658, in build_dependency
    with PushDir(self.create_build_dir_and_prepare(dep)):
  File "/home/lijz/workspace/yugabyte-db/thirdparty/yb_build_thirdparty_main.py", line 745, in create_build_dir_and_prepare
    subprocess.check_call(['rsync', '-a', src_dir + '/', build_dir])
  File "/usr/lib/python2.7/subprocess.py", line 185, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
CMake Error at CMakeLists.txt:578 (message):
  Thirdparty was built unsuccessfully, terminating.

**Comment by ttyusupov** [comment]
Hi @goodforever , do you have `rsync` installed and available in `$PATH` ?

**Comment by goodforever** [comment]
@ttyusupov I have not installed rsync , is it need ?

**Comment by mbautin** [comment]
@goodforever -- have you been able to get the build going? Even though we currently only support the x86-64 architecture, I am curious to see what kind of issues you have discovered trying to build on arm64.
