### ISSUE TITLE
[DocDB] WaitForServer(type=YSQLSERVER) did not respond in the set time during rolling restart

### ISSUE THREAD

**Issue by shamanthchandra-yb** [yugabyte/yugabyte-db#19887]
Jira Link: [DB-8832](https://yugabyte.atlassian.net/browse/DB-8832)
### Description

Slack thread and logs in JIRA.

We are seeing this in packed rows stress test, where we are enabling/disabling packed rows and doing rolling restart.

The update process failed with:

```
java.lang.RuntimeException: WaitForServer : completed 1 out of 1 tasks. failed.
	at com.yugabyte.yw.commissioner.TaskExecutor$RunnableTask.runSubTasks(TaskExecutor.java:1152)
	at com.yugabyte.yw.commissioner.TaskExecutor$RunnableTask.runSubTasks(TaskExecutor.java:1110)
	at com.yugabyte.yw.commissioner.UpgradeTaskBase.runUpgrade(UpgradeTaskBase.java:109)
	at com.yugabyte.yw.commissioner.tasks.upgrade.GFlagsUpgrade.run(GFlagsUpgrade.java:55)
	at com.yugabyte.yw.commissioner.TaskExecutor$AbstractRunnableTask.run(TaskExecutor.java:844)
	at com.yugabyte.yw.commissioner.TaskExecutor$RunnableTask.run(TaskExecutor.java:1037)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.yugabyte.yw.common.logging.MDCAwareRunnable.run(MDCAwareRunnable.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.RuntimeException: WaitForServer(0a709eaf-0306-413a-b754-4cbfe779bdbc, yb-stress-auto-stress-timer-47580-n3, type=YSQLSERVER) did not respond in the set time.
	at com.yugabyte.yw.commissioner.tasks.subtasks.WaitForServer.run(WaitForServer.java:86)
	at com.yugabyte.yw.commissioner.TaskExecutor$AbstractRunnableTask.run(TaskExecutor.java:844)
	at com.yugabyte.yw.commissioner.TaskExecutor$RunnableSubTask.run(TaskExecutor.java:1222)
	... 6 common frames omitted
```

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-8832]: https://yugabyte.atlassian.net/browse/DB-8832?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
Closing this as a number of improvements in tablet bootstrap should have helped with this.
