### ISSUE TITLE
[YSQL] alter user fails in per-database catalog version mode when publication for all tables exist

### ISSUE THREAD

**Issue by myang2021** [yugabyte/yugabyte-db#19965]
Jira Link: [DB-8937](https://yugabyte.atlassian.net/browse/DB-8937)
### Description

1. create a cluster and convert it into per-database catalog version mode

```
yugabyte=# select * from pg_yb_catalog_version;
 db_oid | current_version | last_breaking_version
--------+-----------------+-----------------------
      1 |               1 |                     1
  13242 |               1 |                     1
  13243 |               1 |                     1
  13245 |               1 |                     1
  13246 |               1 |                     1
(5 rows)
```
The above query output indicates that the cluster is running in per-database
catalog version mode.

2. Create a publication for all tables
```
yugabyte=# CREATE PUBLICATION testpub_foralltables FOR ALL TABLES;
CREATE PUBLICATION

```
3. The following DDL statement fails
```
yugabyte=# ALTER USER yugabyte SUPERUSER;
ERROR:  cannot update table "pg_yb_catalog_version" because it does not have a replica identity and publishes updates
HINT:  To enable updating the table, set REPLICA IDENTITY using ALTER TABLE.
CONTEXT:  SQL function "yb_increment_all_db_catalog_versions" statement 1

```

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-8937]: https://yugabyte.atlassian.net/browse/DB-8937?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by myang2021** [comment]
```
#0  errfinish (dummy=0) at ../../../../../../../src/postgres/src/backend/utils/error/elog.c:665
#1  0x0000560f439a7094 in CheckCmdReplicaIdentity (rel=0x5e1bf90c7c0, cmd=CMD_UPDATE) at ../../../../../../src/postgres/src/backend/executor/execReplication.c:571
#2  0x0000560f43999728 in CheckValidResultRel (resultRelInfo=0x5e1bf7d2370, operation=CMD_UPDATE) at ../../../../../../src/postgres/src/backend/executor/execMain.c:1114
#3  0x0000560f439d9dbf in ExecInitModifyTable (node=0x5e1bf7d8928, estate=0x5e1bf7d2120, eflags=0) at ../../../../../../src/postgres/src/backend/executor/nodeModifyTable.c:2828
#4  0x0000560f439a4e05 in ExecInitNode (node=0x5e1bf7d8928, estate=0x5e1bf7d2120, eflags=0) at ../../../../../../src/postgres/src/backend/executor/execProcnode.c:177
#5  0x0000560f439985a7 in InitPlan (queryDesc=0x5e1bf7d9350, eflags=0) at ../../../../../../src/postgres/src/backend/executor/execMain.c:1049
#6  0x0000560f43997bec in standard_ExecutorStart (queryDesc=0x5e1bf7d9350, eflags=0) at ../../../../../../src/postgres/src/backend/executor/execMain.c:255
#7  0x00007f450ff52aee in pgss_ExecutorStart (queryDesc=0x5e1bf7d9350, eflags=0) at ../../../../../src/postgres/contrib/pg_stat_statements/pg_stat_statements.c:1258
#8  0x00007f450ff19e0d in ybpgm_ExecutorStart (queryDesc=0x5e1bf7d9350, eflags=0) at ../../../../../src/postgres/contrib/yb_pg_metrics/yb_pg_metrics.c:479
#9  0x00007f450ff10bed in pgaudit_NextExecutorStart_hook (queryDesc=0x5e1bf7d9350, eflags=0) at ../../../../../src/postgres/contrib/pgaudit/pgaudit.c:1084
#10 0x00007f450ff10255 in pgaudit_ExecutorStart_hook (queryDesc=0x5e1bf7d9350, eflags=0) at ../../../../../src/postgres/contrib/pgaudit/pgaudit.c:1101
#11 0x0000560f439978c3 in ExecutorStart (queryDesc=0x5e1bf7d9350, eflags=0) at ../../../../../../src/postgres/src/backend/executor/execMain.c:136
#12 0x0000560f439afea1 in postquel_start (es=0x5e1bf7d8ff0, fcache=0x5e1bf7ae120) at ../../../../../../src/postgres/src/backend/executor/functions.c:865
#13 0x0000560f439aee19 in fmgr_sql (fcinfo=0x7ffd0c7dbc00) at ../../../../../../src/postgres/src/backend/executor/functions.c:1205
#14 0x0000560f4377752b in YbCallSQLIncrementCatalogVersions (is_breaking_change=true) at ../../../../../../../src/postgres/src/backend/catalog/yb_catalog/yb_catalog_version.c:118
#15 0x0000560f4377429f in YbIncrementMasterDBCatalogVersionTableEntryImpl (db_oid=13245, is_breaking_change=true, is_global_ddl=true) at ../../../../../../../src/postgres/src/backend/catalog/yb_catalog/yb_catalog_version.c:143
#16 0x0000560f437741eb in YbIncrementMasterCatalogVersionTableEntry (is_breaking_change=true, is_global_ddl=true) at ../../../../../../../src/postgres/src/backend/catalog/yb_catalog/yb_catalog_version.c:250
#17 0x0000560f43e673e8 in YBDecrementDdlNestingLevel () at ../../../../../../../src/postgres/src/backend/utils/misc/pg_yb_utils.c:1480
#18 0x0000560f43e6f570 in YBTxnDdlProcessUtility (pstmt=0x5e1bfd21e30, queryString=0x5e1bfd20120 "ALTER USER yugabyte SUPERUSER;", context=PROCESS_UTILITY_TOPLEVEL, params=0x0, queryEnv=0x0, dest=0x5e1bfd21f48, completionTag=0x7ffd0c7dc860 "") at ../../../../../../../src/postgres/src/backend/utils/misc/pg_yb_utils.c:2001
#19 0x0000560f43c2cc6e in ProcessUtility (pstmt=0x5e1bfd21e30, queryString=0x5e1bfd20120 "ALTER USER yugabyte SUPERUSER;", context=PROCESS_UTILITY_TOPLEVEL, params=0x0, queryEnv=0x0, dest=0x5e1bfd21f48, completionTag=0x7ffd0c7dc860 "") at ../../../../../../src/postgres/src/backend/tcop/utility.c:377
#20 0x0000560f43c2c2ae in PortalRunUtility (portal=0x5e1bf852120, pstmt=0x5e1bfd21e30, isTopLevel=true, setHoldSnapshot=false, dest=0x5e1bfd21f48, completionTag=0x7ffd0c7dc860 "") at ../../../../../../src/postgres/src/backend/tcop/pquery.c:1206
#21 0x0000560f43c2b526 in PortalRunMulti (portal=0x5e1bf852120, isTopLevel=true, setHoldSnapshot=false, dest=0x5e1bfd21f48, altdest=0x5e1bfd21f48, completionTag=0x7ffd0c7dc860 "") at ../../../../../../src/postgres/src/backend/tcop/pquery.c:1366
#22 0x0000560f43c2aa48 in PortalRun (portal=0x5e1bf852120, count=9223372036854775807, isTopLevel=true, run_once=true, dest=0x5e1bfd21f48, altdest=0x5e1bfd21f48, completionTag=0x7ffd0c7dc860 "") at ../../../../../../src/postgres/src/backend/tcop/pquery.c:815
#23 0x0000560f43c28033 in exec_simple_query (query_string=0x5e1bfd20120 "ALTER USER yugabyte SUPERUSER;") at ../../../../../../src/postgres/src/backend/tcop/postgres.c:1220
#24 0x0000560f43c25af5 in yb_exec_simple_query_impl (query_string=0x5e1bfd20120) at ../../../../../../src/postgres/src/backend/tcop/postgres.c:4767
#25 0x0000560f43c25c1f in yb_exec_query_wrapper_one_attempt (exec_context=0x5e1bfd20000, restart_data=0x7ffd0c7dcaa8, functor=0x560f43c25ae0 <yb_exec_simple_query_impl>, functor_context=0x5e1bfd20120, attempt=0, retry=0x7ffd0c7dca6f) at ../../../../../../src/postgres/src/backend/tcop/postgres.c:4735
#26 0x0000560f43c25aca in yb_exec_query_wrapper (exec_context=0x5e1bfd20000, restart_data=0x7ffd0c7dcaa8, functor=0x560f43c25ae0 <yb_exec_simple_query_impl>, functor_context=0x5e1bfd20120) at ../../../../../../src/postgres/src/backend/tcop/postgres.c:4759
#27 0x0000560f43c20fc5 in yb_exec_simple_query (query_string=0x5e1bfd20120 "ALTER USER yugabyte SUPERUSER;", exec_context=0x5e1bfd20000) at ../../../../../../src/postgres/src/backend/tcop/postgres.c:4782
#28 0x0000560f43c1faca in PostgresMain (argc=1, argv=0x5e1bfcd95c0, dbname=0x5e1bfcd9420 "yugabyte", username=0x5e1bfcd93f8 "yugabyte") at ../../../../../../src/postgres/src/backend/tcop/postgres.c:5407
#29 0x0000560f43b48089 in BackendRun (port=0x5e1bfc081e0) at ../../../../../../src/postgres/src/backend/postmaster/postmaster.c:4676
#30 0x0000560f43b47037 in BackendStartup (port=0x5e1bfc081e0) at ../../../../../../src/postgres/src/backend/postmaster/postmaster.c:4314
#31 0x0000560f43b45b0f in ServerLoop () at ../../../../../../src/postgres/src/backend/postmaster/postmaster.c:1775
#32 0x0000560f43b4273b in PostmasterMain (argc=25, argv=0x5e1bfd160d0) at ../../../../../../src/postgres/src/backend/postmaster/postmaster.c:1431
#33 0x0000560f43a3b9b8 in PostgresServerProcessMain (argc=25, argv=0x5e1bfd160d0) at ../../../../../../src/postgres/src/backend/main/main.c:234
#34 0x0000560f43a3bf72 in main ()

```
In per-database catalog version mode, we internally call call `yb_increment_all_db_catalog_versions` to update pg_yb_catalog_version table. In global-database catalog version mode, we directly issue an update on pg_yb_catalog_version table which by-passes `CheckCmdReplicaIdentity`. We should also by-pass
`CheckCmdReplicaIdentity` to mimic update of pg_yb_catalog_version under the global catalog version mode.
