### ISSUE TITLE
Encountered JedisConnectionException: Unexpected end of stream.

### ISSUE THREAD

**Issue by ash9r** [YugaByte/yugabyte-db#20]
Occasionally, we are hitting this error stack in our client, and it seems like YugaByte server may not be respecting the keep alive timeout on the connection.

I was looking at the redis code, it seems that the client timeout is infinite - https://github.com/antirez/redis/blob/3.2/src/server.h#L83 can you confirm that YB redis interface behaves the same way?

redis.clients.jedis.exceptions.JedisConnectionException: Unexpected end of stream.
       at redis.clients.util.RedisInputStream.ensureFill(RedisInputStream.java:199)
       at redis.clients.util.RedisInputStream.readByte(RedisInputStream.java:40)
       at redis.clients.jedis.Protocol.process(Protocol.java:167)
       at redis.clients.jedis.Protocol.read(Protocol.java:231)
       at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:363)
       at redis.clients.jedis.Connection.getAll(Connection.java:333)
       at redis.clients.jedis.Connection.getAll(Connection.java:325)
       at redis.clients.jedis.Pipeline.sync(Pipeline.java:99)

**Comment by kmuthukk** [comment]
hi @amitanandaiyer: I believe this issue has been recently resolved. If so, can you please link to relevant commit and close out the issue.

**Comment by amitanandaiyer** [comment]
Thanks @ash9r  for reporting this issue. 

    YB, by default, garbage collects unused connections if they have been idle for more than X secs. It looks like the default behavior in redis is to never garbage collect the connection. While, CQL sets the default to 120 sec.

   We've added support to set the flags separately for both the use cases, and updated the defaults to match Redis and CQL.  This was done in in https://github.com/YugaByte/yugabyte-db/commit/54f3b1393f9f60638755db715daea12cb1489273
