### ISSUE TITLE
[CDCSDK] [Tablet Split] Too many errors while trying to get checkpoint for tablet

### ISSUE THREAD

**Issue by shamanthchandra-yb** [yugabyte/yugabyte-db#20636]
Jira Link: [DB-9634](https://yugabyte.atlassian.net/browse/DB-9634)
### Description

Please find JIRA for stress run.

`
2024-01-15 17:41:22,530 ERROR  YugabyteDB|db_cdc|snapshot|2  Too many errors while trying to get checkpoint for tablet d528844c4aab41a4aa55afa642a24f58, all 10 retries failed.   [io.debezium.connector.yugabytedb.YugabyteDBSnapshotChangeEventSource]
`

Full stacktrace:

```
2024-01-15 17:41:22,544 ERROR  YugabyteDB|db_cdc|snapshot|2  Producer failure   [io.debezium.pipeline.ErrorHandler]
io.debezium.DebeziumException: java.lang.NullPointerException
        at io.debezium.connector.yugabytedb.YugabyteDBSnapshotChangeEventSource.execute(YugabyteDBSnapshotChangeEventSource.java:169)
        at io.debezium.connector.yugabytedb.YugabyteDBSnapshotChangeEventSource.execute(YugabyteDBSnapshotChangeEventSource.java:50)
        at io.debezium.pipeline.ChangeEventSourceCoordinator.doSnapshot(ChangeEventSourceCoordinator.java:155)
        at io.debezium.connector.yugabytedb.YugabyteDBChangeEventSourceCoordinator.executeChangeEventSources(YugabyteDBChangeEventSourceCoordinator.java:108)
        at io.debezium.pipeline.ChangeEventSourceCoordinator.lambda$start$0(ChangeEventSourceCoordinator.java:109)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.NullPointerException
        at java.base/java.util.concurrent.ConcurrentSkipListMap.findNear(ConcurrentSkipListMap.java:1015)
        at java.base/java.util.concurrent.ConcurrentSkipListMap.findNearEntry(ConcurrentSkipListMap.java:1058)
        at java.base/java.util.concurrent.ConcurrentSkipListMap.floorEntry(ConcurrentSkipListMap.java:1975)
        at org.yb.client.AsyncYBClient.getTablet(AsyncYBClient.java:2758)
        at org.yb.client.AsyncYBClient.locateTablet(AsyncYBClient.java:2416)
        at org.yb.client.AsyncYBClient.sendRpcToTablet(AsyncYBClient.java:2083)
        at org.yb.client.AsyncYBClient.getCheckpoint(AsyncYBClient.java:579)
        at org.yb.client.YBClient.getCheckpoint(YBClient.java:1746)
        at io.debezium.connector.yugabytedb.YugabyteDBSnapshotChangeEventSource.getCheckpointWithRetry(YugabyteDBSnapshotChangeEventSource.java:318)
        at io.debezium.connector.yugabytedb.YugabyteDBSnapshotChangeEventSource.doExecute(YugabyteDBSnapshotChangeEventSource.java:436)
        at io.debezium.connector.yugabytedb.YugabyteDBSnapshotChangeEventSource.execute(YugabyteDBSnapshotChangeEventSource.java:160)
        ... 9 more
```

### Source connector version

1.9.5.y.220.SNAPSHOT.2

### Connector configuration

```
adding yb connector stream_id='92ddd30a36f84d0eb38ac227ee135e97' db_name='cdc_ac0c5e' connector_host='172.151.25.127' table_list=['test_cdc_1b1dd0']
2024-01-15 16:36:22,810:DEBUG: add connector connector_name='ybconnector_cdc_ac0c5e_test_cdc_1b1dd0' stream_id='92ddd30a36f84d0eb38ac227ee135e97' db_name='cdc_ac0c5e' connector_host='172.151.25.127' table_list=['test_cdc_1b1dd0'] {'name': 'ybconnector_cdc_ac0c5e_test_cdc_1b1dd0', 'config': {'connector.class': 'io.debezium.connector.yugabytedb.YugabyteDBConnector', 'database.hostname': '172.151.27.162:5433,172.151.25.118:5433,172.151.29.231:5433', 'database.master.addresses': '172.151.27.162:7100,172.151.25.118:7100,172.151.29.231:7100', 'database.port': 5433, 'database.masterhost': '172.151.29.231', 'database.masterport': '7100', 'database.user': 'yugabyte', 'database.password': 'yugabyte', 'database.dbname': 'cdc_ac0c5e', 'database.server.name': 'db_cdc', 'database.streamid': '92ddd30a36f84d0eb38ac227ee135e97', 'snapshot.mode': 'initial', 'admin.operation.timeout.ms': 600000, 'socket.read.timeout.ms': 300000, 'max.connector.retries': '10', 'operation.timeout.ms': 600000, 'topic.creation.default.compression.type': 'lz4', 'topic.creation.default.cleanup.policy': 'delete', 'topic.creation.default.partitions': 2, 'topic.creation.default.replication.factor': '1', 'tasks.max': '5', 'table.include.list': 'public.test_cdc_1b1dd0'}}
2024-01-15 16:36:23,612: INFO: sleep 5s 
2024-01-15 16:36:28,612:DEBUG: yugaware > https://172.151.20.79/api/v1/customers/21405244-9607-49d1-ad51-77d096897162/universes/75697655-4fa2-49dd-97f2-8bf4923d7f00/leader
2024-01-15 16:36:28,634: INFO: adding yb connector stream_id='9b13413a66804d389ec38d613289b8b5' db_name='cdc_ac0c5e' connector_host='172.151.23.182' table_list=['test_cdc_73fc54']
2024-01-15 16:36:28,634:DEBUG: add connector connector_name='ybconnector_cdc_ac0c5e_test_cdc_73fc54' stream_id='9b13413a66804d389ec38d613289b8b5' db_name='cdc_ac0c5e' connector_host='172.151.23.182' table_list=['test_cdc_73fc54'] {'name': 'ybconnector_cdc_ac0c5e_test_cdc_73fc54', 'config': {'connector.class': 'io.debezium.connector.yugabytedb.YugabyteDBConnector', 'database.hostname': '172.151.27.162:5433,172.151.25.118:5433,172.151.29.231:5433', 'database.master.addresses': '172.151.27.162:7100,172.151.25.118:7100,172.151.29.231:7100', 'database.port': 5433, 'database.masterhost': '172.151.29.231', 'database.masterport': '7100', 'database.user': 'yugabyte', 'database.password': 'yugabyte', 'database.dbname': 'cdc_ac0c5e', 'database.server.name': 'db_cdc', 'database.streamid': '9b13413a66804d389ec38d613289b8b5', 'snapshot.mode': 'initial', 'admin.operation.timeout.ms': 600000, 'socket.read.timeout.ms': 300000, 'max.connector.retries': '10', 'operation.timeout.ms': 600000, 'topic.creation.default.compression.type': 'lz4', 'topic.creation.default.cleanup.policy': 'delete', 'topic.creation.default.partitions': 2, 'topic.creation.default.replication.factor': '1', 'tasks.max': '5', 'table.include.list': 'public.test_cdc_73fc54'}}
2024-01-15 16:36:29,317: INFO: sleep 5s 
2024-01-15 16:36:34,318:DEBUG: yugaware > https://172.151.20.79/api/v1/customers/21405244-9607-49d1-ad51-77d096897162/universes/75697655-4fa2-49dd-97f2-8bf4923d7f00/leader
2024-01-15 16:36:34,336: INFO: adding yb connector stream_id='e1ebe82f0a5a422f8d98021cad8ab4c9' db_name='cdc_ac0c5e' connector_host='172.151.25.127' table_list=['test_cdc_6edfb1']
2024-01-15 16:36:34,336:DEBUG: add connector connector_name='ybconnector_cdc_ac0c5e_test_cdc_6edfb1' stream_id='e1ebe82f0a5a422f8d98021cad8ab4c9' db_name='cdc_ac0c5e' connector_host='172.151.25.127' table_list=['test_cdc_6edfb1'] {'name': 'ybconnector_cdc_ac0c5e_test_cdc_6edfb1', 'config': {'connector.class': 'io.debezium.connector.yugabytedb.YugabyteDBConnector', 'database.hostname': '172.151.27.162:5433,172.151.25.118:5433,172.151.29.231:5433', 'database.master.addresses': '172.151.27.162:7100,172.151.25.118:7100,172.151.29.231:7100', 'database.port': 5433, 'database.masterhost': '172.151.29.231', 'database.masterport': '7100', 'database.user': 'yugabyte', 'database.password': 'yugabyte', 'database.dbname': 'cdc_ac0c5e', 'database.server.name': 'db_cdc', 'database.streamid': 'e1ebe82f0a5a422f8d98021cad8ab4c9', 'snapshot.mode': 'initial', 'admin.operation.timeout.ms': 600000, 'socket.read.timeout.ms': 300000, 'max.connector.retries': '10', 'operation.timeout.ms': 600000, 'topic.creation.default.compression.type': 'lz4', 'topic.creation.default.cleanup.policy': 'delete', 'topic.creation.default.partitions': 2, 'topic.creation.default.replication.factor': '1', 'tasks.max': '5', 'table.include.list': 'public.test_cdc_6edfb1'}}
2024-01-15 16:36:34,431: INFO: sleep 5s 
2024-01-15 16:36:39,432:DEBUG: yugaware > https://172.151.20.79/api/v1/customers/21405244-9607-49d1-ad51-77d096897162/universes/75697655-4fa2-49dd-97f2-8bf4923d7f00/leader
2024-01-15 16:36:39,451: INFO: adding yb connector stream_id='a433df393f044aee9cc71f30b11b2ccd' db_name='cdc_ac0c5e' connector_host='172.151.23.182' table_list=['test_cdc_5a416d']
2024-01-15 16:36:39,451:DEBUG: add connector connector_name='ybconnector_cdc_ac0c5e_test_cdc_5a416d' stream_id='a433df393f044aee9cc71f30b11b2ccd' db_name='cdc_ac0c5e' connector_host='172.151.23.182' table_list=['test_cdc_5a416d'] {'name': 'ybconnector_cdc_ac0c5e_test_cdc_5a416d', 'config': {'connector.class': 'io.debezium.connector.yugabytedb.YugabyteDBConnector', 'database.hostname': '172.151.27.162:5433,172.151.25.118:5433,172.151.29.231:5433', 'database.master.addresses': '172.151.27.162:7100,172.151.25.118:7100,172.151.29.231:7100', 'database.port': 5433, 'database.masterhost': '172.151.29.231', 'database.masterport': '7100', 'database.user': 'yugabyte', 'database.password': 'yugabyte', 'database.dbname': 'cdc_ac0c5e', 'database.server.name': 'db_cdc', 'database.streamid': 'a433df393f044aee9cc71f30b11b2ccd', 'snapshot.mode': 'initial', 'admin.operation.timeout.ms': 600000, 'socket.read.timeout.ms': 300000, 'max.connector.retries': '10', 'operation.timeout.ms': 600000, 'topic.creation.default.compression.type': 'lz4', 'topic.creation.default.cleanup.policy': 'delete', 'topic.creation.default.partitions': 2, 'topic.creation.default.replication.factor': '1', 'tasks.max': '5', 'table.include.list': 'public.test_cdc_5a416d'}}
2024-01-15 16:36:39,544: INFO: sleep 5s 
2024-01-15 16:36:44,545:DEBUG: yugaware > https://172.151.20.79/api/v1/customers/21405244-9607-49d1-ad51-77d096897162/universes/75697655-4fa2-49dd-97f2-8bf4923d7f00/leader
2024-01-15 16:36:44,573: INFO: adding yb connector stream_id='ca68567fcd02460fbecdfa13d2372115' db_name='cdc_ac0c5e' connector_host='172.151.25.127' table_list=['test_cdc_cf4bc7']
2024-01-15 16:36:44,574:DEBUG: add connector connector_name='ybconnector_cdc_ac0c5e_test_cdc_cf4bc7' stream_id='ca68567fcd02460fbecdfa13d2372115' db_name='cdc_ac0c5e' connector_host='172.151.25.127' table_list=['test_cdc_cf4bc7'] {'name': 'ybconnector_cdc_ac0c5e_test_cdc_cf4bc7', 'config': {'connector.class': 'io.debezium.connector.yugabytedb.YugabyteDBConnector', 'database.hostname': '172.151.27.162:5433,172.151.25.118:5433,172.151.29.231:5433', 'database.master.addresses': '172.151.27.162:7100,172.151.25.118:7100,172.151.29.231:7100', 'database.port': 5433, 'database.masterhost': '172.151.29.231', 'database.masterport': '7100', 'database.user': 'yugabyte', 'database.password': 'yugabyte', 'database.dbname': 'cdc_ac0c5e', 'database.server.name': 'db_cdc', 'database.streamid': 'ca68567fcd02460fbecdfa13d2372115', 'snapshot.mode': 'initial', 'admin.operation.timeout.ms': 600000, 'socket.read.timeout.ms': 300000, 'max.connector.retries': '10', 'operation.timeout.ms': 600000, 'topic.creation.default.compression.type': 'lz4', 'topic.creation.default.cleanup.policy': 'delete', 'topic.creation.default.partitions': 2, 'topic.creation.default.replication.factor': '1', 'tasks.max': '5', 'table.include.list': 'public.test_cdc_cf4bc7'}}
2024-01-15 16:36:44,681: INFO: sleep 5s 
2024-01-15 16:36:49,681:DEBUG: yugaware > https://172.151.20.79/api/v1/customers/21405244-9607-49d1-ad51-77d096897162/universes/75697655-4fa2-49dd-97f2-8bf4923d7f00/leader
2024-01-15 16:36:49,700: INFO: adding yb connector stream_id='98a30ab91f8b4ab6854b7ba96223892e' db_name='cdc_ac0c5e' connector_host='172.151.23.182' table_list=['test_cdc_80166c']
2024-01-15 16:36:49,700:DEBUG: add connector connector_name='ybconnector_cdc_ac0c5e_test_cdc_80166c' stream_id='98a30ab91f8b4ab6854b7ba96223892e' db_name='cdc_ac0c5e' connector_host='172.151.23.182' table_list=['test_cdc_80166c'] {'name': 'ybconnector_cdc_ac0c5e_test_cdc_80166c', 'config': {'connector.class': 'io.debezium.connector.yugabytedb.YugabyteDBConnector', 'database.hostname': '172.151.27.162:5433,172.151.25.118:5433,172.151.29.231:5433', 'database.master.addresses': '172.151.27.162:7100,172.151.25.118:7100,172.151.29.231:7100', 'database.port': 5433, 'database.masterhost': '172.151.29.231', 'database.masterport': '7100', 'database.user': 'yugabyte', 'database.password': 'yugabyte', 'database.dbname': 'cdc_ac0c5e', 'database.server.name': 'db_cdc', 'database.streamid': '98a30ab91f8b4ab6854b7ba96223892e', 'snapshot.mode': 'initial', 'admin.operation.timeout.ms': 600000, 'socket.read.timeout.ms': 300000, 'max.connector.retries': '10', 'operation.timeout.ms': 600000, 'topic.creation.default.compression.type': 'lz4', 'topic.creation.default.cleanup.policy': 'delete', 'topic.creation.default.partitions': 2, 'topic.creation.default.replication.factor': '1', 'tasks.max': '5', 'table.include.list': 'public.test_cdc_80166c'}}
2024-01-15 16:36:49,778: INFO: sleep 5s 
2024-01-15 16:36:54,779:DEBUG: yugaware > https://172.151.20.79/api/v1/customers/21405244-9607-49d1-ad51-77d096897162/universes/75697655-4fa2-49dd-97f2-8bf4923d7f00/leader
2024-01-15 16:36:54,800: INFO: adding yb connector stream_id='fa8f0b1de3ab45e0add2537c3669ae9a' db_name='cdc_ac0c5e' connector_host='172.151.25.127' table_list=['test_cdc_2bd8e0']
2024-01-15 16:36:54,801:DEBUG: add connector connector_name='ybconnector_cdc_ac0c5e_test_cdc_2bd8e0' stream_id='fa8f0b1de3ab45e0add2537c3669ae9a' db_name='cdc_ac0c5e' connector_host='172.151.25.127' table_list=['test_cdc_2bd8e0'] {'name': 'ybconnector_cdc_ac0c5e_test_cdc_2bd8e0', 'config': {'connector.class': 'io.debezium.connector.yugabytedb.YugabyteDBConnector', 'database.hostname': '172.151.27.162:5433,172.151.25.118:5433,172.151.29.231:5433', 'database.master.addresses': '172.151.27.162:7100,172.151.25.118:7100,172.151.29.231:7100', 'database.port': 5433, 'database.masterhost': '172.151.29.231', 'database.masterport': '7100', 'database.user': 'yugabyte', 'database.password': 'yugabyte', 'database.dbname': 'cdc_ac0c5e', 'database.server.name': 'db_cdc', 'database.streamid': 'fa8f0b1de3ab45e0add2537c3669ae9a', 'snapshot.mode': 'initial', 'admin.operation.timeout.ms': 600000, 'socket.read.timeout.ms': 300000, 'max.connector.retries': '10', 'operation.timeout.ms': 600000, 'topic.creation.default.compression.type': 'lz4', 'topic.creation.default.cleanup.policy': 'delete', 'topic.creation.default.partitions': 2, 'topic.creation.default.replication.factor': '1', 'tasks.max': '5', 'table.include.list': 'public.test_cdc_2bd8e0'}}
2024-01-15 16:36:54,880: INFO: sleep 5s 
2024-01-15 16:36:59,880:DEBUG: yugaware > https://172.151.20.79/api/v1/customers/21405244-9607-49d1-ad51-77d096897162/universes/75697655-4fa2-49dd-97f2-8bf4923d7f00/leader
2024-01-15 16:36:59,929: INFO: adding yb connector stream_id='e257acec19594327b01b16b76998a3bf' db_name='cdc_ac0c5e' connector_host='172.151.23.182' table_list=['test_cdc_d5f046']
2024-01-15 16:36:59,929:DEBUG: add connector connector_name='ybconnector_cdc_ac0c5e_test_cdc_d5f046' stream_id='e257acec19594327b01b16b76998a3bf' db_name='cdc_ac0c5e' connector_host='172.151.23.182' table_list=['test_cdc_d5f046'] {'name': 'ybconnector_cdc_ac0c5e_test_cdc_d5f046', 'config': {'connector.class': 'io.debezium.connector.yugabytedb.YugabyteDBConnector', 'database.hostname': '172.151.27.162:5433,172.151.25.118:5433,172.151.29.231:5433', 'database.master.addresses': '172.151.27.162:7100,172.151.25.118:7100,172.151.29.231:7100', 'database.port': 5433, 'database.masterhost': '172.151.29.231', 'database.masterport': '7100', 'database.user': 'yugabyte', 'database.password': 'yugabyte', 'database.dbname': 'cdc_ac0c5e', 'database.server.name': 'db_cdc', 'database.streamid': 'e257acec19594327b01b16b76998a3bf', 'snapshot.mode': 'initial', 'admin.operation.timeout.ms': 600000, 'socket.read.timeout.ms': 300000, 'max.connector.retries': '10', 'operation.timeout.ms': 600000, 'topic.creation.default.compression.type': 'lz4', 'topic.creation.default.cleanup.policy': 'delete', 'topic.creation.default.partitions': 2, 'topic.creation.default.replication.factor': '1', 'tasks.max': '5', 'table.include.list': 'public.test_cdc_d5f046'}}
2024-01-15 16:37:00,011: INFO: sleep 5s 
2024-01-15 16:37:05,012:DEBUG: yugaware > https://172.151.20.79/api/v1/customers/21405244-9607-49d1-ad51-77d096897162/universes/75697655-4fa2-49dd-97f2-8bf4923d7f00/leader
2024-01-15 16:37:05,031: INFO: adding yb connector stream_id='b452e899901a47e6872b23c6788f2f31' db_name='cdc_ac0c5e' connector_host='172.151.25.127' table_list=['test_cdc_c45c46']
2024-01-15 16:37:05,031:DEBUG: add connector connector_name='ybconnector_cdc_ac0c5e_test_cdc_c45c46' stream_id='b452e899901a47e6872b23c6788f2f31' db_name='cdc_ac0c5e' connector_host='172.151.25.127' table_list=['test_cdc_c45c46'] {'name': 'ybconnector_cdc_ac0c5e_test_cdc_c45c46', 'config': {'connector.class': 'io.debezium.connector.yugabytedb.YugabyteDBConnector', 'database.hostname': '172.151.27.162:5433,172.151.25.118:5433,172.151.29.231:5433', 'database.master.addresses': '172.151.27.162:7100,172.151.25.118:7100,172.151.29.231:7100', 'database.port': 5433, 'database.masterhost': '172.151.29.231', 'database.masterport': '7100', 'database.user': 'yugabyte', 'database.password': 'yugabyte', 'database.dbname': 'cdc_ac0c5e', 'database.server.name': 'db_cdc', 'database.streamid': 'b452e899901a47e6872b23c6788f2f31', 'snapshot.mode': 'initial', 'admin.operation.timeout.ms': 600000, 'socket.read.timeout.ms': 300000, 'max.connector.retries': '10', 'operation.timeout.ms': 600000, 'topic.creation.default.compression.type': 'lz4', 'topic.creation.default.cleanup.policy': 'delete', 'topic.creation.default.partitions': 2, 'topic.creation.default.replication.factor': '1', 'tasks.max': '5', 'table.include.list': 'public.test_cdc_c45c46'}}
2024-01-15 16:37:05,106: INFO: sleep 5s 
2024-01-15 16:37:10,106:DEBUG: yugaware > https://172.151.20.79/api/v1/customers/21405244-9607-49d1-ad51-77d096897162/universes/75697655-4fa2-49dd-97f2-8bf4923d7f00/leader
2024-01-15 16:37:10,126: INFO: adding yb connector stream_id='2968d13879e947ba96401cb52bce5489' db_name='cdc_ac0c5e' connector_host='172.151.23.182' table_list=['test_cdc_9cee52']
2024-01-15 16:37:10,126:DEBUG: add connector connector_name='ybconnector_cdc_ac0c5e_test_cdc_9cee52' stream_id='2968d13879e947ba96401cb52bce5489' db_name='cdc_ac0c5e' connector_host='172.151.23.182' table_list=['test_cdc_9cee52'] {'name': 'ybconnector_cdc_ac0c5e_test_cdc_9cee52', 'config': {'connector.class': 'io.debezium.connector.yugabytedb.YugabyteDBConnector', 'database.hostname': '172.151.27.162:5433,172.151.25.118:5433,172.151.29.231:5433', 'database.master.addresses': '172.151.27.162:7100,172.151.25.118:7100,172.151.29.231:7100', 'database.port': 5433, 'database.masterhost': '172.151.29.231', 'database.masterport': '7100', 'database.user': 'yugabyte', 'database.password': 'yugabyte', 'database.dbname': 'cdc_ac0c5e', 'database.server.name': 'db_cdc', 'database.streamid': '2968d13879e947ba96401cb52bce5489', 'snapshot.mode': 'initial', 'admin.operation.timeout.ms': 600000, 'socket.read.timeout.ms': 300000, 'max.connector.retries': '10', 'operation.timeout.ms': 600000, 'topic.creation.default.compression.type': 'lz4', 'topic.creation.default.cleanup.policy': 'delete', 'topic.creation.default.partitions': 2, 'topic.creation.default.replication.factor': '1', 'tasks.max': '5', 'table.include.list': 'public.test_cdc_9cee52'}}
```

### YugabyteDB version

2.20.2.0-b79

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-9634]: https://yugabyte.atlassian.net/browse/DB-9634?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by vaibhav-yb** [comment]
**RCA:**
The connector flow today is such that:
1. Connector obtains the tablets from service
2. `HashPartitions` are created and the partition keys are passed down to the tasks
3. Tasks receive an immutable list of tablets and start processing that
4. In snapshot phase, connector directly rely on the passed list from the top level connector and take snapshot but in streaming phase it validates the tablet list again by asking the current tablets from service.
5. Now suppose if a tablet is split and connector is in streaming phase, connector will handle the split gracefully.
6. At this stage, if a task is restarted the flow will start from the snapshot phase itself and connector will try to get the checkpoint of tablets in the task to confirm whether to take snapshot. But the tablet list available here is stale and it will error out while getting the checkpoint since the tablet would have been deleted by this time.
