### ISSUE TITLE
[YSQL] Deadlock error in TPCC runs

### ISSUE THREAD

**Issue by sonalsagarwal** [yugabyte/yugabyte-db#20761]
### Description

We are observing a "Deadlock error" in TPCC 1k with restore tests. This is recently introduced and is intermittent error. Since it is not consistently reproducible, it difficult to identity when it was introduced. We first observed this on 2.21.1.0-b377 (in Dec).
Stack trace :
```
23:19:06,901 (Worker.java:542) WARN  - The DBMS rejected the transaction without an error code
com.yugabyte.util.PSQLException: ERROR: deadlock detected\n  Detail: Transaction 8812db88-1caa-431f-b0c0-a5c0c6a139f1 aborted due to a deadlock.
8812db88-1caa-431f-b0c0-a5c0c6a139f1 -> fdb0e15c-61e7-43cf-84ab-6123bcccd78f -> 8812db88-1caa-431f-b0c0-a5c0c6a139f1 : kDeadlock
at com.yugabyte.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2675)
at com.yugabyte.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2365)
at com.yugabyte.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:355)\n\tat com.yugabyte.jdbc.PgStatement.executeInternal(PgStatement.java:490)
at com.yugabyte.jdbc.PgStatement.execute(PgStatement.java:408)
at com.yugabyte.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:162)
at com.yugabyte.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:151)
at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
at com.oltpbenchmark.jdbc.InstrumentedPreparedStatement.execute(InstrumentedPreparedStatement.java:63)
at com.oltpbenchmark.benchmarks.tpcc.procedures.NewOrder.updateStockUsingProcedures(NewOrder.java:556)
at com.oltpbenchmark.benchmarks.tpcc.procedures.NewOrder.newOrderTransaction(NewOrder.java:344)
at com.oltpbenchmark.benchmarks.tpcc.procedures.NewOrder.run(NewOrder.java:251)
at com.oltpbenchmark.api.Worker.executeWork(Worker.java:606)
at com.oltpbenchmark.api.Worker.doWork(Worker.java:500)
at com.oltpbenchmark.api.Worker.run(Worker.java:368)
at java.base/java.lang.Thread.run(Thread.java:1589)
```

Please note : This error is mostly in the warmup phase, and does not cause to any failure in the run(retry may succeed). We get the TPCC results once the runs finishes.
This may not affect the performance numbers, but may be some recently introduced bug.

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

**Comment by basavaraj29** [comment]
> We first observed this on 2.21.1.0-b377 (in Dec).

@sonalsagarwal, do you mean `2.21.0.0-b377` ? because I don't see a `2.21.1.0-b377` yet. 

I can try looking at a few suspect commits in the nearby range if you conform the build id. 

Also when you say it could have been a recent regression - have you seen the TPCC warmup phase fail with generic transaction abort messages earlier? or is it that the warm phase never failed earlier?

**Comment by basavaraj29** [comment]
as per internal discussion, the deadlock seems to be due to the application logic. from the logs, we see two transactions updating rows of table `STOCK` in no pre-determined order, and hence the deadlock.

The consensus here is to edit the TPCC client logic to retry deadlocks/40P01.
