### ISSUE TITLE
[build] build failed when download initial_sys_catalog_snapshot_2.0.9.0_debug error

### ISSUE THREAD

**Issue by tier-cap** [yugabyte/yugabyte-db#20973]
### Description

download_and_extract_archive.py:118 mogdb-dev-0021 pid 11274 2024-02-07 17:21:50,642 INFO: Downloading https://github.com/yugabyte/yugabyte-db-ysql-catalog-snapshots/releases/download/v2.0.9.0/initial_sys_catalog_snapshot_2.0.9.0_debug.tar.gz to /opt/yb-build/ysql-sys-catalog-snapshots/initial_sys_catalog_snapshot_2.0.9.0_debug.tmp.3z3r1_k6/initial_sys_catalog_snapshot_2.0.9.0_debug.tar.gz
curl: (28) SSL connection timeout
download_and_extract_archive.py:59 mogdb-dev-0021 pid 11274 2024-02-07 17:26:51,440 ERROR: Error trying to run command: ['curl', '-LsS', 'https://github.com/yugabyte/yugabyte-db-ysql-catalog-snapshots/releases/download/v2.0.9.0/initial_sys_catalog_snapshot_2.0.9.0_debug.tar.gz', '-o', '/opt/yb-build/ysql-sys-catalog-snapshots/initial_sys_catalog_snapshot_2.0.9.0_debug.tmp.3z3r1_k6/initial_sys_catalog_snapshot_2.0.9.0_debug.tar.gz']
Traceback (most recent call last):
  File "/data1/xiaojinz/ygdb/yugabyte-db/python/yugabyte/download_and_extract_archive.py", line 384, in <module>
    main()
  File "/data1/xiaojinz/ygdb/yugabyte-db/python/yugabyte/download_and_extract_archive.py", line 380, in main
    nfs_cache_dir=args.nfs_cache_dir)
  File "/data1/xiaojinz/ygdb/yugabyte-db/python/yugabyte/download_and_extract_archive.py", line 232, in download_and_extract
    download_url(url, tmp_tar_gz_path)
  File "/data1/xiaojinz/ygdb/yugabyte-db/python/yugabyte/download_and_extract_archive.py", line 122, in download_url
    run_cmd(['curl', '-LsS', url, '-o', dest_path])
  File "/data1/xiaojinz/ygdb/yugabyte-db/python/yugabyte/download_and_extract_archive.py", line 57, in run_cmd
    subprocess.check_call(args)
  File "/usr/lib64/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['curl', '-LsS', 'https://github.com/yugabyte/yugabyte-db-ysql-catalog-snapshots/releases/download/v2.0.9.0/initial_sys_catalog_snapshot_2.0.9.0_debug.tar.gz', '-o', '/opt/yb-build/ysql-sys-catalog-snapshots/initial_sys_catalog_snapsho

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

**Comment by tier-cap** [comment]
Any progress, pls let me know, Thank you~
