### ISSUE TITLE
[DocDB] Core Dumps in CreateBatcher, after node addition while concurrent dml queries were being run against the cluster.

### ISSUE THREAD

**Issue by shishir2001-yb** [yugabyte/yugabyte-db#21103]
Jira Link: [DB-10072](https://yugabyte.atlassian.net/browse/DB-10072)
### Description

Tried on version **2.21.1.0-b117**

After the following [Commit](https://github.com/yugabyte/yugabyte-db/commit/fa30ddbbf3af6da6c649b27136f98a40d8211296),  one of the Xcluster + Wait on Conflict + Read Committed test started failing with the below core dumps. Looks like this issue is only observed after we add a new node to the universe.

```
Core was generated by `postgres: yugabyte test_read_committed_db_1 10.150.1.70(52730) INSERT         '.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f90d8e7facf in raise () from /lib64/libc.so.6
[Current thread is 1 (Thread 0x7f90d4a2c100 (LWP 39743))]
```
```
Core was generated by `/home/yugabyte/master/bin/yb-master --flagfile /home/yugabyte/master/conf/serve'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000055f75babfcc0 in yb::client::(anonymous namespace)::CreateBatcher(yb::client::YBSession::BatcherConfig const&) ()
[Current thread is 1 (Thread 0x7f9c4a61a700 (LWP 50373))]
```

**Note**: Node addition succeeded but core dumps were observed

It seems that all nodes crashed(DML queries were being executed on other nodes which failed with the below error)
```
psycopg2.OperationalError: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
```

Logs and backtrace
[2.21.1.0_testreadcommittedwocxclustercolocationtabletsplitting-aws-rf3_20240220_112208.zip](https://github.com/yugabyte/yugabyte-db/files/14347651/2.21.1.0_testreadcommittedwocxclustercolocationtabletsplitting-aws-rf3_20240220_112208.zip)

Test details
```
            - Create source and target Xcluster with required g-flags
            - Create 1 colocated and 1 non-colocated database
            - Create 2 colocated and 1 non-colocated table in the 1st database and
              1 table in non-colocated Database
            - Create indexes(Secondary, Partial and Unique)
            - Create a backup of both the database on source and restore it on target
            - Setup replication on both source and target
            - Start a thread which will execute flush and compaction on all the tables
                after every 20 mins.
            - Start 8 threads and perform the following operation for n number of times
                (There maybe some conflicts in DMLs)
                a. Insert some rows in all the tables
                b. Add a savepoint S1
                c. Update some rows in all the tables
                d. Add a savepoint S2
                e. Select some rows(FOR (UPDATE, SHARE,
                    NO KEY UPDATE, KEY SHARE, "")) in all the tables
                f. Add a savepoint S3
                g. Delete some rows in all the tables
                h. Add a savepoint S4
                i. Restore to any savepoint
                j. Increase age column of a constant PK
                k. Commit both the transaction
            - Start all the threads
            - Add a node ---------> Node addition succeeded but core dumps were observed
            - Wait for all DML threads to complete
            - Validate Read committed functionality
            - Validate no unexpected exception has occurred
            - Validate data on both source and target
```
G-flags:
```
t_flags.update({
                "enable_wait_queues": "true",
                "enable_deadlock_detection": "true",
                "enable_automatic_tablet_splitting": "true",
                "ysql_num_shards_per_tserver": 1,
                "enable_stream_compression": "true",
                "stream_compression_algo": "1",
                "ysql_output_buffer_size": "16214400",
                "scheduled_full_compaction_frequency_hours": "12",
                "scheduled_full_compaction_jitter_factor_percentage": "100",
                "scheduled_full_compaction_check_interval_min": "5",
                "yb_enable_read_committed_isolation": "true",
                "consistent_restore": "true"
            })
            m_flags.update({
                "enable_wait_queues": "true",
                "enable_deadlock_detection": "true",
                "yb_enable_read_committed_isolation": "true",
                "enable_automatic_tablet_splitting": "true",
                "tablet_split_high_phase_shard_count_per_node": 200,
                "tablet_split_low_phase_shard_count_per_node": 16,
                # high_phase_size 2MB
                "tablet_split_high_phase_size_threshold_bytes": 2097152,  # 2MB
                # low_phase_size 100KB
                "tablet_split_low_phase_size_threshold_bytes": 102400,  # 100 KB
                "enable_stream_compression": "true",
                "stream_compression_algo": "1",
                "ysql_output_buffer_size": "16214400",
                "consistent_restore": "true"
            })
```

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-10072]: https://yugabyte.atlassian.net/browse/DB-10072?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
```
Thread 1 (Thread 0x7fcde6afe700 (LWP 36099)):
#0  0x000055db6ac00cc0 in yb::client::(anonymous namespace)::CreateBatcher(yb::client::YBSession::BatcherConfig const&) ()
No symbol table info available.
#1  0x000055db6abff37a in yb::client::(anonymous namespace)::BatcherFlushDone(std::__1::shared_ptr<yb::client::internal::Batcher> const&, yb::Status const&, boost::function<void (yb::client::FlushStatus*)>, yb::client::YBSession::BatcherConfig) ()
No symbol table info available.
#2  0x000055db6ac00731 in boost::detail::function::void_function_obj_invoker1<std::__1::__bind<void (*)(std::__1::shared_ptr<yb::client::internal::Batcher> const&, yb::Status const&, boost::function<void (yb::client::FlushStatus*)>, yb::client::YBSession::BatcherConfig), std::__1::shared_ptr<yb::client::internal::Batcher> const&, std::__1::placeholders::__ph<1> const&, boost::function<void (yb::client::FlushStatus*)>, yb::client::YBSession::BatcherConfig&>, void, yb::Status const&>::invoke(boost::detail::function::function_buffer&, yb::Status const&) ()
No symbol table info available.
#3  0x000055db6ab50558 in yb::client::internal::Batcher::Run() ()
No symbol table info available.
#4  0x000055db6ab52846 in yb::client::internal::Batcher::FlushFinished() ()
No symbol table info available.
#5  0x000055db6ab487b6 in yb::client::internal::AsyncRpc::Finished(yb::Status const&) ()
No symbol table info available.
#6  0x000055db6ab4dc10 in std::__1::__function::__func<std::__1::__bind<void (yb::client::internal::AsyncRpc::*)(yb::Status const&), yb::client::internal::WriteRpc*, yb::Status::OK>, std::__1::allocator<std::__1::__bind<void (yb::client::internal::AsyncRpc::*)(yb::Status const&), yb::client::internal::WriteRpc*, yb::Status::OK> >, void ()>::operator()() ()
No symbol table info available.
#7  0x000055db6bb1808a in yb::rpc::OutboundCall::InvokeCallbackSync(std::__1::optional<std::__1::chrono::time_point<yb::CoarseMonoClock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > > >) ()
No symbol table info available.
#8  0x000055db6bbf1933 in yb::rpc::(anonymous namespace)::Worker::Execute() ()
No symbol table info available.
#9  0x000055db6c3e7863 in yb::Thread::SuperviseThread(void*) ()
No symbol table info available.
#10 0x00007fce185481ca in start_thread () from /lib64/libpthread.so.0
No symbol table info available.
#11 0x00007fce18799e73 in clone () from /lib64/libc.so.6
No symbol table info available.

```
