### ISSUE TITLE
yb-ctl hangs when starting a cluster with invalid master/tserver options

### ISSUE THREAD

**Issue by mbautin** [yugabyte/yugabyte-db#2165]
Jira Link: [DB-2187](https://yugabyte.atlassian.net/browse/DB-2187)
If we specify master/tserver options incorrectly (i.e. specify non-existent flags), yb-ctl still waits for servers to come up, even though it is clearly indicated in `.err` logs that the flags are incorrect.

Also, in general, if master/tserver do not start up within say 10 seconds, yb-ctl should give up waiting and report an error to the user.

**Comment by jj-kim** [comment]
I am now reproducing this easily.  Running CentOS release build on commit deaa1b80f784475b55315ce7ca0f848212e439c5 plus a small, unrelated patch.  I have verified that no Yugabyte postgres, yb-master, or yb-tserver processes are up before executing the command.

```sh
./bin/yb-ctl create --master_flags="foo"
```

```
Creating cluster.
Waiting for cluster to be ready.
Traceback (most recent call last):
  File "/net/****/share/code/yugabyte-db1/submodules/yugabyte-installation/bin/yb-ctl", line 1898, in <module>
    control.run()
  File "/net/****/share/code/yugabyte-db1/submodules/yugabyte-installation/bin/yb-ctl", line 1875, in run
    self.args.func()
  File "/net/****/share/code/yugabyte-db1/submodules/yugabyte-installation/bin/yb-ctl", line 1665, in create_cmd_impl
    self.wait_for_cluster_or_raise()
  File "/net/****/share/code/yugabyte-db1/submodules/yugabyte-installation/bin/yb-ctl", line 1510, in wait_for_cluster_or_raise
    raise RuntimeError("Timed out waiting for a YugaByte DB cluster!")
RuntimeError: Timed out waiting for a YugaByte DB cluster!
Viewing file /tmp/tmpxrGWjN:
2019-10-03 20:07:02,522 INFO: Starting master-1 with:
/net/****/share/code/yugabyte-db1/build/latest/bin/yb-master --fs_data_dirs "/net/****/share/yugabyte-data/node-1/disk-1" --webserver_interface 127.0.0.1 --rpc_bind_addresses 127.0.0.1 --v 0 --version_file_json_path=/net/****/share/code/yugabyte-db1/build/release-gcc-dynamic-ninja --replication_factor=1 --yb_num_shards_per_tserver 2 --ysql_num_shards_per_tserver=2 --master_addresses 127.0.0.1:7100 --use_initial_sys_catalog_snapshot --foo >"/net/****/share/yugabyte-data/node-1/disk-1/master.out" 2>"/net/****/share/yugabyte-data/node-1/disk-1/master.err" &
2019-10-03 20:07:02,539 INFO: Starting tserver-1 with:
/net/****/share/code/yugabyte-db1/build/latest/bin/yb-tserver --fs_data_dirs "/net/****/share/yugabyte-data/node-1/disk-1" --webserver_interface 127.0.0.1 --rpc_bind_addresses 127.0.0.1 --v 0 --version_file_json_path=/net/****/share/code/yugabyte-db1/build/release-gcc-dynamic-ninja --tserver_master_addrs=127.0.0.1:7100 --yb_num_shards_per_tserver=2 --redis_proxy_bind_address=127.0.0.1:6379 --cql_proxy_bind_address=127.0.0.1:9042 --local_ip_for_outbound_sockets=127.0.0.1 --use_cassandra_authentication=false --ysql_num_shards_per_tserver=2 --start_pgsql_proxy --pgsql_proxy_bind_address=127.0.0.1:5433 >"/net/****/share/yugabyte-data/node-1/disk-1/tserver.out" 2>"/net/****/share/yugabyte-data/node-1/disk-1/tserver.err" &
2019-10-03 20:07:02,544 INFO: Waiting for master and tserver processes to come up.
2019-10-03 20:07:02,576 INFO: Waiting for master leader election and tablet server registration.
2019-10-03 20:08:04,080 ERROR: Failed waiting for None tservers, got None
^^^ Encountered errors ^^^
```

**Comment by jj-kim** [comment]
I had this issue again on CentOS, but I did not look into the cause and rather solved it by logging out of everything.

I have this issue on macOS, and I have found the part where things get stuck:
```python
            output = call_get_output_maybe_error(
                    cmd_list_tservers,
                    should_get_error
                ).decode('utf-8')
```
`cmd_list_tservers` is `['/Users/****/code/yugabyte-db2/build/latest/bin/yb-admin', '--master_addresses', '127.0.0.1:7100', 'list_all_tablet_servers']`.

Here are tserver logs:
```
Log file created at: 2019/10/31 13:40:40
Running on machine: ****.local
Application fingerprint: version 2.0.4.0 build PRE_RELEASE revision e7fbd613704e6490e81e9e87a54aa328335d14a7 build_type DEBUG built at 31 Oct 2019 11:12:29 PST
Running duration (h:mm:ss): 0:00:00
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I1031 13:40:40.879808 250850624 tablet_server_main.cc:134] NumCPUs determined to be: 8
I1031 13:40:40.880904 250850624 tablet_server_main.cc:144] Setting tcmalloc max thread cache bytes to: 268435456
I1031 13:40:40.881193 250850624 mem_tracker.cc:250] MemTracker: hard memory limit is 13.600000 GB
I1031 13:40:40.881227 250850624 mem_tracker.cc:252] MemTracker: soft memory limit is 11.560000 GB
I1031 13:40:40.882763 250850624 shared_mem.cc:152] Using directory /tmp to store shared memory objects
I1031 13:40:40.884794 250850624 encrypted_file_factory.cc:66] Created encrypted file factory
I1031 13:40:41.384626 250850624 pg_wrapper.cc:302] initdb completed successfully. Database initialized at /Users/****/yugabyte-data/node-1/disk-1/pg_data
I1031 13:40:41.384780 250850624 tablet_server_main.cc:171] Starting PostgreSQL server listening on 127.0.0.1, port 5433
I1031 13:40:41.384841 250850624 pg_wrapper.cc:429] Starting PostgreSQL server
I1031 13:40:41.393198 250850624 pg_wrapper.cc:275] PostgreSQL server running as pid 77762
I1031 13:40:41.393996 250850624 tablet_server_main.cc:182] Initializing tablet server...
I1031 13:40:41.394729 250850624 server_base.cc:438] Could not load existing FS layout: Not found (yb/util/env_posix.cc:1405): /Users/****/yugabyte-data/node-1/disk-1/yb-data/tserver/instance: No such file or directory (system error 2)
I1031 13:40:41.394886 250850624 server_base.cc:439] Creating new FS layout
I1031 13:40:41.398633 250850624 fs_manager.cc:461] Generated new instance metadata in path /Users/****/yugabyte-data/node-1/disk-1/yb-data/tserver/instance:
uuid: "924d5050ea814a1d924c32d77057d59a"
format_stamp: "Formatted at 2019-10-31 20:40:41 on ****.local"
I1031 13:40:41.399910 250850624 fs_manager.cc:249] Opened local filesystem: /Users/****/yugabyte-data/node-1/disk-1
uuid: "924d5050ea814a1d924c32d77057d59a"
format_stamp: "Formatted at 2019-10-31 20:40:41 on ****.local"
W1031 13:40:41.400622 250850624 hybrid_clock.cc:109] HybridClock initialized in local mode (OS X only). Not suitable for distributed clusters.
I1031 13:40:41.401492 250850624 server_base.cc:223] Auto setting FLAGS_num_reactor_threads to 8
I1031 13:40:41.405681 250850624 ts_tablet_manager.cc:507] max_bootstrap_threads=7
I1031 13:40:41.406150 250850624 server_base.cc:477] Using private ip address 127.0.0.1
I1031 13:40:41.406428 250850624 tablet_server_main.cc:184] Starting tablet server...
I1031 13:40:41.406491 250850624 tablet_server.cc:256] Auto setting FLAGS_tablet_server_svc_num_threads to 256
I1031 13:40:41.406527 250850624 tablet_server.cc:265] Auto setting FLAGS_ts_consensus_svc_num_threads to 256
I1031 13:40:41.406672 41021440 async_initializer.cc:73] Starting to init ybclient
I1031 13:40:41.407495 41558016 async_initializer.cc:73] Starting to init ybclient
I1031 13:40:41.412497 250850624 webserver.cc:148] Starting webserver on 127.0.0.1:9000
I1031 13:40:41.412600 250850624 webserver.cc:153] Document root: /Users/****/code/yugabyte-db2/www
I1031 13:40:41.413448 250850624 webserver.cc:240] Webserver started. Bound to: http://127.0.0.1:9000/
I1031 13:40:41.414645 250850624 rpc_server.cc:167] RPC server started. Bound to: 127.0.0.1:9100
I1031 13:40:41.415176 250850624 tablet_server_main.cc:186] Tablet server successfully started.
I1031 13:40:41.416292 250850624 tablet_server_main.cc:206] Starting redis server...
I1031 13:40:41.416628 250850624 fs_manager.cc:249] Opened local filesystem: /Users/****/yugabyte-data/node-1/disk-1
uuid: "924d5050ea814a1d924c32d77057d59a"
format_stamp: "Formatted at 2019-10-31 20:40:41 on ****.local"
W1031 13:40:41.416949 250850624 hybrid_clock.cc:109] HybridClock initialized in local mode (OS X only). Not suitable for distributed clusters.
I1031 13:40:41.416939 37265408 tcp_stream.cc:293] { local: 127.0.0.1:49978 remote: 127.0.0.1:7100 }:  Recv failed: Network error (yb/util/net/socket.cc:538): recvmsg error: Connection refused (system error 61)
W1031 13:40:41.417331 43704320 heartbeater.cc:584] P 924d5050ea814a1d924c32d77057d59a: Failed to heartbeat to 127.0.0.1:7100: Network error (yb/util/net/socket.cc:538): Failed to ping master at 127.0.0.1:7100: recvmsg error: Connection refused (system error 61) tries=0, num=1, masters=0x000000010ee11668 -> [[127.0.0.1:7100]], code=Network error
W1031 13:40:41.418076 43704320 heartbeater.cc:584] P 924d5050ea814a1d924c32d77057d59a: Failed to heartbeat to 127.0.0.1:7100: Network error (yb/util/net/socket.cc:538): Failed to ping master at 127.0.0.1:7100: recvmsg error: Connection refused (system error 61) tries=1, num=1, masters=0x000000010ee11668 -> [[127.0.0.1:7100]], code=Network error
W1031 13:40:41.418735 43704320 heartbeater.cc:584] P 924d5050ea814a1d924c32d77057d59a: Failed to heartbeat to 127.0.0.1:7100: Network error (yb/util/net/socket.cc:538): Failed to ping master at 127.0.0.1:7100: recvmsg error: Connection refused (system error 61) tries=2, num=1, masters=0x000000010ee11668 -> [[127.0.0.1:7100]], code=Network error
W1031 13:40:41.418793 43704320 heartbeater.cc:321] P 924d5050ea814a1d924c32d77057d59a: Failed 3 heartbeats in a row: no longer allowing fast heartbeat attempts.
W1031 13:40:41.419469 43704320 heartbeater.cc:584] P 924d5050ea814a1d924c32d77057d59a: Failed to heartbeat to 127.0.0.1:7100: Network error (yb/util/net/socket.cc:538): Failed to ping master at 127.0.0.1:7100: recvmsg error: Connection refused (system error 61) tries=3, num=1, masters=0x000000010ee11668 -> [[127.0.0.1:7100]], code=Network error
```
Here are master logs:
```
Log file created at: 2019/10/31 13:40:40
Running on machine: ****.local
Application fingerprint: version 2.0.4.0 build PRE_RELEASE revision e7fbd613704e6490e81e9e87a54aa328335d14a7 build_type DEBUG built at 31 Oct 2019 11:12:29 PST
Running duration (h:mm:ss): 0:00:00
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I1031 13:40:40.879817 175041856 master_main.cc:93] NumCPUs determined to be: 8
I1031 13:40:40.881201 175041856 mem_tracker.cc:250] MemTracker: hard memory limit is 1.600000 GB
I1031 13:40:40.881237 175041856 mem_tracker.cc:252] MemTracker: soft memory limit is 1.360000 GB
I1031 13:40:40.884155 175041856 master_main.cc:114] Initializing master server...
I1031 13:40:40.884364 175041856 server_base.cc:438] Could not load existing FS layout: Not found (yb/util/env_posix.cc:1405): /Users/****/yugabyte-data/node-1/disk-1/yb-data/master/instance: No such file or directory (system error 2)
I1031 13:40:40.884405 175041856 server_base.cc:439] Creating new FS layout
I1031 13:40:40.886569 175041856 fs_manager.cc:461] Generated new instance metadata in path /Users/****/yugabyte-data/node-1/disk-1/yb-data/master/instance:
uuid: "12a110103b0b4768bf696eaeb8fb9fbe"
format_stamp: "Formatted at 2019-10-31 20:40:40 on ****.local"
I1031 13:40:40.887109 175041856 fs_manager.cc:249] Opened local filesystem: /Users/****/yugabyte-data/node-1/disk-1
uuid: "12a110103b0b4768bf696eaeb8fb9fbe"
format_stamp: "Formatted at 2019-10-31 20:40:40 on ****.local"
W1031 13:40:40.887447 175041856 hybrid_clock.cc:109] HybridClock initialized in local mode (OS X only). Not suitable for distributed clusters.
I1031 13:40:40.887879 175041856 server_base.cc:223] Auto setting FLAGS_num_reactor_threads to 8
I1031 13:40:40.890792 175041856 master_main.cc:117] Starting Master server...
I1031 13:40:40.895576 175041856 webserver.cc:148] Starting webserver on 127.0.0.1:7000
I1031 13:40:40.895609 175041856 webserver.cc:153] Document root: /Users/****/code/yugabyte-db2/www
I1031 13:40:40.895879 175041856 webserver.cc:240] Webserver started. Bound to: http://127.0.0.1:7000/
I1031 13:40:40.896291 175041856 rpc_server.cc:167] RPC server started. Bound to: 127.0.0.1:7100
I1031 13:40:40.896338 175041856 server_base.cc:477] Using private ip address 127.0.0.1
I1031 13:40:40.896682 207384576 sys_catalog.cc:260] Creating new SysCatalogTable data
```
