### ISSUE TITLE
Java sample apps recreate App object when using --run_time

### ISSUE THREAD

**Issue by mbautin** [YugaByte/yugabyte-db#220]
Reported by @bmatican.

Command used from a local ptest run trying to plumb through --run_time flag:
```
2018-03-31 00:00:02,083 test_base.py:403 INFO CassandraKeyValue workload started cmd=['/usr/bin/ssh', '-p', '54422', '-oStrictHostKeyChecking=no', '-i', '/n/users/bogdan/.yugabyte/yb-dev-aws-2.pem', 'centos@<some_ip_address>', '/usr/bin/java', '-jar', '/home/centos/yb-sample-apps.jar', '--num_unique_keys', '1000000', '--num_threads_read', '256', '--num_threads_write'
, '0', '--run_time', '60', '--workload', 'CassandraKeyValue', '--value_size', '16', '--nodes', '<some_ip_address>:9042,<some_ip_address>:9042,<some_ip_address>:9042', '--use_ascii_values', '--create_table_name', 'PerfTest_0', '--sanity_check_at_end']: pid=20714 retCode=None
```

Error reported:
```
2018-03-31 00:00:05,350 test_base.py:471 INFO 2018-03-31 00:00:05,298 [INFO|com.yugabyte.sample.common.CmdLineOpts|CmdLineOpts] Using a randomly generated UUID : 5905dd3b-9973-47a8-b829-f6339b2a0ca8
2018-03-31 00:00:05,374 test_base.py:471 INFO 2018-03-31 00:00:05,341 [INFO|com.yugabyte.sample.common.CmdLineOpts|CmdLineOpts] App: CassandraKeyValue
2018-03-31 00:00:05,374 test_base.py:471 INFO 2018-03-31 00:00:05,341 [INFO|com.yugabyte.sample.common.CmdLineOpts|CmdLineOpts] Run time (seconds): 60
2018-03-31 00:00:05,404 test_base.py:471 INFO 2018-03-31 00:00:05,343 [INFO|com.yugabyte.sample.common.CmdLineOpts|CmdLineOpts] Adding node: <some_ip_address>:9042
2018-03-31 00:00:05,404 test_base.py:471 INFO 2018-03-31 00:00:05,372 [INFO|com.yugabyte.sample.common.CmdLineOpts|CmdLineOpts] Adding node: <some_ip_address>:9042
2018-03-31 00:00:05,404 test_base.py:471 INFO 2018-03-31 00:00:05,372 [INFO|com.yugabyte.sample.common.CmdLineOpts|CmdLineOpts] Adding node: <some_ip_address>:9042
2018-03-31 00:00:05,404 test_base.py:471 INFO 2018-03-31 00:00:05,372 [INFO|com.yugabyte.sample.common.CmdLineOpts|CmdLineOpts] Num reader threads: 256, num writer threads: 0
2018-03-31 00:00:05,405 test_base.py:471 INFO 2018-03-31 00:00:05,372 [INFO|com.yugabyte.sample.common.CmdLineOpts|CmdLineOpts] Create table name: PerfTest_0
2018-03-31 00:00:05,405 test_base.py:471 INFO 2018-03-31 00:00:05,372 [INFO|com.yugabyte.sample.common.CmdLineOpts|CmdLineOpts] Num unique keys to insert: 1000000
2018-03-31 00:00:05,405 test_base.py:471 INFO 2018-03-31 00:00:05,372 [INFO|com.yugabyte.sample.common.CmdLineOpts|CmdLineOpts] Num keys to update: -1000001
2018-03-31 00:00:05,417 test_base.py:471 INFO 2018-03-31 00:00:05,372 [INFO|com.yugabyte.sample.common.CmdLineOpts|CmdLineOpts] Num keys to read: -1
2018-03-31 00:00:05,417 test_base.py:471 INFO 2018-03-31 00:00:05,373 [INFO|com.yugabyte.sample.common.CmdLineOpts|CmdLineOpts] Value size: 16
2018-03-31 00:00:05,417 test_base.py:471 INFO 2018-03-31 00:00:05,373 [INFO|com.yugabyte.sample.common.CmdLineOpts|CmdLineOpts] Restrict values to ASCII strings: true
2018-03-31 00:00:05,417 test_base.py:471 INFO 2018-03-31 00:00:05,373 [INFO|com.yugabyte.sample.common.CmdLineOpts|CmdLineOpts] Perform sanity check at end of app run: true
2018-03-31 00:00:05,417 test_base.py:471 INFO 2018-03-31 00:00:05,373 [INFO|com.yugabyte.sample.common.CmdLineOpts|CmdLineOpts] Table TTL (secs): -1
2018-03-31 00:00:05,417 test_base.py:471 INFO 2018-03-31 00:00:05,373 [INFO|com.yugabyte.sample.common.CmdLineOpts|CmdLineOpts] Local reads: false
2018-03-31 00:00:05,418 test_base.py:471 INFO 2018-03-31 00:00:05,374 [INFO|com.yugabyte.sample.common.CmdLineOpts|CmdLineOpts] Read only load: false
2018-03-31 00:00:05,535 test_base.py:471 INFO 2018-03-31 00:00:05,502 [INFO|com.yugabyte.sample.apps.AppBase|AppBase] Connecting to nodes: <some_ip_address>,<some_ip_address>,<some_ip_address>
2018-03-31 00:00:08,758 test_base.py:471 INFO 2018-03-31 00:00:08,725 [INFO|com.yugabyte.sample.apps.AppBase|AppBase] Created a Cassandra table using query: [CREATE TABLE IF NOT EXISTS PerfTest_0 (k varchar, v blob, primary key (k));]
2018-03-31 00:00:08,758 test_base.py:471 INFO 2018-03-31 00:00:08,725 [INFO|com.yugabyte.sample.Main|Main] Using 16 writer threads for pure read setup.
2018-03-31 00:00:18,469 test_base.py:471 INFO 2018-03-31 00:00:18,435 [INFO|com.yugabyte.sample.Main|Main] Setup step for pure reads done.
2018-03-31 00:00:18,473 test_base.py:471 INFO 2018-03-31 00:00:18,440 [INFO|com.yugabyte.sample.apps.AppBase|AppBase] Connecting to nodes: <some_ip_address>,<some_ip_address>,<some_ip_address>
2018-03-31 00:00:23,509 test_base.py:471 INFO 2018-03-31 00:00:23,475 [INFO|com.yugabyte.sample.common.metrics.MetricsTracker|MetricsTracker] Read: 170600.23 ops/sec (1.50 ms/op), 853060 total ops  |  Write: 0.00 ops/sec (0.00 ms/op), 0 total ops  |  Uptime: 18080 ms | maxWrittenKey: 100014 | maxGeneratedKey: 100014 |
2018-03-31 00:00:28,510 test_base.py:471 INFO 2018-03-31 00:00:28,475 [INFO|com.yugabyte.sample.common.metrics.MetricsTracker|MetricsTracker] Read: 194292.93 ops/sec (1.31 ms/op), 1831781 total ops  |  Write: 0.00 ops/sec (0.00 ms/op), 0 total ops  |  Uptime: 23080 ms | maxWrittenKey: 100014 | maxGeneratedKey: 100014 |
2018-03-31 00:00:33,511 test_base.py:471 INFO 2018-03-31 00:00:33,476 [INFO|com.yugabyte.sample.common.metrics.MetricsTracker|MetricsTracker] Read: 205492.32 ops/sec (1.25 ms/op), 2859366 total ops  |  Write: 0.00 ops/sec (0.00 ms/op), 0 total ops  |  Uptime: 28081 ms | maxWrittenKey: 100014 | maxGeneratedKey: 100014 |
2018-03-31 00:00:38,512 test_base.py:471 INFO 2018-03-31 00:00:38,476 [INFO|com.yugabyte.sample.common.metrics.MetricsTracker|MetricsTracker] Read: 214096.21 ops/sec (1.20 ms/op), 3929942 total ops  |  Write: 0.00 ops/sec (0.00 ms/op), 0 total ops  |  Uptime: 33081 ms | maxWrittenKey: 100014 | maxGeneratedKey: 100014 |
2018-03-31 00:00:43,513 test_base.py:471 INFO 2018-03-31 00:00:43,476 [INFO|com.yugabyte.sample.common.metrics.MetricsTracker|MetricsTracker] Read: 213141.27 ops/sec (1.20 ms/op), 4995748 total ops  |  Write: 0.00 ops/sec (0.00 ms/op), 0 total ops  |  Uptime: 38081 ms | maxWrittenKey: 100014 | maxGeneratedKey: 100014 |
2018-03-31 00:00:48,513 test_base.py:471 INFO 2018-03-31 00:00:48,477 [INFO|com.yugabyte.sample.common.metrics.MetricsTracker|MetricsTracker] Read: 214685.93 ops/sec (1.19 ms/op), 6069272 total ops  |  Write: 0.00 ops/sec (0.00 ms/op), 0 total ops  |  Uptime: 43082 ms | maxWrittenKey: 100014 | maxGeneratedKey: 100014 |
2018-03-31 00:00:53,514 test_base.py:471 INFO 2018-03-31 00:00:53,477 [INFO|com.yugabyte.sample.common.metrics.MetricsTracker|MetricsTracker] Read: 213790.49 ops/sec (1.20 ms/op), 7138322 total ops  |  Write: 0.00 ops/sec (0.00 ms/op), 0 total ops  |  Uptime: 48082 ms | maxWrittenKey: 100014 | maxGeneratedKey: 100014 |
2018-03-31 00:00:58,515 test_base.py:471 INFO 2018-03-31 00:00:58,478 [INFO|com.yugabyte.sample.common.metrics.MetricsTracker|MetricsTracker] Read: 215798.30 ops/sec (1.19 ms/op), 8217417 total ops  |  Write: 0.00 ops/sec (0.00 ms/op), 0 total ops  |  Uptime: 53083 ms | maxWrittenKey: 100014 | maxGeneratedKey: 100014 |
2018-03-31 00:01:03,516 test_base.py:471 INFO 2018-03-31 00:01:03,478 [INFO|com.yugabyte.sample.common.metrics.MetricsTracker|MetricsTracker] Read: 212664.62 ops/sec (1.20 ms/op), 9280841 total ops  |  Write: 0.00 ops/sec (0.00 ms/op), 0 total ops  |  Uptime: 58083 ms | maxWrittenKey: 100014 | maxGeneratedKey: 100014 |
2018-03-31 00:01:08,517 test_base.py:471 INFO 2018-03-31 00:01:08,479 [INFO|com.yugabyte.sample.common.metrics.MetricsTracker|MetricsTracker] Read: 214129.61 ops/sec (1.20 ms/op), 10351589 total ops  |  Write: 0.00 ops/sec (0.00 ms/op), 0 total ops  |  Uptime: 63084 ms | maxWrittenKey: 100014 | maxGeneratedKey: 100014 |
2018-03-31 00:01:13,517 test_base.py:471 INFO 2018-03-31 00:01:13,479 [INFO|com.yugabyte.sample.common.metrics.MetricsTracker|MetricsTracker] Read: 213992.94 ops/sec (1.20 ms/op), 11421655 total ops  |  Write: 0.00 ops/sec (0.00 ms/op), 0 total ops  |  Uptime: 68084 ms | maxWrittenKey: 100014 | maxGeneratedKey: 100014 |
2018-03-31 00:01:18,485 test_base.py:471 INFO 2018-03-31 00:01:18,446 [WARN|com.datastax.driver.core.Cluster|Cluster$Manager] Re-preparing already prepared query is generally an anti-pattern and will likely affect performance. Consider preparing the statement only once. Query='SELECT k, v FROM PerfTest_0 WHERE k = ?;'
2018-03-31 00:01:18,557 test_base.py:471 INFO 2018-03-31 00:01:18,455 [INFO|com.yugabyte.sample.apps.AppBase|AppBase] Caught Exception:
2018-03-31 00:01:18,558 test_base.py:471 INFO java.lang.IllegalStateException: Can't use this cluster instance because it was previously closed
2018-03-31 00:01:18,558 test_base.py:471 INFO   at com.datastax.driver.core.Cluster.checkNotClosed(Cluster.java:604)
2018-03-31 00:01:18,558 test_base.py:471 INFO   at com.datastax.driver.core.Cluster.connectAsync(Cluster.java:329)
2018-03-31 00:01:18,558 test_base.py:471 INFO   at com.datastax.driver.core.Cluster.connectAsync(Cluster.java:305)
2018-03-31 00:01:18,558 test_base.py:471 INFO   at com.datastax.driver.core.Cluster.connect(Cluster.java:247)
2018-03-31 00:01:18,558 test_base.py:471 INFO   at com.yugabyte.sample.apps.AppBase.createCassandraClient(AppBase.java:157)
2018-03-31 00:01:18,558 test_base.py:471 INFO   at com.yugabyte.sample.apps.AppBase.getCassandraClient(AppBase.java:101)
2018-03-31 00:01:18,558 test_base.py:471 INFO   at com.yugabyte.sample.apps.CassandraKeyValue.doRead(CassandraKeyValue.java:144)
2018-03-31 00:01:18,559 test_base.py:471 INFO   at com.yugabyte.sample.apps.AppBase.performRead(AppBase.java:541)
2018-03-31 00:01:18,559 test_base.py:471 INFO   at com.yugabyte.sample.common.IOPSThread.run(IOPSThread.java:88)
2018-03-31 00:01:18,559 test_base.py:471 INFO 2018-03-31 00:01:18,480 [INFO|com.yugabyte.sample.common.metrics.MetricsTracker|MetricsTracker] Read: 213433.22 ops/sec (1.19 ms/op), 12488905 total ops  |  Write: 0.00 ops/sec (0.00 ms/op), 0 total ops  |  Uptime: 73085 ms | maxWrittenKey: 100014 | maxGeneratedKey: 100014 |
```

Talked to @robertpang and we're both assuming this is due to a try/catch doing app.terminate() and potentially concurrent threads recreating the App object. We should introduce a stopped/terminated state in the App and disallow recreating the client/cluster in such a state.

**Comment by robertpang** [comment]
Fixed in commit [c19b14f](https://github.com/YugaByte/yugabyte-db/commit/c19b14fdb609d8ed83491f7791f70fee33875277).
