### ISSUE TITLE
[DocDB] Update cluster operation fails to add node with nemesis restart tserver processes

### ISSUE THREAD

**Issue by archit-rastogi** [yugabyte/yugabyte-db#22089]
Jira Link: [DB-11009](https://yugabyte.atlassian.net/browse/DB-11009)
### Description

Stress run:
http://stress.dev.yugabyte.com/stress_test/707f2d72-96db-4b8f-bcf3-5919d9692795

Description:
1. Add node to us-east-2a
2. Nemesis running concurrently: restart tserver processes 
    - us-west-2 region
    - us-east-2 region [read-only node]

YBA logs:
```
java.lang.RuntimeException: org.yb.client.ConnectionResetException: [Peer fakeUUID -> 172.151.44.167:9100] Connection reset on [id: 0xf0d51322, L:null ! R:/172.151.44.167:9100]
	at com.yugabyte.yw.commissioner.tasks.subtasks.SetFlagInMemory.run(SetFlagInMemory.java:107)
	at com.yugabyte.yw.commissioner.TaskExecutor$AbstractRunnableTask.run(TaskExecutor.java:908)
	at com.yugabyte.yw.commissioner.TaskExecutor$RunnableSubTask.run(TaskExecutor.java:1332)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at com.yugabyte.yw.common.logging.MDCAwareRunnable.run(MDCAwareRunnable.java:46)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.yb.client.ConnectionResetException: [Peer fakeUUID -> 172.151.44.167:9100] Connection reset on [id: 0xf0d51322, L:null ! R:/172.151.44.167:9100]
	at org.yb.client.TabletClient.cleanup(TabletClient.java:656)
	at org.yb.client.TabletClient.doCleanup(TabletClient.java:645)
	at org.yb.client.AsyncYBClient.lambda$newClient$0(AsyncYBClient.java:2960)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:583)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:559)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:636)
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:629)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:118)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:321)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:337)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	... 3 common frames omitted
```

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-11009]: https://yugabyte.atlassian.net/browse/DB-11009?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
@archit-rastogi , Can you clarify if the system was loaded? Was the nemesis run at the same time as add node? Does add node succeed on retry?

**Comment by archit-rastogi** [comment]
1. System was not loaded. cpu < 50 %, there 11 nodes (sync + async), replication factor 5
2. Yes nemesis was running, with random vm restart
3. Cant say, because test ended after failure.
