### ISSUE TITLE
[DocDB] Bank Workload with 1000 accounts, encountered deadlock errors

### ISSUE THREAD

**Issue by shamanthchandra-yb** [yugabyte/yugabyte-db#22197]
Jira Link: [DB-11121](https://yugabyte.atlassian.net/browse/DB-11121)
### Description

This issue was initially observed on 2024.1. But trying to run on 2.20.3 with `"enable_wait_queues": "true",` showed similar error.

Workload log and stress run in JIRA link.

```
  Detail: [Operation expired (yb/docdb/deadlock_detector.cc:376): Transaction 48f4c534-4460-4198-9aaa-fe9e61aaf89a aborted due to a deadlock.
48f4c534-4460-4198-9aaa-fe9e61aaf89a -> ce4d34f1-1b9c-444b-bff9-ca6593656bf6 -> 48f4c534-4460-4198-9aaa-fe9e61aaf89a : kDeadlock (transaction error 6)]
        at com.yugabyte.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2675) ~[yb-stress-sample-apps-1.1.47.jar:?]
        at com.yugabyte.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2365) ~[yb-stress-sample-apps-1.1.47.jar:?]
        at com.yugabyte.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:355) ~[yb-stress-sample-apps-1.1.47.jar:?]
        at com.yugabyte.jdbc.PgStatement.executeInternal(PgStatement.java:490) ~[yb-stress-sample-apps-1.1.47.jar:?]
        at com.yugabyte.jdbc.PgStatement.execute(PgStatement.java:408) ~[yb-stress-sample-apps-1.1.47.jar:?]
        at com.yugabyte.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:162) ~[yb-stress-sample-apps-1.1.47.jar:?]
        at com.yugabyte.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:130) ~[yb-stress-sample-apps-1.1.47.jar:?]
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61) ~[yb-stress-sample-apps-1.1.47.jar:?]
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java) ~[yb-stress-sample-apps-1.1.47.jar:?]
        at com.yugabyte.sample.apps.SqlBankLargeValues.evaluateUpdate(SqlBankLargeValues.java:199) ~[yb-stress-sample-apps-1.1.47.jar:?]
        at com.yugabyte.sample.apps.SqlBankLargeValues.doWrite(SqlBankLargeValues.java:365) [yb-stress-sample-apps-1.1.47.jar:?]
        at com.yugabyte.sample.apps.AppBase.performWrite(AppBase.java:981) [yb-stress-sample-apps-1.1.47.jar:?]
        at com.yugabyte.sample.common.IOPSThread.run(IOPSThread.java:88) [yb-stress-sample-apps-1.1.47.jar:?]
```

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-11121]: https://yugabyte.atlassian.net/browse/DB-11121?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
@shamanthchandra-yb , Closing this as this was confirmed to be a test issue based on offline discussion.
