### ISSUE TITLE
Seg fault in ParseFromCodedStream

### ISSUE THREAD

**Issue by amitanandaiyer** [YugaByte/yugabyte-db#2243]
b) bt
#0  0x00007fdab5fc6bc6 in google::protobuf::MessageLite::ParseFromCodedStream(google::protobuf::io::CodedInputStream*) ()
  from /home/yugabyte/yb-software/yugabyte-1.3.2.0-b19-centos-x86_64/lib/yb-thirdparty/libprotobuf.so.15
#1  0x00007fdaba84c61e in yb::pb_util::ParseFromArray (msg=0x3943bcf028,
   data=data@entry=0x10bd55770b "\n 11bfd1f8146e48248f93e53cc84338f5\020\003\032\305\001\n\b\b\003\020\347\365\343\217\001\020\254\230\243\217\001\032\250\001\b\002\022\243\001\b\t\022rRejecting Update request from peer 8f4b99858cac43e38969c56231d5e54d for earlier term 2. Current term is 3. Ops: []2(../../src/yb/cons"..., length=length@entry=236)
   at ../../src/yb/util/pb_util.cc:193
#2  0x00007fdabc24654c in yb::rpc::OutboundCall::SetResponse(yb::rpc::CallResponse&&) (this=this@entry=0x52d69c2c90,
   resp=resp@entry=<unknown type in /home/yugabyte/yb-software/yugabyte-1.3.2.0-b19-centos-x86_64/lib/yb/libyrpc.so, CU 0x4874a6, DIE 0x53585e>)
   at ../../src/yb/rpc/outbound_call.cc:415
#3  0x00007fdabc22ab5f in yb::rpc::Connection::HandleCallResponse (this=0x14c37210, call_data=<optimized out>) at ../../src/yb/rpc/connection.cc:312
#4  0x00007fdabc29941a in yb::rpc::YBOutboundConnectionContext::HandleCall (this=<optimized out>, connection=..., call_data=<optimized out>) at ../../src/yb/rpc/yb_rpc.cc:466
#5  0x00007fdabc2247a6 in yb::rpc::BinaryCallParser::Parse (this=0x307dfd00, connection=..., data=..., read_buffer_full=...) at ../../src/yb/rpc/binary_call_parser.cc:85
#6  0x00007fdabc2993f5 in yb::rpc::YBOutboundConnectionContext::ProcessCalls (this=<optimized out>, connection=..., data=..., read_buffer_full=...)
   at ../../src/yb/rpc/yb_rpc.cc:487
#7  0x00007fdabc22937f in yb::rpc::Connection::ProcessReceived (this=0x14c37210, data=..., read_buffer_full=...) at ../../src/yb/rpc/connection.cc:275
#8  0x00007fdabc28a3cc in yb::rpc::TcpStream::TryProcessReceived (this=this@entry=0x1694b1e0) at ../../src/yb/rpc/tcp_stream.cc:353
#9  0x00007fdabc28ceb6 in yb::rpc::TcpStream::ReadHandler (this=this@entry=0x1694b1e0) at ../../src/yb/rpc/tcp_stream.cc:302
#10 0x00007fdabc28ed0d in yb::rpc::TcpStream::Handler (this=0x1694b1e0, watcher=..., revents=1) at ../../src/yb/rpc/tcp_stream.cc:250
#11 0x00007fdab95ce98b in ev_invoke_pending () from /home/yugabyte/yb-software/yugabyte-1.3.2.0-b19-centos-x86_64/lib/yb-thirdparty/libev.so.4
#12 0x00007fdab95d1fda in ev_run () from /home/yugabyte/yb-software/yugabyte-1.3.2.0-b19-centos-x86_64/lib/yb-thirdparty/libev.so.4
#13 0x00007fdabc257a69 in run (flags=0, this=0x1124ba8) at ../../thirdparty/installed/common/include/ev++.h:211
#14 yb::rpc::Reactor::RunThread (this=0x1124b40) at ../../src/yb/rpc/reactor.cc:480
#15 0x00007fdaba880ed9 in operator() (this=0x146c728)
   at /home/yugabyte/yb-software/yugabyte-1.3.2.0-b19-centos-x86_64/linuxbrew-xxxxxxxxxxxxx/Cellar/gcc/5.5.0_4/include/c++/5.5.0/functional:2267
#16 yb::Thread::SuperviseThread (arg=<optimized out>) at ../../src/yb/util/thread.cc:690
#17 0x00007fdab538a694 in start_thread (arg=0x7fdaafe33700) at pthread_create.c:333
#18 0x00007fdab4ac741d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:1

**Comment by kmuthukk** [comment]
https://github.com/YugaByte/yugabyte-db/issues/2243
