### ISSUE TITLE
XX000: Operation failed. Try again.: Conflicts  with higher priority transaction in very surprising circumstances

### ISSUE THREAD

**Issue by bllewell** [yugabyte/yugabyte-db#2257]
Jira Link: [DB-1461](https://yugabyte.atlassian.net/browse/DB-1461)
Using YB  1.3.1.0 on macOS Mojave Version 10.14.6. Database created with plain `yb-ctl create`  so RF =1, and one node.

I have a Python program that mechanizes lots of tests. Before each test I set up a known starting state by deleting all rows in my test table and re-inserting what I want. The table is trivial, created just once for all the tests thus:
```
create table t(k int primary key, v int not null unique)
```
The setup for _each_ creates a session (with “AUTOCOMMIT On” mode) and does this:
```
delete from t
```
and then this:
```
with s as (select generate_series(1, 3) as a)
insert into t(k, v) select a as k, a*2 as v from s
```
Then it exits. (And then the test runs using two new concurrent sessions.) Then it's back for the next test. One program run does 64 tests—so 64 repeats of the setup. The program has various degrees of freedom. I invoke it with this script:
```
python basic_tests.py --db=yb --lvl=snp --v_unq=y > basic_tests_output/yb_snp_v_unq.txt
python basic_tests.py --db=yb --lvl=srl --v_unq=y > basic_tests_output/yb_srl_v_unq.txt
python basic_tests.py --db=pg --lvl=snp --v_unq=y > basic_tests_output/pg_snp_v_unq.txt
python basic_tests.py --db=pg --lvl=srl --v_unq=y > basic_tests_output/pg_srl_v_unq.txt

python basic_tests.py --db=yb --lvl=snp --v_unq=n > basic_tests_output/yb_snp_no_v_unq.txt
python basic_tests.py --db=yb --lvl=srl --v_unq=n > basic_tests_output/yb_srl_no_v_unq.txt
python basic_tests.py --db=pg --lvl=snp --v_unq=n > basic_tests_output/pg_snp_no_v_unq.txt
python basic_tests.py --db=pg --lvl=srl --v_unq=n > basic_tests_output/pg_srl_no_v_unq.txt
```
"db=pg" Means Postgres. You can cut those runs out. (I have them to compare behavior, YB vs PG.)

999 times out of 1000 (as it seems—and using this as a metaphor) it works as expected. (And it works 1000 times out of 1000 with Postgres.) But in the 1-in-1000 case, I get the serialization error:
```
XX000: Operation failed. Try again.: Conflicts with higher priority transaction
```
Because this is on my laptop, I can be 100% sure that, at the time the error occurs, mine is the only database client session.

The table is left after this error with the content it had before the setup attempt.

If I get a serialization error during the lifetime of a session, then I note this in the session object and don’t  honor any subsequent “execute” requests.

The program does allow feedback but I’d turned off most of the feedback output for the setup step ’cos seemed too banal to report in my output beyond “setup done”. (Little did I know.) The program design requires me simply to report the serialization error and continue with the next step. The error that causes my program to abort is downstream. I get "unique constraint violation" when I insert a colliding row. The row lingers on from the previous test when (following the serialization error that is this bug's subject) it isn't deleted by the setup.

Ask me if you want to know how to turn it on.

So I conclude, now, that it must be the “delete” that causes the apparently spurious serialization error.

The program is uploaded as `issue_2257.zip`. It contains `basic_tests.py` and `cmn.py`. (The latter is used by other programs too.) The programs import `argparse` and `psycopg2`.

**Comment by bllewell** [comment]
[issue_2257.zip](https://github.com/YugaByte/yugabyte-db/files/3593385/issue_2257.zip)

**Comment by bllewell** [comment]
I created a crude but effective stress test that reproduced the error 36 times in 25,600 executions of the "setup" step. The test took about 2.5 hours to run.

**So the bug probability is 0.14%.**

The attached `issue_2257_stress_test.zip` contains these files:

**1. stress_test.sh**

This has 100 repetitions of this:
```
python basic_tests.py --db=yb --lvl=snp --v_unq=y
python basic_tests.py --db=yb --lvl=srl --v_unq=y
python basic_tests.py --db=yb --lvl=snp --v_unq=n
python basic_tests.py --db=yb --lvl=srl --v_unq=n
```
Each run of `basic_tests.py` does the set up once for each of its 64 tests.

Start it like this:
```
source stress_test.sh > stress_test.txt
```
When the error occurs, the STDERR output is reported in the terminal window. I copied and pasted it into `stress_test_srderr.txt`.

**2. stress_test_srderr.txt**

The error shows up here like this:
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "basic_tests.py", line 414, in <module>
    main()
  File "basic_tests.py", line 404, in main
    sess_2_select)
  File "basic_tests.py", line 246, in do_test
    sess_2.execute(Stmts.insert_17_34_into_t, do_rule_off = l_do_rule_off)
  File "/Users/Bllewell/Documents/Bllewell_Documents/YugaByte/Python/SQL/Transaction_Isolation/Python/cmn.py", line 215, in execute
    assert False, "Unexpected database error"
AssertionError: Unexpected database error
Traceback (most recent call last):
  File "/Users/Bllewell/Documents/Bllewell_Documents/YugaByte/Python/SQL/Transaction_Isolation/Python/cmn.py", line 208, in execute
    self.cur.execute(statement.sql_text)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "t_pkey"
```
This is the downstream error that I mentioned. It's fully expected given how my program is organized. I expect "delete from t" to work! And so when I get a unique constraint violation error in the handler that's designed to detect a serialization error by inspecting the error text, I use a Python `assert` to abort. I used my favorite text editor to count the number of occurrences of `During handling of the above exception, another exception occurred`. There were 36 occurrences.

**3. stress_test.txt**

The error shows up here like this:
```
Test_57
  sess_2_many_txns:     True
  select_kind:          'select by k'
  sess_1_select:        'at end'
  sess_1_insert_midway: False
  sess_2_select:        False

Serialization error, Code: XX000
Operation failed. Try again.: Conflicts
 with higher priority transaction: d...
Rolled back
Starting state: 3 rows
```
As mentioned, I swallow this after reporting the serialization error and carry on. I don't want to clutter my demo code to detect this and abort. Doing so would serve only to advertise this worrisome bug!

**Comment by bllewell** [comment]
[issue_2257_stress_test.zip](https://github.com/YugaByte/yugabyte-db/files/3597273/issue_2257_stress_test.zip)

**Comment by bllewell** [comment]
Look at this. I tested it in YB 1.3.1 from the Internet—i.e. the version against which the present issue is reported.
```
-- Self-doc the AUTOCOMMIT setting
\set AUTOCOMMIT On

drop table if exists test;
create table test(n int primary key);
begin transaction;
insert into test values (1);
delete from test;
select * from test;
insert into test values (1);
```
The `select` still shows the inserted row. So the next thing that happens is that I get this error:
```
duplicate key value violates unique constraint "test_pkey"
```
This is roughly the scenario the of present issue. The difference is that, here, my Python program does the `delete` and the `insert` with `AUTOCOMMIT` set to `On` so that each SQL execution is done in its own separate txn. If I change the code above to mimic that, thus:
```
\set AUTOCOMMIT On
drop table if exists test;
create table test(n int primary key);
insert into test values (1);
delete from test;
select * from test;
insert into test values (1);
```
then the bug behavior vanishes. No idea, therefore, if the root cause of the bug that this new tiny testcase shows has any connection to the root cause of the present issue. Mentioning it for completeness.

**Comment by bllewell** [comment]
I re-tested using YB 2.0.0.0 (everything elase the same). The problem persists unchanged. But it occurs frequently enough that I had to modify my Python program to add a retry loop, thus:
```
def delete_from_t_and_insert_three_rows(params):
    # Executing Stmts.delete_from_t sometimes (with ~1% probability) causes
    # a spurious serialization error. See this
    #
    #   https://github.com/yugabyte/yugabyte-db/issues/2257
    #
    # But cmn.py is designed to handle all serialization errors, print the error text
    # and then turn all subsequent SQL execution during the remaining lifetime of the
    # session as no-ops. That approach is no good here.
    # So we have to this it in a retry loop — else downstream "unique key violated".

    # Limit it to 10 retries.
    for j in range(0, 11):
        if j > 0:
            print("Retry #: " + str(j))

        # We can safely take advantage of AUTOCOMMIT for these single-session DDLs.
        sess = cmn.Session(params, "", report_stmts=False)

        sess.execute(Stmts.delete_from_t)
        if sess.serialization_error:
            print("After delete: unexpected serialization error: Issue #2257")
            sess.close()
            continue

        sess.execute(Stmts.insert_three_rows_into_t)
        if sess.serialization_error:
            print("After insert: unexpected serialization error: Issue #2257")
            sess.close()
            continue

        sess.close()
        break

    print("Starting state: 3 rows")
```
I now have some more statistics:

1. The error (and hence the retry) occurs ONLY when I run the tests using `serializable` txns. At this level, the presence or absence of the unique constraint on `t.v` makes no difference.

2. Sometimes it takes several successive retries before the error doesn't re-occur. The biggest number of successive failures inside the retry loop that I've seen is FOUR.

3. My first version of the retry loop had "create session"—`sess = cmn.Session()`—and "exit session"—`sess.close()`—_outside_ of the loop. Then I also had a genuine infinite loop. Then if the error first occurred, it _NEVER_ went away even after minutes (so at least many thousands of retries). It seems that the session is irreparably damaged after the error first occurs.

**Comment by kriteshranjan** [comment]
Closing this issue based on AI validation. cc: @m-iancu , @VamsidharGunturu

**Comment by kriteshranjan** [comment]
AI validation notes (`yb-issue-2257-analysis.md`):

# Analysis: yugabyte/yugabyte-db#2257 (DB-1461)

**Title:** XX000: Operation failed. Try again.: Conflicts with higher priority transaction in very surprising circumstances
**Reported:** 2019-09-10 against YB 1.3.1.0 (macOS, yb-ctl, RF=1); reporter (bllewell) re-confirmed on YB 2.0.0.0.
**Reviewed:** 2026-08-19.
**Re-verified (reuse):** 2026-08-20 — issue thread unchanged since prior validation (state OPEN, updatedAt 2026-01-23T08:00:50Z); master citations re-checked live against the same checkout HEAD `a27ae83fc1` (`common_flags.cc:50-53` enable_wait_queues=true, `pg_yb_utils.c:10284-10287` ERRCODE_YB_TXN_CONFLICT→"could not serialize access due to concurrent update", `guc.c` yb_max_query_layer_retries default 60).

## Verdict
VALIDATED — the exact reported failure signature (`XX000: Operation failed. Try again.: ... Conflicts with higher priority transaction: <uuid>` on a plain autocommit `delete from t` whose only competitor is a read-only, later-rolled-back serializable transaction) was reproduced live on YB 2.0.0.0-b16, the version the reporter re-confirmed on; root cause located at file:line in the 1.3.1/2.0 source. Master and all current releases are NOT affected: three independent later changes (wait-on-conflict default, kConflict→40001 error mapping, query-layer retries) each remove the user-visible failure — 0 errors in 1,200 modern-loop iterations plus deterministic wait/retry cells. For a backlog reviewer the correct disposition is **Fixed**.

## Root cause
2019-era fail-on-conflict concurrency control + asynchronous transaction abort + no error translation/retry:

1. **ROLLBACK (and disconnect-abort) was fire-and-forget at the DocDB layer.** v1.3.1 `PgTxnManager::AbortTransaction()` calls `txn_->Abort()` and returns immediately (`src/yb/yql/pggate/pg_txn_manager.cc:136-149` @v1.3.1), unlike commit which blocks on `txn_->CommitFuture().get()` (`:131`). `YBTransaction::Impl::Abort` → `DoAbort` fires the `AbortTransaction` RPC to the status tablet asynchronously and only lazily requests intent cleanup on participants (`src/yb/client/transaction.cc:320-341,514-540` @v1.3.1). So after a client's ROLLBACK is acknowledged, the transaction remains PENDING at the coordinator for a short window, its intents still live.
2. **Serializable reads write intents.** `GetStrongIntentTypeSet(SERIALIZABLE, kRead)` returns `kStrongRead` (`src/yb/docdb/intent.cc:83-93` @v1.3.1) — the reporter's serializable test transactions leave read intents covering every row of tiny table `t` even when they only SELECTed. Snapshot-isolation reads leave none, which is why the reporter observed the error only in `--lvl=srl` runs (issue comment 5).
3. **Conflict resolution fails on a priority coin-flip against the ghost.** The next setup step's autocommit `delete from t` (a distributed transaction with a random priority) hits those intents. v1.3.1 `ConflictResolver`: statuses are fetched (`conflict_resolution.cc:283-318` @v1.3.1; a `TryAgain` status response is *assumed PENDING* at `:304-306`); committed/aborted txns are dropped (`Cleanup`, `:246-280`); for the remaining PENDING ghost, `CheckPriority` (`:499-517`) returns `MakeConflictStatus(id, "higher priority")` (`:62-69`, text `"Conflicts with $0 transaction: $1"`) whenever `our_priority < their_priority` — a ~50% coin-flip between two random-priority txns. If the deleter's priority is higher instead, it aborts the ghost and proceeds — hence intermittency.
4. **No translation, no retry.** 1.3.x/2.0 YSQL surfaced the raw DocDB status as SQLSTATE XX000 via `HandleYBStatus` (observed live: `LOCATION: HandleYBStatus, pg_yb_utils.c:242` @2.0.0.0). There was no kConflict→40001 mapping and no query-layer retry loop, so the transient race became a hard client-visible error and the autocommit DELETE rolled back (rows linger → the reporter's downstream unique-violation).

Window (ms of abort-RPC/Raft latency) × coin-flip (~0.5) ≈ the reported 0.14% (36/25,600).

The reporter's "session is irreparably damaged after the error" observation (comment 5, point 3) is a harness artifact: his `cmn.py` marks `serialization_error = True` and turns every later `execute()` into a no-op for the session's lifetime (cmn.py:199-225 in the attached zip), so same-session retries never actually re-ran the DELETE.

**Is master still affected? No.** Three independent layers each prevent the reported failure:

- **Wait-on-Conflict by default.** `enable_wait_queues` defaults to true (`src/yb/common/common_flags.cc:50-53`; commit `9451519f8e` 2023-11-30, #19837, first in 2.21/2024.1). A write meeting pending intents enters the wait queue (`src/yb/docdb/conflict_resolution.cc:1578` policy dispatch; `WaitOnConflictResolver::OnConflictingTransactionsFound` → `wait_queue_->WaitOn` at `:749`) and resumes when the ghost's abort lands — no error, no priorities involved.
- **Error mapping.** Even in legacy fail-on-conflict mode (`enable_wait_queues=false`), the conflict surfaces as SQLSTATE 40001 with PG-parity message `could not serialize access due to concurrent update`; the DocDB text (now `conflicts with higher priority transaction (our pri: ..., their pri: ...)`, `src/yb/docdb/conflict_resolution.cc:1132-1139`, emitted from `MakeConflictStatus` — live LOCATION `conflict_resolution.cc:106`) is demoted to DETAIL (`src/postgres/src/backend/utils/misc/pg_yb_utils.c:10284-10287`; commit `d177d9500f`, #16460). Never XX000.
- **Query-layer retries.** `yb_max_query_layer_retries` defaults to 60 (`src/postgres/src/backend/utils/misc/guc.c:6088-6101`); a single-statement autocommit DELETE hitting a transient 40001 is retried transparently (`src/postgres/src/backend/tcop/postgres.c:5328-5351`).

Residual (documented, not a defect): the abort RPC is still fire-and-forget on master (`txn_value->Abort()` in `DoFinishTransaction`, `src/yb/tserver/pg_client_session.cc:4450`), so the *physical* ghost-intent window still exists; and the priority check still exists behind the non-default `enable_wait_queues=false` (`conflict_resolution.cc:1107-1145`). But with default flags the window is absorbed by the wait queue, and even in legacy mode default retries absorbed it in every observed run (0/600).

## Trigger matrix

| # | Cell (version / config / action) | Predicted | Observed |
|---|---|---|---|
| O1a | 2.0.0.0-b16 defaults; pending read-only srl blocker on `t` (rollback later); autocommit `delete from t` | raw XX000 text on losing coin-flip | `ERROR: XX000: Operation failed. Try again.: 8e109178-... Conflicts with higher priority transaction: bab0a87d-...` — exact reported signature |
| O1b | same, repeat (fresh coin-flip) | success on winning coin-flip | `DELETE 3` |
| O2 | 2.0.0.0-b16 defaults; reporter-faithful teardown→setup ghost loop ×60 | ~0 hits (reported base rate 0.14% ⇒ E≈0.08 in 60) | 0 errors (consistent; deterministic O1a already pins the shape) |
| M1 | 2026.1.1.0 defaults; srl ghost loop ×300 | 0 errors | 0 errors |
| M2 | 2026.1.1.0 defaults; live idle srl read-only blocker + `delete from t` | blocks, then succeeds | blocked 5938.561 ms → `DELETE 3`, no error |
| M3 | 2026.1.1.0 `enable_wait_queues=false`, deleter RR + `yb_max_query_layer_retries=0`, blocker pri 0.9–1 / deleter 0–0.1 | immediate 40001, DETAIL has `conflicts with higher priority transaction` | 21.565 ms → `ERROR: 40001 ...` DETAIL `... conflicts with higher priority transaction (our pri: 1554622048164457642, their pri: 17267974722604890637) ... (conflict_resolution.cc:106)` |
| M3b | M3 with priorities reversed | instant success (deleter aborts blocker) | `DELETE 3` in 17.010 ms |
| M4 | 2026.1.1.0 `enable_wait_queues=false`, default retries; srl ghost loop ×300 | 0 errors | 0 errors |
| M4b | M4 + `yb_max_query_layer_retries=0` + RR deleter (closest 2019-defaults analog) ×300 | ≈0 (window µs-scale on modern single node) | 0 errors |
| M5 | 2026.1.1.0 defaults; snapshot-isolation ghost loop ×300 (control) | 0 errors (snapshot reads leave no intents) | 0 errors |
| S1 | 2026.1.1.0; issue-comment-4 side testcase (`begin; insert; delete; select` in one txn) | row deleted (old side bug fixed) | `DELETE 1`, select returns 0 rows, re-insert + commit OK |

11/11 informative cells match prediction (O1 attempts 3–4 discarded as vacuous: table was empty, so the read-only blocker held no matching intents).

## Reproduction

Runtime: podman on macOS/Apple Silicon. Historical cell runs the amd64 image under emulation.

**Historical (reproduces the reported error verbatim; YB 2.0.0.0):**

```sh
podman run -d --arch amd64 --name yb2257-old docker.io/yugabytedb/yugabyte:2.0.0.0-b16 bash -c \
  'mkdir -p /tmp/m /tmp/t; \
   /home/yugabyte/bin/yb-master --fs_data_dirs=/tmp/m --master_addresses=127.0.0.1:7100 \
     --rpc_bind_addresses=127.0.0.1:7100 --replication_factor=1 \
     --use_initial_sys_catalog_snapshot --logtostderr > /tmp/master.log 2>&1 & \
   sleep 15; \
   /home/yugabyte/bin/yb-tserver --fs_data_dirs=/tmp/t --tserver_master_addrs=127.0.0.1:7100 \
     --rpc_bind_addresses=127.0.0.1:9100 --start_pgsql_proxy \
     --pgsql_proxy_bind_address=0.0.0.0:5433 --logtostderr > /tmp/tserver.log 2>&1 & wait'
# wait until: ysqlsh -h 127.0.0.1 -p 5433 -U postgres -c "select 1;" succeeds (initdb under qemu: ~2-4 min)

podman exec yb2257-old bash -c '/home/yugabyte/bin/ysqlsh -h 127.0.0.1 -p 5433 -U postgres \
  -c "create table t(k int primary key, v int not null unique);" \
  -c "with s as (select generate_series(1, 3) as a) insert into t(k, v) select a as k, a*2 as v from s;"'

# widen the reported race window: a read-only serializable txn on t, still pending
podman exec -d yb2257-old bash -c 'printf "start transaction isolation level serializable;\nselect k, v from t order by v;\nselect pg_sleep(15);\nrollback;\n" | /home/yugabyte/bin/ysqlsh -h 127.0.0.1 -p 5433 -U postgres > /tmp/b.out 2>&1'
sleep 6
podman exec yb2257-old bash -c 'printf "\\\\set VERBOSITY verbose\ndelete from t;\n" | /home/yugabyte/bin/ysqlsh -h 127.0.0.1 -p 5433 -U postgres -a'
# repeat the pair a few times; each attempt is a fresh priority coin-flip
```

Failure signature to grep for (hit on attempt 1):
`XX000: Operation failed. Try again.: .* Conflicts with higher priority transaction`
Success alternative (attempt 2): `DELETE 3`. Re-insert the 3 rows between attempts.

**Modern (default config — failure absent):** same schema on `docker.io/yugabytedb/yugabyte:2026.1.1.0-b91-aarch64` via `bin/yugabyted start --daemon=false --advertise_address=127.0.0.1`; identical blocker+delete pair → DELETE blocks (observed 5938.561 ms) then succeeds. Ghost loop (per iteration: srl txn reads `t`, `rollback`, session exit; then fresh session `delete from t` + 3-row insert) ×300 → 0 errors. Control: same loop at repeatable read ×300 → 0 errors.

**Modern legacy-mode (mechanism still demonstrable, surface fixed):** add `--tserver_flags=enable_wait_queues=false`; blocker session `set yb_transaction_priority_lower_bound = 0.9;` + srl txn reading `t`; deleter session `set yb_transaction_priority_upper_bound = 0.1; set yb_max_query_layer_retries = 0; set default_transaction_isolation = 'repeatable read'; delete from t;` → immediate `40001` with DETAIL `... conflicts with higher priority transaction (our pri: ..., their pri: ...) ... (conflict_resolution.cc:106)`. Reverse the two priority GUCs → `DELETE 3` instantly. With default `yb_max_query_layer_retries=60`: ghost loop ×300 → 0 errors.

## Versions tested
- `docker.io/yugabytedb/yugabyte:2.0.0.0-b16` (amd64 under emulation) — **affected**; exact reported signature reproduced.
- `docker.io/yugabytedb/yugabyte:2026.1.1.0-b91-aarch64` (current STS) — not affected in default config; legacy-mode surface is 40001+DETAIL, absorbed by default retries.
- v1.3.1 source (git tag `v1.3.1`, this checkout) — root-cause citations for the reported version.
- master @ `a27ae83fc1` (this checkout) — not affected; wait-on-conflict default (`common_flags.cc:50-53`), 40001 mapping (`pg_yb_utils.c:10284-10287`), retries default 60 (`guc.c:6088-6101`). Prior session (issue #1289 validation, 2026-08-17) confirmed identical modern behavior on 2024.2.10.0-b62 (LTS), which carries the same three layers.

## Proposed fix direction
None needed on master — the failure mode is unreachable in any supported default configuration; the surviving fail-on-conflict priority check is an intentional, opt-in legacy mode (`enable_wait_queues=false`) whose errors are properly classified 40001 and transparently retried. Recommend closing #2257 as fixed by the combination of:
- `9451519f8e` / #19837 (wait-on-conflict default, 2.21/2024.1+),
- `d177d9500f` / #16460 (kConflict → 40001 PG-parity message),
- query-layer retry framework (`yb_max_query_layer_retries`, default 60).
If a maintainer wants belt-and-braces, the only residual is the fire-and-forget abort (`pg_client_session.cc:4450`); making ROLLBACK wait for coordinator-acknowledged abort would close the physical window too, at latency cost — not justified by any observed failure.

## Test strategy
Existing coverage already pins the fixed behavior:
- `src/postgres/src/test/isolation/specs/yb.orig.concurrent-inserts-duplicate-key-error.spec` — autocommit statements + query-layer retries under conflict.
- `src/yb/yql/pgwrapper/pg_wait_on_conflict-test.cc` (wait-queue conflict resolution) and fail-on-conflict priority assertions in `src/yb/yql/pgwrapper/pg_libpq-test.cc:1679` / `pg_mini-test.cc:1002` (both assert the *DETAIL* text `conflicts with higher priority transaction` under pinned priorities — public SQL entry points only).
A dedicated regression test for "ghost txn of a closed session must not fail a new autocommit statement" would be timing-based and flaky by construction; the wait-queue + retry defaults make it structurally unnecessary.

## Confidentiality check
Artifact reviewed: contains only public GitHub issue content (reporter's own published schema/statements: table `t(k int primary key, v int not null unique)`), synthetic UUIDs/priorities generated in local containers, public image tags, and repo file:line citations. No customer identifiers, PII, internal hostnames/URLs, secrets, or unreleased information. Nothing was posted to GitHub (writes prohibited for this validation).
