### ISSUE TITLE
[YSQL] Handle version output in TestYsqlDump test

### ISSUE THREAD

**Issue by jaki** [yugabyte/yugabyte-db#2276]
Jira Link: [DB-2205](https://yugabyte.atlassian.net/browse/DB-2205)
The `TestYsqlDump` java test fails due to a difference in versions between the expected and actual output.

Stack trace:

```
org.junit.ComparisonFailure: expected:<...ase version 11.2-YB-[2.0.0].0-b0> but was:<...ase version 11.2-YB-[1.3.2].0-b0>
         at org.junit.Assert.assertEquals(Assert.java:115)
         at org.junit.Assert.assertEquals(Assert.java:144)
         at org.yb.AssertionWrappers.lambda$assertEquals$7(AssertionWrappers.java:140)
         at org.yb.AssertionWrappers.wrapAssertion(AssertionWrappers.java:45)
         at org.yb.AssertionWrappers.assertEquals(AssertionWrappers.java:140)
         at org.yb.pgsql.TestYsqlDump.testPgDump(TestYsqlDump.java:74)
         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
         at java.lang.reflect.Method.invoke(Method.java:498)
         at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
         at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
         at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
         at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
         at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
         at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
         at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
         at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
         at java.lang.Thread.run(Thread.java:745) 
```

**Comment by kriteshranjan** [comment]
Closing this issue based on AI validation. cc: @m-iancu , @VamsidharGunturu
