### ISSUE TITLE
Files inside managed/devops/yb_pyenv are picked up by Python syntax checker

### ISSUE THREAD

**Issue by mbautin** [yugabyte/yugabyte-db#2287]
Example (and also yb_pyenv does not seem to be in any .gitignore):

```
11:52:05 /net/centos-gcp-cloud-jenkins-slave-6e5/share/jenkins/workspace/github-yugabyte-db-centos-master-gcc-release/thirdparty/build_definitions
11:52:21 --------------------------------------------------------------------------------
11:52:21 Syntax error in managed/devops/yb_pyenv/lib/python2.7/site-packages/invoke/vendor/yaml3/__init__.py:
11:52:21 
11:52:21 Traceback (most recent call last):
11:52:21   File "/net/centos-gcp-cloud-jenkins-slave-6e5/share/jenkins/workspace/github-yugabyte-db-centos-master-gcc-release/build-support/check_python_syntax.py", line 37, in <module>
11:52:21     compile(source, filename, 'exec')
11:52:21   File "managed/devops/yb_pyenv/lib/python2.7/site-packages/invoke/vendor/yaml3/__init__.py", line 284
11:52:21     class YAMLObject(metaclass=YAMLObjectMetaclass):
11:52:21                               ^
11:52:21 SyntaxError: invalid syntax
11:52:21 --------------------------------------------------------------------------------
11:52:22 --------------------------------------------------------------------------------
11:52:22 Syntax error in managed/devops/yb_pyenv/lib/python2.7/site-packages/jinja2/asyncsupport.py:
11:52:22 
11:52:22 Traceback (most recent call last):
11:52:22   File "/net/centos-gcp-cloud-jenkins-slave-6e5/share/jenkins/workspace/github-yugabyte-db-centos-master-gcc-release/build-support/check_python_syntax.py", line 37, in <module>
11:52:22     compile(source, filename, 'exec')
11:52:22   File "managed/devops/yb_pyenv/lib/python2.7/site-packages/jinja2/asyncsupport.py", line 22
11:52:22     async def concat_async(async_gen):
11:52:22             ^
11:52:22 SyntaxError: invalid syntax
11:52:22 --------------------------------------------------------------------------------
11:52:22 --------------------------------------------------------------------------------
11:52:22 Syntax error in managed/devops/yb_pyenv/lib/python2.7/site-packages/jinja2/asyncfilters.py:
11:52:22 
11:52:22 Traceback (most recent call last):
11:52:22   File "/net/centos-gcp-cloud-jenkins-slave-6e5/share/jenkins/workspace/github-yugabyte-db-centos-master-gcc-release/build-support/check_python_syntax.py", line 37, in <module>
11:52:22     compile(source, filename, 'exec')
11:52:22   File "managed/devops/yb_pyenv/lib/python2.7/site-packages/jinja2/asyncfilters.py", line 7
11:52:22     async def auto_to_seq(value):
11:52:22             ^
11:52:22 SyntaxError: invalid syntax
11:52:22 --------------------------------
```

**Comment by kriteshranjan** [comment]
Closing this issue based on AI validation. cc: @m-iancu , @VamsidharGunturu
