### ISSUE TITLE
Cluster health checker has errors on some universes

### ISSUE THREAD

**Issue by iSignal** [yugabyte/yugabyte-db#2342]
Noticed this error on middleware application logs

2019-09-17 00:50:24,284 [INFO] from com.yugabyte.yw.common.DevopsBase in application-akka.actor.default-dispatcher-867 - Command to run: [bin/py_wrapper bin/cluster_health.py --cluster_payload [{"identityFile":null,"sshPort":0,"namespaceToConfig":{"yb-dev-23fbh5y4g-us-east1b":"/opt/yugabyte/data/keys/8d0e3219-f6fd-483c-96a7-ff5e68b10e7e/cdc9539f-bc14-4d75-b075-55bc5bafb6c1/a653246f-bc43-4ea6-a775-1aa56c1d6e27/yugabyte-helm.conf"},"masterNodes":[],"tserverNodes":[null,null,null],"ybSoftwareVersion":"1.3.2.0-b19","enableTlsClient":false,"enableYSQL":false,"ysqlPort":0}] --universe_name 23fbh5y4g --customer_tag [andrew@yugabyte.com][dev] --destination alerts@yugabyte.com,andrew@yugaybyte.com --start_time_ms 1566430552589]
2019-09-17 00:50:24,490 [INFO] from com.yugabyte.yw.common.ShellProcessHandler in application-akka.actor.default-dispatcher-867 - 2019-09-17 00:50:24,370 INFO: Script started at 2019-09-16 17:50:24
2019-09-17 00:50:24,490 [INFO] from com.yugabyte.yw.common.ShellProcessHandler in application-akka.actor.default-dispatcher-867 - Traceback (most recent call last):
2019-09-17 00:50:24,490 [INFO] from com.yugabyte.yw.common.ShellProcessHandler in application-akka.actor.default-dispatcher-867 -   File "bin/cluster_health.py", line 736, in <module>
2019-09-17 00:50:24,490 [INFO] from com.yugabyte.yw.common.ShellProcessHandler in application-akka.actor.default-dispatcher-867 -     main()
2019-09-17 00:50:24,490 [INFO] from com.yugabyte.yw.common.ShellProcessHandler in application-akka.actor.default-dispatcher-867 -   File "bin/cluster_health.py", line 691, in main
2019-09-17 00:50:24,491 [INFO] from com.yugabyte.yw.common.ShellProcessHandler in application-akka.actor.default-dispatcher-867 -     c.enable_tls_client)
2019-09-17 00:50:24,491 [INFO] from com.yugabyte.yw.common.ShellProcessHandler in application-akka.actor.default-dispatcher-867 -   File "bin/cluster_health.py", line 171, in __init__
2019-09-17 00:50:24,491 [INFO] from com.yugabyte.yw.common.ShellProcessHandler in **application-akka.actor.default-dispatcher-867 -     self.k8s_details = KubernetesDetails(node, namespace_to_config)
2019-09-17 00:50:24,491 [INFO] from com.yugabyte.yw.common.ShellProcessHandler in application-akka.actor.default-dispatcher-867 -   File "bin/cluster_health.py", line 153, in __init__
2019-09-17 00:50:24,491 [INFO] from com.yugabyte.yw.common.ShellProcessHandler in application-akka.actor.default-dispatcher-867 -     self.namespace = node_fqdn.split('.')[2]
2019-09-17 00:50:24,491 [INFO] from com.yugabyte.yw.common.ShellProcessHandler in application-akka.actor.default-dispatcher-867 - AttributeError: 'NoneType' object has no attribute 'split'**
2019-09-17 00:50:24,491 [ERROR] from com.yugabyte.yw.commissioner.HealthChecker in application-akka.actor.default-dispatcher-867 - Health check script got error: code (1), msg:

CC @ramkumarvs @yb-andrew

**Comment by iSignal** [comment]
The issue is that the master and tserver nodes param is None in the cluster playload
masterNodes":[],"tserverNodes":[null,null,null]
These details come from the universe definition.

@yb-andrew , is it possible that this universe failed midway through creation?

If it is an expected error, please feel free to close it out. It does not affect other health checks since each universe spawns its own health check script.
