### ISSUE TITLE
[DocDB] select count under nemesis got NOT_STARTED tablet server error 12 raft group state error 5

### ISSUE THREAD

**Issue by pilshchikov** [yugabyte/yugabyte-db#23891]
Jira Link: [DB-12795](https://yugabyte.atlassian.net/browse/DB-12795)
### Description

Case:
1. run 2 universes, 3 nodes, RF=3, m7g.large (2 CPU 8 RAM), TLS enabled, cluster auth,  `2024.1.3.0-b37`
2. Create non-transactional replication for CQL tables
3. Run cycle:
3.1. Run nemesis in background randomly (1 at the time): 
- restart VM
- stop/start/restart master/tserver processes
- network package loss
- network slowdown
3.1. Run workload against 5 tables on source universe for some time (2-5 min) (with special tag)
3.2. Stop workload
3.3. select count() where uuid=<special tag> on both source and target, waiting for a same results.

After 2 hours and many cycles issue with `select count(*)` was happen
```
06:42:58.385 [Thread-164] INFO  cql: select count(*) as aggr from replication_6390_789f where uuid = '6fd64926-3025-417e-85c5-3ea8c852b61e'
com.datastax.driver.core.exceptions.InvalidQueryException: Execution Error. Read(tablet: 268aa921aae742e5aba18ad69b550f20, num_ops: 1, num_attempts: 300, txn: 00000000-0000-0000-0000-000000000000, subtxn: [none]) passed its deadline 70.273s (passed: 60.022s): Illegal state (yb/tserver/service_util.cc:284): Tablet 268aa921aae742e5aba18ad69b550f20 not RUNNING: NOT_STARTED (tablet server error 12) (raft group state error 5)
select count(*) as aggr from replication_6390_789f where uuid = '6fd64926-3025-417e-85c5-3ea8c852b61e';
^^^^^^
 (ql error -300)
	at com.datastax.driver.core.exceptions.InvalidQueryException.copy(InvalidQueryException.java:50)
	at com.datastax.driver.core.DriverThrowables.propagateCause(DriverThrowables.java:35)
	at com.datastax.driver.core.DefaultResultSetFuture.getUninterruptibly(DefaultResultSetFuture.java:312)
	at com.datastax.driver.core.AbstractSession.execute(AbstractSession.java:58)
	at com.yugabyte.clientserver.Queries.lambda$executeYCql$3(Queries.java:276)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at com.yugabyte.clientserver.Queries.executeYCql(Queries.java:270)
	at com.yugabyte.clientserver.Queries.execute(Queries.java:286)
	at com.yugabyte.clientserver.QueryHandler.runQuery(QueryHandler.java:150)
	at com.yugabyte.clientserver.QueryHandler.lambda$runQueryHandler$2(QueryHandler.java:179)
	at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: com.datastax.driver.core.exceptions.InvalidQueryException: Execution Error. Read(tablet: 268aa921aae742e5aba18ad69b550f20, num_ops: 1, num_attempts: 300, txn: 00000000-0000-0000-0000-000000000000, subtxn: [none]) passed its deadline 70.273s (passed: 60.022s): Illegal state (yb/tserver/service_util.cc:284): Tablet 268aa921aae742e5aba18ad69b550f20 not RUNNING: NOT_STARTED (tablet server error 12) (raft group state error 5)
select count(*) as aggr from replication_6390_789f where uuid = '6fd64926-3025-417e-85c5-3ea8c852b61e';
^^^^^^
 (ql error -300)
	at com.datastax.driver.core.Responses$Error.asException(Responses.java:181)
	at com.datastax.driver.core.DefaultResultSetFuture.onSet(DefaultResultSetFuture.java:234)
	at com.datastax.driver.core.RequestHandler.setFinalResult(RequestHandler.java:235)
	at com.datastax.driver.core.RequestHandler.access$2600(RequestHandler.java:61)
	at com.datastax.driver.core.RequestHandler$SpeculativeExecution.setFinalResult(RequestHandler.java:1011)
	at com.datastax.driver.core.RequestHandler$SpeculativeExecution.onSet(RequestHandler.java:814)
	at com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:1322)
	at com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:1240)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
```

all logs in a first comment in Jira ticket

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-12795]: https://yugabyte.atlassian.net/browse/DB-12795?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
Per @basavaraj29 's investigation, 


looks like all 3 nodes on the source universe restarted around the same time. around 06:42 UTC, 172-151-26-226  seems to have been manually killed, and I can see FATALs on 172.151.18.245  and 172.151.27.84  with the following errors
```
F0904 06:42:57.113039  3162 hybrid_clock.cc:177] Too big clock skew is detected: 0.576s, while max allowed is: 0.500s; clock_skew_force_crash_bound_usec=60000000

F0904 06:42:57.105334  5743 hybrid_clock.cc:177] Too big clock skew is detected: 0.579s, while max allowed is: 0.500s; clock_skew_force_crash_bound_usec=60000000
```
the error is very close to this timeframe
`2024-09-04 06:43:59,483:DEBUG: ... Error. Read(tablet: 268aa921aae742e5aba18ad69b550f20, num_ops: 1, num_attempts: 300, txn: 00000000-0000-0000-0000-000000000000, subtxn: [none]) passed its deadline 70.273s (passed: 60.022s): Illegal state (yb/tserver/service_util.cc:284): Tablet 268aa921aae742e5aba18ad69b550f20 not RUNNING: NOT_STARTED (tablet server error 12) (raft group state error 5)`
which is expected since all three peers are just starting up, and the read couldn't be served within the 1 min deadline.
