### ISSUE TITLE
[YSQL] TestPgBatch fails when not run individually

### ISSUE THREAD

**Issue by jasonyb** [yugabyte/yugabyte-db#24165]
### Description

Running all TestPgBatch tests at once gives failures:

`./yb_build.sh fastdebug --gcc11 --java-test TestPgBatch`

```
[INFO] Running org.yb.pgsql.TestPgBatch
[ERROR] Tests run: 6, Failures: 0, Errors: 3, Skipped: 0, Time elapsed: 137.411 s <<< FAILURE! - in org.yb.pgsql.TestPgBatch
[ERROR] testSyncInLongBatchRcCornerCase(org.yb.pgsql.TestPgBatch)  Time elapsed: 60.308 s  <<< ERROR!
com.yugabyte.util.PSQLException: ERROR: Timed out waiting for Create Table
        at org.yb.pgsql.TestPgBatch.setUpTable(TestPgBatch.java:63)
        at org.yb.pgsql.TestPgBatch.testSyncInLongBatchRcCornerCase(TestPgBatch.java:285)

[ERROR] testTransparentRestartFirstStatement(org.yb.pgsql.TestPgBatch)  Time elapsed: 0.232 s  <<< ERROR!
com.yugabyte.util.PSQLException: ERROR: Invalid table definition: Error creating table yugabyte.t on the master: num_tablets should be greater than 0. Client would need to wait for master leader get heartbeats from tserver.
        at org.yb.pgsql.TestPgBatch.setUpTable(TestPgBatch.java:63)
        at org.yb.pgsql.TestPgBatch.testTransparentRestartHelper(TestPgBatch.java:93)
        at org.yb.pgsql.TestPgBatch.testTransparentRestartFirstStatement(TestPgBatch.java:188)

[ERROR] testSyncInLongBatch(org.yb.pgsql.TestPgBatch)  Time elapsed: 0.216 s  <<< ERROR!
com.yugabyte.util.PSQLException: ERROR: Invalid table definition: Error creating table yugabyte.t on the master: num_tablets should be greater than 0. Client would need to wait for master leader get heartbeats from tserver.
        at org.yb.pgsql.TestPgBatch.setUpTable(TestPgBatch.java:63)
        at org.yb.pgsql.TestPgBatch.testSyncInLongBatchHelper(TestPgBatch.java:198)
        at org.yb.pgsql.TestPgBatch.testSyncInLongBatch(TestPgBatch.java:248)
```

But running them individually works fine.

`./yb_build.sh fastdebug --gcc11 --java-test 'TestPgBatch#testSyncInLongBatchRcCornerCase'`

Tested on master 0d1046abdbd832ea51c7a03dc763ad03737d3ba8 and pg15.

See similar #22247.

### Issue Type

kind/failing-test

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

**Comment by foucher** [comment]
We're not resetting the heartbeat flag in one of the tests. I have a fix for this. I will send it out next week.
