### ISSUE TITLE
[YSQL] Segmentation fault in TestPgRegressTypesUDT

### ISSUE THREAD

**Issue by mbautin** [yugabyte/yugabyte-db#2424]
```
(gdb) where
#0  yb::pggate::PgExpr::TranslateBinary (yb_cursor=0x378e9a0, header=..., index=0, type_entity=0x3868d00, type_attrs=0x4080c18, pg_tuple=0x7ffdac4f4a60) at ../../src/yb/yql/pggate/pg_expr.cc:197
#1  0x00007fbdb9fffb62 in operator() (__args#5=0x7ffdac4f4a60, __args#4=0x4080c18, __args#3=0x3868d00, __args#2=0, __args#1=..., __args#0=0x378e9a0, this=0x4080c20)
    at /n/jenkins/linuxbrew/linuxbrew-20181203T161736-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/Cellar/gcc/5.5.0_4/include/c++/5.5.0/functional:2267
#2  TranslateData (pg_tuple=0x7ffdac4f4a60, index=0, header=..., yb_cursor=0x378e9a0, this=0x4080c00) at ../../src/yb/yql/pggate/pg_expr.h:105
#3  yb::pggate::PgDml::WritePgTuple (this=this@entry=0x378e8b0, pg_tuple=pg_tuple@entry=0x7ffdac4f4a60) at ../../src/yb/yql/pggate/pg_dml.cc:287
#4  0x00007fbdb9fffd21 in yb::pggate::PgDml::Fetch (this=this@entry=0x378e8b0, natts=<optimized out>, values=values@entry=0x3faed30, isnulls=isnulls@entry=0x3faed38, syscols=syscols@entry=0x7ffdac4f4b80, has_data=0x7ffdac4f4b77)
    at ../../src/yb/yql/pggate/pg_dml.cc:269
#5  0x00007fbdb9fead83 in yb::pggate::PgApiImpl::DmlFetch (this=<optimized out>, handle=handle@entry=0x378e8b0, natts=<optimized out>, values=values@entry=0x3faed30, isnulls=isnulls@entry=0x3faed38, syscols=0x7ffdac4f4b80, has_data=0x7ffdac4f4b77)
    at ../../src/yb/yql/pggate/pggate.cc:600
#6  0x00007fbdb9fe638b in yb::pggate::YBCPgDmlFetch (handle=handle@entry=0x378e8b0, natts=<optimized out>, values=values@entry=0x3faed30, isnulls=isnulls@entry=0x3faed38, syscols=syscols@entry=0x7ffdac4f4b80, has_data=has_data@entry=0x7ffdac4f4b77)
    at ../../src/yb/yql/pggate/ybc_pggate.cc:426
#7  0x000000000069d19f in ybcIterateForeignScan (node=0x3fae7b0) at ../../../../../../src/postgres/src/backend/executor/ybc_fdw.c:477
#8  0x0000000000691bb3 in ForeignNext (node=node@entry=0x3fae7b0) at ../../../../../../src/postgres/src/backend/executor/nodeForeignscan.c:56
#9  0x000000000066bbd1 in ExecScanFetch (recheckMtd=0x691a70 <ForeignRecheck>, accessMtd=0x691b00 <ForeignNext>, node=0x3fae7b0) at ../../../../../../src/postgres/src/backend/executor/execScan.c:95
#10 ExecScan (node=0x3fae7b0, accessMtd=0x691b00 <ForeignNext>, recheckMtd=0x691a70 <ForeignRecheck>) at ../../../../../../src/postgres/src/backend/executor/execScan.c:145
#11 0x00000000006622fb in ExecProcNode (node=0x3fae7b0) at ../../../../../../src/postgres/src/include/executor/executor.h:247
#12 ExecutePlan (execute_once=<optimized out>, dest=0x3770738, direction=<optimized out>, numberTuples=0, sendTuples=<optimized out>, operation=CMD_SELECT, use_parallel_mode=<optimized out>, planstate=0x3fae7b0, estate=0x3fae5a0)
    at ../../../../../../src/postgres/src/backend/executor/execMain.c:1729
#13 standard_ExecutorRun (queryDesc=0x3486540, direction=<optimized out>, count=0, execute_once=<optimized out>) at ../../../../../../src/postgres/src/backend/executor/execMain.c:365
#14 0x00007fbdad4d545d in ybpgm_ExecutorRun (queryDesc=0x3486540, direction=ForwardScanDirection, count=0, execute_once=<optimized out>) at ../../../../../src/postgres/contrib/yb_pg_metrics/yb_pg_metrics.c:402
#15 0x00000000007e4c1b in PortalRunSelect (portal=portal@entry=0x34ce010, forward=forward@entry=true, count=0, count@entry=9223372036854775807, dest=dest@entry=0x3770738) at ../../../../../../src/postgres/src/backend/tcop/pquery.c:942
#16 0x00000000007e6339 in PortalRun (portal=portal@entry=0x34ce010, count=count@entry=9223372036854775807, isTopLevel=isTopLevel@entry=true, run_once=run_once@entry=true, dest=dest@entry=0x3770738, altdest=altdest@entry=0x3770738,
    completionTag=0x7ffdac4f5030 "") at ../../../../../../src/postgres/src/backend/tcop/pquery.c:783
#17 0x00000000007e1f9c in exec_simple_query (query_string=0x3456db0 "SELECT * FROM bigname_table;") at ../../../../../../src/postgres/src/backend/tcop/postgres.c:1150
#18 0x00000000007e399f in PostgresMain (argc=<optimized out>, argv=argv@entry=0x3489be0, dbname=0x34899d8 "yugabyte", username=0x34899b8 "yugabyte") at ../../../../../../src/postgres/src/backend/tcop/postgres.c:4440
#19 0x00000000004931c5 in BackendRun (port=0x3477e60) at ../../../../../../src/postgres/src/backend/postmaster/postmaster.c:4398
#20 BackendStartup (port=0x3477e60) at ../../../../../../src/postgres/src/backend/postmaster/postmaster.c:4064
#21 ServerLoop () at ../../../../../../src/postgres/src/backend/postmaster/postmaster.c:1724
#22 0x000000000075d8b8 in PostmasterMain (argc=argc@entry=19, argv=argv@entry=0x347f5d0) at ../../../../../../src/postgres/src/backend/postmaster/postmaster.c:1387
#23 0x00000000006b57fa in PostgresServerProcessMain (argc=19, argv=0x347f5d0) at ../../../../../../src/postgres/src/backend/main/main.c:234
#24 0x00000000006b59f9 in main ()
(gdb)
```

**Comment by kmuthukk** [comment]
@mbautin 

isn't this a duplicate of #2392?

**Comment by mbautin** [comment]
OK, the same stack trace, closing.
