### ISSUE TITLE
Segfault in memtable filter during RocksDB background flush

### ISSUE THREAD

**Issue by mbautin** [YugaByte/yugabyte-db#244]
```
(gdb) where
#0  operator() (memtable=..., __closure=0x7fbc649f47b0) at ../../../../../src/yb/tablet/tablet_peer.cc:179
#1  std::_Function_handler<bool(const rocksdb::MemTable&), yb::tablet::TabletPeer::InitTabletPeer(const std::shared_ptr<yb::tablet::enterprise::Tablet>&, const std::shared_future<std::shared_ptr<yb::client::YBClient> >&, const scoped_refptr<yb::server::Clock>&, const std::shared_ptr<yb::rpc::Messenger>&, const scoped_refptr<yb::log::Log>&, const scoped_refptr<yb::MetricEntity>&, yb::ThreadPool*, yb::ThreadPool*)::<lambda()>::<lambda(const rocksdb::MemTable&)> >::_M_invoke(const std::_Any_data &, const rocksdb::MemTable &) (__functor=..., __args#0=...)
    at /n/jenkins/linuxbrew/linuxbrew_2018-01-09T08_28_02/Cellar/gcc/5.5.0/include/c++/5.5.0/functional:1857
#2  0x00007fbcf9d6d70e in operator() (__args#0=..., this=0x7fbc649f47b0) at /n/jenkins/linuxbrew/linuxbrew_2018-01-09T08_28_02/Cellar/gcc/5.5.0/include/c++/5.5.0/functional:2267
#3  rocksdb::MemTableList::PickMemtablesToFlush(rocksdb::autovector<rocksdb::MemTable*, 8ul>*, std::function<bool (rocksdb::MemTable const&)> const&) (this=0x1ade0678, ret=ret@entry=0x7fbc649f4370, filter=...) at ../../../../../src/yb/rocksdb/db/memtable_list.cc:259
#4  0x00007fbcf9d5817f in rocksdb::FlushJob::Run (this=this@entry=0x7fbc649f4750, file_meta=file_meta@entry=0x7fbc649f48d0) at ../../../../../src/yb/rocksdb/db/flush_job.cc:143
#5  0x00007fbcf9d1e7c3 in rocksdb::DBImpl::FlushMemTableToOutputFile (this=this@entry=0x13c1e900, cfd=cfd@entry=0x1ade0000, mutable_cf_options=..., made_progress=made_progress@entry=0x7fbc649f509e, job_context=job_context@entry=0x7fbc649f50b0, log_buffer=0x7fbc649f5280)
    at ../../../../../src/yb/rocksdb/db/db_impl.cc:1586
#6  0x00007fbcf9d1f19f in rocksdb::DBImpl::BackgroundFlush (this=this@entry=0x13c1e900, made_progress=made_progress@entry=0x7fbc649f509e, job_context=job_context@entry=0x7fbc649f50b0, log_buffer=log_buffer@entry=0x7fbc649f5280) at ../../../../../src/yb/rocksdb/db/db_impl.cc:2816
#7  0x00007fbcf9d2839b in rocksdb::DBImpl::BackgroundCallFlush (this=0x13c1e900) at ../../../../../src/yb/rocksdb/db/db_impl.cc:2838
#8  0x00007fbcf9e184c3 in rocksdb::ThreadPool::BGThread (this=0x2436b60, thread_id=0) at ../../../../../src/yb/rocksdb/util/thread_posix.cc:133
#9  0x00007fbcf9e18558 in rocksdb::BGThreadWrapper (arg=0x136dfb90) at ../../../../../src/yb/rocksdb/util/thread_posix.cc:157
#10 0x00007fbcf325c694 in start_thread (arg=0x7fbc649f6700) at pthread_create.c:333
#11 0x00007fbcf2f9e3cd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

Stack trace:
https://gist.githubusercontent.com/mbautin/cf2c3527e420f43dcfbe1758b1ca5592/raw

Notes on symbolizing the core file:
https://docs.google.com/document/d/17WxtJ9sHsLx_uXnVlwHf58ayaUvMG0QAkvMKculsR44/edit

Core file:
```
[yugabyte@ip-172-151-35-66 cores]$ ls -lt
-rw-------. 1 yugabyte yugabyte 12347019264 Feb 15 10:38 core_rocksdb:high:bg.24462
```

**Comment by rao-vasireddy** [comment]
fixed by 864e72ba501b7c424e05683ce754b01b93f82a74
