### ISSUE TITLE
Improve "yb-docker-ctl create" error message when Docker not running

### ISSUE THREAD

**Issue by stevebang** [yugabyte/yugabyte-db#2450]
When Docker is not running, the message returned is not helpful and not "pretty printed":

```
➜  ~ ./yb-docker-ctl create          
errors pretty printing info
Traceback (most recent call last):
  File "./yb-docker-ctl", line 540, in <module>
    YBDockerControl().run()
  File "./yb-docker-ctl", line 63, in __init__
    self.verify_docker()
  File "./yb-docker-ctl", line 78, in verify_docker
    result = get_subprocess_result_as_str(['docker', 'info'])
  File "./yb-docker-ctl", line 28, in get_subprocess_result_as_str
    result = subprocess.check_output(*popenargs, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['docker', 'info']' returned non-zero exit status 1
```

**Comment by stevebang** [comment]
@ramkumarvs Description added to the `yb-dockter-ctl` page for `--tag` option:

```
...
optional arguments:
  -h, --help            Show the online help and exit
  --tag                 Use with "create" command to specify a specific
                          Docker image tag (version). If not included, then latest Docker image is used.
```
