### ISSUE TITLE
[YSQL] Segmentation fault on UPDATE query

### ISSUE THREAD

**Issue by jeffreims** [yugabyte/yugabyte-db#2466]
Jira Link: [DB-2265](https://yugabyte.atlassian.net/browse/DB-2265)
We are getting a segmentation fault when doing the following query:

```
UPDATE latest SET version_current='608a47e0-d491-11e9-bb65-2a2ae2dbccf5' WHERE as_id='2f5a652c87ea7959d8f1196159051b256b97c27b48360476c76a2f8bf23ae036';
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
```

Example of the schema we are using:

```
CREATE TABLE latest (
    as_id varchar PRIMARY KEY,
    version_current uuid REFERENCES versions(version_current),
);

CREATE TABLE versions (
    version_current uuid PRIMARY KEY,
    version_previous uuid REFERENCES versions(version_current),
    version_parent uuid REFERENCES versions(version_current),
    as_id varchar,
 
    modified_at bigint,
);

CREATE INDEX versions_of_parent ON versions (version_parent, modified_at);
CREATE INDEX versions_of_document ON versions (as_id, modified_at);
```

**Comment by ddorian** [comment]
Can you provide a small dataset where this happens ?

**Comment by ddorian** [comment]
And latest logs from the db ?

**Comment by ajcaldera1** [comment]
I was able to reproduce based on the following dataset and schema from Jeff:
[queries.txt](https://github.com/yugabyte/yugabyte-db/files/3672639/queries.txt)
[schema.txt](https://github.com/yugabyte/yugabyte-db/files/3672644/schema.txt)


Stack trace:
```
#0  heap_compute_data_size (tupleDesc=tupleDesc@entry=0x7fd4573d9ba8, values=values@entry=0x2efba78, isnull=isnull@entry=0x2efbab8) at ../../../../../../../src/postgres/src/backend/access/common/heaptuple.c:177
#1  0x00000000004a0377 in heap_form_tuple (tupleDescriptor=0x7fd4573d9ba8, values=0x2efba78, isnull=0x2efbab8) at ../../../../../../../src/postgres/src/backend/access/common/heaptuple.c:1119
#2  0x000000000066d857 in ExecMaterializeSlot (slot=slot@entry=0x2efba08) at ../../../../../../src/postgres/src/backend/executor/execTuples.c:806
#3  0x00000000006354a8 in AfterTriggerExecute (trigdesc=0x31ca250, trigdesc=0x31ca250, trig_tuple_slot2=0x2efbb48, trig_tuple_slot1=0x2efba08, per_tuple_context=0x2d67ef0, instr=0x0, finfo=0x31ca570, rel=0x3499308, event=0x33f8ed0)
    at ../../../../../../src/postgres/src/backend/commands/trigger.c:4280
#4  afterTriggerInvokeEvents (events=events@entry=0x2bd40b0, firing_id=2, estate=estate@entry=0x31c9f00, delete_ok=delete_ok@entry=false) at ../../../../../../src/postgres/src/backend/commands/trigger.c:4557
#5  0x000000000063f695 in AfterTriggerEndQuery (estate=estate@entry=0x31c9f00) at ../../../../../../src/postgres/src/backend/commands/trigger.c:4867
#6  0x00000000006624f6 in standard_ExecutorFinish (queryDesc=0x2f49cf0) at ../../../../../../src/postgres/src/backend/executor/execMain.c:440
#7  0x00007fd481a592f5 in ybpgm_ExecutorFinish (queryDesc=0x2f49cf0) at ../../../../../src/postgres/contrib/yb_pg_metrics/yb_pg_metrics.c:422
#8  0x00000000007e53a8 in ProcessQuery (isSingleRowModifyTxn=<optimized out>, completionTag=<optimized out>, dest=<optimized out>, queryEnv=<optimized out>, params=<optimized out>, sourceText=<optimized out>, plan=<optimized out>)
    at ../../../../../../src/postgres/src/backend/tcop/pquery.c:215
#9  PortalRunMulti (portal=portal@entry=0x2b88e90, isTopLevel=isTopLevel@entry=true, setHoldSnapshot=setHoldSnapshot@entry=false, dest=dest@entry=0x2c0df10, altdest=altdest@entry=0x2c0df10, completionTag=completionTag@entry=0x7ffc234bdc60 "UPDATE 1")
    at ../../../../../../src/postgres/src/backend/tcop/pquery.c:1317
#10 0x00000000007e6189 in PortalRun (portal=portal@entry=0x2b88e90, count=count@entry=9223372036854775807, isTopLevel=isTopLevel@entry=true, run_once=run_once@entry=true, dest=dest@entry=0x2c0df10, altdest=altdest@entry=0x2c0df10, completionTag=0x7ffc234bdc60 "UPDATE 1")
    at ../../../../../../src/postgres/src/backend/tcop/pquery.c:809
#11 0x00000000007e1f1c in exec_simple_query (query_string=0x2b118b0 "UPDATE latest SET version_current='3867fe52-e85d-4794-9c80-440b33e4d5aa' WHERE as_id='25b09419b12f2e27bc21b10814f053a04630b504934a66fdbd2037a3d80e7c44';")
    at ../../../../../../src/postgres/src/backend/tcop/postgres.c:1150
#12 0x00000000007e391f in PostgresMain (argc=<optimized out>, argv=argv@entry=0x2b449a0, dbname=0x2b44858 "testdb", username=0x2b44838 "postgres") at ../../../../../../src/postgres/src/backend/tcop/postgres.c:4440
#13 0x0000000000493165 in BackendRun (port=0x2b30630) at ../../../../../../src/postgres/src/backend/postmaster/postmaster.c:4398
#14 BackendStartup (port=0x2b30630) at ../../../../../../src/postgres/src/backend/postmaster/postmaster.c:4064
#15 ServerLoop () at ../../../../../../src/postgres/src/backend/postmaster/postmaster.c:1724
#16 0x000000000075d838 in PostmasterMain (argc=argc@entry=23, argv=argv@entry=0x2b39d10) at ../../../../../../src/postgres/src/backend/postmaster/postmaster.c:1387
#17 0x00000000006b577a in PostgresServerProcessMain (argc=23, argv=0x2b39d10) at ../../../../../../src/postgres/src/backend/main/main.c:234
#18 0x00000000006b5979 in main ()
```

**Comment by kriteshranjan** [comment]
Closing this issue based on AI validation. cc: @m-iancu , @VamsidharGunturu
