### ISSUE TITLE
[yb-ctl] Waiting for Postmaster to stop

### ISSUE THREAD

**Issue by jj-kim** [yugabyte/yugabyte-db#2524]
Occasionally, this happens after long periods of inactivity (that may be a correlation and not a causation):

```sh
./bin/yb-ctl destroy
```

```
Destroying cluster.
^CTraceback (most recent call last):
  File "/net/****/share/code/yugabyte-db4/submodules/yugabyte-installation/bin/yb-ctl", line 1898, in <module>
    control.run()
  File "/net/****/share/code/yugabyte-db4/submodules/yugabyte-installation/bin/yb-ctl", line 1875, in run
    self.args.func()
  File "/net/****/share/code/yugabyte-db4/submodules/yugabyte-installation/bin/yb-ctl", line 1711, in destroy_cmd_impl
    self.for_all_daemons(self.stop_daemon)
  File "/net/****/share/code/yugabyte-db4/submodules/yugabyte-installation/bin/yb-ctl", line 1640, in for_all_daemons
    fn(DaemonId(daemon_type, daemon_index)))
  File "/net/****/share/code/yugabyte-db4/submodules/yugabyte-installation/bin/yb-ctl", line 1334, in stop_daemon
    self.stop_process(postgres_pid, "Postmaster for {}".format(daemon_id))
  File "/net/****/share/code/yugabyte-db4/submodules/yugabyte-installation/bin/yb-ctl", line 1322, in stop_process
    time.sleep(0.5)
KeyboardInterrupt
Viewing file /tmp/tmpz2UqDF:
2019-10-07 20:55:25,470 INFO: Stopping Server master-1 PID=22402
2019-10-07 20:55:25,471 INFO: Waiting for Server master-1 PID=22402 to stop...
2019-10-07 20:55:26,284 INFO: Stopping Server tserver-1 PID=22405
2019-10-07 20:55:26,284 INFO: Waiting for Server tserver-1 PID=22405 to stop...
2019-10-07 20:55:26,785 INFO: Stopping Postmaster for tserver-1 PID=22461
2019-10-07 20:55:26,785 INFO: Waiting for Postmaster for tserver-1 PID=22461 to stop...
2019-10-07 20:55:27,787 INFO: Waiting for Postmaster for tserver-1 PID=22461 to stop...
2019-10-07 20:55:28,788 INFO: Waiting for Postmaster for tserver-1 PID=22461 to stop...
```

where the last line gets repeated several times.

The process exists:

```sh
ps 22461
```

```
  PID TTY      STAT   TIME COMMAND
22461 pts/2    S      0:00 /net/****/share/code/yugabyte-db2/build/release-gcc-dynamic-ninja/postgres/bin/postgres -D /net/****/share/yugabyte-data/node-1/disk-1/pg_data -p 5433 -h 127.0.0.1 -k  -c logging_collector=on -c log_directory=/net/****/share/yugabyte-data/node-1/disk-1/yb-data/tserver/logs -c shared_preload_libraries
```

SIGTERM does not stop it.  Looking at the outputs above, this may be related to different checkouts (`yugabyte-db2`, `yugabyte-db4`).

This is on CentOS.

**Comment by jj-kim** [comment]
SIGQUIT stopped it.

**Comment by jj-kim** [comment]
I have come across the issue again, but, this time, it is not `Postmaster for tserver-1`.

```sh
./bin/yb-ctl destroy
```

```
Destroying cluster.
^CTraceback (most recent call last):
  File "/net/****/share/code/yugabyte-db4/submodules/yugabyte-installation/bin/yb-ctl", line 1898, in <module>
    control.run()
  File "/net/****/share/code/yugabyte-db4/submodules/yugabyte-installation/bin/yb-ctl", line 1875, in run
    self.args.func()
  File "/net/****/share/code/yugabyte-db4/submodules/yugabyte-installation/bin/yb-ctl", line 1711, in destroy_cmd_impl
    self.for_all_daemons(self.stop_daemon)
  File "/net/****/share/code/yugabyte-db4/submodules/yugabyte-installation/bin/yb-ctl", line 1640, in for_all_daemons
    fn(DaemonId(daemon_type, daemon_index)))
  File "/net/****/share/code/yugabyte-db4/submodules/yugabyte-installation/bin/yb-ctl", line 1331, in stop_daemon
    self.stop_process(self.get_pid(daemon_id), "Server {}".format(daemon_id))
  File "/net/****/share/code/yugabyte-db4/submodules/yugabyte-installation/bin/yb-ctl", line 1322, in stop_process
    time.sleep(0.5)
KeyboardInterrupt
Viewing file /tmp/tmpj0nz26:
2019-10-10 17:01:35,763 INFO: Stopping Server master-1 PID=32044
2019-10-10 17:01:35,764 INFO: Waiting for Server master-1 PID=32044 to stop...
2019-10-10 17:01:36,765 INFO: Waiting for Server master-1 PID=32044 to stop...
2019-10-10 17:01:37,767 INFO: Waiting for Server master-1 PID=32044 to stop...
```

where the last line gets repeated several times.

After a few minutes, I check whether the process exists, but it cannot not be found:

```sh
ps 32044
```

exits with code 1.

Running destroy again shows a different process:

```sh
./bin/yb-ctl destroy
```

```
Destroying cluster.
^CTraceback (most recent call last):
  File "/net/****/share/code/yugabyte-db4/submodules/yugabyte-installation/bin/yb-ctl", line 1898, in <module>
    control.run()
  File "/net/****/share/code/yugabyte-db4/submodules/yugabyte-installation/bin/yb-ctl", line 1875, in run
    self.args.func()
  File "/net/****/share/code/yugabyte-db4/submodules/yugabyte-installation/bin/yb-ctl", line 1711, in destroy_cmd_impl
    self.for_all_daemons(self.stop_daemon)
  File "/net/****/share/code/yugabyte-db4/submodules/yugabyte-installation/bin/yb-ctl", line 1640, in for_all_daemons
    fn(DaemonId(daemon_type, daemon_index)))
  File "/net/****/share/code/yugabyte-db4/submodules/yugabyte-installation/bin/yb-ctl", line 1331, in stop_daemon
    self.stop_process(self.get_pid(daemon_id), "Server {}".format(daemon_id))
  File "/net/****/share/code/yugabyte-db4/submodules/yugabyte-installation/bin/yb-ctl", line 1322, in stop_process
    time.sleep(0.5)
KeyboardInterrupt
Viewing file /tmp/tmpM6WIL8:
2019-10-10 17:06:58,146 INFO: Server master-1 already stopped
2019-10-10 17:06:58,163 INFO: Stopping Server tserver-1 PID=32047
2019-10-10 17:06:58,163 INFO: Waiting for Server tserver-1 PID=32047 to stop...
2019-10-10 17:06:59,164 INFO: Waiting for Server tserver-1 PID=32047 to stop...
2019-10-10 17:07:00,166 INFO: Waiting for Server tserver-1 PID=32047 to stop...
```

Soon after, I check whether the process exists, and it is found:

```sh
ps 32047
```

```
  PID TTY      STAT   TIME COMMAND
32047 pts/3    Sl     0:15 /net/****/share/code/yugabyte-db4/build/latest/bin/yb-tserver --fs_data_dirs /net/****/share/yugabyte-data/node-1/disk-1 --webserver_interface 127.0.0.1 --rpc_bind_addresses 127.0.0.1 --v 0 --version_file_json_path=/net/****/share/code/yugabyte-db4/build/tsan-clang-dynamic-ninja --tserver_master_addr
```

But when checking a few minutes later, it cannot not be found:

```sh
ps 32047
```

exits with code 1.

Then, running destroy again works.

```sh
./bin/yb-ctl destroy
```

```
Destroying cluster.
```

This issue seems to be a different kind from the previous one because the previous one does not resolve itself after a few minutes.

**Comment by jj-kim** [comment]
Continuing off of the previous work, running create gives this error:

```sh
./bin/yb-ctl create
```

```
Creating cluster.
Waiting for cluster to be ready.
Traceback (most recent call last):
  File "/net/****/share/code/yugabyte-db4/submodules/yugabyte-installation/bin/yb-ctl", line 1898, in <module>
    control.run()
  File "/net/****/share/code/yugabyte-db4/submodules/yugabyte-installation/bin/yb-ctl", line 1875, in run
    self.args.func()
  File "/net/****/share/code/yugabyte-db4/submodules/yugabyte-installation/bin/yb-ctl", line 1665, in create_cmd_impl
    self.wait_for_cluster_or_raise()
  File "/net/****/share/code/yugabyte-db4/submodules/yugabyte-installation/bin/yb-ctl", line 1509, in wait_for_cluster_or_raise
    if not self.wait_for_cluster():
  File "/net/****/share/code/yugabyte-db4/submodules/yugabyte-installation/bin/yb-ctl", line 1448, in wait_for_cluster
    yb_admin_binary_path = self.options.get_binary_path("yb-admin")
  File "/net/****/share/code/yugabyte-db4/submodules/yugabyte-installation/bin/yb-ctl", line 764, in get_binary_path
    binary_name, binary_dirs))
RuntimeError: No binary found for yb-admin. Considered binary directories: ['/net/****/share/code/yugabyte-db4/build/latest/bin', '/net/****/share/code/yugabyte-db4/build/latest/postgres/bin']
Viewing file /tmp/tmpWmEx8F:
2019-10-10 17:18:59,293 INFO: Starting master-1 with:
/net/****/share/code/yugabyte-db4/build/latest/bin/yb-master --fs_data_dirs "/net/****/share/yugabyte-data/node-1/disk-1" --webserver_interface 127.0.0.1 --rpc_bind_addresses 127.0.0.1 --v 0 --version_file_json_path=/net/****/share/code/yugabyte-db4/build/tsan-clang-dynamic-ninja --replication_factor=1 --yb_num_shards_per_tserver 2 --ysql_num_shards_per_tserver=2 --master_addresses 127.0.0.1:7100 --use_initial_sys_catalog_snapshot >"/net/****/share/yugabyte-data/node-1/disk-1/master.out" 2>"/net/****/share/yugabyte-data/node-1/disk-1/master.err" &
2019-10-10 17:18:59,314 INFO: Starting tserver-1 with:
/net/****/share/code/yugabyte-db4/build/latest/bin/yb-tserver --fs_data_dirs "/net/****/share/yugabyte-data/node-1/disk-1" --webserver_interface 127.0.0.1 --rpc_bind_addresses 127.0.0.1 --v 0 --version_file_json_path=/net/****/share/code/yugabyte-db4/build/tsan-clang-dynamic-ninja --tserver_master_addrs=127.0.0.1:7100 --yb_num_shards_per_tserver=2 --redis_proxy_bind_address=127.0.0.1:6379 --cql_proxy_bind_address=127.0.0.1:9042 --local_ip_for_outbound_sockets=127.0.0.1 --use_cassandra_authentication=false --ysql_num_shards_per_tserver=2 --start_pgsql_proxy --pgsql_proxy_bind_address=127.0.0.1:5433 >"/net/****/share/yugabyte-data/node-1/disk-1/tserver.out" 2>"/net/****/share/yugabyte-data/node-1/disk-1/tserver.err" &
2019-10-10 17:18:59,319 INFO: Waiting for master and tserver processes to come up.
^^^ Encountered errors ^^^
```

Seems like a build issue, so fetch latest changes and rebuild.  Then, destroy gives the same waiting messages, except, this time, it gives a clue:

```sh
./bin/yb-ctl destroy
```

```
Destroying cluster.
^CTraceback (most recent call last):
  File "/net/****/share/code/yugabyte-db4/submodules/yugabyte-installation/bin/yb-ctl", line 1898, in <module>
    control.run()
  File "/net/****/share/code/yugabyte-db4/submodules/yugabyte-installation/bin/yb-ctl", line 1875, in run
    self.args.func()
  File "/net/****/share/code/yugabyte-db4/submodules/yugabyte-installation/bin/yb-ctl", line 1711, in destroy_cmd_impl
    self.for_all_daemons(self.stop_daemon)
  File "/net/****/share/code/yugabyte-db4/submodules/yugabyte-installation/bin/yb-ctl", line 1640, in for_all_daemons
    fn(DaemonId(daemon_type, daemon_index)))
  File "/net/****/share/code/yugabyte-db4/submodules/yugabyte-installation/bin/yb-ctl", line 1331, in stop_daemon
    self.stop_process(self.get_pid(daemon_id), "Server {}".format(daemon_id))
  File "/net/****/share/code/yugabyte-db4/submodules/yugabyte-installation/bin/yb-ctl", line 1322, in stop_process
    time.sleep(0.5)
KeyboardInterrupt
Viewing file /tmp/tmp6tep0H:
2019-10-10 17:42:25,592 INFO: Stopping Server master-1 PID=824
2019-10-10 17:42:25,593 INFO: Waiting for Server master-1 PID=824 to stop...
2019-10-10 17:42:26,594 INFO: Waiting for Server master-1 PID=824 to stop...
2019-10-10 17:42:27,596 INFO: Waiting for Server master-1 PID=824 to stop...
2019-10-10 17:42:28,597 INFO: Waiting for Server master-1 PID=824 to stop...
2019-10-10 17:42:29,599 INFO: Waiting for Server master-1 PID=824 to stop...
2019-10-10 17:42:30,600 INFO: Waiting for Server master-1 PID=824 to stop...
2019-10-10 17:42:31,601 INFO: Waiting for Server master-1 PID=824 to stop...
2019-10-10 17:42:32,603 INFO: Waiting for Server master-1 PID=824 to stop...
2019-10-10 17:42:33,604 INFO: Waiting for Server master-1 PID=824 to stop...
2019-10-10 17:42:34,606 INFO: Waiting for Server master-1 PID=824 to stop...
2019-10-10 17:42:35,607 INFO: Waiting for Server master-1 PID=824 to stop...
2019-10-10 17:42:36,609 INFO: Waiting for Server master-1 PID=824 to stop...
2019-10-10 17:42:37,610 INFO: Waiting for Server master-1 PID=824 to stop...
2019-10-10 17:42:38,612 INFO: Waiting for Server master-1 PID=824 to stop...
2019-10-10 17:42:39,613 INFO: Waiting for Server master-1 PID=824 to stop...
2019-10-10 17:42:40,615 INFO: Waiting for Server master-1 PID=824 to stop...
2019-10-10 17:42:41,616 INFO: Waiting for Server master-1 PID=824 to stop...
2019-10-10 17:42:42,618 INFO: Waiting for Server master-1 PID=824 to stop...
2019-10-10 17:42:43,619 INFO: Waiting for Server master-1 PID=824 to stop...
2019-10-10 17:42:44,621 INFO: Waiting for Server master-1 PID=824 to stop...
2019-10-10 17:42:45,622 INFO: Waiting for Server master-1 PID=824 to stop...
2019-10-10 17:42:46,624 INFO: Waiting for Server master-1 PID=824 to stop...
2019-10-10 17:42:47,625 INFO: Waiting for Server master-1 PID=824 to stop...
2019-10-10 17:42:48,627 INFO: Waiting for Server master-1 PID=824 to stop...
2019-10-10 17:42:49,628 INFO: Waiting for Server master-1 PID=824 to stop...
2019-10-10 17:42:50,630 INFO: Waiting for Server master-1 PID=824 to stop...
2019-10-10 17:42:51,631 INFO: Waiting for Server master-1 PID=824 to stop...
2019-10-10 17:42:52,633 INFO: Waiting for Server master-1 PID=824 to stop...
2019-10-10 17:42:53,634 INFO: Waiting for Server master-1 PID=824 to stop...
2019-10-10 17:42:54,636 INFO: Waiting for Server master-1 PID=824 to stop...
2019-10-10 17:42:55,637 INFO: Waiting for Server master-1 PID=824 to stop...
2019-10-10 17:42:56,639 INFO: Waiting for Server master-1 PID=824 to stop...
2019-10-10 17:42:57,640 INFO: Waiting for Server master-1 PID=824 to stop...
2019-10-10 17:42:58,641 INFO: Waiting for Server master-1 PID=824 to stop...
2019-10-10 17:42:59,643 INFO: Waiting for Server master-1 PID=824 to stop...
2019-10-10 17:43:00,645 INFO: Waiting for Server master-1 PID=824 to stop...
2019-10-10 17:43:01,646 INFO: Waiting for Server master-1 PID=824 to stop...
2019-10-10 17:43:02,647 INFO: Waiting for Server master-1 PID=824 to stop...
2019-10-10 17:43:03,648 INFO: Waiting for Server master-1 PID=824 to stop...
2019-10-10 17:43:04,650 INFO: Waiting for Server master-1 PID=824 to stop...
2019-10-10 17:43:05,651 INFO: Waiting for Server master-1 PID=824 to stop...
2019-10-10 17:43:06,652 INFO: Waiting for Server master-1 PID=824 to stop...
2019-10-10 17:43:07,201 INFO: Stopping Server tserver-1 PID=827
2019-10-10 17:43:07,201 INFO: Waiting for Server tserver-1 PID=827 to stop...
2019-10-10 17:43:08,203 INFO: Waiting for Server tserver-1 PID=827 to stop...
2019-10-10 17:43:09,204 INFO: Waiting for Server tserver-1 PID=827 to stop...
2019-10-10 17:43:10,206 INFO: Waiting for Server tserver-1 PID=827 to stop...
2019-10-10 17:43:11,207 INFO: Waiting for Server tserver-1 PID=827 to stop...
2019-10-10 17:43:12,209 INFO: Waiting for Server tserver-1 PID=827 to stop...
2019-10-10 17:43:13,211 INFO: Waiting for Server tserver-1 PID=827 to stop...
2019-10-10 17:43:14,212 INFO: Waiting for Server tserver-1 PID=827 to stop...
2019-10-10 17:43:15,213 INFO: Waiting for Server tserver-1 PID=827 to stop...
2019-10-10 17:43:16,214 INFO: Waiting for Server tserver-1 PID=827 to stop...
2019-10-10 17:43:17,216 INFO: Waiting for Server tserver-1 PID=827 to stop...
2019-10-10 17:43:18,217 INFO: Waiting for Server tserver-1 PID=827 to stop...
2019-10-10 17:43:19,218 INFO: Waiting for Server tserver-1 PID=827 to stop...
2019-10-10 17:43:20,219 INFO: Waiting for Server tserver-1 PID=827 to stop...
2019-10-10 17:43:21,221 INFO: Waiting for Server tserver-1 PID=827 to stop...
2019-10-10 17:43:22,222 INFO: Waiting for Server tserver-1 PID=827 to stop...
2019-10-10 17:43:23,223 INFO: Waiting for Server tserver-1 PID=827 to stop...
2019-10-10 17:43:24,225 INFO: Waiting for Server tserver-1 PID=827 to stop...
2019-10-10 17:43:25,226 INFO: Waiting for Server tserver-1 PID=827 to stop...
^^^ Encountered errors ^^^
```

After a while,

```sh
./bin/yb-ctl destroy
```

```
Destroying cluster.
^CTraceback (most recent call last):
  File "/net/****/share/code/yugabyte-db4/submodules/yugabyte-installation/bin/yb-ctl", line 1898, in <module>
    control.run()
  File "/net/****/share/code/yugabyte-db4/submodules/yugabyte-installation/bin/yb-ctl", line 1875, in run
    self.args.func()
  File "/net/****/share/code/yugabyte-db4/submodules/yugabyte-installation/bin/yb-ctl", line 1711, in destroy_cmd_impl
    self.for_all_daemons(self.stop_daemon)
  File "/net/****/share/code/yugabyte-db4/submodules/yugabyte-installation/bin/yb-ctl", line 1640, in for_all_daemons
    fn(DaemonId(daemon_type, daemon_index)))
  File "/net/****/share/code/yugabyte-db4/submodules/yugabyte-installation/bin/yb-ctl", line 1334, in stop_daemon
    self.stop_process(postgres_pid, "Postmaster for {}".format(daemon_id))
  File "/net/****/share/code/yugabyte-db4/submodules/yugabyte-installation/bin/yb-ctl", line 1322, in stop_process
    time.sleep(0.5)
KeyboardInterrupt
Viewing file /tmp/tmpIYs7Z5:
2019-10-10 17:45:23,738 INFO: Server master-1 already stopped
2019-10-10 17:45:23,784 INFO: Server tserver-1 already stopped
2019-10-10 17:45:23,784 INFO: Stopping Postmaster for tserver-1 PID=929
2019-10-10 17:45:23,784 INFO: Waiting for Postmaster for tserver-1 PID=929 to stop...
2019-10-10 17:45:24,786 INFO: Waiting for Postmaster for tserver-1 PID=929 to stop...
2019-10-10 17:45:25,787 INFO: Waiting for Postmaster for tserver-1 PID=929 to stop...
^^^ Encountered errors ^^^
```

This seems to suggest that stopping the process simply seems to take a long time.  If that covers all cases of this issue, then an investigation should be made as to why it takes so long, and there should be some mechanism to timeout on this so that the user isn't left waiting long with no output information.
