### ISSUE TITLE
[YSQL] org.yb.loadtest are failing in mac

### ISSUE THREAD

**Issue by hari90** [yugabyte/yugabyte-db#25294]
Jira Link: [DB-14492](https://yugabyte.atlassian.net/browse/DB-14492)
### Description

```

[ERROR] Please refer to /Volumes/share/jenkins/workspace/yugabyte-db-phabricator/yugabyte-db/java/yb-cql-4x/target/surefire-reports_org.yb.loadtest.TestUnsetDC__testReadFromFollower for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] ExecutionException The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /Volumes/share/jenkins/workspace/yugabyte-db-phabricator/yugabyte-db/java/yb-cql-4x && /Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home/jre/bin/java -enableassertions -Xmx3000m -Djava.security.egd=file:/dev/./urandom -Djava.net.preferIPv4Stack=true -Djava.awt.headless=true -jar /Volumes/share/jenkins/workspace/yugabyte-db-phabricator/yugabyte-db/java/yb-cql-4x/target/surefire2024-12-13T03_37_22_12932_3182_6780_35826/surefirebooter6746252672800268763.jar /Volumes/share/jenkins/workspace/yugabyte-db-phabricator/yugabyte-db/java/yb-cql-4x/target/surefire2024-12-13T03_37_22_12932_3182_6780_35826 2024-12-13T03-37-48_070-jvmRun1 surefire5642155990475452293tmp surefire_03459444093281220499tmp
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 137
[ERROR] Crashed tests:
[ERROR] org.yb.loadtest.TestUnsetDC
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: ExecutionException The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /Volumes/share/jenkins/workspace/yugabyte-db-phabricator/yugabyte-db/java/yb-cql-4x && /Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home/jre/bin/java -enableassertions -Xmx3000m -Djava.security.egd=file:/dev/./urandom -Djava.net.preferIPv4Stack=true -Djava.awt.headless=true -jar /Volumes/share/jenkins/workspace/yugabyte-db-phabricator/yugabyte-db/java/yb-cql-4x/target/surefire2024-12-13T03_37_22_12932_3182_6780_35826/surefirebooter6746252672800268763.jar /Volumes/share/jenkins/workspace/yugabyte-db-phabricator/yugabyte-db/java/yb-cql-4x/target/surefire2024-12-13T03_37_22_12932_3182_6780_35826 2024-12-13T03-37-48_070-jvmRun1 surefire5642155990475452293tmp surefire_03459444093281220499tmp
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 137
[ERROR] Crashed tests:
[ERROR] org.yb.loadtest.TestUnsetDC
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.awaitResultsDone(ForkStarter.java:510)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.runSuitesForkPerTestSet(ForkStarter.java:457)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:298)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:246)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1183)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1011)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:857)
[ERROR] 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
[ERROR] 	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[ERROR] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
[ERROR] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
[ERROR] 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
[ERROR] 	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
[ERROR] 	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
[ERROR] 	at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
[ERROR] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.lang.reflect.Method.invoke(Method.java:498)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
```

### Issue Type

kind/failing-test

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-14492]: https://yugabyte.atlassian.net/browse/DB-14492?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by hari90** [comment]
https://jenkins.dev.yugabyte.com/job/yugabyte-db-phabricator/315948/artifact/build/release-clang-dynamic-arm64-ninja/yb-test-logs/org.yb.loadtest.TestUnsetDC_testReadFromFollower__error.log
