### ISSUE TITLE
[DocDB] Bulkload failing on colocated tables in 2024.1 branch

### ISSUE THREAD

**Issue by rthallamko3** [yugabyte/yugabyte-db#25365]
Jira Link: [DB-14590](https://yugabyte.atlassian.net/browse/DB-14590)
### Description

Since the fix for #22571 was backported to 2024.1 branch, the bulkload microbenchmark for colocated tables is failing with the error below. The test passes in b21, but fails consistently in b22 with different errors. The failure is reproducible in b23 and subsequent builds, suggesting that a change introduced in either b22 or b23 is likely causing the issue.

**Test Name**: YB-COLOCATED-bulkload -> goal4_varying_columns -> create_100fields_table_then_load

**Error message**

```
[ERROR] 2024-12-02 11:51:25,046 [FeatureBenchWorker<000>] com.oltpbenchmark.ThreadBench uncaughtException - com.yugabyte.util.PSQLException: ERROR: Service unavailable (yb/rpc/yb_rpc.cc:164): Call rejected due to memory pressure: Call yb.tserver.PgClientService.Perform 172.151.19.172:54020 => 172.151.19.172:9100 (request call id 600)
java.lang.RuntimeException: com.yugabyte.util.PSQLException: ERROR: Service unavailable (yb/rpc/yb_rpc.cc:164): Call rejected due to memory pressure: Call yb.tserver.PgClientService.Perform 172.151.19.172:54020 => 172.151.19.172:9100 (request call id 600)
	at com.oltpbenchmark.benchmarks.featurebench.customworkload.bulkload.utils.BulkloadUtils.runCopyCommand(BulkloadUtils.java:95)
	at com.oltpbenchmark.benchmarks.featurebench.customworkload.bulkload.Goal4.executeOnce(Goal4.java:59)
	at com.oltpbenchmark.benchmarks.featurebench.FeatureBenchWorker.executeWork(FeatureBenchWorker.java:262)
	at com.oltpbenchmark.api.Worker.doWork(Worker.java:429)
	at com.oltpbenchmark.api.Worker.run(Worker.java:287)
	at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: com.yugabyte.util.PSQLException: ERROR: Service unavailable (yb/rpc/yb_rpc.cc:164): Call rejected due to memory pressure: Call yb.tserver.PgClientService.Perform 172.151.19.172:54020 => 172.151.19.172:9100 (request call id 600)
	at com.yugabyte.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2675)
	... 5 more
```

Runs on b21 : [8668202](https://perf.dev.yugabyte.com/dashboard/output/8668202), [8668302](https://perf.dev.yugabyte.com/dashboard/output/8668302), [8640602](https://perf.dev.yugabyte.com/dashboard/output/8640602) (all runs passed)
Runs on b22 : [8667602](https://perf.dev.yugabyte.com/dashboard/output/8667602), [8658202](https://perf.dev.yugabyte.com/dashboard/output/8658202), [8654802](https://perf.dev.yugabyte.com/dashboard/output/8654802) (all failed, but with different errors)
Runs on b23 : [8667702](https://perf.dev.yugabyte.com/dashboard/output/8667702) (failed with Call rejected due to memory pressure)

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-14590]: https://yugabyte.atlassian.net/browse/DB-14590?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
Resolved by commit f2e0f58
