### ISSUE TITLE
[YSQL] TestPgSequences java test EOFException

### ISSUE THREAD

**Issue by jaki** [yugabyte/yugabyte-db#2544]
The `TestPgSequences` java test has a test case `testAlterSequence` that has had spotty failures on our [Jenkins builds][1].  I have also reproduced the error on CentOS, asan-clang-dynamic-ninja.

```sh
./yb_build.sh asan --java-test org.yb.pgsql.TestPgSequences
```

Trimmed output:

```
[INFO] Running org.yb.pgsql.TestPgSequences
[ERROR] Tests run: 42, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 555.158 s <<< FAILURE! - in org.yb.pgsql.TestPgSequences
[ERROR] testAlterSequence(org.yb.pgsql.TestPgSequences)  Time elapsed: 16.241 s  <<< ERROR!
org.postgresql.util.PSQLException: An I/O error occurred while sending to the backend.
        at org.yb.pgsql.TestPgSequences.ExecuteQueryWithRetry(TestPgSequences.java:840)
        at org.yb.pgsql.TestPgSequences.testAlterSequence(TestPgSequences.java:875)
Caused by: java.io.EOFException
        at org.yb.pgsql.TestPgSequences.ExecuteQueryWithRetry(TestPgSequences.java:840)
        at org.yb.pgsql.TestPgSequences.testAlterSequence(TestPgSequences.java:875)
```

[1]: http://jenkins.dev.yugabyte.com/job/github-yugabyte-db-centos-master-clang-asan/lastCompletedBuild/testReport/junit/org.yb.pgsql/TestPgSequences/history/

**Comment by jj-kim** [comment]
The above was run on commit 203f37ccff6d5194aac61165984569aaa9953525.

**Comment by m-iancu** [comment]
We should check the stability history to see if this is still the case today -- if not we can just close it.

**Comment by emhna** [comment]
Out of past 24 builds, 7 builds failed on TestPgSequences. Most had to do with connection refusal or master leader time out. The rest have succeeded.
I have verified on centOS that TestPgSequences runs successfully (all 42 test cases work) on latest commit.
