### ISSUE TITLE
yb-docker-ctl create fails on Windows 10

### ISSUE THREAD

**Issue by plemon** [yugabyte/yugabyte-db#2598]
**Issue:** 
I can't create 1 node cluster when following the install steps here https://docs.yugabyte.com/latest/quick-start/create-local-cluster/
and with the script yb-docker-ctl.py from: https://downloads.yugabyte.com/yb-docker-ctl

I am using : 
- Docker Desktop Community Engine:
  v: 19.03.2
- Python v: 2.7.16

**Behaviour**
Running in PowerShell as admin: `python .\yb-docker-ctl.py create`
  
```
docker run --name yb-master-n1 --hostname yb-master-n1 --privileged -p 7000:7000 --net yb-net --detach yugabytedb/yugabyte:latest /home/yugabyte\bin\yb-master --replication_factor=1 --master_addresses=yb-master-n1:7100 --rpc_bind_addresses=yb-master-n1:7100 --use_initial_sys_catalog_snapshot=true --fs_data_dirs=/mnt/disk0,/mnt/disk1 --yb_num_shards_per_tserver=2 --ysql_num_shards_per_tserver=2 --v=0
Adding node yb-master-n1
docker: Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"/home/yugabyte\\\\bin\\\\yb-master\": stat /home/yugabyte\\bin\\yb-master: no such file or directory": unknown.
Traceback (most recent call last):
  File ".\yb-docker-ctl.py", line 541, in <module>
    YBDockerControl().run()
  File ".\yb-docker-ctl.py", line 514, in run
    self.create_clusters()
  File ".\yb-docker-ctl.py", line 366, in create_clusters
    self.start_cluster(server_type, node_id, None)
  File ".\yb-docker-ctl.py", line 347, in start_cluster
    subprocess.check_output(docker_cmd)
  File "C:\Users\Phillip\scoop\apps\python27\current\lib\subprocess.py", line 223, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['docker', 'run', '--name', 'yb-master-n1', '--hostname', 'yb-master-n1', '--privileged', '-p', '7000:7000', '--net', 'yb-net', '--detach', 'yugabytedb/yugabyte:latest', u'/home/yugabyte\\bin\\yb-master', '--replication_factor=1', '--master_addresses=yb-master-n1:7100', '--rpc_bind_addresses=yb-master-n1:7100', '--use_initial_sys_catalog_snapshot=true', '--fs_data_dirs=/mnt/disk0,/mnt/disk1', '--yb_num_shards_per_tserver=2', '--ysql_num_shards_per_tserver=2', '--v=0']' returned non-zero exit status 127 
```
Tried to add: import posixpath at the top of  yb-docker-ctl.py. 
Same result.

**Comment by ddorian** [comment]
@plemon did you just import posixpath ?
or also renamed `os.path.join()` to `posixpath.join()` ? Can you try that and see if it works ?

**Comment by plemon** [comment]
Should have spotted that replacement...thanks :-) That fixed it.
