### ISSUE TITLE
"TransportException: Connection has been closed" exception when removing a node from a cluster while running load-tester

### ISSUE THREAD

**Issue by robertpang** [YugaByte/yugabyte-db#270]
When a node is removed from a cluster while a Cassandra load-tester is running, "TransportException: Connection has been closed" exception is hit:

```
$ java -jar ~/code/yugabyte/java/yb-loadtester/target/yb-sample-apps.jar -workload CassandraKeyValue  -num_threads 8 -num_threads_write 2 -nodes 127.0.0.1:9042
2018-05-04 13:29:47,674 [INFO|com.yugabyte.sample.common.CmdLineOpts|CmdLineOpts] Using a randomly generated UUID : 7b18988a-080d-44e7-bc2a-383d6b102940
2018-05-04 13:29:47,685 [INFO|com.yugabyte.sample.common.CmdLineOpts|CmdLineOpts] App: CassandraKeyValue
2018-05-04 13:29:47,685 [INFO|com.yugabyte.sample.common.CmdLineOpts|CmdLineOpts] Run time (seconds): -1
2018-05-04 13:29:47,686 [INFO|com.yugabyte.sample.common.CmdLineOpts|CmdLineOpts] Adding node: 127.0.0.1:9042
2018-05-04 13:29:47,688 [INFO|com.yugabyte.sample.common.CmdLineOpts|CmdLineOpts] Num reader threads: 24, num writer threads: 2
2018-05-04 13:29:47,688 [INFO|com.yugabyte.sample.common.CmdLineOpts|CmdLineOpts] Num unique keys to insert: 1000000
2018-05-04 13:29:47,688 [INFO|com.yugabyte.sample.common.CmdLineOpts|CmdLineOpts] Num keys to update: -1000001
2018-05-04 13:29:47,689 [INFO|com.yugabyte.sample.common.CmdLineOpts|CmdLineOpts] Num keys to read: -1
2018-05-04 13:29:47,689 [INFO|com.yugabyte.sample.common.CmdLineOpts|CmdLineOpts] Value size: 0
2018-05-04 13:29:47,689 [INFO|com.yugabyte.sample.common.CmdLineOpts|CmdLineOpts] Restrict values to ASCII strings: false
2018-05-04 13:29:47,689 [INFO|com.yugabyte.sample.common.CmdLineOpts|CmdLineOpts] Perform sanity check at end of app run: false
2018-05-04 13:29:47,689 [INFO|com.yugabyte.sample.common.CmdLineOpts|CmdLineOpts] Table TTL (secs): -1
2018-05-04 13:29:47,689 [INFO|com.yugabyte.sample.common.CmdLineOpts|CmdLineOpts] Local reads: false
2018-05-04 13:29:47,689 [INFO|com.yugabyte.sample.common.CmdLineOpts|CmdLineOpts] Read only load: false
2018-05-04 13:29:47,876 [INFO|com.yugabyte.sample.apps.AppBase|AppBase] Connecting to nodes: /127.0.0.1:9042
2018-05-04 13:29:48,178 [WARN|com.datastax.driver.core.NettyUtil|NettyUtil] Found Netty's native epoll transport, but not running on linux-based operating system. Using NIO instead.
...
2018-05-04 13:29:51,985 [INFO|com.yugabyte.sample.apps.AppBase|AppBase] Created a Cassandra table using query: [CREATE TABLE IF NOT EXISTS CassandraKeyValue (k varchar, v blob, primary key (k));]
2018-05-04 13:29:52,977 [WARN|com.datastax.driver.core.ControlConnection|ControlConnection] Cannot find Cassandra version for host /127.0.0.1:9042 to parse the schema, using 2.2.0 based on protocol version in use. If parsing the schema fails, this could be the cause
2018-05-04 13:29:56,989 [INFO|com.yugabyte.sample.common.metrics.MetricsTracker|MetricsTracker] Read: 1939.85 ops/sec (12.12 ms/op), 9700 total ops  |  Write: 120.76 ops/sec (16.51 ms/op), 604 total ops  |  Uptime: 5003 ms | maxWrittenKey: 603 | maxGeneratedKey: 605 |
2018-05-04 13:30:01,990 [INFO|com.yugabyte.sample.common.metrics.MetricsTracker|MetricsTracker] Read: 5165.04 ops/sec (4.65 ms/op), 35540 total ops  |  Write: 319.48 ops/sec (6.25 ms/op), 2202 total ops  |  Uptime: 10004 ms | maxWrittenKey: 2201 | maxGeneratedKey: 2203 |
2018-05-04 13:30:06,996 [INFO|com.yugabyte.sample.common.metrics.MetricsTracker|MetricsTracker] Read: 4093.73 ops/sec (4.47 ms/op), 56032 total ops  |  Write: 248.32 ops/sec (6.14 ms/op), 3445 total ops  |  Uptime: 15010 ms | maxWrittenKey: 3442 | maxGeneratedKey: 3446 |
...
2018-05-04 13:31:02,033 [INFO|com.yugabyte.sample.common.metrics.MetricsTracker|MetricsTracker] Read: 5741.98 ops/sec (4.18 ms/op), 182470 total ops  |  Write: 299.02 ops/sec (6.68 ms/op), 10844 total ops  |  Uptime: 70046 ms | maxWrittenKey: 10843 | maxGeneratedKey: 10845 |
2018-05-04 13:31:03,948 [INFO|com.yugabyte.sample.apps.AppBase|AppBase] Caught Exception:
com.datastax.driver.core.exceptions.TransportException: [/127.0.0.4:9042] Connection has been closed
	at com.datastax.driver.core.exceptions.TransportException.copy(TransportException.java:38)
	at com.datastax.driver.core.exceptions.TransportException.copy(TransportException.java:24)
	at com.datastax.driver.core.DriverThrowables.propagateCause(DriverThrowables.java:37)
	at com.datastax.driver.core.DefaultResultSetFuture.getUninterruptibly(DefaultResultSetFuture.java:264)
	at com.datastax.driver.core.AbstractSession.execute(AbstractSession.java:68)
	at com.yugabyte.sample.apps.CassandraKeyValue.doRead(CassandraKeyValue.java:144)
	at com.yugabyte.sample.apps.AppBase.performRead(AppBase.java:577)
	at com.yugabyte.sample.common.IOPSThread.run(IOPSThread.java:88)
Caused by: com.datastax.driver.core.exceptions.TransportException: [/127.0.0.4:9042] Connection has been closed
	at com.datastax.driver.core.Connection$ConnectionCloseFuture.force(Connection.java:1241)
	at com.datastax.driver.core.Connection$ConnectionCloseFuture.force(Connection.java:1226)
	at com.datastax.driver.core.CloseFuture$Forwarding.force(CloseFuture.java:90)
	at com.datastax.driver.core.SessionManager.onDown(SessionManager.java:478)
	at com.datastax.driver.core.Cluster$Manager.onDown(Cluster.java:1910)
	at com.datastax.driver.core.Cluster$Manager.access$1200(Cluster.java:1354)
	at com.datastax.driver.core.Cluster$Manager$5.runMayThrow(Cluster.java:1867)
	at com.datastax.driver.core.ExceptionCatchingRunnable.run(ExceptionCatchingRunnable.java:32)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
2018-05-04 13:31:03,949 [INFO|com.yugabyte.sample.apps.AppBase|AppBase] Caught Exception:
com.datastax.driver.core.exceptions.TransportException: [/127.0.0.4:9042] Connection has been closed
	at com.datastax.driver.core.exceptions.TransportException.copy(TransportException.java:38)
	at com.datastax.driver.core.exceptions.TransportException.copy(TransportException.java:24)
...
```

**Comment by robertpang** [comment]
Fixed in commit [24c0761](https://github.com/YugaByte/yugabyte-db/commit/24c0761394f5403299cb2870262db7e503051165).
