### ISSUE TITLE
Make encryption at rest itest not fail for older releases

### ISSUE THREAD

**Issue by iSignal** [yugabyte/yugabyte-db#2764]
@bmatican suggested that we need to make sure itests still pass for older releases though they dont understand the encryption at rest flag

**Comment by iSignal** [comment]
2019-10-17 02:16:52,984 requester.py:48 ERROR Response status: 500, response: {"error":"Unrecognized field \"enableEncryptionAtRest\" (class com.yugabyte.yw.forms.UniverseDefinitionTaskParams$UserIntent), not marked as ignorable (19 known properties: \"masterGFlags\", \"enableNodeToNodeEncrypt\", \"deviceInfo\", \"ybSoftwareVersion\", \"providerType\", \"instanceTags\", \"instanceType\", \"universeName\", \"provider\", \"regionList\", \"preferredRegion\", \"tserverGFlags\", \"enableYSQL\", \"enableClientToNodeEncrypt\", \"replicationFactor\", \"assignPublicIP\", \"accessKeyCode\", \"numNodes\", \"useTimeSync\"])\n at [Source: N/A; line: -1, column: -1] (through reference chain: com.yugabyte.yw.forms.Cluster[\"userIntent\"]->com.yugabyte.yw.forms.UserIntent[\"enableEncryptionAtRest\"])"}
2019-10-17 02:16:52,985 test_base.py:129 ERROR Exception : RuntimeError('Failure response status code.',)
Traceback (most recent call last):
  File "/home/centos/code/internal-services/itest/src/test_base.py", line 125, in execute_steps
    step.call()
  File "/home/centos/code/internal-services/itest/src/test_base.py", line 39, in call
    ret = self.function()
  File "/home/centos/code/internal-services/itest/src/universe_tests/test_simple_ops.py", line 9, in do_custom_work
    universe = self.create_and_verify_universe()
  File "/home/centos/code/internal-services/itest/src/universe_tests/test_universe_base.py", line 345, in create_and_verify_universe
    universe_config = self.yw_proxy.configure_universe(params)
  File "/home/centos/code/internal-services/itest/src/yw_proxy.py", line 279, in configure_universe
    params=params, headers=self.login_user.headers())
  File "/home/centos/code/internal-services/itest/src/requester.py", line 17, in POST
    return self._request("POST", route, params, headers, verify=not skip_verify)
  File "/home/centos/code/internal-services/itest/src/requester.py", line 35, in _request
    self._verify_success(response)
  File "/home/centos/code/internal-services/itest/src/requester.py", line 49, in _verify_success
    raise RuntimeError("Failure response status code.")
RuntimeError: Failure response status code.

**Comment by iSignal** [comment]
Fixed in dc6482b37472574d8553b260533490c563635cfd by Bogdan.
