### ISSUE TITLE
CassandraTransactionalKeyValue write workload hangs after write conflicts

### ISSUE THREAD

**Issue by robertpang** [YugaByte/yugabyte-db#280]
When executing CassandraTransactionalKeyValue workload, the workload hangs after write conflicts happen while all keys have been written:

```
$java -jar ~/code/yugabyte/java/yb-loadtester/target/yb-sample-apps.jar -workload CassandraTransactionalKeyValue -num_threads_read 0 -num_threads_write 4 -nodes 127.0.0.1:9042 -num_unique_keys 8
2018-05-08 17:57:23,051 [INFO|com.yugabyte.sample.common.CmdLineOpts|CmdLineOpts] Using a randomly generated UUID : 4820ccc5-ce6e-47d2-a12e-6f6679b081ce
2018-05-08 17:57:23,059 [INFO|com.yugabyte.sample.common.CmdLineOpts|CmdLineOpts] App: CassandraTransactionalKeyValue
2018-05-08 17:57:23,060 [INFO|com.yugabyte.sample.common.CmdLineOpts|CmdLineOpts] Run time (seconds): -1
2018-05-08 17:57:23,060 [INFO|com.yugabyte.sample.common.CmdLineOpts|CmdLineOpts] Adding node: 127.0.0.1:9042
2018-05-08 17:57:23,062 [INFO|com.yugabyte.sample.common.CmdLineOpts|CmdLineOpts] Num reader threads: 0, num writer threads: 4
2018-05-08 17:57:23,062 [INFO|com.yugabyte.sample.common.CmdLineOpts|CmdLineOpts] Num unique keys to insert: 8
2018-05-08 17:57:23,062 [INFO|com.yugabyte.sample.common.CmdLineOpts|CmdLineOpts] Num keys to update: -9
2018-05-08 17:57:23,062 [INFO|com.yugabyte.sample.common.CmdLineOpts|CmdLineOpts] Num keys to read: -1
2018-05-08 17:57:23,063 [INFO|com.yugabyte.sample.common.CmdLineOpts|CmdLineOpts] Value size: 0
2018-05-08 17:57:23,063 [INFO|com.yugabyte.sample.common.CmdLineOpts|CmdLineOpts] Restrict values to ASCII strings: false
2018-05-08 17:57:23,063 [INFO|com.yugabyte.sample.common.CmdLineOpts|CmdLineOpts] Perform sanity check at end of app run: false
2018-05-08 17:57:23,063 [INFO|com.yugabyte.sample.common.CmdLineOpts|CmdLineOpts] Table TTL (secs): -1
2018-05-08 17:57:23,063 [INFO|com.yugabyte.sample.common.CmdLineOpts|CmdLineOpts] Local reads: false
2018-05-08 17:57:23,063 [INFO|com.yugabyte.sample.common.CmdLineOpts|CmdLineOpts] Read only load: false
2018-05-08 17:57:23,233 [INFO|com.yugabyte.sample.apps.AppBase|AppBase] Connecting to nodes: /127.0.0.1:9042
2018-05-08 17:57:23,520 [WARN|com.datastax.driver.core.NettyUtil|NettyUtil] Found Netty's native epoll transport, but not running on linux-based operating system. Using NIO instead.
2018-05-08 17:57:27,253 [INFO|com.yugabyte.sample.apps.AppBase|AppBase] Created a Cassandra table using query: [CREATE TABLE IF NOT EXISTS CassandraKeyValue (k varchar, v blob, primary key (k)) WITH transactions = { 'enabled' : true };]
2018-05-08 17:57:32,261 [INFO|com.yugabyte.sample.common.metrics.MetricsTracker|MetricsTracker] Read: 0.00 ops/sec (0.00 ms/op), 0 total ops  |  Write: 1.40 ops/sec (1718.43 ms/op), 7 total ops  |  Uptime: 5007 ms | maxWrittenKey: -1 | maxGeneratedKey: 7 |
2018-05-08 17:57:33,358 [INFO|com.yugabyte.sample.apps.AppBase|AppBase] Caught Exception:
com.datastax.driver.core.exceptions.SyntaxError: SQL error: Invalid SQL Statement. Operation failed. Try again.: Failed Write(tablet: c6e03c7c6d6f4c5abea7c7ac89ec3514, num_ops: 1, num_attempts: 1) to tablet c6e03c7c6d6f4c5abea7c7ac89ec3514 on tablet server 7aaa1a302c4d45069cd265d04906abb8 (127.0.0.3:9100) after 1 attempt(s): Conflicts with higher priority transaction: 30dc3ed3-fc06-4782-bd61-dc24aefc703c
BEGIN TRANSACTION  INSERT INTO CassandraKeyValue (k, v) VALUES (:k1, :v);  INSERT INTO CassandraKeyValue (k, v) VALUES (:k2, :v);END TRANSACTION;
                                                                           ^^^^^^
 (error -11)
	at com.datastax.driver.core.exceptions.SyntaxError.copy(SyntaxError.java:58)
	at com.datastax.driver.core.exceptions.SyntaxError.copy(SyntaxError.java:24)
	at com.datastax.driver.core.DriverThrowables.propagateCause(DriverThrowables.java:37)
	at com.datastax.driver.core.DefaultResultSetFuture.getUninterruptibly(DefaultResultSetFuture.java:264)
	at com.datastax.driver.core.AbstractSession.execute(AbstractSession.java:68)
	at com.yugabyte.sample.apps.CassandraTransactionalKeyValue.doWrite(CassandraTransactionalKeyValue.java:212)
	at com.yugabyte.sample.apps.AppBase.performWrite(AppBase.java:559)
	at com.yugabyte.sample.common.IOPSThread.run(IOPSThread.java:87)
Caused by: com.datastax.driver.core.exceptions.SyntaxError: SQL error: Invalid SQL Statement. Operation failed. Try again.: Failed Write(tablet: c6e03c7c6d6f4c5abea7c7ac89ec3514, num_ops: 1, num_attempts: 1) to tablet c6e03c7c6d6f4c5abea7c7ac89ec3514 on tablet server 7aaa1a302c4d45069cd265d04906abb8 (127.0.0.3:9100) after 1 attempt(s): Conflicts with higher priority transaction: 30dc3ed3-fc06-4782-bd61-dc24aefc703c
BEGIN TRANSACTION  INSERT INTO CassandraKeyValue (k, v) VALUES (:k1, :v);  INSERT INTO CassandraKeyValue (k, v) VALUES (:k2, :v);END TRANSACTION;
...
2018-05-08 17:57:37,261 [INFO|com.yugabyte.sample.common.metrics.MetricsTracker|MetricsTracker] Read: 0.00 ops/sec (0.00 ms/op), 0 total ops  |  Write: 15.00 ops/sec (137.67 ms/op), 82 total ops  |  Uptime: 10007 ms | maxWrittenKey: 7 | maxGeneratedKey: 7 |
2018-05-08 17:57:42,262 [INFO|com.yugabyte.sample.common.metrics.MetricsTracker|MetricsTracker] Read: 0.00 ops/sec (0.00 ms/op), 0 total ops  |  Write: 0.00 ops/sec (0.00 ms/op), 82 total ops  |  Uptime: 15008 ms | maxWrittenKey: 7 | maxGeneratedKey: 7 |
2018-05-08 17:57:47,264 [INFO|com.yugabyte.sample.common.metrics.MetricsTracker|MetricsTracker] Read: 0.00 ops/sec (0.00 ms/op), 0 total ops  |  Write: 0.00 ops/sec (0.00 ms/op), 82 total ops  |  Uptime: 20010 ms | maxWrittenKey: 7 | maxGeneratedKey: 7 |
2018-05-08 17:57:52,267 [INFO|com.yugabyte.sample.common.metrics.MetricsTracker|MetricsTracker] Read: 0.00 ops/sec (0.00 ms/op), 0 total ops  |  Write: 0.00 ops/sec (0.00 ms/op), 82 total ops  |  Uptime: 25013 ms | maxWrittenKey: 7 | maxGeneratedKey: 7 |
2018-05-08 17:57:57,268 [INFO|com.yugabyte.sample.common.metrics.MetricsTracker|MetricsTracker] Read: 0.00 ops/sec (0.00 ms/op), 0 total ops  |  Write: 0.00 ops/sec (0.00 ms/op), 82 total ops  |  Uptime: 30014 ms | maxWrittenKey: 7 | maxGeneratedKey: 7 |
```

**Comment by robertpang** [comment]
Fixed in commit [0ae2a79](https://github.com/YugaByte/yugabyte-db/commit/0ae2a7976ffe6f4414eb53cb7cff7e1fd7821840).
