### ISSUE TITLE
[2DC] Crash on consumer node

### ISSUE THREAD

**Issue by ndeodhar** [yugabyte/yugabyte-db#2805]
Seen during multi-master testing, a node on consumer crashed with this stack trace:
```
#0  0x00007f616ab74817 in raise () from /home/yugabyte/yb-software/yugabyte-2.0.4.0-aa84374edca0fbcae24f6f9a395eb1ee09293cb6-release-centos-x86_64/linuxbrew/lib/libc.so.6
#1  0x00007f616ab75b7a in abort () from /home/yugabyte/yb-software/yugabyte-2.0.4.0-aa84374edca0fbcae24f6f9a395eb1ee09293cb6-release-centos-x86_64/linuxbrew/lib/libc.so.6
#2  0x00007f616b0ee5cd in __gnu_cxx::__verbose_terminate_handler() ()
   from /home/yugabyte/yb-software/yugabyte-2.0.4.0-aa84374edca0fbcae24f6f9a395eb1ee09293cb6-release-centos-x86_64/linuxbrew/lib/libstdc++.so.6
#3  0x00007f616b0ec636 in ?? () from /home/yugabyte/yb-software/yugabyte-2.0.4.0-aa84374edca0fbcae24f6f9a395eb1ee09293cb6-release-centos-x86_64/linuxbrew/lib/libstdc++.so.6
#4  0x00007f616b0ec681 in std::terminate() ()
   from /home/yugabyte/yb-software/yugabyte-2.0.4.0-aa84374edca0fbcae24f6f9a395eb1ee09293cb6-release-centos-x86_64/linuxbrew/lib/libstdc++.so.6
#5  0x00007f616b0ed12f in __cxa_pure_virtual ()
   from /home/yugabyte/yb-software/yugabyte-2.0.4.0-aa84374edca0fbcae24f6f9a395eb1ee09293cb6-release-centos-x86_64/linuxbrew/lib/libstdc++.so.6
#6  0x00007f616e3d8af1 in operator()<yb::Status::OK&, void> (__object=<optimized out>, this=<optimized out>)
    at /home/yugabyte/yb-software/yugabyte-2.0.4.0-aa84374edca0fbcae24f6f9a395eb1ee09293cb6-/Cellar/gcc/5.5.0_4/include/c++/5.5.0/functional:600
#7  __call<void, 0ul, 1ul> (__args=<optimized out>, this=<optimized out>)
    at /home/yugabyte/yb-software/yugabyte-2.0.4.0-aa84374edca0fbcae24f6f9a395eb1ee09293cb6-/Cellar/gcc/5.5.0_4/include/c++/5.5.0/functional:1074
#8  operator()<, void> (this=<optimized out>)
    at /home/yugabyte/yb-software/yugabyte-2.0.4.0-aa84374edca0fbcae24f6f9a395eb1ee09293cb6-/Cellar/gcc/5.5.0_4/include/c++/5.5.0/functional:1133
#9  std::_Function_handler<void (), std::_Bind<std::_Mem_fn<void (yb::cdc::CDCWriteRpc::*)(yb::Status const&)> (yb::cdc::CDCWriteRpc*, yb::Status::OK)> >::_M_invoke(std::_Any_data const&) (__functor=...) at /home/yugabyte/yb-software/yugabyte-2.0.4.0-aa84374edca0fbcae24f6f9a395eb1ee09293cb6-/Cellar/gcc/5.5.0_4/include/c++/5.5.0/functional:1871
#10 0x00007f616cc54f9c in operator() (this=<optimized out>)
    at /home/yugabyte/yb-software/yugabyte-2.0.4.0-aa84374edca0fbcae24f6f9a395eb1ee09293cb6-/Cellar/gcc/5.5.0_4/include/c++/5.5.0/functional:2267
#11 yb::rpc::OutboundCall::InvokeCallbackSync (this=0x73e6d90) at ../../src/yb/rpc/outbound_call.cc:384
#12 0x00007f616cc551d9 in yb::rpc::InvokeCallbackTask::Run (this=<optimized out>) at ../../src/yb/rpc/outbound_call.cc:165
#13 0x00007f616cca29a8 in yb::rpc::(anonymous namespace)::Worker::Execute (this=<optimized out>) at ../../src/yb/rpc/thread_pool.cc:99
#14 0x00007f616c657443 in operator() (this=0x50cbde8)
    at /home/yugabyte/yb-software/yugabyte-2.0.4.0-aa84374edca0fbcae24f6f9a395eb1ee09293cb6-/Cellar/gcc/5.5.0_4/include/c++/5.5.0/functional:2267
#15 yb::Thread::SuperviseThread (arg=0x50cbdc0) at ../../src/yb/util/thread.cc:741
#16 0x00007f616ad27fc4 in start_thread ()
   from /home/yugabyte/yb-software/yugabyte-2.0.4.0-aa84374edca0fbcae24f6f9a395eb1ee09293cb6-release-centos-x86_64/linuxbrew/lib/libpthread.so.0
#17 0x00007f616ac279bd in clone () from /home/yugabyte/yb-software/yugabyte-2.0.4.0-aa84374edca0fbcae24f6f9a395eb1ee09293cb6-release-centos-x86_64/linuxbrew/lib/libc.so.6
```

And another similar stack trace but with CDCReadRpc:
```
(gdb) bt
#0  0x00007f5dd28fc817 in raise () from /home/yugabyte/yb-software/yugabyte-2.0.4.0-aa84374edca0fbcae24f6f9a395eb1ee09293cb6-release-centos-x86_64/linuxbrew/lib/libc.so.6
#1  0x00007f5dd28fdb7a in abort () from /home/yugabyte/yb-software/yugabyte-2.0.4.0-aa84374edca0fbcae24f6f9a395eb1ee09293cb6-release-centos-x86_64/linuxbrew/lib/libc.so.6
#2  0x00007f5dd2e765cd in __gnu_cxx::__verbose_terminate_handler() ()
   from /home/yugabyte/yb-software/yugabyte-2.0.4.0-aa84374edca0fbcae24f6f9a395eb1ee09293cb6-release-centos-x86_64/linuxbrew/lib/libstdc++.so.6
#3  0x00007f5dd2e74636 in ?? () from /home/yugabyte/yb-software/yugabyte-2.0.4.0-aa84374edca0fbcae24f6f9a395eb1ee09293cb6-release-centos-x86_64/linuxbrew/lib/libstdc++.so.6
#4  0x00007f5dd2e74681 in std::terminate() ()
   from /home/yugabyte/yb-software/yugabyte-2.0.4.0-aa84374edca0fbcae24f6f9a395eb1ee09293cb6-release-centos-x86_64/linuxbrew/lib/libstdc++.so.6
#5  0x00007f5dd2e7512f in __cxa_pure_virtual ()
   from /home/yugabyte/yb-software/yugabyte-2.0.4.0-aa84374edca0fbcae24f6f9a395eb1ee09293cb6-release-centos-x86_64/linuxbrew/lib/libstdc++.so.6
#6  0x00007f5dd6160b51 in operator()<yb::Status::OK&, void> (__object=<optimized out>, this=<optimized out>)
    at /home/yugabyte/yb-software/yugabyte-2.0.4.0-aa84374edca0fbcae24f6f9a395eb1ee09293cb6-/Cellar/gcc/5.5.0_4/include/c++/5.5.0/functional:600
#7  __call<void, 0ul, 1ul> (__args=<optimized out>, this=<optimized out>)
    at /home/yugabyte/yb-software/yugabyte-2.0.4.0-aa84374edca0fbcae24f6f9a395eb1ee09293cb6-/Cellar/gcc/5.5.0_4/include/c++/5.5.0/functional:1074
#8  operator()<, void> (this=<optimized out>)
    at /home/yugabyte/yb-software/yugabyte-2.0.4.0-aa84374edca0fbcae24f6f9a395eb1ee09293cb6-/Cellar/gcc/5.5.0_4/include/c++/5.5.0/functional:1133
#9  std::_Function_handler<void (), std::_Bind<std::_Mem_fn<void (yb::cdc::CDCReadRpc::*)(yb::Status const&)> (yb::cdc::CDCReadRpc*, yb::Status::OK)> >::_M_invoke(std::_Any_data const&) (__functor=...) at /home/yugabyte/yb-software/yugabyte-2.0.4.0-aa84374edca0fbcae24f6f9a395eb1ee09293cb6-/Cellar/gcc/5.5.0_4/include/c++/5.5.0/functional:1871
#10 0x00007f5dd49dcf9c in operator() (this=<optimized out>)
    at /home/yugabyte/yb-software/yugabyte-2.0.4.0-aa84374edca0fbcae24f6f9a395eb1ee09293cb6-/Cellar/gcc/5.5.0_4/include/c++/5.5.0/functional:2267
#11 yb::rpc::OutboundCall::InvokeCallbackSync (this=0x3d8ca250) at ../../src/yb/rpc/outbound_call.cc:384
#12 0x00007f5dd49dd1d9 in yb::rpc::InvokeCallbackTask::Run (this=<optimized out>) at ../../src/yb/rpc/outbound_call.cc:165
#13 0x00007f5dd4a2a9a8 in yb::rpc::(anonymous namespace)::Worker::Execute (this=<optimized out>) at ../../src/yb/rpc/thread_pool.cc:99
#14 0x00007f5dd43df443 in operator() (this=0x6745988)
    at /home/yugabyte/yb-software/yugabyte-2.0.4.0-aa84374edca0fbcae24f6f9a395eb1ee09293cb6-/Cellar/gcc/5.5.0_4/include/c++/5.5.0/functional:2267
#15 yb::Thread::SuperviseThread (arg=0x6745960) at ../../src/yb/util/thread.cc:741
#16 0x00007f5dd2aaffc4 in start_thread ()
   from /home/yugabyte/yb-software/yugabyte-2.0.4.0-aa84374edca0fbcae24f6f9a395eb1ee09293cb6-release-centos-x86_64/linuxbrew/lib/libpthread.so.0
#17 0x00007f5dd29af9bd in clone () from /home/yugabyte/yb-software/yugabyte-2.0.4.0-aa84374edca0fbcae24f6f9a395eb1ee09293cb6-release-centos-x86_64/linuxbrew/lib/libc.so.6
```

**Comment by nspiegelberg** [comment]
Likely related to #3433
