### ISSUE TITLE
[docdb] ASAN PgLibPqTest.CatalogManagerMapsTest always fails in master

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#3031]
See https://detective-gcp.dev.yugabyte.com/job/github-yugabyte-db-centos-master-clang-asan%2F500%2Fartifact%2Fbuild%2Fasan-clang-dynamic-ninja%2Fyb-test-logs%2Ftests-pgwrapper__pg_libpq-test%2FPgLibPqTest_CatalogManagerMapsTest.log?max_lines=3000&start_line=6001

> ybd asan --cxx-test pgwrapper_pg_libpq-test --gtest_filter PgLibPqTest.CatalogManagerMapsTest

```

8578 | [ts-1] | Direct leak of 368 byte(s) in 1 object(s) allocated from:
-- | -- | --
8579 | [ts-1] | #0 0x5a4488 in operator new(unsigned long) $YB_THIRDPARTY_DIR/build/common/llvm-7.0.1.src/../../../src/llvm-7.0.1.src/projects/compiler-rt/lib/asan/asan_new_delete.cc:106
8580 | [ts-1] | #1 0x7f7b05d8515a in yb::client::YBClient::NewTableAlterer(string) /net/centos-gcp-cloud-jenkins-slave-c5c/share/jenkins/workspace/github-yugabyte-db-centos-master-clang-asan/build/asan-clang-dynamic-ninja/../../src/yb/client/client.cc:491:10
8581 | [ts-1] | #2 0x7f7b074c0e86 in yb::pggate::PgSession::NewTableAlterer(string) /net/centos-gcp-cloud-jenkins-slave-c5c/share/jenkins/workspace/github-yugabyte-db-centos-master-clang-asan/build/asan-clang-dynamic-ninja/../../src/yb/yql/pggate/pg_session.cc:403:19
8582 | [ts-1] | #3 0x7f7b074e9525 in yb::pggate::PgAlterTable::PgAlterTable(scoped_refptr<yb::pggate::PgSession>, yb::pggate::PgObjectId const&) /net/centos-gcp-cloud-jenkins-slave-c5c/share/jenkins/workspace/github-yugabyte-db-centos-master-clang-asan/build/asan-clang-dynamic-ninja/../../src/yb/yql/pggate/pg_ddl.cc:368:34
8583 | [ts-1] | #4 0x7f7b074ab542 in scoped_refptr<yb::pggate::PgAlterTable> make_scoped_refptr<yb::pggate::PgAlterTable, yb::pggate::PgSession*&, yb::pggate::PgObjectId const&>(yb::pggate::PgSession*&, yb::pggate::PgObjectId const&) /net/centos-gcp-cloud-jenkins-slave-c5c/share/jenkins/workspace/github-yugabyte-db-centos-master-clang-asan/build/asan-clang-dynamic-ninja/../../src/yb/gutil/ref_counted.h:424:31
8584 | [ts-1] | #5 0x7f7b0749fa24 in yb::pggate::PgApiImpl::NewAlterTable(yb::pggate::PgSession*, yb::pggate::PgObjectId const&, yb::pggate::PgStatement**) /net/centos-gcp-cloud-jenkins-slave-c5c/share/jenkins/workspace/github-yugabyte-db-centos-master-clang-asan/build/asan-clang-dynamic-ninja/../../src/yb/yql/pggate/pggate.cc:394:15
8585 | [ts-1] | #6 0x7f7b0748e6d7 in YBCPgNewAlterTable /net/centos-gcp-cloud-jenkins-slave-c5c/share/jenkins/workspace/github-yugabyte-db-centos-master-clang-asan/build/asan-clang-dynamic-ninja/../../src/yb/yql/pggate/ybc_pggate.cc:276:29
8586 | [ts-1] | #7 0xb762fb in YBCRename /net/centos-gcp-cloud-jenkins-slave-c5c/share/jenkins/workspace/github-yugabyte-db-centos-master-clang-asan/src/postgres/src/backend/commands/../../../../../../src/postgres/src/backend/commands/ybccmds.c:785:19


```

**Comment by bmatican** [comment]
Analyzing asan leaks, also ran into the same leak stack here:

> jobs/github-yugabyte-db-centos-master-clang-asan/builds/557/archive/build/asan-clang-dynamic-ninja/yb-test-logs/tests-pgwrapper__pg_libpq-test/PgLibPqTest_TestSystemTableRollback.log

cc @m-iancu @ndeodhar @mbautin
