### ISSUE TITLE
[dist-txns] Occasional "SQL error: Restart Required" error when inserting into a table with secondary index

### ISSUE THREAD

**Issue by robertpang** [YugaByte/yugabyte-db#304]
When running the CassandraSecondaryIndex workload, occasional "SQL error: Restart Required" error happens:

```
$ java -jar ~/code/yugabyte/java/yb-loadtester/target/yb-sample-apps.jar -workload CassandraSecondaryIndex -num_threads_read 0 -num_threads_write 4 -nodes 127.0.0.1:9042
2018-05-25 11:46:26,776 [INFO|com.yugabyte.sample.common.CmdLineOpts|CmdLineOpts] Using a randomly generated UUID : f0b8db2c-60f5-44fb-9c71-917aa29f5781
2018-05-25 11:46:26,792 [INFO|com.yugabyte.sample.common.CmdLineOpts|CmdLineOpts] App: CassandraSecondaryIndex
2018-05-25 11:46:26,792 [INFO|com.yugabyte.sample.common.CmdLineOpts|CmdLineOpts] Run time (seconds): -1
2018-05-25 11:46:26,792 [INFO|com.yugabyte.sample.common.CmdLineOpts|CmdLineOpts] Adding node: 127.0.0.1:9042
2018-05-25 11:46:26,797 [INFO|com.yugabyte.sample.common.CmdLineOpts|CmdLineOpts] Num reader threads: 0, num writer threads: 4
2018-05-25 11:46:26,797 [INFO|com.yugabyte.sample.common.CmdLineOpts|CmdLineOpts] Num unique keys to insert: 1000000
2018-05-25 11:46:26,797 [INFO|com.yugabyte.sample.common.CmdLineOpts|CmdLineOpts] Num keys to update: -1000001
2018-05-25 11:46:26,797 [INFO|com.yugabyte.sample.common.CmdLineOpts|CmdLineOpts] Num keys to read: -1
2018-05-25 11:46:26,797 [INFO|com.yugabyte.sample.common.CmdLineOpts|CmdLineOpts] Value size: 0
2018-05-25 11:46:26,797 [INFO|com.yugabyte.sample.common.CmdLineOpts|CmdLineOpts] Restrict values to ASCII strings: false
2018-05-25 11:46:26,797 [INFO|com.yugabyte.sample.common.CmdLineOpts|CmdLineOpts] Perform sanity check at end of app run: false
2018-05-25 11:46:26,798 [INFO|com.yugabyte.sample.common.CmdLineOpts|CmdLineOpts] Table TTL (secs): -1
2018-05-25 11:46:26,798 [INFO|com.yugabyte.sample.common.CmdLineOpts|CmdLineOpts] Local reads: false
2018-05-25 11:46:26,798 [INFO|com.yugabyte.sample.common.CmdLineOpts|CmdLineOpts] Read only load: false
2018-05-25 11:46:27,050 [INFO|com.yugabyte.sample.apps.AppBase|AppBase] Connecting to nodes: /127.0.0.1:9042
2018-05-25 11:46:27,465 [WARN|com.datastax.driver.core.NettyUtil|NettyUtil] Found Netty's native epoll transport, but not running on linux-based operating system. Using NIO instead.
2018-05-25 11:46:31,287 [INFO|com.yugabyte.sample.apps.AppBase|AppBase] Created a Cassandra table using query: [CREATE TABLE IF NOT EXISTS CassandraSecondaryIndex (k varchar, v varchar, primary key (k)) WITH transactions = { 'enabled' : true };]
2018-05-25 11:46:33,948 [INFO|com.yugabyte.sample.apps.AppBase|AppBase] Created a Cassandra table using query: [CREATE INDEX IF NOT EXISTS CassandraSecondaryIndexByValue ON CassandraSecondaryIndex (v);]
2018-05-25 11:46:38,153 [INFO|com.yugabyte.sample.apps.AppBase|AppBase] Caught Exception:
com.datastax.driver.core.exceptions.InvalidQueryException: SQL error: Restart Required. Restart read required at: { read: { physical: 1527273998149548 } local_limit: { physical: 1527273998151161 } global_limit: <min> serial_no: 0}
INSERT INTO CassandraSecondaryIndex (k, v) VALUES (?, ?);
^^^^^^
 (error -313)
	at com.datastax.driver.core.exceptions.InvalidQueryException.copy(InvalidQueryException.java:50)
	at com.datastax.driver.core.DriverThrowables.propagateCause(DriverThrowables.java:37)
	at com.datastax.driver.core.DefaultResultSetFuture.getUninterruptibly(DefaultResultSetFuture.java:264)
	at com.datastax.driver.core.AbstractSession.execute(AbstractSession.java:68)
	at com.yugabyte.sample.apps.CassandraSecondaryIndex.doWrite(CassandraSecondaryIndex.java:116)
	at com.yugabyte.sample.apps.AppBase.performWrite(AppBase.java:559)
	at com.yugabyte.sample.common.IOPSThread.run(IOPSThread.java:87)
Caused by: com.datastax.driver.core.exceptions.InvalidQueryException: SQL error: Restart Required. Restart read required at: { read: { physical: 1527273998149548 } local_limit: { physical: 1527273998151161 } global_limit: <min> serial_no: 0}
INSERT INTO CassandraSecondaryIndex (k, v) VALUES (?, ?);
^^^^^^
 (error -313)
	at com.datastax.driver.core.Responses$Error.asException(Responses.java:148)
	at com.datastax.driver.core.DefaultResultSetFuture.onSet(DefaultResultSetFuture.java:198)
	at com.datastax.driver.core.RequestHandler.setFinalResult(RequestHandler.java:179)
	at com.datastax.driver.core.RequestHandler.access$2400(RequestHandler.java:49)
	at com.datastax.driver.core.RequestHandler$SpeculativeExecution.setFinalResult(RequestHandler.java:799)
	at com.datastax.driver.core.RequestHandler$SpeculativeExecution.onSet(RequestHandler.java:633)
	at com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:1101)
	at com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:1024)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:276)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:263)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
2018-05-25 11:46:38,956 [INFO|com.yugabyte.sample.common.metrics.MetricsTracker|MetricsTracker] Read: 0.00 ops/sec (0.00 ms/op), 0 total ops  |  Write: 75.15 ops/sec (50.99 ms/op), 376 total ops  |  Uptime: 5005 ms | maxWrittenKey: 376 | maxGeneratedKey: 379 |
2018-05-25 11:46:42,316 [INFO|com.yugabyte.sample.apps.AppBase|AppBase] Caught Exception:
com.datastax.driver.core.exceptions.InvalidQueryException: SQL error: Restart Required. Restart read required at: { read: { physical: 1527274002314879 } local_limit: { physical: 1527274002315696 } global_limit: <min> serial_no: 0}
INSERT INTO CassandraSecondaryIndex (k, v) VALUES (?, ?);
^^^^^^
 (error -313)
```

**Comment by robertpang** [comment]
Fixed in commit [65b7854](https://github.com/YugaByte/yugabyte-db/commit/65b7854ea8f9c3999c9efc7ebaefc70f964ec805).
