### ISSUE TITLE
[DocDb] Make bad data-dir argument more visible

### ISSUE THREAD

**Issue by creisle** [yugabyte/yugabyte-db#3058]
Jira Link: [DB-10815](https://yugabyte.atlassian.net/browse/DB-10815)
I got the following error creating the cluster

```
./bin/yb-ctl create --data_dir ../cluster_data
Creating cluster.
Waiting for cluster to be ready.
Traceback (most recent call last):
  File "./bin/yb-ctl", line 1968, in <module>
    control.run()
  File "./bin/yb-ctl", line 1945, in run
    self.args.func()
  File "./bin/yb-ctl", line 1707, in create_cmd_impl
    self.wait_for_cluster_or_raise()
  File "./bin/yb-ctl", line 1552, in wait_for_cluster_or_raise
    raise RuntimeError("Timed out waiting for a YugaByte DB cluster!")
RuntimeError: Timed out waiting for a YugaByte DB cluster!
Viewing file /var/tmp/tmpWyQ6Jb:
2019-12-03 10:47:58,792 INFO: Starting master-1 with:
/projects/vardb/vardb_scratch/yugabyte_testing/yugabyte-2.0.6.0/bin/yb-master --fs_data_dirs "../cluster_data/node-1/disk-1" --webserver_interface 127.0.0.1 --rpc_bind_addresses 127.0.0.1 --v 0 --version_file_json_path=/projects/vardb/vardb_scratch/yugabyte_testing/yugabyte-2.0.6.0 --webserver_doc_root "/projects/vardb/vardb_scratch/yugabyte_testing/yugabyte-2.0.6.0/www" --replication_factor=1 --yb_num_shards_per_tserver 2 --ysql_num_shards_per_tserver=2 --master_addresses 127.0.0.1:7100 --enable_ysql=true >"../cluster_data/node-1/disk-1/master.out" 2>"../cluster_data/node-1/disk-1/master.err" &
2019-12-03 10:47:58,817 INFO: Starting tserver-1 with:
/projects/vardb/vardb_scratch/yugabyte_testing/yugabyte-2.0.6.0/bin/yb-tserver --fs_data_dirs "../cluster_data/node-1/disk-1" --webserver_interface 127.0.0.1 --rpc_bind_addresses 127.0.0.1 --v 0 --version_file_json_path=/projects/vardb/vardb_scratch/yugabyte_testing/yugabyte-2.0.6.0 --webserver_doc_root "/projects/vardb/vardb_scratch/yugabyte_testing/yugabyte-2.0.6.0/www" --tserver_master_addrs=127.0.0.1:7100 --yb_num_shards_per_tserver=2 --redis_proxy_bind_address=127.0.0.1:6379 --cql_proxy_bind_address=127.0.0.1:9042 --local_ip_for_outbound_sockets=127.0.0.1 --use_cassandra_authentication=false --ysql_num_shards_per_tserver=2 --enable_ysql=true --pgsql_proxy_bind_address=127.0.0.1:5433 >"../cluster_data/node-1/disk-1/tserver.out" 2>"../cluster_data/node-1/disk-1/tserver.err" &
2019-12-03 10:47:58,820 INFO: Waiting for master and tserver processes to come up.
2019-12-03 10:47:58,872 INFO: Waiting for master leader election and tablet server registration.
2019-12-03 10:49:01,775 ERROR: Failed waiting for None tservers, got None
^^^ Encountered errors ^^^
```
I had to delve pretty far into the logs to find what was causing this

```
>>> cd cluster_data/node-1/disk-1/yb-data/tserver/logs
>>> cat yb-tserver.<hostname>.<username>.log.ERROR.20191203-185226.126782
Log file created at: 2019/12/03 18:52:26
Running on machine: <hostname>
Application fingerprint: version 2.0.6.0 build 5 revision <id> build_type RELEASE built at 22 Nov 2019 11:36:19 UTC
Running duration (h:mm:ss): 0:00:00
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
E1203 18:52:26.385077 126782 main_util.cc:22] IO error (yb/fs/fs_manager.cc:176): Failed to load FS layout: Relative path cluster_data//node-1/disk-1 provided for filesystem root
```

If relative paths are a problem could it be an argument error on the CLI vs having to look at the logs?

Note: when I swapped to an absolute path this was solved

[DB-10815]: https://yugabyte.atlassian.net/browse/DB-10815?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by kmuthukk** [comment]
Thx @creisle for the detailed info. We'll look into this.

**Comment by jaki** [comment]
I recently hit this.  I got a more helpful, but still not user-friendly, error message in 2.2.0.0 release for linux:

```
F20210901 15:08:49 ../../src/yb/master/master_main.cc:116] IO error (yb/fs/fs_manager.cc:178): Failed to load FS layout: Relative path ./data/node-1/disk-1 provided for filesystem root
    @     0x7efd0bec892c  yb::LogFatalHandlerSink::send()
    @     0x7efd0b0ae376  google::LogMessage::SendToLog()
    @     0x7efd0b0ab7da  google::LogMessage::Flush()
    @     0x7efd0b0ae8a9  google::LogMessageFatal::~LogMessageFatal()
    @           0x4090b4  yb::master::MasterMain()
    @     0x7efd06d04825  __libc_start_main
    @           0x408469  _start
    @              (nil)  (unknown)

*** Check failure stack trace: ***
    @     0x7efd0bec6d11  yb::(anonymous namespace)::DumpStackTraceAndExit()
    @     0x7efd0b0abc8d  google::LogMessage::Fail()
    @     0x7efd0b0addfd  google::LogMessage::SendToLog()
    @     0x7efd0b0ab7da  google::LogMessage::Flush()
    @     0x7efd0b0ae8a9  google::LogMessageFatal::~LogMessageFatal()
    @           0x4090b4  yb::master::MasterMain()
    @     0x7efd06d04825  __libc_start_main
    @           0x408469  _start
    @              (nil)  (unknown)
```

For recent master centos-gcc-debug, centos-gcc-release, I get the timeout shown in the first post.

**Comment by hkimura** [comment]
I am assuming this one doesn't need backport. If it does, please let us know.
