### ISSUE TITLE
ASAN failure in PgWrapperTestSecure.TestConnectionTSL and PgWrapperTestAuthSecure.TestConnectionAuthTLS

### ISSUE THREAD

**Issue by rao-vasireddy** [yugabyte/yugabyte-db#3085]

**Comment by bmatican** [comment]
Both of these show the same problem
```
PgWrapperTestAuthSecure_TestConnectionAuthTLS.log
PgWrapperTestSecure_TestConnectionTSL.log
```

See: https://detective-gcp.dev.yugabyte.com/job/github-yugabyte-db-centos-master-clang-asan/514/artifact/build/asan-clang-dynamic-ninja/yb-test-logs/tests-pgwrapper__pg_wrapper-test/PgWrapperTestSecure_TestConnectionTSL.log

```
1229 | [ts-1] | ==17841==ERROR: LeakSanitizer: detected memory leaks
-- | -- | --
1230 | [ts-1] |  
1231 | [ts-1] | Direct leak of 144 byte(s) in 1 object(s) allocated from:
1232 | [ts-1] | #0 0x563c9f in __interceptor_malloc /n/jenkins/thirdparty/yugabyte-thirdparty-2019-12-05T15_39_49/thirdparty/build/common/llvm-7.0.1.src/../../../src/llvm-7.0.1.src/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:146
1233 | [ts-1] | #1 0x7fa8470e4ee7 in CRYPTO_malloc (/n/jenkins/linuxbrew/linuxbrew-20181203T161736-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/lib/libcrypto.so.1.0.0+0x71ee7)
1234 | [ts-1] |  
1235 | [ts-1] | Objects leaked above:
1236 | [ts-1] | 0x60d000004550 (144 bytes)
1237 | [ts-1] |  
1238 | [ts-1] | Indirect leak of 320 byte(s) in 4 object(s) allocated from:
1239 | [ts-1] | #0 0x563c9f in __interceptor_malloc $YB_THIRDPARTY_DIR/build/common/llvm-7.0.1.src/../../../src/llvm-7.0.1.src/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:146
1240 | [ts-1] | #1 0x7fa8470e4ee7 in CRYPTO_malloc (/n/jenkins/linuxbrew/linuxbrew-20181203T161736-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/lib/libcrypto.so.1.0.0+0x71ee7)
```

Is this just some generic asan suppression we need to add? cc @mbautin

**Comment by d-uspenskiy** [comment]
Stack trace for memory allocation
```
[ts-1] ==17346==ERROR: LeakSanitizer: detected memory leaks
[ts-1] 
[ts-1] Direct leak of 144 byte(s) in 1 object(s) allocated from:
[ts-1]     #0 0x563b7f in __interceptor_malloc /home/duspensky/code/yugabyte-db/thirdparty/build/common/llvm-7.0.1.src/../../../src/llvm-7.0.1.src/projects/comp
iler-rt/lib/asan/asan_malloc_linux.cc:146
[ts-1]     #1 0x7f697e6a7ee7 in CRYPTO_malloc (/home/duspensky/.linuxbrew-yb-build/linuxbrew-20181203T161736/lib/libcrypto.so.1.0.0+0x71ee7)
[ts-1]     #2 0x7f697e746b2e in DH_new_method (/home/duspensky/.linuxbrew-yb-build/linuxbrew-20181203T161736/lib/libcrypto.so.1.0.0+0x110b2e)
[ts-1]     #3 0x7f697e74609c in dh_cb (/home/duspensky/.linuxbrew-yb-build/linuxbrew-20181203T161736/lib/libcrypto.so.1.0.0+0x11009c)
[ts-1]     #4 0x7f697e78a1fc in ASN1_item_ex_new (/home/duspensky/.linuxbrew-yb-build/linuxbrew-20181203T161736/lib/libcrypto.so.1.0.0+0x1541fc)
[ts-1]     #5 0x7f697e78f09a in ASN1_item_ex_d2i (/home/duspensky/.linuxbrew-yb-build/linuxbrew-20181203T161736/lib/libcrypto.so.1.0.0+0x15909a)
[ts-1]     #6 0x7f697e78f7ba in ASN1_item_d2i (/home/duspensky/.linuxbrew-yb-build/linuxbrew-20181203T161736/lib/libcrypto.so.1.0.0+0x1597ba)
[ts-1]     #7 0x7f697e7a0ad3 in PEM_read_bio_DHparams (/home/duspensky/.linuxbrew-yb-build/linuxbrew-20181203T161736/lib/libcrypto.so.1.0.0+0x16aad3)
[ts-1]     #8 0xcd75bd in load_dh_buffer /home/duspensky/code/yugabyte-db/src/postgres/src/backend/libpq/../../../../../../src/postgres/src/backend/libpq/be-secure-openssl.c:848:7
[ts-1]     #9 0xcd4d07 in initialize_dh /home/duspensky/code/yugabyte-db/src/postgres/src/backend/libpq/../../../../../../src/postgres/src/backend/libpq/be-secure-openssl.c:976:8
[ts-1]     #10 0xcd437c in be_tls_init /home/duspensky/code/yugabyte-db/src/postgres/src/backend/libpq/../../../../../../src/postgres/src/backend/libpq/be-secure-openssl.c:198:7
[ts-1]     #11 0xeecd86 in PostmasterMain /home/duspensky/code/yugabyte-db/src/postgres/src/backend/postmaster/../../../../../../src/postgres/src/backend/postmaster/postmaster.c:981:10
[ts-1]     #12 0xcd79e3 in PostgresServerProcessMain /home/duspensky/code/yugabyte-db/src/postgres/src/backend/main/../../../../../../src/postgres/src/backend/main/main.c:234:3
[ts-1]     #13 0xcd8081 in main (/home/duspensky/code/yugabyte-db/build/asan-clang-dynamic-ninja/postgres/bin/postgres+0xcd8081)
[ts-1]     #14 0x7f697c71b824 in __libc_start_main /tmp/glibc-20181130-26094-cs1x60/glibc-2.23/csu/../csu/libc-start.c:289
[ts-1]     #15 0x494e18 in _start /tmp/glibc-20181130-26094-cs1x60/glibc-2.23/csu/../sysdeps/x86_64/start.S:118
```
