### ISSUE TITLE
ASAN issue (memory leak) in org.yb.pgsql.TestPgRegressPgMisc.testPgRegressPgMisc

### ISSUE THREAD

**Issue by mbautin** [yugabyte/yugabyte-db#3114]
https://gist.githubusercontent.com/mbautin/1a7206f449870469bb912a6804d3be80/raw

Memory leak:
```
ts1|pid25880|:26937 
ts1|pid25880|:26937 =================================================================
ts1|pid25880|:26937 ==27025==ERROR: LeakSanitizer: detected memory leaks
ts1|pid25880|:26937 
ts1|pid25880|:26937 Direct leak of 368 byte(s) in 1 object(s) allocated from:
ts1|pid25880|:26937     #0 0x5a3c68 in operator new(unsigned long) /n/jenkins/thirdparty/yugabyte-thirdparty-2019-12-05T15_39_49/thirdparty/build/common/llvm-7.0.1.src/../../../src/llvm-7.0.1.src/projects/compiler-rt/lib/asan/asan_new_delete.cc:106
ts1|pid25880|:26937     #1 0x7f730bd5d29a in yb::client::YBClient::NewTableAlterer(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) /net/centos-gcp-cloud-jenkins-slave-be1/share/jenkins/workspace/github-yugabyte-db-centos-master-clang-asan/build/asan-clang-dynamic-ninja/../../src/yb/client/client.cc:491:10
ts1|pid25880|:26937     #2 0x7f730e4873c6 in yb::pggate::PgSession::NewTableAlterer(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) /net/centos-gcp-cloud-jenkins-slave-be1/share/jenkins/workspace/github-yugabyte-db-centos-master-clang-asan/build/asan-clang-dynamic-ninja/../../src/yb/yql/pggate/pg_session.cc:403:19
ts1|pid25880|:26937     #3 0x7f730e4afa65 in yb::pggate::PgAlterTable::PgAlterTable(scoped_refptr<yb::pggate::PgSession>, yb::pggate::PgObjectId const&) /net/centos-gcp-cloud-jenkins-slave-be1/share/jenkins/workspace/github-yugabyte-db-centos-master-clang-asan/build/asan-clang-dynamic-ninja/../../src/yb/yql/pggate/pg_ddl.cc:368:34
ts1|pid25880|:26937     #4 0x7f730e4712a2 in scoped_refptr<yb::pggate::PgAlterTable> make_scoped_refptr<yb::pggate::PgAlterTable, yb::pggate::PgSession*&, yb::pggate::PgObjectId const&>(yb::pggate::PgSession*&, yb::pggate::PgObjectId const&) /net/centos-gcp-cloud-jenkins-slave-be1/share/jenkins/workspace/github-yugabyte-db-centos-master-clang-asan/build/asan-clang-dynamic-ninja/../../src/yb/gutil/ref_counted.h:424:31
ts1|pid25880|:26937     #5 0x7f730e465774 in yb::pggate::PgApiImpl::NewAlterTable(yb::pggate::PgSession*, yb::pggate::PgObjectId const&, yb::pggate::PgStatement**) /net/centos-gcp-cloud-jenkins-slave-be1/share/jenkins/workspace/github-yugabyte-db-centos-master-clang-asan/build/asan-clang-dynamic-ninja/../../src/yb/yql/pggate/pggate.cc:400:15
ts1|pid25880|:26937     #6 0x7f730e454137 in YBCPgNewAlterTable /net/centos-gcp-cloud-jenkins-slave-be1/share/jenkins/workspace/github-yugabyte-db-centos-master-clang-asan/build/asan-clang-dynamic-ninja/../../src/yb/yql/pggate/ybc_pggate.cc:276:29
ts1|pid25880|:26937     #7 0xb75d0b in YBCRename /net/centos-gcp-cloud-jenkins-slave-be1/share/jenkins/workspace/github-yugabyte-db-centos-master-clang-asan/src/postgres/src/backend/commands/../../../../../../src/postgres/src/backend/commands/ybccmds.c:785:19
ts1|pid25880|:26937     #8 0xad8e13 in renameatt /net/centos-gcp-cloud-jenkins-slave-be1/share/jenkins/workspace/github-yugabyte-db-centos-master-clang-asan/src/postgres/src/backend/commands/../../../../../../src/postgres/src/backend/commands/tablecmds.c:3026:3
ts1|pid25880|:26937     #9 0x9e40cb in ExecRenameStmt /net/centos-gcp-cloud-jenkins-slave-be1/share/jenkins/workspace/github-yugabyte-db-centos-master-clang-asan/src/postgres/src/backend/commands/../../../../../../src/postgres/src/backend/commands/alter.c:355:11
ts1|pid25880|:26937     #10 0x10aedb6 in ProcessUtilitySlow /net/centos-gcp-cloud-jenkins-slave-be1/share/jenkins/workspace/github-yugabyte-db-centos-master-clang-asan/src/postgres/src/backend/tcop/../../../../../../src/postgres/src/backend/tcop/utility.c:1589:15
ts1|pid25880|:26937     #11 0x10acc8c in standard_ProcessUtility /net/centos-gcp-cloud-jenkins-slave-be1/share/jenkins/workspace/github-yugabyte-db-centos-master-clang-asan/src/postgres/src/backend/tcop/../../../../../../src/postgres/src/backend/tcop/utility.c
ts1|pid25880|:26937     #12 0x7f72f4060948 in ybpgm_ProcessUtility /net/centos-gcp-cloud-jenkins-slave-be1/share/jenkins/workspace/github-yugabyte-db-centos-master-clang-asan/src/postgres/contrib/yb_pg_metrics/../../../../../src/postgres/contrib/yb_pg_metrics/yb_pg_metrics.c:515:9
ts1|pid25880|:26937     #13 0x10ab85d in PortalRunUtility /net/centos-gcp-cloud-jenkins-slave-be1/share/jenkins/workspace/github-yugabyte-db-centos-master-clang-asan/src/postgres/src/backend/tcop/../../../../../../src/postgres/src/backend/tcop/pquery.c:1188:2
ts1|pid25880|:26937     #14 0x10aa04d in PortalRunMulti /net/centos-gcp-cloud-jenkins-slave-be1/share/jenkins/workspace/github-yugabyte-db-centos-master-clang-asan/src/postgres/src/backend/tcop/../../../../../../src/postgres/src/backend/tcop/pquery.c
ts1|pid25880|:26937     #15 0x10a8b15 in PortalRun /net/centos-gcp-cloud-jenkins-slave-be1/share/jenkins/workspace/github-yugabyte-db-centos-master-clang-asan/src/postgres/src/backend/tcop/../../../../../../src/postgres/src/backend/tcop/pquery.c:809:5
ts1|pid25880|:26937     #16 0x10a3b85 in exec_simple_query /net/centos-gcp-cloud-jenkins-slave-be1/share/jenkins/workspace/github-yugabyte-db-centos-master-clang-asan/src/postgres/src/backend/tcop/../../../../../../src/postgres/src/backend/tcop/postgres.c:1159:10
ts1|pid25880|:26937     #17 0x109e4fb in yb_exec_simple_query_attempting_to_restart_read /net/centos-gcp-cloud-jenkins-slave-be1/share/jenkins/workspace/github-yugabyte-db-centos-master-clang-asan/src/postgres/src/backend/tcop/../../../../../../src/postgres/src/backend/tcop/postgres.c:4019:4
ts1|pid25880|:26937     #18 0x109cbd1 in PostgresMain /net/centos-gcp-cloud-jenkins-slave-be1/share/jenkins/workspace/github-yugabyte-db-centos-master-clang-asan/src/postgres/src/backend/tcop/../../../../../../src/postgres/src/backend/tcop/postgres.c:4666:23
ts1|pid25880|:26937     #19 0xef46cb in BackendRun /net/centos-gcp-cloud-jenkins-slave-be1/share/jenkins/workspace/github-yugabyte-db-centos-master-clang-asan/src/postgres/src/backend/postmaster/../../../../../../src/postgres/src/backend/postmaster/postmaster.c:4398:2
ts1|pid25880|:26937     #20 0xef35d4 in BackendStartup /net/centos-gcp-cloud-jenkins-slave-be1/share/jenkins/workspace/github-yugabyte-db-centos-master-clang-asan/src/postgres/src/backend/postmaster/../../../../../../src/postgres/src/backend/postmaster/postmaster.c:4064:3
ts1|pid25880|:26937     #21 0xef1a20 in ServerLoop /net/centos-gcp-cloud-jenkins-slave-be1/share/jenkins/workspace/github-yugabyte-db-centos-master-clang-asan/src/postgres/src/backend/postmaster/../../../../../../src/postgres/src/backend/postmaster/postmaster.c:1724:7
ts1|pid25880|:26937     #22 0xeeda5a in PostmasterMain /net/centos-gcp-cloud-jenkins-slave-be1/share/jenkins/workspace/github-yugabyte-db-centos-master-clang-asan/src/postgres/src/backend/postmaster/../../../../../../src/postgres/src/backend/postmaster/postmaster.c:1387:11
ts1|pid25880|:26937     #23 0xcd7b03 in PostgresServerProcessMain /net/centos-gcp-cloud-jenkins-slave-be1/share/jenkins/workspace/github-yugabyte-db-centos-master-clang-asan/src/postgres/src/backend/main/../../../../../../src/postgres/src/backend/main/main.c:234:3
ts1|pid25880|:26937     #24 0xcd81a1 in main (/net/centos-gcp-cloud-jenkins-slave-be1/share/jenkins/workspace/github-yugabyte-db-centos-master-clang-asan/build/asan-clang-dynamic-ninja/postgres/bin/postgres+0xcd81a1)
ts1|pid25880|:26937     #25 0x7f730c970824 in __libc_start_main /tmp/glibc-20181130-26094-cs1x60/glibc-2.23/csu/../csu/libc-start.c:289
ts1|pid25880|:26937 
ts1|pid25880|:26937 Objects leaked above:
ts1|pid25880|:26937 0x613000124440 (368 bytes)
```

This happens in a postgres process so is limited to a single YSQL connection (gets cleaned up as the connection gets closed).

**Comment by mbautin** [comment]
Seems like a duplicate of #3031, so closing this.
