### ISSUE TITLE
failed to load data with sqoop

### ISSUE THREAD

**Issue by rogerlzp** [yugabyte/yugabyte-db#3120]
Jira Link: [DB-2244](https://yugabyte.atlassian.net/browse/DB-2244)
Hi, 
the case is using sqoop to import data agin.

ENV: RedHat 7.6
YugabyteDB: 2.0.6.0
Sqoop: 1.4.5
test case: import 40 million data from hdfs to yugabytedb.

from sqoop side, the log is as follow:

Error: java.io.IOException: Can't export data, please check failed map task logs
at org.apache.sqoop.mapreduce.TextExportMapper.map(TextExportMapper.java:112)
at org.apache.sqoop.mapreduce.TextExportMapper.map(TextExportMapper.java:39)
at org.apache.hadoop.mapreduce.Mapper.run(Mapper.java:146)
at org.apache.sqoop.mapreduce.AutoProgressMapper.run(AutoProgressMapper.java:64)
at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:787)
at org.apache.hadoop.mapred.MapTask.run(MapTask.java:341)
at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:164)
at java.security.AccessController.doPrivileged(Native Method)
at javax.security.auth.Subject.doAs(Subject.java:415)
at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1996)
at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:158)
Caused by: java.io.IOException: org.postgresql.util.PSQLException: ERROR: Snapshot too old: Snapshot too old. Read point: { physical: 1575883980176681 }, earliest read time allowed: { physical: 1575883981012787 logical: 8 }, delta (usec): 836106: kSnapshotTooOld
at org.apache.sqoop.mapreduce.AsyncSqlRecordWriter.write(AsyncSqlRecordWriter.java:220)
at org.apache.sqoop.mapreduce.AsyncSqlRecordWriter.write(AsyncSqlRecordWriter.java:46)
at org.apache.hadoop.mapred.MapTask$NewDirectOutputCollector.write(MapTask.java:658)
at org.apache.hadoop.mapreduce.task.TaskInputOutputContextImpl.write(TaskInputOutputContextImpl.java:89)
at org.apache.hadoop.mapreduce.lib.map.WrappedMapper$Context.write(WrappedMapper.java:112)
at org.apache.sqoop.mapreduce.TextExportMapper.map(TextExportMapper.java:84)
... 10 more
Caused by: org.postgresql.util.PSQLException: ERROR: Snapshot too old: Snapshot too old. Read point: { physical: 1575883980176681 }, earliest read time allowed: { physical: 1575883981012787 logical: 8 }, delta (usec): 836106: kSnapshotTooOld
at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2157)
at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1886)
at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:555)
at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:417)
at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:410)
at org.apache.sqoop.mapreduce.AsyncSqlOutputFormat$AsyncSqlExecThread.run(AsyncSqlOutputFormat.java:233)
2019-12-09 17:33:19,883 INFO [main] mapreduce.Job (Job.java:monitorAndPrintJob(1367)) - map 6% reduce 0%
2019-12-09 17:36:12,236 INFO [main] mapreduce.Job (Job.java:monitorAndPrintJob(1367)) - map 7% reduce 0%
2019-12-09 17:42:39,964 INFO [main] mapreduce.Job (Job.java:monitorAndPrintJob(1367)) - map 8% reduce 0%
2019-12-09 17:44:31,162 INFO [main] mapreduce.Job (Job.java:printTaskEvents(1406)) - Task Id : attempt_1575256923024_0006_m_000002_1, Status : FAILED
Error: java.io.IOException: Can't export data, please check failed map task logs
at org.apache.sqoop.mapreduce.TextExportMapper.map(TextExportMapper.java:112)
at org.apache.sqoop.mapreduce.TextExportMapper.map(TextExportMapper.java:39)
at org.apache.hadoop.mapreduce.Mapper.run(Mapper.java:146)
at org.apache.sqoop.mapreduce.AutoProgressMapper.run(AutoProgressMapper.java:64)
at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:787)
at org.apache.hadoop.mapred.MapTask.run(MapTask.java:341)
at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:164)
at java.security.AccessController.doPrivileged(Native Method)
at javax.security.auth.Subject.doAs(Subject.java:415)
at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1996)
at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:158)
Caused by: java.io.IOException: org.postgresql.util.PSQLException: ERROR: Snapshot too old: Snapshot too old. Read point: { physical: 1575884639428075 }, earliest read time allowed: { physical: 1575884654207598 }, delta (usec): 14779523: kSnapshotTooOld
at org.apache.sqoop.mapreduce.AsyncSqlRecordWriter.write(AsyncSqlRecordWriter.java:220)
at org.apache.sqoop.mapreduce.AsyncSqlRecordWriter.write(AsyncSqlRecordWriter.java:46)
at org.apache.hadoop.mapred.MapTask$NewDirectOutputCollector.write(MapTask.java:658)
at org.apache.hadoop.mapreduce.task.TaskInputOutputContextImpl.write(TaskInputOutputContextImpl.java:89)
at org.apache.hadoop.mapreduce.lib.map.WrappedMapper$Context.write(WrappedMapper.java:112)
at org.apache.sqoop.mapreduce.TextExportMapper.map(TextExportMapper.java:84)
... 10 more
Caused by: org.postgresql.util.PSQLException: ERROR: Snapshot too old: Snapshot too old. Read point: { physical: 1575884639428075 }, earliest read time allowed: { physical: 1575884654207598 }, delta (usec): 14779523: kSnapshotTooOld
at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2157)
at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1886)
at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:555)
at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:417)
at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:410)
at org.apache.sqoop.mapreduce.AsyncSqlOutputFormat$AsyncSqlExecThread.run(AsyncSqlOutputFormat.java:233)
2019-12-09 17:44:32,165 INFO [main] mapreduce.Job (Job.java:monitorAndPrintJob(1367)) - map 7% reduce 0%
2019-12-09 17:45:27,260 INFO [main] mapreduce.Job (Job.java:monitorAndPrintJob(1367)) - map 8% reduce 0%
2019-12-09 17:46:25,361 INFO [main] mapreduce.Job (Job.java:printTaskEvents(1406)) - Task Id : attempt_1575256923024_0006_m_000001_0, Status : FAILED
Error: java.io.IOException: Can't export data, please check failed map task logs
at org.apache.sqoop.mapreduce.TextExportMapper.map(TextExportMapper.java:112)
at org.apache.sqoop.mapreduce.TextExportMapper.map(TextExportMapper.java:39)
at org.apache.hadoop.mapreduce.Mapper.run(Mapper.java:146)
at org.apache.sqoop.mapreduce.AutoProgressMapper.run(AutoProgressMapper.java:64)
at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:787)
at org.apache.hadoop.mapred.MapTask.run(MapTask.java:341)
at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:164)
at java.security.AccessController.doPrivileged(Native Method)
at javax.security.auth.Subject.doAs(Subject.java:415)
at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1996)
at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:158)
Caused by: java.io.IOException: org.postgresql.util.PSQLException: ERROR: Snapshot too old: Snapshot too old. Read point: { physical: 1575884763829526 }, earliest read time allowed: { physical: 1575884768321387 logical: 8 }, delta (usec): 4491861: kSnapshotTooOld
at org.apache.sqoop.mapreduce.AsyncSqlRecordWriter.write(AsyncSqlRecordWriter.java:220)
at org.apache.sqoop.mapreduce.AsyncSqlRecordWriter.write(AsyncSqlRecordWriter.java:46)
at org.apache.hadoop.mapred.MapTask$NewDirectOutputCollector.write(MapTask.java:658)
at org.apache.hadoop.mapreduce.task.TaskInputOutputContextImpl.write(TaskInputOutputContextImpl.java:89)
at org.apache.hadoop.mapreduce.lib.map.WrappedMapper$Context.write(WrappedMapper.java:112)
at org.apache.sqoop.mapreduce.TextExportMapper.map(TextExportMapper.java:84)
... 10 more

it imported  4,590,000 data finally.
for the log in master or tserver, I didn't find any log related to this failure.

for the log from sqoop, it looks like that Snapshot in yugabyte db failed.

let me know if you need more details on this.

**Comment by ddorian** [comment]
@rogerlzp 

Did you check the `.WARNING` logs for both tserver/master processes ?
Can you attach them ?

In this case, `snapshot too old`, may happen if compactions trigger on long running write transactions.
Do you know how sqoop writes ? Using single-row, batch-rows, transaction-per-file ?

**Comment by sushantrmishra** [comment]
@rogerlzp 
Can you please answer the question 

`Do you know how sqoop writes ? Using single-row, batch-rows, transaction-per-file  or uses copy command?
`
please reopen the issue once you have more information to share.  Closing this issue for now as there is not sufficient information to debug this further.
