### ISSUE TITLE
[yugabyted] Crash when running demo a second time

### ISSUE THREAD

**Issue by m-iancu** [yugabyte/yugabyte-db#3201]
Started, ran demo once, then a couple of manual commands with `ysqlsh`. Finally tried to run `demo` again and it crashed.

```
[yugabyted:1685] 2019-12-20 14:02:58,848 INFO: Completed waiting for yb master, num tservers=1.
[yugabyted:1685] 2019-12-20 14:02:58,850 INFO: Checking play_evolutions table
[yugabyted:1685] 2019-12-20 14:02:59,191 INFO: Finished play evolutions table
[yugabyted:1685] 2019-12-20 14:03:04,192 INFO: Waiting for yb master via ybadmin...
[yugabyted:1685] 2019-12-20 14:03:06,275 INFO: Completed waiting for yb master, num tservers=1.
[yugabyted:1685] 2019-12-20 14:03:06,275 INFO: Checking play_evolutions table
[yugabyted:1685] 2019-12-20 14:03:06,992 INFO: Finished play evolutions table
[yugabyted:1685] 2019-12-20 14:03:06,992 INFO: Setting up admin console schema...
[yugabyted:1685] 2019-12-20 14:03:06,993 ERROR: Traceback (most recent call last):
  File "./bin/yugabyted", line 952, in run
    args.func()
  File "./bin/yugabyted", line 140, in start
    self.start_processes()
  File "./bin/yugabyted", line 458, in start_processes
    Output.begin_replace_line("Installing database...")
  File "./bin/yugabyted", line 1659, in begin_replace_line
    sys.stdout.flush()
IOError: [Errno 9] Bad file descriptor
[yugabyted:1685] 2019-12-20 14:03:06,993 INFO: Shutting down...
```

Full log is here: https://gist.github.com/m-iancu/9954297a39f461d6c69c0a378dc2d0bf

**Comment by iSignal** [comment]
The bad file descriptor issue was fixed by 82b070afc039a9c382037496c569316d8e238018
