### ISSUE TITLE
[YSQL] libpq from a system library directory might be linked and pull in other system libraries

### ISSUE THREAD

**Issue by mbautin** [yugabyte/yugabyte-db#3215]
E.g. https://gist.githubusercontent.com/mbautin/7b7bbfed06ec7b2770557efe98ff0e05/raw

Here are other system libraries besides libpq that are getting pulled in:
```
	libssl.so.10 => /usr/lib64/libssl.so.10 (0x00007f0336bd4000)
	libcrypto.so.10 => /usr/lib64/libcrypto.so.10 (0x00007f0336773000)
	libkrb5.so.3 => /usr/lib64/libkrb5.so.3 (0x00007f033648b000)
	libcom_err.so.2 => /usr/lib64/libcom_err.so.2 (0x00007f0336287000)
	libgssapi_krb5.so.2 => /usr/lib64/libgssapi_krb5.so.2 (0x00007f033603a000)
	libldap_r-2.4.so.2 => /usr/lib64/libldap_r-2.4.so.2 (0x00007f0335ddb000)
	libicudata.so.61 => /opt/yb-build/brew/linuxbrew-20181203T161736v2-3ba4c2ed9b0587040949a4a9a95b576f520bae/Cellar/icu4c/61.1/lib/libicudata.so.61 (0x00007f0334235000)
	libk5crypto.so.3 => /usr/lib64/libk5crypto.so.3 (0x00007f0334002000)
	libkrb5support.so.0 => /usr/lib64/libkrb5support.so.0 (0x00007f0333df4000)
	libkeyutils.so.1 => /usr/lib64/libkeyutils.so.1 (0x00007f0333bf0000)
	libresolv.so.2 => /opt/yb-build/brew/linuxbrew-20181203T161736v2-3ba4c2ed9b0587040949a4a9a95b576f520bae/lib/libresolv.so.2 (0x00007f03339d9000)
	liblber-2.4.so.2 => /usr/lib64/liblber-2.4.so.2 (0x00007f03337ca000)
	libsasl2.so.3 => /usr/lib64/libsasl2.so.3 (0x00007f03335ad000)
	libssl3.so => /usr/lib64/libssl3.so (0x00007f033335b000)
	libsmime3.so => /usr/lib64/libsmime3.so (0x00007f0333134000)
	libnss3.so => /usr/lib64/libnss3.so (0x00007f0332e07000)
	libnssutil3.so => /usr/lib64/libnssutil3.so (0x00007f0332bd8000)
	libplds4.so => /usr/lib64/libplds4.so (0x00007f03329d4000)
	libplc4.so => /usr/lib64/libplc4.so (0x00007f03327cf000)
	libnspr4.so => /usr/lib64/libnspr4.so (0x00007f0332591000)
	libselinux.so.1 => /usr/lib64/libselinux.so.1 (0x00007f033236a000)
	libpcre.so.1 => /usr/lib64/libpcre.so.1 (0x00007f0331ed1000)
```

This could most likely be resolved by fixing rpath.

**Comment by tedyu** [comment]
./yb_release --build release --build_target ./build/target --build_archive

The build ended up with:
```
2020-11-06 13:24:49,327 [release_util.py:82 INFO] Substituting '$BUILD_ROOT/postgres/*' -> '/nfusr/dev-server/tedyu/yugabyte-db/build/release-gcc-dynamic-ninja/postgres/*' in manifest
2020-11-06 13:24:49,327 [release_util.py:82 INFO] Substituting 'thirdparty/installed/common/cqlsh/pylib/*' -> '/opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20201023135146-67b1057678-centos/installed/common/cqlsh/pylib/*' in manifest
2020-11-06 13:24:49,327 [release_util.py:82 INFO] Substituting '$BUILD_ROOT/share/initial_sys_catalog_snapshot' -> '/nfusr/dev-server/tedyu/yugabyte-db/build/release-gcc-dynamic-ninja/share/initial_sys_catalog_snapshot' in manifest
Traceback (most recent call last):
  File "/nfusr/dev-server/tedyu/yugabyte-db/build-support/yb_release.py", line 294, in <module>
    main()
  File "/nfusr/dev-server/tedyu/yugabyte-db/build-support/yb_release.py", line 237, in main
    library_packager.package_binaries()
  File "/nfusr/dev-server/tedyu/yugabyte-db/python/yb/library_packager.py", line 347, in package_binaries
    dep_name, deps
RuntimeError: Multiple dependencies with the same name libpq.so.5 but different targets: [Dependency(name='libpq.so.5', target='/nfusr/dev-server/tedyu/yugabyte-db/build/release-gcc-dynamic-ninja/postgres/lib/libpq.so.5.11', origin='/nfusr/dev-server/tedyu/yugabyte-db/build/release-gcc-dynamic-ninja/postgres/bin/vacuumlo'), Dependency(name='libpq.so.5', target='/usr/lib64/libpq.so.5.5', origin='/nfusr/dev-server/tedyu/yugabyte-db/build/release-gcc-dynamic-ninja/bin/yb-admin')]
```
What remediation should I take ?

thanks

**Comment by bmatican** [comment]
We no longer link to system libpq
