### ISSUE TITLE
[YW] NPE encountered when adding a node after node decommission

### ISSUE THREAD

**Issue by ajcaldera1** [yugabyte/yugabyte-db#3232]
This error was encountered on portal (2.0.9.0-b16)
Configure a universe with TLS (node-to-node) enabled 
Decommission one of the nodes and remove it from the universe
Commission a new node to take its place

```
2019-12-28 00:44:47,819 [ERROR] from com.yugabyte.yw.commissioner.SubTaskGroup in TaskPool-7 - Failed to execute task java.util.concurrent.FutureTask@11f47ca5, hit error java.lang.NullPointerException: The id is null.
java.util.concurrent.ExecutionException: java.lang.NullPointerException: The id is null
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:192)
    at com.yugabyte.yw.commissioner.SubTaskGroup.waitFor(SubTaskGroup.java:175)
    at com.yugabyte.yw.commissioner.SubTaskGroupQueue.run(SubTaskGroupQueue.java:42)
    at com.yugabyte.yw.commissioner.tasks.AddNodeToUniverse.run(AddNodeToUniverse.java:182)
    at com.yugabyte.yw.commissioner.TaskRunner.run(TaskRunner.java:143)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException: The id is null
    at com.avaje.ebeaninternal.server.core.DefaultServer.find(DefaultServer.java:1033)
    at com.avaje.ebeaninternal.server.core.DefaultServer.find(DefaultServer.java:1024)
    at com.avaje.ebean.Model$Find.byId(Model.java:556)
    at com.yugabyte.yw.models.CertificateInfo.get(CertificateInfo.java:69)
    at com.yugabyte.yw.common.NodeManager.getConfigureSubCommand(NodeManager.java:240)
    at com.yugabyte.yw.common.NodeManager.nodeCommand(NodeManager.java:406)
    at com.yugabyte.yw.commissioner.tasks.subtasks.AnsibleConfigureServers.run(AnsibleConfigureServers.java:52)
    ... 5 common frames omitted
2019-12-28 00:44:47,821 [ERROR] from com.yugabyte.yw.commissioner.SubTaskGroupQueue in TaskPool-7 - SubTaskGroup 'AnsibleConfigureServers : completed 0 out of 1 tasks.' waitFor() returned failed status.
2019-12-28 00:44:47,822 [ERROR] from com.yugabyte.yw.commissioner.tasks.AddNodeToUniverse in TaskPool-7 - Error executing task AddNodeToUniverse(2354825f-5d86-4f4c-b364-e57de2cd5812) with error='AnsibleConfigureServers : completed 0 out of 1 tasks. failed.'.
java.lang.RuntimeException: AnsibleConfigureServers : completed 0 out of 1 tasks. failed.
    at com.yugabyte.yw.commissioner.SubTaskGroupQueue.run(SubTaskGroupQueue.java:54)
    at com.yugabyte.yw.commissioner.tasks.AddNodeToUniverse.run(AddNodeToUniverse.java:182)
    at com.yugabyte.yw.commissioner.TaskRunner.run(TaskRunner.java:143)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
```
Other relevant interesting message:
```
ansible-prometheus : install libselinux-python binary for Ansible to work --- 1.87s'
2019-12-28 00:44:46,395 [INFO] from com.yugabyte.yw.commissioner.SubTaskGroup in TaskPool-7 - Running task list AnsibleUpdateNodeInfo.
2019-12-28 00:44:46,399 [INFO] from com.yugabyte.yw.common.DevopsBase in TaskPool-AddNodeToUniverse(2354825f-5d86-4f4c-b364-e57de2cd5812)-2 - Command to run: [bin/ybcloud.sh aws --region us-east-1 --zone us-east-1a instance list --as_json yb-15-ac-c1-largetest-east-n5]
2019-12-28 00:44:47,806 [INFO] from com.yugabyte.yw.common.ShellProcessHandler in TaskPool-AddNodeToUniverse(2354825f-5d86-4f4c-b364-e57de2cd5812)-2 - [{"subnet": "subnet-43b5bf0b", "name": "yb-15-ac-c1-largetest-east-n5", "zone": "us-east-1a", "server_type": "cluster-server", "region": "us-east-1", "launch_time": "2019-12-28T00:41:01+00:00", "launched_by": "yugabyte", "public_ip": "54.221.149.97", "instance_type": "c5.2xlarge", "public_dns": "ec2-54-221-149-97.compute-1.amazonaws.com", "vpc": "vpc-54416f2d", "private_dns": "ip-172-152-16-250.ec2.internal", "id": "i-026fdf9728d1cb2e1", "private_ip": "172.152.16.250"}]
2019-12-28 00:44:47,806 [INFO] from com.yugabyte.yw.common.ShellProcessHandler in TaskPool-AddNodeToUniverse(2354825f-5d86-4f4c-b364-e57de2cd5812)-2 - 2019-12-28 00:44:46,937 INFO: Found aws cloud credentials in env.
2019-12-28 00:44:47,806 [INFO] from com.yugabyte.yw.common.ShellProcessHandler in TaskPool-AddNodeToUniverse(2354825f-5d86-4f4c-b364-e57de2cd5812)-2 - 2019-12-28 00:44:46,968 INFO: Found credentials in environment variables.
2019-12-28 00:44:47,806 [INFO] from com.yugabyte.yw.commissioner.AbstractTaskBase in TaskPool-AddNodeToUniverse(2354825f-5d86-4f4c-b364-e57de2cd5812)-2 - [AnsibleUpdateNodeInfo(2354825f-5d86-4f4c-b364-e57de2cd5812, yb-15-ac-c1-largetest-east-n5)] STDOUT: '[{"subnet": "subnet-43b5bf0b", "name": "yb-15-ac-c1-largetest-east-n5", "zone": "us-east-1a", "server_type": "cluster-server", "region": "us-east-1", "launch_time": "2019-12-28T00:41:01+00:00", "launched_by": "yugabyte", "public_ip": "54.221.149.97", "instance_type": "c5.2xlarge", "public_dns": "ec2-54-221-149-97.compute-1.amazonaws.com", "vpc": "vpc-54416f2d", "private_dns": "ip-172-152-16-250.ec2.internal", "id": "i-026fdf9728d1cb2e1", "private_ip": "172.152.16.250"}]'
2019-12-28 00:44:47,806 [INFO] from com.yugabyte.yw.commissioner.tasks.subtasks.AnsibleUpdateNodeInfo in TaskPool-AddNodeToUniverse(2354825f-5d86-4f4c-b364-e57de2cd5812)-2 - Updating details uuid=2354825f-5d86-4f4c-b364-e57de2cd5812, name=yb-15-ac-c1-largetest-east-n5.
2019-12-28 00:44:47,808 [INFO] from com.yugabyte.yw.commissioner.tasks.subtasks.AnsibleUpdateNodeInfo in TaskPool-AddNodeToUniverse(2354825f-5d86-4f4c-b364-e57de2cd5812)-2 - Node yb-15-ac-c1-largetest-east-n5: setting field subnet to value "subnet-43b5bf0b".
2019-12-28 00:44:47,809 [WARN] from com.yugabyte.yw.commissioner.tasks.subtasks.AnsibleUpdateNodeInfo in TaskPool-AddNodeToUniverse(2354825f-5d86-4f4c-b364-e57de2cd5812)-2 - Skipping field subnet with value "subnet-43b5bf0b" due to error subnet.
2019-12-28 00:44:47,809 [INFO] from com.yugabyte.yw.commissioner.tasks.subtasks.AnsibleUpdateNodeInfo in TaskPool-AddNodeToUniverse(2354825f-5d86-4f4c-b364-e57de2cd5812)-2 - Node yb-15-ac-c1-largetest-east-n5: setting field name to value "yb-15-ac-c1-largetest-east-n5".
2019-12-28 00:44:47,809 [WARN] from com.yugabyte.yw.commissioner.tasks.subtasks.AnsibleUpdateNodeInfo in TaskPool-AddNodeToUniverse(2354825f-5d86-4f4c-b364-e57de2cd5812)-2 - Skipping field name with value "yb-15-ac-c1-largetest-east-n5" due to error name.
2019-12-28 00:44:47,809 [INFO] from com.yugabyte.yw.commissioner.tasks.subtasks.AnsibleUpdateNodeInfo in TaskPool-AddNodeToUniverse(2354825f-5d86-4f4c-b364-e57de2cd5812)-2 - Node yb-15-ac-c1-largetest-east-n5: setting field zone to value "us-east-1a".
2019-12-28 00:44:47,809 [WARN] from com.yugabyte.yw.commissioner.tasks.subtasks.AnsibleUpdateNodeInfo in TaskPool-AddNodeToUniverse(2354825f-5d86-4f4c-b364-e57de2cd5812)-2 - Skipping field zone with value "us-east-1a" due to error zone.
2019-12-28 00:44:47,809 [INFO] from com.yugabyte.yw.commissioner.tasks.subtasks.AnsibleUpdateNodeInfo in TaskPool-AddNodeToUniverse(2354825f-5d86-4f4c-b364-e57de2cd5812)-2 - Node yb-15-ac-c1-largetest-east-n5: setting field server_type to value "cluster-server".
019-12-28 00:44:47,809 [WARN] from com.yugabyte.yw.commissioner.tasks.subtasks.AnsibleUpdateNodeInfo in TaskPool-AddNodeToUniverse(2354825f-5d86-4f4c-b364-e57de2cd5812)-2 - Skipping field server_type with value "cluster-server" due to error server_type.
2019-12-28 00:44:47,809 [INFO] from com.yugabyte.yw.commissioner.tasks.subtasks.AnsibleUpdateNodeInfo in TaskPool-AddNodeToUniverse(2354825f-5d86-4f4c-b364-e57de2cd5812)-2 - Node yb-15-ac-c1-largetest-east-n5: setting field region to value "us-east-1".
2019-12-28 00:44:47,809 [INFO] from com.yugabyte.yw.commissioner.tasks.subtasks.AnsibleUpdateNodeInfo in TaskPool-AddNodeToUniverse(2354825f-5d86-4f4c-b364-e57de2cd5812)-2 - Node yb-15-ac-c1-largetest-east-n5: setting field launch_time to value "2019-12-28T00:41:01+00:00".
2019-12-28 00:44:47,809 [WARN] from com.yugabyte.yw.commissioner.tasks.subtasks.AnsibleUpdateNodeInfo in TaskPool-AddNodeToUniverse(2354825f-5d86-4f4c-b364-e57de2cd5812)-2 - Skipping field launch_time with value "2019-12-28T00:41:01+00:00" due to error launch_time.
2019-12-28 00:44:47,809 [INFO] from com.yugabyte.yw.commissioner.tasks.subtasks.AnsibleUpdateNodeInfo in TaskPool-AddNodeToUniverse(2354825f-5d86-4f4c-b364-e57de2cd5812)-2 - Node yb-15-ac-c1-largetest-east-n5: setting field launched_by to value "yugabyte".
2019-12-28 00:44:47,809 [WARN] from com.yugabyte.yw.commissioner.tasks.subtasks.AnsibleUpdateNodeInfo in TaskPool-AddNodeToUniverse(2354825f-5d86-4f4c-b364-e57de2cd5812)-2 - Skipping field launched_by with value "yugabyte" due to error launched_by.
2019-12-28 00:44:47,809 [INFO] from com.yugabyte.yw.commissioner.tasks.subtasks.AnsibleUpdateNodeInfo in TaskPool-AddNodeToUniverse(2354825f-5d86-4f4c-b364-e57de2cd5812)-2 - Node yb-15-ac-c1-largetest-east-n5: setting field public_ip to value "54.221.149.97".
2019-12-28 00:44:47,809 [INFO] from com.yugabyte.yw.commissioner.tasks.subtasks.AnsibleUpdateNodeInfo in TaskPool-AddNodeToUniverse(2354825f-5d86-4f4c-b364-e57de2cd5812)-2 - Node yb-15-ac-c1-largetest-east-n5: setting field instance_type to value "c5.2xlarge".
2019-12-28 00:44:47,809 [INFO] from com.yugabyte.yw.commissioner.tasks.subtasks.AnsibleUpdateNodeInfo in TaskPool-AddNodeToUniverse(2354825f-5d86-4f4c-b364-e57de2cd5812)-2 - Node yb-15-ac-c1-largetest-east-n5: setting field public_dns to value "ec2-54-221-149-97.compute-1.amazonaws.com".
2019-12-28 00:44:47,810 [INFO] from com.yugabyte.yw.commissioner.tasks.subtasks.AnsibleUpdateNodeInfo in TaskPool-AddNodeToUniverse(2354825f-5d86-4f4c-b364-e57de2cd5812)-2 - Node yb-15-ac-c1-largetest-east-n5: setting field vpc to value "vpc-54416f2d".
2019-12-28 00:44:47,810 [WARN] from com.yugabyte.yw.commissioner.tasks.subtasks.AnsibleUpdateNodeInfo in TaskPool-AddNodeToUniverse(2354825f-5d86-4f4c-b364-e57de2cd5812)-2 - Skipping field vpc with value "vpc-54416f2d" due to error vpc.
2019-12-28 00:44:47,810 [INFO] from com.yugabyte.yw.commissioner.tasks.subtasks.AnsibleUpdateNodeInfo in TaskPool-AddNodeToUniverse(2354825f-5d86-4f4c-b364-e57de2cd5812)-2 - Node yb-15-ac-c1-largetest-east-n5: setting field private_dns to value "ip-172-152-16-250.ec2.internal".
2019-12-28 00:44:47,810 [INFO] from com.yugabyte.yw.commissioner.tasks.subtasks.AnsibleUpdateNodeInfo in TaskPool-AddNodeToUniverse(2354825f-5d86-4f4c-b364-e57de2cd5812)-2 - Node yb-15-ac-c1-largetest-east-n5: setting field id to value "i-026fdf9728d1cb2e1".
2019-12-28 00:44:47,810 [WARN] from com.yugabyte.yw.commissioner.tasks.subtasks.AnsibleUpdateNodeInfo in TaskPool-AddNodeToUniverse(2354825f-5d86-4f4c-b364-e57de2cd5812)-2 - Skipping field id with value "i-026fdf9728d1cb2e1" due to error id.
2019-12-28 00:44:47,810 [INFO] from com.yugabyte.yw.commissioner.tasks.subtasks.AnsibleUpdateNodeInfo in TaskPool-AddNodeToUniverse(2354825f-5d86-4f4c-b364-e57de2cd5812)-2 - Node yb-15-ac-c1-largetest-east-n5: setting field private_ip to value "172.152.16.250".
2019-12-28 00:44:47,815 [INFO] from com.yugabyte.yw.commissioner.SubTaskGroup in TaskPool-7 - Running task list AnsibleConfigureServers.
```

Aha! Link: https://yugabyte-test.aha.io/features/PLATFORM-877

**Comment by kriteshranjan** [comment]
Closing this issue based on AI validation. cc: @m-iancu , @VamsidharGunturu
