### ISSUE TITLE
TypeError: not enough arguments for format string in build_postgres.py

### ISSUE THREAD

**Issue by mbautin** [yugabyte/yugabyte-db#3238]
09:10:15 [build_postgres.py:732] 2019-12-31 17:10:15,026 INFO: PostgreSQL build stamp:
09:10:15 git_commit_sha1=ba64a7ed991c5f392578b12e46f0b4902e1c0ddc
09:10:15 git_diff_sha256=e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
09:10:15 git_diff_cached_sha256=e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
09:10:15 env_vars_sha256=fe062591b8a2c4b399226b4d8c6ed89bfb931d9f2341b16dddc872065bcff9e5
09:10:15 Traceback (most recent call last):
09:10:15   File "/usr/lib64/python2.7/logging/__init__.py", line 851, in emit
09:10:15     msg = self.format(record)
09:10:15   File "/usr/lib64/python2.7/logging/__init__.py", line 724, in format
09:10:15     return fmt.format(record)
09:10:15   File "/usr/lib64/python2.7/logging/__init__.py", line 464, in format
09:10:15     record.message = record.getMessage()
09:10:15   File "/usr/lib64/python2.7/logging/__init__.py", line 328, in getMessage
09:10:15     msg = msg % self.args
09:10:15 TypeError: not enough arguments for format string
09:10:15 Logged from file build_postgres.py, line 743

**Comment by kriteshranjan** [comment]
Closing this issue based on AI validation. cc: @m-iancu , @VamsidharGunturu
