### ISSUE TITLE
[YW] Creating onprem provider causes infinite recursion

### ISSUE THREAD

**Issue by WesleyW** [yugabyte/yugabyte-db#3274]
Creating on-prem with "Passwordless Sudo" disabled and "Air Gap Installation" enabled causes the UI to crash with the following error:

```
The above error occurred in the <OnPremConfiguration> component:
    in OnPremConfiguration (created by Connect(OnPremConfiguration))
    in Connect(OnPremConfiguration) (at DataCenterConfiguration.js:80)
    in div (created by TabPane)
    in Transition (created by Fade)
    in Fade (created by TabPane)
    in TabPane (created by Tab)
    in Tab (at DataCenterConfiguration.js:79)
    in div (created by TabContent)
    in TabContent (created by Tabs)
    in div (created by Tabs)
    in TabContainer (created by Tabs)
    in Tabs (created by Uncontrolled(Tabs))
    in Uncontrolled(Tabs) (created by ForwardRef)
    in ForwardRef (at YBTabsPanel.js:45)
    in YBTabsPanel (created by withRouter(YBTabsPanel))
    in withRouter(YBTabsPanel) (at DataCenterConfiguration.js:63)
    in div (created by TabPane)
    in Transition (created by Fade)
    in Fade (created by TabPane)
    in TabPane (created by Tab)
    in Tab (at DataCenterConfiguration.js:62)
    in div (created by TabContent)
    in TabContent (created by Tabs)
    in div (created by Tabs)
    in TabContainer (created by Tabs)
    in Tabs (created by Uncontrolled(Tabs))
    in Uncontrolled(Tabs) (created by ForwardRef)
    in ForwardRef (at YBTabsPanel.js:45)
    in YBTabsPanel (created by withRouter(YBTabsPanel))
    in withRouter(YBTabsPanel) (at DataCenterConfiguration.js:60)
    in div (at DataCenterConfiguration.js:58)
    in DataCenterConfiguration (created by withRouter(DataCenterConfiguration))
    in withRouter(DataCenterConfiguration) (created by Connect(withRouter(DataCenterConfiguration)))
    in Connect(withRouter(DataCenterConfiguration)) (at DataCenterConfiguration.js:10)
    in div (at DataCenterConfiguration.js:9)
    in DataCenterConfiguration (created by RouterContext)
    in div (at AuthenticatedComponent.js:89)
    in div (at AuthenticatedComponent.js:85)
    in AuthenticatedComponent (created by withRouter(AuthenticatedComponent))
    in withRouter(AuthenticatedComponent) (created by Connect(withRouter(AuthenticatedComponent)))
    in Connect(withRouter(AuthenticatedComponent)) (at AuthenticatedComponent.js:87)
    in AuthenticatedComponent (created by _class)
    in _class (created by RouterContext)
    in div (at App.js:12)
    in App (created by RouterContext)
    in RouterContext (created by Router)
    in Router (at src/index.js:18)
    in IntlProvider (at src/index.js:17)
    in Provider (at src/index.js:16)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
__stack_frame_overlay_proxy_console__ @ proxyConsole.js:56
r @ backend.js:6
logCapturedError @ react-dom.development.js:19814
logError @ react-dom.development.js:19850
update.callback @ react-dom.development.js:20929
callCallback @ react-dom.development.js:12929
commitUpdateEffects @ react-dom.development.js:12968
commitUpdateQueue @ react-dom.development.js:12956
commitLifeCycles @ react-dom.development.js:20098
commitLayoutEffects @ react-dom.development.js:22813
callCallback @ react-dom.development.js:347
invokeGuardedCallbackDev @ react-dom.development.js:397
invokeGuardedCallback @ react-dom.development.js:454
commitRootImpl @ react-dom.development.js:22585
unstable_runWithPriority @ scheduler.development.js:643
runWithPriority$2 @ react-dom.development.js:11305
commitRoot @ react-dom.development.js:22414
runRootCallback @ react-dom.development.js:21554
(anonymous) @ react-dom.development.js:11353
unstable_runWithPriority @ scheduler.development.js:643
runWithPriority$2 @ react-dom.development.js:11305
flushSyncCallbackQueueImpl @ react-dom.development.js:11349
flushSyncCallbackQueue @ react-dom.development.js:11338
scheduleUpdateOnFiber @ react-dom.development.js:21431
enqueueSetState @ react-dom.development.js:13100
Component.setState @ react.development.js:325
handleChange @ connect.js:302
dispatch @ createStore.js:173
e @ VM11333:1
(anonymous) @ index.js:28
dispatch @ applyMiddleware.js:35
(anonymous) @ index.js:25
Promise.then (async)
(anonymous) @ index.js:24
createOnPremProvider @ OnPremConfigurationContainer.js:58
OnPremConfiguration._this.submitWizardJson @ OnPremConfiguration.js:252
setOnPremRegionsAndZones @ OnPremRegionsAndZonesContainer.js:28
OnPremRegionsAndZones._this3.createOnPremRegionsAndZones @ OnPremRegionsAndZones.js:102
doSubmit @ handleSubmit.js:30
handleSubmit @ handleSubmit.js:92
(anonymous) @ createReduxForm.js:293
(anonymous) @ silenceEvents.js:9
callCallback @ react-dom.development.js:347
invokeGuardedCallbackDev @ react-dom.development.js:397
invokeGuardedCallback @ react-dom.development.js:454
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:468
executeDispatch @ react-dom.development.js:600
executeDispatchesInOrder @ react-dom.development.js:622
executeDispatchesAndRelease @ react-dom.development.js:725
executeDispatchesAndReleaseTopLevel @ react-dom.development.js:733
forEachAccumulated @ react-dom.development.js:707
runEventsInBatch @ react-dom.development.js:750
runExtractedPluginEventsInBatch @ react-dom.development.js:881
handleTopLevel @ react-dom.development.js:5901
batchedEventUpdates @ react-dom.development.js:2344
dispatchEventForPluginEventSystem @ react-dom.development.js:5996
dispatchEvent @ react-dom.development.js:6025
unstable_runWithPriority @ scheduler.development.js:643
runWithPriority$2 @ react-dom.development.js:11305
discreteUpdates$1 @ react-dom.development.js:21672
discreteUpdates @ react-dom.development.js:2359
dispatchDiscreteEvent @ react-dom.development.js:5979
Show 2 more frames

-------

react-dom.development.js:23115 Uncaught (in promise) Invariant Violation: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
    at http://localhost:3000/static/js/bundle.js:349708:28
    at checkForNestedUpdates (http://localhost:3000/static/js/bundle.js:349711:7)
    at scheduleUpdateOnFiber (http://localhost:3000/static/js/bundle.js:347982:3)
    at Object.enqueueSetState (http://localhost:3000/static/js/bundle.js:339693:5)
    at OnPremConfiguration.Component.setState (http://localhost:3000/static/js/bundle.js:415177:16)
    at OnPremConfiguration.componentDidUpdate (http://localhost:3000/static/js/bundle.js:373275:14)
    at commitLifeCycles (http://localhost:3000/static/js/bundle.js:346657:22)
    at commitLayoutEffects (http://localhost:3000/static/js/bundle.js:349406:7)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/bundle.js:326940:14)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/bundle.js:326990:16)
    at invokeGuardedCallback (http://localhost:3000/static/js/bundle.js:327047:31)
    at commitRootImpl (http://localhost:3000/static/js/bundle.js:349178:9)
    at unstable_runWithPriority (http://localhost:3000/static/js/bundle.js:424750:12)
    at runWithPriority$2 (http://localhost:3000/static/js/bundle.js:337898:10)
    at commitRoot (http://localhost:3000/static/js/bundle.js:349007:3)
    at runRootCallback (http://localhost:3000/static/js/bundle.js:348147:20)
    at http://localhost:3000/static/js/bundle.js:337946:24
    at unstable_runWithPriority (http://localhost:3000/static/js/bundle.js:424750:12)
    at runWithPriority$2 (http://localhost:3000/static/js/bundle.js:337898:10)
    at flushSyncCallbackQueueImpl (http://localhost:3000/static/js/bundle.js:337942:7)
    at flushSyncCallbackQueue (http://localhost:3000/static/js/bundle.js:337931:3)
    at scheduleUpdateOnFiber (http://localhost:3000/static/js/bundle.js:348024:9)
    at Object.enqueueSetState (http://localhost:3000/static/js/bundle.js:339693:5)
    at Connect.Component.setState (http://localhost:3000/static/js/bundle.js:415177:16)
    at Connect.handleChange (http://localhost:3000/static/js/bundle.js:362728:14)
    at Object.dispatch (http://localhost:3000/static/js/bundle.js:179007:7)
    at e (<anonymous>:1:40553)
    at http://localhost:3000/static/js/bundle.js:178770:12
    at dispatch (http://localhost:3000/static/js/bundle.js:422409:18)
    at http://localhost:3000/static/js/bundle.js:178767:16
```

**Comment by yb-andrew** [comment]
@WesleyW I wasn't able to reproduce this when I tested a couple weeks ago. Can you confirm if this is still an issue?

**Comment by ramkumarvs** [comment]
I reverted some react changes to address this.
