### ISSUE TITLE
[YSQL] Catalog Version Mismatch: A DDL occurred while processing this query. Try Again

### ISSUE THREAD

**Issue by MPaularBear** [yugabyte/yugabyte-db#3350]
Jira Link: [DB-2561](https://yugabyte.atlassian.net/browse/DB-2561)
While benchmarking YugabyteDB using sysbench, during prepare stage, if added the --threads = N flag, as below:

```
sysbench oltp_read_only  \
--tables=10  \
--table_size=1000  \
--threads=10  \
prepare
```

Then problem soon occure as shown in the header. Its obvious that **concurrent create table ddls** cause the problem.  the below issue as been closed, but seems the problem still exist.  Any suggestions?

https://github.com/YugaByte/yugabyte-db/issues/1457
[YSQL] Spurious "Catalog Version Mismatch: A DDL occurred while processing this query" #1457

--------------update 2020 01 16------------------
The problem also occurs today,  when 
**session 1 :**
```
creating table 'sbtest1'...
Inserting 3 records into 'sbtest1'...
creating table 'sbtest2'...
Inserting 3 records into 'sbtest2'...
creating table 'sbtest3'...
Inserting 3 records into 'sbtest3'...
```

**session 2:**
`select * from sbtest4;`
after much a while, session 2 returns : ERROR: Catalog Version Mismatch: a DDL occured while processing this query. Try again.

**Comment by ndeodhar** [comment]
Hi @MPaularBear , thanks for reporting. We see this error if there's concurrent DDL operations sometimes. It's also being tracked here: https://github.com/yugabyte/yugabyte-db/issues/2323.
We'll have a solution for this towards the end of February.

In the meantime, can you please use threads=1 during the prepare stage to work around this problem?

**Comment by MPaularBear** [comment]
> Hi @MPaularBear , thanks for reporting. We see this error if there's concurrent DDL operations sometimes. It's also being tracked here: #2323.
> We'll have a solution for this towards the end of February.
> 
> In the meantime, can you please use threads=1 during the prepare stage to work around this problem?
Thx ndeodhar, using threads=1 cause too much time , 200M inserts/ hour, we are going to prepare 32 tables with 1000M data / table.  i will pay close attention to the issue, thx.

**Comment by shuyouZZ** [comment]
After using the threads parameter，I had the same problem. <FATAL: PQexec() failed: 7 Catalog Version Mismatch: A DDL occurred while processing this query. Try Again.> Is this problem solved now?

**Comment by ddorian** [comment]
@shuyouZZ did you try with our sysbench fork https://github.com/yugabyte/sysbench ?

**Comment by snehalbhavsar916** [comment]
when I am running any DDL operation, it is blocking all the write operations on that server, even if the DDL is running on different object or on different database. So we are not able to conduct other  write operation on any database on that server at that time.

**Comment by snehalbhavsar916** [comment]
#3350 ERROR: Catalog Version Mismatch: a DDL occured while processing this query. Try again.
This error is impacting us in the way that is, when I am running any DDL operation, it is blocking all the write operations on that server, even if the DDL is running on different object or different database. So we are not able to conduct other  write operation on any database on that server at that time. 

Could anyone help to  understand what is the solution for this issue?

**Comment by iswarezwp** [comment]
same problems when run tpcc test with 2500 warehouses:
```
09:10:58,574 (DBWorkload.java:331) INFO  - Configuration -> nodes: [10.10.10.11, 10.10.10.12, 10.10.10.10], port: 5433, startWH: 1, warehouses: 2500, total warehouses across shards: 2500, terminals: 25000, dbConnections: 600, loaderThreads: 48
09:10:58,939 (DBWorkload.java:362) INFO  - ======================================================================

Benchmark:     TPCC {com.oltpbenchmark.benchmarks.tpcc.TPCCBenchmark}
Configuration: config/workload_all.xml
Type:          POSTGRES
Driver:        org.postgresql.Driver
URL:           [10.10.10.11, 10.10.10.12, 10.10.10.10]
Isolation:     TRANSACTION_REPEATABLE_READ
Scale Factor:  2500

09:10:58,939 (DBWorkload.java:363) INFO  - ======================================================================
09:10:58,952 (DBWorkload.java:638) INFO  - Creating new TPCC database...
09:11:13,645 (DBWorkload.java:640) INFO  - Finished!
09:11:13,645 (DBWorkload.java:641) INFO  - ======================================================================
09:11:13,646 (DBWorkload.java:664) INFO  - Loading data into TPCC database with 48 threads...
java.sql.BatchUpdateException: Batch entry 2 INSERT INTO OORDER VALUES (239, 1, 509, 1379, 4, 13, 1, '2020-10-22 09:52:58.167+08') was aborted: ERROR: Catalog Version Mismatch: A DDL occurred while processing this query. Try Again.  Call getNextException to see other errors in the batch.
        at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:148)
        at org.postgresql.core.ResultHandlerDelegate.handleError(ResultHandlerDelegate.java:50)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2212)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:509)
        at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:853)
        at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1546)
        at com.oltpbenchmark.benchmarks.tpcc.TPCCLoader.loadOrders(TPCCLoader.java:696)
        at com.oltpbenchmark.benchmarks.tpcc.TPCCLoader$2.load(TPCCLoader.java:112)
        at com.oltpbenchmark.api.Loader$LoaderThread.run(Loader.java:64)
        at com.oltpbenchmark.util.ThreadUtil$LatchRunnable.run(ThreadUtil.java:343)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.postgresql.util.PSQLException: ERROR: Catalog Version Mismatch: A DDL occurred while processing this query. Try Again.
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2468)
```

**Comment by kriteshranjan** [comment]
Closing this issue based on AI validation. cc: @m-iancu , @VamsidharGunturu
