### ISSUE TITLE
[YCQL] Application stuck in BoundStatement execution if a variable was not bound

### ISSUE THREAD

**Issue by OlegLoginov** [yugabyte/yugabyte-db#3419]
The Application is stuck with the Java reproducer:
```
    session.execute("CREATE TABLE productkey (key text," +
                    "                         key_type text," +
                    "                         tenant text," +
                    "                         PRIMARY KEY (key)) " +
                    "WITH TRANSACTIONS = {'enabled' : true};");
    String transactionStmt = "BEGIN TRANSACTION insert into productkey (key, tenant) values (:key, :timestamp); insert into productkey (key, key_type, tenant) values (:key, :keyType, :tenant); END TRANSACTION;";
    PreparedStatement preparedStatement = session.prepare(transactionStmt);
    BoundStatement boundStatement  = preparedStatement.bind();
    boundStatement.setString("key", "test");
    ResultSet rs = session.execute(boundStatement);
    Row row  = rs.one();
    LOG.info("ROW: " + row);    
```
It hangs. And failed with the timeout later:
```
org.junit.runners.model.TestTimedOutException: test timed out after 180 seconds
	at app//org.yb.cql.TestBindVariable.test1(TestBindVariable.java:2397)
```

**Comment by OlegLoginov** [comment]
Scala reproducer:
The same code in scala and the application was stuck. The client didnot receive the error back to the client:
```
object TestYugabyte extends App  {
  implicit val session = Cluster.builder
    .addContactPoint("127.0.0.1")
    .withPort(9042)
    .build
    .connect()
  val selectStmt: String = "SELECT * FROM matchingapp.keymapping WHERE key = :key AND key_type = :key_type;"
  val preparedStatement: PreparedStatement = session.prepare(selectStmt)
  val boundStatement: BoundStatement = preparedStatement.bind
  boundStatement.setString("key", "test")
  //boundStatement.setString("key_type", "test")
  try {
    val rs: ResultSet = session.execute(boundStatement)
    val row: Row = rs.one
    println(row)
  } catch {
    case exception: Exception => {
      println("Error while executing" + " " + exception)
      throw new RuntimeException("Error while executing")
    }
  }
}
```

**Comment by OlegLoginov** [comment]
I cannot reproduce the issue from the java reproducer on the master branch.

**Comment by OlegLoginov** [comment]
I've reproduced the issue locally. The reproducer:
```
    session.execute("CREATE TABLE productkey (key text," +
                    "                         key_type text," +
                    "                         tenant text," +
                    "                         PRIMARY KEY (key)) " +
                    "WITH TRANSACTIONS = {'enabled' : true};");
    String transactionStmt = "BEGIN TRANSACTION insert into productkey (key, tenant) values (:key, :timestamp); insert into productkey (key, key_type, tenant) values (:key, :keyType, :tenant); END TRANSACTION;";
    {
      PreparedStatement preparedStatement = session.prepare(transactionStmt);
      BoundStatement boundStatement  = preparedStatement.bind();
      boundStatement.setString("key", "test");
      ResultSet rs = session.execute(boundStatement);
      Row row  = rs.one();
      LOG.info("ROW: " + row);    
    }
  }
```
It hangs. And failed with timeout later:
```
org.junit.runners.model.TestTimedOutException: test timed out after 180 seconds
	at app//org.yb.cql.TestBindVariable.test1(TestBindVariable.java:2397)
```

**Comment by OlegLoginov** [comment]
The log - it looks like endless retry-loop:
```
ts2|pid31142|:18313|http://127.9.36.33:15552 E0123 23:47:16.267711 31360 process_context.cc:180] SQL Error: Invalid Arguments. Invalid bind variable kind -2
ts2|pid31142|:18313|http://127.9.36.33:15552 BEGIN TRANSACTION insert into productkey (key, tenant) values (:key, :timestamp); insert into productkey (key, key_type, tenant) values (:key, :keyType, :tenant); END TRANSACTION;
ts2|pid31142|:18313|http://127.9.36.33:15552                          ^^^^
ts2|pid31142|:18313|http://127.9.36.33:15552 I0123 23:47:16.267829 31455 replica_state.cc:1268] T 7fb0bd1bb13646308945c7ffa600d318 P 142b19d0674142f9a17c23f3b6e37573 [term 2 FOLLOWER]: SetLeaderNoOpCommittedUnlocked(1)
2020-01-23 23:47:16,267 (cluster1-nio-worker-4) [INFO - com.datastax.driver.core.RequestHandler$SpeculativeExecution.onSet(RequestHandler.java:618)] Query BEGIN TRANSACTION insert into productkey (key, tenant) values (:key, :timestamp); insert into productkey (key, key_type, tenant) values (:key, :keyType, :tenant); END TRANSACTION; is not prepared on /127.9.36.33:9042, preparing before retrying executing. Seeing this message a few times is fine, but seeing it a lot may be source of performance problems
m2|pid30972|:16640|http://127.198.121.144:30930 I0123 23:47:16.272327 30998 catalog_manager.cc:4050] Peer 7988d3ea08b04fde9156953212900226 sent incremental report for 7fb0bd1bb13646308945c7ffa600d318, prev state op id: -1, prev state term: 2, prev state has_leader_uuid: 1. Consensus state: current_term: 2 leader_uuid: "cffcbf3a7821488eacd785f1921cde87" config { opid_index: -1 peers { permanent_uuid: "7988d3ea08b04fde9156953212900226" member_type: VOTER last_known_private_addr { host: "127.172.85.213" port: 15745 } cloud_info { placement_cloud: "cloud1" placement_region: "datacenter1" placement_zone: "rack1" } } peers { permanent_uuid: "cffcbf3a7821488eacd785f1921cde87" member_type: VOTER last_known_private_addr { host: "127.90.84.76" port: 23344 } cloud_info { placement_cloud: "cloud1" placement_region: "datacenter1" placement_zone: "rack1" } } peers { permanent_uuid: "142b19d0674142f9a17c23f3b6e37573" member_type: VOTER last_known_private_addr { host: "127.9.36.33" port: 18313 } cloud_info { placement_cloud: "cloud1" placement_region: "datacenter1" placement_zone: "rack1" } } }
ts2|pid31142|:18313|http://127.9.36.33:15552 E0123 23:47:16.272325 31360 process_context.cc:180] SQL Error: Invalid Arguments. Invalid bind variable kind -2
ts2|pid31142|:18313|http://127.9.36.33:15552 BEGIN TRANSACTION insert into productkey (key, tenant) values (:key, :timestamp); insert into productkey (key, key_type, tenant) values (:key, :keyType, :tenant); END TRANSACTION;
ts2|pid31142|:18313|http://127.9.36.33:15552                          ^^^^
2020-01-23 23:47:16,272 (cluster1-nio-worker-4) [INFO - com.datastax.driver.core.RequestHandler$SpeculativeExecution.onSet(RequestHandler.java:618)] Query BEGIN TRANSACTION insert into productkey (key, tenant) values (:key, :timestamp); insert into productkey (key, key_type, tenant) values (:key, :keyType, :tenant); END TRANSACTION; is not prepared on /127.9.36.33:9042, preparing before retrying executing. Seeing this message a few times is fine, but seeing it a lot may be source of performance problems
m2|pid30972|:16640|http://127.198.121.144:30930 I0123 23:47:16.272812 31352 catalog_manager.cc:4050] Peer 142b19d0674142f9a17c23f3b6e37573 sent incremental report for 7fb0bd1bb13646308945c7ffa600d318, prev state op id: -1, prev state term: 2, prev state has_leader_uuid: 1. Consensus state: current_term: 2 leader_uuid: "cffcbf3a7821488eacd785f1921cde87" config { opid_index: -1 peers { permanent_uuid: "7988d3ea08b04fde9156953212900226" member_type: VOTER last_known_private_addr { host: "127.172.85.213" port: 15745 } cloud_info { placement_cloud: "cloud1" placement_region: "datacenter1" placement_zone: "rack1" } } peers { permanent_uuid: "cffcbf3a7821488eacd785f1921cde87" member_type: VOTER last_known_private_addr { host: "127.90.84.76" port: 23344 } cloud_info { placement_cloud: "cloud1" placement_region: "datacenter1" placement_zone: "rack1" } } peers { permanent_uuid: "142b19d0674142f9a17c23f3b6e37573" member_type: VOTER last_known_private_addr { host: "127.9.36.33" port: 18313 } cloud_info { placement_cloud: "cloud1" placement_region: "datacenter1" placement_zone: "rack1" } } }
m2|pid30972|:16640|http://127.198.121.144:30930 I0123 23:47:16.273391 30997 catalog_manager.cc:4050] Peer 7988d3ea08b04fde9156953212900226 sent incremental report for 7fb0bd1bb13646308945c7ffa600d318, prev state op id: -1, prev state term: 2, prev state has_leader_uuid: 1. Consensus state: current_term: 2 leader_uuid: "cffcbf3a7821488eacd785f1921cde87" config { opid_index: -1 peers { permanent_uuid: "7988d3ea08b04fde9156953212900226" member_type: VOTER last_known_private_addr { host: "127.172.85.213" port: 15745 } cloud_info { placement_cloud: "cloud1" placement_region: "datacenter1" placement_zone: "rack1" } } peers { permanent_uuid: "cffcbf3a7821488eacd785f1921cde87" member_type: VOTER last_known_private_addr { host: "127.90.84.76" port: 23344 } cloud_info { placement_cloud: "cloud1" placement_region: "datacenter1" placement_zone: "rack1" } } peers { permanent_uuid: "142b19d0674142f9a17c23f3b6e37573" member_type: VOTER last_known_private_addr { host: "127.9.36.33" port: 18313 } cloud_info { placement_cloud: "cloud1" placement_region: "datacenter1" placement_zone: "rack1" } } }
ts2|pid31142|:18313|http://127.9.36.33:15552 E0123 23:47:16.277335 31360 process_context.cc:180] SQL Error: Invalid Arguments. Invalid bind variable kind -2
ts2|pid31142|:18313|http://127.9.36.33:15552 BEGIN TRANSACTION insert into productkey (key, tenant) values (:key, :timestamp); insert into productkey (key, key_type, tenant) values (:key, :keyType, :tenant); END TRANSACTION;
ts2|pid31142|:18313|http://127.9.36.33:15552                          ^^^^
2020-01-23 23:47:16,277 (cluster1-nio-worker-4) [INFO - com.datastax.driver.core.RequestHandler$SpeculativeExecution.onSet(RequestHandler.java:618)] Query BEGIN TRANSACTION insert into productkey (key, tenant) values (:key, :timestamp); insert into productkey (key, key_type, tenant) values (:key, :keyType, :tenant); END TRANSACTION; is not prepared on /127.9.36.33:9042, preparing before retrying executing. Seeing this message a few times is fine, but seeing it a lot may be source of performance problems
ts2|pid31142|:18313|http://127.9.36.33:15552 E0123 23:47:16.281597 31360 process_context.cc:180] SQL Error: Invalid Arguments. Invalid bind variable kind -2
ts2|pid31142|:18313|http://127.9.36.33:15552 BEGIN TRANSACTION insert into productkey (key, tenant) values (:key, :timestamp); insert into productkey (key, key_type, tenant) values (:key, :keyType, :tenant); END TRANSACTION;
ts2|pid31142|:18313|http://127.9.36.33:15552                          ^^^^
2020-01-23 23:47:16,281 (cluster1-nio-worker-4) [INFO - com.datastax.driver.core.RequestHandler$SpeculativeExecution.onSet(RequestHandler.java:618)] Query BEGIN TRANSACTION insert into productkey (key, tenant) values (:key, :timestamp); insert into productkey (key, key_type, tenant) values (:key, :keyType, :tenant); END TRANSACTION; is not prepared on /127.9.36.33:9042, preparing before retrying executing. Seeing this message a few times is fine, but seeing it a lot may be source of performance problems
ts2|pid31142|:18313|http://127.9.36.33:15552 E0123 23:47:16.285771 31360 process_context.cc:180] SQL Error: Invalid Arguments. Invalid bind variable kind -2
ts2|pid31142|:18313|http://127.9.36.33:15552 BEGIN TRANSACTION insert into productkey (key, tenant) values (:key, :timestamp); insert into productkey (key, key_type, tenant) values (:key, :keyType, :tenant); END TRANSACTION;
ts2|pid31142|:18313|http://127.9.36.33:15552                          ^^^^
2020-01-23 23:47:16,286 (cluster1-nio-worker-4) [INFO - com.datastax.driver.core.RequestHandler$SpeculativeExecution.onSet(RequestHandler.java:618)] Query BEGIN TRANSACTION insert into productkey (key, tenant) values (:key, :timestamp); insert into productkey (key, key_type, tenant) values (:key, :keyType, :tenant); END TRANSACTION; is not prepared on /127.9.36.33:9042, preparing before retrying executing. Seeing this message a few times is fine, but seeing it a lot may be source of performance problems
ts2|pid31142|:18313|http://127.9.36.33:15552 E0123 23:47:16.290482 31360 process_context.cc:180] SQL Error: Invalid Arguments. Invalid bind variable kind -2
ts2|pid31142|:18313|http://127.9.36.33:15552 BEGIN TRANSACTION insert into productkey (key, tenant) values (:key, :timestamp); insert into productkey (key, key_type, tenant) values (:key, :keyType, :tenant); END TRANSACTION;
ts2|pid31142|:18313|http://127.9.36.33:15552                          ^^^^
2020-01-23 23:47:16,290 (cluster1-nio-worker-4) [INFO - com.datastax.driver.core.RequestHandler$SpeculativeExecution.onSet(RequestHandler.java:618)] Query BEGIN TRANSACTION insert into productkey (key, tenant) values (:key, :timestamp); insert into productkey (key, key_type, tenant) values (:key, :keyType, :tenant); END TRANSACTION; is not prepared on /127.9.36.33:9042, preparing before retrying executing. Seeing this message a few times is fine, but seeing it a lot may be source of performance problems
ts2|pid31142|:18313|http://127.9.36.33:15552 E0123 23:47:16.294919 31360 process_context.cc:180] SQL Error: Invalid Arguments. Invalid bind variable kind -2
ts2|pid31142|:18313|http://127.9.36.33:15552 BEGIN TRANSACTION insert into productkey (key, tenant) values (:key, :timestamp); insert into productkey (key, key_type, tenant) values (:key, :keyType, :tenant); END TRANSACTION;
ts2|pid31142|:18313|http://127.9.36.33:15552                          ^^^^
2020-01-23 23:47:16,295 (cluster1-nio-worker-4) [INFO - com.datastax.driver.core.RequestHandler$SpeculativeExecution.onSet(RequestHandler.java:618)] Query BEGIN TRANSACTION insert into productkey (key, tenant) values (:key, :timestamp); insert into productkey (key, key_type, tenant) values (:key, :keyType, :tenant); END TRANSACTION; is not prepared on /127.9.36.33:9042, preparing before retrying executing. Seeing this message a few times is fine, but seeing it a lot may be source of performance problems
ts2|pid31142|:18313|http://127.9.36.33:15552 E0123 23:47:16.299459 31360 process_context.cc:180] SQL Error: Invalid Arguments. Invalid bind variable kind -2
ts2|pid31142|:18313|http://127.9.36.33:15552 BEGIN TRANSACTION insert into productkey (key, tenant) values (:key, :timestamp); insert into productkey (key, key_type, tenant) values (:key, :keyType, :tenant); END TRANSACTION;
ts2|pid31142|:18313|http://127.9.36.33:15552                          ^^^^
2020-01-23 23:47:16,299 (cluster1-nio-worker-4) [INFO - com.datastax.driver.core.RequestHandler$SpeculativeExecution.onSet(RequestHandler.java:618)] Query BEGIN TRANSACTION insert into productkey (key, tenant) values (:key, :timestamp); insert into productkey (key, key_type, tenant) values (:key, :keyType, :tenant); END TRANSACTION; is not prepared on /127.9.36.33:9042, preparing before retrying executing. Seeing this message a few times is fine, but seeing it a lot may be source of performance problems
ts2|pid31142|:18313|http://127.9.36.33:15552 E0123 23:47:16.303897 31360 process_context.cc:180] SQL Error: Invalid Arguments. Invalid bind variable kind -2
ts2|pid31142|:18313|http://127.9.36.33:15552 BEGIN TRANSACTION insert into productkey (key, tenant) values (:key, :timestamp); insert into productkey (key, key_type, tenant) values (:key, :keyType, :tenant); END TRANSACTION;
ts2|pid31142|:18313|http://127.9.36.33:15552                          ^^^^
```

**Comment by OlegLoginov** [comment]
It happens when the TS returns retry-able CQL return code to the driver, so the driver repeat the request again and again. To fix this - TS must return another (non retry-able) CQL error code.

**Comment by OlegLoginov** [comment]
Point of the error generating:
```
Status CQLMessage::QueryParameters::GetBindVariable(const std::string& name,
                                                    const int64_t pos,
                                                    const shared_ptr<QLType>& type,
                                                    QLValue* value) const {
...
  switch (v->kind) {
    case Value::Kind::NOT_NULL: {
...
      return value->Deserialize(type, YQL_CLIENT_CQL, &data);
    }
    case Value::Kind::IS_NULL:
      value->SetNull();
      return Status::OK();
    case Value::Kind::NOT_SET:
      break;     <<<<<<<<<<<<<<<
  }
  return STATUS_SUBSTITUTE(
      RuntimeError, "Invalid bind variable kind $0", static_cast<int>(v->kind)); <<<<<<
}
```

**Comment by OlegLoginov** [comment]
Stack:
```
0x7fdf048faa00  yb::cqlserver::CQLMessage::QueryParameters::GetBindVariable(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, long, shared_ptr<yb::QLType> const&, yb::QLValue*) const (src/yb/yql/cql/cqlserver/cql_message.cc:138)
0x7fdf037c552a  yb::ql::Executor::PTExprToPB(yb::ql::PTBindVar const*, yb::QLExpressionPB*) (src/yb/yql/cql/ql/exec/eval_expr.cc:106)
0x7fdf037c579a  yb::ql::Executor::PTExprToPB(shared_ptr<yb::ql::PTExpr> const&, yb::QLExpressionPB*) (src/yb/yql/cql/ql/exec/eval_expr.cc:62)
0x7fdf037c7b39  yb::ql::Executor::ColumnArgsToPB(yb::ql::PTDmlStmt const*, yb::QLWriteRequestPB*) (src/yb/yql/cql/ql/exec/eval_col.cc:56)
0x7fdf037ee31e  yb::ql::Executor::ExecPTNode(yb::ql::PTInsertStmt const*, yb::ql::TnodeContext*) (src/yb/yql/cql/ql/exec/executor.cc:1139)
0x7fdf037f412b  yb::ql::Executor::ExecTreeNode(yb::ql::TreeNode const*) (src/yb/yql/cql/ql/exec/executor.cc:278)
0x7fdf037f4e54  yb::ql::Executor::ExecPTNode(yb::ql::PTListNode const*) (src/yb/yql/cql/ql/exec/executor.cc:372)
0x7fdf037f4070  yb::ql::Executor::ExecTreeNode(yb::ql::TreeNode const*) (src/yb/yql/cql/ql/exec/executor.cc:247)
0x7fdf037f42a1  yb::ql::Executor::Execute(yb::ql::ParseTree const&, yb::ql::StatementParameters const&) (src/yb/yql/cql/ql/exec/executor.cc:180)
0x7fdf037f441d  yb::ql::Executor::ExecuteAsync(yb::ql::ParseTree const&, yb::ql::StatementParameters const&, yb::Callback<void (yb::Status const&, shared_ptr<yb::ql::ExecutedResult> const&)>) (src/yb/yql/cql/ql/exec/executor.cc:94)
0x7fdf03c3365d  yb::ql::QLProcessor::ExecuteAsync(yb::ql::ParseTree const&, yb::ql::StatementParameters const&, yb::Callback<void (yb::Status const&, shared_ptr<yb::ql::ExecutedResult> const&)>) (src/yb/yql/cql/ql/ql_processor.cc:386)
0x7fdf03c29937  yb::ql::Statement::ExecuteAsync(yb::ql::QLProcessor*, yb::ql::StatementParameters const&, yb::Callback<void (yb::Status const&, shared_ptr<yb::ql::ExecutedResult> const&)>) const (src/yb/yql/cql/ql/statement.cc:90)
0x7fdf04906d29  yb::cqlserver::CQLProcessor::ProcessRequest(yb::cqlserver::ExecuteRequest const&) (src/yb/yql/cql/cqlserver/cql_processor.cc:315)
0x7fdf04907a24  yb::cqlserver::CQLProcessor::ProcessRequest(yb::cqlserver::CQLRequest const&) (src/yb/yql/cql/cqlserver/cql_processor.cc:227)
0x7fdf04907de4  yb::cqlserver::CQLProcessor::ProcessCall(shared_ptr<yb::rpc::InboundCall>) (src/yb/yql/cql/cqlserver/cql_processor.cc:176)
0x7fdf04925461  yb::cqlserver::CQLServiceImpl::Handle(shared_ptr<yb::rpc::InboundCall>) (src/yb/yql/cql/cqlserver/cql_service.cc:142)
0x7fdefcb2ced3  yb::rpc::ServicePoolImpl::Handle(shared_ptr<yb::rpc::InboundCall>) (src/yb/rpc/service_pool.cc:262)
0x7fdefcac5adf  yb::rpc::InboundCall::InboundCallTask::Run() (src/yb/rpc/inbound_call.cc:212)
0x7fdefcb3c33e  Execute (src/yb/rpc/thread_pool.cc:99)
0x7fdefcb3894f  __invoke_impl<void, void (yb::rpc::(anonymous namespace)::Worker::*&)(), yb::rpc::(anonymous namespace)::Worker*&> (/usr/include/c++/7/bits/invoke.h:73)
0x7fdefcb3894f  __invoke<void (yb::rpc::(anonymous namespace)::Worker::*&)(), yb::rpc::(anonymous namespace)::Worker*&> (/usr/include/c++/7/bits/invoke.h:95)
0x7fdefcb3894f  __call<void, 0> (/usr/include/c++/7/functional:467)
0x7fdefcb3894f  operator()<> (/usr/include/c++/7/functional:551)
0x7fdefcb3894f  _M_invoke (/usr/include/c++/7/bits/std_function.h:316)
0x7fdefb1bd69e  std::function<void ()>::operator()() const (/usr/include/c++/7/bits/std_function.h:706)
0x7fdefb1bd69e  yb::Thread::SuperviseThread(void*) (src/yb/util/thread.cc:739)
```

**Comment by OlegLoginov** [comment]
The same as in the issue https://github.com/yugabyte/yugabyte-db/issues/2116

Root cause: the error code mapping: Status::RuntimeError -> ErrorCode::INVALID_ARGUMENTS -> ErrorCode::STALE_METADATA -> Code::UNPREPARED (YCQL error code). UNPREPARED code is retryable in the driver.
(In case of Python driver the retry loop is endless, so the user will never get the error message.)

Fix: the fixed error code mapping is: (value too long) Status::NotSupported -> ErrorCode::INVALID_REQUEST -> Code::INVALID (non-retryable YCQL error code).

**Comment by OlegLoginov** [comment]
Reusing the existing code:

```
Status Executor::ExecPTNode(const PTInsertStmt *tnode, TnodeContext* tnode_context) {
...
  } else {
    s = ColumnArgsToPB(tnode, req);
    if (PREDICT_FALSE(!s.ok())) {
      // Note: INVALID_ARGUMENTS is retryable error code (due to mapping into STALE_METADATA),
      //       INVALID_REQUEST - non-retryable.
      ErrorCode error_code = (s.code() == Status::kNotSupported ?
          ErrorCode::INVALID_REQUEST : ErrorCode::INVALID_ARGUMENTS);    <<<<<<<<<<

      return exec_context_->Error(tnode, s, error_code);
    }
  }
```

**Comment by OlegLoginov** [comment]
Fixed by the commit above.
