### ISSUE TITLE
SIGSEGV encountered in CDCErrorPB::Clear during CDC testing

### ISSUE THREAD

**Issue by ajcaldera1** [yugabyte/yugabyte-db#3441]
The following stack trace occurred on a producer during CDC testing (2.0.11.0-b1)
```
#0  yb::AppStatusPB::Clear (this=0x0) at src/yb/common/wire_protocol.pb.cc:507
#1  0x00007fda1f618d39 in yb::cdc::CDCErrorPB::Clear (this=0x46ca9f0) at src/yb/cdc/cdc_service.pb.cc:1039
#2  0x00007fda1f619eca in yb::cdc::GetChangesResponsePB::Clear (this=0x19f0fc80) at src/yb/cdc/cdc_service.pb.cc:5244
#3  0x00007fda1f8952b3 in yb::cdc::CDCReadRpc::Finished (this=0x19f0fb10, status=...) at ../../ent/src/yb/cdc/cdc_rpc.cc:171
#4  0x00007fda1f8938d1 in operator()<yb::Status::OK&, void> (__object=<optimized out>, this=<optimized out>)
    at /home/yugabyte/yb-software/yugabyte-2.0.11.0-b1-centos-x86_64/linuxbrew-xxxxxxxxxxxxx/Cellar/gcc/5.5.0_4/include/c++/5.5.0/functional:600
#5  __call<void, 0ul, 1ul> (__args=<optimized out>, this=<optimized out>) at /home/yugabyte/yb-software/yugabyte-2.0.11.0-b1-centos-x86_64/linuxbrew-xxxxxxxxxxxxx/Cellar/gcc/5.5.0_4/include/c++/5.5.0/functional:1074
#6  operator()<, void> (this=<optimized out>) at /home/yugabyte/yb-software/yugabyte-2.0.11.0-b1-centos-x86_64/linuxbrew-xxxxxxxxxxxxx/Cellar/gcc/5.5.0_4/include/c++/5.5.0/functional:1133
#7  std::_Function_handler<void (), std::_Bind<std::_Mem_fn<void (yb::cdc::CDCReadRpc::*)(yb::Status const&)> (yb::cdc::CDCReadRpc*, yb::Status::OK)> >::_M_invoke(std::_Any_data const&) (__functor=...)
    at /home/yugabyte/yb-software/yugabyte-2.0.11.0-b1-centos-x86_64/linuxbrew-xxxxxxxxxxxxx/Cellar/gcc/5.5.0_4/include/c++/5.5.0/functional:1871
#8  0x00007fda199f5f2e in operator() (this=<optimized out>) at /home/yugabyte/yb-software/yugabyte-2.0.11.0-b1-centos-x86_64/linuxbrew-xxxxxxxxxxxxx/Cellar/gcc/5.5.0_4/include/c++/5.5.0/functional:2267
#9  yb::rpc::OutboundCall::InvokeCallbackSync (this=0x3c350250) at ../../src/yb/rpc/outbound_call.cc:384
#10 0x00007fda199f6149 in yb::rpc::InvokeCallbackTask::Run (this=<optimized out>) at ../../src/yb/rpc/outbound_call.cc:165
#11 0x00007fda19a4d8e8 in yb::rpc::(anonymous namespace)::Worker::Execute (this=<optimized out>) at ../../src/yb/rpc/thread_pool.cc:99
#12 0x00007fda1801854f in operator() (this=0x203ab258) at /home/yugabyte/yb-software/yugabyte-2.0.11.0-b1-centos-x86_64/linuxbrew-xxxxxxxxxxxxx/Cellar/gcc/5.5.0_4/include/c++/5.5.0/functional:2267
#13 yb::Thread::SuperviseThread (arg=0x203ab200) at ../../src/yb/util/thread.cc:739
#14 0x00007fda12ad7694 in start_thread (arg=0x7fd951d68700) at pthread_create.c:333
#15 0x00007fda1221441d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

**Comment by bmatican** [comment]
I had found this in some older TSAN test outputs, not sure if still relevant
> /var/lib/jenkins/jobs/github-yugabyte-db-centos-master-clang-tsan/builds/526/archive/build/tsan-clang-dynamic-ninja/yb-test-logs/tests-integration-tests__twodc-test/BatchSize__TwoDCTest_TestWalRetentionSet__1.log

```
WARNING: ThreadSanitizer: data race (pid=16746)
  Read of size 4 at 0x7b5401027188 by thread T689:
    #0 yb::cdc::GetChangesResponsePB::Clear() /net/centos-gcp-cloud-jenkins-slave-ff9/share/jenkins/workspace/github-yugabyte-db-centos-master-clang-tsan/build/tsan-clang-dynamic-ninja/src/yb/cdc/cdc_service.pb.cc:5240:21 (libcdc_servic
e_proto.so+0x45c3b)
    #1 google::protobuf::MessageLite::ParseFromCodedStream(google::protobuf::io::CodedInputStream*) <null> (libprotobuf.so.15+0x1280aa)
    #2 yb::pb_util::ParseFromArray(google::protobuf::MessageLite*, unsigned char const*, unsigned int) /net/centos-gcp-cloud-jenkins-slave-ff9/share/jenkins/workspace/github-yugabyte-db-centos-master-clang-tsan/build/tsan-clang-dynamic-ninja/../../src/yb/util/pb_util.cc:194:13 (libyb_util.so+0x32333e)
    #3 yb::rpc::OutboundCall::SetResponse(yb::rpc::CallResponse&&) /net/centos-gcp-cloud-jenkins-slave-ff9/share/jenkins/workspace/github-yugabyte-db-centos-master-clang-tsan/build/tsan-clang-dynamic-ninja/../../src/yb/rpc/outbound_call.cc:421:10 (libyrpc.so+0x188964)
    #4 yb::rpc::Connection::HandleCallResponse(yb::rpc::CallData*) /net/centos-gcp-cloud-jenkins-slave-ff9/share/jenkins/workspace/github-yugabyte-db-centos-master-clang-tsan/build/tsan-clang-dynamic-ninja/../../src/yb/rpc/connection.cc:313:9 (libyrpc.so+0x158140)
    #5 yb::rpc::YBOutboundConnectionContext::HandleCall(std::__1::shared_ptr<yb::rpc::Connection> const&, yb::rpc::CallData*) /net/centos-gcp-cloud-jenkins-slave-ff9/share/jenkins/workspace/github-yugabyte-db-centos-master-clang-tsan/build/tsan-clang-dynamic-ninja/../../src/yb/rpc/yb_rpc.cc:474:22 (libyrpc.so+0x21b121)
    #6 non-virtual thunk to yb::rpc::YBOutboundConnectionContext::HandleCall(std::__1::shared_ptr<yb::rpc::Connection> const&, yb::rpc::CallData*) /net/centos-gcp-cloud-jenkins-slave-ff9/share/jenkins/workspace/github-yugabyte-db-centos-master-clang-tsan/build/tsan-clang-dynamic-ninja/../../src/yb/rpc/yb_rpc.cc (libyrpc.so+0x21b179)
    #7 yb::rpc::BinaryCallParser::Parse(std::__1::shared_ptr<yb::rpc::Connection> const&, boost::container::small_vector<iovec, 4ul, boost::container::new_allocator<iovec> > const&, yb::StronglyTypedBool<yb::rpc::ReadBufferFull_Tag>) /net/centos-gcp-cloud-jenkins-slave-ff9/share/jenkins/workspace/github-yugabyte-db-centos-master-clang-tsan/build/tsan-clang-dynamic-ninja/../../src/yb/rpc/binary_call_parser.cc:85:7 (libyrpc.so+0x1504e1)
    #8 yb::rpc::YBOutboundConnectionContext::ProcessCalls(std::__1::shared_ptr<yb::rpc::Connection> const&, boost::container::small_vector<iovec, 4ul, boost::container::new_allocator<iovec> > const&, yb::StronglyTypedBool<yb::rpc::ReadBufferFull_Tag>) /net/centos-gcp-cloud-jenkins-slave-ff9/share/jenkins/workspace/github-yugabyte-db-centos-master-clang-tsan/build/tsan-clang-dynamic-ninja/../../src/yb/rpc/yb_rpc.cc:495:19 (libyrpc.so+0x21b641)
    #9 yb::rpc::Connection::ProcessReceived(boost::container::small_vector<iovec, 4ul, boost::container::new_allocator<iovec> > const&, yb::StronglyTypedBool<yb::rpc::ReadBufferFull_Tag>) /net/centos-gcp-cloud-jenkins-slave-ff9/share/jenkins/workspace/github-yugabyte-db-centos-master-clang-tsan/build/tsan-clang-dynamic-ninja/../../src/yb/rpc/connection.cc:276:27 (libyrpc.so+0x157dd3)
    #10 yb::rpc::TcpStream::TryProcessReceived() /net/centos-gcp-cloud-jenkins-slave-ff9/share/jenkins/workspace/github-yugabyte-db-centos-master-clang-tsan/build/tsan-clang-dynamic-ninja/../../src/yb/rpc/tcp_stream.cc:361:17 (libyrpc.so+0x20de18)
    #11 yb::rpc::TcpStream::ReadHandler() /net/centos-gcp-cloud-jenkins-slave-ff9/share/jenkins/workspace/github-yugabyte-db-centos-master-clang-tsan/build/tsan-clang-dynamic-ninja/../../src/yb/rpc/tcp_stream.cc:310:31 (libyrpc.so+0x20d71d)
    #12 yb::rpc::TcpStream::Handler(ev::io&, int) /net/centos-gcp-cloud-jenkins-slave-ff9/share/jenkins/workspace/github-yugabyte-db-centos-master-clang-tsan/build/tsan-clang-dynamic-ninja/../../src/yb/rpc/tcp_stream.cc:258:14 (libyrpc.so+0x20d533)
    #13 void ev::base<ev_io, ev::io>::method_thunk<yb::rpc::TcpStream, &(yb::rpc::TcpStream::Handler(ev::io&, int))>(ev_loop*, ev_io*, int) /n/jenkins/thirdparty/yugabyte-thirdparty-2019-12-05T15_39_49/thirdparty/installed/common/include/ev++.h:479:7 (libyrpc.so+0x2101ea)
    #14 ev_invoke_pending <null> (libev.so.4+0x4b2a)
    #15 yb::rpc::Reactor::RunThread() /net/centos-gcp-cloud-jenkins-slave-ff9/share/jenkins/workspace/github-yugabyte-db-centos-master-clang-tsan/build/tsan-clang-dynamic-ninja/../../src/yb/rpc/reactor.cc:481:9 (libyrpc.so+0x1af0bc)
    #16 decltype(*(std::__1::forward<yb::rpc::Reactor*&>(fp0)).*fp()) std::__1::__invoke<void (yb::rpc::Reactor::*&)(), yb::rpc::Reactor*&, void>(void (yb::rpc::Reactor::*&)(), yb::rpc::Reactor*&) /n/jenkins/thirdparty/yugabyte-thirdparty-2019-12-05T15_39_49/thirdparty/installed/tsan/libcxx/include/c++/v1/type_traits:4286:1 (libyrpc.so+0x1bb453)
    #17 std::__1::__bind_return<void (yb::rpc::Reactor::*)(), std::__1::tuple<yb::rpc::Reactor*>, std::__1::tuple<>, __is_valid_bind_return<void (yb::rpc::Reactor::*)(), std::__1::tuple<yb::rpc::Reactor*>, std::__1::tuple<> >::value>::type std::__1::__apply_functor<void (yb::rpc::Reactor::*)(), std::__1::tuple<yb::rpc::Reactor*>, 0ul, std::__1::tuple<> >(void (yb::rpc::Reactor::*&)(), std::__1::tuple<yb::rpc::Reactor*>&, std::__1::__tuple_indices<0ul>, std::__1::tuple<>&&) /n/jenkins/thirdparty/yugabyte-thirdparty-2019-12-05T15_39_49/thirdparty/installed/tsan/libcxx/include/c++/v1/functional:2216 (libyrpc.so+0x1bb453)
    #18 std::__1::__bind_return<void (yb::rpc::Reactor::*)(), std::__1::tuple<yb::rpc::Reactor*>, std::__1::tuple<>, __is_valid_bind_return<void (yb::rpc::Reactor::*)(), std::__1::tuple<yb::rpc::Reactor*>, std::__1::tuple<> >::value>::type std::__1::__bind<void (yb::rpc::Reactor::* const&)(), yb::rpc::Reactor* const&>::operator()<>() /n/jenkins/thirdparty/yugabyte-thirdparty-2019-12-05T15_39_49/thirdparty/installed/tsan/libcxx/include/c++/v1/functional:2249 (libyrpc.so+0x1bb453)
    #19 decltype(std::__1::forward<std::__1::__bind<void (yb::rpc::Reactor::* const&)(), yb::rpc::Reactor* const&>&>(fp)()) std::__1::__invoke<std::__1::__bind<void (yb::rpc::Reactor::* const&)(), yb::rpc::Reactor* const&>&>(std::__1::__bind<void (yb::rpc::Reactor::* const&)(), yb::rpc::Reactor* const&>&) /n/jenkins/thirdparty/yugabyte-thirdparty-2019-12-05T15_39_49/thirdparty/installed/tsan/libcxx/include/c++/v1/type_traits:4345 (libyrpc.so+0x1bb453)
    #20 void std::__1::__invoke_void_return_wrapper<void>::__call<std::__1::__bind<void (yb::rpc::Reactor::* const&)(), yb::rpc::Reactor* const&>&>(std::__1::__bind<void (yb::rpc::Reactor::* const&)(), yb::rpc::Reactor* const&>&) /n/jenkins/thirdparty/yugabyte-thirdparty-2019-12-05T15_39_49/thirdparty/installed/tsan/libcxx/include/c++/v1/__functional_base:349 (libyrpc.so+0x1bb453)
    #21 std::__1::__function::__func<std::__1::__bind<void (yb::rpc::Reactor::* const&)(), yb::rpc::Reactor* const&>, std::__1::allocator<std::__1::__bind<void (yb::rpc::Reactor::* const&)(), yb::rpc::Reactor* const&> >, void ()>::operator()() /n/jenkins/thirdparty/yugabyte-thirdparty-2019-12-05T15_39_49/thirdparty/installed/tsan/libcxx/include/c++/v1/functional:1562:12 (libyrpc.so+0x1bb35d)
    #22 std::__1::function<void ()>::operator()() const /n/jenkins/thirdparty/yugabyte-thirdparty-2019-12-05T15_39_49/thirdparty/installed/tsan/libcxx/include/c++/v1/functional:1913:12 (libyb-redis.so+0xe6314)
    #23 yb::Thread::SuperviseThread(void*) /net/centos-gcp-cloud-jenkins-slave-ff9/share/jenkins/workspace/github-yugabyte-db-centos-master-clang-tsan/build/tsan-clang-dynamic-ninja/../../src/yb/util/thread.cc:741:3 (libyb_util.so+0x36b8e9)

Previous write of size 4 at 0x7b5401027188 by thread T715:
    #0 google::protobuf::internal::HasBits<1ul>::Clear() /n/jenkins/thirdparty/yugabyte-thirdparty-2019-12-05T15_39_49/thirdparty/installed/tsan/include/google/protobuf/has_bits.h:47:5 (libcdc_service_proto.so+0x45d49)
    #1 yb::cdc::GetChangesResponsePB::Clear() /net/centos-gcp-cloud-jenkins-slave-ff9/share/jenkins/workspace/github-yugabyte-db-centos-master-clang-tsan/build/tsan-clang-dynamic-ninja/src/yb/cdc/cdc_service.pb.cc:5253 (libcdc_service_proto.so+0x45d49)
    #2 yb::cdc::CDCReadRpc::Finished(yb::Status const&) /net/centos-gcp-cloud-jenkins-slave-ff9/share/jenkins/workspace/github-yugabyte-db-centos-master-clang-tsan/build/tsan-clang-dynamic-ninja/../../ent/src/yb/cdc/cdc_rpc.cc:171:13 (libcdc.so+0xcf2fa)
    #3 decltype(*(std::__1::forward<yb::cdc::CDCReadRpc*&>(fp0)).*fp(std::__1::forward<yb::Status::OK&>(fp1))) std::__1::__invoke<void (yb::cdc::CDCReadRpc::*&)(yb::Status const&), yb::cdc::CDCReadRpc*&, yb::Status::OK&, void>(void (yb::cdc::CDCReadRpc::*&)(yb::Status const&), yb::cdc::CDCReadRpc*&, yb::Status::OK&) /n/jenkins/thirdparty/yugabyte-thirdparty-2019-12-05T15_39_49/thirdparty/installed/tsan/libcxx/include/c++/v1/type_traits:4286:1 (libcdc.so+0xd0a0b)
    #4 std::__1::__bind_return<void (yb::cdc::CDCReadRpc::*)(yb::Status const&), std::__1::tuple<yb::cdc::CDCReadRpc*, yb::Status::OK>, std::__1::tuple<>, __is_valid_bind_return<void (yb::cdc::CDCReadRpc::*)(yb::Status const&), std::__1::tuple<yb::cdc::CDCReadRpc*, yb::Status::OK>, std::__1::tuple<> >::value>::type std::__1::__apply_functor<void (yb::cdc::CDCReadRpc::*)(yb::Status const&), std::__1::tuple<yb::cdc::CDCReadRpc*, yb::Status::OK>, 0ul, 1ul, std::__1::tuple<> >(void (yb::cdc::CDCReadRpc::*&)(yb::Status const&), std::__1::tuple<yb::cdc::CDCReadRpc*, yb::Status::OK>&, std::__1::__tuple_indices<0ul, 1ul>, std::__1::tuple<>&&) /n/jenkins/thirdparty/yugabyte-thirdparty-2019-12-05T15_39_49/thirdparty/installed/tsan/libcxx/include/c++/v1/functional:2216 (libcdc.so+0xd0a0b)
    #5 std::__1::__bind_return<void (yb::cdc::CDCReadRpc::*)(yb::Status const&), std::__1::tuple<yb::cdc::CDCReadRpc*, yb::Status::OK>, std::__1::tuple<>, __is_valid_bind_return<void (yb::cdc::CDCReadRpc::*)(yb::Status const&), std::__1::tuple<yb::cdc::CDCReadRpc*, yb::Status::OK>, std::__1::tuple<> >::value>::type std::__1::__bind<void (yb::cdc::CDCReadRpc::*)(yb::Status const&), yb::cdc::CDCReadRpc*, yb::Status::OK>::operator()<>() /n/jenkins/thirdparty/yugabyte-thirdparty-2019-12-05T15_39_49/thirdparty/installed/tsan/libcxx/include/c++/v1/functional:2249 (libcdc.so+0xd0a0b)
    #6 decltype(std::__1::forward<std::__1::__bind<void (yb::cdc::CDCReadRpc::*)(yb::Status const&), yb::cdc::CDCReadRpc*, yb::Status::OK>&>(fp)()) std::__1::__invoke<std::__1::__bind<void (yb::cdc::CDCReadRpc::*)(yb::Status const&), yb::cdc::CDCReadRpc*, yb::Status::OK>&>(std::__1::__bind<void (yb::cdc::CDCReadRpc::*)(yb::Status const&), yb::cdc::CDCReadRpc*, yb::Status::OK>&) /n/jenkins/thirdparty/yugabyte-thirdparty-2019-12-05T15_39_49/thirdparty/installed/tsan/libcxx/include/c++/v1/type_traits:4345 (libcdc.so+0xd0a0b)
    #7 void std::__1::__invoke_void_return_wrapper<void>::__call<std::__1::__bind<void (yb::cdc::CDCReadRpc::*)(yb::Status const&), yb::cdc::CDCReadRpc*, yb::Status::OK>&>(std::__1::__bind<void (yb::cdc::CDCReadRpc::*)(yb::Status const&), yb::cdc::CDCReadRpc*, yb::Status::OK>&) /n/jenkins/thirdparty/yugabyte-thirdparty-2019-12-05T15_39_49/thirdparty/installed/tsan/libcxx/include/c++/v1/__functional_base:349 (libcdc.so+0xd0a0b)
    #8 std::__1::__function::__func<std::__1::__bind<void (yb::cdc::CDCReadRpc::*)(yb::Status const&), yb::cdc::CDCReadRpc*, yb::Status::OK>, std::__1::allocator<std::__1::__bind<void (yb::cdc::CDCReadRpc::*)(yb::Status const&), yb::cdc::CDCReadRpc*, yb::Status::OK> >, void ()>::operator()() /n/jenkins/thirdparty/yugabyte-thirdparty-2019-12-05T15_39_49/thirdparty/installed/tsan/libcxx/include/c++/v1/functional:1562:12 (libcdc.so+0xd08fd)
    #9 std::__1::function<void ()>::operator()() const /n/jenkins/thirdparty/yugabyte-thirdparty-2019-12-05T15_39_49/thirdparty/installed/tsan/libcxx/include/c++/v1/functional:1913:12 (libyb-redis.so+0xe6314)
    #10 yb::rpc::OutboundCall::InvokeCallbackSync() /net/centos-gcp-cloud-jenkins-slave-ff9/share/jenkins/workspace/github-yugabyte-db-centos-master-clang-tsan/build/tsan-clang-dynamic-ninja/../../src/yb/rpc/outbound_call.cc:384:3 (libyrpc.so+0x185caa)
    #11 yb::rpc::InvokeCallbackTask::Run() /net/centos-gcp-cloud-jenkins-slave-ff9/share/jenkins/workspace/github-yugabyte-db-centos-master-clang-tsan/build/tsan-clang-dynamic-ninja/../../src/yb/rpc/outbound_call.cc:165:10 (libyrpc.so+0x185c36)
    #12 yb::rpc::(anonymous namespace)::Worker::Execute() /net/centos-gcp-cloud-jenkins-slave-ff9/share/jenkins/workspace/github-yugabyte-db-centos-master-clang-tsan/build/tsan-clang-dynamic-ninja/../../src/yb/rpc/thread_pool.cc:99:15 (libyrpc.so+0x213f10)
    #13 decltype(*(std::__1::forward<yb::rpc::(anonymous namespace)::Worker*&>(fp0)).*fp()) std::__1::__invoke<void (yb::rpc::(anonymous namespace)::Worker::*&)(), yb::rpc::(anonymous namespace)::Worker*&, void>(void (yb::rpc::(anonymous namespace)::Worker::*&)(), yb::rpc::(anonymous namespace)::Worker*&) /n/jenkins/thirdparty/yugabyte-thirdparty-2019-12-05T15_39_49/thirdparty/installed/tsan/libcxx/include/c++/v1/type_traits:4286:1 (libyrpc.so+0x214273)
    #14 std::__1::__bind_return<void (yb::rpc::(anonymous namespace)::Worker::*)(), std::__1::tuple<yb::rpc::(anonymous namespace)::Worker*>, std::__1::tuple<>, __is_valid_bind_return<void (yb::rpc::(anonymous namespace)::Worker::*)(), std::__1::tuple<yb::rpc::(anonymous namespace)::Worker*>, std::__1::tuple<> >::value>::type std::__1::__apply_functor<void (yb::rpc::(anonymous namespace)::Worker::*)(), std::__1::tuple<yb::rpc::(anonymous namespace)::Worker*>, 0ul, std::__1::tuple<> >(void (yb::rpc::(anonymous namespace)::Worker::*&)(), std::__1::tuple<yb::rpc::(anonymous namespace)::Worker*>&, std::__1::__tuple_indices<0ul>, std::__1::tuple<>&&) /n/jenkins/thirdparty/yugabyte-thirdparty-2019-12-05T15_39_49/thirdparty/installed/tsan/libcxx/include/c++/v1/functional:2216 (libyrpc.so+0x214273)
    #15 std::__1::__bind_return<void (yb::rpc::(anonymous namespace)::Worker::*)(), std::__1::tuple<yb::rpc::(anonymous namespace)::Worker*>, std::__1::tuple<>, __is_valid_bind_return<void (yb::rpc::(anonymous namespace)::Worker::*)(), std::__1::tuple<yb::rpc::(anonymous namespace)::Worker*>, std::__1::tuple<> >::value>::type std::__1::__bind<void (yb::rpc::(anonymous namespace)::Worker::* const&)(), yb::rpc::(anonymous namespace)::Worker* const&>::operator()<>() /n/jenkins/thirdparty/yugabyte-thirdparty-2019-12-05T15_39_49/thirdparty/installed/tsan/libcxx/include/c++/v1/functional:2249 (libyrpc.so+0x214273)
    #16 decltype(std::__1::forward<std::__1::__bind<void (yb::rpc::(anonymous namespace)::Worker::* const&)(), yb::rpc::(anonymous namespace)::Worker* const&>&>(fp)()) std::__1::__invoke<std::__1::__bind<void (yb::rpc::(anonymous namespace)::Worker::* const&)(), yb::rpc::(anonymous namespace)::Worker* const&>&>(std::__1::__bind<void (yb::rpc::(anonymous namespace)::Worker::* const&)(), yb::rpc::(anonymous namespace)::Worker* const&>&) /n/jenkins/thirdparty/yugabyte-thirdparty-2019-12-05T15_39_49/thirdparty/installed/tsan/libcxx/include/c++/v1/type_traits:4345 (libyrpc.so+0x214273)
    #17 void std::__1::__invoke_void_return_wrapper<void>::__call<std::__1::__bind<void (yb::rpc::(anonymous namespace)::Worker::* const&)(), yb::rpc::(anonymous namespace)::Worker* const&>&>(std::__1::__bind<void (yb::rpc::(anonymous namespace)::Worker::* const&)(), yb::rpc::(anonymous namespace)::Worker* const&>&) /n/jenkins/thirdparty/yugabyte-thirdparty-2019-12-05T15_39_49/thirdparty/installed/tsan/libcxx/include/c++/v1/__functional_base:349 (libyrpc.so+0x214273)
    #18 std::__1::__function::__func<std::__1::__bind<void (yb::rpc::(anonymous namespace)::Worker::* const&)(), yb::rpc::(anonymous namespace)::Worker* const&>, std::__1::allocator<std::__1::__bind<void (yb::rpc::(anonymous namespace)::Worker::* const&)(), yb::rpc::(anonymous namespace)::Worker* const&> >, void ()>::operator()() /n/jenkins/thirdparty/yugabyte-thirdparty-2019-12-05T15_39_49/thirdparty/installed/tsan/libcxx/include/c++/v1/functional:1562:12 (libyrpc.so+0x21417d)
    #19 std::__1::function<void ()>::operator()() const /n/jenkins/thirdparty/yugabyte-thirdparty-2019-12-05T15_39_49/thirdparty/installed/tsan/libcxx/include/c++/v1/functional:1913:12 (libyb-redis.so+0xe6314)
    #20 yb::Thread::SuperviseThread(void*) /net/centos-gcp-cloud-jenkins-slave-ff9/share/jenkins/workspace/github-yugabyte-db-centos-master-clang-tsan/build/tsan-clang-dynamic-ninja/../../src/yb/util/thread.cc:741:3 (libyb_util.so+0x36b8e9)
```

**Comment by nspiegelberg** [comment]
Note: While this crash occured on the "Test Producer" cluster, it was configured for bi-directional replication.  The actual crash occurred within it's CDC Consumer logic, calling GetChanges to the "Test Consumer" cluster.

**Comment by ndeodhar** [comment]
Can we close this issue @nspiegelberg ?

**Comment by nspiegelberg** [comment]
Fixed with above commit
