### ISSUE TITLE
Peer::Close() can get stuck waiting for the pending request semaphore

### ISSUE THREAD

**Issue by mbautin** [YugaByte/yugabyte-db#350]
The following issue was observed on a client request.

GetTableLocations(system_redis.redis, hash_code: NaN, 5) failed: timed out after deadline expired: GetTableLocations(system_redis.redis, hash_code: NaN, 5) passed its deadline 7313896.654s (now: 7313897.511s): Remote error (yb/rpc/outbound_call.cc:376): Service unavailable (yb/rpc/service_pool.cc:170): GetTableLocations request on yb.master.MasterService from ip_address:53662 dropped due to backpressure. The service queue is full, it has 1000 items.

The master in question got into a state where it was not able to process any MasterService or Consensus requests.

List of master threads: https://gist.githubusercontent.com/mbautin/9b018f4ea37ee31aa80fed1b7f9f947f/raw

Looking at the thread dump of one of the threads waiting for the Raft state lock, we can see the thread holding that lock:
```
(gdb) where
#0  __lll_lock_wait () at ../sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:135
#1  0x00007f409cd146e3 in __GI___pthread_mutex_lock (mutex=0x183a4f0) at ../nptl/pthread_mutex_lock.c:80
#2  0x00007f40a5b97b7e in __gthread_mutex_lock (__mutex=0x183a4f0) at /n/jenkins/linuxbrew/linuxbrew_2018-03-16T16_38_10/Cellar/gcc/5.5.0/include/c++/5.5.0/x86_64-unknown-linux-gnu/bits/gthr-default.h:748
#3  lock (this=0x183a4f0) at /n/jenkins/linuxbrew/linuxbrew_2018-03-16T16_38_10/Cellar/gcc/5.5.0/include/c++/5.5.0/mutex:135
#4  lock (this=<synthetic pointer>) at /n/jenkins/linuxbrew/linuxbrew_2018-03-16T16_38_10/Cellar/gcc/5.5.0/include/c++/5.5.0/mutex:485
#5  unique_lock (__m=..., this=<synthetic pointer>) at /n/jenkins/linuxbrew/linuxbrew_2018-03-16T16_38_10/Cellar/gcc/5.5.0/include/c++/5.5.0/mutex:415
#6  yb::consensus::ReplicaState::LockForRead (this=0x183a4e0, lock=lock@entry=0x7f4098a933f0) at ../../../../../src/yb/consensus/replica_state.cc:142
#7  0x00007f40a5b7dbac in yb::consensus::RaftConsensus::GetLastOpId (this=0x183a1b0, type=yb::consensus::COMMITTED_OPID, id=0x7f4098a934e0) at ../../../../../src/yb/consensus/raft_consensus.cc:2689
#8  0x00007f40a739d712 in yb::tablet::TabletPeer::GetEarliestNeededLogIndex (this=this@entry=0x183a000, min_index=min_index@entry=0x7f4098a93560) at ../../../../../src/yb/tablet/tablet_peer.cc:619
#9  0x00007f40a739d9c8 in yb::tablet::TabletPeer::GetGCableDataSize (this=0x183a000, retention_size=retention_size@entry=0x7f4098a935a0) at ../../../../../src/yb/tablet/tablet_peer.cc:641
#10 0x00007f40a73958d4 in yb::tablet::LogGCOp::UpdateStats (this=0x2c92e00, stats=0x1a15d88) at ../../../../../src/yb/tablet/tablet_peer_mm_ops.cc:80
#11 0x00007f40a73c3ff6 in yb::MaintenanceManager::FindBestOp (this=this@entry=0x121e100) at ../../../../../src/yb/tablet/maintenance_manager.cc:290
#12 0x00007f40a73c5d92 in yb::MaintenanceManager::RunSchedulerThread (this=0x121e100) at ../../../../../src/yb/tablet/maintenance_manager.cc:216
#13 0x00007f40a1551156 in operator() (this=0x14d0438) at /n/jenkins/linuxbrew/linuxbrew_2018-03-16T16_38_10/Cellar/gcc/5.5.0/include/c++/5.5.0/functional:2267
#14 yb::Thread::SuperviseThread (arg=<optimized out>) at ../../../../../src/yb/util/thread.cc:602
#15 0x00007f409cd12694 in start_thread (arg=0x7f4098a94700) at pthread_create.c:333
#16 0x00007f409ca543cd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
(gdb) frame 4
#4  lock (this=<synthetic pointer>) at /n/jenkins/linuxbrew/linuxbrew_2018-03-16T16_38_10/Cellar/gcc/5.5.0/include/c++/5.5.0/mutex:485
485     /n/jenkins/linuxbrew/linuxbrew_2018-03-16T16_38_10/Cellar/gcc/5.5.0/include/c++/5.5.0/mutex: No such file or directory.
(gdb) locals
Undefined command: "locals".  Try "help".
(gdb) local
Undefined command: "local".  Try "help".
(gdb) info locals
No locals.
(gdb) frame 3
#3  lock (this=0x183a4f0) at /n/jenkins/linuxbrew/linuxbrew_2018-03-16T16_38_10/Cellar/gcc/5.5.0/include/c++/5.5.0/mutex:135
135     in /n/jenkins/linuxbrew/linuxbrew_2018-03-16T16_38_10/Cellar/gcc/5.5.0/include/c++/5.5.0/mutex
(gdb) info locals
No locals.
(gdb) print _M_mutex
$1 = {__data = {__lock = 2, __count = 0, __owner = 27886, __nusers = 1, __kind = 0, __spins = 0, __elision = 0, __list = {__prev = 0x0, __next = 0x0}}, __size = "\002\000\000\000\000\000\000\000\356l\000\000\001", '\000' <repeats 26 times>, __align = 2}
(gdb)
```
The second thread is handling `Peer::Close` and is waiting for the semaphore:

```
(gdb) 
#0  0x00007f409cd1918a in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, futex_word=0x18e15b0) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
#1  do_futex_wait (sem=sem@entry=0x18e15b0, abstime=0x0) at sem_waitcommon.c:111
#2  0x00007f409cd19231 in __new_sem_wait_slow (sem=0x18e15b0, abstime=0x0) at sem_waitcommon.c:181
#3  0x00007f40a1470e92 in yb::Semaphore::Acquire (this=this@entry=0x18e15b0) at ../../../../../src/yb/util/semaphore.cc:55
#4  0x00007f40a5b4a565 in lock (this=0x18e15b0) at ../../../../../src/yb/util/semaphore.h:70
#5  lock_guard (__m=..., this=<synthetic pointer>) at /n/jenkins/linuxbrew/linuxbrew_2018-03-16T16_38_10/Cellar/gcc/5.5.0/include/c++/5.5.0/mutex:386
#6  yb::consensus::Peer::Close (this=0x18e1400) at ../../../../../src/yb/consensus/consensus_peers.cc:393
#7  0x00007f40a5b73159 in yb::consensus::PeerManager::Close (this=0x2cd4480) at ../../../../../src/yb/consensus/peer_manager.cc:128
#8  0x00007f40a5b7c324 in yb::consensus::RaftConsensus::BecomeReplicaUnlocked (this=this@entry=0x183a1b0) at ../../../../../src/yb/consensus/raft_consensus.cc:836
#9  0x00007f40a5b7d185 in yb::consensus::RaftConsensus::HandleTermAdvanceUnlocked (this=this@entry=0x183a1b0, new_term=new_term@entry=6) at ../../../../../src/yb/consensus/raft_consensus.cc:2821
#10 0x00007f40a5b7f6d1 in yb::consensus::RaftConsensus::NotifyTermChange (this=0x183a1b0, term=6) at ../../../../../src/yb/consensus/raft_consensus.cc:1015
#11 0x00007f40a5b57e34 in yb::consensus::PeerMessageQueue::NotifyObserversOfTermChangeTask (this=<optimized out>, term=6) at ../../../../../src/yb/consensus/consensus_queue.cc:1037
#12 0x00007f40a15549c4 in yb::ThreadPool::DispatchThread (this=0x17e2a00, permanent=false) at ../../../../../src/yb/util/threadpool.cc:608
#13 0x00007f40a1551156 in operator() (this=0x14d1f08) at /n/jenkins/linuxbrew/linuxbrew_2018-03-16T16_38_10/Cellar/gcc/5.5.0/include/c++/5.5.0/functional:2267
#14 yb::Thread::SuperviseThread (arg=<optimized out>) at ../../../../../src/yb/util/thread.cc:602
#15 0x00007f409cd12694 in start_thread (arg=0x7f40903a2700) at pthread_create.c:333
#16 0x00007f409ca543cd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
(gdb) 
```

This semaphore should be released when we receive a response from the peer, even if that response is a network error or a timeout. The time by which the response should be received has long passed. So we either failed to release the semaphore, or we never handled the response because it got stuck in one of the queues.

One possibility is that the thread running `Peer::Close()` is doing so in a Raft thread pool token, and that token is also needed to handle the response in `Peer::ProcessResponse()`. That's when the semaphore should be released but we never get to that point.

**Comment by hectorgcr** [comment]
We found a performance regression with commit https://github.com/YugaByte/yugabyte-db/commit/4f445a34a574f857ce9c520dfa4573eb472d91cf. Reverting it and reopening the issue.
