### ISSUE TITLE
[CDC] SIGSEGV in ProcessRecord encountered 

### ISSUE THREAD

**Issue by ajcaldera1** [yugabyte/yugabyte-db#3522]
Encountered during b23 testing:
```
#0  0x00007f5123160b70 in tc_newarray () from /home/yugabyte/yb-software/yugabyte-2.0.11.0-b23-centos-x86_64/lib/yb-thirdparty/libtcmalloc.so.4
(gdb) bt
#0  0x00007f5123160b70 in tc_newarray () from /home/yugabyte/yb-software/yugabyte-2.0.11.0-b23-centos-x86_64/lib/yb-thirdparty/libtcmalloc.so.4
#1  0x00007f511ea160c9 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_mutate(unsigned long, unsigned long, char const*, unsigned long) ()
   from /home/yugabyte/yb-software/yugabyte-2.0.11.0-b23-centos-x86_64/linuxbrew/lib/libstdc++.so.6
#2  0x00007f511ea17603 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_append(char const*, unsigned long) ()
   from /home/yugabyte/yb-software/yugabyte-2.0.11.0-b23-centos-x86_64/linuxbrew/lib/libstdc++.so.6
#3  0x00007f5122ab960e in append (__n=<optimized out>, __s=0x7f50812d8200 "    @     0x7f512b2eb4dd  yb::tserver::enterprise::CDCPoller::HandlePoll()", this=0x7f50812d8be0)
    at /home/yugabyte/yb-software/yugabyte-2.0.11.0-b23-centos-x86_64/linuxbrew-xxxxxxxxxxxx/Cellar/gcc/5.5.0_4/include/c++/5.5.0/bits/basic_string.h:1105
#4  StringAppendV (dst=0x7f50812d8be0, format=0x7f512373cf78 <yb::(anonymous namespace)::kStackTraceEntryFormat> "    @ %*p  %s", ap=ap@entry=0x7f50812d8648) at ../../../../../src/yb/gutil/stringprintf.cc:54
#5  0x00007f5122ab98e4 in StringAppendF (dst=dst@entry=0x7f50812d8be0, format=format@entry=0x7f512373cf78 <yb::(anonymous namespace)::kStackTraceEntryFormat> "    @ %*p  %s") at ../../../../../src/yb/gutil/stringprintf.cc:111
#6  0x00007f5123629a6d in yb::SymbolizeAddress (stack_trace_line_format=stack_trace_line_format@entry=yb::SHORT, pc=
    0x7f512b2eb4dd <yb::tserver::enterprise::CDCPoller::HandlePoll(yb::Status, std::shared_ptr<yb::cdc::GetChangesResponsePB>)+701>,
    pc@entry=0x7f512b2eb4de <yb::tserver::enterprise::CDCPoller::HandlePoll(yb::Status, std::shared_ptr<yb::cdc::GetChangesResponsePB>)+702>, buf=buf@entry=0x7f50812d8be0, global_backtrace_state=global_backtrace_state@entry=0x0)
    at ../../../../../src/yb/util/debug-util.cc:781
#7  0x00007f512362a80f in yb::SymbolizeAddress[abi:cxx11](void*, yb::StackTraceLineFormat) (
    pc=pc@entry=0x7f512b2eb4de <yb::tserver::enterprise::CDCPoller::HandlePoll(yb::Status, std::shared_ptr<yb::cdc::GetChangesResponsePB>)+702>, stack_trace_line_format=stack_trace_line_format@entry=yb::SHORT)
    at ../../../../../src/yb/util/debug-util.cc:857
#8  0x00007f512367c94b in yb::(anonymous namespace)::CustomGlogFailureWriter (data=<optimized out>, size=<optimized out>) at ../../../../../src/yb/util/logging.cc:192
#9  0x00007f512287ca4e in google::(anonymous namespace)::DumpStackFrameInfo(char const*, void*) () from /home/yugabyte/yb-software/yugabyte-2.0.11.0-b23-centos-x86_64/lib/yb-thirdparty/libglog.so.0
#10 0x00007f512287d20e in google::(anonymous namespace)::FailureSignalHandler(int, siginfo_t*, void*) () from /home/yugabyte/yb-software/yugabyte-2.0.11.0-b23-centos-x86_64/lib/yb-thirdparty/libglog.so.0
#11 <signal handler called>
#12 GetNoArena (this=0x623364201232314b) at /n/jenkins/thirdparty/yugabyte-thirdparty-2019-12-07T23_26_21/thirdparty/installed/uninstrumented/include/google/protobuf/arenastring.h:231
#13 key (this=0x6233642012323133) at ../../yb/cdc/cdc_service.pb.h:3781
#14 yb::tserver::enterprise::BatchedWriteImplementation::ProcessRecord (this=0x1c8be600, tablet_id=..., record=...) at ../../../../../ent/src/yb/tserver/twodc_write_implementations.cc:128
#15 0x00007f512b2e99fc in yb::tserver::enterprise::TwoDCOutputClient::TabletLookupCallbackFastTrack (this=0x60a0c60, record_idx=<optimized out>) at ../../../../../ent/src/yb/tserver/twodc_output_client.cc:226
#16 0x00007f512b2e9d9b in yb::tserver::enterprise::TwoDCOutputClient::ApplyChanges (this=<optimized out>, resp=<optimized out>) at ../../../../../ent/src/yb/tserver/twodc_output_client.cc:165
#17 0x00007f512b2eb4de in yb::tserver::enterprise::CDCPoller::HandlePoll (this=<optimized out>, status=..., resp=...) at ../../../../../ent/src/yb/tserver/cdc_poller.cc:170
#18 0x00007f512b2ede03 in operator()<yb::Status&, std::shared_ptr<yb::cdc::GetChangesResponsePB>&, void> (__object=0xb86f390, this=0x2b07f5a8)
    at /home/yugabyte/yb-software/yugabyte-2.0.11.0-b23-centos-x86_64/linuxbrew-xxxxxxxxxxxx/Cellar/gcc/5.5.0_4/include/c++/5.5.0/functional:600
#19 __call<void, 0ul, 1ul, 2ul> (__args=<optimized out>, this=0x2b07f5a8) at /home/yugabyte/yb-software/yugabyte-2.0.11.0-b23-centos-x86_64/linuxbrew-xxxxxxxxxxxx/Cellar/gcc/5.5.0_4/include/c++/5.5.0/functional:1074
#20 operator()<, void> (this=0x2b07f5a8) at /home/yugabyte/yb-software/yugabyte-2.0.11.0-b23-centos-x86_64/linuxbrew-xxxxxxxxxxxx/Cellar/gcc/5.5.0_4/include/c++/5.5.0/functional:1133
#21 yb::RunnableImpl<std::_Bind<std::_Mem_fn<void (yb::tserver::enterprise::CDCPoller::*)(yb::Status, std::shared_ptr<yb::cdc::GetChangesResponsePB>)> (yb::tserver::enterprise::CDCPoller*, yb::Status, std::shared_ptr<yb::cdc::GetChangesResponsePB>)> >::Run() (this=0x2b07f5a0) at ../../../../../src/yb/util/threadpool.h:77
#22 0x00007f512370d704 in yb::ThreadPool::DispatchThread (this=0x81fda00, permanent=false) at ../../../../../src/yb/util/threadpool.cc:608
---Type <return> to continue, or q <return> to quit---
#23 0x00007f5123709e0f in operator() (this=0x16a8b378) at /home/yugabyte/yb-software/yugabyte-2.0.11.0-b23-centos-x86_64/linuxbrew-xxxxxxxxxxxx/Cellar/gcc/5.5.0_4/include/c++/5.5.0/functional:2267
#24 yb::Thread::SuperviseThread (arg=0x16a8b320) at ../../../../../src/yb/util/thread.cc:739
#25 0x00007f511e1c8694 in start_thread (arg=0x7f50812db700) at pthread_create.c:333
#26 0x00007f511d90541d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

**Comment by ajcaldera1** [comment]
I encountered another instance of this crash with a slightly different stack. Seems still to be entangled with SetNoArena/GetNoArena.
```
#0  SetNoArena (default_value=<optimized out>, value=..., this=<optimized out>) at /n/jenkins/thirdparty/yugabyte-thirdparty-2019-12-07T23_26_21/thirdparty/installed/uninstrumented/include/google/protobuf/arenastring.h:212
#1  set_key (value=..., this=<optimized out>) at ../../yb/docdb/docdb.pb.h:542
#2  yb::tserver::enterprise::BatchedWriteImplementation::ProcessRecord (this=0x19a8b300, tablet_id=..., record=...) at ../../../../../ent/src/yb/tserver/twodc_write_implementations.cc:128
#3  0x00007f026ae699fc in yb::tserver::enterprise::TwoDCOutputClient::TabletLookupCallbackFastTrack (this=0x842c420, record_idx=<optimized out>) at ../../../../../ent/src/yb/tserver/twodc_output_client.cc:226
#4  0x00007f026ae69d9b in yb::tserver::enterprise::TwoDCOutputClient::ApplyChanges (this=<optimized out>, resp=<optimized out>) at ../../../../../ent/src/yb/tserver/twodc_output_client.cc:165
#5  0x00007f026ae6b4de in yb::tserver::enterprise::CDCPoller::HandlePoll (this=<optimized out>, status=..., resp=...) at ../../../../../ent/src/yb/tserver/cdc_poller.cc:170
#6  0x00007f026ae6de03 in operator()<yb::Status&, std::shared_ptr<yb::cdc::GetChangesResponsePB>&, void> (__object=0x1761d210, this=0x459f6928)
    at /home/yugabyte/yb-software/yugabyte-2.0.11.0-b23-centos-x86_64/linuxbrew-xxxxxxxxxxxx/Cellar/gcc/5.5.0_4/include/c++/5.5.0/functional:600
#7  __call<void, 0ul, 1ul, 2ul> (__args=<optimized out>, this=0x459f6928) at /home/yugabyte/yb-software/yugabyte-2.0.11.0-b23-centos-x86_64/linuxbrew-xxxxxxxxxxxx/Cellar/gcc/5.5.0_4/include/c++/5.5.0/functional:1074
#8  operator()<, void> (this=0x459f6928) at /home/yugabyte/yb-software/yugabyte-2.0.11.0-b23-centos-x86_64/linuxbrew-xxxxxxxxxxxx/Cellar/gcc/5.5.0_4/include/c++/5.5.0/functional:1133
#9  yb::RunnableImpl<std::_Bind<std::_Mem_fn<void (yb::tserver::enterprise::CDCPoller::*)(yb::Status, std::shared_ptr<yb::cdc::GetChangesResponsePB>)> (yb::tserver::enterprise::CDCPoller*, yb::Status, std::shared_ptr<yb::cdc::GetChangesResponsePB>)> >::Run() (this=0x459f6920) at ../../../../../src/yb/util/threadpool.h:77
#10 0x00007f026328d704 in yb::ThreadPool::DispatchThread (this=0x4244400, permanent=false) at ../../../../../src/yb/util/threadpool.cc:608
#11 0x00007f0263289e0f in operator() (this=0x394e7378) at /home/yugabyte/yb-software/yugabyte-2.0.11.0-b23-centos-x86_64/linuxbrew-xxxxxxxxxxxx/Cellar/gcc/5.5.0_4/include/c++/5.5.0/functional:2267
#12 yb::Thread::SuperviseThread (arg=0x394e7320) at ../../../../../src/yb/util/thread.cc:739
#13 0x00007f025dd48694 in start_thread (arg=0x7f01ced30700) at pthread_create.c:333
#14 0x00007f025d48541d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

**Comment by bmatican** [comment]
Managed to repro this in house finally thanks to @jiaolongxue, adding some stacks

STACK1
```
Core was generated by `/home/yugabyte/tserver/bin/yb-tserver --flagfile /home/yugabyte/tserver/conf/se'.
Program terminated with signal 11, Segmentation fault.
#0  MessageSize (value=...) at /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20200707012818-49ca690c1f-centos/installed/uninstrumented/include/google/protobuf/wire_format_lite_inl.h:1020
1020	/opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20200707012818-49ca690c1f-centos/installed/uninstrumented/include/google/protobuf/wire_format_lite_inl.h: No such file or directory.
(gdb) bt
#0  MessageSize (value=...) at /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20200707012818-49ca690c1f-centos/installed/uninstrumented/include/google/protobuf/wire_format_lite_inl.h:1020
#1  yb::tserver::WriteRequestPB::ByteSizeLong (this=0x8641e10) at src/yb/tserver/tserver.pb.cc:2191
#2  0x00007f6d43f05bfb in ByteSize (this=<optimized out>) at /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20200707012818-49ca690c1f-centos/installed/uninstrumented/include/google/protobuf/message_lite.h:346
#3  yb::tserver::enterprise::BatchedWriteImplementation::ProcessRecord (this=0x4232ac0, tablet_id=..., record=...) at ../../ent/src/yb/tserver/twodc_write_implementations.cc:115
#4  0x00007f6d43f0011b in yb::tserver::enterprise::TwoDCOutputClient::TabletLookupCallback (this=0x9de18c0, record_idx=<optimized out>, tablet=...) at ../../ent/src/yb/tserver/twodc_output_client.cc:217
#5  0x00007f6d40fedeeb in operator() (__args#0=..., this=0xd5f2000) at /home/yugabyte/yb-software/yugabyte-2.2.4.0-b6-centos-x86_64/linuxbrew-xxxxxxxxxxxxxx/Cellar/gcc/5.5.0_4/include/c++/5.5.0/functional:2267
#6  yb::client::internal::MetaCache::ProcessTabletLocations (this=<optimized out>, locations=..., partition_group_start=partition_group_start@entry=0xd426228, request_no=<optimized out>) at ../../src/yb/client/meta_cache.cc:921
#7  0x00007f6d40ffdcc0 in yb::client::internal::LookupRpc::DoFinished<yb::master::GetTableLocationsResponsePB> (this=this@entry=0xd426170, status=..., resp=..., partition_group_start=partition_group_start@entry=0xd426228)
    at ../../src/yb/client/meta_cache.cc:741
#8  0x00007f6d40ffe0e9 in yb::client::internal::LookupByKeyRpc::Finished (this=0xd426170, status=...) at ../../src/yb/client/meta_cache.cc:1249
#9  0x00007f6d40fef071 in operator()<yb::Status::OK&, void> (__object=<optimized out>, this=<optimized out>) at /home/yugabyte/yb-software/yugabyte-2.2.4.0-b6-centos-x86_64/linuxbrew-xxxxxxxxxxxxxx/Cellar/gcc/5.5.0_4/include/c++/5.5.0/functional:600
#10 __call<void, 0ul, 1ul> (__args=<optimized out>, this=<optimized out>) at /home/yugabyte/yb-software/yugabyte-2.2.4.0-b6-centos-x86_64/linuxbrew-xxxxxxxxxxxxxx/Cellar/gcc/5.5.0_4/include/c++/5.5.0/functional:1074
#11 operator()<, void> (this=<optimized out>) at /home/yugabyte/yb-software/yugabyte-2.2.4.0-b6-centos-x86_64/linuxbrew-xxxxxxxxxxxxxx/Cellar/gcc/5.5.0_4/include/c++/5.5.0/functional:1133
#12 std::_Function_handler<void (), std::_Bind<std::_Mem_fn<void (yb::client::internal::LookupByKeyRpc::*)(yb::Status const&)> (yb::client::internal::LookupByKeyRpc*, yb::Status::OK)> >::_M_invoke(std::_Any_data const&) (__functor=...)
    at /home/yugabyte/yb-software/yugabyte-2.2.4.0-b6-centos-x86_64/linuxbrew-xxxxxxxxxxxxxx/Cellar/gcc/5.5.0_4/include/c++/5.5.0/functional:1871
#13 0x00007f6d3c504bae in operator() (this=<optimized out>) at /home/yugabyte/yb-software/yugabyte-2.2.4.0-b6-centos-x86_64/linuxbrew-xxxxxxxxxxxxxx/Cellar/gcc/5.5.0_4/include/c++/5.5.0/functional:2267
#14 yb::rpc::OutboundCall::InvokeCallbackSync (this=0x94b0250) at ../../src/yb/rpc/outbound_call.cc:384
#15 0x00007f6d3c504dc9 in yb::rpc::InvokeCallbackTask::Run (this=<optimized out>) at ../../src/yb/rpc/outbound_call.cc:165
#16 0x00007f6d3c5594a8 in yb::rpc::(anonymous namespace)::Worker::Execute (this=<optimized out>) at ../../src/yb/rpc/thread_pool.cc:100
#17 0x00007f6d3ad8b03f in operator() (this=0xb9df138) at /home/yugabyte/yb-software/yugabyte-2.2.4.0-b6-centos-x86_64/linuxbrew-xxxxxxxxxxxxxx/Cellar/gcc/5.5.0_4/include/c++/5.5.0/functional:2267
#18 yb::Thread::SuperviseThread (arg=0xb9df0e0) at ../../src/yb/util/thread.cc:759
#19 0x00007f6d355a7694 in start_thread (arg=0x7f6c51f2b700) at pthread_create.c:333
#20 0x00007f6d34ce441d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

STACK2
```
Core was generated by `/home/yugabyte/tserver/bin/yb-tserver --flagfile /home/yugabyte/tserver/conf/se'.
Program terminated with signal 11, Segmentation fault.
#0  mutable_write_batch (this=<optimized out>) at src/yb/tserver/tserver.pb.h:3700
3700	src/yb/tserver/tserver.pb.h: No such file or directory.
(gdb) bt
#0  mutable_write_batch (this=<optimized out>) at src/yb/tserver/tserver.pb.h:3700
#1  yb::tserver::enterprise::BatchedWriteImplementation::ProcessRecord (this=0x46ec1c0, tablet_id=..., record=...) at ../../ent/src/yb/tserver/twodc_write_implementations.cc:125
#2  0x00007f9045e5911b in yb::tserver::enterprise::TwoDCOutputClient::TabletLookupCallback (this=0x4856000, record_idx=<optimized out>, tablet=...) at ../../ent/src/yb/tserver/twodc_output_client.cc:217
#3  0x00007f9042f4f2b4 in operator() (__args#0=..., this=<optimized out>) at /home/yugabyte/yb-software/yugabyte-2.2.4.0-b6-centos-x86_64/linuxbrew-xxxxxxxxxxxxxx/Cellar/gcc/5.5.0_4/include/c++/5.5.0/functional:2267
#4  bool yb::client::internal::MetaCache::DoLookupTabletByKey<yb::SharedLock<boost::shared_mutex> >(yb::client::YBTable const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::chrono::time_point<yb::CoarseMonoClock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > >, std::function<void (yb::Result<scoped_refptr<yb::client::internal::RemoteTablet> > const&)>*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const**)::{lambda()#1}::operator()() const (__closure=__closure@entry=0x7f8fbd4b4200) at ../../src/yb/client/meta_cache.cc:1331
#5  0x00007f9042f54a5f in ~ScopeExitLambda (this=0x7f8fbd4b4200, __in_chrg=<optimized out>) at ../../src/yb/util/scope_exit.h:34
#6  yb::client::internal::MetaCache::DoLookupTabletByKey<yb::SharedLock<boost::shared_mutex> >(yb::client::YBTable const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::chrono::time_point<yb::CoarseMonoClock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > >, std::function<void (yb::Result<scoped_refptr<yb::client::internal::RemoteTablet> > const&)>*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const**) (
    this=this@entry=0x191b500, table=table@entry=0x46eab00, partition_start=..., deadline=..., callback=callback@entry=0x7f8fbd4b43f0, partition_group_start=partition_group_start@entry=0x7f8fbd4b4330) at ../../src/yb/client/meta_cache.cc:1333
#7  0x00007f9042f443c1 in yb::client::internal::MetaCache::LookupTabletByKey(yb::client::YBTable const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::chrono::time_point<yb::CoarseMonoClock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > >, std::function<void (yb::Result<scoped_refptr<yb::client::internal::RemoteTablet> > const&)>) (this=0x191b500, table=0x46eab00, partition_key=..., deadline=..., callback=...)
    at ../../src/yb/client/meta_cache.cc:1396
#8  0x00007f9042ed1ca6 in yb::client::YBClient::LookupTabletByKey(yb::client::YBTable const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::chrono::time_point<yb::CoarseMonoClock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > >, std::function<void (yb::Result<scoped_refptr<yb::client::internal::RemoteTablet> > const&)>) (this=<optimized out>, table=<optimized out>, partition_key=..., deadline=..., deadline@entry=..., callback=...)
    at ../../src/yb/client/client.cc:1429
#9  0x00007f9045e58af9 in yb::tserver::enterprise::TwoDCOutputClient::ApplyChanges (this=<optimized out>, poller_resp=<optimized out>) at ../../ent/src/yb/tserver/twodc_output_client.cc:169
#10 0x00007f9045e5a121 in yb::tserver::enterprise::CDCPoller::HandlePoll (this=0x4854010, status=..., resp=...) at ../../ent/src/yb/tserver/cdc_poller.cc:187
#11 0x00007f9045e5ce43 in operator()<yb::Status&, std::shared_ptr<yb::cdc::GetChangesResponsePB>&, void> (__object=0x4854010, this=0x4e5b5a8)
    at /home/yugabyte/yb-software/yugabyte-2.2.4.0-b6-centos-x86_64/linuxbrew-xxxxxxxxxxxxxx/Cellar/gcc/5.5.0_4/include/c++/5.5.0/functional:600
#12 __call<void, 0ul, 1ul, 2ul> (__args=<optimized out>, this=0x4e5b5a8) at /home/yugabyte/yb-software/yugabyte-2.2.4.0-b6-centos-x86_64/linuxbrew-xxxxxxxxxxxxxx/Cellar/gcc/5.5.0_4/include/c++/5.5.0/functional:1074
#13 operator()<, void> (this=0x4e5b5a8) at /home/yugabyte/yb-software/yugabyte-2.2.4.0-b6-centos-x86_64/linuxbrew-xxxxxxxxxxxxxx/Cellar/gcc/5.5.0_4/include/c++/5.5.0/functional:1133
#14 yb::RunnableImpl<std::_Bind<std::_Mem_fn<void (yb::tserver::enterprise::CDCPoller::*)(yb::Status, std::shared_ptr<yb::cdc::GetChangesResponsePB>)> (yb::tserver::enterprise::CDCPoller*, yb::Status, std::shared_ptr<yb::cdc::GetChangesResponsePB>)> >::Run() (this=0x4e5b5a0) at ../../src/yb/util/threadpool.h:77
#15 0x00007f903cce7864 in yb::ThreadPool::DispatchThread (this=0x1931200, permanent=false) at ../../src/yb/util/threadpool.cc:608
#16 0x00007f903cce403f in operator() (this=0x4776958) at /home/yugabyte/yb-software/yugabyte-2.2.4.0-b6-centos-x86_64/linuxbrew-xxxxxxxxxxxxxx/Cellar/gcc/5.5.0_4/include/c++/5.5.0/functional:2267
#17 yb::Thread::SuperviseThread (arg=0x4776900) at ../../src/yb/util/thread.cc:759
#18 0x00007f9037500694 in start_thread (arg=0x7f8fbd4b5700) at pthread_create.c:333
#19 0x00007f9036c3d41d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

**Comment by nspiegelberg** [comment]
Thanks to @jiaolongxue for finding the bug and submitting the initial fix!
