### ISSUE TITLE
[YCQL] Failed calling '+(int,anytype)'. Found too many matches for builtin function '+'

### ISSUE THREAD

**Issue by ddorian** [yugabyte/yugabyte-db#3559]
Reproduced from Java:

     @Test
      public void testPrepare() throws Exception {
        session.execute("CREATE TABLE dialog(userId INT PRIMARY KEY, unreadCount INT);");
        session.execute("insert into dialog (userId, unreadCount) values (100, 1);");
        String stmt = "UPDATE dialog SET unreadCount = unreadCount + ? WHERE userId = 10;";
        PreparedStatement prep = session.prepare(stmt);
        session.execute(prep.bind(2));
        assertQueryRowsUnordered("select * from dialog;", "Row[100, 3]");
        session.execute("drop table dialog;");
      }

Exception:

    [ERROR] testPrepare(org.yb.cql.TestPrepareExecute)  Time elapsed: 9.713 s  <<< ERROR!
    com.datastax.driver.core.exceptions.InvalidQueryException: 
    Invalid Function Call. Failed calling '+(int,anytype)'. Found too many matches for builtin function '+'
    UPDATE dialog SET unreadCount = unreadCount + ? WHERE userId = 10;
                                                ^
     (ql error -214)

**Comment by OlegLoginov** [comment]
Cassandra result for the test in the description:
```
com.datastax.driver.core.exceptions.InvalidQueryException: Invalid operation (unreadcount = unreadcount + ?) for non counter column unreadcount
	at com.datastax.driver.core.exceptions.InvalidQueryException.copy(InvalidQueryException.java:50)
	at com.datastax.driver.core.DriverThrowables.propagateCause(DriverThrowables.java:37)
	at com.datastax.driver.core.AbstractSession.prepare(AbstractSession.java:104)
	at com.domain.app.AppTest.testApp(AppTest.java:70)
```

**Comment by OlegLoginov** [comment]
New test - with 'counter' type:
```
   session.execute("CREATE TABLE dialog(userId INT PRIMARY KEY, unreadCount counter);");
    session.execute("UPDATE dialog SET unreadCount = unreadCount + 1 WHERE userId = 10;");
    String stmt = "UPDATE dialog SET unreadCount = unreadCount + ? WHERE userId = 10;";
    PreparedStatement insert1 = session.prepare(stmt);
    session.execute(insert1.bind(2));
```
Yugabyte result:
```
com.datastax.driver.core.exceptions.CodecNotFoundException: Codec not found for requested operation: [bigint <-> java.lang.Integer]
	at org.yb.cql.TestPrepareExecute.testPrepareAfterTableDrop(TestPrepareExecute.java:359)
```
Cassandra result:
```
com.datastax.driver.core.exceptions.CodecNotFoundException: Codec not found for requested operation: [counter <-> java.lang.Integer]
	at com.datastax.driver.core.CodecRegistry.notFound(CodecRegistry.java:741)
	at com.datastax.driver.core.CodecRegistry.createCodec(CodecRegistry.java:602)
	at com.datastax.driver.core.CodecRegistry.findCodec(CodecRegistry.java:582)
	at com.datastax.driver.core.CodecRegistry.codecFor(CodecRegistry.java:507)
	at com.datastax.driver.core.AbstractGettableByIndexData.codecFor(AbstractGettableByIndexData.java:77)
	at com.datastax.driver.core.BoundStatement.bind(BoundStatement.java:201)
	at com.datastax.driver.core.DefaultPreparedStatement.bind(DefaultPreparedStatement.java:126)
	at com.domain.app.AppTest.testApp(AppTest.java:71)
```

**Comment by OlegLoginov** [comment]
Duplicate issue on stackoverflow site:
https://stackoverflow.com/questions/60044197/yugabyte-c-sharp-driver-found-too-many-matches-for-builtin-function

**Comment by OlegLoginov** [comment]
Call stack:
```
    @     0x7fb589d629b3  FindMatch (src/yb/util/bfql/bfql.cc:201)
    @     0x7fb589d638c5  yb::bfql::FindOpcodeByType(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<yb::DataType, std::allocator<yb::DataType> > const&, yb::bfql::BFOpcode*, yb::bfql::BFDecl const**, yb::DataType*) (src/yb/util/bfql/bfql.cc:288)
    @     0x7fb591f9871d  yb::Status yb::bfql::FindOpcode<std::vector<shared_ptr<yb::ql::PTExpr>, std::allocator<shared_ptr<yb::ql::PTExpr> > >, shared_ptr<yb::ql::PTExpr> const&>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<shared_ptr<yb::ql::PTExpr>, std::allocator<shared_ptr<yb::ql::PTExpr> > > const&, yb::bfql::BFOpcode*, yb::bfql::BFDecl const**, shared_ptr<yb::ql::PTExpr> const&) (src/yb/util/bfql/bfql_template.h:72)
    @     0x7fb591f93153  yb::Status yb::bfql::BFCompileApi<yb::ql::PTExpr, yb::ql::PTExpr>::FindQLOpcodeImpl<std::vector, std::allocator<shared_ptr<yb::ql::PTExpr> > >(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<shared_ptr<yb::ql::PTExpr>, std::allocator<shared_ptr<yb::ql::PTExpr> > > const&, yb::bfql::BFOpcode*, yb::bfql::BFDecl const**, shared_ptr<yb::ql::PTExpr> const&) (src/yb/util/bfql/bfql.h:127)
    @     0x7fb591f93153  yb::bfql::BFCompileApi<yb::ql::PTExpr, yb::ql::PTExpr>::FindQLOpcode(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<shared_ptr<yb::ql::PTExpr>, std::allocator<shared_ptr<yb::ql::PTExpr> > > const&, yb::bfql::BFOpcode*, yb::bfql::BFDecl const**, shared_ptr<yb::ql::PTExpr> const&) (src/yb/util/bfql/bfql.h:153)
    @     0x7fb591f93153  yb::ql::PTBcall::Analyze(yb::ql::SemContext*) (src/yb/yql/cql/ql/ptree/pt_bcall.cc:131)
    @     0x7fb591f7858d  yb::ql::PTAssign::Analyze(yb::ql::SemContext*) (src/yb/yql/cql/ql/ptree/pt_update.cc:98)
    @     0x7fb591f76a03  yb::ql::PTUpdateStmt::AnalyzeSetExpr(yb::ql::PTAssign*, yb::ql::SemContext*) (src/yb/yql/cql/ql/ptree/pt_update.cc:197)
    @     0x7fb591f79fe2  yb::Status std::__invoke_impl<yb::Status, yb::Status (yb::ql::PTUpdateStmt::*&)(yb::ql::PTAssign*, yb::ql::SemContext*), yb::ql::PTUpdateStmt*&, yb::ql::PTAssign*, yb::ql::SemContext*>(std::__invoke_memfun_deref, yb::Status (yb::ql::PTUpdateStmt::*&)(yb::ql::PTAssign*, yb::ql::SemContext*), yb::ql::PTUpdateStmt*&, yb::ql::PTAssign*&&, yb::ql::SemContext*&&) (/usr/include/c++/7/bits/invoke.h:73)
    @     0x7fb591f79fe2  std::__invoke_result<yb::Status (yb::ql::PTUpdateStmt::*&)(yb::ql::PTAssign*, yb::ql::SemContext*), yb::ql::PTUpdateStmt*&, yb::ql::PTAssign*, yb::ql::SemContext*>::type std::__invoke<yb::Status (yb::ql::PTUpdateStmt::*&)(yb::ql::PTAssign*, yb::ql::SemContext*), yb::ql::PTUpdateStmt*&, yb::ql::PTAssign*, yb::ql::SemContext*>(yb::Status (yb::ql::PTUpdateStmt::*&)(yb::ql::PTAssign*, yb::ql::SemContext*), yb::ql::PTUpdateStmt*&, yb::ql::PTAssign*&&, yb::ql::SemContext*&&) (/usr/include/c++/7/bits/invoke.h:96)
    @     0x7fb591f79fe2  yb::Status std::_Bind<yb::Status (yb::ql::PTUpdateStmt::*(yb::ql::PTUpdateStmt*, std::_Placeholder<1>, std::_Placeholder<2>))(yb::ql::PTAssign*, yb::ql::SemContext*)>::__call<yb::Status, yb::ql::PTAssign*&&, yb::ql::SemContext*&&, 0ul, 1ul, 2ul>(tuple<yb::ql::PTAssign*&&, yb::ql::SemContext*&&>&&, std::_Index_tuple<0ul, 1ul, 2ul>) (/usr/include/c++/7/functional:469)
    @     0x7fb591f79fe2  yb::Status std::_Bind<yb::Status (yb::ql::PTUpdateStmt::*(yb::ql::PTUpdateStmt*, std::_Placeholder<1>, std::_Placeholder<2>))(yb::ql::PTAssign*, yb::ql::SemContext*)>::operator()<yb::ql::PTAssign*, yb::ql::SemContext*, yb::Status>(yb::ql::PTAssign*&&, yb::ql::SemContext*&&) (/usr/include/c++/7/functional:551)
    @     0x7fb591f79fe2  std::_Function_handler<yb::Status (yb::ql::PTAssign*, yb::ql::SemContext*), std::_Bind<yb::Status (yb::ql::PTUpdateStmt::*(yb::ql::PTUpdateStmt*, std::_Placeholder<1>, std::_Placeholder<2>))(yb::ql::PTAssign*, yb::ql::SemContext*)> >::_M_invoke(std::_Any_data const&, yb::ql::PTAssign*&&, yb::ql::SemContext*&&) (/usr/include/c++/7/bits/std_function.h:302)
    @     0x7fb592295089  std::function<yb::Status (yb::ql::PTAssign*, yb::ql::SemContext*)>::operator()(yb::ql::PTAssign*, yb::ql::SemContext*) const (/usr/include/c++/7/bits/std_function.h:706)
    @     0x7fb592295089  yb::ql::TreeListNode<yb::ql::PTAssign, (yb::ql::TreeNodeOpcode)1>::Analyze(yb::ql::SemContext*, std::function<yb::Status (yb::ql::PTAssign*, yb::ql::SemContext*)>) (src/yb/yql/cql/ql/ptree/list_node.h:97)
    @     0x7fb591f78c29  yb::ql::PTUpdateStmt::Analyze(yb::ql::SemContext*) (src/yb/yql/cql/ql/ptree/pt_update.cc:150)
    @     0x7fb591f13684  yb::ql::ParseTree::Analyze(yb::ql::SemContext*) (src/yb/yql/cql/ql/ptree/parse_tree.cc:67)
    @     0x7fb5927f9d0c  yb::ql::Analyzer::Analyze(unique_ptr<yb::ql::ParseTree, std::default_delete<yb::ql::ParseTree> >) (src/yb/yql/cql/ql/sem/analyzer.cc:38)
    @     0x7fb592a0a40c  yb::ql::QLProcessor::Analyze(unique_ptr<yb::ql::ParseTree, std::default_delete<yb::ql::ParseTree> >*) (src/yb/yql/cql/ql/ql_processor.cc:157)
    @     0x7fb592a0a692  yb::ql::QLProcessor::Prepare(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unique_ptr<yb::ql::ParseTree, std::default_delete<yb::ql::ParseTree> >*, bool, shared_ptr<yb::MemTracker> const&, bool) (src/yb/yql/cql/ql/ql_processor.cc:173)
    @     0x7fb592a084f1  yb::ql::Statement::Prepare(yb::ql::QLProcessor*, shared_ptr<yb::MemTracker> const&, bool, unique_ptr<yb::ql::PreparedResult, std::default_delete<yb::ql::PreparedResult> >*) (src/yb/yql/cql/ql/statement.cc:43)
    @     0x55649b228ca9  yb::ql::TestQLStatement_TestPrepareWithOpPlus_Test::TestBody() (src/yb/yql/cql/ql/test/ql-statement-test.cc:111)
    @     0x7fb587a1d17c  void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (/home/oleg/code/yugabyte-db/thirdparty/src/googletest-release-1.8.0/googletest/src/gtest.cc:2402)
    @     0x7fb587a1d17c  void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (/home/oleg/code/yugabyte-db/thirdparty/src/googletest-release-1.8.0/googletest/src/gtest.cc:2438)
    @     0x7fb587a125a1  testing::Test::Run() (/home/oleg/code/yugabyte-db/thirdparty/src/googletest-release-1.8.0/googletest/src/gtest.cc:2474)
    @     0x7fb587a12683  testing::TestInfo::Run() (/home/oleg/code/yugabyte-db/thirdparty/src/googletest-release-1.8.0/googletest/src/gtest.cc:2656)
    @     0x7fb587a127c6  testing::TestCase::Run() (/home/oleg/code/yugabyte-db/thirdparty/src/googletest-release-1.8.0/googletest/src/gtest.cc:2774)
    @     0x7fb587a12ca7  testing::internal::UnitTestImpl::RunAllTests() (/home/oleg/code/yugabyte-db/thirdparty/src/googletest-release-1.8.0/googletest/src/gtest.cc:4649)
    @     0x7fb587a1d65c  bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (/home/oleg/code/yugabyte-db/thirdparty/src/googletest-release-1.8.0/googletest/src/gtest.cc:2402)
    @     0x7fb587a1d65c  bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (/home/oleg/code/yugabyte-db/thirdparty/src/googletest-release-1.8.0/googletest/src/gtest.cc:2438)
    @     0x7fb587a12e00  testing::UnitTest::Run() (/home/oleg/code/yugabyte-db/thirdparty/src/googletest-release-1.8.0/googletest/src/gtest.cc:4257)
    @     0x7fb592ef6952  RUN_ALL_TESTS() (thirdparty/installed/uninstrumented/include/gtest/gtest.h:2233)
    @     0x7fb592ef6952  main (src/yb/util/test_main.cc:104)
```

**Comment by llKetanll** [comment]
@OlegLoginov / @kmuthukk - any updates on this?

**Comment by ZjuYTW** [comment]
Same issue encountered with c++ driver.
```
FATAL] Batch execution failed, Invalid Function Call. Failed calling '+(bigint,anytype)'. Found too many matches for builtin function '+'
UPDATE ybtest.stock SET s_quantity = ?, s_ytd = s_ytd + ?, s_order_cnt = s_order_cnt + 1, s_remote_cnt = s_remote_cnt + ? WHERE s_w_id = ? and s_i_id = ? IF s_quantity = ?
                                                                                               ^
 (ql error -214) (78)
```
