### ISSUE TITLE
[YW] Create universe fails if amzn2-linux AMI is provided

### ISSUE THREAD

**Issue by ajcaldera1** [yugabyte/yugabyte-db#3572]
I updated the region table in portal to use a amzn2-linux AMI because a prospect was trying to run tests on that version of Amazon Linux. It looks like it fails during the ansible step to set up the node after it has been created:
```
2020-02-06 14:42:29,493 INFO: Found credentials in environment variables.
2020-02-06 14:42:47,691 INFO: Waiting for instance yb-15-ac-xx-cdc-test-west-amzn2-n4
2020-02-06 14:43:26,596 INFO: Connected (version 2.0, client OpenSSH_7.4)
2020-02-06 14:43:27,076 INFO: Authentication (publickey) failed.
2020-02-06 14:43:27,236 INFO: Authentication (publickey) failed.
2020-02-06 14:43:28,522 INFO: Connected (version 2.0, client OpenSSH_7.4)
2020-02-06 14:43:29,001 INFO: Authentication (publickey) failed.
2020-02-06 14:43:29,164 INFO: Authentication (publickey) failed.
2020-02-06 14:43:30,449 INFO: Connected (version 2.0, client OpenSSH_7.4)
2020-02-06 14:43:30,933 INFO: Authentication (publickey) failed.
2020-02-06 14:43:31,128 INFO: Authentication (publickey) failed.
2020-02-06 14:43:32,402 INFO: Connected (version 2.0, client OpenSSH_7.4)
2020-02-06 14:43:32,869 INFO: Authentication (publickey) failed.
2020-02-06 14:43:33,040 INFO: Authentication (publickey) failed.
2020-02-06 14:43:34,332 INFO: Connected (version 2.0, client OpenSSH_7.4)
2020-02-06 14:43:34,819 INFO: Authentication (publickey) failed.
2020-02-06 14:43:35,011 INFO: Authentication (publickey) failed.
<snip>
2020-02-06 14:45:12,639 INFO: Authentication (publickey) failed.
2020-02-06 14:45:12,809 INFO: Authentication (publickey) failed.
Traceback (most recent call last):
  File "/opt/yugabyte/yb-software/devops-2.0.12.0-b2-centos-x86_64/python_virtual_env/bin/ybcloud.py", line 4, in <module>
    __import__('pkg_resources').run_script('ybops==0.4', 'ybcloud.py')
  File "/opt/yugabyte/yb-software/devops-2.0.12.0-b2-centos-x86_64/python_virtual_env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/opt/yugabyte/yb-software/devops-2.0.12.0-b2-centos-x86_64/python_virtual_env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1462, in run_script
    exec(code, namespace, namespace)
  File "/opt/yugabyte/yb-software/devops-2.0.12.0-b2-centos-x86_64/python_virtual_env/lib/python2.7/site-packages/ybops-0.4-py2.7.egg/EGG-INFO/scripts/ybcloud.py", line 15, in <module>
    YbCloud().run()
  File "/opt/yugabyte/yb-software/devops-2.0.12.0-b2-centos-x86_64/python_virtual_env/lib/python2.7/site-packages/ybops-0.4-py2.7.egg/ybops/cloud/ybcloud.py", line 54, in run
    self.options.func(self.options)
  File "/opt/yugabyte/yb-software/devops-2.0.12.0-b2-centos-x86_64/python_virtual_env/lib/python2.7/site-packages/ybops-0.4-py2.7.egg/ybops/cloud/common/method.py", line 76, in callback_wrapper
    self.callback(args)
  File "/opt/yugabyte/yb-software/devops-2.0.12.0-b2-centos-x86_64/python_virtual_env/lib/python2.7/site-packages/ybops-0.4-py2.7.egg/ybops/cloud/common/method.py", line 356, in callback
    self.create_method.callback(args)
  File "/opt/yugabyte/yb-software/devops-2.0.12.0-b2-centos-x86_64/python_virtual_env/lib/python2.7/site-packages/ybops-0.4-py2.7.egg/ybops/cloud/aws/method.py", line 82, in callback
    super(AwsCreateInstancesMethod, self).callback(args)
  File "/opt/yugabyte/yb-software/devops-2.0.12.0-b2-centos-x86_64/python_virtual_env/lib/python2.7/site-packages/ybops-0.4-py2.7.egg/ybops/cloud/common/method.py", line 260, in callback
    host_info = self.wait_for_host(args)
  File "/opt/yugabyte/yb-software/devops-2.0.12.0-b2-centos-x86_64/python_virtual_env/lib/python2.7/site-packages/ybops-0.4-py2.7.egg/ybops/cloud/common/method.py", line 301, in wait_for_host
    args.private_key_file):
  File "/opt/yugabyte/yb-software/devops-2.0.12.0-b2-centos-x86_64/python_virtual_env/lib/python2.7/site-packages/ybops-0.4-py2.7.egg/ybops/utils/__init__.py", line 449, in wait_for_ssh
    "Timed out trying to SSH to instance: {}:{}".format(host_ip, ssh_port))
ybops.common.exceptions.YBOpsRuntimeError: Runtime error: Timed out trying to SSH to instance: 172.152.107.148:22.
```

**Comment by ramkumarvs** [comment]
There seem to be couple of issues on our platform side that we need to address to fix this.
- Access Key setup we need to pass the sshUser all the way, right now this doesn't seem to be getting saved into our db properly
- Cloud provision and other steps should use the sshUser.

**Comment by WesleyW** [comment]
It seems like the sshUser is saved to our DB now, but it is still not being passed down properly.

To test this, I'd recommend the following:
1. Create ssh key on AWS.
2. Create ec2 instance with Amazon Linux 2 with that key. Create a new user.
3. Create an OnPrem provider with SSH User set to that new user and keyfile contents.
4. Add the IP of the instance you created to the provider.
5. Create a universe with the provider.
