### ISSUE TITLE
ysql BLOB support

### ISSUE THREAD

**Issue by reptillicus** [yugabyte/yugabyte-db#3576]
This is a feature request for supporting BLOB type with ysql/postgres. Also, what are the limits on `bytea` type? max size?

**Comment by ddorian** [comment]
We have a potential bug with big values: https://github.com/yugabyte/yugabyte-db/issues/3586

**Comment by ddorian** [comment]
@reptillicus 
Currently you can insert rows up to `64MB` in size.

We still don't support BLOB (large object in postgresql land).

**Comment by ddorian** [comment]
@reptillicus 
While max row size is ~64MB, we recommend row sizes to not go over 4MB so you get consistent latency/performance on read/write.

**Comment by reptillicus** [comment]
Thanks!

**Comment by ibrohimislam** [comment]
when using YSQL with postgres LO, gives me error:

```Caused by: org.postgresql.util.PSQLException: ERROR: Illegal state: Transaction for catalog table write operation 'pg_largeobject_metadata' not found
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2675)
        at org.postgresql.core.v3.QueryExecutorImpl.receiveFastpathResult(QueryExecutorImpl.java:856)
        at org.postgresql.core.v3.QueryExecutorImpl.fastpathCall(QueryExecutorImpl.java:643)
        at org.postgresql.fastpath.Fastpath.fastpath(Fastpath.java:110)
        at org.postgresql.fastpath.Fastpath.fastpath(Fastpath.java:152)
        at org.postgresql.fastpath.Fastpath.getInteger(Fastpath.java:164)
        at org.postgresql.fastpath.Fastpath.getOID(Fastpath.java:215)
        at org.postgresql.largeobject.LargeObjectManager.createLO(LargeObjectManager.java:289)
        at org.postgresql.largeobject.LargeObjectManager.createLO(LargeObjectManager.java:272)
        at org.postgresql.jdbc.PgPreparedStatement.setClob(PgPreparedStatement.java:1261)
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.setClob(HikariProxyPreparedStatement.java)
        at org.hibernate.type.descriptor.sql.ClobTypeDescriptor$3$1.doBind(ClobTypeDescriptor.java:105)
        at org.hibernate.type.descriptor.sql.BasicBinder.bind(BasicBinder.java:73)
        at org.hibernate.type.AbstractStandardBasicType.nullSafeSet(AbstractStandardBasicType.java:276)
        at org.hibernate.type.AbstractStandardBasicType.nullSafeSet(AbstractStandardBasicType.java:271)
        at org.hibernate.type.AbstractSingleColumnStandardBasicType.nullSafeSet(AbstractSingleColumnStandardBasicType.java:39)
        at org.hibernate.persister.entity.AbstractEntityPersister.dehydrate(AbstractEntityPersister.java:3073)
        at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3372)
        ... 95 common frames omitted```
