### ISSUE TITLE
C#: Cassandra.NoHostAvailableException: No host is available to be queried (no host tried)

### ISSUE THREAD

**Issue by zeinali0** [yugabyte/yugabyte-db#3598]
In C# driver (YugabyteCassandraCSharpDriver 3.7.1) I create one instance of ISession for hole application run time and it work without problem but after a period time of inactivity (5-10 min) i face with this exception:

```
Cassandra.NoHostAvailableException: No host is available to be queried (no host tried)
   at Cassandra.Requests.PrepareHandler.GetNextConnection(IInternalSession session, Dictionary`2 triedHosts)
   at Cassandra.Requests.PrepareHandler.Prepare(PrepareRequest request, IInternalSession session, Dictionary`2 triedHosts)
   at Cassandra.Requests.PrepareHandler.Prepare(IInternalSession session, Serializer serializer, PrepareRequest request)
   at Cassandra.Session.PrepareAsync(String query, IDictionary`2 customPayload)
   at Cassandra.Mapping.Statements.StatementFactory.GetStatementAsync(ISession session, Cql cql, Nullable`1 forceNoPrepare)
   at Cassandra.Data.Linq.CqlQueryBase`1.InternalExecuteAsync(String cqlQuery, Object[] values)
   at Cassandra.Data.Linq.CqlQueryBase`1.ExecuteAsync()
   at Cassandra.Data.Linq.CqlQuerySingleElement`1.ExecuteAsync()
```

And i need to restart application again to it work.

Here is how I Create an ISession:

```
Cluster.Builder().AddContactPoint(key).WithPoolingOptions(PoolingOptions.Create(ProtocolVersion.V3)
    .SetHeartBeatInterval(1000).SetCoreConnectionsPerHost(HostDistance.Remote, 1)).Build().Connect();
```

**Comment by kmuthukk** [comment]
hi @zeinali0 --

when this happens, can you confirm that the yb-tserver processes are still alive?

**Comment by zeinali0** [comment]
Yes. Because when i restart my application every thing start working again without. It seems singleton ISession lost it's connection after a time if inactivity

**Comment by kmuthukk** [comment]
hi @zeinali0 --

can you also try adding in:

`  .WithReconnectionPolicy(new ConstantReconnectionPolicy(1000))`

not 100% sure, but it'll be great if you can give this a quick try to see if this could help with the issue you are seeing.

**Comment by zeinali0** [comment]
> hi @zeinali0 --
> 
> can you also try adding in:
> 
> ` .WithReconnectionPolicy(new ConstantReconnectionPolicy(1000))`
> 
> not 100% sure, but it'll be great if you can give this a quick try to see if this could help with the issue you are seeing.

It seems it work fine now.

**Comment by kmuthukk** [comment]
Glad to hear that this worked, @zeinali0 .

Will close out the issue.
