### ISSUE TITLE
YugaByte server unresponsive after sometime; log spew: "A memtable with no frontiers set found when deciding what memtables to flush!"

### ISSUE THREAD

**Issue by amit2103** [yugabyte/yugabyte-db#396]
Jira Link: [DB-6277](https://yugabyte.atlassian.net/browse/DB-6277)
This is the log we are getting :- 

```
E0723 08:57:37.407618  8048 memtable_list.cc:286] Failed when checking if memtable can be flushed (will still flush it): Illegal state (yb/tablet/tablet_peer.cc:191): A memtable with no frontiers set found when deciding what memtables to flush! This should not happen.. Memtable: MemTable { num_entries: 0 num_deletes: 0 IsEmpty: 1 flush_state: kNotRequested first_seqno: 0 eariest_seqno: 1125899917985563 frontiers: N/A }. All memtables:
  MemTable { num_entries: 0 num_deletes: 0 IsEmpty: 1 flush_state: kNotRequested first_seqno: 0 eariest_seqno: 1125899917985563 frontiers: N/A }
E0724 05:25:19.605695  8048 tablet_peer.cc:190] A memtable with no frontiers set found when deciding what memtables to flush! This should not happen. Stack trace:
    @     0x7f0033636983  operator() (yb/tablet/tablet_peer.cc:190)
    @     0x7f0033636983  _M_invoke (gcc/5.5.0/include/c++/5.5.0/functional:1857)
    @     0x7f003066c466  std::function<yb::Result<bool> (rocksdb::MemTable const&)>::operator()(rocksdb::MemTable const&) const (gcc/5.5.0/include/c++/5.5.0/functional:2267)
    @     0x7f003066c466  rocksdb::MemTableList::PickMemtablesToFlush(rocksdb::autovector<rocksdb::MemTable*, 8ul>*, std::function<yb::Result<bool> (rocksdb::MemTable const&)> const&) (yb/rocksdb/db/memtable_list.cc:269)
    @     0x7f003065658e  rocksdb::FlushJob::Run(rocksdb::FileMetaData*) (yb/rocksdb/db/flush_job.cc:143)
    @     0x7f003061ca62  rocksdb::DBImpl::FlushMemTableToOutputFile(rocksdb::ColumnFamilyData*, rocksdb::MutableCFOptions const&, bool*, rocksdb::JobContext*, rocksdb::LogBuffer*) (yb/rocksdb/db/db_impl.cc:1582)
    @     0x7f003061d416  rocksdb::DBImpl::BackgroundFlush(bool*, rocksdb::JobContext*, rocksdb::LogBuffer*) (yb/rocksdb/db/db_impl.cc:2817)
    @     0x7f003062671a  rocksdb::DBImpl::BackgroundCallFlush() (yb/rocksdb/db/db_impl.cc:2839)
    @     0x7f00307197f2  rocksdb::ThreadPool::BGThread(unsigned long) (yb/rocksdb/util/thread_posix.cc:133)
    @     0x7f0030719887  BGThreadWrapper (yb/rocksdb/util/thread_posix.cc:157)
    @     0x7f00293c8693  start_thread (/tmp/glibc-20180316-12585-rgaxli/glibc-2.23/nptl/pthread_create.c:333)
    @     0x7f0028b063cc  (unknown) (../sysdeps/unix/sysv/linux/x86_64/clone.S:109)
    @ 0xffffffffffffffff
E0724 05:25:19.605768  8048 memtable_list.cc:286] Failed when checking if memtable can be flushed (will still flush it): Illegal state (yb/tablet/tablet_peer.cc:191): A memtable with no frontiers set found when deciding what memtables to flush! This should not happen.. Memtable: MemTable { num_entries: 0 num_deletes: 0 IsEmpty: 1 flush_state: kNotRequested first_seqno: 0 eariest_seqno: 1125899918988666 frontiers: N/A }. All memtables:
  MemTable { num_entries: 0 num_deletes: 0 IsEmpty: 1 flush_state: kNotRequested first_seqno: 0 eariest_seqno: 1125899918988666 frontiers: N/A }
```

[DB-6277]: https://yugabyte.atlassian.net/browse/DB-6277?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by amit2103** [comment]
For more details we are using Redis api of Yugabyte, this is what we see in the client repeadtedly :-  
Caused by: com.lambdaworks.redis.RedisCommandExecutionException: Some errors occurred
 at com.lambdaworks.redis.protocol.AsyncCommand.completeResult(AsyncCommand.java:119)
 at com.lambdaworks.redis.protocol.AsyncCommand.complete(AsyncCommand.java:110)
 at com.lambdaworks.redis.protocol.CommandHandler.complete(CommandHandler.java:336)

**Comment by mbautin** [comment]
@amit2103 Thank you for reporting this issue! Would you mind uploading the full set of master / tablet server logs for this system, as well as tell us more about the deployment? (Local cluster / distributed cluster, machine configuration, number of disks, etc.) Also would you mind checking if there is sufficient disk space on the cluster nodes?

**Comment by mbautin** [comment]
Putting the stack trace in an easier-to-view format: https://gist.githubusercontent.com/mbautin/b6524763c852fdbb0a8192ed947661fb/raw

**Comment by amit2103** [comment]
@mbautin  This is a 3 node cluster. Its m4.large each of them

**Comment by amit2103** [comment]
[logs-master1.zip](https://github.com/YugaByte/yugabyte-db/files/2228339/logs-master1.zip)

**Comment by amit2103** [comment]
Some files are so large cant upload them

**Comment by mbautin** [comment]
@amit2103 Even if tablet server logs are too long, it would be extremely useful for us to have them for diagnosing this issue. Perhaps you could limit it to the last 10MB or so by using `tail -c 10000000 file_name >file_name_for_upload`. Also would you mind double-checking the free disk space on the cluster nodes? Thank you!

**Comment by amit2103** [comment]
[yb-tserver.log](https://github.com/YugaByte/yugabyte-db/files/2228735/yb-tserver.log)
This is error file renamed

**Comment by amit2103** [comment]
[log1.log](https://github.com/YugaByte/yugabyte-db/files/2228737/log1.log)

**Comment by amit2103** [comment]
[log2.log](https://github.com/YugaByte/yugabyte-db/files/2228739/log2.log)

**Comment by amit2103** [comment]
[log_truncated.log](https://github.com/YugaByte/yugabyte-db/files/2228745/log_truncated.log)

**Comment by amit2103** [comment]
The server had 8GB of hard disk left.
we have upgraded it to 40GB now (empty space).

**Comment by mbautin** [comment]
@amit2103 can we do a video call so we can do some live debugging on your cluster? You can email me mikhail at yugabyte dot com with some time slots that would work for you. I'm seeing a couple of different issues in the logs, neither of which we've seen in our own cluster testing, and I would like to understand your setup and workload a little better.

**Comment by mesbahmajed** [comment]
@mbautin I sent you an email regarding this, please double check it, thanks

**Comment by rthallamko3** [comment]
@arybochkin , Lets increase the priority of reproducing the issue that repros the above failure. It was hit on YBM cluster recently.

**Comment by mbautin** [comment]
It would be helpful if someone could post the exact logs (without any sensitive information, of course) from the latest occurrence of this error. We have the following check in master:

```
        // It is correct to not have frontiers when memtable is empty
        if (memtable.IsEmpty()) {
          return true;
        }
```

That means, for this issue to occur with a recent release, the memtable has to be non-empty but should not have frontiers.

**Comment by mbautin** [comment]
```
Failed when checking if memtable can be flushed (will still flush it): Illegal state (yb/tablet/tablet_peer.cc:253): A memtable with no frontiers set found when deciding what memtables to flush! This should not happen.. Memtable: MemTable { num_entries: 1367964 num_deletes: 0 IsEmpty: 0 flush_state: kNotRequested first_seqno: 1125899922242779 eariest_seqno: 0 frontiers: N/A }. All memtables:
```

**Comment by mbautin** [comment]
In tablet.cc, the WriteToRocksDB function, we have this comment: "Frontiers can be null for deferred apply operations."

So, it is possible that all operations in a particular RocksDB memtable are generated by deferred apply operations.

**Comment by rthallamko3** [comment]
@jmeehan16 , Considering creating the frontier in all cases, so as to eliminate the cause of the above log spew.

**Comment by rthallamko3** [comment]
@ttyusupov , Did you fix the above symptom in the context of another issue?

**Comment by rthallamko3** [comment]
Backport is expensive. Closing the issue for now.
