### ISSUE TITLE
spring data cassandra batch operation - Exception

### ISSUE THREAD

**Issue by jmirc** [yugabyte/yugabyte-db#3965]
Spring Boot: 2.2.5.RELEASE
Spring Cloud: Hoxton.SR3

I am using the backOperation from cassandraTemplate and I am getting an exception

```org.springframework.data.cassandra.core.cassandraOperations.batchOps().insert(p).execute()```

Here is the exception.
```
Caused by: com.datastax.driver.core.exceptions.SyntaxError: Invalid SQL Statement. syntax error, unexpected IDENT, expecting TRANSACTION
BEGIN BATCH INSERT INTO cgs (key,value) VALUES (?,?);APPLY BATCH;
      ^^^^^
 (ql error -11)
	at com.datastax.driver.core.Responses$Error.asException(Responses.java:177)
	at com.datastax.driver.core.DefaultResultSetFuture.onSet(DefaultResultSetFuture.java:215)
	at com.datastax.driver.core.RequestHandler.setFinalResult(RequestHandler.java:236)
	at com.datastax.driver.core.RequestHandler.access$2600(RequestHandler.java:62)
	at com.datastax.driver.core.RequestHandler$SpeculativeExecution.setFinalResult(RequestHandler.java:1005)
	at com.datastax.driver.core.RequestHandler$SpeculativeExecution.onSet(RequestHandler.java:808)
	at com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:1240)
```

**Comment by ddorian** [comment]
We don't support `BEGIN BATCH` in YugabyteDB. We do support through `BatchStatement` object. Example in Java: https://docs.yugabyte.com/latest/develop/learn/batch-operations-ycql/#java-example
