### ISSUE TITLE
[YW] onpremise flow fails to install epel-release in some Centos7/RHEL 7 AMIs

### ISSUE THREAD

**Issue by ajcaldera1** [yugabyte/yugabyte-db#4020]
This may be a regression, but I am no longer able to run the onpremise provision flow with Ubuntu or some RHEL 7/Centos 7 AMI's. Ubuntu fails with `dpkg` errors and Centos/RHEL fail to install epel-release. I must manually go in and do a `wget` on:
```
https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
```
Here is the error log from Yugaware:
```
Failed to execute task java.util.concurrent.FutureTask@4f5a7328, hit error java.lang.RuntimeException: 2020-03-19 19:34:11,359 INFO: Found onprem cloud credentials in env.
2020-03-19 19:34:11,360 INFO: Host yb-demo-yb-ac-txn-test-3-n5 already created.
2020-03-19 19:34:11,361 INFO: Running ansible command ["ansible-playbook" "/opt/yugabyte/devops/yb-server-provision.yml" "--vault-password-file" "/opt/yugabyte/yugaware/data/keys/63cc0fd3-7377-4f93-8293-2615cd8cf0ae/external-onprem-2-key.vault_password" "--private-key" "/opt/yugabyte/yugaware/data/keys/63cc0fd3-7377-4f93-8293-2615cd8cf0ae/external-onprem-2-key.pem" "--user" "ec2-user" "-i" "172.201.22.247," "-c" "ssh" "--extra-vars" "{\"ansible_port\": 22, \"cloud_type\": \"onprem\", \"server_type\": \"cluster-server\", \"ssd_size_gb\": 500, \"yb_home_dir\": \"/home/yugabyte\", \"mount_points\": \"/data\", \"instance_search_pattern\": \"all\", \"yb_server_ssh_user\": \"ec2-user\", \"num_volumes\": 5, \"instance_name\": \"yb-demo-yb-ac-txn-test-3-n5\", \"instance_type\": null, \"device_names\": [], \"ssh_user\": \"ec2-user\", \"vars_file\": \"/opt/yugabyte/yugaware/data/keys/63cc0fd3-7377-4f93-8293-2615cd8cf0ae/external-onprem-2-key.vault\", \"cloud_zone\": \"us-west-2a\", \"disk_iops\": 1000, \"yb_ansible_host\": \"172.201.22.247\", \"user_name\": \"yugabyte\", \"cloud_region\": \"us-west-2\", \"local_package_path\": \"/opt/third-party\"}"]
Traceback (most recent call last):
  File "/opt/yugabyte/devops/python_virtual_env/bin/ybcloud.py", line 4, in <module>
    __import__('pkg_resources').run_script('ybops==0.4', 'ybcloud.py')
  File "/opt/yugabyte/devops/python_virtual_env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/opt/yugabyte/devops/python_virtual_env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1462, in run_script
    exec(code, namespace, namespace)
  File "/opt/yugabyte/devops/python_virtual_env/lib/python2.7/site-packages/ybops-0.4-py2.7.egg/EGG-INFO/scripts/ybcloud.py", line 15, in <module>
    YbCloud().run()
  File "/opt/yugabyte/devops/python_virtual_env/lib/python2.7/site-packages/ybops-0.4-py2.7.egg/ybops/cloud/ybcloud.py", line 54, in run
    self.options.func(self.options)
  File "/opt/yugabyte/devops/python_virtual_env/lib/python2.7/site-packages/ybops-0.4-py2.7.egg/ybops/cloud/common/method.py", line 76, in callback_wrapper
    self.callback(args)
  File "/opt/yugabyte/devops/python_virtual_env/lib/python2.7/site-packages/ybops-0.4-py2.7.egg/ybops/cloud/onprem/method.py", line 67, in callback
    super(OnPremProvisionInstancesMethod, self).callback(args)
  File "/opt/yugabyte/devops/python_virtual_env/lib/python2.7/site-packages/ybops-0.4-py2.7.egg/ybops/cloud/common/method.py", line 366, in callback
    self.cloud.setup_ansible(args).run("yb-server-provision.yml", self.extra_vars, host_info)
  File "/opt/yugabyte/devops/python_virtual_env/lib/python2.7/site-packages/ybops-0.4-py2.7.egg/ybops/cloud/common/ansible.py", line 130, in run
    process_args, p.returncode, stderr))
ybops.common.exceptions.YBOpsRuntimeError: Runtime error: Playbook with args ['ansible-playbook', '/opt/yugabyte/devops/yb-server-provision.yml', '--vault-password-file', '/opt/yugabyte/yugaware/data/keys/63cc0fd3-7377-4f93-8293-2615cd8cf0ae/external-onprem-2-key.vault_password', '--private-key', '/opt/yugabyte/yugaware/data/keys/63cc0fd3-7377-4f93-8293-2615cd8cf0ae/external-onprem-2-key.pem', '--user', u'ec2-user', '-i', u'172.201.22.247,', '-c', 'ssh', '--extra-vars', '{"ansible_port": 22, "cloud_type": "onprem", "server_type": "cluster-server", "ssd_size_gb": 500, "yb_home_dir": "/home/yugabyte", "mount_points": "/data", "instance_search_pattern": "all", "yb_server_ssh_user": "ec2-user", "num_volumes": 5, "instance_name": "yb-demo-yb-ac-txn-test-3-n5", "instance_type": null, "device_names": [], "ssh_user": "ec2-user", "vars_file": "/opt/yugabyte/yugaware/data/keys/63cc0fd3-7377-4f93-8293-2615cd8cf0ae/external-onprem-2-key.vault", "cloud_zone": "us-west-2a", "disk_iops": 1000, "yb_ansible_host": "172.201.22.247", "user_name": "yugabyte", "cloud_region": "us-west-2", "local_package_path": "/opt/third-party"}'] failed with return code 2 and error fatal: [172.201.22.247] FAILED! => {"attempts": 5, "changed": false, "failed": true, "msg": "No package matching 'epel-release' found available, installed or updated", "rc": 126, "results": ["No package matching 'epel-release' found available, installed or updated"]}.
```

**Comment by WesleyW** [comment]
For onprem, certain packages have been disabled a while back as a temporary fix, so this shouldn't be a problem anymore.
