### ISSUE TITLE
[YSQL] Postgres process crash while running COPY

### ISSUE THREAD

**Issue by ndeodhar** [yugabyte/yugabyte-db#4073]
Stack trace:
```
(gdb) where
#0  0x00007fea8998d0a7 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007fea8998e4aa in __GI_abort () at abort.c:89
#2  0x00007fea899c7e16 in __libc_message (do_abort=do_abort@entry=2,
    fmt=fmt@entry=0x7fea89abff70 "*** Error in `%s': %s: 0x%s ***\n") at ../sysdeps/posix/libc_fatal.c:175
#3  0x00007fea899cd5f6 in malloc_printerr (action=3, str=0x7fea89abc867 "free(): invalid pointer", ptr=<optimized out>,
    ar_ptr=<optimized out>) at malloc.c:5007
#4  0x00007fea899ce343 in _int_free (av=0x7fea89cf0640 <main_arena>, p=<optimized out>, have_lock=0) at malloc.c:3868
#5  0x00007fea861686a8 in ~intrusive_ptr (this=0x7fea600338c0, __in_chrg=<optimized out>)
    at /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20191209181439-7fc63d1583-centos/installed/uninstrumented/include/boost/smart_ptr/intrusive_ptr.hpp:98
#6  ~Status (this=0x7fea600338c0, __in_chrg=<optimized out>) at ../../src/yb/util/status.h:374
#7  yb::client::YBError::~YBError (this=0x7fea600338b0, __in_chrg=<optimized out>) at ../../src/yb/client/error.cc:26
#8  0x00007fea8af22d50 in operator() (this=<optimized out>, __ptr=0x7fea600338b0)
    at /home/yugabyte/yb-software/yugabyte-2.1.3.0-b21-centos-x86_64/linuxbrew-xxxxxxxxxxxxx/Cellar/gcc/5.5.0_4/include/c++/5.5.0/bits/unique_ptr.h:76
#9  ~unique_ptr (this=<optimized out>, __in_chrg=<optimized out>)
    at /home/yugabyte/yb-software/yugabyte-2.1.3.0-b21-centos-x86_64/linuxbrew-xxxxxxxxxxxxx/Cellar/gcc/5.5.0_4/include/c++/5.5.0/bits/unique_ptr.h:239
#10 _Destroy<std::unique_ptr<yb::client::YBError> > (__pointer=<optimized out>)
    at /home/yugabyte/yb-software/yugabyte-2.1.3.0-b21-centos-x86_64/linuxbrew-xxxxxxxxxxxxx/Cellar/gcc/5.5.0_4/include/c++/5.5.0/bits/stl_construct.h:93
#11 __destroy<std::unique_ptr<yb::client::YBError>*> (__last=<optimized out>, __first=0x7fea600338e0)
    at /home/yugabyte/yb-software/yugabyte-2.1.3.0-b21-centos-x86_64/linuxbrew-xxxxxxxxxxxxx/Cellar/gcc/5.5.0_4/include/c++/5.5.0/bits/stl_construct.h:103
#12 _Destroy<std::unique_ptr<yb::client::YBError>*> (__last=<optimized out>, __first=<optimized out>)
    at /home/yugabyte/yb-software/yugabyte-2.1.3.0-b21-centos-x86_64/linuxbrew-xxxxxxxxxxxxx/Cellar/gcc/5.5.0_4/include/c++/5.5.0/bits/stl_construct.h:126
#13 _Destroy<std::unique_ptr<yb::client::YBError>*, std::unique_ptr<yb::client::YBError> > (__last=0x7fea600338e8,
    __first=<optimized out>)
    at /home/yugabyte/yb-software/yugabyte-2.1.3.0-b21-centos-x86_64/linuxbrew-xxxxxxxxxxxxx/Cellar/gcc/5.5.0_4/include/c++/5.5.0/bits/stl_construct.h:151
#14 std::vector<std::unique_ptr<yb::client::YBError, std::default_delete<yb::client::YBError> >, std::allocator<std::unique_ptr<yb::client::YBError, std::default_delete<yb::cl\
ient::YBError> > > >::~vector (this=0x7ffce4804460, __in_chrg=<optimized out>)
    at /home/yugabyte/yb-software/yugabyte-2.1.3.0-b21-centos-x86_64/linuxbrew-xxxxxxxxxxxxx/Cellar/gcc/5.5.0_4/include/c++/5.5.0/bits/stl_vector.h:424
#15 0x00007fea8af1da4c in yb::pggate::PgSession::FlushBufferedOperationsImpl (this=this@entry=0x3146150, ops=...,
    transactional=transactional@entry=true) at ../../src/yb/yql/pggate/pg_session.cc:838
#16 0x00007fea8af1de2a in yb::pggate::PgSession::FlushBufferedOperationsImpl (this=0x3146150)
    at ../../src/yb/yql/pggate/pg_session.cc:766
#17 0x00007fea8af1dfc8 in yb::pggate::PgSession::FlushBufferedOperations (this=<optimized out>)
    at ../../src/yb/yql/pggate/pg_session.cc:751
#18 0x00007fea8af12378 in yb::pggate::PgApiImpl::FlushBufferedOperations (this=<optimized out>)
    at ../../src/yb/yql/pggate/pggate.cc:671
#19 0x00007fea8af0cdec in yb::pggate::YBCPgFlushBufferedOperations () at ../../src/yb/yql/pggate/ybc_pggate.cc:444
#20 0x0000000000530827 in CommitTransactionCommand () at ../../../../../../../src/postgres/src/backend/access/transam/xact.c:3138
```

Command being run was:
`COPY sqlsecondaryindex TO 'index.csv' DELIMITER ',' CSV HEADER;`

cc: @kmuthukk (if there are more details that you want to add)

**Comment by kmuthukk** [comment]
Saw the crash, but haven't been able to repro it. And not 100% sure if it is related to the COPY command.
