### ISSUE TITLE
[docdb] Potential deadlock after fully changing master quorum

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#4089]
We generally refer to moving from an initial set of nodes, like ABC to a completely new set of nodes, like DEF, as a `full move`. One of the aspects of this is that the master quorum will be completely reconfigured which affects both masters and tservers, which at startup know about the masters through a fixed list of master endpoints, provided via gflags:
- `--master_addresses` for masters
- `--tserver_master_addrs` for tservers

We've added a `YBClient` in the master code a while back and it seems the client can get stuck if the known list of masters is empty.

**Signs of the problem in the logs:**
```
E0417 05:51:34.147912 25527 async_initializer.cc:83] Failed to initialize client: Invalid argument (yb/client/client-internal.cc:1642): Could not locate the leader master: No master address specified by '' (all master server addresses: [])
I0417 05:51:35.148046 25527 client-internal.cc:1762] Reinitialize master addresses from file: /home/yugabyte/master/conf/server.conf
E0417 05:51:35.148109 25527 async_initializer.cc:83] Failed to initialize client: Invalid argument (yb/client/client-internal.cc:1642): Could not locate the leader master: No master address specified by '' (all master server addresses: [])
I0417 05:51:36.148247 25527 client-internal.cc:1762] Reinitialize master addresses from file: /home/yugabyte/master/conf/server.conf

```

Relevant stack after `kill -11` on the `yb-master`:
```
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x00007faebfc8b748 in std::__atomic_futex_unsigned_base::_M_futex_wait_until(unsigned int*, unsigned int, bool, std::chrono::duration<long, std::ratio<1l, 1l> >, std::chrono::duration<long, std::ratio<1l, 1000000000l> >) ()
   from /home/yugabyte/yb-software/yugabyte-2.1.3.0-b22-centos-x86_64/linuxbrew/lib/libstdc++.so.6
#2  0x00007faeccdda6a8 in _M_load_and_test_until (__ns=..., __s=..., __has_timeout=<optimized out>, __mo=<optimized out>, __equal=<optimized out>, __operand=<optimized out>, __assumed=<optimized out>, this=<optimized out>)
    at /home/yugabyte/yb-software/yugabyte-2.1.3.0-b22-centos-x86_64/linuxbrew-xxxxxxxxxxxxx/Cellar/gcc/5.5.0_4/include/c++/5.5.0/bits/atomic_futex.h:104
#3  _M_load_and_test (__mo=<optimized out>, __equal=<optimized out>, __operand=<optimized out>, __assumed=<optimized out>, this=<optimized out>)
    at /home/yugabyte/yb-software/yugabyte-2.1.3.0-b22-centos-x86_64/linuxbrew-xxxxxxxxxxxxx/Cellar/gcc/5.5.0_4/include/c++/5.5.0/bits/atomic_futex.h:122
#4  _M_load_when_equal (__mo=std::memory_order_acquire, __val=1, this=0x2f4faf0) at /home/yugabyte/yb-software/yugabyte-2.1.3.0-b22-centos-x86_64/linuxbrew-xxxxxxxxxxxxx/Cellar/gcc/5.5.0_4/include/c++/5.5.0/bits/atomic_futex.h:162
#5  wait (this=0x2f4fae0) at /home/yugabyte/yb-software/yugabyte-2.1.3.0-b22-centos-x86_64/linuxbrew-xxxxxxxxxxxxx/Cellar/gcc/5.5.0_4/include/c++/5.5.0/future:322
#6  _M_get_result (this=<optimized out>) at /home/yugabyte/yb-software/yugabyte-2.1.3.0-b22-centos-x86_64/linuxbrew-xxxxxxxxxxxxx/Cellar/gcc/5.5.0_4/include/c++/5.5.0/future:681
#7  get (this=<optimized out>) at /home/yugabyte/yb-software/yugabyte-2.1.3.0-b22-centos-x86_64/linuxbrew-xxxxxxxxxxxxx/Cellar/gcc/5.5.0_4/include/c++/5.5.0/future:889
#8  client (this=0x7faeae851aa0) at ../../../../../src/yb/tablet/transaction_participant.cc:1085
#9  yb::tablet::TransactionParticipant::Impl::NotifyApplied (this=this@entry=0x39d5200, data=...) at ../../../../../src/yb/tablet/transaction_participant.cc:488
#10 0x00007faeccddabfe in yb::tablet::TransactionParticipant::Impl::ProcessApply (this=this@entry=0x39d5200, data=...) at ../../../../../src/yb/tablet/transaction_participant.cc:446
#11 0x00007faeccdcb88a in ReplicatedApplying (data=..., id=..., this=0x39d5200) at ../../../../../src/yb/tablet/transaction_participant.cc:1194
#12 ProcessReplicated (data=..., this=<optimized out>, this=<optimized out>, this=<optimized out>) at ../../../../../src/yb/tablet/transaction_participant.cc:412
#13 yb::tablet::TransactionParticipant::ProcessReplicated (this=this@entry=0x3748bc0, data=...) at ../../../../../src/yb/tablet/transaction_participant.cc:1361
#14 0x00007faeccdec67d in yb::tablet::UpdateTxnOperation::DoReplicated (this=<optimized out>, leader_term=<optimized out>, complete_status=<optimized out>) at ../../../../../src/yb/tablet/operations/update_txn_operation.cc:89
#15 0x00007faeccddf61c in yb::tablet::Operation::Replicated (this=0x3300260, leader_term=leader_term@entry=5) at ../../../../../src/yb/tablet/operations/operation.cc:63
#16 0x00007faeccde5721 in yb::tablet::OperationDriver::ApplyTask (this=this@entry=0x361a500, leader_term=leader_term@entry=5, applied_op_ids=applied_op_ids@entry=0x7faeae852220)
    at ../../../../../src/yb/tablet/operations/operation_driver.cc:442
#17 0x00007faeccde5add in yb::tablet::OperationDriver::ApplyOperation (this=this@entry=0x361a500, leader_term=leader_term@entry=5, applied_op_ids=applied_op_ids@entry=0x7faeae852220)
    at ../../../../../src/yb/tablet/operations/operation_driver.cc:421
#18 0x00007faeccde64dc in yb::tablet::OperationDriver::ReplicationFinished (this=0x361a500, status=..., leader_term=5, applied_op_ids=0x7faeae852220) at ../../../../../src/yb/tablet/operations/operation_driver.cc:375
#19 0x00007faecb6e3089 in operator() (__args#2=0x7faeae852220, __args#1=5, __args#0=..., this=<optimized out>)
    at /home/yugabyte/yb-software/yugabyte-2.1.3.0-b22-centos-x86_64/linuxbrew-xxxxxxxxxxxxx/Cellar/gcc/5.5.0_4/include/c++/5.5.0/functional:2267
#20 yb::consensus::ConsensusRound::NotifyReplicationFinished (this=<optimized out>, status=..., leader_term=leader_term@entry=5, applied_op_ids=applied_op_ids@entry=0x7faeae852220) at ../../../../../src/yb/consensus/consensus.cc:70
#21 0x00007faecb738a68 in yb::consensus::ReplicaState::NotifyReplicationFinishedUnlocked (this=this@entry=0x3ddf440, round=..., status=..., leader_term=leader_term@entry=5, applied_op_ids=applied_op_ids@entry=0x7faeae852220)
    at ../../../../../src/yb/consensus/replica_state.cc:1261
#22 0x00007faecb73e6fe in yb::consensus::ReplicaState::ApplyPendingOperationsUnlocked (this=this@entry=0x3ddf440, committed_op_id=..., could_stop=..., could_stop@entry=...) at ../../../../../src/yb/consensus/replica_state.cc:860
#23 0x00007faecb73f1ef in yb::consensus::ReplicaState::AdvanceCommittedOpIdUnlocked (this=this@entry=0x3ddf440, committed_op_id=..., could_stop=...) at ../../../../../src/yb/consensus/replica_state.cc:797
#24 0x00007faecb73f7bf in yb::consensus::ReplicaState::UpdateMajorityReplicatedUnlocked (this=0x3ddf440, majority_replicated=..., committed_op_id=committed_op_id@entry=0x7faeae8526c0,
    committed_op_id_changed=committed_op_id_changed@entry=0x7faeae85248f) at ../../../../../src/yb/consensus/replica_state.cc:711
#25 0x00007faecb71973b in yb::consensus::RaftConsensus::UpdateMajorityReplicated (this=0x32c9c30, majority_replicated_data=..., committed_op_id=0x7faeae8526c0) at ../../../../../src/yb/consensus/raft_consensus.cc:1051
#26 0x00007faecb6fcf6e in yb::consensus::PeerMessageQueue::NotifyObserversOfMajorityReplOpChangeTask (this=0x329fb00, majority_replicated_data=...) at ../../../../../src/yb/consensus/consensus_queue.cc:1296
#27 0x00007faec3d60794 in yb::ThreadPool::DispatchThread (this=0x2f82e00, permanent=false) at ../../../../../src/yb/util/threadpool.cc:608
#28 0x00007faec3d5ce9f in operator() (this=0x35cf378) at /home/yugabyte/yb-software/yugabyte-2.1.3.0-b22-centos-x86_64/linuxbrew-xxxxxxxxxxxxx/Cellar/gcc/5.5.0_4/include/c++/5.5.0/functional:2267
#29 yb::Thread::SuperviseThread (arg=0x35cf320) at ../../../../../src/yb/util/thread.cc:744
#30 0x00007faebf4a2694 in start_thread (arg=0x7faeae853700) at pthread_create.c:333
#31 0x00007faebebdf41d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

2/3 of the masters in the quorum were stuck like this.

**Comment by bmatican** [comment]
Previous internal slack link for more details: https://yugabyte.slack.com/archives/C4K1838GL/p1585276064040600

**Comment by bmatican** [comment]
Discussed with Sergei that he'd look into it.

**Comment by bmatican** [comment]
Confirmed that this is fixed now!
