### ISSUE TITLE
[YCQL] Using DataGrip to get schema info results in - [localhost/127.0.0.1:53315] Connection has been closed.

### ISSUE THREAD

**Issue by z0mb1ek** [yugabyte/yugabyte-db#4196]
Jira Link: [DB-4675](https://yugabyte.atlassian.net/browse/DB-4675)
Hi. Cannot get schemas for database.
<img width="804" alt="Screenshot 2020-04-12 at 18 37 53" src="https://user-images.githubusercontent.com/1172005/79073006-bfc97b00-7cec-11ea-8c5d-1863cef740b4.png">

**Comment by z0mb1ek** [comment]
Connection is ok
<img width="800" alt="Screenshot 2020-04-12 at 18 38 44" src="https://user-images.githubusercontent.com/1172005/79073028-dd96e000-7cec-11ea-8708-8e889beee9d0.png">

**Comment by kmuthukk** [comment]
@z0mb1ek 

1) To confirm, you are using this with YB version of drivers or Apache Cassandra drivers?

2) Looks like the yb-tserver process might have crashed. We'll need to look at the yb-tserver log files to see if there's a *FATAL, *.err or core file; that should give us clues.

**Comment by z0mb1ek** [comment]
@kmuthukk 
1. has YB jdbc driver for YCQL? Datagrip can use only jdbs
<img width="565" alt="Screenshot 2020-04-12 at 19 38 36" src="https://user-images.githubusercontent.com/1172005/79074473-4da96400-7cf5-11ea-8c15-45ec4b67d4ef.png">

**Comment by z0mb1ek** [comment]
@kmuthukk 
2. log file has

> E0412 16:42:52.774022   107 process_context.cc:180] SQL Error: Object Not Found
SELECT * FROM system.peers_v2
              ^^^^^^^^^^^^^^^
E0412 16:42:52.774062   107 process_context.cc:180] SQL Error: Server Error. Unknown keyspace/cf pair (system.peers_v2)
SELECT * FROM system.peers_v2
^^^^^^

**Comment by psudheer21** [comment]
The error seems to be correc here:
"Unknown keyspace/cf pair (system.peers_v2)"

 based on the generic cassandra driver here:
https://github.com/datastax/java-driver/blob/4.x/core/src/main/java/com/datastax/oss/driver/internal/core/metadata/DefaultTopologyMonitor.java#L186

But the driver used here is the CassandraJDbc driver. Shouldn't that be done here?

**Comment by z0mb1ek** [comment]
I think driver is here https://github.com/DataGrip/cassandra-jdbc-driver/releases

**Comment by z0mb1ek** [comment]
any news? don't want to buy table plus(

**Comment by psudheer21** [comment]
I didn't get time to look at this. I will get to it ASAP and get you more info..

**Comment by psudheer21** [comment]
So looks like this is the issue that is happening on the Datagrip side:

[localhost/127.0.0.1:9042] Connection has been closed                                                                                                                                                                                         
The SQL statement:                                                                                                                                                                                                                            
SELECT keyspace_name, durable_writes, toJson(replication) as replication                                                                                                                                                                      
FROM system_schema.keyspaces

is failing with the stack trace and the log message as:
`2020-04-26 18:54:49,333 [ 399404]   WARN - ution.rmi.RemoteProcessSupport - at com.intellij.execution.rmi.RemoteServer.start(RemoteServer.java:93)                                                                                            
2020-04-26 18:54:49,333 [ 399404]   WARN - ution.rmi.RemoteProcessSupport - at com.intellij.database.remote.RemoteJdbcServerBase.setupAndStart(RemoteJdbcServerBase.java:19)                                                                  
2020-04-26 18:54:49,333 [ 399404]   WARN - ution.rmi.RemoteProcessSupport - at com.intellij.database.remote.RemoteJdbcServer.main(RemoteJdbcServer.java:14)                                                                                   
2020-04-26 18:54:49,333 [ 399404]   WARN - ution.rmi.RemoteProcessSupport - The cook failed to start due to java.net.ConnectException: Connection refused (Connection refused)                                                                
2020-04-26 18:54:49,660 [ 399731]   WARN - ution.rmi.RemoteProcessSupport - SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".                                                                                                  
2020-04-26 18:54:49,660 [ 399731]   WARN - ution.rmi.RemoteProcessSupport - SLF4J: Defaulting to no-operation (NOP) logger implementation                                                                                                     
2020-04-26 18:54:49,661 [ 399732]   WARN - ution.rmi.RemoteProcessSupport - SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.                                                                                
2020-04-26 18:54:49,702 [ 399773]   WARN - ution.rmi.RemoteProcessSupport - Apr 27, 2020 1:54:49 AM com.dbschema.CassandraClientURI createCluster                                                                                             
2020-04-26 18:54:49,702 [ 399773]   WARN - ution.rmi.RemoteProcessSupport - INFO: sslenabled: false                                                                                                                                           
2020-04-26 18:54:50,194 [ 400265]   WARN - lij.database.util.ErrorHandler - [localhost/127.0.0.1:9042] Connection has been closed                                                                                                             
[localhost/127.0.0.1:9042] Connection has been closed                                                                                                                                                                                         
The SQL statement:                                                                                                                                                                                                                            
SELECT keyspace_name, durable_writes, toJson(replication) as replication                                                                                                                                                                      
FROM system_schema.keyspaces                                                                                                                                                                                                                  
                                                                                                                                                                                                                                              
        at com.intellij.database.remote.jdba.jdbc.dialects.CassandraExceptionRecognizer.recognizeSpecificException(CassandraExceptionRecognizer.java:28)                                                                                      
        at com.intellij.database.remote.jdba.jdbc.BaseExceptionRecognizer.recognizeException(BaseExceptionRecognizer.java:44)                                                                                                                 
        at com.intellij.database.remote.jdba.jdbc.JdbcIntermediateSession.recognizeException(JdbcIntermediateSession.java:387)                                                                                                                
        at com.intellij.database.remote.jdba.jdbc.JdbcIntermediateSimpleSeance.<init>(JdbcIntermediateSimpleSeance.java:27)                                                                                                                   
        at com.intellij.database.remote.jdba.jdbc.JdbcIntermediateSession.openSimpleStatementSeance(JdbcIntermediateSession.java:138)                                                                                                         
        at com.intellij.database.remote.jdba.jdbc.JdbcIntermediateSession.openSeance(JdbcIntermediateSession.java:126)                                                                                                                        
        at com.intellij.database.remote.jdba.jdbc.dialects.CassandraIntermediateSession.openSeance(CassandraIntermediateSession.java:38)                                                                                                      
        at com.intellij.database.remote.jdba.jdbc.dialects.CassandraIntermediateSession.openSeance(CassandraIntermediateSession.java:16)                                                                                                      
        at com.intellij.database.remote.jdba.impl.RemoteSessionImpl.openSeance(RemoteSessionImpl.java:38)                                                                                                                                     
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)                                                                                                                                                     
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)                                                                                                                                   
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)                                                                                                                           
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)                                                                                                                                                                         
        at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:359)                                                                                                                                                       
        at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)                                                                                                                                                                     
        at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)                                                                                                                                                                     
        at java.base/java.security.AccessController.doPrivileged(Native Method)                                                                                                                                                               
        at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)                                                                                                                                                               
        at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:562)                                                                                                                                                  
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:796)                                                                                                                                          
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:677)                                                                                                                                  
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:676)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
`

**Comment by psudheer21** [comment]
Going to debug this a bit more and figure out what are the fields they are expecting.

**Comment by litone01** [comment]
Hi, can I kindly check if there is an update for this issue?  Many thanks!

**Comment by bencurio** [comment]
Interesting, I can run this query from the DataGrip console without the `toJson()` function:

```cql
SELECT keyspace_name, durable_writes, replication as replication FROM system_schema.keyspaces;
```

![image](https://github.com/yugabyte/yugabyte-db/assets/7604637/2cf60ccb-129f-4820-b292-ac6517c615d3)

When I add `toJson()`, I get this error message:

<img width="671" alt="image" src="https://github.com/yugabyte/yugabyte-db/assets/7604637/0990cfc5-66f8-4d48-9ba7-1b2accc87403">


+1:

```log
==> yb-tserver.WARNING <==
W0503 18:54:55.304661  4896 cql_processor.cc:387] Unsupported driver option DRIVER_NAME = DataStax Java Driver
              ^^^^^^^^^^^^^^^
```

**Comment by bencurio** [comment]
Hmm... I was able to get it working with this driver, but the fields still don't load.

https://mvnrepository.com/artifact/com.yugabyte/cassandra-jdbc-wrapper

**Comment by oskoi** [comment]
Hi!
I patched DataGrip Cassandra driver https://github.com/oskoi/cassandra-jdbc-driver .
You can download jar files from release https://github.com/oskoi/cassandra-jdbc-driver/releases/tag/yb-4.15 .
And then update driver paths to this files.

<img width="1798" alt="Image" src="https://github.com/user-attachments/assets/f2ac5db6-f5b6-4fd0-baec-1333b71a1e97" />
