### ISSUE TITLE
[YCQL] YugaByte doesn't work with recent Spring Data Cassandra that uses Cassandra driver 4.6

### ISSUE THREAD

**Issue by lhotari** [yugabyte/yugabyte-db#4390]
The upcoming Spring Boot version 2.3.0 defaults to Spring Data Cassandra version that uses Cassandra driver 4.6 .

*Expected behavior*

YugaByte YCQL should support Spring Boot 2.3.0 and Spring Data Cassandra out-of-the-box.

*Actual behavior*

Starting a Spring Boot application fails when it's using YugaByte YCQL.

The failure message is "Can't find referenced user type jsonb"

here's a cleaned up stack trace showing the exception:
```
Failed to load ApplicationContext
java.lang.IllegalStateException: Failed to load ApplicationContext
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:132)
...
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'cassandraSessionFactory' defined in class path resource [org/springframework/boot/autoconfigure/data/cassandra/CassandraDataAutoConfiguration.class]: Invocation of init method failed; nested exception is java.lang.IllegalStateException: Can't find referenced user type jsonb
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1796)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:595)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:876)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
...
Caused by: java.lang.IllegalStateException: Can't find referenced user type jsonb
	at com.datastax.oss.driver.internal.core.metadata.schema.parsing.DataTypeCqlNameParser.parse(DataTypeCqlNameParser.java:83)
	at com.datastax.oss.driver.internal.core.metadata.schema.parsing.DataTypeCqlNameParser.parse(DataTypeCqlNameParser.java:50)
	at com.datastax.oss.driver.internal.core.metadata.schema.parsing.TableParser.parseTable(TableParser.java:170)
	at com.datastax.oss.driver.internal.core.metadata.schema.parsing.CassandraSchemaParser.parseTables(CassandraSchemaParser.java:178)
	at com.datastax.oss.driver.internal.core.metadata.schema.parsing.CassandraSchemaParser.parseKeyspace(CassandraSchemaParser.java:129)
	at com.datastax.oss.driver.internal.core.metadata.schema.parsing.CassandraSchemaParser.parse(CassandraSchemaParser.java:75)
	at com.datastax.oss.driver.internal.core.metadata.MetadataManager$SingleThreaded.parseAndApplySchemaRows(MetadataManager.java:484)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	... 1 more
```

*Workaround*

By debugging the issue I found out that setting these system properties will get the application started:
```
System.setProperty("datastax-java-driver.advanced.metadata.schema.enabled", "false");
System.setProperty("datastax-java-driver.advanced.metadata.schema.refreshed-keyspaces.0", "refresh_disabled");
```
Documentation for the config properties is in https://docs.datastax.com/en/developer/java-driver/4.6/manual/core/metadata/schema/#enabling-disabling .

The second system property is required since Spring Data Cassandra explicitly calls `CqlSession.refreshSchema()` which triggers the schema refresh. By limiting the keyspaces, no `jsonb` column types are met, so the error doesn't show up. It normally finds the `jsonb` column type in a `metrics` system table.

*Notes*
YugaByte 2.1.3+ is required since it includes fix #3862 which is required by Cassandra 4.6 driver.

**Comment by rkarthik007** [comment]
I believe @nchandrappa and @m-iancu are looking into this.

**Comment by nchandrappa** [comment]
Upgrading `cassandra-java-driver` from `3.x` to `4.x` requires upgrading the existing iTest setup as there are major API change with `4.x`. Since there are many users still using 3.x driver, we'll need to maintain the iTests for both versions. Gradually we'll refactor the iTests to 4.x as more users adopt `4.x` driver. In order to expedite the effort for upgrading 4.x, we'll create a new set of test cases for just testing the compatibility with `spring-data-cassandra` project.  

## Re-applying YugabyteDB specific changes to 4.x driver

### Task 1:

- YB local reads: PartitionMetadata.java, ControlConnection.java
- YB Load balancer policy: PartitionAwarePolicy.java, Cluster.java, ConsistencyLevel.java, QueryOptions.java, Statement.java
- JSONB related changes
- Port over the classes from `com.yugabyte.*` to driver 4.x

### Task 2:

- Add unit test cases for YB specific changes 

### Task 3:

- Add iTests in YugabyteDB java projects
- Create Spring Data Cassandra related iTest for 4.x related changes

**Comment by nchandrappa** [comment]
In 3.x, We are maintaining the `PartitionMetadata` of tables in `Cluster` object which is refreshed during cluster state change (Like node up/down, token map update) and also during schema refresh. 

```
Cluster.java -> requiresPartitionMap (state)

PartitionMetadata.java -> ControlConnection.java (refreshPartitionMap) 
					-> refreshNodeListAndTokenMap ()
                                        -> refreshSchema()

```

In 4.x, Internal administrative tasks implementation has considerably changed and moved to an event based architecture. Also, `Cluster` object is replaced by `CqlSession` object. We'll need to reapply all the changes to maintain the `PartitionMetadata` in a `CqlSession` object and refresh the `PartitionMetadata` during cluster events.

**Comment by nchandrappa** [comment]
YCQL Java driver `4.6.0-yb-6` released which brings in support for Cassandra driver 4.6.
