### ISSUE TITLE
K8S: Sample apps failed to connect to CQL after scale up and down

### ISSUE THREAD

**Issue by ttyusupov** [yugabyte/yugabyte-db#442]
Steps to reproduce:

- `kubectl apply -f yugabyte-statefulset.yaml`
- Wait until all pods are running: `kubectl get pods`
- Scale up: `kubectl scale statefulset yb-tserver --replicas=4`
- Wait until all pods are running: `kubectl get pods`
- `kubectl exec -it yb-master-0 -- yum -y install java-1.8.0-openjdk-headless.x86_64`
- Run sample app: `kubectl exec -it yb-master-0 -- java -jar /home/yugabyte/java/yb-sample-apps.jar --run_time 5 --workload CassandraKeyValue --nodes yb-tservers.default.svc.cluster.local:9042`
- Scale down: `kubectl scale statefulset yb-tserver --replicas=3`
- Wait until yb-tserver-3 pod is terminated: `kubectl get pods`
- Run sample app again: `kubectl exec -it yb-master-0 -- java -jar /home/yugabyte/java/yb-sample-apps.jar --run_time 5 --workload CassandraKeyValue --nodes yb-tservers.default.svc.cluster.local:9042`

The sample app is failing with the following output:
```
01:41 $ kubectl exec -it yb-master-0 -- java -jar /home/yugabyte/java/yb-sample-apps.jar --run_time 5 --workload CassandraKeyValue --nodes yb-tservers.default.svc.cluster.local:9042
W0815 01:41:13.237092   10958 flags.go:39] run_time is DEPRECATED and will be removed in a future version. Use run-time instead.
W0815 01:41:13.237358   10958 flags.go:39] run_time is DEPRECATED and will be removed in a future version. Use run-time instead.
W0815 01:41:13.237390   10958 flags.go:39] run_time is DEPRECATED and will be removed in a future version. Use run-time instead.
2018-08-14 22:41:14,041 [INFO|com.yugabyte.sample.common.CmdLineOpts|CmdLineOpts] Using a randomly generated UUID : 6667adae-cea5-4340-af76-3d68ca574774
2018-08-14 22:41:14,101 [INFO|com.yugabyte.sample.common.CmdLineOpts|CmdLineOpts] App: CassandraKeyValue
2018-08-14 22:41:14,101 [INFO|com.yugabyte.sample.common.CmdLineOpts|CmdLineOpts] Run time (seconds): 5
2018-08-14 22:41:14,106 [INFO|com.yugabyte.sample.common.CmdLineOpts|CmdLineOpts] Adding node: yb-tservers.default.svc.cluster.local:9042
2018-08-14 22:41:14,127 [INFO|com.yugabyte.sample.common.CmdLineOpts|CmdLineOpts] Num reader threads: 24, num writer threads: 2
2018-08-14 22:41:14,131 [INFO|com.yugabyte.sample.common.CmdLineOpts|CmdLineOpts] Num unique keys to insert: 1000000
2018-08-14 22:41:14,131 [INFO|com.yugabyte.sample.common.CmdLineOpts|CmdLineOpts] Num keys to update: -1000001
2018-08-14 22:41:14,132 [INFO|com.yugabyte.sample.common.CmdLineOpts|CmdLineOpts] Num keys to read: -1
2018-08-14 22:41:14,133 [INFO|com.yugabyte.sample.common.CmdLineOpts|CmdLineOpts] Value size: 0
2018-08-14 22:41:14,134 [INFO|com.yugabyte.sample.common.CmdLineOpts|CmdLineOpts] Restrict values to ASCII strings: false
2018-08-14 22:41:14,137 [INFO|com.yugabyte.sample.common.CmdLineOpts|CmdLineOpts] Perform sanity check at end of app run: false
2018-08-14 22:41:14,138 [INFO|com.yugabyte.sample.common.CmdLineOpts|CmdLineOpts] Table TTL (secs): -1
2018-08-14 22:41:14,139 [INFO|com.yugabyte.sample.common.CmdLineOpts|CmdLineOpts] Local reads: false
2018-08-14 22:41:14,140 [INFO|com.yugabyte.sample.common.CmdLineOpts|CmdLineOpts] Read only load: false
2018-08-14 22:41:14,480 [INFO|com.yugabyte.sample.apps.AppBase|AppBase] Connecting to nodes: yb-tservers.default.svc.cluster.local/172.17.0.6:9042,yb-tservers.default.svc.cluster.local/172.17.0.8:9042,yb-tservers.default.svc.cluster.local/172.17.0.7:9042
Exception in thread "main" com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: yb-tservers.default.svc.cluster.local/172.17.0.7:9042 (com.datastax.driver.core.exceptions.ServerError: An unexpected error occurred server side on yb-tservers.default.svc.cluster.local/172.17.0.7:9042: SQL error: Server Error. yb-tserver-3.yb-tservers.default.svc.cluster.local is an invalid host/ip address: Host not found (authoritative)
SELECT keyspace_name, table_name, start_key, end_key, replica_addresses FROM system.partitions
^^^^^^
 (error -2)), yb-tservers.default.svc.cluster.local/172.17.0.6:9042 (com.datastax.driver.core.exceptions.ServerError: An unexpected error occurred server side on yb-tservers.default.svc.cluster.local/172.17.0.6:9042: SQL error: Server Error. yb-tserver-3.yb-tservers.default.svc.cluster.local is an invalid host/ip address: Host not found (authoritative)
SELECT keyspace_name, table_name, start_key, end_key, replica_addresses FROM system.partitions
^^^^^^
 (error -2)), yb-tservers.default.svc.cluster.local/172.17.0.8:9042 (com.datastax.driver.core.exceptions.ServerError: An unexpected error occurred server side on yb-tservers.default.svc.cluster.local/172.17.0.8:9042: SQL error: Server Error. yb-tserver-3.yb-tservers.default.svc.cluster.local is an invalid host/ip address: Host not found (authoritative)
SELECT keyspace_name, table_name, start_key, end_key, replica_addresses FROM system.partitions
^^^^^^
 (error -2)))
	at com.datastax.driver.core.ControlConnection.reconnectInternal(ControlConnection.java:255)
	at com.datastax.driver.core.ControlConnection.connect(ControlConnection.java:102)
	at com.datastax.driver.core.Cluster$Manager.negotiateProtocolVersionAndConnect(Cluster.java:1623)
	at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:1541)
	at com.datastax.driver.core.Cluster.init(Cluster.java:160)
	at com.datastax.driver.core.Cluster.connectAsync(Cluster.java:331)
	at com.datastax.driver.core.Cluster.connectAsync(Cluster.java:306)
	at com.datastax.driver.core.Cluster.connect(Cluster.java:248)
	at com.yugabyte.sample.apps.AppBase.createCassandraClient(AppBase.java:198)
	at com.yugabyte.sample.apps.AppBase.getCassandraClient(AppBase.java:122)
	at com.yugabyte.sample.apps.AppBase.createTablesIfNeeded(AppBase.java:420)
	at com.yugabyte.sample.Main.run(Main.java:165)
	at com.yugabyte.sample.Main.main(Main.java:240)
command terminated with exit code 1
```

**Comment by kriteshranjan** [comment]
Closing this issue based on AI validation. cc: @m-iancu , @VamsidharGunturu

**Comment by kriteshranjan** [comment]
AI validation notes (`yb-issue-442-analysis.md`):

# Analysis: yugabyte/yugabyte-db#442 (no Jira cross-link)

Issue: "K8S: Sample apps failed to connect to CQL after scale up and down"
(filed 2018-08-14, kind/bug, still OPEN, zero comments).
Reviewed 2026-08-15/16 against master `b89bc62335` (2026-08-11).

## Verdict
VALIDATED as filed (era root cause pinned in source with exact signature match) —
mechanism FIXED on master by `e7964086be` (2021-10-07, #9898); shipped in 2.8.0+ /
2.11.0+. Master NOT affected. Recommend closing as Fixed.

## Failure signature (from issue body)
```
com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed
  ... ServerError: ... SQL error: Server Error. yb-tserver-3.yb-tservers.default.svc.cluster.local
  is an invalid host/ip address: Host not found (authoritative)
SELECT keyspace_name, table_name, start_key, end_key, replica_addresses FROM system.partitions
```
Note: the failing query is `system.partitions` (driver control-connection init), not
`system.peers`.

## Root cause (era: 2018-08-14, sha `2a4fb09169`)
- `src/yb/master/yql_partitions_vtable.cc:76-77` (era):
  ```cpp
  InetAddress addr;
  RETURN_NOT_OK(addr.FromString(DesiredHostPort(replica.ts_info(), CloudInfoPB()).host()));
  ```
  Inside `YQLPartitionsVTable::RetrieveData`'s per-replica loop. `RETURN_NOT_OK` means
  ONE unresolvable replica hostname aborts generation of the ENTIRE `system.partitions`
  vtable; the SELECT returns a Server Error to every CQL client on every node.
- `src/yb/util/net/inetaddress.cc:46` (era): `InetAddress::FromString` → `ResolveInternal`
  produces exactly `"$0 is an invalid host/ip address: $1"` with boost resolver's
  "Host not found (authoritative)" — verbatim match to the reported error.
- Trigger chain: `kubectl scale --replicas=3` deletes pod `yb-tserver-3` without
  decommission → its headless-service DNS record vanishes immediately, but the master's
  tablet locations still list it as a replica until Raft-follower eviction
  (`follower_unavailable_considered_failed_sec`, default 900 — HEAD
  `src/yb/consensus/consensus_queue.cc:84`). During that window every
  `system.partitions` read fails on all endpoints → Datastax driver control connection
  cannot initialize → `NoHostAvailableException`. Deterministic for ~15 min after any
  k8s scale-down (or any permanent node removal whose DNS dies with it).

## Fix (present on master `b89bc62335`)
`e7964086be` "[#9898] docdb: Fix queries on system.partitions when unable to resolve
some addresses" (2021-10-07):
- `src/yb/master/yql_partitions_vtable.cc:176-184` — DNS lookups resolved as futures;
  failures log `"Unable to resolve host: ..."` (WARN, throttled) and are dropped from
  `dns_results` instead of failing the query.
- `src/yb/master/yql_partitions_vtable.cc:258-263` — unresolved replica is omitted from
  the `replica_addresses` map; row still emitted; SELECT succeeds.
- Regression test: `src/yb/integration-tests/cql-test.cc:370-389`
  `CqlThreeMastersTest.HostnameResolutionFailureInYqlPartitionsTable` — forces
  resolution failure for a downed node's hostname, asserts `SELECT * FROM
  system.partitions` succeeds with that address absent (3 → 2 addrs).
- Same hardening exists for `system.peers`: only live tservers listed
  (`src/yb/master/yql_peers_vtable.cc:59-66`, `GetSortedLiveDescriptors`) and
  resolution failures warn+skip the row (`yql_peers_vtable.cc:115-127`); test
  `src/yb/yql/cql/ql/test/ql-query-test.cc:1602-1622` asserts an invalid-hostname
  tserver never appears in `system.peers`.
- First release tags containing the fix: `2.8.1_FINAL`/`2.8_FINAL`, `2.11.0_FINAL`
  (`git tag --contains e7964086be`); absent from 2.4/2.6. All currently supported
  release lines descend from it.

## Trigger matrix (source-derived prediction vs observed evidence)
| # | condition | predicted | observed |
|---|-----------|-----------|----------|
| 1 | era (≤2.6): 1 replica host unresolvable | whole `system.partitions` SELECT fails: "invalid host/ip address" | era `yql_partitions_vtable.cc:76-77` `RETURN_NOT_OK`; error string at era `inetaddress.cc:46` — verbatim signature match |
| 2 | era: all replica hosts resolvable | SELECT OK | same loop; error path only on resolver `ec` |
| 3 | master/2.8+/2.11+: replica host unresolvable | SELECT OK; replica omitted; WARNING logged | `yql_partitions_vtable.cc:176-184,258-263`; upstream test `cql-test.cc:370-389` passes in CI |
| 4 | master: dead/unresolvable tserver in `system.peers` | not listed / skipped | `yql_peers_vtable.cc:59-66,115-127`; test `ql-query-test.cc:1602-1622` |
| 5 | k8s scale-down staleness window (master) | replica stays listed ≤900s but is omitted from vtable when DNS dead; app connects | `consensus_queue.cc:84` (eviction) + matrix row 3 |

Observed column is static-analysis + upstream-regression-test evidence: live repro
intentionally skipped (multi-node k8s StatefulSet scenario; dispatch budget excluded
containers/builds).

## Reproduction
N/A (live) — requires a k8s StatefulSet cluster plus a 2018-era (≤2.6 / 1.x) image;
modern images no longer contain the defect. Rerunnable evidence commands (repo root):
```sh
git log -1 --format='%h %ad %s' --date=short e7964086be
git show 2a4fb09169:src/yb/master/yql_partitions_vtable.cc | sed -n '72,88p'   # era RETURN_NOT_OK
git show 2a4fb09169:src/yb/util/net/inetaddress.cc | sed -n '40,50p'           # exact error string
sed -n '176,184p;255,264p' src/yb/master/yql_partitions_vtable.cc              # HEAD warn+skip
sed -n '370,389p' src/yb/integration-tests/cql-test.cc                          # regression test
```
Optional dynamic confirmation (out of budget):
`./yb_build.sh release --cxx-test cql-test --gtest_filter CqlThreeMastersTest.HostnameResolutionFailureInYqlPartitionsTable`

## Versions tested
- Era source at issue date: sha `2a4fb09169` (2018-08-14) — defect present.
- Master `b89bc62335` (2026-08-11) — defect absent; master affected: NO.
- Fix availability: 2.8.0+/2.11.0+ per `git tag --contains e7964086be`.

## Proposed fix direction
None — already fixed upstream (`e7964086be`, with regression tests). Action: close
#442 as fixed, referencing #9898/`e7964086be`. Residual (by design, not this bug):
after an un-blacklisted scale-down the cluster stays under-replicated until
follower eviction (~900s); docs recommend blacklist-driven scale-down.

## Test strategy
Covered upstream: `CqlThreeMastersTest.HostnameResolutionFailureInYqlPartitionsTable`
(`src/yb/integration-tests/cql-test.cc:370`) and the peers-table invalid-host test
(`src/yb/yql/cql/ql/test/ql-query-test.cc:1602`). No new tests needed.

## Confidentiality check
Clean — only public issue text, upstream code/commits, k8s example hostnames from the
public report. No customer data, PII, secrets, or internal refs.
