### ISSUE TITLE
[docdb][test] UndefinedBehaviorSanitizer in CppCassandraDriverTest.BigQueryExpr

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#4513]
```
/opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20200424080731-4c3da9360f-centos/src/cassandra-cpp-driver-2.9.0-yb-6/src/jenkins_hash.cpp:97:10: runtime error: load of misaligned address 0x621000232904 for type 'const uint64_t' (aka 'const unsigned long'), which requires 8 byte alignment
0x621000232904: note: pointer points here
  01 00 00 00 35 49 73 36  52 34 33 71 4b 31 4e 50  62 37 70 34 69 39 4c 50  37 46 4c 55 53 76 4a 6e
              ^
    #0 0x7f27704a3873 in cass::Word64At(char const*) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20200424080731-4c3da9360f-centos/src/cassandra-cpp-driver-2.9.0-yb-6/src/jenkins_hash.cpp:97:10
    #1 0x7f27704a3873 in cass::Hash64StringWithSeed(char const*, unsigned int, unsigned long) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20200424080731-4c3da9360f-centos/src/cassandra-cpp-driver-2.9.0-yb-6/src/jenkins_hash.cpp:127
    #2 0x7f2770651aa3 in cass::bytes_to_key(char const*, unsigned long) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20200424080731-4c3da9360f-centos/src/cassandra-cpp-driver-2.9.0-yb-6/src/partition_aware_policy.cpp:73:24
    #3 0x7f2770651aa3 in cass::get_hash_key_from_execute(cass::ExecuteRequest const*, int*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20200424080731-4c3da9360f-centos/src/cassandra-cpp-driver-2.9.0-yb-6/src/partition_aware_policy.cpp:123
    #4 0x7f277064fafe in cass::PartitionAwarePolicy::get_hash_code(cass::Request const*, int*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20200424080731-4c3da9360f-centos/src/cassandra-cpp-driver-2.9.0-yb-6/src/partition_aware_policy.cpp:136:12
    #5 0x7f2770655898 in cass::PartitionAwarePolicy::new_query_plan(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, cass::RequestHandler*) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20200424080731-4c3da9360f-centos/src/cassandra-cpp-driver-2.9.0-yb-6/src/partition_aware_policy.cpp:213:9
    #6 0x7f27706f2da8 in cass::RequestHandler::init(cass::Session*) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20200424080731-4c3da9360f-centos/src/cassandra-cpp-driver-2.9.0-yb-6/src/request_handler.cpp:125:53
    #7 0x7f27707567a6 in cass::Session::on_execute(uv_async_s*) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20200424080731-4c3da9360f-centos/src/cassandra-cpp-driver-2.9.0-yb-6/src/session.cpp:823:24
    #8 0x7f276c551644 in uv__async_io /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20200424080731-4c3da9360f-centos/src/libuv-1.23.0/src/unix/async.c:118:5
    #9 0x7f276c5d260a in uv__io_poll /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20200424080731-4c3da9360f-centos/src/libuv-1.23.0/src/unix/linux-core.c:401:11
    #10 0x7f276c553c9e in uv_run /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20200424080731-4c3da9360f-centos/src/libuv-1.23.0/src/unix/core.c:370:5
    #11 0x7f2770780d71 in cass::LoopThread::on_run_internal(void*) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20200424080731-4c3da9360f-centos/src/cassandra-cpp-driver-2.9.0-yb-6/src/loop_thread.hpp:128:5
    #12 0x7f276ed79693 in start_thread /tmp/glibc-20181130-26094-cs1x60/glibc-2.23/nptl/pthread_create.c:333
    #13 0x7f276e8a441c in __clone /tmp/glibc-20181130-26094-cs1x60/glibc-2.23/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:109

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20200424080731-4c3da9360f-centos/src/cassandra-cpp-driver-2.9.0-yb-6/src/jenkins_hash.cpp:97:10 in
```

**Comment by OlegLoginov** [comment]
Error:  cassandra-cpp-driver-2.9.0-yb-6/src/jenkins_hash.cpp:97:10: 
`runtime error: load of misaligned address 0x621000232904 for type 'const uint64_t' (aka 'const unsigned long'), which requires 8 byte alignment`

Code:
```
#define UNALIGNED_LOAD64(_p) (*reinterpret_cast<const uint64_t *>(_p))     <<<<<<<<<

#if defined(JENKINS_LITTLE_ENDIAN) && !defined(NEED_ALIGNED_LOADS)

static inline uint64_t Word64At(const char *ptr) {
  return UNALIGNED_LOAD64(ptr);             <<<<<<<<<<<<<
}
```
The unaligned read is used here for optimization purposes, but it can be disabled by the `NEED_ALIGNED_LOADS` flag.

**Comment by OlegLoginov** [comment]
Possibly it's a 'false-positive'.

**Comment by OlegLoginov** [comment]
Suggested fix:  in cassandra-cpp-driver-2.9.0-yb-6/cmake/modules/CppDriver.cmake 
change line 856
`    set(CASS_DRIVER_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${CASS_DRIVER_CXX_FLAGS} ${WARNING_COMPILER_FLAGS} -Werror")`
into
`    set(CASS_DRIVER_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${CASS_DRIVER_CXX_FLAGS} ${WARNING_COMPILER_FLAGS} -Werror -DNEED_ALIGNED_LOADS")`

**Comment by mbautin** [comment]
@OlegLoginov: the fix sounds good to me. Would you mind updating the driver and sending a pull request to yugabyte-db-thirdparty?

**Comment by OlegLoginov** [comment]
As discussed in Slack - let's just suppress the error. Because this is really unaligned read but aligned function version should be not optimal.

**Comment by bmatican** [comment]
Hey @OlegLoginov seems like now this test is failing with a known issue:
```
WARNING: ThreadSanitizer: data race (pid=14248)
  Read of size 8 at 0x7b1000035790 by thread T38:
    #0 cass::LoadBalancingPolicy::control_connection() /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20200521213813-7f9cce4964-centos/src/cassandra-cpp-driver-2.9.0-yb-6/src/load_balancing.cpp:21:10 (libcassandra.so.2+0xedc5a)
    #1 cass::PartitionAwarePolicy::on_work(cass::PeriodicTask*) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20200521213813-7f9cce4964-centos/src/cassandra-cpp-driver-2.9.0-yb-6/src/partition_aware_policy.cpp:319:15 (libcassandra.so.2+0x133246)
    #2 cass::PeriodicTask::on_work(uv_work_s*) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20200521213813-7f9cce4964-centos/src/cassandra-cpp-driver-2.9.0-yb-6/src/periodic_task.hpp:76:5 (libcassandra.so.2+0xecceb)
    #3 uv__queue_work /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20200521213813-7f9cce4964-centos/src/libuv-1.23.0/src/threadpool.c:259:3 (libuv.so+0xb375)
    #4 worker /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20200521213813-7f9cce4964-centos/src/libuv-1.23.0/src/threadpool.c:83:5 (libuv.so+0xb707)
```

See https://jenkins.dev.yugabyte.com/job/github-yugabyte-db-centos-master-clang-tsan/970/artifact/build/tsan-clang-dynamic-ninja/yb-test-logs/tests-integration-tests__cassandra_cpp_driver-test/CppCassandraDriverTest_BigQueryExpr.log

And in stability it's only TSAN: https://detective-gcp.dev.yugabyte.com/stability/test?class=CppCassandraDriverTest&name=BigQueryExpr

I believe the problem is that we need to disable the LB policy because it is known to be not thread safe? Do you mind doing that and validating it fixes the problem?

**Comment by OlegLoginov** [comment]
That's another issue. https://github.com/yugabyte/yugabyte-db/issues/2854

It's data race on the `session_` field in the LoadBalancingPolicy:
THREAD-1:
```
    #0 cass::LoadBalancingPolicy::control_connection() /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20200521213813-7f9cce4964-centos/src/cassandra-cpp-driver-2.9.0-yb-6/src/load_balancing.cpp:21:10 (libcassandra.so.2+0xedc5a)

ControlConnection* LoadBalancingPolicy::control_connection() {
  return session_ == NULL ? NULL : session_->control_connection();    <<<<< ACCESS to session_
```
THREAD-2:
```
    #0 cass::LoadBalancingPolicy::init_session(cass::Session*) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20200521213813-7f9cce4964-centos/src/cassandra-cpp-driver-2.9.0-yb-6/src/load_balancing.hpp:90:57 (libcassandra.so.2+0x8caae)

  virtual void init_session(Session* session) { session_=session; }   <<<<< SET the session
```

Fix:  'session_' reading/writing should be done with a mutex.

From other hand - that's a pointer reading/writing, so the operation should be atomic, and it's not a problem in fact.

**Comment by mbautin** [comment]
@OlegLoginov: even for a simple pointer, reading/writing it from different threads without synchronization is not a valid solution. You can use e.g.`std::atomic<Session*>`.
