### ISSUE TITLE
[YEDIS] Support for EXEC, WATCH for celery

### ISSUE THREAD

**Issue by rajaiswal** [yugabyte/yugabyte-db#4570]
I am trying to use Yedis on port 6379 as Celery broker and Celery result backend, but whenever I start a worker I get error:

```
[2020-05-23 04:20:55,857: INFO/MainProcess] Connected to redis://localhost:6379//
[2020-05-23 04:20:55,869: INFO/MainProcess] mingle: searching for neighbors
[2020-05-23 04:20:55,873: CRITICAL/MainProcess] Unrecoverable error: ResponseError('EXEC: Unsupported call.')
Traceback (most recent call last):
  File "/Users/myproject/lib/python3.7/site-packages/celery/worker/worker.py", line 205, in start
    self.blueprint.start(self)
  File "/Users/myproject/lib/python3.7/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/Users/myproject/lib/python3.7/site-packages/celery/bootsteps.py", line 369, in start
    return self.obj.start()
  File "/Users/myproject/lib/python3.7/site-packages/celery/worker/consumer/consumer.py", line 318, in start
    blueprint.start(self)
  File "/Users/myproject/lib/python3.7/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/Users/myproject/lib/python3.7/site-packages/celery/worker/consumer/mingle.py", line 40, in start
    self.sync(c)
  File "/Users/myproject/lib/python3.7/site-packages/celery/worker/consumer/mingle.py", line 44, in sync
    replies = self.send_hello(c)
  File "/Users/myproject/lib/python3.7/site-packages/celery/worker/consumer/mingle.py", line 57, in send_hello
    replies = inspect.hello(c.hostname, our_revoked._data) or {}
  File "/Users/myproject/lib/python3.7/site-packages/celery/app/control.py", line 154, in hello
    return self._request('hello', from_node=from_node, revoked=revoked)
  File "/Users/myproject/lib/python3.7/site-packages/celery/app/control.py", line 106, in _request
    pattern=self.pattern, matcher=self.matcher,
  File "/Users/myproject/lib/python3.7/site-packages/celery/app/control.py", line 480, in broadcast
    limit, callback, channel=channel,
  File "/Users/myproject/lib/python3.7/site-packages/kombu/pidbox.py", line 346, in _broadcast
    matcher=matcher)
  File "/Users/myproject/lib/python3.7/site-packages/kombu/pidbox.py", line 302, in _publish
    maybe_declare(self.reply_queue(channel))
  File "/Users/myproject/lib/python3.7/site-packages/kombu/common.py", line 121, in maybe_declare
    return _maybe_declare(entity, channel)
  File "/Users/myproject/lib/python3.7/site-packages/kombu/common.py", line 161, in _maybe_declare
    entity.declare(channel=channel)
  File "/Users/myproject/lib/python3.7/site-packages/kombu/entity.py", line 609, in declare
    self._create_queue(nowait=nowait, channel=channel)
  File "/Users/myproject/lib/python3.7/site-packages/kombu/entity.py", line 618, in _create_queue
    self.queue_declare(nowait=nowait, passive=False, channel=channel)
  File "/Users/myproject/lib/python3.7/site-packages/kombu/entity.py", line 653, in queue_declare
    nowait=nowait,
  File "/Users/myproject/lib/python3.7/site-packages/kombu/transport/virtual/base.py", line 532, in queue_declare
    return queue_declare_ok_t(queue, self._size(queue), 0)
  File "/Users/myproject/lib/python3.7/site-packages/kombu/transport/redis.py", line 775, in _size
    sizes = pipe.execute()
  File "/Users/myproject/lib/python3.7/site-packages/redis/client.py", line 3967, in execute
    return execute(conn, stack, raise_on_error)
  File "/Users/myproject/lib/python3.7/site-packages/redis/client.py", line 3860, in _execute_transaction
    response = self.parse_response(connection, '_')
  File "/Users/myproject/lib/python3.7/site-packages/redis/client.py", line 3926, in parse_response
    self, connection, command_name, **options)
  File "/Users/myproject/lib/python3.7/site-packages/redis/client.py", line 892, in parse_response
    response = connection.read_response()
  File "/Users/myproject/lib/python3.7/site-packages/redis/connection.py", line 752, in read_response
    raise response
redis.exceptions.ResponseError: EXEC: Unsupported call.
```
Sometimes it is 
```
redis.exceptions.ResponseError: WATCH: Unsupported call.
```

The only other help regarding celery integration I could find was here: https://github.com/yugabyte/yugabyte-db/issues/1183
which is closed which leads me to believe celery integration is working. Am I configuring it wrong?

**Comment by kmuthukk** [comment]
hi @rajaiswal --

1. Yes, we don't support the Redis' transaction capabilities (EXEC, WATCH, etc.) in YEDIS. 

2. Can you tell a bit more about your use case -- is persistence & clustering (multi-node scaling) important, or are you looking more for a in-memory caching solution? If the latter, the using vanilla Redis would be more optimal.

3. Also, please note that YEDIS is not being actively worked on right now. 

* The list of supported commands in YEDIS is documented here: https://docs.yugabyte.com/latest/yedis/api/. 

* And the note in this section https://docs.yugabyte.com/latest/yedis/ explains current limitations and points to consider.

**Comment by rajaiswal** [comment]
@kmuthukk Thanks for the detailed response and the links. Yes my goal was to test using Yedis as a broker for Celery. Guess that won't work for now, will resume using vanilla Redis. Will close Issue.
