### ISSUE TITLE
yb-ctl uses a pgrep option that is not present on Amazon Linux

### ISSUE THREAD

**Issue by mbautin** [yugabyte/yugabyte-db#4573]
```
$ ~/yugabyte-2.1.6.0/bin/yb-ctl --data_dir /mnt/ramdisk/yugabyte-data --replication_factor 3 create
Creating cluster.
pgrep: invalid option -- '-'
Usage: pgrep [-flvx] [-d DELIM] [-n|-o] [-P PPIDLIST] [-g PGRPLIST] [-s SIDLIST]
	[-u EUIDLIST] [-U UIDLIST] [-G GIDLIST] [-t TERMLIST] [PATTERN]
Traceback (most recent call last):
  File "/home/ec2-user/yugabyte-2.1.6.0/bin/yb-ctl", line 2007, in <module>
    control.run()
  File "/home/ec2-user/yugabyte-2.1.6.0/bin/yb-ctl", line 1984, in run
    self.args.func()
  File "/home/ec2-user/yugabyte-2.1.6.0/bin/yb-ctl", line 1738, in create_cmd_impl
    self.pre_create_checks()
  File "/home/ec2-user/yugabyte-2.1.6.0/bin/yb-ctl", line 1459, in pre_create_checks
    pids = self.for_all_daemons(self.get_pid)
  File "/home/ec2-user/yugabyte-2.1.6.0/bin/yb-ctl", line 1716, in for_all_daemons
    fn(DaemonId(daemon_type, daemon_index)))
  File "/home/ec2-user/yugabyte-2.1.6.0/bin/yb-ctl", line 1239, in get_pid
    raise RuntimeError("Error during pgrep: {}".format(e.output))
RuntimeError: Error during pgrep:
Viewing file /tmp/tmpd9bydD:
^^^ Encountered errors ^^^
```

**Comment by yaducool** [comment]
I am having the same issue in CentOS 6

$ ./yb-ctl create --replication_factor 3 --num_shards_per_tserver 4
Creating cluster.
pgrep: invalid option -- '-'
Usage: pgrep [-flvx] [-d DELIM] [-n|-o] [-P PPIDLIST] [-g PGRPLIST] [-s SIDLIST]
	[-u EUIDLIST] [-U UIDLIST] [-G GIDLIST] [-t TERMLIST] [PATTERN]
Traceback (most recent call last):
  File "./yb-ctl", line 2023, in <module>
    control.run()
  File "./yb-ctl", line 2000, in run
    self.args.func()
  File "./yb-ctl", line 1754, in create_cmd_impl
    self.pre_create_checks()
  File "./yb-ctl", line 1475, in pre_create_checks
    pids = self.for_all_daemons(self.get_pid)
  File "./yb-ctl", line 1732, in for_all_daemons
    fn(DaemonId(daemon_type, daemon_index)))
  File "./yb-ctl", line 1253, in get_pid
    raise RuntimeError("Error during pgrep: {}".format(e.output))
RuntimeError: Error during pgrep: 
Viewing file /tmp/tmpBbANCb:
^^^ Encountered errors ^^^

**Comment by bmatican** [comment]
we've moved the getting started and dev flow to yugabyted
