### ISSUE TITLE
[TPCC] TakeTransaction timeout for 100 warehouse workload

### ISSUE THREAD

**Issue by ndeodhar** [yugabyte/yugabyte-db#4603]
Running TPCC workload on 100 warehouses errors out with
`TakeTransaction RPC timed out` errors within a few seconds of starting the workload.

We need to understand what the bottleneck is and come up with a solution.

Some context on the workload:
100 warehouse workload uses 1000 connections. The workload first sets up 1000 YSQL/postgres connections and then starts executing transactions using those connections.
It's possible that too many transactions are starting up concurrently and we are not able to handle the load.

**Comment by mbautin** [comment]
I could not reproduce this error using TPC-C, but ran into it while running a different workload:

```
79467 [Thread-1] INFO com.yugabyte.sample.common.metrics.MetricsTracker  - Read: 0.00 ops/sec (0.00 ms/op), 0 total ops  |  Write: 0.60 ops/sec (25204.33 ms/op), 3 total ops  |  Uptime: 30016 ms |
79657 [Thread-62] ERROR com.yugabyte.sample.apps.MultiTableMultiIndexInserts  - Write failed with error
java.sql.BatchUpdateException: Batch entry 0 INSERT INTO Schema1_a1 VALUES ('00000000-0009-27c0-0000-0000000927c1'::uuid, '00000000-0009-27c2-0000-0000000927c3'::uuid, '00000000-0009-27c4-0000-0000000927c5'::uuid, 600000, 600001) was aborted: ERROR: Timed out: TakeTransaction RPC (request call id 115) to a.b.c.d:9100 timed out after 10.000s  Call getNextException to see other errors in the batch.
	at org.postgresql.jdbc.BatchResultHandler.handleCompletion(BatchResultHandler.java:166)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:490)
	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:835)
	at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1556)
	at com.yugabyte.sample.apps.MultiTableMultiIndexInserts.doWrite(MultiTableMultiIndexInserts.java:440)
	at com.yugabyte.sample.apps.AppBase.performWrite(AppBase.java:711)
	at com.yugabyte.sample.common.IOPSThread.run(IOPSThread.java:87)
Caused by: org.postgresql.util.PSQLException: ERROR: Timed out: TakeTransaction RPC (request call id 115) to a.b.c.d:9100 timed out after 10.000s
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2178)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:479)
	... 5 more
```

Details of the workload:

java -jar ~/yb-sample-apps/target/yb-sample-apps.jar --workload MultiTableMultiIndexInserts --nodes ... --num_threads_read 0 --num_threads_write 384 --num_writes -1 --run_time 1800

Cluster: 3 x n1-standard-4 on GCP

TServer flags:

tserver_tcmalloc_max_total_thread_cache_bytes 3221225472
priority_thread_pool_size 10
retryable_rpc_single_call_timeout_ms 60000
