### ISSUE TITLE
The USER variable may be unset

### ISSUE THREAD

**Issue by mbautin** [yugabyte/yugabyte-db#4607]
./build-support/common-build-env.sh: line 1580: USER: unbound variable

**Comment by mbautin** [comment]
We might actually get a segfault in tserver if USER is unset.

```
Core was generated by `/opt/yb-install/yugabyte-2.2.1.0/bin/yb-tserver'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  strlen () at ../sysdeps/x86_64/strlen.S:106
106	../sysdeps/x86_64/strlen.S: No such file or directory.
(gdb)
(gdb)
(gdb) where
#0  strlen () at ../sysdeps/x86_64/strlen.S:106
#1  0x00007fca6eb0cfc4 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::assign(char const*) () from /opt/yb-install/yugabyte-2.2.1.0/linuxbrew/lib/libstdc++.so.6
#2  0x00007fca72be68a5 in google::glog_internal_namespace_::MyUserNameInitializer() () from /opt/yb-install/yugabyte-2.2.1.0/lib/yb-thirdparty/libglog.so.0
#3  0x00007fca7f0fcd5a in call_init (l=<optimized out>, argc=argc@entry=1, argv=argv@entry=0x7ffd93785088, env=env@entry=0x7ffd93785098) at dl-init.c:72
#4  0x00007fca7f0fce43 in call_init (env=0x7ffd93785098, argv=0x7ffd93785088, argc=1, l=<optimized out>) at dl-init.c:30
#5  _dl_init (main_map=0x7fca7f312168, argc=1, argv=0x7ffd93785088, env=0x7ffd93785098) at dl-init.c:120
#6  0x00007fca7f0ef1aa in _dl_start_user () from /opt/yb-install/yugabyte-2.2.1.0/lib/ld.so
#7  0x0000000000000001 in ?? ()
#8  0x00007ffd937858c8 in ?? ()
#9  0x0000000000000000 in ?? ()
```
