### ISSUE TITLE
Investigate the retry of requests in TPCC.

### ISSUE THREAD

**Issue by psudheer21** [yugabyte/yugabyte-db#4614]
Since 2.1.7-b6 we have gotten away with the 2.5 second timeout and are using either 60 second timeouts or the statement timeout set by the user.
We have had issues where we still see the requests being timed out in TPCC and giving the following error:
```
06:26:36.935+00') was aborted: ERROR: Already present: Multiple homogeneous errors: [Already present (yb/consensus/retryable_requests.cc:239): Duplicate request]  Call getNextException to see other errors in the batch.
        at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:148)
        at org.postgresql.core.ResultHandlerDelegate.handleError(ResultHandlerDelegate.java:50)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2212)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:509)
        at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:853)
        at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1546)
        at com.oltpbenchmark.benchmarks.tpcc.TPCCLoader.loadOrders(TPCCLoader.java:706)
        at com.oltpbenchmark.benchmarks.tpcc.TPCCLoader$2.load(TPCCLoader.java:126)
        at com.oltpbenchmark.api.Loader$LoaderThread.run(Loader.java:63)
        at com.oltpbenchmark.util.ThreadUtil$LatchRunnable.run(ThreadUtil.java:343)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.postgresql.util.PSQLException: ERROR: Already present: Multiple homogeneous errors: [Already present (yb/consensus/retryable_requests.cc:239): Duplicate request]
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2468)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2211)
        ... 10 more
```

Investigate this error.

**Comment by mbautin** [comment]
Here is the full log of this load attempt: https://gist.githubusercontent.com/mbautin/1f5231912e963c4d431ba5f74a87207a/raw

**Comment by mbautin** [comment]
TPCC conf size: https://gist.githubusercontent.com/mbautin/0c8be7e6cf07a237dc23b7fe7bffec9f/raw
