### ISSUE TITLE
[ycql] C++ client segfault in refresh_partitions

### ISSUE THREAD

**Issue by danielmh0** [yugabyte/yugabyte-db#4638]
Jira Link: [DB-2029](https://yugabyte.atlassian.net/browse/DB-2029)
Long-lived C++ connections have a segfault coming from ControlConnection::refresh_partitions. Disabling partition-aware routing or setting the refresh interval to 0 (never refresh after init) are workarounds.

We should reproduce and fix the segfault. A shorter refresh interval should make the repro easier. See `cass_cluster_set_partition_aware_routing`.

Stack trace sample:
```
#0  __GI_raise (sig=sig@entry=6) at [...]/linux/raise.c:51
#1  0x00007fb125b2442a in __GI_abort () at abort.c:89
#2  0x00007fb125b60c00 in __libc_message (do_abort=do_abort@entry=2, fmt=fmt@entry=0x7fb125c56190 "*** Error in `%s': %s: 0x%s ***\n") at ../sysdeps/posix/libc_fatal.c:175
#3  0x00007fb125b67096 in malloc_printerr (action=3, str=0x7fb125c562e8 "double free or corruption (fasttop)", ptr=<optimized out>, ar_ptr=<optimized out>) at malloc.c:5078
#4  0x00007fb125b678de in _int_free (av=0x7fb0c0000020, p=0x7fb0c0000df0, have_lock=0, no_trim=<optimized out>) at malloc.c:3931
#5  0x00007fb1221fa56d in void std::vector<cass::Buffer, std::allocator<cass::Buffer> >::_M_realloc_insert<cass::Buffer>(__gnu_cxx::__normal_iterator<cass::Buffer*, std::vector<cass::Buffer, std::allocator<cass::Buffer> > >, cass::Buffer&&) () from [...]
#6  0x00007fb1221fc1d0 in cass::Statement::encode_begin(int, unsigned short, cass::RequestCallback*, std::vector<cass::Buffer, std::allocator<cass::Buffer> >*) const ()
   from [...]
#7  0x00007fb122280d9e in cass::QueryRequest::encode(int, cass::RequestCallback*, std::vector<cass::Buffer, std::allocator<cass::Buffer> >*) const ()
   from [...]
#8  0x00007fb1222832ef in cass::RequestCallback::encode(int, int, std::vector<cass::Buffer, std::allocator<cass::Buffer> >*) ()
   from [...]
#9  0x00007fb1222fce4e in cass::Connection::PendingWriteBase::write(cass::RequestCallback*) ()
   from [...]
#10 0x00007fb1222feed0 in cass::Connection::internal_write(cass::SharedRefPtr<cass::RequestCallback> const&, bool) ()
   from [...]
#11 0x00007fb1222ffae1 in cass::Connection::write(cass::SharedRefPtr<cass::RequestCallback> const&, bool) ()
   from [...]
#12 0x00007fb122283c40 in cass::MultipleRequestCallback::execute_query(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) () from [...]
#13 0x00007fb12220caf8 in cass::ControlConnection::refresh_partitions() () from [...]
#14 0x00007fb11f9b29b4 in ?? () from /usr/lib/x86_64-linux-gnu/libuv.so.1
#15 0x00007fb1269e54a4 in start_thread (arg=0x7fb0d9ffc700) at pthread_create.c:456
#16 0x00007fb125bd8eef in clone () at [...]linux/x86_64/clone.S:97
```

**Comment by pmb311** [comment]
Please assign this one to me as a placeholder.

**Comment by danielmh0** [comment]
We haven't seen this in a while. Has it been fixed by https://github.com/yugabyte/cassandra-cpp-driver/commit/3fefa97889adfd25ec1f53e8d747d16c47f13895 or https://github.com/yugabyte/cassandra-cpp-driver/commit/bccc76e6af60f513070d71b2cddd9580d0003cd6?

**Comment by m-iancu** [comment]
Closing this (assuming fixed by https://github.com/yugabyte/cassandra-cpp-driver/commit/3fefa97889adfd25ec1f53e8d747d16c47f13895).
To reopen if there's a new repro for it.
