### ISSUE TITLE
[test][backup] YBBackupTest.* tests failure on MacOS.

### ISSUE THREAD

**Issue by OlegLoginov** [yugabyte/yugabyte-db#4924]
Jira Link: [DB-1430](https://yugabyte.atlassian.net/browse/DB-1430)
The tests are failing on MacOS due to python environment issues like:
```
8713	Traceback (most recent call last):
8714	   File "/Volumes/share/jenkins/jenkins-github-yugabyte-db-phabricator-42588/build/debug-clang-dynamic-ninja/tests-tools/../../../managed/devops/bin/yb_backup.py", line 29, in <module>
8715	     from six import iteritems
8716	ImportError: No module named six
```

**Comment by bmatican** [comment]
Note, this is also failing on centos! See https://detective-gcp.dev.yugabyte.com/stability/test?class=YBBackupTest&name=TestYCQLKeyspaceBackup

```
   File "/nfusr/centos-gcp-cloud/jenkins-slave-c69/jenkins/jenkins-github-yugabyte-db-phabricator-43896/build/release-clang-dynamic-ninja/tests-tools/../../../managed/devops/bin/yb_backup.py", line 25, in <module>
     from boto.utils import get_instance_metadata
ImportError: No module named boto.utils
ent/src/yb/tools/yb-backup-test_ent.cc:138: Failure
```

**Comment by OlegLoginov** [comment]
In the latest build the failure looks like:
```
../../ent/src/yb/tools/yb-backup-test_ent.cc:132 Failed Bad status: Runtime error (yb/tools/yb-backup-test_ent.cc:97): yb_backup.py error: Exception: Command '['bash', '-c', 'ps -o command']' returned non-zero exit status 1.
```
```
Log: https://jenkins.dev.yugabyte.com/job/github-yugabyte-db-phabricator/49249/artifact/build/release-clang-dynamic-ninja/yb-test-logs/tests-tools__yb-backup-test_ent/YBBackupTest_TestYCQLKeyspaceBackup.log

../../ent/src/yb/tools/yb-backup-test_ent.cc:132
Failed
Bad status: Runtime error (yb/tools/yb-backup-test_ent.cc:97): yb_backup.py error: Exception: Command '['bash', '-c', 'ps -o command']' returned non-zero exit status 1.
```

**Comment by OlegLoginov** [comment]
No backports planned. (Because it only affects backup tests on MAC. MAC is not a production platform.)
