### ISSUE TITLE
cassandra-loader does not support JSONB datatype

### ISSUE THREAD

**Issue by ajcaldera1** [YugaByte/yugabyte-db#496]
If I attempt to load a table that contains a JSONB column with cassandra-loader, it throws the following error:

Exception in thread "main" java.util.concurrent.ExecutionException: java.text.ParseException: Column data type not recognized (json)
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.datastax.loader.CqlDelimLoad.run(CqlDelimLoad.java:668)
	at com.datastax.loader.CqlDelimLoad.main(CqlDelimLoad.java:713)
Caused by: java.text.ParseException: Column data type not recognized (json)
	at com.datastax.loader.CqlDelimParser.schemaBits(CqlDelimParser.java:289)
	at com.datastax.loader.CqlDelimParser.processCqlSchema(CqlDelimParser.java:194)
	at com.datastax.loader.CqlDelimParser.<init>(CqlDelimParser.java:82)
	at com.datastax.loader.CqlDelimLoadTask.setup(CqlDelimLoadTask.java:189)
	at com.datastax.loader.CqlDelimLoadTask.call(CqlDelimLoadTask.java:152)
	at com.datastax.loader.CqlDelimLoadTask.call(CqlDelimLoadTask.java:53)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

For reference I created the following table:
CREATE TABLE timeseries(device_id text, ts int, metrics jsonb, PRIMARY KEY((device_id), ts)) WITH CLUSTERING ORDER BY (ts DESC);

**Comment by amitanandaiyer** [comment]
Fixed as part of #739
