### ISSUE TITLE
YugabyteDB 2.2.0 `yb-ctl --rf 3 stop`, `yb-ctl --rf 3 destroy` and `yb-ctl --rf wipe_restart` errors  

### ISSUE THREAD

**Issue by yeongsheng-tan** [yugabyte/yugabyte-db#5118]
Running either of the above on a `start`ed cluster of 3 on my macOS Catalina 10.15.5 machine throws the following errors:

```
./bin/yb-ctl --rf 3 stop
Stopping cluster.
Traceback (most recent call last):
  File "./bin/yb-ctl", line 1394, in stop_process
    os.kill(pid, signal.SIGTERM)
ProcessLookupError: [Errno 3] No such process

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./bin/yb-ctl", line 2021, in <module>
    control.run()
  File "./bin/yb-ctl", line 1998, in run
    self.args.func()
  File "./bin/yb-ctl", line 1797, in stop_cmd_impl
    self.for_all_daemons(self.stop_daemon)
  File "./bin/yb-ctl", line 1730, in for_all_daemons
    fn(DaemonId(daemon_type, daemon_index)))
  File "./bin/yb-ctl", line 1429, in stop_daemon
    self.stop_process(postgres_pid, "Postmaster for {}".format(daemon_id))
  File "./bin/yb-ctl", line 1396, in stop_process
    if e.errno == os.errno.ESRCH:
AttributeError: module 'os' has no attribute 'errno'
Viewing file /var/folders/11/btv6w5410yz8bcyrx0nn6gsw0000gn/T/tmp_yn2p238:
^^^ Encountered errors ^^^
2020-07-16 18:06:58,140 INFO: Stopping Server master-1 PID=20487
2020-07-16 18:06:58,140 INFO: Waiting for Server master-1 PID=20487 to stop...
2020-07-16 18:06:58,672 INFO: Stopping Server master-2 PID=20490
2020-07-16 18:06:58,672 INFO: Waiting for Server master-2 PID=20490 to stop...
2020-07-16 18:06:59,199 INFO: Stopping Server master-3 PID=20493
2020-07-16 18:06:59,199 INFO: Waiting for Server master-3 PID=20493 to stop...
2020-07-16 18:06:59,725 INFO: Stopping Server tserver-1 PID=20501
2020-07-16 18:06:59,725 INFO: Waiting for Server tserver-1 PID=20501 to stop...
2020-07-16 18:07:00,229 INFO: Stopping Postmaster for tserver-1 PID=23321
```

Running `yb-ctl status` after the above `yb-ctl stop` shows the cluster in correct state though:
```
./bin/yb-ctl --rf 3 status 
----------------------------------------------------------------------------------------------------
| Node Count: 3 | Replication Factor: 3                                                            |
----------------------------------------------------------------------------------------------------
| JDBC                : jdbc:postgresql://127.0.0.1:5433/yugabyte                                  |
| YSQL Shell          : bin/ysqlsh                                                                 |
| YCQL Shell          : bin/ycqlsh                                                                 |
| YEDIS Shell         : bin/redis-cli                                                              |
| Web UI              : http://127.0.0.1:7000/                                                     |
| Cluster Data        : /Users/yeongsheng/yugabyte-data                                            |
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
| Node 1: yb-tserver (Stopped), yb-master (Stopped)                                                |
----------------------------------------------------------------------------------------------------
| JDBC                : jdbc:postgresql://127.0.0.1:5433/yugabyte                                  |
| YSQL Shell          : bin/ysqlsh                                                                 |
| YCQL Shell          : bin/ycqlsh                                                                 |
| YEDIS Shell         : bin/redis-cli                                                              |
| data-dir[0]         : /Users/yeongsheng/yugabyte-data/node-1/disk-1/yb-data                      |
| yb-tserver Logs     : /Users/yeongsheng/yugabyte-data/node-1/disk-1/yb-data/tserver/logs         |
| yb-master Logs      : /Users/yeongsheng/yugabyte-data/node-1/disk-1/yb-data/master/logs          |
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
| Node 2: yb-tserver (pid 20511), yb-master (Stopped)                                              |
----------------------------------------------------------------------------------------------------
| JDBC                : jdbc:postgresql://127.0.0.2:5433/yugabyte                                  |
| YSQL Shell          : bin/ysqlsh -h 127.0.0.2                                                    |
| YCQL Shell          : bin/ycqlsh 127.0.0.2                                                       |
| YEDIS Shell         : bin/redis-cli -h 127.0.0.2                                                 |
| data-dir[0]         : /Users/yeongsheng/yugabyte-data/node-2/disk-1/yb-data                      |
| yb-tserver Logs     : /Users/yeongsheng/yugabyte-data/node-2/disk-1/yb-data/tserver/logs         |
| yb-master Logs      : /Users/yeongsheng/yugabyte-data/node-2/disk-1/yb-data/master/logs          |
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
| Node 3: yb-tserver (pid 20521), yb-master (Stopped)                                              |
----------------------------------------------------------------------------------------------------
| JDBC                : jdbc:postgresql://127.0.0.3:5433/yugabyte                                  |
| YSQL Shell          : bin/ysqlsh -h 127.0.0.3                                                    |
| YCQL Shell          : bin/ycqlsh 127.0.0.3                                                       |
| YEDIS Shell         : bin/redis-cli -h 127.0.0.3                                                 |
| data-dir[0]         : /Users/yeongsheng/yugabyte-data/node-3/disk-1/yb-data                      |
| yb-tserver Logs     : /Users/yeongsheng/yugabyte-data/node-3/disk-1/yb-data/tserver/logs         |
| yb-master Logs      : /Users/yeongsheng/yugabyte-data/node-3/disk-1/yb-data/master/logs          |
----------------------------------------------------------------------------------------------------
```

However, when I performed `ps grep` on `yugabyte` processes yielded:
```
ps aux | grep yugabyte | grep -v grep                                                                                                                   
yeongsheng       20521   6.4  0.2  4492272  27504 s003  S     6:06PM   0:35.86 /Users/yeongsheng/Downloads/yugabyte-2.2.0.0/bin/yb-tserver --fs_data_dirs /Users/yeongsheng/yugabyte-data/node-3/disk-1 --webserver_interface 127.0.0.3 --rpc_bind_addresses 127.0.0.3 --v 0 --version_file_json_path=/Users/yeongsheng/Downloads/yugabyte-2.2.0.0 --webserver_doc_root /Users/yeongsheng/Downloads/yugabyte-2.2.0.0/www --tserver_master_addrs=127.0.0.1:7100,127.0.0.2:7100,127.0.0.3:7100 --yb_num_shards_per_tserver=2 --redis_proxy_bind_address=127.0.0.3:6379 --cql_proxy_bind_address=127.0.0.3:9042 --local_ip_for_outbound_sockets=127.0.0.3 --use_cassandra_authentication=false --ysql_num_shards_per_tserver=2 --default_memory_limit_to_ram_ratio=0.65 --enable_ysql=true --pgsql_proxy_bind_address=127.0.0.3:5433
yeongsheng       20511   6.1  0.2  4491772  27552 s003  S     6:06PM   0:36.16 /Users/yeongsheng/Downloads/yugabyte-2.2.0.0/bin/yb-tserver --fs_data_dirs /Users/yeongsheng/yugabyte-data/node-2/disk-1 --webserver_interface 127.0.0.2 --rpc_bind_addresses 127.0.0.2 --v 0 --version_file_json_path=/Users/yeongsheng/Downloads/yugabyte-2.2.0.0 --webserver_doc_root /Users/yeongsheng/Downloads/yugabyte-2.2.0.0/www --tserver_master_addrs=127.0.0.1:7100,127.0.0.2:7100,127.0.0.3:7100 --yb_num_shards_per_tserver=2 --redis_proxy_bind_address=127.0.0.2:6379 --cql_proxy_bind_address=127.0.0.2:9042 --local_ip_for_outbound_sockets=127.0.0.2 --use_cassandra_authentication=false --ysql_num_shards_per_tserver=2 --default_memory_limit_to_ram_ratio=0.65 --enable_ysql=true --pgsql_proxy_bind_address=127.0.0.2:5433
```

**Comment by ddorian** [comment]
@yeongsheng-tan Just found the issue. 
Can you paste the output of `python --version` ?

For a quick fix, can you try replacing `os.errno` with `errno` in `yb-ctl` file until the fix is in ?

**Comment by yeongsheng-tan** [comment]
> @yeongsheng-tan Just found the issue.
> Can you paste the output of `python --version` ?
> 
> For a quick fix, can you try replacing `os.errno` with `errno` in `yb-ctl` file until the fix is in ?

```
python --version
Python 3.8.4
```

**Comment by ddorian** [comment]
fixed in https://github.com/yugabyte/yugabyte-installation/pull/37
