### ISSUE TITLE
[yugabyted] fails to start the UI with error related to org.pac4j.play.store.PlaySessionStore

### ISSUE THREAD

**Issue by bhavin192** [yugabyte/yugabyte-db#5193]
When starting yugabyted with `./bin/yugabyted start --ui true` the UI status is reported as failed. 
### How to reproduce
```console
$ wget https://downloads.yugabyte.com/yugabyte-2.2.0.0-linux.tar.gz
…
$ tar xfz yugabyte-2.2.0.0-linux.tar.gz && cd yugabyte-2.2.0.0/
$ ./bin/post_install.sh
…
$  ./bin/yugabyted start --ui true
Starting yugabyted...
✅ System checks           
❌ UI status        

+--------------------------------------------------------------------------------------------------+
|                                            yugabyted                                             |
+--------------------------------------------------------------------------------------------------+
| Status              : Running                                                                    |
| Web console         : http://127.0.0.1:7200                                                      |
| JDBC                : jdbc:postgresql://127.0.0.1:5433/yugabyte?user=yugabyte&password=yugabyte  |
| YSQL                : bin/ysqlsh                                                                 |
| YCQL                : bin/ycqlsh                                                                 |
| Data Dir            : /home/bhavin/yugabyte-2.2.0.0/var/data                                     |
| Log Dir             : /home/bhavin/yugabyte-2.2.0.0/var/logs                                     |
| Universe UUID       : 42bde272-b45a-4e7f-bb88-ecb11a35edc0                                       |
+--------------------------------------------------------------------------------------------------+
🚀 yugabyted started successfully! To load a sample dataset, try 'yugabyted demo'.
🎉 Join us on Slack at https://www.yugabyte.com/slack
👕 Claim your free t-shirt at …
```
### Logs
The log file `yugaware.err` has following error repeated 15 times.
```console
$ tail -n35 /home/bhavin/yugabyte-2.2.0.0/var/logs/yugaware.err
  while locating play.api.DefaultApplication

15) No implementation for org.pac4j.play.store.PlaySessionStore was bound.
  while locating org.pac4j.play.store.PlaySessionStore
    for field at org.pac4j.play.LogoutController.playSessionStore(LogoutController.java:28)
  while locating com.google.inject.Provider<org.pac4j.play.LogoutController>
    for parameter 26 at v1.Routes.<init>(Routes.scala:128)
  while locating v1.Routes
    for parameter 1 at router.Routes.<init>(Routes.scala:36)
  while locating router.Routes
  while locating play.api.inject.RoutesProvider
  while locating play.api.routing.Router
    for parameter 0 at play.api.http.JavaCompatibleHttpRequestHandler.<init>(HttpRequestHandler.scala:200)
  while locating play.api.http.JavaCompatibleHttpRequestHandler
  while locating play.api.http.HttpRequestHandler
    for parameter 4 at play.api.DefaultApplication.<init>(Application.scala:221)
  at play.api.DefaultApplication.class(Application.scala:221)
  while locating play.api.DefaultApplication
  while locating play.api.Application
    for parameter 0 at play.DefaultApplication.<init>(DefaultApplication.java:30)
  at play.DefaultApplication.class(DefaultApplication.java:30)
  while locating play.DefaultApplication

15 errors
	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:466)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:184)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
	at com.google.inject.Guice.createInjector(Guice.java:96)
	at com.google.inject.Guice.createInjector(Guice.java:84)
	at play.api.inject.guice.GuiceBuilder.injector(GuiceInjectorBuilder.scala:181)
	at play.api.inject.guice.GuiceApplicationBuilder.build(GuiceApplicationBuilder.scala:123)
	at play.api.inject.guice.GuiceApplicationLoader.load(GuiceApplicationLoader.scala:21)
	at play.core.server.ProdServerStart$.start(ProdServerStart.scala:47)
	at play.core.server.ProdServerStart$.main(ProdServerStart.scala:22)
	at play.core.server.ProdServerStart.main(ProdServerStart.scala)
```
### Other details
```console
$ java -version
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (build 1.8.0_252-b09)
OpenJDK 64-Bit Server VM (build 25.252-b09, mixed mode)

$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
…
```
This seem to be happening on Debian, Ubuntu and Fedora as well.

**Comment by bhavin192** [comment]
Same issue, #5069. Fixed by https://github.com/yugabyte/yugabyte-db/commit/eabb4d4752348fa670cb14d2bbef112ea87f081d
