### ISSUE TITLE
build_postgres.py failing to build from CLion environment

### ISSUE THREAD

**Issue by svarnau** [yugabyte/yugabyte-db#5255]
This will enable CLion invoked builds without specifying the YB_THIRDPARTY_DIR environment variable (since it changes semi-frequently).

Related to previous Cmake change: #4905

**Comment by svarnau** [comment]
```
[build_postgres.py:227] 2020-07-29 10:48:28,805 INFO: Replaced cflags in /Users/spolitov/code/yugabyte/build/debug-clang-dynamic-ninja/postgres_build/src/Makefile.global
Traceback (most recent call last):
  File "/Users/spolitov/code/yugabyte/python/yb/build_postgres.py", line 786, in <module>
    PostgresBuilder().run()
  File "/Users/spolitov/code/yugabyte/python/yb/build_postgres.py", line 724, in run
    self.build_postgres()
  File "/Users/spolitov/code/yugabyte/python/yb/build_postgres.py", line 765, in build_postgres
    self.make_postgres()
  File "/Users/spolitov/code/yugabyte/python/yb/build_postgres.py", line 513, in make_postgres
    raise RuntimeError("Expected env var %s to be set" % env_var_name)
RuntimeError: Expected env var YB_THIRDPARTY_DIR to be set
```

**Comment by svarnau** [comment]
Actually it is not needed to pick up value from thirdparty_path.txt file, since the build_postgres command already requires the value to be passed on the command line.
