### ISSUE TITLE
[ysql] yb::pggate::YBCPgExecInsert getting stuck on semaphore acquisition in yb::pggate::PgDocOp::WaitForData

### ISSUE THREAD

**Issue by mbautin** [YugaByte/yugabyte-db#539]
```
bin/remote_build.py -- --java-test TestPgWrapper#testTransactionConflicts -n 100
```

Log here:
https://gist.githubusercontent.com/mbautin/ad7c12720e3e7836c14f629677bf24bf/raw

Stack trace:
```
    #3  0x00007f0274c0a130 in yb::Semaphore::Acquire (this=0x386f758) at ../../src/yb/util/semaphore.cc:55
    #4  0x00007f027460d06c in yb::pggate::PgDocOp::WaitForData (this=0x386f740) at ../../src/yb/yql/pggate/pg_doc_op.cc:85
    #5  0x00007f027460cf00 in yb::pggate::PgDocOp::GetResult (this=0x386f740, result_set=0x36700e8) at ../../src/yb/yql/pggate/pg_doc_op.cc:64
    #6  0x00007f0274606276 in yb::pggate::PgDmlWrite::Exec (this=0x3670000) at ../../src/yb/yql/pggate/pg_dml_write.cc:81
    #7  0x00007f02745ef9b6 in yb::pggate::PgApiImpl::ExecInsert (this=0x3672400, handle=0x3670000) at ../../src/yb/yql/pggate/pggate.cc:328
    #8  0x00007f02745e7ac5 in yb::pggate::YBCPgExecInsert (handle=0x3670000) at ../../src/yb/yql/pggate/ybc_pggate.cc:224
    #9  0x00000000006fed4a in YBCExecuteInsert (relationDesc=0x390b448, tupleDesc=0x3945310, tuple=0x3945c48) at ybcModifyTable.c:68
    #10 0x00000000006e3504 in ExecInsert (mtstate=0x3944c58, slot=0x3945218, planSlot=0x3945218, arbiterIndexes=0x0, onconflict=ONCONFLICT_NONE, estate=0x39448f0, canSetTag=1 '\001') at nodeModifyTable.c:547
    #11 0x00000000006e521e in ExecModifyTable (pstate=0x3944c58) at nodeModifyTable.c:1807
    #12 0x00000000006beab9 in ExecProcNodeFirst (node=0x3944c58) at execProcnode.c:430
    #13 0x00000000006b7269 in ExecProcNode (node=0x3944c58) at ../../../src/include/executor/executor.h:250
    #14 0x00000000006b9aac in ExecutePlan (estate=0x39448f0, planstate=0x3944c58, use_parallel_mode=0 '\000', operation=CMD_INSERT, sendTuples=0 '\000', numberTuples=0, direction=ForwardScanDirection, dest=0xefbe00 <donothingDR>, execute_once=1 '\001') at execMain.c:1722
    #15 0x00000000006b7813 in standard_ExecutorRun (queryDesc=0x2e3a3e8, direction=ForwardScanDirection, count=0, execute_once=1 '\001') at execMain.c:363
    #16 0x00000000006b7645 in ExecutorRun (queryDesc=0x2e3a3e8, direction=ForwardScanDirection, count=0, execute_once=1 '\001') at execMain.c:306
    #17 0x000000000087add3 in ProcessQuery (plan=0x37be270, sourceText=0x2e3a390 "INSERT INTO test(h, r, v) VALUES (49, 49, 9800)", params=0x0, queryEnv=0x0, dest=0xefbe00 <donothingDR>, completionTag=0x7ffec09fe380 "") at pquery.c:161
    #18 0x000000000087c6db in PortalRunMulti (portal=0x39428e0, isTopLevel=1 '\001', setHoldSnapshot=0 '\000', dest=0xefbe00 <donothingDR>, altdest=0xefbe00 <donothingDR>, completionTag=0x7ffec09fe380 "") at pquery.c:1286
    #19 0x000000000087bcc1 in PortalRun (portal=0x39428e0, count=9223372036854775807, isTopLevel=1 '\001', run_once=1 '\001', dest=0x37b5038, altdest=0x37b5038, completionTag=0x7ffec09fe380 "") at pquery.c:799
    #20 0x0000000000877475 in exec_execute_message (portal_name=0x37b4c20 "", max_rows=9223372036854775807) at postgres.c:1982
    #21 0x000000000087a0f5 in PostgresMain (argc=1, argv=0x3761a08, dbname=0x3761738 "postgres", username=0x2e31440 "postgres") at postgres.c:4155
    #22 0x00000000007dd361 in BackendRun (port=0x2e3a760) at postmaster.c:4406
    #23 0x00000000007dcada in BackendStartup (port=0x2e3a760) at postmaster.c:4078
    #24 0x00000000007d9058 in ServerLoop () at postmaster.c:1756
    #25 0x00000000007d868c in PostmasterMain (argc=5, argv=0x2e2f230) at postmaster.c:1364
    #26 0x000000000071656d in PostgresServerProcessMain (argc=5, argv=0x2e2f230) at main.c:228
    #27 0x0000000000716856 in main ()
```

**Comment by mbautin** [comment]
This was fixed by commit https://github.com/YugaByte/yugabyte-db/commit/db3b14a99a98fc8ac9f81bee12a8f5a6a7e5e222 and is a side effect of https://github.com/YugaByte/yugabyte-db/issues/507
