### ISSUE TITLE
[test][YCQL] Data race in test TestConsistencyLevels#testReadFromLeader. 

### ISSUE THREAD

**Issue by OlegLoginov** [yugabyte/yugabyte-db#5518]
Jira Link: [DB-4673](https://yugabyte.atlassian.net/browse/DB-4673)
Test: `ybd --java-test 'org.yb.cql.TestConsistencyLevels#testReadFromLeader' -n 100`

Link: https://detective-gcp.dev.yugabyte.com/job/github-yugabyte-db-phabricator%2F51868%2Fartifact%2Fjava%2Fyb-cql%2Ftarget%2Fsurefire-reports_org.yb.cql.TestConsistencyLevels__testReadFromLeader%2Forg.yb.cql.TestConsistencyLevels-output.txt?class=org.yb.cql.TestConsistencyLevels&name=testReadFromLeader

Error: `junit.framework.AssertionFailedError: expected:<100> but was:<0>`

The test has a potential race:
```
....  <<<< WRITE ROWS... in setUpTable()
    // Verify all reads went to the leader.
    Map<HostAndPort, MiniYBDaemon> tservers = miniCluster.getTabletServers();
    assertEquals(tservers.size(), tablet.getReplicas().size());
    for (LocatedTablet.Replica replica : tablet.getReplicas()) {
      String host = replica.getRpcHost();
      int webPort = tservers.get(HostAndPort.fromParts(host, replica.getRpcPort())).getWebPort();
      Metrics metrics = new Metrics(host, webPort, "server");
      long numOps = metrics.getHistogram(TSERVER_READ_METRIC).totalCount;         <<<< READ METRIC
      if (replica.getRole().equals(Metadata.RaftPeerPB.Role.LEADER.toString())) {
        assertEquals(NUM_OPS, numOps);
      } else {
        assertEquals(0, numOps);
      }
```
On the LEADER numOps==100, on FOLLOWER numOps==0.
But it fails if the Leader was changed AFTER the write operations.
I ran it 20 times and it failed 1 time.

**Comment by OlegLoginov** [comment]
```
2149 |   | ERROR | 19.837000 | main | BaseYBTest.java:240 | YB Java test failed: class="org.yb.cql.TestConsistencyLevels", method="testReadFromLeader"
2150 | junit.framework.AssertionFailedError: expected:<100> but was:<0>
2151 | at junit.framework.Assert.fail(Assert.java:57)
2152 | at junit.framework.Assert.failNotEquals(Assert.java:329)
2153 | at junit.framework.Assert.assertEquals(Assert.java:78)
2154 | at junit.framework.Assert.assertEquals(Assert.java:159)
2155 | at junit.framework.Assert.assertEquals(Assert.java:166)
2156 | at junit.framework.TestCase.assertEquals(TestCase.java:324)
2157 | at org.yb.cql.TestConsistencyLevels.testReadFromLeader(TestConsistencyLevels.java:146)
2158 | at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2159 | at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2160 | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2161 | at java.lang.reflect.Method.invoke(Method.java:498)
2162 | at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
2163 | at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
2164 | at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
2165 | at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
2166 | at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
2167 | at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
2168 | at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
2169 | at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
2170 | at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2171 | at java.lang.Thread.run(Thread.java:748)
2172 |   | INFO | 19.840000 | main | BaseYBTest.java:247 | YB Java test class="org.yb.cql.TestConsistencyLevels", method="testReadFromLeader" took 19.82 seconds
2173 |  
2174 | ----------------------------------------------------------------------------------------------------
2175 | Finished YB Java test: class="org.yb.cql.TestConsistencyLevels", method="testReadFromLeader"
2176 | ----------------------------------------------------------------------------------------------------
```

**Comment by OlegLoginov** [comment]
```
[2020-08-27T12:13:39 repeat_unit_test.sh:393 main] Saving repeated test execution logs to: /home/centos/logs/repeat_unit_test/yb-cql/org.yb.cql.TestConsistencyLevels#testReadFromLeader/2020-08-27T12_13_39
PASSED: iteration 3, 44 sec
PASSED: iteration 4, 45 sec
PASSED: iteration 1, 45 sec
PASSED: iteration 2, 45 sec
PASSED: iteration 5, 41 sec
PASSED: iteration 6, 41 sec
PASSED: iteration 8, 41 sec
PASSED: iteration 7, 46 sec
PASSED: iteration 11, 41 sec
PASSED: iteration 10, 42 sec
PASSED: iteration 12, 42 sec
PASSED: iteration 9, 51 sec
PASSED: iteration 14, 39 sec
PASSED: iteration 16, 37 sec
PASSED: iteration 15, 42 sec
PASSED: iteration 17, 41 sec
PASSED: iteration 18, 34 sec
PASSED: iteration 19, 29 sec
PASSED: iteration 20, 17 sec
FAILED: iteration 13, 1801 sec; test log path: /home/centos/logs/repeat_unit_test/yb-cql/org.yb.cql.TestConsistencyLevels#testReadFromLeader/2020-08-27T12_13_39/13.reports_combined_logs.txt.gz
```

**Comment by OlegLoginov** [comment]
[log2.txt](https://github.com/yugabyte/yugabyte-db/files/5137289/log2.txt)
The detailed log.

**Comment by m-iancu** [comment]
Closing as this tests looks stable now in latest: https://detective-gcp.dev.yugabyte.com/stability/test?analyze_trends=true&branch=master&build_type=all&class=org.yb.cql.TestConsistencyLevels&fail_tag=all&name=testReadFromLeader&platform=all
