### ISSUE TITLE
Understanding error conditions when running TPCC against YB cluster

### ISSUE THREAD

**Issue by tylarb** [yugabyte/yugabyte-db#5673]
I've encountered a somewhat strange scenario.

After loading data into a YB server, I can run TPCC against it. I run TPCC command like the following:

```
./tpccbenchmark --nodes=n1,n2,n3,n4,n5,n6,n7,n8,n9 --warehouses=10 --execute=true -s 300 -o output
```

All nodes (9 unique IPs) have been loaded with data using TPCC load. For example, say Masters on N1,N2,N3

If I _panic_ a host containing yugabyte master, for example, n3, while including it in the node list when running TPCC, I get an error like this:

```
java.lang.RuntimeException: Unexpected fatal, error in 'TPCCWorker<038>' when executing 'Payment/02' [POSTGRES]
        at com.oltpbenchmark.api.Worker.doWork(Worker.java:516)
        at com.oltpbenchmark.api.Worker.run(Worker.java:316)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.postgresql.util.PSQLException: ERROR: Already present: Duplicate request
```

However, if I exclude this same node from TPCC nodes list (i.e. total of 8 nodes, instead of 9), then panic the same node, I cannot get this error.

Example:
```
./tpccbenchmark --nodes=n1,n2,n4,n5,n6,n7,n8,n9 ...
```

It also seems that the error still is present if I panic a node which is _not_ the master. In above example, say N4 gets panicked while `--nodes=n1,n2,n3,n5,n6,n7,n8,n9`

**Comment by ddorian** [comment]
@tylarb are you running our fork of TPCC https://github.com/yugabyte/tpcc ?

**Comment by tylarb** [comment]
Yes, running the Yugabyte fork of tpcc
