### ISSUE TITLE
 o.y.pg.PgWriteRestart.WriteRestart fails with assertion

### ISSUE THREAD

**Issue by tedyu** [yugabyte/yugabyte-db#5760]
WriteRestart fails with the following assertion:
```
java.lang.AssertionError: expected:<12> but was:<13>
--
7624 | at org.junit.Assert.fail(Assert.java:88)
7625 | at org.junit.Assert.failNotEquals(Assert.java:834)
7626 | at org.junit.Assert.assertEquals(Assert.java:645)
7627 | at org.junit.Assert.assertEquals(Assert.java:631)
7628 | at org.yb.AssertionWrappers.lambda$assertEquals$37(AssertionWrappers.java:580)
7629 | at org.yb.AssertionWrappers.wrapAssertion(AssertionWrappers.java:45)
7630 | at org.yb.AssertionWrappers.assertEquals(AssertionWrappers.java:580)
7631 | at org.yb.pgsql.TestPgWriteRestart.performImplicitPreparedParallelWrites(TestPgWriteRestart.java:209)
7632 | at org.yb.pgsql.TestPgWriteRestart.testWriteRestart(TestPgWriteRestart.java:271)
```

**Comment by psudheer21** [comment]
This is strange. The execution of the test has one write failure when it encounters a higher priority transaction:
```
org.postgresql.util.PSQLException: ERROR: IO error: Errors occured while reaching out to the tablet servers: . Errors from tablet servers: [Operation failed. Try again. (yb/docdb/conflict_resolution.cc:71): e471f268-7b3d-49f8-9d30-5f4721bfd125 Conflicts with higher priority transaction: c1622761-d2f2-4c60-8412-f7b1da1d3680 (transaction error 3), Operation failed. Try again. (yb/tablet/tablet.cc:1074): Transaction was recently aborted: e471f268-7b3d-49f8-9d30-5f4721bfd125 (pgsql error 40001)]
›   at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
›   at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
›   at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
›   at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
›   at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
›   at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:143)
›   at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:132)
›   at org.yb.pgsql.TestPgWriteRestart$ParallelRunWithImplicitPrepared.run(TestPgWriteRestart.java:79)
›   at java.lang.Thread.run(Thread.java:748)
```
This used to work with all of my testing on my machine.
Will post more details on why this happened.

**Comment by tedyu** [comment]
Added log with priorities.
Snippet from org.yb.pgsql.TestPgWriteRestart-output.txt
```
ts1|pid29807|:13323|http://127.198.179.199:28068 I0926 02:47:08.139922 29940 conflict_resolution.cc:557] 18446744069414584319<18446744071132733698 { id: 75a83c7e-6548-4c15-b3c5-649fcafaad92 status: PENDING commit_time: <invalid> priority: 18446744071132733698 failure: OK }
ts1|pid29807|:13323|http://127.198.179.199:28068 I0926 02:47:08.140477 29940 tablet_service.cc:407] T 56b52f809e2f4bf8889061a696158674 P 929bd617f8284714b6a2a8c5b6853f47 [state=RUNNING]: Write failed: Operation failed. Try again. (yb/docdb/conflict_resolution.cc:71): 00000000-0000-0000-0000-000000000000 Conflicts with higher priority transaction: 75a83c7e-6548-4c15-b3c5-649fcafaad92 (transaction error 3)
ts1|pid29807|:13323|http://127.198.179.199:28068 I0926 02:47:08.148205 31214 tablet_rpc.cc:421] Operation failed. Try again. (yb/docdb/conflict_resolution.cc:71): Failed Write(tablet: 56b52f809e2f4bf8889061a696158674, num_ops: 1, num_attempts: 1, txn: 00000000-0000-0000-0000-000000000000) to tablet 56b52f809e2f4bf8889061a696158674 on tablet server { uuid: 929bd617f8284714b6a2a8c5b6853f47 private: [host: "127.198.179.199" port: 13323] cloud_info: placement_cloud: "cloud1" placement_region: "datacenter1" placement_zone: "rack1" after 1 attempt(s): 00000000-0000-0000-0000-000000000000 Conflicts with higher priority transaction: 75a83c7e-6548-4c15-b3c5-649fcafaad92 (transaction error 3)
```
Note: 18446744069414584319 is txn_priority_regular_upper_bound

**Comment by psudheer21** [comment]
This bug happens because in the case of Implicit prepared statements the Triggers were being called in parallel with the actual write:
After ensuring that the write and read rpcs are being logged by tservers, I see that there are 2 writes being received by the tservers at almost the same time:

The first one is the write for the update statement:
```
0928 21:21:58.598294 26109 tablet_service.cc:1700] Received Read RPC: tablet_id: "ac6382b44f4044abb75ce892529f6e04"
...
I0928 21:21:58.599113 26108 tablet_service.cc:1337] Received Write RPC: tablet_id: "ac6382b44f4044abb75ce892529f6e04"
transaction_id: "U\025\274?\203\205A\004\222\254\026`\355\322\000\227"
priority: 4133552418486544194
column_new_values {
  column_id: 11
  expr {
    value {
      int32_value: 14
    }
  }
}
```

The second request is for the trigger:
```
I0928 21:21:58.599124 25981 tablet_service.cc:1337] Received Write RPC: tablet_id: "cd5e861403954b6fa04705afb1128ca3"
transaction_id: "U\025\274?\203\205A\004\222\254\026`\355\322\000\227"
priority: 4133552418486544194
...
string_value: "{OPEXPR :opno 551 :opfuncid 177 :opresulttype 23 :opretset false :opcollid 0 :inputcollid 0 :args ({VAR :varno 1 :varattno 2 :vartype 23 :vartypmod -1 :varcollid 0 :varlevelsup 0 :varnoold 1 :varoattno 2 :location 24} {CONST :consttype 23 :consttypmod -1 :constcollid 0 :constlen 4      :constbyval true :constisnull false :location 26 :constvalue 4 [ 1 0 0 0 0 0 0 0 ]}) :location 25}"
```

Ideally we should have waited for the first write to succeed before the write for the trigger is sent to the tserver.
For all the other requests in the test, this was true. But for this request it is doing this weird parallel write.
