### ISSUE TITLE
Why is read from my YugaByte database slow with a geo-distributed cluster of servers?

### ISSUE THREAD

**Issue by yjiangnan** [yugabyte/yugabyte-db#5777]
Jira Link: [DB-2275](https://yugabyte.atlassian.net/browse/DB-2275)
I have a cluster of three servers. Two are in Los Angeles but in different locations (with different cloud providers) and another is in Tokyo. They are assigned with three domain names: s1.mydomain.com, s2.mydomain.com, s3.mydomain.com. These servers communicate with TLS encryption. One of the TServer is started with the following setup and others are similar:
```
./bin/yb-tserver --tserver_master_addrs s1.mydomain.com:7100,s2.mydomain.com:7100,s3.mydomain.com:7100 \
  --rpc_bind_addresses s1.mydomain.com:9100 --start_pgsql_proxy --pgsql_proxy_bind_address s1.mydomain.com:5433\
  --cql_proxy_bind_address s1.mydomain.com:9042 --fs_data_dirs /root/yugabyte \
  --certs_dir=/root/certs/s1.mydomain.com --use_node_to_node_encryption=true --allow_insecure_connections=false
```
Then I created an empty table:
```
CREATE TABLE IF NOT EXISTS mydatabase.klines(
              symbol  TEXT,
              period  INT,
              ts      BIGINT,
              open    FLOAT,
              high    FLOAT,
              low     FLOAT,
              close   FLOAT,
              smaxpr  FLOAT,
              bminpr  FLOAT,
              netam   FLOAT,
              absam   FLOAT,
              PRIMARY KEY ((symbol, period), ts)
            );
```

Then I installed python3 `yb-cassandra-driver` and run the following commands on server s1.mydomain.com, with slow responses:
```
root@HDGia:~/trade# python3
Python 3.8.2 (default, Apr 27 2020, 15:53:34)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from cassandra.cluster import Cluster
<stdin>:1: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
>>> import time
>>> cluster = Cluster(['s1.mydomain.com'])
>>> session = cluster.connect()
>>> t0=time.time(); r = session.execute('select * from mydatabase.klines'); time.time()-t0
2.3011372089385986
>>> t0=time.time(); r = session.execute('select * from mydatabase.klines'); time.time()-t0
1.2971725463867188
>>> t0=time.time(); r = session.execute('select * from mydatabase.klines'); time.time()-t0
0.8368041515350342
>>> t0=time.time(); r = session.execute('select * from mydatabase.klines'); time.time()-t0
1.4511823654174805
>>> t0=time.time(); r = session.execute('select * from mydatabase.klines'); time.time()-t0
1.3057949542999268
```
My question is, why does it take such a long time (usually more than 1 second) to get the response? How can I get almost instant responses? The table is empty anyway and I only need to read locally.

**Comment by m-iancu** [comment]
Hi @yjiangnan, I think this is related to the full-table scan query and the number of tablets.

In Yugabyte YCQL each table is split by default into `8` tablets per node (controlled by the `yb_num_shards_per_tserver` flag). That means on a 3 node cluster you will have `24` tablet leaders (and `48` followers if using RF-3).
Also, Yugabyte is strongly-consistent by default, so all reads will go to the leader (to guarantee they get the _current_ data).

That means that a query like `select * from mydatabase.klines` will have to go through all `24` tablet leaders to accumulate the results (this is not parallelized because there is also some ordering semantics based on the hash key).
In your case I imagine `s1` is in LA so `16` of those queries will be local, but `8` will go to the Tokyo node. Assuming the ping latency is around `120ms` that accounts for around `960ms`for such a query which seems similar to your testing.
So the current results make sense based on the setup.

Now to address this, there are a few options.

First, if your general workload is single-table operations (e.g. single-row writes, and single-row or short-range scans with fixed hash key) then all such operations will hit a single tablet and latency will be lower as expected. 
So maybe this is not going to be an issue in practice.
Then, just for testing, you can change you query to something like:
`select * from mydatabase.klines where partition_hash(symbol, period) = <some 0-65535 uint16>`
to fix a particular partition and therefore ensure it only hits one tablet.
Note: [`partition_hash`](https://docs.yugabyte.com/latest/api/ycql/expr_fcall/#partition-hash-function) is a Yugabyte builtin function similar to `token`.

Otherwise, there are a few configuration options that can help.

#### Use local (consistent-prefix) reads
Since you mentioned local reads above, you can use the consistency option of your respective driver to enable that.
In Yugabyte, as I mentioned above, reads will go to the leader by deafult, but you can set consistency level to `ONE` to enable [reading from followers](https://docs.yugabyte.com/latest/explore/follower-reads/).
For Python I think [adding an argument like `consistency_level=ConsistencyLevel.ONE`](https://github.com/dkoepke/cassandra-python-driver/blob/master/example.py#L48) when creating a statement to execute should work.
That should improve latency significantly in this case, but as a trade-off such reads may see older version of the data.

#### Pin the tablet leaders to preferred zones
If you know most clients will be running (for instance) in LA, you can [pin the tablet leaders to that region](https://docs.yugabyte.com/latest/admin/yb-admin/#set-preferred-zones ) so that writes and strongly-consistent reads will be local. That will improve latency for client apps close to LA, but, as a trade-off, it will make it worse for any Tokyo client apps (that need to do writes or strongly-consistent reads).

#### Reduce number of tablets
You can do that by changing the tserver flag above `yb_num_shards_per_tserver`.
Alternatively, you can also specify the number of tablets explicitly for each table using the [`WITH TABLETS` syntax](https://docs.yugabyte.com/latest/api/ycql/ddl_create_table/#create-a-table-specifying-the-number-of-tablets)

**Comment by yjiangnan** [comment]
@m-iancu 
You are right. I can significantly improve the speed by specifying the partition keys. However, I still see something very strange. There is a significant delay every other query:
```
>>> t0=time.time(); r = session.execute("select * from mydatabase.klines where symbol='BTC/USDT' and period=60"); time.time()-t0
0.24623584747314453
>>> t0=time.time(); r = session.execute("select * from mydatabase.klines where symbol='BTC/USDT' and period=60"); time.time()-t0
0.0020694732666015625
>>> t0=time.time(); r = session.execute("select * from mydatabase.klines where symbol='BTC/USDT' and period=60"); time.time()-t0
0.23306655883789062
>>> t0=time.time(); r = session.execute("select * from mydatabase.klines where symbol='BTC/USDT' and period=60"); time.time()-t0
0.002290964126586914
>>> t0=time.time(); r = session.execute("select * from mydatabase.klines where symbol='BTC/USDT' and period=60"); time.time()-t0
0.2350623607635498
>>> t0=time.time(); r = session.execute("select * from mydatabase.klines where symbol='BTC/USDT' and period=60"); time.time()-t0
0.002440214157104492
>>> t0=time.time(); r = session.execute("select * from mydatabase.klines where symbol='BTC/USDT' and period=60"); time.time()-t0
0.22635221481323242
>>> t0=time.time(); r = session.execute("select * from mydatabase.klines where symbol='BTC/USDT' and period=60"); time.time()-t0
0.002053499221801758
```
Why is there a 100X difference in time for even and odd numbers of queries?

**Comment by ddorian** [comment]
@yjiangnan it's probably selecting from a node that's in another region ?
Can you specify debug logging to see which node it's querying ?

**Comment by yjiangnan** [comment]
@ddorian Where can I find the right log? File `yb-data/tserver/logs/yb-tserver.INFO` does not show such info for each query. Even if the leader is in another region, why does the latency change for each query? It almost looks like there is a local cache that is enabled for a query if it is disabled and then disabled if it is enabled.

**Comment by ddorian** [comment]
@yjiangnan this should be shown in your client code. Let me try it and report back.

**Comment by ddorian** [comment]
@yjiangnan Modify your code like this:

```python

from cassandra.cluster import Cluster, BatchStatement
import logging
import sys
cass_logger = logging.getLogger('cassandra')
cass_logger.setLevel(logging.DEBUG)
formatter = logging.Formatter('%(asctime)s:%(process)s:%(thread)d:%(name)s:%(levelname)s'
                              ':%(filename)s:%(funcName)s():%(lineno)d:%(message)s')

stderr_handler = logging.StreamHandler(sys.stdout)
stderr_handler.setFormatter(formatter)
stderr_handler.setLevel(logging.DEBUG)
cass_logger.addHandler(stderr_handler)

# continue creating the cluster and running code
cluster = .......
```

**Comment by yjiangnan** [comment]
@ddorian 
It seems that the reason why the delay is very large every other query is because one server died. However, when I bring all the three servers alive, the delay rotates every three queries, it seems that the query goes to different servers each time:
```
root@HDGia:~/yugabyte# python3
Python 3.8.2 (default, Apr 27 2020, 15:53:34)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from cassandra.cluster import Cluster, BatchStatement
_handler)<stdin>:1: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working

>>> import logging
>>> import sys
>>> cass_logger = logging.getLogger('cassandra')
>>> cass_logger.setLevel(logging.DEBUG)
>>> formatter = logging.Formatter('%(asctime)s:%(process)s:%(thread)d:%(name)s:%(levelname)s'
...                               ':%(filename)s:%(funcName)s():%(lineno)d:%(message)s')
>>>
>>> stderr_handler = logging.StreamHandler(sys.stdout)
>>> stderr_handler.setFormatter(formatter)
>>> stderr_handler.setLevel(logging.DEBUG)
>>> cass_logger.addHandler(stderr_handler)
>>> from cassandra.query import SimpleStatement
>>> from cassandra import ConsistencyLevel
>>> query = SimpleStatement("select * from binance.klines  where symbol=%(symbol)s and period=%(period)s", consistency_level=ConsistencyLevel.ONE)
>>> import time
>>> cluster = Cluster(['www.mydomain.com'])
2020-09-26 20:05:05,087:704388:139906292168512:cassandra.cluster:WARNING:<stdin>:<module>():1:Cluster.__init__ called with contact_points specified, but no load_balancing_policy. In the next major version, this will raise an error; please specify a load-balancing policy. (contact_points = ['www.mydomain.com'], lbp = None)
>>> session = cluster.connect()
2020-09-26 20:05:20,889:704388:139906292168512:cassandra.cluster:DEBUG:<stdin>:<module>():1:Connecting to cluster, contact points: ['www.mydomain.com']; protocol version: 4
2020-09-26 20:05:20,890:704388:139906292168512:cassandra.io.asyncorereactor:DEBUG:asyncorereactor.py:__init__():224:Validated loop dispatch with <class 'cassandra.io.asyncorereactor._AsyncorePipeDispatcher'>
2020-09-26 20:05:20,890:704388:139906292168512:cassandra.pool:DEBUG:<stdin>:<module>():1:Host 123.45.67.89 is now marked up
2020-09-26 20:05:20,895:704388:139906292168512:cassandra.cluster:DEBUG:<stdin>:<module>():1:[control connection] Opening new connection to 123.45.67.89
2020-09-26 20:05:20,910:704388:139906123228928:cassandra.io.asyncorereactor:DEBUG:asyncorereactor.py:_run_loop():254:Starting asyncore event loop
2020-09-26 20:05:20,911:704388:139906292168512:cassandra.connection:DEBUG:asyncorereactor.py:__init__():360:Not sending options message for new connection(139906123292240) to 123.45.67.89 because compression is disabled and a cql version was not specified
2020-09-26 20:05:20,911:704388:139906292168512:cassandra.connection:DEBUG:asyncorereactor.py:__init__():360:Sending StartupMessage on <AsyncoreConnection(139906123292240) 123.45.67.89:9042>
2020-09-26 20:05:20,939:704388:139906292168512:cassandra.connection:DEBUG:asyncorereactor.py:__init__():360:Sent StartupMessage on <AsyncoreConnection(139906123292240) 123.45.67.89:9042>
2020-09-26 20:05:20,975:704388:139906123228928:cassandra.connection:DEBUG:asyncorereactor.py:handle_read():438:Got ReadyMessage on new connection (139906123292240) from 123.45.67.89
2020-09-26 20:05:20,975:704388:139906292168512:cassandra.cluster:DEBUG:<stdin>:<module>():1:[control connection] Established new connection <AsyncoreConnection(139906123292240) 123.45.67.89:9042>, registering watchers and refreshing schema and topology
2020-09-26 20:05:21,345:704388:139906292168512:cassandra.cluster:DEBUG:<stdin>:<module>():1:[control connection] Refreshing node list and token map using preloaded results
2020-09-26 20:05:21,345:704388:139906292168512:cassandra.policies:INFO:policies.py:on_up():280:Using datacenter 'datacenter1' for DCAwareRoundRobinPolicy (via host '123.45.67.89'); if incorrect, please specify a local_dc to the constructor, or limit contact points to local cluster nodes
2020-09-26 20:05:21,345:704388:139906292168512:cassandra.cluster:DEBUG:<stdin>:<module>():1:[control connection] Found new host to connect to: 12.23.34.45
2020-09-26 20:05:21,345:704388:139906292168512:cassandra.cluster:INFO:<stdin>:<module>():1:New Cassandra host <Host: 12.23.34.45 datacenter1> discovered
2020-09-26 20:05:21,345:704388:139906292168512:cassandra.cluster:DEBUG:<stdin>:<module>():1:Handling new host <Host: 12.23.34.45 datacenter1> and notifying listeners
2020-09-26 20:05:21,360:704388:139906292168512:cassandra.cluster:DEBUG:<stdin>:<module>():1:Done preparing queries for new host <Host: 12.23.34.45 datacenter1>
2020-09-26 20:05:21,361:704388:139906292168512:cassandra.pool:DEBUG:<stdin>:<module>():1:Host 12.23.34.45 is now marked up
2020-09-26 20:05:21,361:704388:139906292168512:cassandra.cluster:DEBUG:<stdin>:<module>():1:[control connection] Found new host to connect to: 11.22.33.44
2020-09-26 20:05:21,361:704388:139906292168512:cassandra.cluster:INFO:<stdin>:<module>():1:New Cassandra host <Host: 11.22.33.44 datacenter1> discovered
2020-09-26 20:05:21,361:704388:139906292168512:cassandra.cluster:DEBUG:<stdin>:<module>():1:Handling new host <Host: 11.22.33.44 datacenter1> and notifying listeners
2020-09-26 20:05:21,361:704388:139906292168512:cassandra.cluster:DEBUG:<stdin>:<module>():1:Done preparing queries for new host <Host: 11.22.33.44 datacenter1>
2020-09-26 20:05:21,361:704388:139906292168512:cassandra.pool:DEBUG:<stdin>:<module>():1:Host 11.22.33.44 is now marked up
2020-09-26 20:05:21,361:704388:139906292168512:cassandra.cluster:DEBUG:<stdin>:<module>():1:[control connection] Finished fetching ring info
2020-09-26 20:05:21,361:704388:139906292168512:cassandra.cluster:DEBUG:<stdin>:<module>():1:[control connection] Rebuilding token map due to topology changes
2020-09-26 20:05:21,767:704388:139906292168512:cassandra.cluster:DEBUG:<stdin>:<module>():1:Control connection created
2020-09-26 20:05:21,787:704388:139906106181376:cassandra.pool:DEBUG:thread.py:run():57:Initializing connection for host 123.45.67.89
2020-09-26 20:05:21,788:704388:139906097788672:cassandra.pool:DEBUG:thread.py:run():57:Initializing connection for host 12.23.34.45
2020-09-26 20:05:21,789:704388:139906106181376:cassandra.connection:DEBUG:asyncorereactor.py:__init__():360:Not sending options message for new connection(139906123406880) to 123.45.67.89 because compression is disabled and a cql version was not specified
2020-09-26 20:05:21,789:704388:139906106181376:cassandra.connection:DEBUG:asyncorereactor.py:__init__():360:Sending StartupMessage on <AsyncoreConnection(139906123406880) 123.45.67.89:9042>
2020-09-26 20:05:21,789:704388:139906097788672:cassandra.connection:DEBUG:asyncorereactor.py:__init__():360:Not sending options message for new connection(139906123443024) to 12.23.34.45 because compression is disabled and a cql version was not specified
2020-09-26 20:05:21,790:704388:139906097788672:cassandra.connection:DEBUG:asyncorereactor.py:__init__():360:Sending StartupMessage on <AsyncoreConnection(139906123443024) 12.23.34.45:9042>
2020-09-26 20:05:21,790:704388:139906097788672:cassandra.connection:DEBUG:asyncorereactor.py:__init__():360:Sent StartupMessage on <AsyncoreConnection(139906123443024) 12.23.34.45:9042>
2020-09-26 20:05:21,790:704388:139906106181376:cassandra.connection:DEBUG:asyncorereactor.py:__init__():360:Sent StartupMessage on <AsyncoreConnection(139906123406880) 123.45.67.89:9042>
2020-09-26 20:05:21,792:704388:139906123228928:cassandra.connection:DEBUG:asyncorereactor.py:handle_read():438:Got ReadyMessage on new connection (139906123443024) from 12.23.34.45
2020-09-26 20:05:21,792:704388:139906097788672:cassandra.pool:DEBUG:thread.py:run():57:Finished initializing connection for host 12.23.34.45
2020-09-26 20:05:21,792:704388:139906097788672:cassandra.cluster:DEBUG:thread.py:run():57:Added pool for host 12.23.34.45 to session
2020-09-26 20:05:21,792:704388:139906097788672:cassandra.pool:DEBUG:thread.py:run():57:Initializing connection for host 11.22.33.44
2020-09-26 20:05:21,798:704388:139906123228928:cassandra.connection:DEBUG:asyncorereactor.py:handle_read():438:Got ReadyMessage on new connection (139906123406880) from 123.45.67.89
2020-09-26 20:05:21,798:704388:139906106181376:cassandra.pool:DEBUG:thread.py:run():57:Finished initializing connection for host 123.45.67.89
2020-09-26 20:05:21,799:704388:139906106181376:cassandra.cluster:DEBUG:thread.py:run():57:Added pool for host 123.45.67.89 to session
>>> 2020-09-26 20:05:21,904:704388:139906097788672:cassandra.connection:DEBUG:asyncorereactor.py:__init__():360:Not sending options message for new connection(139906123443888) to 11.22.33.44 because compression is disabled and a cql version was not specified
2020-09-26 20:05:21,904:704388:139906097788672:cassandra.connection:DEBUG:asyncorereactor.py:__init__():360:Sending StartupMessage on <AsyncoreConnection(139906123443888) 11.22.33.44:9042>
2020-09-26 20:05:21,905:704388:139906097788672:cassandra.connection:DEBUG:asyncorereactor.py:__init__():360:Sent StartupMessage on <AsyncoreConnection(139906123443888) 11.22.33.44:9042>
2020-09-26 20:05:22,043:704388:139906123228928:cassandra.connection:DEBUG:asyncorereactor.py:handle_read():438:Got ReadyMessage on new connection (139906123443888) from 11.22.33.44
2020-09-26 20:05:22,043:704388:139906097788672:cassandra.pool:DEBUG:thread.py:run():57:Finished initializing connection for host 11.22.33.44
2020-09-26 20:05:22,043:704388:139906097788672:cassandra.cluster:DEBUG:thread.py:run():57:Added pool for host 11.22.33.44 to session

>>> query = SimpleStatement("select * from binance.klines  where symbol=%(symbol)s and period=%(period)s", consistency_level=ConsistencyLevel.ONE)
>>>
>>>
>>> t0=time.time(); r = session.execute(query, {'symbol':'BTC/USDT', 'period':60}); time.time()-t0
0.37664055824279785
>>> t0=time.time(); r = session.execute(query, {'symbol':'BTC/USDT', 'period':60}); time.time()-t0
0.9959113597869873
>>> t0=time.time(); r = session.execute(query, {'symbol':'BTC/USDT', 'period':60}); time.time()-t0
0.002908468246459961
>>> t0=time.time(); r = session.execute(query, {'symbol':'BTC/USDT', 'period':60}); time.time()-t0
0.11825752258300781
>>> t0=time.time(); r = session.execute(query, {'symbol':'BTC/USDT', 'period':60}); time.time()-t0
0.1164083480834961
>>> t0=time.time(); r = session.execute(query, {'symbol':'BTC/USDT', 'period':60}); time.time()-t0
0.002574443817138672
>>> t0=time.time(); r = session.execute(query, {'symbol':'BTC/USDT', 'period':60}); time.time()-t0
0.1170649528503418
>>> t0=time.time(); r = session.execute(query, {'symbol':'BTC/USDT', 'period':60}); time.time()-t0
0.00873708724975586
>>> t0=time.time(); r = session.execute(query, {'symbol':'BTC/USDT', 'period':60}); time.time()-t0
0.003129243850708008
>>> t0=time.time(); r = session.execute(query, {'symbol':'BTC/USDT', 'period':60}); time.time()-t0
0.11914610862731934
>>> t0=time.time(); r = session.execute(query, {'symbol':'BTC/USDT', 'period':60}); time.time()-t0
0.11838483810424805
>>> t0=time.time(); r = session.execute(query, {'symbol':'BTC/USDT', 'period':60}); time.time()-t0
0.0028586387634277344
>>> t0=time.time(); r = session.execute(query, {'symbol':'BTC/USDT', 'period':60}); time.time()-t0
0.11548638343811035
>>> t0=time.time(); r = session.execute(query, {'symbol':'BTC/USDT', 'period':60}); time.time()-t0
0.023334741592407227
>>> t0=time.time(); r = session.execute(query, {'symbol':'BTC/USDT', 'period':60}); time.time()-t0
0.0028226375579833984
>>> t0=time.time(); r = session.execute(query, {'symbol':'BTC/USDT', 'period':60}); time.time()-t0
0.11678242683410645
>>> t0=time.time(); r = session.execute(query, {'symbol':'BTC/USDT', 'period':60}); time.time()-t0
0.058563947677612305
>>> t0=time.time(); r = session.execute(query, {'symbol':'BTC/USDT', 'period':60}); time.time()-t0
0.002539396286010742
>>> t0=time.time(); r = session.execute(query, {'symbol':'BTC/USDT', 'period':60}); time.time()-t0
0.1212015151977539
>>> t0=time.time(); r = session.execute(query, {'symbol':'BTC/USDT', 'period':60}); time.time()-t0
0.04344320297241211
>>> t0=time.time(); r = session.execute(query, {'symbol':'BTC/USDT', 'period':60}); time.time()-t0
0.0027298927307128906
>>> t0=time.time(); r = session.execute(query, {'symbol':'BTC/USDT', 'period':60}); time.time()-t0
0.11667704582214355
>>> t0=time.time(); r = session.execute(query, {'symbol':'BTC/USDT', 'period':60}); time.time()-t0
0.05892491340637207
>>> t0=time.time(); r = session.execute(query, {'symbol':'BTC/USDT', 'period':60}); time.time()-t0
0.0028009414672851562
>>> t0=time.time(); r = session.execute(query, {'symbol':'BTC/USDT', 'period':60}); time.time()-t0
0.11434340476989746
>>> t0=time.time(); r = session.execute(query, {'symbol':'BTC/USDT', 'period':60}); time.time()-t0
0.04154849052429199
>>> t0=time.time(); r = session.execute(query, {'symbol':'BTC/USDT', 'period':60}); time.time()-t0
0.002917051315307617
```

**Comment by yjiangnan** [comment]
@ddorian @m-iancu 

How can I only read from the local server to reduce latency?

**Comment by ddorian** [comment]
@yjiangnan can you run all queries as prepared statements and try again ?

**Comment by ddorian** [comment]
@yjiangnan 

When you create the cluster, can you set it up like this:

```python
from cassandra.policies import TokenAwarePolicy, DCAwareRoundRobinPolicy
token_policy = TokenAwarePolicy(child_policy=DCAwareRoundRobinPolicy(local_dc="<LOCAL datacenter name>"))
cluster = Cluster(
    ['<your node ips here>'],
    load_balancing_policy=token_policy
)
```

**Comment by yjiangnan** [comment]
@ddorian 
If I run `t0=time.time(); r = session.execute("select * from binance.klines  where symbol='BTC/USDT' and period=60"); time.time()-t0`, the delay is always >0.1s. 

if I use your above settings to create the cluster, what I get is a `cassandra.cluster.NoHostAvailable` error:
```

root@HDGia:~/yugabyte# python3
Python 3.8.2 (default, Apr 27 2020, 15:53:34)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from cassandra.cluster import Cluster, BatchStatement
<stdin>:1: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
>>> import logging
>>> import sys
>>> cass_logger = logging.getLogger('cassandra')
>>> cass_logger.setLevel(logging.DEBUG)
>>> formatter = logging.Formatter('%(asctime)s:%(process)s:%(thread)d:%(name)s:%(levelname)s'
...                               ':%(filename)s:%(funcName)s():%(lineno)d:%(message)s')
>>>
>>> stderr_handler = logging.StreamHandler(sys.stdout)
>>> stderr_handler.setFormatter(formatter)
>>> stderr_handler.setLevel(logging.DEBUG)
>>> cass_logger.addHandler(stderr_handler)
>>>
>>> from cassandra.policies import TokenAwarePolicy, DCAwareRoundRobinPolicy
>>> from cassandra import ConsistencyLevel
>>> from cassandra.query import SimpleStatement
>>> import time
>>>
>>> token_policy = TokenAwarePolicy(child_policy=DCAwareRoundRobinPolicy(local_dc="www.mydomain.com"))
>>>
>>> cluster = Cluster(['www.mydomain.com'], load_balancing_policy=token_policy)
<stdin>:1: DeprecationWarning: Legacy execution parameters will be removed in 4.0. Consider using execution profiles.
>>> session = cluster.connect()
2020-09-28 17:03:22,609:790609:140625325930304:cassandra.cluster:DEBUG:<stdin>:<module>():1:Connecting to cluster, contact points: ['www.mydomain.com']; protocol version: 4
2020-09-28 17:03:22,610:790609:140625325930304:cassandra.io.asyncorereactor:DEBUG:asyncorereactor.py:__init__():224:Validated loop dispatch with <class 'cassandra.io.asyncorereactor._AsyncorePipeDispatcher'>
2020-09-28 17:03:22,617:790609:140625325930304:cassandra.pool:DEBUG:<stdin>:<module>():1:Host 11.11.11.11 is now marked up
2020-09-28 17:03:22,631:790609:140625325930304:cassandra.cluster:DEBUG:<stdin>:<module>():1:[control connection] Opening new connection to 11.11.11.11
2020-09-28 17:03:22,666:790609:140625166964480:cassandra.io.asyncorereactor:DEBUG:asyncorereactor.py:_run_loop():254:Starting asyncore event loop
2020-09-28 17:03:22,666:790609:140625325930304:cassandra.connection:DEBUG:asyncorereactor.py:__init__():360:Not sending options message for new connection(140625175794400) to 11.11.11.11 because compression is disabled and a cql version was not specified
2020-09-28 17:03:22,689:790609:140625325930304:cassandra.connection:DEBUG:asyncorereactor.py:__init__():360:Sending StartupMessage on <AsyncoreConnection(140625175794400) 11.11.11.11:9042>
2020-09-28 17:03:22,703:790609:140625325930304:cassandra.connection:DEBUG:asyncorereactor.py:__init__():360:Sent StartupMessage on <AsyncoreConnection(140625175794400) 11.11.11.11:9042>
2020-09-28 17:03:22,759:790609:140625166964480:cassandra.connection:DEBUG:asyncorereactor.py:handle_read():438:Got ReadyMessage on new connection (140625175794400) from 11.11.11.11
2020-09-28 17:03:22,760:790609:140625325930304:cassandra.cluster:DEBUG:<stdin>:<module>():1:[control connection] Established new connection <AsyncoreConnection(140625175794400) 11.11.11.11:9042>, registering watchers and refreshing schema and topology
2020-09-28 17:03:23,021:790609:140625325930304:cassandra.cluster:DEBUG:<stdin>:<module>():1:[control connection] Refreshing node list and token map using preloaded results
2020-09-28 17:03:23,021:790609:140625325930304:cassandra.cluster:DEBUG:<stdin>:<module>():1:[control connection] Found new host to connect to: 22.22.22.22
2020-09-28 17:03:23,021:790609:140625325930304:cassandra.cluster:INFO:<stdin>:<module>():1:New Cassandra host <Host: 22.22.22.22 datacenter1> discovered
2020-09-28 17:03:23,022:790609:140625325930304:cassandra.cluster:DEBUG:<stdin>:<module>():1:Handling new host <Host: 22.22.22.22 datacenter1> and notifying listeners
2020-09-28 17:03:23,041:790609:140625325930304:cassandra.cluster:DEBUG:<stdin>:<module>():1:Not adding connection pool for new host <Host: 22.22.22.22 datacenter1> because the load balancing policy has marked it as IGNORED
2020-09-28 17:03:23,041:790609:140625325930304:cassandra.cluster:DEBUG:<stdin>:<module>():1:[control connection] Found new host to connect to: 33.33.33.33
2020-09-28 17:03:23,041:790609:140625325930304:cassandra.cluster:INFO:<stdin>:<module>():1:New Cassandra host <Host: 33.33.33.33 datacenter1> discovered
2020-09-28 17:03:23,041:790609:140625325930304:cassandra.cluster:DEBUG:<stdin>:<module>():1:Handling new host <Host: 33.33.33.33 datacenter1> and notifying listeners
2020-09-28 17:03:23,042:790609:140625325930304:cassandra.cluster:DEBUG:<stdin>:<module>():1:Not adding connection pool for new host <Host: 33.33.33.33 datacenter1> because the load balancing policy has marked it as IGNORED
2020-09-28 17:03:23,042:790609:140625325930304:cassandra.cluster:DEBUG:<stdin>:<module>():1:[control connection] Finished fetching ring info
2020-09-28 17:03:23,042:790609:140625325930304:cassandra.cluster:DEBUG:<stdin>:<module>():1:[control connection] Rebuilding token map due to topology changes
2020-09-28 17:03:23,679:790609:140625325930304:cassandra.cluster:DEBUG:<stdin>:<module>():1:Control connection created
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "cassandra/cluster.py", line 1295, in cassandra.cluster.Cluster.connect
  File "cassandra/cluster.py", line 1342, in cassandra.cluster.Cluster._new_session
  File "cassandra/cluster.py", line 2105, in cassandra.cluster.Session.__init__
cassandra.cluster.NoHostAvailable: ('Unable to connect to any servers', ['11.11.11.11', '22.22.22.22', '33.33.33.33'])
```
The error remains if I list all the server addresses in `'<your node ips here>'`.

**Comment by ddorian** [comment]
@yjiangnan 

Here is a full tutorial on how to deploy a multi region cluster: https://docs.yugabyte.com/latest/deploy/public-clouds/aws/manual-deployment/. (While it says multi-az, it's the same for multi-region.)

The steps that you need to follow are:

1. You need to specify on each yb-tserver/yb-master process, on which region they are residing. See https://docs.yugabyte.com/latest/reference/configuration/yb-tserver/#geo-distribution-flags. ([tutorial part](https://docs.yugabyte.com/latest/deploy/public-clouds/aws/manual-deployment/#create-yb-master1-configuration-file))

2. Configure the cluster so it tries to spread replicas into the regions using `modify_placement_info` command of `yb-admin` cli. See example: https://docs.yugabyte.com/latest/deploy/public-clouds/aws/manual-deployment/#7-configure-az-and-region-aware-placement ([tutorial part](https://docs.yugabyte.com/latest/deploy/public-clouds/aws/manual-deployment/#7-configure-az-and-region-aware-placement))

3. Use the correct names for the `local_dc` parameter. Example if we'd use the configuration in the tutorial:
```
token_policy = TokenAwarePolicy(child_policy=DCAwareRoundRobinPolicy(local_dc="aws.us-west.us-west-2a"))
```

4.  Use prepared statements like this:
```python
query = session.prepare("select * from binance.klines where symbol=%(symbol)s and period=%(period)s",
                            consistency_level=ConsistencyLevel.ONE)
```

And retry ?

**Comment by ddorian** [comment]
Closing as unresponsive. Please reply again if the issue persists.
