### ISSUE TITLE
[platform] yb_platform_virtualenv.tar.gz incomplete for on-prem platform installs

### ISSUE THREAD

**Issue by streddy-yb** [yugabyte/yugabyte-db#5836]
This is reproducible in both 2.2.3.0-b27 and 2.2.3.0-b28 yugabundle builds. 

Steps to reproduce: 
- Install platform using 2.2.3.0-b28
- Try configuring a provider; it fails with _Could not find platform dependent libraries error_

```
2020-09-27 23:04:50,493 [ERROR] from com.yugabyte.yw.common.DevopsBase in application-akka.actor.default-dispatcher-32 - Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Traceback (most recent call last):
  File "/opt/yugabyte/yugabyte-2.2.3.0-b28/devops/python_virtual_env/bin/ybcloud.py", line 4, in <module>
    __import__('pkg_resources').run_script('ybops==0.4', 'ybcloud.py')
  File "/opt/yugabyte/yugabyte-2.2.3.0-b28/devops/python_virtual_env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 18, in <module>
    from __future__ import absolute_import
ImportError: No module named __future__
```

**Comment by streddy-yb** [comment]
On-prem install bundles provided to customers have a proper yb_platform_virtualenv.tar.gz file. This issue is mainly to track internal devops changes.
