### ISSUE TITLE
[platform] Better error for handling when user creates concurrent backup tasks 

### ISSUE THREAD

**Issue by streddy-yb** [yugabyte/yugabyte-db#5888]
Backup tasks stay in "processing" forever if multiple backup tasks are created to run concurrently.

Platform only supports running one backup at a time for a universe. If the user submits multiple backup jobs (either scheduled -or- manual), you will see the following error in the log file but the backup task is left in "processing" state forever.

```
2020-09-30 20:14:16,739 [ERROR] from com.yugabyte.yw.commissioner.tasks.BackupUniverse in TaskPool-7 - Error executing task BackupUniverse(818f6039-6ed0-469b-a9d9-5c25fd7f8eac) with error='A backup for this universe is already in progress.'.
java.lang.RuntimeException: A backup for this universe is already in progress.
	at com.yugabyte.yw.commissioner.tasks.BackupUniverse.run(BackupUniverse.java:37)
	at com.yugabyte.yw.commissioner.TaskRunner.run(TaskRunner.java:143)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by streddy-yb** [comment]
Two things should be fixed here:
- If a backup task fails, always update backup status failed and not leave in "in progress". Here is an example where task failed but backup still shows as "in progress".
```
select b.state BackupState, task_type, task_state from task_info t, backup b where backup_uuid = '1ef9e046-8af6-4f40-b9ef-1abe3d48ee8a' and t.uuid = b.task_uuid;
 backupstate |   task_type    | task_state 
-------------+----------------+------------
 In Progress | BackupUniverse | Failure
(1 row)
```
- In the UI, do not allow the user to submit another backup task while there is one currently in progress
- API should be enhanced to do a pre-check and throw an error right away

**Comment by Arnav15** [comment]
Commit https://github.com/yugabyte/yugabyte-db/commit/08f0a6a9c247f5b1ff63ebc21c36e28a66465c61 prevents the task being created on the backend, but we should also prevent the user from creating the task in the first place from the UI. We can check the `universeDetails` field for the `backupInProgress` param and if that is `true`, we can just disable the backup button in the UI.

**Comment by sshev** [comment]
UI change backported to `2.4` branch by this commit https://github.com/yugabyte/yugabyte-db/commit/7ddd78fcadbf1108cd1fc3a826293e6e03c036da
