### ISSUE TITLE
CREATE TABLE () INHERITS not supported

### ISSUE THREAD

**Issue by Tedezed** [yugabyte/yugabyte-db#5956]
Jira Link: [DB-1496](https://yugabyte.atlassian.net/browse/DB-1496)
Hi!
I am trying to use Odoo with YugabyteDB, I thought it would be interesting to reflect in this issue the related problems with this application. 

```
ERROR: INHERITS not supported yet
LINE 9: CREATE TABLE ir_act_window (primary key(id)) INHERITS (ir_ac...
                                                     ^
XXX-XX-XX XX ERROR None odoo.service.db: CREATE DATABASE failed: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/odoo-13.0-py3.8.egg/odoo/service/db.py", line 58, in _initialize_db
    odoo.modules.db.initialize(cr)
  File "/usr/local/lib/python3.8/dist-packages/odoo-13.0-py3.8.egg/odoo/modules/db.py", line 32, in initialize
    cr.execute(base_sql_file.read())
  File "/usr/local/lib/python3.8/dist-packages/odoo-13.0-py3.8.egg/odoo/sql_db.py", line 164, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/odoo-13.0-py3.8.egg/odoo/sql_db.py", line 241, in execute
    res = self._obj.execute(query, params)
psycopg2.errors.FeatureNotSupported: INHERITS not supported yet
LINE 9: CREATE TABLE ir_act_window (primary key(id)) INHERITS (ir_ac...
```
#### Related
- CREATE TABLE: #1129

Regards! 🍀

**Comment by damendieta** [comment]
Hi, Any updates about INHERITS support?

**Comment by agaldemas** [comment]
Hello same question, Any updates about INHERITS support ?

**Comment by bosskopp** [comment]
I'm an official Odoo partner who'd also be interested in that feature :smiley:
Ping me if you need someone checking Odoo compatibility from time to time.

**Comment by martinfar** [comment]
Hi, any news ? We are needing it

**Comment by agaldemas** [comment]
Hello, any news about fixing this ?

**Comment by agaldemas** [comment]
> Hi @agaldemas , I think you misunderstood the context in which I mentioned this issue. I mentioned the GH in commit summary because I commented some query in PG upstream ported regression test that uses inherits. We did this change to make test YugaByteDB compatible. Inherits is still not supported in YugabyteDB.
> 
> I'm sorry for misunderstanding caused.

That's why I ask for some details about your comment ;O)...
I was trying to dive in your backlog to find out, but better to ask to people who knows...
Any idea of when INHERITS support in CREATE TABLE can be testable with Odoo ? I'm really eager to !
Thanks by advance

**Comment by agaldemas** [comment]
Hello, any news about scheduling suport of CREATE TABLE with INHERITS in YSQL ?

**Comment by iSignal** [comment]
[Table inheritance](https://docs.yugabyte.com/preview/explore/ysql-language-features/advanced-features/inheritance/) will be available as a tech preview feature in the next Yugabyte release `Preview train: 2.27+, Stable train: 2025.1+`. 

For known limitations and remaining issues, see the docs page and https://github.com/yugabyte/yugabyte-db/issues/27949
