### ISSUE TITLE
pggate_test_catalog core dumps when built with devtoolset-8's gcc 8

### ISSUE THREAD

**Issue by mbautin** [yugabyte/yugabyte-db#6039]
```
(gdb) where
#0  0x00007fb75dace243 in set_next (next=0x1d232c8, n=0x0) at ../../src/yb/yql/pggate/pg_memctx.cc:65
#1  link_before (this_node=0x1d232c8, nxt_node=0x2170ec8) at ../../../yugabyte-db-thirdparty/installed/uninstrumented/include/boost/intrusive/circular_list_algorithms.hpp:182
#2  push_back (value=..., this=0x2170ec0) at ../../../yugabyte-db-thirdparty/installed/uninstrumented/include/boost/intrusive/list.hpp:272
#3  yb::pggate::PgMemctx::Register (this=0x2170e80, obj=0x1d232c0) at ../../src/yb/yql/pggate/pg_memctx.cc:65
Python Exception <class 'gdb.error'> There is no member or method named _M_head_impl.:
#4  0x00007fb75da7e00f in yb::pggate::PgApiImpl::AddToCurrentPgMemctx (this=this@entry=0x216e280, stmt=, handle=handle@entry=0x7ffff8df7128) at ../../src/yb/yql/pggate/pggate.cc:278
#5  0x00007fb75da82400 in yb::pggate::PgApiImpl::NewCreateDatabase (this=0x216e280, database_name=0x218fb48 "pggate_test_database", database_oid=database_oid@entry=1, source_database_oid=source_database_oid@entry=0, next_oid=next_oid@entry=0, colocated=false, handle=0x7ffff8df7128)
    at ../../src/yb/yql/pggate/pggate.cc:381
#6  0x00007fb75da77e18 in yb::pggate::YBCPgNewCreateDatabase (database_name=<optimized out>, database_oid=database_oid@entry=1, source_database_oid=source_database_oid@entry=0, next_oid=next_oid@entry=0, colocated=colocated@entry=false, handle=handle@entry=0x7ffff8df7128)
    at ../../src/yb/yql/pggate/ybc_pggate.cc:171
#7  0x00007fb7624cb3c3 in yb::pggate::PggateTest::CreateDB (this=this@entry=0x1c68300, db_name="pggate_test_database", db_oid=db_oid@entry=1) at ../../src/yb/yql/pggate/test/pggate_test.cc:147
#8  0x00007fb7624cb446 in yb::pggate::PggateTest::SetupDB (this=this@entry=0x1c68300, db_name="pggate_test_database", db_oid=db_oid@entry=1) at ../../src/yb/yql/pggate/test/pggate_test.cc:141
#9  0x00007fb7624cb53e in yb::pggate::PggateTest::Init (this=this@entry=0x1c68300, test_name=test_name@entry=0x40deda "TestCopydb", num_tablet_servers=num_tablet_servers@entry=3) at ../../src/yb/yql/pggate/test/pggate_test.cc:118
#10 0x0000000000409d7d in yb::pggate::PggateTestCatalog_TestCopydb_Test::TestBody (this=0x1c68300) at ../../src/yb/yql/pggate/test/pggate_test_catalog.cc:367
#11 0x00007fb75543c3be in HandleSehExceptionsInMethodIfSupported<testing::Test, void> (location=0x7fb75544fa5f "the test body", method=<optimized out>, object=0x1c68300) at /home/yugabyte/code/yugabyte-db-thirdparty/src/gmock-1.8.0/googletest/src/gtest-internal-inl.h:803
#12 testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void> (object=object@entry=0x1c68300, method=<optimized out>, location=location@entry=0x7fb75544fa5f "the test body") at /home/yugabyte/code/yugabyte-db-thirdparty/src/gmock-1.8.0/googletest/src/gtest.cc:2438
#13 0x00007fb755432ed2 in Run (this=0x1c68300) at /home/yugabyte/code/yugabyte-db-thirdparty/src/gmock-1.8.0/googletest/src/gtest.cc:2474
#14 testing::Test::Run (this=0x1c68300) at /home/yugabyte/code/yugabyte-db-thirdparty/src/gmock-1.8.0/googletest/src/gtest.cc:2465
#15 0x00007fb755433018 in Run (this=0x1c720c0) at /home/yugabyte/code/yugabyte-db-thirdparty/src/gmock-1.8.0/googletest/src/gtest.cc:2656
#16 testing::TestInfo::Run (this=0x1c720c0) at /home/yugabyte/code/yugabyte-db-thirdparty/src/gmock-1.8.0/googletest/src/gtest.cc:2630
#17 0x00007fb7554330f5 in Run (this=0x1cdc1c0) at /home/yugabyte/code/yugabyte-db-thirdparty/src/gmock-1.8.0/googletest/src/gtest.cc:2774
#18 testing::TestCase::Run (this=0x1cdc1c0) at /home/yugabyte/code/yugabyte-db-thirdparty/src/gmock-1.8.0/googletest/src/gtest.cc:2759
#19 0x00007fb7554335cc in RunAllTests (this=0x1d4c960) at /home/yugabyte/code/yugabyte-db-thirdparty/src/gmock-1.8.0/googletest/src/gtest-internal-inl.h:586
#20 testing::internal::UnitTestImpl::RunAllTests() () at /home/yugabyte/code/yugabyte-db-thirdparty/src/gmock-1.8.0/googletest/src/gtest.cc:4551
#21 0x00007fb75543c8de in HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (location=0x7fb755450c98 "auxiliary test code (environments or event listeners)", method=<optimized out>, object=0x1d4c960)
    at /home/yugabyte/code/yugabyte-db-thirdparty/src/gmock-1.8.0/googletest/src/gtest-internal-inl.h:803
#22 testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (object=0x1d4c960, method=<optimized out>, location=location@entry=0x7fb755450c98 "auxiliary test code (environments or event listeners)")
    at /home/yugabyte/code/yugabyte-db-thirdparty/src/gmock-1.8.0/googletest/src/gtest.cc:2438
#23 0x00007fb7554336c5 in testing::UnitTest::Run() () at /home/yugabyte/code/yugabyte-db-thirdparty/src/gmock-1.8.0/googletest/include/gtest/gtest.h:1287
#24 0x00007fb7622c091e in RUN_ALL_TESTS () at ../../../yugabyte-db-thirdparty/installed/uninstrumented/include/gtest/gtest.h:2233
#25 main (argc=<optimized out>, argv=<optimized out>) at ../../src/yb/util/test_main.cc:104
#26 0x00007fb7506f2555 in __libc_start_main () from /lib64/libc.so.6
#27 0x0000000000406719 in _start ()
```

**Comment by mbautin** [comment]
Another stack trace in initdb, the same type of build:
```
(gdb) where
#0  0x00007f7192a17387 in raise () from /lib64/libc.so.6
#1  0x00007f7192a18a78 in abort () from /lib64/libc.so.6
#2  0x00007f718fdb7dca in tcmalloc::Log(tcmalloc::LogMode, char const*, int, tcmalloc::LogItem, tcmalloc::LogItem, tcmalloc::LogItem, tcmalloc::LogItem) [clone .cold.1] ()
   from /nfusr/dev-server/mbautin2/code/yugabyte-db-devtoolset8/build/debug-gcc-dynamic-ninja/lib/../../../../yugabyte-db-thirdparty-devtoolset-8/installed/uninstrumented/lib/libtcmalloc.so.4
#3  0x00007f718fdb94b9 in (anonymous namespace)::InvalidFree(void*) () from /nfusr/dev-server/mbautin2/code/yugabyte-db-devtoolset8/build/debug-gcc-dynamic-ninja/lib/../../../../yugabyte-db-thirdparty-devtoolset-8/installed/uninstrumented/lib/libtcmalloc.so.4
#4  0x00007f718b714ba4 in ~percpu_rwlock (this=0x253c720, __in_chrg=<optimized out>) at ../../src/yb/util/locks.h:110
#5  yb::rpc::Messenger::~Messenger (this=0x253c6c0, __in_chrg=<optimized out>) at ../../src/yb/rpc/messenger.cc:577
#6  0x00007f718b714c4d in yb::rpc::Messenger::~Messenger (this=0x253c6c0, __in_chrg=<optimized out>) at ../../src/yb/rpc/messenger.cc:577
#7  0x00007f71938a2a98 in operator() (__ptr=<optimized out>, this=0x24e8d48) at ../../src/yb/yql/pggate/pggate.cc:198
#8  ~unique_ptr (this=0x24e8d48, __in_chrg=<optimized out>) at /opt/rh/devtoolset-8/root/usr/include/c++/8/bits/unique_ptr.h:274
#9  ~MessengerHolder (this=0x24e8d40, __in_chrg=<optimized out>) at ../../src/yb/yql/pggate/pggate.h:478
#10 yb::pggate::PgApiImpl::~PgApiImpl (this=0x24e8bc0, __in_chrg=<optimized out>) at ../../src/yb/yql/pggate/pggate.cc:196
#11 0x00007f71938a2bf1 in yb::pggate::PgApiImpl::~PgApiImpl (this=0x24e8bc0, __in_chrg=<optimized out>) at ../../src/yb/yql/pggate/pggate.cc:196
#12 0x00007f719389692c in yb::pggate::YBCDestroyPgGate () at ../../src/yb/yql/pggate/ybc_pggate.cc:95
#13 0x00000000009dfdf5 in YBOnPostgresBackendShutdown () at ../../../../../../../src/postgres/src/backend/utils/misc/pg_yb_utils.c:440
#14 0x000000000083f646 in proc_exit (code=code@entry=0) at ../../../../../../../src/postgres/src/backend/storage/ipc/ipc.c:152
#15 0x0000000000871d42 in PostgresMain (argc=argc@entry=10, argv=argv@entry=0x24b7130, dbname=<optimized out>, dbname@entry=0x0, username=0x24bcc60 "mbautin2") at ../../../../../../src/postgres/src/backend/tcop/postgres.c:5337
#16 0x000000000072eebe in PostgresServerProcessMain (argc=10, argv=0x24b7130) at ../../../../../../src/postgres/src/backend/main/main.c:230
#17 0x000000000072efc1 in main ()
```
