### ISSUE TITLE
Consistent crash when failing to resolve DNS during a master web ui request

### ISSUE THREAD

**Issue by iSignal** [yugabyte/yugabyte-db#6109]
It looks like if we fail to resolve DNS while processing a master web UI request, we are not in the right thread pool to execute the failure handler.

```
Thread 1 (LWP 752):
#0  alloc (this=0x0) at /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20200829090443-f431681041-centos/installed/uninstrumented/include/cds/gc/dhp.h:109
#1  Guard (this=<synthetic pointer>) at /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20200829090443-f431681041-centos/installed/uninstrumented/include/cds/gc/dhp.h:710
#2  cds::intrusive::BasketQueue<cds::gc::DHP, cds::container::details::make_basket_queue<cds::gc::DHP, yb::rpc::ThreadPoolTask*, cds::container::basket_queue::traits>::node_type, cds::container::details::make_basket_queue<cds::gc::DHP, yb::rpc::ThreadPoolTask*, cds::container::basket_queue::traits>::intrusive_traits>::enqueue (this=this@entry=0x1a48930, val=...)
    at /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20200829090443-f431681041-centos/installed/uninstrumented/include/cds/intrusive/basket_queue.h:634
#3  0x00007fcf507c7d0b in enqueue (val=<synthetic pointer>, this=<optimized out>)
    at /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20200829090443-f431681041-centos/installed/uninstrumented/include/cds/container/basket_queue.h:296
#4  push (val=<synthetic pointer>, this=<optimized out>)
    at /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20200829090443-f431681041-centos/installed/uninstrumented/include/cds/container/basket_queue.h:339
#5  yb::rpc::ThreadPool::Impl::Enqueue (this=<optimized out>, task=task@entry=0x3544e40) at ../../src/yb/rpc/thread_pool.cc:186
#6  0x00007fcf507c36fd in yb::rpc::ThreadPool::Enqueue (this=<optimized out>, task=task@entry=0x3544e40) at ../../src/yb/rpc/thread_pool.cc:290
#7  0x00007fcf5077018b in yb::rpc::OutboundCall::InvokeCallback (this=this@entry=0x3544d90) at ../../src/yb/rpc/outbound_call.cc:368
#8  0x00007fcf507703b7 in yb::rpc::OutboundCall::SetFailed (this=0x3544d90, status=..., err_pb=...) at ../../src/yb/rpc/outbound_call.cc:495
#9  0x00007fcf5077b1eb in yb::rpc::Proxy::NotifyFailed (controller=<optimized out>, status=...) at ../../src/yb/rpc/proxy.cc:293
#10 0x00007fcf5077b39f in yb::rpc::Proxy::NotifyAllFailed (this=this@entry=0x3132140, status=...) at ../../src/yb/rpc/proxy.cc:251
#11 0x00007fcf5077b4e7 in yb::rpc::Proxy::ResolveDone (this=this@entry=0x3132140, result=...) at ../../src/yb/rpc/proxy.cc:270
#12 0x00007fcf5077d0dc in yb::rpc::Proxy::HandleResolve (this=0x3132140, result=...) at ../../src/yb/rpc/proxy.cc:259
#13 0x00007fcf4efa8bfd in operator() (__args#0=..., this=0x7fcf34b3bec0)
    at /tmp/core/yugabyte-2.3.2.0/linuxbrew-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/Cellar/gcc/5.5.0_4/include/c++/5.5.0/functional:2267
#14 yb::DnsResolver::Impl::CacheEntry::DoResolve(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::function<void (yb::Result<boost::asio::ip::address> const&)> const*, boost::asio::ip::basic_resolver<boost::asio::ip::tcp>*) (this=this@entry=0x1a4ed18, host=..., callback=<optimized out>, callback@entry=0x7fcf34b3bec0,
    resolver=resolver@entry=0x1a4e6c0) at ../../src/yb/util/net/dns_resolver.cc:146
#15 0x00007fcf4efa31f2 in AsyncResolve (callback=..., host=..., this=<optimized out>) at ../../src/yb/util/net/dns_resolver.cc:98
#16 yb::DnsResolver::AsyncResolve(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::function<void (yb::Result<boost::asio::ip::address> const&)> const&) (this=<optimized out>, host=..., callback=...) at ../../src/yb/util/net/dns_resolver.cc:240
#17 0x00007fcf5077c39a in yb::rpc::Proxy::Resolve (this=this@entry=0x3132140) at ../../src/yb/rpc/proxy.cc:245
#18 0x00007fcf5077ccb2 in yb::rpc::Proxy::DoAsyncRequest(yb::rpc::RemoteMethod const*, google::protobuf::Message const&, google::protobuf::Message*, yb::rpc::RpcController*, std::function<void ()>, bool) (this=0x3132140,
    method=method@entry=0x7fcf52a2cc20 <yb::master::MasterServiceProxy::GetMasterRegistrationAsync(yb::master::GetMasterRegistrationRequestPB const&, yb::master::GetMasterRegistrationResponsePB*, yb::rpc::RpcController*, std::function<void ()>)::method>, req=..., resp=resp@entry=0x3356d10, controller=controller@entry=0x3356d48, callback=...,
    force_run_callback_on_reactor=<optimized out>) at ../../src/yb/rpc/proxy.cc:198
#19 0x00007fcf5077cf4b in yb::rpc::Proxy::AsyncRequest(yb::rpc::RemoteMethod const*, google::protobuf::Message const&, google::protobuf::Message*, yb::rpc::RpcController*, std::function<void ()>) (this=<optimized out>,
    method=method@entry=0x7fcf52a2cc20 <yb::master::MasterServiceProxy::GetMasterRegistrationAsync(yb::master::GetMasterRegistrationRequestPB const&, yb::master::GetMasterRegistrationResponsePB*, yb::rpc::RpcController*, std::function<void ()>)::method>, req=..., resp=resp@entry=0x3356d10, controller=controller@entry=0x3356d48, callback=...)
    at ../../src/yb/rpc/proxy.cc:120
#20 0x00007fcf52799ee1 in yb::master::MasterServiceProxy::GetMasterRegistrationAsync(yb::master::GetMasterRegistrationRequestPB const&, yb::master::GetMasterRegistrationResponsePB*, yb::rpc::RpcController*, std::function<void ()>) (this=this@entry=0x3356d70, req=..., resp=resp@entry=0x3356d10, controller=controller@entry=0x3356d48, callback=...)
    at src/yb/master/master.proxy.cc:604
#21 0x00007fcf52f4df51 in yb::master::GetMasterEntryForHosts (proxy_cache=0x1a56690, hostports=..., timeout=..., e=e@entry=0x7fcf34b3c4f0) at ../../src/yb/master/master_util.cc:67
---Type <return> to continue, or q <return> to quit---
#22 0x00007fcf59806a6a in yb::master::Master::ListMasters (this=0x7ffd437afe20, masters=masters@entry=0x7fcf34b3c630) at ../../src/yb/master/master.cc:423
#23 0x00007fcf5981fb7b in yb::master::MasterPathHandlers::RedirectToLeader (this=this@entry=0x1a6a2c0, req=..., resp=resp@entry=0x7fcf34b3cde0)
    at ../../src/yb/master/master-path-handlers.cc:144
#24 0x00007fcf5982e74a in yb::master::MasterPathHandlers::RootHandler (this=0x1a6a2c0, req=..., resp=0x7fcf34b3cde0) at ../../src/yb/master/master-path-handlers.cc:1205
#25 0x00007fcf55e4de7c in operator() (__args#1=0x7fcf34b3cde0, __args#0=..., this=<optimized out>)
    at /tmp/core/yugabyte-2.3.2.0/linuxbrew-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/Cellar/gcc/5.5.0_4/include/c++/5.5.0/functional:2267
#26 yb::Webserver::RunPathHandler (this=this@entry=0x1dae000, handler=..., connection=connection@entry=0x9d14000, request_info=request_info@entry=0x9d14000)
    at ../../src/yb/server/webserver.cc:423
#27 0x00007fcf55e4eb0a in yb::Webserver::BeginRequestCallback (this=0x1dae000, connection=0x9d14000, request_info=0x9d14000) at ../../src/yb/server/webserver.cc:360
#28 0x00007fcf55e63e16 in handle_request () from /tmp/core/yugabyte-2.3.2.0/lib/yb/libserver_process.so
#29 0x00007fcf55e669fe in worker_thread () from /tmp/core/yugabyte-2.3.2.0/lib/yb/libserver_process.so
#30 0x00007fcf4a73f694 in ?? ()
```

**Comment by bmatican** [comment]
From @spolitov in slack
> it looks like webserver library starts his own threads, that does not init cds. So we should handle it somehow. Not sure that there will be a clean way to attach/detach cds to them
