### ISSUE TITLE
provision_instance.py script not prompting for password for "non-passwordless sudo" case

### ISSUE THREAD

**Issue by streddy-yb** [yugabyte/yugabyte-db#6196]
How to repro:
- Create an onprem provider and add a node
- On the node, enable sudo password requirement for SSH user
- Run provision_instance.py and it fails

```
/opt/yugabyte/data/provision/a0175d58-52ba-48ab-b7ce-55bb4eb9345a/provision_instance.py --ip 10.150.0.102 --mount_points /storage
Executing provision now for instance with IP 10.150.0.102...
Failed!
2020-10-28 16:22:27,746 INFO: Found onprem cloud credentials in env.
2020-10-28 16:22:27,746 INFO: Host @@DEFAULT_NODE_NAME@@ already created.
2020-10-28 16:22:27,746 INFO: Running ansible command ["ansible-playbook" "/opt/yugabyte/yugabyte-2.2.4.0-b5/devops/yb-server-provision.yml" "--vault-password-file" "/opt/yugabyte/data/keys/a0175d58-52ba-48ab-b7ce-55bb4eb9345a/onprem-provider-key.vault_password" "--private-key" "/opt/yugabyte/data/keys/a0175d58-52ba-48ab-b7ce-55bb4eb9345a/onprem-provider-key.pem" "--user" "centos" "-i" "10.150.0.102," "-c" "ssh" "--extra-vars" "{\"server_type\": \"cluster-server\", \"ssd_size_gb\": 250, \"yb_home_dir\": \"/home/yugabyte\", \"instance_search_pattern\": \"all\", \"disk_iops\": 1000, \"device_names\": [], \"node_exporter_port\": 9300, \"yb_ansible_host\": \"10.150.0.102\", \"install_node_exporter\": true, \"vars_file\": \"/opt/yugabyte/data/keys/a0175d58-52ba-48ab-b7ce-55bb4eb9345a/onprem-provider-key.vault\", \"ansible_port\": 22, \"cloud_type\": \"onprem\", \"mount_points\": \"/storage\", \"local_package_path\": \"/opt/yugabyte/third-party\", \"yb_server_ssh_user\": \"centos\", \"num_volumes\": 8, \"instance_name\": \"@@DEFAULT_NODE_NAME@@\", \"instance_type\": null, \"ssh_user\": \"centos\", \"node_exporter_user\": \"prometheus\", \"user_name\": \"yugabyte\", \"air_gap\": true}"]

PLAY [Validate server type] ****************************************************

TASK [setup] *******************************************************************
Wednesday 28 October 2020  16:22:28 +0000 (0:00:00.012)       0:00:00.012 ***** 
ok: [localhost]

TASK [assert] ******************************************************************
Wednesday 28 October 2020  16:22:29 +0000 (0:00:00.458)       0:00:00.470 ***** 
ok: [localhost] => {
    "changed": false, 
    "msg": "All assertions passed"
}

PLAY [Install Python on Ubuntu] ************************************************

TASK [Verify and Install Python] ***********************************************
Wednesday 28 October 2020  16:22:29 +0000 (0:00:00.025)       0:00:00.496 ***** 
skipping: [10.150.0.102]

PLAY [Provision server] ********************************************************

TASK [setup] *******************************************************************
Wednesday 28 October 2020  16:22:29 +0000 (0:00:00.083)       0:00:00.579 ***** 
fatal: [10.150.0.102] FAILED! => {"changed": false, "failed": true, "module_stderr": "Shared connection to 10.150.0.102 closed.\r\n", "module_stdout": "sudo: a password is required\r\n", "msg": "MODULE FAILURE"}
	to retry, use: --limit @/opt/yugabyte/yugabyte-2.2.4.0-b5/devops/yb-server-provision.retry

PLAY RECAP *********************************************************************
10.150.0.102               : ok=0    changed=0    unreachable=0    failed=1   
localhost                  : ok=2    changed=0    unreachable=0    failed=0   

Wednesday 28 October 2020  16:22:30 +0000 (0:00:00.928)       0:00:01.508 ***** 
=============================================================================== 
setup ------------------------------------------------------------------- 0.93s
setup ------------------------------------------------------------------- 0.46s
Verify and Install Python ----------------------------------------------- 0.08s
assert ------------------------------------------------------------------ 0.03s
Traceback (most recent call last):
  File "/opt/yugabyte/yugabyte-2.2.4.0-b5/devops/python_virtual_env/bin/ybcloud.py", line 4, in <module>
    __import__('pkg_resources').run_script('ybops==0.4', 'ybcloud.py')
  File "/opt/yugabyte/yugabyte-2.2.4.0-b5/devops/python_virtual_env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/opt/yugabyte/yugabyte-2.2.4.0-b5/devops/python_virtual_env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1462, in run_script
    exec(code, namespace, namespace)
  File "/opt/yugabyte/yugabyte-2.2.4.0-b5/devops/python_virtual_env/lib/python2.7/site-packages/ybops-0.4-py2.7.egg/EGG-INFO/scripts/ybcloud.py", line 15, in <module>
    YbCloud().run()
  File "/opt/yugabyte/yugabyte-2.2.4.0-b5/devops/python_virtual_env/lib/python2.7/site-packages/ybops-0.4-py2.7.egg/ybops/cloud/ybcloud.py", line 54, in run
    self.options.func(self.options)
  File "/opt/yugabyte/yugabyte-2.2.4.0-b5/devops/python_virtual_env/lib/python2.7/site-packages/ybops-0.4-py2.7.egg/ybops/cloud/common/method.py", line 76, in callback_wrapper
    self.callback(args)
  File "/opt/yugabyte/yugabyte-2.2.4.0-b5/devops/python_virtual_env/lib/python2.7/site-packages/ybops-0.4-py2.7.egg/ybops/cloud/onprem/method.py", line 61, in callback
    super(OnPremProvisionInstancesMethod, self).callback(args)
  File "/opt/yugabyte/yugabyte-2.2.4.0-b5/devops/python_virtual_env/lib/python2.7/site-packages/ybops-0.4-py2.7.egg/ybops/cloud/common/method.py", line 387, in callback
    self.cloud.setup_ansible(args).run("yb-server-provision.yml", self.extra_vars, host_info)
  File "/opt/yugabyte/yugabyte-2.2.4.0-b5/devops/python_virtual_env/lib/python2.7/site-packages/ybops-0.4-py2.7.egg/ybops/cloud/common/ansible.py", line 130, in run
    process_args, p.returncode, stderr))
ybops.common.exceptions.YBOpsRuntimeError: Runtime error: Playbook with args ['ansible-playbook', '/opt/yugabyte/yugabyte-2.2.4.0-b5/devops/yb-server-provision.yml', '--vault-password-file', '/opt/yugabyte/data/keys/a0175d58-52ba-48ab-b7ce-55bb4eb9345a/onprem-provider-key.vault_password', '--private-key', '/opt/yugabyte/data/keys/a0175d58-52ba-48ab-b7ce-55bb4eb9345a/onprem-provider-key.pem', '--user', 'centos', '-i', u'10.150.0.102,', '-c', 'ssh', '--extra-vars', '{"server_type": "cluster-server", "ssd_size_gb": 250, "yb_home_dir": "/home/yugabyte", "instance_search_pattern": "all", "disk_iops": 1000, "device_names": [], "node_exporter_port": 9300, "yb_ansible_host": "10.150.0.102", "install_node_exporter": true, "vars_file": "/opt/yugabyte/data/keys/a0175d58-52ba-48ab-b7ce-55bb4eb9345a/onprem-provider-key.vault", "ansible_port": 22, "cloud_type": "onprem", "mount_points": "/storage", "local_package_path": "/opt/yugabyte/third-party", "yb_server_ssh_user": "centos", "num_volumes": 8, "instance_name": "@@DEFAULT_NODE_NAME@@", "instance_type": null, "ssh_user": "centos", "node_exporter_user": "prometheus", "user_name": "yugabyte", "air_gap": true}'] failed with return code 2 and error fatal: [10.150.0.102] FAILED! => {"changed": false, "failed": true, "module_stderr": "Shared connection to 10.150.0.102 closed.\r\n", "module_stdout": "sudo: a password is required\r\n", "msg": "MODULE FAILURE"}
```

**Comment by streddy-yb** [comment]
Hi @WesleyW -can you update the informational message that shows the script users needs to run to pre-provision a node include "--ask_password" option?
