### ISSUE TITLE
./yb_release --build release --build_target ./build/target --build_archive  throw  exception

### ISSUE THREAD

**Issue by jiaolongxue** [yugabyte/yugabyte-db#6293]
**os：centos7.4**
**yugabytedb src version    2.3.3**

**cmd**
```
[root@localhost yugabyte]# pwd
/root/code/yugabyte
./yb_release --build release --build_target ./build/target --build_archive
```

**errmsg**
```
Traceback (most recent call last):
  File "/root/code/yugabyte/build-support/yb_release.py", line 294, in <module>
    main()
  File "/root/code/yugabyte/build-support/yb_release.py", line 185, in main
    subprocess.check_call(final_build_cmd_list)
  File "/usr/lib64/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['./yb_build.sh', '--write-build-descriptor', '/root/code/yugabyte/build/yb_release_tmp_52eebb03-15c1-44bd-ba66-0a16408377e4/build_descriptor.yaml', 'release', 'packaged_targets', '--skip-java', 'reinitdb']' returned non-zero exit status 2.

```

```
ard error)', <yugabyte_pycommon.external_calls.ProgramResult object at 0x7fc057aeacc0>)
make[3]: *** [src/yb/yql/pgwrapper/CMakeFiles/initial_sys_catalog_snapshot] Error 1
make[2]: *** [src/yb/yql/pgwrapper/CMakeFiles/initial_sys_catalog_snapshot.dir/all] Error 2
make[1]: *** [src/yb/yql/pgwrapper/CMakeFiles/initial_sys_catalog_snapshot.dir/rule] Error 2
make: *** [initial_sys_catalog_snapshot] Error 2

```

```
[m-1] I1106 12:39:27.738485 14729 catalog_manager.cc:711] T 00000000000000000000000000000000 P e924ba2088d64bfcac275753f9a33df3: Completed load of sys catalog in term 1
E1106 12:39:28.104327 14696 external_mini_cluster.cc:1030] master reported an initdb error: Runtime error (yb/yql/pgwrapper/pg_wrapper.cc:341): /root/code/yugabyte/build/release-gcc-dynamic/postgres/bin/initdb failed with exit code 256
/root/code/yugabyte/src/yb/yql/pgwrapper/pg_wrapper_test_base.cc:55: Failure
Failed
Bad status: Runtime error (yb/integration-tests/external_mini_cluster.cc:1031): Failed to start masters.: initdb failed: Runtime error (yb/yql/pgwrapper/pg_wrapper.cc:341): /root/code/yugabyte/build/release-gcc-dynamic/postgres/bin/initdb failed with exit code 256
Test failure stack trace:
    @     0x7f4e3bf01225  MinimalistPrinter::OnTestPartResult()
    @     0x7f4e2b42aca1  testing::internal::TestEventRepeater::OnTestPartResult()
    @     0x7f4e2b444581  testing::UnitTest::AddTestPartResult()
    @     0x7f4e2b444a53  testing::internal::AssertHelper::operator=()
    @     0x7f4e3c127f34  yb::pgwrapper::PgWrapperTestBase::SetUp()
    @     0x7f4e2b44efe8  testing::internal::HandleExceptionsInMethodIfSupported<>()
    @     0x7f4e2b445db6  testing::Test::Run()
    @     0x7f4e2b445f68  testing::TestInfo::Run()
    @     0x7f4e2b446045  testing::TestCase::Run()
    @     0x7f4e2b4462f8  testing::internal::UnitTestImpl::RunAllTests()
    @     0x7f4e2b44f498  testing::internal::HandleExceptionsInMethodIfSupported<>()
    @     0x7f4e2b44663e  testing::UnitTest::Run()
    @     0x7f4e3bf00ccf  main
    @     0x7f4e2a38f825  __libc_start_main
    @           0x406759  _start
    @              (nil)  (unknown)

I1106 12:39:28.113143 14696 external_mini_cluster.cc:1849] { daemon_id: m-1 bound_rpc: :0 } Starting Shutdown()
I1106 12:39:28.113164 14696 external_mini_cluster.cc:1892] Killing /root/code/yugabyte/build/release-gcc-dynamic/tests-pgwrapper/../bin/yb-master with pid 14703 with SIGKILL
I1106 12:39:28.118628 14696 test_util.cc:93] -----------------------------------------------
I1106 12:39:28.118646 14696 test_util.cc:94] Had fatal failures, leaving test files at /tmp/yb_test.tmp.15152.26796.2771.pid14632/create_initial_sys_catalog_snapshot.CreateInitialSysCatalogSnapshotTest.CreateInitialSysCatalogSnapshot.1604666126024832-14696
[m-1 stdout] running bootstrap script ... 
[  FAILED  ] CreateInitialSysCatalogSnapshotTest.CreateInitialSysCatalogSnapshot (242074 ms)
[----------] 1 test from CreateInitialSysCatalogSnapshotTest (242074 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (242074 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] CreateInitialSysCatalogSnapshotTest.CreateInitialSysCatalogSnapshot

 1 FAILED TEST

```

**without build_archive executed successfully**

**Comment by svarnau** [comment]
I ran this command on code version v2.3.3.0 on centos7.

Ran into slight packaging issue with the --build_target option, but it worked without that option.

I did not run into any issues with initdb. I'm not best person to figure that out. Maybe @mbautin or @d-uspenskiy can suggest someone to look at this.
