### ISSUE TITLE
TestYSQLMetrics#testStatementTime sometimes fails due to getAutoCommit() throwing error

### ISSUE THREAD

**Issue by tedyu** [yugabyte/yugabyte-db#6297]
From https://detective-gcp.dev.yugabyte.com/job/github-yugabyte-db-phabricator%2F63258%2Fartifact%2Fjava%2Fyb-pgsql%2Ftarget%2Fsurefire-reports_org.yb.pgsql.TestYSQLMetrics__testStatementTime%2Forg.yb.pgsql.TestYSQLMetrics-output.txt?class=org.yb.pgsql.TestYSQLMetrics&max_lines=3000&name=testStatementTime&start_line=3001 
```
[ts-1] | I | 33.862925 | 5309 | client-internal.cc:644 | Deleted table 000030af000030008000000000004001
-- | -- | -- | -- | -- | --
5987 |   | ERROR | 33.867000 | main | BaseYBTest.java:240 | YB Java test failed: class="org.yb.pgsql.TestYSQLMetrics", method="testStatementTime"
5988 | java.lang.AssertionError: pgStatement.getConnection().getAutoCommit() should not throw
5989 | at org.postgresql.jdbc.BatchResultHandler.isAutoCommit(BatchResultHandler.java:105)
5990 | at org.postgresql.jdbc.BatchResultHandler.handleCompletion(BatchResultHandler.java:161)
5991 | at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:492)
5992 | at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:840)
5993 | at org.yb.pgsql.TestYSQLMetrics.testStatement(TestYSQLMetrics.java:218)
5994 | at org.yb.pgsql.TestYSQLMetrics.testStatement(TestYSQLMetrics.java:202)
5995 | at org.yb.pgsql.TestYSQLMetrics.testStatementTime(TestYSQLMetrics.java:170)
```

**Comment by tedyu** [comment]
Caused by https://github.com/pgjdbc/pgjdbc/issues/1458
