### ISSUE TITLE
 ./yb_release --build release --build_target ./build/target --yw throw exception

### ISSUE THREAD

**Issue by jiaolongxue** [yugabyte/yugabyte-db#6312]
**os centos7.4**
**sbt version 1.4.0**
**Java version: 1.8.0_262, vendor: Oracle Corporation**
**Maven 3.0.5**
**node v6.17.1**
**npm v3.10.10**

**/yugabyte-db/managed/project\x1b[0m\nInstalling the s3:// URLStreamHandler via **
+ It looks like the S3 address （YB_MAP_URL）is missing
+ Which version of nodejs i need to install
```
Traceback (most recent call last):
  File "/root/yugabyte-db/build-support/yb_release.py", line 294, in <module>
    main()
  File "/root/yugabyte-db/build-support/yb_release.py", line 263, in main
    subprocess.check_output(package_yw_cmd, cwd=managed_dir)
  File "/usr/lib64/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib64/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/root/yugabyte-db/managed/yb_release', '--destination', './build/target/ui', '--unarchived']' returned non-zero exit status 1.
```

```
2020-11-08 23:35:03,453 INFO: [yb_release.py:4] Finished running SBT universal packaging.
2020-11-08 23:35:03,454 ERROR: [yb_release.py:4] No archives found matching the pattern '/root/yugabyte-db/managed/target/universal/yugaware*.tgz'
Traceback (most recent call last):
  File "/root/yugabyte-db/managed/yb_release.py", line 73, in <module>
    raise e
  File "/root/yugabyte-db/managed/yb_release.py", line 49, in <module>
    raise IOError("No archives found matching the pattern '%s'" % yugaware_tar_gz_glob)
OSError: No archives found matching the pattern '/root/yugabyte-db/managed/target/universal/yugaware*.tgz'
2020-11-08 23:35:03,490 [yb_release.py:267 ERROR] Failed to build YugaWare package:
Traceback (most recent call last):
  File "/root/yugabyte-db/build-support/yb_release.py", line 263, in main
    subprocess.check_output(package_yw_cmd, cwd=managed_dir)
  File "/usr/lib64/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib64/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/root/yugabyte-db/managed/yb_release', '--destination', './build/target/ui', '--unarchived']' returned non-zero exit status 1.

```

**output**
```
ot/yugabyte-db/managed/project\x1b[0m\nInstalling the s3:// URLStreamHandler via java.net.URL.setURLStreamHandlerFactory\nCreating a new Ivy URLHandlerDispatcher to handle s3:// URLs\njava.lang.NullPointerException\n\tat sbt.StringUtilities$.nonEmpty(StringUtilities.scala:11)\n\tat sbt.impl.RepositoryName.at(DependencyBuilders.scala:66)\n\tat $5ac92381bcc66b3203fd$$anonfun$$sbtdef$1.apply(/root/yugabyte-db/managed/build.sbt:60)\n\tat $5ac92381bcc66b3203fd$$anonfun$$sbtdef$1.apply(/root/yugabyte-db/managed/build.sbt:51)\n\tat sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$constant$1.apply(INode.scala:163)\n\tat sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$constant$1.apply(INode.scala:163)\n\tat sbt.EvaluateSettings$MixedNode.evaluate0(INode.scala:175)\n\tat sbt.EvaluateSettings$INode.evaluate(INode.scala:135)\n\tat sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$submitEvaluate$1.apply$mcV$sp(INode.scala:69)\n\tat sbt.EvaluateSettings.sbt$EvaluateSettings$$run0(INode.scala:78)\n\tat sbt.EvaluateSettings$$anon$3.run(INode.scala:74)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat java.lang.Thread.run(Thread.java:748)\n\x1b[0m[\x1b[31merror\x1b[0m] \x1b[0mjava.lang.NullPointerException\x1b[0m\n\x1b[0m[\x1b[31merror\x1b[0m] \x1b[0mUse 'last' for the full log.\x1b[0m\nProject loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? "
```

**Comment by jiaolongxue** [comment]
sbt.ResolveException: unresolved dependency: org.yb#yb-client;0.8.1-SNAPSHOT: not found

**Comment by ddorian** [comment]
@jiaolongxue the "managed" version is [YugabyteDB Platform](https://www.yugabyte.com/platform/) which is commerical software. 

You have to contact on the link above to get a license/trial.

**Comment by rtsisyk** [comment]
I have the same problem:

```
[info]  [SUCCESSFUL ] org.scalaz#scalaz-effect_2.10;7.2.14!scalaz-effect_2.10.jar(bundle) (18ms)
[info] Done updating.
[info] Compiling 1 Scala source to /home/roman/yugabyte-db/managed/project/target/scala-2.10/sbt-0.13/classes...
[info] 'compiler-interface' not yet compiled for Scala 2.10.6. Compiling...
[info]   Compilation completed in 4.086 s
Installing the s3:// URLStreamHandler via java.net.URL.setURLStreamHandlerFactory
Creating a new Ivy URLHandlerDispatcher to handle s3:// URLs
java.lang.NullPointerException
        at sbt.StringUtilities$.nonEmpty(StringUtilities.scala:11)
        at sbt.impl.RepositoryName.at(DependencyBuilders.scala:66)
        at $256464e709ac64945084$$anonfun$$sbtdef$1.apply(/home/roman/yugabyte-db/managed/build.sbt:65)
        at $256464e709ac64945084$$anonfun$$sbtdef$1.apply(/home/roman/yugabyte-db/managed/build.sbt:56)
        at sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$constant$1.apply(INode.scala:163)
        at sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$constant$1.apply(INode.scala:163)
        at sbt.EvaluateSettings$MixedNode.evaluate0(INode.scala:175)
        at sbt.EvaluateSettings$INode.evaluate(INode.scala:135)
        at sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$submitEvaluate$1.apply$mcV$sp(INode.scala:69)
        at sbt.EvaluateSettings.sbt$EvaluateSettings$$run0(INode.scala:78)
        at sbt.EvaluateSettings$$anon$3.run(INode.scala:74)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[error] java.lang.NullPointerException
[error] Use 'last' for the full log.
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?
```

```
$cat /etc/centos-release
CentOS Linux release 7.9.2009 (Core)
```

```
sbtVersion
[info] welcome to sbt 1.4.6 (Red Hat, Inc. Java 1.8.0_275)
```

```
java -version
openjdk version "1.8.0_275"
OpenJDK Runtime Environment (build 1.8.0_275-b01)
OpenJDK 64-Bit Server VM (build 25.275-b01, mixed mode)
```

```
mvn -version
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /opt/maven
Java version: 1.8.0_275, vendor: Red Hat, Inc., runtime: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.275.b01-0.el7_9.x86_64/jre
Default locale: en_GB, platform encoding: UTF-8
OS name: "linux", version: "3.10.0-1160.el7.x86_64", arch: "amd64", family: "unix"
```

```
node --version
v15.6.0
```

```
npm --version
7.4.0
```

> @jiaolongxue the "managed" version is YugabyteDB Platform which is commerical software.
>
> You have to contact on the link above to get a license/trial.
>

Is it possible to build YugaWare without having a license? I just wanted to take a quick look. No plans for the production and/or commercial use.

**Comment by ddorian** [comment]
@rtsisyk 

> Is it possible to build YugaWare without having a license? I just wanted to take a quick look. No plans for the production and/or commercial use.

You can view a demo here: YugabyteDB Day 2 Operations Best Practices - Distributed SQL Summit Asia 2021 https://vimeo.com/showcase/8034885/video/502817020

**Comment by rtsisyk** [comment]
OK, thanks for the information!
