### ISSUE TITLE
[YSQL] [Index Backfill] Handle Snapshot too old errors during ysql index backfill.

### ISSUE THREAD

**Issue by amitanandaiyer** [yugabyte/yugabyte-db#6333]
YSQL index backfill can run into `Snapshot too old` error if the backfill process takes longer than the time set for `timestamp_history_retention_interval_sec` and there are compactions happening concurrently.

To avoid this, we can either increase the flag -- which has other consequences. Or we can add an option to ignore such errors for backfill reads. Unlike timestamp reads, for backfill purposes, it is perfectly okay if the older records that are overwritten by newer records are garbage collected. 

We should be able to add and pass an option to historic reads, that are used in backfill process, to ignore snapshot being too old.

**Comment by kmuthukk** [comment]
Just adding additional notes on what we saw (when testing with 2.5.0.0-b2):

On a table with 10M rows, with the default settings of `timestamp_history_retention_interval_sec` we got:
```
yugabyte=# CREATE INDEX IF NOT EXISTS name_idx ON users(ename, age ASC);
ERROR:  index backfill failed
```

and the yb-master leader logs showed that the backfill process failed with errors like:

```
W1110 19:16:42.705049  7429 outbound_call.cc:396] RPC callback for RPC call yb.tserver.TabletServerAdminService.BackfillIndex -> { remote: 172.151.62.126:9100 idx: 6 protocol: 0x00007f4260775f20 -> tcp } , state=FINISHED_SUCCESS. took 0.097s
W1110 19:16:42.705108  9020 backfill_index.cc:1159] TS e02d963f3cb34683892e797790d2aa36: backfill failed for tablet d816f808217344ca8f1fbfdcf1bf97f9 (table users [id=000030af000030008000000000004100]) no further retry: Illegal state (yb/tablet/tablet.cc:2200): BACKFILL request failed: PQ status 7 with message "ERROR:  Snapshot too old: Snapshot too old. Read point: { physical: 1605035663989242 logical: 3 }, earliest read time allowed: { physical: 1605035681724274 logical: 2 }, delta (usec): 17735032: kSnapshotTooOld
" when running "BACKFILL INDEX 17153 READ TIME 6574226079699935235 PARTITION x'bff4';"
```

After increasing the yb-tserver gflag `timestamp_history_retention_interval_sec` to 3600, a subsequent attempt to create the index went through cleanly. But this is just a near-term workaround, and we should do the fix suggested by @amitanandaiyer to avoid having to increase the default retention setting.

**Comment by jaki** [comment]
@amitanandaiyer, can you also show how this only affects YSQL, not YCQL?  I know YCQL is fine because backfill worked before commit 533d36f04eb9248b0c9a8dad09af4ac12bcd2cd6, where the read was taken at time 50.  However, the snapshot too old code path seems to be shared by YCQL and YSQL.

**Comment by amitanandaiyer** [comment]
CQL doesn’t do a “read” from the TServer like SQL. 

SQL uses the TServer::Read. CQL bypasses this layer that register the reader timestamp etc, and directly creates the needed iterator and goes through the rows

you may want to just avoid registering the Timestamp in
```
Result<ReadHybridTime> TabletServiceImpl::DoReadImpl(ReadContext* read_context) {
  auto read_tx = VERIFY_RESULT(
      tablet::ScopedReadOperation::Create(
          read_context->tablet.get(), read_context->require_lease, read_context->read_time));
  read_context->used_read_time = read_tx.read_time();
```
by signalling to the TServer that the read is coming for a backfill purpose

**Comment by jaki** [comment]
I was previously looking at the backfill write, not read.  My bad.

I got a stack trace:

```
Breakpoint 1, yb::tablet::TabletRetentionPolicy::RegisterReaderTimestamp (this=0x35fe850, timestamp=...) at ../../src/yb/tablet/tablet_retention_policy.cc:90
90     return STATUS(
#0  yb::tablet::TabletRetentionPolicy::RegisterReaderTimestamp (this=0x35fe850, timestamp=...) at ../../src/yb/tablet/tablet_retention_policy.cc:90
#1  0x00007f5b50f9da91 in yb::tablet::ScopedReadOperation::Create (tablet=0x2d01610, require_lease=..., read_time=...) at ../../src/yb/tablet/tablet.cc:3363
#2  0x00007f5b518c7b6e in yb::tserver::TabletServiceImpl::DoReadImpl (this=this@entry=0x2ca8aa0, read_context=read_context@entry=0x7f5b399b7f80) at ../../src/yb/tserver/tablet_service.cc:2084
#3  0x00007f5b518c92a3 in yb::tserver::TabletServiceImpl::DoRead (this=this@entry=0x2ca8aa0, read_context=read_context@entry=0x7f5b399b7f80) at ../../src/yb/tserver/tablet_service.cc:2069
#4  0x00007f5b518c983d in yb::tserver::TabletServiceImpl::CompleteRead (this=this@entry=0x2ca8aa0, read_context=read_context@entry=0x7f5b399b7f80) at ../../src/yb/tserver/tablet_service.cc:1973
#5  0x00007f5b518cbd91 in yb::tserver::TabletServiceImpl::Read (this=this@entry=0x2ca8aa0, req=req@entry=0xf6da6f0, resp=resp@entry=0x32f3e10, context=...) at ../../src/yb/tserver/tablet_service.cc:1964
#6  0x00007f5b4e48bea2 in yb::tserver::TabletServerServiceIf::Handle (this=0x2ca8aa0, call=...) at src/yb/tserver/tserver_service.service.cc:166
#7  0x00007f5b49eb8df3 in yb::rpc::ServicePoolImpl::Handle (this=0x2fa6b40, incoming=std::shared_ptr (empty) 0x0) at ../../src/yb/rpc/service_pool.cc:262
#8  0x00007f5b49e567e5 in yb::rpc::InboundCall::InboundCallTask::Run (this=<optimized out>) at ../../src/yb/rpc/inbound_call.cc:212
#9  0x00007f5b49ecbfcd in yb::rpc::(anonymous namespace)::Worker::Execute (this=0x319f4000) at ../../src/yb/rpc/thread_pool.cc:105
#10 0x00007f5b49ec76db in operator()<, void> (__object=<optimized out>, this=<optimized out>) at /opt/yb-build/brew/linuxbrew-20181203T161736v9-3ba4c2ed9b0587040949a4a9a95b576f520bae/Cellar/gcc/5.5.0_4/include/c++/5.5.0/functional:600
#11 __call<void, 0ul> (__args=<optimized out>, this=<optimized out>) at /opt/yb-build/brew/linuxbrew-20181203T161736v9-3ba4c2ed9b0587040949a4a9a95b576f520bae/Cellar/gcc/5.5.0_4/include/c++/5.5.0/functional:1074
#12 operator()<, void> (this=<optimized out>) at /opt/yb-build/brew/linuxbrew-20181203T161736v9-3ba4c2ed9b0587040949a4a9a95b576f520bae/Cellar/gcc/5.5.0_4/include/c++/5.5.0/functional:1133
#13 std::_Function_handler<void(), std::_Bind<std::_Mem_fn<void (yb::rpc::(anonymous namespace)::Worker::*)()>(yb::rpc::(anonymous namespace)::Worker*)> >::_M_invoke(const std::_Any_data &) (__functor=...) at /opt/yb-build/brew/linuxbrew-20181203T161736v9-3ba4c2ed9b0587040949a4a9a95b576f520bae/Cellar/gcc/5.5.0_4/include/c++/5.5.0/functional:1871
#14 0x00007f5b487c1f50 in operator() (this=0x35f6838) at /opt/yb-build/brew/linuxbrew-20181203T161736v9-3ba4c2ed9b0587040949a4a9a95b576f520bae/Cellar/gcc/5.5.0_4/include/c++/5.5.0/functional:2267
#15 yb::Thread::SuperviseThread (arg=0x35f67e0) at ../../src/yb/util/thread.cc:771
#16 0x00007f5b43186694 in start_thread (arg=0x7f5b399c1700) at pthread_create.c:333
#17 0x00007f5b42ec841d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

It's easy to get the error using

```sh
./bin/yb-ctl start --tserver_flags "timestamp_history_retention_interval_sec=5,TEST_slowdown_backfill_by_ms=10000"
```

and flushing + compacting the indexed table 5-10 seconds after the backfill read time is chosen (indicated by `Completed fetching SafeTime` in master logs).
