### ISSUE TITLE
[Platform] PersistenceException in tests

### ISSUE THREAD

**Issue by sb-yb** [yugabyte/yugabyte-db#6415]
Example test run:
https://jenkins.dev.yugabyte.com/job/yugaware-centos-phabricator/3146/consoleFull

You will see many error logs like:
```
2020-11-17 22:40:08.546 ERROR Scheduler.java:193 [application-akka.actor.default-dispatcher-3] Error Running scheduler threadjavax.persistence.PersistenceException: java.sql.SQLException: HikariDataSource HikariDataSource (HikariPool-17) has been closed.
2020-11-17 22:40:08.546 ERROR QueryAlerts.java:121 [application-akka.actor.default-dispatcher-3] Error querying for alerts
javax.persistence.PersistenceException: java.sql.SQLException: HikariDataSource HikariDataSource (HikariPool-17) has been closed.
	at io.ebeaninternal.server.transaction.TransactionFactoryBasic.createQueryTransaction(TransactionFactoryBasic.java:35)
	at io.ebeaninternal.server.transaction.TransactionManager.createQueryTransaction(TransactionManager.java:360)
	at io.ebeaninternal.server.core.DefaultServer.createQueryTransaction(DefaultServer.java:2306)
	at io.ebeaninternal.server.core.OrmQueryRequest.initTransIfRequired(OrmQueryRequest.java:275)
	at io.ebeaninternal.server.core.DefaultServer.findList(DefaultServer.java:1595)
	at io.ebeaninternal.server.core.DefaultServer.findList(DefaultServer.java:1574)
	at io.ebeaninternal.server.querydefn.DefaultOrmQuery.findList(DefaultOrmQuery.java:1474)
	at com.yugabyte.yw.models.Customer.getAll(Customer.java:138)
	at com.yugabyte.yw.commissioner.QueryAlerts.scheduleRunner(QueryAlerts.java:107)
	at akka.actor.LightArrayRevolverScheduler$$anon$2$$anon$1.run(LightArrayRevolverScheduler.scala:104)
	at akka.actor.LightArrayRevolverScheduler$TaskHolder.run(LightArrayRevolverScheduler.scala:343)
	at akka.actor.LightArrayRevolverScheduler$$anonfun$close$1.apply(LightArrayRevolverScheduler.scala:145)
	at akka.actor.LightArrayRevolverScheduler$$anonfun$close$1.apply(LightArrayRevolverScheduler.scala:144)
	at scala.collection.Iterator$class.foreach(Iterator.scala:742)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1194)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
```

**Comment by sb-yb** [comment]
This is happening due to initialization of QueryAlert during construction.
