### ISSUE TITLE
[YSQL] SIGABRT/SIGSEGV in postgres process

### ISSUE THREAD

**Issue by d-uspenskiy** [yugabyte/yugabyte-db#6436]
Postgres process `debug` build is crashed with assertion and `release` with segmentation fault in case of running the following unit test

```
package org.yb.pgsql;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.yb.util.YBTestRunnerNonTsanOnly;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.util.Map;
import java.util.concurrent.CyclicBarrier;
import java.util.concurrent.atomic.AtomicBoolean;

import static org.yb.AssertionWrappers.assertFalse;

@RunWith(value=YBTestRunnerNonTsanOnly.class)
public class TestSegFault extends BasePgSQLTest {

  @Override
  protected Map<String, String> getTServerFlags() {
    Map<String, String> flagMap = super.getTServerFlags();
    flagMap.put("ysql_log_statement", "all");
    return flagMap;
  }

  @Override
  protected int getReplicationFactor() {
    return 1;
  }

  protected int getInitialNumMasters() {
    return 1;
  }

  protected int getInitialNumTServers() {
    return 1;
  }

  @Test
  public void testSimple() throws Exception {
    try (Statement s = connection.createStatement()) {
      s.execute("CREATE TABLE t(k INT PRIMARY KEY, v1 SERIAL, v2 SERIAL)");
      s.execute("INSERT INTO t VALUES(1), (2), (3)");
      int count = 50;
      final AtomicBoolean errorsDetected = new AtomicBoolean(false);
      final AtomicBoolean stopped = new AtomicBoolean(false);
      final CyclicBarrier barrier = new CyclicBarrier(count);
      final Thread[] threads = new Thread[count];
      final Connection[] connections = new Connection[count];
      for (int i = 0; i < count; ++i) {
        ConnectionBuilder b = getConnectionBuilder();
        b.withTServer(count % miniCluster.getNumTServers());
        connections[i] = b.connect();
      }
      threads[0] = new Thread(() -> {
        try (Statement s0 = connections[0].createStatement()) {
          long idx = 0;
          while(!stopped.get() && !errorsDetected.get()) {
            barrier.await();
            try {
              s0.execute("ALTER TABLE t ADD COLUMN v INT DEFAULT 100");
              s0.execute("ALTER TABLE t DROP COLUMN v");
            } catch (Exception e) {
              errorsDetected.set(true);
              throw e;
            }
          }
        } catch (Exception e) {
        } finally {
          barrier.reset();
        }
      });
      for (int i = 1; i < count; ++i) {
        int idx = i;
        threads[i] = new Thread(() -> {
          try {
            try (PreparedStatement ps = connections[idx].prepareStatement("SELECT COUNT(*) FROM t WHERE k > ?");
                  Statement ss = connections[idx].createStatement()){
              int li = 0;
              while(!stopped.get() && !errorsDetected.get()) {
                barrier.await();
                try {
                  for (int j = 0; !stopped.get() && j < 5; ++j) {
                    ss.execute(String.format("INSERT INTO t(k) VALUES(%d)", idx * 1000000 + (++li)));
                    ps.setInt(1, -1);
                    ps.executeQuery();
                  }
                } catch (Exception e) {
                  String m = e.getMessage();
                  if (!(m.contains("Catalog Version Mismatch") || m.contains("Restart read required") || m.contains("schema version mismatch"))) {
                    errorsDetected.set(true);
                    throw  e;
                  }
                }
              }
            }
          } catch (Exception e) {
          } finally {
            barrier.reset();
          }
        });
      }
      for (Thread t : threads) {
        t.start();
      }
      Thread.sleep(10000);
      stopped.set(true);
      for (Thread t : threads) {
        t.join();
      }
      assertFalse(errorsDetected.get());
    }
  }
}
``` 

Error's stack is:

```
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
[Current thread is 1 (Thread 0x7fbcf38d52c0 (LWP 6240))]
(gdb) where
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007fbcf0b73801 in __GI_abort () at abort.c:79
#2  0x000055e421853310 in ExceptionalCondition (conditionName=conditionName@entry=0x55e4218b83bc "!(attnum <= tupleDesc->natts)", errorType=errorType@entry=0x55e4218b2f36 "FailedAssertion", 
    fileName=fileName@entry=0x55e4218b7fb8 "../../../../../../../src/postgres/src/backend/access/common/heaptuple.c", lineNumber=lineNumber@entry=90)
    at ../../../../../../../src/postgres/src/backend/utils/error/assert.c:54
#3  0x000055e42130c17f in getmissingattr (tupleDesc=tupleDesc@entry=0x55e42376de30, attnum=attnum@entry=4, isnull=isnull@entry=0x7ffd97599f3f)
    at ../../../../../../../src/postgres/src/backend/access/common/heaptuple.c:90
#4  0x000055e4215963d7 in YBCExecuteInsertInternal (rel=0x7fbcf3823c80, tupleDesc=0x55e42376de30, tuple=tuple@entry=0x55e42376f4d8, is_single_row_txn=is_single_row_txn@entry=false)
    at ../../../../../../src/postgres/src/backend/executor/ybcModifyTable.c:260
#5  0x000055e421596714 in YBCExecuteInsert (rel=<optimized out>, tupleDesc=<optimized out>, tuple=tuple@entry=0x55e42376f4d8) at ../../../../../../src/postgres/src/backend/executor/ybcModifyTable.c:368
#6  0x000055e42159674d in YBCHeapInsert (slot=slot@entry=0x55e42376dc80, tuple=tuple@entry=0x55e42376f4d8, estate=estate@entry=0x55e42376d6c0)
    at ../../../../../../src/postgres/src/backend/executor/ybcModifyTable.c:407
#7  0x000055e42157dde4 in ExecInsert (mtstate=mtstate@entry=0x55e42376da28, slot=0x55e42376dc80, planSlot=planSlot@entry=0x55e42376dc80, estate=estate@entry=0x55e42376d6c0, canSetTag=<optimized out>)
    at ../../../../../../src/postgres/src/backend/executor/nodeModifyTable.c:582
#8  0x000055e42157f4c2 in ExecModifyTable (pstate=0x55e42376da28) at ../../../../../../src/postgres/src/backend/executor/nodeModifyTable.c:2434
#9  0x000055e421558cfb in ExecProcNodeFirst (node=0x55e42376da28) at ../../../../../../src/postgres/src/backend/executor/execProcnode.c:446
#10 0x000055e42154fd05 in ExecProcNode (node=0x55e42376da28) at ../../../../../../src/postgres/src/include/executor/executor.h:249
#11 ExecutePlan (execute_once=<optimized out>, dest=0x55e421d70500 <donothingDR>, direction=21988, numberTuples=0, sendTuples=false, operation=CMD_INSERT, use_parallel_mode=<optimized out>, 
    planstate=0x55e42376da28, estate=0x55e42376d6c0) at ../../../../../../src/postgres/src/backend/executor/execMain.c:1730
#12 standard_ExecutorRun (queryDesc=queryDesc@entry=0x55e4235e0028, direction=direction@entry=ForwardScanDirection, count=count@entry=0, execute_once=execute_once@entry=true)
    at ../../../../../../src/postgres/src/backend/executor/execMain.c:367
#13 0x00007fbce4401e7c in pgss_ExecutorRun (queryDesc=0x55e4235e0028, direction=ForwardScanDirection, count=0, execute_once=<optimized out>)
    at ../../../../../src/postgres/contrib/pg_stat_statements/pg_stat_statements.c:947
#14 0x00007fbce41fa6ff in ybpgm_ExecutorRun (queryDesc=0x55e4235e0028, direction=ForwardScanDirection, count=0, execute_once=<optimized out>)
    at ../../../../../src/postgres/contrib/yb_pg_metrics/yb_pg_metrics.c:415
#15 0x000055e42154fd9e in ExecutorRun (queryDesc=queryDesc@entry=0x55e4235e0028, direction=direction@entry=ForwardScanDirection, count=count@entry=0, execute_once=execute_once@entry=true)
    at ../../../../../../src/postgres/src/backend/executor/execMain.c:308
#16 0x000055e4217062d5 in ProcessQuery (plan=plan@entry=0x55e4237a7cc8, sourceText=0x55e4235dffd0 "INSERT INTO t(k) VALUES(2000001)", params=0x0, queryEnv=0x0, dest=dest@entry=0x55e421d70500 <donothingDR>, 
    completionTag=completionTag@entry=0x7ffd9759a7a0 "", isSingleRowModifyTxn=false) at ../../../../../../src/postgres/src/backend/tcop/pquery.c:172
#17 0x000055e4217065a5 in PortalRunMulti (portal=portal@entry=0x55e4236549c0, isTopLevel=isTopLevel@entry=true, setHoldSnapshot=setHoldSnapshot@entry=false, dest=0x55e421d70500 <donothingDR>, 
    dest@entry=0x55e4235da5e0, altdest=0x55e421d70500 <donothingDR>, altdest@entry=0x55e4235da5e0, completionTag=completionTag@entry=0x7ffd9759a7a0 "")
    at ../../../../../../src/postgres/src/backend/tcop/pquery.c:1307
#18 0x000055e421707744 in PortalRun (portal=portal@entry=0x55e4236549c0, count=count@entry=9223372036854775807, isTopLevel=isTopLevel@entry=true, run_once=run_once@entry=true, dest=dest@entry=0x55e4235da5e0, 
    altdest=altdest@entry=0x55e4235da5e0, completionTag=0x7ffd9759a7a0 "") at ../../../../../../src/postgres/src/backend/tcop/pquery.c:810
#19 0x000055e421701a89 in exec_execute_message (max_rows=9223372036854775807, portal_name=0x55e4235da190 "") at ../../../../../../src/postgres/src/backend/tcop/postgres.c:2063
#20 yb_exec_execute_message (portal_name=portal_name@entry=0x55e4235da190 "", max_rows=max_rows@entry=0, restart_data=restart_data@entry=0x55e4235da5a8, exec_context=exec_context@entry=0x55e4235da070)
    at ../../../../../../src/postgres/src/backend/tcop/postgres.c:4341
#21 0x000055e421704bfd in PostgresMain (argc=<optimized out>, argv=argv@entry=0x55e4235d7678, dbname=<optimized out>, username=0x55e4235d7378 "yugabyte_test")
    at ../../../../../../src/postgres/src/backend/tcop/postgres.c:5060
#22 0x000055e421668e6f in BackendRun (port=0x55e4235d4930) at ../../../../../../src/postgres/src/backend/postmaster/postmaster.c:4428
#23 BackendStartup (port=0x55e4235d4930) at ../../../../../../src/postgres/src/backend/postmaster/postmaster.c:4094
#24 ServerLoop () at ../../../../../../src/postgres/src/backend/postmaster/postmaster.c:1737
#25 PostmasterMain (argc=argc@entry=19, argv=argv@entry=0x55e422b0ea50) at ../../../../../../src/postgres/src/backend/postmaster/postmaster.c:1400
#26 0x000055e4215b8656 in PostgresServerProcessMain (argc=19, argv=0x55e422b0ea50) at ../../../../../../src/postgres/src/backend/main/main.c:234
#27 0x000055e4215b8676 in main ()
```

Another one
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  pg_strtok (length=length@entry=0x7ffe4c7f436c) at ../../../../../../src/postgres/src/backend/nodes/read.c:138
138		while (*local_str == ' ' || *local_str == '\n' || *local_str == '\t')
[Current thread is 1 (Thread 0x7f0baba952c0 (LWP 11511))]
(gdb) where
#0  pg_strtok (length=length@entry=0x7ffe4c7f436c) at ../../../../../../src/postgres/src/backend/nodes/read.c:138
#1  0x0000559d248aa3aa in nodeRead (token=token@entry=0x0, tok_len=<optimized out>, tok_len@entry=0) at ../../../../../../src/postgres/src/backend/nodes/read.c:302
#2  0x0000559d248aa995 in stringToNode (str=0x0) at ../../../../../../src/postgres/src/backend/nodes/read.c:77
#3  0x0000559d2496da40 in build_column_default (rel=rel@entry=0x7f0bab9f2bf0, attrno=5) at ../../../../../../src/postgres/src/backend/rewrite/rewriteHandler.c:1147
#4  0x0000559d2496e70f in rewriteTargetListIU (targetList=<optimized out>, commandType=CMD_INSERT, override=OVERRIDING_NOT_SET, target_relation=target_relation@entry=0x7f0bab9f2bf0, result_rti=1, 
    attrno_list=attrno_list@entry=0x0) at ../../../../../../src/postgres/src/backend/rewrite/rewriteHandler.c:852
#5  0x0000559d2496f21f in RewriteQuery (parsetree=parsetree@entry=0x559d26b9bfe0, rewrite_events=rewrite_events@entry=0x0) at ../../../../../../src/postgres/src/backend/rewrite/rewriteHandler.c:3473
#6  0x0000559d249718b5 in QueryRewrite (parsetree=parsetree@entry=0x559d26b9bfe0) at ../../../../../../src/postgres/src/backend/rewrite/rewriteHandler.c:3746
#7  0x0000559d249bc23e in pg_rewrite_query (query=query@entry=0x559d26b9bfe0) at ../../../../../../src/postgres/src/backend/tcop/postgres.c:798
#8  0x0000559d249bd4d1 in exec_parse_message (query_string=query_string@entry=0x559d26a44191 "INSERT INTO t(k) VALUES(7000002)", stmt_name=stmt_name@entry=0x559d26a44190 "", paramTypes=<optimized out>, 
    paramTypes@entry=0x0, numParams=<optimized out>, numParams@entry=0, output_dest=DestRemote) at ../../../../../../src/postgres/src/backend/tcop/postgres.c:1423
#9  0x0000559d249bff92 in PostgresMain (argc=<optimized out>, argv=argv@entry=0x559d26a41678, dbname=<optimized out>, username=0x559d26a41378 "yugabyte_test")
    at ../../../../../../src/postgres/src/backend/tcop/postgres.c:4997
#10 0x0000559d24924e6f in BackendRun (port=0x559d26a3ef20) at ../../../../../../src/postgres/src/backend/postmaster/postmaster.c:4428
#11 BackendStartup (port=0x559d26a3ef20) at ../../../../../../src/postgres/src/backend/postmaster/postmaster.c:4094
#12 ServerLoop () at ../../../../../../src/postgres/src/backend/postmaster/postmaster.c:1737
#13 PostmasterMain (argc=argc@entry=19, argv=argv@entry=0x559d25f78a50) at ../../../../../../src/postgres/src/backend/postmaster/postmaster.c:1400
#14 0x0000559d24874656 in PostgresServerProcessMain (argc=19, argv=0x559d25f78a50) at ../../../../../../src/postgres/src/backend/main/main.c:234
#15 0x0000559d24874676 in main ()
```

Possible root cause is the changing of relation description while processing single statement.

**Comment by tedyu** [comment]
It seems the test may receive the following exception:
```
ts1|pid26399|:19245|http://127.89.135.54:21723 2020-11-21 00:47:47.642 UTC [27096] DETAIL:  parameters: $1 = '-1'
2020-11-21 00:47:47,638 (Thread-41) [ERROR - org.yb.pgsql.TestSegFault.lambda$testSimple$1(TestSegFault.java:105)] 
org.postgresql.util.PSQLException: ERROR: Operation failed. Try again.: Resource unavailable : RocksDB
    at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
    at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
    at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
    at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
    at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
    at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:307)
```

**Comment by tedyu** [comment]
Sometimes I would see:
```
m1|pid27005|:31613|http://127.38.79.54:21980 Fatal failure details written to /nfusr/dev-server/tedyu/yugabyte-db/java/yb-pgsql/target/surefire-reports_org.yb.pgsql.TestSegFault/org.yb.pgsql.TestSegFault.testSimple.fatal_failure_details.m-1.127.38.79.54-port31613.2020-11-21T01_23_26.pid27005.txt
m1|pid27005|:31613|http://127.38.79.54:21980 F20201121 01:23:26 ../../src/yb/tserver/tablet_service.cc:1937] CompleteRead, restarting read with the same read time: { read: { physical: 1605921806795247 } local_limit: { physical: 1605921806794179 } global_limit: { physical: 1605921806994181 } in_txn_limit: <invalid> serial_no: 55047 }
m1|pid27005|:31613|http://127.38.79.54:21980     @     0x7fc78446ebe3  yb::LogFatalHandlerSink::send(int, char const*, char const*, int, tm const*, char const*, unsigned long) (src/yb/util/logging.cc:474)
m1|pid27005|:31613|http://127.38.79.54:21980     @     0x7fc783643865
m1|pid27005|:31613|http://127.38.79.54:21980     @     0x7fc783640e39
m1|pid27005|:31613|http://127.38.79.54:21980     @     0x7fc783641062
m1|pid27005|:31613|http://127.38.79.54:21980     @     0x7fc78e217097  yb::tserver::TabletServiceImpl::CompleteRead(yb::tserver::ReadContext*) (src/yb/tserver/tablet_service.cc:1937)
m1|pid27005|:31613|http://127.38.79.54:21980     @     0x7fc78e219146  yb::tserver::TabletServiceImpl::Read(yb::tserver::ReadRequestPB const*, yb::tserver::ReadResponsePB*, yb::rpc::RpcContext) (src/yb/tserver/tablet_service.cc:1918)
m1|pid27005|:31613|http://127.38.79.54:21980     @     0x7fc788e34e61  yb::tserver::TabletServerServiceIf::Handle(shared_ptr<yb::rpc::InboundCall>) (src/yb/tserver/tserver_service.service.cc:166)
m1|pid27005|:31613|http://127.38.79.54:21980     @     0x7fc785c4ff50  yb::rpc::ServicePoolImpl::Handle(shared_ptr<yb::rpc::InboundCall>) (src/yb/rpc/service_pool.cc:262)
m1|pid27005|:31613|http://127.38.79.54:21980     @     0x7fc785bed8c4  yb::rpc::InboundCall::InboundCallTask::Run() (src/yb/rpc/inbound_call.cc:212)
m1|pid27005|:31613|http://127.38.79.54:21980     @     0x7fc785c6312a  Execute (src/yb/rpc/thread_pool.cc:105)
m1|pid27005|:31613|http://127.38.79.54:21980     @     0x7fc785c5e838  operator()<, void> (gcc/5.5.0_4/include/c++/5.5.0/functional:600)
```
