### ISSUE TITLE
NPE while creating a universe on GCP

### ISSUE THREAD

**Issue by chirag-yb** [yugabyte/yugabyte-db#6472]
Use Case

Cloud provider - GCP
VPC - YW managed 
ssh key - YW managed
Universe config - 3 nodes in N. Virginia 

First universe creation failed with an NPE

`2020-11-24 18:22:48,145 [INFO] from com.yugabyte.yw.common.PlacementInfoUtil in application-akka.actor.default-dispatcher-106 - Set of nodes after node configure: [name: null, cloudInfo: us-east4-c.us-east4.gcp, type: n1-standard-8, ip: null, isMaster: false, isTserver: true, state: ToBeAdded, azUuid: a03b5508-d9f6-45b2-b3e6-ac1dd562265f, placementUuid: 4eed4f95-314e-49ac-ac6b-f634a292866f, name: null, cloudInfo: us-east4-b.us-east4.gcp, type: n1-standard-8, ip: null, isMaster: false, isTserver: true, state: ToBeAdded, azUuid: c9612ae4-7e2f-47e0-adec-d8b0fbe05b23, placementUuid: 4eed4f95-314e-49ac-ac6b-f634a292866f, name: null, cloudInfo: us-east4-a.us-east4.gcp, type: n1-standard-8, ip: null, isMaster: false, isTserver: true, state: ToBeAdded, azUuid: 65190416-9f49-4523-9f4a-0951b271b39a, placementUuid: 4eed4f95-314e-49ac-ac6b-f634a292866f].
2020-11-24 18:22:48,145 [INFO] from com.yugabyte.yw.common.PlacementInfoUtil in application-akka.actor.default-dispatcher-106 - Setting per AZ replication factor.
2020-11-24 18:22:48,146 [INFO] from com.yugabyte.yw.common.PlacementInfoUtil in application-akka.actor.default-dispatcher-106 - Final Placement info: Cloud=gcp Region=us-east4 : (AZ=us-east4-c, count=1, replication factor=1)(AZ=us-east4-b, count=1, replication factor=1)(AZ=us-east4-a, count=1, replication factor=1).
2020-11-24 18:22:48,146 [INFO] from com.yugabyte.yw.common.PlacementInfoUtil in application-akka.actor.default-dispatcher-106 - Az placement map {a03b5508-d9f6-45b2-b3e6-ac1dd562265f=1, 65190416-9f49-4523-9f4a-0951b271b39a=1, c9612ae4-7e2f-47e0-adec-d8b0fbe05b23=1}
2020-11-24 18:22:48,147 [INFO] from com.yugabyte.yw.common.PlacementInfoUtil in application-akka.actor.default-dispatcher-106 - Az Map {a03b5508-d9f6-45b2-b3e6-ac1dd562265f=1, c9612ae4-7e2f-47e0-adec-d8b0fbe05b23=1, 65190416-9f49-4523-9f4a-0951b271b39a=1}
2020-11-24 18:22:48,297 [INFO] from com.yugabyte.yw.controllers.UniverseController in application-akka.actor.default-dispatcher-124 - Finding Universe with name test.
2020-11-24 18:23:07,552 [INFO] from com.yugabyte.yw.controllers.UniverseController in application-akka.actor.default-dispatcher-123 - Finding Universe with name test.
2020-11-24 18:23:07,689 [INFO] from com.yugabyte.yw.controllers.UniverseController in application-akka.actor.default-dispatcher-125 - Finding Universe with name test.
2020-11-24 18:23:07,830 [INFO] from com.yugabyte.yw.controllers.UniverseController in application-akka.actor.default-dispatcher-122 - Create for 08695973-187c-4151-91fb-9566453e38b7.
2020-11-24 18:23:07,860 [ERROR] from com.yugabyte.yw.controllers.UniverseController in application-akka.actor.default-dispatcher-122 - Error creating universe
java.lang.NullPointerException: null
	at com.yugabyte.yw.controllers.UniverseController.create(UniverseController.java:469)
	at v1.Routes$$anonfun$routes$1$$anonfun$applyOrElse$72$$anonfun$apply$72.apply(Routes.scala:3275)
	at v1.Routes$$anonfun$routes$1$$anonfun$applyOrElse$72$$anonfun$apply$72.apply(Routes.scala:3275)
	at play.core.routing.HandlerInvokerFactory$$anon$3.resultCall(HandlerInvoker.scala:143)
	at play.core.routing.HandlerInvokerFactory$$anon$3.resultCall(HandlerInvoker.scala:142)
	at play.core.routing.HandlerInvokerFactory$JavaActionInvokerFactory$$anon$8$$anon$2$$anon$1.invocation(HandlerInvoker.scala:116)
	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:112)
	at play.http.DefaultActionCreator$1.call(DefaultActionCreator.java:33)
	at com.yugabyte.yw.controllers.TokenAuthenticator.call(TokenAuthenticator.java:113)
	at play.core.j.JavaAction$$anonfun$9.apply(JavaAction.scala:171`

**Comment by SergeyPotachev** [comment]
Met the same issue while creating universes in Azure (platform version 2.5.2.0) for 2 or 3 times. Nothing special was done, all scenarios were the same, looks like a spontaneous error.
