### ISSUE TITLE
[YCQL] BfqlTest.TestBuiltinToJson ASAN failure

### ISSUE THREAD

**Issue by jaki** [yugabyte/yugabyte-db#6474]
Jira Link: [DB-4662](https://yugabyte.atlassian.net/browse/DB-4662)
Found this in `BfqlTest.TestBuiltinToJson` test.  The log is very short, and the error seems to come from `DateTime::DateFromString` calling `CreateCalendar`.

```
uloc.cpp:1206:5: runtime error: null pointer passed as argument 1, which is declared to never be null
/usr/include/string.h:43:28: note: nonnull attribute specified here
    #0 0x7f140fec1cfa in ulocimp_getLanguage_67 (/opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20201111062958-7047513803-centos7-linuxbrew/installed/asan/lib/libicuuc.so.67+0x794cfa)
    #1 0x7f140fec5b16 in uloc_getScript_67 (/opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20201111062958-7047513803-centos7-linuxbrew/installed/asan/lib/libicuuc.so.67+0x798b16)
    #2 0x7f140ff0d6a6 in createTagStringWithAlternates(char const*, int, char const*, int, char const*, int, char const*, int, char const*, icu_67::ByteSink&, UErrorCode*) (/opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20201111062958-7047513803-centos7-linuxbrew/installed/asan/lib/libicuuc.so.67+0x7e06a6)
    #3 0x7f140ff0bf1f in createLikelySubtagsString(char const*, int, char const*, int, char const*, int, char const*, int, icu_67::ByteSink&, UErrorCode*) (/opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20201111062958-7047513803-centos7-linuxbrew/installed/asan/lib/libicuuc.so.67+0x7def1f)
    #4 0x7f140ff0724c in _uloc_addLikelySubtags(char const*, icu_67::ByteSink&, UErrorCode*) (/opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20201111062958-7047513803-centos7-linuxbrew/installed/asan/lib/libicuuc.so.67+0x7da24c)
    #5 0x7f140ff08696 in _uloc_minimizeSubtags(char const*, icu_67::ByteSink&, UErrorCode*) (/opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20201111062958-7047513803-centos7-linuxbrew/installed/asan/lib/libicuuc.so.67+0x7db696)
    #6 0x7f140ff07bc8 in ulocimp_minimizeSubtags_67 (/opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20201111062958-7047513803-centos7-linuxbrew/installed/asan/lib/libicuuc.so.67+0x7dabc8)
    #7 0x7f140fedbccc in icu_67::Locale::minimizeSubtags(UErrorCode&) (/opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20201111062958-7047513803-centos7-linuxbrew/installed/asan/lib/libicuuc.so.67+0x7aeccc)
    #8 0x7f14115379c9 in icu_67::Calendar::setWeekData(icu_67::Locale const&, char const*, UErrorCode&) (/opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20201111062958-7047513803-centos7-linuxbrew/installed/asan/lib/libicui18n.so.67+0xba09c9)
    #9 0x7f141153a6ad in icu_67::Calendar::Calendar(icu_67::TimeZone const&, icu_67::Locale const&, UErrorCode&) (/opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20201111062958-7047513803-centos7-linuxbrew/installed/asan/lib/libicui18n.so.67+0xba36ad)
    #10 0x7f1411566426 in icu_67::GregorianCalendar::GregorianCalendar(icu_67::TimeZone const&, UErrorCode&) (/opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20201111062958-7047513803-centos7-linuxbrew/installed/asan/lib/libicui18n.so.67+0xbcf426)
    #11 0x7f14136678b2 in yb::(anonymous namespace)::CreateCalendar() /path/to/build/asan-clang-dynamic-ninja/../../src/yb/util/date_time.cc:82:21
    #12 0x7f1413666e84 in yb::DateTime::DateFromString(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) /path/to/build/asan-clang-dynamic-ninja/../../src/yb/util/date_time.cc:233:27
    #13 0x55d335 in yb::bfql::BfqlTest_TestBuiltinToJson_Test::TestBody() /path/to/build/asan-clang-dynamic-ninja/../../src/yb/util/bfql/bfql-test.cc:584:27
    #14 0x7f1416333421 in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20201111062958-7047513803-centos7-linuxbrew/src/gmock-1.8.0/googletest/src/gtest.cc:2402:10
    #15 0x7f1416333421 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20201111062958-7047513803-centos7-linuxbrew/src/gmock-1.8.0/googletest/src/gtest.cc:2438
    #16 0x7f14162ac3db in testing::Test::Run() /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20201111062958-7047513803-centos7-linuxbrew/src/gmock-1.8.0/googletest/src/gtest.cc:2474:5
    #17 0x7f14162af189 in testing::TestInfo::Run() /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20201111062958-7047513803-centos7-linuxbrew/src/gmock-1.8.0/googletest/src/gtest.cc:2656:11
    #18 0x7f14162b1c07 in testing::TestCase::Run() /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20201111062958-7047513803-centos7-linuxbrew/src/gmock-1.8.0/googletest/src/gtest.cc:2774:28
    #19 0x7f14162d7817 in testing::internal::UnitTestImpl::RunAllTests() /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20201111062958-7047513803-centos7-linuxbrew/src/gmock-1.8.0/googletest/src/gtest.cc:4649:43
    #20 0x7f141633c0fc in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20201111062958-7047513803-centos7-linuxbrew/src/gmock-1.8.0/googletest/src/gtest.cc:2402:10
    #21 0x7f141633c0fc in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20201111062958-7047513803-centos7-linuxbrew/src/gmock-1.8.0/googletest/src/gtest.cc:2438
    #22 0x7f14162d648b in testing::UnitTest::Run() /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20201111062958-7047513803-centos7-linuxbrew/src/gmock-1.8.0/googletest/src/gtest.cc:4257:10
    #23 0x7f141768a92b in main /path/to/build/asan-clang-dynamic-ninja/../../src/yb/util/test_main.cc:104:13
    #24 0x7f14096ce824 in __libc_start_main /tmp/glibc-20181130-26094-cs1x60/glibc-2.23/csu/../csu/libc-start.c:289
    #25 0x4388b8 in _start /tmp/glibc-20181130-26094-cs1x60/glibc-2.23/csu/../sysdeps/x86_64/start.S:118

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior uloc.cpp:1206:5 in 
uloc.cpp:1254:5: runtime error: null pointer passed as argument 1, which is declared to never be null
/usr/include/string.h:43:28: note: nonnull attribute specified here
    #0 0x7f140fec2cca in ulocimp_getScript_67 (/opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20201111062958-7047513803-centos7-linuxbrew/installed/asan/lib/libicuuc.so.67+0x795cca)
    #1 0x7f140fec5f7f in uloc_getCountry_67 (/opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20201111062958-7047513803-centos7-linuxbrew/installed/asan/lib/libicuuc.so.67+0x798f7f)
    #2 0x7f140ff0d751 in createTagStringWithAlternates(char const*, int, char const*, int, char const*, int, char const*, int, char const*, icu_67::ByteSink&, UErrorCode*) (/opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20201111062958-7047513803-centos7-linuxbrew/installed/asan/lib/libicuuc.so.67+0x7e0751)
    #3 0x7f140ff0bf1f in createLikelySubtagsString(char const*, int, char const*, int, char const*, int, char const*, int, icu_67::ByteSink&, UErrorCode*) (/opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20201111062958-7047513803-centos7-linuxbrew/installed/asan/lib/libicuuc.so.67+0x7def1f)
    #4 0x7f140ff08850 in _uloc_minimizeSubtags(char const*, icu_67::ByteSink&, UErrorCode*) (/opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20201111062958-7047513803-centos7-linuxbrew/installed/asan/lib/libicuuc.so.67+0x7db850)
    #5 0x7f140ff07bc8 in ulocimp_minimizeSubtags_67 (/opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20201111062958-7047513803-centos7-linuxbrew/installed/asan/lib/libicuuc.so.67+0x7dabc8)
    #6 0x7f140fedbccc in icu_67::Locale::minimizeSubtags(UErrorCode&) (/opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20201111062958-7047513803-centos7-linuxbrew/installed/asan/lib/libicuuc.so.67+0x7aeccc)
    #7 0x7f14115379c9 in icu_67::Calendar::setWeekData(icu_67::Locale const&, char const*, UErrorCode&) (/opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20201111062958-7047513803-centos7-linuxbrew/installed/asan/lib/libicui18n.so.67+0xba09c9)
    #8 0x7f141153a6ad in icu_67::Calendar::Calendar(icu_67::TimeZone const&, icu_67::Locale const&, UErrorCode&) (/opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20201111062958-7047513803-centos7-linuxbrew/installed/asan/lib/libicui18n.so.67+0xba36ad)
    #9 0x7f1411566426 in icu_67::GregorianCalendar::GregorianCalendar(icu_67::TimeZone const&, UErrorCode&) (/opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20201111062958-7047513803-centos7-linuxbrew/installed/asan/lib/libicui18n.so.67+0xbcf426)
    #10 0x7f14136678b2 in yb::(anonymous namespace)::CreateCalendar() /path/to/build/asan-clang-dynamic-ninja/../../src/yb/util/date_time.cc:82:21
    #11 0x7f1413666e84 in yb::DateTime::DateFromString(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) /path/to/build/asan-clang-dynamic-ninja/../../src/yb/util/date_time.cc:233:27
    #12 0x55d335 in yb::bfql::BfqlTest_TestBuiltinToJson_Test::TestBody() /path/to/build/asan-clang-dynamic-ninja/../../src/yb/util/bfql/bfql-test.cc:584:27
    #13 0x7f1416333421 in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20201111062958-7047513803-centos7-linuxbrew/src/gmock-1.8.0/googletest/src/gtest.cc:2402:10
    #14 0x7f1416333421 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20201111062958-7047513803-centos7-linuxbrew/src/gmock-1.8.0/googletest/src/gtest.cc:2438
    #15 0x7f14162ac3db in testing::Test::Run() /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20201111062958-7047513803-centos7-linuxbrew/src/gmock-1.8.0/googletest/src/gtest.cc:2474:5
    #16 0x7f14162af189 in testing::TestInfo::Run() /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20201111062958-7047513803-centos7-linuxbrew/src/gmock-1.8.0/googletest/src/gtest.cc:2656:11
    #17 0x7f14162b1c07 in testing::TestCase::Run() /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20201111062958-7047513803-centos7-linuxbrew/src/gmock-1.8.0/googletest/src/gtest.cc:2774:28
    #18 0x7f14162d7817 in testing::internal::UnitTestImpl::RunAllTests() /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20201111062958-7047513803-centos7-linuxbrew/src/gmock-1.8.0/googletest/src/gtest.cc:4649:43
    #19 0x7f141633c0fc in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20201111062958-7047513803-centos7-linuxbrew/src/gmock-1.8.0/googletest/src/gtest.cc:2402:10
    #20 0x7f141633c0fc in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20201111062958-7047513803-centos7-linuxbrew/src/gmock-1.8.0/googletest/src/gtest.cc:2438
    #21 0x7f14162d648b in testing::UnitTest::Run() /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20201111062958-7047513803-centos7-linuxbrew/src/gmock-1.8.0/googletest/src/gtest.cc:4257:10
    #22 0x7f141768a92b in main /path/to/build/asan-clang-dynamic-ninja/../../src/yb/util/test_main.cc:104:13
    #23 0x7f14096ce824 in __libc_start_main /tmp/glibc-20181130-26094-cs1x60/glibc-2.23/csu/../csu/libc-start.c:289
    #24 0x4388b8 in _start /tmp/glibc-20181130-26094-cs1x60/glibc-2.23/csu/../sysdeps/x86_64/start.S:118

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior uloc.cpp:1254:5 in 
```

**Comment by m-iancu** [comment]
Could not find this test in latest, closing.
