### ISSUE TITLE
Fix TestSystemTables test

### ISSUE THREAD

**Issue by jaki** [yugabyte/yugabyte-db#6480]
Test `com.datastax.driver.core.TestSystemTables#testSystemTables` started failing regularly on TSAN build type.  The message is

```
java.lang.AssertionError: expected:<2> but was:<1>
```

It seems to have started from commit 9e9b93428593524d4cc31e14708c6f2d316dd499

- https://jenkins.dev.yugabyte.com/job/github-yugabyte-db-centos-master-clang-tsan/lastCompletedBuild/testReport/junit/com.datastax.driver.core/TestSystemTables/testSystemTables/history/?start=50 -> https://jenkins.dev.yugabyte.com/job/github-yugabyte-db-centos-master-clang-tsan/1409/ has

  ```
  [#1259] Speedup DROP TABLE (details / githubweb)
  [#5427] Added ordering logic for the tablet servers on /tablet-servers page (#6087) (details / githubweb)
  [#6080] Disable New PG Mini Test in ASAN (DropAllTablesInColocatedDB) (details / githubweb)
  ```

- https://detective-gcp.dev.yugabyte.com/stability/test?buckets=100&class=com.datastax.driver.core.TestSystemTables&name=testSystemTables has

  ```
  10/30/2020 21:53 | 3c058f96f~..3c058f96f | 1
  10/30/2020 13:09 | e9e96610f~..e9e96610f | 0
  ```

**Comment by OlegLoginov** [comment]
Stack:
```
2020-12-01 16:27:13,627 (Time-limited test) [ERROR - org.yb.AssertionWrappers.logError(AssertionWrappers.java:40)] Assertion error:
java.lang.AssertionError: expected:<2> but was:<1>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at org.yb.AssertionWrappers.lambda$assertEquals$37(AssertionWrappers.java:580)
	at org.yb.AssertionWrappers.wrapAssertion(AssertionWrappers.java:45)
	at org.yb.AssertionWrappers.assertEquals(AssertionWrappers.java:580)
	at org.yb.cql.TestSystemTables.verifyPeersTable(TestSystemTables.java:87)
	at org.yb.cql.TestSystemTables.testSystemPeersTable(TestSystemTables.java:172)
```
Failed:
```
  private void verifyPeersTable(List<Row> rows, boolean addressesOnly) throws Exception {
    List<InetSocketAddress> contactPoints = miniCluster.getCQLContactPoints();
    // One of the contact points will be missing, since that is the node we connected to.
    assertEquals(contactPoints.size() - 1, rows.size());            <<<<<<<<< rows.size() must be 2
```
From:
```
  public void testSystemPeersTable() throws Exception {
    // Pick only 1 contact point since all will have same IP.
    List<InetSocketAddress> contactPoints = miniCluster.getCQLContactPoints();
    assertEquals(NUM_TABLET_SERVERS, contactPoints.size());

    ResultSet rs = session.execute("SELECT * FROM system.peers;");
    List <Row> rows = rs.all();
    verifyPeersTable(rows, false);

    rs = session.execute("SELECT * FROM system.peers WHERE peer = '181.123.12.1'");
    assertEquals(0, rs.all().size());

    rows = session.execute("SELECT peer, rpc_address, schema_version FROM system.peers").all();
    verifyPeersTable(rows, true);   <<<<<<< EXPECTED 2 rows as result of previous SELECT
```
