### ISSUE TITLE
[platform] Create Universe failed for on promised with ubuntu machine.

### ISSUE THREAD

**Issue by jaydeepkumara** [yugabyte/yugabyte-db#6757]
Steps:- 
1. Create one VM with ubuntu.
2. Configure on promise as a provider
3. Create the universe and select newly created on the promise provider.
4. Create a universe is getting failed with the below logs.

`Scheduler.java:116 [application-akka.actor.default-dispatcher-273] Running scheduler
2020-12-28 15:22:51.201 INFO  ShellProcessHandler.java:124 [TaskPool-CreateUniverse(32846aaf-9def-48f0-9fa2-6d0e266e84d1)-0] Completed proc 'bin/ybcloud.sh onprem --region ap-south1 instance precheck yb-admin-test-JD-ompromise-28-12-n1' status=success [ 337721 ms ]
2020-12-28 15:22:51.210 ERROR SubTaskGroup.java:193 [TaskPool-8] Failed to execute task {"errorString":null,"nodeExporterUser":"prometheus","deviceInfo":{"volumeSize":8,"numVolumes":1,"diskIops":null,"storageClass":"standard","mountPoints":"/","storageType":null},"universeUUID":"32846aaf-9def-48f0-9fa2-6d0e266e84d1","expectedUniverseVersion":0,"cmkArn":null,"encryptionAtRestConfig":{"encryptionAtRestEnabled":false,"kmsConfigUUID":null,"opType":"UNDEFINED","type":"DATA_KEY"},"nodeDetailsSet":null,"communicationPorts":{"masterHttpPort":7000,"masterRpcPort":7100,"tserverHttpPort":9000,"tserverRpcPort":9100,"redisServerHttpPort":11000,"redisServerRpcPort":6379,"yqlServerHttpPort":12000,"yqlServerRpcPort":9042,"ysqlServerHttpPort":13000,"ysqlServerRpcPort":5433,"nodeExporterPort":9300},"extraDependencies":{"installNodeExporter":true},"firstTry":true,"clusters":[],"preflight_checks":null,"nodePrefix":null,"rootCA":null,"userAZSelected":false,"resetAZConfig":false,"updateInProgress":false,"backupInProgress":false,"updateSucceeded":true,"nextClusterIndex":1,"allowInsecure":true,"itestS3PackagePath":"","remotePackagePath":"","importedState":"NONE","capability":"EDITS_ALLOWED","azUuid":"0ed3c4ca-0ac3-4bef-b4d3-582ea63ad96e","nodeName":"yb-admin-test-JD-ompromise-28-12-n1","nodeUuid":null,"placementUuid":null,"instanceType":null,"properties":{},"az":{"uuid":"0ed3c4ca-0ac3-4bef-b4d3-582ea63ad96e","code":"ap-south2a","name":"ap-south2a","active":true,"subnet":null},"provider":{"uuid":"1f55b023-1391-4c1d-a2f7-aa5727eeafb3","code":"onprem","name":"ubuntu-onpromise","active":true,"customerUUID":"f33e3c9b-75ab-4c30-80ad-cba85646ea39","awsHostedZoneId":null,"awsHostedZoneName":null,"cloudParams":{"errorString":null,"providerUUID":null,"perRegionMetadata":{},"keyPairName":null,"sshPrivateKeyContent":null,"sshUser":null,"airGapInstall":false,"sshPort":54422,"hostVpcId":null,"hostVpcRegion":null,"customHostCidrs":[],"destVpcId":null}},"region":{"uuid":"4c56aee3-9e5c-4bba-894e-35df5750d3e3","code":"ap-south1","name":"ap-south1","ybImage":null,"longitude":78.4,"latitude":18.4,"zones":[{"uuid":"0ed3c4ca-0ac3-4bef-b4d3-582ea63ad96e","code":"ap-south2a","name":"ap-south2a","active":true,"subnet":null},{"uuid":"43362ce6-a953-4986-9ae7-1a985253b8a3","code":"ap-south1a","name":"ap-south1a","active":true,"subnet":null}],"active":true,"details":null,"securityGroupId":null,"vnetName":null}}, hit error java.lang.RuntimeException: {
  "SSH Connection": false
}.
java.util.concurrent.ExecutionException: java.lang.RuntimeException: {
  "SSH Connection": false
}
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.yugabyte.yw.commissioner.SubTaskGroup.waitFor(SubTaskGroup.java:182)
	at com.yugabyte.yw.commissioner.SubTaskGroupQueue.run(SubTaskGroupQueue.java:43)
	at com.yugabyte.yw.commissioner.tasks.CreateUniverse.run(CreateUniverse.java:154)
	at com.yugabyte.yw.commissioner.TaskRunner.run(TaskRunner.java:144)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: {
  "SSH Connection": false
}
	at com.yugabyte.yw.commissioner.AbstractTaskBase.processShellResponse(AbstractTaskBase.java:112)
	at com.yugabyte.yw.commissioner.tasks.subtasks.PrecheckNode.run(PrecheckNode.java:64)
	... 5 common frames omitted
2020-12-28 15:22:51.213 ERROR SubTaskGroupQueue.java:53 [TaskPool-8] SubTaskGroup 'AnsibleSetupServer : completed 0 out of 1 tasks.' waitFor() returned failed status.
2020-12-28 15:22:51.216 ERROR CreateUniverse.java:156 [TaskPool-8] Error executing task CreateUniverse(32846aaf-9def-48f0-9fa2-6d0e266e84d1), error='AnsibleSetupServer : completed 0 out of 1 tasks. failed.'
java.lang.RuntimeException: AnsibleSetupServer : completed 0 out of 1 tasks. failed.
	at com.yugabyte.yw.commissioner.SubTaskGroupQueue.run(SubTaskGroupQueue.java:56)
	at com.yugabyte.yw.commissioner.tasks.CreateUniverse.run(CreateUniverse.java:154)
	at com.yugabyte.yw.commissioner.TaskRunner.run(TaskRunner.java:144)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2020-12-28 15:22:51.222 ERROR TaskRunner.java:150 [TaskPool-8] Error running task
java.lang.RuntimeException: AnsibleSetupServer : completed 0 out of 1 tasks. failed.
	at com.yugabyte.yw.commissioner.SubTaskGroupQueue.run(SubTaskGroupQueue.java:56)
	at com.yugabyte.yw.commissioner.tasks.CreateUniverse.run(CreateUniverse.java:154)
	at com.yugabyte.yw.commissioner.TaskRunner.run(TaskRunner.java:144)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2020-12-28 15:22:51.229 INFO  TaskRunner.java:179 [TaskPool-8] Updating task [taskType : CreateUniverse, taskState: Running] to new state Failure
2020-12-28 15:22:51.496 INFO  Commissioner.java:167 [TaskProgressMonitor] Task task-info {taskType : CreateUniverse, taskState: Failure}, task {CreateUniverse(32846aaf-9def-48f0-9fa2-6d0e266e84d1)} has failed.`

**Comment by ddorian** [comment]
@jaydeepkumara what was the issue here ?
