### ISSUE TITLE
[YCQL] C* Spark connector should allow predicate involving json column to be pushed down

### ISSUE THREAD

**Issue by tedyu** [yugabyte/yugabyte-db#6763]
Jira Link: [DB-2399](https://yugabyte.atlassian.net/browse/DB-2399)
We support json column in CQL query:
```
ycqlsh> SELECT id, details->'address' FROM k.person WHERE details->>'phone' = '1';

 id | details->'address'
----+--------------------
  1 |              "xxx"
```
However, quoted json column is not supported:
```
ycqlsh> SELECT id, details->'address' FROM k.person WHERE "details->>'phone'" = '1';
InvalidRequest: Error from server: code=2200 [Invalid query] message="Undefined Column. Column doesn't exist 3
SELECT id, details->'address' FROM k.person WHERE "details->>'phone'" = '1';
                                                  ^^^^^^^^^^^^^^^^^^^
 (ql error -203)"
```
while quoted normal column is supported:
```
ycqlsh> SELECT "id", details->'address' FROM k.person WHERE details->>'phone' = '1';

 id | details->'address'
----+--------------------
  1 |              "xxx"

(1 rows)
```
Cause: the prepared statement issued by C* Spark connector uses quotes around json column. This makes YB CQL parser treat it as a normal column:
```
ts3|pid2208128|:18561|http://127.173.156.155:19359 I1229 00:52:00.739440 2208238 pt_expr.cc:1004] Column phone->'phone' not found
```
Other changes for supporting json column push down include transforming GetJsonObject() to syntax using arrow (accepted by YB CQL parser) in BasicCassandraPredicatePushDown

**Comment by frozenspider** [comment]
I think the problem here is the driver quoting JSONB expression (thinking it's just a glorified column name), not YB not supporting quotes.

**Comment by tedyu** [comment]
Thanks Alex for the comment, I have modified the description.

**Comment by tedyu** [comment]
Attempted specifying json expression in data frame select call:
```
2021-01-11 23:14:06,183 (main) [ERROR - org.yb.BaseYBTest$1$2.logEventDetails(BaseYBTest.java:240)] YB Java test failed: class="org.yb.loadtest.TestSpark3Jsonb", method="testJsonb"
org.apache.spark.sql.AnalysisException: cannot resolve '`get_json_object(phone, '$.code')`' given input columns: [address, id, name, phone];
'Project ['get_json_object(phone, '$.code')]
+- RelationV2[id#0, address#1, name#2, phone#3] person

    at org.apache.spark.sql.catalyst.analysis.package$AnalysisErrorAt.failAnalysis(package.scala:42)
    at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$$anonfun$$nestedInanonfun$checkAnalysis$1$2.applyOrElse(CheckAnalysis.scala:170)
    at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$$anonfun$$nestedInanonfun$checkAnalysis$1$2.applyOrElse(CheckAnalysis.scala:167)
    at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformUp$2(TreeNode.scala:341)
    at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:73)
    at org.apache.spark.sql.catalyst.trees.TreeNode.transformUp(TreeNode.scala:341)
    at org.apache.spark.sql.catalyst.plans.QueryPlan.$anonfun$transformExpressionsUp$1(QueryPlan.scala:104)
    at org.apache.spark.sql.catalyst.plans.QueryPlan.$anonfun$mapExpressions$1(QueryPlan.scala:116)
    at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:73)
```
Currently there is no notion of json(b) column in Spark.
There is no easy way to interpret json expression without knowing that it is concerned with jsonb column.

**Comment by tedyu** [comment]
In CassandraMetaDataRule, we have:
```
    val cassandraColumnName = metaDataExpression.child.asInstanceOf[AttributeReference].name
    val cassandraCql = s"${metaDataExpression.cql}($cassandraColumnName)"
```
The CassandraMetadataFunctions such as TTL() are based on UnaryExpression.
If "phone->'code'" is passed as the expression, we would see:
```
java.lang.AssertionError: assertion failed: Can only use Cassandra Metadata Functions on Attribute References,
found a class org.apache.spark.sql.catalyst.expressions.Literal
    at scala.Predef$.assert(Predef.scala:223)
    at org.apache.spark.sql.cassandra.CassandraMetaDataRule$.replaceMetadata(CassandraMetadataFunctions.scala:122)
    at org.apache.spark.sql.cassandra.CassandraMetaDataRule$$anonfun$apply$1.$anonfun$applyOrElse$2(CassandraMetadataFunctions.scala:213)
    at scala.collection.immutable.Stream.foldLeft(Stream.scala:549)
    at org.apache.spark.sql.cassandra.CassandraMetaDataRule$$anonfun$apply$1.applyOrElse(CassandraMetadataFunctions.scala:212)
    at org.apache.spark.sql.cassandra.CassandraMetaDataRule$$anonfun$apply$1.applyOrElse(CassandraMetadataFunctions.scala:209)
```
Some change in connector/src/main/scala/org/apache/spark/sql/cassandra/CassandraMetadataFunctions.scala is needed so that the CassandraMetadataFunction for json expression can deal with both column name and fields.

**Comment by tedyu** [comment]
Resolved by:

commit 71d9cc3b59517cbd0a2e8a01e2be0548d5c6a71d
Author: Ted Yu <yuzhihong@gmail.com>
Date:   Tue Feb 23 09:11:15 2021 -0800

    [#6763] ycql: Allow predicate involving json column to be pushed down
