### ISSUE TITLE
[Platform][BUG] YW fails at startup due to incorrect ordering of guice bindings

### ISSUE THREAD

**Issue by sb-yb** [yugabyte/yugabyte-db#6898]
Recently we moved to using runtime config in `EmailHelper.java`
This works fine EXCEPT when you have not already completed the migration `V60` 

Repro steps:
1. Delete scoped_runtime_config and runtime_config_tables if exist.
2. Delete  V60  that adds tables related to runtime config if exist.
3. sync to head (introduced in https://phabricator.dev.yugabyte.com/D10177)
4. start server

```
2021-01-15 21:02:08.541 ERROR AlertManager.java:103 [application-akka.actor.default-dispatcher-33] Error transitioning alert state for alert 04979d22-e885-4af1-bbdc-902ec0073acb
javax.persistence.PersistenceException: Query threw SQLException:ERROR: relation "runtime_config_entry" does not exist
  Position: 46 Bind values:[] Query was:select t0.scope_uuid, t0.path, t0.value from runtime_config_entry t0 where scope_uuid = ?
        at io.ebean.config.dbplatform.SqlCodeTranslator.translate(SqlCodeTranslator.java:52)
        at io.ebean.config.dbplatform.DatabasePlatform.translate(DatabasePlatform.java:219)
        at io.ebeaninternal.server.query.CQueryEngine.translate(CQueryEngine.java:149)
        at io.ebeaninternal.server.query.DefaultOrmQueryEngine.translate(DefaultOrmQueryEngine.java:43)
        at io.ebeaninternal.server.core.OrmQueryRequest.translate(OrmQueryRequest.java:102)
        at io.ebeaninternal.server.query.CQuery.createPersistenceException(CQuery.java:703)
        at io.ebeaninternal.server.query.CQueryEngine.findMany(CQueryEngine.java:411)
        at io.ebeaninternal.server.query.DefaultOrmQueryEngine.findMany(DefaultOrmQueryEngine.java:133)
        at io.ebeaninternal.server.core.OrmQueryRequest.findList(OrmQueryRequest.java:452)
        at io.ebeaninternal.server.core.DefaultServer.findList(DefaultServer.java:1596)
        at io.ebeaninternal.server.core.DefaultServer.findList(DefaultServer.java:1574)
        at io.ebeaninternal.server.querydefn.DefaultOrmQuery.findList(DefaultOrmQuery.java:1474)
        at io.ebeaninternal.server.expression.DefaultExpressionList.findList(DefaultExpressionList.java:428)
        at com.yugabyte.yw.models.RuntimeConfigEntry.getAll(RuntimeConfigEntry.java:51)
        at com.yugabyte.yw.common.config.RuntimeConfigFactory.getConfigForScope(RuntimeConfigFactory.java:98)
        at com.yugabyte.yw.common.config.RuntimeConfigFactory.forCustomer(RuntimeConfigFactory.java:41)
        at com.yugabyte.yw.common.EmailHelper.getYbEmail(EmailHelper.java:134)
        at com.yugabyte.yw.common.EmailHelper.getDestinations(EmailHelper.java:148)
        at com.yugabyte.yw.common.AlertManager.sendEmail(AlertManager.java:40)
        at com.yugabyte.yw.common.AlertManager.transitionAlert(AlertManager.java:87)
        at java.lang.Iterable.forEach(Iterable.java:75)
        at com.yugabyte.yw.commissioner.QueryAlerts.scheduleRunner(QueryAlerts.java:119)
```

**Comment by sb-yb** [comment]
This is because of the way we end up spawning threads and doing wok in Constructor. 
This causes bunch of things to start up during Module creation time. 
But migrations do not run until AppInit.

Hence we hit config usage code path even though the migration has not completed successfully.

**Comment by sb-yb** [comment]
The fix PR is ready but more thorough testing is needed. The test involves lot of manual setup work right now. Hence putting it on hold until after other priorities (OR this blows up at customer :) )

**Comment by sb-yb** [comment]
FWIW this is fixed here:
https://github.com/flyway/flyway-play/commit/cf274a3eb023588ce360fc5c993495a100c1b1bf

Any chance of getting this against play 2.6.x?
