### ISSUE TITLE
[Platform][BUG] YW Fails to send alert email

### ISSUE THREAD

**Issue by sb-yb** [yugabyte/yugabyte-db#6901]
Server startup succeeds but alerting code  keeps trying to send email periodically for a stuck alert. The email never goes out because of this error:

```
2021-01-16 07:04:16.443 INFO  EmailHelper.java:75 [application-akka.actor.default-dispatcher-2] Sending email: 'Yugabyte Platform Alert - <[admin][admin]>' to 'sbapat@yugabyte.com'
java.lang.NullPointerException
        at java.util.Hashtable.put(Hashtable.java:460)
        at com.yugabyte.yw.common.EmailHelper.sendEmail(EmailHelper.java:90)
        at com.yugabyte.yw.common.AlertManager.sendEmail(AlertManager.java:69)
        at com.yugabyte.yw.common.AlertManager.transitionAlert(AlertManager.java:87)
        at java.lang.Iterable.forEach(Iterable.java:75)
        at com.yugabyte.yw.commissioner.QueryAlerts.scheduleRunner(QueryAlerts.java:114)
```

My profile is:
![image](https://user-images.githubusercontent.com/73500297/104815797-9eda0d00-57cb-11eb-8d27-33f001307cc3.png)

**Comment by sb-yb** [comment]
Issue is because smtpData.smtpServer is null.
```
      prop.put("mail.smtp.ssl.enable", Boolean.valueOf(smtpData.useSSL));
      if (smtpData.useSSL) {
        prop.put("mail.smtp.ssl.trust", smtpData.smtpServer); // <--- throws here
      }


```
