### ISSUE TITLE
asan build is broken with 'postgres.h' not found

### ISSUE THREAD

**Issue by tedyu** [yugabyte/yugabyte-db#7039]
```
/-------------------------------------------------------------------------------
| COMPILATION FAILED
|-------------------------------------------------------------------------------
src/postgres/third-party-extensions/pg_hint_plan/pg_hint_plan.c:12:10: fatal error: 'postgres.h' file not found
#include "postgres.h"
         ^~~~~~~~~~~~
1 error generated.

Input files:
  build/asan-clang-dynamic-ninja/postgres_build/third-party-extensions/pg_hint_plan/pg_hint_plan.c
Output file (from -o): pg_hint_plan.o
```
Could be related to the leak message from sanitizer:
```
==6350==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 368 byte(s) in 1 object(s) allocated from:
    #0 0x4e988f in __interceptor_malloc /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20201207195011-bbf28cf4f1-centos7-linuxbrew/src/llvm7-7.1.0.src/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:146
    #1 0x52cf41 in pg_malloc_internal (/nfusr/dev-server/julien/yugabyte-db/build/asan-clang-dynamic-ninja/postgres_build/src/bin/pg_config/pg_config+0x52cf41)
    #2 0x52a34a in get_configdata (/nfusr/dev-server/julien/yugabyte-db/build/asan-clang-dynamic-ninja/postgres_build/src/bin/pg_config/pg_config+0x52a34a)
    #3 0x529a3a in main (/nfusr/dev-server/julien/yugabyte-db/build/asan-clang-dynamic-ninja/postgres_build/src/bin/pg_config/pg_config+0x529a3a)
    #4 0x7f5e02a91824 in __libc_start_main /tmp/glibc-20181130-26094-cs1x60/glibc-2.23/csu/../csu/libc-start.c:289
```

**Comment by tedyu** [comment]
Fixed via commit 749d4df0a17888b8289d925bb42409f7d1995518
