### ISSUE TITLE
[Platform] Health-check script generates an alert for 2.5.x when using Python 3

### ISSUE THREAD

**Issue by SergeyPotachev** [yugabyte/yugabyte-db#7082]
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "bin/cluster_health.py", line 446, in multithreaded_caller
    return getattr(instance, func_name)(*args, **kwargs)
  File "bin/cluster_health.py", line 315, in check_uptime_for_process
    uptime = self.get_uptime_for_process(process)
  File "bin/cluster_health.py", line 310, in get_uptime_for_process
    return self._remote_check_output(remote_cmd).strip()
  File "bin/cluster_health.py", line 233, in _remote_check_output
    if output.endswith('No route to host'):
TypeError: endswith first arg must be bytes or a tuple of bytes, not str
"""

The script requires small update.

**Comment by SergeyPotachev** [comment]
One more stack trace for Python 3:

Traceback (most recent call last):
 File "bin/cluster_health.py", line 605, in <module>
   main()
 File "bin/cluster_health.py", line 589, in main
   entries = coordinator.run()
 File "bin/cluster_health.py", line 488, in run
   " for check " + check.func_name)
