### ISSUE TITLE
[Platform] "Exception: 'ascii' codec can't encode character" while doing backup

### ISSUE THREAD

**Issue by SergeyPotachev** [yugabyte/yugabyte-db#7269]
I think we can improve our backup script to avoid this error and to pass correct error to the end user.

Invoked as: /usr/bin/s3cmd --force --no-check-certificate --config=/tmp/yb_backup_wygnfycffkppgomv/cloud_cfg get s3://backups.yugabyte.com/portal/univ-9e9fba85-eeef-4304-9558-a3efc5670fa0/backup-2021-02-17T16:08:33-808616546/keyspace-yugabyte/tablet-3ebd0fa75a3e4abc9b5e91
b3820c72d0.sha256 /mnt/d0/yb-data/tserver/data/rocksdb/table-000030af00003000800000000000422f/tablet-3ebd0fa75a3e4abc9b5e91b3820c72d0.snapshots/559580f7-a018-4073-943a-6f0e1de85178.sha256.downloaded
Problem: IOError: [Errno 28] No space left on device
S3cmd:   2.0.1
python:   2.7.5 (default, Aug  4 2017, 00:39:18) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
environment LANG=en_US.UTF-8

Traceback (most recent call last):
  File "/usr/bin/s3cmd", line 3073, in <module>
    rc = main()
  File "/usr/bin/s3cmd", line 2989, in main
    rc = cmd_func(args)
  File "/usr/bin/s3cmd", line 587, in cmd_object_get
    dst_stream.close()
IOError: [Errno 28] No space left on device

...

2021-02-17 17:18:41,709 INFO: Sleep 10... (6 retries left)
2021-02-17 17:18:41,753 ERROR: Failed to run command [[ ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i /opt/yugabyte/data/keys/08c0ba0e-3558-40fc-94e5-a87a627de8c5/yb-15-aws-portal-1-key.pem -p 54422 -q yugabyte@172.161.16.254 'cd / &&  bash -c '"'"'s3
cmd --force --no-check-certificate --config=/tmp/yb_backup_wygnfycffkppgomv/cloud_cfg sync --no-check-md5 s3://backups.yugabyte.com/portal/univ-9e9fba85-eeef-4304-9558-a3efc5670fa0/backup-2021-02-17T16:08:33-808616546/keyspace-yugabyte/tablet-f03fa0eb783a47b4b0aa65ed6cf21
d1d/ /mnt/d0/yb-data/tserver/data/rocksdb/table-000030af00003000800000000000420a/tablet-f03fa0eb783a47b4b0aa65ed6cf21d1d.snapshots/559580f7-a018-4073-943a-6f0e1de85178.tmp/'"'"'' ]]: code=71 output=ERROR: Download of '001986.sst.sblock.0' failed (Reason: No space left)
ERROR: Exiting now because of fatal error
ERROR: [Errno 28] No space left on device: '/mnt/d0/yb-data/tserver/data/rocksdb/table-000030af00003000800000000000420a/tablet-f03fa0eb783a47b4b0aa65ed6cf21d1d.snapshots/559580f7-a018-4073-943a-6f0e1de85178.tmp/.s3cmd.HAsjSl.tmp'

...

2021-02-17 17:18:46,707 INFO: Sleep 10... (6 retries left)
2021-02-17 17:18:48,334 [INFO] from ShellProcessHandler in TaskPool-BackupUniverse(9e9fba85-eeef-4304-9558-a3efc5670fa0)-0 - Completed proc 'bin/py_wrapper bin/yb_backup.py --masters 172.161.16.254:7100,172.16 ... 2-17T16:08:33-808616546/keyspace-yugabyte --storage_type s3 restore' status=success [ 956884 ms ]
2021-02-17 17:18:48,334 [ERROR] from AbstractTaskBase in TaskPool-BackupUniverse(9e9fba85-eeef-4304-9558-a3efc5670fa0)-0 - Response code=0, hasError=true.
2021-02-17 17:18:48,334 [ERROR] from AbstractTaskBase in TaskPool-BackupUniverse(9e9fba85-eeef-4304-9558-a3efc5670fa0)-0 - Errored out with: java.lang.RuntimeException: {"error": "Exception: 'ascii' codec can't encode character u'\\u2018' in position 31: ordinal not in range(128)"}
2021-02-17 17:18:48,337 [ERROR] from SubTaskGroup in TaskPool-36 - Failed to execute task {"errorString":null,"nodeExporterUser":"prometheus","deviceInfo":null,"universeUUID":"9e9fba85-eeef-4304-9558-a3efc5670fa0","expectedUniverseVersion":0,"cmkArn":null,"encryptionAtRestConfig":{"encryptionAtRestEnabled":false,"kmsConfigUUID":null,"opType":"UNDEFINED","type":"DATA_KEY"},"nodeDetailsSet":null,"communicationPorts":{"masterHttpPort":7000,"masterRpcPort":7100,"tserverHttpPort":9000,"tserverRpcPort":9100,"redisServerHttpPort":11000,"redisServerRpcPort":6379,"yqlServerHttpPort":12000,"yqlServerRpcPort":9042,"ysqlServerHttpPort":13000,"ysqlServerRpcPort":5433,"nodeExporterPort":9300},"extraDependencies":{"installNodeExporter":true},"firstTry":true,"keyspace":null,"tableName":null,"tableUUID":null,"sse":false,"storageConfigUUID":"c045b0bb-f154-4198-9d6e-2dfb95c633e4","kmsConfigUUID":null,"storageLocation":null,"actionType":"RESTORE","backupType":null,"tableNameList":null,"tableUUIDList":null,"backupList":[{"errorString":null,"nodeExporterUser":"prometheus","deviceInfo":null,"universeUUID":"9e9fba85-eeef-4304-9558-a3efc5670fa0","expectedUniverseVersion":0,"cmkArn":null,"encryptionAtRestConfig":{"encryptionAtRestEnabled":false,"kmsConfigUUID":null,"opType":"UNDEFINED","type":"DATA_KEY"},"nodeDetailsSet":null,"communicationPorts":{"masterHttpPort":7000,"masterRpcPort":7100,"tserverHttpPort":9000,"tserverRpcPort":9100,"redisServerHttpPort":11000,"redisServerRpcPort":6379,"yqlServerHttpPort":12000,"yqlServerRpcPort":9042,"ysqlServerHttpPort":13000,"ysqlServerRpcPort":5433,"nodeExporterPort":9300},"extraDependencies":{"installNodeExporter":true},"firstTry":true,"keyspace":null,"tableName":null,"tableUUID":null,"sse":false,"storageConfigUUID":"c045b0bb-f154-4198-9d6e-2dfb95c633e4","kmsConfigUUID":null,"storageLocation":"s3://backups.yugabyte.com/portal/univ-9e9fba85-eeef-4304-9558-a3efc5670fa0/backup-2021-02-17T16:08:33-808616546/keyspace-yugabyte","actionType":"RESTORE","backupType":"PGSQL_TABLE_TYPE","tableNameList":null,"tableUUIDList":null,"backupList":null,"schedulingFrequency":0,"cronExpression":null,"timeBeforeDelete":0,"enableVerboseLogs":false,"transactionalBackup":false,"parallelism":32,"scheduleUUID":null}],"schedulingFrequency":0,"cronExpression":null,"timeBeforeDelete":0,"enableVerboseLogs":false,"transactionalBackup":false,"parallelism":32,"scheduleUUID":null}, hit error java.lang.RuntimeException: java.lang.RuntimeException: {"error": "Exception: 'ascii' codec can't encode character u'\\u2018' in position 31: ordinal not in range(128)"}.
java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.RuntimeException: {"error": "Exception: 'ascii' codec can't encode character u'\\u2018' in position 31: ordinal not in range(128)"}
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at com.yugabyte.yw.commissioner.SubTaskGroup.waitFor(SubTaskGroup.java:181)
        at com.yugabyte.yw.commissioner.SubTaskGroupQueue.run(SubTaskGroupQueue.java:43)
        at com.yugabyte.yw.commissioner.tasks.BackupUniverse.run(BackupUniverse.java:90)
        at com.yugabyte.yw.commissioner.TaskRunner.run(TaskRunner.java:144)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: {"error": "Exception: 'ascii' codec can't encode character u'\\u2018' in position 31: ordinal not in range(128)"}
        at com.yugabyte.yw.commissioner.tasks.subtasks.BackupTable.run(BackupTable.java:92)
        ... 5 common frames omitted
Caused by: java.lang.RuntimeException: {"error": "Exception: 'ascii' codec can't encode character u'\\u2018' in position 31: ordinal not in range(128)"}
        at com.yugabyte.yw.commissioner.tasks.subtasks.BackupTable.run(BackupTable.java:66)
        ... 5 common frames omitted

**Comment by robertsami** [comment]
i also wonder if we can detect this preemptively by looking at the size of the backup vs. amount of free disk space
