### ISSUE TITLE
[ASAN] Core dump when releasing ScopedLeaderSharedLock

### ISSUE THREAD

**Issue by tedyu** [yugabyte/yugabyte-db#7328]
From https://detective-gcp.dev.yugabyte.com/job/github-yugabyte-db-phabricator%2F76843%2Fartifact%2Fbuild%2Fasan-clang-dynamic-ninja%2Fyb-test-logs%2Ftests-integration-tests__master-partitioned-test%2FMasterPartitionedTest_CauseMasterLeaderStepdownWithTasksInProgress.log?class=MasterPartitionedTest&max_lines=3000&name=CauseMasterLeaderStepdownWithTasksInProgress&start_line=21001

```
Core was generated by `/nfusr/centos-gcp-cloud/jenkins-worker-a76/jenkins/jenkins-github-yugabyte-db-p'.
--
23779 | Program terminated with signal 11, Segmentation fault.
23780 | #0 0x00007fb7cd431638 in yb::intrusive_ptr_release (state=0x61900204ea80) at src/yb/util/status.cc:584
23781 | 584 ../../src/yb/util/status.cc: No such file or directory.
23782 | #0 0x00007fb7cd431638 in yb::intrusive_ptr_release (state=0x61900204ea80) at src/yb/util/status.cc:584
23783 | #1 0x000000000055651b in boost::intrusive_ptr<yb::Status::State>::~intrusive_ptr (this=0x7ffc5b90e028) at /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20210129085319-35a57c6c37-centos7-linuxbrew/installed/asan/include/boost/smart_ptr/intrusive_ptr.hpp:98
23784 | #2 0x00007fb7eb042730 in yb::master::ScopedLeaderSharedLock::~ScopedLeaderSharedLock (this=0x7ffc5b90e010) at src/yb/master/scoped_leader_shared_lock.h:79
23785 | #3 0x00007fb7eb028010 in yb::MiniCluster::LeaderMasterIdx (this=0x612000007b40) at src/yb/integration-tests/mini_cluster.cc:344
23786 | #4 0x00007fb7eb0286d6 in yb::MiniCluster::leader_mini_master (this=0x612000007b40) at src/yb/integration-tests/mini_cluster.cc:353
23787 | #5 0x000000000054c8e7 in yb::MasterPartitionedTest_CauseMasterLeaderStepdownWithTasksInProgress_Test::TestBody()::$_0::operator()() const (this=<optimized out>) at src/yb/integration-tests/master-partitioned-test.cc:182
23788 | #6 0x000000000054c74b in __invoke<(lambda at src/yb/integration-tests/master-partitioned-test.cc:181:31) &> (__f=...) at /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20210129085319-35a57c6c37-centos7-linuxbrew/installed/asan/libcxx/include/c++/v1/type_traits:4345
23789 | #7 std::__1::__invoke_void_return_wrapper<yb::Result<bool> >::__call<yb::MasterPartitionedTest_CauseMasterLeaderStepdownWithTasksInProgress_Test::TestBody()::$_0&>(yb::MasterPartitionedTest_CauseMasterLeaderStepdownWithTasksInProgress_Test::TestBody()::$_0&) (__args=...) at /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20210129085319-35a57c6c37-centos7-linuxbrew/installed/asan/libcxx/include/c++/v1/__functional_base:318
23790 | #8 0x000000000054c5ee in std::__1::__function::__func<yb::MasterPartitionedTest_CauseMasterLeaderStepdownWithTasksInProgress_Test::TestBody()::$_0, std::__1::allocator<yb::MasterPartitionedTest_CauseMasterLeaderStepdownWithTasksInProgress_Test::TestBody()::$_0>, yb::Result<bool> ()>::operator()() (this=<optimized out>) at /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20210129085319-35a57c6c37-centos7-linuxbrew/installed/asan/libcxx/include/c++/v1/functional:1562
23791 | #9 0x00007fb7ce086de7 in std::__1::function<yb::Result<bool> ()>::operator()() const (this=<optimized out>) at /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20210129085319-35a57c6c37-centos7-linuxbrew/installed/asan/libcxx/include/c++/v1/functional:1913
23792 | #10 0x00007fb7ce0841f7 in yb::Wait(std::__1::function<yb::Result<bool> ()>, yb::MonoTime, string const&, yb::MonoDelta, double, yb::MonoDelta) (condition=..., deadline=..., description=..., initial_delay=..., delay_multiplier=1.1000000000000001, max_delay=...) at src/yb/util/test_util.cc:268
23793
```
It seems state pointer was null (or pointing to invalid memory address):
```
void intrusive_ptr_release(Status::State* state) {
```

**Comment by bmatican** [comment]
Closing as old.
