### ISSUE TITLE
[Platform] Resuming an universe sometimes failing

### ISSUE THREAD

**Issue by VijiYB** [yugabyte/yugabyte-db#7481]
Resuming an universe fails

<img width="1794" alt="Screen Shot 2021-03-04 at 8 05 00 AM" src="https://user-images.githubusercontent.com/78048211/109992745-6d0bff80-7cc0-11eb-960d-d59d6f6695b8.png">

Logs:
Failed to execute task {"errorString":null,"nodeExporterUser":"prometheus","deviceInfo":null,"universeUUID":"c75ddcb1-cc4a-45e2-b078-f14864d0ce04","expectedUniverseVersion":0,"cmkArn":null,"encryptionAtRestConfig":{"encryptionAtRestEnabled":false,"kmsConfigUUID":null,"opType":"UNDEFINED","type":"DATA_KEY"},"nodeDetailsSet":null,"communicationPorts":{"masterHttpPort":7000,"masterRpcPort":7100,"tserverHttpPort":9000,"tserverRpcPort":9100,"redisServerHttpPort":11000,"redisServerRpcPort":6379,"yqlServerHttpPort":12000,"yqlServerRpcPort":9042,"ysqlServerHttpPort":13000,"ysqlServerRpcPort":5433,"nodeExporterPort":9300},"extraDependencies":{"installNodeExporter":true},"firstTry":true,"clusters":[],"preflight_checks":null,"nodePrefix":null,"rootCA":null,"userAZSelected":false,"resetAZConfig":false,"updateInProgress":false,"backupInProgress":false,"updateSucceeded":true,"universePaused":false,"nextClusterIndex":1,"allowInsecure":true,"itestS3PackagePath":"","remotePackagePath":"","importedState":"NONE","capability":"EDITS_ALLOWED","azUuid":"947b969a-53f8-4610-ab5a-aa427a06b23a","nodeName":"yb-15-rtsisyk-playground-n3","nodeUuid":null,"placementUuid":null,"instanceType":"c4.large","properties":{},"process":"tserver","command":"start","sleepAfterCmdMills":0,"isForceDelete":false,"forceDelete":false,"region":{"uuid":"f7e753d3-ea72-400f-8f7e-f2fe061b9d9f","code":"eu-central-1","name":"EU (Frankfurt)","ybImage":"ami-1e038d71","longitude":8.682127,"latitude":50.110922,"zones":[{"uuid":"b089fa37-4121-40f7-ac9f-569dd659b477","code":"eu-central-1a","name":"eu-central-1a","active":true,"subnet":"subnet-5d7b9936","kubeconfigPath":null},{"uuid":"947b969a-53f8-4610-ab5a-aa427a06b23a","code":"eu-central-1c","name":"eu-central-1c","active":true,"subnet":"subnet-733dd03e","kubeconfigPath":null},{"uuid":"401952de-7ed4-4976-bbf3-3d8b7f493c3a","code":"eu-central-1b","name":"eu-central-1b","active":true,"subnet":"subnet-afc9e4d5","kubeconfigPath":null}],"active":true,"details":null,"securityGroupId":null,"vnetName":null},"provider":{"uuid":"08c0ba0e-3558-40fc-94e5-a87a627de8c5","code":"aws","name":"aws-portal-1","active":true,"customerUUID":"11d78d93-1381-4d1d-8393-ba76f47ba7a6","awsHostedZoneId":"Z3TGQ3ML504YWU","awsHostedZoneName":"universe.yugabyte.com.","cloudParams":{"errorString":null,"providerUUID":null,"perRegionMetadata":{},"keyPairName":null,"sshPrivateKeyContent":null,"sshUser":null,"airGapInstall":false,"sshPort":54422,"hostVpcId":null,"hostVpcRegion":null,"customHostCidrs":[],"destVpcId":null}},"az":{"uuid":"947b969a-53f8-4610-ab5a-aa427a06b23a","code":"eu-central-1c","name":"eu-central-1c","active":true,"subnet":"subnet-733dd03e","kubeconfigPath":null}}, hit error java.lang.RuntimeException: 2021-03-04 00:34:27,806 INFO validate_credentials:cloud.py:95: Found aws cloud credentials in env.
2021-03-04 00:34:27,841 INFO load:credentials.py:1087: Found credentials in environment variables.
2021-03-04 00:34:28,786 INFO callback:method.py:729: Running ctl command start for process: tserver in instance: yb-15-rtsisyk-playground-n3
2021-03-04 00:34:28,786 INFO run:ansible.py:123: [app] Running ansible playbook yb-server-ctl.yml against target 172.158.51.250,
2021-03-04 00:34:28,787 INFO run:ansible.py:125: Running ansible command ["ansible-playbook" "/opt/yugabyte/packages/yugabyte-2.5.3.0-b14/devops/yb-server-ctl.yml" "--vault-password-file" "/opt/yugabyte/data/keys/08c0ba0e-3558-40fc-94e5-a87a627de8c5/yb-15-aws-portal-1-key.vault_password" "--private-key" "/opt/yugabyte/data/keys/08c0ba0e-3558-40fc-94e5-a87a627de8c5/yb-15-aws-portal-1-key.pem" "--user" "yugabyte" "-i" "172.158.51.250," "-c" "ssh" "-e" "ansible_python_interpreter='/usr/bin/env python'" "--extra-vars" "{\"ansible_port\": \"54422\", \"custom_ssh_port\": \"54422\", \"cloud_type\": \"aws\", \"server_type\": \"cluster-server\", \"process\": \"tserver\", \"ssd_size_gb\": 250, \"yb_home_dir\": \"/home/yugabyte\", \"instance_search_pattern\": \"all\", \"yb_server_ssh_user\": \"yugabyte\", \"instance_name\": \"yb-15-rtsisyk-playground-n3\", \"command\": \"start\", \"vars_file\": \"/opt/yugabyte/data/keys/08c0ba0e-3558-40fc-94e5-a87a627de8c5/yb-15-aws-portal-1-key.vault\", \"cloud_zone\": \"eu-central-1c\", \"disk_iops\": 1000, \"ssh_user\": \"yugabyte\", \"yb_ansible_host\": \"172.158.51.250\", \"user_name\": \"yugabyte\", \"cloud_region\": \"eu-central-1\"}"]
Traceback (most recent call last):
  File "/opt/yugabyte/packages/yugabyte-2.5.3.0-b14/devops/python_virtual_env/bin/ybcloud.py", line 4, in <module>
    __import__('pkg_resources').run_script('ybops==0.4', 'ybcloud.py')
  File "/opt/yugabyte/packages/yugabyte-2.5.3.0-b14/devops/python_virtual_env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/opt/yugabyte/packages/yugabyte-2.5.3.0-b14/devops/python_virtual_env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1462, in run_script
    exec(code, namespace, namespace)
  File "/opt/yugabyte/packages/yugabyte-2.5.3.0-b14/devops/python_virtual_env/lib/python2.7/site-packages/ybops-0.4-py2.7.egg/EGG-INFO/scripts/ybcloud.py", line 15, in <module>
    YbCloud().run()
  File "/opt/yugabyte/packages/yugabyte-2.5.3.0-b14/devops/python_virtual_env/lib/python2.7/site-packages/ybops-0.4-py2.7.egg/ybops/cloud/ybcloud.py", line 56, in run
    self.options.func(self.options)
  File "/opt/yugabyte/packages/yugabyte-2.5.3.0-b14/devops/python_virtual_env/lib/python2.7/site-packages/ybops-0.4-py2.7.egg/ybops/cloud/common/method.py", line 77, in callback_wrapper
    self.callback(args)
  File "/opt/yugabyte/packages/yugabyte-2.5.3.0-b14/devops/python_virtual_env/lib/python2.7/site-packages/ybops-0.4-py2.7.egg/ybops/cloud/common/method.py", line 733, in callback
    self.base_command.name, self.name, args, self.extra_vars, host_info)
  File "/opt/yugabyte/packages/yugabyte-2.5.3.0-b14/devops/python_virtual_env/lib/python2.7/site-packages/ybops-0.4-py2.7.egg/ybops/cloud/common/cloud.py", line 174, in run_control_script
    self.setup_ansible(args).run("yb-server-ctl.yml", updated_vars, host_info)
  File "/opt/yugabyte/packages/yugabyte-2.5.3.0-b14/devops/python_virtual_env/lib/python2.7/site-packages/ybops-0.4-py2.7.egg/ybops/cloud/common/ansible.py", line 134, in run
    filename, inventory_target, process_args, p.returncode, stderr))
ybops.common.exceptions.YBOpsRuntimeError: Runtime error: Playbook run of yb-server-ctl.yml against 172.158.51.250, with args ['ansible-playbook', '/opt/yugabyte/packages/yugabyte-2.5.3.0-b14/devops/yb-server-ctl.yml', '--vault-password-file', '/opt/yugabyte/data/keys/08c0ba0e-3558-40fc-94e5-a87a627de8c5/yb-15-aws-portal-1-key.vault_password', '--private-key', '/opt/yugabyte/data/keys/08c0ba0e-3558-40fc-94e5-a87a627de8c5/yb-15-aws-portal-1-key.pem', '--user', 'yugabyte', '-i', '172.158.51.250,', '-c', 'ssh', '-e', "ansible_python_interpreter='/usr/bin/env python'", '--extra-vars', '{"ansible_port": "54422", "custom_ssh_port": "54422", "cloud_type": "aws", "server_type": "cluster-server", "process": "tserver", "ssd_size_gb": 250, "yb_home_dir": "/home/yugabyte", "instance_search_pattern": "all", "yb_server_ssh_user": "yugabyte", "instance_name": "yb-15-rtsisyk-playground-n3", "command": "start", "vars_file": "/opt/yugabyte/data/keys/08c0ba0e-3558-40fc-94e5-a87a627de8c5/yb-15-aws-portal-1-key.vault", "cloud_zone": "eu-central-1c", "disk_iops": 1000, "ssh_user": "yugabyte", "yb_ansible_host": "172.158.51.250", "user_name": "yugabyte", "cloud_region": "eu-central-1"}'] failed with return code 4 and error ''.

**Comment by VijiYB** [comment]
Tried one more universe - just created (no worklods added), paused and resumed and it failed. Seems to be an issue while starting the node.

Logs:
Failed to execute task {"errorString":null,"nodeExporterUser":"prometheus","deviceInfo":null,"universeUUID":"802bafc0-7f98-4c4b-8ea3-93edc30852a5","expectedUniverseVersion":0,"cmkArn":null,"encryptionAtRestConfig":{"encryptionAtRestEnabled":false,"kmsConfigUUID":null,"opType":"UNDEFINED","type":"DATA_KEY"},"nodeDetailsSet":null,"communicationPorts":{"masterHttpPort":7000,"masterRpcPort":7100,"tserverHttpPort":9000,"tserverRpcPort":9100,"redisServerHttpPort":11000,"redisServerRpcPort":6379,"yqlServerHttpPort":12000,"yqlServerRpcPort":9042,"ysqlServerHttpPort":13000,"ysqlServerRpcPort":5433,"nodeExporterPort":9300},"extraDependencies":{"installNodeExporter":true},"firstTry":true,"clusters":[],"preflight_checks":null,"nodePrefix":null,"rootCA":null,"userAZSelected":false,"resetAZConfig":false,"updateInProgress":false,"backupInProgress":false,"updateSucceeded":true,"universePaused":false,"nextClusterIndex":1,"allowInsecure":true,"itestS3PackagePath":"","remotePackagePath":"","importedState":"NONE","capability":"EDITS_ALLOWED","azUuid":"cfe87580-f559-4e92-a9b4-8a92b234a41a","nodeName":"yb-15-viji-test-pause-resume-n1","nodeUuid":null,"placementUuid":null,"instanceType":"c5.large","properties":{},"process":"tserver","command":"start","sleepAfterCmdMills":0,"isForceDelete":false,"forceDelete":false,"region":{"uuid":"050d866b-dfaf-4acf-9467-f2c45d965eb9","code":"us-west-1","name":"US West (N. California)","ybImage":"ami-b1a59fd1","longitude":-119.417932,"latitude":36.778261,"zones":[{"uuid":"0041e83c-c850-43c9-bccd-4fb3a233c435","code":"us-west-1a","name":"us-west-1a","active":true,"subnet":"subnet-1a5aa841","kubeconfigPath":null},{"uuid":"cfe87580-f559-4e92-a9b4-8a92b234a41a","code":"us-west-1b","name":"us-west-1b","active":true,"subnet":"subnet-e8b01c8f","kubeconfigPath":null}],"active":true,"details":null,"securityGroupId":null,"vnetName":null},"provider":{"uuid":"08c0ba0e-3558-40fc-94e5-a87a627de8c5","code":"aws","name":"aws-portal-1","active":true,"customerUUID":"11d78d93-1381-4d1d-8393-ba76f47ba7a6","awsHostedZoneId":"Z3TGQ3ML504YWU","awsHostedZoneName":"universe.yugabyte.com.","cloudParams":{"errorString":null,"providerUUID":null,"perRegionMetadata":{},"keyPairName":null,"sshPrivateKeyContent":null,"sshUser":null,"airGapInstall":false,"sshPort":54422,"hostVpcId":null,"hostVpcRegion":null,"customHostCidrs":[],"destVpcId":null}},"az":{"uuid":"cfe87580-f559-4e92-a9b4-8a92b234a41a","code":"us-west-1b","name":"us-west-1b","active":true,"subnet":"subnet-e8b01c8f","kubeconfigPath":null}}, hit error java.lang.RuntimeException: 2021-03-04 16:15:54,531 INFO validate_credentials:cloud.py:95: Found aws cloud credentials in env.
2021-03-04 16:15:54,563 INFO load:credentials.py:1087: Found credentials in environment variables.
2021-03-04 16:15:54,973 INFO callback:method.py:729: Running ctl command start for process: tserver in instance: yb-15-viji-test-pause-resume-n1
2021-03-04 16:15:54,973 INFO run:ansible.py:123: [app] Running ansible playbook yb-server-ctl.yml against target 172.150.46.128,
2021-03-04 16:15:54,973 INFO run:ansible.py:125: Running ansible command ["ansible-playbook" "/opt/yugabyte/packages/yugabyte-2.5.3.0-b14/devops/yb-server-ctl.yml" "--vault-password-file" "/opt/yugabyte/data/keys/08c0ba0e-3558-40fc-94e5-a87a627de8c5/yb-15-aws-portal-1-key.vault_password" "--private-key" "/opt/yugabyte/data/keys/08c0ba0e-3558-40fc-94e5-a87a627de8c5/yb-15-aws-portal-1-key.pem" "--user" "yugabyte" "-i" "172.150.46.128," "-c" "ssh" "-e" "ansible_python_interpreter='/usr/bin/env python'" "--extra-vars" "{\"ansible_port\": \"54422\", \"custom_ssh_port\": \"54422\", \"cloud_type\": \"aws\", \"server_type\": \"cluster-server\", \"process\": \"tserver\", \"ssd_size_gb\": 250, \"yb_home_dir\": \"/home/yugabyte\", \"instance_search_pattern\": \"all\", \"yb_server_ssh_user\": \"yugabyte\", \"instance_name\": \"yb-15-viji-test-pause-resume-n1\", \"command\": \"start\", \"vars_file\": \"/opt/yugabyte/data/keys/08c0ba0e-3558-40fc-94e5-a87a627de8c5/yb-15-aws-portal-1-key.vault\", \"cloud_zone\": \"us-west-1b\", \"disk_iops\": 1000, \"ssh_user\": \"yugabyte\", \"yb_ansible_host\": \"172.150.46.128\", \"user_name\": \"yugabyte\", \"cloud_region\": \"us-west-1\"}"]
Traceback (most recent call last):
  File "/opt/yugabyte/packages/yugabyte-2.5.3.0-b14/devops/python_virtual_env/bin/ybcloud.py", line 4, in <module>
    __import__('pkg_resources').run_script('ybops==0.4', 'ybcloud.py')
  File "/opt/yugabyte/packages/yugabyte-2.5.3.0-b14/devops/python_virtual_env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/opt/yugabyte/packages/yugabyte-2.5.3.0-b14/devops/python_virtual_env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1462, in run_script
    exec(code, namespace, namespace)
  File "/opt/yugabyte/packages/yugabyte-2.5.3.0-b14/devops/python_virtual_env/lib/python2.7/site-packages/ybops-0.4-py2.7.egg/EGG-INFO/scripts/ybcloud.py", line 15, in <module>
    YbCloud().run()
  File "/opt/yugabyte/packages/yugabyte-2.5.3.0-b14/devops/python_virtual_env/lib/python2.7/site-packages/ybops-0.4-py2.7.egg/ybops/cloud/ybcloud.py", line 56, in run
    self.options.func(self.options)
  File "/opt/yugabyte/packages/yugabyte-2.5.3.0-b14/devops/python_virtual_env/lib/python2.7/site-packages/ybops-0.4-py2.7.egg/ybops/cloud/common/method.py", line 77, in callback_wrapper
    self.callback(args)
  File "/opt/yugabyte/packages/yugabyte-2.5.3.0-b14/devops/python_virtual_env/lib/python2.7/site-packages/ybops-0.4-py2.7.egg/ybops/cloud/common/method.py", line 733, in callback
    self.base_command.name, self.name, args, self.extra_vars, host_info)
  File "/opt/yugabyte/packages/yugabyte-2.5.3.0-b14/devops/python_virtual_env/lib/python2.7/site-packages/ybops-0.4-py2.7.egg/ybops/cloud/common/cloud.py", line 174, in run_control_script
    self.setup_ansible(args).run("yb-server-ctl.yml", updated_vars, host_info)
  File "/opt/yugabyte/packages/yugabyte-2.5.3.0-b14/devops/python_virtual_env/lib/python2.7/site-packages/ybops-0.4-py2.7.egg/ybops/cloud/common/ansible.py", line 134, in run
    filename, inventory_target, process_args, p.returncode, stderr))
ybops.common.exceptions.YBOpsRuntimeError: Runtime error: Playbook run of yb-server-ctl.yml against 172.150.46.128, with args ['ansible-playbook', '/opt/yugabyte/packages/yugabyte-2.5.3.0-b14/devops/yb-server-ctl.yml', '--vault-password-file', '/opt/yugabyte/data/keys/08c0ba0e-3558-40fc-94e5-a87a627de8c5/yb-15-aws-portal-1-key.vault_password', '--private-key', '/opt/yugabyte/data/keys/08c0ba0e-3558-40fc-94e5-a87a627de8c5/yb-15-aws-portal-1-key.pem', '--user', 'yugabyte', '-i', '172.150.46.128,', '-c', 'ssh', '-e', "ansible_python_interpreter='/usr/bin/env python'", '--extra-vars', '{"ansible_port": "54422", "custom_ssh_port": "54422", "cloud_type": "aws", "server_type": "cluster-server", "process": "tserver", "ssd_size_gb": 250, "yb_home_dir": "/home/yugabyte", "instance_search_pattern": "all", "yb_server_ssh_user": "yugabyte", "instance_name": "yb-15-viji-test-pause-resume-n1", "command": "start", "vars_file": "/opt/yugabyte/data/keys/08c0ba0e-3558-40fc-94e5-a87a627de8c5/yb-15-aws-portal-1-key.vault", "cloud_zone": "us-west-1b", "disk_iops": 1000, "ssh_user": "yugabyte", "yb_ansible_host": "172.150.46.128", "user_name": "yugabyte", "cloud_region": "us-west-1"}'] failed with return code 4 and error ''.

**Comment by nishantSharma459** [comment]
@VijiYB It seems a BE bug and not only related to the Resume Universe. It can occur for any task for eg. while taking backups, alerts, etc. So, on that note, I'm assigning the bug to BE folks.

@mahendranbhat Please take a look at it on a priority basis.

**Comment by mahendranbhat** [comment]
@VijiYB able to reproduce this after repeated pause and resume. Looks like `tserver` start is failing for some reason.

**Comment by mahendranbhat** [comment]
A resume is failing because the OS boot-up takes some time even after the AWS instance is in a running state. Added retry mechanism until we can ssh into the machine in the PR.
https://github.com/yugabyte/yugabyte-db/pull/7508 @Arnav15 @SergeyPotachev

**Comment by mahendranbhat** [comment]
@VijiYB Can you please test it by enabling the feature?
