### ISSUE TITLE
[SPARK][YCQL] Support IPV6 in SparkConf() method to set host by IP

### ISSUE THREAD

**Issue by ajcaldera1** [yugabyte/yugabyte-db#7567]
Jira Link: [DB-2144](https://yugabyte.atlassian.net/browse/DB-2144)
When a customer attempts to pass an ipv6 address to spark.cassandra.connection.host, the application is unable to connect because the IPv6 address cannot be properly parsed.

```
java.lang.IllegalArgumentException: Couldn't parse host [xxxx:xxxx:xxx:xxxx:xxxx:x:x:x]
at com.datastax.spark.connector.cql.CassandraConnectorConf$.maybeResolveHostAndPort(CassandraConnectorConf.scala:339)
at com.datastax.spark.connector.cql.CassandraConnectorConf$.$anonfun$getIpBasedContactInfoFromSparkConf$1(CassandraConnectorConf.scala:380)
at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:245)
```

**Comment by m-iancu** [comment]
@ajcaldera1 What spark and cassandra driver versions were they using?

**Comment by ajcaldera1** [comment]
@m-iancu:
```
spark connector - spark-cassandra-connector_2.12-3.0-yb-2
spark connector driver - spark-cassandra-connector-driver_2.12-3.0-yb-2
```

**Comment by m-iancu** [comment]
Thank @ajcaldera1  -- I think this should be addressed by the following PR: https://github.com/yugabyte/spark-cassandra-connector/pull/8  cc @tedyu to confirm.
