### ISSUE TITLE
TestTablespaceProperties#testTablespaces fails in ASAN

### ISSUE THREAD

**Issue by tedyu** [yugabyte/yugabyte-db#7598]
https://detective-gcp.dev.yugabyte.com/job/github-yugabyte-db-phabricator%2F80105%2Fartifact%2Fjava%2Fyb-pgsql%2Ftarget%2Fsurefire-reports_org.yb.pgsql.TestTablespaceProperties__testTablespaces%2Forg.yb.pgsql.TestTablespaceProperties-output.txt?class=org.yb.pgsql.TestTablespaceProperties&max_lines=3000&name=testTablespaces&start_line=42001

Noticed repeated message in the following form:
```
42001 | [m-2AL] | I | 415.598226 | 8918 | cluster_balance_util.h:523 | tablet server PEER_TS-3A has invalid placement info. Not allowing it to take more tablets.
-- | -- | -- | -- | -- | -- | --
42002 | [m-2AL] | I | 415.598245 | 8918 | cluster_balance_util.h:523 | tablet server PEER_TS-3A has invalid placement info. Not allowing it to take more tablets.
42003 | [m-2AL] | I | 415.598264 | 8918 | cluster_balance_util.h:523 | tablet server PEER_TS-3A has invalid placement info. Not allowing it to take more tablets.
```

**Comment by tedyu** [comment]
Saw the following when running the test locally:
```
m2|pid32481|:18703|http://127.205.14.96:10905 I0311 04:57:15.119746  1559 sys_catalog.cc:1098] CopyPgsqlTables: Batch# 7 copied 1408 rows with 559.71 KB bytes
m2|pid32481|:18703|http://127.205.14.96:10905 W0311 04:57:15.468822  1559 long_operation_tracker.cc:141] ScopedRWOperation took a long time: 5.819s
2021-03-11 04:57:16,292 (Time-limited test) [WARN - org.yb.pgsql.BasePgSQLTest.cleanUpAfter(BasePgSQLTest.java:344)] No connection created, skipping cleanup
2021-03-11 04:57:16,293 (main) [ERROR - org.yb.BaseYBTest$1$2.logEventDetails(BaseYBTest.java:240)] YB Java test failed: class="org.yb.pgsql.TestTablespaceProperties", method="testTablespaces"
org.junit.runners.model.TestTimedOutException: test timed out after 450 seconds
    at java.lang.Thread.sleep(Native Method)
    at org.yb.client.TestUtils.waitFor(TestUtils.java:359)
    at org.yb.client.TestUtils.waitFor(TestUtils.java:352)
    at org.yb.pgsql.BasePgSQLTest.initPostgresBefore(BasePgSQLTest.java:264)
```
It seems CopyPgsqlTables took long time.

**Comment by bmatican** [comment]
Closing as it's been a long time.
