### ISSUE TITLE
[DocDB] FlushTablets rpc causes SEGV of the tserver process.

### ISSUE THREAD

**Issue by psudheer21** [yugabyte/yugabyte-db#7602]
Noticed SEGV of the Tserver process while compacting all the tablets.
Compaction was initiated using the yb-ts-cli utility:
`yb-ts-cli -server_address <ip>:9100 compact_all_tablets`

The backtrace is:
```
#0  yb::tserver::TabletServiceAdminImpl::FlushTablets (this=this@entry=0x28a45b0, req=req@entry=0x464b030, resp=resp@entry=0x24cea50, context=...) at /mnt/d0/repositories/yugabyte-db/src/yb/tserver/tablet_service.cc:1250
#1  0x00007f582d4b116b in yb::tserver::TabletServerAdminServiceIf::Handle (this=0x28a45b0, call=...) at /mnt/d0/repositories/yugabyte-db/build/release-gcc-dynamic/src/yb/tserver/tserver_admin.service.cc:238
#2  0x00007f582b1db209 in yb::rpc::ServicePoolImpl::Handle (this=0x261a900, incoming=...) at /mnt/d0/repositories/yugabyte-db/src/yb/rpc/service_pool.cc:262
#3  0x00007f582b17f464 in yb::rpc::InboundCall::InboundCallTask::Run (this=<optimized out>) at /mnt/d0/repositories/yugabyte-db/src/yb/rpc/inbound_call.cc:216
#4  0x00007f582b1ed138 in yb::rpc::(anonymous namespace)::Worker::Execute (this=<optimized out>) at /mnt/d0/repositories/yugabyte-db/src/yb/rpc/thread_pool.cc:105
#5  0x00007f5826f695df in operator() (this=0x55335b8) at /home/yugabyte/yb-software/yugabyte-2.5.3.0-sudheer-release-centos-x86_64/linuxbrew-x/Cellar/gcc/5.5.0_4/include/c++/5.5.0/functional:2267
#6  yb::Thread::SuperviseThread (arg=0x5533560) at /mnt/d0/repositories/yugabyte-db/src/yb/util/thread.cc:771
#7  0x00007f5822684694 in start_thread (arg=0x7f57ec27c700) at pthread_create.c:333
#8  0x00007f5821dc141d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

The line in our code that does this:
```
1215 void TabletServiceAdminImpl::FlushTablets(const FlushTabletsRequestPB* req,                          
1216                                           FlushTabletsResponsePB* resp,                              
1217                                           rpc::RpcContext context) {                                 
.....                                                  
1238                                                                                                      
1239   if (req->all_tablets()) {                                                                          
1240     server_->tablet_manager()->GetTabletPeers(&tablet_peers, &tablet_ptrs);                          
1241   } else {                                                                                           
1242     for (const TabletId& id : req->tablet_ids()) {                                                   
1243       auto tablet_peer = VERIFY_RESULT_OR_RETURN(LookupTabletPeerOrRespond(                          
1244           server_->tablet_peer_lookup(), id, resp, &context));                                       
1245       tablet_peers.push_back(std::move(tablet_peer.tablet_peer));                                    
1246       tablet_ptrs.push_back(std::move(tablet_peer.tablet));                                          
1247     }                                                                                                
1248   }                                                                                                  
1249   for (const TabletPeerPtr& tablet_peer : tablet_peers) {                                            
1250     resp->set_failed_tablet_id(tablet_peer->tablet()->tablet_id()); 
......
```

This is happening pretty frequently on my ~50 node cluster.

This is running the 2.5.3.0 version of master with my rpc forwarding code on top of it.
I don't anticipate that causing any issues as the rpc forwarding happens only from the Postgres process.

**Comment by psudheer21** [comment]
Attaching logs for the tserver when the SEGV happened:

[yb-tserver.ip-172-151-41-87.us-west-2.compute.internal.yugabyte.log.INFO.20210311-095101.26537.gz](https://github.com/yugabyte/yugabyte-db/files/6124304/yb-tserver.ip-172-151-41-87.us-west-2.compute.internal.yugabyte.log.INFO.20210311-095101.26537.gz)
