### ISSUE TITLE
yb_release failure for yugabyte cli package on darwin, 2.4 branch

### ISSUE THREAD

**Issue by iSignal** [yugabyte/yugabyte-db#7628]
Running `./yb_release --package=cli --force --destination=$(realpath ~/yugabyte-client)` from origin/2.4 results in

```
1-03-12 18:11:05,729 [mac_library_packager.py:389 INFO] Absolute dependency /Users/sanketh/code/yugabyte-db/build/release-clang-dynamic-ninja/postgres/lib/libpq.5.dylib
2021-03-12 18:11:05,729 [mac_library_packager.py:389 INFO] Absolute dependency /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20201111063103-7047513803-macos/installed/common/lib/libz.1.dylib
2021-03-12 18:11:05,729 [mac_library_packager.py:389 INFO] Absolute dependency /Users/sanketh/code/yugabyte-db/build/release-clang-dynamic-ninja/lib/libyb_pggate.dylib
2021-03-12 18:11:05,729 [mac_library_packager.py:389 INFO] Absolute dependency /Users/sanketh/code/yugabyte-db/build/release-clang-dynamic-ninja/lib/libyb_common.dylib
2021-03-12 18:11:05,800 [mac_library_packager.py:365 INFO] Setting new path to @loader_path/../lib/libpq.5.dylib for file /Users/sanketh/code/yugabyte-db/build/yb_release_tmp_5883d75d-87d6-4976-8ad0-963e53373fdb/yb_distribution/postgres/bin/clusterdb
2021-03-12 18:11:05,809 [mac_library_packager.py:389 INFO] Absolute dependency /Users/sanketh/code/yugabyte-db/build/release-clang-dynamic-ninja/postgres/lib/libpq.5.dylib
2021-03-12 18:11:05,883 [mac_library_packager.py:373 INFO] Setting new path to @loader_path/../../lib/libssl.1.0.0.dylib/libssl.1.0.0.dylib for file /Users/sanketh/code/yugabyte-db/build/yb_release_tmp_5883d75d-87d6-4976-8ad0-963e53373fdb/yb_distribution/postgres/bin/postgres
2021-03-12 18:11:05,893 [mac_library_packager.py:373 INFO] Setting new path to @loader_path/../../lib/libcrypto.1.0.0.dylib/libcrypto.1.0.0.dylib for file /Users/sanketh/code/yugabyte-db/build/yb_release_tmp_5883d75d-87d6-4976-8ad0-963e53373fdb/yb_distribution/postgres/bin/postgres
Traceback (most recent call last):
  File "/Users/sanketh/code/yugabyte-db/build-support/yb_release.py", line 294, in <module>
    main()
  File "/Users/sanketh/code/yugabyte-db/build-support/yb_release.py", line 237, in main
    library_packager.package_binaries()
  File "/Users/sanketh/code/yugabyte-db/python/yb/mac_library_packager.py", line 138, in package_binaries
    self.fix_postgres_load_paths(os.path.join(postgres_bin, bin_file), dst)
  File "/Users/sanketh/code/yugabyte-db/python/yb/mac_library_packager.py", line 380, in fix_postgres_load_paths
    raise RuntimeError("filename {} lib {}".format(filename, os.path.join(rpath, basename)))
RuntimeError: filename /Users/sanketh/code/yugabyte-db/build/yb_release_tmp_5883d75d-87d6-4976-8ad0-963e53373fdb/yb_distribution/postgres/bin/postgres lib /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20201111063103-7047513803-macos/installed/common/lib/libldap-2.4.2.dylib
```

@jaki @mbautin

**Comment by jaki** [comment]
It says ldap, but I see it most recently touched in commit c1462a1240f71ccea98591ad09a86f0183d5a54b, long ago.  Anyway, adding @d-uspenskiy.

**Comment by rthallamko3** [comment]
@iSignal , Can we close this issue now?
