### ISSUE TITLE
[YSQL] Segmentation fault of PostgreSQL process in TestPgWrapper#testDefaultValues on macOS

### ISSUE THREAD

**Issue by mbautin** [yugabyte/yugabyte-db#765]
```
9075 | [ts-1] | W | 293.540785 | 118232512 | hybrid_clock.cc:109 | HybridClock initialized in local mode (OS X only). Not suitable for distributed clusters.
9076 | [ts-1] | I | 293.540810 | 147574784 | async_initializer.cc:73 | Starting to init ybclient
9077 | [ts-1] | I | 293.544599 | 147574784 | client-internal.cc:1233 | Reinitialize master addresses from file: /tmp/ybtest-jenkins-1547718841425-395996215/yb-flags2177307316363852744.flags
9078 | [ts-1] | I | 293.544819 | 147574784 | client-internal.cc:1242 | New master addresses: M-1_RPC_HOST_PORT,M-2_RPC_HOST_PORT,M-3_RPC_HOST_PORT
9079 | [ts-1] | 2019-01-17 01:58:54.978 PST [92635] LOG: server process (PID 93768) was terminated by signal 11: Segmentation fault
9080 | [ts-1] | 2019-01-17 01:58:54.978 PST [92635] LOG: terminating any other active server processes
9081 | [ts-1] | 2019-01-17 01:58:54.981 PST [92635] LOG: all server processes terminated; reinitializing

9082 |   | ERROR | 293.553000 | Time-limited test | BasePgSQLTest.java:193 | Exception while trying to create connection (after 1 attempts): The connection attempt failed.
9083 |   | WARN | 293.553000 | Time-limited test | BasePgSQLTest.java:272 | No connection created, skipping dropping tables
9084 |   | ERROR | 293.556000 | main | BaseYBTest.java:240 | YB Java test failed: class="org.yb.pgsql.TestPgWrapper", method="testDefaultValues"
9085 | org.postgresql.util.PSQLException: The connection attempt failed.
9086 | at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:292)
9087 | at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
9088 | at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:195)
9089 | at org.postgresql.Driver.makeConnection(Driver.java:454)
9090 | at org.postgresql.Driver.connect(Driver.java:256)
9091 | at java.sql.DriverManager.getConnection(DriverManager.java:664)
9092 | at java.sql.DriverManager.getConnection(DriverManager.java:247)
9093 | at org.yb.pgsql.BasePgSQLTest.createConnection(BasePgSQLTest.java:162)
9094 | at org.yb.pgsql.BasePgSQLTest.createConnection(BasePgSQLTest.java:146)
9095 | at org.yb.pgsql.BasePgSQLTest.initPostgresBefore(BasePgSQLTest.java:117)
9096 | at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
9097 | at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
9098 | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
9099 | at java.lang.reflect.Method.invoke(Method.java:498)
9100 | at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
9101 | at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
9102 | at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
9103 | at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
9104 | at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
9105 | at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
9106 | at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
9107 | at java.util.concurrent.FutureTask.run(FutureTask.java:266)
9108 | at java.lang.Thread.run(Thread.java:748)
9109 | Caused by: java.io.EOFException
9110 | at org.postgresql.core.PGStream.receiveChar(PGStream.java:308)
9111 | at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:499)
9112 | at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:141)
9113 | at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:192)
9114 | ... 22 more
9115 |   | INFO | 293.558000 | main | BaseYBTest.java:247 | YB Java test class="org.yb.pgsql.TestPgWrapper", method="testDefaultValues" took 293.51 seconds
9116 |  
9117 | ----------------------------------------------------------------------------------------------------
9118 | Finished YB Java test: class="org.yb.pgsql.TestPgWrapper", method="testDefaultValues"
9119 | ----------------------------------------------------------------------------------------------------
9120 |  

9121 | [ts-1]


```

**Comment by m-iancu** [comment]
Closing, confirmed `0` failures in Jenkins for the last `100` commits and across all build platforms.
