### ISSUE TITLE
[Platform] Improve DeleteBackup task processing and error handling

### ISSUE THREAD

**Issue by SergeyPotachev** [yugabyte/yugabyte-db#7754]
Internal GCP portal doesn't process any http requests being busy processing a lot of DeleteBackup requests.
Each of the requests is finished with an error:

2021-03-22 17:51:20.700 ERROR DeleteBackup.java:79 [TaskPool-126] Delete Backup failed for gs://ybdevportalbackup/univ-f25b1152-c41d-4906-ba34-0d813ed1390e/backup-2021-03-19T03:23:15-1273049692/keyspace-postgres. Response code=0, hasError=true.
2021-03-22 17:51:20.700 ERROR DeleteBackup.java:87 [TaskPool-126] Errored out with: java.lang.RuntimeException: {"error": "Exception: Command '['ssh', '-o', 'StrictHostKeyChecking=no', '-o', 'UserKnownHostsFile=/dev/null', '-i', '/opt/yugabyte/yugaware/data/keys/f8438937-
bef6-4ed7-8304-2fad20f54946/yb-1-gcp-provider-key.pem', '-p', '54422', '-q', 'yugabyte@10.151.0.34', \"cd / &&  bash -c 'mkdir -p /tmp/yb_backup_hmyjzdjiipcbntrp'\"]' returned non-zero exit status 255"}
2021-03-22 17:51:20.700 ERROR TaskRunner.java:149 [TaskPool-126] Error running task
java.lang.RuntimeException: java.lang.RuntimeException: {"error": "Exception: Command '['ssh', '-o', 'StrictHostKeyChecking=no', '-o', 'UserKnownHostsFile=/dev/null', '-i', '/opt/yugabyte/yugaware/data/keys/f8438937-bef6-4ed7-8304-2fad20f54946/yb-1-gcp-provider-key.pem', 
'-p', '54422', '-q', 'yugabyte@x.x.x.x', \"cd / &&  bash -c 'mkdir -p /tmp/yb_backup_hmyjzdjiipcbntrp'\"]' returned non-zero exit status 255"}
        at com.yugabyte.yw.commissioner.tasks.DeleteBackup.run(DeleteBackup.java:92)
        at com.yugabyte.yw.commissioner.TaskRunner.run(TaskRunner.java:143)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: {"error": "Exception: Command '['ssh', '-o', 'StrictHostKeyChecking=no', '-o', 'UserKnownHostsFile=/dev/null', '-i', '/opt/yugabyte/yugaware/data/keys/f8438937-bef6-4ed7-8304-2fad20f54946/yb-1-gcp-provider-key.pem', '-p', '54422', '-
q', 'yugabyte@x.x.x.x', \"cd / &&  bash -c 'mkdir -p /tmp/yb_backup_hmyjzdjiipcbntrp'\"]' returned non-zero exit status 255"}
        at com.yugabyte.yw.commissioner.tasks.DeleteBackup.run(DeleteBackup.java:81)
        ... 6 common frames omitted

Java threads dump and the full log file could be provided on demand.
Setting the issue priority to "priority/critical" as the problem leads to `Denial of Service`.

**Comment by SergeyPotachev** [comment]
One of proposals - update the DeleteBackup processing from synchronous to asynchronous.

**Comment by SergeyPotachev** [comment]
One of problems - there is an ability to create a Backup schedule with very small execution interval (as example, one second).

**Comment by streddy-yb** [comment]
- Throttle the number of DeleteBackup tasks that can be executed in one shot
- If a DeleteBackup tasks more than a certain number of times, fail the DeleteBackup task; provide manual steps to clean up the backups in such cases. For example, if the storage config key is no longer valid, both create and delete backup tasks will fail.

**Comment by gaurav061** [comment]
PR: https://github.com/yugabyte/yugabyte-db/pull/8241
