### ISSUE TITLE
YCQL Java throws InvalidQueryException when table already exists

### ISSUE THREAD

**Issue by beatrausch** [yugabyte/yugabyte-db#7796]
**Expectation:**
In case a table already exists an AlreadyExistsException shall be thrown

**Description:**
Running the following sample code with yugabytedb leads to InvalidQueryException.
When running the sample code against a cassandra cluster an AlreadyExistsException is thrown in case the table already exists. 

```
import com.datastax.oss.driver.api.core.CqlSession;
import com.datastax.oss.driver.api.core.servererrors.AlreadyExistsException;
import com.datastax.oss.driver.api.core.servererrors.InvalidQueryException;
 
import java.net.InetSocketAddress;
 
public class CreateTableExample
{
    public static void main(String[] args) {
        try (final CqlSession session = CqlSession
                .builder()
                .addContactPoint(new InetSocketAddress("127.0.0.1", 9042))
                .withLocalDatacenter("datacenter1")
                .build())
        {
            session.execute("CREATE KEYSPACE IF NOT EXISTS example_keyspace WITH REPLICATION = {'class':'SimpleStrategy', 'replication_factor': '1'} AND DURABLE_WRITES = true;");
                                           
            session.execute("CREATE TABLE example_keyspace.example_table (key TEXT, value INT, PRIMARY KEY(key));");
            // create table creates different exceptions for Yugabyte YCQL and Cassandra CQL, if the table already exists
            session.execute("CREATE TABLE example_keyspace.example_table (key TEXT, value INT, PRIMARY KEY(key));");
        }
        catch (final InvalidQueryException e)
        {
            // YCQL throws an InvalidQueryException
            System.out.println("This is how the YCQL library reports an error if the table already exists");
            e.printStackTrace();
        } catch(AlreadyExistsException e) {
            // CQL throws an AlreadyExistsException
            System.out.println("This is how the CQL library reports an error if the table already exists");
            e.printStackTrace();
        }
        catch (final Exception e)
        {
            System.err.println("Error: " + e.getMessage());
            e.printStackTrace();
        }
    }
}
```

Stacktrace with Yugabyte Cassandra Driver:
```
com.datastax.oss.driver.api.core.servererrors.InvalidQueryException: Duplicate Object. Object 'example_keyspace.example_table' already exists
CREATE TABLE example_keyspace.example_table (key TEXT, value INT, PRIMARY KEY(key));
                             ^^^^^^^^^^^^^^
(ql error -202)
at com.datastax.oss.driver.api.core.servererrors.InvalidQueryException.copy(InvalidQueryException.java:48)
at com.datastax.oss.driver.internal.core.util.concurrent.CompletableFutures.getUninterruptibly(CompletableFutures.java:149)
at com.datastax.oss.driver.internal.core.cql.CqlRequestSyncProcessor.process(CqlRequestSyncProcessor.java:53)
at com.datastax.oss.driver.internal.core.cql.CqlRequestSyncProcessor.process(CqlRequestSyncProcessor.java:30)
at com.datastax.oss.driver.internal.core.session.DefaultSession.execute(DefaultSession.java:230)
at com.datastax.oss.driver.api.core.cql.SyncCqlSession.execute(SyncCqlSession.java:53)
at com.datastax.oss.driver.api.core.cql.SyncCqlSession.execute(SyncCqlSession.java:73)
at de.esolutions.datalake.kvstore.yugabyte.CreateTableExample.main(CreateTableExample.java:23)

```

Stacktracw with Datastax OSS Cassandra Driver:
```
com.datastax.oss.driver.api.core.servererrors.AlreadyExistsException: Object example_keyspace.example_table already exists
at com.datastax.oss.driver.api.core.servererrors.AlreadyExistsException.copy(AlreadyExistsException.java:65)
at com.datastax.oss.driver.internal.core.util.concurrent.CompletableFutures.getUninterruptibly(CompletableFutures.java:149)
at com.datastax.oss.driver.internal.core.cql.CqlRequestSyncProcessor.process(CqlRequestSyncProcessor.java:53)
at com.datastax.oss.driver.internal.core.cql.CqlRequestSyncProcessor.process(CqlRequestSyncProcessor.java:30)
at com.datastax.oss.driver.internal.core.session.DefaultSession.execute(DefaultSession.java:230)
at com.datastax.oss.driver.api.core.cql.SyncCqlSession.execute(SyncCqlSession.java:53)
at com.datastax.oss.driver.api.core.cql.SyncCqlSession.execute(SyncCqlSession.java:73)
at de.esolutions.datalake.kvstore.yugabyte.CreateTableExample.main(CreateTableExample.java:23)

```

**Versions**
Docker Image: yugabytedb/yugabyte:2.5.3.1-b10
Yugabyte Cassandra: group: 'com.yugabyte', name: 'java-driver-core', version: '4.6.0-yb-6'
Cassandra: group: 'com.datastax.oss', name: 'java-driver-core', version: '4.6.0'

**Comment by beatrausch** [comment]
Hi,
any update?
Regards
