### ISSUE TITLE
[Platform] Backups are failing on 2.7.0.0-b10

### ISSUE THREAD

**Issue by rao-vasireddy** [yugabyte/yugabyte-db#7828]
2021-03-26 01:50:49,253 ERROR: Failed to run command [[ ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i /opt/yugabyte/yugaware/data/keys/6c88d8d8-ee29-42e1-abb6-754433dc832b/yb-demo-aws-portal-2-key.pem -p 54422 -q yugabyte@172.151.29.73 'cd / &&  bash -c '"'"'s3cmd --force --no-check-certificate --config=/tmp/yb_backup_aciewfozgxashluj/cloud_cfg put /tmp/yb_backup_aciewfozgxashluj/SnapshotInfoPB.sha256 s3://backups.yugabyte.com/portal-2/univ-c2dfbfdf-c224-44fc-b327-a58aed4b9282/backup-2021-03-26T01:48:53-2107801856/table-ybdemo_keyspace.batch_ts_metrics_raw-6efeb0220c754fbcbd6888d7ddab247b/SnapshotInfoPB.sha256'"'"'' ]]: code=72 output=
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
ImportError trying to import dateutil.parser.
Please install the python dateutil module:
$ sudo apt-get install python-dateutil
  or
$ sudo yum install python-dateutil
  or
$ pip install python-dateutil
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Traceback (most recent call last):
  File "bin/yb_backup.py", line 2247, in run
    self.backup_table()
  File "bin/yb_backup.py", line 1877, in backup_table
    snapshot_id = self.create_and_upload_metadata_files(snapshot_filepath)
  File "bin/yb_backup.py", line 1826, in create_and_upload_metadata_files
    os.path.join(snapshot_filepath, METADATA_FILE_NAME))
  File "bin/yb_backup.py", line 1723, in upload_metadata_and_checksum
    server_ip)
  File "bin/yb_backup.py", line 1207, in run_ssh_cmd
    num_retry=num_retries)
  File "bin/yb_backup.py", line 594, in run_program
    self.sleep_or_raise(num_retry, timeout, e)
  File "bin/yb_backup.py", line 562, in sleep_or_raise
    raise ex
CalledProcessError: Command '['ssh', '-o', 'StrictHostKeyChecking=no', '-o', 'UserKnownHostsFile=/dev/null', '-i', '/opt/yugabyte/yugaware/data/keys/6c88d8d8-ee29-42e1-abb6-754433dc832b/yb-demo-aws-portal-2-key.pem', '-p', '54422', '-q', 'yugabyte@172.151.29.73', "cd / &&  bash -c 's3cmd --force --no-check-certificate --config=/tmp/yb_backup_aciewfozgxashluj/cloud_cfg put /tmp/yb_backup_aciewfozgxashluj/SnapshotInfoPB.sha256 s3://backups.yugabyte.com/portal-2/univ-c2dfbfdf-c224-44fc-b327-a58aed4b9282/backup-2021-03-26T01:48:53-2107801856/table-ybdemo_keyspace.batch_ts_metrics_raw-6efeb0220c754fbcbd6888d7ddab247b/SnapshotInfoPB.sha256'"]' returned non-zero exit status 72
  File "bin/yb_backup.py", line 2264, in <module>
    YBBackup().run()
  File "bin/yb_backup.py", line 2260, in run
    traceback.print_stack()
2021-03-26 01:50:50,541 [INFO] from ShellProcessHandler in TaskPool-BackupUniverse(c2dfbfdf-c224-44fc-b327-a58aed4b9282)-1 - Completed proc 'bin/py_wrapper bin/yb_backup.py --masters 172.151.29.73:7100,172.151 ... trics_raw-6efeb0220c754fbcbd6888d7ddab247b --storage_type s3 create' status=success [ 116400 ms ]
2021-03-26 01:50:50,541 [ERROR] from AbstractTaskBase in TaskPool-BackupUniverse(c2dfbfdf-c224-44fc-b327-a58aed4b9282)-1 - Response code=0, hasError=true.
2021-03-26 01:50:50,542 [ERROR] from AbstractTaskBase in TaskPool-BackupUniverse(c2dfbfdf-c224-44fc-b327-a58aed4b9282)-1 - Errored out with: java.lang.RuntimeException: {"error": "Exception: Command '['ssh', '-o', 'StrictHostKeyChecking=no', '-o', 'UserKnownHostsFile=/dev/null', '-i', '/opt/yugabyte/yugaware/data/keys/6c88d8d8-ee29-42e1-abb6-754433dc832b/yb-demo-aws-portal-2-key.pem', '-p', '54422', '-q', 'yugabyte@172.151.29.73', \"cd / &&  bash -c 's3cmd --force --no-check-certificate --config=/tmp/yb_backup_aciewfozgxashluj/cloud_cfg put /tmp/yb_backup_aciewfozgxashluj/SnapshotInfoPB.sha256 s3://backups.yugabyte.com/portal-2/univ-c2dfbfdf-c224-44fc-b327-a58aed4b9282/backup-2021-03-26T01:48:53-2107801856/table-ybdemo_keyspace.batch_ts_metrics_raw-6efeb0220c754fbcbd6888d7ddab247b/SnapshotInfoPB.sha256'\"]' returned non-zero exit status 72"}
2021-03-26 01:50:50,545 [ERROR] from SubTaskGroup in TaskPool-48 - Failed to execute task {"errorString":null,"nodeExporterUser":"prometheus","deviceInfo":null,"universeUUID":"c2dfbfdf-c224-44fc-b327-a58aed4b9282","expectedUniverseVersion":0,"cmkArn":null,"encryptionAtRestConfig":{"encryptionAtRestEnabled":false,"kmsConfigUUID":null,"opType":"UNDEFINED","type":"DATA_KEY"},"nodeDetailsSet":null,"communicationPorts":{"masterHttpPort":7000,"masterRpcPort":7100,"tserverHttpPort":9000,"tserverRpcPort":9100,"redisServerHttpPort":11000,"redisServerRpcPort":6379,"yqlServerHttpPort":12000,"yqlServerRpcPort":9042,"ysqlServerHttpPort":13000,"ysqlServerRpcPort":5433,"nodeExporterPort":9300},"extraDependencies":{"installNodeExporter":true},"firstTry":true,"keyspace":"ybdemo_keyspace","tableName":"batch_ts_metrics_raw","tableUUID":"6efeb022-0c75-4fbc-bd68-88d7ddab247b","sse":false,"storageConfigUUID":"b26beb85-5f1a-4b8d-93fb-871463ee0dd0","kmsConfigUUID":null,"storageLocation":"s3://backups.yugabyte.com/portal-2/univ-c2dfbfdf-c224-44fc-b327-a58aed4b9282/backup-2021-03-26T01:48:53-2107801856/table-ybdemo_keyspace.batch_ts_metrics_raw-6efeb0220c754fbcbd6888d7ddab247b","actionType":"CREATE","backupType":"YQL_TABLE_TYPE","tableNameList":null,"tableUUIDList":null,"backupList":null,"schedulingFrequency":0,"cronExpression":null,"timeBeforeDelete":0,"enableVerboseLogs":false,"transactionalBackup":false,"parallelism":4,"scheduleUUID":null}, hit error java.lang.RuntimeException: java.lang.RuntimeException: {"error": "Exception: Command '['ssh', '-o', 'StrictHostKeyChecking=no', '-o', 'UserKnownHostsFile=/dev/null', '-i', '/opt/yugabyte/yugaware/data/keys/6c88d8d8-ee29-42e1-abb6-754433dc832b/yb-demo-aws-portal-2-key.pem', '-p', '54422', '-q', 'yugabyte@172.151.29.73', \"cd / &&  bash -c 's3cmd --force --no-check-certificate --config=/tmp/yb_backup_aciewfozgxashluj/cloud_cfg put /tmp/yb_backup_aciewfozgxashluj/SnapshotInfoPB.sha256 s3://backups.yugabyte.com/portal-2/univ-c2dfbfdf-c224-44fc-b327-a58aed4b9282/backup-2021-03-26T01:48:53-2107801856/table-ybdemo_keyspace.batch_ts_metrics_raw-6efeb0220c754fbcbd6888d7ddab247b/SnapshotInfoPB.sha256'\"]' returned non-zero exit status 72"}.
java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.RuntimeException: {"error": "Exception: Command '['ssh', '-o', 'StrictHostKeyChecking=no', '-o', 'UserKnownHostsFile=/dev/null', '-i', '/opt/yugabyte/yugaware/data/keys/6c88d8d8-ee29-42e1-abb6-754433dc832b/yb-demo-aws-portal-2-key.pem', '-p', '54422', '-q', 'yugabyte@172.151.29.73', \"cd / &&  bash -c 's3cmd --force --no-check-certificate --config=/tmp/yb_backup_aciewfozgxashluj/cloud_cfg put /tmp/yb_backup_aciewfozgxashluj/SnapshotInfoPB.sha256 s3://backups.yugabyte.com/portal-2/univ-c2dfbfdf-c224-44fc-b327-a58aed4b9282/backup-2021-03-26T01:48:53-2107801856/table-ybdemo_keyspace.batch_ts_metrics_raw-6efeb0220c754fbcbd6888d7ddab247b/SnapshotInfoPB.sha256'\"]' returned non-zero exit status 72"}
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:192)
    at com.yugabyte.yw.commissioner.SubTaskGroup.waitFor(SubTaskGroup.java:181)
    at com.yugabyte.yw.commissioner.SubTaskGroupQueue.run(SubTaskGroupQueue.java:43)
    at com.yugabyte.yw.commissioner.tasks.BackupUniverse.run(BackupUniverse.java:90)
    at com.yugabyte.yw.commissioner.TaskRunner.run(TaskRunner.java:150)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: {"error": "Exception: Command '['ssh', '-o', 'StrictHostKeyChecking=no', '-o', 'UserKnownHostsFile=/dev/null', '-i', '/opt/yugabyte/yugaware/data/keys/6c88d8d8-ee29-42e1-abb6-754433dc832b/yb-demo-aws-portal-2-key.pem', '-p', '54422', '-q', 'yugabyte@172.151.29.73', \"cd / &&  bash -c 's3cmd --force --no-check-certificate --config=/tmp/yb_backup_aciewfozgxashluj/cloud_cfg put /tmp/yb_backup_aciewfozgxashluj/SnapshotInfoPB.sha256 s3://backups.yugabyte.com/portal-2/univ-c2dfbfdf-c224-44fc-b327-a58aed4b9282/backup-2021-03-26T01:48:53-2107801856/table-ybdemo_keyspace.batch_ts_metrics_raw-6efeb0220c754fbcbd6888d7ddab247b/SnapshotInfoPB.sha256'\"]' returned non-zero exit status 72"}
    at com.yugabyte.yw.commissioner.tasks.subtasks.BackupTable.run(BackupTable.java:92)
    ... 5 common frames omitted
Caused by: java.lang.RuntimeException: {"error": "Exception: Command '['ssh', '-o', 'StrictHostKeyChecking=no', '-o', 'UserKnownHostsFile=/dev/null', '-i', '/opt/yugabyte/yugaware/data/keys/6c88d8d8-ee29-42e1-abb6-754433dc832b/yb-demo-aws-portal-2-key.pem', '-p', '54422', '-q', 'yugabyte@172.151.29.73', \"cd / &&  bash -c 's3cmd --force --no-check-certificate --config=/tmp/yb_backup_aciewfozgxashluj/cloud_cfg put /tmp/yb_backup_aciewfozgxashluj/SnapshotInfoPB.sha256 s3://backups.yugabyte.com/portal-2/univ-c2dfbfdf-c224-44fc-b327-a58aed4b9282/backup-2021-03-26T01:48:53-2107801856/table-ybdemo_keyspace.batch_ts_metrics_raw-6efeb0220c754fbcbd6888d7ddab247b/SnapshotInfoPB.sha256'\"]' returned non-zero exit status 72"}
    at com.yugabyte.yw.commissioner.tasks.subtasks.BackupTable.run(BackupTable.java:79)
    ... 5 common frames omitted
2021-03-26 01:50:50,546 [ERROR] from SubTaskGroupQueue in TaskPool-48 - SubTaskGroup 'BackupTable : completed 0 out of 1 tasks.' waitFor() returned failed status.
2021-03-26 01:50:50,548 [ERROR] from BackupUniverse in TaskPool-48 - Error executing task BackupUniverse(c2dfbfdf-c224-44fc-b327-a58aed4b9282) with error='BackupTable : completed 0 out of 1 tasks. failed.'.
java.lang.RuntimeException: BackupTable : completed 0 out of 1 tasks. failed.
    at com.yugabyte.yw.commissioner.SubTaskGroupQueue.run(SubTaskGroupQueue.java:56)
    at com.yugabyte.yw.commissioner.tasks.BackupUniverse.run(BackupUniverse.java:90)
    at com.yugabyte.yw.commissioner.TaskRunner.run(TaskRunner.java:150)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
Collapse

**Comment by daniel-yb** [comment]
required a devops change so doesn't require any backports. The fix should be picked up in new YW docker image builds moving forwards.
