### ISSUE TITLE
[Platform] Deleting a universe with a stopped node failed

### ISSUE THREAD

**Issue by SergeyPotachev** [yugabyte/yugabyte-db#7908]
Provider AWS. 4 nodes (az1:1, az2:2, az3:1), one node is stopped (in az2, invoked "Stop Processes"). The universe deletion failed:

Failed to execute task {"errorString":null,"nodeExporterUser":"prometheus","deviceInfo":null,"universeUUID":"374a8210-1ccc-4dd2-a0e8-c2603c9f112d","expectedUniverseVersion":0,"cmkArn":null,"encryptionAtRestConfig":{"encryptionAtRestEnabled":false,"kmsConfigUUID":null,"opType":"UNDEFINED","type":"DATA_KEY"},"nodeDetailsSet":null,"communicationPorts":{"masterHttpPort":7000,"masterRpcPort":7100,"tserverHttpPort":9000,"tserverRpcPort":9100,"redisServerHttpPort":11000,"redisServerRpcPort":6379,"yqlServerHttpPort":12000,"yqlServerRpcPort":9042,"ysqlServerHttpPort":13000,"ysqlServerRpcPort":5433,"nodeExporterPort":9300},"extraDependencies":{"installNodeExporter":true},"firstTry":true,"type":"Delete","providerUUID":"08c0ba0e-3558-40fc-94e5-a87a627de8c5","hostedZoneId":"Z3TGQ3ML504YWU","domainNamePrefix":"spotachev-test-aws.15","isForceDelete":false,"forceDelete":false}, hit error java.lang.RuntimeException: 2021-04-01 21:59:01,363 INFO validate_credentials:cloud.py:95: Found aws cloud credentials in env.
/opt/yugabyte/packages/yugabyte-2.7.1.0-b53/devops/python2_installed_modules/boto3/compat.py:86: PythonDeprecationWarning: Boto3 will no longer support Python 2.7 starting July 15, 2021. To continue receiving service updates, bug fixes, and security updates please upgrade to Python 3.6 or later. More information can be found here: https://aws.amazon.com/blogs/developer/announcing-end-of-support-for-python-2-7-in-aws-sdk-for-python-and-aws-cli-v1/
  warnings.warn(warning, PythonDeprecationWarning)
2021-04-01 21:59:01,382 INFO load:credentials.py:1100: Found credentials in environment variables.
Traceback (most recent call last):
  File "/opt/yugabyte/packages/yugabyte-2.7.1.0-b53/devops/python2_installed_modules/bin/ybcloud.py", line 15, in <module>
    YbCloud().run()
  File "/opt/yugabyte/packages/yugabyte-2.7.1.0-b53/devops/python2_installed_modules/ybops/cloud/ybcloud.py", line 56, in run
    self.options.func(self.options)
  File "/opt/yugabyte/packages/yugabyte-2.7.1.0-b53/devops/python2_installed_modules/ybops/cloud/common/method.py", line 77, in callback_wrapper
    self.callback(args)
  File "/opt/yugabyte/packages/yugabyte-2.7.1.0-b53/devops/python2_installed_modules/ybops/cloud/aws/method.py", line 434, in callback
    delete_dns_record_set(args.hosted_zone_id, args.domain_name_prefix, self.ip_list)
  File "/opt/yugabyte/packages/yugabyte-2.7.1.0-b53/devops/python2_installed_modules/ybops/cloud/aws/utils.py", line 1027, in delete_dns_record_set
    return _update_dns_record_set(hosted_zone_id, domain_name_prefix, ip_list, 'DELETE')
  File "/opt/yugabyte/packages/yugabyte-2.7.1.0-b53/devops/python2_installed_modules/ybops/cloud/aws/utils.py", line 1052, in _update_dns_record_set
    ChangeBatch=change_batch)
  File "/opt/yugabyte/packages/yugabyte-2.7.1.0-b53/devops/python2_installed_modules/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/yugabyte/packages/yugabyte-2.7.1.0-b53/devops/python2_installed_modules/botocore/client.py", line 676, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.InvalidChangeBatch: An error occurred (InvalidChangeBatch) when calling the ChangeResourceRecordSets operation: [Tried to delete resource record set [name='spotachev-test-aws.15.universe.yugabyte.com.', type='A'] but the values provided do not match the current values].

Maybe the similar issue as #5781.

**Comment by anmalysh-yb** [comment]
Tried to reproduce this one locally, but wasn't able to. Universe is deleted successfully.
Will try to do that on dev portal and also will try to do it similar to how it's described in #5781 - there's additional "Release Instance" step

**Comment by anmalysh-yb** [comment]
Ok, for some reason it's reproducing easily on aws dev portal, but not locally..

**Comment by anmalysh-yb** [comment]
I think it's because my provider does not have hosted zone ID configured..

**Comment by anmalysh-yb** [comment]
It seems like the issue here is that stopping processes actually makes the node to lose it's TServer role. And hence we need to update DNS records in order to make it consistent with our local config. This way on any later actions, including universe removal - dns recods will be consistent with our local config and we'll be able to manipulate them
