### ISSUE TITLE
Editing universe in 2 tabs

### ISSUE THREAD

**Issue by epratt-yb** [yugabyte/yugabyte-db#7954]
When editing a universe to add nodes or remove nodes, and someone (or yourself) has another tab open editing a universe you can hit an issue where one will fail and return the error below.
Steps to reproduce:
1. open 2 tabs for the same universe
2. Edit both universes with the same command either adding a node or removing one (easier repro with adding a node)
3. submit one and then shortly after submit the other from the edit universe page
4. check the logs for the error below on the node you submitted the job on first:

`2021-04-07 19:01:06,420 [INFO] from com.yugabyte.yw.commissioner.TaskRunner in TaskPool-8 - Running task
2021-04-07 19:01:06,420 [INFO] from com.yugabyte.yw.commissioner.TaskRunner in TaskPool-8 - Updating task [taskType : EditUniverse, taskState: Created] to new state Running
2021-04-07 19:01:06,422 [INFO] from com.yugabyte.yw.controllers.UniverseController in application-akka.actor.default-dispatcher-7546 - Saved task uuid 407ef99a-b3f9-4718-a1fe-22ca4b5c4da7 in customer tasks table for universe f6ba3a67-8f9d-42f8-b62f-f7944fab7407 : epratt-edit-test1.
2021-04-07 19:01:06,423 [INFO] from com.yugabyte.yw.commissioner.tasks.EditUniverse in TaskPool-8 - Started EditUniverse(f6ba3a67-8f9d-42f8-b62f-f7944fab7407) task for uuid=f6ba3a67-8f9d-42f8-b62f-f7944fab7407
2021-04-07 19:01:06,423 [ERROR] from com.yugabyte.yw.commissioner.tasks.UniverseTaskBase in TaskPool-8 - Universe f6ba3a67-8f9d-42f8-b62f-f7944fab7407 version 17, is different from the expected version of 15. User would have to sumbit the operation from a refreshed top-level universe page.
2021-04-07 19:01:06,424 [ERROR] from com.yugabyte.yw.commissioner.tasks.EditUniverse in TaskPool-8 - Error executing task EditUniverse(f6ba3a67-8f9d-42f8-b62f-f7944fab7407) with error='Universe f6ba3a67-8f9d-42f8-b62f-f7944fab7407 version 17, is different from the expected version of 15. User would have to sumbit the operation from a refreshed top-level universe page.'.
java.lang.IllegalStateException: Universe f6ba3a67-8f9d-42f8-b62f-f7944fab7407 version 17, is different from the expected version of 15. User would have to sumbit the operation from a refreshed top-level universe page.
	at com.yugabyte.yw.commissioner.tasks.UniverseTaskBase.verifyUniverseVersion(UniverseTaskBase.java:91)
	at com.yugabyte.yw.commissioner.tasks.UniverseTaskBase$1.run(UniverseTaskBase.java:62)
	at com.yugabyte.yw.models.Universe.readModifyWrite(Universe.java:332)
	at com.yugabyte.yw.models.Universe.saveDetails(Universe.java:352)
	at com.yugabyte.yw.commissioner.tasks.UniverseTaskBase.lockUniverseForUpdate(UniverseTaskBase.java:98)
	at com.yugabyte.yw.commissioner.tasks.UniverseTaskBase.lockUniverseForUpdate(UniverseTaskBase.java:200)
	at com.yugabyte.yw.commissioner.tasks.EditUniverse.run(EditUniverse.java:57)
	at com.yugabyte.yw.commissioner.TaskRunner.run(TaskRunner.java:143)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2021-04-07 19:01:06,424 [WARN] from com.yugabyte.yw.commissioner.tasks.UniverseTaskBase in TaskPool-8 - Unlock universe called when it was not locked.
2021-04-07 19:01:06,424 [ERROR] from com.yugabyte.yw.commissioner.TaskRunner in TaskPool-8 - Error running task
java.lang.IllegalStateException: Universe f6ba3a67-8f9d-42f8-b62f-f7944fab7407 version 17, is different from the expected version of 15. User would have to sumbit the operation from a refreshed top-level universe page.
	at com.yugabyte.yw.commissioner.tasks.UniverseTaskBase.verifyUniverseVersion(UniverseTaskBase.java:91)
	at com.yugabyte.yw.commissioner.tasks.UniverseTaskBase$1.run(UniverseTaskBase.java:62)
	at com.yugabyte.yw.models.Universe.readModifyWrite(Universe.java:332)
	at com.yugabyte.yw.models.Universe.saveDetails(Universe.java:352)
	at com.yugabyte.yw.commissioner.tasks.UniverseTaskBase.lockUniverseForUpdate(UniverseTaskBase.java:98)
	at com.yugabyte.yw.commissioner.tasks.UniverseTaskBase.lockUniverseForUpdate(UniverseTaskBase.java:200)
	at com.yugabyte.yw.commissioner.tasks.EditUniverse.run(EditUniverse.java:57)
	at com.yugabyte.yw.commissioner.TaskRunner.run(TaskRunner.java:143)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)`

**Comment by daniel-yb** [comment]
We do want to keep this check in the backend as it's important to make sure a task isn't submitted with stale data cached in the UI, but I think that periodically updating more components in the UI (such as how we currently update the HA data + task data) will minimize the window that this is a possibility. In the case that we do still hit this, we should convey why the task failed more clearly to the customer in the UI (i.e. say something like "Stale data detected. Please refresh your window and re-try submitting this task") cc @yb-andrew @sshev

**Comment by sshev** [comment]
@daniel-yb that is the expected behavior of optimistic locking for an attempt to change smth that already been changed by another user. What could be improved here is if platform API notifies about that right away by rejecting the universe edit PUT request. There is a built-in HTTP mechanism for implementing an optimistic locking using `ETag` header and we could leverage it as shown in these examples [here](https://medium.com/bestmile/optimistic-concurrency-control-in-http-services-c1bd911b89ad) and [here](https://medium.com/swlh/api-concurrency-control-strategies-cd546c2cdc16)
