### ISSUE TITLE
[Platform][UnitTest] TableManagerTest.testCreateBackupWithSSHUser broken at head

### ISSUE THREAD

**Issue by sb-yb** [yugabyte/yugabyte-db#7989]
```
[error] Test com.yugabyte.yw.common.TableManagerTest.testCreateBackupWithSSHUser failed: org.mockito.exceptions.verification.junit.ArgumentsAreDifferent:
[error] Argument(s) are different! Wanted:
[error] shellProcessHandler.run(
[error]     [bin/py_wrapper, bin/yb_backup.py, --masters, , --parallelism, 8, --table, mock_table, --keyspace, mock_ks, --table_uuid, 696bb9f3f85b41d79e3c38f0ba3ebbdc, --no_auto_name, --ssh_user, foo, --ssh_port, 3333, --ssh_key_path, /path/to/private.key, --backup_location, s3://foo/univ-18d163e0-a21e-40af-a7ee-edfb58a27ea2/backup-2021-04-09T16:28:17-582768181/table-mock_ks.mock_table-696bb9f3f85b41d79e3c38f0ba3ebbdc, --storage_type, s3, create],
[error]     {"BACKUP_LOCATION" = "s3://foo", "ACCESS_KEY" = "A-KEY", "ACCESS_SECRET" = "A-SECRET"}
[error] );
[error] -> at com.yugabyte.yw.common.TableManagerTest.testCreateBackupWithSSHUser(TableManagerTest.java:482)
[error] Actual invocation has different arguments:
[error] shellProcessHandler.run(
[error]     [bin/py_wrapper, bin/yb_backup.py, --masters, , --parallelism, 8, --table, mock_table, --keyspace, mock_ks, --table_uuid, 696bb9f3f85b41d79e3c38f0ba3ebbdc, --no_auto_name, --ssh_port, 3333, --ssh_key_path, /path/to/private.key, --backup_location, s3://foo/univ-18d163e0-a21e-40af-a7ee-edfb58a27ea2/backup-2021-04-09T16:28:17-582768181/table-mock_ks.mock_table-696bb9f3f85b41d79e3c38f0ba3ebbdc, --storage_type, s3, create],
[error]     {"BACKUP_LOCATION" = "s3://foo", "ACCESS_KEY" = "A-KEY", "ACCESS_SECRET" = "A-SECRET"}
[error] );
[error] -> at com.yugabyte.yw.common.TableManager.runCommand(TableManager.java:211)
[error] , took 4.935 sec
[error]     at com.yugabyte.yw.common.TableManagerTest.testCreateBackupWithSSHUser(TableManagerTest.java:482)
[error]     ...
[info] Test run finished: 1 failed, 0 ignored, 1 total, 4.944s
[error] Failed: Total 18, Failed 1, Errors 0, Passed 0, Skipped 17
[error] Failed tests:
[error]         com.yugabyte.yw.common.TableManagerTest
[error] (Test / testOnly) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 8 s, completed Apr 9, 2021 4:28:17 PM
```

**Comment by SergeyPotachev** [comment]
Closed as already fixed.
