### ISSUE TITLE
[Platform] Full move failed on 2.4.2

### ISSUE THREAD

**Issue by VijiYB** [yugabyte/yugabyte-db#8104]
I tried full move (changed the instance type) on 2.4.2 portal and it failed with follwing

repro steps:
1. created gcp universe with 3 nodes of n1-standard-4
2. Ran sample apps
3. Edit universe -> changed the instance type to n1-standard-8

Traceback (most recent call last):
  File "/opt/yugabyte/devops/python_virtual_env/bin/ybcloud.py", line 4, in <module>
    __import__('pkg_resources').run_script('ybops==0.4', 'ybcloud.py')
  File "/opt/yugabyte/devops/python_virtual_env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/opt/yugabyte/devops/python_virtual_env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1462, in run_script
    exec(code, namespace, namespace)
  File "/opt/yugabyte/devops/python_virtual_env/lib/python2.7/site-packages/ybops-0.4-py2.7.egg/EGG-INFO/scripts/ybcloud.py", line 15, in <module>
    YbCloud().run()
  File "/opt/yugabyte/devops/python_virtual_env/lib/python2.7/site-packages/ybops-0.4-py2.7.egg/ybops/cloud/ybcloud.py", line 56, in run
    self.options.func(self.options)
  File "/opt/yugabyte/devops/python_virtual_env/lib/python2.7/site-packages/ybops-0.4-py2.7.egg/ybops/cloud/common/method.py", line 77, in callback_wrapper
    self.callback(args)
  File "/opt/yugabyte/devops/python_virtual_env/lib/python2.7/site-packages/ybops-0.4-py2.7.egg/ybops/cloud/common/method.py", line 672, in callback
    "configure-{}.yml".format(args.type), self.extra_vars, host_info)
  File "/opt/yugabyte/devops/python_virtual_env/lib/python2.7/site-packages/ybops-0.4-py2.7.egg/ybops/cloud/common/ansible.py", line 133, in run
    process_args, p.returncode, stderr))
ybops.common.exceptions.YBOpsRuntimeError: Runtime error: Playbook with args ['ansible-playbook', '/opt/yugabyte/devops/configure-cluster

"instance_name": "yb-dev-viji-242-apr19-gcp-n5", "instance_type": "n1-standard-8", "tserver_rpc_port": "9100", "cloud_region": "us-west1"}'] failed with return code 4 and error.

Please check the 2.4.2 portal for more logs.

**Comment by streddy-yb** [comment]
@Arnav15 - can you look at the logs / do an initial triage of the issue?

**Comment by VijiYB** [comment]
Seems to be some connection issue. Retrying worked fine, so closing. @streddy-yb
