### ISSUE TITLE
TServer crash with "../../src/yb/client/session.cc:277] Check failed: flushed_batchers_.erase(batcher) == 1 (0 vs. 1)"

### ISSUE THREAD

**Issue by deeps1991** [yugabyte/yugabyte-db#8111]
Jira Link: [DB-1780](https://yugabyte.atlassian.net/browse/DB-1780)
In the Detective test runs for https://phabricator.dev.yugabyte.com/D11133
The test TestTablespaceProperties.testTablespaces fails in the ASAN build while creating test_lb_placement_default_idx_on_custom_table.

This is because of a CHECK failure that occurred during INDEX BACKFILL

```
ts2|pid17721|:18930 F20210417 00:18:50 ../../src/yb/client/session.cc:277] Check failed: flushed_batchers_.erase(batcher) == 1 (0 vs. 1)
ts2|pid17721|:18930     @     0x7fc35075e968  yb::(anonymous namespace)::DumpStackTraceAndExit() (src/yb/util/logging.cc:166)
ts2|pid17721|:18930     @     0x7fc34b8c20f1
ts2|pid17721|:18930     @     0x7fc34b8bdd62
ts2|pid17721|:18930     @     0x7fc34b8c0b7c
ts2|pid17721|:18930     @     0x7fc34b8d53b3
ts2|pid17721|:18930     @     0x7fc35c196d88  yb::client::YBSession::FlushFinished(scoped_refptr<yb::client::internal::Batcher>) (src/yb/client/session.cc:277)
ts2|pid17721|:18930     @     0x7fc35bf4122c  yb::client::internal::Batcher::CheckForFinishedFlush() (src/yb/client/batcher.cc:220)
ts2|pid17721|:18930     @     0x7fc35bf1d1a9  yb::client::internal::AsyncRpc::Finished(yb::Status const&) (src/yb/client/async_rpc.cc:207)
ts2|pid17721|:18930     @     0x7fc35bf3d763  decltype(*(std::forward<yb::client::internal::ReadRpc*&>(fp0)).*fp(std::forward<yb::Status::OK&>(fp1))) std::__invoke<void (yb::client::internal::AsyncRpc::*&)(yb::Status const&), yb::client::internal::ReadRpc*&, yb::Status::OK&, void>(void (yb::client::internal::AsyncRpc::*&)(yb::Status const&), yb::client::internal::ReadRpc*&, yb::Status::OK&) (/opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20210210192532-45c97f45f1-centos7-linuxbrew/installed/asan/libcxx/include/c++/v1/type_traits:4286)
ts2|pid17721|:18930     @     0x7fc35bf3d763  std::__bind_return<void (yb::client::internal::AsyncRpc::*)(yb::Status const&), tuple<yb::client::internal::ReadRpc*, yb::Status::OK>, tuple<>, __is_valid_bind_return<void (yb::client::internal::AsyncRpc::*)(yb::Status const&), tuple<yb::client::internal::ReadRpc*, yb::Status::OK>, tuple<> >::value>::type std::__apply_functor<void (yb::client::internal::AsyncRpc::*)(yb::Status const&), tuple<yb::client::internal::ReadRpc*, yb::Status::OK>, 0ul, 1ul, tuple<> >(void (yb::client::internal::AsyncRpc::*&)(yb::Status const&), tuple<yb::client::internal::ReadRpc*, yb::Status::OK>&, std::__tuple_indices<0ul, 1ul>, tuple<>&&) (/opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20210210192532-45c97f45f1-centos7-linuxbrew/installed/asan/libcxx/include/c++/v1/functional:2216)
ts2|pid17721|:18930     @     0x7fc35bf3d763  std::__bind_return<void (yb::client::internal::AsyncRpc::*)(yb::Status const&), tuple<yb::client::internal::ReadRpc*, yb::Status::OK>, tuple<>, __is_valid_bind_return<void (yb::client::internal::AsyncRpc::*)(yb::Status const&), tuple<yb::client::internal::ReadRpc*, yb::Status::OK>, tuple<> >::value>::type std::__bind<void (yb::client::internal::AsyncRpc::*)(yb::Status const&), yb::client::internal::ReadRpc*, yb::Status::OK>::operator()<>() (/opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20210210192532-45c97f45f1-centos7-linuxbrew/installed/asan/libcxx/include/c++/v1/functional:2249)
ts2|pid17721|:18930     @     0x7fc35bf3d763  decltype(std::forward<std::__bind<void (yb::client::internal::AsyncRpc::*)(yb::Status const&), yb::client::internal::ReadRpc*, yb::Status::OK>&>(fp)()) std::__invoke<std::__bind<void (yb::client::internal::AsyncRpc::*)(yb::Status const&), yb::client::internal::ReadRpc*, yb::Status::OK>&>(std::__bind<void (yb::client::internal::AsyncRpc::*)(yb::Status const&), yb::client::internal::ReadRpc*, yb::Status::OK>&) (/opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20210210192532-45c97f45f1-centos7-linuxbrew/installed/asan/libcxx/include/c++/v1/type_traits:4345)
ts2|pid17721|:18930     @     0x7fc35bf3d763  void std::__invoke_void_return_wrapper<void>::__call<std::__bind<void (yb::client::internal::AsyncRpc::*)(yb::Status const&), yb::client::internal::ReadRpc*, yb::Status::OK>&>(std::__bind<void (yb::client::internal::AsyncRpc::*)(yb::Status const&), yb::client::internal::ReadRpc*, yb::Status::OK>&) (/opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20210210192532-45c97f45f1-centos7-linuxbrew/installed/asan/libcxx/include/c++/v1/__functional_base:349)
ts2|pid17721|:18930     @     0x7fc356a3f479  yb::rpc::OutboundCall::InvokeCallbackSync() (src/yb/rpc/outbound_call.cc:384)
ts2|pid17721|:18930     @     0x7fc356a3f2ed  yb::rpc::InvokeCallbackTask::Run() (src/yb/rpc/outbound_call.cc:164)
ts2|pid17721|:18930     @     0x7fc356b8a5bb  yb::rpc::(anonymous namespace)::Worker::Execute() (src/yb/rpc/thread_pool.cc:105)
ts2|pid17721|:18930     @     0x7fc35093ad60  yb::Thread::SuperviseThread(void*) (src/yb/util/thread.cc:771)
ts2|pid17721|:18930     @     0x7fc35e022693  start_thread (/tmp/glibc-20181130-26094-cs1x60/glibc-2.23/nptl/pthread_create.c:333)
ts2|pid17721|:18930     @     0x7fc35d74141c  (unknown) (sysdeps/unix/sysv/linux/x86_64/clone.S:109)
ts2|pid17721|:18930     @ 0xffffffffffffffff
m3|pid17475|:26206 I0417 00:18:51.965571 17540 reactor.cc:440] Master_R001: Connection Connection (0x00006120000c82d8) server 127.238.30.63:51102 => 127.85.134.115:26206 not idle
m3|pid17475|:26206 I0417 00:18:51.979830 17541 reactor.cc:440] Master_R002: Connection Connection (0x00006120000f8758) server 127.238.30.63:37848 => 127.85.134.115:26206 not idle
m3|pid17475|:26206 I0417 00:18:51.988900 17542 reactor.cc:440] Master_R003: Connection Connection (0x00006120000aded8) server 127.217.110.19:60183 => 127.85.134.115:26206 not idle
m3|pid17475|:26206 I0417 00:18:51.989064 17542 reactor.cc:440] Master_R003: Connection Connection (0x00006120000c8d58) server 127.204.16.249:59991 => 127.85.134.115:26206 not idle
m3|pid17475|:26206 I0417 00:18:51.990259 17539 tcp_stream.cc:360] { local: 127.85.134.115:55571 remote: 127.166.29.118:17566 }: socket_.Recvv() error: Network error (yb/util/net/socket.cc:537): recvmsg error: Resource temporarily unavailable (system error 11)
ts2|pid17721|:18930 W0417 00:18:52.022961 17851 tablet.cc:2302] libpq query "BACKFILL INDEX 16413 READ TIME 6629862167406850048 PARTITION x'6aa9';" returned PGRES_FATAL_ERROR: server closed the connection unexpectedly
ts2|pid17721|:18930     This probably means the server terminated abnormally
ts2|pid17721|:18930     before or while processing the request.```

**Comment by tedyu** [comment]
I ran the test in ASAN:
```
m2|pid12861|:20404|http://127.238.172.243:25279 I0421 17:38:23.741937 18362 operation_counter.cc:81] [0x61d000041500] Update(-1), result = 1
2021-04-21 17:38:23,755 (main) [ERROR - org.yb.BaseYBTest$1$2.logEventDetails(BaseYBTest.java:240)] YB Java test failed: class="org.yb.pgsql.TestTablespaceProperties", method="testTablespaces"
java.lang.AssertionError
    at org.junit.Assert.fail(Assert.java:86)
    at org.junit.Assert.assertTrue(Assert.java:41)
    at org.junit.Assert.assertTrue(Assert.java:52)
    at org.yb.AssertionWrappers.lambda$assertTrue$1(AssertionWrappers.java:71)
    at org.yb.AssertionWrappers.wrapAssertion(AssertionWrappers.java:45)
    at org.yb.AssertionWrappers.assertTrue(AssertionWrappers.java:71)
    at org.yb.pgsql.TestTablespaceProperties.testLBTablespacePlacement(TestTablespaceProperties.java:223)
    at org.yb.pgsql.TestTablespaceProperties.testTablespaces(TestTablespaceProperties.java:147)
```

**Comment by deeps1991** [comment]
@tedyu You'd need to apply the change I mentioned above. It fixes a timing issue in the test, which will then expose the CHECK failure I mentioned above.

**Comment by deeps1991** [comment]
Not seen in a long time
