### ISSUE TITLE
[Platform] Email sending stuck by unknown reason

### ISSUE THREAD

**Issue by SergeyPotachev** [yugabyte/yugabyte-db#8175]
The stack trace for this thread is:

"application-akka.actor.default-dispatcher-5" #39 prio=5 os_prio=0 tid=0x00007f08e62b1800 nid=0x73 runnable [0x00007f08906c8000]
   java.lang.Thread.State: RUNNABLE
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
        at java.net.SocketInputStream.read(SocketInputStream.java:171)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at com.sun.mail.util.TraceInputStream.read(TraceInputStream.java:126)
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
        - locked <0x00000000eb525a28> (a java.io.BufferedInputStream)
        at com.sun.mail.util.LineInputStream.readLine(LineInputStream.java:106)
        at com.sun.mail.smtp.SMTPTransport.readServerResponse(SMTPTransport.java:2440)
        at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:2187)
        at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:740)
        - locked <0x00000000eb525af8> (a com.sun.mail.smtp.SMTPTransport)
        at javax.mail.Service.connect(Service.java:388)
        - locked <0x00000000eb525af8> (a com.sun.mail.smtp.SMTPTransport)
        at javax.mail.Service.connect(Service.java:246)
        at javax.mail.Service.connect(Service.java:195)
        at javax.mail.Transport.send0(Transport.java:254)
        at javax.mail.Transport.send(Transport.java:124)
        at com.yugabyte.yw.common.EmailHelper.sendEmail(EmailHelper.java:98)
        at com.yugabyte.yw.common.AlertManager.sendEmail(AlertManager.java:89)
        at com.yugabyte.yw.common.AlertManager.transitionAlert(AlertManager.java:107)
        at com.yugabyte.yw.commissioner.QueryAlerts$$Lambda$129/679144621.accept(Unknown Source)
        at java.lang.Iterable.forEach(Iterable.java:75)
        at com.yugabyte.yw.commissioner.QueryAlerts.scheduleRunner(QueryAlerts.java:130)
        at com.yugabyte.yw.commissioner.QueryAlerts$$Lambda$91/913001083.run(Unknown Source)
        at akka.actor.LightArrayRevolverScheduler$$anon$2$$anon$1.run(LightArrayRevolverScheduler.scala:104)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:49)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

   Locked ownable synchronizers:
        - None

As the thread stalled, also Alerts and Health-checks stopped to work too.

[threads-dump.txt](https://github.com/yugabyte/yugabyte-db/files/6380598/threads-dump.txt)

**Comment by SergeyPotachev** [comment]
Looks like the same problem is described here - https://community.oracle.com/tech/developers/discussion/1589635/diferences-between-mail-smtp-connectiontimeout-and-mail-smtp-timeout
Most probably the server was down for a while or the SMTP settings had some incorrect values. Tried to reproduce it using the correct settings in different combinations but failed. Fortunately, we can add some additional settings to be able to track such problems (at least to generate a YW alert for this).

**Comment by SergeyPotachev** [comment]
Was able to reproduce the issue with next parameters:  host "smtp.socketlabs.com", port 465, isSSL false

**Comment by streddy-yb** [comment]
Please backport #8329 as part of this change.

**Comment by RP1807** [comment]
Validated this issue on the 2.6 portal. Followed below steps
 
1. Configured SMTP customization in alerts with SSL OFF.
2. Created a universe and stop processes for one of the Node to trigger alerts. 
3. Alert manager fails to send an email and ALERT_MANAGER_FAILURE error code appears in Alerts 
4. Turn ON SSL for SMTP config 
5. Ensure alert manager failure is resolved and email are now received
