### ISSUE TITLE
[Platform][UnitTest] ResumeUniverseTest failing at head

### ISSUE THREAD

**Issue by sb-yb** [yugabyte/yugabyte-db#8200]
com.yugabyte.yw.commissioner.tasks.ResumeUniverseTest.testResumeUniverseSuccess is failing at head

```
2021-04-27 14:22:36.714 [error] TaskRunner.java:156 [TaskPool-0] Error running task
java.lang.RuntimeException: WaitForServer : completed 0 out of 1 tasks. failed.
        at com.yugabyte.yw.commissioner.SubTaskGroupQueue.run(SubTaskGroupQueue.java:56)
        at com.yugabyte.yw.commissioner.tasks.ResumeUniverse.run(ResumeUniverse.java:76)
        at com.yugabyte.yw.commissioner.TaskRunner.run(TaskRunner.java:150)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2021-04-27 14:22:36.715 [info] TaskRunner.java:188 [TaskPool-0] Updating task [taskType : ResumeUniverse, taskState: Running] to new state Failure
2021-04-27 14:22:36.740 [info] Commissioner.java:173 [TaskProgressMonitor] Task task-info {taskType : ResumeUniverse, taskState: Failure}, task {ResumeUniverse(448849f3-8e9f-448c-90fd-14b2aeac53dd)} has failed.
2021-04-27 14:22:37.720 [info] Scheduler.java:95 [application-akka.actor.default-dispatcher-4] Running scheduler
2021-04-27 14:22:37.722 [info] HikariCPModule.scala:79 [application-akka.actor.default-dispatcher-4] Shutting down connection pool.
[error] Test com.yugabyte.yw.commissioner.tasks.ResumeUniverseTest.testResumeUniverseSuccess failed: java.lang.AssertionError: expected:<Success> but was:<Failure>, took 6.334 sec
[error]     at com.yugabyte.yw.commissioner.tasks.ResumeUniverseTest.testResumeUniverseSuccess(ResumeUniverseTest.java:146)
[error]     ...
[MockitoHint] ResumeUniverseTest.testResumeUniverseSuccess (see javadoc for MockitoHint):
[MockitoHint] 1. Unused... -> at com.yugabyte.yw.commissioner.tasks.ResumeUniverseTest.setUp(ResumeUniverseTest.java:63)
[MockitoHint]  ...args ok? -> at com.yugabyte.yw.commissioner.tasks.subtasks.ServerSubTaskBase.getClient(ServerSubTaskBase.java:69)

[info] Test com.yugabyte.yw.commissioner.tasks.ResumeUniverseTest.testResumeUniverseWithUpdateInProgress started
[info] Test run finished: 1 failed, 0 ignored, 2 total, 8.071s
[error] Failed: Total 2, Failed 1, Errors 0, Passed 1
[error] Failed tests:
[error]         com.yugabyte.yw.commissioner.tasks.ResumeUniverseTest
[error] (Test / testOnly) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 10 s, completed Apr 27, 2021 2:22:39 PM
```

**Comment by anmalysh-yb** [comment]
Fixed it here: https://github.com/yugabyte/yugabyte-db/issues/8203
Closing this one.

**Comment by anmalysh-yb** [comment]
Here is phabricator revision which contains fix: https://phabricator.dev.yugabyte.com/D11386
