### ISSUE TITLE
[Platform] Exception during itest runs related to AWS universe creation

### ISSUE THREAD

**Issue by anmalysh-yb** [yugabyte/yugabyte-db#8203]
`2021-04-22 15:36:11,035 [ERROR] from AbstractInitializer in TaskPool-CloudBootstrap(ae312e46-b5c9-4e08-a251-7f7015266c8d)-3 - AWS initialize failed
io.ebean.DuplicateKeyException: Error[ERROR: duplicate key value violates unique constraint "price_component_pkey"   Detail: Key (provider_uuid, region_code, component_code)=(ae312e46-b5c9-4e08-a251-7f7015266c8d, us-west-2, c5.24xlarge) already exists.]
	at io.ebean.config.dbplatform.SqlCodeTranslator.translate(SqlCodeTranslator.java:46)
	at io.ebean.config.dbplatform.DatabasePlatform.translate(DatabasePlatform.java:219)
	at io.ebeaninternal.server.persist.dml.DmlBeanPersister.execute(DmlBeanPersister.java:83)
	at io.ebeaninternal.server.persist.dml.DmlBeanPersister.insert(DmlBeanPersister.java:49)
	at io.ebeaninternal.server.core.PersistRequestBean.executeInsert(PersistRequestBean.java:1280)
	at io.ebeaninternal.server.core.PersistRequestBean.executeNow(PersistRequestBean.java:790)
	at io.ebeaninternal.server.core.PersistRequestBean.executeNoBatch(PersistRequestBean.java:845)
	at io.ebeaninternal.server.core.PersistRequestBean.executeOrQueue(PersistRequestBean.java:836)
	at io.ebeaninternal.server.persist.DefaultPersister.insert(DefaultPersister.java:503)
	at io.ebeaninternal.server.persist.DefaultPersister.insert(DefaultPersister.java:451)
	at io.ebeaninternal.server.persist.DefaultPersister.save(DefaultPersister.java:438)
	at io.ebeaninternal.server.core.DefaultServer.save(DefaultServer.java:1745)
	at io.ebeaninternal.server.core.DefaultServer.save(DefaultServer.java:1737)
	at io.ebean.Model.save(Model.java:188)
	at com.yugabyte.yw.models.PriceComponent.setPriceDetails(PriceComponent.java:75)
	at com.yugabyte.yw.models.PriceComponent.upsert(PriceComponent.java:147)
	at com.yugabyte.yw.cloud.AWSInitializer.storeInstancePriceComponent(AWSInitializer.java:360)
	at com.yugabyte.yw.cloud.AWSInitializer.storeInstancePriceComponents(AWSInitializer.java:304)
	at com.yugabyte.yw.cloud.AWSInitializer.initialize(AWSInitializer.java:103)
	at com.yugabyte.yw.commissioner.tasks.subtasks.cloud.CloudInitializer.run(CloudInitializer.java:50)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "price_component_pkey"
  Detail: Key (provider_uuid, region_code, component_code)=(ae312e46-b5c9-4e08-a251-7f7015266c8d, us-west-2, c5.24xlarge) already exists.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2284)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2003)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:200)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:424)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:161)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:133)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
	at io.ebeaninternal.server.type.DataBind.executeUpdate(DataBind.java:92)
	at io.ebeaninternal.server.persist.dml.InsertHandler.execute(InsertHandler.java:124)
	at io.ebeaninternal.server.persist.dml.DmlBeanPersister.execute(DmlBeanPersister.java:73)
	... 22 common frames omitted
2021-04-22 15:36:11,037 [ERROR] from ApiResponse in TaskPool-CloudBootstrap(ae312e46-b5c9-4e08-a251-7f7015266c8d)-3 - Hit error 500, message: {"error":"Error[ERROR: duplicate key value violates unique constraint \"price_component_pkey\"   Detail: Key (provider_uuid, region_code, component_code)=(ae312e46-b5c9-4e08-a251-7f7015266c8d, us-west-2, c5.24xlarge) already exists.]"}`

**Comment by anmalysh-yb** [comment]
Failing itest run: https://jenkins.dev.yugabyte.com/view/Test%20Jobs/job/itest/637
