### ISSUE TITLE
[Platform] Crash while creating AWS universe of disk volume type IO1 

### ISSUE THREAD

**Issue by iSignal** [yugabyte/yugabyte-db#8385]
itest reports the following failure stack while creating an AWS universe of disk volume type IO1 in 2.7.1.0-b192. The issue happens on multiple runs so it is not a temporary issue. 

The universe got created fine on portal.dev b131 though.

cc @VijiYB 

```
021-05-07 19:44:22,719 requester.py:51 ERROR testsimpleops-aws-rf3-io1 Response status: 500, response: <!DOCTYPE html>
2021-05-07 19:44:22,719 test_base.py:150 ERROR testsimpleops-aws-rf3-io1 ITEST FAILED testsimpleops-aws-rf3-io1 : RuntimeError('Failure response status code.')
```

while doing a 
```
 Doing a POST request, URL: http://35.197.8.101:80/api/customers/408b2f47-29cf-4703-8819-4015526a9763/universes, params: {'currentClusterType': 'PRIMARY', 'clusterOperation': 'CREATE'`
```

Platform application.log contains the following error

```
Caused by: java.lang.NullPointerException: null
        at com.yugabyte.yw.cloud.UniverseResourceDetails.addPrice(UniverseResourceDetails.java:143)
        at com.yugabyte.yw.cloud.UniverseResourceDetails.create(UniverseResourceDetails.java:213)
        at com.yugabyte.yw.cloud.UniverseResourceDetails.create(UniverseResourceDetails.java:162)
        at com.yugabyte.yw.controllers.UniverseController.createResp(UniverseController.java:1553)
        at com.yugabyte.yw.controllers.UniverseController.create(UniverseController.java:536)
        at v1.Routes$$anonfun$routes$1.$anonfun$applyOrElse$160(Routes.scala:3978)
        at play.core.routing.HandlerInvokerFactory$$anon$6.resultCall(HandlerInvoker.scala:143)
        at play.core.routing.HandlerInvokerFactory$$anon$6.resultCall(HandlerInvoker.scala:142)
        at play.core.routing.HandlerInvokerFactory$JavaActionInvokerFactory$$anon$3$$anon$4$$anon$5.invocation(HandlerInvoker.scala:116)
        at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:112)
        at play.http.DefaultActionCreator$1.call(DefaultActionCreator.java:33)
        at com.yugabyte.yw.controllers.TokenAuthenticator.call(TokenAuthenticator.java:123)
        at play.core.j.JavaAction.$anonfun$apply$8(JavaAction.scala:171)
        at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
        at scala.util.Success.$anonfun$map$1(Try.scala:255)
        at scala.util.Success.map(Try.scala:213)
        at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
        at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
        at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
        at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:65)
        at play.api.libs.streams.Execution$trampoline$.execute(Execution.scala:72)
        at play.core.j.HttpExecutionContext.execute(HttpExecutionContext.scala:57)
        at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:72)
        at scala.concurrent.impl.Promise$KeptPromise$Kept.onComplete(Promise.scala:372)
        at scala.concurrent.impl.Promise$KeptPromise$Kept.onComplete$(Promise.scala:371)
        at scala.concurrent.impl.Promise$KeptPromise$Successful.onComplete(Promise.scala:379)
        at scala.concurrent.impl.Promise.transform(Promise.scala:33)
        at scala.concurrent.impl.Promise.transform$(Promise.scala:31)
        at scala.concurrent.impl.Promise$KeptPromise$Successful.transform(Promise.scala:379)
        at scala.concurrent.Future.map(Future.scala:292)
        at scala.concurrent.Future.map$(Future.scala:292)
        at scala.concurrent.impl.Promise$KeptPromise$Successful.map(Promise.scala:379)
        at scala.concurrent.Future$.apply(Future.scala:659)
        at play.core.j.JavaAction.apply(JavaAction.scala:172)
        at play.api.mvc.Action.$anonfun$apply$2(Action.scala:98)
        at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
        ... 13 common frames omitted
```

**Comment by anmalysh-yb** [comment]
Discussed it with @iSignal and this one should be closed - as it was fixed by itest changes.
Will perform some enhancements on the Platform side to avoid these issues in future as part of this: https://github.com/yugabyte/yugabyte-db/issues/8406
