### ISSUE TITLE
[Platform] Adding read replica to a TLS enabled universe fails

### ISSUE THREAD

**Issue by VijiYB** [yugabyte/yugabyte-db#8399]
In 2.7.1.0 - adding a read replica cluster to an universe (which has node-node TLS/client-node TLS enabled) is failing.

Logs:
Failed to execute task {"errorString":null,"nodeExporterUser":"prometheus","deviceInfo":null,"universeUUID":"d1a584b0-b049-4c5c-914c-e15eb8d56b2a","expectedUniverseVersion":0,"cmkArn":null,"encryptionAtRestConfig":{"encr..., hit error java.lang.RuntimeException: WaitForServer(d1a584b0-b049-4c5c-914c-e15eb8d56b2a, yb-15-viji-271-may10-t1-readonly1-n1, type=TSERVER) did not respond to pings in the set time..

<img width="1079" alt="Screen Shot 2021-05-11 at 1 18 24 PM" src="https://user-images.githubusercontent.com/78048211/117879102-67500e80-b25b-11eb-87cb-002112583e76.png">

Stack trace:
2021-05-11 21:04:41,117 [ERROR] from SubTaskGroup in TaskPool-52 - Failed to execute task {"errorString":null,"nodeExporterUser":"prometheus","deviceInfo":null,"universeUUID":"ae5e0819-d79b-49d7-8f5f-99400fedffdc","expectedUniverseVersion":0,"cmkArn":null,"encryptionAtRestConfig":{"encryptionAtRestEnabled":false,"kmsConfigUUID":null,"opType":"UNDEFINED","type":"DATA_KEY"},"nodeDetailsSet":null,"communicationPorts":{"masterHttpPort":7000,"masterRpcPort":7100,"tserverHttpPort":9000,"tserverRpcPort":9100,"redisServerHttpPort":11000,"redisServerRpcPort":6379,"yqlServerHttpPort":12000,"yqlServerRpcPort":9042,"ysqlServerHttpPort":13000,"ysqlServerRpcPort":5433,"nodeExporterPort":9300},"extraDependencies":{"installNodeExporter":true},"firstTry":true,"nodeName":"yb-15-viji-271-may11-t5-readonly1-n2","serverType":"TSERVER","serverWaitTimeoutMs":120000}, hit error.
java.util.concurrent.ExecutionException: java.lang.RuntimeException: WaitForServer(ae5e0819-d79b-49d7-8f5f-99400fedffdc, yb-15-viji-271-may11-t5-readonly1-n2, type=TSERVER) did not respond to pings in the set time.
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.yugabyte.yw.commissioner.SubTaskGroup.waitFor(SubTaskGroup.java:181)
	at com.yugabyte.yw.commissioner.SubTaskGroupQueue.run(SubTaskGroupQueue.java:43)
	at com.yugabyte.yw.commissioner.tasks.ReadOnlyClusterCreate.run(ReadOnlyClusterCreate.java:140)
	at com.yugabyte.yw.commissioner.TaskRunner.run(TaskRunner.java:150)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: WaitForServer(ae5e0819-d79b-49d7-8f5f-99400fedffdc, yb-15-viji-271-may11-t5-readonly1-n2, type=TSERVER) did not respond to pings in the set time.
	at com.yugabyte.yw.commissioner.tasks.subtasks.WaitForServer.run(WaitForServer.java:53)
	... 5 common frames omitted
2021-05-11 21:04:41,117 [DEBUG] from LocalYBClientService in TaskPool-ReadOnlyClusterCreate(ae5e0819-d79b-49d7-8f5f-99400fedffdc)-8 - Closing client masters=.

**Comment by streddy-yb** [comment]
cc @Arnav15

**Comment by VijiYB** [comment]
@streddy-yb - Added 2.6 backport required to this
