### ISSUE TITLE
INDEX on column of type 'CIDR' not yet supported

### ISSUE THREAD

**Issue by vireakkeosokvibol** [yugabyte/yugabyte-db#8445]
Is index not yet support on CIDR type column?

`INDEX on column of type 'CIDR' not yet supported`

| OS Version | Yugabyte Version | DIGEST | 
| --- | --- | --- |
| Ubuntu 18.04 | Docker 2.5.3.1-b10 | 467c948cae58

**Comment by ddorian** [comment]
Hi @vireakkeosokvibol 

Can you paste the full query that you ran ?

**Comment by vireakkeosokvibol** [comment]
I was installing a maas from django application and i don't know how the query code look like because django handle all the database migration. here is the migration file that reproduce the error

https://github.com/maas/maas/blob/1aa6276c0b6d7d702f1ed3036fd11d30e879c285/src/maasserver/migrations/maasserver/0001_initial.py#L1522

**Comment by ddorian** [comment]
@vireakkeosokvibol this was your comment, correct ?

I was installing a maas from django application and i don't know how the query code look like because django handle all the database migration. here is the migration file that reproduce the error

https://github.com/maas/maas/blob/1aa6276c0b6d7d702f1ed3036fd11d30e879c285/src/maasserver/migrations/maasserver/0001_initial.py#L1522

**Comment by vireakkeosokvibol** [comment]
@ddorian  Yes it is! but unfortunately i was being in a suddently lockdown due to covid-19 so i was unable to access my work computer. So i decided to delete the comment until i beable to access my computer and start the debug.

Yes it was a script generate by django application and i was try to setup high availability for Ubuntu Maas that use postgres as database.

**Comment by ddorian** [comment]
@vireakkeosokvibol can you [print the sqlmigrations](https://stackoverflow.com/questions/62547433/prints-the-sql-for-all-migration-django) so we can see what it actually does ?

**Comment by vireakkeosokvibol** [comment]
> @vireakkeosokvibol can you [print the sqlmigrations](https://stackoverflow.com/questions/62547433/prints-the-sql-for-all-migration-django) so we can see what it actually does ?

    Operations to perform:
      Apply all migrations: auth, contenttypes, maasserver, metadataserver, piston3, sessions, sites
    Running migrations:
      Applying contenttypes.0001_initial... OK
      Applying auth.0001_initial... OK
      Applying auth.0002_auto_20151119_1629... OK
      Applying auth.0003_django_1_11_update... OK
      Applying auth.0004_user_email_allow_null... OK
      Applying auth.0005_auto_20200626_1049... OK
      Applying contenttypes.0002_remove_content_type_name... OK
      Applying piston3.0001_initial... OK
      Applying maasserver.0001_initial...Traceback (most recent call last):
      File "/snap/maas/12555/usr/lib/python3/dist-packages/django/db/backends/utils.py", line 82, in _execute
        return self.cursor.execute(sql)
    psycopg2.errors.FeatureNotSupported: INDEX on column of type 'CIDR' not yet supported
    
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "/snap/maas/12555/bin/maas-region", line 8, in <module>
        sys.exit(run())
      File "/snap/maas/12555/lib/python3.8/site-packages/maasserver/region_script.py", line 77, in run
        run_django(is_snap, is_devenv)
      File "/snap/maas/12555/lib/python3.8/site-packages/maasserver/region_script.py", line 66, in run_django
        management.execute_from_command_line()
      File "/snap/maas/12555/usr/lib/python3/dist-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
        utility.execute()
      File "/snap/maas/12555/usr/lib/python3/dist-packages/django/core/management/__init__.py", line 375, in execute
        self.fetch_command(subcommand).run_from_argv(self.argv)
      File "/snap/maas/12555/usr/lib/python3/dist-packages/django/core/management/base.py", line 323, in run_from_argv
        self.execute(*args, **cmd_options)
      File "/snap/maas/12555/usr/lib/python3/dist-packages/django/core/management/base.py", line 364, in execute
        output = self.handle(*args, **options)
      File "/snap/maas/12555/lib/python3.8/site-packages/maasserver/management/commands/dbupgrade.py", line 116, in handle
        call_command("migrate", interactive=False)
      File "/snap/maas/12555/usr/lib/python3/dist-packages/django/core/management/__init__.py", line 148, in call_command
        return command.execute(*args, **defaults)
      File "/snap/maas/12555/usr/lib/python3/dist-packages/django/core/management/base.py", line 364, in execute
        output = self.handle(*args, **options)
      File "/snap/maas/12555/usr/lib/python3/dist-packages/django/core/management/base.py", line 83, in wrapped
        res = handle_func(*args, **kwargs)
      File "/snap/maas/12555/usr/lib/python3/dist-packages/django/core/management/commands/migrate.py", line 232, in handle
        post_migrate_state = executor.migrate(
      File "/snap/maas/12555/usr/lib/python3/dist-packages/django/db/migrations/executor.py", line 117, in migrate
        state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
      File "/snap/maas/12555/usr/lib/python3/dist-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
        state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
      File "/snap/maas/12555/usr/lib/python3/dist-packages/django/db/migrations/executor.py", line 245, in apply_migration
        state = migration.apply(state, schema_editor)
      File "/snap/maas/12555/usr/lib/python3/dist-packages/django/db/migrations/migration.py", line 124, in apply
        operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
      File "/snap/maas/12555/usr/lib/python3/dist-packages/django/db/migrations/operations/models.py", line 92, in database_forwards
        schema_editor.create_model(model)
      File "/snap/maas/12555/usr/lib/python3/dist-packages/django/db/backends/base/schema.py", line 307, in create_model
        self.execute(sql, params or None)
      File "/snap/maas/12555/usr/lib/python3/dist-packages/django/db/backends/base/schema.py", line 137, in execute
        cursor.execute(sql, params)
      File "/snap/maas/12555/usr/lib/python3/dist-packages/django/db/backends/utils.py", line 67, in execute
        return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
      File "/snap/maas/12555/usr/lib/python3/dist-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
        return executor(sql, params, many, context)
      File "/snap/maas/12555/usr/lib/python3/dist-packages/django/db/backends/utils.py", line 84, in _execute
        return self.cursor.execute(sql, params)
      File "/snap/maas/12555/usr/lib/python3/dist-packages/django/db/utils.py", line 89, in __exit__
        raise dj_exc_value.with_traceback(traceback) from exc_value
      File "/snap/maas/12555/usr/lib/python3/dist-packages/django/db/backends/utils.py", line 82, in _execute
        return self.cursor.execute(sql)
    django.db.utils.NotSupportedError: INDEX on column of type 'CIDR' not yet supported




I hope this help!
