### ISSUE TITLE
[Platform] Full move on Azure universe fails

### ISSUE THREAD

**Issue by VijiYB** [yugabyte/yugabyte-db#8449]
Tried a full move from instance type D2s_v3 to D2s_v4 but it failed while provisioning

Failed to execute task {"errorString":null,"nodeExporterUser":"prometheus","deviceInfo":{"volumeSize":250,"numVolumes":1,"diskIops":null,"throughput":null,"storageClass":"standard","mountPoints":null,"storageType":"Premi..., hit error java.lang.RuntimeException: 2021-05-14 06:44:44,221 INFO validate_credentials:cloud.py:95: Found azu cloud credentials in env.
2021-05-14 06:44:44,574 INFO create_or_update_instance:cloud.py:89: [app] Creating/Updating Azure VM yb-15-viji-271-azure-t4-n4 in eastus2/3.
2021-05-14 06:47:09,876 INFO create_or_update_instance:cloud.py:114: [app] Updated Azure VM yb-15-viji-271-azure-t4-n4.
2021-05-14 06:47:09,876 INFO wait_for_host:method.py:309: Waiting for instance yb-15-viji-271-azure-t4-n4
Traceback (most recent call last):
  File "/opt/yugabyte/devops/python_virtual_env/bin/ybcloud.py", line 4, in <module>
    __import__('pkg_resources').run_script('ybops==0.4', 'ybcloud.py')
  File "/opt/yugabyte/devops/python_virtual_env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/opt/yugabyte/devops/python_virtual_env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1462, in run_script
    exec(code, namespace, namespace)
  File "/opt/yugabyte/devops/python_virtual_env/lib/python2.7/site-packages/ybops-0.4-py2.7.egg/EGG-INFO/scripts/ybcloud.py", line 15, in <module>
    YbCloud().run()
  File "/opt/yugabyte/devops/python_virtual_env/lib/python2.7/site-packages/ybops-0.4-py2.7.egg/ybops/cloud/ybcloud.py", line 56, in run
    self.options.func(self.options)
  File "/opt/yugabyte/devops/python_virtual_env/lib/python2.7/site-packages/ybops-0.4-py2.7.egg/ybops/cloud/common/method.py", line 77, in callback_wrapper
    self.callback(args)
  File "/opt/yugabyte/devops/python_virtual_env/lib/python2.7/site-packages/ybops-0.4-py2.7.egg/ybops/cloud/azure/method.py", line 79, in callback
    super(AzureProvisionInstancesMethod, self).callback(args)
  File "/opt/yugabyte/devops/python_virtual_env/lib/python2.7/site-packages/ybops-0.4-py2.7.egg/ybops/cloud/common/method.py", line 387, in callback
    self.create_method.callback(args)
  File "/opt/yugabyte/devops/python_virtual....

**Comment by streddy-yb** [comment]
There shouldn't be Azure specific full move logic. Good to check why this is failing.

**Comment by shashwat-yb** [comment]
Created a 3 node universe in instance(Standard_D2as) and the applied full move with instance(Standard_B8ms).
2/3 nodes were created in the underlying  console but it fails after that.

**Comment by VijiYB** [comment]
@WesleyW -  Can you please check why the full move on Azure universe is failing. Observed this in 2.6. Please check as Azure will be GA release for 2.6.
