### ISSUE TITLE
[Platform] Backup stays in the 'InProcess' state if the task failed with 'UserUniverse ... is already being updated' exception

### ISSUE THREAD

**Issue by SergeyPotachev** [yugabyte/yugabyte-db#8456]
The log is below (some lines were removed from the log):

2021-05-14 06:14:03,777 [INFO] from TaskRunner in TaskPool-161 - Updating task [taskType : BackupUniverse, taskState: Created] to new state Running
2021-05-14 06:14:03,778 [INFO] from Scheduler in application-akka.actor.default-dispatcher-7065 - Submitted task to backup table cfd14aef-46e2-4cd0-a235-5fc9980d9c70:cassandrakeyvalue, task uuid = 9dfcd839-8b88-4627-8492-ebfe35d740e5.
2021-05-14 06:14:03,782 [INFO] from Scheduler in application-akka.actor.default-dispatcher-7065 - Saved task uuid 9dfcd839-8b88-4627-8492-ebfe35d740e5 in customer tasks table for table cfd14aef-46e2-4cd0-a235-5fc9980d9c70:ybdemo_keyspace.cassandrakeyvalue
2021-05-14 06:14:03,805 [DEBUG] from SetUniverseKey in application-akka.actor.default-dispatcher-6844 - Setting universe encryption key for universe db365ae5-54bb-4545-91bd-e7db28bb3ee6
2021-05-14 06:14:03,823 [DEBUG] from EncryptionAtRestUtil in application-akka.actor.default-dispatcher-6844 - Retrieving universe key cache entry for universe db365ae5-54bb-4545-91bd-e7db28bb3ee6 and keyRef AQIDAHjuWDjDdqqLE829cjWMt2LAJIXQ5d05lojXg5OrCPNLyAEPwDQwwP0sW3O9x
D/+z6SjAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMVMaBX52lG+GEi73GAgEQgDtvNxdRTYMll6vckWgdaROIxPVqpeSB6vpOEBuw35SQuqqYEkytxixbn8CVF3QQEvBuV24Gfq5jtiUI4w==
2021-05-14 06:14:03,886 [DEBUG] from UniverseTaskBase in TaskPool-160 - Updated cluster config version from 77 to 78
2021-05-14 06:14:03,913 [INFO] from MultiTableBackup in TaskPool-160 - Queuing backup for table postgres:postgresqlkeyvalue
2021-05-14 06:14:03,914 [INFO] from MultiTableBackup in TaskPool-160 - Skipping keyspace/universe backup of table cfd14aef-46e2-4cd0-a235-5fc9980d9c70. Expected keyspace is postgres; actual keyspace is ybdemo_keyspace
2021-05-14 06:14:03,946 [DEBUG] from UniverseTaskBase in TaskPool-161 - Updated cluster config version from 78 to 79
2021-05-14 06:14:03,948 [ERROR] from UniverseTaskBase in TaskPool-161 - UserUniverse 9335fd05-0d22-4d7f-a760-337c2101cc64 is already being updated.
2021-05-14 06:14:03,948 [DEBUG] from Universe in TaskPool-161 - Error running universe updater
java.lang.RuntimeException: UserUniverse 9335fd05-0d22-4d7f-a760-337c2101cc64 is already being updated.
        at com.yugabyte.yw.commissioner.tasks.UniverseTaskBase$1.run(UniverseTaskBase.java:79)
        at com.yugabyte.yw.models.Universe.readModifyWrite(Universe.java:335)
        at com.yugabyte.yw.models.Universe.saveDetails(Universe.java:367)
        at com.yugabyte.yw.commissioner.tasks.UniverseTaskBase.saveUniverseDetails(UniverseTaskBase.java:1432)
        at com.yugabyte.yw.commissioner.tasks.UniverseTaskBase.saveUniverseDetails(UniverseTaskBase.java:1436)
        at com.yugabyte.yw.commissioner.tasks.UniverseTaskBase.lockUniverseForUpdate(UniverseTaskBase.java:109)
        at com.yugabyte.yw.commissioner.tasks.UniverseTaskBase.lockUniverse(UniverseTaskBase.java:264)
        at com.yugabyte.yw.commissioner.tasks.BackupUniverse.run(BackupUniverse.java:47)
        at com.yugabyte.yw.commissioner.TaskRunner.run(TaskRunner.java:150)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2021-05-14 06:14:03,952 [DEBUG] from SetUniverseKey in application-akka.actor.default-dispatcher-6844 - Setting universe encryption key for universe dfc7c510-4989-43f0-be20-19bc896c9762
2021-05-14 06:14:03,956 [DEBUG] from EncryptionAtRestUtil in application-akka.actor.default-dispatcher-6844 - Retrieving universe key cache entry for universe dfc7c510-4989-43f0-be20-19bc896c9762 and keyRef AQIDAHjuWDjDdqqLE829cjWMt2LAJIXQ5d05lojXg5OrCPNLyAEOEkUUbSJlAmvxT
bFlculCAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMGH5nZ8RYcSCuXdC0AgEQgDsVTk8Fnp5u9xEVFLTmm9KPyuvtCfQOj4cmcEejd285a1sVghKpRZjtLNMsa3AtnkiA9mLPN47DrjkXrg==
2021-05-14 06:14:03,959 [ERROR] from BackupUniverse in TaskPool-161 - Error executing task BackupUniverse(9335fd05-0d22-4d7f-a760-337c2101cc64) with error='UserUniverse 9335fd05-0d22-4d7f-a760-337c2101cc64 is already being updated.'.
java.lang.RuntimeException: UserUniverse 9335fd05-0d22-4d7f-a760-337c2101cc64 is already being updated.
        at com.yugabyte.yw.commissioner.tasks.UniverseTaskBase$1.run(UniverseTaskBase.java:79)
        at com.yugabyte.yw.models.Universe.readModifyWrite(Universe.java:335)
        at com.yugabyte.yw.models.Universe.saveDetails(Universe.java:367)
        at com.yugabyte.yw.commissioner.tasks.UniverseTaskBase.saveUniverseDetails(UniverseTaskBase.java:1432)
        at com.yugabyte.yw.commissioner.tasks.UniverseTaskBase.saveUniverseDetails(UniverseTaskBase.java:1436)
        at com.yugabyte.yw.commissioner.tasks.UniverseTaskBase.lockUniverseForUpdate(UniverseTaskBase.java:109)
        at com.yugabyte.yw.commissioner.tasks.UniverseTaskBase.lockUniverse(UniverseTaskBase.java:264)
        at com.yugabyte.yw.commissioner.tasks.BackupUniverse.run(BackupUniverse.java:47)
        at com.yugabyte.yw.commissioner.TaskRunner.run(TaskRunner.java:150)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

2021-05-14 06:14:03,959 [WARN] from UniverseTaskBase in TaskPool-161 - Unlock universe called when it was not locked.
2021-05-14 06:14:04,004 [DEBUG] from UniverseTaskBase in TaskPool-160 - Updated cluster config version from 79 to 80
2021-05-14 06:14:04,018 [INFO] from MultiTableBackup in TaskPool-160 - Successfully started scheduled backup of tables.
2021-05-14 06:14:04,020 [INFO] from SubTaskGroup in TaskPool-160 - Adding task #0: BackupUniverseKeys
2021-05-14 06:14:04,021 [DEBUG] from SubTaskGroup in TaskPool-160 - Details for task #0: BackupUniverseKeys : details={"errorString":null,"nodeExporterUser":"prometheus","deviceInfo":null,"universeUUID":"9335fd05-0d22-4d7f-a760-337c2101cc64","expectedUniverseVersion":0,"c
mkArn":null,"encryptionAtRestConfig":{"encryptionAtRestEnabled":false,"kmsConfigUUID":null,"opType":"UNDEFINED","type":"DATA_KEY"},"nodeDetailsSet":null,"communicationPorts":{"masterHttpPort":7000,"masterRpcPort":7100,"tserverHttpPort":9000,"tserverRpcPort":9100,"redisSer
verHttpPort":11000,"redisServerRpcPort":6379,"yqlServerHttpPort":12000,"yqlServerRpcPort":9042,"ysqlServerHttpPort":13000,"ysqlServerRpcPort":5433,"nodeExporterPort":9300},"extraDependencies":{"installNodeExporter":true},"firstTry":true,"keyspace":"postgres","tableName":n
ull,"tableUUID":null,"sse":false,"storageConfigUUID":"c045b0bb-f154-4198-9d6e-2dfb95c633e4","kmsConfigUUID":null,"storageLocation":"s3://backups.yugabyte.com/portal/univ-9335fd05-0d22-4d7f-a760-337c2101cc64/backup-2021-05-14T06:14:04-1382973396/keyspace-postgres","actionT
ype":"CREATE","backupType":"PGSQL_TABLE_TYPE","tableNameList":null,"tableUUIDList":null,"backupList":null,"schedulingFrequency":0,"cronExpression":null,"timeBeforeDelete":43200000,"enableVerboseLogs":false,"transactionalBackup":false,"parallelism":8,"scheduleUUID":"882609
52-0752-4c91-922d-7ed160d25fdc"}
2021-05-14 06:14:04,026 [INFO] from SubTaskGroup in TaskPool-160 - Adding task #0: BackupTable
2021-05-14 06:14:04,026 [DEBUG] from SubTaskGroup in TaskPool-160 - Details for task #0: BackupTable : details={"errorString":null,"nodeExporterUser":"prometheus","deviceInfo":null,"universeUUID":"9335fd05-0d22-4d7f-a760-337c2101cc64","expectedUniverseVersion":0,"cmkArn":
null,"encryptionAtRestConfig":{"encryptionAtRestEnabled":false,"kmsConfigUUID":null,"opType":"UNDEFINED","type":"DATA_KEY"},"nodeDetailsSet":null,"communicationPorts":{"masterHttpPort":7000,"masterRpcPort":7100,"tserverHttpPort":9000,"tserverRpcPort":9100,"redisServerHttp
Port":11000,"redisServerRpcPort":6379,"yqlServerHttpPort":12000,"yqlServerRpcPort":9042,"ysqlServerHttpPort":13000,"ysqlServerRpcPort":5433,"nodeExporterPort":9300},"extraDependencies":{"installNodeExporter":true},"firstTry":true,"keyspace":"postgres","tableName":null,"ta
bleUUID":null,"sse":false,"storageConfigUUID":"c045b0bb-f154-4198-9d6e-2dfb95c633e4","kmsConfigUUID":null,"storageLocation":"s3://backups.yugabyte.com/portal/univ-9335fd05-0d22-4d7f-a760-337c2101cc64/backup-2021-05-14T06:14:04-1382973396/keyspace-postgres","actionType":"C
REATE","backupType":"PGSQL_TABLE_TYPE","tableNameList":null,"tableUUIDList":null,"backupList":null,"schedulingFrequency":0,"cronExpression":null,"timeBeforeDelete":43200000,"enableVerboseLogs":false,"transactionalBackup":false,"parallelism":8,"scheduleUUID":"88260952-0752
-4c91-922d-7ed160d25fdc"}
2021-05-14 06:14:04,035 [INFO] from SubTaskGroup in TaskPool-160 - Adding task #0: UniverseUpdateSucceeded(9335fd05-0d22-4d7f-a760-337c2101cc64)(9335fd05-0d22-4d7f-a760-337c2101cc64)
2021-05-14 06:14:04,036 [DEBUG] from SubTaskGroup in TaskPool-160 - Details for task #0: UniverseUpdateSucceeded(9335fd05-0d22-4d7f-a760-337c2101cc64)(9335fd05-0d22-4d7f-a760-337c2101cc64) : details={"errorString":null,"nodeExporterUser":"prometheus","deviceInfo":null,"un
iverseUUID":"9335fd05-0d22-4d7f-a760-337c2101cc64","expectedUniverseVersion":0,"cmkArn":null,"encryptionAtRestConfig":{"encryptionAtRestEnabled":false,"kmsConfigUUID":null,"opType":"UNDEFINED","type":"DATA_KEY"},"nodeDetailsSet":null,"communicationPorts":{"masterHttpPort"
:7000,"masterRpcPort":7100,"tserverHttpPort":9000,"tserverRpcPort":9100,"redisServerHttpPort":11000,"redisServerRpcPort":6379,"yqlServerHttpPort":12000,"yqlServerRpcPort":9042,"ysqlServerHttpPort":13000,"ysqlServerRpcPort":5433,"nodeExporterPort":9300},"extraDependencies"
:{"installNodeExporter":true},"firstTry":true}
2021-05-14 06:14:04,040 [DEBUG] from SetUniverseKey in application-akka.actor.default-dispatcher-6844 - Setting universe encryption key for universe 4ffc24fb-4c46-48ba-9538-6e3b818e6b48
2021-05-14 06:14:04,040 [DEBUG] from UniverseTaskBase in TaskPool-161 - Updated cluster config version from 80 to 81
2021-05-14 06:14:04,043 [DEBUG] from EncryptionAtRestUtil in application-akka.actor.default-dispatcher-6844 - Retrieving universe key cache entry for universe 4ffc24fb-4c46-48ba-9538-6e3b818e6b48 and keyRef AQIDAHjuWDjDdqqLE829cjWMt2LAJIXQ5d05lojXg5OrCPNLyAFYZzHOSlEAwt7pQ74q43OqAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMMNkXYANSoLREY0KzAgEQgDvTgCyXgOtSA2weouEqs91YHiyuQS/VZE9yORS3ZiLE4GVm8JGWfa1eITw+v31z8Wn2F/VQJCE7gJVJDw==
2021-05-14 06:14:04,053 [ERROR] from TaskRunner in TaskPool-161 - Error running task
java.lang.RuntimeException: UserUniverse 9335fd05-0d22-4d7f-a760-337c2101cc64 is already being updated.
        at com.yugabyte.yw.commissioner.tasks.UniverseTaskBase$1.run(UniverseTaskBase.java:79)
        at com.yugabyte.yw.models.Universe.readModifyWrite(Universe.java:335)
        at com.yugabyte.yw.models.Universe.saveDetails(Universe.java:367)
        at com.yugabyte.yw.commissioner.tasks.UniverseTaskBase.saveUniverseDetails(UniverseTaskBase.java:1432)
        at com.yugabyte.yw.commissioner.tasks.UniverseTaskBase.saveUniverseDetails(UniverseTaskBase.java:1436)
        at com.yugabyte.yw.commissioner.tasks.UniverseTaskBase.lockUniverseForUpdate(UniverseTaskBase.java:109)
        at com.yugabyte.yw.commissioner.tasks.UniverseTaskBase.lockUniverse(UniverseTaskBase.java:264)
        at com.yugabyte.yw.commissioner.tasks.BackupUniverse.run(BackupUniverse.java:47)
        at com.yugabyte.yw.commissioner.TaskRunner.run(TaskRunner.java:150)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2021-05-14 06:14:04,071 [INFO] from TaskRunner in TaskPool-161 - Updating task [taskType : BackupUniverse, taskState: Running] to new state Failure

**Comment by SergeyPotachev** [comment]
![Screenshot 2021-05-14 at 21 37 17](https://user-images.githubusercontent.com/70904578/118314303-a18c0b00-b4fc-11eb-90e4-94e9723c8b98.png)

**Comment by SergeyPotachev** [comment]
Comments from @VijiYB:

"YCQL backup is Inprogress state for ~12hrs now in this universe - http://....../universes/9335fd05-0d22-4d7f-a760-337c2101cc64/backups
This was a scheduled backup that I started(with freq 3mins)  but seeing the inprocess for the first few backups, I deleted the schedule, but looks like it never ended."

**Comment by SergeyPotachev** [comment]
From logs also I see that earlier for the same universe MultiTableBackup was started and was still in process.
So the scenario is:
- Create a backup schedule with the high frequency (from the test scenario it were 3 minutes);
- Start MultiTableBackup with long duration (much more than 3 minutes);
- Observe appeared backups.
All failed backups remain in the `InProcess` state.

**Comment by streddy-yb** [comment]
In realty, customers will not schedule backups at such high frequency but you can always run into such scenarios when you're dealing with large databases where a single backup tasks can take a longtime. We should make the default behavior for these scenarios more graceful. For example, do not run a backup task if one is already running and also do not schedule more than one instance of the backup task for the same universe.

**Comment by streddy-yb** [comment]
@Arnav15 - I thought we don't schedule backups if one is already done. Has something changed recently?

cc @kkg-yb
