### ISSUE TITLE
exception/error message better be more meaningful for developers to find and solve the error

### ISSUE THREAD

**Issue by patrick-li** [YugaByte/yugabyte-db#851]
1) attach the original query.
2) point out a few possible directions for developers to look into it.

{ NoHostAvailableError: All host(s) tried for query failed. First host tried, 10.240.87.28:9042: OperationTimedOutError: The host 10.240.87.28:9042 did not reply before timeout 12000 ms. See innerErrors.

        at Function.borrowNextConnection (/data/reports/node_modules/cassandra-driver/lib/request-handler.js:54:23)

        at RequestHandler.getNextConnection (/data/reports/node_modules/cassandra-driver/lib/request-handler.js:144:20)

        at RequestExecution.start (/data/reports/node_modules/cassandra-driver/lib/request-execution.js:41:18)

        at RequestExecution._retry (/data/reports/node_modules/cassandra-driver/lib/request-execution.js:207:10)

        at RequestExecution._handleError (/data/reports/node_modules/cassandra-driver/lib/request-execution.js:132:17)

        at responseCb (/data/reports/node_modules/cassandra-driver/lib/request-execution.js:68:23)

        at OperationState._swapCallbackAndInvoke (/data/reports/node_modules/cassandra-driver/lib/operation-state.js:145:5)

        at OperationState._markAsTimedOut (/data/reports/node_modules/cassandra-driver/lib/operation-state.js:119:10)

        at Timeout.requestTimedOut (/data/reports/node_modules/cassandra-driver/lib/operation-state.js:93:12)

        at Timeout.wrappedCallback (/data/reports/node_modules/newrelic/lib/transaction/tracer/index.js:352:23)

        at Timeout.wrapped (/data/reports/node_modules/newrelic/lib/transaction/tracer/index.js:181:22)

        at Timeout.wrappedCallback (/data/reports/node_modules/newrelic/lib/transaction/tracer/index.js:443:66)

        at Timeout.wrapped [as _onTimeout] (/data/reports/node_modules/newrelic/lib/transaction/tracer/index.js:181:22)

        at ontimeout (timers.js:498:11)

        at tryOnTimeout (timers.js:323:5)

        at Timer.listOnTimeout (timers.js:290:5)

      name: 'NoHostAvailableError',

      info: 'Represents an error when a query cannot be performed because no host is available or could be reached by the driver.',

      message: 'All host(s) tried for query failed. First host tried, 10.240.87.28:9042: OperationTimedOutError: The host 10.240.87.28:9042 did not reply before timeout 12000 ms. See innerErrors.',

      innerErrors: 

       { '10.240.87.28:9042': 

          { OperationTimedOutError: The host 10.240.87.28:9042 did not reply before timeout 12000 ms

        at Timeout.requestTimedOut (/data/reports/node_modules/cassandra-driver/lib/operation-state.js:93:28)

        at Timeout.wrappedCallback (/data/reports/node_modules/newrelic/lib/transaction/tracer/index.js:352:23)

        at Timeout.wrapped (/data/reports/node_modules/newrelic/lib/transaction/tracer/index.js:181:22)

        at Timeout.wrappedCallback (/data/reports/node_modules/newrelic/lib/transaction/tracer/index.js:443:66)

        at Timeout.wrapped [as _onTimeout] (/data/reports/node_modules/newrelic/lib/transaction/tracer/index.js:181:22)

        at ontimeout (timers.js:498:11)

        at tryOnTimeout (timers.js:323:5)

        at Timer.listOnTimeout (timers.js:290:5)

            name: 'OperationTimedOutError',

            info: 'Represents a client-side error that is raised when the client did not hear back from the server within socketOptions.readTimeout',

            message: 'The host 10.240.87.28:9042 did not reply before timeout 12000 ms',

            coordinator: '10.240.87.28:9042' },

         '10.240.72.136:9042': 

          { OperationTimedOutError: The host 10.240.72.136:9042 did not reply before timeout 12000 ms

        at Timeout.requestTimedOut (/data/reports/node_modules/cassandra-driver/lib/operation-state.js:93:28)

        at Timeout.wrappedCallback (/data/reports/node_modules/newrelic/lib/transaction/tracer/index.js:352:23)

        at Timeout.wrapped (/data/reports/node_modules/newrelic/lib/transaction/tracer/index.js:181:22)

        at Timeout.wrappedCallback (/data/reports/node_modules/newrelic/lib/transaction/tracer/index.js:443:66)

        at Timeout.wrapped [as _onTimeout] (/data/reports/node_modules/newrelic/lib/transaction/tracer/index.js:181:22)

        at ontimeout (timers.js:498:11)

        at tryOnTimeout (timers.js:323:5)

        at Timer.listOnTimeout (timers.js:290:5)

            name: 'OperationTimedOutError',

            info: 'Represents a client-side error that is raised when the client did not hear back from the server within socketOptions.readTimeout',

            message: 'The host 10.240.72.136:9042 did not reply before timeout 12000 ms',

            coordinator: '10.240.72.136:9042' },

         '10.240.54.93:9042': 

          { OperationTimedOutError: The host 10.240.54.93:9042 did not reply before timeout 12000 ms

        at Timeout.requestTimedOut (/data/reports/node_modules/cassandra-driver/lib/operation-state.js:93:28)

        at Timeout.wrappedCallback (/data/reports/node_modules/newrelic/lib/transaction/tracer/index.js:352:23)

        at Timeout.wrapped (/data/reports/node_modules/newrelic/lib/transaction/tracer/index.js:181:22)

        at Timeout.wrappedCallback (/data/reports/node_modules/newrelic/lib/transaction/tracer/index.js:443:66)

        at Timeout.wrapped [as _onTimeout] (/data/reports/node_modules/newrelic/lib/transaction/tracer/index.js:181:22)

        at ontimeout (timers.js:498:11)

        at tryOnTimeout (timers.js:323:5)

        at Timer.listOnTimeout (timers.js:290:5)

            name: 'OperationTimedOutError',

            info: 'Represents a client-side error that is raised when the client did not hear back from the server within socketOptions.readTimeout',

            message: 'The host 10.240.54.93:9042 did not reply before timeout 12000 ms',

            coordinator: '10.240.54.93:9042' } } }

**Comment by ravimurthy** [comment]
In case of a query error due to timeout, we should return the query text & suggest potential reasons for timeout such as not including a partition key in the query..
