### ISSUE TITLE
[Platform] [Unit Test] SessionControllerTest.testProxyRequestValid fails

### ISSUE THREAD

**Issue by sb-yb** [yugabyte/yugabyte-db#8514]
```
[info] Test com.yugabyte.yw.controllers.SessionControllerTest.testProxyRequestValid started
2021-05-18 19:41:37.623 [info] HikariCPModule.scala:54 [pool-1-thread-1] Creating Pool for datasource 'default'
2021-05-18 19:41:37.674 [info] ScopedRuntimeConfig.java:54 [pool-1-thread-1] Created Global ScopedRuntimeConfig
2021-05-18 19:41:37.847 [info] YWErrorHandler.java:39 [pool-1-thread-1] Created YWErrorHandler
2021-05-18 19:41:37.852 [warn] ParameterMessageInterpolator.java:28 [pool-1-thread-1] HV000184: ParameterMessageInterpolator has been chosen, EL interpolation will not be supported
2021-05-18 19:41:37.853 [info] CloudAPI.java:24 [pool-1-thread-1] Created cloud API factory for [aws]
2021-05-18 19:41:37.853 [info] Commissioner.java:69 [pool-1-thread-1] Started Commissioner TaskPool.
2021-05-18 19:41:37.854 [info] Commissioner.java:75 [pool-1-thread-1] Started TaskProgressMonitor thread.
2021-05-18 19:41:37.856 [info] AppInit.java:44 [pool-1-thread-1] Yugaware Application has started
2021-05-18 19:41:37.917 [info] Universe.java:230 [pool-1-thread-1] Created db entry for universe Test Universe [8608647e-7608-42a7-88a4-12529c618122]
2021-05-18 19:41:37.918 [info] PlacementInfoUtil.java:1964 [pool-1-thread-1] numRegions=1, numAzsInRegions=3, zonesIntended=3
2021-05-18 19:41:37.918 [info] PlacementInfoUtil.java:2077 [pool-1-thread-1] Incrementing RF for PlacementAZ-1 to: 1
2021-05-18 19:41:37.919 [info] PlacementInfoUtil.java:2079 [pool-1-thread-1] Number of nodes in PlacementAZ-1: 1
2021-05-18 19:41:37.919 [info] PlacementInfoUtil.java:2077 [pool-1-thread-1] Incrementing RF for PlacementAZ-2 to: 1
2021-05-18 19:41:37.919 [info] PlacementInfoUtil.java:2079 [pool-1-thread-1] Number of nodes in PlacementAZ-2: 1
2021-05-18 19:41:37.919 [info] PlacementInfoUtil.java:2077 [pool-1-thread-1] Incrementing RF for PlacementAZ-3 to: 1
2021-05-18 19:41:37.919 [info] PlacementInfoUtil.java:2079 [pool-1-thread-1] Number of nodes in PlacementAZ-3: 1
2021-05-18 19:41:37.936 [error] ApiResponse.java:23 [application-akka.actor.default-dispatcher-4] Hit error 500, message: {"error":"No configuration setting found for key 'yb.proxy_endpoint_timeout'"}
2021-05-18 19:41:37.956 [info] HikariCPModule.scala:79 [application-akka.actor.default-dispatcher-3] Shutting down connection pool.
[error] Test com.yugabyte.yw.controllers.SessionControllerTest.testProxyRequestValid failed: java.lang.AssertionError:
[error] Expected: (not null and a string containing "\"java.net.UnknownHostException: host-n1:")
[error]      but: a string containing "\"java.net.UnknownHostException: host-n1:" was ""No configuration setting found for key 'yb.proxy_endpoint_timeout'"", took 0.373 sec
[error]     at com.yugabyte.yw.common.AssertHelper.assertErrorResponse(AssertHelper.java:54)
[error]     at com.yugabyte.yw.common.AssertHelper.assertInternalServerError(AssertHelper.java:33)
[error]     at com.yugabyte.yw.controllers.SessionControllerTest.testProxyRequestValid(SessionControllerTest.java:573)
[error]     ...
```

**Comment by sb-yb** [comment]
Fix out for review https://phabricator.dev.yugabyte.com/D11643
