### ISSUE TITLE
[Platform] Audit migration failed on AWS portal

### ISSUE THREAD

**Issue by anmalysh-yb** [yugabyte/yugabyte-db#8525]
Most probably because audit payload was not properly escaped

Migration was introduced here: https://github.com/yugabyte/yugabyte-db/issues/8051

**Comment by SergeyPotachev** [comment]
```
2021-05-19 16:26:40.156 [info] HealthChecker.java:289 [application-akka.actor.default-dispatcher-5] Skipping customer 48ce7be9-08eb-4c72-a323-1408d7a23705 due to missing alerting config...
	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:554)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:188)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:111)
	at com.google.inject.Guice.createInjector(Guice.java:87)
	at com.google.inject.Guice.createInjector(Guice.java:78)
	at play.api.inject.guice.GuiceBuilder.injector(GuiceInjectorBuilder.scala:201)
	at play.api.inject.guice.GuiceApplicationBuilder.build(GuiceApplicationBuilder.scala:155)
	at play.api.inject.guice.GuiceApplicationLoader.load(GuiceApplicationLoader.scala:26)
	at play.core.server.ProdServerStart$.start(ProdServerStart.scala:54)
	at play.core.server.ProdServerStart$.main(ProdServerStart.scala:28)
	at play.core.server.ProdServerStart.main(ProdServerStart.scala)
Caused by: org.flywaydb.core.api.FlywayException: Migration failed !
	at org.flywaydb.core.internal.resolver.jdbc.JdbcMigrationExecutor.execute(JdbcMigrationExecutor.java:47)
	at org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:343)
	at org.flywaydb.core.internal.command.DbMigrate.access$900(DbMigrate.java:53)
	at org.flywaydb.core.internal.command.DbMigrate$4.call(DbMigrate.java:276)
	at org.flywaydb.core.internal.util.jdbc.TransactionTemplate.execute(TransactionTemplate.java:75)
	at org.flywaydb.core.internal.command.DbMigrate.applyMigrations(DbMigrate.java:273)
	at org.flywaydb.core.internal.command.DbMigrate.access$800(DbMigrate.java:53)
	at org.flywaydb.core.internal.command.DbMigrate$2.call(DbMigrate.java:210)
	at org.flywaydb.core.internal.command.DbMigrate$2.call(DbMigrate.java:146)
	at org.flywaydb.core.internal.dbsupport.postgresql.PostgreSQLAdvisoryLockTemplate.execute(PostgreSQLAdvisoryLockTemplate.java:68)
	at org.flywaydb.core.internal.dbsupport.postgresql.PostgreSQLDbSupport.lock(PostgreSQLDbSupport.java:162)
	at org.flywaydb.core.internal.metadatatable.MetaDataTableImpl.lock(MetaDataTableImpl.java:174)
	at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:146)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:1010)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:971)
	at org.flywaydb.core.Flyway.execute(Flyway.java:1464)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:971)
	at org.flywaydb.play.PlayInitializer.$anonfun$migrateAutomatically$1(PlayInitializer.scala:156)
	at org.flywaydb.play.PlayInitializer.$anonfun$migrateAutomatically$1$adapted(PlayInitializer.scala:155)
	at scala.Option.foreach(Option.scala:407)
	at org.flywaydb.play.PlayInitializer.migrateAutomatically(PlayInitializer.scala:155)
	at org.flywaydb.play.PlayInitializer.$anonfun$onStart$1(PlayInitializer.scala:147)
	at org.flywaydb.play.PlayInitializer.$anonfun$onStart$1$adapted(PlayInitializer.scala:145)
	at scala.collection.Iterator.foreach(Iterator.scala:941)
	at scala.collection.Iterator.foreach$(Iterator.scala:941)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
	at scala.collection.MapLike$DefaultKeySet.foreach(MapLike.scala:181)
	at org.flywaydb.play.PlayInitializer.onStart(PlayInitializer.scala:145)
	at org.flywaydb.play.PlayInitializer.<init>(PlayInitializer.scala:164)
	at org.flywaydb.play.PlayInitializer$$FastClassByGuice$$fd53e8fe.newInstance(<generated>)
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
	at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:213)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:184)
	... 9 more
Caused by: org.postgresql.util.PSQLException: ERROR: syntax error at or near "?"
  Position: 1766
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2284)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2003)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:200)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:424)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:321)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:313)
	at db.migration.default.common.R__Redact_Secrets_From_Audit.migrate(R__Redact_Secrets_From_Audit.scala:29)
```

Failed migration is **R__Redact_Secrets_From_Audit**.

**Comment by shashwat-yb** [comment]
Validated this issue in the 2.6 portal. Checked that no sensitive information is exposed in the audit table (issue raised in #8051) by connecting to the platform database through the following procedures -
1)ssh -i ~/.yugabyte/yb-dev-aws-2.pem centos@portal2.6.dev.yugabyte.com
2)psql -d yugaware -U postgres
3)select payload from audit;
and then verified that no (Audit migration failed on AWS portal) error is present in the logs.

cc @VijiYB
