### ISSUE TITLE
Crashes and false-positive OOMs with gperftools 2.8

### ISSUE THREAD

**Issue by tvesely** [yugabyte/yugabyte-db#8531]
We have been tracking a number of crashes/OOM issues like the following:

```	
	(gdb) bt
#0  0x00007f31b17da0a7 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007f31b17db4aa in __GI_abort () at abort.c:89
#2  0x00007f31b29135cd in __gnu_cxx::__verbose_terminate_handler() () from /data/yb/yb-software/yugabyte-2.5.3.1-b10-centos-x86_64/linuxbrew/lib/libstdc++.so.6
#3  0x00007f31b2911636 in ?? () from /data/yb/yb-software/yugabyte-2.5.3.1-b10-centos-x86_64/linuxbrew/lib/libstdc++.so.6
#4  0x00007f31b2911681 in std::terminate() () from /data/yb/yb-software/yugabyte-2.5.3.1-b10-centos-x86_64/linuxbrew/lib/libstdc++.so.6
#5  0x00007f31b2911898 in __cxa_throw () from /data/yb/yb-software/yugabyte-2.5.3.1-b10-centos-x86_64/linuxbrew/lib/libstdc++.so.6
#6  0x00007f31b6446fbb in (anonymous namespace)::handle_oom(void* (*)(void*), void*, bool, bool) () from /data/yb/yb-software/yugabyte-2.5.3.1-b10-centos-x86_64/lib/yb-thirdparty/libtcmalloc.so.4
#7  0x00007f31b6467c02 in tcmalloc::allocate_full_cpp_throw_oom(unsigned long) () from /data/yb/yb-software/yugabyte-2.5.3.1-b10-centos-x86_64/lib/yb-thirdparty/libtcmalloc.so.4
#8  0x00007f31bfef9a10 in yb::log::ReadableLogSegment::ScanForValidEntryHeaders (this=this@entry=0xcb4bce10, offset=591, has_valid_entries=has_valid_entries@entry=0x7f319f19e350) at ../../src/yb/consensus/log_util.cc:615
#9  0x00007f31bff0027f in yb::log::ReadableLogSegment::ReadEntries (this=this@entry=0xcb4bce10, max_entries_to_read=max_entries_to_read@entry=9223372036854775807) at ../../src/yb/consensus/log_util.cc:524
#10 0x00007f31bff00856 in yb::log::ReadableLogSegment::RebuildFooterByScanning (this=0xcb4bce10) at ../../src/yb/consensus/log_util.cc:242
#11 0x00007f31bff1f31d in yb::log::LogReader::Init (this=this@entry=0x15b480a0, tablet_wal_path=...) at ../../src/yb/consensus/log_reader.cc:186
#12 0x00007f31bff1ff30 in yb::log::LogReader::Open (env=0x1dbd8d0, index=..., tablet_id=..., tablet_wal_path=..., peer_uuid=..., metric_entity=..., reader=0x15fac3160) at ../../src/yb/consensus/log_reader.cc:119
#13 0x00007f31bff0cced in yb::log::Log::Init (this=this@entry=0x15fac2f00) at ../../src/yb/consensus/log.cc:544
#14 0x00007f31bff0d669 in yb::log::Log::Open (options=..., tablet_id=..., wal_dir=..., peer_uuid=..., schema=..., schema_version=0, metric_entity=..., append_thread_pool=0x1e6d600, allocation_thread_pool=0x1e6de00, 
    cdc_min_replicated_index=9223372036854775807, log=0x7f319f19f760, create_new_segment=...) at ../../src/yb/consensus/log.cc:493
#15 0x00007f31c056e057 in yb::tablet::TabletBootstrap::OpenNewLog (this=this@entry=0x7f319f19f600, create_new_segment=...) at ../../src/yb/tablet/tablet_bootstrap.cc:779
#16 0x00007f31c057c282 in yb::tablet::TabletBootstrap::PlaySegments (this=this@entry=0x7f319f19f600, consensus_info=consensus_info@entry=0x7f319f19fc80) at ../../src/yb/tablet/tablet_bootstrap.cc:1233
#17 0x00007f31c057e53f in yb::tablet::TabletBootstrap::Bootstrap (this=this@entry=0x7f319f19f600, rebuilt_tablet=rebuilt_tablet@entry=0x7f319f19f9a0, rebuilt_log=rebuilt_log@entry=0x7f319f19f938, 
    consensus_info=consensus_info@entry=0x7f319f19fc80) at ../../src/yb/tablet/tablet_bootstrap.cc:557
#18 0x00007f31c056c3a3 in yb::tablet::BootstrapTabletImpl (data=..., rebuilt_tablet=rebuilt_tablet@entry=0x7f319f19f9a0, rebuilt_log=rebuilt_log@entry=0x7f319f19f938, results=results@entry=0x7f319f19fc80)
    at ../../src/yb/tablet/tablet_bootstrap.cc:1655
#19 0x00007f31c057f6fb in yb::tablet::BootstrapTablet (data=..., rebuilt_tablet=rebuilt_tablet@entry=0x7f319f19f9a0, rebuilt_log=rebuilt_log@entry=0x7f319f19f938, consensus_info=consensus_info@entry=0x7f319f19fc80)
    at ../../src/yb/tablet/tablet_bootstrap_if.cc:92
#20 0x00007f31c0ece625 in yb::tserver::TSTabletManager::OpenTablet (this=0x1e22d00, meta=..., deleter=...) at ../../src/yb/tserver/ts_tablet_manager.cc:1503
#21 0x00007f31b6a38c94 in yb::ThreadPool::DispatchThread (this=0x1f01c00, permanent=false) at ../../src/yb/util/threadpool.cc:617
#22 0x00007f31b6a3546f in operator() (this=0x229c718) at /data/yb/yb-software/yugabyte-2.5.3.1-b10-centos-x86_64/linuxbrew-xxxxxxxxxxxxxxxxxxx/Cellar/gcc/5.5.0_4/include/c++/5.5.0/functional:2267
#23 yb::Thread::SuperviseThread (arg=0x229c6c0) at ../../src/yb/util/thread.cc:771
#24 0x00007f31b2150694 in start_thread (arg=0x7f319f1a8700) at pthread_create.c:333
#25 0x00007f31b188d41d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

```
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
*** Aborted at 1616617820 (unix time) try "date -d @1616617820" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGABRT (@0x3e500006ecc) received by PID 28364 (TID 0x7fd529021700) from PID 28364; stack trace: ***
    @     0x7fd560e54ba0 (unknown)
    @     0x7fd5604d60a7 __GI_raise
    @     0x7fd5604d74aa __GI_abort
    @     0x7fd56160f5cc  __gnu_cxx::__verbose_terminate_handler()
    @     0x7fd56160d636 (unknown)
    @     0x7fd56160d680  std::terminate()
    @     0x7fd56160d898 __cxa_throw
    @     0x7fd565142fba  (anonymous namespace)::handle_oom()
    @     0x7fd565163c01  tcmalloc::allocate_full_cpp_throw_oom()
    @     0x7fd5656837c8  yb::faststring::GrowArray()
    @     0x7fd56d1abfea  yb::pggate::PgWire::WriteBinary()
    @     0x7fd56d1ae074  yb::pggate::WriteColumn()
 ...
```

```
(gdb) bt
#0  0x00007f4ebe4460a7 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007f4ebe4474aa in __GI_abort () at abort.c:89
#2  0x00007f4ebf57f5cd in __gnu_cxx::__verbose_terminate_handler() () from /home/yugabyte/yb-software/yugabyte-2.4.0.0-b60-centos-x86_64/linuxbrew/lib/libstdc++.so.6
#3  0x00007f4ebf57d636 in ?? () from /home/yugabyte/yb-software/yugabyte-2.4.0.0-b60-centos-x86_64/linuxbrew/lib/libstdc++.so.6
#4  0x00007f4ebf57d681 in std::terminate() () from /home/yugabyte/yb-software/yugabyte-2.4.0.0-b60-centos-x86_64/linuxbrew/lib/libstdc++.so.6
#5  0x00007f4ebf57d898 in __cxa_throw () from /home/yugabyte/yb-software/yugabyte-2.4.0.0-b60-centos-x86_64/linuxbrew/lib/libstdc++.so.6
#6  0x00007f4ec3fc41fb in (anonymous namespace)::handle_oom(void* (*)(void*), void*, bool, bool) ()
   from /home/yugabyte/yb-software/yugabyte-2.4.0.0-b60-centos-x86_64/lib/yb-thirdparty/libtcmalloc.so.4
#7  0x00007f4ec3fe4a82 in tcmalloc::allocate_full_cpp_throw_oom(unsigned long) ()
   from /home/yugabyte/yb-software/yugabyte-2.4.0.0-b60-centos-x86_64/lib/yb-thirdparty/libtcmalloc.so.4
#8  0x00007f4ebf60a0c9 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_mutate(unsigned long, unsigned long, char const*, unsigned long) ()
   from /home/yugabyte/yb-software/yugabyte-2.4.0.0-b60-centos-x86_64/linuxbrew/lib/libstdc++.so.6
#9  0x00007f4ebf60b603 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_append(char const*, unsigned long) ()
   from /home/yugabyte/yb-software/yugabyte-2.4.0.0-b60-centos-x86_64/linuxbrew/lib/libstdc++.so.6
#10 0x00007f4ec8128b71 in append (__n=<optimized out>, __s=<optimized out>, this=0x7f4e8d367768)
    at /home/yugabyte/yb-software/yugabyte-2.4.0.0-b60-centos-x86_64/linuxbrew-xxxxxxxxxxxxx/Cellar/gcc/5.5.0_4/include/c++/5.5.0/bits/basic_string.h:1105
#11 PutLengthPrefixedSliceParts (slice_parts=..., dst=<optimized out>) at ../../src/yb/rocksdb/util/coding.h:216
#12 rocksdb::WriteBatchInternal::Put (b=0x7f4e8d367750, column_family_id=<optimized out>, key=..., value=...) at ../../src/yb/rocksdb/db/write_batch.cc:403
#13 0x00007f4ecc12a6dd in yb::docdb::IntentToWriteRequest (transaction_id_slice=..., commit_ht=..., commit_ht@entry=..., reverse_index_key=..., reverse_index_value=..., 
    intent_iter=intent_iter@entry=0x7f4e8d367560, regular_batch=0x7f4e8d367750, write_id=0x7f4e8d367324) at ../../src/yb/docdb/docdb.cc:1038
#14 0x00007f4ecc130c5e in yb::docdb::PrepareApplyIntentsBatch (transaction_id=..., commit_ht=..., key_bounds=key_bounds@entry=0x3632f590, apply_state=0x0, 
    regular_batch=regular_batch@entry=0x7f4e8d367750, intents_db=0x35ecca00, intents_batch=0x0) at ../../src/yb/docdb/docdb.cc:1176
#15 0x00007f4ecd12a63d in yb::tablet::Tablet::ApplyIntents (this=0x3632f210, data=...) at ../../src/yb/tablet/tablet.cc:1968
#16 0x00007f4ecd19d464 in yb::tablet::TransactionParticipant::Impl::ProcessApply (this=this@entry=0x33fb3100, data=...) at ../../src/yb/tablet/transaction_participant.cc:534
#17 0x00007f4ecd18a86f in ReplicatedApplying (data=..., id=..., this=0x33fb3100) at ../../src/yb/tablet/transaction_participant.cc:1294
#18 ProcessReplicated (data=..., this=<optimized out>, this=<optimized out>, this=<optimized out>) at ../../src/yb/tablet/transaction_participant.cc:465
#19 yb::tablet::TransactionParticipant::ProcessReplicated (this=this@entry=0x35ff11c0, data=...) at ../../src/yb/tablet/transaction_participant.cc:1547
#20 0x00007f4ecd1b4c9d in yb::tablet::UpdateTxnOperation::DoReplicated (this=<optimized out>, leader_term=<optimized out>, complete_status=<optimized out>)
    at ../../src/yb/tablet/operations/update_txn_operation.cc:83
#21 0x00007f4ecd1a307c in yb::tablet::Operation::Replicated (this=0x1b314820, leader_term=leader_term@entry=-1) at ../../src/yb/tablet/operations/operation.cc:68
#22 0x00007f4ecd1ab2a1 in yb::tablet::OperationDriver::ApplyTask (this=this@entry=0x33b0d360, leader_term=leader_term@entry=-1, applied_op_ids=applied_op_ids@entry=0x7f4e8d3680e0)
    at ../../src/yb/tablet/operations/operation_driver.cc:435
```

Other examples can be found in issue https://github.com/yugabyte/yugabyte-db/issues/7034 and issue https://github.com/yugabyte/yugabyte-db/issues/8238.

These issues started to occur after we upgraded gperftools to `v2.8`, and they appear to have been caused by https://github.com/gperftools/gperftools/issues/1204.

**Comment by bmatican** [comment]
Downgrade covered in #8496
