### ISSUE TITLE
[docdb] SEGV on UpdateTransaction being called on a non transaction tablet

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#8592]
Example stack
```
#0 yb::tablet::TransactionCoordinator::Handle (this=0x0, request=..., term=term@entry=5) at ../../src/yb/tablet/transaction_coordinator.cc:1393
#1 0x00007f41d82a0b3b in yb::tserver::TabletServiceImpl::UpdateTransaction (this=this@entry=0x14435e0, req=req@entry=0x4c7473d0, resp=resp@entry=0x192c2450,
context=...) at ../../src/yb/tserver/tablet_service.cc:939
#2 0x00007f41d503c5c0 in yb::tserver::TabletServerServiceIf::Handle (this=0x14435e0, call=...) at src/yb/tserver/tserver_service.service.cc:292
#3 0x00007f41d08d5019 in yb::rpc::ServicePoolImpl::Handle (this=0x1ec86c0, incoming=...) at ../../src/yb/rpc/service_pool.cc:262
#4 0x00007f41d087bae4 in yb::rpc::InboundCall::InboundCallTask::Run (this=<optimized out>) at ../../src/yb/rpc/inbound_call.cc:212
#5 0x00007f41d08e0d98 in yb::rpc::(anonymous namespace)::Worker::Execute (this=<optimized out>) at ../../src/yb/rpc/thread_pool.cc:100
#6 0x00007f41cf11203f in operator() (this=0xc6d8d138)
at /home/yugabyte/yb-software/yugabyte-2.2.6.0-b4-centos-x86_64/linuxbrew-xxxxxxxxxxxxxx/Cellar/gcc/5.5.0_4/include/c++/5.5.0/functional:2267
#7 yb::Thread::SuperviseThread (arg=0xc6d8d0e0) at ../../src/yb/util/thread.cc:759
#8 0x00007f41c992e694 in start_thread (arg=0x7f3242594700) at pthread_create.c:333
#9 0x00007f41c906b41d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

After some investigation, seems like this was called on a tablet ID which was a user tablet, not a transaction status tablet.

**Comment by bmatican** [comment]
@spolitov looked into this further, seems it traces back to 70e3768a2acb2826f6c735ac8eb95c0fdb718b1d, which means any upgrade from 2.2.x to 2.4.x might hit this.

Sergei's planning on putting in a new capability and checking for that during the bad RPC interactions.

**Comment by hari90** [comment]
.
