### ISSUE TITLE
YSQL webserver terminated with signal 6

### ISSUE THREAD

**Issue by cigoldstein** [yugabyte/yugabyte-db#8609]
Jira Link: [DB-1569](https://yugabyte.atlassian.net/browse/DB-1569)
The following backtrace was taken from a core file generated on a node running 2.0.5.6:

```
Core was generated by `postgres: YSQL webserver                                                      '.
Program terminated with signal 6, Aborted.
#0  0x00007f3bfd3de817 in raise () from /home/yugabyte/yb-software/yugabyte-2.0.5.6-b2-centos-x86_64/linuxbrew/lib/libc.so.6
(gdb) bt
#0  0x00007f3bfd3de817 in raise () from /home/yugabyte/yb-software/yugabyte-2.0.5.6-b2-centos-x86_64/linuxbrew/lib/libc.so.6
#1  0x00007f3bfd3dfb7a in abort () from /home/yugabyte/yb-software/yugabyte-2.0.5.6-b2-centos-x86_64/linuxbrew/lib/libc.so.6
#2  0x00007f3bfd4196e7 in __libc_message () from /home/yugabyte/yb-software/yugabyte-2.0.5.6-b2-centos-x86_64/linuxbrew/lib/libc.so.6
#3  0x00007f3bfd41eed6 in malloc_printerr () from /home/yugabyte/yb-software/yugabyte-2.0.5.6-b2-centos-x86_64/linuxbrew/lib/libc.so.6
#4  0x00007f3bfd41fc23 in _int_free () from /home/yugabyte/yb-software/yugabyte-2.0.5.6-b2-centos-x86_64/linuxbrew/lib/libc.so.6
#5  0x00007f3bfb8df728 in deallocate (this=<optimized out>, __p=<optimized out>)
    at /home/yugabyte/yb-software/yugabyte-2.0.5.6-b2-centos-x86_64/linuxbrew-xxxxxxxxxxxxxx/Cellar/gcc/5.5.0_4/include/c++/5.5.0/ext/new_allocator.h:110
#6  deallocate (__a=..., __n=<optimized out>, __p=<optimized out>)
    at /home/yugabyte/yb-software/yugabyte-2.0.5.6-b2-centos-x86_64/linuxbrew-xxxxxxxxxxxxxx/Cellar/gcc/5.5.0_4/include/c++/5.5.0/bits/alloc_traits.h:517
#7  _M_deallocate (this=<optimized out>, __n=<optimized out>, __p=<optimized out>)
    at /home/yugabyte/yb-software/yugabyte-2.0.5.6-b2-centos-x86_64/linuxbrew-xxxxxxxxxxxxxx/Cellar/gcc/5.5.0_4/include/c++/5.5.0/bits/stl_vector.h:178
#8  ~_Vector_base (this=<optimized out>, __in_chrg=<optimized out>)
    at /home/yugabyte/yb-software/yugabyte-2.0.5.6-b2-centos-x86_64/linuxbrew-xxxxxxxxxxxxxx/Cellar/gcc/5.5.0_4/include/c++/5.5.0/bits/stl_vector.h:160
#9  std::vector<std::pair<rocksdb::Histograms, std::string>, std::allocator<std::pair<rocksdb::Histograms, std::string> > >::~vector (this=<optimized out>, 
    __in_chrg=<optimized out>)
    at /home/yugabyte/yb-software/yugabyte-2.0.5.6-b2-centos-x86_64/linuxbrew-xxxxxxxxxxxxxx/Cellar/gcc/5.5.0_4/include/c++/5.5.0/bits/stl_vector.h:425
#10 0x00007f3bfd3e13a7 in __cxa_finalize () from /home/yugabyte/yb-software/yugabyte-2.0.5.6-b2-centos-x86_64/linuxbrew/lib/libc.so.6
#11 0x00007f3bfb535d43 in ?? () from /home/yugabyte/yb-software/yugabyte-2.0.5.6-b2-centos-x86_64/lib/yb/librocksdb.so
#12 0x00007fff99bdecf0 in ?? ()
#13 0x00007f3bfe7158ca in _dl_fini () from /home/yugabyte/yb-software/yugabyte-2.0.5.6-b2-centos-x86_64/lib/ld.so
Backtrace stopped: frame did not save the PC
```

It looks like the universe was initially created with YSQL turned off (which makes it confusing that we'd have a YSQL core):

<img src="https://user-images.githubusercontent.com/9438699/119528825-88caf300-bd4f-11eb-8012-314d65e33ef8.png" width="305" height="428">

However, when we check the flags, we can see that `--enable_ysql=true`:

![enable-ysql-true](https://user-images.githubusercontent.com/9438699/119531298-c892da00-bd51-11eb-9c16-31fbf3db7c33.png)

It's unclear whether the fact that ysql was likely enabled after the initial universe creation is relevant to this issue.

**Comment by sushantrmishra** [comment]
Closing this issue, as reported in 2.0.5.6 which is very old release and no clear steps to reproduce the issue. Please reopen if this issue is sen again.
