### ISSUE TITLE
Queue overflow during SerializableTxnTest.Increment

### ISSUE THREAD

**Issue by spolitov** [yugabyte/yugabyte-db#867]
A lot of threads stuck on locking:
```

8941 | Thread 94 (LWP 21381), 104 (LWP 21344), 108 (LWP 21347), 120 (LWP 21361), 128 (LWP 21376), 129 (LWP 21378), 135 (LWP 21379), 144 (LWP 21383), 148 (LWP 21387), 152 (LWP 21682), 154 (LWP 21391), 155 (LWP 21394), 182 (LWP 21687), 206 (LWP 21927), 211 (LWP 21933), 216 (LWP 21934), 220 (LWP 21944), 222 (LWP 21715), 224 (LWP 21948), 225 (LWP 21677), 227 (LWP 21957), 228 (LWP 21924), 229 (LWP 21678), 230 (LWP 21725), 231 (LWP 21925), 232 (LWP 21958), 233 (LWP 21679), 234 (LWP 21728), 236 (LWP 21926), 237 (LWP 21680), 238 (LWP 21729), 240 (LWP 21928), 241 (LWP 21731), 244 (LWP 21929), 246 (LWP 21735), 249 (LWP 21691), 251 (LWP 21694), 253 (LWP 21700), 254 (LWP 21930), 255 (LWP 21741), 257 (LWP 21742), 259 (LWP 21703), 260 (LWP 21751), 262 (LWP 21707), 264 (LWP 21752), 265 (LWP 21708), 267 (LWP 21753), 268 (LWP 21718), 270 (LWP 21756), 273 (LWP 21758), 274 (LWP 21726), 276 (LWP 21759), 277 (LWP 21727), 279 (LWP 21761), 280 (LWP 21730), 282 (LWP 21732), 283 (LWP 21763), 285 (LWP 21733), 286 (LWP 21764), 288 (LWP 21765), 289 (LWP 21740), 290 (LWP 21766), 291 (LWP 21743), 292 (LWP 21767), 293 (LWP 21744), 294 (LWP 21768), 295 (LWP 21745), 296 (LWP 21746), 297 (LWP 21769), 298 (LWP 21747), 299 (LWP 21776), 300 (LWP 21748), 301 (LWP 21778), 302 (LWP 21749), 303 (LWP 21779), 304 (LWP 21750), 305 (LWP 21754), 306 (LWP 21780), 307 (LWP 21755), 308 (LWP 21781), 309 (LWP 21757), 310 (LWP 21784), 311 (LWP 21760), 312 (LWP 21786), 313 (LWP 21762), 314 (LWP 21788), 315 (LWP 21770), 316 (LWP 21789), 317 (LWP 21771), 318 (LWP 21790), 319 (LWP 21772), 320 (LWP 21792), 321 (LWP 21773), 322 (LWP 21793), 323 (LWP 21774), 324 (LWP 21775), 325 (LWP 21794), 326 (LWP 21795), 327 (LWP 21777), 328 (LWP 21796), 329 (LWP 21782), 330 (LWP 21783), 331 (LWP 21798), 332 (LWP 21785), 333 (LWP 21799), 334 (LWP 21787), 335 (LWP 21800), 336 (LWP 21791), 337 (LWP 21801), 338 (LWP 21797), 339 (LWP 21802), 340 (LWP 21806), 341 (LWP 21803), 342 (LWP 21807), 343 (LWP 21804), 344 (LWP 21809), 345 (LWP 21805), 346 (LWP 21811), 347 (LWP 21808), 348 (LWP 21812), 349 (LWP 21810), 350 (LWP 21813), 351 (LWP 21814), 352 (LWP 21817), 353 (LWP 21815), 354 (LWP 21816), 355 (LWP 21819), 356 (LWP 21821), 357 (LWP 21818), 358 (LWP 21820), 359 (LWP 21823), 360 (LWP 21822), 361 (LWP 21825), 362 (LWP 21824), 363 (LWP 21826), 364 (LWP 21827), 365 (LWP 21829), 366 (LWP 21828), 367 (LWP 21831), 368 (LWP 21830), 369 (LWP 21832), 370 (LWP 21834), 371 (LWP 21833), 372 (LWP 21837), 373 (LWP 21835), 374 (LWP 21840), 375 (LWP 21836), 376 (LWP 21838), 377 (LWP 21843), 378 (LWP 21839), 379 (LWP 21849), 380 (LWP 21841), 381 (LWP 21854), 382 (LWP 21842), 383 (LWP 21855), 384 (LWP 21844), 385 (LWP 21845), 386 (LWP 21857), 387 (LWP 21846), 388 (LWP 21858), 389 (LWP 21847), 390 (LWP 21859), 391 (LWP 21848), 392 (LWP 21850), 393 (LWP 21861), 394 (LWP 21851), 395 (LWP 21862), 396 (LWP 21852), 397 (LWP 21863), 398 (LWP 21853), 399 (LWP 21865), 400 (LWP 21856), 401 (LWP 21866), 402 (LWP 21860), 403 (LWP 21864), 404 (LWP 21867), 405 (LWP 21868), 406 (LWP 21869), 407 (LWP 21870), 408 (LWP 21871), 409 (LWP 21872), 410 (LWP 21874), 411 (LWP 21873), 412 (LWP 21875), 413 (LWP 21876), 414 (LWP 21879), 415 (LWP 21877), 416 (LWP 21880), 417 (LWP 21878), 418 (LWP 21881), 419 (LWP 21884), 420 (LWP 21882), 421 (LWP 21887), 422 (LWP 21883), 423 (LWP 21885), 424 (LWP 21888), 425 (LWP 21890), 426 (LWP 21886), 427 (LWP 21892), 428 (LWP 21889), 429 (LWP 21894), 430 (LWP 21891), 431 (LWP 21895), 432 (LWP 21893), 433 (LWP 21898), 434 (LWP 21896), 435 (LWP 21899), 436 (LWP 21897), 437 (LWP 21900), 438 (LWP 21901), 439 (LWP 21902), 440 (LWP 21903), 441 (LWP 21904), 442 (LWP 21907), 443 (LWP 21905), 444 (LWP 21908), 445 (LWP 21906), 446 (LWP 21910), 447 (LWP 21909), 448 (LWP 21918), 449 (LWP 21911), 450 (LWP 21912), 451 (LWP 21920), 452 (LWP 21913), 453 (LWP 21922), 454 (LWP 21914), 456 (LWP 21915), 457 (LWP 21943), 458 (LWP 21916), 459 (LWP 21917), 460 (LWP 21947), 461 (LWP 21919), 462 (LWP 21951), 463 (LWP 21921), 464 (LWP 21953), 465 (LWP 21923), 466 (LWP 21954), 467 (LWP 21931), 468 (LWP 21932), 469 (LWP 21955), 471 (LWP 21956), 472 (LWP 21964), 473 (LWP 21965), 476 (LWP 21945), 478 (LWP 21946), 479 (LWP 21949), 481 (LWP 21950), 483 (LWP 21952), 485 (LWP 21959), 486 (LWP 21960), 488 (LWP 21961), 490 (LWP 21962), 492 (LWP 21963)
-- | --
8942 | #0 pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
8943 | #1 0x00007f7006aef85c in std::condition_variable::wait(std::unique_lock<std::mutex>&) () from /n/jenkins/linuxbrew/linuxbrew-20181203T161736-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/lib/libstdc++.so.6
8944 | #2 0x00007f701665856a in yb::docdb::LockedBatchEntry::Lock (this=0x..., lock_type=...) at src/yb/docdb/shared_lock_manager.cc:188
8945 | #3 0x00007f7016658bcf in yb::docdb::SharedLockManager::Impl::Lock (this=0x..., key_to_intent_type=0x...) at src/yb/docdb/shared_lock_manager.cc:242
8946 | #4 0x00007f7016659224 in yb::docdb::SharedLockManager::Lock (this=0x..., key_to_intent_type=0x...) at src/yb/docdb/shared_lock_manager.cc:291
8947 | #5 0x00007f7016642729 in yb::docdb::LockBatch::LockBatch(yb::docdb::SharedLockManager*, std::vector<yb::docdb::LockBatchEntry, std::allocator<yb::docdb::LockBatchEntry> >&&) (this=0x..., lock_manager=0x..., key_to_intent_type=<unknown type in /net/centos-gcp-cloud-jenkins-slave-104/share/jenkins/workspace/yugabyte-centos-master-gcc-debug/build/debug-gcc-dynamic-enterprise-ninja/tests-client/../lib/libyb_docdb.so, CU 0x8fd9da, DIE 0x92f54b>) at src/yb/docdb/lock_batch.cc:27
8948 | #6 0x00007f701657190f in yb::docdb::PrepareDocWriteOperation (doc_write_ops=..., read_pairs=..., write_lock_latency=..., isolation_level=yb::SERIALIZABLE_ISOLATION, operation_kind=yb::docdb::kWrite, transactional_table=true, lock_manager=0x...) at src/yb/docdb/docdb.cc:263
8949 | #7 0x00007f701710f085 in yb::tablet::Tablet::StartDocWriteOperation (this=0x..., operation=0x...) at src/yb/tablet/tablet.cc:1720
8950 | #8 0x00007f7017107c28 in yb::tablet::Tablet::KeyValueBatchFromQLWriteBatch (this=0x..., operation=...) at src/yb/tablet/tablet.cc:972
8951 | #9 0x00007f701710a329 in yb::tablet::Tablet::AcquireLocksAndPerformDocOperations (this=0x..., operation=...) at src/yb/tablet/tablet.cc:1259
8952 | #10 0x00007f70171786f6 in yb::tablet::TabletPeer::WriteAsync (this=0x..., state=..., term=1, deadline=...) at src/yb/tablet/tablet_peer.cc:470
8953 | #11 0x00007f70177d10c7 in yb::tserver::TabletServiceImpl::Write (this=0x..., req=0x..., resp=0x..., context=...) at src/yb/tserver/tablet_service.cc:770
8954 | #12 0x00007f70110c4a3b in yb::tserver::TabletServerServiceIf::Handle (this=0x..., call=...) at src/yb/tserver/tserver_service.service.cc:129
8955 | #13 0x00007f700c7705cd in yb::rpc::ServicePoolImpl::Handle (this=0x..., incoming=...) at src/yb/rpc/service_pool.cc:214
8956 | #14 0x00007f700c76c758 in yb::rpc::(anonymous namespace)::InboundCallTask::Run (this=0x...) at src/yb/rpc/service_pool.cc:252
8957 | #15 0x00007f700c76f28c in yb::rpc::TasksPool<yb::rpc::(anonymous namespace)::InboundCallTask>::WrappedTask::Run (this=0x...) at src/yb/rpc/tasks_pool.h:70
8958 | #16 0x00007f700c7787f3 in yb::rpc::(anonymous namespace)::Worker::Execute (this=0x...) at src/yb/rpc/thread_pool.cc:101
8959 | #17 0x00007f700c77bdcd in std::_Mem_fn_base<void (yb::rpc::(anonymous namespace)::Worker::*)(), true>::operator()<, void>(std::_Mem_fn_base<void (yb::rpc::(anonymous namespace)::Worker::*)(), true>::_Class *) const (this=0x..., __object=0x...) at /n/jenkins/linuxbrew/linuxbrew-20181203T161736-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/Cellar/gcc/5.5.0_4/include/c++/5.5.0/functional:600
8960 | #18 0x00007f700c77bab0 in std::_Bind<std::_Mem_fn<void (yb::rpc::(anonymous namespace)::Worker::*)()>(yb::rpc::(anonymous namespace)::Worker*)>::__call<void, 0ul>(<unknown type in /net/centos-gcp-cloud-jenkins-slave-104/share/jenkins/workspace/yugabyte-centos-master-gcc-debug/build/debug-gcc-dynamic-enterprise-ninja/tests-client/../lib/libyrpc.so, CU 0xa15398, DIE 0xa3a96f>, std::_Index_tuple<0ul>) (this=0x..., __args=<unknown type in /net/centos-gcp-cloud-jenkins-slave-104/share/jenkins/workspace/yugabyte-centos-master-gcc-debug/build/debug-gcc-dynamic-enterprise-ninja/tests-client/../lib/libyrpc.so, CU 0xa15398, DIE 0xa3a96f>) at /n/jenkins/linuxbrew/linuxbrew-20181203T161736-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/Cellar/gcc/5.5.0_4/include/c++/5.5.0/functional:1074
8961 | #19 0x00007f700c77b4ce in std::_Bind<std::_Mem_fn<void (yb::rpc::(anonymous namespace)::Worker::*)()>(yb::rpc::(anonymous namespace)::Worker*)>::operator()<, void>(void) (this=0x...) at /n/jenkins/linuxbrew/linuxbrew-20181203T161736-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/Cellar/gcc/5.5.0_4/include/c++/5.5.0/functional:1133
8962 | #20 0x00007f700c77ab01 in std::_Function_handler<void(), std::_Bind<std::_Mem_fn<void (yb::rpc::(anonymous namespace)::Worker::*)()>(yb::rpc::(anonymous namespace)::Worker*)> >::_M_invoke(const std::_Any_data &) (__functor=...) at /n/jenkins/linuxbrew/linuxbrew-20181203T161736-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/Cellar/gcc/5.5.0_4/include/c++/5.5.0/functional:1871
8963 | #21 0x00007f7017813a0e in std::function<void ()>::operator()() const (this=0x...) at /n/jenkins/linuxbrew/linuxbrew-20181203T161736-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/Cellar/gcc/5.5.0_4/include/c++/5.5.0/functional:2267
8964 | #22 0x00007f700a29ff20 in yb::Thread::SuperviseThread (arg=0x...) at src/yb/util/thread.cc:603
8965 | #23 0x00007f70127a3694 in start_thread (arg=0x...) at pthread_create.c:333
8966 | #24 0x00007f700626e41d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

```

**Comment by kriteshranjan** [comment]
Closing this issue based on AI validation. cc: @m-iancu , @VamsidharGunturu
