### ISSUE TITLE
[xCluster]Failure to update replication map causes crash + core dump 

### ISSUE THREAD

**Issue by CharlotteRose** [yugabyte/yugabyte-db#8772]
**Issue**
When there is a Master node change initiated by a user in any given environment with xCluster replication, the `masterAddrs` under the `producerMap` fails to update, and any subsequent `alter_universe_replication` will crash with a cored dump file: 

```
#0  0x00007f67e425f227 in yb::RefCntBuffer::size (this=0x2ba08f48) at ../../src/yb/util/ref_cnt_buffer.h:61
#1  yb::rpc::YBInboundCall::Serialize (this=0x2ba08d90, output=0x7f67d52f9d40) at ../../src/yb/rpc/yb_rpc.cc:446
#2  0x00007f67e4240370 in yb::rpc::(anonymous namespace)::SecureStream::SendEncrypted (this=0x2b32f560, data=...) at ../../src/yb/rpc/secure_stream.cc:489
#3  0x00007f67e4240ace in yb::rpc::(anonymous namespace)::SecureStream::Send (this=<optimized out>, data=...) at ../../src/yb/rpc/secure_stream.cc:523
#4  0x00007f67e41e1d45 in yb::rpc::Connection::DoQueueOutboundData (this=this@entry=0x2b32f9f0, outbound_data=..., batch=batch@entry=true) at ../../src/yb/rpc/connection.cc:267
#5  0x00007f67e41e2640 in yb::rpc::Connection::ProcessResponseQueue (this=0x2b32f9f0) at ../../src/yb/rpc/connection.cc:439
#6  0x00007f67e41e5999 in std::_Mem_fn_base<void (yb::rpc::Connection::*)(), true>::operator()<, void>(yb::rpc::Connection*) const (__object=<optimized out>, this=<optimized out>)
    at /home/charlotterose/yb-releases/yugabyte-2.4.4.0-b7/yugabyte-2.4.4.0/linuxbrew-xxxxxx/Cellar/gcc/5.5.0_4/include/c++/5.5.0/functional:600
#7  std::_Bind<std::_Mem_fn<void (yb::rpc::Connection::*)()> (yb::rpc::Connection*)>::__call<void, yb::rpc::Reactor*&, 0ul>(std::tuple<yb::rpc::Reactor*&>&&, std::_Index_tuple<0ul>) (__args=..., this=<optimized out>)
    at /home/charlotterose/yb-releases/yugabyte-2.4.4.0-b7/yugabyte-2.4.4.0/linuxbrew-xxxxxx/Cellar/gcc/5.5.0_4/include/c++/5.5.0/functional:1074
#8  std::_Bind<std::_Mem_fn<void (yb::rpc::Connection::*)()> (yb::rpc::Connection*)>::operator()<yb::rpc::Reactor*&, void>(yb::rpc::Reactor*&) (this=<optimized out>)
    at /home/charlotterose/yb-releases/yugabyte-2.4.4.0-b7/yugabyte-2.4.4.0/linuxbrew-xxxxxx/Cellar/gcc/5.5.0_4/include/c++/5.5.0/functional:1133
#9  yb::rpc::FunctorReactorTaskWithWeakPtr<std::_Bind<std::_Mem_fn<void (yb::rpc::Connection::*)()> (yb::rpc::Connection*)>, yb::rpc::Connection>::Run(yb::rpc::Reactor*) (this=<optimized out>, reactor=<optimized out>)
    at ../../src/yb/rpc/reactor.h:187
#10 0x00007f67e4212de3 in yb::rpc::Reactor::AsyncHandler (this=0x222ea00, watcher=..., revents=<optimized out>) at ../../src/yb/rpc/reactor.cc:357
#11 0x00007f67e063e7db in ev_invoke_pending () from /home/charlotterose/yb-releases/home/yugabyte/yb-software/yugabyte-2.4.4.0-b7-centos-x86_64/lib/yb-thirdparty/libev.so.4
#12 0x00007f67e06428ea in ev_run () from /home/charlotterose/yb-releases/home/yugabyte/yb-software/yugabyte-2.4.4.0-b7-centos-x86_64/lib/yb-thirdparty/libev.so.4
#13 0x00007f67e420dbcc in ev::loop_ref::run (flags=0, this=0x222ea98) at /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v2.4-20210519151206-07aad69677-centos7-linuxbrew/installed/common/include/ev++.h:211
#14 yb::rpc::Reactor::RunThread (this=0x222ea00) at ../../src/yb/rpc/reactor.cc:482
#15 0x00007f67e1b45edf in std::function<void ()>::operator()() const (this=0x1ecda38) at /home/charlotterose/yb-releases/yugabyte-2.4.4.0-b7/yugabyte-2.4.4.0/linuxbrew-xxxxxx/Cellar/gcc/5.5.0_4/include/c++/5.5.0/functional:2267
#16 yb::Thread::SuperviseThread (arg=0x1ecd9e0) at ../../src/yb/util/thread.cc:771
#17 0x00007f67dd293694 in start_thread (arg=0x7f67d5302700) at pthread_create.c:333
#18 0x00007f67dc9d041d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

**Steps to reproduce**
-    Setup xCluster replication
-    From the Yugaware platform UI, stop all services on the MasterLeader/Tserver node
-    Start the Master process on a TServer node
-    From the CLI - issue, change the master - where the new masterLeader is the node that was only a tserver prior.

```
yb-admin -master_addresses <master-addresses> master_leader_stepdown [ <new_leader_id> ]
```

-   Attempt to add bidirectional-replication for a new table

```
yb-admin master_addresses <master-addresses> alter_universe_replication <producer_universe_uuid> { set_master_addresses <producer_master_addresses> |  add_table <table_id>[, <table_id>...] | remove_table <table_id>[, <table_id>...] }
```

**Additional Information**
looking into the core dump we can see the exact actions that are failing - strictly related to replication changes

```
(gdb) up
#1  yb::rpc::YBInboundCall::Serialize (this=0x2ba08d90, output=0x7f67d52f9d40) at ../../src/yb/rpc/yb_rpc.cc:446
446	../../src/yb/rpc/yb_rpc.cc: No such file or directory.
(gdb) p this.request_data_
$3 = {
  data_ = 0x2b731830 ";\b\004\022\063\n\027yb.master.MasterService\022\030AlterUniverseReplication\030\340\324\003H\n$4f558902-684a-436f-bef4-886abbbc7b74\" fd9a70138f0d4d389828b25f3275c8bc", size_ = 133}
```

**Request** 
We need to have the producer/consumer map update when the master leader changes. Additionally this needs to result in a simple error message and not a crash+ core dump. 

Please see reference ticket: [1390](https://yugabyte.zendesk.com/agent/tickets/1390)

**Comment by tylarb** [comment]
Let's open a new GHI for the platform feature request @CharlotteRose

**Comment by CharlotteRose** [comment]
@streddy-yb @bmatican   - while we have our eye and minds on Replication issues as a whole I want to be sure that we can get this addressed as well for the issues we are hitting from the other GHIs related to replication :)
