### ISSUE TITLE
[Platform]Remove Unsupported Instance types from pull down menu for Azure.

### ISSUE THREAD

**Issue by shashwat-yb** [yugabyte/yugabyte-db#8859]
**Description:**
Standard_B4ms instance type is failing to create universe in azure. All such unsupported Instances need to be removed from the pull down menu of Instance type.

**Comment by shashwat-yb** [comment]
Instance types- d2s_v3 and d2as_v4 are supported. 

Universes with other instance types fail with the error-
`Failed to execute task {"nodeExporterUser":"prometheus","deviceInfo":{"volumeSize":250,"numVolumes":1,"storageClass":"standard","storageType":"Premium_LRS"},"universeUUID":"17e677e4-4df9-41db-b9a2-80364291e56b","encryptionAtRestConfig":{"encryptionAtRestEnabled":false,"opType":"UNDEFINED","type":"DATA_KEY"},"communicationPorts":{"masterHttpPort":7000,"masterRpcPort":7100,"tserverHttpPort":9000,"tserverRpcPort":9100,"redisServerHttpPort":11000,"redisServerRpcPort":6379,"yqlServerHttpPort":12000,"yqlServerRpcPort":90..., hit error java.lang.RuntimeException: [0;32m[2021-09-02_05_39_39 common.sh:323 activate_virtualenv][0m Using virtualenv python executable now.
2021-09-02 05:39:40,888 INFO validate_credentials:cloud.py:102: Found azu cloud credentials in env.
2021-09-02 05:39:41,334 INFO create_or_update_instance:cloud.py:89: [app] Creating/Updating Azure VM yb-dev-kkg-tp-1622-16-n3 in westus2/1.
2021-09-02 05:42:03,812 INFO create_or_update_instance:cloud.py:114: [app] Updated Azure VM yb-dev-kkg-tp-1622-16-n3.
2021-09-02 05:42:03,812 INFO wait_for_host:method.py:361: Waiting for instance yb-dev-kkg-tp-1622-16-n3
Traceback (most recent call last):
  File "/opt/yugabyte/devops/venv/bin/ybcloud.py", line 4, in <module>
    __import__('pkg_resources').run_script('ybops==0.4', 'ybcloud.py')
  File "/opt/yugabyte/devops/venv/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 654, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/opt/yugabyte/devops/venv/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 1434, in run_script
    exec(code, namespace, namespace)
  File "/opt/yugabyte/devops/venv/lib/python3.6/site-packages/ybops-0.4-py3.6.egg/EGG-INFO/scripts/ybcloud.py", line 15, in <module>
    YbCloud().run()
  File "/opt/yugabyte/devops/venv/lib64/python3.6/site-packages/ybops-0.4-py3.6.egg/ybops/cloud/ybcloud.py", line 56, in run
    self.options.func(self.options)
  File "/opt/yugabyte/devops/venv/lib64/python3.6/site-packages/ybops-0.4-py3.6.egg/ybops/cloud/common/method.py", line 74, in callback_wrapper
    self.callback(args)
  File "/opt/yugabyte/devops/venv/lib64/python3.6/site-packages/ybops-0.4-py3.6.egg/ybops/cloud/azure/method.py", line 79, in callback
    super(AzureProvisionInstancesMethod, self).callback(args)
  File "/opt/yugabyte/devops/venv/lib64/python3.6/site-packages/ybops-0.4-py3.6.egg/ybops/cloud/common/method.py", line 441, in callback
    self.create_method.callback(args)
  File "/opt/yugabyte/devops/venv/lib64/python3.6/site-packages/ybops-0.4-py3.6.egg/ybops/cloud/azure/method.py", line 61, in callback
    super(AzureCreateInstancesMethod, self).callback(args)
  File "/opt/yugabyte/devops/venv/lib64/python3.6/site-packages/ybops-0.4-py3.6.egg/ybops/cloud/common/method.py", line 326, in callback
    self.preprovision(args)
  File "/opt/yugabyte/devops/venv/lib64/python3.6/site-packages/ybops-0.4-py3.6.egg/ybops/cloud/common/method.py", line 353, in preprovision
    host_info = self.wait_for_host(args)
  File "/opt/yugabyte/devops/venv/lib64/python3.6/site-packages/ybops-0.4-py3.6.egg/ybops/cloud/common/method.py", line 375, in wait_for_host
    args.private_key_file):
  File "/opt/yugabyte/devops/venv/lib64/python3.6/site-packages/ybops-0.4-py3.6.egg/ybops/utils/__init__.py", line 441, in wait_for_ssh
    "Timed out trying to SSH to instance: {}:{}".format(host_ip, ssh_port))
ybops.common.exceptions.YBOpsRuntimeError: Runtime error: Timed out trying to SSH to instance: 10.12.16.33:22.`
