### ISSUE TITLE
[Platform] Failure on invocation of createProvider

### ISSUE THREAD

**Issue by SergeyPotachev** [yugabyte/yugabyte-db#8970]
itest testonpremuniverse-onprem failed with the error:
Failure response status code 500 for URL https://www.google.com/url?q=http://XXX.XXX.XXX.XXX:80/api/customers/1c3...ea-f48818072e27/providers&source=gmail-imap&ust=1624562798000000&usg=AOvVaw24BJiJ300id559BM_Er5UQ

The exception from YW logs is:
```
play.api.UnexpectedException: Unexpected exception[NullPointerException: null]
        at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:277)
        at play.api.http.HttpErrorHandlerExceptions.throwableToUsefulException(HttpErrorHandler.scala)
        at play.http.DefaultHttpErrorHandler.throwableToUsefulException(DefaultHttpErrorHandler.java:231)
        at play.http.DefaultHttpErrorHandler.onServerError(DefaultHttpErrorHandler.java:186)
        at com.yugabyte.yw.common.YWErrorHandler.onServerError(YWErrorHandler.java:52)
        at play.core.j.JavaHttpErrorHandlerAdapter.$anonfun$onServerError$1(JavaHttpErrorHandlerAdapter.scala:24)
        at play.core.j.JavaHelpers.$anonfun$invokeWithContext$1(JavaHelpers.scala:305)
        at play.core.j.JavaHelpers.withContext(JavaHelpers.scala:316)
        at play.core.j.JavaHelpers.withContext$(JavaHelpers.scala:312)
        at play.core.j.JavaHelpers$.withContext(JavaHelpers.scala:325)
        at play.core.j.JavaHelpers.invokeWithContext(JavaHelpers.scala:304)
        at play.core.j.JavaHelpers.invokeWithContext$(JavaHelpers.scala:299)
        at play.core.j.JavaHelpers$.invokeWithContext(JavaHelpers.scala:325)
        at play.core.j.JavaHttpErrorHandlerAdapter.onServerError(JavaHttpErrorHandlerAdapter.scala:24)
        at play.core.server.AkkaHttpServer$$anonfun$1.applyOrElse(AkkaHttpServer.scala:434)
        at play.core.server.AkkaHttpServer$$anonfun$1.applyOrElse(AkkaHttpServer.scala:432)
        at scala.concurrent.Future.$anonfun$recoverWith$1(Future.scala:417)
        at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:92)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:92)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:49)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.NullPointerException: null
        at com.yugabyte.yw.models.Provider.setConfig(Provider.java:82)
        at com.yugabyte.yw.models.Provider.create(Provider.java:152)
        at com.yugabyte.yw.models.Provider.create(Provider.java:138)
        at com.yugabyte.yw.controllers.CloudProviderService.createProvider(CloudProviderService.java:106)
        at com.yugabyte.yw.controllers.CloudProviderController.create(CloudProviderController.java:79)
        at v1.Routes$$anonfun$routes$1.$anonfun$applyOrElse$36(Routes.scala:3834)
        at play.core.routing.HandlerInvokerFactory$$anon$6.resultCall(HandlerInvoker.scala:143)
        at play.core.routing.HandlerInvokerFactory$$anon$6.resultCall(HandlerInvoker.scala:142)
        at play.core.routing.HandlerInvokerFactory$JavaActionInvokerFactory$$anon$3$$anon$4$$anon$5.invocation(HandlerInvoker.scala:116)
        at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:112)

```

Also I don't see any failed tasks in logs at this time.

**Comment by sb-yb** [comment]
Issue seems to be that the config `None` in python  that gets serialized  NullNode and deserialized to java null. It overwrites the field's default value. Luckily we have a solution in jackson 2.9.
