### ISSUE TITLE
[Platform] Failed k8s universe expansion (due to insufficient cluster resources) should be recoverable

### ISSUE THREAD

**Issue by jvigil-yugabyte** [yugabyte/yugabyte-db#9145]
When a Universe deployed on Kubernetes is expanded via the Platform (by increasing number of nodes) and there is insufficient CPU/memory in the Kubernetes cluster for the requested number of pods, the Platform enters an error state that requires manual intervention to fix.

The Platform should provide some means to recover from this failure. Perhaps the Platform could allow the user to reduce the number of pods, or perform a rollback of the expansion.

```
jason@jv-work:~/code/charts/stable/yugabyte$ kubectl get all -n universe
NAME               READY   STATUS    RESTARTS   AGE
pod/yb-master-0    2/2     Running   0          10m
pod/yb-tserver-0   2/2     Running   0          10m
pod/yb-tserver-1   2/2     Running   0          6m23s
pod/yb-tserver-2   2/2     Running   0          6m23s
pod/yb-tserver-6   0/2     Pending   0          5m32s
pod/yb-tserver-5   2/2     Running   0          5m32s
pod/yb-tserver-3   0/2     Pending   0          5m32s
pod/yb-tserver-4   0/2     Pending   0          5m32s

NAME                  TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)                                                                      AGE
service/yb-masters    ClusterIP   None         <none>        7000/TCP,7100/TCP                                                            10m
service/yb-tservers   ClusterIP   None         <none>        9000/TCP,12000/TCP,11000/TCP,13000/TCP,9100/TCP,6379/TCP,9042/TCP,5433/TCP   10m

NAME                          READY   AGE
statefulset.apps/yb-master    1/1     10m
statefulset.apps/yb-tserver   4/7     10m
```

```
2021-06-29 22:05:39,213 [ERROR] from SubTaskGroup in TaskPool-2 - Failed to execute task {"errorString":null,"nodeExporterUser":"prometheus","deviceInfo":null,"universeUUID":"1926b744-b357-405d-b8fd-d732e269b4bc","expectedUniverseVersion":0,"cmkArn":null,"encryptionAtRestConfig":{"encryptionAtRestEnabled":false,"kmsConfigUUID":null,"opType":"UNDEFINED","type":"DATA_KEY"},"nodeDetailsSet":null,"communicationPorts":{"masterHttpPort":7000,"masterRpcPort":7100,"tserverHttpPort":9000,"tserverRpcPort":9100,"redisServerHttpPort":11000,"redisServerRpcPort":6379,"yqlServerHttpPort":12000,"yqlServerRpcPort":9042,"ysqlServerHttpPort":13000,"ysqlServerRpcPort":5433,"nodeExporterPort":9300},"extraDependencies":{"installNodeExporter":true},"firstTry":true,"providerUUID":"f24e0296-ee0f-48e6-b53a-a99157e093fe","commandType":"HELM_UPGRADE","nodePrefix":"yb-dev-test","namespace":"universe","ybSoftwareVersion":null,"enableNodeToNodeEncrypt":true,"enableClientToNodeEncrypt":true,"rootCA":"0b7bdaa7-b3ca-40b0-8eba-452cfa575071","serverType":"TSERVER","tserverPartition":0,"masterPartition":0,"masterAddresses":null,"placementInfo":{"cloudList":[{"uuid":"f24e0296-ee0f-48e6-b53a-a99157e093fe","code":"kubernetes","regionList":[{"uuid":"c713a2ba-a0e5-4a4a-ad34-c9b85c59472f","code":"us-west","name":"US West","azList":[{"uuid":"d1338ec6-4767-48a5-bc18-5ac8708ac44a","name":"default","replicationFactor":1,"subnet":null,"numNodesInAZ":7,"isAffinitized":true,"affinitized":true}]}]}]},"config":{"OVERRIDES":"","STORAGE_CLASS":"microk8s-hostpath","KUBECONFIG":"/opt/yugabyte/yugaware/data/keys/f24e0296-ee0f-48e6-b53a-a99157e093fe/c713a2ba-a0e5-4a4a-ad34-c9b85c59472f/d1338ec6-4767-48a5-bc18-5ac8708ac44a/yugabyte-helm.conf","KUBENAMESPACE":"universe"}}, hit error.
java.util.concurrent.ExecutionException: java.lang.RuntimeException: 0/1 nodes are available: 1 Insufficient cpu.
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.yugabyte.yw.commissioner.SubTaskGroup.waitFor(SubTaskGroup.java:182)
	at com.yugabyte.yw.commissioner.SubTaskGroupQueue.run(SubTaskGroupQueue.java:39)
	at com.yugabyte.yw.commissioner.tasks.EditKubernetesUniverse.run(EditKubernetesUniverse.java:225)
	at com.yugabyte.yw.commissioner.TaskRunner.run(TaskRunner.java:146)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: 0/1 nodes are available: 1 Insufficient cpu.
	at com.yugabyte.yw.commissioner.AbstractTaskBase.processShellResponse(AbstractTaskBase.java:113)
	at com.yugabyte.yw.commissioner.tasks.subtasks.KubernetesCommandExecutor.run(KubernetesCommandExecutor.java:222)
	... 5 common frames omitted
2021-06-29 22:05:39,215 [ERROR] from SubTaskGroupQueue in TaskPool-2 - SubTaskGroup 'HelmInstall : completed 0 out of 1 tasks.' waitFor() returned failed status.
2021-06-29 22:05:39,216 [ERROR] from EditKubernetesUniverse in TaskPool-2 - Error executing task EditKubernetesUniverse(1926b744-b357-405d-b8fd-d732e269b4bc), error='HelmInstall : completed 0 out of 1 tasks. failed.'
java.lang.RuntimeException: HelmInstall : completed 0 out of 1 tasks. failed.
	at com.yugabyte.yw.commissioner.SubTaskGroupQueue.run(SubTaskGroupQueue.java:52)
	at com.yugabyte.yw.commissioner.tasks.EditKubernetesUniverse.run(EditKubernetesUniverse.java:225)
	at com.yugabyte.yw.commissioner.TaskRunner.run(TaskRunner.java:146)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by hsiaosu-yb** [comment]
May need to discuss how to handle this -- should we prevent this from happening in the first place, for example?

**Comment by jvigil-yugabyte** [comment]
Would propose a different approach. It's impossible to ensure that the amount of resources will remain static on the k8s cluster as there could be many things changing at once. We cannot ensure the yugabyte database is the only application running on the k8s cluster, or the amount of resources available in the k8s cluster will remain constant. From the kuberentes controller architecture documentation (https://kubernetes.io/docs/concepts/architecture/controller/#desired-vs-current):
> Kubernetes takes a cloud-native view of systems, and is able to handle constant change.
> Your cluster could be changing at any point as work happens and control loops automatically fix failures. This means that, potentially, your cluster never reaches a stable state.
> As long as the controllers for your cluster are running and able to make useful changes, it doesn't matter if the overall state is stable or not.

So, to follow these principles, we should allow the user to continue to make useful changes, such as reducing the desired universe size despite never fully achieving the previously desired state (of expanding beyond available resources).
