### ISSUE TITLE
[Platform] downloadNodeLogs throws 500 after recent change

### ISSUE THREAD

**Issue by sb-yb** [yugabyte/yugabyte-db#9209]
```
Caused by: java.lang.RuntimeException: There is no HTTP Context available from here.
	at play.mvc.Http$Context.current(Http.java:65)
	at play.mvc.Controller.response(Controller.java:78)
	at com.yugabyte.yw.controllers.UniverseInfoController.lambda$downloadNodeLogs$0(UniverseInfoController.java:192)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
	... 5 common frames omitted
```
This is because we are no longer using ec.current to run async work.

**Comment by sb-yb** [comment]
I believe that this is broken because we started using try with resource and as a result input stream being returned in resul is closed abruptly. 
I 'll  add the missing unit test for this and confirm that.

**Comment by sb-yb** [comment]
Backported
