### ISSUE TITLE
[docdb] PITR: core dump during running YSQL restore

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#9259]
```
(gdb) bt full
#0  0x00007fe4a41413c1 in MakeDoneCallback<boost::multi_index::multi_index_container<std::unique_ptr<yb::master::RestorationState>, boost::multi_index::indexed_by<boost::multi_index::hashed_unique<boost::multi_index::const_mem_fun<yb::master::RestorationState, const yb::StronglyTypedUuid<yb::TxnSnapshotRestorationId_Tag>&, &yb::master::RestorationState::restoration_id> > > >, std::_Bind<std::_Mem_fn<void (yb::master::MasterSnapshotCoordinator::Impl::*)(yb::master::RestorationState*, long int)>(yb::master::MasterSnapshotCoordinator::Impl*, std::_Placeholder<1>, long int)> > (post_process=..., tablet_id=..., key=..., collection=..., mutex=0x2e25208) at ../../src/yb/master/master_snapshot_coordinator.cc:126
No locals.
#1  DoRestore (phase=yb::master::(anonymous namespace)::kPostSysCatalogLoad, leader_term=1, phase=yb::master::(anonymous namespace)::kPostSysCatalogLoad, restore_tablets=..., restoration_id=..., restore_at=..., snapshot_id=..., this=<optimized out>,
    this=<optimized out>, this=<optimized out>, this=<optimized out>, this=<optimized out>, this=<optimized out>, this=<optimized out>, this=<optimized out>) at ../../src/yb/master/master_snapshot_coordinator.cc:1081
        task = {<std::__shared_ptr<yb::master::AsyncTabletSnapshotOp, (__gnu_cxx::_Lock_policy)2>> = {_M_ptr = 0x3468010, _M_refcount = {_M_pi = 0x3468000}}, <No data fields>}
        __for_range = @0x7fe4293f7a60: {<std::_Vector_base<scoped_refptr<yb::master::TabletInfo>, std::allocator<scoped_refptr<yb::master::TabletInfo> > >> = {
            _M_impl = {<std::allocator<scoped_refptr<yb::master::TabletInfo> >> = {<__gnu_cxx::new_allocator<scoped_refptr<yb::master::TabletInfo> >> = {<No data fields>}, <No data fields>}, _M_start = 0x8d14300, _M_finish = 0x8d14600,
              _M_end_of_storage = 0x8d14600}}, <No data fields>}
        snapshot_id_str = {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>},
            _M_p = 0x2c9131e0 "\237\247\320\r\t\231OU\220\232\213\202\203\002\242\227"}, _M_string_length = 16, {_M_local_buf = "\020\000\000\000\000\000\000\000Š\v\225\344\177\000", _M_allocated_capacity = 16}}
        tablet_infos = {<std::_Vector_base<scoped_refptr<yb::master::TabletInfo>, std::allocator<scoped_refptr<yb::master::TabletInfo> > >> = {
            _M_impl = {<std::allocator<scoped_refptr<yb::master::TabletInfo> >> = {<__gnu_cxx::new_allocator<scoped_refptr<yb::master::TabletInfo> >> = {<No data fields>}, <No data fields>}, _M_start = 0x8d14300, _M_finish = 0x8d14600,
              _M_end_of_storage = 0x8d14600}}, <No data fields>}
        restore_sys_catalog = false
        snapshot_tablets = {
          _M_h = {<std::__detail::_Hashtable_base<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__detail::_Identity, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Hashtable_traits<true, true, true> >> = {<std::__detail::_Hash_code_base<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__detail::_Identity, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, true>> = {<std::__detail::_Hashtable_ebo_helper<0, std::__detail::_Identity, true>> = {<std::__detail::_Identity> = {<No data fields>}, <No data fields>}, <std::__detail::_Hashtable_ebo_helper<1, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, true>> = {<std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >> = {<std::__hash_base<unsigned long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >> = {<No data fields>}, <No data fields>}, <No data fields>}, <std::__detail::_Hashtable_ebo_helper<2, std::__detail::_Mod_range_hashing, true>> = {<std::__detail::_Mod_range_hashing> = {<No data fields>}, <No data fields>}, <No data fields>}, <std::__detail::_Hashtable_ebo_helper<0, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, true>> = {<std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >> = {<std::binary_function<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool>> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, <std::__detail::_Map_base<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::__detail::_Identity, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, true, true>, true>> = {<No data fields>}, <std::__detail::_Insert<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::__detail::_Identity, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, true, true>, true, true>> = {<std::__detail::_Insert_base<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::__detail::_Identity, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, true, true> >> = {<No data fields>}, <No data fields>}, <std::__detail::_Rehash_base<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::__detail::_Identity, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, true, true> >> = {<No data fields>}, <std::__detail::_Equality<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::__detail::_Identity, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, true, true>, true>> = {<No data fields>}, <std::__detail::_Hashtable_alloc<std::allocator<std::__detail::_Hash_node<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, true> > >> = {<std::__detail::_Hashtable_ebo_helper<0, std::allocator<std::__detail::_Hash_node<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, true> >, true>> = {<std::allocator<std::__detail::_Hash_node<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, true> >> = {<__gnu_cxx::new_allocator<std::__detail::_Hash_node<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, true> >> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, _M_buckets = 0x4eb6480, _M_bucket_count = 47, _M_before_begin = {_M_nxt = 0x4eb19290}, _M_element_count = 24, _M_rehash_policy = {
              static _S_growth_factor = 2, _M_max_load_factor = 1, _M_next_resize = 47}, _M_single_bucket = 0x0}}
#2  yb::master::MasterSnapshotCoordinator::Impl::SysCatalogLoaded (this=0x2e25200, term=1) at ../../src/yb/master/master_snapshot_coordinator.cc:519
        status = {state_ = {px = 0x407bb170}}
        restore_tablets = {<std::_Vector_base<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >> = {
---Type <return> to continue, or q <return> to quit---
            _M_impl = {<std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >> = {<__gnu_cxx::new_allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >> = {<No data fields>}, <No data fields>}, _M_start = 0x8c7d000, _M_finish = 0x8c7dc00, _M_end_of_storage = 0x8c7e000}}, <No data fields>}
        __for_range = @0x7fe4293f7a20: {<std::_Vector_base<std::shared_ptr<yb::master::SnapshotScheduleRestoration>, std::allocator<std::shared_ptr<yb::master::SnapshotScheduleRestoration> > >> = {
            _M_impl = {<std::allocator<std::shared_ptr<yb::master::SnapshotScheduleRestoration> >> = {<__gnu_cxx::new_allocator<std::shared_ptr<yb::master::SnapshotScheduleRestoration> >> = {<No data fields>}, <No data fields>},
              _M_start = 0x487baf0, _M_finish = 0x487bb00, _M_end_of_storage = 0x487bb00}}, <No data fields>}
        postponed_restores = {<std::_Vector_base<std::shared_ptr<yb::master::SnapshotScheduleRestoration>, std::allocator<std::shared_ptr<yb::master::SnapshotScheduleRestoration> > >> = {
            _M_impl = {<std::allocator<std::shared_ptr<yb::master::SnapshotScheduleRestoration> >> = {<__gnu_cxx::new_allocator<std::shared_ptr<yb::master::SnapshotScheduleRestoration> >> = {<No data fields>}, <No data fields>},
              _M_start = 0x487baf0, _M_finish = 0x487bb00, _M_end_of_storage = 0x487bb00}}, <No data fields>}
#3  0x00007fe4a4052a2d in yb::master::CatalogManager::LoadSysCatalogDataTask (this=0x2cc4000) at ../../src/yb/master/catalog_manager.cc:847
        consensus = {<std::__shared_ptr<yb::consensus::Consensus, (__gnu_cxx::_Lock_policy)2>> = {_M_ptr = 0x3eb5450, _M_refcount = {_M_pi = 0x3eb5440}}, <No data fields>}
        s = {state_ = {px = 0x0}}
#4  0x00007fe4991d0c34 in yb::ThreadPool::DispatchThread (this=0x2e20000, permanent=false) at ../../src/yb/util/threadpool.cc:611
        wall_us = <optimized out>
        token = 0x2a92600
        task = {runnable = {<std::__shared_ptr<yb::Runnable, (__gnu_cxx::_Lock_policy)2>> = {_M_ptr = 0x5fb72b90, _M_refcount = {_M_pi = 0x5fb72b80}}, <No data fields>}, trace = 0x0, submit_time = {static kNanosecondsPerMicrosecond = 1000,
            static kMicrosecondsPerMillisecond = 1000, static kMillisecondsPerSecond = 1000, static kSecondsPerMinute = 60, static kNanosecondsPerMillisecond = 1000000, static kMicrosecondsPerSecond = 1000000,
            static kNanosecondsPerSecond = 1000000000, static kNanosecondsPerMinute = 60000000000, static kMin = {static kNanosecondsPerMicrosecond = 1000, static kMicrosecondsPerMillisecond = 1000, static kMillisecondsPerSecond = 1000,
              static kSecondsPerMinute = 60, static kNanosecondsPerMillisecond = 1000000, static kMicrosecondsPerSecond = 1000000, static kNanosecondsPerSecond = 1000000000, static kNanosecondsPerMinute = 60000000000,
              static kMin = <same as static member of an already seen type>, static kMax = {static kNanosecondsPerMicrosecond = 1000, static kMicrosecondsPerMillisecond = 1000, static kMillisecondsPerSecond = 1000, static kSecondsPerMinute = 60,
                static kNanosecondsPerMillisecond = 1000000, static kMicrosecondsPerSecond = 1000000, static kNanosecondsPerSecond = 1000000000, static kNanosecondsPerMinute = 60000000000,
                static kMin = <same as static member of an already seen type>, static kMax = <same as static member of an already seen type>, static kUninitialized = {static kNanosecondsPerMicrosecond = 1000,
                  static kMicrosecondsPerMillisecond = 1000, static kMillisecondsPerSecond = 1000, static kSecondsPerMinute = 60, static kNanosecondsPerMillisecond = 1000000, static kMicrosecondsPerSecond = 1000000,
                  static kNanosecondsPerSecond = 1000000000, static kNanosecondsPerMinute = 60000000000, static kMin = <same as static member of an already seen type>, static kMax = <same as static member of an already seen type>,
                  static kUninitialized = <same as static member of an already seen type>, value_ = {__d = {__r = 0}}}, value_ = {__d = {__r = 9223372036854775807}}}, static kUninitialized = <same as static member of an already seen type>, value_ = {
                __d = {__r = 1}}}, static kMax = <same as static member of an already seen type>, static kUninitialized = <same as static member of an already seen type>, value_ = {__d = {__r = 4180299155617470}}}}
        _adopt_trace = {old_trace_ = 0x0, trace_ = {ptr_ = 0x0}, is_enabled_ = false}
        now = {static kNanosecondsPerMicrosecond = 1000, static kMicrosecondsPerMillisecond = 1000, static kMillisecondsPerSecond = 1000, static kSecondsPerMinute = 60, static kNanosecondsPerMillisecond = 1000000,
          static kMicrosecondsPerSecond = 1000000, static kNanosecondsPerSecond = 1000000000, static kNanosecondsPerMinute = 60000000000, static kMin = {static kNanosecondsPerMicrosecond = 1000, static kMicrosecondsPerMillisecond = 1000,
            static kMillisecondsPerSecond = 1000, static kSecondsPerMinute = 60, static kNanosecondsPerMillisecond = 1000000, static kMicrosecondsPerSecond = 1000000, static kNanosecondsPerSecond = 1000000000,
            static kNanosecondsPerMinute = 60000000000, static kMin = <same as static member of an already seen type>, static kMax = {static kNanosecondsPerMicrosecond = 1000, static kMicrosecondsPerMillisecond = 1000,
              static kMillisecondsPerSecond = 1000, static kSecondsPerMinute = 60, static kNanosecondsPerMillisecond = 1000000, static kMicrosecondsPerSecond = 1000000, static kNanosecondsPerSecond = 1000000000,
              static kNanosecondsPerMinute = 60000000000, static kMin = <same as static member of an already seen type>, static kMax = <same as static member of an already seen type>, static kUninitialized = {
                static kNanosecondsPerMicrosecond = 1000, static kMicrosecondsPerMillisecond = 1000, static kMillisecondsPerSecond = 1000, static kSecondsPerMinute = 60, static kNanosecondsPerMillisecond = 1000000,
                static kMicrosecondsPerSecond = 1000000, static kNanosecondsPerSecond = 1000000000, static kNanosecondsPerMinute = 60000000000, static kMin = <same as static member of an already seen type>,
                static kMax = <same as static member of an already seen type>, static kUninitialized = <same as static member of an already seen type>, value_ = {__d = {__r = 0}}}, value_ = {__d = {__r = 9223372036854775807}}},
            static kUninitialized = <same as static member of an already seen type>, value_ = {__d = {__r = 1}}}, static kMax = <same as static member of an already seen type>, static kUninitialized = <same as static member of an already seen type>,
          value_ = {__d = {__r = 4180299155793495}}}
        queue_time_us = <optimized out>
        unique_lock = {lock_ = 0x2e20040, owned_ = false}
#5  0x00007fe4991cd3ef in operator() (this=0x86b9138) at /home/yugabyte/yb-software/yugabyte-2.7.2.38-sergei-release-centos-x86_64/linuxbrew-x/Cellar/gcc/5.5.0_4/include/c++/5.5.0/functional:2267
No locals.
#6  yb::Thread::SuperviseThread (arg=0x86b90e0) at ../../src/yb/util/thread.cc:771
        __clframe = {__cancel_routine = 0x7fe4991cc950 <yb::Thread::FinishThread(void*)>, __cancel_arg = 0x86b90e0, __do_it = 1, __cancel_type = <optimized out>}
        t = 0x86b90e0
        name = {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x5fb86600 "leader-initialization [worker]-21441"}, _M_string_length = 36, {
            _M_local_buf = "$\000\000\000\000\000\000\000\f\300\035\000\000\000\000", _M_allocated_capacity = 36}}
        thread_mgr_ref = {<std::__shared_ptr<yb::(anonymous namespace)::ThreadMgr, (__gnu_cxx::_Lock_policy)2>> = {_M_ptr = <optimized out>, _M_refcount = {_M_pi = 0x2a86c60}}, <No data fields>}
---Type <return> to continue, or q <return> to quit---
        thread_ref = {ptr_ = 0x86b90e0}
        loop_count = <optimized out>
#7  0x00007fe494888694 in start_thread (arg=0x7fe429400700) at pthread_create.c:333
        __res = <optimized out>
        pd = 0x7fe429400700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140617921332992, -7748866801506570025, 0, 140617786744927, 27, 140617921332992, 7763692062370836695, 7764020636054728919}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {
              prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#8  0x00007fe493fc541d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
No locals.
```

Context from Slack: https://yugabyte.slack.com/archives/C01HF6X4HDX/p1626110376158200?thread_ts=1625668253.136200&cid=C01HF6X4HDX

**Comment by karlfunk-ydb** [comment]
@bmatican 
Output from (gdb) thread apply all bt is attached
[threadapplyallbt.txt](https://github.com/yugabyte/yugabyte-db/files/6831231/threadapplyallbt.txt)

(note I had to use script to capture and then clean the control characters - from inspection the result looks like it's the same as on screen but if something looks strange I can redo more manually)
