### ISSUE TITLE
TestYsqlUpgrade.sharedRelsIndexesWork may fail to find pg_class

### ISSUE THREAD

**Issue by tedyu** [yugabyte/yugabyte-db#9332]
From https://detective-gcp.dev.yugabyte.com/job/github-yugabyte-db-phabricator%2F103178%2Fartifact%2Fjava%2Fyb-pgsql%2Ftarget%2Fsurefire-reports_org.yb.pgsql.TestYsqlUpgrade__sharedRelsIndexesWork%2Forg.yb.pgsql.TestYsqlUpgrade-output.txt?class=org.yb.pgsql.TestYsqlUpgrade&max_lines=3000&name=sharedRelsIndexesWork&start_line=3001 
```
ERROR | 122.192000 | main | BaseYBTest.java:240 | YB Java test failed: class="org.yb.pgsql.TestYsqlUpgrade", method="sharedRelsIndexesWork"
-- | -- | -- | -- | --
4847 | org.postgresql.util.PSQLException: FATAL: Not found: Error loading table with oid 1259 in database with oid 16385: The object '00004001000030008000000000000000.pg_class' does not exist
4848 | at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
4849 | at org.postgresql.core.v3.QueryExecutorImpl.readStartupMessages(QueryExecutorImpl.java:2559)
4850 | at org.postgresql.core.v3.QueryExecutorImpl.<init>(QueryExecutorImpl.java:133)
4851 | at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:250)
4852 | at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
4853 | at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:195)
4854 | at org.postgresql.Driver.makeConnection(Driver.java:454)
4855 | at org.postgresql.Driver.connect(Driver.java:256)
4856 | at java.sql.DriverManager.getConnection(DriverManager.java:664)
4857 | at java.sql.DriverManager.getConnection(DriverManager.java:208)
4858 | at org.yb.pgsql.BasePgSQLTest$ConnectionBuilder.connect(BasePgSQLTest.java:1806)
4859 | at org.yb.pgsql.TestYsqlUpgrade.sharedRelsIndexesWork(TestYsqlUpgrade.java:391)
```
It seems pg_class was deleted earlier:
```
[m-3L] I   110.761877  27614   catalog_manager.cc:4494 Marking table as DELETED: pg_class [id=000040010000300080000000000004eb]
```

**Comment by frozenspider** [comment]
Full log for reference: [org.yb.pgsql.TestYsqlUpgrade-output.txt](https://github.com/yugabyte/yugabyte-db/files/6831517/org.yb.pgsql.TestYsqlUpgrade-output.txt)
