### ISSUE TITLE
signed integer overflow during ConcurrentPod::Load()

### ISSUE THREAD

**Issue by tedyu** [yugabyte/yugabyte-db#9335]
Saw the following for centos-clang7-asan build:
```
[m-1] /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20210708193823-e7937bbf4a-centos7-clang7/installed/asan/libcxx/include/c++/v1/chrono:1217:35: runtime error: signed integer overflow: 4439543105544 - -9223372036853775808 cannot be represented in type 'long long'
[m-1]     #0 0x7f7badc3830e in std::__1::common_type<std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> >, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > >::type std::__1::chrono::operator-<long long, std::__1::ratio<1l, 1000000000l>, long long, std::__1::ratio<1l, 1000000000l> >(std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > const&, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > const&) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20210708193823-e7937bbf4a-centos7-clang7/installed/asan/libcxx/include/c++/v1/chrono:1217:35
[m-1]     #1 0x7f7badc3830e in std::__1::common_type<std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> >, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > >::type std::__1::chrono::operator-<yb::CoarseMonoClock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> >, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > >(std::__1::chrono::time_point<yb::CoarseMonoClock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > > const&, std::__1::chrono::time_point<yb::CoarseMonoClock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > > const&) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20210708193823-e7937bbf4a-centos7-clang7/installed/asan/libcxx/include/c++/v1/chrono:1535
[m-1]     #2 0x7f7badc3830e in yb::ConcurrentPod<boost::asio::ip::basic_endpoint<boost::asio::ip::tcp> >::Load() const /nfusr/centos-gcp-cloud/jenkins-worker-cw28jt/jenkins/jenkins-github-yugabyte-db-phabricator-103538/build/asan-clang7-dynamic-ninja/../../src/yb/util/concurrent_pod.h:42
[m-1]     #3 0x7f7badc3272f in yb::rpc::Proxy::DoAsyncRequest(yb::rpc::RemoteMethod const*, google::protobuf::Message const&, google::protobuf::Message*, yb::rpc::RpcController*, std::__1::function<void ()>, bool) /nfusr/centos-gcp-cloud/jenkins-worker-cw28jt/jenkins/jenkins-github-yugabyte-db-phabricator-103538/build/asan-clang7-dynamic-ninja/../../src/yb/rpc/proxy.cc:200:28
[m-1]     #4 0x7f7badc31d26 in yb::rpc::Proxy::AsyncRequest(yb::rpc::RemoteMethod const*, google::protobuf::Message const&, google::protobuf::Message*, yb::rpc::RpcController*, std::__1::function<void ()>) /nfusr/centos-gcp-cloud/jenkins-worker-cw28jt/jenkins/jenkins-github-yugabyte-db-phabricator-103538/build/asan-clang7-dynamic-ninja/../../src/yb/rpc/proxy.cc:123:3
[m-1]     #5 0x7f7baece94a8 in yb::consensus::ConsensusServiceProxy::GetNodeInstanceAsync(yb::consensus::GetNodeInstanceRequestPB const&, yb::consensus::GetNodeInstanceResponsePB*, yb::rpc::RpcController*, std::__1::function<void ()>) /nfusr/centos-gcp-cloud/jenkins-worker-cw28jt/jenkins/jenkins-github-yugabyte-db-phabricator-103538/build/asan-clang7-dynamic-ninja/src/yb/consensus/consensus.proxy.cc:72:11
[m-1]     #6 0x7f7bb8f9e287 in yb::consensus::SetPermanentUuidForRemotePeer(yb::rpc::ProxyCache*, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> >, std::__1::vector<yb::HostPort, std::__1::allocator<yb::HostPort> > const&, yb::consensus::RaftPeerPB*) /nfusr/centos-gcp-cloud/jenkins-worker-cw28jt/jenkins/jenkins-github-yugabyte-db-phabricator-103538/build/asan-clang7-dynamic-ninja/../../src/yb/consensus/consensus_peers.cc:625:21
[m-1]     #7 0x7f7bc1c2b34c in yb::master::SysCatalogTable::SetupConfig(yb::master::MasterOptions const&, yb::consensus::RaftConfigPB*) /nfusr/centos-gcp-cloud/jenkins-worker-cw28jt/jenkins/jenkins-github-yugabyte-db-phabricator-103538/build/asan-clang7-dynamic-ninja/../../src/yb/master/sys_catalog.cc:344:5
[m-1]     #8 0x7f7bc1c2a632 in yb::master::SysCatalogTable::CreateNew(yb::FsManager*) /nfusr/centos-gcp-cloud/jenkins-worker-cw28jt/jenkins/jenkins-github-yugabyte-db-phabricator-103538/build/asan-clang7-dynamic-ninja/../../src/yb/master/sys_catalog.cc:317:3
[m-1]     #9 0x7f7bc17f24dc in yb::master::CatalogManager::InitSysCatalogAsync() /nfusr/centos-gcp-cloud/jenkins-worker-cw28jt/jenkins/jenkins-github-yugabyte-db-phabricator-103538/build/asan-clang7-dynamic-ninja/../../src/yb/master/catalog_manager.cc:1499:5
[m-1]     #10 0x7f7bc17f0499 in yb::master::CatalogManager::Init() /nfusr/centos-gcp-cloud/jenkins-worker-cw28jt/jenkins/jenkins-github-yugabyte-db-phabricator-103538/build/asan-clang7-dynamic-ninja/../../src/yb/master/catalog_manager.cc:711:3
[m-1]     #11 0x7f7bc1ad56e7 in yb::master::Master::InitCatalogManager() /nfusr/centos-gcp-cloud/jenkins-worker-cw28jt/jenkins/jenkins-github-yugabyte-db-phabricator-103538/build/asan-clang7-dynamic-ninja/../../src/yb/master/master.cc:283:3
```

**Comment by bmatican** [comment]
Dmitry, Sergei, didn't we just do some test-related work on this?

**Comment by tedyu** [comment]
@bmatican 
I have submitted a patch for this issue.
