### ISSUE TITLE
[Platform] itest failures when creating provider

### ISSUE THREAD

**Issue by sb-yb** [yugabyte/yugabyte-db#9395]
``` 
(     0.104s) Setup Provider : >>> Integration Test Failed <<<
expected string or bytes-like object
```
Fails against 2.6 as well as latest (2.7.2)

**Comment by sb-yb** [comment]
Traceback in stderr. (Would be nice to have this in itest.log)
```
Traceback (most recent call last):
  File "/var/lib/jenkins/code/internal-services/itest/src/test_base.py", line 151, in execute_steps
    step.call()
  File "/var/lib/jenkins/code/internal-services/itest/src/test_base.py", line 52, in call
    ret = self.function()
  File "/var/lib/jenkins/code/internal-services/itest/src/universe_tests/test_onprem_universe.py", line 78, in setup_provider
    self.yugabyte_version)
  File "/var/lib/jenkins/code/internal-services/itest/src/yw_proxy.py", line 157, in get_or_create_provider
    provider_code, provider_name, config, region_name, yugabyte_version)['uuid']
  File "/var/lib/jenkins/code/internal-services/itest/src/yw_proxy.py", line 140, in __create_provider
    route=self.__create_provider_url(yugabyte_version),
  File "/var/lib/jenkins/code/internal-services/itest/src/yw_proxy.py", line 144, in __create_provider_url
    if is_release_current(yugabyte_version, CREATE_PROVIDER_UI_VERSION):
  File "/var/lib/jenkins/code/internal-services/itest/src/release.py", line 27, in is_release_current
    c_match = re.match(RELEASE_VERSION_PATTERN_WITH_BUILD, current_release_version)
  File "/usr/share/python-3.7.7/lib/python3.7/re.py", line 173, in match
    return _compile(pattern, flags).match(string)
TypeError: expected string or bytes-like object
```

Looks like currenr release version is `None`

**Comment by sb-yb** [comment]
This was fixed by https://phabricator.dev.yugabyte.com/D12318.
Looks like this does not link automatically due to it being a different repo.
