### ISSUE TITLE
[Platform] [UnitTest] UpgradeUniverseTest.testResizeNodeUpgrade failure

### ISSUE THREAD

**Issue by sb-yb** [yugabyte/yugabyte-db#9666]
```
2021-08-11 07:25:13.630 [[31merror[0m] UpgradeUniverse.java:331 [TaskPool-0] Error executing task UpgradeUniverse(73244088-3fc1-4d31-8036-83aadaad3690) with error={}.
java.lang.IllegalArgumentException: Provider aws does not have the intended instance type c5.2xlarge
	at com.yugabyte.yw.commissioner.tasks.UpgradeUniverse.verifyParams(UpgradeUniverse.java:146)
	at com.yugabyte.yw.commissioner.tasks.UpgradeUniverse.run(UpgradeUniverse.java:313)
	at com.yugabyte.yw.commissioner.TaskRunner.run(TaskRunner.java:144)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2021-08-11 07:25:13.631 [[31merror[0m] TaskRunner.java:150 [TaskPool-0] Error running task
java.lang.IllegalArgumentException: Provider aws does not have the intended instance type c5.2xlarge
	at com.yugabyte.yw.commissioner.tasks.UpgradeUniverse.verifyParams(UpgradeUniverse.java:146)
	at com.yugabyte.yw.commissioner.tasks.UpgradeUniverse.run(UpgradeUniverse.java:313)
	at com.yugabyte.yw.commissioner.TaskRunner.run(TaskRunner.java:144)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2021-08-11 07:25:13.631 [[37minfo[0m] TaskRunner.java:181 [TaskPool-0] Updating task [taskType : UpgradeUniverse, taskState: Running] to new state Failure
2021-08-11 07:25:13.632 [[37minfo[0m] Commissioner.java:182 [TaskProgressMonitor] Task task-info {taskType : UpgradeUniverse, taskState: Failure}, task {UpgradeUniverse(73244088-3fc1-4d31-8036-83aadaad3690)} has failed.
2021-08-11 07:25:14.644 [[36mdebug[0m] SetUniverseKey.java:147 [application-akka.actor.default-dispatcher-6] Running universe key setter
2021-08-11 07:25:14.646 [[37minfo[0m] Scheduler.java:101 [application-akka.actor.default-dispatcher-6] Running scheduler
2021-08-11 07:25:14.646 [[37minfo[0m] HikariCPModule.scala:79 [application-akka.actor.default-dispatcher-6] Shutting down connection pool.
[error] Test com.yugabyte.yw.commissioner.tasks.UpgradeUniverseTest.testResizeNodeUpgrade failed: org.mockito.exceptions.verification.WantedButNotInvoked: 
[error] Wanted but not invoked:
[error] mockNodeManager.nodeCommand(<any>, <any>);
[error] -> at com.yugabyte.yw.commissioner.tasks.UpgradeUniverseTest.testResizeNodeUpgrade(UpgradeUniverseTest.java:993)
[error] Actually, there were zero interactions with this mock.
[error] , took 1.676 sec
[error]     at com.yugabyte.yw.commissioner.tasks.UpgradeUniverseTest.testResizeNodeUpgrade(UpgradeUniverseTest.java:993)
[error]     ...
```

**Comment by hkandala** [comment]
@vmallepalli has resolved this yesterday
Commit: 2f119695ddadab7cb9c373be45f081d6b14e21a7
