### ISSUE TITLE
[Platform] [Unitetest] Metrcs test flakyness

### ISSUE THREAD

**Issue by sb-yb** [yugabyte/yugabyte-db#9765]
```
[info] Test run started
[info] Test com.yugabyte.yw.models.MetricTest.testAddAndGetByKey started
2021-08-18 08:35:55.236 [[37minfo[0m] HikariCPModule.scala:54 [pool-1-thread-1] Creating Pool for datasource 'default'
2021-08-18 08:35:55.303 [[37minfo[0m] ScopedRuntimeConfig.java:47 [pool-1-thread-1] Created Global ScopedRuntimeConfig
2021-08-18 08:35:55.310 [[36mdebug[0m] PlayInitializer.scala:48 [pool-1-thread-1] Directory for migration files found. db/migration/default
2021-08-18 08:35:55.792 [[37minfo[0m] YWErrorHandler.java:40 [pool-1-thread-1] Created YWErrorHandler
2021-08-18 08:35:55.795 [[33mwarn[0m] ParameterMessageInterpolator.java:28 [pool-1-thread-1] HV000184: ParameterMessageInterpolator has been chosen, EL interpolation will not be supported
2021-08-18 08:35:55.802 [[37minfo[0m] AppInit.java:45 [pool-1-thread-1] Yugaware Application has started
2021-08-18 08:35:55.805 [[37minfo[0m] Universe.java:199 [pool-1-thread-1] Created db entry for universe Test Universe [8fe64e64-6bcd-42ae-a775-5c0b1266fd78]
2021-08-18 08:35:55.805 [[36mdebug[0m] Universe.java:200 [pool-1-thread-1] Details for universe Test Universe [8fe64e64-6bcd-42ae-a775-5c0b1266fd78] : [{"errorString":null,"nodeExporterUser":"prometheus","deviceInfo":null,"universeUUID":"8fe64e64-6bcd-42ae-a775-5c0b1266fd78","expectedUniverseVersion":null,"cmkArn":null,"encryptionAtRestConfig":{"encryptionAtRestEnabled":false,"kmsConfigUUID":null,"opType":"UNDEFINED","type":"DATA_KEY"},"nodeDetailsSet":[],"communicationPorts":{"masterHttpPort":7000,"masterRpcPort":7100,"tserverHttpPort":9000,"tserverRpcPort":9100,"redisServerHttpPort":11000,"redisServerRpcPort":6379,"yqlServerHttpPort":12000,"yqlServerRpcPort":9042,"ysqlServerHttpPort":13000,"ysqlServerRpcPort":5433,"nodeExporterPort":9300},"extraDependencies":{"installNodeExporter":true},"firstTry":true,"clusters":[{"uuid":"ab0ac155-5d4e-4158-b081-cb0f8986cb55","clusterType":"PRIMARY","userIntent":{"universeName":"Test Universe","provider":"b119459f-e048-42ae-a63e-1d98bd7a3035","providerType":"aws","replicationFactor":3,"regionList":null,"preferredRegion":null,"instanceType":null,"numNodes":0,"ybSoftwareVersion":null,"accessKeyCode":null,"deviceInfo":null,"assignPublicIP":true,"useTimeSync":false,"enableYSQL":false,"enableYEDIS":true,"enableNodeToNodeEncrypt":false,"enableClientToNodeEncrypt":false,"enableVolumeEncryption":false,"enableIPV6":false,"enableExposingService":"NONE","awsArnString":null,"useHostname":false,"useSystemd":false,"masterGFlags":{},"tserverGFlags":{},"instanceTags":{}},"index":0}],"currentClusterType":"PRIMARY","nodePrefix":"Test Universe","rootCA":null,"clientRootCA":null,"rootAndClientRootCASame":true,"userAZSelected":false,"resetAZConfig":false,"updateInProgress":false,"backupInProgress":false,"updateSucceeded":true,"universePaused":false,"nextClusterIndex":1,"allowInsecure":true,"setTxnTableWaitCountFlag":false,"itestS3PackagePath":"","remotePackagePath":"","importedState":"NONE","capability":"EDITS_ALLOWED","targetAsyncReplicationRelationships":[],"sourceAsyncReplicationRelationships":[]}].
2021-08-18 08:35:55.808 [[37minfo[0m] HikariCPModule.scala:79 [pool-1-thread-1] Shutting down connection pool.
[error] Test com.yugabyte.yw.models.MetricTest.testAddAndGetByKey failed: java.lang.AssertionError: null, took 0.673 sec
[error]     at com.yugabyte.yw.models.MetricTest.assertMetric(MetricTest.java:134)
[error]     at com.yugabyte.yw.models.MetricTest.testAddAndGetByKey(MetricTest.java:62)
[error]     ...
[info] Test com.yugabyte.yw.models.MetricTest.testUpdateAndGetByKey started
```

Test run is at: https://jenkins.dev.yugabyte.com/job/platform-phabricator-pipeline/1835/

**Comment by sb-yb** [comment]
Had talked to alkzander about this and he was going to take a look.
