### ISSUE TITLE
ybase: fix segfault on cmeta_->GetRoleAndTerm()

### ISSUE THREAD

**Issue by jaki** [yugabyte/yugabyte-db#9828]
Jira Link: [DB-2231](https://yugabyte.atlassian.net/browse/DB-2231)
Encountered a segfault.

```sh
./yb_build.sh --cxx-test pgwrapper_pg_index_backfill-test --gtest_filter PgIndexBackfillTest.CreateIndexSimultaneously -n 100 --tp 1
```

One of the runs gave

```
Core was generated by `yb-tserver --fs_data_dirs=/tmp/yb_tests__2021-08-25T15_22_27__1496.13116.26584/'.
Program terminated with signal 11, Segmentation fault.
#0  0x00007f3ce6f84ad8 in std::unique_ptr<yb::consensus::ConsensusMetadata, std::default_delete<yb::consensus::ConsensusMetadata> >::get (this=0x3339393236312f11) at /opt/yb-build/brew/linuxbrew-20181203T161736v9-3ba4c2ed9b0587040949a4a9a95b576f520bae/C
ellar/gcc/5.5.0_4/include/c++/5.5.0/bits/unique_ptr.h:308
308           { return std::get<0>(_M_t); }
warning: File "/opt/yb-build/brew/linuxbrew-20181203T161736v9-3ba4c2ed9b0587040949a4a9a95b576f520bae/Cellar/gcc/5.5.0_4/lib/libstdc++.so.6.0.21-gdb.py" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load:/us
r/bin/mono-gdb.py".
#0  0x00007f3ce6f84ad8 in std::unique_ptr<yb::consensus::ConsensusMetadata, std::default_delete<yb::consensus::ConsensusMetadata> >::get (this=0x3339393236312f11) at /opt/yb-build/brew/linuxbrew-20181203T161736v9-3ba4c2ed9b0587040949a4a9a95b576f520bae/C
ellar/gcc/5.5.0_4/include/c++/5.5.0/bits/unique_ptr.h:308
#1  0x00007f3ce6f80e74 in std::unique_ptr<yb::consensus::ConsensusMetadata, std::default_delete<yb::consensus::ConsensusMetadata> >::operator-> (this=0x3339393236312f11) at /opt/yb-build/brew/linuxbrew-20181203T161736v9-3ba4c2ed9b0587040949a4a9a95b576f5
20bae/Cellar/gcc/5.5.0_4/include/c++/5.5.0/bits/unique_ptr.h:302
#2  0x00007f3ce1dff6fc in yb::consensus::ReplicaState::LogPrefix[abi:cxx11]() const (this=0x3339393236312e79) at ../../src/yb/consensus/replica_state.cc:1043
#3  0x00007f3ce1dcafd2 in yb::consensus::RaftConsensus::LogPrefix[abi:cxx11]() (this=0x675f690) at ../../src/yb/consensus/raft_consensus.cc:2876
#4  0x00007f3ce1db87c2 in yb::consensus::RaftConsensus::RunLeaderElectionResponseRpcCallback (this=0x675f690, election_state=...) at ../../src/yb/consensus/raft_consensus.cc:972
#5  0x00007f3ce1dec721 in std::_Mem_fn_base<void (yb::consensus::RaftConsensus::*)(std::shared_ptr<yb::consensus::RaftConsensus::RunLeaderElectionState>), true>::operator()<std::shared_ptr<yb::consensus::RaftConsensus::RunLeaderElectionState>&, void> (t
his=0x2d11830, __object=0x675f690) at /opt/yb-build/brew/linuxbrew-20181203T161736v9-3ba4c2ed9b0587040949a4a9a95b576f520bae/Cellar/gcc/5.5.0_4/include/c++/5.5.0/functional:600
#6  0x00007f3ce1de9eb1 in std::_Bind<std::_Mem_fn<void (yb::consensus::RaftConsensus::*)(std::shared_ptr<yb::consensus::RaftConsensus::RunLeaderElectionState>)> (yb::consensus::RaftConsensus*, std::shared_ptr<yb::consensus::RaftConsensus::RunLeaderElect
ionState>)>::__call<void, , 0ul, 1ul>(std::tuple<>&&, std::_Index_tuple<0ul, 1ul>) (this=0x2d11830, __args=<unknown type in /nfusr/dev-server/jason/code/yugabyte-db/7/build/debug-gcc-dynamic-ninja/bin/../lib/libconsensus.so, CU 0x3fe2c0, DIE 0x5312a7>)
at /opt/yb-build/brew/linuxbrew-20181203T161736v9-3ba4c2ed9b0587040949a4a9a95b576f520bae/Cellar/gcc/5.5.0_4/include/c++/5.5.0/functional:1074
#7  0x00007f3ce1de526c in std::_Bind<std::_Mem_fn<void (yb::consensus::RaftConsensus::*)(std::shared_ptr<yb::consensus::RaftConsensus::RunLeaderElectionState>)> (yb::consensus::RaftConsensus*, std::shared_ptr<yb::consensus::RaftConsensus::RunLeaderElect
ionState>)>::operator()<, void>() (this=0x2d11830) at /opt/yb-build/brew/linuxbrew-20181203T161736v9-3ba4c2ed9b0587040949a4a9a95b576f520bae/Cellar/gcc/5.5.0_4/include/c++/5.5.0/functional:1133
#8  0x00007f3ce1de0053 in std::_Function_handler<void (), std::_Bind<std::_Mem_fn<void (yb::consensus::RaftConsensus::*)(std::shared_ptr<yb::consensus::RaftConsensus::RunLeaderElectionState>)> (yb::consensus::RaftConsensus*, std::shared_ptr<yb::consensu
s::RaftConsensus::RunLeaderElectionState>)> >::_M_invoke(std::_Any_data const&) (__functor=...) at /opt/yb-build/brew/linuxbrew-20181203T161736v9-3ba4c2ed9b0587040949a4a9a95b576f520bae/Cellar/gcc/5.5.0_4/include/c++/5.5.0/functional:1871
#9  0x00007f3ce77d5b7e in std::function<void ()>::operator()() const (this=0x6456be0) at /opt/yb-build/brew/linuxbrew-20181203T161736v9-3ba4c2ed9b0587040949a4a9a95b576f520bae/Cellar/gcc/5.5.0_4/include/c++/5.5.0/functional:2267
#10 0x00007f3cda43b9c2 in yb::rpc::OutboundCall::InvokeCallbackSync (this=0x6456b50) at ../../src/yb/rpc/outbound_call.cc:353
#11 0x00007f3cda439895 in yb::rpc::InvokeCallbackTask::Run (this=0x6456c00) at ../../src/yb/rpc/outbound_call.cc:120
#12 0x00007f3cda4ed527 in yb::rpc::(anonymous namespace)::Worker::Execute (this=0x796b2d0) at ../../src/yb/rpc/thread_pool.cc:105
#13 0x00007f3cda4f19af in std::_Mem_fn_base<void (yb::rpc::(anonymous namespace)::Worker::*)(), true>::operator()<, void>(std::_Mem_fn_base<void (yb::rpc::(anonymous namespace)::Worker::*)(), true>::_Class *) const (this=0x79c6540, __object=0x796b2d0) a
t /opt/yb-build/brew/linuxbrew-20181203T161736v9-3ba4c2ed9b0587040949a4a9a95b576f520bae/Cellar/gcc/5.5.0_4/include/c++/5.5.0/functional:600
#14 0x00007f3cda4f102e in std::_Bind<std::_Mem_fn<void (yb::rpc::(anonymous namespace)::Worker::*)()>(yb::rpc::(anonymous namespace)::Worker*)>::__call<void, 0ul>(<unknown type in /nfusr/dev-server/jason/code/yugabyte-db/7/build/debug-gcc-dynamic-ninja/
bin/../lib/libyrpc.so, CU 0xd0bd78, DIE 0xd3aa1f>, std::_Index_tuple<0ul>) (this=0x79c6540, __args=<unknown type in /nfusr/dev-server/jason/code/yugabyte-db/7/build/debug-gcc-dynamic-ninja/bin/../lib/libyrpc.so, CU 0xd0bd78, DIE 0xd3aa1f>) at /opt/yb-bu
ild/brew/linuxbrew-20181203T161736v9-3ba4c2ed9b0587040949a4a9a95b576f520bae/Cellar/gcc/5.5.0_4/include/c++/5.5.0/functional:1074
#15 0x00007f3cda4f01a2 in std::_Bind<std::_Mem_fn<void (yb::rpc::(anonymous namespace)::Worker::*)()>(yb::rpc::(anonymous namespace)::Worker*)>::operator()<, void>(void) (this=0x79c6540) at /opt/yb-build/brew/linuxbrew-20181203T161736v9-3ba4c2ed9b058704
0949a4a9a95b576f520bae/Cellar/gcc/5.5.0_4/include/c++/5.5.0/functional:1133
#16 0x00007f3cda4ef071 in std::_Function_handler<void(), std::_Bind<std::_Mem_fn<void (yb::rpc::(anonymous namespace)::Worker::*)()>(yb::rpc::(anonymous namespace)::Worker*)> >::_M_invoke(const std::_Any_data &) (__functor=...) at /opt/yb-build/brew/lin
uxbrew-20181203T161736v9-3ba4c2ed9b0587040949a4a9a95b576f520bae/Cellar/gcc/5.5.0_4/include/c++/5.5.0/functional:1871
#17 0x00007f3ce77d5b7e in std::function<void ()>::operator()() const (this=0x529f378) at /opt/yb-build/brew/linuxbrew-20181203T161736v9-3ba4c2ed9b0587040949a4a9a95b576f520bae/Cellar/gcc/5.5.0_4/include/c++/5.5.0/functional:2267
#18 0x00007f3cd4c4dba3 in yb::Thread::SuperviseThread (arg=0x529f320) at ../../src/yb/util/thread.cc:771
#19 0x00007f3ccffec694 in start_thread (arg=0x7f3b38509700) at pthread_create.c:333
#20 0x00007f3ccfd2e41d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

I omit the stack traces of the other threads.  The key line is

```
#2  0x00007f3ce1dff6fc in yb::consensus::ReplicaState::LogPrefix[abi:cxx11]() const (this=0x3339393236312e79) at ../../src/yb/consensus/replica_state.cc:1043
```

It appears to fail on `->` of

```cpp
  auto role_and_term = cmeta_->GetRoleAndTerm();
```

This was debug-gcc-dynamic-ninja on centos, commit acb23dd475637b40af7b7e613dc47a8409042653.  I think it is difficult to reproduce.

**Comment by rthallamko3** [comment]
@Huqicheng , Add it to the queue of raft issues.
