### ISSUE TITLE
[YSQL] PgExpr:TranslateDecimal appears to leak memory in long running queries

### ISSUE THREAD

**Issue by ajcaldera1** [yugabyte/yugabyte-db#9957]
While running a query in a cursor and periodically fetching rows, I note that there is a great deal of heap memory allocation with TranslateDecimal in the stack:

```
Thread 1 (process 28713):
#0  0x00007f74159d6434 in _int_malloc (av=av@entry=0x7f7415cf7640 <main_arena>, bytes=bytes@entry=264133) at malloc.c:3451
#1  0x00007f74159d81c0 in __GI___libc_malloc (bytes=264133) at malloc.c:2914
#2  0x00007f74167c6d58 in operator new(unsigned long) () from /home/yugabyte/linuxbrew/lib/libstdc++.so.6
#3  0x00007f741739183e in _M_construct<char const*> (__end=<optimized out>, __beg=0x7f73d010e547 "\350[\247\245\206", this=0x7fff9d994180) at /home/yugabyte/linuxbrew-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/Cellar/gcc/5.5.0_4/include/c++/5.5.0/bits/basic_string.tcc:219
#4  _M_construct_aux<char const*> (__end=<optimized out>, __beg=<optimized out>, this=0x7fff9d994180) at /home/yugabyte/linuxbrew-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/Cellar/gcc/5.5.0_4/include/c++/5.5.0/bits/basic_string.h:195
#5  _M_construct<char const*> (__end=<optimized out>, __beg=<optimized out>, this=0x7fff9d994180) at /home/yugabyte/linuxbrew-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/Cellar/gcc/5.5.0_4/include/c++/5.5.0/bits/basic_string.h:214
#6  basic_string (__a=..., __n=<optimized out>, __s=<optimized out>, this=0x7fff9d994180) at /home/yugabyte/linuxbrew-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/Cellar/gcc/5.5.0_4/include/c++/5.5.0/bits/basic_string.h:448
#7  yb::Slice::ToBuffer[abi:cxx11]() const (this=this@entry=0x8ab256e50) at ../../src/yb/util/slice.cc:57
#8  0x00007f7416f5bd61 in yb::pggate::PgExpr::TranslateDecimal (yb_cursor=0x8ab256e50, header=..., index=11, type_entity=0xe996a8 <YBCTypeEntityTable+3880>, type_attrs=0x2911e38, pg_tuple=0x7fff9d9943d0) at ../../src/yb/yql/pggate/pg_expr.cc:231
#9  0x00007f7416f608c7 in operator() (__args#5=0x7fff9d9943d0, __args#4=0x2911e38, __args#3=0xe996a8 <YBCTypeEntityTable+3880>, __args#2=11, __args#1=..., __args#0=0x8ab256e50, this=0x2911e40) at /home/yugabyte/linuxbrew-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/Cellar/gcc/5.5.0_4/include/c++/5.5.0/functional:2267
#10 TranslateData (pg_tuple=0x7fff9d9943d0, index=11, header=..., yb_cursor=0x8ab256e50, this=0x2911e20) at ../../src/yb/yql/pggate/pg_expr.h:112
#11 yb::pggate::PgDocResult::WritePgTuple (this=this@entry=0x8ab256e30, targets=..., pg_tuple=pg_tuple@entry=0x7fff9d9943d0, row_order=row_order@entry=0x7fff9d994328) at ../../src/yb/yql/pggate/pg_doc_op.cc:82
#12 0x00007f7416f51d17 in yb::pggate::PgDml::GetNextRow (this=this@entry=0x2955a60, pg_tuple=pg_tuple@entry=0x7fff9d9943d0) at ../../src/yb/yql/pggate/pg_dml.cc:350
#13 0x00007f7416f52da9 in yb::pggate::PgDml::Fetch (this=0x2955a60, natts=<optimized out>, values=values@entry=0x2b6bf48, isnulls=isnulls@entry=0x289fe48, syscols=syscols@entry=0x7fff9d9944e0, has_data=0x7fff9d9944df) at ../../src/yb/yql/pggate/pg_dml.cc:295
#14 0x00007f7416f2d793 in yb::pggate::PgApiImpl::DmlFetch (this=<optimized out>, handle=<optimized out>, natts=<optimized out>, values=values@entry=0x2b6bf48, isnulls=isnulls@entry=0x289fe48, syscols=0x7fff9d9944e0, has_data=0x7fff9d9944df) at ../../src/yb/yql/pggate/pggate.cc:840
#15 0x00007f7416f26d8b in yb::pggate::YBCPgDmlFetch (handle=<optimized out>, natts=<optimized out>, values=values@entry=0x2b6bf48, isnulls=isnulls@entry=0x289fe48, syscols=syscols@entry=0x7fff9d9944e0, has_data=has_data@entry=0x7fff9d9944df) at ../../src/yb/yql/pggate/ybc_pggate.cc:575
#16 0x0000000000554e6b in ybcFetchNextHeapTuple (is_forward_scan=true, ybScan=0x2b6bde8) at ../../../../../../../src/postgres/src/backend/access/ybc/ybcam.c:247
#17 ybc_getnext_heaptuple (ybScan=ybScan@entry=0x2b6bde8, is_forward_scan=is_forward_scan@entry=true, recheck=recheck@entry=0x2b6bccc) at ../../../../../../../src/postgres/src/backend/access/ybc/ybcam.c:1241
#18 0x0000000000556289 in ybcingettuple (scan=0x2b6bc48, dir=<optimized out>) at ../../../../../../../src/postgres/src/backend/access/ybc/ybcin.c:344
#19 0x00000000004f8a75 in index_getnext_tid (scan=scan@entry=0x2b6bc48, direction=direction@entry=ForwardScanDirection) at ../../../../../../../src/postgres/src/backend/access/index/indexam.c:592
#20 0x00000000004f8cf4 in index_getnext (scan=scan@entry=0x2b6bc48, direction=direction@entry=ForwardScanDirection) at ../../../../../../../src/postgres/src/backend/access/index/indexam.c:742
#21 0x00000000006e40bc in IndexNext (node=node@entry=0x277a538) at ../../../../../../src/postgres/src/backend/executor/nodeIndexscan.c:153
#22 0x00000000006cce81 in ExecScanFetch (recheckMtd=0x6e3f60 <IndexRecheck>, accessMtd=0x6e4000 <IndexNext>, node=0x277a538) at ../../../../../../src/postgres/src/backend/executor/execScan.c:95
#23 ExecScan (node=0x277a538, accessMtd=0x6e4000 <IndexNext>, recheckMtd=0x6e3f60 <IndexRecheck>) at ../../../../../../src/postgres/src/backend/executor/execScan.c:145
#24 0x00000000006efc8d in ExecProcNode (node=0x277a538) at ../../../../../../src/postgres/src/include/executor/executor.h:249
#25 ExecNestLoop (pstate=0x277a348) at ../../../../../../src/postgres/src/backend/executor/nodeNestloop.c:109
#26 0x00000000006f2ab6 in ExecProcNode (node=0x277a348) at ../../../../../../src/postgres/src/include/executor/executor.h:249
#27 ExecSort (pstate=0x277a238) at ../../../../../../src/postgres/src/backend/executor/nodeSort.c:116
#28 0x00000000006c1e8b in ExecProcNode (node=0x277a238) at ../../../../../../src/postgres/src/include/executor/executor.h:249
#29 ExecutePlan (execute_once=<optimized out>, dest=0x26780e8, direction=<optimized out>, numberTuples=0, sendTuples=<optimized out>, operation=CMD_SELECT, use_parallel_mode=<optimized out>, planstate=0x277a238, estate=0x2779fa8) at ../../../../../../src/postgres/src/backend/executor/execMain.c:1730
#30 standard_ExecutorRun (queryDesc=0x2b37f58, direction=<optimized out>, count=0, execute_once=<optimized out>) at ../../../../../../src/postgres/src/backend/executor/execMain.c:367
#31 0x00007f7408d5489d in pgss_ExecutorRun (queryDesc=0x2b37f58, direction=ForwardScanDirection, count=0, execute_once=<optimized out>) at ../../../../../src/postgres/contrib/pg_stat_statements/pg_stat_statements.c:947
#32 0x00007f7408b4d56a in ybpgm_ExecutorRun (queryDesc=0x2b37f58, direction=ForwardScanDirection, count=0, execute_once=<optimized out>) at ../../../../../src/postgres/contrib/yb_pg_metrics/yb_pg_metrics.c:492
#33 0x00000000008767ab in PortalRunSelect (portal=portal@entry=0x26fbc98, forward=forward@entry=true, count=0, count@entry=9223372036854775807, dest=dest@entry=0x26780e8) at ../../../../../../src/postgres/src/backend/tcop/pquery.c:947
#34 0x0000000000878291 in PortalRun (portal=portal@entry=0x26fbc98, count=count@entry=9223372036854775807, isTopLevel=isTopLevel@entry=true, run_once=run_once@entry=true, dest=dest@entry=0x26780e8, altdest=altdest@entry=0x26780e8, completionTag=0x7fff9d994c50 "") at ../../../../../../src/postgres/src/backend/tcop/pquery.c:784
#35 0x00000000008721e8 in exec_execute_message (max_rows=9223372036854775807, portal_name=0x2677ca8 "") at ../../../../../../src/postgres/src/backend/tcop/postgres.c:2061
#36 yb_exec_execute_message (portal_name=portal_name@entry=0x2677ca8 "", max_rows=max_rows@entry=0, restart_data=restart_data@entry=0x26780b8, exec_context=exec_context@entry=0x2677b90) at ../../../../../../src/postgres/src/backend/tcop/postgres.c:4361
#37 0x00000000008751a3 in PostgresMain (argc=<optimized out>, argv=argv@entry=0x2674d28, dbname=0x2674ad8 "candb", username=0x2674ab8 "candb_ro") at ../../../../../../src/postgres/src/backend/tcop/postgres.c:5081
#38 0x000000000049af59 in BackendRun (port=0x26a2ac0) at ../../../../../../src/postgres/src/backend/postmaster/postmaster.c:4429
#39 BackendStartup (port=0x26a2ac0) at ../../../../../../src/postgres/src/backend/postmaster/postmaster.c:4095
#40 ServerLoop () at ../../../../../../src/postgres/src/backend/postmaster/postmaster.c:1737
#41 0x00000000007dbd1f in PostmasterMain (argc=argc@entry=25, argv=argv@entry=0x26732d0) at ../../../../../../src/postgres/src/backend/postmaster/postmaster.c:1400
#42 0x0000000000727aaa in PostgresServerProcessMain (argc=25, argv=0x26732d0) at ../../../../../../src/postgres/src/backend/main/main.c:234
#43 0x0000000000727ca9 in main ()```

If you look at the top frame, you note the  size requested as over 250K. The longer the session runs, I have seen this at 400K. Eventually, OOM killer will victimize this PG child process.

**Comment by m-iancu** [comment]
Fixed by c3c4262.
