### ISSUE TITLE
[YSQL] Nodes failed after index creation

### ISSUE THREAD

**Issue by pilshchikov** [yugabyte/yugabyte-db#9973]
Steps to reproduce:
1. Start 3 nodes universe with RF=3 on `c5.xlarge`
2. Start workloads
```
java -jar yb-sample-apps.jar --workload SqlInserts  --num_writes 1000000 --num_threads_write 50 --num_threads_read 0 --num_reads 0 --num_unique_keys 100000000 --create_table_name table_10_9_13_31_41e3ea_SqlInserts --uuid eafdcd81-d1eb-4e61-ba02-393b258490f3 --nodes 
java -jar yb-sample-apps.jar --workload SqlUpdates  --num_writes 1000000 --num_threads_write 50 --num_threads_read 0 --num_reads 0 --num_unique_keys 100000000 --max_written_key 1000000 --create_table_name table_10_9_13_31_41e3ea_SqlInserts --uuid 9c0b7a2c-dac2-40cb-a6ad-8563d74588bd --nodes 
java -jar yb-sample-apps.jar --workload SqlDataLoad  --num_writes 1000000 --num_threads_write 50 --num_threads_read 0 --num_reads 0 --num_unique_keys 100000000 --num_foreign_key_table_rows 1000000 --create_table_name table_10_9_13_31_e3ec33_SqlDataLoad --uuid 55723f45-f9d5-4332-a6e2-a302aeb5c9bb --nodes
java -jar yb-sample-apps.jar --workload SqlSecondaryIndex  --num_writes 1000000 --num_threads_write 50 --num_threads_read 0 --num_reads 0 --num_unique_keys 100000000 --create_table_name table_10_9_5_4_d9f8c0_SqlSecondaryIndex --uuid c5ffdd7f-aa17-4c1e-9127-a5793fbd21ea --nodes
java -jar yb-sample-apps.jar --workload SqlSnapshotTxns  --num_writes 1000000 --num_threads_write 50 --num_threads_read 0 --num_reads 0 --num_unique_keys 100000000 --create_table_name table_10_9_13_31_84c519_SqlSnapshotTxns --uuid ab2eb174-92a7-493c-8a5a-b9467461191c --nodes
java -jar yb-sample-apps.jar --workload SqlForeignKeysAndJoins  --num_writes 1000000 --num_threads_write 50 --num_threads_read 0 --num_reads 0 --num_unique_keys 100000000 --create_table_name table_10_9_5_4_9f34b8_SqlForeignKeysAndJoins --uuid c7afc2ad-bb68-44aa-84c4-93fb11fd1f2d --nodes
```
3. Start constantly create and drop index on SqlIndex workload table
```
./bin/ysqlsh -d postgres -c "CREATE INDEX SQL_INSERTS_BACKFILL_INDEX_600774 ON table_10_9_4_12_f279d2_SqlInserts(V);"
wait 1 min
./bin/ysqlsh -d postgres -c "DROP INDEX SQL_INSERTS_BACKFILL_INDEX_600774;"
```
Processes start hanging, node leaving topology

[client_logs.zip](https://github.com/yugabyte/yugabyte-db/files/7145746/client_logs.zip)
[server_logs.zip](https://github.com/yugabyte/yugabyte-db/files/7145747/server_logs.zip)

**Comment by amitanandaiyer** [comment]
@pilshchikov Can you clarify what you mean by Nodes failed -- did you see any of the nodes crash?

**Comment by amitanandaiyer** [comment]
I don't see any nodes (master or the tserver) crashing.

**Comment by amitanandaiyer** [comment]
The Delete Table RPC (0910 18:05:13) seems to happen after the backfill has successfully completed (at I0910 18:04:10).

```
I0910 18:03:46.441303 17639 backfill_index.cc:1318] Started BackfillChunk : Backfilling indexes { sql_inserts_backfill_index_35beee } for tablet 0a221742a2c24c848c2fbe78c44721a6 from key ''
 I0910 18:03:46.441359 17639 backfill_index.cc:1318] Started BackfillChunk : Backfilling indexes { sql_inserts_backfill_index_35beee } for tablet e0412d4ab0d14bb287299ae4a7d8fab1 from key ''
 I0910 18:03:46.441387 17639 backfill_index.cc:1318] Started BackfillChunk : Backfilling indexes { sql_inserts_backfill_index_35beee } for tablet b1388614615041729f3c68c5c878b55f from key ''
 I0910 18:03:46.441413 17639 backfill_index.cc:1318] Started BackfillChunk : Backfilling indexes { sql_inserts_backfill_index_35beee } for tablet 06eb3d1120ef4737b84e481ec22188e2 from key ''
 I0910 18:03:46.441437 17639 backfill_index.cc:1318] Started BackfillChunk : Backfilling indexes { sql_inserts_backfill_index_35beee } for tablet e0a9c9cc37d649209d326c030bdcd525 from key ''
 I0910 18:03:46.441464 17639 backfill_index.cc:1318] Started BackfillChunk : Backfilling indexes { sql_inserts_backfill_index_35beee } for tablet c9fa103c6905461c8d46f581f1a290e7 from key ''
 I0910 18:03:46.441488 17639 backfill_index.cc:1318] Started BackfillChunk : Backfilling indexes { sql_inserts_backfill_index_35beee } for tablet 2271a9a4b4b148469152bfa991819407 from key ''
 I0910 18:03:46.441514 17639 backfill_index.cc:1318] Started BackfillChunk : Backfilling indexes { sql_inserts_backfill_index_35beee } for tablet ffaa64ac6dd347d5bc96fcd41d7bd4a2 from key ''
 I0910 18:03:46.441536 17639 backfill_index.cc:1318] Started BackfillChunk : Backfilling indexes { sql_inserts_backfill_index_35beee } for tablet 46d0f679882a4ea1851e4eddddce0d59 from key ''
 I0910 18:03:46.441560 17639 backfill_index.cc:1318] Started BackfillChunk : Backfilling indexes { sql_inserts_backfill_index_35beee } for tablet 7564e7d735c1425cb9badcede3e33cba from key ''
 I0910 18:03:46.441591 17639 backfill_index.cc:1318] Started BackfillChunk : Backfilling indexes { sql_inserts_backfill_index_35beee } for tablet 6be2148755544ee4bb1814179a1186fe from key ''
 I0910 18:03:46.441618 17639 backfill_index.cc:1318] Started BackfillChunk : Backfilling indexes { sql_inserts_backfill_index_35beee } for tablet 0389a88690734fc68920f61b64c886c1 from key ''
 I0910 18:03:54.156453 17820 backfill_index.cc:291] table_10_9_8_108_9f4250_sqlsecondaryindex [id=000030ad00003000800000000000402d] - Alter table completed version=1, state: RUNNING
 I0910 18:04:03.373775 18147 backfill_index.cc:291] table_10_9_8_108_9f4250_sqlsecondaryindex [id=000030ad00003000800000000000402d] - Alter table completed version=2, state: RUNNING
 I0910 18:04:04.803900 18197 backfill_index.cc:1199] Done backfilling the tablet 0x0000000004bebb80 -> 06eb3d1120ef4737b84e481ec22188e2 (table table_10_9_4_12_f279d2_sqlinserts [id=000030ad000030008000000000004100])
 I0910 18:04:05.357303 18212 backfill_index.cc:1199] Done backfilling the tablet 0x00000000042b6c80 -> e0a9c9cc37d649209d326c030bdcd525 (table table_10_9_4_12_f279d2_sqlinserts [id=000030ad000030008000000000004100])
 I0910 18:04:07.018528 18200 backfill_index.cc:1199] Done backfilling the tablet 0x00000000042b7680 -> 0a221742a2c24c848c2fbe78c44721a6 (table table_10_9_4_12_f279d2_sqlinserts [id=000030ad000030008000000000004100])
 I0910 18:04:07.236959 18197 backfill_index.cc:1199] Done backfilling the tablet 0x00000000042f7180 -> 0389a88690734fc68920f61b64c886c1 (table table_10_9_4_12_f279d2_sqlinserts [id=000030ad000030008000000000004100])
 I0910 18:04:07.237274 18215 backfill_index.cc:1199] Done backfilling the tablet 0x00000000042b6780 -> 7564e7d735c1425cb9badcede3e33cba (table table_10_9_4_12_f279d2_sqlinserts [id=000030ad000030008000000000004100])
 I0910 18:04:07.585770 18215 backfill_index.cc:1199] Done backfilling the tablet 0x00000000038b4000 -> b1388614615041729f3c68c5c878b55f (table table_10_9_4_12_f279d2_sqlinserts [id=000030ad000030008000000000004100])
 I0910 18:04:08.896581 18212 backfill_index.cc:1199] Done backfilling the tablet 0x00000000042f6c80 -> 6be2148755544ee4bb1814179a1186fe (table table_10_9_4_12_f279d2_sqlinserts [id=000030ad000030008000000000004100])
 I0910 18:04:08.934165 18200 backfill_index.cc:1199] Done backfilling the tablet 0x00000000042b6500 -> 2271a9a4b4b148469152bfa991819407 (table table_10_9_4_12_f279d2_sqlinserts [id=000030ad000030008000000000004100])
 I0910 18:04:09.069774 18197 backfill_index.cc:1199] Done backfilling the tablet 0x00000000042b7b80 -> c9fa103c6905461c8d46f581f1a290e7 (table table_10_9_4_12_f279d2_sqlinserts [id=000030ad000030008000000000004100])
 I0910 18:04:09.304623 18215 backfill_index.cc:1199] Done backfilling the tablet 0x00000000042b7180 -> ffaa64ac6dd347d5bc96fcd41d7bd4a2 (table table_10_9_4_12_f279d2_sqlinserts [id=000030ad000030008000000000004100])
 I0910 18:04:10.205669 18325 backfill_index.cc:1199] Done backfilling the tablet 0x00000000042b6a00 -> 46d0f679882a4ea1851e4eddddce0d59 (table table_10_9_4_12_f279d2_sqlinserts [id=000030ad000030008000000000004100])
 I0910 18:04:10.516708 18325 backfill_index.cc:1199] Done backfilling the tablet 0x0000000004693180 -> e0412d4ab0d14bb287299ae4a7d8fab1 (table table_10_9_4_12_f279d2_sqlinserts [id=000030ad000030008000000000004100])
 I0910 18:04:10.522663 18325 backfill_index.cc:877] Backfill Index Table(s) { sql_inserts_backfill_index_35beee } Completed backfilling the index table.
 I0910 18:04:10.563074 18325 backfill_index.cc:991] Done backfill on table_10_9_4_12_f279d2_sqlinserts [id=000030ad000030008000000000004100] setting permissions to [{000030ad000030008000000000004037, 6}]
 I0910 18:04:10.630026 18328 backfill_index.cc:291] table_10_9_4_12_f279d2_sqlinserts [id=000030ad000030008000000000004100] - Alter table completed version=2, state: RUNNING
 I0910 18:05:13.956880 17524 catalog_manager.cc:4330] Deleting table: sql_inserts_backfill_index_35beee, retained by: []
 I0910 18:05:14.022073 19081 async_rpc_tasks.cc:646] DeleteTablet RPC for tablet 8953b872f85c47e99a4f7aef8d35946a (sql_inserts_backfill_index_35beee [id=000030ad000030008000000000004037]) on TS=b2439f6457b546f68a3a1e4a1216ba5a     (task=0x105e2690, state=kRunning): TS b2439f6457b546f68a3a1e4a1216ba5a: tablet 8953b872f85c47e99a4f7aef8d35946a (table sql_inserts_backfill_index_35beee [id=000030ad000030008000000000004037]) successfully done
 I0910 18:05:14.039737 19079 async_rpc_tasks.cc:646] DeleteTablet RPC for tablet 8953b872f85c47e99a4f7aef8d35946a (sql_inserts_backfill_index_35beee [id=000030ad000030008000000000004037]) on TS=55a9593e349c4c02866a4d678f08dede     (task=0xb60a1b0, state=kRunning): TS 55a9593e349c4c02866a4d678f08dede: tablet 8953b872f85c47e99a4f7aef8d35946a (table sql_inserts_backfill_index_35beee [id=000030ad000030008000000000004037]) successfully done
 I0910 18:05:14.039803 19079 async_rpc_tasks.cc:646] DeleteTablet RPC for tablet 7b0de19fcda64c2f93b45135fbbb2926 (sql_inserts_backfill_index_35beee [id=000030ad000030008000000000004037]) on TS=b2439f6457b546f68a3a1e4a1216ba5a
 ```
 
 I  see some schema version mismatch errors. These seem to happen not only for the SQLInsert/Update -- where the index was added/created. But also on other workloads. 
 
 @m-iancu my guess is that the catalog version got bumped up, and these sample apps are unable to recover gracefully? Can someone from lrt take a look and confirm the theory why this is happening? Thanks.
 
 
 
 org.postgresql.util.PSQLException: ERROR: Query error: schema version mismatch for table 000030ad000030008000000000004232: expected 1, got 0
     at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2553)
     at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2285)
     at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:323)
     at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:473)
     at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:393)
     at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:164)
     at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:130)
     at com.yugabyte.sample.apps.SqlInserts.doWrite(SqlInserts.java:176)
     at com.yugabyte.sample.apps.AppBase.performWrite(AppBase.java:761)
     at com.yugabyte.sample.common.IOPSThread.run(IOPSThread.java:87)

**Comment by m-iancu** [comment]
@pilshchikov Can we check if this still happens on latest version?
